### ISSUE TITLE
[Android] Tried to use permissions API while not attached to an Activity.

### ISSUE THREAD

**Issue by alexHlebnikov** [facebook/react-native#10009]
I've got this error.
I'm using RN Android Permission Module.
Tested on RN 0.33.0 and RN 0.34.0.RC.0.
Problem occurs only on Android devices with API Level 23+ (where Android Permission Module is used).

Here is my code:

```
    requestPermission = async () => {
        try {
            const granted = await PermissionsAndroid.requestPermission(
                PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION
            );

            const { actions } = this.props;
            actions.setGeolocationPermissionStatus(granted);
        } catch (err) {
            /*eslint-disable */
            console.warn(err);
            /*eslint-enable */
        }
    };

    componentDidMount() {
        setTimeout(() => {
            this.requestPermission();
        }, 0);
    }
```

And here is stack trace: 

```
Exception java.lang.IllegalStateException: Tried to use permissions API while not attached to an Activity.
com.facebook.react.modules.permissions.PermissionsModule.getPermissionAwareActivity (PermissionsModule.java:125)
com.facebook.react.modules.permissions.PermissionsModule.requestPermission (PermissionsModule.java:86)
java.lang.reflect.Method.invoke (Method.java)
com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke (BaseJavaModule.java:319)
com.facebook.react.cxxbridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:158)
com.facebook.react.bridge.queue.NativeRunnable.run (NativeRunnable.java)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:31)
android.os.Looper.loop (Looper.java:148)
com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run (MessageQueueThreadImpl.java:196)
java.lang.Thread.run (Thread.java:818)
```

**Comment by alexHlebnikov** [comment]
Same problem on RN 0.35.0.RC.0.

**Comment by hey99xx** [comment]
Well the stack trace looks pretty clear. Was your React instance manager attached to an activity when you called this or not? It's a plain English error message, I don't see what you are asking here.

**Comment by alexHlebnikov** [comment]
@hey99xx how could there be no activity?
I'm requesting permission on `componentDidMount()` - at that point activity is already exists.

**Comment by alexHlebnikov** [comment]
Seems like https://github.com/facebook/react-native/pull/10221 could fix the issue. Waiting for review.

**Comment by alexHlebnikov** [comment]
The problem is still here. I can reproduce it now. 

When our app loads for the first time, the permission dialog is shown and if user "pauses" the app via click on right button on Android or if there is another app appears over our app (message from messenger, for example), our app became resumed, and crashes at that moment.

**Comment by alexHlebnikov** [comment]
@grabbou Hi! Fix for this problem (https://github.com/facebook/react-native/pull/10351) doesn't helped. I've write above how to reproduce this issue. It could be great if you can check my guess.

**Comment by felipemartim** [comment]
I was having the same problem as I was requesting the permission as soon as the Activity was created. Delaying the permission request a bit solved it for me.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-tried-to-use-permissions-api-while-not-attached-to-an-activity

**Comment by ujwal-setlur** [comment]
I see this on a real device with react-native 0.47. Didn't see it on an emulator.

**Comment by mannol** [comment]
Still present on 0.47

**Comment by kontinuity** [comment]
I think this happens when the app is in the background while starting or requesting permissions and may only happen in dev mode.

**Comment by mannol** [comment]
This happens to me while using react-native-navigation in release mode. It's probably related to RNN but I'm not sure.

**Comment by xhou** [comment]
I got the same issue to @mannol.
Here is my adb logcat result:
`9-21 16:12:22.598   609   622 I GnssLocationProvider: WakeLock released by handleMessage(3, 0, com.android.server.location.GnssLocationProvider$GpsRequest@4ed4899)
09-21 16:12:22.616  4371  4371 D AndroidRuntime: Shutting down VM
09-21 16:12:22.617  4371  4371 E AndroidRuntime: FATAL EXCEPTION: main
09-21 16:12:22.617  4371  4371 E AndroidRuntime: Process: com.mycompany.maycompany, PID: 4371
09-21 16:12:22.617  4371  4371 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.limebike.limebikeops/com.reactnativenavigation.controllers.NavigationActivity}: java.lang.IllegalStateException: Tried to use permissions API while not attached to an Activity.
09-21 16:12:22.617  4371  4371 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4089)
09-21 16:12:22.617  4371  4371 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132)
09-21 16:12:22.617  4371  4371 E AndroidRuntime: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
09-21 16:12:22.617  4371  4371 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
09-21 16:12:22.617  4371  4371 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-21 16:12:22.617  4371  4371 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-21 16:12:22.617  4371  4371 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
09-21 16:12:22.617  4371  4371 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-21 16:12:22.617  4371  4371 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
09-21 16:12:22.617  4371  4371 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
09-21 16:12:22.617  4371  4371 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Tried to use permissions API while not attached to an Activity.
09-21 16:12:22.617  4371  4371 E AndroidRuntime: 	at com.facebook.react.modules.permissions.PermissionsModule.getPermissionAwareActivity(PermissionsModule.java:215)
09-21 16:12:22.617  4371  4371 E AndroidRuntime: 	at com.facebook.react.modules.permissions.PermissionsModule.onRequestPermissionsResult(PermissionsModule.java:207)
09-21 16:12:22.617  4371  4371 E AndroidRuntime: 	at com.reactnativenavigation.controllers.NavigationActivity.onRequestPermissionsResult(NavigationActivity.java:442)
09-21 16:12:22.617  4371  4371 E AndroidRuntime: 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7084)
09-21 16:12:22.617  4371  4371 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6936)
09-21 16:12:22.617  4371  4371 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)
09-21 16:12:22.617  4371  4371 E AndroidRuntime: 	... 9 more
09-21 16:12:22.667   609   823 W ActivityManager:   Force finishing activity com.limebike.limebikeops/com.reactnativenavigation.controllers.NavigationActivity
09-21 16:12:22.696  2164  2178 D OpenGLRenderer: endAllActiveAnimators on 0xcf5b5d00 (RippleDrawable) with handle 0xcf5ccb60
09-21 16:12:22.748   341  2546 D gralloc_vbox86: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
09-21 16:12:22.751   341  2546 D gralloc_vbox86: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
09-21 16:12:22.754   341  2546 D gralloc_vbox86: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
09-21 16:12:22.758   609  2356 I OpenGLRenderer: Initialized EGL, version 1.4
09-21 16:12:22.758   609  2356 D OpenGLRenderer: Swap behavior 1
09-21 16:12:22.779   609  2356 E EGL_emulation: tid 2356: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
09-21 16:12:22.779   609  2356 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xcec9fba0, error=EGL_BAD_MATCH
09-21 16:12:23.196   609   623 W ActivityManager: Activity pause timeout for ActivityRecord{9d5c438 u0 com.mycompany.mycompany/com.reactnativenavigation.controllers.NavigationActivity t231 f}
09-21 16:12:23.248   341   606 D gralloc_vbox86: gralloc_alloc: format 1 and usage 0x333 imply creation of host color buffer
09-21 16:12:23.267   341   341 E EGL_emulation: tid 341: eglCreateSyncKHR(1669): error 0x3004 (EGL_BAD_ATTRIBUTE)
09-21 16:12:23.475   341   345 D gralloc_vbox86: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
09-21 16:12:23.480   341   345 D gralloc_vbox86: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
09-21 16:12:23.485   341   345 D gralloc_vbox86: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
09-21 16:12:23.499  1151  1245 E EGL_emulation: tid 1245: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
09-21 16:12:23.499  1151  1245 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xcf8a7500, error=EGL_BAD_MATCH
09-21 16:12:23.510   341   341 W SurfaceFlinger: couldn't log to binary event log: overflow.
09-21 16:12:23.642  4000  4009 W SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/com.google.android.gms/databases/metrics.db.16' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
09-21 16:12:23.644  4000  4009 W SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/com.google.android.gms/databases/help_responses.db.18' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
09-21 16:12:23.646  4000  4009 W SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/com.google.android.gms/databases/auto_complete_suggestions.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.`

**Comment by mehdijjz** [comment]
I'm having this issue as well, why is this issue closed?

**Comment by thevolcanomanishere** [comment]
Same here

**Comment by Moreno97** [comment]
Same here...

**Comment by thevolcanomanishere** [comment]
Turned out it was problems with Oreo. Use the latest RN

**Comment by Moreno97** [comment]
@thevolcanomanishere using last RN version that supports Oreo and error stills there. Probably is something related to `react-native-navigation`??

**Comment by thevolcanomanishere** [comment]
Sorry I was thinking of a separate problem. It was RNN. I removed it and it went away. RNN with the react native debug overlay doesn't request permissions properly in line with Androids new permission model for drawing over the screen.

**Comment by Moreno97** [comment]
@thevolcanomanishere so the problem is RNN. I suppose there's no fix for that, true?

**Comment by thevolcanomanishere** [comment]
I read somewhere about implementing PermissionAwareActivity but just gave
up and reverted to my old navigation.

Regards,
Alex McGonagle

**Comment by Moreno97** [comment]
@thevolcanomanishere that was already implemented on previous versions in RNN. Probably a quick fix is using `setTimeout` on `componentDidMount`.

**Comment by brunolemos** [comment]
Anyone have a fix or workaround?

``` java.lang.RuntimeException · Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } (has extras) }} to activity {com.minderapps.minder/com.reactnativenavigation.controllers.NavigationActivity}: java.lang.IllegalStateException: Tried to use permissions API while not attached to an Activity. ```

I'm requesting permissions after the screen is visible so I don't see why this happens.

react-native 0.54
react-native-navigation 1.1.365

**Comment by brunolemos** [comment]
This may fix: https://github.com/wix/react-native-navigation/pull/2043#issuecomment-339329766

**Comment by anwarhamr** [comment]
@Moreno97 setTimeout worked for me but what a hack.  I'm not using anything special in React-native-navigation so I should just dump it since it's giving me such pains...
