### ISSUE TITLE
Unable to Generate IPA file and preview on iphone

### ISSUE THREAD

**Issue by spalagani** [facebook/react-native#10144]
## Command /bin/sh failed with exit code 1
- DEST=/Users/spalagani/Library/Developer/Xcode/DerivedData/topups-dbyhlheboyiseocaqmpsephakjjr/Build/Products/Debug-iphoneos/topups.app
- node /Users/spalagani/Documents/reachapp/topups/node_modules/react-native/local-cli/cli.js bundle --entry-file index.ios.js --platform ios --dev true --bundle-output /Users/spalagani/Library/Developer/Xcode/DerivedData/topups-dbyhlheboyiseocaqmpsephakjjr/Build/Products/Debug-iphoneos/topups.app/main.jsbundle --assets-dest /Users/spalagani/Library/Developer/Xcode/DerivedData/topups-dbyhlheboyiseocaqmpsephakjjr/Build/Products/Debug-iphoneos/topups.app
  bundle: Created ReactPackager
  uncaught error Error: Error: Uncaught error in the transformer worker: /Users/spalagani/Documents/reachapp/topups/node_modules/react-native/packager/transformer.js
  at index.js:164:37
  at tryCallOne (/Users/spalagani/Documents/reachapp/topups/node_modules/promise/lib/core.js:37:12)
  at /Users/spalagani/Documents/reachapp/topups/node_modules/promise/lib/core.js:123:15
  at flush (/Users/spalagani/Documents/reachapp/topups/node_modules/asap/raw.js:50:29)
  at doNTCallback0 (node.js:407:9)
  at process._tickCallback (node.js:336:13)
  See logs /var/folders/25/6553ppd52cvbjj_wgzz614mc38yd3s/T/react-packager.log
  at SocketClient._handleMessage (SocketClient.js:144:23)
  at BunserBuf.<anonymous> (SocketClient.js:53:42)
  at emitOne (events.js:77:13)
  at BunserBuf.emit (events.js:169:7)
  at BunserBuf.process (/Users/spalagani/Documents/reachapp/topups/node_modules/bser/index.js:289:10)
  at /Users/spalagani/Documents/reachapp/topups/node_modules/bser/index.js:244:12
  at doNTCallback0 (node.js:407:9)
  at process._tickCallback (node.js:336:13)
  Command /bin/sh failed with exit code 1

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow
