### ISSUE TITLE
TypeError: expected dynamic type `string', but had type `int64'

### ISSUE THREAD

**Issue by t-moe** [facebook/react-native#10198]
### Issue Description

I'm getting a native exception when using networking (firebase).
```
E/unknown:React( 6607): Exception in native call
E/unknown:React( 6607): com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `string', but had type `int64'
E/unknown:React( 6607):         at com.facebook.react.bridge.ReadableNativeArray.getString(Native Method)
E/unknown:React( 6607):         at com.facebook.react.modules.network.NetworkingModule.extractHeaders(NetworkingModule.java:535)
E/unknown:React( 6607):         at com.facebook.react.modules.network.NetworkingModule.sendRequest(NetworkingModule.java:222)
E/unknown:React( 6607):         at java.lang.reflect.Method.invoke(Native Method)
E/unknown:React( 6607):         at java.lang.reflect.Method.invoke(Method.java:372)
E/unknown:React( 6607):         at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
E/unknown:React( 6607):         at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
E/unknown:React( 6607):         at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E/unknown:React( 6607):         at android.os.Handler.handleCallback(Handler.java:739)
E/unknown:React( 6607):         at android.os.Handler.dispatchMessage(Handler.java:95)
E/unknown:React( 6607):         at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
E/unknown:React( 6607):         at android.os.Looper.loop(Looper.java:135)
E/unknown:React( 6607):         at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
E/unknown:React( 6607):         at java.lang.Thread.run(Thread.java:818)

```

### Steps to Reproduce / Code Snippets

I have an app that uses firebase and I'm trying to upload an image to firebase storage.
Dependencies:
````
 "buffer": "^5.0.0",
 "firebase": "^3.4.1",
  "react": "15.3.2",
  "react-native": "0.34.1",
  "react-native-image-picker": "^0.22.9"
````
Source: https://gist.github.com/t-moe/1b99a256988d2c16eac720dfa73d2a2a

#### Expected Results

No crash when using firebaseDatabaseRef.putString..

### Additional Information

* React Native version: 0.34.1
* Platform: Android
* Operating System: Windows
* Node: v4.3.1

I'm having a hard time debugging this one, since the exception happens async.
How to debug such a bug?

**Comment by leeight** [comment]
Maybe you can set breakpoints in the Android Studio.

**Comment by leeight** [comment]
Maybe it was caused by the `content-length:` in the request header.
