### ISSUE TITLE
Headless tasks: can't use WritableMap

### ISSUE THREAD

**Issue by rafales** [facebook/react-native#10352]
Headless tasks is an awesome idea, I tried it right away. I ran into some problems though.
### Issue Description

I was trying out the new headless tasks feature. It seems that there is a case where it fails. Basically if you kill the app and try to start a headless task with some arguments it will crash.

This is probably caused by the fact that `getTaskConfig` is called before react native gets initialized but WritableNativeMap requires react to be initialized. More details in the traceback.
### Steps to Reproduce / Code Snippets

Js headless task service:

```
import android.content.Intent;
import android.os.Bundle;

import com.facebook.react.HeadlessJsTaskService;
import com.facebook.react.bridge.Arguments;
import com.facebook.react.jstasks.HeadlessJsTaskConfig;

import javax.annotation.Nullable;


public class HeadlessTaskService extends HeadlessJsTaskService {
    @Nullable
    @Override
    protected HeadlessJsTaskConfig getTaskConfig(Intent intent) {
        Bundle data = intent.getBundleExtra("data");
        String taskKey = intent.getStringExtra("taskKey");

        return new HeadlessJsTaskConfig(taskKey, Arguments.fromBundle(data), 30, true);
    }

    static public void startTask(Context ctx, String taskKey, Bundle data) {
        Intent intent = new Intent(ctx, HeadlessTaskService.class);
        intent.putExtra("taskKey", taskKey);
        intent.putExtra("data", data);

        ctx.startService(intent);
    }
}
```

Notification listener service:

```
package com.nnap;


import android.os.Bundle;

import com.google.android.gms.gcm.GcmListenerService;
import com.nnap.react.HeadlessTaskService;


public class NotificationListenerService extends GcmListenerService {
    @Override
    public void onMessageReceived(String s, Bundle bundle) {
        HeadlessTaskService.startTask(this, "handleGcmMessage", bundle);
    }
}
```

Traceback

```
10-12 15:02:07.570 26539-26539/com.nnap E/AndroidRuntime: FATAL EXCEPTION: main
                                                          Process: com.nnap, PID: 26539
                                                          java.lang.ExceptionInInitializerError
                                                              at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
                                                              at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22)
                                                              at com.facebook.react.bridge.Arguments.createMap(Arguments.java:29)
                                                              at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:119)
                                                              at com.nnap.react.HeadlessTaskService.getTaskConfig(HeadlessTaskService.java:22)
                                                              at com.facebook.react.HeadlessJsTaskService.onStartCommand(HeadlessJsTaskService.java:51)
                                                              at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)
                                                              at android.app.ActivityThread.-wrap17(ActivityThread.java)
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                              at android.os.Looper.loop(Looper.java:148)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                           Caused by: java.lang.RuntimeException: SoLoader.init() not yet called
                                                              at com.facebook.soloader.SoLoader.assertInitialized(SoLoader.java:335)
                                                              at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:238)
                                                              at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
                                                              at com.facebook.react.bridge.ReactBridge.<clinit>(ReactBridge.java:20)
                                                              at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24) 
                                                              at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22) 
                                                              at com.facebook.react.bridge.Arguments.createMap(Arguments.java:29) 
                                                              at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:119) 
                                                              at com.nnap.react.HeadlessTaskService.getTaskConfig(HeadlessTaskService.java:22) 
                                                              at com.facebook.react.HeadlessJsTaskService.onStartCommand(HeadlessJsTaskService.java:51) 
                                                              at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010) 
                                                              at android.app.ActivityThread.-wrap17(ActivityThread.java) 
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                              at android.os.Looper.loop(Looper.java:148) 
                                                              at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```
#### Expected Results

React Native gets initialized before attempting to run or configure a headless task. Headless task executes correctly.
### Additional Information
- React Native version: 0.36.0-rc.0
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): OSX

**Comment by javache** [comment]
cc @foghina

**Comment by eskim** [comment]
+1

**Comment by foghina** [comment]
Ugh it just needs a call to `SoLoader.init()`, which we do in `Application#onCreate()` internally, but I realize the OSS template doesn't do that. I'll see if I can add that.
