### ISSUE TITLE
Can't require image with spaces, etc. in filename

### ISSUE THREAD

**Issue by alex-paterson** [facebook/react-native#10364]
### Issue Description

React-native asset server struggles with images that have spaces in the filename; any non-URI characters I'm assuming. Obviously close if this is by design. [Here's a recreation (index.ios.js only).](https://github.com/alex-paterson/react-native-image-name-bug-recreated).
### Steps to Reproduce / Code Snippets

`<Image source={require('./im/spaces in name.jpg')}/>`
#### Expected Results

Server:

```
Error: Asset not found: im/spaces%20in%20name.jpg for platform: ios
    at _findRoot.then.then.res (/Users/alexpaterson/Desktop/testImage/node_modules/react-native/packager/react-packager/src/AssetServer/index.js:155:17)
    at tryCallOne (/Users/alexpaterson/Desktop/testImage/node_modules/promise/lib/core.js:37:12)
    at /Users/alexpaterson/Desktop/testImage/node_modules/promise/lib/core.js:123:15
    at flush (/Users/alexpaterson/Desktop/testImage/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
### Additional Information
- React Native version: 0.35.0
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by alex-paterson** [comment]
[Added PR](https://github.com/facebook/react-native/pull/10365)

**Comment by lacker** [comment]
fixed in https://github.com/facebook/react-native/pull/10365
