### ISSUE TITLE
RN version0.34,run on MX4,can not run,can solve the problem?

### ISSUE THREAD

**Issue by ma5069073** [facebook/react-native#10414]
java.lang.ClassCastException: com.meizu.widget.MzOverScroller cannot be cast to android.widget.OverScroller
at com.facebook.react.views.scroll.ReactScrollView.(ReactScrollView.java:85)
at com.facebook.react.views.scroll.ReactScrollViewManager.createViewInstance(ReactScrollViewManager.java:53)
at com.facebook.react.views.scroll.ReactScrollViewManager.createViewInstance(ReactScrollViewManager.java:31)
at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:211)
at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:890)
at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:863)
at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:786)
at android.view.Choreographer.doCallbacks(Choreographer.java:591)
at android.view.Choreographer.doFrame(Choreographer.java:559)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
at android.os.Handler.handleCallback(Handler.java:808)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5332)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
at dalvik.system.NativeStart.main(Native Method)

**Comment by reneweb** [comment]
Same as this issue #9697
Looks like it is fixed in RN 0.35: https://github.com/facebook/react-native/commit/5deb528695a8a47156a331b2a0182fabef0253d7

**Comment by ma5069073** [comment]
thank you

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
