### ISSUE TITLE
Android app fails after update to Android 25.0.0

### ISSUE THREAD

**Issue by varungupta85** [facebook/react-native#10587]
### Description

I updated the android appcompat library version to 25.0.0 because I wanted to use some APIs that were introduced in API level 24. After downloading and installing the required files, when I start the app on either device or Genymotion Simulator, it throws the below exception and the attached screenshot appears on the app screen. So, the app isn't exactly crashed but I don't see the app launch screen.

Exception:

```
10-27 13:45:08.550 7317-7317/com.galarmapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.galarmapp, PID: 7317
                                                             android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@c51fa6 -- permission denied for this window type
                                                                 at android.view.ViewRootImpl.setView(ViewRootImpl.java:591)
                                                                 at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
                                                                 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                                 at android.app.Dialog.show(Dialog.java:319)
                                                                 at com.facebook.react.devsupport.DevSupportManagerImpl.handleReloadJS(DevSupportManagerImpl.java:644)
                                                                 at com.facebook.react.XReactInstanceManagerImpl$3$1.run(XReactInstanceManagerImpl.java:401)
                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Below screen shows up on the device and the Simulator

![screen shot 2016-10-27 at 1 57 10 pm](https://cloud.githubusercontent.com/assets/7475133/19760240/5a31095c-9c4e-11e6-92a7-36194cdabd9d.png)

By default, the Draw over other apps permissions is set to No for the app. On the device, if I enable the permission and restart the app, it works as expected. On the Simulator, it keeps showing the same screen. Is there a way to allow this permission by default because a user may not know that he has to enable the Draw over other apps permissions.
### Reproduction

Update the android appcompat library version by updating the following the `android/app/build.gradle` file

`buildToolsVersion "25.0.0`
`compile "com.android.support:appcompat-v7:25.0.0`

Add following permissions to the `AndroidManifest.xml` file

`<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>`
`<uses-permission android:name="android.permission.READ_CONTACTS" />`

Run the app and observe the specified behavior
### Additional Information
- React Native version: 0.34.1
- Platform: Android
- Operating System: MacOS

**Comment by leeight** [comment]
What's your targetSdkVersion? Please set it to `22`.

**Comment by varungupta85** [comment]
I just tested on a Nexus 5 device and observed same behavior on the device also. I have updated the issue with the findings.

@leeight I updated the `targetSdkVersion` in the build.gradle file to 22 and that seemed to have fixed the problem. I had changed it to 25 after updating the android appcompat library version to 25. How does the `targetSdkVersion` affect my app. From what I read on stackoverflow, it seems to indicate that it has no effect on the actual app and is more of a sign to the Android OS as to how I have tested my app.

Specifically, I want to know that would I still be able to use the new features added on API level 24 and 25 even though the `targetSdkVersion` is set to 25. Thanks!

**Comment by leeight** [comment]
Please check the discussion on https://github.com/facebook/react-native/pull/10479

**Comment by raedur** [comment]
@leeight Is there still compatibility issues with targetSdkVersion 24+?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-app-fails-after-update-to-android-2500
