### ISSUE TITLE
[Android]Text's lineHeight should be float instead of int

### ISSUE THREAD

**Issue by littlesome** [facebook/react-native#10607]
Got this error on android when set a float lineHeight property to Text component,

```
E/unknown:ViewManager: Error while updating prop lineHeight
  com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `int64', but had type `double'
      at com.facebook.react.bridge.ReadableNativeMap.getInt(Native Method)
      at com.facebook.react.uimanager.ReactStylesDiffMap.getInt(ReactStylesDiffMap.java:67)
      at com.facebook.react.uimanager.ViewManagersPropertyCache$IntPropSetter.extractProperty(ViewManagersPropertyCache.java:133)
      at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:98)
      at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:150)
      at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:52)
      at com.facebook.react.uimanager.ReactShadowNode.updateProperties(ReactShadowNode.java:231)
      at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:167)
      at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:206)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:322)
      at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
      at android.os.Handler.handleCallback(Handler.java:743)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
      at android.os.Looper.loop(Looper.java:150)
      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
      at java.lang.Thread.run(Thread.java:833)
```

[iOS RCTTextManager.m](https://github.com/facebook/react-native/blob/master/Libraries/Text/RCTTextManager.m#L72)

```
RCT_EXPORT_SHADOW_PROPERTY(lineHeight, CGFloat)
```

[Android ReactTextShadowNode.java](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextShadowNode.java#L415-L419)

```
  @ReactProp(name = ViewProps.LINE_HEIGHT, defaultInt = UNSET)
  public void setLineHeight(int lineHeight) {
    mLineHeight = lineHeight == UNSET ? Float.NaN : PixelUtil.toPixelFromSP(lineHeight);
    markUpdated();
  }
```

Change to float solves my problem:

```
  @ReactProp(name = ViewProps.LINE_HEIGHT, defaultFloat = UNSET)
  public void setLineHeight(float lineHeight) {
    mLineHeight = lineHeight == UNSET ? Float.NaN : PixelUtil.toPixelFromSP(lineHeight);
    markUpdated();
  }
```

Is this a bug?
### Additional Information
- React Native version: 0.33
- Platform: [FILL THIS OUT: iOS, Android, or both?] android
- Operating System: [FILL THIS OUT: MacOS, Linux, or Windows?] windows

**Comment by leeight** [comment]
👍

**Comment by lacker** [comment]
Hmm, well our documentation is somewhat unhelpful here just saying this is supposed to be a "number" and offering no further description. https://facebook.github.io/react-native/docs/text.html . So we can't use the docs as a source of truth. Do non-integer line heights work on iOS?

**Comment by mkonicek** [comment]
On Android, does it make sense to set the line height to 3.5 Scale-independent Pixels (sp)?

We might be better off just accepting the 3.5sp rather than crashing, since `PixelUtil.toPixelFromSP` accepts floats. Another argument for doing this is that on iOS it won't crash if you pass a float - platform parity is important.

Can you send a pull request with your change please?

**Comment by mkonicek** [comment]
> Hmm, well our documentation is somewhat unhelpful here just saying this is supposed to be a "number"

JS only has floats so a number really means a float here.

**Comment by mkonicek** [comment]
Thanks for reporting this @littlesome, good catch!

**Comment by lacker** [comment]
@mkonicek Well things that are supposed to be integers we also only document as a "number", like numberOfLines, so I guess what I mean is just that our docs contain insufficient info to use that as the source of truth. Anyway I am convinced that this is indeed a bug!

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/androidtexts-lineheight-should-be-float-instead-of-int
