### ISSUE TITLE
App crash due to 'Could not create CursorWindow from Parcel due to error -12'

### ISSUE THREAD

**Issue by narychen** [facebook/react-native#10639]
I create a CameraRoll viewer to view photos in my android phone which has a lot photos taken by me. The photos are listed in three items of one row in a ListView just as what UIExplorer Example does.
I also set removeClippedSubviews={true} in my ListView.
When I browse the photos, I monitor the memory dump to see if it will be out of memory.
It seems that removeClippedSubviews works. The memory will raise up and down when I scroll down to browse more and more photos.
But I always crashed at some point of view. It seems like the images could recycle by fresco but the views are too many to create.
I use react-native 0.27.2
The log is
```
10-31 11:06:21.259 4008-4080/com.eggf E/CursorWindow: Could not create CursorWindow from Parcel due to error -12.
10-31 11:06:21.279 4008-4080/com.eggf E/unknown:React: Exception in native call from JS
                                                       android.database.CursorWindowAllocationException: Cursor window could not be created from binder.
                                                           at android.database.CursorWindow.<init>(CursorWindow.java:133)
                                                           at android.database.CursorWindow.<init>(CursorWindow.java:41)
                                                           at android.database.CursorWindow$1.createFromParcel(CursorWindow.java:681)
                                                           at android.database.CursorWindow$1.createFromParcel(CursorWindow.java:679)
                                                           at android.database.BulkCursorDescriptor.readFromParcel(BulkCursorDescriptor.java:75)
                                                           at android.database.BulkCursorDescriptor$1.createFromParcel(BulkCursorDescriptor.java:34)
                                                           at android.database.BulkCursorDescriptor$1.createFromParcel(BulkCursorDescriptor.java:30)
                                                           at android.content.ContentProviderProxy.query(ContentProviderNative.java:388)
                                                           at android.content.ContentResolver.query(ContentResolver.java:414)
                                                           at android.content.ContentResolver.query(ContentResolver.java:357)
                                                           at com.facebook.react.modules.camera.CameraRollManager$GetPhotosTask.doInBackgroundGuarded(CameraRollManager.java:296)
                                                           at com.facebook.react.modules.camera.CameraRollManager$GetPhotosTask.doInBackgroundGuarded(CameraRollManager.java:246)
                                                           at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:34)
                                                           at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:22)
                                                           at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                           at java.lang.Thread.run(Thread.java:841)
```

**Comment by brentvatne** [comment]
Hi there! React Native 0.27.2 is nearly 10 releases behind the current version, can you try this on the latest version and see if it's still an issue? If so, please re-create the issue and include a simple reproducible example so that it's easy for people who can help you with the issue to do so.
