### ISSUE TITLE
Crash on Android 4.4.2: XmlPullParserException, VectorDrawable, Switch

### ISSUE THREAD

**Issue by adrienjt** [facebook/react-native#10711]
Since I've upgraded react-native from 0.32.0 to 0.35.0, it seems that older versions of Android have issues with Switch. When running on my device (4.4.2), my app crashes when I request the view containing switches. No problem on the Android emulator or iOS.

Here is the fatal exception:
```
E/VdcInflateDelegate(16532): Exception while inflating <vector>
E/VdcInflateDelegate(16532): org.xmlpull.v1.XmlPullParserException: Binary XML file line #17<vector> tag requires viewportWidth > 0
E/VdcInflateDelegate(16532): 	at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:717)
E/VdcInflateDelegate(16532): 	at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:654)
E/VdcInflateDelegate(16532): 	at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:617)
E/VdcInflateDelegate(16532): 	at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:745)
E/VdcInflateDelegate(16532): 	at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:365)
E/VdcInflateDelegate(16532): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
E/VdcInflateDelegate(16532): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
E/VdcInflateDelegate(16532): 	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:723)
E/VdcInflateDelegate(16532): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
E/VdcInflateDelegate(16532): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
E/VdcInflateDelegate(16532): 	at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
E/VdcInflateDelegate(16532): 	at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:71)
E/VdcInflateDelegate(16532): 	at android.support.v7.widget.SwitchCompat.<init>(SwitchCompat.java:212)
E/VdcInflateDelegate(16532): 	at android.support.v7.widget.SwitchCompat.<init>(SwitchCompat.java:189)
E/VdcInflateDelegate(16532): 	at android.support.v7.widget.SwitchCompat.<init>(SwitchCompat.java:178)
E/VdcInflateDelegate(16532): 	at com.facebook.react.views.switchview.ReactSwitch.<init>(ReactSwitch.java:26)
E/VdcInflateDelegate(16532): 	at com.facebook.react.views.switchview.ReactSwitchManager.createViewInstance(ReactSwitchManager.java:101)
E/VdcInflateDelegate(16532): 	at com.facebook.react.views.switchview.ReactSwitchManager.createViewInstance(ReactSwitchManager.java:31)
E/VdcInflateDelegate(16532): 	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
E/VdcInflateDelegate(16532): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:211)
E/VdcInflateDelegate(16532): 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
E/VdcInflateDelegate(16532): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:890)
E/VdcInflateDelegate(16532): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:863)
E/VdcInflateDelegate(16532): 	at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
E/VdcInflateDelegate(16532): 	at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
E/VdcInflateDelegate(16532): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:801)
E/VdcInflateDelegate(16532): 	at android.view.Choreographer.doCallbacks(Choreographer.java:603)
E/VdcInflateDelegate(16532): 	at android.view.Choreographer.doFrame(Choreographer.java:572)
E/VdcInflateDelegate(16532): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
E/VdcInflateDelegate(16532): 	at android.os.Handler.handleCallback(Handler.java:733)
E/VdcInflateDelegate(16532): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/VdcInflateDelegate(16532): 	at android.os.Looper.loop(Looper.java:157)
E/VdcInflateDelegate(16532): 	at android.app.ActivityThread.main(ActivityThread.java:5356)
E/VdcInflateDelegate(16532): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/VdcInflateDelegate(16532): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/VdcInflateDelegate(16532): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
E/VdcInflateDelegate(16532): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
E/VdcInflateDelegate(16532): 	at dalvik.system.NativeStart.main(Native Method)
```

This stackoverflow question http://stackoverflow.com/q/35622438 has unsatisfying answers messing up with gradle. This answer http://stackoverflow.com/a/35814299 seems good but requires changing react-native's source code. I haven't tried it yet.

**Comment by tema87** [comment]
I had the same problem. I solved the problem by updating gradle from 1.3.1 to 2.1.2.

**Comment by vafada** [comment]
@tema87 

how did you upgrade gradle to 2.1.2?

just replace `classpath 'com.android.tools.build:gradle:1.3.1'` to `classpath 'com.android.tools.build:gradle:2.1.2` in `android/build.gradle`?

**Comment by mkonicek** [comment]
This likely has to do with the Android Support Library. Thanks for reporting! We should switch to a more recent Gradle version.

**Comment by dapatricio** [comment]
i have the same problem my app only runs in android 5 or superior but i need it in 4.4 but it makes me the same error

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/crash-on-android-442-xmlpullparserexception-vectordrawable-switch
