### ISSUE TITLE
Android: NPE in UIImplementation.setChildren (0.34.1)

### ISSUE THREAD

**Issue by silverspace** [facebook/react-native#10755]
A customer received this NPE in UIImplementation.setChildren: 

```
Fatal Exception: java.lang.NullPointerException
       at com.facebook.react.uimanager.UIImplementation.setChildren(UIImplementation.java:369)
       at com.facebook.react.uimanager.UIManagerModule.setChildren(UIManagerModule.java:289)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:146)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:841)
```

### Reproduction

This happened on a customer production device, so I only have the above stack trace. I have been unable to reproduce this issue myself. The customer thinks that he was rotating the device while a new page was being rendered, but that could be completely unrelated. 

I am filing this primarily because there should be a defensive programming check against **mShadowNodeRegistry.getNode(viewTag)** returning null in:
https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIImplementation.java#L371

### Additional Information

* React Native version: 0.34.1
* Platform: Android: SM-T230, 4.4.2
* Operating System: MacOS

**Comment by brentvatne** [comment]
Hi there! Please keep trying to create a repro-case. I'm not sure defensively checking against null is the fix, that could patch up the problem here but I think you should never get this far when the node is null to begin with.

**Comment by littlesome** [comment]
#11524

**Comment by gavinyeah** [comment]
I have also encountered this issue and it can repro quite frequently when you rotating the device and the page gets re-rendering. I guess maybe because the rendering phase before rotate can't get the original objects after rotated. The previous rendering is not properly stopped when rotating, is it possible?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-npe-in-uiimplementationsetchildren-0341

**Comment by Dantalion** [comment]
I just encountered the same issue, also on a Customer Device.
