### ISSUE TITLE
Android crashes after package change

### ISSUE THREAD

**Issue by af-fess** [facebook/react-native#10809]
My project is named `demo`. I created new Android project with command: `react-native android`.
So it generated me package `com.demo`.
Everything is runs successfully.

Run on device Nexus 5x with Android 7

Now I want  to change package name to `com.company.reactnative.demo`. I changed 4 resources from `com.demo` to `com.company.reactnative.demo`:

- `BUCK` section:
```
android_build_config(
  name = 'build_config',
  package = 'com.company.reactnative.demo',
)

android_resource(
  name = 'res',
  res = 'src/main/res',
  package = 'com.company.reactnative.demo',
)
```

- `bundle.gradle` section:

```
defaultConfig {
        applicationId "com.company.reactnative.demo"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
```
-  java file package names
- `AndroidManifest` -> `package="com.company.reactnative.demo"`
- physical sources for java files.

Result:

Application is build successfully but on start crashes with error:

```

11-08 12:00:18.709 2304-2304/? I/art: Late-enabling -Xcheck:jni
11-08 12:00:18.869 2304-2304/com.company.reactnative.demo V/fb-UnpackingSoSource: locked dso store /data/user/0/com.company.reactnative.demo/lib-main
11-08 12:00:18.874 2304-2304/com.company.reactnative.demo V/fb-UnpackingSoSource: deps mismatch on deps store: regenerating
11-08 12:00:18.874 2304-2304/com.company.reactnative.demo V/fb-UnpackingSoSource: so store dirty: regenerating
11-08 12:00:18.903 2304-2304/com.company.reactnative.demo D/ApkSoSource: not allowing consideration of lib/armeabi-v7a/libfb.so: deferring to libdir
11-08 12:00:18.904 2304-2304/com.company.reactnative.demo D/ApkSoSource: not allowing consideration of lib/armeabi-v7a/libfolly_json.so: deferring to libdir
11-08 12:00:18.904 2304-2304/com.company.reactnative.demo D/ApkSoSource: not allowing consideration of lib/armeabi-v7a/libglog.so: deferring to libdir
11-08 12:00:18.904 2304-2304/com.company.reactnative.demo D/ApkSoSource: not allowing consideration of lib/armeabi-v7a/libglog_init.so: deferring to libdir
11-08 12:00:18.904 2304-2304/com.company.reactnative.demo D/ApkSoSource: not allowing consideration of lib/armeabi-v7a/libgnustl_shared.so: deferring to libdir
11-08 12:00:18.904 2304-2304/com.company.reactnative.demo D/ApkSoSource: not allowing consideration of lib/armeabi-v7a/libicu_common.so: deferring to libdir
11-08 12:00:18.904 2304-2304/com.company.reactnative.demo D/ApkSoSource: not allowing consideration of lib/armeabi-v7a/libimagepipeline.so: deferring to libdir
11-08 12:00:18.904 2304-2304/com.company.reactnative.demo D/ApkSoSource: not allowing consideration of lib/armeabi-v7a/libjsc.so: deferring to libdir
11-08 12:00:18.904 2304-2304/com.company.reactnative.demo D/ApkSoSource: not allowing consideration of lib/armeabi-v7a/libreactnativejni.so: deferring to libdir
11-08 12:00:18.904 2304-2304/com.company.reactnative.demo D/ApkSoSource: not allowing consideration of lib/armeabi-v7a/libreactnativejnifb.so: deferring to libdir
11-08 12:00:18.904 2304-2304/com.company.reactnative.demo V/fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
11-08 12:00:18.905 2304-2304/com.company.reactnative.demo V/fb-UnpackingSoSource: starting syncer worker
11-08 12:00:18.914 2304-2304/com.company.reactnative.demo V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.company.reactnative.demo/lib-main (from syncer thread)
11-08 12:00:18.916 2304-2304/com.company.reactnative.demo V/fb-UnpackingSoSource: not releasing dso store lock for /data/user/0/com.company.reactnative.demo/lib-main (syncer thread started)
11-08 12:00:18.939 2304-2304/com.company.reactnative.demo I/art: Thread[1,tid=2304,Native,Thread*=0xe5305400,peer=0x74071000,"main"] recursive attempt to load library "/data/app/com.company.reactnative.demo-1/lib/arm/libfb.so"
11-08 12:00:18.961 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTRenderableViewManager
11-08 12:00:18.969 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
11-08 12:00:18.972 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
11-08 12:00:18.973 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
11-08 12:00:18.974 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
11-08 12:00:18.977 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
11-08 12:00:18.983 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
11-08 12:00:18.985 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
11-08 12:00:18.986 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
11-08 12:00:18.989 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
11-08 12:00:18.990 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
11-08 12:00:18.994 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
11-08 12:00:18.998 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
11-08 12:00:18.999 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
11-08 12:00:19.000 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
11-08 12:00:19.002 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
11-08 12:00:19.003 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
11-08 12:00:19.006 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
11-08 12:00:19.009 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
11-08 12:00:19.011 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
11-08 12:00:19.013 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
11-08 12:00:19.013 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
11-08 12:00:19.015 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
11-08 12:00:19.016 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
11-08 12:00:19.017 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
11-08 12:00:19.018 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
11-08 12:00:19.031 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
11-08 12:00:19.032 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
11-08 12:00:19.032 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
11-08 12:00:19.036 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
11-08 12:00:19.056 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
11-08 12:00:19.059 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
11-08 12:00:19.060 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
11-08 12:00:19.061 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.recyclerview.RecyclerViewBackedScrollViewManager
11-08 12:00:19.063 2304-2315/com.company.reactnative.demo I/art: Background partial concurrent mark sweep GC freed 24100(1447KB) AllocSpace objects, 1(36KB) LOS objects, 39% free, 4MB/8MB, paused 7.432ms total 47.565ms
11-08 12:00:19.066 2304-2321/com.company.reactnative.demo W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
11-08 12:00:19.092 2304-2321/com.company.reactnative.demo D/NetworkSecurityConfig: No Network Security Config specified, using platform default
11-08 12:00:19.094 2304-2324/com.company.reactnative.demo I/Adreno: QUALCOMM build                   : 74df444, I409c65498b
                                                                      Build Date                       : 06/22/16
                                                                      OpenGL ES Shader Compiler Version: XE031.08.00.02
                                                                      Local Branch                     : N16
                                                                      Remote Branch                    : 
                                                                      Remote Branch                    : 
                                                                      Reconstruct Branch               : 
11-08 12:00:19.140 2304-2324/com.company.reactnative.demo I/OpenGLRenderer: Initialized EGL, version 1.4
11-08 12:00:19.140 2304-2324/com.company.reactnative.demo D/OpenGLRenderer: Swap behavior 1
11-08 12:00:19.195 2304-2333/com.company.reactnative.demo E/AndroidRuntime: FATAL EXCEPTION: mqt_js
                                                                              Process: com.company.reactnative.demo, PID: 2304
                                                                              java.lang.RuntimeException: com.facebook.react.devsupport.JSException: Could not get BatchedBridge, make sure your bundle is packaged correctly
                                                                                  at com.facebook.react.bridge.DefaultNativeModuleCallExceptionHandler.handleException(DefaultNativeModuleCallExceptionHandler.java:24)
                                                                                  at com.facebook.react.devsupport.DisabledDevSupportManager.handleException(DisabledDevSupportManager.java:144)
                                                                                  at com.facebook.react.cxxbridge.CatalystInstanceImpl.onNativeException(CatalystInstanceImpl.java:393)
                                                                                  at com.facebook.react.cxxbridge.CatalystInstanceImpl.access$400(CatalystInstanceImpl.java:50)
                                                                                  at com.facebook.react.cxxbridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:409)
                                                                                  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:33)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                                  at java.lang.Thread.run(Thread.java:761)
                                                                               Caused by: com.facebook.react.devsupport.JSException: Could not get BatchedBridge, make sure your bundle is packaged correctly
                                                                                  at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                                  at android.os.Looper.loop(Looper.java:154) 
                                                                                  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                                                  at java.lang.Thread.run(Thread.java:761) 
                                                                               Caused by: com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
                                                                                  at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                                  at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                                  at android.os.Looper.loop(Looper.java:154) 
                                                                                  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                                                  at java.lang.Thread.run(Thread.java:761) 
 
```

tried to run `adb reverse tcp:8081 tcp:8081` doesn't help

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by damusnet** [comment]
Try something like https://github.com/JuneDomingo/react-native-rename
