### ISSUE TITLE
Not able to run on Node v7.1.0 on Windows

### ISSUE THREAD

**Issue by sonnyvan** [facebook/react-native#10824]
### Description
I upgraded to Node v7.1.0 on Windows 10 and I'm running into an error when running `react-native run-android`.  

Error:  
```>react-native run-android

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at WriteStream.stream.write (C:\Users\[...]\node_modules\ansi\lib\newlines.js:36:21)
    at Object.execFileSync (child_process.js:506:20)
    at Object.run (C:/Users/[....]/node_modules/react-native/local-cli/cliEntry.js:163:16)
```

### Reproduction

I have downgraded to Node v7.0.0 and this has resolved my issue. However, once I upgraded to Node 7.1.0 it errors out again.

Also, I'm not able to upgrade to RN 0.37.0 using `react-native upgrade` as it gives the same error.

### Additional Information

* React Native version: 0.36.0
* Platform: Android
* Operating System: Windows 10

**Comment by mischah** [comment]
I filed an issue in the Node.js repo: https://github.com/nodejs/node/issues/9542

Please head over there in case you have any additional (and useful) information to share.
Thanks :octocat:

**Comment by g-guth** [comment]
same error here, but for installing any package.
