### ISSUE TITLE
Keeps getting error "SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (4:0)"

### ISSUE THREAD

**Issue by ChrisOHu** [facebook/react-native#10829]
### Description

Hi,
Simply run ```npm start``` and run the iphone simulator from xcode, the native xcode building is successful, however when loading the JS codes, I keep getting this error:

```
yntaxError: 'import' and 'export' may appear only with 'sourceType: module' (4:0)
    at Parser.pp.raise (/Users/chrishu/Projects/Cabin/Cabin/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.parseStatement (/Users/chrishu/Projects/Cabin/Cabin/node_modules/babylon/lib/parser/statement.js:138:16)
    at Parser.pp.parseBlockBody (/Users/chrishu/Projects/Cabin/Cabin/node_modules/babylon/lib/parser/statement.js:529:21)
    at Parser.pp.parseTopLevel (/Users/chrishu/Projects/Cabin/Cabin/node_modules/babylon/lib/parser/statement.js:36:8)
    at Parser.parse (/Users/chrishu/Projects/Cabin/Cabin/node_modules/babylon/lib/parser/index.js:129:19)
    at Object.parse (/Users/chrishu/Projects/Cabin/Cabin/node_modules/babylon/lib/index.js:47:47)
    at extractDependencies (/Users/chrishu/Projects/Cabin/Cabin/node_modules/react-native/packager/react-packager/src/JSTransformer/worker/extract-dependencies.js:29:23)
transformed 182/304 (60%)es/react-native/packager/react-packager/src/JSTransformer/worker/index.js:53:9)
    at module.exports (/Users/chrishu/Projects/Cabin/Cabin/node_modules/react-native/packager/transformer.js:130:3)
    at transformCode (/Users/chrishu/Projects/Cabin/Cabin/node_modules/react-native/packager/react-packager/src/JSTransformer/worker/index.js:27:3)
transformed 196/314 (62%)/Users/chrishu/Projects/Cabin/Cabin/node_modules/babylon/lib/parser/location.js:25
  throw err;
```

I'm using ```"babel-preset-react-native``` and ```babel-root-import```.

Thanks a lot : )

### Additional Information

* React Native version: [0.36.1]
* Platform: [iOS]
* Operating System: [MacOS]

**Comment by ChrisOHu** [comment]
Hi,

After digging around for a while, I removed all the babel & eslint package, also removed .eslintrc, .babelrc, this error was gone.

However now I got a white screen on the Simulator after js codes transform complete.

Anyone got an clue here ? Thanks in advance : )

**Comment by ChrisOHu** [comment]
Hi guys,

Just found the white screen is caused by a missing package (babel-root-import).
The xcode console printed the errors in the JS code.

Closing this : )

**Comment by ChrisOHu** [comment]
Hi guys,

If I `npm link` (which creates a symbol link to /usr/local/lib/node_module/the_module) a local module then this error would be thrown by packager.
Instead if I `npm install` (which copies the content of the_module) it this error would be gone.
