### ISSUE TITLE
`react-native init` fails to run

### ISSUE THREAD

**Issue by kwak27** [facebook/react-native#10886]
### Description

Following the Getting Started guide, running `react-native init myProject` fails with the following error message:

```
dkwak-C02Q1083FVH8:~ davidkwak$ react-native init myProject

/Users/davidkwak/.nvm/v0.10.32/lib/node_modules/react-native-cli/index.js:81
  let yarnVersion;
  ^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

### Reproduction

Run:
```
npm install -g react-native-cli
react-native init myProject
```

Here are some versions in my environment that may be relevant. I couldn't find any info on what version of node is required, if any:
```
dkwak-C02Q1083FVH8:~ davidkwak$ node --version
v0.10.32
dkwak-C02Q1083FVH8:~ davidkwak$ npm --version
3.10.9
dkwak-C02Q1083FVH8:~ davidkwak$ nvm --version
0.32.1
```

I'm able to workaround this by installing 1.0.0: `npm install -g react-native-cli`

### Additional Information

* React Native version: react-native-cli@1.2.0 
* Platform: iOS
* Operating System: MacOS

**Comment by kwak27** [comment]
After installing react-native-cli@1.0.0 and running `react-native init`, I see the message now that Node 4.0 or newer is required and that v0.10.32 is not supported. 

Running the init command on node 7.1.0 and react-native-cli@1.2.0 appears to work normally, so I'm closing this issue
