### ISSUE TITLE
crashed in release mode

### ISSUE THREAD

**Issue by zbdyiliu** [facebook/react-native#10890]
### Description

When I try to run app in release mode with `react-native run-android --variant=release`. My app will crashed after launch and get the exception below:

```java
11-11 20:17:50.594 5177-5177/com.xxx E/AndroidRuntime: FATAL EXCEPTION: main
                                                            Process: com.xxx, PID: 5177
                                                            java.lang.RuntimeException: Could not get BatchedBridge, make sure your bundle is packaged correctly
                                                                at com.facebook.react.cxxbridge.CatalystInstanceImpl.loadScriptFromAssets(Native Method)
                                                                at com.facebook.react.cxxbridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:33)
                                                                at com.facebook.react.cxxbridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:177)
                                                                at com.facebook.react.XReactInstanceManagerImpl$4.call(XReactInstanceManagerImpl.java:918)
                                                                at com.facebook.react.XReactInstanceManagerImpl$4.call(XReactInstanceManagerImpl.java:911)
                                                                at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:74)
                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                at android.os.Looper.loop(Looper.java:154)
                                                                at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                at java.lang.Thread.run(Thread.java:761)
```

But it works fine in debug mode with `react-native run-android`.

### Additional Information

* React Native version: 0.35
* Platform: Android
* Operating System: MacOS

**Comment by zbdyiliu** [comment]
It is solved by turning off Configuration on demand option in global gradle settings
