### ISSUE TITLE
react-native run-android command error

### ISSUE THREAD

**Issue by CaiHuan** [facebook/react-native#10920]
PS E:\react-native> cd .\demo\
PS E:\react-native\demo> react-native run-android
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at WriteStream.stream.write (E:\react-native\demo\node_modules\ansi\lib\newlines.js:36:21)
    at Object.execFileSync (child_process.js:506:20)
    at Object.run (E:/react-native/demo/node_modules/react-native/local-cli/cliEntry.js:157:16)

windows 10 x64

**Comment by sanjibnarzary** [comment]
Node v7 causing problem. There is a possible duplicate [10824](https://github.com/facebook/react-native/issues/10824)

**Comment by ericvicenti** [comment]
It looks like this issue is being tracked in the nodejs repo: https://github.com/nodejs/node/issues/9542

Hopefully it gets fixed soon!
