### ISSUE TITLE
[Packager] Requiring unknown module "Dimensions" in Release Bundle

### ISSUE THREAD

**Issue by sreejithr** [facebook/react-native#10943]
I upgraded to `v0.37` from `v0.23`. I generated the bundle using this command:

```
react-native bundle \
   --assets-dest ./android/app/src/main/res/ \
   --entry-file ./index.android.js \
   --bundle-output ./android/app/src/main/assets/index.android.bundle \
   --platform android --dev false
```
I churned out a release APK which crashes on launch with this stack trace:
```
E/ReactNativeJS( 6610): Requiring unknown module "Dimensions".
D/OpenGLRenderer( 6610): Enabling debug mode 0
W/EGL_emulation( 6610): eglSurfaceAttrib not implemented
W/OpenGLRenderer( 6610): Failed to set EGL_SWAP_BEHAVIOR on surface 0xe3a92020, error=EGL_SUCCESS
E/AndroidRuntime( 6610): FATAL EXCEPTION: mqt_native_modules
E/AndroidRuntime( 6610): Process: com.driveu.partner, PID: 6610
E/AndroidRuntime( 6610): com.facebook.react.common.JavascriptException: Requiring unknown module "Dimensions"., stack:
E/AndroidRuntime( 6610): n@2:700
E/AndroidRuntime( 6610): o@2:404
E/AndroidRuntime( 6610): e@2:326
E/AndroidRuntime( 6610): i@2:188
E/AndroidRuntime( 6610): <unknown>@509:190
E/AndroidRuntime( 6610): o@2:517
E/AndroidRuntime( 6610): e@2:326
E/AndroidRuntime( 6610): i@2:188
E/AndroidRuntime( 6610): <unknown>@494:168
E/AndroidRuntime( 6610): o@2:517
E/AndroidRuntime( 6610): e@2:326
E/AndroidRuntime( 6610): i@2:188
E/AndroidRuntime( 6610): <unknown>@462:200
E/AndroidRuntime( 6610): o@2:517
E/AndroidRuntime( 6610): e@2:326
E/AndroidRuntime( 6610): i@2:188
E/AndroidRuntime( 6610): <unknown>@12:579
E/AndroidRuntime( 6610): o@2:517
E/AndroidRuntime( 6610): e@2:256
E/AndroidRuntime( 6610): i@2:188
E/AndroidRuntime( 6610): global code@586:9
E/AndroidRuntime( 6610):
E/AndroidRuntime( 6610): 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:95)
E/AndroidRuntime( 6610): 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:79)
E/AndroidRuntime( 6610): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6610): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 6610): 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:322)
E/AndroidRuntime( 6610): 	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
E/AndroidRuntime( 6610): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E/AndroidRuntime( 6610): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 6610): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 6610): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
E/AndroidRuntime( 6610): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 6610): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
E/AndroidRuntime( 6610): 	at java.lang.Thread.run(Thread.java:818)
```
## Reproduction

I cannot reproduce this in the example project. This leads me to believe there's some issue with the way my project is crafted. I've posted my `package.json` ~~and `build.gradle`~~ below.

**When I bundle my JS bundle with `--dev true`, this error doesn't happen.**  I'm guessing this is some issue with the `packager`. Has anyone run into this before?

* React Native version: `0.37.0`
* Platform: Android
* Operating System: MacOS

### package.json
```
{
  "name": "DriverApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "qs": "^6.1.0",
    "react": "^15.3.2",
    "react-native": "^0.37.0",
    "react-native-dismiss-keyboard": "0.0.3",
    "react-native-drawer-layout": "^0.4.0",
    "react-native-fabric": "^0.2.1",
    "react-native-maps": "^0.10.2",
    "react-native-modalbox": "^1.3.1",
    "react-native-progress-circular": "^0.1.0",
    "react-native-radio-buttons": "^0.12.1",
    "react-native-router-flux": "^3.35.0",
    "react-native-scrollable-tab-view": "^0.4.0",
    "react-native-send-intent": "^1.0.7",
    "react-native-simple-radio-button": "^2.3.0",
    "react-native-slide-button": "^1.2.1",
    "react-native-star-rating": "^1.0.6",
    "react-native-swipeout": "^2.0.12",
    "react-native-vector-icons": "^1.3.2",
    "react-redux": "^4.4.0",
    "redux": "^3.3.1",
    "redux-persist": "^2.0.1",
    "remote-redux-devtools-on-debugger": "^0.3.5"
  },
  "devDependencies": {
    "redux-devtools": "^3.1.1"
  }
}
```
**EDIT**: Removed build.gradle since I'm pretty convinced it's an issue with the packager.

**Comment by sreejithr** [comment]
I turned off minification in the bundle command and snooped around. I saw one occurrence where this happened:
```
var Dimensions=require('Dimensions');
```
In every other place, I'm seeing this:
```
var Dimensions=require(109 /* Dimensions */);
```
It seems obvious why require crashed. So, what gives? The packager didn't translate this `require` line?

**Comment by sreejithr** [comment]
For anyone facing this issue, a temporary work-around is to goto `node_modules/react-native/local-cli/bundle/buildBundle.js` and goto line 34 (v0.37). There, in the `requestOpts`, hardcode the value of minify to `false`.
```
function buildBundle(args, config, output = outputBundle, packagerInstance) {
  // This is used by a bazillion of npm modules we don't control so we don't
  // have other choice than defining it as an env variable here.
  process.env.NODE_ENV = args.dev ? 'development' : 'production';

  const requestOpts = {
    entryFile: args.entryFile,
    sourceMapUrl: args.sourcemapOutput && path.basename(args.sourcemapOutput),
    dev: args.dev,
    minify: !args.dev,  // <----- Hardcode this to false
    platform: args.platform,
  };
```
Note that you will get a non-minified bundle. Generate and open the bundle. Search for phrase `Dimensions=`. You'll run into a line like this:
```
var Dimensions=require(109 /* Dimensions */);var
```
Now find and replace occurrences of `var Dimensions=require('Dimensions')` with `require(109)`. Haven't gotten around to fixing this. This is a work-around.

**Comment by akhenda** [comment]
Thank you for this workaround @sreejithr  It has really saved me some valuable time. I hope someone fixes this though.

![image](https://cloud.githubusercontent.com/assets/15331021/20809399/f7769a86-b816-11e6-9039-4600cc0fd93e.png)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/packager-requiring-unknown-module-dimensions-in-release-bundle
