### ISSUE TITLE
[Docs] I can't publish the website

### ISSUE THREAD

**Issue by Beomi** [facebook/react-native#10945]
I've cloned master and modified docs(md files) for translation.
when i tried to runserver, it seems works well.
but when i followed the guide to publish website,

cd website
npm run publish-website

when i tried to publish-website, it throws error "missing script: website-publish".

How can I publish my react-native website?

**Comment by ruci06** [comment]
Try 
npm run gh-pages

refer `react-native/website/package.json`

**Comment by Beomi** [comment]
Thanks @ruci06 , but one more question.
Should I have to use my own CI(circus?) for deploy?
This error happens,

```
> @ gh-pages /Users/beomi/coding/react-native/website
> node publish-gh-pages.js

/Users/beomi/coding/react-native/website/publish-gh-pages.js:27
if (CIRCLE_BRANCH.indexOf(`-stable`) !== -1) {
                 ^

TypeError: Cannot read property 'indexOf' of undefined
    at Object.<anonymous> (/Users/beomi/coding/react-native/website/publish-gh-pages.js:27:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.6.0/bin/node" "/usr/local/bin/npm" "run" "gh-pages"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! @ gh-pages: `node publish-gh-pages.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ gh-pages script 'node publish-gh-pages.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node publish-gh-pages.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/beomi/coding/react-native/website/npm-debug.log
```

**Comment by mdamien** [comment]
You can't use `npm run gh-pages` since would you need commit right to this repo to commit to the `gh-pages` branch.

To test your fix to the website, just run `npm start`.

Then, when you will do the PR, the CI is gonna test the code for you too.

**Comment by ericvicenti** [comment]
To make changes to the website, please submit a pull request so the community can review.

Are you able to run the website with `cd website && npm install && npm start`? It can be very slow in development mode, before the static html gets generated.
