### ISSUE TITLE
[Android] webview use protocol start other APP

### ISSUE THREAD

**Issue by vistier** [facebook/react-native#10967]
### Description
Use the protocol to start the app, when there is no app application will collapse

### Reproduction

```
cn.com.vister.imeth W/System.err: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=mbspay://netbank?payparam=2,okq3HiA==&merchantid=105&orderid=J10001&payrequrl=https://ibsbjstar.ccb.com.cn/CCBIS/B2CMainPlat_07_MPAY flg=0x10000000 }
cn.com.vister.imeth W/System.err:     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1801)
cn.com.vister.imeth W/System.err:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1499)
cn.com.vister.imeth W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:3942)
cn.com.vister.imeth W/System.err:     at android.app.Activity.startActivityForResult(Activity.java:3889)
cn.com.vister.imeth W/System.err:     at android.app.Activity.startActivity(Activity.java:4213)
cn.com.vister.imeth W/System.err:     at android.app.Activity.startActivity(Activity.java:4181)
cn.com.vister.imeth W/System.err:     at android.content.ContextWrapper.startActivity(ContextWrapper.java:337)
cn.com.vister.imeth W/System.err:     at com.facebook.react.views.webview.ReactWebViewManager$ReactWebViewClient.shouldOverrideUrlLoading(ReactWebViewManager.java:126)
cn.com.vister.imeth W/System.err:     at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:310)
cn.com.vister.imeth W/System.err:     at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:261)
cn.com.vister.imeth W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
cn.com.vister.imeth W/System.err:     at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
cn.com.vister.imeth W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
cn.com.vister.imeth W/System.err:     at android.os.Looper.loop(Looper.java:145)
cn.com.vister.imeth W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5942)
cn.com.vister.imeth W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
cn.com.vister.imeth W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
cn.com.vister.imeth W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
cn.com.vister.imeth W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
cn.com.vister.imeth A/chromium: [FATAL:jni_android.cc(295)] Check failed: false. Please include Java exception stack in crash report
cn.com.vister.imeth W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
cn.com.vister.imeth W/google-breakpad: Chrome build fingerprint:
cn.com.vister.imeth W/google-breakpad: 1.0.7
cn.com.vister.imeth W/google-breakpad: 1
cn.com.vister.imeth W/google-breakpad: 92675e2e-3e24-4fdd-9bc9-d979deace950
cn.com.vister.imeth W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
cn.com.vister.imeth E/chromium: ### WebView Version 43.0.2357.121 (code 2357121)
cn.com.vister.imeth A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 3433 (com.pansky.sgss)
```
### Solution

package com.facebook.react.views.webview.ReactWebViewManager$ReactWebViewClient
```
@Override
    public boolean shouldOverrideUrlLoading(WebView view, String url) {
        if (url.startsWith("http://") || url.startsWith("https://") || url.startsWith("file://")) {
          return false;
        } else {
          try{
             Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(url));
             intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
             view.getContext().startActivity(intent);
             return true;
           } catch (Exception e) {
             return false
           }
        }
    }
```

### Additional Information

* React Native version: [0.34.1]
* Platform: [Android]
* Operating System: [MacOS]

**Comment by BROUDING** [comment]
I get the same error even I have the payment application....

**Comment by sriraman** [comment]
I'm also facing the same crash even in React Native 0.42 + Android. Did anyone find a workaround for this crash?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-webview-use-protocol-start-other-app

**Comment by PratikG9** [comment]
Hello,
Facing the same issue with react-native 0.42.3
Does anybody got the solution for this?
Here is the reference [https://github.com/wkh237/react-native-azure-ad/issues/39](link)
