### ISSUE TITLE
Android 4.4 Crash before application start

### ISSUE THREAD

**Issue by doubleDdai** [facebook/react-native#10971]
### Description
In Dev mode, app crashes before app start.
### Reproduction
Log:

```
Process: com.baidu.mbaby, PID: 5886
E/AndroidRuntime( 5886): java.lang.IllegalStateException: closed
E/AndroidRuntime( 5886):    at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:374)
E/AndroidRuntime( 5886):    at okio.Buffer.writeAll(Buffer.java:993)
E/AndroidRuntime( 5886):    at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:106)
E/AndroidRuntime( 5886):    at okhttp3.ResponseBody.bytes(ResponseBody.java:128)
E/AndroidRuntime( 5886):    at okhttp3.ResponseBody.string(ResponseBody.java:154)
E/AndroidRuntime( 5886):    at com.facebook.react.devsupport.DevServerHelper$3.onResponse(DevServerHelper.java:302)
E/AndroidRuntime( 5886):    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
E/AndroidRuntime( 5886):    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
E/AndroidRuntime( 5886):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 5886):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 5886):    at java.lang.Thread.run(Thread.java:841)
```

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow
