### ISSUE TITLE
[WINDOWS 10] - issue when trying to run react-native init AwesomeProject

### ISSUE THREAD

**Issue by sundayhd** [facebook/react-native#11018]
### Description

I want to start React Native for the first time.

### Additional Information

* React Native version: 0.37
* Platform: both
* Operating System: Windows 10

### Error Log

C:\>react-native init AwesomeProject
This will walk you through creating a new React Native project in C:\AwesomeProject
Installing react-native from npm...
Consider installing yarn to make this faster: https://yarnpkg.com
Setting up new React Native app in C:\AwesomeProject
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:683:19)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at WriteStream.stream.write (C:\AwesomeProject\node_modules\ansi\lib\newlines.js:36:21)
    at Console.warn (console.js:51:16)
    at process.on (internal/process/warning.js:21:17)
    at emitOne (events.js:96:13)

**Comment by sundayhd** [comment]
the problam was related to nodejs
https://github.com/nodejs/node/issues/9542

I just reinstall nodejs with msi (from the offical site)
and it seems to fix the problam.
