### ISSUE TITLE
StringDecoder ENOS

### ISSUE THREAD

**Issue by anassaeed72** [facebook/react-native#11050]
### Description

While running react-native start and then react-native run-android, the app does not work and instead the following error shows on the server and then it quits.

ERROR  watch /home/anas/Documents/React_Native/Test/node_modules/react-native/node_modules/yeoman-generator/node_modules/through2/node_modules/readable-stream/node_modules/string_decoder ENOSPC
{"code":"ENOSPC","errno":"ENOSPC","syscall":"watch /home/anas/Documents/React_Native/Test/node_modules/react-native/node_modules/yeoman-generator/node_modules/through2/node_modules/readable-stream/node_modules/string_decoder","filename":"/home/anas/Documents/React_Native/Test/node_modules/react-native/node_modules/yeoman-generator/node_modules/through2/node_modules/readable-stream/node_modules/string_decoder"}
Error: watch /home/anas/Documents/React_Native/Test/node_modules/react-native/node_modules/yeoman-generator/node_modules/through2/node_modules/readable-stream/node_modules/string_decoder ENOSPC
    at exports._errnoException (util.js:911:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at NodeWatcher.watchdir (/home/anas/Documents/React_Native/Test/node_modules/react-native/node_modules/sane/src/node_watcher.js:144:20)
    at Walker.<anonymous> (/home/anas/Documents/React_Native/Test/node_modules/react-native/node_modules/sane/src/node_watcher.js:353:12)
    at emitTwo (events.js:87:13)
    at Walker.emit (events.js:172:7)
    at /home/anas/Documents/React_Native/Test/node_modules/react-native/node_modules/sane/node_modules/walker/lib/walker.js:69:16
    at go$readdir$cb (/home/anas/Documents/React_Native/Test/node_modules/react-native/node_modules/graceful-fs/graceful-fs.js:149:14)

* Platform: Android
* Operating System: Linux Ubuntu

**Comment by mkonicek** [comment]
Looks like you're out of disk space?
http://stackoverflow.com/questions/22475849/node-js-error-enospc
