### ISSUE TITLE
Crash on startup for Android Jellybean (API 18)

### ISSUE THREAD

**Issue by vafada** [facebook/react-native#11092]
### Description

Our app crashes on startup when using API 18 (Jellybean). This is the stacktrace:

`
android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
	at android.content.res.Resources.loadDrawable(Resources.java:2091)
	at android.content.res.Resources.getDrawable(Resources.java:695)
	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:200)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:723)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
	at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
	at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:71)
	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:301)
	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:231)
	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:227)
	at com.facebook.react.views.toolbar.ReactToolbar.<init>(ReactToolbar.java:136)
	at com.facebook.react.views.toolbar.ReactToolbarManager.createViewInstance(ReactToolbarManager.java:50)
	at com.facebook.react.views.toolbar.ReactToolbarManager.createViewInstance(ReactToolbarManager.java:39)
	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:46)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:211)
	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
	at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:776)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:829)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:44)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:868)
	at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
	at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:747)
	at android.view.Choreographer.doCallbacks(Choreographer.java:562)
	at android.view.Choreographer.doFrame(Choreographer.java:531)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5103)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:897)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:837)
`

We **don't** have this issue with API 23

### Reproduction

Just starting the app causes the issue.

### Solution

Stackoverflow has some solutions http://stackoverflow.com/questions/34417843/how-to-use-vector-drawables-in-android-api-lower-21

But adding

`defaultConfig { vectorDrawables.useSupportLibrary = true}`

causes the build to fail with the following error:

`
Could not find property 'vectorDrawables' on ProductFlavor_Decorated{name=main, dimension=null, minSdkVersion=ApiVersionImpl{mApiLevel=16, mCodename='null'}, targetSdkVersion=ApiVersionImpl{mApiLevel=22, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptNdkModeEnabled=null, versionCode=72, versionName=2.0.2, applicationId=com.truebill, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}}.
`

### Additional Information

* React Native version: 0.36.0
* Platform: Android
* Operating System: Linux

**Comment by vafada** [comment]
related to 10711

**Comment by mkonicek** [comment]
Does your app use any 3rd-party native modules? What is `abc_vector_test.xml`?

The StackOverflow questions answers this:
http://stackoverflow.com/questions/34417843/how-to-use-vector-drawables-in-android-api-lower-21

Try replacing classpath 'com.android.tools.build:gradle:1.3.1' to classpath 'com.android.tools.build:gradle:2.1.2 in android/build.gradle.

We should really upgrade to a more recent version of Gradle.
