### ISSUE TITLE
android.os.DeadObjectException

### ISSUE THREAD

**Issue by smuyyh** [facebook/react-native#11180]
Hello, when I tried to start service in CustomModule/MainActivity/MainApplication, then my app crash with a android.os.DeadObjectException exception.

### Log
```
11-29 09:27:48.740 30331-30594/? W/InputDispatcher: Attempted to unregister already unregistered input channel '421008d0 com.awesomeproject/com.awesomeproject.MainActivity (server)'
11-29 09:27:48.740 30331-30594/? I/WindowState: WIN DEATH: Window{421008d0 u0 com.awesomeproject/com.awesomeproject.MainActivity}
11-29 09:27:48.750 30331-31474/? W/ActivityManager: Exception thrown during pause
                                                    android.os.DeadObjectException
                                                        at android.os.BinderProxy.transact(Native Method)
                                                        at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:660)
                                                        at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:769)
                                                        at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2513)
                                                        at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2387)
                                                        at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2039)
                                                        at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:9762)
                                                        at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:9655)
                                                        at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10300)
                                                        at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9851)
                                                        at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
11-29 09:27:48.770 30331-30571/? I/ActivityManager: Process com.awesomeproject (pid 31387) has died.
11-29 09:27:48.820 30331-30586/? W/InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 31387 uid 10056
11-29 09:27:48.830 30508-30520/? W/Binder: Caught a RuntimeException from the binder stub implementation.
                                           java.lang.NullPointerException
                                               at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
                                               at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
                                               at android.os.Binder.execTransact(Binder.java:404)
                                               at dalvik.system.NativeStart.run(Native Method)
```

### Additional Information

* React Native version: [com.facebook.react:react-native:+]
* Platform: [Android]
* Operating System: [Windows]

**Comment by wicharek** [comment]
Hi. Did you figure out what was wrong?
