### ISSUE TITLE
android app build successfully ,but launch crashed

### ISSUE THREAD

**Issue by rocwangv** [facebook/react-native#11258]
### Description
 FATAL EXCEPTION: mqt_js
                                                                       Process: com.aaaai.bbbbb, PID: 7023
                                                                       java.lang.RuntimeException: com.facebook.react.devsupport.JSException: TypeError: undefined is not an object (evaluating '_configProvider.remoteModuleConfig') (index.android.bundle:3552)
                                                                           at com.facebook.react.bridge.DefaultNativeModuleCallExceptionHandler.handleException(DefaultNativeModuleCallExceptionHandler.java:24)
                                                                           at com.facebook.react.devsupport.DisabledDevSupportManager.handleException(DisabledDevSupportManager.java:153)
                                                                           at com.facebook.react.cxxbridge.CatalystInstanceImpl.onNativeException(CatalystInstanceImpl.java:393)
                                                                           at com.facebook.react.cxxbridge.CatalystInstanceImpl.access$400(CatalystInstanceImpl.java:50)
                                                                           at com.facebook.react.cxxbridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:409)
                                                                           at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:33)
                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                           at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                           at java.lang.Thread.run(Thread.java:818)
                                                                        Caused by: com.facebook.react.devsupport.JSException: TypeError: undefined is not an object (evaluating '_configProvider.remoteModuleConfig') (index.android.bundle:3552)
                                                                           at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                           at android.os.Looper.loop(Looper.java:135) 
                                                                           at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                                           at java.lang.Thread.run(Thread.java:818) 
                                                                        Caused by: com.facebook.jni.CppException: TypeError: undefined is not an object (evaluating '_configProvider.remoteModuleConfig') (index.android.bundle:3552)
                                                                           at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                           at android.os.Handler.handleCallback(Handler.java:739) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                           at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                           at android.os.Looper.loop(Looper.java:135) 
                                                                           at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                                           at java.lang.Thread.run(Thread.java:818) 
12-02 10:01:49.634 7023-7108/com.aaaaaa.bbbbbb I/Process: Sending signal. PID: 7023 SIG: 9
### Reproduction

run `react-native run-android`  in android phone Redmi Note 3 - 5.1.1'
build successfully and launches crashed

### Additional Information

*  "react": "^15.3.1",
*  "react-native": "^0.37.0",
* Platform:just android,ios works well
* Operating System: MacOS

**Comment by rocwangv** [comment]
when I upgrade my gradle to version 2.2 , everything works well for now . Close it .
