### ISSUE TITLE
react-native-git-upgrade  this.adapter.log.create is not a function error

### ISSUE THREAD

**Issue by teyou** [facebook/react-native#11290]
### Description
I have read this article: http://facebook.github.io/react-native/blog/2016/12/05/easy-upgrades-processed-by-git.html

I tried to run react-native-git-upgrade command in my project

these are the error log

```
git-upgrade info Read project descriptors
git-upgrade info Check declared version
git-upgrade info Check matching versions
git-upgrade info Check React peer dependency
git-upgrade info Check Git installation
git-upgrade info Get react-native version from NPM registry
git-upgrade info Check new version
git-upgrade info Setup temporary working directory
git-upgrade info Configure Git environment
git-upgrade info Init Git repository
git-upgrade info Add all files to commit
git-upgrade info Commit pristine sources
git-upgrade info Create a tag before updating sources
git-upgrade info Generate old version template
/Users/teyou/Documents/Development/Git/rn-app/node_modules/yeoman-generator/lib/util/conflicter.js:108
    this.adapter.log.create(rfilepath);
                     ^

TypeError: this.adapter.log.create is not a function
    at Conflicter.collision (/Users/teyou/Documents/Development/Git/rn-app/node_modules/yeoman-generator/lib/util/conflicter.js:108:22)
    at /Users/teyou/Documents/Development/Git/rn-app/node_modules/yeoman-generator/lib/util/conflicter.js:77:12
    at /Users/teyou/Documents/Development/Git/rn-app/node_modules/async/lib/async.js:718:13
    at iterate (/Users/teyou/Documents/Development/Git/rn-app/node_modules/async/lib/async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (/Users/teyou/Documents/Development/Git/rn-app/node_modules/async/lib/async.js:281:9)
    at _parallel (/Users/teyou/Documents/Development/Git/rn-app/node_modules/async/lib/async.js:717:9)
    at Object.async.series (/Users/teyou/Documents/Development/Git/rn-app/node_modules/async/lib/async.js:739:9)
    at Conflicter.resolve (/Users/teyou/Documents/Development/Git/rn-app/node_modules/yeoman-generator/lib/util/conflicter.js:86:9)
    at DestroyableTransform._transform (/Users/teyou/Documents/Development/Git/rn-app/node_modules/yeoman-generator/lib/base.js:815:21)
    at DestroyableTransform.Transform._read (/Users/teyou/Documents/Development/Git/rn-app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)

```
### Additional Information

* React Native version: 0.34.1
* Platform: none
* Operating System: MacOS

**Comment by ncuillery** [comment]
Hi @teyou,

The blog post has been published by mistake 😄 

The version you got (0.0.1) is an unfinished version I published a month ago to prevent name squatting. I encountered this error during the development, [it's already fixed](https://github.com/facebook/react-native/blob/master/react-native-git-upgrade/cliEntry.js#L177).

Please wait for the official announcement and the first release tomorrow.

**Comment by teyou** [comment]
cool, thanks!
it always been a painful upgrading procees. 
looking forward on the release :)

**Comment by mkonicek** [comment]
Thanks for replying @ncuillery! Closing as resolved.
