### ISSUE TITLE
MAC OS Sierra: com.github.facebook.watchman.plist for write 

### ISSUE THREAD

**Issue by anil826** [facebook/react-native#11312]
### Description
I am not able to create a sample project in my MAC OS Sierra please help me.

All I just follow the react-native documentation but it's look like the .plist file is not created and I don't know why I have folder /Users/anilyadav/Library/LaunchAgents on same path but didn't get the com.github.facebook.watchman.plist because the file is not there.

## Error on` npm start`

```
> AwesomeProject@0.0.1 start /Users/anilyadav/AwesomeProject
> node node_modules/react-native/local-cli/cli.js start

(node:2437) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
Scanning 711 folders for symlinks in /Users/anilyadav/AwesomeProject/node_modules (339ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/anilyadav/AwesomeProject 

[Hot Module Replacement] Server listening on /hot

React packager ready.

2016-12-05T23:36:00,866: [cli] Failed to open /Users/anilyadav/Library/LaunchAgents/com.github.facebook.watchman.plist for write: Not a directory

2016-12-05T23:36:00,866: [cli] Failed to open /Users/anilyadav/Library/LaunchAgents/com.github.facebook.watchman.plist for write: Not a directory

Watchman:  watchman--no-pretty get-sockname returned with exit code null 2016-12-05T23:36:00,866: [cli] Failed to open /Users/anilyadav/Library/LaunchAgents/com.github.facebook.watchman.plist for write: Not a directory

 ERROR  watchman--no-pretty get-sockname returned with exit code null 2016-12-05T23:36:00,866: [cli] Failed to open /Users/anilyadav/Library/LaunchAgents/com.github.facebook.watchman.plist for write: Not a directory

Error: watchman--no-pretty get-sockname returned with exit code null 2016-12-05T23:36:00,866: [cli] Failed to open /Users/anilyadav/Library/LaunchAgents/com.github.facebook.watchman.plist for write: Not a directory

    at ChildProcess.<anonymous> (/Users/anilyadav/AwesomeProject/node_modules/fb-watchman/index.js:198:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.2.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! AwesomeProject@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 11
npm ERR! 
npm ERR! Failed at the AwesomeProject@0.0.1 start script 'node node_modules/react-native/local-cli/cli.js start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the AwesomeProject package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/react-native/local-cli/cli.js start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs AwesomeProject
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls AwesomeProject
npm ERR! There is likely additional logging output above.
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.2.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! path npm-debug.log.2423895624
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.2423895624'
npm ERR!  { Error: EACCES: permission denied, open 'npm-debug.log.2423895624'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.2423895624' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/anilyadav/AwesomeProject/npm-debug.log

```

### Additional Information

* React Native version: [latest --HEAD]
* Platform: [ iOS]
* Operating System: [ MacOS]

**Comment by zhangdw** [comment]
install watchman。
install the latest build from github:
brew install --HEAD watchman

**Comment by anil826** [comment]
Thanks but the problem was different after debugging i found that *mysql.plist file is pointing to  `LaunchAgents` folder so I remove the linking between  *mysql.plist file and ` LaunchAgents` folder and move the *mysql.plist `LaunchAgents` and errors are goes away.

**Comment by PCGeekBrain** [comment]
Where was this file? I am having this same issue with just creating a project with `react-native init Project` followed by `react-native run-ios`
