### ISSUE TITLE
error:react-native run-android

### ISSUE THREAD

**Issue by ifgyong** [facebook/react-native#11320]
S server already running.
Running /Users/Jerry/Library/Android/sdk/platform-tools/adb -s emulator-5556 reverse tcp:8081 tcp:8081
Building and installing the app on the device (cd android && ./gradlew installDebug...

Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: /Users/Jerry/.gradle/wrapper/dists/gradle-2.14.1-all/8bnwg5hd3w55iofp58khbp6yv/gradle-2.14.1-all.zip
       	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
       	at org.gradle.wrapper.Install.createDist(Install.java:46)
       	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
       	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment.
Go to https://facebook.github.io/react-native/docs/getting-started.html
and check the Android tab for setup instructions.``

**Comment by TyrealGray** [comment]
> set up your Android development environment.
Go to https://facebook.github.io/react-native/docs/getting-started.html
and check the Android tab for setup instructions.``

The output already told you.

**Comment by mkonicek** [comment]
> Timeout reached waiting for exclusive access to file

Can you Google this message? Might be a permissions problem? Try creating a fresh RN app using 'react-native init MyApp' in your home directory.

**Comment by shubhamtakode** [comment]
Problem is with permissions of folder.
Please run following command 
`sudo chown -R $USER ~/.gradle`
