### ISSUE TITLE
Cannot find module 'invariant'

### ISSUE THREAD

**Issue by DavidE2000** [facebook/react-native#11324]
I upgraded to React Native 39 for 38 and now I cannot build to android because of this error "Cannot find module invariant"

Here is the full error

`
$ react-native run-android
module.js:328
    throw err;
    ^

Error: Cannot find module 'invariant'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:/xampp/htdocs/project/node_modules/react-native/packager/react-packager/src/node-haste/Module.js:18:19)
    at Module._compile (module.js:410:26)
    at loader (C:\xampp\htdocs\project\node_modules\react-native\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\xampp\htdocs\project\node_modules\react-native\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
`

I rimraf the old react native folder and npm installed this.

**Comment by frankyLHJ** [comment]
"npm install npm@latest -g" is work for me.
