### ISSUE TITLE
react-native-git-upgrade fails on npm v2

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#11330]
The `react-native-git-upgrade` tool is failing to upgrade one of my projects with the following error:

```
Error: The specified version of React Native undefined doesn't exist.
Re-run the react-native-git-upgrade command with an existing version,
for example: "react-native-git-upgrade 0.38.0",
or without arguments to upgrade to the latest: "react-native-git-upgrade".
```

This occurs when running `react-native-git-upgrade` by itself, as well as when a version is specified (e.g. `react-native-git-upgrade 0.39.0`).

I noticed that npm is not returning a JSON response to [`npm view react-native@latest peerDependencies.react version --json`](https://github.com/facebook/react-native/blob/59dd2133cb2bc8292ae932b77337c2a4ba35645b/react-native-git-upgrade/cliEntry.js#L261) as the CLI seems to expect:

```
$ npm view react-native@latest peerDependencies.react version --json
peerDependencies.react = "~15.4.0-rc.4"
version = "0.39.0"
```

This occurred while using node v4.4.7 and npm v2.15.8. Switching to node v6.5.0 and npm v3.10.3 resolved the issue.

## Environment

react-native-git-upgrade: 0.2.3
react-native: 0.34.1
react: 15.3.2
npm: 2.15.8
node: 4.4.7
os: macOS Sierra 10.12.1
react-native latest as of this writing: 0.39.0

## Logs

`react-native-git-upgrade` output:

```
$ react-native-git-upgrade
git-upgrade info Check for updates 
git-upgrade WARN Check for latest version failed Invalid Version: null
Cannot parse yarn version: Using globally installed version of Yarn
0.17.8
git-upgrade info Read package.json files 
git-upgrade info Check declared version 
git-upgrade info Check matching versions 
git-upgrade info Check React peer dependency 
git-upgrade info Check that Git is installed 
git-upgrade info Get information from NPM registry 
git-upgrade ERR! An error occurred during upgrade: 
git-upgrade ERR! Error: The specified version of React Native undefined doesn't exist.
Re-run the react-native-git-upgrade command with an existing version,
for example: "react-native-git-upgrade 0.38.0",
or without arguments to upgrade to the latest: "react-native-git-upgrade".
    at parseInformationJsonOutput (/Users/hramos/.nvm/versions/node/v4.4.7/lib/node_modules/react-native-git-upgrade/cliEntry.js:109:11)
    at Object.<anonymous> (/Users/hramos/.nvm/versions/node/v4.4.7/lib/node_modules/react-native-git-upgrade/cliEntry.js:263:48)
    at next (native)
    at step (/Users/hramos/.nvm/versions/node/v4.4.7/lib/node_modules/react-native-git-upgrade/cliEntry.js:182:191)
    at /Users/hramos/.nvm/versions/node/v4.4.7/lib/node_modules/react-native-git-upgrade/cliEntry.js:182:361
    at tryCallOne (/Users/hramos/.nvm/versions/node/v4.4.7/lib/node_modules/react-native-git-upgrade/node_modules/promise/lib/core.js:37:12)
    at /Users/hramos/.nvm/versions/node/v4.4.7/lib/node_modules/react-native-git-upgrade/node_modules/promise/lib/core.js:123:15
    at flush (/Users/hramos/.nvm/versions/node/v4.4.7/lib/node_modules/react-native-git-upgrade/node_modules/promise/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13) 
```

**Comment by hramos** [comment]
cc @mkonicek @ncuillery

**Comment by hojberg** [comment]
I am seeing this usse also
