### ISSUE TITLE
Error!! react-native init HelloWorld

### ISSUE THREAD

**Issue by miho7031** [facebook/react-native#11383]
Yesterday OK
Today Error

$ react-native init HelloWorld
This will walk you through creating a new React Native project in /Users/miho7031/gonworks/HelloWorld
Using yarn v0.17.10
Installing react-native...
/Users/miho7031/gonworks/HelloWorld/node_modules/react-native/local-cli/util/Config.js:43
  cwd: string,
     ^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at loader (/Users/miho7031/gonworks/HelloWorld/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/miho7031/gonworks/HelloWorld/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/miho7031/gonworks/HelloWorld/node_modules/react-native/local-cli/cliEntry.js:13:16)

Why?

**Comment by Micjoyce** [comment]
I also get this Error, today.
`node_modules/react-native/local-cli/util/Config.js:43
  cwd: string,
     ^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at loader (/Users/michaelxu/seerline-dev/clchatApp/SeerChatApp/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/michaelxu/seerline-dev/clchatApp/SeerChatApp/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/michaelxu/seerline-dev/clchatApp/SeerChatApp/node_modules/react-native/local-cli/cliEntry.js:13:16)
`
how to fixed this.

**Comment by liuhong1happy** [comment]
+1

**Comment by miho7031** [comment]
Now!! Ok!!

$ react-native init HelloWorld2
This will walk you through creating a new React Native project in /Users/miho7031/gonworks/HelloWorld2
Using yarn v0.17.10
Installing react-native...
Setting up new React Native app in /Users/miho7031/gonworks/HelloWorld2
Installing React...
Installing Jest...
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global marked@0.3.6 should be installed with -g
To run your app on iOS:
   react-native run-ios
   - or -
   Open ios/HelloWorld2.xcodeproj in Xcode
   Hit the Run button
To run your app on Android:
   Have an Android emulator running (quickest way to get started), or a device connected
   react-native run-android

:(

**Comment by miho7031** [comment]
react-native init HelloWorld > Error
react-native init HelloWorld2 > No Error

:(

**Comment by miho7031** [comment]
Now!!

react-native init HelloWorld > No Error
react-native init HelloWorld2 > No Error

:(
