### ISSUE TITLE
Unable to build app to phone

### ISSUE THREAD

**Issue by gastonche** [facebook/react-native#11476]
### Description
react-native run-android keeps giving errors when trying to build to mobile device. when i run the command all i get is the following error:
 react-native run-android
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Unzipping /home/webshinobis/.gradle/wrapper/dists/gradle-2.4-all/6r4uqcc6ovnq6ac6s0txzcpc0/gradle-2.4-all.zip to /home/webshinobis/.gradle/wrapper/dists/gradle-2.4-all/6r4uqcc6ovnq6ac6s0txzcpc0
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.gradle.wrapper.Install.unzip(Install.java:159)
	at org.gradle.wrapper.Install.access$500(Install.java:26)
	at org.gradle.wrapper.Install$1.call(Install.java:69)
	at org.gradle.wrapper.Install$1.call(Install.java:46)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:46)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

### Reproduction
run react-native run-android

* Platform:Android
* Operating System: Linux

**Comment by sunnyraz** [comment]
I have same issue .Is someone there to help us ??

**Comment by gastonche** [comment]
Oh, i found the solution to that.  the zip in ~/.gradle/wrapper/dists/gradle-2.4-all/6r4uqcc6ovnq6ac6s0txzcpc0/gradle-2.4-all.zip was corrupt in my case. that file has to be deleted for the project to download a correct one.

**Comment by sunnyraz** [comment]
Yeah it work
thank you @gastonche
