### ISSUE TITLE
Android App crashed at startup.No Activity found to handle Intent { act=android.settings.action.MANAGE_OVERLAY_PERMISSION }

### ISSUE THREAD

**Issue by Yangzhilang** [facebook/react-native#11525]
Just run the template on my android device, but the emulator is OK.
react-native-cli: 1.3.0
react-native: 0.38.1

Here is the crash log.
```
12-17 15:45:40.520 26382-26382/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.rntest, PID: 26382
Theme: themes:{}
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rntest/com.rntest.MainActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.action.MANAGE_OVERLAY_PERMISSION }
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2536)
at android.app.ActivityThread.access$900(ActivityThread.java:159)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5504)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.action.MANAGE_OVERLAY_PERMISSION }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1812)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1516)
at android.app.Activity.startActivityForResult(Activity.java:3963)
at android.app.Activity.startActivityForResult(Activity.java:3924)
at android.app.Activity.startActivity(Activity.java:4247)
at android.app.Activity.startActivity(Activity.java:4215)
at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:84)
at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54)
at android.app.Activity.performCreate(Activity.java:6285)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2536) 
at android.app.ActivityThread.access$900(ActivityThread.java:159) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:148) 
at android.app.ActivityThread.main(ActivityThread.java:5504) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
    12-17 15:45:40.521 4055-5389/? W/ActivityManager:   Force finishing activity com.rntest/.MainActivity
```

**Comment by Yangzhilang** [comment]
I found that this could be some android rom issue, maybe the rom offered by the Mobile phone manufacturers lost the user grant UI.And I go to  Settings and grant some permission, the App runs well.

**Comment by Rcrosp** [comment]
how to resolve this issue
