### ISSUE TITLE
[Android]very dangerous thread safe issue

### ISSUE THREAD

**Issue by littlesome** [facebook/react-native#11524]
I got some IllegalViewOperationException from:
UIImplementation.updateView
UIImplementation.setChildren ...

and I add some log to debug this:
```Java
  protected final void removeShadowNode(ReactShadowNode nodeToRemove) {
    mNativeViewHierarchyOptimizer.handleRemoveNode(nodeToRemove);
    // add log here
    Log.e("Remove", "tag:" + nodeToRemove.getReactTag());
    mShadowNodeRegistry.removeNode(nodeToRemove.getReactTag());
    for (int i = nodeToRemove.getChildCount() - 1; i >= 0; i--) {
      removeShadowNode(nodeToRemove.getChildAt(i));
    }
    nodeToRemove.removeAllChildren();
  }

  public void registerRootView(
      SizeMonitoringFrameLayout rootView,
      int tag,
      int width,
      int height,
      int sizeFlexibility,
      ThemedReactContext context) {
    final ReactShadowNode rootCSSNode = createRootShadowNode();
    rootCSSNode.setReactTag(tag);
    rootCSSNode.setThemedContext(context);
    rootCSSNode.setStyleWidth(width);
    rootCSSNode.setStyleHeight(height);
    rootCSSNode.setSizeFlexibility(sizeFlexibility);

    // add log here
    Log.e("Add", "root " + tag);
    mShadowNodeRegistry.addRootNode(rootCSSNode);

    // register it within NativeViewHierarchyManager
    mOperationsQueue.addRootView(tag, rootView, context);
  }

  public void createView(int tag, String className, int rootViewTag, ReadableMap props) {
    ReactShadowNode cssNode = createShadowNode(className);
    ReactShadowNode rootNode = mShadowNodeRegistry.getNode(rootViewTag);
    cssNode.setReactTag(tag);
    cssNode.setViewClassName(className);
    cssNode.setRootNode(rootNode);
    cssNode.setThemedContext(rootNode.getThemedContext());

    // add log here
    Log.e("Add", "view:" + tag);
    mShadowNodeRegistry.addNode(cssNode);

    ReactStylesDiffMap styles = null;
    if (props != null) {
      styles = new ReactStylesDiffMap(props);
      cssNode.updateProperties(styles);
    }

    handleCreateView(cssNode, rootViewTag, styles);
  }

```

here is the logcat output:

```
12-17 19:19:13.774 30602-30753/com.GF.platform E/Add: view:974
12-17 19:19:13.774 30602-30753/com.GF.platform E/Add: view:975
12-17 19:19:13.784 30602-30753/com.GF.platform E/Add: view:976
12-17 19:19:14.245 30602-30753/com.GF.platform E/Add: view:977
12-17 19:19:14.255 30602-30753/com.GF.platform E/Add: view:978
12-17 19:19:14.275 30602-30753/com.GF.platform E/Remove: tag:958
12-17 19:19:14.275 30602-30753/com.GF.platform E/Remove: tag:959
12-17 19:19:14.275 30602-30753/com.GF.platform E/Remove: tag:962
12-17 19:19:14.275 30602-30753/com.GF.platform E/Remove: tag:963
12-17 19:19:14.275 30602-30753/com.GF.platform E/Remove: tag:960
12-17 19:19:14.325 30602-30753/com.GF.platform E/Add: view:979
12-17 19:19:14.345 30602-30753/com.GF.platform E/Add: view:980
12-17 19:19:14.365 30602-30753/com.GF.platform E/Remove: tag:969
12-17 19:19:14.365 30602-30753/com.GF.platform E/Remove: tag:970
12-17 19:19:14.365 30602-30753/com.GF.platform E/Remove: tag:973
12-17 19:19:14.365 30602-30753/com.GF.platform E/Remove: tag:974
12-17 19:19:14.365 30602-30753/com.GF.platform E/Remove: tag:972
12-17 19:19:14.535 30602-30602/com.GF.platform E/Add: root 221
12-17 19:19:14.555 30602-30602/com.GF.platform E/Add: root 231
12-17 19:19:14.555 30602-30602/com.GF.platform E/Add: root 241
12-17 19:19:14.555 30602-30602/com.GF.platform E/Add: root 251
12-17 19:19:14.555 30602-30602/com.GF.platform E/Add: root 261
12-17 19:19:14.565 30602-30602/com.GF.platform E/Add: root 271
12-17 19:19:14.565 30602-30602/com.GF.platform E/Add: root 281
12-17 19:19:14.565 30602-30602/com.GF.platform E/Add: root 291
12-17 19:19:14.565 30602-30602/com.GF.platform E/Add: root 301
12-17 19:19:14.565 30602-30602/com.GF.platform E/Add: root 311
12-17 19:19:14.565 30602-30602/com.GF.platform E/Add: root 321
12-17 19:19:14.575 30602-30602/com.GF.platform E/Add: root 331
12-17 19:19:14.575 30602-30602/com.GF.platform E/Add: root 341
12-17 19:19:14.575 30602-30602/com.GF.platform E/Add: root 351
12-17 19:19:14.575 30602-30753/com.GF.platform E/unknown:React: Exception in native call
                                                                com.facebook.react.uimanager.IllegalViewOperationException: Trying to update non-existent view with tag 980
                                                                    at com.facebook.react.uimanager.UIImplementation.updateView(UIImplementation.java:196)
                                                                    at com.facebook.react.uimanager.UIManagerModule.updateView(UIManagerModule.java:216)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:322)
                                                                    at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
                                                                    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                    at java.lang.Thread.run(Thread.java:818)


```

See view with tag 980 is already added to the registry through thread:30753 (the message queue thread)
and then some root views are created and registered through thread:30602 (the main thread)
this breaks the registry. In the source of ShadowNodeRegistry there is a TODO

```Java
  public void addRootNode(ReactShadowNode node) {
    // TODO(6242243): This should be asserted... but UIManagerModule is
    // thread-unsafe and calls this on the wrong thread.
    //mThreadAsserter.assertNow();
    int tag = node.getReactTag();
    mTagsToCSSNodes.put(tag, node);
    mRootTags.put(tag, true);
  }
```

I think this is an known issue, and this may be very dangerous, when this will be fixed? 

### Additional Information

* React Native version: 0.33.0
* Platform: Android
* Operating System: Windows

**Comment by hramos** [comment]
We're cutting down on the number of outstanding issues, in order to allow us to focus. I'm closing this issue because it has been open for over 60 days with no activity. If you think it should still be opened let us know why. PRs are always welcome.
