### ISSUE TITLE
Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by phantomk** [facebook/react-native#11630]
### Description

Cannot read property 'on' of undefined
TypeError: Cannot read property 'on' of undefined
    at Client.connect (/Users/kio/Code/AwesomeProject/node_modules/.1.9.0@fb-watchman/index.js:184:14)
    at Client.command (/Users/kio/Code/AwesomeProject/node_modules/.1.9.0@fb-watchman/index.js:228:12)
    at Client.capabilityCheck (/Users/kio/Code/AwesomeProject/node_modules/.1.9.0@fb-watchman/index.js:290:8)
    at WatchmanWatcher.init (/Users/kio/Code/AwesomeProject/node_modules/.1.4.1@sane/src/watchman_watcher.js:173:15)
    at new WatchmanWatcher (/Users/kio/Code/AwesomeProject/node_modules/.1.4.1@sane/src/watchman_watcher.js:40:8)
    at createWatcher (/Users/kio/Code/AwesomeProject/node_modules/.17.0.3@jest-haste-map/build/index.js:536:23)
    at Array.map (native)
    at HasteMap._watch (/Users/kio/Code/AwesomeProject/node_modules/.17.0.3@jest-haste-map/build/index.js:654:44)
    at _buildPromise._buildFileMap.then.then.hasteMap (/Users/kio/Code/AwesomeProject/node_modules/.17.0.3@jest-haste-map/build/index.js:250:21)
    at process._tickCallback (internal/process/next_tick.js:103:7)
~

### Additional Information

* React Native version: 0.39
* Platform: iOS
* Operating System: MacOS

**Comment by phantomk** [comment]
I have solve this problem, just update npm
