### ISSUE TITLE
Android should use okhttp:3.5.0

### ISSUE THREAD

**Issue by el** [facebook/react-native#11680]
### Description

okhttp:3.4.1 has a bug makes working with http/2 + SSL unstable

### Reproduction

Have an http/2 + SSL setup and try fetch or XMLHttpRequest API (frisbee or axios) to make an http request, sometimes it hangs at connection

### Solution

update okhttp to 3.5.0 and compile react-native again

### Additional Information

* React Native version: 0.40
* Platform: Android
* Operating System: MacOS

**Comment by el-iz** [comment]
```
12-30 19:36:24.581 6266-6563/? E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                 Process: express.whatson, PID: 6266
                                                 java.lang.IllegalStateException: closed
                                                     at okio.RealBufferedSink.write(RealBufferedSink.java:39)
                                                     at okio.ForwardingSink.write(ForwardingSink.java:35)
                                                     at com.facebook.react.modules.network.ProgressRequestBody$1.write(ProgressRequestBody.java:58)
                                                     at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
                                                     at com.facebook.react.modules.network.ProgressRequestBody.writeTo(ProgressRequestBody.java:48)
                                                     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:47)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                                                     at okhttp3.RealCall.access$100(RealCall.java:33)
                                                     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
                                                     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                     at java.lang.Thread.run(Thread.java:818)

```

**Comment by el-iz** [comment]
Unfortunately I couldn't update okhttp to 3.5.0 because the latest version of okhttp-ws is 3.4.2
updating to 3.4.2 did not have any affects.

**Comment by theseansy** [comment]
I'm also experiencing issues being able to use okhttp 3.5.0 wth react native

When I run the app I get
```
FATAL EXCEPTION: AsyncTask #7
                                                                        Process: com.app.runapp, PID: 26999
                                                                        java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                            at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                            at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                         Caused by: java.lang.NoClassDefFoundError: com.facebook.react.devsupport.JSPackagerWebSocketClient
                                                                            at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:122)
                                                                            at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:119)
                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                            at java.lang.Thread.run(Thread.java:818) 
```

My gradle:
```
    compile 'com.squareup.okhttp3:okhttp:3.5.0'
    compile 'com.squareup.okhttp3:okhttp-urlconnection:3.5.0'
```

**Comment by el-iz** [comment]
I have made necessary changes and made a pull request https://github.com/facebook/react-native/pull/11698

https://github.com/el-iz/react-native

**Comment by cinder92** [comment]
any fix for this? i'm having same issue as @theseansy

**Comment by theseansy** [comment]
@cinder92 - I'm following this PR now: https://github.com/facebook/react-native/issues/11835

**Comment by cinder92** [comment]
idk why but i'm still getting same issue with RN 0.42.3 :(

**Comment by theseansy** [comment]
The [PR hasn't been merged](https://github.com/facebook/react-native/pull/11835)

**Comment by fab1an** [comment]
Developing with react-native is just depressing.

**Comment by ouyangdxq** [comment]
@el https://github.com/el/react-native,I try it,no work

**Comment by stephenlaughton** [comment]
anyone having any luck with this? i am getting the same error as @theseansy although we are using okhttp3.4.1 in our android app.

**Comment by simonracz** [comment]
I think this can be closed now. On the master branch RN has okhttp 3.8.0.

https://github.com/facebook/react-native/commit/93a1d592d61b229d3dafe57d1590d286312cc0bf

**Comment by githubdoramon** [comment]
But when the master branch will be released??? I tried to use it but was unsucessful

**Comment by Alonexx** [comment]
On master branch, okhttp was reverted to 3.6.0. Anybody can tell me why making this change? OkHttp 3.8.0 release recovers a bug gracefully on Huawei devices running Android 7.0 which can cause app crash . Can master branch work with OkHttp 3.8.0 well ?

**Comment by simonracz** [comment]
Here is the commit. Can't find an explanation. https://github.com/facebook/react-native/commit/3af9be52b272b767b480ed4f989ddfd6146a56f8

**Comment by goodmind** [comment]
Any progress here?

**Comment by fencex** [comment]
I have tried okhttp:3.8.0, but didn't succeed。

I do not need to know the POST progress， so I solved the problem by modify this java file:

```
node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java
```

**`NOTICE`** In order for these changes to take effect，you need to [Building React Native from source](http://facebook.github.io/react-native/docs/android-building-from-source.html)

here is the code `NetworkingModule.java` 
```
       // 1.  comment those lines comes after     
} else if (data.hasKey(REQUEST_BODY_KEY_FORMDATA)) {
        ......
//      requestBuilder.method(
//        method,
//        RequestBodyUtil.createProgressRequest(
//          multipartBuilder.build(),
//          new ProgressListener() {
//        long last = System.nanoTime();
//
//        @Override
//        public void onProgress(long bytesWritten, long contentLength, boolean done) {
//          long now = System.nanoTime();
//          if (done || shouldDispatch(now, last)) {
//            ResponseUtil.onDataSend(eventEmitter, requestId, bytesWritten, contentLength);
//            last = now;
//          }
//        }
//      }));

      // 2. and add the following 2 lines
      RequestBody requestBody = multipartBuilder.build();
      requestBuilder.post(requestBody).build();

```

**Comment by derakhshanfar** [comment]
same issue for me any solution?

**Comment by derakhshanfar** [comment]
@simonracz thanks but how can i upgrade react-native that refer to specific commit or tag when it is not release on NPM?

**Comment by oximer** [comment]
Any news on this issue?

**Comment by DevilSoulcz** [comment]
so...  How to solve this problem?? ('·ω·`)

**Comment by 1k2k** [comment]
Still seeing this in RN v0.53

**Comment by Ambujesh** [comment]
Has someone solved this issue? I am still facing it :(

**Comment by Ambujesh** [comment]
RN v0.51
Okhttp 3.6.0
OS Linux
