### ISSUE TITLE
Watchman was not found in PATH

### ISSUE THREAD

**Issue by junaidahmed93** [facebook/react-native#11801]
Hello everyone,
I am trying to run react-native app since last week but i am unable to run it.
Already created an issue but that has been closed by saying "try to google for it"

I don't know what going wrong with `react-native start`

Always getting 
```
Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
 ERROR  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
{"code":"ENOENT","errno":"ENOENT","syscall":"spawn watchman","path":"watchman","spawnargs":["--no-pretty","get-sockname"]}
Error: Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I am unable to understand if the process is depended on watchman then why there is no discussion in official document with regards to start process
I haven't found any tutorial that installed watchman before starting.
Not even found the way to install watchman except `npm install watchman`

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by ajaysaini-sgvu** [comment]
@junaidahmed93 How did you resolve this issue ?

**Comment by junaidahmed93** [comment]
Just remove watchman
npm uninstall -g watchman
And Never install that again :)

**Comment by DanielMSchmidt** [comment]
@junaidahmed93 I think you need to install it with homebrew
