### ISSUE TITLE
Android ListView IndexOutOfBoundsException

### ISSUE THREAD

**Issue by messense** [facebook/react-native#11825]
### Description

Scroll down a complex `ListView` on Android randomly crash caused by `java.lang.IndexOutOfBoundsException`

```
01-11 11:04:53.362  1502  1502 E AndroidRuntime: FATAL EXCEPTION: main
01-11 11:04:53.362  1502  1502 E AndroidRuntime: Process: com.riskstorm.riskstorm.debug, PID: 1502
01-11 11:04:53.362  1502  1502 E AndroidRuntime: java.lang.IndexOutOfBoundsException: index=14 count=13
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.addInArray(ViewGroup.java:4559)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.addViewInner(ViewGroup.java:4476)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.addViewInLayout(ViewGroup.java:4430)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at com.facebook.react.views.view.ReactViewGroup.updateSubviewClipStatus(ReactViewGroup.java:312)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at com.facebook.react.views.view.ReactViewGroup.updateClippingToRect(ReactViewGroup.java:285)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at com.facebook.react.views.view.ReactViewGroup.updateClippingRect(ReactViewGroup.java:278)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at com.facebook.react.views.scroll.ReactScrollView.updateClippingRect(ReactScrollView.java:220)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at com.facebook.react.views.scroll.ReactScrollView.onScrollChanged(ReactScrollView.java:152)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.View.scrollTo(View.java:13272)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.widget.ScrollView.onOverScrolled(ScrollView.java:822)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at com.facebook.react.views.scroll.ReactScrollView.onOverScrolled(ReactScrollView.java:342)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.View.overScrollBy(View.java:20915)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.widget.ScrollView.onTouchEvent(ScrollView.java:682)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at com.facebook.react.views.scroll.ReactScrollView.onTouchEvent(ReactScrollView.java:192)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:9939)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2663)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:411)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:67)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:373)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:10159)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4434)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3995)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4052)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6210)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6184)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6145)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6313)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6284)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6336)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:613)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
01-11 11:04:53.362  1502  1502 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

### Solution

Set `ListView`'s `removeClippedSubviews` to `false` can prevent the crash, but may causing other display problems.

### Additional Information

* React Native version: 0.39
* Platform: Android only, iOS works fine
* Operating System: macOS

**Comment by freiserg** [comment]
I have the same crash.

**Comment by vuongp** [comment]
Hi I'm having te same issue:
```
Fatal Exception: java.lang.IndexOutOfBoundsException: index=14 count=12
       at android.view.ViewGroup.addInArray(ViewGroup.java:4755)
       at android.view.ViewGroup.addViewInner(ViewGroup.java:4676)
       at android.view.ViewGroup.addView(ViewGroup.java:4490)
       at android.view.ViewGroup.addView(ViewGroup.java:4431)
       at com.facebook.react.views.view.ReactViewManager.addView(ReactViewManager.java:203)
       at com.facebook.react.views.view.ReactViewManager.addView(ReactViewManager.java:37)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:394)
       at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:175)
       at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:782)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:829)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:44)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:868)
       at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
       at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:918)
       at android.view.Choreographer.doCallbacks(Choreographer.java:695)
       at android.view.Choreographer.doFrame(Choreographer.java:628)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by radko93** [comment]
Probably this is related? https://github.com/facebook/react-native/issues/3042

**Comment by mienaikoe** [comment]
Having the same issue with react-native version 0.40.0

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.
