### ISSUE TITLE
Because gestures to crash

### ISSUE THREAD

**Issue by 1097616819** [facebook/react-native#11826]
### 
Operating System： MacOS
The react native problem in android: use ScrollView,listView,TouchableOpacity,and so on As long as the associated with gestures run in huawei 7.0 system, with slide from the edge to the middle finger, sliding a few times more, crash will occur. Then I went to run f8app appear the same problem!
### 
### 
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Tried to get non-existent cookie
    at com.facebook.react.uimanager.events.TouchEventCoalescingKeyHelper.getCoalescingKey(TouchEventCoalescingKeyHelper.java:75)
    at com.facebook.react.uimanager.events.TouchEvent.init(TouchEvent.java:89)
    at com.facebook.react.uimanager.events.TouchEvent.obtain(TouchEvent.java:45)
    at com.facebook.react.uimanager.JSTouchDispatcher.handleTouchEvent(JSTouchDispatcher.java:114)
    at com.facebook.react.ReactRootView.dispatchJSTouchEvent(ReactRootView.java:155)
    at com.facebook.react.ReactRootView.onInterceptTouchEvent(ReactRootView.java:127)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2212)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
    at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
    at android.app.Activity.dispatchTouchEvent(Activity.java:3213)
    at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
    at android.view.View.dispatchPointerEvent(View.java:10228)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4845)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4705)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4238)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4291)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4257)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4384)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4265)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4441)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4238)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4291)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4257)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4265)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4238)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6665)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6639)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6600)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6792)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
    at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
    at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:181)
    at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6739)
    at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6820)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:923)
    at android.view.Choreographer.doCallbacks(Choreographer.java:735)
    at android.view.Choreographer.doFrame(Choreographer.java:661)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:909)
    at android.os.Handler.handleCallback(Handler.java:755)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:156)
    at android.app.ActivityThread.main(ActivityThread.java:6524)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
###

**Comment by sidbusy** [comment]
#11927

**Comment by hilkeheremans** [comment]
Same here, following device info (extract from bugsnag):
```
apiLevel 24
brand HUAWEI
freeDisk 26933690368
freeMemory 450364592
manufacturer HUAWEI
model EVA-L09
orientationportrait
osBuild EVA-L09C432B378
osName android
osVersion 7.0
screenDensity 3
screenResolution1794x1080
```
