### ISSUE TITLE
 Caused by: java.lang.IllegalAccessError: tried to access method android.support.v4.net.ConnectivityManagerCompat.<init>:(Lcom/facebook/react/bridge/ReactApplicationContext;)V from class com.facebook.react.modules.netinfo.NetInfoModule

### ISSUE THREAD

**Issue by APLK** [facebook/react-native#11859]
![default](https://cloud.githubusercontent.com/assets/24518328/21879761/d1eff958-d8d5-11e6-9197-0cb2a84f603f.png)

![default](https://cloud.githubusercontent.com/assets/24518328/21879779/f3562eaa-d8d5-11e6-80a5-79fcfa62d76a.png)

compile 'com.android.support:design:23.2.1'
compile 'com.android.support:support-v13:23.2.1'
compile 'com.facebook.react:react-native:+'

please help me!How to solve the problem?I wann't to reduced my support version,thanks!

**Comment by alexblack** [comment]
I get this too, using React Native `0.41.2`

```
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                  Process: com.aadhk.woinvoice, PID: 2862
                  java.lang.RuntimeException: An error occurred while executing doInBackground()
                      at android.os.AsyncTask$3.done(AsyncTask.java:309)
                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                      at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                      at java.lang.Thread.run(Thread.java:818)
                   Caused by: java.lang.IllegalAccessError: Method 'void android.support.v4.net.ConnectivityManagerCompat.<init>()' is inaccessible to class 'com.facebook.react.modules.netinfo.NetInfoModule' (declaration of 'com.facebook.react.modules.netinfo.NetInfoModule' appears in /data/data/com.aadhk.woinvoice/files/instant-run/dex/slice-com.facebook.react-react-native-0.20.1_dd7e8361611dc34898c750d11b5ece4d3990a0aa-classes.dex)
                      at com.facebook.react.modules.netinfo.NetInfoModule.<init>(NetInfoModule.java:55)
                      at com.facebook.react.shell.MainReactPackage.createNativeModules(MainReactPackage.java:67)
                      at com.facebook.react.ReactInstanceManagerImpl.processPackage(ReactInstanceManagerImpl.java:793)
                      at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:730)
                      at com.facebook.react.ReactInstanceManagerImpl.access$600(ReactInstanceManagerImpl.java:91)
                      at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:184)
                      at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:169)
                      at android.os.AsyncTask$2.call(AsyncTask.java:295)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                      at java.lang.Thread.run(Thread.java:818) 
```

Using `com.android.support:appcompat-v7:23.3.0`

**Comment by APLK** [comment]
use compile 'com.facebook.react:react-native:+',make sure the build package is up to date,then in your activity to extends ReactActivity,in your Application to implement ReactApplication.

**Comment by alexblack** [comment]
I solved my problem, the problem was that I was using `com.facebook.react:react-native:+` which pulled in version 21 from the web, instead of 0.41.2 locally due to a path error.  I changed it to specify 0.41.2 specifically, then it failed to find it, enabling me to discover and fix the path issue.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/caused-by-javalangillegalaccesserror-tried-to-access-method-androidsupportv4netc
