### ISSUE TITLE
Packager fails w/ error 500

### ISSUE THREAD

**Issue by csotiriou** [facebook/react-native#11965]
Hello,

upon running npm update, we encountered the following issue when the packager runs (both iOS and Android).

The following happens w/ both npm and yarn.

```
node_modules/react-native-mock/build/plugins/Platform.js: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "StringLiteral"
    at Object.validate (/Users/soulstorm/Documents/Programming/test_project/test_project/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/Users/soulstorm/Documents/Programming/test_project/test_project/node_modules/babel-types/lib/index.js:511:9)
    at NodePath._replaceWith (/Users/soulstorm/Documents/Programming/test_project/test_project/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath.replaceWith (/Users/soulstorm/Documents/Programming/test_project/test_project/node_modules/babel-traverse/lib/path/replacement.js:160:8)
    at PluginPass.MemberExpression (/Users/soulstorm/Documents/Programming/test_project/test_project/node_modules/react-native/packager/react-packager/src/JSTransformer/worker/inline.js:120:14)
    at newFn (/Users/soulstorm/Documents/Programming/test_project/test_project/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/soulstorm/Documents/Programming/test_project/test_project/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/soulstorm/Documents/Programming/test_project/test_project/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/soulstorm/Documents/Programming/test_project/test_project/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/soulstorm/Documents/Programming/test_project/test_project/node_modules/babel-traverse/lib/context.js:150:16)
```

for the sake of completion, this is my package.json file

```
{
  "name": "Test Project",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "rm -rf ./test_database; jest",
    "build-realm": "./bin/build-realm.sh"
  },
  "jest": {
    "preset": "jest-react-native",
    "setupFiles": [
      "./__tests__setup/setup.jest.js"
    ]
  },
  "dependencies": {
    "accounting": "^0.4.1",
    "autobind-decorator": "^1.3.4",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-remove-console": "^6.8.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "bluebird": "^3.4.6",
    "glob": "^7.1.1",
    "install": "^0.8.2",
    "lodash": "^4.16.4",
    "mobx": "^2.6.0",
    "mobx-react": "^4.0.2",
    "moment": "^2.17.1",
    "npm": "^3.10.9",
    "react": "15.4.1",
    "react-native": "0.40.0",
    "react-native-android-permissions": "0.0.7",
    "react-native-animatable": "^0.6.1",
    "react-native-camera": "^1.0.0-alpha1",
    "react-native-dialogs": "0.0.19",
    "react-native-extended-stylesheet": "^0.3.0",
    "react-native-prompt": "^1.0.0",
    "react-native-radio-buttons": "^0.13.0",
    "realm": "^0.15.4",
    "whatwg-fetch": "^1.0.0"
  },
  "devDependencies": {
    "babel-jest": "^16.0.0",
    "babel-preset-react-native": "^1.9.0",
    "jest": "^18.1.0",
    "jest-react-native": "test",
    "react-native-mock": "^0.2.7",
    "react-native-spinkit": "^0.1.3",
    "react-test-renderer": "^15.3.2"
  }
}

```

This is my .babelrc file

```
{
  "presets": [
    "react-native",
    "react-native-stage-0/decorator-support"
  ],
  "ignore": false,
  "env": {
    "production": {
      "plugins": [
        "transform-decorators-legacy",
        "transform-remove-console"
      ]
    },
    "development": {
      "plugins": [
        "transform-decorators-legacy"
      ]
    }
  }
}
```

And this is my yarn.lock file, showing what packages and versions have been resolved.
[yarn.lock.zip](https://github.com/facebook/react-native/files/714173/yarn.lock.zip)

Can anyone point us in the right direction?

Thank you

**Comment by hramos** [comment]
We're cutting down on the number of outstanding issues, in order to allow us to focus. I'm closing this issue because it has been open for over 60 days with no activity. If you think it should still be opened let us know why. PRs are always welcome.
