### ISSUE TITLE
Live/Hot reload ENAMETOOLONG?

### ISSUE THREAD

**Issue by butchmarshall** [facebook/react-native#12005]
Created a fresh react-native project (0.40.0), enabled live & hot reloading.  When I change a file it crashes the package manager server.

I've have another project running 0.38.0 that runs successfully.

butch@work-desktop:~/workspace/snow_trails$ sudo npm start
[sudo] password for butch: 

> snow_trails@0.0.1 start /home/butch/workspace/snow_trails
> node node_modules/react-native/local-cli/cli.js start

Scanning 573 folders for symlinks in /home/butch/workspace/snow_trails/node_modules (254ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /home/butch/workspace/snow_trails 

[01/20/2017, 08:35:14] <START> Initializing Packager
[01/20/2017, 08:35:15]         HMR Server listening on /hot

React packager ready.

[01/20/2017, 08:35:58] <START> Building Haste Map
[01/20/2017, 08:35:58] <END>   Building Haste Map (74ms)
[01/20/2017, 08:35:58] <END>   Initializing Packager (44389ms)
[01/20/2017, 08:39:15] <START> Requesting bundle
                               bundle_url: /index.android.bundle?platform=android&dev=true&hot=true&minify=false
[01/20/2017, 08:39:15] <START> Transforming files
transformed 575/575 (100%)
[01/20/2017, 08:39:17] <END>   Transforming files (1379ms)
[01/20/2017, 08:39:17] <END>   Requesting bundle (1505ms)
                               bundle_url: /index.android.bundle?platform=android&dev=true&hot=true&minify=false
[01/20/2017, 08:39:18]         HMR Client connected
[01/20/2017, 08:42:35]         HMR Server detected file change
[01/20/2017, 08:42:36]         HMR Server detected file change
[01/20/2017, 08:42:36]         HMR Server detected file change
[01/20/2017, 08:42:36]         HMR Server detected file change                                                                                                
[01/20/2017, 08:42:36]         HMR Server detected file change                                                                                                
[01/20/2017, 08:42:36]         HMR Server detected file change                                                                                                
[01/20/2017, 08:42:37]         HMR Server detected file change                                                                                                
[01/20/2017, 08:42:37]         HMR Server detected file change                                                                                                
[01/20/2017, 08:42:37]         HMR Server detected file change                                                                                                
[01/20/2017, 08:42:37]         HMR Server detected file change                                                                                                
[01/20/2017, 08:42:37]         HMR Server detected file change                                                                                                
[01/20/2017, 08:42:37]         HMR Server detected file change                                                                                                
[01/20/2017, 08:42:37]         HMR Server detected file change                                                                                                
[01/20/2017, 08:42:38]         HMR Server detected file change                                                                                                
[01/20/2017, 08:42:38]         HMR Server detected file change                                                                                                
[01/20/2017, 08:42:38]         HMR Server detected file change                                                                                                
[01/20/2017, 08:42:38]         HMR Server detected file change                                                                                                
[01/20/2017, 08:42:38]         HMR Server detected file change                                                                                                
[01/20/2017, 08:42:38]         HMR Server detected file change                                                                                                
[01/20/2017, 08:42:39]         HMR Server detected file change                                                                                                
 ERROR  ENAMETOOLONG: name too long, open '/home/butch/workspace/snow_trails/react-native-packager-cache-ea307a65/28/8e29e610b655f76447d259d59546c64702e9b11eaf52da65bb0e2ed7fdad12025adb82ab4987c8ade0d9eaa9edf758d6792873d77cfdb8a531d992e9package.json.meta.1585722273'                                                  
{"errno":-36,"code":"ENAMETOOLONG","syscall":"open","path":"/home/butch/workspace/snow_trails/react-native-packager-cache-ea307a65/28/8e29e610b655f76447d259d59546c64702e9b11eaf52da65bb0e2ed7fdad12025adb82ab4987c8ade0d9eaa9edf758d6792873d77cfdb8a531d992e9package.json.meta.1585722273"}                                
Error: ENAMETOOLONG: name too long, open '/home/butch/workspace/snow_trails/react-native-packager-cache-ea307a65/28/8e29e610b655f76447d259d59546c64702e9b11eaf52da65bb0e2ed7fdad12025adb82ab4987c8ade0d9eaa9edf758d6792873d77cfdb8a531d992e9package.json.meta.1585722273'                                                   
    at Error (native)                                                                                                                                         
    at Object.fs.openSync (fs.js:640:18)                                                                                                                      
    at Object.fs.writeFileSync (fs.js:1333:33)                                                                                                                
    at writeFileSync (/home/butch/workspace/snow_trails/node_modules/write-file-atomic/index.js:92:8)                                                         
    at Object.writeSync (/home/butch/workspace/snow_trails/node_modules/react-native/packager/react-packager/src/lib/TransformCache.js:131:3)                 
    at _getTransformedCode (/home/butch/workspace/snow_trails/node_modules/react-native/packager/react-packager/src/node-haste/Module.js:299:22)              
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by a1gemmel** [comment]
I'm having this same issue on Linux, also with react-native 0.40.0.  Have you happened to find a solution?

**Comment by lucaspenney** [comment]
I have the same issue after upgrading to react-native 0.420-rc.3. from 39. Haven't been able to find a way around it - just have to restart the packager whenever it crashes, which seems to be after a couple of successful hot reloads, not necessarily right away.

**Comment by butchmarshall** [comment]
I found it eventually went away.

Not sure if deleting all the cache (cd android && ./gradlew clean) and running package manager w/ react-native start --reset-cache helped at all?

**Comment by georgesdoe** [comment]
I am still having this issue, even after deleting all the cache. Any suggestions?

**Comment by a1gemmel** [comment]
My issue also went away by itself. Too many intermediate steps to pin down what fixed it though. I did downgrade to 0.38 for a while, do a couple of `rm -rf node modules`, and butchmarshall's suggestion may have helped.

**Comment by butchmarshall** [comment]
It's intermittent.  The issue came back for me.  No solution... I just don't run hot-reload/live-reload anymore (sadly).

**Comment by cyclops24** [comment]
I have same issue. Anyone know any solution?

**Comment by cyclops24** [comment]
I can't use hot-reload/live-reload after upgrade my react native 😞

**Comment by cyclops24** [comment]
@butchmarshall , @a1gemmel , @lucaspenney , @georgesdoe  Any news about this?

**Comment by a1gemmel** [comment]
I did find a workaround. I pivoted my career path and became a Java developer.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
