### ISSUE TITLE
Error report - react-native local-cli/cli.js

### ISSUE THREAD

**Issue by ORESoftware** [facebook/react-native#12143]
got this error after running npm start in my project

`npm start =>     "start": "node node_modules/react-native/local-cli/cli.js start",`

I got an error and the process crashed, it looks like it happened after a some node_module get moved or deleted:

```
> AwesomeProject@0.0.1 start /home/oleg/ReactNativeProjects/AwesomeProject
> node node_modules/react-native/local-cli/cli.js start

Scanning 591 folders for symlinks in /home/oleg/ReactNativeProjects/AwesomeProject/node_modules (5ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /home/oleg/ReactNativeProjects/AwesomeProject 

[01/31/2017, 21:38:11] <START> Initializing Packager
[01/31/2017, 21:38:11]         HMR Server listening on /hot

React packager ready.

[01/31/2017, 21:38:15] <START> Building Haste Map
[01/31/2017, 21:38:15] <END>   Building Haste Map (91ms)
[01/31/2017, 21:38:15] <END>   Initializing Packager (3701ms)
[01/31/2017, 21:40:28] <START> Requesting bundle
                               bundle_url: /index.android.bundle?platform=android&dev=true&hot=false&minify=false
[01/31/2017, 21:40:28] <START> Transforming files
transformed 401/401 (100%)
[01/31/2017, 21:40:34] <END>   Transforming files (6233ms)
[01/31/2017, 21:40:34] <END>   Requesting bundle (6424ms)
                               bundle_url: /index.android.bundle?platform=android&dev=true&hot=false&minify=false
 ERROR  watch /home/oleg/ReactNativeProjects/AwesomeProject/node_modules/.util.DELETE ENOENT
{"code":"ENOENT","errno":"ENOENT","syscall":"watch /home/oleg/ReactNativeProjects/AwesomeProject/node_modules/.util.DELETE","filename":"/home/oleg/ReactNativeProjects/AwesomeProject/node_modules/.util.DELETE"}
Error: watch /home/oleg/ReactNativeProjects/AwesomeProject/node_modules/.util.DELETE ENOENT
    at exports._errnoException (util.js:870:11)
    at FSWatcher.start (fs.js:1234:19)
    at Object.fs.watch (fs.js:1262:11)
    at NodeWatcher.watchdir (/home/oleg/ReactNativeProjects/AwesomeProject/node_modules/sane/src/node_watcher.js:144:20)
    at NodeWatcher.<anonymous> (/home/oleg/ReactNativeProjects/AwesomeProject/node_modules/sane/src/node_watcher.js:278:14)
    at /home/oleg/ReactNativeProjects/AwesomeProject/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:82:15)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.

npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! AwesomeProject@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 11
npm ERR! 
npm ERR! Failed at the AwesomeProject@0.0.1 start script 'node node_modules/react-native/local-cli/cli.js start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the AwesomeProject package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/react-native/local-cli/cli.js start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs AwesomeProject
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls AwesomeProject
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/oleg/ReactNativeProjects/AwesomeProject/npm-debug.log
```

### Additional Information

React native v = 0.40.0
Android
On Ubuntu 16.04

**Comment by hramos** [comment]
Hey, thanks for reporting this issue! It seems there has been no activity on this issue for the past three months. I'll close the issue so it doesn't stay open indefinitely. 

If you or someone else is interested in continuing the discussion, please do not hesitate to open a new issue with all the details specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md). 

If you or someone else has a fix for this, please do send a pull request.

Thanks!
