### ISSUE TITLE
RN 0.41 Includes a bundle file which causes a node haste conflict

### ISSUE THREAD

**Issue by lelandrichardson** [facebook/react-native#12183]
to: @grabbou 

### Description

One cannot successfully run the packager in RN 0.41 because there is a bundle file which causes a node haste conflict (duplicate module). It looks like there is a webpack built bundle which includes a `@providesModule` declaration in it which is causing the packager to get confused.

```
Loading dependency graph...
React packager ready.

Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: deprecated
  Paths: ./lottie-react-native/node_modules/react-native/local-cli/server/middleware/heapCapture/bundle.js collides with ./lottie-react-native/node_modules/react-native/Libraries/Renderer/src/shared/utils/deprecated.js

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: deprecated
  Paths: ./lottie-react-native/node_modules/react-native/local-cli/server/middleware/heapCapture/bundle.js collides with ./lottie-react-native/node_modules/react-native/Libraries/Renderer/src/shared/utils/deprecated.js

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (./lottie-react-native/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at module.getName.then.name (./lottie-react-native/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:119:31)

```

It looks like the offending file is `$(package_root)/local-cli/server/middleware/heapCapture/bundle.js`

### Reproduction

```
react-native init
npm start
```

### Solution

My guess is this got npm published by accident.

### Additional Information

* React Native version: 0.41
* Platform: both
* Operating System:MacOS

**Comment by lelandrichardson** [comment]
(Related: https://github.com/airbnb/lottie-react-native/issues/29)

**Comment by grabbou** [comment]
Interesting. Could've happened on the CI? Locally all was working fine as the general release guidelines assume we actually run & test it.

**Comment by grabbou** [comment]
I’ll double check locally. However, that shouldn’t happen as:
1) CI checks the app so packager has to start
2) I’ve checked it manually and was able to trigger dev menu and all these things

**Comment by grabbou** [comment]
```
➔ react-native start 
Scanning 557 folders for symlinks in /private/tmp/RNTestProject/node_modules (3ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /private/tmp/RNTestProject 

Loading dependency graph...
React packager ready.

Loading dependency graph, done.
Bundling `index.ios.js`
  Transforming modules  100.0% (392/392), done.
Bundling `index.ios.js`
  No module changed.
```

**Comment by raffij** [comment]
My duplications are because React is included in the pod as well as within my react-native project.

**Comment by lelandrichardson** [comment]
@grabbou This appears to still be in `0.41.0-rc.1`. Is this expected? cc @mkonicek

**Comment by IljaDaderko** [comment]
I believe I am experiencing similar issue via #12196

**Comment by lelandrichardson** [comment]
Reopening as I think the issue persists since it was gitignored and not npmignored

**Comment by IljaDaderko** [comment]
@lambdapioneer @mkonicek still getting following error on 0.41.1 :/

```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: jsc-heap-capture
  Paths: /Users/ilja/Documents/repositories/testProject/node_modules/react-native/local-cli/server/middleware/heapCapture/package.json collides with /Users/ilja/Documents/repositories/testProject/node_modules/react-router-native/node_modules/react-native/local-cli/server/middleware/heapCapture/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: jsc-heap-capture
  Paths: /Users/ilja/Documents/repositories/testProject/node_modules/react-native/local-cli/server/middleware/heapCapture/package.json collides with /Users/ilja/Documents/repositories/testProject/node_modules/react-router-native/node_modules/react-native/local-cli/server/middleware/heapCapture/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/ilja/Documents/repositories/testProject/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at p.getName.then.name (/Users/ilja/Documents/repositories/skimitar/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:133:31)
```

Literary all I do is init new project, replace package.json file with my one that has few additional packages (double checked that all initial dependencies are correct i.e. v 0.41.1), run `yarn` and `react-native run-ios` and get this in the end
