### ISSUE TITLE
Cannot run react native packed bundle on node.js

### ISSUE THREAD

**Issue by riteshsangwan** [facebook/react-native#12258]
### Description

I created a react native application offline bundle. I want to serve this bundle from a node express server. But whenever I try to `require` that bundle in my node application I get following error

```
assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: path must be a string
    at Module.require (module.js:496:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sabertooth/temp/react-bundle-min.js:68635:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

### Reproduction

I created a gist for my bundle file. Follow [this](https://gist.github.com/riteshsangwan/4f249df4043031af48fe48a5beca4440) link.

To reproduce the issue simply run this file as `node react-bundle.js` or require it in another file `const bundle = require('./react-bundle.js');`

### Additional Information

* React Native version: 0.41.2
* Platform: none
* Operating System: MacOS

StackOverflow question can be found [here](http://stackoverflow.com/questions/42090220/nodejs-javascript-execution-environment-for-react-native)

**Comment by hramos** [comment]
We're cutting down on the number of outstanding issues, in order to allow us to focus. I'm closing this issue because it has been open for over 60 days with no activity. If you think it should still be opened let us know why. PRs are always welcome.
