### ISSUE TITLE
Packager doesn't even start due to syntax error

### ISSUE THREAD

**Issue by Mohamed-Abo-El-Soud** [facebook/react-native#12345]
### Description

I updated all my dependencies and ran `react-native run-ios`, and I got this instead:
```
SyntaxError: node_modules/react-native/packager/react-packager/src/Bundler/index.js: Unexpected token, expected ) (45:8)
  43 | 
  44 | export type GetTransformOptions<T> = (
> 45 |   string,
     |         ^
  46 |   Object,
  47 |   string => Promise<Array<string>>,
  48 | ) => T | Promise<T>;
at Parser.pp$5.raise (node_modules/babylon/lib/index.js:4215:13)
at Parser.pp.unexpected (node_modules/babylon/lib/index.js:1599:8)
at Parser.pp.expect (node_modules/babylon/lib/index.js:1587:33)
at Parser.pp$7.flowParsePrimaryType (node_modules/babylon/lib/index.js:4952:14)
at Parser.pp$7.flowParsePostfixType (node_modules/babylon/lib/index.js:5025:38)
at Parser.pp$7.flowParsePrefixType (node_modules/babylon/lib/index.js:5041:17)
at Parser.pp$7.flowParseIntersectionType (node_modules/babylon/lib/index.js:5047:19)
at Parser.pp$7.flowParseUnionType (node_modules/babylon/lib/index.js:5057:19)
at Parser.pp$7.flowParseType (node_modules/babylon/lib/index.js:5068:19)
at Parser.pp$7.flowParseTypeInitialiser (node_modules/babylon/lib/index.js:4393:19)
```

The packager failed to start I guess.

### Reproduction

Update to the latest version of react-native and `run-ios`.

### Solution

umm, it shouldn't syntaxerror on me!

### Additional Information

* React Native version: 0.41.2
* Platform: both?
* Operating System: MacOS

**Comment by rh389** [comment]
What's your `node --version`?

**Comment by Mohamed-Abo-El-Soud** [comment]
v5.12.0

**Comment by rh389** [comment]
I can't reproduce this but looks like you might have a babylon version mismatch locally? See https://github.com/facebook/react-native/issues/11336.

If recreating your `node_modules` doesn't help let me know if you can reproduce with a fresh `react-native init` project, or something you can share.

**Comment by Mohamed-Abo-El-Soud** [comment]
Ya apparently i had to reinstall the `node_modules` repos. Thanks, everything works now. I don't know why it didn't update the affected modules automatically.
