### ISSUE TITLE
crash：undefined is not a function (evaluating '(bridgeConfig.remoteModuleConfig||[]).forEach'

### ISSUE THREAD

**Issue by xiaobeibeinihao** [facebook/react-native#12397]
com.facebook.react.bridge.JSExecutionException: TypeError: undefined is not a function (evaluating '(bridgeConfig.remoteModuleConfig||[]).forEach') (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false:7261)
                                                                            at com.facebook.react.bridge.ReactBridge.loadScriptFromFile(Native Method)
                                                                            at com.facebook.react.bridge.JSBundleLoader$2.loadScript(JSBundleLoader.java:58)
                                                                            at com.facebook.react.bridge.CatalystInstanceImpl$2.call(CatalystInstanceImpl.java:146)
                                                                            at com.facebook.react.bridge.CatalystInstanceImpl$2.call(CatalystInstanceImpl.java:137)
                                                                            at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:73)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                            at android.os.Looper.loop(Looper.java:158)
                                                                            at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:184)
                                                                            at java.lang.Thread.run(Thread.java:818)

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"
    defaultConfig {
        applicationId "tinker.rong360.com.myrn"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    configurations.all { resolutionStrategy.force 'com.google.code.findbugs:jsr305:3.0.0' }

}

dependencies {
    compile "com.facebook.react:react-native:+"// From node_modules.
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.android.support:design:23.1.1'
    testCompile 'junit:junit:4.12'

}`

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    //
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            // All of React Native (JS, Android binaries) is installed from npm
           // url "./node_modules/react-native/android"
           // url "$projectDir/node_modules/react-native/android"
           //url "$rootDir/node_modules/react-native/android"
            url "$rootDir/../node_modules/react-native/android"
        }

        /*flatDir{
            dirs 'libs_aar'
        }*/
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`

when I change the maven from url "$rootDir/../node_modules/react-native/android" to "$rootDir/node_modules/react-native/android" then clean the project ,the React-Native libs can not be founed!
![image](https://cloud.githubusercontent.com/assets/3068075/22967141/3665f6fa-f3a0-11e6-843e-1c6096dc6ddb.png)

**Comment by hramos** [comment]
We're cutting down on the number of outstanding issues, in order to allow us to focus. I'm closing this issue because it has been open for over 60 days with no activity. If you think it should still be opened let us know why. PRs are always welcome.

**Comment by phamios** [comment]
I got the same this error , please let me know how to resolve this problem. thanks so much

**Comment by sasindroid** [comment]
Hi @xiaobeibeinihao @phamios - Any luck on resolving this issue?
