### ISSUE TITLE
Bundle fails on unexpected token when minification is enabled

### ISSUE THREAD

**Issue by aeirola** [facebook/react-native#12473]
### Description

I noticed an issue where the minified bundling fails on syntax errors, even though the development build works flawlessly.

Bundling the invalid code produces the output:

```
Loading dependency graph, done.
/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:4336
  throw err;
  ^

SyntaxError: Unexpected token, expected , (4:0)
    at Parser.pp$5.raise (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:4333:13)
    at Parser.pp.unexpected (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:1705:8)
    at Parser.pp.expect (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:1693:33)
    at Parser.pp$3.parseCallExpressionArguments (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3484:12)
    at Parser.pp$3.parseSubscripts (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3453:31)
    at Parser.pp$3.parseExprSubscripts (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3424:15)
    at Parser.pp$3.parseMaybeUnary (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3394:19)
    at Parser.pp$3.parseExprOps (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3324:19)
    at Parser.pp$3.parseMaybeConditional (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3301:19)
    at Parser.pp$3.parseMaybeAssign (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3264:19)
/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:4336
  throw err;
  ^

SyntaxError: Unexpected token, expected , (4:0)
    at Parser.pp$5.raise (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:4333:13)
    at Parser.pp.unexpected (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:1705:8)
    at Parser.pp.expect (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:1693:33)
    at Parser.pp$3.parseCallExpressionArguments (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3484:12)
    at Parser.pp$3.parseSubscripts (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3453:31)
    at Parser.pp$3.parseExprSubscripts (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3424:15)
    at Parser.pp$3.parseMaybeUnary (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3394:19)
    at Parser.pp$3.parseExprOps (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3324:19)
    at Parser.pp$3.parseMaybeConditional (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3301:19)
    at Parser.pp$3.parseMaybeAssign (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3264:19)
/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:4336
  throw err;
  ^

SyntaxError: Unexpected token, expected , (4:0)
    at Parser.pp$5.raise (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:4333:13)
    at Parser.pp.unexpected (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:1705:8)
    at Parser.pp.expect (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:1693:33)
    at Parser.pp$3.parseCallExpressionArguments (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3484:12)
    at Parser.pp$3.parseSubscripts (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3453:31)
    at Parser.pp$3.parseExprSubscripts (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3424:15)
    at Parser.pp$3.parseMaybeUnary (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3394:19)
    at Parser.pp$3.parseExprOps (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3324:19)
    at Parser.pp$3.parseMaybeConditional (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3301:19)
    at Parser.pp$3.parseMaybeAssign (/Users/aeir/Downloads/TestProject/node_modules/babylon/lib/index.js:3264:19)

Uncaught error in the transformer worker: /Users/aeir/Downloads/TestProject/node_modules/react-native/packager/transformer.js
```

See reproduction section for invalid code example.

### Reproduction

```bash
# Create new project
react-native init TestProject
cd TestProject/

# Create file with non-minifiable syntax
echo "var barWidth = Math.max(
    (
        (parent.width - 60) // Width of single data point on chart [Removing this comment fixes the issue)
        / data.length // Number of data points in chart
    )
    * 0.8, 5);
" > test.js

# Bundle code
node node_modules/react-native/local-cli/cli.js bundle --dev false --entry-file test.js --bundle-output /dev/null --assets-dest /dev/null
```

### Solution

Would need to dig deep into the react native package to figure out what babel plugins or configurations cause this issue.

### Additional Information

* React Native version: 0.41.2
* Platform: both
* Operating System: MacOS

**Comment by andrerfneves** [comment]
^^ can confirm this is happening on my build too

### Information

React Native version: 0.41.2
Platform: both
Operating System: MacOS

**Comment by MikeBlair** [comment]
We are having a similar problem with release builds on 41.2.  

For us, the cause was React Native 41.2 on a fresh npm install is pulling in uglify-js vs 2.8.3.  We shrinkwrapped it back to 2.7.5 and everything is working fine again.

**Comment by jjshammas** [comment]
I am seeing this same issue even on RN 0.43.4.

**Comment by jjshammas** [comment]
Wow—bizarrely enough, this occurred in my app because I used `name` as a variable in JSX. For example:

```
const Thing = ({ name }) => (
  <Text>{name}</Text>
)
```

I changed that code to the following to fix all errors:

```
const Thing = ({ ...props }) => (
  <Text>{props.name}</Text>
)
```

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by MoOx** [comment]
That's a shame to see this issue closed. Currently it's a pain to debug this kind of issues as you don't have any code related to this. And when you have a huge codebase and make some upgrades, you don't any any clue to what bothering babylon....
