### ISSUE TITLE
SoLoader crashes android 4.x running from android studio 

### ISSUE THREAD

**Issue by npomfret** [facebook/react-native#12494]
using RN 0.39 and testing on physical android 4.1 and virtual 4.3 (geny motion sony experia z 4.3 api 18) devices...

My app works fine when I run a production build, but I'm trying to debug something and need to run through android studio.  When I try this on a 4.x device it won't start and crashes when it reaches this line in `MainApplication.java`

`SoLoader.init(this, /* native exopackage */ false);`

I looks like it can't find the `SoLoader` class, I see this:

```
02-21 05:12:47.739 6803-6803/com.pomochat E/dalvikvm: Could not find class 'com.facebook.soloader.DirectorySoSource', referenced from method com.facebook.soloader.SoLoader.initImpl
02-21 05:12:47.739 6803-6803/com.pomochat W/dalvikvm: VFY: unable to resolve new-instance 4646 (Lcom/facebook/soloader/DirectorySoSource;) in Lcom/facebook/soloader/SoLoader;
02-21 05:12:47.739 6803-6803/com.pomochat D/dalvikvm: VFY: replacing opcode 0x22 at 0x0032
02-21 05:12:47.739 6803-6803/com.pomochat E/dalvikvm: Could not find class 'com.facebook.soloader.ExoSoSource', referenced from method com.facebook.soloader.SoLoader.initImpl
02-21 05:12:47.739 6803-6803/com.pomochat W/dalvikvm: VFY: unable to resolve new-instance 4647 (Lcom/facebook/soloader/ExoSoSource;) in Lcom/facebook/soloader/SoLoader;
02-21 05:12:47.739 6803-6803/com.pomochat D/dalvikvm: VFY: replacing opcode 0x22 at 0x004d
02-21 05:12:47.743 6803-6803/com.pomochat E/dalvikvm: Could not find class 'com.facebook.soloader.SoSource[]', referenced from method com.facebook.soloader.SoLoader.initImpl
02-21 05:12:47.743 6803-6803/com.pomochat W/dalvikvm: VFY: unable to resolve new-array 8396 ([Lcom/facebook/soloader/SoSource;) in Lcom/facebook/soloader/SoLoader;
02-21 05:12:47.743 6803-6803/com.pomochat D/dalvikvm: VFY: replacing opcode 0x23 at 0x0067
02-21 05:12:47.743 6803-6803/com.pomochat E/dalvikvm: Could not find class 'com.facebook.soloader.ApkSoSource', referenced from method com.facebook.soloader.SoLoader.initImpl
02-21 05:12:47.743 6803-6803/com.pomochat W/dalvikvm: VFY: unable to resolve new-instance 4645 (Lcom/facebook/soloader/ApkSoSource;) in Lcom/facebook/soloader/SoLoader;
02-21 05:12:47.743 6803-6803/com.pomochat D/dalvikvm: VFY: replacing opcode 0x22 at 0x00a4
02-21 05:12:47.743 6803-6803/com.pomochat E/dalvikvm: Could not find class 'com.facebook.soloader.DirectorySoSource', referenced from method com.facebook.soloader.SoLoader.initImpl
02-21 05:12:47.743 6803-6803/com.pomochat W/dalvikvm: VFY: unable to resolve new-instance 4646 (Lcom/facebook/soloader/DirectorySoSource;) in Lcom/facebook/soloader/SoLoader;
02-21 05:12:47.743 6803-6803/com.pomochat D/dalvikvm: VFY: replacing opcode 0x22 at 0x00cc
02-21 05:12:47.743 6803-6803/com.pomochat E/dalvikvm: Could not find class 'com.facebook.soloader.SoLoader$WrongAbiError', referenced from method com.facebook.soloader.SoLoader.loadLibrary
02-21 05:12:47.743 6803-6803/com.pomochat W/dalvikvm: VFY: unable to resolve new-instance 4649 (Lcom/facebook/soloader/SoLoader$WrongAbiError;) in Lcom/facebook/soloader/SoLoader;
02-21 05:12:47.743 6803-6803/com.pomochat D/dalvikvm: VFY: replacing opcode 0x22 at 0x0042
02-21 05:12:47.747 6803-6803/com.pomochat W/dalvikvm: VFY: array-length on non-array
02-21 05:12:47.747 6803-6803/com.pomochat W/dalvikvm: VFY:  rejecting opcode 0x21 at 0x001e
02-21 05:12:47.747 6803-6803/com.pomochat W/dalvikvm: VFY:  rejected Lcom/facebook/soloader/SoLoader;.loadLibraryBySoName (Ljava/lang/String;I)V
02-21 05:12:47.747 6803-6803/com.pomochat W/dalvikvm: Verifier rejected class Lcom/facebook/soloader/SoLoader;
02-21 05:12:47.747 6803-6803/com.pomochat D/AndroidRuntime: Shutting down VM
02-21 05:12:47.747 6803-6803/com.pomochat W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa4bcf648)
02-21 05:12:47.751 6803-6803/com.pomochat E/AndroidRuntime: FATAL EXCEPTION: main
                                                            java.lang.VerifyError: com/facebook/soloader/SoLoader
                                                                at com.pomochat.MainApplication.onCreate(MainApplication.java:76)
                                                                at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4444)
                                                                at android.app.ActivityThread.access$1300(ActivityThread.java:141)
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
                                                                at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                at android.os.Looper.loop(Looper.java:137)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:525)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                at dalvik.system.NativeStart.main(Native Method)
```

**Comment by brentvatne** [comment]
Can you post this to StackOverflow? Thanks!

**Comment by wj495175289** [comment]
how to resolve this issue? I can not find the commit?  thanks

**Comment by drakmail** [comment]
Have same issue on android 4.4.2

**Comment by fenglu09** [comment]
Have same issue under android 5.0.  How to fix it ?

**Comment by ibmsoft** [comment]
Have same issue on android 4.4.2
