### ISSUE TITLE
You can only use Class Properties when the 'classProperties' plugin is enabled

### ISSUE THREAD

**Issue by huxinmin** [facebook/react-native#12545]
I use react-native init preoject, and it failed and I dont know why:

├─ yallist@2.0.0
├─ yargs-parser@4.2.1
└─ yargs@6.6.0
Done in 338.50s.
G:\TestReact\node_modules\babel-core\lib\transformation\file\index.js:600
      throw err;
      ^

SyntaxError: G:/TestReact/node_modules/react-native/packager/react-packager/src/node-haste/index.js: You can only use Class Properties when the 'classProperties' plugin is enabled. (389:2)
  387 |   }
  388 |
> 389 |   static Cache;
      |   ^
  390 |   static Module;
  391 |   static Polyfill;
  392 |   static getAssetDataFromName;
    at Parser.pp$5.raise (G:\TestReact\node_modules\babylon\lib\index.js:4380:13)
    at Parser.pp$1.parseClassProperty (G:\TestReact\node_modules\babylon\lib\index.js:2508:10)
    at Parser.parseClassProperty (G:\TestReact\node_modules\babylon\lib\index.js:5947:20)
    at Parser.pp$1.parseClassBody (G:\TestReact\node_modules\babylon\lib\index.js:2424:34)
    at Parser.pp$1.parseClass (G:\TestReact\node_modules\babylon\lib\index.js:2361:8)
    at Parser.pp$1.parseStatement (G:\TestReact\node_modules\babylon\lib\index.js:1798:19)
    at Parser.parseStatement (G:\TestReact\node_modules\babylon\lib\index.js:5719:22)
    at Parser.pp$1.parseBlockBody (G:\TestReact\node_modules\babylon\lib\index.js:2223:21)
    at Parser.pp$1.parseTopLevel (G:\TestReact\node_modules\babylon\lib\index.js:1733:8)
    at Parser.parse (G:\TestReact\node_modules\babylon\lib\index.js:1628:17)

**Comment by mcmillan** [comment]
Please see #12542.

**Comment by huxinmin** [comment]
I run this in windows and My nodejs version is v6.9.5,
react-native-cli: 2.0.1

**Comment by brentvatne** [comment]
@huxinmin - as @mcmillan pointed out, #12542 seems to solve this problem
