### ISSUE TITLE
[Packager] Offset is out of bounds

### ISSUE THREAD

**Issue by josebalius** [facebook/react-native#1265]
Hey guys,

Ever since I upgraded to 0.4.2, I keep getting this error from time to time in the middle of development:

```
 ERROR  Offset is out of bounds
Error: Offset is out of bounds
    at Object.fs.read (evalmachine.<anonymous>:462:11)
    at Object.fs.read (/Users/josebalius/Sites/Ravedish/node_modules/react-native/node_modules/graceful-fs/polyfills.js:237:15)
    at /Users/josebalius/Sites/Ravedish/node_modules/react-native/node_modules/image-size/lib/index.js:46:8
    at OpenReq.Req.done (/Users/josebalius/Sites/Ravedish/node_modules/react-native/node_modules/graceful-fs/graceful-fs.js:141:5)
    at OpenReq.done (/Users/josebalius/Sites/Ravedish/node_modules/react-native/node_modules/graceful-fs/graceful-fs.js:61:22)
    at Object.oncomplete (evalmachine.<anonymous>:107:15)
```

Has any ran into this before? Not a big issue but it sucks to have to keep restarting the packager.

**Comment by christopherdro** [comment]
@donghanji Is this still a continuing problem?

**Comment by josebalius** [comment]
@christopherdro sorry for the late reply, I need to upgrade my version of RN to the latest and see if it's still an issue. I'll let you know.

**Comment by josebalius** [comment]
@christopherdro this looks to be fixed for good can't replicate with 0.6.0.

**Comment by ide** [comment]
thanks for the update!

**Comment by christopherdro** [comment]
:+1:

**Comment by weremax** [comment]
I had this error this morning.
Working thru the issue and posting this for anyone else that may get this: in my case this was an image that was empty the file existed and was named but had no content for the system to read. Once the image was fixed reran after closing the process window and everything back to normal.
