### ISSUE TITLE
Android APK crashes after start.

### ISSUE THREAD

**Issue by dmius** [facebook/react-native#12835]
**Description**

Builded release APK file do not started on device (emulator). Same problem with my application and empty project created as described in
https://facebook.github.io/react-native/docs/getting-started.html
After apk started on device I see what application is initialized, but loading of RN part failed, as result all application crashed.
In adb log i see:

```03-09 18:39:47.678  1544  1948 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.postila/.MainActivity (has extras)} from uid 10007 on display 0
03-09 18:39:48.079  1544  1558 W BroadcastQueue: Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.android.launcher3 (pid=1818, uid=10007) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.gms/.icing.proxy.ApplicationLauncherReceiver
03-09 18:39:48.079  1544  1558 W BroadcastQueue: Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.android.launcher3 (pid=1818, uid=10007) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.googlequicksearchbox/com.google.android.search.core.icingsync.ApplicationLaunchReceiver
03-09 18:39:48.101  1544  2158 I ActivityManager: Start proc 4301:io.postila/u0a81 for activity io.postila/.MainActivity
03-09 18:39:48.236  1818  2036 E Surface : getSlotFromBufferLocked: unknown buffer: 0x9cacd470
03-09 18:39:48.286  4301  4301 I CrashlyticsCore: Initializing Crashlytics 2.3.8.97
03-09 18:39:48.343  4301  4315 W GooglePlayServicesUtil: Google Play services out of date.  Requires 10084000 but found 9877470
03-09 18:39:48.608  4301  4320 W art     : Long monitor contention event with owner method=com.google.android.gms.common.zzd$zza com.google.android.gms.common.zzf.zza(android.content.pm.PackageInfo, com.google.android.gms.common.zzd$zza[]) from :4294967295 waiters=1 for 263ms
03-09 18:39:48.935  1544  2083 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=1 for 641ms
03-09 18:39:49.331  1544  2083 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=1 for 396ms
03-09 18:39:49.331  1544  2078 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=2 for 207ms
03-09 18:39:49.332  1544  1556 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=1 for 792ms
03-09 18:39:49.333  1544  1558 W art     : Long monitor contention event with owner method=java.util.List com.android.server.am.ActivityManagerService.getAllStackInfos() from ActivityManagerService.java:8937 waiters=0 for 147ms
03-09 18:39:49.342  1818  1818 I Choreographer: Skipped 66 frames!  The application may be doing too much work on its main thread.
03-09 18:39:49.347  4301  4301 V fb-UnpackingSoSource: locked dso store /data/user/0/io.postila/lib-main
03-09 18:39:49.348  4301  4301 I fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/io.postila/lib-main
03-09 18:39:49.348  4301  4301 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/io.postila/lib-main
03-09 18:39:49.398  4301  4301 I art     : Thread[1,tid=4301,Native,Thread*=0xb4034500,peer=0x741c8f68,"main"] recursive attempt to load library "/data/app/io.postila-1/lib/x86/libfb.so"
03-09 18:39:49.402  4301  4301 D MainActivity: POSTILA >>>>>>>>>>>>>>>>>>>>>> MAIN ACTIVITY ON START !!!!!!!!!!!!!!com.facebook.react.XReactInstanceManagerImpl@7e1d25d
03-09 18:39:49.402  4301  4301 D MainActivity: POSTILA >>>>>>>>>>>>>>>>>>>>>> MAIN ACTIVITY ON RESUME !!!!!!!!!!!!!!com.facebook.react.XReactInstanceManagerImpl@7e1d25d
03-09 18:39:49.450  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTRenderableViewManager
03-09 18:39:49.451  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
03-09 18:39:49.454  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
03-09 18:39:49.454  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
03-09 18:39:49.455  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
03-09 18:39:49.456  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
03-09 18:39:49.457  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
03-09 18:39:49.458  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
03-09 18:39:49.458  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
03-09 18:39:49.459  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
03-09 18:39:49.459  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
03-09 18:39:49.460  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
03-09 18:39:49.463  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
03-09 18:39:49.465  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
03-09 18:39:49.465  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
03-09 18:39:49.469  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
03-09 18:39:49.471  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
03-09 18:39:49.474  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
03-09 18:39:49.475  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
03-09 18:39:49.476  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
03-09 18:39:49.476  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
03-09 18:39:49.477  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
03-09 18:39:49.477  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
03-09 18:39:49.478  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
03-09 18:39:49.478  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
03-09 18:39:49.514  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
03-09 18:39:49.520  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
03-09 18:39:49.520  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
03-09 18:39:49.520  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
03-09 18:39:49.522  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
03-09 18:39:49.525  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
03-09 18:39:49.528  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
03-09 18:39:49.528  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
03-09 18:39:49.529  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.recyclerview.RecyclerViewBackedScrollViewManager
03-09 18:39:49.530  4301  4325 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
03-09 18:39:49.706  1544  1948 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=0 for 302ms
03-09 18:39:49.840  1233  1538 E SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
03-09 18:39:49.841  4301  4331 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
03-09 18:39:50.056  4301  4331 I OpenGLRenderer: Initialized EGL, version 1.4
03-09 18:39:50.120  4301  4327 E ReactNativeJS: Can't find variable: runInContext
03-09 18:39:50.128  4301  4327 E ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
03-09 18:39:50.046  4331  4331 W RenderThread: type=1400 audit(0.0:31): avc: denied { search } for name="graphics" dev="tmpfs" ino=1193 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:graphics_device:s0 tclass=dir permissive=0
03-09 18:39:50.393  4301  4331 D gralloc_ranchu: Emulator without host-side GPU emulation detected.
03-09 18:39:50.444  1544  1563 I ActivityManager: Displayed io.postila/.MainActivity: +2s355ms
03-09 18:39:50.644  4301  4328 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
03-09 18:39:50.644  4301  4328 E AndroidRuntime: Process: io.postila, PID: 4301
03-09 18:39:50.644  4301  4328 E AndroidRuntime: com.facebook.react.common.JavascriptException: Can't find variable: runInContext, stack:
03-09 18:39:50.644  4301  4328 E AndroidRuntime: <unknown>@404:4171
03-09 18:39:50.644  4301  4328 E AndroidRuntime: <unknown>@404:7841
03-09 18:39:50.644  4301  4328 E AndroidRuntime: <unknown>@404:7999
03-09 18:39:50.644  4301  4328 E AndroidRuntime: o@2:517
03-09 18:39:50.644  4301  4328 E AndroidRuntime: e@2:326
03-09 18:39:50.644  4301  4328 E AndroidRuntime: i@2:188
03-09 18:39:50.644  4301  4328 E AndroidRuntime: <unknown>@401:2286
03-09 18:39:50.644  4301  4328 E AndroidRuntime: o@2:517
03-09 18:39:50.644  4301  4328 E AndroidRuntime: e@2:326
03-09 18:39:50.644  4301  4328 E AndroidRuntime: i@2:188
03-09 18:39:50.644  4301  4328 E AndroidRuntime: <unknown>@379:141
03-09 18:39:50.644  4301  4328 E AndroidRuntime: o@2:517
03-09 18:39:50.644  4301  4328 E AndroidRuntime: e@2:326
03-09 18:39:50.644  4301  4328 E AndroidRuntime: i@2:188
03-09 18:39:50.644  4301  4328 E AndroidRuntime: <unknown>@378:229
03-09 18:39:50.644  4301  4328 E AndroidRuntime: o@2:517
03-09 18:39:50.644  4301  4328 E AndroidRuntime: e@2:326
03-09 18:39:50.644  4301  4328 E AndroidRuntime: i@2:188
03-09 18:39:50.644  4301  4328 E AndroidRuntime: <unknown>@12:79
03-09 18:39:50.644  4301  4328 E AndroidRuntime: o@2:517
03-09 18:39:50.644  4301  4328 E AndroidRuntime: e@2:256
03-09 18:39:50.644  4301  4328 E AndroidRuntime: i@2:188
03-09 18:39:50.644  4301  4328 E AndroidRuntime: global code@738:9
03-09 18:39:50.644  4301  4328 E AndroidRuntime:
03-09 18:39:50.644  4301  4328 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:97)
03-09 18:39:50.644  4301  4328 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:81)
03-09 18:39:50.644  4301  4328 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-09 18:39:50.644  4301  4328 E AndroidRuntime:        at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
03-09 18:39:50.644  4301  4328 E AndroidRuntime:        at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
03-09 18:39:50.644  4301  4328 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
03-09 18:39:50.644  4301  4328 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
03-09 18:39:50.644  4301  4328 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
03-09 18:39:50.644  4301  4328 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
03-09 18:39:50.644  4301  4328 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
03-09 18:39:50.644  4301  4328 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
03-09 18:39:50.644  4301  4328 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
03-09 18:39:51.245  1544  1952 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=0 for 341ms
03-09 18:39:51.570  1544  1952 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=0 for 325ms
03-09 18:39:51.573  1544  1952 W ActivityManager:   Force finishing activity io.postila/.MainActivity
03-09 18:39:51.619  4301  4320 I CrashlyticsCore: Crashlytics report upload complete: 58C1A1740126-0001-10CD-0C54DE472E52.cls
03-09 18:39:51.943  1544  1952 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=0 for 326ms
03-09 18:39:52.266  1233  1233 D gralloc : Registering a buffer in the process that created it. This may cause memory ordering problems.
03-09 18:39:52.282  1544  1560 W art     : Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12502 waiters=0 for 1.631s
03-09 18:39:52.282  1544  1610 W art     : Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12502 waiters=1 for 1.565s
03-09 18:39:52.284  1544  1544 W art     : Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12502 waiters=2 for 1.515s
03-09 18:39:52.284  4301  4301 D MainActivity: POSTILA >>>>>>>>>>>>>>>>>>>>>> MAIN ACTIVITY ON PAUSE !!!!!!!!!!!!!!com.facebook.react.XReactInstanceManagerImpl@7e1d25d
03-09 18:39:52.413  1544  4124 I OpenGLRenderer: Initialized EGL, version 1.4
03-09 18:39:52.737  1544  2083 W art     : Long monitor contention event with owner method=int com.android.server.wm.WindowManagerService.relayoutWindow(com.android.server.wm.Session, android.view.IWindow, int, android.view.WindowManager$LayoutParams, int, int, int, int, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.content.res.Configuration, android.view.Surface) from WindowManagerService.java:3103 waiters=1 for 273ms
03-09 18:39:53.694  1544  1559 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=0 for 415ms
03-09 18:39:54.003  1544  1687 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=1 for 657ms
03-09 18:39:54.323  1544  1832 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=2 for 913ms
03-09 18:39:54.599  1544  1559 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=2 for 905ms
03-09 18:39:54.915  1544  1687 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=2 for 912ms
03-09 18:39:55.243  1544  1832 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=2 for 920ms
03-09 18:39:55.523  1544  1559 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=2 for 924ms
03-09 18:39:55.845  1544  1687 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=2 for 930ms
03-09 18:39:56.124  1544  1832 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=2 for 881ms
03-09 18:39:56.481  1544  1559 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=2 for 958ms
03-09 18:39:56.797  1544  1687 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=2 for 951ms
03-09 18:39:57.126  1544  1832 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=2 for 1.002s
03-09 18:39:57.439  1544  1559 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=2 for 958ms
03-09 18:39:57.716  1544  1687 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=2 for 919ms
03-09 18:39:57.765  1544  1832 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=2 for 639ms
03-09 18:39:57.781  4301  4331 E Surface : getSlotFromBufferLocked: unknown buffer: 0x9f0fb290
03-09 18:39:58.113  1544  1559 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=2 for 674ms
03-09 18:39:58.113  1544  1559 I Choreographer: Skipped 338 frames!  The application may be doing too much work on its main thread.
03-09 18:39:58.113  1544  1687 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowManagerService$H.handleMessage(android.os.Message) from WindowManagerService.java:8000 waiters=2 for 397ms
03-09 18:39:58.122  1544  1832 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=2 for 357ms
03-09 18:39:58.122  1544  1948 W art     : Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.doFrame(long) from WindowAnimator.java:121 waiters=3 for 338ms
03-09 18:39:58.123  1544  1558 W art     : Long monitor contention event with owner method=java.util.List com.android.server.am.ActivityManagerService.getAllStackInfos() from ActivityManagerService.java:8937 waiters=0 for 4.736s
03-09 18:39:58.123  1544  1610 W art     : Long monitor contention event with owner method=java.util.List com.android.server.am.ActivityManagerService.getAllStackInfos() from ActivityManagerService.java:8937 waiters=1 for 3.801s
03-09 18:39:58.124  1544  1556 W art     : Long monitor contention event with owner method=java.util.List com.android.server.am.ActivityManagerService.getAllStackInfos() from ActivityManagerService.java:8937 waiters=2 for 602ms
03-09 18:39:58.126  1818  1818 I Choreographer: Skipped 319 frames!  The application may be doing too much work on its main thread.
03-09 18:39:58.322  2159  2175 I art     : Background partial concurrent mark sweep GC freed 22930(1214KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 5MB/9MB, paused 494us total 177.088ms```

Also I can provide config files to analyse.

**Reproduction**
I have created empty application as described in https://facebook.github.io/react-native/docs/getting-started.html Also I have added sign keys for app as descrbed here: https://facebook.github.io/react-native/docs/signed-apk-android.html.
Builded apk was started on emmulator Nexus 5, Android 6 - API level 23.

I saw some similar issues, but none of the solutions from there did not help me.

React Native version: 0.36.1, 0.42
Platform(s) (iOS, Android, or both?): Android
Operating System (macOS, Linux, or Windows?): Windows

**Comment by glcrazier** [comment]
I believed there is something wrong with your JS code. You should take a look at it first.

**Comment by dmius** [comment]
In debug mode RN is started normal. As I wrote before for test I use empty app generated as described here: https://facebook.github.io/react-native/docs/getting-started.html  
So all my code is 
`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

export default class pn extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.android.js
        </Text>
        <Text style={styles.instructions}>
          Double tap R on your keyboard to reload,{'\n'}
          Shake or press menu button for dev menu
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('pn', () => pn); `

**Comment by glcrazier** [comment]
It's a bit strange of what you wrote in render function. Should you add some tags like <Text> or <View>?

**Comment by dmius** [comment]
I mean default code generated, because some part () is not displayed in post.
Really where is 

 render() {
    return (
      < View style={styles.container}>
        < Text style={styles.welcome}>
          Welcome to React Native!
        < /Text>
        < Text style={styles.instructions}>
          To get started, edit index.android.js
        < /Text>
        < Text style={styles.instructions}>
          Double tap R on your keyboard to reload,{'\n'}
          Shake or press menu button for dev menu
        < /Text>
      < /View>
    );
  }

**Comment by glcrazier** [comment]
I saw a line in your post "React Native version: 0.36.1, 0.42". You're running 0.42 JS code in application with 0.36.1 react native library? If so, you should align them.

**Comment by dmius** [comment]
My main application use RN 0.36 but have same problem. I started new empty application with 0.42 and see described problem like in my main app. So every version of RN started with different library.

**Comment by glcrazier** [comment]
At this moment, I think whenever you upgraded your JS, you need to upgrade your application as well with react native library with the same version.

**Comment by dmius** [comment]
Now I have two different application, wth different package.json, placed in different places with different node_modules folder.

**Comment by hasLandon** [comment]
I believe it's related to this: https://github.com/facebook/react-native/issues/12772

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
