### ISSUE TITLE
EACCES: PERMISSION DENIED unable to init react-native Awesomeproject example

### ISSUE THREAD

**Issue by shaunstanislaus** [facebook/react-native#12879]
### unable to use React-Native example

i tried running the default `react-native init AwesomeProject` but it came out this error.

### Reproduction
```bash
[~/workspace]$ react-native init AwesomeProject
This will walk you through creating a new React Native project in /Users/shaun/workspace/AwesomeProject
Using yarn v0.21.3
Installing react-native...
yarn add v0.21.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning react-native > xcode > node-uuid@1.4.7: use uuid module instead
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "EACCES: permission denied, unlink '/Users/shaun/Library/Caches/Yarn/npm-react-native-0.42.0-59b501603a63232598fff653a36307a26010402e/.yarn-tarball.tgz'".
info If you think this is a bug, please open a bug report with the information provided in "/Users/shaun/workspace/AwesomeProject/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
{ Error: Command failed: yarn add react-native --exact
    at checkExecSyncError (child_process.js:489:13)
    at execSync (child_process.js:529:13)
    at run (/usr/local/lib/node_modules/react-native-cli/index.js:294:5)
    at createProject (/usr/local/lib/node_modules/react-native-cli/index.js:249:3)
    at init (/usr/local/lib/node_modules/react-native-cli/index.js:200:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:153:7)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
  error: null,
  cmd: 'yarn add react-native --exact',
  file: '/bin/sh',
  args: [ '/bin/sh', '-c', 'yarn add react-native --exact' ],
  options:
   { stdio: [ [Object], [Object], [Object] ],
     shell: true,
     file: '/bin/sh',
     args: [ '/bin/sh', '-c', 'yarn add react-native --exact' ],
     envPairs:
      [ 'TERM_SESSION_ID=w1t1p1:9C6437BD-70BD-4E8F-93BF-5707E2854D4C',
        'SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.cex0xqDA5j/Listeners',
        'Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.iJRLa2d9dx/Render',
        'COLORFGBG=15;0',
        'ITERM_PROFILE=Default',
        'XPC_FLAGS=0x0',
        'PWD=/Users/shaun/workspace',
        'SHELL=/bin/zsh',
        'SECURITYSESSIONID=186a6',
        'LC_CTYPE=UTF-8',
        'TERM_PROGRAM_VERSION=3.0.14',
        'TERM_PROGRAM=iTerm.app',
        'PATH=/usr/local/opt/jpeg-turbo/bin:/Users/shaun/.rbenv/shims:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin',
        'DISPLAY=/private/tmp/com.apple.launchd.hsbdg4UJSe/org.macosforge.xquartz:0',
        'COMMAND_MODE=unix2003',
        'TERM=xterm-256color',
        'HOME=/Users/shaun',
        'TMPDIR=/var/folders/9f/skdt4s897732vgdd98r_1lhm0000gn/T/',
        'USER=shaun',
        'XPC_SERVICE_NAME=0',
        'LOGNAME=shaun',
        '__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0',
        'ITERM_SESSION_ID=w1t1p1:9C6437BD-70BD-4E8F-93BF-5707E2854D4C',
        'SHLVL=1',
        'OLDPWD=/Users/shaun/workspace/AwesomeProject',
        'ZSH=/Users/shaun/.oh-my-zsh',
        'UPDATE_ZSH_DAYS=1',
        'PAGER=less',
        'LESS=-R',
        'LSCOLORS=Gxfxcxdxbxegedabagacad',
        'RBENV_SHELL=zsh',
        '_=/usr/local/bin/react-native' ] },
  envPairs:
   [ 'TERM_SESSION_ID=w1t1p1:9C6437BD-70BD-4E8F-93BF-5707E2854D4C',
     'SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.cex0xqDA5j/Listeners',
     'Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.iJRLa2d9dx/Render',
     'COLORFGBG=15;0',
     'ITERM_PROFILE=Default',
     'XPC_FLAGS=0x0',
     'PWD=/Users/shaun/workspace',
     'SHELL=/bin/zsh',
     'SECURITYSESSIONID=186a6',
     'LC_CTYPE=UTF-8',
     'TERM_PROGRAM_VERSION=3.0.14',
     'TERM_PROGRAM=iTerm.app',
     'PATH=/usr/local/opt/jpeg-turbo/bin:/Users/shaun/.rbenv/shims:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin',
     'DISPLAY=/private/tmp/com.apple.launchd.hsbdg4UJSe/org.macosforge.xquartz:0',
     'COMMAND_MODE=unix2003',
     'TERM=xterm-256color',
     'HOME=/Users/shaun',
     'TMPDIR=/var/folders/9f/skdt4s897732vgdd98r_1lhm0000gn/T/',
     'USER=shaun',
     'XPC_SERVICE_NAME=0',
     'LOGNAME=shaun',
     '__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0',
     'ITERM_SESSION_ID=w1t1p1:9C6437BD-70BD-4E8F-93BF-5707E2854D4C',
     'SHLVL=1',
     'OLDPWD=/Users/shaun/workspace/AwesomeProject',
     'ZSH=/Users/shaun/.oh-my-zsh',
     'UPDATE_ZSH_DAYS=1',
     'PAGER=less',
     'LESS=-R',
     'LSCOLORS=Gxfxcxdxbxegedabagacad',
     'RBENV_SHELL=zsh',
     '_=/usr/local/bin/react-native' ],
  stderr: null,
  stdout: null,
  pid: 21771,
  output: [ null, null, null ],
  signal: null,
  status: 1 }
Command `yarn add react-native --exact` failed.
[~/workspace]$
[FILL THIS OUT: Try to reproduce your bug on rnplay.org and provide a link. If you can't reproduce the bug on rnplay.org, provide a sample project.]
```

### Additional Information

* React Native version: 2.0.1
* Platform: iOS
* Operating System: MacOS
* Dev tools: iterm/terminal xcode

**Comment by hramos** [comment]
We're cutting down on the number of outstanding issues, in order to allow us to focus. I'm closing this issue because it has been open for over 60 days with no activity. If you think it should still be opened let us know why. PRs are always welcome.
