### ISSUE TITLE
Error: watch /mnt/c/ubuntu/AwesomeProject EPERM

### ISSUE THREAD

**Issue by joetidee** [facebook/react-native#12871]
I followed the steps in the getitng started guide (Android + Windows):

https://facebook.github.io/react-native/docs/getting-started.html

I am running Bash on Windows 10 and my working directory is `/mnt/c/ubuntu/AwesomeProject`.

I run the command `react-native start` and get the following errors:

```
Scanning 548 folders for symlinks in /mnt/c/ubuntu/AwesomeProject/node_modules (51ms)
 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   /mnt/c/ubuntu/AwesomeProject

Loading dependency graph...
React packager ready.

watch /mnt/c/ubuntu/AwesomeProject EPERM
Error: watch /mnt/c/ubuntu/AwesomeProject EPERM
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1429:19)
    at Object.fs.watch (fs.js:1456:11)
    at NodeWatcher.watchdir (/mnt/c/ubuntu/AwesomeProject/node_modules/sane/src/node_watcher.js:144:20)
    at new NodeWatcher (/mnt/c/ubuntu/AwesomeProject/node_modules/sane/src/node_watcher.js:45:8)
    at createWatcher (/mnt/c/ubuntu/AwesomeProject/node_modules/jest-haste-map/build/index.js:536:23)
    at Array.map (native)
    at HasteMap._watch (/mnt/c/ubuntu/AwesomeProject/node_modules/jest-haste-map/build/index.js:654:44)
    at _buildPromise._buildFileMap.then.then.hasteMap (/mnt/c/ubuntu/AwesomeProject/node_modules/jest-haste-map/build/index.js:250:21)
```

**Comment by hramos** [comment]
We're cutting down on the number of outstanding issues, in order to allow us to focus. I'm closing this issue because it has been open for over 60 days with no activity. If you think it should still be opened let us know why. PRs are always welcome.

**Comment by unip** [comment]
I have the same problem too
