### ISSUE TITLE
React Packager 0.43.0-rc.2 EPIPE

### ISSUE THREAD

**Issue by pocesar** [facebook/react-native#12885]
### Description

React Packager in react-native 0.43.0-rc.2 is giving random EPIPE errors on Windows 10. It seems that sourceMaps stopped working (the red box shows `index.android.bundle`. URL instead of the proper symbolication)

### Reproduction

* `npm run start` then wait

### Additional Information

* React Native version: 0.43.0-rc.2
* Platform: Android 6
* Operating System: Windows 10 x64

```
Bundling `index.android.js`  100.0% (971/971), done.
SyntaxError: Unexpected end of JSON input
    at parse (<anonymous>)
    at process._tickCallback (internal/process/next_tick.js:109:7)
{ Error: write EPIPE
    at exports._errnoException (util.js:1033:11)
    at Socket._writeGeneric (net.js:727:26)
    at Socket._write (net.js:746:8)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at Socket.Writable.write (_stream_writable.js:241:11)
    at Socket.write (net.js:673:40)
    at Socket.Writable.end (_stream_writable.js:475:10)
    at Socket.end (net.js:443:31)
    at Promise.resolve.then.then.then.catch.then.message (G:\mobile\cadastro\node_modules\react-native\packager\src\Server\symbolicate\worker.js:35:33) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
```

**Comment by maheshbeeravelli** [comment]
I am also facing the same issue in windows 7 with react-native-cli: 2.0.1 and
react-native: 0.43.1

**Comment by jackyef** [comment]
I am also facing the same issue
react-native: 0.43.0

No errors on my code. The bundling process was completed successfully to 100%.

The error is as shown:
```
Bundling `index.android.js`  100.0% (407/407), done.
SyntaxError: Unexpected end of JSON input
    at parse (native)
    at process._tickCallback (internal/process/next_tick.js:103:7)
SyntaxError: Unexpected end of JSON input
    at parse (native)
    at process._tickCallback (internal/process/next_tick.js:103:7)
{ Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at Socket._writeGeneric (net.js:710:26)
    at Socket._write (net.js:729:8)
    at doWrite (_stream_writable.js:333:12)
    at writeOrBuffer (_stream_writable.js:319:5)
    at Socket.Writable.write (_stream_writable.js:246:11)
    at Socket.write (net.js:656:40)
    at Socket.Writable.end (_stream_writable.js:479:10)
    at Socket.end (net.js:428:31)
    at Promise.resolve.then.then.then.catch.then.message (D:\Projects\ReactNative\AwesomeProject\node_modules\react-native\packager\src\Server\symbolicate\worker.js:35:33) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
{ Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at Socket._writeGeneric (net.js:710:26)
    at Socket._write (net.js:729:8)
    at doWrite (_stream_writable.js:333:12)
    at writeOrBuffer (_stream_writable.js:319:5)
    at Socket.Writable.write (_stream_writable.js:246:11)
    at Socket.write (net.js:656:40)
    at Socket.Writable.end (_stream_writable.js:479:10)
    at Socket.end (net.js:428:31)
    at Promise.resolve.then.then.then.catch.then.message (D:\Projects\ReactNative\AwesomeProject\node_modules\react-native\packager\src\Server\symbolicate\worker.js:35:33) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' } 
```

**Comment by RemeJuan** [comment]
Just spun up a new application this morning and am hitting the same issues.

**Comment by cbt2016** [comment]
Same Problem here but still the app is compiling and running as expected .Does have to do with package.json format ,i remember starting to get this problem after installing 'redux-thunk' ??!!

**Comment by cbt2016** [comment]
EPIPE error happens generally when your program does not have permissions to run something (in this case a pipe stream ) on your computer .i opened git bash as Administrator and rerun 'react-native run-android' and the error disappeared :)

**Comment by pocesar** [comment]
nope, not a problem with permissions, everything permission-wise is fine, it's completely random, and I guess it's mainly because of consecutive writes onto the same file (like rapidly pressing Ctrl + S twice on the same file, for example)

**Comment by cbt2016** [comment]
In my case ,this is the code throwing the error ,it is a Promise : 
`function symbolicate(connection, data) {
  return Promise.resolve(data)
    .then(JSON.parse)
    .then(symbolicateStack)
    .then(JSON.stringify)
    .catch(makeErrorMessage)
    **.then(message => connection.end(message));**
}`

**Comment by RemeJuan** [comment]
@cbt2016 good idea is relative, if it fixes the problem for now and you can carry on working then yes, when 0.43.3 pops out with the actual (possibly same) fix, then you just update.

**Comment by nogi1** [comment]
Anyone found at least temporary solution? @cbt2016 what's your solution?

**Comment by RemeJuan** [comment]
@nogi1 I found it simply easier to go back to 0.42.x

**Comment by janicduplessis** [comment]
@davidaurelio @cpojer Any ideas on how to fix this? It is pretty bad since symbolication is completely broken on windows.

The only workaround I found is using a random numeric port as the socket instead of `xpipe.eq(temp.path(affixes))` in https://github.com/facebook/react-native/blob/master/packager/src/Server/symbolicate/symbolicate.js#L33

**Comment by pbassut** [comment]
Also running into this.

**Comment by rockmacaca** [comment]
I'm currently stuck on 0.42 due to this as well, this problem persists in 0.44. On Windows 10.

**Comment by jorgepcbraz** [comment]
same thing here with react-native 0.43.4

**Comment by davidaurelio** [comment]
Sorry about the bad breakage. Could somebody on windows fix the code in question and send a PR, please? This is the code: https://github.com/facebook/react-native/blob/58ba7fc07518afdacb5363b6449fadfedc0ad6d7/packager/src/Server/symbolicate/symbolicate.js#L32-L45

**Comment by stoffern** [comment]
The error `Expected a run on UI thread! ` is related to this issue..

**Comment by stoffern** [comment]
@janicduplessis thanks for the PR to fix this.
074fd33725626530c68d897150413a13715280a1 fixes this issue.

Will be on next release?

**Comment by janicduplessis** [comment]
It will be in 0.45 for sure, I'll check if we can cherry pick it in 0.44 also

**Comment by khangbkhn** [comment]
I'm using window 7. Applying the solution by replacing your symbolicate.js to mine its cause another error.
Here is stacktrace:



`TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
at launchEditor (D:/AwesomeProject/node_modules/react-native/local-cli/server/util/launchEditor.js:154:27)
at Object.handle (D:/AwesomeProject/node_modules/react-native/local-cli/server/middleware/openStackFrameInEditorMidd
leware.js:17:7)
at next (D:\AwesomeProject\node_modules\react-native\node_modules\connect\lib\proto.js:174:15)
at Object.handle (D:/AwesomeProject/node_modules/react-native/local-cli/server/middleware/getDevToolsMiddleware.js:7
4:7)
at next (D:\AwesomeProject\node_modules\react-native\node_modules\connect\lib\proto.js:174:15)
at Object.handle (D:/AwesomeProject/node_modules/react-native/local-cli/server/middleware/getDevToolsMiddleware.js:7
4:7)
at next (D:\AwesomeProject\node_modules\react-native\node_modules\connect\lib\proto.js:174:15)
at Object.compression [as handle] (D:\AwesomeProject\node_modules\react-native\node_modules\connect\node_modules\com
pression\index.js:205:5)
at next (D:\AwesomeProject\node_modules\react-native\node_modules\connect\lib\proto.js:174:15)
at IncomingMessage. (D:/AwesomeProject/node_modules/react-native/local-cli/server/middleware/loadRawBodyM
iddleware.js:20:5)`
I'm using 0.44.0 react-native version

**Comment by stoffern** [comment]
@khangbkhn then you have a error in your code.. it works just fine here.

**Comment by asongsoekamti** [comment]
same with me, my react produce this error message on windows 10...

    at exports._errnoException (util.js:1050:11)                                                                                                                            at Socket._writeGeneric (net.js:725:26)                                                                                                                                 at Socket._write (net.js:744:8)                                                                                                                                         at doWrite (_stream_writable.js:329:12)                                                                                                                                 at writeOrBuffer (_stream_writable.js:315:5)                                                                                                                            at Socket.Writable.write (_stream_writable.js:241:11)                                                                                                                   at Socket.write (net.js:671:40)                                                                                                                                         at Socket.Writable.end (_stream_writable.js:475:10)                                                                                                                     at Socket.end (net.js:441:31)                                                                                                                                           at Promise.resolve.then.then.then.catch.then.message (C:\Users\myusername\AwesomeProject2\node_modules\react-native\packager\src\Server\symbolicate\worker.js:35:33) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }

**Comment by sclanc** [comment]
@janicduplessis, @khangbkhn 

By adding 

 +  const socket = process.platform === 'win32'
 +    ? 34712
 +    : xpipe.eq(temp.path(affixes));

and removing

33 -  const socket = xpipe.eq(temp.path(affixes));

I get a similar error to Khangbkhn on Windows 10: 

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
    at launchEditor (node_modules/react-native/local-cli/server/util/launchEditor.js:154:27)
    at Object.handle (node_modules/react-native/local-cli/server/middleware/openStackFrameInEditorMiddleware.js:17:7)
    at next (node_modules\connect\lib\proto.js:174:15)
    at Object.handle (node_modules/react-native/local-cli/server/middleware/getDevToolsMiddleware.js:74:7)
    at next (node_modules\connect\lib\proto.js:174:15)
    at Object.handle (node_modules/react-native/local-cli/server/middleware/getDevToolsMiddleware.js:74:7)
    at next (node_modules\connect\lib\proto.js:174:15)
    at Object.compression [as handle] (node_modules\compression\index.js:205:5)
    at next (node_modules\connect\lib\proto.js:174:15)
    at IncomingMessage.<anonymous> (node_modules/react-native/local-cli/server/middleware/loadRawBodyMiddleware.js:20:5)

**Comment by stoffern** [comment]
Node versjon?

**Comment by asongsoekamti** [comment]
hi @stoffern , I'm using node version v7.10.0

**Comment by mohaaqqani** [comment]
Same Error as @pocesar  , Win 10, Node 7.10.0 , I have tried 

- ruining `react-native run-android` using Administrative privileges , 
- tried fixing the solution @stoffern provided. 

Same error.
Also I have initiated new project in some new directory and same issue is displayed there too.

**Comment by mohaaqqani** [comment]
I tried closing all Packagers and then restarting my machine 
After restart, I started packager using `npm start -- reset-cache` and it is working perfectly fine.

**Comment by matthiasprieth** [comment]
I get the same errors also with react-native 0.44.0, Win 7, Node 7.8.0

**Comment by namphuongtran** [comment]
i got the same errors also with react native 0.44, Window 10 x64. But i try to resolve according to @cbt2016  recommended then it was working fine! thanks

**Comment by ishwarrimal** [comment]
I was getting the same error while running 'react-native run-android' and was getting a white screen. I followed @stoffern instructions. Now that error is gone. But still getting white screen. Please help

**Comment by puzpuz** [comment]
@ishwarrimal did you run it on android emulator or real device?

**Comment by ishwarrimal** [comment]
Thanks @puzpuz  for your response. I was running it on device. Nwz, i fixed it. It was problem specific to my Phone. Xiomi Redmi Note 3.

**Comment by puzpuz** [comment]
@ishwarrimal  exactly what I suspected, every xiaomi phone needs permission for overlay screen to be accepted manually. Glad you found it :)

**Comment by Fed0t** [comment]
```
C:\Project\node_modules\react-native\packager\src\Server\symbolicate\symbolicate.js:29
coNst affixes = { prefix: 'metro-bundler-symbolicate', suffix: '.sock' };
      ^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at loader (C:\Project\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Project\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

This error suddenly triggered just after random react-native run-android command.
I fixed it with replacing symbolicate.js file with @stoffern / @janicduplessis response.
[https://github.com/facebook/react-native/commit/074fd33725626530c68d897150413a13715280a1](url)

But why did it suddenly appear? I dont updated nothing.I do not install nothing with npm.There was just a live reload.
Thank you!

**Comment by pocesar** [comment]
still happens, but have no cause or reproducibility
