### ISSUE TITLE
Error: Can't find variable: __fbBatchedBridgeConfig

### ISSUE THREAD

**Issue by anderson916** [facebook/react-native#12914]
03-14 10:53:07.683 26038-26079/com.drcontroller E/ReactNativeJS: Error: Can't find variable: __fbBatchedBridgeConfig, stack:
                                                                 index.android.bundle:9:2042
                                                                 r@index.android.bundle:1:747
                                                                 n@index.android.bundle:1:413
                                                                 index.android.bundle:9:895
                                                                 r@index.android.bundle:1:747
                                                                 n@index.android.bundle:1:413
                                                                 index.android.bundle:9:12312
                                                                 r@index.android.bundle:1:747
                                                                 n@index.android.bundle:1:413
                                                                 u@index.android.bundle:8:58469
                                                                 index.android.bundle:8:31104
                                                                 r@index.android.bundle:1:747
                                                                 r@index.android.bundle:1:476
                                                                 n@index.android.bundle:1:413
                                                                 global code@index.android.bundle:25:16283
                                                                 
                                                                 --------- beginning of crash
03-14 10:53:07.687 26038-26079/com.drcontroller E/AndroidRuntime: FATAL EXCEPTION: mqt_js
                                                                  Process: com.drcontroller, PID: 26038
                                                                  java.lang.RuntimeException: com.facebook.react.devsupport.JSException: Error: Requiring module "NativeModules" which threw an exception (index.android.bundle:1)
                                                                      at com.facebook.react.bridge.DefaultNativeModuleCallExceptionHandler.handleException(DefaultNativeModuleCallExceptionHandler.java:24)
                                                                      at com.facebook.react.devsupport.DisabledDevSupportManager.handleException(DisabledDevSupportManager.java:158)
                                                                      at com.facebook.react.cxxbridge.CatalystInstanceImpl.onNativeException(CatalystInstanceImpl.java:471)
                                                                      at com.facebook.react.cxxbridge.CatalystInstanceImpl.access$400(CatalystInstanceImpl.java:51)
                                                                      at com.facebook.react.cxxbridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:487)
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:33)
                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                      at java.lang.Thread.run(Thread.java:761)

**Comment by brunolemos** [comment]
@anderson916 @hramos what was the fix? I'm getting this on Android

**Comment by hramos** [comment]
@brunolemos this issue was closed immediately because it didn't provide enough information as required by the template. I recommend opening a new issue.

**Comment by brunolemos** [comment]
Thanks.
