### ISSUE TITLE
[Android] NativeModules Runtime Error

### ISSUE THREAD

**Issue by brunocascio** [facebook/react-native#12932]
```
03-14 13:39:49.251 6001-6036/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                 Process: com.fbtmobile, PID: 6001
                                                 com.facebook.react.common.JavascriptException: Requiring unknown module "NativeModules"., stack:
                                                 o@2:742
                                                 n@2:426
                                                 i@2:348
                                                 t@2:210
                                                 exports@759:402
                                                 <unknown>@446:6937
                                                 n@2:557
                                                 i@2:348
                                                 t@2:210
                                                 <unknown>@445:30
                                                 n@2:557
                                                 i@2:348
                                                 t@2:210
                                                 <unknown>@365:208
                                                 n@2:557
                                                 i@2:348
                                                 t@2:210
                                                 <unknown>@12:38
                                                 n@2:557
                                                 i@2:278
                                                 t@2:210
                                                 global code@1087:9
                                                 
                                                     at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:97)
                                                     at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:81)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
                                                     at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
                                                     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                     at android.os.Handler.handleCallback(Handler.java:815)
                                                     at android.os.Handler.dispatchMessage(Handler.java:104)
                                                     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                     at android.os.Looper.loop(Looper.java:207)
                                                     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                     at java.lang.Thread.run(Thread.java:818)
```

It's happening when I try to release an .apk file following the docs: https://facebook.github.io/react-native/docs/signed-apk-android.html

react-native version: `0.41.2`

**Comment by marcoacierno** [comment]
Same issue with `0.42.0`

**Comment by brunocascio** [comment]
@marcoacierno and everyone.

I removed the reactotron dependency and it seems working. Let me know if you are experiencing same issue with another package. I'll leave open this issue anyway until your response.

**Comment by marcoacierno** [comment]
Hello, fixed the same way. thank you : )

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by mcconkiee** [comment]
@brunocascio / @marcoacierno - i'm having this exact issue w/ 0.42.0. - however i'm not seeing a `reactotron` dependency. Any more explanation why production builds fail with this exception?

```
12-04 13:49:27.006  3484  3524 E AndroidRuntime: java.lang.RuntimeException: com.facebook.react.devsupport.JSException: Error: Requiring module "NativeModules" which threw an exception (index.android.bundle:1)
12-04 13:49:27.006  3484  3524 E AndroidRuntime:  at com.facebook.react.bridge.DefaultNativeModuleCallExceptionHandler.handleException(DefaultNativeModuleCallExceptionHandler.java:24)
12-04 13:49:27.006  3484  3524 E AndroidRuntime:  at com.facebook.react.devsupport.DisabledDevSupportManager.handleException(DisabledDevSupportManager.java:158)
12-04 13:49:27.006  3484  3524 E AndroidRuntime:  at com.facebook.react.cxxbridge.CatalystInstanceImpl.onNativeException(CatalystInstanceImpl.java:471)
12-04 13:49:27.006  3484  3524 E AndroidRuntime:  at com.facebook.react.cxxbridge.CatalystInstanceImpl.access$400(CatalystInstanceImpl.java:51)
12-04 13:49:27.006  3484  3524 E AndroidRuntime:  at com.facebook.react.cxxbridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:487)
12-04 13:49:27.006  3484  3524 E AndroidRuntime:  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:33)
12-04 13:49:27.006  3484  3524 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:148)
12-04 13:49:27.006  3484  3524 E AndroidRuntime:  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
12-04 13:49:27.006  3484  3524 E AndroidRuntime:  at java.lang.Thread.run(Thread.java:818)
12-04 13:49:27.006  3484  3524 E AndroidRuntime: Caused by: com.facebook.react.devsupport.JSException: Error: Requiring module "NativeModules" which threw an exception (index.android.bundle:1)
12-04 13:49:27.006  3484  3524 E AndroidRuntime:  at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
12-04 13:49:27.006  3484  3524 E AndroidRuntime:  at android.os.Handler.handleCallback(Handler.java:739)
12-04 13:49:27.006  3484  3524 E AndroidRuntime:  at android.os.Handler.dispatchMessage(Handler.java:95)
12-04 13:49:27.006  3484  3524 E AndroidRuntime:  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
12-04 13:49:27.006  3484  3524 E AndroidRuntime:  ... 3 more
12-04 13:49:27.006  3484  3524 E AndroidRuntime: Caused by: com.facebook.jni.CppException: Error: Requiring module "NativeModules" which threw an exception (index.android.bundle:1)
12-04 13:49:27.006  3484  3524 E AndroidRuntime:  ... 7 more
```
