### ISSUE TITLE
Apply native animation on layout only component throws error on Android

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#12975]
### Description

Use an animation with useNativeDriver on a layout only View will throw an error like this:

```
Unable to update properties for view tag 827
                                                                     com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 827 could not be found
                                                                         at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:106)
                                                                         at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:123)
                                                                         at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:234)
                                                                         at com.facebook.react.animated.PropsAnimatedNode.updateView(PropsAnimatedNode.java:69)
                                                                         at com.facebook.react.animated.NativeAnimatedNodesManager.updateNodes(NativeAnimatedNodesManager.java:469)
                                                                         at com.facebook.react.animated.NativeAnimatedNodesManager.runUpdates(NativeAnimatedNodesManager.java:380)
                                                                         at com.facebook.react.animated.NativeAnimatedModule$1.doFrameGuarded(NativeAnimatedModule.java:117)
                                                                         at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
                                                                         at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:129)
                                                                         at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:759)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:543)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                         at android.os.Handler.handleCallback(Handler.java:733)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                         at dalvik.system.NativeStart.main(Native Method)
```

### Reproduction

```
// translateY is an AnimatedValue with `useNativeDriver: true`

 <Animated.View style={{flex: 1, transform: [{ translateY }]}} />
```

### Solution

Apply a backgroundColor on this layout only component will fix this.

```
 <Animated.View style={{flex: 1, backgroundColor: 'transparent', transform: [{ translateY }]}} />
```

### Additional Information

* React Native version: 0.43.0-rc
* Platform: Android

**Comment by janicduplessis** [comment]
Fix here #12983
