### ISSUE TITLE
Timeout Error using react-native-git-upgrade

### ISSUE THREAD

**Issue by gwmccull** [facebook/react-native#12979]
### Description

I'm trying to upgrade my app from RN 0.36.0 to RN 0.40.0 (and eventually to RN 0.42.0).  I installed `react-native-git-upgrade` and ran it but it gave timeout errors.  I also attempted to ping the IP address and it timed out.

The error I received was:
```
git-upgrade ERR! An error occurred during upgrade: 
git-upgrade ERR! Error: Command 'npm view react-native@0.42.0 --json' exited with code 1:
stderr: undefinednpm ERR! Darwin 16.4.0
npm ERR! argv "/Users/gmccullough/.nvm/versions/node/v6.2.2/bin/node" "/Users/gmccullough/.nvm/versions/node/v6.2.2/bin/npm" "view" "react-native@0.42.0" "--json"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 198.105.254.17:8081
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gmccullough/Development/Build/BuildApp/npm-debug.log

stdout: 
    at ChildProcess.child.on.code (/Users/gmccullough/.nvm/versions/node/v6.2.2/lib/node_modules/react-native-git-upgrade/cliEntry.js:58:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12) 
```

### Reproduction

I ran the following commands:
`npm install -g react-native-git-upgrade`
`react-native-git-upgrade 0.42.0`

### Solution

Solution?  I don't know, restart the server?

### Additional Information

* React Native version: RN 0.36.0
* Platform: n/a
* Operating System: MacOS
* Dev tools: n/a

**Comment by gwmccull** [comment]
Seems to be working now.  Closing
