### ISSUE TITLE
Android SIGSEGV crash on .42 [Navigator related]

### ISSUE THREAD

**Issue by natdm** [facebook/react-native#13016]
### Description

Android 0.40, and 0.42 are both experiencing this problem. Genymotion and Android Studio builds, android SDK 23 and 25 (since 25 comes with Android Studio).

I don't know what is causing the crash. I'm not a Java developer and am quite unfamiliar with the Java environment. Please let me know what else I can get for this, and how I can get it. I do not know how to reproduce the problem on a separate project to assist in the fix. 

Edit: It's possible that it's related to the Navigator. I removed all instances of `Navigator.push(scene)` and replaced with `Navigator. resetTo(scene)` and it works fine, but that's no way to write an app. Seems like it happens after 2-3 routes are on the stack. It will freeze the application, and a few moments later, crash.

Android Monitor in Android Studio outputs this line just before crashing:
`03-18 23:10:08.110 2864-2936/com.bideasy_rn A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x3c in tid 2936 (mqt_js)`
This makes me believe it could be similar to [this issue](https://code.google.com/p/android/issues/detail?id=8709). I do use a lot of lists and arrays, and converting objects to arrays, as well as arrays to objects (utilizing lodash a bit). Using `ListView` for my lists. 

Stacktrace (`adb logcat`) output:
```
03-18 22:59:19.524  3408  3431 E Surface : getSlotFromBufferLocked: unknown buffer: 0xdd889760
03-18 22:59:20.804  1999  1999 I LatinIME: Starting input. Cursor position = 0,0
03-18 22:59:20.922  1311  2049 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-18 22:59:20.933  1311  1350 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-18 22:59:20.940  1311  1350 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-18 22:59:29.960  1999  3033 E Surface : getSlotFromBufferLocked: unknown buffer: 0x7f64a2322aa0
03-18 22:59:59.978  1311  1351 D hwcomposer: hw_composer sent 2592 syncs in 60s
03-18 23:00:01.013  1664  1680 I ActivityManager: Start proc 3490:com.android.deskclock/u0a25 for broadcast com.android.deskclock/com.android.alarmclock.DigitalAppWidgetProvider
03-18 23:00:01.028  3490  3490 E art     : Failed to send JDWP packet APNM to debugger (-1 of 69): Broken pipe
03-18 23:00:01.029  3490  3495 E art     : Failed writing handshake bytes (-1 of 14): Broken pipe
03-18 23:00:01.029  3490  3495 I art     : Debugger is no longer active
03-18 23:00:01.041  3490  3490 W System  : ClassLoader referenced unknown path: /system/app/DeskClock/lib/x86_64
03-18 23:00:01.049  1664  2020 I ActivityManager: Killing 2743:com.android.messaging/u0a49 (adj 15): empty #17
03-18 23:00:34.660  3408  3433 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x3c in tid 3433 (mqt_js)
03-18 23:00:34.763  1381  1381 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-18 23:00:34.763  1381  1381 F DEBUG   : Build fingerprint: 'Android/sdk_google_phone_x86_64/generic_x86_64:6.0/MASTER/3738108:userdebug/test-keys'
03-18 23:00:34.763  1381  1381 F DEBUG   : Revision: '0'
03-18 23:00:34.763  1381  1381 F DEBUG   : ABI: 'x86'
03-18 23:00:34.763  1381  1381 F DEBUG   : pid: 3408, tid: 3433, name: mqt_js  >>> com.bideasy_rn <<<
03-18 23:00:34.763  1381  1381 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x3c
03-18 23:00:34.774  1381  1381 F DEBUG   :     eax 00000000  ebx e18f3d9c  ecx fffffffb  edx e00ffc40
03-18 23:00:34.774  1381  1381 F DEBUG   :     esi 00000000  edi 00000000
03-18 23:00:34.774  1381  1381 F DEBUG   :     xcs 00000023  xds 0000002b  xes 0000002b  xfs 0000009f  xss 0000002b
03-18 23:00:34.774  1381  1381 F DEBUG   :     eip e14ee74b  ebp 00000000  esp e06daf10  flags 00210286
03-18 23:00:34.779  1381  1381 F DEBUG   :
03-18 23:00:34.779  1381  1381 F DEBUG   : backtrace:
03-18 23:00:34.779  1381  1381 F DEBUG   :     #00 pc 0006174b  /data/app/com.bideasy_rn-2/lib/x86/libjsc.so
03-18 23:00:34.779  1381  1381 F DEBUG   :     #01 pc 001031c3  /data/app/com.bideasy_rn-2/lib/x86/libjsc.so
03-18 23:00:34.779  1381  1381 F DEBUG   :     #02 pc 00128294  /data/app/com.bideasy_rn-2/lib/x86/libjsc.so
03-18 23:00:34.779  1381  1381 F DEBUG   :     #03 pc 00142c10  /data/app/com.bideasy_rn-2/lib/x86/libjsc.so
03-18 23:00:34.779  1381  1381 F DEBUG   :     #04 pc 00002843  <unknown>
03-18 23:00:34.779  1381  1381 F DEBUG   :     #05 pc 0017ac7d  /data/app/com.bideasy_rn-2/lib/x86/libjsc.so
03-18 23:00:34.780  1381  1381 F DEBUG   :     #06 pc 00126763  /data/app/com.bideasy_rn-2/lib/x86/libjsc.so
03-18 23:00:34.780  1381  1381 F DEBUG   :     #07 pc 001039f8  /data/app/com.bideasy_rn-2/lib/x86/libjsc.so
03-18 23:00:34.780  1381  1381 F DEBUG   :     #08 pc 00225591  /data/app/com.bideasy_rn-2/lib/x86/libjsc.so (JSC::call(JSC::ExecState*, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&)+113)
03-18 23:00:34.780  1381  1381 F DEBUG   :     #09 pc 00265bfc  /data/app/com.bideasy_rn-2/lib/x86/libjsc.so
03-18 23:00:34.780  1381  1381 F DEBUG   :     #10 pc 00000bcc  <unknown>
03-18 23:00:34.781  1381  1381 F DEBUG   :     #11 pc 0000404a  <unknown>
03-18 23:00:34.781  1381  1381 F DEBUG   :     #12 pc 00002793  <unknown>
03-18 23:00:34.781  1381  1381 F DEBUG   :     #13 pc 0017ac7d  /data/app/com.bideasy_rn-2/lib/x86/libjsc.so
03-18 23:00:34.781  1381  1381 F DEBUG   :     #14 pc 00126763  /data/app/com.bideasy_rn-2/lib/x86/libjsc.so
03-18 23:00:34.781  1381  1381 F DEBUG   :     #15 pc 001039f8  /data/app/com.bideasy_rn-2/lib/x86/libjsc.so
03-18 23:00:34.781  1381  1381 F DEBUG   :     #16 pc 00225591  /data/app/com.bideasy_rn-2/lib/x86/libjsc.so (JSC::call(JSC::ExecState*, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&)+113)
03-18 23:00:34.781  1381  1381 F DEBUG   :     #17 pc 00265bfc  /data/app/com.bideasy_rn-2/lib/x86/libjsc.so
03-18 23:00:34.782  1381  1381 F DEBUG   :     #18 pc 00000bcc  <unknown>
03-18 23:00:34.782  1381  1381 F DEBUG   :     #19 pc 0000cfca  <unknown>
03-18 23:00:34.782  1381  1381 F DEBUG   :     #20 pc 000010d9  <unknown>
03-18 23:00:34.782  1381  1381 F DEBUG   :     #21 pc 000009c0  <unknown>
03-18 23:00:34.782  1381  1381 F DEBUG   :     #22 pc 00000496  <unknown>
03-18 23:00:34.782  1381  1381 F DEBUG   :     #23 pc 00003eac  <unknown>
03-18 23:00:34.783  1381  1381 F DEBUG   :     #24 pc 0000c8a0  <unknown>
03-18 23:00:34.783  1381  1381 F DEBUG   :     #25 pc 000002cc  <unknown>
03-18 23:00:34.783  1381  1381 F DEBUG   :     #26 pc 000031ae  <unknown>
03-18 23:00:34.783  1381  1381 F DEBUG   :     #27 pc 000001d7  <unknown>
03-18 23:00:34.784  1381  1381 F DEBUG   :     #28 pc 00002fef  <unknown>
03-18 23:00:34.784  1381  1381 F DEBUG   :     #29 pc 0000266b  <unknown>
03-18 23:00:34.784  1381  1381 F DEBUG   :     #30 pc 000043ac  <unknown>
03-18 23:00:34.784  1381  1381 F DEBUG   :     #31 pc 00000f41  <unknown>
03-18 23:00:34.784  1381  1381 F DEBUG   :     #32 pc 00001117  <unknown>
03-18 23:00:34.784  1381  1381 F DEBUG   :     #33 pc 000027ec  <unknown>
03-18 23:00:34.784  1381  1381 F DEBUG   :     #34 pc 000012b3  <unknown>
03-18 23:00:34.784  1381  1381 F DEBUG   :     #35 pc 00000186  <unknown>
03-18 23:00:34.784  1381  1381 F DEBUG   :     #36 pc 00001022  <unknown>
03-18 23:00:34.784  1381  1381 F DEBUG   :     #37 pc 000005e2  <unknown>
03-18 23:00:34.784  1381  1381 F DEBUG   :     #38 pc 000004a8  <unknown>
03-18 23:00:34.785  1381  1381 F DEBUG   :     #39 pc 00002fef  <unknown>
03-18 23:00:34.785  1381  1381 F DEBUG   :     #40 pc 0000266b  <unknown>
03-18 23:00:34.785  1381  1381 F DEBUG   :     #41 pc 000043ac  <unknown>
03-18 23:00:34.785  1381  1381 F DEBUG   :     #42 pc 00000f41  <unknown>
03-18 23:00:34.785  1381  1381 F DEBUG   :     #43 pc 000004a8  <unknown>
03-18 23:00:34.785  1381  1381 F DEBUG   :     #44 pc 00002fef  <unknown>
03-18 23:00:34.785  1381  1381 F DEBUG   :     #45 pc 0000266b  <unknown>
03-18 23:00:34.786  1381  1381 F DEBUG   :     #46 pc 000043ac  <unknown>
03-18 23:00:34.786  1381  1381 F DEBUG   :     #47 pc 00000f41  <unknown>
03-18 23:00:34.786  1381  1381 F DEBUG   :     #48 pc 000004a8  <unknown>
03-18 23:00:34.786  1381  1381 F DEBUG   :     #49 pc 00002fef  <unknown>
03-18 23:00:34.786  1381  1381 F DEBUG   :     #50 pc 0000266b  <unknown>
03-18 23:00:34.786  1381  1381 F DEBUG   :     #51 pc 000043ac  <unknown>
03-18 23:00:34.786  1381  1381 F DEBUG   :     #52 pc 00000f41  <unknown>
03-18 23:00:34.786  1381  1381 F DEBUG   :     #53 pc 00001117  <unknown>
03-18 23:00:34.787  1381  1381 F DEBUG   :     #54 pc 000027ec  <unknown>
03-18 23:00:34.787  1381  1381 F DEBUG   :     #55 pc 000012b3  <unknown>
03-18 23:00:34.787  1381  1381 F DEBUG   :     #56 pc 00000186  <unknown>
03-18 23:00:34.787  1381  1381 F DEBUG   :     #57 pc 00001022  <unknown>
03-18 23:00:34.787  1381  1381 F DEBUG   :     #58 pc 000005e2  <unknown>
03-18 23:00:34.787  1381  1381 F DEBUG   :     #59 pc 000004a8  <unknown>
03-18 23:00:34.787  1381  1381 F DEBUG   :     #60 pc 00002fef  <unknown>
03-18 23:00:34.788  1381  1381 F DEBUG   :     #61 pc 0000266b  <unknown>
03-18 23:00:34.788  1381  1381 F DEBUG   :     #62 pc 000043ac  <unknown>
03-18 23:00:34.788  1381  1381 F DEBUG   :     #63 pc 00000f41  <unknown>
03-18 23:00:34.946  1381  1381 F DEBUG   :
03-18 23:00:34.946  1381  1381 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_08
03-18 23:00:34.946  1664  3512 W ActivityManager:   Force finishing activity com.bideasy_rn/.MainActivity
03-18 23:00:34.946  1381  1381 E DEBUG   : AM write failed: Broken pipe
03-18 23:00:34.946  1664  1683 I BootReceiver: Copying /data/tombstones/tombstone_08 to DropBox (SYSTEM_TOMBSTONE)
03-18 23:00:34.956  1311  1372 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x333 imply creation of host color buffer
03-18 23:00:34.966  1664  3512 D         : HostConnection::get() New Host Connection established 0x7f649f1b5920, tid 3512
03-18 23:00:34.988  1311  1311 E EGL_emulation: tid 1311: eglCreateSyncKHR(1660): error 0x3004 (EGL_BAD_ATTRIBUTE)
03-18 23:00:35.001  1664  1702 W InputDispatcher: channel 'ff4df53 com.bideasy_rn/com.bideasy_rn.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-18 23:00:35.001  1664  1702 E InputDispatcher: channel 'ff4df53 com.bideasy_rn/com.bideasy_rn.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-18 23:00:35.016  1664  2840 D GraphicsStats: Buffer count: 4
03-18 23:00:35.060  1390  1390 I Zygote  : Process 3408 exited due to signal (11)
03-18 23:00:35.088  1664  2229 I WindowState: WIN DEATH: Window{ff4df53 u0 com.bideasy_rn/com.bideasy_rn.MainActivity}
03-18 23:00:35.088  1664  2229 W InputDispatcher: Attempted to unregister already unregistered input channel 'ff4df53 com.bideasy_rn/com.bideasy_rn.MainActivity (server)'
03-18 23:00:35.090  1664  3512 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-18 23:00:35.093  1664  3512 W ActivityManager: Exception thrown during pause
03-18 23:00:35.093  1664  3512 W ActivityManager: android.os.DeadObjectException
03-18 23:00:35.093  1664  3512 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
03-18 23:00:35.093  1664  3512 W ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:503)
03-18 23:00:35.093  1664  3512 W ActivityManager: 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
03-18 23:00:35.093  1664  3512 W ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:867)
03-18 23:00:35.093  1664  3512 W ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
03-18 23:00:35.093  1664  3512 W ActivityManager: 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
03-18 23:00:35.093  1664  3512 W ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2755)
03-18 23:00:35.093  1664  3512 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11971)
03-18 23:00:35.093  1664  3512 W ActivityManager: 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11867)
03-18 23:00:35.093  1664  3512 W ActivityManager: 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12556)
03-18 23:00:35.093  1664  3512 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12063)
03-18 23:00:35.093  1664  3512 W ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
03-18 23:00:35.099  1664  1664 W art     : Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12502 waiters=0 for 127ms
03-18 23:00:35.109  1664  2823 I ActivityManager: Process com.bideasy_rn (pid 3408) has died
03-18 23:00:35.154  1664  3271 I OpenGLRenderer: Initialized EGL, version 1.4
03-18 23:00:35.180  1311  1348 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-18 23:00:35.188  1664  2842 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
03-18 23:00:35.192  1311  2147 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-18 23:00:35.194  1311  1372 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-18 23:00:35.196  1311  2147 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-18 23:00:35.225  1311  2147 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-18 23:00:35.237  1311  2147 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-18 23:00:35.779  2036  2208 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
03-18 23:00:35.779  2036  2208 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
03-18 23:00:35.822  1664  1685 W WindowAnimator: Failed to dispatch window animation state change.
03-18 23:00:35.822  1664  1685 W WindowAnimator: android.os.DeadObjectException
03-18 23:00:35.822  1664  1685 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
03-18 23:00:35.822  1664  1685 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
03-18 23:00:35.822  1664  1685 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
03-18 23:00:35.822  1664  1685 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
03-18 23:00:35.822  1664  1685 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
03-18 23:00:35.822  1664  1685 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
03-18 23:00:35.822  1664  1685 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
03-18 23:00:35.822  1664  1685 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
03-18 23:00:35.822  1664  1685 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
03-18 23:00:35.822  1664  1685 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
03-18 23:00:35.822  1664  1685 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
03-18 23:00:35.822  1664  1685 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:739)
03-18 23:00:35.822  1664  1685 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-18 23:00:35.822  1664  1685 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148)
03-18 23:00:35.822  1664  1685 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-18 23:00:35.822  1664  1685 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
03-18 23:00:40.229  2431  3515 W PlatformStatsUtil: Could not retrieve Usage & Diagnostics setting. Giving up.
03-18 23:00:40.248  1664  2541 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
03-18 23:00:45.289  2431  3515 W PlatformStatsUtil: Could not retrieve Usage & Diagnostics setting. Giving up.
03-18 23:01:00.054  1311  1351 D hwcomposer: hw_composer sent 2004 syncs in 60s
```

### Reproduction

Unknown as to what causes this, or what area of code. It's a fairly large RN project.

### Additional Information

* React Native version: 0.42
* Platform: Android
* Operating System: MacOS
* Dev tools: Android Studio

**Comment by hramos** [comment]
We're cutting down on the number of outstanding issues, in order to allow us to focus. I'm closing this issue because it has been open for over 60 days with no activity. If you think it should still be opened let us know why. PRs are always welcome.
