### ISSUE TITLE
Reload app on android device issue on windows (ERROR  EBUSY: resource busy or locked)

### ISSUE THREAD

**Issue by farhan687** [facebook/react-native#13022]
### Description

I have connected android device and then I ran following commands on different terminal tabs:
`react-native start`
`react-native run-android`

App is working fine for the first time. 
After changing the content in `index.android.js` file, I tap Reload option from dev menu of the device, and then it shows analyzing and start transforming modules for couple of seconds and suddenly it stops with the following error.

![native-error](https://cloud.githubusercontent.com/assets/6059027/24088269/6c76d2e2-0d4e-11e7-91c3-300651c8b0da.png)

`
ERROR  EBUSY: resource busy or locked,
rename 'C:\Users\Farhan\AppData\Local\Temp\react-native-packager-cache-bc7c6964\1f\ad664aAppRegistry.js.meta.4164767065' -> 'C:\Users\Farhan\AppData\Local\Temp\react-native-packager-cache-bc7c6964\1f\ad664aAppRegistry.js.meta'
{"errno":-4082,"code":"EBUSY","syscall":"rename","path":"C:\\Users\\Farhan\\AppData\\Local\\Temp\\react-native-packager-cache-bc7c6964\\1f\\ad664aAppRegistry.js.meta.4164767065","dest":"C:\\Users\\Farhan\\AppData\\Local\\Temp\\react-native-packager-cache-bc7c6964\\1f\\ad664aAppRegistry.js.meta"}
Error: EBUSY: resource busy or locked, rename 'C:\Users\Farhan\AppData\Local\Temp\react-native-packager-cache-bc7c6964\1f\ad664aAppRegistry.js.meta.4164767065' -> 'C:\Users\Farhan\AppData\Local\Temp\react-native-packager-cache-bc7c6964\1f\ad664aAppRegistry.js.meta'
    at Error (native)
    at Object.fs.renameSync (fs.js:809:18)
    at writeFileSync (E:\Work\appbaseWork\native\HelloWorld\node_modules\write-file-atomic\index.js:95:8)
    at Object.writeSync (E:/Work/appbaseWork/native/HelloWorld/node_modules/react-native/packager/src/lib/TransformCache.js:138:3)
    at _getTransformedCode (E:/Work/appbaseWork/native/HelloWorld/node_modules/react-native/packager/src/node-haste/Module.js:296:22)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
` 

**It looks like npm issue with windows. It would be very helpful if anybody can provide me solution or any helpful link to get rid off this issue.**

### Reproduction

Steps:
On windows 10 
- `react-native start`
- `react-native run-android`
- change contend and tap reload option on device

### Additional Information

* React Native version: 0.42.2
* Platform: Android
* Operating System: Windows 10
* Dev tools: Android device - android version 5.1.1

**Comment by hramos** [comment]
We're cutting down on the number of outstanding issues, in order to allow us to focus. I'm closing this issue because it has been open for over 60 days with no activity. If you think it should still be opened let us know why. PRs are always welcome.

**Comment by phamhuyhoang95** [comment]
I have the same issue, after running well few time I get exactly what happened to him the problem still exist!

OS: window 10
react-native-cli: 2.0.1
react-native: 0.45.1
emulator: Genymotion
npm version: 5.0.3
nodejs : 4.3.0
![error](https://user-images.githubusercontent.com/17705370/27515720-7b87b09e-59d4-11e7-81e6-c90bec415942.png)

I try to remove node_modules folder and reinstall again but nothing work

**Comment by Ehsan0007** [comment]
i have also same issue after building  app packeger loader give error  
![image](https://user-images.githubusercontent.com/16970748/28365792-c7acb470-6c3e-11e7-8a09-8db994dce8be.png)

**Comment by sabiya115** [comment]
i have also same issue, any suggestions would be helpful.

Bundling `index.android.js`  [development, non-minified, hmr enabled]  0.0% (1/563), failed.
Error: EBUSY: resource busy or locked, rename 'C:\Users\admin\AppData\Local\Temp\react-native-packager-cache-14500f530db20da864db142a5d2446251200d698\cache\6c\b1190407433b50f6c3dc6af5d8e91f3bff2431.947356251' -> 'C:\Users\admin\AppData\Local\Temp\react-native-packager-cache-14500f530db20da864db142a5d2446251200d698\cache\6c\b1190407433b50f6c3dc6af5d8e91f3bff2431'
    at Error (native)
    at Object.fs.renameSync (fs.js:810:18)
    at writeFileSync (d:\sabiya\PROJECTS\AndroidCaliva\Caliva_Android\node_modules\write-file-atomic\index.js:124:8)
    at FileBasedCache.writeSync (d:\sabiya\PROJECTS\AndroidCaliva\Caliva_Android\node_modules\metro-bundler\src\lib\TransformCaching.js:138:5)
    at d:\sabiya\PROJECTS\AndroidCaliva\Caliva_Android\node_modules\metro-bundler\src\node-haste\Module.js:302:38
    at next (native)
    at step (d:\sabiya\PROJECTS\AndroidCaliva\Caliva_Android\node_modules\metro-bundler\src\node-haste\Module.js:13:445)
    at d:\sabiya\PROJECTS\AndroidCaliva\Caliva_Android\node_modules\metro-bundler\src\node-haste\Module.js:13:605
    at process._tickCallback (internal/process/next_tick.js:109:7)
Error: EBUSY: resource busy or locked, rename 'C:\Users\admin\AppData\Local\Temp\react-native-packager-cache-14500f530db20da864db142a5d2446251200d698\cache\6c\b1190407433b50f6c3dc6af5d8e91f3bff2431.947356251' -> 'C:\Users\admin\AppData\Local\Temp\react-native-packager-cache-14500f530db20da864db142a5d2446251200d698\cache\6c\b1190407433b50f6c3dc6af5d8e91f3bff2431'
    at Error (native)
    at Object.fs.renameSync (fs.js:810:18)
    at writeFileSync (d:\sabiya\PROJECTS\AndroidCaliva\Caliva_Android\node_modules\write-file-atomic\index.js:124:8)
    at FileBasedCache.writeSync (d:\sabiya\PROJECTS\AndroidCaliva\Caliva_Android\node_modules\metro-bundler\src\lib\TransformCaching.js:138:5)
    at d:\sabiya\PROJECTS\AndroidCaliva\Caliva_Android\node_modules\metro-bundler\src\node-haste\Module.js:302:38
    at next (native)
    at step (d:\sabiya\PROJECTS\AndroidCaliva\Caliva_Android\node_modules\metro-bundler\src\node-haste\Module.js:13:445)
    at d:\sabiya\PROJECTS\AndroidCaliva\Caliva_Android\node_modules\metro-bundler\src\node-haste\Module.js:13:605
    at process._tickCallback (internal/process/next_tick.js:109:7)
Error: EBUSY: resource busy or locked, rename 'C:\Users\admin\AppData\Local\Temp\react-native-packager-cache-14500f530db20da864db142a5d2446251200d698\cache\6c\b1190407433b50f6c3dc6af5d8e91f3bff2431.947356251' -> 'C:\Users\admin\AppData\Local\Temp\react-native-packager-cache-14500f530db20da864db142a5d2446251200d698\cache\6c\b1190407433b50f6c3dc6af5d8e91f3bff2431'
    at Error (native)
    at Object.fs.renameSync (fs.js:810:18)
    at writeFileSync (d:\sabiya\PROJECTS\AndroidCaliva\Caliva_Android\node_modules\write-file-atomic\index.js:124:8)
    at FileBasedCache.writeSync (d:\sabiya\PROJECTS\AndroidCaliva\Caliva_Android\node_modules\metro-bundler\src\lib\TransformCaching.js:138:5)
    at d:\sabiya\PROJECTS\AndroidCaliva\Caliva_Android\node_modules\metro-bundler\src\node-haste\Module.js:302:38
    at next (native)
    at step (d:\sabiya\PROJECTS\AndroidCaliva\Caliva_Android\node_modules\metro-bundler\src\node-haste\Module.js:13:445)
    at d:\sabiya\PROJECTS\AndroidCaliva\Caliva_Android\node_modules\metro-bundler\src\node-haste\Module.js:13:605
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by nukes88** [comment]
has this ever been fixed?

**Comment by RiBj1993** [comment]
npm install --save

**Comment by senthilkumar04** [comment]
@farhan687 @phamhuyhoang95 This is due to the security restrictions which is made on your AppData folder. The packager which starts automatically when building the package does not have admin privileges. So follow the steps to fix it:
1. Start the packager in a seperate cmd from the project folder : react-native start "project-name" --port xxxx
2. Run "react-native run-android --port xxxx" from your project folder
3. After the app loads go to the developer options by pressing Ctrl + M (Windows) and in the debud server host type : "localhost:xxxx"

The port number has to be same in the commands.
