### ISSUE TITLE
packager creating invalid source maps?

### ISSUE THREAD

**Issue by SEAPUNK** [facebook/react-native#13059]
### Description

I'm trying to hook up react-native-webpack-server to react-native (due to our project setup, we need webpack), but during builds, we can't get source maps to correctly build.

Investigating the problem, it turns out that react-native's packager seems to generate source maps that the `source-map` module doesn't like. (See: https://github.com/mozilla/source-map/issues/258)

### Reproduction

0. have react-native cli and yarn globally installed
1. `git clone https://github.com/SEAPUNK/rn-source-map-problem-demo`
2. `cd rn-source-map-problem-demo`
3. `yarn install`
4. `react-native start`
5. (in another window) `node problem-demo.js`

The repo is a clean `react-native init` setup, with `index.ios.js` adjusted for our scenario.

Stack trace output in problem-demo.js should look something like this:

```
Error: No element indexed by null
    at ArraySet_at [as at] (/Users/seapunk/code/a/b/node_modules/source-map/lib/array-set.js:92:9)
    at IndexedSourceMapConsumer_parseMappings [as _parseMappings] (/Users/seapunk/code/a/b/node_modules/source-map/lib/source-map-consumer.js:1050:44)
    at IndexedSourceMapConsumer.get (/Users/seapunk/code/a/b/node_modules/source-map/lib/source-map-consumer.js:68:12)
    at IndexedSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/Users/seapunk/code/a/b/node_modules/source-map/lib/source-map-consumer.js:132:22)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/Users/seapunk/code/a/b/node_modules/source-map/lib/source-node.js:80:24)
    at got.then.then.then (/Users/seapunk/code/a/b/problem-demo.js:24:23)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

### Solution

Not sure. Either the source map is correct and `source-map` needs to support it, or the packager's source map generation should be fixed.

### Additional Information

* React Native version: 0.42
* Platform: iOS (but probably also on android)
* Operating System: N/A (but using macOS)
* Dev tools: N/A

**Comment by hramos** [comment]
We're cutting down on the number of outstanding issues, in order to allow us to focus. I'm closing this issue because it has been open for over 60 days with no activity. If you think it should still be opened let us know why. PRs are always welcome.

**Comment by SEAPUNK** [comment]
I want this issue to remain open because the problem still stands.

**Comment by SEAPUNK** [comment]
Also, I strongly believe that your "60 days inactive" condition for automatically closing issues is a bad one, which is likely to make many reporters angry. Issues should only be able to be automatically closed if further instructions to progress this issue have been given, and nobody has contributed to the issue since.

**Comment by hramos** [comment]
Note that only issues with 0 comments that are older than 60 days are being closed. I think that's a fair cutoff considering that the chances of someone jumping in to help after that point are not that great.

I'm OK with re-opening issues where the OP is still actively invested though.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
