### ISSUE TITLE
Default Timepicker randomly crash on Android release version

### ISSUE THREAD

**Issue by kenma9123** [facebook/react-native#13057]
### Description

It's a hard crash randomly when somebody is opening the default Timepicker(`TimePickerAndroid`) on android(release version). It happens on random phone. I can't reproduce it myself. On genymotion I can't seem to launch the picker it always make the emulator crash. But google developer console was able to track people having crash and here's the log. 

```
android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class android.widget.TimePicker
	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at android.app.TimePickerDialog.<init>(TimePickerDialog.java:121)
	at android.app.TimePickerDialog.<init>(TimePickerDialog.java:81)
	at com.facebook.react.modules.timepicker.DismissableTimePickerDialog.<init>(DismissableTimePickerDialog.java:38)
	at com.facebook.react.modules.timepicker.TimePickerDialogFragment.createDialog(TimePickerDialogFragment.java:55)
	at com.facebook.react.modules.timepicker.TimePickerDialogFragment.onCreateDialog(TimePickerDialogFragment.java:36)
	at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:408)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
	at android.app.BackStackRecord.run(BackStackRecord.java:793)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5551)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
Caused by: android.view.InflateException: Binary XML file line #20: Error inflating class android.widget.TimePicker
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	... 20 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
	... 25 more
Caused by: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class android.widget.RadialTimePickerView
	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at android.widget.TimePickerClockDelegate.<init>(TimePickerClockDelegate.java:140)
	at android.widget.TimePicker.<init>(TimePicker.java:83)
	at android.widget.TimePicker.<init>(TimePicker.java:70)
	at android.widget.TimePicker.<init>(TimePicker.java:66)
	... 27 more
Caused by: android.view.InflateException: Binary XML file line #29: Error inflating class android.widget.RadialTimePickerView
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	... 33 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
	... 38 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.res.ColorStateList.getColorForState(int[], int)' on a null object reference
	at android.widget.RadialTimePickerView.<init>(RadialTimePickerView.java:338)
	at android.widget.RadialTimePickerView.<init>(RadialTimePickerView.java:300)
	at android.widget.RadialTimePickerView.<init>(RadialTimePickerView.java:296)
	... 40 more
```

### Reproduction

I can't reproduce it on my real phone. It happens randomly on other phones. That's according to Google Developer console. Tho in Genymotion, it happens most of the time. The app crashes when I open the default Timepicker.

### Solution

I don't have any valid solutions through code for now. I'm just merely reporting it incase somebody has it already encountered. The patch I made is just to provide my users a basic time picker in case they encountered a crash opening the default timepicker.

### Additional Information

* React Native version: 0.42
* Platform: Android
* Operating System:Windows
* Dev tools: Sublime? The latest Android SDK version

**Comment by hramos** [comment]
Please at least provide a sample of your code.

**Comment by kenma9123** [comment]
Actually I'm just using the default code. Nothing fancy. Some phones keep it crashing, some are not.

```
try {
  const {action, hour, minute} = await TimePickerAndroid.open({
    hour: 12,
    minute: 0
  });

  if (action !== TimePickerAndroid.dismissedAction) {
   // handles the `hour` and `minute`
  }
} catch ({code, message}) {
  console.warn('Cannot open time picker. Please try it again.'');
}
```

**Comment by kenma9123** [comment]
@hramos any news about this? I was able to replicate it with an android 6.0 emulator and a real device.

**Comment by kenma9123** [comment]
@hramos I have an update. Yes it only happens for Android 6.0 and up devices.

**Comment by kenma9123** [comment]
anyway I solved the issue by getting rid of the async/await. Normal promise seems to work just fine. I'm not sure but this seems to do the job.

```
  TimePickerAndroid.open({
    hour: 12,
    minute: 0
  }).then(({action, hour, minute}) => {
    if (action !== TimePickerAndroid.dismissedAction) {
     // handles the `hour` and `minute`
    }
  }).catch(() => {
     console.warn('Cannot open time picker. Please try it again.');  
  });
```
