### ISSUE TITLE
NoClassDefFoundError: com.facebook.react.bridge.WritableNativeMap

### ISSUE THREAD

**Issue by pampang** [facebook/react-native#13079]
I've just enter a NoClassDefFoundError when I re-start my MainActivity.
But I don't know the reason why will cause the error.
Can somebody give me a clue to fix it?
Thanks a lot.

```
    java.lang.NoClassDefFoundError: com.facebook.react.bridge.WritableNativeMap
     at com.facebook.react.JSCConfig$1.getConfigMap(JSCConfig.java:14)
     at com.facebook.react.XReactInstanceManagerImpl.onJSBundleLoadedFromServer(XReactInstanceManagerImpl.java:739)
     at com.facebook.react.XReactInstanceManagerImpl.recreateReactContextInBackgroundInner(XReactInstanceManagerImpl.java:399)
     at com.facebook.react.XReactInstanceManagerImpl.createReactContextInBackground(XReactInstanceManagerImpl.java:370)
     at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:213)
     at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:101)
     at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:91)
     at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54)
     at com.shefenqi.mall.MainActivity.onCreate(MainActivity.java:42)
     at android.app.Activity.performCreate(Activity.java:6366)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1124)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2779)
     at android.app.ActivityThread.-wrap11(ActivityThread.java)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
     at android.os.Handler.dispatchMessage(Handler.java:111)
     at android.os.Looper.loop(Looper.java:207)
     at android.app.ActivityThread.main(ActivityThread.java:5968)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800)
```

**Comment by zgxzgxzg** [comment]
Yes, I've met the question as you too.
help.....

**Comment by samhann** [comment]
We are also facing the same issue.

**Comment by get2abhi** [comment]
+1. 
Restarting the device fixes the issue but a fix is needed. Is it related to multidex?

**Comment by nagamanir** [comment]
+1. We are also facing this issue. Can some one help?

**Comment by minzhitang** [comment]
+1

**Comment by get2abhi** [comment]
We solved the problem by following the answer given on SO

https://stackoverflow.com/questions/44568756/noclassdeffounderror-com-facebook-react-bridge-writablenativemap

**Comment by Temereru** [comment]
any solution?
the solution ge2abhi referenced is talking about android 5.1, but I have this bug on android 6.0.1.
is this problem still exists in recent versions?

**Comment by get2abhi** [comment]
we solved the problem by preloading the soloader.

soloader.init()

Will share the exact code Tomorrow.

**Comment by xwartz** [comment]
I have the same issue.

**Comment by get2abhi** [comment]
Write this code in the very beginning of the application

`import com.facebook.soloader.SoLoader;`

```
@Override public void onCreate() {

...
...
SoLoader.init(getApplicationContext(), /* native exopackage */ false);
//SoLoader.loadLibrary("fbjni"); //uncomment this line if the issue is not resolved
}
```

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
