### ISSUE TITLE
Cannot read property 'onStartShouldSetResponderCapture' of undefined RN v0.43.0-rc.4

### ISSUE THREAD

**Issue by prigornitskiy** [facebook/react-native#13080]
### Description

Error log:
```
Cannot read property 'onStartShouldSetResponderCapture' of undefined
handleException @ ExceptionsManager.js:63
handleError @ InitializeCore.js:125
reportFatalError @ error-guard.js:44
guard @ MessageQueue.js:48
callFunctionReturnFlushedQueue @ MessageQueue.js:107
(anonymous) @ debuggerWorker.js:71

ExceptionsManager.js:63 Cannot read property 'onMoveShouldSetResponderCapture' of undefined
handleException @ ExceptionsManager.js:63
handleError @ InitializeCore.js:125
reportFatalError @ error-guard.js:44
guard @ MessageQueue.js:48
callFunctionReturnFlushedQueue @ MessageQueue.js:107
(anonymous) @ debuggerWorker.js:71

ExceptionsManager.js:63 Cannot read property 'onTouchEndCapture' of undefined
handleException @ ExceptionsManager.js:63
handleError @ InitializeCore.js:125
reportFatalError @ error-guard.js:44
guard @ MessageQueue.js:48
callFunctionReturnFlushedQueue @ MessageQueue.js:107
(anonymous) @ debuggerWorker.js:71

```

Log from google play:
```
`com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'u[n]'), stack:
getListener@95:1029
n@103:62
i@103:156
s@104:587
c@103:340
i@100:95
p@103:800
n@115:385
extractEvents@115:2987
extractEvents@95:1297
handleTopLevel@109:179
<unknown>@108:595
a@111:298
c@111:60
perform@150:596
batchedUpdates@143:464
i@144:358
i@111:90
u@111:150
_receiveRootNodeIDEvent@108:567
receiveTouches@108:941
value@19:2897
<unknown>@19:1013
<unknown>@19:106
value@19:985
	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:99)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:83)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:141)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:154)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
	at java.lang.Thread.run(Thread.java:761)`
```

### Additional Information

I am used FlatList, this is only in android. When i tap button in renderItem sometimes see this error. In release build app crashing

* React Native version: v0.43.0-rc.4
* Platform: Android
* Development Operating System: MacOS
* Dev tools: Android Studio 2.3

**Comment by prigornitskiy** [comment]
## Step to reproduce
Rewind the flatList from the bottom up and click on the button when the application scrolls

**Comment by AdriaRios** [comment]
+1

**Comment by AdriaRios** [comment]
It my case, it happens when I make click in an <Image> that contains a <Text> inside (all inside virtualist).

**Comment by snowjade** [comment]
doing as @AdriaRios said works for me . It is ridiculous.

**Comment by dastoori** [comment]
I have the same problem on v0.43.1 (only on Android).
I have something like `<Text>{123}</Text>` (`123` is a number) and when i tap the text area, i get this error

**Comment by stefalda** [comment]
Same problem with RN 0.43.2 Android... but I'm unable to find the Text causing the error...

**Comment by rouge3351** [comment]
+1

**Comment by sunnylqm** [comment]
this should be fixed in 0.44.0-rc.0 https://github.com/facebook/react-native/commit/17cb70efdd1ed6378677e720a022c9d83ad87dd6

**Comment by tsiiiboho** [comment]
I get this issue in Android where I have a list of TouchableOpacity items with onPressed functions.

**Comment by baotoan1905** [comment]
same issue here. +1

**Comment by rayjoe716** [comment]
`<Text>{this.state.integer.toString()}</Text>` worked for me
