### ISSUE TITLE
Packager not handling .babelignore'd files due to sourcemap generation logic

### ISSUE THREAD

**Issue by kevinold** [facebook/react-native#13168]
### Description

I have a need to bundle a pre-optimized external lib with my RN application.  Until RN 0.42 I had been using a `.babelignore` to prevent the packager from trying to optimize this file and choke.

It seems in 0.42 and higher I'm no longer allowed to ignore the file.

This issue has also been reported as https://github.com/facebook/react-native/issues/12071

I've chatted with @loganfsmyth from BabelJS and his comments were:

> cool, I think this is a regression in react-native, their code in that stacktrace is not handling ignored files: https://github.com/facebook/react-native/blob/master/packager/transformer.js#L110, `ast` will be `undefined` if the file was ignored (edited)
> I believe that code was added recently for their faster sourcemap generation logic

### Reproduction Steps and Sample Code

A project running 0.43.0-rc4 which produces a more verbose error than 0.42 does is here:

https://github.com/kevinold/RNBabelIgnoreIssue

Upon running `react-native run-ios` the following error is produced:

```Loading dependency graph, done.
error: bundling: TypeError: Cannot read property 'tokens' of undefined
    at new Generator (/Users/kold/eval-projects/RNBabelIgnoreIssue/node_modules/babel-generator/lib/index.js:51:21)
    at exports.default (/Users/kold/eval-projects/RNBabelIgnoreIssue/node_modules/babel-generator/lib/index.js:19:13)
    at Object.transform (/Users/kold/eval-projects/RNBabelIgnoreIssue/node_modules/react-native/packager/transformer.js:110:20)
    at transformCode (/Users/kold/eval-projects/RNBabelIgnoreIssue/node_modules/react-native/packager/src/JSTransformer/worker/worker.js:91:31)
    at exports.transformAndExtractDependencies (/Users/kold/eval-projects/RNBabelIgnoreIssue/node_modules/react-native/packager/src/JSTransformer/worker/worker.js:148:3)
    at handle (/Users/kold/eval-projects/RNBabelIgnoreIssue/node_modules/worker-farm/lib/child/index.js:41:8)
    at process.<anonymous> (/Users/kold/eval-projects/RNBabelIgnoreIssue/node_modules/worker-farm/lib/child/index.js:47:3)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:194:7)
TransformError: /Users/kold/eval-projects/RNBabelIgnoreIssue/epublican-native-context-opt.js: Cannot read property 'tokens' of undefined
Bundling `index.ios.js`  99.0% (403/405), failed.
```

### Solution

Handle ignored files in the packager: https://github.com/facebook/react-native/blob/master/packager/transformer.js#L110

### Additional Information

* React Native version: Broken: 0.42-0.43.0-rc4, works on 0.41
* Platform: iOS (I assume Android too)
* Development Operating System: OS X El Capitan

**Comment by kevinold** [comment]
@davidaurelio Hi David, see this issue.  Adding you here as this might be related to your recent patch (https://github.com/facebook/react-native/commit/0849f84df26e4c56f5763375363bae90d94015fe#diff-4676ea0b3c55c65c3929aa993144f07f).

**Comment by kevinold** [comment]
@davidaurelio Any chance you could look into this?

@loganfsmyth Would you be able to provide me with a bit of guidance on a patch for this issue if David is not able to?

**Comment by kevinold** [comment]
As a workaround I am using [haul](https://github.com/callstack-io/haul) to package my app with my ignored files in `.babelrc` instead of a `.babelignore` like so:

```
{
  "presets": ["react-native"],
  "ignore": [
    "my-ignored-lib.js"
  ]
}
```

**Comment by alexanderkjeldaas** [comment]
I'm having this issue, but with 0.45.0-rc.0, I'm getting out of memory. The behavior is not the same as with 0.40.0:
```
transform[stdout]:
transform[stdout]: <--- Last few GCs --->
transform[stdout]:
transform[stdout]: [24516:0x293f6c0]    67948 ms: Mark-sweep 1411.8 (1497.5) -> 1411.3 (1501.0) MB, 2285.6 / 0.0 ms  allocation failure GC in old space requested
transform[stdout]: [24516:0x293f6c0]    70247 ms: Mark-sweep 1411.3 (1501.0) -> 1411.3 (1470.0) MB, 2298.1 / 0.0 ms  last resort
transform[stdout]: [24516:0x293f6c0]    72527 ms: Mark-sweep 1411.3 (1470.0) -> 1411.3 (1470.0) MB, 2280.0 / 0.0 ms  last resort
transform[stdout]:
transform[stdout]:
transform[stdout]: <--- JS stacktrace --->
transform[stdout]:
transform[stdout]: ==== JS stack trace =========================================
transform[stdout]:
transform[stdout]: Security context: 0xca215ea66a1 <JS Object>
transform[stdout]:     2: parseExprOp [/home/astor/code/accounting-common2/app-react/rn-code/node_modules/babylon/lib/index.js:~3416] [pc=0x4bbbf43ea8](this=0x684952922d9 <a Parser with map 0x2d43317b7999>,left=0x337d1acdc149 <a Node with map 0x2d43317c8351>,leftStartPos=1220248,leftStartLoc=0x337d1acdc0d9 <a Position with map 0x2d43317c56f9>,minPrec=-1,noIn=0x28c0c4c02311 <undefined>)
transform[stdout]:     3: parseMaybeAssign [/ho...
transform[stdout]:
transform[stderr]: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
transform[stderr]:  1: node::Abort() [/usr/bin/nodejs]
transform[stderr]:  2: 0x134e91c [/usr/bin/nodejs]
transform[stderr]:  3:
transform[stderr]: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/bin/nodejs]
transform[stderr]:  4:
transform[stderr]: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/bin/nodejs]
transform[stderr]:  5: v8::internal::Factory::NewUninitializedFixedArray(int) [/usr/bin/nodejs]
transform[stderr]:  6: 0xe1f0f5 [/usr/bin/nodejs]
transform[stderr]:  7:
transform[stderr]: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/bin/nodejs]
transform[stderr]:  8: 0x4bbb7843a7
```

**Comment by alexanderkjeldaas** [comment]
I still have the same out-of-memory issue with 0.46.4

**Comment by GarimaMathur07** [comment]
@alexanderkjeldaas did you find any solution for Android?

**Comment by sujitpk-perennial** [comment]
@alexanderkjeldaas @GarimaMathur07  I am also getting JavaScript heap out of memory issue for large file. How you resolved this?
