### ISSUE TITLE
debug apk also crash .  android log ,  one   bug?

### ISSUE THREAD

**Issue by hongyang51** [facebook/react-native#13215]
`  
  java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                          at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                          at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                          at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)
                                                                       Caused by: java.lang.IllegalStateException: closed
                                                                          at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:164)
                                                                          at com.facebook.react.devsupport.JSPackagerWebSocketClient.closeWebSocketQuietly(JSPackagerWebSocketClient.java:103)
                                                                          at com.facebook.react.devsupport.JSPackagerWebSocketClient.closeQuietly(JSPackagerWebSocketClient.java:97)
                                                                          at com.facebook.react.devsupport.DevServerHelper$2.doInBackground(DevServerHelper.java:142)
                                                                          at com.facebook.react.devsupport.DevServerHelper$2.doInBackground(DevServerHelper.java:138)
                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                          at java.lang.Thread.run(Thread.java:818) 

`

**Comment by Rcrosp** [comment]
java.lang.RuntimeException: An error occurred while executing doInBackground()
AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
AndroidRuntime: Caused by: java.lang.IllegalStateException: closed
AndroidRuntime: 	at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:164)
AndroidRuntime: 	at com.facebook.react.packagerconnection.ReconnectingWebSocket.closeWebSocketQuietly(ReconnectingWebSocket.java:110)
AndroidRuntime: 	at com.facebook.react.packagerconnection.ReconnectingWebSocket.closeQuietly(ReconnectingWebSocket.java:103)
AndroidRuntime: 	at com.facebook.react.packagerconnection.JSPackagerClient.close(JSPackagerClient.java:96)
AndroidRuntime: 	at com.facebook.react.devsupport.DevServerHelper$2.doInBackground(DevServerHelper.java:158)
AndroidRuntime: 	at com.facebook.react.devsupport.DevServerHelper$2.doInBackground(DevServerHelper.java:154)
AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
AndroidRuntime: 	... 3 more

AndroidRuntime: 	at okhttp3.internal.ws.Rea

**Comment by Rcrosp** [comment]
I had the same crash .react-native 0.43.2 android to debug apk also crash . android log , one bug? on 30 Mar

**Comment by hramos** [comment]
If you're seeing this, please open a new issue and make sure to fill out the entire template.
