### ISSUE TITLE
Failed to upgrade RN with react-native-git-upgrade

### ISSUE THREAD

**Issue by xareelee** [facebook/react-native#13366]
I tried to use `react-native-git-upgrade` to upgrade RN from 0.43.1 to 0.43.2, but it failed.

```
$ react-native-git-upgrade
git-upgrade info Check for updates 
module.js:472
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
git-upgrade WARN Check for latest version failed Command 'npm view react-native-git-upgrade@latest version' exited with code 1:
git-upgrade WARN Check for latest version failed stderr: undefinedmodule.js:472
git-upgrade WARN Check for latest version failed     throw err;
git-upgrade WARN Check for latest version failed     ^
git-upgrade WARN Check for latest version failed 
git-upgrade WARN Check for latest version failed Error: Cannot find module 'semver'
git-upgrade WARN Check for latest version failed     at Function.Module._resolveFilename (module.js:470:15)
git-upgrade WARN Check for latest version failed     at Function.Module._load (module.js:418:25)
git-upgrade WARN Check for latest version failed     at Module.require (module.js:498:17)
git-upgrade WARN Check for latest version failed     at require (internal/module.js:20:19)
git-upgrade WARN Check for latest version failed     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
git-upgrade WARN Check for latest version failed     at Module._compile (module.js:571:32)
git-upgrade WARN Check for latest version failed     at Object.Module._extensions..js (module.js:580:10)
git-upgrade WARN Check for latest version failed     at Module.load (module.js:488:32)
git-upgrade WARN Check for latest version failed     at tryModuleLoad (module.js:447:12)
git-upgrade WARN Check for latest version failed     at Function.Module._load (module.js:439:3)
git-upgrade WARN Check for latest version failed 
git-upgrade WARN Check for latest version failed stdout: 
git-upgrade info Using yarn 0.21.3 
git-upgrade info Read package.json files 
git-upgrade info Check declared version 
git-upgrade info Check matching versions 
git-upgrade info Check React peer dependency 
git-upgrade info Check that Git is installed 
git-upgrade info Get information from NPM registry 
module.js:472
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
git-upgrade ERR! An error occurred during upgrade: 
git-upgrade ERR! Error: Command 'npm view react-native@latest --json' exited with code 1:
stderr: undefinedmodule.js:472
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

stdout: 
    at ChildProcess.child.on.code (/usr/local/lib/node_modules/react-native-git-upgrade/cliEntry.js:58:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by xareelee** [comment]
I found the problem is that `npm install -g npm` failed and it brake `npm` itself.
