### ISSUE TITLE
Can't find variable: FlatList

### ISSUE THREAD

**Issue by huowenxuan** [facebook/react-native#13438]
**   
"react": "^16.0.0-alpha.6",
"react-native": "^0.43.1",
**

crash on android

com.facebook.react.common.JavascriptException: TaskQueue: Error with task : Can't find variable: FlatList, stack:
value@650:17942
_renderValidatedComponentWithoutOwnerOrContext@256:8564
_renderValidatedComponent@256:8731
_updateRenderedComponent@256:7741
_performComponentUpdate@256:7178
updateComponent@256:6222
performUpdateIfNecessary@256:5134
performUpdateIfNecessary@201:943
s@199:832
perform@205:596
perform@205:596
perform@199:1544
U@199:1700
closeAll@205:1249
perform@205:683
batchedUpdates@198:464
l@199:954
t@213:65
enqueueSetState@213:939
setState@16:433
<unknown>@650:14764
value@305:1020
a@304:371
<unknown>@104:968
callTimer@99:602
callImmediatesPass@99:1749
callImmediates@99:1865
<unknown>@97:2501
<unknown>@97:108
value@97:2466
<unknown>@97:1043
<unknown>@97:108
value@97:989

	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:99)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:83)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:141)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:207)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
	at java.lang.Thread.run(Thread.java:818)

**Comment by alainib** [comment]
i got the same errror

can't find variable FlatList
