### ISSUE TITLE
Geolocation Inaccurate Android

### ISSUE THREAD

**Issue by parkerdan** [facebook/react-native#13567]
Using React-Native `0.43.2`
Air-BnB Maps `"react-native-maps": "0.13.0"`

Sometimes the coordinates provided from the React-Native Geolocation API are up to 20 miles away from where the blue dot is shown on the `react-native-maps` Map.

This only happens on some Android devices.

The blue dot has always been correct in these situations.

The users have all been on WiFi (at a workplace) in these situations.

Whatever method the `react-native-maps` package uses to get the users location should be used for the React-Native Geolocation API.

I do have a watch on the position so the possibility of a faulty initial reading is not the reason for this.

**Comment by ababba15** [comment]
Yes, it would be cool to be able to get that blue dot coords : )

**Comment by parkerdan** [comment]
Air BnB maps uses google play services, so using this helps `https://www.npmjs.com/package/react-native-google-location`

**Comment by ababba15** [comment]
@parkerdan just tried and got this:

```
06-13 23:10:44.719 15132-15132/com.cltw_2 E/MultiWindowProxy: getServiceInstance failed!
06-13 23:10:45.464 15132-15187/com.cltw_2 E/AndroidRuntime: FATAL EXCEPTION: Thread-1375
                                                            Process: com.cltw_2, PID: 15132
                                                            java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Lcom/google/android/gms/common/api/Api$zza;Lcom/google/android/gms/common/api/Api$zzc;)V in class Lcom/google/android/gms/common/api/Api; or its super classes (declaration of 'com.google.android.gms.common.api.Api' appears in /data/app/com.cltw_2-1/split_lib_dependencies_apk.apk:classes9.dex)
                                                                at com.google.android.gms.location.LocationServices.<clinit>(Unknown Source)
                                                                at com.timhagn.rngloc.LocationProvider.<init>(LocationProvider.java:62)
                                                                at com.timhagn.rngloc.RNGLocationModule.<init>(RNGLocationModule.java:41)
                                                                at com.timhagn.rngloc.RNGLocation.createNativeModules(RNGLocation.java:19)
                                                                at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
                                                                at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1009)
                                                                at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:944)
                                                                at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109)
                                                                at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:746)
                                                                at java.lang.Thread.run(Thread.java:818)
```
