### ISSUE TITLE
letv crashed,maybe because of the name of phone includes chinese

### ISSUE THREAD

**Issue by tigerohuang** [facebook/react-native#13631]
I got the following error:
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0-rc.0",

4-23 22:23:34.093 7291-7355/com.ehscheck E/unknown:React: Exception in native call
                                                           java.lang.IllegalArgumentException: Unexpected char 0x4e50 at 0 in model value: 乐1s
                                                               at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:320)
                                                               at okhttp3.Headers$Builder.add(Headers.java:270)
                                                               at com.facebook.react.modules.network.NetworkingModule.extractHeaders(NetworkingModule.java:556)
                                                               at com.facebook.react.modules.network.NetworkingModule.sendRequest(NetworkingModule.java:225)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368)
                                                               at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138)
                                                               at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                               at android.os.Handler.handleCallback(Handler.java:815)
                                                               at android.os.Handler.dispatchMessage(Handler.java:104)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                               at android.os.Looper.loop(Looper.java:207)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
                                                               at java.lang.Thread.run(Thread.java:818)

**Comment by yschimke** [comment]
@hramos curious about closing this.  Seems like a bug in ReactNative https://github.com/square/okhttp/issues/2802
