### ISSUE TITLE
website JSDOC_ERROR

### ISSUE THREAD

**Issue by vision-ken** [facebook/react-native#13769]
### Description
when running react native website in local, visit http://localhost:8079/react-native/index.html, it works fine. but when I click the 'Docs' link，I got a error in console:
```
error in renderAPI for ../Libraries/Alert/AlertIOS.js
JSDOC_ERROR: There are no input files to process.
    at ExplainSync.verifyOutput (/Users/tangyz/Downloads/tmp/react-native/website/node_modules/jsdoc-api/lib/jsdoc-command.js:108:19)
    at ExplainSync._runJsdoc (/Users/tangyz/Downloads/tmp/react-native/website/node_modules/jsdoc-api/lib/explain-sync.js:32:32)
    at ExplainSync.getOutput (/Users/tangyz/Downloads/tmp/react-native/website/node_modules/jsdoc-api/lib/explain-sync.js:18:19)
    at ExplainSync.execute (/Users/tangyz/Downloads/tmp/react-native/website/node_modules/jsdoc-api/lib/jsdoc-command.js:51:24)
    at Object.explainSync (/Users/tangyz/Downloads/tmp/react-native/website/node_modules/jsdoc-api/lib/jsdoc-api.js:63:18)
    at parseAPIJsDocFormat (/Users/tangyz/Downloads/tmp/react-native/website/server/extractDocs.js:320:29)
    at renderAPI (/Users/tangyz/Downloads/tmp/react-native/website/server/extractDocs.js:460:25)
    at /Users/tangyz/Downloads/tmp/react-native/website/server/extractDocs.js:527:12
    at Array.map (native)
    at extractDocs (/Users/tangyz/Downloads/tmp/react-native/website/server/extractDocs.js:526:28)
```
### Reproduction Steps and Sample Code
Environment:
OS: mac os 10.11.6
Node: v5.8.0

Steps:
```
mkdir tmp && cd tmp
git clone https://github.com/facebook/react-native.git
cd react-native
npm install
cd website
npm install
npm start
open http://localhost:8079/react-native/index.html in Chrome
click the 'Docs' link on top of index.html
```
then error occur.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/website-jsdocerror
