### ISSUE TITLE
0.44.0 ReactNativeAttributePayload.js: Unexpected token

### ISSUE THREAD

**Issue by WhatAKitty** [facebook/react-native#13814]
### Description

After upgrading to 0.44.0 version, the error occurred.
```
error: bundling: SyntaxError: /Users/xuqiang/Git/VIPShare/node_modules/react-native/Libraries/Renderer/src/renderers/native/ReactNativeAttributePayload.js: Unexpected token (40:4)
  38 | type AttributeConfiguration = {
  39 |   [key: string]:
> 40 |     | CustomAttributeConfiguration
     |     ^
  41 |     | AttributeConfiguration /*| boolean*/,
  42 | };
  43 | 
    at Parser.pp$5.raise (/Users/xuqiang/Git/VIPShare/node_modules/babylon/lib/index.js:4246:13)
    at Parser.pp.unexpected (/Users/xuqiang/Git/VIPShare/node_modules/babylon/lib/index.js:1627:8)
    at Parser.pp$7.flowParsePrimaryType (/Users/xuqiang/Git/VIPShare/node_modules/babylon/lib/index.js:5093:8)
    at Parser.pp$7.flowParsePostfixType (/Users/xuqiang/Git/VIPShare/node_modules/babylon/lib/index.js:5099:19)
    at Parser.pp$7.flowParsePrefixType (/Users/xuqiang/Git/VIPShare/node_modules/babylon/lib/index.js:5116:17)
    at Parser.pp$7.flowParseAnonFunctionWithoutParens (/Users/xuqiang/Git/VIPShare/node_modules/babylon/lib/index.js:5121:20)
    at Parser.pp$7.flowParseIntersectionType (/Users/xuqiang/Git/VIPShare/node_modules/babylon/lib/index.js:5135:19)
    at Parser.pp$7.flowParseUnionType (/Users/xuqiang/Git/VIPShare/node_modules/babylon/lib/index.js:5145:19)
    at Parser.pp$7.flowParseType (/Users/xuqiang/Git/VIPShare/node_modules/babylon/lib/index.js:5156:19)
    at Parser.pp$7.flowParseTypeInitialiser (/Users/xuqiang/Git/VIPShare/node_modules/babylon/lib/index.js:4424:19)
Bundling `index.ios.js`  99.5% (1098/1101), failed.
```

### Additional Information

* React Native version: 0.44.0
* Platform: IOS
* Development Operating System:MACOS

**Comment by WhatAKitty** [comment]
Upgrading devDependencies
```
"devDependencies": {
    "babel-jest": "^18.0.0",
    "babel-plugin-flow-react-proptypes": "^1.2.0",
    "babel-preset-react-native": "^1.9.1",
    "esdoc": "^0.5.2",
    "jest": "^18.1.0",
    "jest-react-native": "^18.0.0",
    "react-test-renderer": "16.0.0-alpha.3",
    "reactotron-react-native": "^1.7.0"
  }
```
to 
```
"devDependencies": {
    "babel-jest": "20.0.0",
    "babel-plugin-flow-react-proptypes": "^2.1.3",
    "babel-preset-react-native": "^1.9.1",
    "esdoc": "^0.5.2",
    "jest": "^20.0.0",
    "jest-react-native": "^18.0.0",
    "react-test-renderer": "16.0.0-alpha.6",
    "reactotron-react-native": "^1.7.0"
  }
```
solved the `Unexpected token` error.

**Comment by Daemon1993** [comment]
hi , i have same problem
![image](https://cloud.githubusercontent.com/assets/10513454/25988746/c535399e-372b-11e7-9f63-698fd77313f7.png)

**Comment by WhatAKitty** [comment]
@Daemon1993  your devDependencies?

**Comment by Daemon1993** [comment]
@WhatAKitty thanks, Upgrading react to 16.0.0   solved the error

**Comment by miguelmsanchezm** [comment]
@WhatAKitty @Daemon1993 I have just upgraded my project to React Native version: 0.44.0 and I have exactly the same problem. But I can't figure out how to fix it...

This are my devDependencies
```
  "devDependencies": {
    "ava": "^0.19.1",
    "babel-eslint": "^7.2.3",
    "babel-preset-es2015": "^6.18.0",
    "enzyme": "^2.8.2",
    "flow-bin": "0.46.0",
    "mockery": "^2.0.0",
    "nyc": "^10.3.2",
    "reactotron-apisauce": "^1.11.0",
    "reactotron-react-native": "^1.11.0",
    "reactotron-redux": "^1.11.0",
    "reactotron-redux-saga": "^1.11.0",
    "snazzy": "^7.0.0",
    "standard": "10.0.2",
    "standard-flow": "^1.0.0"
  }
```
**Additional Information**

```
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
```
