### ISSUE TITLE
WebSocket connection no longer valid - Exception in native call

### ISSUE THREAD

**Issue by dobrienlzd** [facebook/react-native#13830]
Web Socket Connection no longer valid.  So am I supposed to be checking for valid socket connections? I don't see anything in documentation about checking for validity of socket connections.  I think I have gotten rid of this a few times by rebooting everything but really this is far from ideal situation. What can be done to prevent this error?

UPDATE:  This seems to be related to debug sessions with emulator.  It appears to be multiple debug sessions being open. The only thing that works is 
1) Close the emulator.
2) Close the chrome browser.
3) restart
4) Cmd M  -> Turn off debugging
5) Cmd M ->  Turn on debugging

Seems like there should be a better way to prevent this error.  It also belongs in the FAQ of documentation etc.

05-08 00:46:00.162 1445-2162/com.abc.android E/unknown:React: Exception in native call
                                                                 com.facebook.react.bridge.JavaJSExecutor$ProxyExecutorException: java.lang.IllegalStateException: WebSocket connection no longer valid
                                                                     at com.facebook.react.devsupport.WebsocketJavaScriptExecutor.executeJSCall(WebsocketJavaScriptExecutor.java:188)
                                                                     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                     at java.lang.Thread.run(Thread.java:841)
                                                                  Caused by: java.lang.IllegalStateException: WebSocket connection no longer valid
                                                                     at com.facebook.react.devsupport.JSDebuggerWebSocketClient.sendMessage(JSDebuggerWebSocketClient.java:154)
                                                                     at com.facebook.react.devsupport.JSDebuggerWebSocketClient.executeJSCall(JSDebuggerWebSocketClient.java:135)
                                                                     at com.facebook.react.devsupport.WebsocketJavaScriptExecutor.executeJSCall(WebsocketJavaScriptExecutor.java:181)
                                                                     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                     at android.os.Handler.handleCallback(Handler.java:733) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                     at android.os.Looper.loop(Looper.java:136) 
                                                                     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                                     at java.lang.Thread.run(Thread.java:841) 
05-08 00:46:00.178 1445-2162/com.mydomain.android E/unknown:React: Exception in native call
                                                                 com.facebook.react.bridge.JavaJSExecutor$ProxyExecutorException: java.lang.IllegalStateException: WebSocket connection no longer valid
                                                                     at com.facebook.react.devsupport.WebsocketJavaScriptExecutor.executeJSCall(WebsocketJavaScriptExecutor.java:188)
                                                                     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                     at java.lang.Thread.run(Thread.java:841)
                                                                  Caused by: java.lang.IllegalStateException: WebSocket connection no longer valid
                                                                     at com.facebook.react.devsupport.JSDebuggerWebSocketClient.sendMessage(JSDebuggerWebSocketClient.java:154)
                                                                     at com.facebook.react.devsupport.JSDebuggerWebSocketClient.executeJSCall(JSDebuggerWebSocketClient.java:135)
                                                                     at com.facebook.react.devsupport.WebsocketJavaScriptExecutor.executeJSCall(WebsocketJavaScriptExecutor.java:181)

### Additional Information

* React Native version: 0.43.4
* Platform:  Android
* Development Operating System: 
* Dev tools: Android Studio 2.3

**Comment by nonameolsson** [comment]
Happens to me as well all the time.

**Comment by murugancmi** [comment]
HI i am also face this same issue, And app  crash how to avoid my app crash because of this issue

**Comment by murugancmi** [comment]
Is there any way to fix this issue

**Comment by Cygnus2112** [comment]
+1

**Comment by sauloaguiar** [comment]
I'm having the same issue in react native version 0.45.1. As I haven't found a workaround so far, I just disabled the debug mode.

**Comment by rcartwright** [comment]
+1
