### ISSUE TITLE
Version 0.44.0 应用一启动闪退 Open the application crash

### ISSUE THREAD

**Issue by lanjie233** [facebook/react-native#13857]
react-native run-android 
installDebug is SUCCESSFUL

但是应用打开（Open the application），就闪退（crash）

* React Native version: 0.44.0
* Platform: Android
* Development Operating System: Windows
* Dev tools:  Android Studio 

05-09 16:38:13.982 15873-15914/cn.miguche.shcs.internal E/AndroidRuntime: FATAL EXCEPTION: mqt_js
                                                                          Process: cn.miguche.shcs.internal, PID: 15873
                                                                          java.lang.RuntimeException: Error calling AppRegistry.runApplication
                                                                              at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
                                                                              at java.lang.Thread.run(Thread.java:818)
                                                                           Caused by: com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
                                                                              at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                              at android.os.Handler.handleCallback(Handler.java:739) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                              at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                              at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208) 
                                                                              at java.lang.Thread.run(Thread.java:818) 
05-09 16:38:19.424 7116-7116/? E/DEVICE_SDKTAG: Error reading from /proc/1.
05-09 16:38:19.426 7116-7116/? E/DEVICE_SDKTAG: Error reading from /proc/2.
05-09 16:38:19.428 7116-7116/? E/DEVICE_SDKTAG: Error reading from /proc/3.
05-09 16:38:19.429 7116-7116/? E/DEVICE_SDKTAG: Error reading from /proc/6.

**Comment by dobrienlzd** [comment]
Look inside package.json for versions of react and react-native.
For example in mine this is what I see:

"react": "^16.0.0-alpha.6",
"react-native": "^0.43.4",

most people believe that when you do:

npm install

You are guaranteed that these versions are the ones installed.  But that is not always the case. Sometimes npm just grabs whatever it can find from internet.

You may need to do:

npm install --save react@16.0.0-alpha.6
npm install --save react-native@0.43.4

Dont assume that 'npm install' puts exactly what you need into node_modules.  You might have to occasionally clean out node_modules

rm -rf node_modules
npm install --save react@16.0.0-alpha.6
npm install --save react-native@0.43.4  // in your case 0.44.0  but check what's in package.json
npm install

Let us know if that fixes it.  (Also note in SOME cases you need to do 'react-native link' after the installs but you should see some messages about this after npm install if that's the case.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/version-0440--open-the-application-crash
