### ISSUE TITLE
Issue with `npm start`:  ERROR  watch EMFILE although open files limit = 65536

### ISSUE THREAD

**Issue by pukhalski** [facebook/react-native#1399]
`ulimit -a` log:
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited
```

Although I am still getting EMFILE error while `npm start`.

```
> react-native@0.3.11 start /node_modules/react-native
> ./packager/packager.sh


 ===============================================================
 |  Running packager on port 8081.       
 |  Keep this packager running while developing on any JS         
 |  projects. Feel free to close this tab and run your own      
 |  packager instance if you prefer.                              
 |                                                              
 |     https://github.com/facebook/react-native                 
 |                                                              
 ===============================================================

Looking for JS files in /


React packager ready.

 ERROR  watch EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"watch"}
Error: watch EMFILE
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at NodeWatcher.watchdir (/node_modules/sane/src/node_watcher.js:144:20)
    at Walker.<anonymous> (/node_modules/react-native/node_modules/sane/src/node_watcher.js:351:12)
    at Walker.emit (events.js:110:17)
    at /node_modules/react-native/node_modules/sane/node_modules/walker/lib/walker.js:69:16
    at FSReqWrap.oncomplete (fs.js:95:15)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE
npm ERR! react-native@0.3.11 start: `./packager/packager.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-native@0.3.11 start script './packager/packager.sh'.
npm ERR! This is most likely a problem with the react-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./packager/packager.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /node_modules/react-native/npm-debug.log
```

**Comment by pukhalski** [comment]
Forgot to insatll watchman. Sorry.

**Comment by abbothzhang** [comment]
@pukhalski, I have run into this issue as well and fix the problem by install watchman
