### ISSUE TITLE
libreactnativejni.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol _ZSt14__once_functor

### ISSUE THREAD

**Issue by JobsSteve** [facebook/react-native#14036]
### Description

I have tried to integerate react native component to my existed android app. But failed for reasons below:
```
dlopen("/data/app/com.xxxxx/lib/arm/libreactnativejni.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "_ZSt14__once_functor" referenced by "**libfb.so**"...
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZSt14__once_functor" referenced by "libfb.so"...
                                                                           at java.lang.Runtime.load(Runtime.java:331)
                                                                           at java.lang.System.load(System.java:981)
                                                                           at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
                                                                           at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
                                                                           at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
                                                                           at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:247)
                                                                           at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
                                                                           at com.facebook.react.bridge.ReactBridge.<clinit>(ReactBridge.java:20)
                                                                           at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
                                                                           at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22)
                                                                           at com.facebook.react.JSCConfig$1.getConfigMap(JSCConfig.java:14)
                                                                           at com.facebook.react.ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader(ReactInstanceManager.java:450)
                                                                           at com.facebook.react.ReactInstanceManager.access$1300(ReactInstanceManager.java:108)
                                                                           at com.facebook.react.ReactInstanceManager$3$1.run(ReactInstanceManager.java:435)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5298)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708)

```
I followed the facebook's guide, but failed every time, I donnot know why and hope anyone can help me. Thanks.

**Comment by JobsSteve** [comment]
PS: it's rn0.44

**Comment by NikolaBorislavovHristov** [comment]
i have the same issue with RN 0.43

**Comment by BolexLiu** [comment]
I have a similar problem. But I found that he was caused by third party sdk. When I eliminated the third party, SDK recovered.

**Comment by BolexLiu** [comment]
I've solved this problem because he's using the same source of the third party SDK's .so dynamic link library as the .so dynamic link library in React native. My approach is to find the third party sdk. Delete the same .so file. That's the solution to this bug.

我已经解决了这个问题，他是由于第三方sdk的so动态链接库与React native中的so动态链接库用了同一份导致的。我的办法是找到这个第三方的sdk。将相同的so文件删除掉。这样做就解决了这个bug。

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.
