### ISSUE TITLE
npm run-script test failed because of rounding change to V8's arithmetic

### ISSUE THREAD

**Issue by dalinaum** [facebook/react-native#1412]
npm run-script test

````
> react-native@0.4.4 test /Users/lameduck/project/react-native
> jest

Using Jest CLI v0.4.5
 PASS  Examples/Movies/__tests__/getImageSource-test.js (0.069s)
 PASS  Libraries/Image/__tests__/resolveAssetSource-test.js (0.268s)
 PASS  Libraries/Utilities/differ/__tests__/deepDiffer-test.js (0.168s)
 FAIL  Libraries/Animation/__tests__/AnimationUtils-test.js (0.356s)
● AnimationUtils › it should interpolate easeInSine
  - Expected: {
    | 0: 0,
    | 1: 0.003805301908254455,
    | 10: 0.35721239031346064,
    | 11: 0.42642356364895395,
    | 12: 0.4999999999999999,
    | 13: 0.5773817382593005,
    | 14: 0.6579798566743311,
    | 15: 0.7411809548974793,
    | 16: 0.8263518223330696,
    | 17: 0.9128442572523416,
    | 18: 0.9999999999999999,
    | 2: 0.01519224698779198,
    | 3: 0.03407417371093169,
    | 4: 0.06030737921409157,
    | 5: 0.09369221296335006,
    | 6: 0.1339745962155613,
    | 7: 0.1808479557110082,
    | 8: 0.233955556881022,
    | 9: 0.2928932188134524
    } toEqual: {
    | 0: 0,
    | 1: 0.003805301908254455,
    | 10: 0.35721239031346064,
    | 11: 0.42642356364895384,
    | 12: 0.4999999999999999,
    | 13: 0.5773817382593005,
    | 14: 0.6579798566743311,
    | 15: 0.7411809548974793,
    | 16: 0.8263518223330696,
    | 17: 0.9128442572523416,
    | 18: 0.9999999999999999,
    | 2: 0.01519224698779198,
    | 3: 0.03407417371093169,
    | 4: 0.06030737921409157,
    | 5: 0.09369221296335006,
    | 6: 0.1339745962155613,
    | 7: 0.1808479557110082,
    | 8: 0.233955556881022,
    | 9: 0.2928932188134524
    }
        at Spec.<anonymous> (/Users/lameduck/project/react-native/Libraries/Animation/__tests__/AnimationUtils-test.js:51:10)
● AnimationUtils › it should interpolate easeInElastic
  - Expected: {
    | 0: 0,
    | 1: 0.0008570943160003016,
    | 10: -0.045618646044515744,
    | 11: -0.01936028903971309,
    | 12: 0.07600123467884114,
    | 13: 0.13030605320629246,
    | 14: -0.012461076179381799,
    | 15: -0.2959846283397618,
    | 16: -0.3176868895106366,
    | 17: 0.2694906924487451,
    | 18: 1,
    | 2: 0.0020526300563455885,
    | 3: 0.0005383775388688477,
    | 4: -0.003807112477441741,
    | 5: -0.005595444524068916,
    | 6: 0.0017092421431128787,
    | 7: 0.014076838118604966,
    | 8: 0.012696991251677569,
    | 9: -0.015625000000000045
    } toEqual: {
    | 0: 0,
    | 1: 0.0008570943160003016,
    | 10: -0.045618646044515744,
    | 11: -0.01936028903971309,
    | 12: 0.07600123467884114,
    | 13: 0.13030605320629246,
    | 14: -0.012461076179381799,
    | 15: -0.29598462833976175,
    | 16: -0.3176868895106366,
    | 17: 0.2694906924487451,
    | 18: 1,
    | 2: 0.0020526300563455885,
    | 3: 0.0005383775388688477,
    | 4: -0.003807112477441741,
    | 5: -0.005595444524068916,
    | 6: 0.0017092421431128787,
    | 7: 0.014076838118604966,
    | 8: 0.012696991251677569,
    | 9: -0.015625000000000045
    }
        at Spec.<anonymous> (/Users/lameduck/project/react-native/Libraries/Animation/__tests__/AnimationUtils-test.js:51:10)
 PASS  Libraries/Utilities/__tests__/MatrixMath-test.js (0.433s)
Waiting on 11 tests..._writableState.buffer is deprecated. Use _writableState.getBuffer() instead.
_writableState.buffer is deprecated. Use _writableState.getBuffer() instead.
 FAIL  packager/react-packager/src/AssetServer/__tests__/AssetServer-test.js
Error: Worker process exited before responding! exit code: null, exit signal: SIGSEGV
stderr:


A worker process has quit unexpectedly! This is bad news, shutting down now!

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "run-script" "test"
npm ERR! node v0.12.2
npm ERR! npm  v2.10.0
npm ERR! code ELIFECYCLE
npm ERR! react-native@0.4.4 test: `jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native@0.4.4 test script 'jest'.
npm ERR! This is most likely a problem with the react-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jest
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lameduck/project/react-native/npm-debug.log
````

cat npm-debug.log

````
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run-script', 'test' ]
2 info using npm@2.10.0
3 info using node@v0.12.2
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'pretest', 'test', 'posttest' ]
6 info pretest react-native@0.4.4
7 info test react-native@0.4.4
8 verbose unsafe-perm in lifecycle true
9 info react-native@0.4.4 Failed to exec test script
10 verbose stack Error: react-native@0.4.4 test: `jest`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid react-native@0.4.4
12 verbose cwd /Users/lameduck/project/react-native
13 error Darwin 14.3.0
14 error argv "node" "/usr/local/bin/npm" "run-script" "test"
15 error node v0.12.2
16 error npm  v2.10.0
17 error code ELIFECYCLE
18 error react-native@0.4.4 test: `jest`
18 error Exit status 1
19 error Failed at the react-native@0.4.4 test script 'jest'.
19 error This is most likely a problem with the react-native package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     jest
19 error You can get their info via:
19 error     npm owner ls react-native
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
````

**Comment by brentvatne** [comment]
Being tracked in #1382 now :smile: thanks for the report @dalinaum
