### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Error in callNativeModules

### ISSUE THREAD

**Issue by xwartz** [facebook/react-native#14152]
### Description

Fabric crash log

```
Fatal Exception: java.lang.RuntimeException: Error in callNativeModules():4,30,9,12,event,transfer,[object Object],364,365,2862,RCTView,[object Object],7793
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:148)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.RuntimeException: Overflow during conversion: "900000000000000000000"
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:148)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
```

### Additional Information

* React Native version: 0.37.0
* Platform: Android
* Development Operating System: macOS
* Dev tools: Android Studio version

**Comment by hramos** [comment]
There isn't sufficient information here to act on the bug report.
