### ISSUE TITLE
"ReferenceError: __DEV__ is not defined" when building React-Native 0.44.0 after npm update

### ISSUE THREAD

**Issue by Smarq** [facebook/react-native#14230]
A few weeks ago, I upgraded to 0.44.0 with relatively no issue. Today, I updated my package.json dependencies, I run 'react-native run-android', my app begins building but it gets halted when it encounters the following issue:

```
error: bundling: ReferenceError: __DEV__ is not defined (While processing preset: "~/repos/WorkIn/node_modules/react-native/Libraries/react-native/react-native-implementation.js")
    at Object.<anonymous> (~/repos/WorkIn/node_modules/react-native/Libraries/react-native/react-native-implementation.js:17:5)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (~/repos/WorkIn/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```
I did this after running `npm update`. This is what my package.json dependencies looked like before: 
```
  "dependencies": {
    "express-jwt": "^5.3.0",
    "jsonwebtoken": "^7.3.0",
    "mongoose": "^4.9.0",
    "prop-types": "^15.5.8",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-fbsdk": "^0.5.0",
    "react-navigation": "^1.0.0-beta.9",
    "react-redux": "^5.0.3",
    "react-router-native": "^4.1.1",
    "redux": "^3.6.0",
    "redux-form": "^6.7.0",
    "redux-thunk": "^2.2.0"
```
and this is what it looked like after:
```
  "dependencies": {
    "express-jwt": "^5.3.0",
    "jsonwebtoken": "^7.4.1",
    "mongoose": "^4.10.3",
    "prop-types": "^15.5.10",
    "react": "^16.0.0-alpha.6",
    "react-native": "^0.44.0",
    "react-native-fbsdk": "^0.5.0",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.5",
    "react-router-native": "^4.1.1",
    "redux": "^3.6.0",
    "redux-form": "^6.7.0",
    "redux-persist": "^4.8.0",
    "redux-thunk": "^2.2.0"
  }
```
EDIT: 
After blowing away node_modules and reinstalling, I have ridden my self of the aforementioned error. Though now, I am presented with this error:
![screenshot_1495920246](https://cloud.githubusercontent.com/assets/2789511/26524484/0c811eb6-42f9-11e7-80b3-46c630a5af56.png)

EDIT 2: 
While experimenting, I found that I am able to get the app to load and work but only when I set debug js remotely to 'ON'. I can only do this once though; Once I stop remote debugging, the app gives me a blank white screen and attempting to start debugging again results in an indefinite load.

EDIT 3:
I have also noticed that the stack trace in errors no longer refer to the actual location in the code. I am attaching another screenshot:
![screenshot_1495989402](https://cloud.githubusercontent.com/assets/2789511/26530394/ef43945e-4399-11e7-9e73-5a8ccae42576.png)

**Comment by Smarq** [comment]
Issue has been resolved with a restart.
