### ISSUE TITLE
Consistently crashing at seemingly random times during development (Android on Windows)

### ISSUE THREAD

**Issue by ChrisPikul510** [facebook/react-native#14253]
This is a bug I've actually been battling for a long time. But it's been happening more frequently since the upgrade to RN 0.44.1. Basically when testing on device with USB plugged in, I can get in roughly 30 - 45 seconds of testing and then the app crashes with the android dialog. Using fabric I have the following entries for it (there's 2 I believe are related)

```
Fatal Exception: java.lang.OutOfMemoryError: Could not allocate JNI Env
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
       at okhttp3.ConnectionPool.put(ConnectionPool.java:135)
       at okhttp3.OkHttpClient$1.put(OkHttpClient.java:149)
       at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:188)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
       at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
       at okhttp3.RealCall.access$100(RealCall.java:33)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
       at java.io.File.fixSlashes(File.java:183)
       at java.io.File.<init>(File.java:130)
       at com.facebook.react.devsupport.StackTraceHelper$StackFrameImpl.<init>(StackTraceHelper.java:43)
       at com.facebook.react.devsupport.StackTraceHelper$StackFrameImpl.<init>(StackTraceHelper.java:31)
       at com.facebook.react.devsupport.StackTraceHelper.convertJsStackTrace(StackTraceHelper.java:115)
       at com.facebook.react.devsupport.DevSupportManagerImpl$3.run(DevSupportManagerImpl.java:294)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

RN: 0.44.1
React: 16.0.0-alpha.6
Platform: Android 6.0.1 (device)
OS: Windows 10 (Creators update)
Node: v7.0.0
NPM: 3.10.8

**Comment by hramos** [comment]
Hey @ChrisPikul510 thanks for reporting this! As it happens, without sufficient repro steps, we can't really act on this issue. The issue tracker is not the best place to get help tracking a crash in a particular app, issues are better suited for reproducible crashes on the React Native core library.

**Comment by ChrisPikul510** [comment]
Ok I think this is part of #9665, since it's always happened regardless of App it seems like. Guess I'll have to investigate further since I didn't bring in or use any of the described packages in the stack trace explicitly.
