### ISSUE TITLE
ImageEditingManager$CleanTask ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mpkuth** [facebook/react-native#14256]
### Description

```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:309)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at android.app.ContextImpl.getExternalCacheDir(ContextImpl.java:532)
       at android.content.ContextWrapper.getExternalCacheDir(ContextWrapper.java:249)
       at android.content.ContextWrapper.getExternalCacheDir(ContextWrapper.java:249)
       at com.facebook.react.modules.camera.ImageEditingManager$CleanTask.doInBackgroundGuarded(ImageEditingManager.java:129)
       at com.facebook.react.modules.camera.ImageEditingManager$CleanTask.doInBackgroundGuarded(ImageEditingManager.java:118)
       at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:34)
       at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:22)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

### Reproduction Steps and Sample Code

```
mReactInstanceManager = ReactInstanceManager.builder()
                .setInitialLifecycleState(mLifecycleState)
                .setNativeModuleCallExceptionHandler(this)
                .setDefaultHardwareBackBtnHandler(this)
                .addPackage(new MainReactPackage())
                .setApplication(getApplication())
                .setJSBundleFile(jsBundlePath)
                .setUseDeveloperSupport(false)
                .setCurrentActivity(this)
                .build();

        mReactRootView.startReactApplication(mReactInstanceManager, mModuleName, mLaunchOptions);
```

Exact reproduction steps are unknown. We received a single crash report from a GT-I9192 device running Android 6.0.1. However, `MainReactPackage` calls `new ImageEditingManager(reactContext),` in `createNativeModules`. The `ImageEditingManager` starts `CleanTask` in it's constructor and in it's `onCatalystInstanceDestroy` method. We do not use this module in our code.

### Solution

An unused React Native feature should not crash the app.

### Additional Information

* React Native version: 0.29.0
* Platform: Android
* Development Operating System: macOS
* Dev tools: Android Studio

**Comment by hramos** [comment]
Hey @mpkuth thanks for reporting this! As it happens, without sufficient repro steps, we can't really act on this issue. The issue tracker is not the best place to get help tracking a single crash. Ideally we'd have something reproducible on master that we can work on.
