### ISSUE TITLE
App get's a syntax error after upgrade to 0.45

### ISSUE THREAD

**Issue by iremlopsum** [facebook/react-native#14373]
### Description

I upgraded from 0.44.2 to 0.45.0 and after that I get and error:

C:\a\swipes-api\mobile\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\index.js:590
      throw err;
      ^

SyntaxError: C:/a/swipes-api/mobile/node_modules/react-native/local-cli/core/index.js: Unexpected token (23:2)
  21 |
  22 | export type RNConfig = {
> 23 |   ...ConfigT,
     |   ^
  24 |   /**
  25 |    * Returns an array of project commands used by the CLI to load
  26 |    */
    at Parser.pp$5.raise (C:\a\swipes-api\mobile\node_modules\babylon\lib\index.js:4373:13)
    at Parser.pp.unexpected (C:\a\swipes-api\mobile\node_modules\babylon\lib\index.js:1716:8)
    at Parser.pp$3.parseIdentifier (C:\a\swipes-api\mobile\node_modules\babylon\lib\index.js:4251:10)
    at Parser.pp$8.flowParseObjectPropertyKey (C:\a\swipes-api\mobile\node_modules\babylon\lib\index.js:5169:90)
    at Parser.pp$8.flowParseObjectType (C:\a\swipes-api\mobile\node_modules\babylon\lib\index.js:5283:26)
    at Parser.pp$8.flowParsePrimaryType (C:\a\swipes-api\mobile\node_modules\babylon\lib\index.js:5462:19)
    at Parser.pp$8.flowParsePostfixType (C:\a\swipes-api\mobile\node_modules\babylon\lib\index.js:5580:19)
    at Parser.pp$8.flowParsePrefixType (C:\a\swipes-api\mobile\node_modules\babylon\lib\index.js:5597:17)
    at Parser.pp$8.flowParseAnonFunctionWithoutParens (C:\a\swipes-api\mobile\node_modules\babylon\lib\index.js:5602:20)
    at Parser.pp$8.flowParseIntersectionType (C:\a\swipes-api\mobile\node_modules\babylon\lib\index.js:5617:19)

### Additional Information

* React Native version: 0.45.0
* Platform: Android (7.1.2)
* Development Operating System: Windows

**Comment by pangpond** [comment]
did you try to re-install `babel-register` or use `ncu -a` to update node_modules package

**Comment by iremlopsum** [comment]
@pangpond I updated it to 6.24.1, but still receiving the same error

**Comment by ccdwyer** [comment]
I had this issue as well, deleting the node_modules folder and reinstalling dependencies got me to the issue in 14366.

**Comment by iremlopsum** [comment]
@ccdwyer same!

**Comment by iremlopsum** [comment]
Fixed by rimrafing node_modules and reinstalling modules

**Comment by antoinerousseau** [comment]
Had to `rm -rf node_modules/` AND `rm package-lock.json` to make it work (using npm 5)

**Comment by Koblaid** [comment]
@iremlopsum Thanks for your solution, removing node_modules and reinstalling worked for me. But I'm confused. Does this mean that my old node_modules differed from the reinstalled one? I thought that this kind of difference is prevented by yarn? (I used yarn)

**Comment by iremlopsum** [comment]
@Koblaid I don't actually understand what is causing this issue. I updated to 0.45.1 and I had to go through the same thing again. It seems like it's the same versions of the things. Maybe some issue with cache?

**Comment by Koblaid** [comment]
@iremlopsum Yes, I remember that `react-native start` has the flag `--reset-cache`. Maybe running this would help. If this is true then it could be worth it to let `react-native-git-upgrade` run the `--reset-cache` command.

**Comment by iremlopsum** [comment]
@Koblaid I guess that would help. Will try that with the next update if the issue remains.

**Comment by dlindahl** [comment]
`rm -rf node_modules && npm cache clean --force && yarn cache clean && watchman watch-del-all && yarn && npm run react-native -- start --reset-cache` did not resolve the error for me. Anyone have any other suggestions?
