### ISSUE TITLE
[0.46] react-native-stage-0 plugin doesn't work in 0.46.0-rc.0?

### ISSUE THREAD

**Issue by ethanyanjiali** [facebook/react-native#14387]
### Description

Upgraded to 0.46.0-rc.0, and the packager gave me an error

/Users/yanjia.li/Projects/penny-mobile/Penny/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

ReferenceError: Unknown plugin "transform-runtime" specified in "/Users/yanjia.li/Projects/penny-mobile/Penny/node_modules/regenerator-transform/package.json" at 0, attempted to resolve relative to "/Users/yanjia.li/Projects/penny-mobile/Penny/node_modules/regenerator-transform" (While processing preset: "/Users/yanjia.li/Projects/penny-mobile/Penny/node_modules/babel-preset-react-native/index.js")
    at /Users/yanjia.li/Projects/penny-mobile/Penny/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/yanjia.li/Projects/penny-mobile/Penny/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/yanjia.li/Projects/penny-mobile/Penny/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/yanjia.li/Projects/penny-mobile/Penny/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/yanjia.li/Projects/penny-mobile/Penny/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/yanjia.li/Projects/penny-mobile/Penny/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/yanjia.li/Projects/penny-mobile/Penny/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

### Reproduction Steps and Sample Code
 my babelrc is 
{
  "presets": ["react-native-stage-0"]
}

### Solution

Not sure yet

### Additional Information

* React Native version: 0.46.0-RC.0
* Platform: iOS
* Development Operating System: MacOS

**Comment by JonnyBurger** [comment]
`babel-preset-react-native-stage-0` is not official and pretty old. It extends an old version of the official `babel-preset-react-native` preset which does not have all the plugins that react-native now needs. 

Most likely you can fix this by removing the `babel-preset-react-native-stage-0` preset and switch to the newest version of `babel-preset-react-native`.

```sh
npm uninstall babel-preset-react-native-stage-0
npm upgrade babel-preset-react-native
```
.babelrc
```diff
{
- "presets": ["react-native-stage-0"]
+ "presets": ["react-native"]
}
```

If you depend on plugins that are specifically in the `react-native-stage-0` preset, you could make a PR to that repo that upgrades the `react-native` preset to the newest version.
