### ISSUE TITLE
TextInput AutoFocus Prop Causes Jest to Crash

### ISSUE THREAD

**Issue by agentilela** [facebook/react-native#14434]
### Reproduction Steps and Sample Code

Broken Test File
```javascript
// __tests__/Sample-test.js
import React from 'react'
import 'react-native'
import { TextInput } from 'react-native'

const mockFunction = () => {return}
const mockValue = 'value'

test('renders correctly', () => {
  const tree = renderer
    .create(
        <TextInput
          autoFocus
          multiline
          onChangeText={mockFunction}
          value={mockValue}
        />
    )
    .toJSON()
  expect(tree).toMatchSnapshot()
})
```

Broken Jest Output
```bash
 FAIL  app/components/__tests__/Sample-test.js
  ● Test suite failed to run

    ProcessTerminatedError: cancel after 2 retries!

      at Farm.<anonymous> (node_modules/worker-farm/lib/farm.js:81:25)
      at Array.forEach (native)
      at Farm.<anonymous> (node_modules/worker-farm/lib/farm.js:75:36)
      at ontimeout (timers.js:386:14)
      at tryOnTimeout (timers.js:250:5)
      at Timer.listOnTimeout (timers.js:214:5)

A worker process has quit unexpectedly! Most likely this is an initialization error.
```

Working Test File
```javascript
// __tests__/Sample-test.js
import React from 'react'
import 'react-native'
import { TextInput } from 'react-native'

const mockFunction = () => {return}
const mockValue = 'value'

test('renders correctly', () => {
  const tree = renderer
    .create(
        <TextInput
          multiline
          onChangeText={mockFunction}
          value={mockValue}
        />
    )
    .toJSON()
  expect(tree).toMatchSnapshot()
})
```

Working Jest Output
```bash
 PASS  app/components/__tests__/Sample-test.js
  ✓ renders correctly (303ms)
```

### Additional Information

Not 100% sure whether this was a bug with react-native or Jest, but just wanted to make you guys aware. Up until now, I am able to run the app properly without any errors, only tests fail. I will keep digging and see if I can find any other side effects.

* React Native version: 0.45.0
* Platform: both
* Development Operating System: macOS

**Comment by chris-griffin** [comment]
Relevant discussion on the jest repo

https://github.com/facebook/jest/issues/3707

**Comment by sospedra** [comment]
The mentioned workaround in here https://github.com/facebook/jest/issues/3707#issuecomment-311169259 worked for me. In the meantime the issue is being fixed ;)
