### ISSUE TITLE
[0.46.0-rc.2] react-native init fails

### ISSUE THREAD

**Issue by sjmueller** [facebook/react-native#14476]
Running `react-native init rn46 --version "0.46.0-rc.2"` fails to create a new project, with exception:

```
npm WARN react-native@0.46.0-rc.2 requires a peer of react@16.0.0-alpha.12 but none was installed.
module.js:472
    throw err;
    ^

Error: Cannot find module 'metro-bundler/build/lib/TerminalClass'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/rn46/node_modules/react-native/local-cli/server/runServer.js:18:18)
    at Module._compile (module.js:571:32)
    at loader (/rn46/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/rn46/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

The generated package.json does not include react:
```
  "dependencies": {
    "react-native": "0.46.0-rc.2"
  }
```

I tried this with node version `v7.9`, `v7.10`, `v8.1`, and yarn `v0.24.6`, all giving the same exception.

**Comment by zhenliliu** [comment]
I have the same issue

**Comment by zhenliliu** [comment]
I have the same problem

**Comment by JobsSteve** [comment]
Me tooooooo

**Comment by JobsSteve** [comment]
0.44以后的这几次升级，太TM蛋疼了，我又不得不退回到44

**Comment by nihgwu** [comment]
`TerminalClass` was renamed to `Terminal` https://github.com/facebook/metro-bundler/commit/c1ff8b5b81f53d359abee0696ba9468d4fae9b85

**Comment by jeanlauliac** [comment]
Sorry about that. We should have published the packager with a breaking-change version number bump but didn't. See explanations on #14477. We're looking into it.

**Comment by jeanlauliac** [comment]
If you try again, I believe this should now work as expected.
