### ISSUE TITLE
Android Websocket errors on closed connections and attempting to send

### ISSUE THREAD

**Issue by ddolheguy** [facebook/react-native#14527]
We have ben seeing a lot of errors on Android using WebSockets with the below error coming through from Google Play.

It seems to be not handled correct when the connection is closed but it's not a error we can easily reproduce.

java.lang.RuntimeException: 
  at com.facebook.react.modules.websocket.WebSocketModule.send(WebSocketModule.java:221)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
  at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
  at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method:0)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
  at android.os.Looper.loop(Looper.java:154)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
  at java.lang.Thread.run(Thread.java:762)

* React Native version: 0.39.1 (We have also tested this on 0.44 with the same issue)
* Platform: Android
* Development Operating System: MacOS

**Comment by hramos** [comment]
I'm afraid that without clear reproduction steps, this issue may not get resolved.

**Comment by ddolheguy** [comment]
Thanks, unfortunately this is something we are struggling with ourselves as we cannot replicate it no matter what we do, but we seeing tons of issues via the app store.

**Comment by hramos** [comment]
Thanks for opening the issue! It does not appear like a community member will be able to reliably reproduce this issue. This may be for several reasons; perhaps it affects a particular app but a minimal repro has not been provided, or the issue may be sporadic. As it happens, we need a concrete set of steps that can demonstrably reproduce the issue as this will allow your fellow community members to validate a fix. We'll close the issue for now, but feel free to submit a new issue once you're able to reliably reproduce the issue locally. Thanks for your understanding!

**Comment by Hitabis** [comment]
@ddolheguy any luck resolving this issue? We are having this exact same issue and it's being reported daily by our users in the Google Play Store. Unfortunately, I cannot offer any reproduction steps either.

### Details
react native:  0.42.0
platform: android
development operating system: macos
