### ISSUE TITLE
java.lang.IllegalStateException: 

### ISSUE THREAD

**Issue by kisubs** [facebook/react-native#14565]
Hello,

I've been getting crash reports on my product from the google play console.

The user uses a Le Eco Max 2 and has Android 7.1

`java.lang.IllegalStateException: 
  at okio.RealBufferedSink.write(RealBufferedSink.java:39)
  at okio.ForwardingSink.write(ForwardingSink.java:35)
  at com.facebook.react.modules.network.ProgressRequestBody$1.write(ProgressRequestBody.java:58)
  at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
  at com.facebook.react.modules.network.ProgressRequestBody.writeTo(ProgressRequestBody.java:48)
  at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:47)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
  at okhttp3.RealCall.access$100(RealCall.java:33)
  at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
  at java.lang.Thread.run(Thread.java:761)`

**Comment by JAGATBARAIYA** [comment]
Getting this as well on LG G5 and Samsung devices. Any solutions?
