### ISSUE TITLE
Okhttp dependencies conflict 

### ISSUE THREAD

**Issue by jishuo1213** [facebook/react-native#14595]
I want to use react-native in my existing app,I follow [this guilde](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html) to do so.When I start my app,I got an error when I use sockt.io:

`06-19 15:42:39.466 8468-8504/com.inspur.playwork:push E/EventThread: Task threw exception
                                                                     java.lang.VerifyError: Rejecting class okhttp3.OkHttpClient because it failed compile-time verification (declaration of 'okhttp3.OkHttpClient' appears in /data/app/com.inspur.playwork-1/base.apk:classes43.dex)
                                                                         at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:443)
                                                                         at io.socket.engineio.client.transports.WebSocket.doOpen(WebSocket.java:42)
                                                                         at io.socket.engineio.client.Transport$1.run(Transport.java:82)
                                                                         at io.socket.thread.EventThread.exec(EventThread.java:55)
                                                                         at io.socket.engineio.client.Transport.open(Transport.java:77)
                                                                         at io.socket.engineio.client.Socket.probe(Socket.java:472)
                                                                         at io.socket.engineio.client.Socket.onOpen(Socket.java:485)
                                                                         at io.socket.engineio.client.Socket.onHandshake(Socket.java:526)
                                                                         at io.socket.engineio.client.Socket.onPacket(Socket.java:499)
                                                                         at io.socket.engineio.client.Socket.access$1000(Socket.java:31)
                                                                         at io.socket.engineio.client.Socket$5.call(Socket.java:313)
                                                                         at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                         at io.socket.engineio.client.Transport.onPacket(Transport.java:134)
                                                                         at io.socket.engineio.client.transports.Polling.access$700(Polling.java:17)
                                                                         at io.socket.engineio.client.transports.Polling$2.call(Polling.java:124)
                                                                         at io.socket.engineio.parser.Parser.decodePayload(Parser.java:251)
                                                                         at io.socket.engineio.client.transports.Polling._onData(Polling.java:134)
                                                                         at io.socket.engineio.client.transports.Polling.onData(Polling.java:106)
                                                                         at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:111)
                                                                         at io.socket.thread.EventThread$2.run(EventThread.java:80)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                         at java.lang.Thread.run(Thread.java:818)
06-19 15:42:39.466 8468-8504/com.inspur.playwork:push E/AndroidRuntime: FATAL EXCEPTION: EventThread
                                                                        Process: com.inspur.playwork:push, PID: 8468
                                                                        java.lang.VerifyError: Rejecting class okhttp3.OkHttpClient because it failed compile-time verification (declaration of 'okhttp3.OkHttpClient' appears in /data/app/com.inspur.playwork-1/base.apk:classes43.dex)
                                                                            at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:443)
                                                                            at io.socket.engineio.client.transports.WebSocket.doOpen(WebSocket.java:42)
                                                                            at io.socket.engineio.client.Transport$1.run(Transport.java:82)
                                                                            at io.socket.thread.EventThread.exec(EventThread.java:55)
                                                                            at io.socket.engineio.client.Transport.open(Transport.java:77)
                                                                            at io.socket.engineio.client.Socket.probe(Socket.java:472)
                                                                            at io.socket.engineio.client.Socket.onOpen(Socket.java:485)
                                                                            at io.socket.engineio.client.Socket.onHandshake(Socket.java:526)
                                                                            at io.socket.engineio.client.Socket.onPacket(Socket.java:499)
                                                                            at io.socket.engineio.client.Socket.access$1000(Socket.java:31)
                                                                            at io.socket.engineio.client.Socket$5.call(Socket.java:313)
                                                                            at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                            at io.socket.engineio.client.Transport.onPacket(Transport.java:134)
                                                                            at io.socket.engineio.client.transports.Polling.access$700(Polling.java:17)
                                                                            at io.socket.engineio.client.transports.Polling$2.call(Polling.java:124)
                                                                            at io.socket.engineio.parser.Parser.decodePayload(Parser.java:251)
                                                                            at io.socket.engineio.client.transports.Polling._onData(Polling.java:134)
                                                                            at io.socket.engineio.client.transports.Polling.onData(Polling.java:106)
                                                                            at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:111)
                                                                            at io.socket.thread.EventThread$2.run(EventThread.java:80)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)`

It seems to be because I use socket.io and react-native,they all use okhttp,but the okhttp version they use is different.so I exclude some modlue in my build.gradle file:

    **compile("com.facebook.react:react-native:0.45.1") {
        exclude module:'okhttp'
        exclude module:'okio'
        exclude module:'okhttp-urlconnection'
        exclude module:'okhttp-ws'
    }**

After this,no error when I use socket.io,but when I start my ReactActivity,there's an NoClassFoundExecption because I exlude some module.Is there any suggestion about this error,thank you.

I have another question,I use some native code in my app, and my app abiFilters is 'armeabi', 'armeabi-v7a', 'arm64-v8a', but react-native  ABI configurations is 'armeabi-v7a','x86',how can I to prevent error in arm64 phone.
Here is my app dependencies tree:

+--- io.socket:socket.io-client:0.8.3
|    \--- io.socket:engine.io-client:0.8.3
|         \--- com.squareup.okhttp3:okhttp:3.5.0
|              \--- com.squareup.okio:okio:1.11.0
\--- com.facebook.react:react-native:0.45.1
       +--- javax.inject:javax.inject:1
       +--- com.android.support:appcompat-v7:23.0.1 -> 25.3.1 (*)
       +--- com.facebook.fbui.textlayoutbuilder:textlayoutbuilder:1.0.0
       |    \--- com.facebook.fbui.textlayoutbuilder:staticlayout-proxy:1.0
       +--- com.facebook.fresco:fresco:1.0.1
       |    +--- com.facebook.fresco:drawee:1.0.1
       |    |    \--- com.facebook.fresco:fbcore:1.0.1
       |    +--- com.facebook.fresco:fbcore:1.0.1
       |    \--- com.facebook.fresco:imagepipeline:1.0.1
       |         +--- com.parse.bolts:bolts-tasks:1.4.0
       |         +--- com.facebook.fresco:fbcore:1.0.1
       |         \--- com.facebook.fresco:imagepipeline-base:1.0.1
       |              +--- com.parse.bolts:bolts-tasks:1.4.0
       |              \--- com.facebook.fresco:fbcore:1.0.1
       +--- com.facebook.fresco:imagepipeline-okhttp3:1.0.1
       |    +--- com.squareup.okhttp3:okhttp:3.0.1 -> 3.5.0 (*)
       |    +--- com.facebook.fresco:fbcore:1.0.1
       |    \--- com.facebook.fresco:imagepipeline:1.0.1 (*)
       +--- com.facebook.soloader:soloader:0.1.0
       +--- com.google.code.findbugs:jsr305:3.0.0
       +--- com.squareup.okhttp3:okhttp:3.4.1 -> 3.5.0 (*)
       +--- com.squareup.okhttp3:okhttp-urlconnection:3.4.1
       |    \--- com.squareup.okhttp3:okhttp:3.4.1 -> 3.5.0 (*)
       +--- com.squareup.okhttp3:okhttp-ws:3.4.1
       |    \--- com.squareup.okhttp3:okhttp:3.4.1 -> 3.5.0 (*)
       +--- com.squareup.okio:okio:1.9.0 -> 1.11.0
       \--- org.webkit:android-jsc:r174650

**Comment by iegik** [comment]
Is it relative to: https://github.com/square/okhttp/issues/3411 ?
