### ISSUE TITLE
bundling: NotFoundError: Cannot find entry file index.android.js in any of the roots

### ISSUE THREAD

**Issue by iremlopsum** [facebook/react-native#14736]
### Description

Cloned a repo to a new computer and getting the following error:
    > swipes@0.0.1 start C:\a\swipes-api\mobile
    > node node_modules/react-native/local-cli/cli.js start

    Scanning 722 folders for symlinks in C:\a\swipes-api\mobile\node_modules (30ms)
    ┌────────────────────────────────────────────────────────────────────────────┐
    │  Running packager on port 8081.                                            │
    │                                                                            │
    │  Keep this packager running while developing on any JS projects. Feel      │
    │  free to close this tab and run your own packager instance if you          │
    │  prefer.                                                                   │
    │                                                                            │
    │  https://github.com/facebook/react-native                                  │
    │                                                                            │
    └────────────────────────────────────────────────────────────────────────────┘
    Looking for JS files in
      C:\a\swipes-api\mobile
    error: bundling: NotFoundError: Cannot find entry file index.android.js in any of the roots: ["C:\\a\\swipes-api\\mobile"]
        at DependencyGraph._getAbsolutePath (C:/a/swipes-api/mobile/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:280:11)
        at DependencyGraph.getDependencies (C:/a/swipes-api/mobile/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:218:26)
        at Resolver.getDependencies (C:/a/swipes-api/mobile/node_modules/react-native/packager/src/Resolver/index.js:107:27)
        at C:/a/swipes-api/mobile/node_modules/react-native/packager/src/Bundler/index.js:591:37
        at next (native)
        at step (C:\a\swipes-api\mobile\node_modules\react-native\packager\src\Bundler\index.js:12:445)
        at C:\a\swipes-api\mobile\node_modules\react-native\packager\src\Bundler\index.js:12:605
        at process._tickCallback (internal/process/next_tick.js:103:7)
    Bundling `index.android.js`  0.0% (0/1), failed.

The path is correct where it's searching from. I've been stuck with this for the whole day now.

Is this somehow because there are double backslashes in the path to the index file?

npm start -- --reset-cache results in the same error.
Running yarn start after react-native run-android results in the same issue as well.
npm run start -- --root C:\a\swipes-api\mobile  - No result.

This does not seem to be connected to the previous issue in the RN 0.45.0.

### Additional Information

* React Native version: 0.45.1
* Platform: Android
* Development Operating System: Windows

## Edit:

All new projects with react-native init result in the same issue. Seems to be an issue with the config something something. 

## Edit 2:

The issue seems to live in DependencyGraph and the fact that path doesn't exist in `this._hasteFS.exists(potentialAbsPath))`. And I think that this issue cause because that the path is wrong. if I run `this._hasteFS.getAllFiles()` then paths have weird slashes in them, example `C:/testingA\\node_modules/browser-resolve/node_modules/resolve/test/resolver/biz/node_modules/garply/lib/index.js`

Any ideas?

**Comment by iremlopsum** [comment]
https://github.com/facebook/jest/pull/3887 this solves the issue, just waiting for this to go through, patching manually until then.
