### ISSUE TITLE
React native issues with npm

### ISSUE THREAD

**Issue by divyam3897** [facebook/react-native#14763]
### Is this a bug report?
yes

### Environment
1. `react-native -v`: 
react-native-cli: 2.0.1
react-native: 0.45.1
2. `node -v`: v8.0.0
3. `npm -v`: 5.0.4
4. `yarn --version` (if you use Yarn): 0.24.5

Then, specify:

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): Linux
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Android SDK 23

### Steps to Reproduce

1. create-react-native-app AwesomeProject
2. cd AwesomeProject
3. npm start

### Expected Behavior
Expected to  start a development server for you, and print a QR code in your terminal.

### Actual Behavior
Got these errors (attaching the log)
``` 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.0.4
3 info using node@v8.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle AwesomeProject@0.1.0~prestart: AwesomeProject@0.1.0
6 silly lifecycle AwesomeProject@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle AwesomeProject@0.1.0~start: AwesomeProject@0.1.0
8 verbose lifecycle AwesomeProject@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle AwesomeProject@0.1.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/divyam/summerProjects/AwesomeProject/node_modules/.bin:/home/divyam/nitHack/google-cloud-sdk/bin:/home/divyam/.rbenv/shims:/home/divyam/.rbenv/bin:/home/divyam/.rbenv/shims:/home/divyam/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/divyam/Android/android-sdk/platform-tools
10 verbose lifecycle AwesomeProject@0.1.0~start: CWD: /home/divyam/summerProjects/AwesomeProject
11 silly lifecycle AwesomeProject@0.1.0~start: Args: [ '-c', 'react-native-scripts start' ]
12 silly lifecycle AwesomeProject@0.1.0~start: Returned: code: 1  signal: null
13 info lifecycle AwesomeProject@0.1.0~start: Failed to exec start script
14 verbose stack Error: AwesomeProject@0.1.0 start: `react-native-scripts start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:887:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid AwesomeProject@0.1.0
16 verbose cwd /home/divyam/summerProjects/AwesomeProject
17 verbose Linux 4.11.3-1-ARCH
18 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
19 verbose node v8.0.0
20 verbose npm  v5.0.4
21 error code ELIFECYCLE
22 error errno 1
23 error AwesomeProject@0.1.0 start: `react-native-scripts start`
23 error Exit status 1
24 error Failed at the AwesomeProject@0.1.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by Bombe93** [comment]
Hi,

I think it's was probably best to write in the create-react-native-app repo.

However I have tried in my development environment and I work.

MacOS
 node -v v7.9.0
 npm -v 4.2.0
 react-native-cli: 2.0.1
 react-native: 0.45.1

I found this: https://github.com/react-community/create-react-native-app/issues/233

It may be that it is not compatible with Node > 8.0 and/or npm > 5.0.1

**Comment by divyam3897** [comment]
yes, it's similar. Probably npm > 5.0.0 as react-community/create-react-native-app#233 has 5.0.1 probably.

**Comment by hramos** [comment]
Try using npm 4. Agree that this is best opened in the CRNA repo.
