### ISSUE TITLE
App crashes when receiving "adb shell input swipe x y z c"

### ISSUE THREAD

**Issue by lehoanglu0ng** [facebook/react-native#14774]
### Is this a bug report?

YES

### Have you read the Bugs section of the Contributing to React Native Guide?

YES

### Environment

1. `react-native -v`: 2.0.1
2. `node -v`: v6.10.2
3. `npm -v`: 3.10.10

Then, specify:

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): Windows 10 and macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): IntelliJ Idea

### Steps to Reproduce

(Write your steps here:)

1. Build app to device
2. Open app on device
3. Open cmd on Windows 10
4. Type "adb shell input swipe x y z c"
5. Notice that app crashes

### Expected Behavior

App should not crash

### Actual Behavior

App crashes

### Log

```
InputEventReceiver: Exception dispatching input event.
UncaughtException: java.lang.RuntimeException: Tried to get non-existent cookie
                                                                     at com.facebook.react.uimanager.events.TouchEventCoalescingKeyHelper.getCoalescingKey(SourceFile:75)
                                                                     at com.facebook.react.uimanager.events.TouchEvent.init(SourceFile:90)
                                                                     at com.facebook.react.uimanager.events.TouchEvent.obtain(SourceFile:45)
                                                                     at com.facebook.react.uimanager.JSTouchDispatcher.handleTouchEvent(SourceFile:115)
                                                                     at com.facebook.react.ReactRootView.dispatchJSTouchEvent(SourceFile:151)
                                                                     at com.facebook.react.ReactRootView.onInterceptTouchEvent(SourceFile:127)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1960)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
                                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
                                                                     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
                                                                     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
                                                                     at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
                                                                     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(SourceFile:63)
                                                                     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(SourceFile:63)
                                                                     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
                                                                     at android.view.View.dispatchPointerEvent(View.java:8666)
                                                                     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
                                                                     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
                                                                     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
                                                                     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
                                                                     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
                                                                     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
                                                                     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
                                                                     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
                                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
                                                                     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5807)
                                                                     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5781)
                                                                     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5752)
                                                                     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5897)
                                                                     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                     at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                     at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                     at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5868)
                                                                     at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5920)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)

```

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by hramos** [comment]
Can you clarify what the app is in this instance? Is it a brand new app created using `react-native init`?

**Comment by lehoanglu0ng** [comment]
You can reproduce this bug by using React Native UIExplorer app on CH Play.

**Comment by hramos** [comment]
What is CH Play?

**Comment by lehoanglu0ng** [comment]
Google Play Store on Android device

**Comment by hramos** [comment]
https://play.google.com/store/apps/details?id=name.ratson.uiexplorer&hl=en Is not maintained by us and is likely using an old version.

**Comment by lehoanglu0ng** [comment]
It's just an app you can use to reproduce this bug easily. My main working is this app: https://play.google.com/store/apps/details?id=com.mservice.momotransfer

**Comment by pavankumar9** [comment]
Even me too facing the same issue when using adb swipe. Please let me know if its automation tool issue or has to be fixed in the app:

08-29 03:28:30.378  6548  6548 E AndroidRuntime: java.lang.RuntimeException: Tried to get non-existent cookie
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at com.facebook.react.uimanager.events.g.c(SourceFile:75)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at com.facebook.react.uimanager.events.f.b(SourceFile:90)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at com.facebook.react.uimanager.events.f.a(SourceFile:45)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at com.facebook.react.uimanager.f.b(SourceFile:115)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at com.facebook.react.n.b(SourceFile:151)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at com.facebook.react.n.onInterceptTouchEvent(SourceFile:127)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:2765)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:9514)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5996)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6048)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:600)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-29 03:28:30.378  6548  6548 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-29 03:28:30.379   624   635 W ActivityManager:   Force finishing activity com.goibibo/.MyReactActivity
