### ISSUE TITLE
AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher

### ISSUE THREAD

**Issue by nb7123** [facebook/react-native#14802]
FATAL EXCEPTION: OkHttp Dispatcher
                                                              Process: com.firstapp, PID: 16371
                                                              java.lang.IllegalStateException: closed
                                                                  at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:374)
                                                                  at okio.Buffer.writeAll(Buffer.java:993)
                                                                  at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:106)
                                                                  at okhttp3.ResponseBody.bytes(ResponseBody.java:128)
                                                                  at okhttp3.ResponseBody.string(ResponseBody.java:154)
                                                                  at com.facebook.react.devsupport.DevServerHelper$8.onResponse(DevServerHelper.java:577)
                                                                  at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
                                                                  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                  at java.lang.Thread.run(Thread.java:848)

When i init a react app throung: react-native init XXX and run it on CHANGHONG T11 device
(Other device run ok)

**Comment by nb7123** [comment]
device error

**Comment by cinder92** [comment]
same issue here, testing in real device... huawei gx8 android 6

**Comment by itinance** [comment]
Same issue when debugging on real device (Motorola E2).

**Comment by jacargentina** [comment]
i'm having this on the emulator; why is this issue closed ?

**Comment by pets1vets** [comment]
I had the same issue with OkHttp, It's related to the connection being kept alive, as a workaround you could close the connection on each call using `'Connection': 'close'`, hopefully it will be fixed soon.

Example: 
`fetch(backendAPI, {
        method: 'POST',
        headers: {
          'Connection': 'close'
        },
        body: data
      })`

**Comment by kareem-adel** [comment]
I had the same issue with OkHttp, It's related to the connection being kept alive, as a workaround you could close the connection on each call using `'Connection': 'close'` header, hopefully it will be fixed soon.

Example:
`fetch(backendAPI, { method: 'POST', headers: { 'Connection': 'close' }, body: data })`

**Comment by Hamzablm** [comment]
same issue

**Comment by ayushnawani** [comment]
Still facing this issue in 0.52.2. Please reopen it
