### ISSUE TITLE
 Cannot find module './Module' Error at module.js:487

### ISSUE THREAD

**Issue by ejaz47** [facebook/react-native#14865]
I really getting stuck while trying to run **react-native init AwesomProject** on windows 7 the following error is occurring,

![image](https://user-images.githubusercontent.com/16835868/27913114-b271cada-627c-11e7-8029-4b8c5e480d96.png)

I have already tried following,

- **yarn** :  latest
- **node** : 6.11.0 and 8.11.3
- **npm** : 4 and 5
- **reinstalled** **react-native-cli**
- **restarted** pc several time.

One thing is that it was all going perfectly before 1 hour.

> Complete Output

` **$ react-native init hello3**
This will walk you through creating a new React Native project in D:\react\hello 3
Using yarn v0.27.5
Installing react-native...
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "react-native@0.46.0" has unmet peer dependency "react@16.0.0-alpha.12".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 469 new dependencies.
├─ absolute-path@0.0.0
├─ accepts@1.2.13
├─ ajv@4.11.8
├─ assert-plus@1.0.0
├─ async@2.5.0
.
.
.
.
├─ yargs-parser@4.2.1
└─ yargs@6.6.0
Done in 53.86s.
module.js:487
    throw err;
    ^

Error: Cannot find module './Module'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\react\hello3\node_modules\metro-bundler\build\node -haste\DependencyGraph.js:19:16)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\react\hello3\ node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)`

**Comment by ravis95** [comment]
module.js:487 error arises if node is unable to detect the module you want to run in the selected directory,
Copy the files into some other directory and try C:\users\admin\...and Run it.

![1](https://user-images.githubusercontent.com/22999821/27951305-1477c09a-6322-11e7-889f-d81558483d4e.JPG)
![2](https://user-images.githubusercontent.com/22999821/27951306-147a15de-6322-11e7-890a-3722a5e2582b.JPG)

**Comment by ejaz47** [comment]
Its same even after changing the directive and drive too :(

**Comment by ejaz47** [comment]
I found this is a bug in **react-native 0.46.0**.
downgrading to **react-native 0.44.0** solved it.
its a bug in latest **virsion 0.46.0** so i am not closing this issue.

**Comment by vigneshmack** [comment]
I cannot able to create a sails app. It shows an error.
I set the environmental variables like:C:\Users\Vignesh Ravi\WebstormProjects\sailsapplication\sails.
I created the notepad file added the path:
 node "C:\Users\Vignesh Ravi\WebstormProjects\sailsapplication\sails.js"
saved it as batch file. I added this batch file in C:\Windows\System32

![sailerror2](https://user-images.githubusercontent.com/24427592/28016680-1ca608f8-6593-11e7-89ad-d4952ac1776f.PNG)

**Comment by samipsairam** [comment]
I am still facing the same issue:
=======================
verifying that npm is installed...
module.js:487
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /home/ubuntu/.nvm/versions/node/v8.2.1/lib/node_modules/npm/bin/npm-cli.js:22:13
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v8.2.1/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
Uh oh!  npm had a problem! { Error: Command failed: "/home/ubuntu/.nvm/versions/node/v8.2.1/bin/npm" --version
module.js:487
    throw err;

**Comment by AishwaryaSurana** [comment]
Is anyone able to troubleshoot it?

**Comment by AishwaryaSurana** [comment]
Try removing node modules

`rm -r node_modules
`
Reinstall node modules by:

`npm install
`

or

`yarn install
`

**Comment by CrazzzyDev** [comment]
@AishwaryaSurana, thanks. It worked for me as well.

**Comment by Anujmoglix** [comment]
Worked for me @AishwaryaSurana   . Thanks

**Comment by ehwest** [comment]
Same exact problem.
No effective solution at this time....
MAC OSX

**Comment by Ariven1** [comment]
I solved this issue by doing the following

  1. C: drive -> Users -> "username" eg. john -> AppData -> Roaming

  2. Inside the "Roaming" folder you need to delete both "npm" and "npm-cache" 
       folder.

  3. Now build your project, and it should work

**Comment by masumbillah** [comment]
Error: Cannot find module './lib/mediaType'
   at Function.Module._resolveFilename (module.js:538:15)
   at Function.Module._load (module.js:468:25)
   at Module.require (module.js:587:17)
   at require (internal/module.js:11:18)
   at loadModule (/Users/ms/ReactNative/chatApp/node_modules/errorhandler/node_modules/negotiator/index.js:114:16)
   at Negotiator.mediaTypes (/Users/ms/ReactNative/chatApp/node_modules/errorhandler/node_modules/negotiator/index.js:76:29)
   at Accepts.type.Accepts.types (/Users/ms/ReactNative/chatApp/node_modules/errorhandler/node_modules/accepts/index.js:105:33)
   at Object.errorHandler [as handle] (/Users/ms/ReactNative/chatApp/node_modules/errorhandler/index.js:112:23)
   at next (/Users/ms/ReactNative/chatApp/node_modules/connect/lib/proto.js:169:17)
   at next (/Users/ms/ReactNative/chatApp/node_modules/connect/lib/proto.js:171:11)

**Comment by MarkBolden** [comment]
@AishwaryaSurana that helped me as well.. the big question I would like answered now is... why? sigh.

**Comment by AishwaryaSurana** [comment]
@MarkBolden I guess that may be because of some error during installation of a particular module.

**Comment by jeremyfrancis** [comment]
sudo react-native init ProjectName did the trick for me!

**Comment by vijayku86** [comment]
@AishwaryaSurana Reinstalling node works for me. I updated the node to the latest version i.e. 9.10.1
