### ISSUE TITLE
No bundle url present

### ISSUE THREAD

**Issue by ZombieWang** [facebook/react-native#14871]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment

1. `react-native -v`:  0.46.0
2. `node -v`: v8.1.3
3. `npm -v`: 5.0.4
4. `yarn --version` (if you use Yarn): N/A

Then, specify:

1. Target Platform (e.g. iOS, Android): iOS
2. Development Operating System (e.g. macOS Sierra, Windows 10): 
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant): Xcode, iOS 10.3

### Steps to Reproduce

(Write your steps here:)

In terminal:
run ->react-native init myproject to init a new project
run ->react-native run-ios --simulator='iPhone 7'

Simulator shows red screen and says No bundle URL present.
You can also see error log in terminal like,

/(mylocal path)/testproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

ReferenceError: Unknown plugin "transform-runtime" specified in "/(mylocal path)/testproject/node_modules/regenerator-transform/package.json" at 0, attempted to resolve relative to "/(mylocal path)/testproject/node_modules/regenerator-transform" (While processing preset: "/(mylocal path)/testproject/node_modules/babel-preset-react-native/index.js")
    at /(mylocal path)/testproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/(mylocal path)/testproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/(mylocal path)/testproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/(mylocal path)/testproject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/(mylocal path)/testproject/node_modules/babel-register/lib/node.js:103:45)
    at loader (/(mylocal path)/testproject/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/(mylocal path)/testproject/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
Process terminated. Press <enter> to close the window

### Expected Behavior

I found that if I switch react native version to 0.45.1 there will be no problem to run the app on simulator.

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by Amurmurmur** [comment]
+1
Happens on iOS with React-native v0.46

**Comment by Amurmurmur** [comment]
This is same as #14866

**Comment by thechee514** [comment]
@ZombieWang a temporary workaround is initializing your new project this way: _react-native init --version="0.45.1" projectName_. This downgrades the version of react-native to 0.45.1 and it seems to be working for me right now.

**Comment by hramos** [comment]
Duplicate.

**Comment by holasebas** [comment]
+1
