### ISSUE TITLE
upgrade to 0.46.2  java.lang.ClassNotFoundException: Didn't find class "com.facebook.react.cxxbridge.JSCJavaScriptExecutor"

### ISSUE THREAD

**Issue by breeze1988** [facebook/react-native#14997]
When upgrade RN version to 0.46.2,I run my apk get this error:

java.lang.ExceptionInInitializerError
                                                                at com.facebook.react.JSCConfig$1.getConfigMap(JSCConfig.java:14)
                                                                at com.facebook.react.ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader(ReactInstanceManager.java:364)
                                                                at com.facebook.react.ReactInstanceManager.recreateReactContextInBackgroundInner(ReactInstanceManager.java:358)
                                                                at com.facebook.react.ReactInstanceManager.createReactContextInBackground(ReactInstanceManager.java:299)
                                                                at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:220)
                                                                at com.wm.dmall.rn.CommonRNPage.onPageDidLoad(CommonRNPage.java:187)
                                                                at com.dmall.appframework.navigator.Navigator$4.run(Navigator.java:947)
                                                                at com.dmall.appframework.navigator.PageAnimatePushLeft.fireCallbackOnce(PageAnimatePushLeft.java:33)
                                                                at com.dmall.appframework.navigator.PageAnimatePushLeft.access$000(PageAnimatePushLeft.java:12)
                                                                at com.dmall.appframework.navigator.PageAnimatePushLeft$1.onAnimationEnd(PageAnimatePushLeft.java:79)
                                                                at android.view.animation.Animation$3.run(Animation.java:374)
                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:135)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5313)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1116)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)
                                                             Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.react.cxxbridge.JSCJavaScriptExecutor" on path: DexPathList[[zip file "/data/app/com.wm.dmall.debug-2/base.apk"],nativeLibraryDirectories=[/data/app/com.wm.dmall.debug-2/lib/arm, /vendor/lib, /system/lib]]
                                                                at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                at java.lang.Runtime.nativeLoad(Native Method)
                                                                at java.lang.Runtime.doLoad(Runtime.java:445)
                                                                at java.lang.Runtime.load(Runtime.java:346)
                                                                at java.lang.System.load(System.java:981)
                                                                at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
                                                                at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:42)
                                                                at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:299)
                                                                at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:247)
                                                                at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:17)
                                                                at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:21)
                                                                at com.facebook.react.JSCConfig$1.getConfigMap(JSCConfig.java:14) 
                                                                at com.facebook.react.ReactInstanceManager.recreateReactContextInBackgroundFromBundleLoader(ReactInstanceManager.java:364) 
                                                                at com.facebook.react.ReactInstanceManager.recreateReactContextInBackgroundInner(ReactInstanceManager.java:358) 
                                                                at com.facebook.react.ReactInstanceManager.createReactContextInBackground(ReactInstanceManager.java:299) 
                                                                at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:220) 
                                                                at com.wm.dmall.rn.CommonRNPage.onPageDidLoad(CommonRNPage.java:187) 
                                                                at com.dmall.appframework.navigator.Navigator$4.run(Navigator.java:947) 
                                                                at com.dmall.appframework.navigator.PageAnimatePushLeft.fireCallbackOnce(PageAnimatePushLeft.java:33) 
                                                                at com.dmall.appframework.navigator.PageAnimatePushLeft.access$000(PageAnimatePushLeft.java:12) 
                                                                at com.dmall.appframework.navigator.PageAnimatePushLeft$1.onAnimationEnd(PageAnimatePushLeft.java:79) 
                                                                at android.view.animation.Animation$3.run(Animation.java:374) 
                                                                at android.os.Handler.handleCallback(Handler.java:739) 
                                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                at android.os.Looper.loop(Looper.java:135) 
                                                                at android.app.ActivityThread.main(ActivityThread.java:5313) 
                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1116) 
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809) 
                                                            	Suppressed: java.lang.ClassNotFoundException: com.facebook.react.cxxbridge.JSCJavaScriptExecutor
                                                                at java.lang.Class.classForName(Native Method)
                                                                at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                		... 30 more

### Environment

1. `react-native -v`: 0.46.2
2. `node -v`: v6.2.1
3. `npm -v`: 4.0.2
4. `yarn --version` (if you use Yarn):0.17.6

have someone meet that problem?

**Comment by thatjuan** [comment]
What have you tried?

Try:

1. `rm -f node_modules`
2. `rm -rf ~/.rncache/`
3. `npm install`
4. `react-native link`

**Comment by liucr** [comment]
I have the same problem after upgrade 0.47.1.

**Comment by breeze1988** [comment]
@liucr  are you solve it?

**Comment by caltv** [comment]
I have the same issue, only on Android 7.0 and up though

**Comment by breeze1988** [comment]
@caltv  it happened on Android 5.1.1

**Comment by caltv** [comment]
I turned off "Instant Run" in Android studio and now it works...

**Comment by breeze1988** [comment]
@caltv I have the same problem and don't know how to solve it...

**Comment by breeze1988** [comment]
@thatjuan I have tried but it's not work

**Comment by briandilley** [comment]
does adding `compile 'com.facebook.soloader:soloader:0.1.0+'` to your project's dependencies fix it?

**Comment by 70kg** [comment]
I have the same problem,Did anyone solve this problem?

**Comment by meixq2006** [comment]
the same problem after upgrade to 0.51，on android 7.0，how to fix it？

**Comment by meixq2006** [comment]
Recompile and generate libreactnativejni.so & libprivatedata.so in new version， to replace the libreactnativejni.so and libreactnativefnjni.so in \libs\armeabi-v7a works for me，hope to help you to fix the problem. RN 0.51.0，android 7.0。

**Comment by Chaunjie** [comment]
@meixq2006 0.51版本你这个是怎么解决的？

**Comment by meixq2006** [comment]
@Chaunjie,我这边出现问题的原因，是native工程和rn工程不在一个文件夹下，所以升级rn后native那边libs里的libreactnativejni.so 和libprivatedata.so的版本还是之前的，在rn的android工程里重新生成这两个so文件移动过去替换掉之前的，就可以了。

**Comment by Chaunjie** [comment]
@meixq2006我出现的问题不是这个原因，不过还是要谢谢你
