### ISSUE TITLE
[Android] App crash at launch after upgrading to 0.46.3

### ISSUE THREAD

**Issue by valinaga** [facebook/react-native#15068]
### Is this a bug report?

Yes.

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes.

### Environment

Android

1. `react-native -v`: 0.46.3
2. `node -v`: 7.7.2
3. `npm -v`: 5.0.4
4. `yarn --version` (if you use Yarn): 0.23.4

Then, specify:

- Target Platform:  Android

- Development Operating System: macOS

- Build tools: 23.0.1

### Steps to Reproduce

(Write your steps here:)

1. react-native-git-upgrade
2. react-native run-android

### Expected Behavior

App to launch in emulator

### Actual Behavior

App crash at the beginning without opening the window.

### Reproducible Demo

07-18 06:36:40.655 4782-4801/com.appcenter.wishbox E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                     Process: com.appcenter.wishbox, PID: 4782
                                                                     java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                         at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                         at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                         at java.lang.Thread.run(Thread.java:818)
                                                                      Caused by: java.lang.NoClassDefFoundError: com.facebook.react.devsupport.InspectorPackagerConnection$Connection
                                                                         at com.facebook.react.devsupport.InspectorPackagerConnection.<init>(InspectorPackagerConnection.java:36)
                                                                         at com.facebook.react.devsupport.DevServerHelper$3.doInBackground(DevServerHelper.java:194)
                                                                         at com.facebook.react.devsupport.DevServerHelper$3.doInBackground(DevServerHelper.java:191)
                                                                         at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                         at java.lang.Thread.run(Thread.java:818) 

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by Jose4gg** [comment]
Same Problem @valinaga any updates?

**Comment by dorthwein** [comment]
Same here ;(

**Comment by fxhereng** [comment]
Setting Overlay permissions in app settings enabled to solve it for me (RN 0.49.3)
