### ISSUE TITLE
Fail when run react-native link, missing module 'inquirer' and 'mute-stream' from node_modules folder after install react-native 0.46.4

### ISSUE THREAD

**Issue by ibrahimker** [facebook/react-native#15099]
After run `npm install react-native@0.46.4`, I try to run `react-native link`. However I got the following error
```
Error: Cannot find module 'inquirer'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:/Git/cancure/node_modules/react-native/local-cli/li
nk/pollParams.js:1:16)
    at Module._compile (module.js:569:30)
    at loader (C:\Git\cancure\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Git\cancure\n
ode_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

```
Error: Cannot find module 'mute-stream'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Git\cancure\node_modules\inquirer\lib\ui\baseUI.js
:3:18)
    at Module._compile (module.js:569:30)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Git\cancure\n
ode_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

Obviously running `npm install inquirer mute-stream` solve the issue, but I still confure why the module isn't installed by default

**Comment by hramos** [comment]
Thanks for reporting the issue. What is the state of the project prior to installing RN 0.46.4? Does this reproduce with react-native-upgrade?

**Comment by devjaw** [comment]
use `react-native-git-upgrade` and the problem will be solved

**Comment by hramos** [comment]
#answered
