### ISSUE TITLE
RN - Android - Modal + Home Button Long Press = app crash

### ISSUE THREAD

**Issue by GitHubTracey** [facebook/react-native#15440]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.44.3
2. `node -v`: v8.2.1
3. `npm -v`: 5.3.0
4. `yarn --version`<!-- (if you use Yarn) —>: n/a

Target Platform: [Android/iOS]
Development Operating System: macOS
Build tools: Android Studios/xCode

### Steps to Reproduce
Open App on Android phone
Open Category (custom component)
Open Modal 
Hold Home button  (long press)
App Crashes…

### Expected Behavior
Expect app to hide in background until user brings app back up again, and return to same screen.

### Actual Behavior
App Crashes with error:  “Unfortunately myApp has stopped [OK]”

### Notes / Comments
- does not happen for iOS
- does not happen for any other component
- for one of the modals, we use touchid to log the user in - if the user has a registered fingerprint, on a longpress, the user is signed in and the app does not crash.

### Reproducible Demo
All modals are designed the same way. I have removed styling for clarity.
```
<Modal
    onRequestClose={()=> {
        props.waitingForResponse(false);
    }}
    visible={props.visible}>
    <View>
        <View>
            <View>
                <Image source={modalImageSrc} />
                <Text>
                    {props.showErrorMesage ? "Error" : props.title}
                </Text>
                <Text>{props.showErrorMesage ? "Item disabled" : props.text}</Text>
            </View>
            <View>
                <Button
                    onPress={()=> {
                        props.waitingForResponse(false);
                    }}
                    title="Cancel"
                />
            </View>
        </View>
    </View>
</Modal>
```

**Comment by christophermark** [comment]
I can reproduce as well on React Native 43.3

Android error:
```
                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.dispatchProvideStructure(android.view.ViewStructure)' on a null object reference
                                                                            at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:2961)
                                                                            at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:2961)
                                                                            at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:2961)
                                                                            at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:2961)
                                                                            at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:2961)
                                                                            at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:2961)
                                                                            at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:2961)
                                                                            at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:2961)
                                                                            at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:422)
                                                                            at android.app.assist.AssistStructure.<init>(AssistStructure.java:1335)
                                                                            at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:2586)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1539)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by christophermark** [comment]
Dupe of #13201

**Comment by GitHubTracey** [comment]
closing in favour of https://github.com/facebook/react-native/issues/13201
