### ISSUE TITLE
Can't run npm start in website - module not in specified search paths

### ISSUE THREAD

**Issue by amccloud** [facebook/react-native#155]
@84207f2ec86efd743fef7d69aa622948c900963e

```
Connect
500 Error: Error: Following module not in specified search paths: /Users/amccloud/.Labs/react-native/website/src/index.js
at /Users/amccloud/.Labs/react-native/website/node_modules/react-page-middleware/src/guard.js:27:12
at Object.onModuleDependenciesLoaded [as done] (/Users/amccloud/.Labs/react-native/website/node_modules/react-page-middleware/src/Packager.js:253:16)
at MapUpdateTask. (/Users/amccloud/.Labs/react-native/website/node_modules/react-page-middleware/node_modules/node-haste/lib/HasteDependencyLoader.js:100:22)
at MapUpdateTask.emit (events.js:117:20)
at MapUpdateTask. (/Users/amccloud/.Labs/react-native/website/node_modules/react-page-middleware/node_modules/node-haste/lib/MapUpdateTask.js:83:18)
at finished (/Users/amccloud/.Labs/react-native/website/node_modules/react-page-middleware/node_modules/node-haste/lib/MapUpdateTask.js:271:16)
at /Users/amccloud/.Labs/react-native/website/node_modules/react-page-middleware/node_modules/node-haste/lib/loader/ResourceLoader.js:145:5
at process._tickCallback (node.js:419:13)
```

**Comment by zpao** [comment]
The site is up now at index.html so this can be closed.
