### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.String com.facebook.AccessToken.getApplicationId()' on a null object reference

### ISSUE THREAD

**Issue by kennyfox7** [facebook/react-native#15549]
### Environment

$ react-native -v
react-native-cli: 2.0.1
react-native: 0.46.0
$ node -v
v6.11.2
$ npm -v
5.3.0

- Target Platform: Android (On iOs it is working...)

- Development Operating System: either way, on windows and iOS it is broken

- Build tools: XCode and Android Studio

### Steps to Reproduce

Just do a Graph-Request, without logging in before.

### Expected Behavior

I expected that I don't need to log in to make aGraphApi-Request if i use my Application-AccessToken. I thought I only need to set the App-AccessToken for the Request.
This works for me on (React-Native-)iOS...
Sending a request to the Graph API and receiving a response.

(Write what you thought would happen.)

### Actual Behavior

    "const eventRequestParams = {
      fields: {
        string: 'id, name, place, description, start_time, cover, owner, updated_time'
      },
      limit: {string: '999'},
      since: {string: today},
    };

    const eventRequestConfig = {
      parameters: eventRequestParams,
      accessToken: 'MY_APP_ID|MY_APP_SECRET'
    };

    const infoRequest = new GraphRequest(
      '/compassentertainment/events/',
      eventRequestConfig,
      this._responseInfoCallback,
    );

    new GraphRequestManager().addRequest(infoRequest).start();"

When I do this. I get the following error.

08-18 11:44:19.344 26796-26839/com.compass E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
       Process: com.compass, PID: 26796
       java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.facebook.AccessToken.getApplicationId()' on a null object reference
           at com.facebook.reactnative.androidsdk.FBGraphRequestModule.setConfig(FBGraphRequestModule.java:157)
           at com.facebook.reactnative.androidsdk.FBGraphRequestModule.buildRequest(FBGraphRequestModule.java:136)
           at com.facebook.reactnative.androidsdk.FBGraphRequestModule.start(FBGraphRequestModule.java:123)
           at java.lang.reflect.Method.invoke(Native Method)
           at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
           at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:166)
           at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
           at android.os.Handler.handleCallback(Handler.java:751)
           at android.os.Handler.dispatchMessage(Handler.java:95)
           at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
           at android.os.Looper.loop(Looper.java:154)
           at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
           at java.lang.Thread.run(Thread.java:761)

### Reproducible Demo

Following.

**Comment by eduardojunio** [comment]
Same here
