### ISSUE TITLE
React Native 0.47.0, 0.47.1, 0.48.0-rc.1 - Could not find class 'com.facebook.react.modules.accessibilityinfo.AccessibilityInfoModule$ReactTouchExplorationStateChangeListener'

### ISSUE THREAD

**Issue by amirdew** [facebook/react-native#15569]
**Is this a bug report?**
yes

Hi,
when I want to "Generating Signed APK" or run "react-native run-android --variant=release"
the APK generated and signed successfully but when app launch it's crashed with this error:

``
Could not find class 'com.facebook.react.modules.accessibilityinfo.AccessibilityInfoModule$ReactTouchExplorationStateChangeListener', referenced from method com.facebook.react.modules.accessibilityinfo.AccessibilityInfoModule.<init>
08-20 04:02:29.087 1439-1452/? E/AndroidRuntime: FATAL EXCEPTION: Thread-111
                                                 java.lang.RuntimeException: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
                                                     at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
                                                     at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:206)
                                                     at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:34)
                                                     at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:224)
                                                     at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1014)
                                                     at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109)
                                                     at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:802)
``

app work with "react-native run-android" or "react-native run-ios" and also no problem on iOS release,

I try these but my problem doesn't solve:
- clean project
- remove node_modules and clean npm cache 
- create a new react-native project with "react-native init"
- follow [docs](http://facebook.github.io/react-native/docs/signed-apk-android.html) for "Generating Signed APK" step by step

**Environment**
react-native-cli: 2.0.1
react-native: (0.47.0, 0.47.1, 0.48.0-rc.1 )
node -v8.0.0
npm -v5.3.0
macOS 10.12

**Comment by iegik** [comment]
Duplicated: https://github.com/facebook/react-native/issues/14209

**Comment by chirag04** [comment]
@facebook-github-bot duplicate

**Comment by chirag04** [comment]
@facebook-github-bot duplicate #14209
