### ISSUE TITLE
error after create-react-native-app AwesomeProject command ?

### ISSUE THREAD

**Issue by hiteshsomani** [facebook/react-native#15574]
### Is this a bug report?

yes 

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

(Write your answer here.)

### Environment

1. `react-native -v`: gives this error `/usr/local/lib/node_modules/react-native-cli/index.js:266
  const rnPackage = options.version;
  ^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3`

2. `node -v`: v0.10.25
3. `npm -v`: 1.3.10
4. `yarn --version`:

Then, specify:

- Target Platform:
 development not yet statred stucked in this command `create-react-native-app AwesomeProject
` given [here](https://facebook.github.io/react-native/docs/getting-started.html)

- Development Operating System: ubuntu 14.4

- Build tools:

### Steps to Reproduce
  after this command `create-react-native-app AwesomeProject` getting this error
`/usr/local/lib/node_modules/create-react-native-app/node_modules/fs-extra/lib/index.js:3
const assign = require('./util/assign')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/create-react-native-app/build/index.js:233:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)`

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by Ehesp** [comment]
Your Node version is really old (v0.10.25), I'm not even sure it's supported!
