### ISSUE TITLE
Could not find class 'okhttp3.OkHttpClient$Builder'

### ISSUE THREAD

**Issue by hey-mx** [facebook/react-native#15594]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

1. `react-native -v`: 0.47.1
2. `node -v`: 7.8.0
3. `npm -v`: 4.2.0
4. `yarn --version`:

Then, specify:

- Target Platform: Android  4

- Development Operating System: Mac Os Sierra

- Build tools: Android Studio 2.3.3

### Steps to Reproduce

1. Upgrade react native from 0.44 to 0.47.1 using the manual steps described on https://facebook.github.io/react-native/docs/upgrading.html

### Expected Behavior

My app was using the version 0.44 of react native and it runned on devices with Android 4.x, I hoped that the app still running in the devices with android 4.x

### Actual Behavior

I have the error "_Could not find class okhttp3.OkHttpClient$Builder", referenced from method com.facebook.react.devsupport.DevServerHelper_"

### Reproducible Demo

Only follow the steps for  the manual upgrade described on https://facebook.github.io/react-native/docs/upgrading.html

**Comment by alfonsodev** [comment]
I

**Comment by alfonsodev** [comment]
I have similar after updating to react-native 0.49 
```
10-13 20:50:22.800: I/art(28368): Ciaused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.WebSocketListener" on path: DexPathList[[zip file "/data/app/com.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp-1/lib/arm, /system/fake-libs, /data/app/com.myapp-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]
```

**Comment by tobob** [comment]
same issue, still on RN 0.52, on Kitkat app crash at very beggining

**Comment by RameshSain** [comment]
same issue, still on RN 0.40, on Kitkat app crash at very beggining

**Comment by tobob** [comment]
I resolve this by adding:

```
    compile 'com.android.support:multidex:1.0.1'
```

inside `android/app/build.grandle` `dependencies`

and:

```
android {
    dexOptions {
        jumboMode true
    }
    compileSdkVersion 26
    buildToolsVersion "26.0.2"

    defaultConfig {
        applicationId "com.myApp.name"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 32
        versionName "1.2.1"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        multiDexEnabled true
    }

```

multiDexEnabled! is most important

**Comment by RameshSain** [comment]
Thanks for reply https://github.com/tobob

No thing works for me : 
I tied it 

compile 'com.android.support:multidex:1.0.1'

android {
    dexOptions {
        jumboMode true
    }
    compileSdkVersion 26
    buildToolsVersion "26.0.2"

    defaultConfig {
        applicationId "in.myao.app"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 2
        versionName "2.0.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        multiDexEnabled true
    }

**Comment by tobob** [comment]
did you check catlog? what you get there?

`adb logcat`

**Comment by RameshSain** [comment]
This is logcat output:-

02-27 15:58:28.261 12878-12878/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: in.studybase.app, PID: 12878
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{in.studybase.app/in.studybase.app.MainActivity}: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2342)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5421)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:979)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
                                                       at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:77)
                                                       at com.facebook.react.XReactInstanceManagerImpl.<init>(XReactInstanceManagerImpl.java:315)
                                                       at com.facebook.react.ReactInstanceManager$Builder.build(ReactInstanceManager.java:419)
                                                       at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:84)
                                                       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
                                                       at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:111)
                                                       at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:100)
                                                       at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54)
                                                       at in.studybase.app.MainActivity.onCreate(MainActivity.java:12)
                                                       at android.app.Activity.performCreate(Activity.java:5264)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1099)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5421) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:979) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Constructor.constructNative(Native Method)
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                       at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:70)
                                                       at com.facebook.react.XReactInstanceManagerImpl.<init>(XReactInstanceManagerImpl.java:315) 
                                                       at com.facebook.react.ReactInstanceManager$Builder.build(ReactInstanceManager.java:419) 
                                                       at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:84) 
                                                       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41) 
                                                       at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:111) 
                                                       at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:100) 
                                                       at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54) 
                                                       at in.studybase.app.MainActivity.onCreate(MainActivity.java:12) 
                                                       at android.app.Activity.performCreate(Activity.java:5264) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1099) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5421) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:979) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.NoClassDefFoundError: okhttp3.OkHttpClient$Builder
                                                       at com.facebook.react.devsupport.DevServerHelper.<init>(DevServerHelper.java:105)
                                                       at com.facebook.react.devsupport.DevSupportManagerImpl.<init>(DevSupportManagerImpl.java:183)
                                                       at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                       at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:70) 
                                                       at com.facebook.react.XReactInstanceManagerImpl.<init>(XReactInstanceManagerImpl.java:315) 
                                                       at com.facebook.react.ReactInstanceManager$Builder.build(ReactInstanceManager.java:419) 
                                                       at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:84) 
                                                       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41) 
                                                       at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:111) 
                                                       at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:100) 
                                                       at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54) 
                                                       at in.studybase.app.MainActivity.onCreate(MainActivity.java:12) 
                                                       at android.app.Activity.performCreate(Activity.java:5264) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1099) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5421) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:979) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
02-27 15:59:14.386 588-588/? E/DeviceStorageMonitorService: Will not process invalid message
02-27 16:00:14.394 588-588/? E/DeviceStorageMonitorService: Will not process invalid message
02-27 16:00:29.299 921-921/? E/ActivityThread: Failed to find provider info for childmode
02-27 16:01:14.393 588-588/? E/DeviceStorageMonitorService: Will not process invalid message
02-27 16:01:21.740 588-655/? E/PerformBackupTask: Transport error in initializeDevice()
02-27 16:02:14.401 588-588/? E/DeviceStorageMonitorService: Will not process invalid message
02-27 16:02:22.389 588-646/? E/ConnectivityService: Exception trying to remove a route: java.lang.IllegalStateException: command '101 interface route remove wlan0 default 192.168.0.0 24 0.0.0.0' failed with '400 101 Failed to remove route from default table (No such process)'
02-27 16:02:22.389 588-646/? E/ConnectivityService: Exception trying to remove a route: java.lang.IllegalStateException: command '102 interface route remove wlan0 default 192.168.0.1 32 0.0.0.0' failed with '400 102 Failed to remove route from default table (No such process)'
02-27 16:02:22.399 588-646/? E/ConnectivityService: Exception trying to remove a route: java.lang.IllegalStateException: command '103 interface route remove wlan0 default 0.0.0.0 0 192.168.0.1' failed with '400 103 Failed to remove route from default table (No such process)'
02-27 16:02:57.874 12990-12990/? E/DHCPCD: dhcpcd: lpf ipv4_opensocket s = 16
02-27 16:02:57.874 12990-12990/? E/DHCPCD: dhcpcd: lpf ipv4_opensocket index = 11
02-27 16:02:57.904 12990-12990/? E/DHCPCD: dhcpcd: lpf ipv4_opensocket *fd = 16
02-27 16:02:57.904 12990-12990/? E/DHCPCD: dhcpcd: dhcp add raw_fd 16
02-27 16:02:57.904 12990-12990/? E/DHCPCD: dhcp: send_raw_packet: wlan0
02-27 16:02:57.904 12990-12990/? E/DHCPCD: dhcpcd: lpf send_raw_packet ifp->index = 11, protocol = 8
02-27 16:02:57.904 12990-12990/? E/DHCPCD: dhcpcd: lpf send_raw_packet fd = 16 len = 362 su.to addr = 255.255.255.255
02-27 16:02:57.904 12990-12990/? E/DHCPCD: dhcp: send_raw_packet errno =22
02-27 16:02:58.084 12990-12990/? E/DHCPCD: dhcpcd: ifp->index = 11 ifp->name = wlan0
02-27 16:02:58.264 588-646/? E/ConnectivityService: Unexpected mtu value: android.net.wifi.WifiStateTracker@422cb0c0
02-27 16:02:58.334 12990-12990/? E/DHCPCD: dhcpcd: ifp->index = 11 ifp->name = wlan0
02-27 16:02:58.464 12990-12990/? E/DHCPCD: dhcpcd: ifp->index = 11 ifp->name = wlan0
02-27 16:02:58.514 12990-12990/? E/DHCPCD: dhcpcd: ifp->index = 11 ifp->name = wlan0
02-27 16:02:58.544 12990-12990/? E/DHCPCD: dhcpcd: ifp->index = 11 ifp->name = wlan0
02-27 16:02:58.765 588-604/? E/LIBGPS: agps update network state,connected=1,type=1,roaming=0
02-27 16:02:58.765 588-604/? E/LIBGPS: assist_ril_update,avaiable=1,apn=dummy-apn
02-27 16:02:59.295 588-624/? E/AlarmManagerService: set alarm to 23183.789000000
02-27 16:02:59.295 588-624/? E/AlarmManagerService: set alarm to 23421.246000000
02-27 16:02:59.295 588-624/? E/AlarmManagerService: set alarm to 23422.793000000
02-27 16:02:59.295 588-624/? E/AlarmManagerService: set alarm to 23422.875000000
02-27 16:02:59.365 588-934/? E/AlarmManagerService: set alarm to 23422.793000000
02-27 16:02:59.365 588-934/? E/AlarmManagerService: set alarm to 23422.875000000
02-27 16:02:59.375 588-943/? E/AlarmManagerService: set alarm to 23183.864000000
02-27 16:02:59.375 588-943/? E/AlarmManagerService: set alarm to 23421.246000000
02-27 16:02:59.375 588-943/? E/AlarmManagerService: set alarm to 23422.793000000
02-27 16:02:59.375 588-943/? E/AlarmManagerService: set alarm to 23422.875000000
02-27 16:03:00.006 588-588/? E/AlarmManagerService: set alarm to 22344.487000000
02-27 16:03:14.140 767-767/? E/MtpService: ptp mode false
02-27 16:03:14.400 588-588/? E/DeviceStorageMonitorService: Will not process invalid message
02-27 16:03:16.992 767-767/? E/MtpService: ptp mode false
02-27 16:03:19.775 767-767/? E/MtpService: ptp mode false
02-27 16:04:00.004 588-588/? E/AlarmManagerService: set alarm to 22404.486000000
02-27 16:04:13.107 588-588/? E/DeviceStorageMonitorService: Will not process invalid message
02-27 16:04:14.408 588-588/? E/DeviceStorageMonitorService: Will not process invalid message
02-27 16:04:46.129 767-767/? E/MtpService: ptp mode false
02-27 16:04:47.511 767-767/? E/MtpService: ptp mode false
02-27 16:04:50.223 767-767/? E/MtpService: ptp mode false
02-27 16:04:51.184 767-767/? E/MtpService: ptp mode false
02-27 16:04:53.466 767-767/? E/MtpService: ptp mode false
02-27 16:04:54.998 767-767/? E/MtpService: ptp mode false
02-27 16:04:56.539 767-767/? E/MtpService: ptp mode false
02-27 16:04:59.993 588-588/? E/AlarmManagerService: set alarm to 22464.487000000
02-27 16:05:14.407 588-588/? E/DeviceStorageMonitorService: Will not process invalid message
02-27 16:06:00.001 588-588/? E/AlarmManagerService: set alarm to 22524.486000000
02-27 16:06:14.405 588-588/? E/DeviceStorageMonitorService: Will not process invalid message
02-27 16:07:00.000 588-588/? E/AlarmManagerService: set alarm to 22584.486000000
02-27 16:07:14.404 588-588/? E/DeviceStorageMonitorService: Will not process invalid message
02-27 16:08:00.008 588-588/? E/AlarmManagerService: set alarm to 22644.486000000
02-27 16:08:14.403 588-588/? E/DeviceStorageMonitorService: Will not process invalid message
02-27 16:08:59.997 588-588/? E/AlarmManagerService: set alarm to 22704.486000000
02-27 16:09:14.411 588-588/? E/DeviceStorageMonitorService: Will not process invalid message
02-27 16:09:24.181 588-622/? E/AlarmManagerService: set alarm to 23183.864000000
02-27 16:09:24.181 588-622/? E/AlarmManagerService: set alarm to 23421.246000000
02-27 16:09:24.181 588-622/? E/AlarmManagerService: set alarm to 23422.793000000
02-27 16:09:24.181 588-622/? E/AlarmManagerService: set alarm to 23422.875000000
02-27 16:09:24.541 13203-13203/? E/dalvik-internals: Failed to look up ladDumpProfiles
02-27 16:09:24.541 13203-13203/? E/dalvik-internals: Failed to look up ladResetProfiles
02-27 16:09:24.541 13203-13203/? E/dalvik-internals: Failed to look up ladPrintHeaderInfo
02-27 16:09:26.643 13203-13203/? E/ACRA: Handling exception for crash
                                         java.lang.RuntimeException: org.tukaani.xz.XZIOException: Decompression failed (xz_ret=XZ_DATA_ERROR)
                                             at com.facebook.common.dextricks.DexLibLoader.a(DexLibLoader.java:1561)
                                             at com.facebook.katana.app.FacebookApplication.e(FacebookApplication.java:246)
                                             at com.facebook.katana.app.FacebookApplication.a(FacebookApplication.java:191)
                                             at com.facebook.base.app.DelegatingApplication.e(DelegatingApplication.java:33)
                                             at com.facebook.base.app.DelegatingApplication.attachBaseContext(DelegatingApplication.java:62)
                                             at android.app.Application.attach(Application.java:181)
                                             at android.app.Instrumentation.newApplication(Instrumentation.java:1003)
                                             at android.app.Instrumentation.newApplication(Instrumentation.java:987)
                                             at android.app.LoadedApk.makeApplication(LoadedApk.java:526)
                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4698)
                                             at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1326)
                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                             at android.os.Looper.loop(Looper.java:136)
                                             at android.app.ActivityThread.main(ActivityThread.java:5421)
                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:979)
                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795)
                                             at dalvik.system.NativeStart.main(Native Method)
                                          Caused by: org.tukaani.xz.XZIOException: Decompression failed (xz_ret=XZ_DATA_ERROR)
                                             at com.facebook.xzdecoder.XzDecoder.decompressFile(Native Method)
                                             at com.facebook.xzdecoder.XzDecoder.a(XzDecoder.java:180)
                                             at com.facebook.xzdecoder.XzDecoder.a(XzDecoder.java:133)
                                             at com.facebook.common.dextricks.DexLibLoader$ResourceResProvider.b(DexLibLoader.java:244)
                                             at com.facebook.common.dextricks.DexLibLoader.a(DexLibLoader.java:760)
                                             at com.facebook.common.dextricks.DexLibLoader.c(DexLibLoader.java:1391)
                                             at com.facebook.common.dextricks.DexLibLoader.a(DexLibLoader.java:1559)
                                             at com.facebook.katana.app.FacebookApplication.e(FacebookApplication.java:246) 
                                             at com.facebook.katana.app.FacebookApplication.a(FacebookApplication.java:191) 
                                             at com.facebook.base.app.DelegatingApplication.e(DelegatingApplication.java:33) 
                                             at com.facebook.base.app.DelegatingApplication.attachBaseContext(DelegatingApplication.java:62) 
                                             at android.app.Application.attach(Application.java:181) 
                                             at android.app.Instrumentation.newApplication(Instrumentation.java:1003) 
                                             at android.app.Instrumentation.newApplication(Instrumentation.java:987) 
                                             at android.app.LoadedApk.makeApplication(LoadedApk.java:526) 
                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4698) 
                                             at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1326) 
                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                             at android.os.Looper.loop(Looper.java:136) 
                                             at android.app.ActivityThread.main(ActivityThread.java:5421) 
                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:979) 
                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795) 
                                             at dalvik.system.NativeStart.main(Native Method) 
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan: Uncaught exception in '<default>':
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan: java.lang.RuntimeException: org.tukaani.xz.XZIOException: Decompression failed (xz_ret=XZ_DATA_ERROR)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at com.facebook.common.dextricks.DexLibLoader.a(DexLibLoader.java:1561)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at com.facebook.katana.app.FacebookApplication.e(FacebookApplication.java:246)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at com.facebook.katana.app.FacebookApplication.a(FacebookApplication.java:191)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at com.facebook.base.app.DelegatingApplication.e(DelegatingApplication.java:33)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at com.facebook.base.app.DelegatingApplication.attachBaseContext(DelegatingApplication.java:62)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at android.app.Application.attach(Application.java:181)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at android.app.Instrumentation.newApplication(Instrumentation.java:1003)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at android.app.Instrumentation.newApplication(Instrumentation.java:987)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at android.app.LoadedApk.makeApplication(LoadedApk.java:526)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4698)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at android.app.ActivityThread.access$1500(ActivityThread.java:151)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1326)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at android.os.Looper.loop(Looper.java:136)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at android.app.ActivityThread.main(ActivityThread.java:5421)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at java.lang.reflect.Method.invokeNative(Native Method)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at java.lang.reflect.Method.invoke(Method.java:515)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:979)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at dalvik.system.NativeStart.main(Native Method)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan: Caused by: org.tukaani.xz.XZIOException: Decompression failed (xz_ret=XZ_DATA_ERROR)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at com.facebook.xzdecoder.XzDecoder.decompressFile(Native Method)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at com.facebook.xzdecoder.XzDecoder.a(XzDecoder.java:180)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at com.facebook.xzdecoder.XzDecoder.a(XzDecoder.java:133)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at com.facebook.common.dextricks.DexLibLoader$ResourceResProvider.b(DexLibLoader.java:244)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at com.facebook.common.dextricks.DexLibLoader.a(DexLibLoader.java:760)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at com.facebook.common.dextricks.DexLibLoader.c(DexLibLoader.java:1391)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan:     at com.facebook.common.dextricks.DexLibLoader.a(DexLibLoader.java:1559)
02-27 16:09:27.454 13203-13203/? E/CatchMeIfYouCan: 	... 19 more
02-27 16:09:27.464 13203-13203/? E/CatchMeIfYouCan: Process (<default>) is exiting...
02-27 16:09:27.584 767-767/? E/MtpService: ptp mode false
02-27 16:10:00.006 588-588/? E/AlarmManagerService: set alarm to 22764.486000000
02-27 16:10:14.420 588-588/? E/DeviceStorageMonitorService: Will not process invalid message
02-27 16:11:00.004 588-588/? E/AlarmManagerService: set alarm to 22824.487000000
02-27 16:11:14.418 588-588/? E/DeviceStorageMonitorService: Will not process invalid message
02-27 16:12:00.003 588-588/? E/AlarmManagerService: set alarm to 22884.486000000
02-27 16:12:14.417 588-588/? E/DeviceStorageMonitorService: Will not process invalid message
02-27 16:13:00.011 588-588/? E/AlarmManagerService: set alarm to 22944.486000000
02-27 16:13:14.425 588-588/? E/DeviceStorageMonitorService: Will not process invalid message

**Comment by tobob** [comment]
aw forgot `extends Application` to `extends MultiDexApplication` in MainApplication.java but add `import android.support.multidex.MultiDexApplication;`

**Comment by tobob** [comment]
for example `public class MainApplication extends MultiDexApplication implements ReactApplication {`

**Comment by RameshSain** [comment]
Thanks, Man!!! You save my whole day
