### ISSUE TITLE
[0.48.1] [Android] Bug: no "Lcom/facebook/jni/HybridData;" field "mHybridData" in class

### ISSUE THREAD

**Issue by iegik** [facebook/react-native#15621]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

1. `react-native -v`: 
react-native-cli: 2.0.1
react-native: 0.48.1
2. `node -v`:
v8.4.0
3. `npm -v`:
5.3.0
4. `yarn --version`:

Then, specify:

- Target Platform: Android 7.1.1 android-25

```
classpath 'com.android.tools.build:gradle:2.3.3' // For Android 7 (O)
```

```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-bin.zip
```

```
android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"
    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 25
        ndk {
            // Test all dependences on x64 devices (might not work)
            // https://github.com/facebook/react-native/issues/2814
            abiFilters "armeabi-v7a", "x86"
        }
        multiDexEnabled true
        packagingOptions {
            exclude "lib/arm64-v8a/librealm-jni.so"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            // include "armeabi-v7a", "x86"
            include 'armeabi', 'armeabi-v7a', 'arm64-v8a', 'mips', 'x86', 'x86_64'
        }
    }
    buildTypes {
        debug {
            shrinkResources true
            debuggable true
            minifyEnabled true
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro", "devsupport.pro"
            applicationIdSuffix ".debug"
        }
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
}

...

    compile "com.android.support:appcompat-v7:26.0.0-alpha1"

```

- Development Operating System: macOS 10.12.6

- Build tools:

### Steps to Reproduce

(Write your steps here:)

1. cd android && ./gradlew clean && cd ..
2. node node_modules/react-native/local-cli/cli.js run-android
3. Open app in Emulator

### Expected Behavior

App works as in react-native v0.45.1

### Actual Behavior

App crashes at start

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

Fail to build an application on **android-25** with **ProGuard** enabled

```
java.lang.NoSuchFieldError: no "Lcom/facebook/jni/HybridData;" field "mHybridData" in class "Lcom/facebook/react/bridge/JavaScriptExecutor;" or its superclasses
	at com.facebook.react.bridge.CatalystInstanceImpl.initializeBridge(Native Method)
	at com.facebook.react.bridge.CatalystInstanceImpl.<init>(SourceFile:114)
	at com.facebook.react.bridge.CatalystInstanceImpl.<init>(SourceFile:42)
	at com.facebook.react.bridge.CatalystInstanceImpl$b.a(SourceFile:574)
	at com.facebook.react.l.a(SourceFile:999)
	at com.facebook.react.l.a(SourceFile:109)
	at com.facebook.react.l$4.run(SourceFile:802)
	at java.lang.Thread.run(Thread.java:818)
SFEffectCache:clear(), mSize = 0
```

react-native-cli: 2.0.1
react-native:

latest
0.48.1
0.47.2
0.47.1
0.47.0
0.47.0-rc.3
0.46.4

Works on:
 #0.45.1

Relative: https://github.com/facebook/react-native/pull/15619

**Comment by iegik** [comment]
Could be related https://github.com/facebook/react-native/issues/6692

**Comment by iegik** [comment]
Please, help

**Comment by akshetpandey** [comment]
This should fix the crashes
In `android/app/proguard-rules.pro`
```patch
--keep,includedescriptorclasses class com.facebook.react.cxxbridge.ModuleRegistryHolder { *; }
--keep,includedescriptorclasses class com.facebook.react.cxxbridge.CatalystInstanceImpl { *; }
--keep,includedescriptorclasses class com.facebook.react.cxxbridge.JavaScriptExecutor { *; }
+-keep,includedescriptorclasses class com.facebook.react.bridge.CatalystInstanceImpl { *; }
+-keep,includedescriptorclasses class com.facebook.react.bridge.JavaScriptExecutor { *; }
```

**Comment by iegik** [comment]
Please, share Your version of proguard-rules.pro file!
https://github.com/facebook/react-native/blob/master/local-cli/templates/HelloWorld/android/app/proguard-rules.pro

**Comment by akshetpandey** [comment]
```proguard
# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /usr/local/Cellar/android-sdk/24.3.3/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
# -keepclassmembers class fqcn.of.javascript.interface.for.webview {
#    public *;
# }

# Disabling obfuscation is useful if you collect stack traces from production crashes
# (unless you are using a system that supports de-obfuscate the stack traces).
# -dontobfuscate

# Just Android Stuff
-dontwarn org.apache.http.**
-dontnote org.apache.http.**
-dontwarn android.net.http.**
-dontnote android.net.http.**

# React Native

# Keep our interfaces so they can be used by other ProGuard rules.
# See http://sourceforge.net/p/proguard/bugs/466/
-keep,allowobfuscation,includedescriptorclasses @interface com.facebook.proguard.annotations.DoNotStrip
-keep,allowobfuscation,includedescriptorclasses @interface com.facebook.proguard.annotations.KeepGettersAndSetters
-keep,allowobfuscation,includedescriptorclasses @interface com.facebook.common.internal.DoNotStrip

# SoLoader
-keep class com.facebook.soloader.** { *; }
-keepclassmembers class com.facebook.soloader.SoLoader {
     static <fields>;
}

# Do not strip any method/class that is annotated with @DoNotStrip
-keep,includedescriptorclasses @com.facebook.proguard.annotations.DoNotStrip class *
-keep,includedescriptorclasses @com.facebook.common.internal.DoNotStrip class *
-keepclassmembers,includedescriptorclasses class * {
    @com.facebook.proguard.annotations.DoNotStrip *;
    @com.facebook.common.internal.DoNotStrip *;
}

-keepclassmembers,includedescriptorclasses @com.facebook.proguard.annotations.KeepGettersAndSetters class * {
  void set*(***);
  *** get*();
}

-keep,includedescriptorclasses class * { native <methods>; }
-keep,includedescriptorclasses class * { @com.facebook.react.uimanager.UIProp <fields>; }
-keep,includedescriptorclasses class * { @com.facebook.react.uimanager.annotations.ReactProp <methods>; }
-keep,includedescriptorclasses class * { @com.facebook.react.uimanager.annotations.ReactPropGroup <methods>; }
-keep,includedescriptorclasses class com.facebook.react.uimanager.UIProp { *; }

-keep,includedescriptorclasses class * extends com.facebook.react.bridge.JavaScriptModule { *; }
-keep,includedescriptorclasses class * extends com.facebook.react.bridge.NativeModule { *; }
-keep,includedescriptorclasses class com.facebook.react.bridge.CatalystInstanceImpl { *; }
-keep,includedescriptorclasses class com.facebook.react.bridge.JavaScriptExecutor { *; }
-keep,includedescriptorclasses class com.facebook.react.bridge.queue.NativeRunnable { *; }
-keep,includedescriptorclasses class com.facebook.react.bridge.ExecutorToken { *; }
-keep,includedescriptorclasses class com.facebook.react.bridge.ReadableType { *; }

-dontwarn com.facebook.react.**
-dontnote com.facebook.**

# TextLayoutBuilder uses a non-public Android constructor within StaticLayout.
# See libs/proxy/src/main/java/com/facebook/fbui/textlayoutbuilder/proxy for details.
-dontwarn android.text.StaticLayout

# GIF Support

-keep,includedescriptorclasses class com.facebook.imagepipeline.animated.factory.AnimatedFactoryImpl {
  public AnimatedFactoryImpl(com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory, com.facebook.imagepipeline.core.ExecutorSupplier);
}

# okhttp/okio

-keepattributes Signature
-keepattributes *Annotation*
-keep,includedescriptorclasses class okhttp3.** { *; }
-keep,includedescriptorclasses interface okhttp3.** { *; }
-dontwarn okhttp3.**
-dontnote okhttp3.**

-dontwarn javax.annotation.Nullable
-dontwarn javax.annotation.ParametersAreNonnullByDefault

-keep,includedescriptorclasses class sun.misc.Unsafe { *; }
-dontwarn java.nio.file.*
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
-dontwarn okio.**
-dontnote okio.**

# Adjust

-keep,includedescriptorclasses public class com.adjust.sdk.** { *; }
-keep,includedescriptorclasses class com.google.android.gms.common.ConnectionResult {
    int SUCCESS;
}
-keep,includedescriptorclasses class com.google.android.gms.ads.identifier.AdvertisingIdClient {
    com.google.android.gms.ads.identifier.AdvertisingIdClient$Info getAdvertisingIdInfo(android.content.Context);
}
-keep,includedescriptorclasses class com.google.android.gms.ads.identifier.AdvertisingIdClient$Info {
    java.lang.String getId();
    boolean isLimitAdTrackingEnabled();
}
# -keep,includedescriptorclasses class dalvik.system.VMRuntime {
#     java.lang.String getRuntime();
# }
# -keep class android.os.Build {
#     java.lang.String[] SUPPORTED_ABIS;
#     java.lang.String CPU_ABI;
# }
# -keep class android.content.res.Configuration {
#     android.os.LocaledList getLocales();
#     java.util.Locale locale;
# }
# -keep,includedescriptorclasses class android.os.LocaledList {
#     java.util.Locale get(int);
# }

# Firebase

-keepattributes EnclosingMethod
-keepattributes InnerClasses

# React-native-config

-keep,includedescriptorclasses class com.thriller.BuildConfig { *; }

# IAB V3

-keep,includedescriptorclasses class com.android.vending.billing.**

# React native deps ignore
-dontwarn io.invertase.firebase.**
-dontwarn com.idehub.Billing.**
-dontwarn com.google.firebase.**
-dontwarn com.google.android.**
-dontnote com.google.**
-dontnote me.leolin.shortcutbadger.**
-dontnote com.brentvatne.**
-dontnote com.yqritc.**
```
