### ISSUE TITLE
why i can't install devtool for window 10 

### ISSUE THREAD

**Issue by EroticCode** [facebook/react-native#15763]
C:\Users\MrBui\AppData\Roaming\npm\node_modules\react-devtools\node_modules\electron\index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (C:\Users\MrBui\AppData\Roaming\npm\node_modules\react-devtools\node_modules\electron\index.js:9:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\MrBui\AppData\Roaming\npm\node_modules\react-devtools\bin.js:2:16)
    at Module._compile (module.js:570:32)

**Comment by kelset** [comment]
It looks like it's an issue with [Electron](https://github.com/electron/electron), so I think you should try reinstalling it - if it doesn't solve it, you should open an issue on the [appropriate repo](https://github.com/facebook/react-devtools).
