### ISSUE TITLE
Release build crashes

### ISSUE THREAD

**Issue by bagrusss** [facebook/react-native#15794]
I used this config according to [documentation](https://facebook.github.io/react-native/docs/signed-apk-android.html):

```
...
android {
    ...
    defaultConfig { ... }
    signingConfigs {
        release {
             storeFile file(keyfile.jks)
             storePassword "some_pass"
             keyAlias "some_alias"
             keyPassword "some_pas_for_key"

        }
    }
    buildTypes {
        release {
            ...
            signingConfig signingConfigs.release
           ...
        }
    }
}
...
```
and run with `react-native run-android --variant=release` and got this exception:

```
Fatal Exception: java.lang.RuntimeException: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
       at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(CatalystInstanceImpl.java)
       at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:206)
       at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:34)
       at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:224)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1014)
       at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109)
       at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:802)
       at java.lang.Thread.run(Thread.java:762)
```

React version - 0.48

[this answer](https://stackoverflow.com/a/45506236/3078602) helped me, but it is crutch.

**Comment by radko93** [comment]
@facebook-github-bot no-template
