### ISSUE TITLE
C++ Exception in 'NativeModules': java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File java.io.File.getParentFile()' on a null object reference, stack:

### ISSUE THREAD

**Issue by cheerr** [facebook/react-native#15976]
com.facebook.react.common.JavascriptException: C++ Exception in 'NativeModules': java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File java.io.File.getParentFile()' on a null object reference, stack:
<unknown>@472:101
n@2:565
i@2:348
t@2:210
<unknown>@471:3413
n@2:565
i@2:348
t@2:210
<unknown>@468:3421
n@2:565
i@2:348
t@2:210
<unknown>@462:741
n@2:565
i@2:348
t@2:210
<unknown>@345:275
n@2:565
i@2:348
t@2:210
<unknown>@283:145
n@2:565
i@2:348
t@2:210
<unknown>@12:135
n@2:565
i@2:278
t@2:210
global code@532:9

	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:166)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:224)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
	at java.lang.Thread.run(Thread.java:818)

**Comment by radko93** [comment]
@facebook-github-bot no-template

**Comment by nes123** [comment]
any luck figuring it out ?

**Comment by yocokirk** [comment]
@cheerr did you manage to solve this? Are you using `react-native-fetch-blob` or are any of your dependencies using `react-native-fetch-blob`?

**Comment by nes123** [comment]
I am still having this problem and I am using react-native-fetch-blob

**Comment by yocokirk** [comment]
Interesting. I've got the same stack trace in bugsnag and using react-native-fetch-blob. I'll keep you updated if i find a solution

**Comment by chrusart** [comment]
This is a ```react-native-fetch-blob``` issue.
https://github.com/wkh237/react-native-fetch-blob/pull/557
WIP

**Comment by jheimes-silveira** [comment]
I also have a problem with this, here is the error code

```#0. Crashed: mqt_native_modules: 0 0 0x0000000000000000
       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:99)
       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:83)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:135)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
       at java.lang.Thread.run(Thread.java:818)

--

Fatal Exception: com.facebook.react.common.JavascriptException: C++ Exception in 'NativeModules': java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File java.io.File.getParentFile()' on a null object reference, stack:
<unknown>@1388:118
o@2:565
i@2:348
t@2:210
<unknown>@1387:3413
o@2:565
i@2:348
t@2:210
<unknown>@1384:3423
o@2:565
i@2:348
t@2:210
<unknown>@1383:136
o@2:565
i@2:348
t@2:210
<unknown>@1381:608
o@2:565
i@2:348
t@2:210
<unknown>@631:2291
o@2:565
i@2:348
t@2:210
<unknown>@380:350
o@2:565
i@2:348
t@2:210
<unknown>@12:47
o@2:565
i@2:278
t@2:210
global code@1705:9

       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:99)
       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:83)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:135)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
       at java.lang.Thread.run(Thread.java:818)

#0. Crashed: mqt_native_modules: 0 0 0x0000000000000000
       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:99)
       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:83)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:135)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
       at java.lang.Thread.run(Thread.java:818)```
