### ISSUE TITLE
Android app crashes upon enabling "Remote JS Debugging"

### ISSUE THREAD

**Issue by iremlopsum** [facebook/react-native#15987]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

1. `react-native -v`: 0.48.1
2. `node -v`: v6.9.5
3. `npm -v`: 4.6.1

Then, specify:
- Target Platform: Android & iOS
- Development Operating System: Linux (Elementary OS)

### Issue

This started happening lately, not directly a result of upgrading RN or installing a package (as far as I can tell). As soon as I press  "Remote JS Debugging" the app crashes and stays in a loop like that. Open app, crashes again until I'm fast enough to disable "Remote JS Debugging" or unintall and reinstall the app again.

Using logcat I receive the following error

```
09-18 16:05:17.683 10778 10834 E AndroidRuntime: FATAL EXCEPTION: mqt_js
09-18 16:05:17.683 10778 10834 E AndroidRuntime: Process: com.MyPackageName, PID: 10778
09-18 16:05:17.683 10778 10834 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 3680336 byte allocation with 322024 free bytes and 314KB until OOM, max allowed footprint 16777216, growth limit 16777216
09-18 16:05:17.683 10778 10834 E AndroidRuntime: 	at java.lang.StringFactory.newStringFromChars(StringFactory.java:220)
09-18 16:05:17.683 10778 10834 E AndroidRuntime: 	at java.lang.StringBuffer.toString(StringBuffer.java:671)
09-18 16:05:17.683 10778 10834 E AndroidRuntime: 	at java.io.StringWriter.toString(StringWriter.java:210)
09-18 16:05:17.683 10778 10834 E AndroidRuntime: 	at com.facebook.react.devsupport.JSDebuggerWebSocketClient.executeJSCall(JSDebuggerWebSocketClient.java:131)
09-18 16:05:17.683 10778 10834 E AndroidRuntime: 	at com.facebook.react.devsupport.WebsocketJavaScriptExecutor.executeJSCall(WebsocketJavaScriptExecutor.java:181)
09-18 16:05:17.683 10778 10834 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-18 16:05:17.683 10778 10834 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
09-18 16:05:17.683 10778 10834 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
09-18 16:05:17.683 10778 10834 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
09-18 16:05:17.683 10778 10834 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
09-18 16:05:17.683 10778 10834 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
09-18 16:05:17.683 10778 10834 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
09-18 16:05:17.684  1472  2253 W ActivityManager:   Force finishing activity com.MyPackageName/.MainActivity
09-18 16:05:17.697  1472  1488 I ActivityManager: Showing crash dialog for package com.MyPackageName u0
```

Any ideas?

**Comment by rodrigopivi** [comment]
Using RN v0.48.3 here.
The app runs fine without debugging on. and having the same issue, there is this bountysource issue describing the problem as well too https://www.bountysource.com/issues/37414352-android-throwing-outofmemoryerror-crash

I think the problem is when it connects to chrome, because if i turn the debug port off. `adb forward --remove-all`. The app does not crash, i see a red exception box with the XMLHttpRequest exception. Then the crash happens when turning the `adb forward tcp:8082 tcp:8082`.

This is the logs as soon as i forward 8082:
```
--------- beginning of crash
0.375 4839-4915/x.x.x A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 4915 (NanoHttpd Reque)
0.479 1356-1356/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
0.479 1356-1356/? A/DEBUG: Build fingerprint: 'Android/sdk_google_phone_x86_64/generic_x86_64:6.0/MASTER/3738108:userdebug/test-keys'
0.479 1356-1356/? A/DEBUG: Revision: '0'
0.479 1356-1356/? A/DEBUG: ABI: 'x86'
0.479 1356-1356/? A/DEBUG: pid: 4839, tid: 4915, name: NanoHttpd Reque  >>> x.x.x <<<
0.479 1356-1356/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
0.486 1356-1356/? A/DEBUG: Abort message: 'art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: GetStringUTFChars received NULL jstring'
0.486 1356-1356/? A/DEBUG:     eax 00000000  ebx 000012e7  ecx 00001333  edx 00000006
0.486 1356-1356/? A/DEBUG:     esi deed2980  edi 0000000b
0.486 1356-1356/? A/DEBUG:     xcs 00000023  xds 0000002b  xes 0000002b  xfs 000000e7  xss 0000002b
0.487 1356-1356/? A/DEBUG:     eip f72e27c6  ebp 00001333  esp deed0ff0  flags 00200206
0.493 1356-1356/? A/DEBUG: backtrace:
0.493 1356-1356/? A/DEBUG:     #00 pc 000857c6  /system/lib/libc.so (tgkill+22)
0.493 1356-1356/? A/DEBUG:     #01 pc 00082478  /system/lib/libc.so (pthread_kill+70)
0.493 1356-1356/? A/DEBUG:     #02 pc 000280a5  /system/lib/libc.so (raise+36)
0.493 1356-1356/? A/DEBUG:     #03 pc 0002187d  /system/lib/libc.so (abort+80)
0.494 1356-1356/? A/DEBUG:     #04 pc 005171cb  /system/lib/libart.so (art::Runtime::Abort()+377)
0.494 1356-1356/? A/DEBUG:     #05 pc 0014d933  /system/lib/libart.so (art::LogMessage::~LogMessage()+1343)
0.494 1356-1356/? A/DEBUG:     #06 pc 003a5042  /system/lib/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+3842)
0.494 1356-1356/? A/DEBUG:     #07 pc 003a5c9c  /system/lib/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, char*)+116)
0.495 1356-1356/? A/DEBUG:     #08 pc 00163950  /system/lib/libart.so (art::ScopedCheck::AbortF(char const*, ...)+62)
0.495 1356-1356/? A/DEBUG:     #09 pc 0016f0b6  /system/lib/libart.so (art::ScopedCheck::Check(art::ScopedObjectAccess&, bool, char const*, art::JniValueType*) (.constprop.114)+4710)
0.495 1356-1356/? A/DEBUG:     #10 pc 0017d0ec  /system/lib/libart.so (art::CheckJNI::GetStringUTFChars(_JNIEnv*, _jstring*, unsigned char*)+636)
0.495 1356-1356/? A/DEBUG:     #11 pc 0044c654  /data/app/x.x.x-1/lib/x86/librealmreact.so (JNIEnv_::GetStringUTFChars(_jstring*, unsigned char*)+40)
0.495 1356-1356/? A/DEBUG:     #12 pc 0044ca58  /data/app/x.x.x-1/lib/x86/librealmreact.so (Java_io_realm_react_RealmReactModule_processChromeDebugCommand+109)
0.495 1356-1356/? A/DEBUG:     #13 pc 0013d887  /system/lib/libart.so (art_quick_generic_jni_trampoline+71)
0.495 1356-1356/? A/DEBUG:     #14 pc 00137a42  /system/lib/libart.so (art_quick_invoke_stub+338)
0.495 1356-1356/? A/DEBUG:     #15 pc 00143584  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+212)
0.495 1356-1356/? A/DEBUG:     #16 pc 005e048e  /system/lib/libart.so (artInterpreterToCompiledCodeBridge+190)
0.495 1356-1356/? A/DEBUG:     #17 pc 0032894d  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+445)
0.496 1356-1356/? A/DEBUG:     #18 pc 0032d374  /system/lib/libart.so (bool art::interpreter::DoInvoke<(art::InvokeType)1, false, false>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+196)
0.496 1356-1356/? A/DEBUG:     #19 pc 000fc789  /system/lib/libart.so (art::JValue art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue)+30089)
0.496 1356-1356/? A/DEBUG:     #20 pc 003008e7  /system/lib/libart.so (artInterpreterToInterpreterBridge+188)
0.496 1356-1356/? A/DEBUG:     #21 pc 0032894d  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+445)
0.496 1356-1356/? A/DEBUG:     #22 pc 0032cdb0  /system/lib/libart.so (bool art::interpreter::DoInvoke<(art::InvokeType)0, false, false>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+160)
0.496 1356-1356/? A/DEBUG:     #23 pc 000fc6c3  /system/lib/libart.so (art::JValue art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue)+29891)
0.496 1356-1356/? A/DEBUG:     #24 pc 003008e7  /system/lib/libart.so (artInterpreterToInterpreterBridge+188)
0.496 1356-1356/? A/DEBUG:     #25 pc 0032894d  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+445)
0.496 1356-1356/? A/DEBUG:     #26 pc 0032e9e9  /system/lib/libart.so (bool art::interpreter::DoInvoke<(art::InvokeType)2, false, false>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+297)
0.496 1356-1356/? A/DEBUG:     #27 pc 000fc915  /system/lib/libart.so (art::JValue art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue)+30485)
0.496 1356-1356/? A/DEBUG:     #28 pc 003008e7  /system/lib/libart.so (artInterpreterToInterpreterBridge+188)
0.497 1356-1356/? A/DEBUG:     #29 pc 0032894d  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+445)
0.497 1356-1356/? A/DEBUG:     #30 pc 0032e9e9  /system/lib/libart.so (bool art::interpreter::DoInvoke<(art::InvokeType)2, false, false>(art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+297)
0.497 1356-1356/? A/DEBUG:     #31 pc 000fc915  /system/lib/libart.so (art::JValue art::interpreter::ExecuteGotoImpl<false, false>(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue)+30485)
0.497 1356-1356/? A/DEBUG:     #32 pc 003004f0  /system/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*)+128)
0.497 1356-1356/? A/DEBUG:     #33 pc 00667a23  /system/lib/libart.so (artQuickToInterpreterBridge+808)
0.497 1356-1356/? A/DEBUG:     #34 pc 0013d94d  /system/lib/libart.so (art_quick_to_interpreter_bridge+77)
0.497 1356-1356/? A/DEBUG:     #35 pc 722c29cf  /data/dalvik-cache/x86/system@framework@boot.oat (offset 0x1eb2000)
0.709 1356-1356/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_04
0.709 1356-1356/? E/DEBUG: AM write failed: Broken pipe
                                        
                                        --------- beginning of system
0.709 1642-1659/system_process I/BootReceiver: Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE)
0.735 1642-4920/system_process W/ActivityManager:   Force finishing activity x.x.x/net.x.android.MainActivity
0.757 1261-1347/? D/gralloc_ranchu: gralloc_alloc: format 1 and usage 0x333 imply creation of host color buffer
                                                 
                                                 [ 0.774  1642: 4920 D/         ]
                                                 HostConnection::get() New Host Connection established 0x7face71fbd20, tid 4920
0.785 1642-1687/system_process W/InputDispatcher: channel '2022845  (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
0.785 1642-1687/system_process E/InputDispatcher: channel '2022845  (server)' ~ Channel is unrecoverably broken and will be disposed!
0.785 1642-1687/system_process W/InputDispatcher: channel 'e189fd5 x.x.x/net.x.android.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
0.786 1642-1687/system_process E/InputDispatcher: channel 'e189fd5 x.x.x/net.x.android.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
0.786 1642-1687/system_process W/InputDispatcher: channel '61bda60 x.x.x/net.x.android.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
0.787 1642-1687/system_process E/InputDispatcher: channel '61bda60 x.x.x/net.x.android.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
0.798 1642-1653/system_process D/GraphicsStats: Buffer count: 4
0.819 1364-1364/? I/Zygote: Process 4839 exited due to signal (6)
0.821 1261-1261/? E/EGL_emulation: tid 1261: eglCreateSyncKHR(1660): error 0x3004 (EGL_BAD_ATTRIBUTE)
0.870 1642-2052/system_process I/WindowState: WIN DEATH: Window{2022845 u0 x.x.x}
0.870 1642-2052/system_process W/InputDispatcher: Attempted to unregister already unregistered input channel '2022845  (server)'
0.876 1642-2287/system_process I/WindowState: WIN DEATH: Window{61bda60 u0 x.x.x/net.x.android.MainActivity}
0.876 1642-2287/system_process W/InputDispatcher: Attempted to unregister already unregistered input channel '61bda60 x.x.x/net.x.android.MainActivity (server)'
0.877 1642-2003/system_process I/WindowState: WIN DEATH: Window{e189fd5 u0 x.x.x/net.x.android.MainActivity}
0.877 1642-2003/system_process W/InputDispatcher: Attempted to unregister already unregistered input channel 'e189fd5 x.x.x/net.x.android.MainActivity (server)'
0.879 1642-4920/system_process D/gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
0.881 1642-4920/system_process W/ActivityManager: Exception thrown during pause
                                                               android.os.DeadObjectException
                                                                   at android.os.BinderProxy.transactNative(Native Method)
                                                                   at android.os.BinderProxy.transact(Binder.java:503)
                                                                   at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
                                                                   at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:867)
                                                                   at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
                                                                   at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
                                                                   at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2755)
                                                                   at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11971)
                                                                   at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11867)
                                                                   at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12556)
                                                                   at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12063)
                                                                   at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
0.887 1259-1259/? E/lowmemorykiller: Error opening /proc/4839/oom_score_adj; errno=2
0.888 1642-1792/system_process I/ActivityManager: Process x.x.x (pid 4839) has died
0.898 1642-1661/system_process W/WindowAnimator: Failed to dispatch window animation state change.
                                                              android.os.DeadObjectException
                                                                  at android.os.BinderProxy.transactNative(Native Method)
                                                                  at android.os.BinderProxy.transact(Binder.java:503)
                                                                  at android.view.IWindow$Stub$Proxy.onAnimationStarted(IWindow.java:520)
                                                                  at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:282)
                                                                  at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
                                                                  at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
                                                                  at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                  at com.android.server.ServiceThread.run(ServiceThread.java:46)
0.933 1261-1307/? D/gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
0.947 1261-1347/? D/gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
0.951 1261-1347/? D/gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
0.005 1642-3421/system_process I/OpenGLRenderer: Initialized EGL, version 1.4
0.025 1642-2100/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
0.073 1261-1347/? D/gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
0.086 1261-1307/? D/gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
0.088 1261-1307/? D/gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
0.150 1642-1661/system_process W/WindowAnimator: Failed to dispatch window animation state change.
                                                              android.os.DeadObjectException
                                                                  at android.os.BinderProxy.transactNative(Native Method)
                                                                  at android.os.BinderProxy.transact(Binder.java:503)
                                                                  at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
                                                                  at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
                                                                  at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
                                                                  at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
                                                                  at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                  at com.android.server.ServiceThread.run(ServiceThread.java:46)
0.152 1642-1661/system_process W/AppOps: Finishing op nesting under-run: uid 10086 pkg x.x.x code 24 time=0 duration=0 nesting=0
0.922 1642-1661/system_process W/WindowAnimator: Failed to dispatch window animation state change.
                                                              android.os.DeadObjectException
                                                                  at android.os.BinderProxy.transactNative(Native Method)
                                                                  at android.os.BinderProxy.transact(Binder.java:503)
                                                                  at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
                                                                  at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
                                                                  at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
                                                                  at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
                                                                  at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                  at com.android.server.ServiceThread.run(ServiceThread.java:46)
0.923 1642-1661/system_process W/WindowAnimator: Failed to dispatch window animation state change.
                                                              android.os.DeadObjectException
                                                                  at android.os.BinderProxy.transactNative(Native Method)
                                                                  at android.os.BinderProxy.transact(Binder.java:503)
                                                                  at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
                                                                  at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
                                                                  at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
                                                                  at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
                                                                  at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                  at com.android.server.ServiceThread.run(ServiceThread.java:46)
09-23 09:15:29.031 2480-4922/com.google.android.gms W/PlatformStatsUtil: Could not retrieve Usage & Diagnostics setting. Giving up.
09-23 09:15:29.062 1642-2287/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
09-23 09:15:34.100 2480-4922/com.google.android.gms W/PlatformStatsUtil: Could not retrieve Usage & Diagnostics setting. Giving up.
09-23 09:16:00.073 1261-1324/? D/hwcomposer: hw_composer sent 824 syncs in 60s
```

**Comment by rodrigopivi** [comment]
Nevermind, found that this issue was related to Realm update >> https://github.com/realm/realm-js/issues/1294

Fixed there now.
