### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Error invoking callback 3657

### ISSUE THREAD

**Issue by oakis** [facebook/react-native#16072]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

No

### Environment

    react-native: 0.47.1
    react: 16.0.0-alpha.12

I got this crash report from Fabric.io but I dont know where and when it happened.

```
Fatal Exception: java.lang.RuntimeException: Error invoking callback 3657
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:154)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:761)
Caused by com.facebook.jni.CppException: Failed to convert to string: No default value
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:154)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by iamdurui** [comment]
yes ，I also get this problem ,but my crash is 
Fatal Exception: java.lang.RuntimeException
Error invoking callback 2432

**Comment by iamdurui** [comment]
@oakis  have you find the solution ? thanks

**Comment by oakis** [comment]
@iamdurui I have not found any solution, but the error has not happened again as far as I can see.
It seems that it happened while the phone was locked and in my pocket if that is any help to you.
Let me know if you solve it!
