### ISSUE TITLE
Unable to load react from android library

### ISSUE THREAD

**Issue by amarkovits** [facebook/react-native#16112]
I want to integrate react native into my existing android library.
The problem is that it only works if the activity using ReactRootView is part of the final android app (I use the same activity as in the integration example). If I move the activity from the app to the library i get the error: 
` java.lang.RuntimeException: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
                                                                                at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
                                                                                at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:206)
                                                                                at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:34)
                                                                                at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:224)
                                                                                at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:993)
                                                                                at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109)
                                                                                at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:802)
                                                                                at java.lang.Thread.run(Thread.java:761)

This only happens when I try to use the packager server. When I bundle react in the assets folder of the library everything works fine. But when I try to use the packager server it only works if the activity with the ReactRootView is part of the app and not of the library. Unfortunatly I really need the activity to be part of the library since I reuse the library in hundreds of applications.

**Comment by amarkovits** [comment]
I found the problem. In my library BuildConfig.DEBUG is false and I use .setUseDeveloperSupport(BuildConfig.DEBUG). 
Setting .setUseDeveloperSupport(true) enables the packager server also using the library.
