### ISSUE TITLE
react-native-git-upgrade ERROR: fatal: No remote repository specified.  Please, specify either a URL or a remote name from which new revisions should be fetched.

### ISSUE THREAD

**Issue by sandropoluan** [facebook/react-native#16131]
I have problems when trying to upgrade using `react-native-git-upgrade`.
First issue was same with [https://github.com/facebook/react-native/issues/11578](https://github.com/facebook/react-native/issues/11578).

Unfortunately, none of the solution on that thread helped me.

So, I trying to clear yarn cache. 
I run `yarn cache clean`

And when I trying to run `react-native-git-upgrade` again,
This error appear:
 
```
git-upgrade info Install the new version
error Command failed.
Exit code: 1
Command: git
Arguments: pull
Directory: C:\Users\Ando\AppData\Local\Yarn\cache\v1\.tmp\a3450fedabcb67009ae55c8f322f57b0
Output:
fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.
git-upgrade ERR! An error occurred during upgrade:
git-upgrade ERR! Error: Command 'yarn add react-native@0.48.4 react@16.0.0-alpha.12' exited with code 1:
stderr: undefinederror Command failed.
Exit code: 1
Command: git
Arguments: pull
Directory: C:\Users\Ando\AppData\Local\Yarn\cache\v1\.tmp\a3450fedabcb67009ae55c8f322f57b0
Output:
fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.

stdout: yarn add v0.24.5
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

    at ChildProcess.child.on.code (C:/Users/Ando/AppData/Roaming/npm/node_modules/react-native-git-upgrade/cliEntry.js:58:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
git-upgrade ERR! Restore initial sources
Note: checking out 'project-snapshot'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at adaaa8d... Project snapshot
```
What should I do?

My Current React Native : 0.44.0
git version 2.13.1.windows.2
Yarn version 0.24.5

**Comment by spencewine** [comment]
@sandropoluan did you ever resolve this issue? I'm running into it with an upgrade from RN@0.50.3
