### ISSUE TITLE
peerDependencies = '16.0.0-beta.5' instead of ^16.0.0

### ISSUE THREAD

**Issue by darknoon** [facebook/react-native#16140]
### Is this a bug report?

YES

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

YES
### Environment

$ react-native info
/Users/andrew/Code/Lobe/lobe/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

SyntaxError: /Users/andrew/Code/Lobe/lobe/node_modules/react-native/local-cli/core/index.js: Unexpected token (29:2)
  27 | 
  28 | export type RNConfig = {
> 29 |   ...ConfigT,
     |   ^
  30 |   /**
  31 |    * Returns an array of project commands used by the CLI to load
  32 |    */
    at Parser.pp$5.raise (/Users/andrew/Code/Lobe/lobe/node_modules/babylon/lib/index.js:4373:13)
    at Parser.pp.unexpected (/Users/andrew/Code/Lobe/lobe/node_modules/babylon/lib/index.js:1716:8)
    at Parser.pp$3.parseIdentifier (/Users/andrew/Code/Lobe/lobe/node_modules/babylon/lib/index.js:4251:10)
    at Parser.pp$8.flowParseObjectPropertyKey (/Users/andrew/Code/Lobe/lobe/node_modules/babylon/lib/index.js:5169:90)
    at Parser.pp$8.flowParseObjectType (/Users/andrew/Code/Lobe/lobe/node_modules/babylon/lib/index.js:5283:26)
    at Parser.pp$8.flowParsePrimaryType (/Users/andrew/Code/Lobe/lobe/node_modules/babylon/lib/index.js:5462:19)
    at Parser.pp$8.flowParsePostfixType (/Users/andrew/Code/Lobe/lobe/node_modules/babylon/lib/index.js:5580:19)
    at Parser.pp$8.flowParsePrefixType (/Users/andrew/Code/Lobe/lobe/node_modules/babylon/lib/index.js:5597:17)
    at Parser.pp$8.flowParseAnonFunctionWithoutParens (/Users/andrew/Code/Lobe/lobe/node_modules/babylon/lib/index.js:5602:20)
    at Parser.pp$8.flowParseIntersectionType (/Users/andrew/Code/Lobe/lobe/node_modules/babylon/lib/index.js:5617:19)
### Steps to Reproduce

(Write your steps here:)

1. $ yarn info react-native@0.49.0-rc.6 peerDependencies

### Expected Behavior

Can use `react-native` with the currently released version of React

### Actual Behavior

Not clear if it's supported.

**Comment by vonovak** [comment]
use the react version that comes with react native by default

**Comment by grabbou** [comment]
"Fixed" in `0.50.0-rc.0`

**Comment by jpb12** [comment]
Is there a reason the version is not specified as a range?  The new peer dependency specifies 16.0.0 exactly, but why would a hypothetical 16.0.1 not work?
