### ISSUE TITLE
PermissionsAndroid is not mocked in Jest

### ISSUE THREAD

**Issue by FrancisMurillo** [facebook/react-native#16156]
### Is this a bug report?

YES

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

NO

### Environment

Environment:
  OS:  Linux 4.9
  Node:  7.10.0
  Yarn:  0.24.6
  npm:  4.6.1
  Watchman:  Not Found
  Xcode: Not Found
  Android Studio: Not Found

  Target Platform: Android (5.0)
  
  Packages: (wanted => installed)
    react-native: 0.48.4 => 0.48.4
    react: 16.0.0 => 16.0.0
    jest: 21.1.0 => 21.1.0
    babel-preset-react-native: 4.0.0 => 4.0.0

### Steps to Reproduce

1. Create a new `react-native` project with minimal `redux` and `redux-saga` setup
2. Create a simple saga with a line `yield call(PermissionsAndroid.requestMultiple, [PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION]);`
3. Test the saga using `npm test`

### Expected Behavior

Test should just complete normally

### Actual Behavior

Test completed but with a verbose error

```
    console.log node_modules/redux-saga/lib/internal/utils.js:238
      redux-saga error: uncaught
      at _callee 
       TypeError: Cannot read property 'requestMultiplePermissions' of undefined
          at requestMultiple (/home/somewhere/Fakespace/react-native-sandbox/test_bug/node_modules/react-native/Libraries/PermissionsAndroid/PermissionsAndroid.js:189:40)
          at runCallEffect (/home/somewhere/Fakespace/react-native-sandbox/test_bug/node_modules/redux-saga/lib/internal/proc.js:514:19)
          at runEffect (/home/somewhere/Fakespace/react-native-sandbox/test_bug/node_modules/redux-saga/lib/internal/proc.js:436:402)
          at next (/home/somewhere/Fakespace/react-native-sandbox/test_bug/node_modules/redux-saga/lib/internal/proc.js:317:9)
          at proc (/home/somewhere/Fakespace/react-native-sandbox/test_bug/node_modules/redux-saga/lib/internal/proc.js:272:3)
          at runSaga (/home/somewhere/Fakespace/react-native-sandbox/test_bug/node_modules/redux-saga/lib/internal/runSaga.js:59:33)
          at Object.<anonymous> (/home/somewhere/Fakespace/react-native-sandbox/test_bug/index.android.js:26:16)
          at Runtime._execModule (/home/somewhere/Fakespace/react-native-sandbox/test_bug/node_modules/jest-runtime/build/index.js:520:13)
          at Runtime.requireModule (/home/somewhere/Fakespace/react-native-sandbox/test_bug/node_modules/jest-runtime/build/index.js:332:14)
          at Runtime.requireModuleOrMock (/home/somewhere/Fakespace/react-native-sandbox/test_bug/node_modules/jest-runtime/build/index.js:408:19)
```

Although not fatal at the moment, this might affect testing of sagas or flows or is slightly inconvenient when reading the log.

### Reproducible Demo

https://github.com/FrancisMurillo/react-native-permissions-android-jest-bug

### Possible Solution

Add this snippet to the `setup.js`

```
  Networking: {
    sendRequest: jest.fn(),
    abortRequest: jest.fn(),
    addListener: jest.fn(),
    removeListeners: jest.fn(),
  },
  // New sample mock here
  PermissionsAndroid: {
    PERMISSIONS: {ACCESS_FINE_LOCATION: "MEOW"},
    requestMultiple: () => ({})
  },
```

**Comment by vonovak** [comment]
this is not a bug, you have to mock this yourself, or use react-native-mock

**Comment by FrancisMurillo** [comment]
I see. Thanks.
