### ISSUE TITLE
Execution failed for task ':app:compileDebugAidl' during compilation

### ISSUE THREAD

**Issue by giacomocerquone** [facebook/react-native#16178]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Environment

(There is a bug in your info too)

```
Environment:
  OS:  Linux 4.10
  Node:  8.6.0
  Yarn:  Not Found
  npm:  5.4.2
  Watchman:  Not Found
Error: unable to print environment info
{ Error: not found: xcodebuild
    at getNotFoundError (/home/jhacked/Github/asd/node_modules/which/which.js:13:12)
    at Function.whichSync [as sync] (/home/jhacked/Github/asd/node_modules/which/which.js:134:9)
    at getXcodeVersion (/home/jhacked/Github/asd/node_modules/envinfo/envinfo.js:17:25)
    at Object.module.exports.print (/home/jhacked/Github/asd/node_modules/envinfo/envinfo.js:136:28)
    at Object.info (/home/jhacked/Github/asd/node_modules/react-native/local-cli/info/info.js:17:13)
    at Promise.resolve.then (/home/jhacked/Github/asd/node_modules/react-native/local-cli/cliEntry.js:109:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:187:16) code: 'ENOENT' }

```
### Steps to Reproduce

1. Create a new project wiht react-native init temp
2. cd temp
3. npm install
4. react-native run-android (and here I get the error)

### Actual Behavior

I've got an `Execution failed for task ':app:compileDebugAidl'`

Actually I found this issue where the guy had the same problem: https://github.com/facebook/react-native/issues/14733 and I managed to solve it like he says, but I'm not comfortable repeating all those steps for every project I have.

I'd like to know why this happens, what exactly is missing and how to install this missing piece in order to happily compile my apks

Thank you very much for you work

**Comment by giacomocerquone** [comment]
Hint: with create-react-native-app everything works gracefully

**Comment by giacomocerquone** [comment]
Another guy has the same problem here and it got it working but I don't know how: https://github.com/react-community/react-native-image-picker/issues/521

Someone can give me a hand on this?

**Comment by DanielArthurUK** [comment]
@giacomocerquone Did you ever find a fix for this? 🤞

**Comment by giacomocerquone** [comment]
@DanielArthurUK I've always used the react-native boilerplate and upgrading it with react-native-git-upgrade, this problem disappeared

**Comment by giacomocerquone** [comment]
@DanielArthurUK I correct myself, after upgrading it is actually not working.
Someone from above can explain us something?
