### ISSUE TITLE
Test renderer generates an error when trying to render an animated FlatList

### ISSUE THREAD

**Issue by Elethier** [facebook/react-native#16188]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  6.11.2
  Yarn:  Not Found
  npm:  3.10.10
  Watchman:  4.9.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.4 => 0.48.4

### Steps to Reproduce

I imported a module that was using an animated `FlatList` and ran into some issues when running the unit test provided out-of-the-box by `react-native init`. Specifically, I was seeing an error during test execution, where none of the code was related to my project. I isolated the issue to a specific test case and have provided it here.

Here's the exact steps:
1. Create an animated component based on `FlatList`.
2. Create the component in a Jest test using the `renderer.create()` function.

Here's a code snippet of the failing test.

```
import React from 'react'
import { Animated, FlatList } from 'react-native'
import renderer from 'react-test-renderer'

it('Renders an AnimatedFlatList', () => {
    const AnimatedFlatList = Animated.createAnimatedComponent(FlatList)
    renderer.create(
        <AnimatedFlatList />
    )
})
```

### Expected Behavior

I expected the test to pass.

### Actual Behavior

The test fails with this output:
```
 FAIL  __tests__/flatlist.js
  ✕ Renders an AnimatedFlatList (312ms)

  ● Renders an AnimatedFlatList

    TypeError: nodeHandle.getHostNode is not a function
      
      at Object.findNumericNodeHandleStack [as findNodeHandle] (node_modules/react-native/Libraries/Renderer/ReactNativeStack-dev.js:2324:76)
      at VirtualizedList.getScrollableNode (node_modules/react-native/Libraries/Lists/VirtualizedList.js:314:20)
      at FlatList.getScrollableNode (node_modules/react-native/Libraries/Lists/FlatList.js:544:886)
      at AnimatedComponent._attachNativeEvents (node_modules/react-native/Libraries/Animated/src/AnimatedImplementation.js:1790:17)
      at AnimatedComponent.componentDidMount (node_modules/react-native/Libraries/Animated/src/AnimatedImplementation.js:1783:6)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5217:24)
      at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5752:9)
      at invokeGuardedCallback$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2003:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2073:36)
      at commitAllWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5865:19)

  console.error node_modules/react-native/Libraries/Core/ExceptionsManager.js:73
    React caught an error thrown by AnimatedComponent. You should fix this error in your code. Consider adding an error boundary to your tree to customize error handling behavior.
    
    TypeError: nodeHandle.getHostNode is not a function
    
    The error is located at: 
        in AnimatedComponent
    
    The error was thrown at: 
        at Object.findNumericNodeHandleStack [as findNodeHandle] (/Users/praneetsahgal/Desktop/react-native-bug-reports/FlatListBug/node_modules/react-native/Libraries/Renderer/ReactNativeStack-dev.js:2324:76),
        at VirtualizedList.getScrollableNode (/Users/praneetsahgal/Desktop/react-native-bug-reports/FlatListBug/node_modules/react-native/Libraries/Lists/VirtualizedList.js:314:20),
        at FlatList.getScrollableNode (/Users/praneetsahgal/Desktop/react-native-bug-reports/FlatListBug/node_modules/react-native/Libraries/Lists/FlatList.js:544:886),
        at AnimatedComponent._attachNativeEvents (/Users/praneetsahgal/Desktop/react-native-bug-reports/FlatListBug/node_modules/react-native/Libraries/Animated/src/AnimatedImplementation.js:1790:17),
        at AnimatedComponent.componentDidMount (/Users/praneetsahgal/Desktop/react-native-bug-reports/FlatListBug/node_modules/react-native/Libraries/Animated/src/AnimatedImplementation.js:1783:6),
        at commitLifeCycles (/Users/praneetsahgal/Desktop/react-native-bug-reports/FlatListBug/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5217:24),
        at commitAllLifeCycles (/Users/praneetsahgal/Desktop/react-native-bug-reports/FlatListBug/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5752:9),
        at invokeGuardedCallback$1 (/Users/praneetsahgal/Desktop/react-native-bug-reports/FlatListBug/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2003:10),
        at invokeGuardedCallback (/Users/praneetsahgal/Desktop/react-native-bug-reports/FlatListBug/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2073:36),
        at commitAllWork (/Users/praneetsahgal/Desktop/react-native-bug-reports/FlatListBug/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5865:19)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
```

### Reproducible Demo

[Here's](https://github.com/Elethier/ReactNativeFlatListBug) an example project with the issue. Simply run `npm test` to see the test fail.

### Other notes
I should note that I _did_ find a workaround, but I'm logging this issue anyway, because the workaround involves mocking out React Native code using Jest. The following code stubs out FlatList, "fixing" the issue:

```
jest.mock('FlatList', () => {
    const RealComponent = require.requireActual('FlatList')
    const React = require('React')
    class FlatList extends React.Component {
        render () {
            this.props.getScrollableNode = function () {}
            return React.createElement('FlatList', this.props, this.props.children)
        }
    }
    FlatList.propTypes = RealComponent.propTypes
    return FlatList
})
```

**Comment by Elethier** [comment]
So, in the time it took me to write up this issue, version 0.49.0 of React Native was released, and I think it fixed the error. What should I do with this issue?
