### ISSUE TITLE
ReactNative app generated on Windows 10 is not working on Linux Mint 18.2 (react-native-cli 2.0.1)

### ISSUE THREAD

**Issue by ManvendraSK** [facebook/react-native#16209]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Scanning 658 folders for symlinks in /home/manvendra/Desktop/work/app/node_modules (4ms)

Environment:
  OS:  Linux 4.8
  Node:  6.10.1
  Yarn:  1.1.0
  npm:  3.10.10
  Watchman:  Not Found
Error: unable to print environment info
{ Error: not found: xcodebuild
    at getNotFoundError (/home/manvendra/Desktop/work/app/node_modules/which/which.js:13:12)
    at Function.whichSync [as sync] (/home/manvendra/Desktop/work/app/node_modules/which/which.js:134:9)
    at getXcodeVersion (/home/manvendra/Desktop/work/app/node_modules/envinfo/envinfo.js:17:25)
    at Object.module.exports.print (/home/manvendra/Desktop/work/app/node_modules/envinfo/envinfo.js:136:28)
    at Object.info (/home/manvendra/Desktop/work/app/node_modules/react-native/local-cli/info/info.js:17:13)
    at Promise.resolve.then (/home/manvendra/Desktop/work/app/node_modules/react-native/local-cli/cliEntry.js:109:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9) code: 'ENOENT' }

  Packages: (wanted => installed)
    react-native: 0.48.4 => 0.48.4
    react: 16.0.0-alpha.12 => 16.0.0-alpha.12

  Target Platform: Android 6 (23.0.1)`

### Steps to Reproduce

1. Create new project *react-native init myapp* on Windows 10
2. Run it on Linux, after pushing and cloning the repo to and from github

### Expected Behavior

Should install on the emulator.

### Actual Behavior

It's not working and exiting with the error below
Scanning 658 folders for symlinks in /home/manvendra/Desktop/work/charlieapp/node_modules (3ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by ManvendraSK** [comment]
I have resolved this issue. When we create an app on Windows the file *android/gradlew* will not get an execution permission. To run the same project on the Linux execute a command from your app folder `chmod 755 android/gradlew`. It would fix the issue.
