### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by thoth-nexlesoft** [facebook/react-native#16411]
### This is a bug report
My app has a bug on Google Play:

```
java.lang.IndexOutOfBoundsException: 
  at android.view.ViewGroup.addInArray (ViewGroup.java:4764)
  at android.view.ViewGroup.addViewInner (ViewGroup.java:4681)
  at android.view.ViewGroup.addView (ViewGroup.java:4500)
  at com.facebook.react.views.view.ReactViewGroup.addView (ReactViewGroup.java:389)
  at android.view.ViewGroup.addView (ViewGroup.java:4440)
  at com.facebook.react.views.view.ReactViewManager.addView (ReactViewManager.java:209)
  at com.facebook.react.views.view.ReactViewManager.addView (ReactViewManager.java:41)
  at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren (NativeViewHierarchyManager.java:395)
  at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute (UIViewOperationQueue.java:177)
  at com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:776)
  at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:855)
  at com.facebook.react.uimanager.UIViewOperationQueue.access$1600 (UIViewOperationQueue.java:46)
  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:900)
  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:31)
  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:136)
  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:107)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:957)
  at android.view.Choreographer.doCallbacks (Choreographer.java:734)
  at android.view.Choreographer.doFrame (Choreographer.java:667)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:945)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6776)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
```

### Environment
```OS: macOS Sierra 10.12.6
Node: 8.1.2
Yarn: 0.24.6
npm: 5.3.0
Watchman: 4.7.0
Xcode: Xcode 8.3.3 Build version 8E3004b
Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
react: ^16.0.0-alpha.12 => 16.0.0-alpha.12
react-native: ^0.48.4 => 0.48.4
```

### Steps to Reproduce
I can't reproduce this bug.
Can you help me ?

**Comment by Froelund** [comment]
Any progress on this @thoth-nexlesoft?

**Comment by dluksza** [comment]
Got same similar exception in RN 0.52.0 on Xiaomi Redmi Note 4:

```
Fatal Exception: java.lang.IndexOutOfBoundsException: index=2 count=1
       at android.view.ViewGroup.addInArray(ViewGroup.java:4561)
       at android.view.ViewGroup.addViewInner(ViewGroup.java:4478)
       at android.view.ViewGroup.addView(ViewGroup.java:4297)
       at com.facebook.react.views.view.ReactViewGroup.addView(ReactViewGroup.java:430)
       at android.view.ViewGroup.addView(ViewGroup.java:4237)
       at com.facebook.react.views.view.ReactViewManager.addView(ReactViewManager.java:247)
       at com.facebook.react.views.view.ReactViewManager.addView(ReactViewManager.java:38)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:401)
       at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:180)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:819)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:926)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:47)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:986)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
       at android.view.Choreographer.doCallbacks(Choreographer.java:685)
       at android.view.Choreographer.doFrame(Choreographer.java:618)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6237)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by Fsarmento** [comment]
Can this issue be opened again?

I am also getting the same exception. It happens every time my app renders a SectionList (wrapped in createAnimatedComponent for the record) with **removeClippedSubviews** and **initialNumToRender** > than the **number of items** in the list. 

In my case, after a first install or a login preceded by a logout, the store is empty so the SectionList is rendered a 1st time with an empty array while waiting to get data from firebase. This is when I get this error. 
The index in  "java.lang.IndexOutOfBoundsException: **index=10** count=0" is the value I pass to initialNumToRender (I tried with different values to confirm).

I removed the **removeClippedSubviews** prop from my SectionList and I am not getting this error anymore. However, it would be good to be able to use this prop since my lists can have a few hundreds of items.


## Info
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.4.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0


```

Package: pt.peeq.pais
Version Code: 2
Version Name: 0.2-alpha
Android: 6.0.1
Android Build: MHC19Q
Manufacturer: OnePlus
Model: A0001
Thread: main-1
CrashReporter Key: 7D06CA3E-F236-EBF2-7ADB-D5026C5C3FBEB4DACC7B
Start Date: Tue Feb 20 19:02:55 GMT+00:00 2018
Date: Tue Feb 20 19:03:33 GMT+00:00 2018

java.lang.IndexOutOfBoundsException: index=10 count=0
	at android.view.ViewGroup.addInArray(ViewGroup.java:4410)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:4331)
	at android.view.ViewGroup.addView(ViewGroup.java:4145)
	at com.facebook.react.views.view.ReactViewGroup.addView(ReactViewGroup.java:430)
	at android.view.ViewGroup.addView(ViewGroup.java:4086)
	at com.facebook.react.views.view.ReactViewManager.addView(ReactViewManager.java:247)
	at com.facebook.react.views.view.ReactViewManager.addView(ReactViewManager.java:38)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:401)
	at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:180)
	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:819)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:926)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:47)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:986)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:603)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```
