### ISSUE TITLE
Android  java.lang.IllegalStateException: closed  

### ISSUE THREAD

**Issue by XiaYongjie** [facebook/react-native#16422]
log:
at okio.RealBufferedSource.rangeEquals(RealBufferedSource.java:398)
	at okio.RealBufferedSource.rangeEquals(RealBufferedSource.java:392)
	at okhttp3.internal.Util.bomAwareCharset(Util.java:412)
	at okhttp3.ResponseBody.string(ResponseBody.java:173)
	at com.facebook.react.devsupport.DevServerHelper$7.onResponse(DevServerHelper.java:430)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

phone:
 android 7.1.1 (25)，OnePlus:ONEPLUS A3010:arm64-v8a
React-native version: 0.47.0

**Comment by XiaYongjie** [comment]
@react-native-bot I have look at a same question and get some methon  to solve the problem

**Comment by iamdurui** [comment]
I met the same problem. How did you solve it? thanks @XiaYongjie

**Comment by fencex** [comment]
I solved the problem by modify this java file:
```
node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java
```

**`NOTICE`** In order for these changes to take effect，you need to [Building React Native from source](http://facebook.github.io/react-native/docs/android-building-from-source.html)

here is the code `NetworkingModule.java` 
```
       // 1.  comment those lines comes after     
} else if (data.hasKey(REQUEST_BODY_KEY_FORMDATA)) {
        ......
//      requestBuilder.method(
//        method,
//        RequestBodyUtil.createProgressRequest(
//          multipartBuilder.build(),
//          new ProgressListener() {
//        long last = System.nanoTime();
//
//        @Override
//        public void onProgress(long bytesWritten, long contentLength, boolean done) {
//          long now = System.nanoTime();
//          if (done || shouldDispatch(now, last)) {
//            ResponseUtil.onDataSend(eventEmitter, requestId, bytesWritten, contentLength);
//            last = now;
//          }
//        }
//      }));

      // 2. and add the following 2 lines
      RequestBody requestBody = multipartBuilder.build();
      requestBuilder.post(requestBody).build();

```
