### ISSUE TITLE
Connect React Native with Native UI Component uses JNI library ( .so files )

### ISSUE THREAD

**Issue by dekemega** [facebook/react-native#16424]
I found an amazing library to display panoramic images and it has incredible features but it is written in native java code ... so I tried to make it as an UI component in react native by building the bridge between them .... after a heck lot of time of learning and trying I stuck on this:

The panoramaGL library uses JNI library so when I test it on its own it works just fine, BUT it doesn't work on react native because of the JNI library.

  Environment:
    OS:  Windows 7
    Android Studio:  2.3
    react-native: 0.49.4

**Comment by dekemega** [comment]
i tried to 
extract jni libraries and copy them into into src/main/ of the whole app and it doesn't work

**Comment by dekemega** [comment]
i am getting 

 No implementation found for void com.reactlibrary.opengl.GLUES.gluSphereAndroid(javax.microedition.khronos.opengles.GL10, com.reactlibrary.opengl.GLUquadric, float, int, int, int, int, int, int, boolean) (tried Java_com_reactlibrary_opengl_GLUES_gluSphereAndroid and Java_com_reactlibrary_opengl_GLUES_gluSphereAndroid__Ljavax_microedition_khronos_opengles_GL10_2Lcom_reactlibrary_opengl_GLUquadric_2FIIIIIIZ)
PLRenderableElementBase::render: java.lang.UnsatisfiedLinkError: No implementation found for void com.reactlibrary.opengl.GLUES.gluSphereAndroid(javax.microedition.khronos.opengles.GL10, com.reactlibrary.opengl.GLUquadric, float, int, int, int, int, int, int, boolean) (tried Java_com_reactlibrary_opengl_GLUES_gluSphereAndroid and Java_com_reactlibrary_opengl_GLUES_gluSphereAndroid__Ljavax_microedition_khronos_opengles_GL10_2Lcom_reactlibrary_opengl_GLUquadric_2FIIIIIIZ)
			at com.reactlibrary.opengl.GLUES.gluSphereAndroid(Native Method)
			at com.reactlibrary.opengl.GLUES.gluSphere(GLUES.java:155)
			at com.reactlibrary.PLSphericalPanorama.internalRender(PLSphericalPanorama.java:84)
			at com.reactlibrary.PLRenderableElementBase.render(PLRenderableElementBase.java:163)
			at com.reactlibrary.PLRenderer.renderScene(PLRenderer.java:266)
			at com.reactlibrary.PLRenderer.render(PLRenderer.java:316)
			at com.reactlibrary.PLRenderer.onDrawFrame(PLRenderer.java:476)
			at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
			at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by dekemega** [comment]
the weird thing is when i put this code it doesn't through error 

static {
        Log.e(TAG, "static initializer ");
        try {
            System.loadLibrary("glues");
            Log.e(TAG, "library : Loaded successfully.\n");
        } catch (UnsatisfiedLinkError e) {
            Log.e(TAG, "Native code library failed to load :" + e);
            System.exit(1);
        }
    }

**Comment by dekemega** [comment]
the problem was  ... i've changed the package name while building the bridge between react native and the panoramaGL library so the solution is to change the package name to the old package name of panoramaGL and it works like a charm :)
