### ISSUE TITLE
Cannot find module 'metro-bundler/src/lib/formatBanner'

### ISSUE THREAD

**Issue by alanlong9278** [facebook/react-native#16593]
### Is this a bug report?
yes

### Environment
react-native-cli: 2.0.1
react-native: 0.49.5

`
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "metro-bundler" that matches "^0.13.0"
? Please choose a version from this list: (Use arrow keys)
? Please choose a version from this list: 0.0.0

module.js:491
    throw err;
    ^

Error: Cannot find module 'metro-bundler/src/lib/formatBanner'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/alan/Documents/react/AwesomeProject/node_modules/react-native/local-cli/server/checkNodeVersion.js:12:20)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
`

**Comment by varunprasadyadav** [comment]
I am also having the same exact issue :(

**Comment by max-prosper** [comment]
After initializing the project via Expo I just re-installed node modules with _npm install_ in the terminal and it solved the problem.

**Comment by ratnesh697427** [comment]
I am also having the same exact issue :(
