### ISSUE TITLE
Module AppRegistry is not a registered callable module

### ISSUE THREAD

**Issue by azhon** [facebook/react-native#16659]
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

yes

### Steps to Reproduce

(Write your steps here:)

1.Generate Signed Apk
2.install the app 
3.open the app
4.the app Stop running

5.Supplementary explanation: When I use WebStrom to run the program and install it on the emulator, everything works fine. But when I Generate Signed Apk installed into the emulator, open the app then stop running.

6. the Logcat logs

```
E/ReactNativeJS: undefined is not an object (evaluating 'n.View.propTypes.style')
E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                  Process: com.time, PID: 6081
                  com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'n.View.propTypes.style'), stack:
                  <unknown>@368:2084
                  i@2:565
                  n@2:348
                  t@2:210
                  <unknown>@367:135
                  i@2:565
                  n@2:348
                  t@2:210
                  <unknown>@365:185
                  i@2:565
                  n@2:348
                  t@2:210
                  <unknown>@303:144
                  i@2:565
                  n@2:348
                  t@2:210
                  <unknown>@12:38
                  i@2:565
                  n@2:278
                  t@2:210
                  global code@386:9
                  
                      at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
                      at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
                      at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
                      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                      at android.os.Looper.loop(Looper.java:148)
                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                      at java.lang.Thread.run(Thread.java:818)
E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb40fcb20
E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag)
```
### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by juangl** [comment]
Use `viewPropTypes` instead of `View.propTypes`.

**Comment by azhon** [comment]
My View.js file is the latest version

`View.js`
[View.js.zip](https://github.com/facebook/react-native/files/1442901/View.js.zip)

I think the problem is not here, I hope you can help me solve this problem

**Comment by azhon** [comment]
I found the problem, I used [react-native-easy-toast](https://github.com/crazycodeboy/react-native-easy-toast)  which has a `View.propTypes.style`.

Thank you for your help.

**Comment by ide** [comment]
Closing this as it's been resolved.

If this issue is happening with RN 0.49, check for View.propTypes which no longer exists. Use ViewPropTypes instead. One way to check is `grep -r 'View.propTypes' .`

**Comment by Kielan** [comment]
Very misleading error response, instead of closing probably should discuss how to give more clear error handling responses when deprecating keywords are being used, especially in the case of 3rd party dependencies.
