### ISSUE TITLE
jsc native crash

### ISSUE THREAD

**Issue by supercocoa** [facebook/react-native#16657]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment
OS:  macOS Sierra 10.12.6
    Node:  8.4.0
    Yarn:  0.27.5
    npm:  5.4.0
    Watchman:  4.7.0
    Xcode:  Xcode 8.3.3 Build version 8E3004b
    Android Studio:  2.3 AI-162.4069837

  Packages:
    react-native: 0.42.3
    react:  15.6.x

  Target Platform: Android (5.0+)

### Steps to Reproduce

JSC native crash sometimes:
```
Process Name: 'com.myapp'
Thread Name: 'mqt_js'
pid: 22225  tid: 30074  >>> com.myapp <<<
signal 11 (SIGSEGV)  code 2 (SEGV_ACCERR)  fault addr 76657270
r0 c8bddfc0  r1 76657270  r2 0000000e  r3 00000000
r4 c8bddfd0  r5 cf7dff40  r6 c83ee164  r7 c8bddfc0
r8 00000000  r9 ca600868  10 00000004  fp 00000012
ip c835b609  sp ca6006d4  lr c8322a31  pc c8397962  cpsr 800b0030
#00  pc 0017c962  /data/data/com.myapp/lib/libjsc.so (_ZN3WTF5equalEPKNS_10StringImplEPKh)
#01  pc 00107a2c  /data/data/com.myapp/lib/libjsc.so
#02  pc 0014061e  /data/data/com.myapp/lib/libjsc.so
#03  pc 000b12bc  /data/data/com.myapp/lib/libjsc.so
--- --- ---
00 pc 0017c962  /data/data/com.myapp/lib/libjsc.so (_ZN3WTF5equalEPKNS_10StringImplEPKh+27)
01 pc 00107a2d  /data/data/com.myapp/lib/libjsc.so
02 pc 0014061f  /data/data/com.myapp/lib/libjsc.so
03 pc 000b12bd  /data/data/com.myapp/lib/libjsc.so
04 pc 000b4b6b  /data/data/com.myapp/lib/libjsc.so
```
```
"mqt_js" prio=10 tid=78 Native
| group="" sCount=0 dsCount=0 obj=0x13a5a3a0 self=0xad7958c0
| sysTid=30074 nice=-8 cgrp=default sched=0/0 handle=0xca601930
| state=? schedstat=( 0 0 0 ) utm=0 stm=0 core=0 HZ=100
| stack=0xca4ff000-0xca501000 stackSize=1038KB
| held mutexes=
at com.facebook.react.bridge.queue.NativeRunnable.run(Native method)
at android.os.Handler.handleCallback(Handler.java:743)
at android.os.Handler.dispatchMessage(Handler.java:95)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
at android.os.Looper.loop(Looper.java:150)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
at java.lang.Thread.run(Thread.java:833)
```

**Comment by cdlewis** [comment]
Can you provide an example project that replicates this crash?

**Comment by supercocoa** [comment]
@cdlewis  It's in our production app, still not find how to replicates this crash.

**Comment by lomanyong** [comment]
@cdlewis @supercocoa  Our application has the same crash log and still not found a way to reproduce this case.
