### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method newWebSocket

### ISSUE THREAD

**Issue by wwf7758258** [facebook/react-native#16926]
FATAL EXCEPTION: AsyncTask #2
                                                                     Process: com.heniaokeji.geji, PID: 11493
                                                                     java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                         at android.os.AsyncTask$3.done(AsyncTask.java:318)
                                                                         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                         at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                         at java.lang.Thread.run(Thread.java:761)
                                                                      Caused by: java.lang.NoSuchMethodError: No virtual method newWebSocket(Lokhttp3/Request;Lokhttp3/WebSocketListener;)Lokhttp3/WebSocket; in class Lokhttp3/OkHttpClient; or its super classes (declaration of 'okhttp3.OkHttpClient' appears in /data/app/com.heniaokeji.geji-1/base.apk:classes3.dex)
                                                                         at com.facebook.react.devsupport.InspectorPackagerConnection$Connection.connect(InspectorPackagerConnection.java:239)
                                                                         at com.facebook.react.devsupport.InspectorPackagerConnection.connect(InspectorPackagerConnection.java:44)
                                                                         at com.facebook.react.devsupport.DevServerHelper$3.doInBackground(DevServerHelper.java:198)
                                                                         at com.facebook.react.devsupport.DevServerHelper$3.doInBackground(DevServerHelper.java:194)
                                                                         at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                         at java.lang.Thread.run(Thread.java:761) 

- 

- [ ] 1. 

Additional Information

React Native version: 0.49.0

    "react": "16.0.0-beta.5",
    "react-native": "0.49.0",
    "react-navigation": "^1.0.0-beta.19",
    "teaset": "^0.4.8"

Platform: Android
Development Operating System:
Dev tools: Android Studio 3.0

This problem is very urgent!!!
what should I do?
Thank you for the first!!!

**Comment by wwf7758258** [comment]
configurations.all {
        resolutionStrategy.force 'com.google.code.findbugs:jsr305:1.3.9'
//        resolutionStrategy.force 'com.squareup.okhttp3:okhttp:3.5.0'
//        exclude module: 'okhttp-ws'
        resolutionStrategy.force 'com.squareup.okhttp3:okhttp:3.8.0'
        resolutionStrategy.force 'com.squareup.okhttp3:logging-interceptor:3.8.0'
        resolutionStrategy.force 'com.squareup.okio:okio:1.7.0'
    }

I made mandatory  resolutionStrategy, but there is no effect.
