### ISSUE TITLE
RN 0.50.3 android release run crash help me!

### ISSUE THREAD

**Issue by PeterLocas** [facebook/react-native#16942]
11-23 01:36:45.296 23624-23714/com.shiyueapp W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe3c072a0, error=EGL_SUCCESS
11-23 01:36:45.507 23624-23634/com.shiyueapp W/art: Suspending all threads took: 19.192ms
11-23 01:36:45.883 684-743/system_process D/WifiService: New client listening to asynchronous messages
11-23 01:36:46.075 684-710/system_process I/ActivityManager: Displayed com.shiyueapp/.MainActivity: +7s576ms (total +3m3s618ms)
11-23 01:36:46.630 23624-23721/com.shiyueapp E/ReactNativeJS: undefined is not an object (evaluating 'l.View.propTypes.style')
11-23 01:36:46.666 23624-23722/com.shiyueapp I/WebViewFactory: Loading com.android.webview version 37 (eng.genymotion-x86) (code 199997)
11-23 01:36:46.673 23624-23721/com.shiyueapp I/ReactNativeJS: Running application "shiyueapp" with appParams: {"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
11-23 01:36:46.676 23624-23721/com.shiyueapp E/ReactNativeJS: Application shiyueapp has not been registered.
                                                              
                                                              Hint: This error often happens when you're running the packager (local dev server) from a wrong folder. For example you have multiple apps and the packager is still running for the app you were working on before.
                                                              If this is the case, simply kill the old packager instance (e.g. close the packager terminal window) and start the packager in the correct app folder (e.g. cd into app folder and run 'npm start').
                                                              
                                                              This error can also happen due to a require() error during initialization or failure to call AppRegistry.registerComponent.
11-23 01:36:46.676 23624-23722/com.shiyueapp I/LibraryLoader: Loading: webviewchromium
11-23 01:36:46.679 23624-23722/com.shiyueapp I/LibraryLoader: Time to load native libraries: 3 ms (timestamps 1011-1014)
11-23 01:36:46.679 23624-23722/com.shiyueapp I/LibraryLoader: Expected native library version number "",actual native library version number ""
11-23 01:36:46.681 23624-23722/com.shiyueapp W/art: Attempt to remove local handle scope entry from IRT, ignoring
11-23 01:36:46.743 23624-23722/com.shiyueapp E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                               Process: com.shiyueapp, PID: 23624
                                                               com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'l.View.propTypes.style'), stack:
                                                               <unknown>@515:1138
                                                               t@2:633
                                                               <unknown>@2:224
                                                               e@2:231
                                                               <unknown>@512:214
                                                               t@2:633
                                                               <unknown>@2:224
                                                               e@2:231
                                                               <unknown>@299:381
                                                               t@2:633
                                                               <unknown>@2:224
                                                               e@2:231
                                                               <unknown>@12:99
                                                               t@2:633
                                                               <unknown>@2:154
                                                               e@2:231
                                                               global code@1007:9
                                                               
                                                                   at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
                                                                   at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
                                                                   at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
                                                                   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                                   at java.lang.Thread.run(Thread.java:818)
11-23 01:36:46.745 684-1046/system_process W/ActivityManager:   Force finishing activity com.shiyueapp/.MainActivity
11-23 01:36:46.771 423-423/? E/EGL_emulation: tid 423: eglCreateSyncKHR(1181): error 0x3004 (EGL_BAD_ATTRIBUTE)
11-23 01:36:46.899 684-684/system_process W/art: Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12038 waiters=0 for 151ms
11-23 01:36:47.010 23624-23634/com.shiyueapp W/art: Suspending all threads took: 19.323ms

**Comment by PeterLocas** [comment]
![image](https://user-images.githubusercontent.com/5467858/33163283-70a37e3e-cff3-11e7-915d-ddf4a901701e.png)

**Comment by flyskywhy** [comment]
@PeterLocas , as said in [verifyPropTypes.js](https://github.com/facebook/react-native/blob/master/Libraries/ReactNative/verifyPropTypes.js) , ReactNative `View.propTypes` have been deprecated in favor of `ViewPropTypes`, in my own app, debug is good, release will crash, then I search all include node_modules, replace View.propTypes to ViewPropTypes, now release is also good.
