### ISSUE TITLE
FlatList does not render properly

### ISSUE THREAD

**Issue by DragWeb** [facebook/react-native#16983]
### FlatList does not render properly on Android devices

```javascript
Unable to update properties for view tag 1255
                                                                         com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 1255 could not be found
                                                                             at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:106)
                                                                             at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:123)
                                                                             at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:248)
                                                                             at com.facebook.react.animated.PropsAnimatedNode.updateView(PropsAnimatedNode.java:69)
                                                                             at com.facebook.react.animated.NativeAnimatedNodesManager.updateNodes(NativeAnimatedNodesManager.java:516)
                                                                             at com.facebook.react.animated.NativeAnimatedNodesManager.runUpdates(NativeAnimatedNodesManager.java:427)
                                                                             at com.facebook.react.animated.NativeAnimatedModule$1.doFrameGuarded(NativeAnimatedModule.java:117)
                                                                             at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
                                                                             at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
                                                                             at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:549)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5264)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
```

### Environment

    OS:  macOS Sierra 10.12.6
    Node:  7.10.1
    npm: 4.2.0
    android: 5.0

  Packages: (wanted => installed)
    react-native: 0.49.3
    react: 16.0.0-beta.5

**Comment by sun2rise** [comment]
@DragWeb I am facing a similar issue... have you found any solution?

**Comment by DragWeb** [comment]
@sun2rise I change the code,is solution,but I'm not found the what's wrong.
that's my code
```javascript

import React, { Component } from 'react';
import {
  StyleSheet,
  Text,
  View,
  FlatList,
  Image,
  Button,
  Platform,
  DeviceEventEmitter,
  Animated
} from 'react-native';

import { addNavigationHelpers, NavigationActions } from "react-navigation";
import { px2dp, API, isIphoneX } from '../utils'
import ArticleHead from '../components/articleHead'
import ArticlePreview from '../components/articlePreview'

let forumData;

class AnimateView extends Component {
  constructor(props) {
    super(props);
    this.state = {
      delay: this.props.delay,
      fadeAnim: new Animated.Value(0),          // 透明度初始值设为0
    };
  }
  componentDidMount() {
    Animated.timing(                            // 随时间变化而执行的动画类型
      this.state.fadeAnim,                      // 动画中的变量值
      {
        toValue: 1,                             // 透明度最终变为1，即完全不透明
        delay: this.state.delay,
      }
    ).start();                                  // 开始执行动画
  }
  render() {
    return (
      <Animated.View                            // 可动画化的视图组件
        style={[this.props.style,{
          opacity: this.state.fadeAnim,          // 将透明度指定为动画变量值
        }]}
      >
        {this.props.children}
      </Animated.View>
    );
  }
}

export default class List extends Component {

  constructor(props){
    super(props);
    this.state = {
      dataSource: [],
      isRefreshing: false,
      pageCount: '',
      page: 1,
      pageSize: 15,
      onEndReachedCalledDuringMomentum: true,
      footText: '正在加载....',
      loadingText: '',
      member_uid: ''
    };

  }

  static navigationOptions = ({ navigation }) => {
    const { params = {} } = navigation.state;
    let config = {
      title: `${navigation.state.params.data.name}`,
      headerStyle: {
        backgroundColor: '#141D26',
        paddingTop: Platform.OS !== 'ios' ? 24 : isIphoneX() ? 44 : 20,
        height: Platform.OS !== 'ios' ? 64 : isIphoneX() ? 88 : 64,
      },
      headerTitleStyle: { color: '#fff' },
      headerBackTitleStyle: { color: '#fff' },
      tintColor: { color: 'white' },
      gesturesEnabled: true,
      headerTintColor: 'white'
    };
    forumData = navigation.state.params.data;
    if(navigation.state.params.data.id) {
      config.headerRight = <Button
        title='发帖'
        color={Platform.OS === 'android' ? '' : "#fff"}
        onPress={() => params.navigatePost(navigation)}
      />
    }
    return config;
  };

  componentWillMount() {
    let self = this;
    // this.setState({ page: 1 });
    this.getData();
    this.props.navigation.setParams({ navigatePost: this.navigatePost.bind(this) });
  }

  componentDidMount(){
    let self = this;
    this.subscription = DeviceEventEmitter.addListener('refreshList', function(){
      self.getData();
    });
  };

  componentWillUnmount() {
    forumData = '';
    this.subscription.remove();
  }

  navigatePost(navigation) {
    navigation.navigate('PostStack', {data: {title: '发贴', fid: navigation.state.params.data.id, isSetName: this.state.isSetName, member_uid: this.state.member_uid}})
  }

  async getData() {
    let list;
    let key = forumData ? forumData.name : '';
    let params = {
      page: this.state.page,
      pageSize: this.state.pageSize
    }

    this.setState({isRefreshing: true});

    switch (key) {
      case '精华贴':
        list = await API.essencePostsList(params);
        break;
      case '同城会':
        list = await API.cityForumList({fid: forumData.id});
        break;
      case '配件专区':
        list = await API.essencePostsList(params);
        break;
      case 'N1/N1s':
        list = await API.n1PostsList(params);
        break;
      case 'M1':
        list = await API.m1PostsList(params);
        break;
      case 'U1':
        list = await API.u1PostsList(params);
        break;
      default :
        this.setState({footText: ''})
        list = await API.hotPostsList(params);
    }

    this.setState({
      member_uid: list.variables.member_uid,
      dataSource: this.state.page == 1 ? list.variables.forum_threadlist : this.state.dataSource.concat(list.variables.forum_threadlist),
      isRefreshing: false,
      isSetName: list.variables.member_uid == '0' ? true : false,
      pageCount: parseInt(list.variables.page_count),
    });
    if(list.variables.forum_threadlist.length == '') {
      this.setState({loadingText: '没有内容，赶紧发个帖子吧'})
    }

  }

  renderAllData() {
    let allData = [];
    let dataSource = this.state.dataSource;

    dataSource = dataSource.map((item, index) => {
      let head = {
        avatar: item.author_avatar,
        author: item.author,
        group: item.group,
        author_v: item.author_v,
        signature: item.author_signhtml,
        lastpost: item.lastpost
      };

      item.head = head;
      item.key = index;

      return item;

    });

    return dataSource
  }

  _onRefresh() {
    this.setState({page: 1, dataSource: []}, () => {
      this.getData();
    })
  }

  _nextPage() {
    if (!this.state.onEndReachedCalledDuringMomentum) {
      let _page = this.state.page;
      if(this.state.pageCount && (this.state.pageCount > _page)) {
        this.setState({ onEndReachedCalledDuringMomentum: true, page: _page + 1 }, () => {
          this.getData();
        });
      } else {
        this.setState({footText: '没有了'})
      }
    }
  }

  _footer = () => {
    if(this.state.dataSource.length != 0) {
      return (<View style={{
                height: 44,
                justifyContent: 'center',
                alignItems: 'center',
              }}>
                <Text style={{color: '#454553'}}>{this.state.footText}</Text>
              </View>)
    }
    return null
  }

  render() {
    let navigation = this.props.navigation;

    let allData = this.renderAllData();

    if(allData.length == 0) {
      return (<View><Text style={{textAlign: 'center', paddingVertical: 10}}>{this.state.loadingText}</Text></View>);
    }

    return (
      <FlatList
        data={allData}
        onRefresh={() => this._onRefresh()}
        refreshing={this.state.isRefreshing}
        onEndReachedThreshold={0.2}
        initialNumToRender={3}
        onEndReached={() => this._nextPage()}
        ListFooterComponent={this._footer}
        onMomentumScrollBegin={() => { this.setState({onEndReachedCalledDuringMomentum: false}) }}
        extraData={this.state}
        removeClippedSubviews={false}
        renderItem={({item}) => <AnimateView delay={100} style={styles.item} key={item.key} >
          <ArticleHead data={item.head} />
          <ArticlePreview data={item} navigation={this.props.navigation} />
        </AnimateView>}
      />
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center'
  },
  item: {
    flex: 1,
    backgroundColor: '#fff',
    marginBottom: px2dp(15),
    padding: px2dp(20)
  }
});

```
