### ISSUE TITLE
App crashes when running in release mode

### ISSUE THREAD

**Issue by adrianboimvaser** [facebook/react-native#17018]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: Windows 10
  Node: 6.10.3
  Yarn: 0.24.6
  npm: 5.5.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.3.0.0 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

### Steps to Reproduce

1. RUN react-native run-android --variant=release

### Expected Behavior

The app should run like when running in debug mode.

### Actual Behavior

The app crashes continuouly

![image](https://user-images.githubusercontent.com/1104728/33399296-df10a9b8-d530-11e7-9995-3818c7490fbd.png)

**Comment by adrianboimvaser** [comment]
From adb logcat:
```
4  8655 E ReactNativeJS: undefined is not an object (evaluating 'u.View.propTypes.style')
11-29 17:34:52.511  8624  8655 E ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
11-29 17:34:52.515  8624  8656 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
11-29 17:34:52.515  8624  8656 E AndroidRuntime: Process: com.skybox, PID: 8624
11-29 17:34:52.515  8624  8656 E AndroidRuntime: com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'u.View.propTypes.style'), stack:
11-29 17:34:52.515  8624  8656 E AndroidRuntime: <unknown>@691:643
11-29 17:34:52.515  8624  8656 E AndroidRuntime: t@2:633
11-29 17:34:52.515  8624  8656 E AndroidRuntime: <unknown>@2:224
11-29 17:34:52.515  8624  8656 E AndroidRuntime: e@2:231
11-29 17:34:52.515  8624  8656 E AndroidRuntime: <unknown>@690:172
11-29 17:34:52.515  8624  8656 E AndroidRuntime: t@2:633
11-29 17:34:52.515  8624  8656 E AndroidRuntime: <unknown>@2:224
11-29 17:34:52.515  8624  8656 E AndroidRuntime: e@2:231
11-29 17:34:52.515  8624  8656 E AndroidRuntime: <unknown>@689:157
11-29 17:34:52.515  8624  8656 E AndroidRuntime: t@2:633
11-29 17:34:52.515  8624  8656 E AndroidRuntime: <unknown>@2:224
11-29 17:34:52.515  8624  8656 E AndroidRuntime: e@2:231
11-29 17:34:52.515  8624  8656 E AndroidRuntime: <unknown>@641:206
11-29 17:34:52.515  8624  8656 E AndroidRuntime: t@2:633
11-29 17:34:52.515  8624  8656 E AndroidRuntime: <unknown>@2:224
11-29 17:34:52.515  8624  8656 E AndroidRuntime: e@2:231
11-29 17:34:52.515  8624  8656 E AndroidRuntime: <unknown>@636:264
11-29 17:34:52.515  8624  8656 E AndroidRuntime: t@2:633
11-29 17:34:52.515  8624  8656 E AndroidRuntime: <unknown>@2:224
11-29 17:34:52.515  8624  8656 E AndroidRuntime: e@2:231
11-29 17:34:52.515  8624  8656 E AndroidRuntime: <unknown>@635:149
11-29 17:34:52.515  8624  8656 E AndroidRuntime: t@2:633
11-29 17:34:52.515  8624  8656 E AndroidRuntime: <unknown>@2:224
11-29 17:34:52.515  8624  8656 E AndroidRuntime: e@2:231
11-29 17:34:52.515  8624  8656 E AndroidRuntime: <unknown>@634:171
11-29 17:34:52.515  8624  8656 E AndroidRuntime: t@2:633
11-29 17:34:52.515  8624  8656 E AndroidRuntime: <unknown>@2:224
11-29 17:34:52.515  8624  8656 E AndroidRuntime: e@2:231
11-29 17:34:52.515  8624  8656 E AndroidRuntime: <unknown>@571:101
11-29 17:34:52.515  8624  8656 E AndroidRuntime: t@2:633
11-29 17:34:52.515  8624  8656 E AndroidRuntime: <unknown>@2:224
11-29 17:34:52.515  8624  8656 E AndroidRuntime: e@2:231
11-29 17:34:52.515  8624  8656 E AndroidRuntime: <unknown>@341:110
11-29 17:34:52.515  8624  8656 E AndroidRuntime: t@2:633
11-29 17:34:52.515  8624  8656 E AndroidRuntime: <unknown>@2:224
11-29 17:34:52.515  8624  8656 E AndroidRuntime: e@2:231
11-29 17:34:52.515  8624  8656 E AndroidRuntime: <unknown>@12:231
11-29 17:34:52.515  8624  8656 E AndroidRuntime: t@2:633
11-29 17:34:52.515  8624  8656 E AndroidRuntime: <unknown>@2:154
11-29 17:34:52.515  8624  8656 E AndroidRuntime: e@2:231
11-29 17:34:52.515  8624  8656 E AndroidRuntime: global code@978:9
11-29 17:34:52.515  8624  8656 E AndroidRuntime: 
11-29 17:34:52.515  8624  8656 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
11-29 17:34:52.515  8624  8656 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
11-29 17:34:52.515  8624  8656 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-29 17:34:52.515  8624  8656 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
11-29 17:34:52.515  8624  8656 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
11-29 17:34:52.515  8624  8656 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
11-29 17:34:52.515  8624  8656 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
11-29 17:34:52.515  8624  8656 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-29 17:34:52.515  8624  8656 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
11-29 17:34:52.515  8624  8656 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-29 17:34:52.515  8624  8656 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
11-29 17:34:52.515  8624  8656 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
```

**Comment by Guodadada** [comment]
replace "u.View.propTypes.style" with "ViewPropTypes.style", import {ViewPropTypes} from 'react-native'

**Comment by santhosh77h** [comment]
this issue may help [https://github.com/facebook/react-native/issues/created_by/santhosh77h](issue)

**Comment by adrianboimvaser** [comment]
I figured out the offending dependency was https://github.com/obipawan/react-native-dash. Thanks a lot for the help.
