### ISSUE TITLE
Android - App crashes with ReactRootView inside viewpager

### ISSUE THREAD

**Issue by tdekoning** [facebook/react-native#17123]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Steps to Reproduce

(Write your steps here:)

1. Create a native `ViewPager` with a `ReactRootView` as content, preferably with some images inside the `ReactRootView`
2. Swipe fast
3. See this stack trace

### Expected Behavior

I would expect no stack trace or errors to occur.

### Actual Behavior

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.uimanager.ReactShadowNode.addChildAt(com.facebook.react.uimanager.ReactShadowNode, int)' on a null object reference
       at com.facebook.react.uimanager.UIImplementation.setChildren(UIImplementation.java:472)
       at com.facebook.react.uimanager.UIManagerModule.setChildren(UIManagerModule.java:436)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:158)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:818)
```

This occurs after swiping through the ViewPager quickly.

### Reproducible Demo

Proposed fix:
Below [this line of code](https://github.com/facebook/react-native/blob/d19afc73f5048f81656d0b4424232ce6d69a6368/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIImplementation.java#L474): Add the same fix as [this one](https://github.com/facebook/react-native/blob/d19afc73f5048f81656d0b4424232ce6d69a6368/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIImplementation.java#L152)

**Comment by ssuchanowski** [comment]
Do you have anywhere demo you used to reproduce this?

I get this exception on prod and the change you are proposing looks reasonable but I cannot reproduce it.

**Comment by Frank1234** [comment]
Here is a very simple demo project that reproduces this bug: https://github.com/facebook/react-native/issues/19233 . Sadly, it reproduces not only this bug but many other bugs as well, in a random manner.

**Comment by SudoPlz** [comment]
So what is happening is, react-native is trying to manipulate a view (with `setChildren`) but that view is not found within the node array.

This is an issue I've been facing for a long time but have NO idea how to resolve.
The fix proposed does not fix the issue, it just outputs a better error log, but the issue remains..

**Comment by Frank1234** [comment]
All hail SudoPlz! https://gist.github.com/SudoPlz/23ea2dee9772cb39e1e742034cdf8b98

**Comment by patrickkempff** [comment]
#20025 should fix this
