### ISSUE TITLE
npm install -g react-native-cli npm ERR! code E503 npm ERR! 503 Maximum threads for service reached: react-native-cli@latest

### ISSUE THREAD

**Issue by dancomanlive** [facebook/react-native#17253]
When installing react-native on a new Macbook Pro

**Comment by dancomanlive** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.3.0_1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'react-native-cli' ]
2 info using npm@5.6.0
3 info using node@v9.3.0
4 verbose npm-session a2bc480c1215c0a6
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 503 https://registry.npmjs.org/react-native-cli 74075ms attempt #3
8 silly fetchPackageMetaData error for react-native-cli@latest 503 Maximum threads for service reached: react-native-cli@latest
9 verbose stack Error: 503 Maximum threads for service reached: react-native-cli@latest
9 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
9 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
9 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
9 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
9 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
9 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
9 verbose stack     at runCallback (timers.js:773:18)
9 verbose stack     at tryOnImmediate (timers.js:734:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:711:5)
10 verbose cwd /Users/dancoman
11 verbose Darwin 17.3.0
12 verbose argv "/usr/local/Cellar/node/9.3.0_1/bin/node" "/usr/local/bin/npm" "install" "-g" "react-native-cli"
13 verbose node v9.3.0
14 verbose npm  v5.6.0
15 error code E503
16 error 503 Maximum threads for service reached: react-native-cli@latest
17 verbose exit [ 1, true ]
