### ISSUE TITLE
ScrollViewMock does not define scrollTo

### ISSUE THREAD

**Issue by n-kumari** [facebook/react-native#17261]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.0 Build version 9A235
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

### Steps to Reproduce

1. Make a component with a ScrollView.
2. Create a ref for the ScrollView.
2. Call scrollTo on the ref.
3. Run a test that renders the component and triggers scrollTo

### Expected Behavior

1. The tests will pass
### Actual Behavior

1. The tests fail with the error
``` 
   TypeError: scrollView.scrollTo is not a function

      28 |
      29 |   setRef = (scrollView) => {
    > 30 |     scrollView.scrollTo({y: 100, animated: false});
      31 |   }
      32 |
      33 |   render() {

      at App._this.setRef (App.js:30:12)
      at commitAttachRef (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5535:11)
      at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6257:9)
      at Object.invokeGuardedCallback$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2159:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2106:29)
      at commitAllWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6371:9)
      at workLoop (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6643:13)
      at Object.invokeGuardedCallback$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2159:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2106:29)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6756:7)

  console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2053
    The above error occurred in the <ScrollViewMock> component:
        in ScrollViewMock (created by App)
        in App

    Consider adding an error boundary to your tree to customize error handling behavior.
    You can learn more about error boundaries at https://fb.me/react-error-boundaries. 
```

### Reproducible Demo

1. Clone the [repo](https://github.com/n-kumari/scrollViewIssue)
2. In package.json, remove `--setupTestFrameworkScriptFile=./setJestTest.js` from the test script
3. Run `npm run  test` from the project directory.

[Example project](https://github.com/n-kumari/scrollViewIssue)

**Comment by n-kumari** [comment]
It appears that Facebook is providing a jest mock for the [ScrollView](https://github.com/facebook/react-native/blob/11a2a35c63ae68de46482f5cd25271f8b0fb5ad4/Libraries/Components/ScrollView/__mocks__/ScrollViewMock.js) and [hooking it up](https://github.com/facebook/react-native/blob/11a2a35c63ae68de46482f5cd25271f8b0fb5ad4/jest/setup.js). However, when we copy the exact same mock into our project and register it with jest the error no longer appears and the test passes.
