### ISSUE TITLE
Duplicate declaration "AnimatedComponent" Probably an internal error

### ISSUE THREAD

**Issue by Dineshchitta** [facebook/react-native#17382]
### Is this a bug report?

"Yes"

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

No

### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.0
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Not Found
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

  Target Platform: iOS (8)

### Steps to Reproduce

(Write your steps here:)

1) Just upgraded react-native to 51.0 
2) Added babel plugin babel-plugin-transform-flow-strip-types@6.22.0 Since I was getting a flow error in findSymlinkModules.js 

### Expected Behavior

Bundling should be done without any errors and Hot module reloading should work

### Actual Behavior

1. Could not able to run development server throwing error 
```
bundling failed: TypeError: /node_modules/react-native/Libraries/Animated/src/createAnimatedComponent.js: Duplicate declaration "AnimatedComponent" (This is an error on an internal node. Probably an internal error)
    at File.buildCodeFrameError (/node_modules/babel-core/lib/transformation/file/index.js:427:15)
    at Scope.checkBlockScopedCollisions (/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:398:27)
    at Scope.registerBinding (/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:592:16)
    at Scope.registerDeclaration (node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:496:14)
    at Object.BlockScoped (node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:244:28)
    at Object.newFn (node_modules/babel-core/node_modules/babel-traverse/lib/visitors.js:318:17)
    at NodePath._call (node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:44:14)
    at NodePath.visit (/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:105:12)
```
Previous Experience
-------------------------
When I was working react-native 48.4 when I enable Hot module reloading(hmr) I used to get this error .After updating to 51.0 I could not able to development server because of bundling error

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

I dont think it is a issue caused by react-native. I am thinking it is because of my configuration(babel probably).

**Comment by PavanGangireddy** [comment]
Even after I upgraded to 0.54.0 I am getting this issue

**Comment by Dineshchitta** [comment]
I am facing issue in the latest version(0.54.0) also

**Comment by iiitmanikanta** [comment]
probably issue is with **transform-react-remove-prop-types** babel plugin,,,,

Try removing this plugin from .babelrc , it will solves the problem
