### ISSUE TITLE
app crash on call PermissionsAndroid.request when another native permission request is prompted

### ISSUE THREAD

**Issue by icfr** [facebook/react-native#17402]
### Is this a bug report?
yes

### Environment
Environment:
  OS: Linux 4.4
  Node: 8.8.1
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: N/A
  Android Studio: 2.2 AI-145.3360264

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3

### Steps to Reproduce

call PermissionsAndroid.request when another native permission request is prompted

### Expected Behavior
prompt user for permission

### Actual Behavior
app crash with 

```
 java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference
12-31 08:16:44.451 10003 10003 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3132)
12-31 08:16:44.451 10003 10003 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3163)
12-31 08:16:44.451 10003 10003 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1413)
12-31 08:16:44.451 10003 10003 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-31 08:16:44.451 10003 10003 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:150)
12-31 08:16:44.451 10003 10003 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5546)
12-31 08:16:44.451 10003 10003 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-31 08:16:44.451 10003 10003 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
12-31 08:16:44.451 10003 10003 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)
12-31 08:16:44.451 10003 10003 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference
12-31 08:16:44.451 10003 10003 E AndroidRuntime: 	at com.facebook.react.modules.permissions.PermissionsModule.onRequestPermissionsResult(PermissionsModule.java:207)
12-31 08:16:44.451 10003 10003 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate$1.invoke(ReactActivityDelegate.java:211)
12-31 08:16:44.451 10003 10003 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onResume(ReactActivityDelegate.java:131)
12-31 08:16:44.451 10003 10003 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onResume(ReactActivity.java:66)
12-31 08:16:44.451 10003 10003 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1266)
12-31 08:16:44.451 10003 10003 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6446)
12-31 08:16:44.451 10003 10003 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3122)

```

**Comment by sibelius** [comment]
this still a problem in RN53 as well

**Comment by gao520sun** [comment]
this still a problem in RN0.55.0 as well
