### ISSUE TITLE
npm start or npm install not working

### ISSUE THREAD

**Issue by RakeshKW** [facebook/react-native#17612]
following is the error:

E:\React Native\quizgame>npm start

quizgame@0.1.0 start E:\React Native\quizgame
react-native-scripts start

10:04:22 PM: Starting packager...
10:04:34 PM: Error starting packager: TypeError: Invalid Version: undefined
at new SemVer (E:\React Native\quizgame\node_modules\semver\semver.js:279:11)
at Function.major (E:\React Native\quizgame\node_modules\semver\semver.js:551:10)
at E:\xdl\src\project\Doctor.js:555:18
at E:\React Native\quizgame\node_modules\lodash\lodash.js:4944:15
at baseForOwn (E:\React Native\quizgame\node_modules\lodash\lodash.js:3001:24)
at E:\React Native\quizgame\node_modules\lodash\lodash.js:4913:18
at Function.forEach (E:\React Native\quizgame\node_modules\lodash\lodash.js:9359:14)
at E:\xdl\src\project\Doctor.js:548:9
at throw (native)
at step (E:\React Native\quizgame\node_modules\xdl\build\project\Doctor.js:609:191)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! quizgame@0.1.0 start: react-native-scripts start
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the quizgame@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\rakes\AppData\Roaming\npm-cache_logs\2018-01-15T16_34_34_630Z-debug.log

**Comment by RakeshKW** [comment]
Please check my debug log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\rakes\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v6.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle quizgame@0.1.0~prestart: quizgame@0.1.0
6 info lifecycle quizgame@0.1.0~start: quizgame@0.1.0
7 verbose lifecycle quizgame@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle quizgame@0.1.0~start: PATH: C:\Users\rakes\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\React Native\quizgame\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;c:\Program Files (x86)\AMD APP\bin\x86_64;c:\Program Files (x86)\AMD APP\bin\x86;c:\Program Files (x86)\Intel\iCLS Client\;c:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Gradle\gradle-4.0\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\xampp\php;C:\composer;C:\Program Files (x86)\Yarn\bin;C:\Users\rakes\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\rakes\AppData\Roaming\npm;C:\Users\rakes\AppData\Roaming\Composer\vendor\bin;C:\Program Files\Java\jdk1.8.0_131\bin;C:\Users\rakes\AppData\Local\Yarn\bin;C:\Users\rakes\AppData\Local\Android\android-sdk\platform-tools;
9 verbose lifecycle quizgame@0.1.0~start: CWD: E:\React Native\quizgame
10 silly lifecycle quizgame@0.1.0~start: Args: [ '/d /s /c', 'react-native-scripts start' ]
11 silly lifecycle quizgame@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle quizgame@0.1.0~start: Failed to exec start script
13 verbose stack Error: quizgame@0.1.0 start: `react-native-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\rakes\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\rakes\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:891:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid quizgame@0.1.0
15 verbose cwd E:\React Native\quizgame
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rakes\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v6.11.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error quizgame@0.1.0 start: `react-native-scripts start`
22 error Exit status 1
23 error Failed at the quizgame@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
