### ISSUE TITLE
React Native is not building since metro 0.24.5 has been released

### ISSUE THREAD

**Issue by SMJ93** [facebook/react-native#17675]
Since version `0.24.5` has been released we have been unable to run our react-native project on iOS and Android:

```
 BUNDLE  [android, dev] ./index.android.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

error: bundling failed: Error: invalid value for dynamic deps behavior: `null`
    at getDynamicDepsBehavior (/Users/user/Documents/app/applications/apps/product-mobile/node_modules/metro/src/JSTransformer/worker/index.js:185:13)
    at postTransform (/Users/user/Documents/app/applications/apps/product-mobile/node_modules/metro/src/JSTransformer/worker/index.js:131:26)
    at Object.transformCode [as transform] (/Users/user/Documents/app/applications/apps/product-mobile/node_modules/metro/src/JSTransformer/worker/index.js:251:17)
    at execMethod (/Users/user/Documents/app/applications/apps/product-mobile/node_modules/jest-worker/build/child.js:92:29)
    at process.on (/Users/user/Documents/app/applications/apps/product-mobile/node_modules/jest-worker/build/child.js:42:7)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at process.nextTick (internal/child_process.js:755:12)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
```

We reverted back to `0.24.4` and the app bundled as expected. 

Environment:

-  "react-native": "0.52.0"
-  "react": "16.2.0"

Let me know if you need any more details.

**Comment by SMJ93** [comment]
https://github.com/facebook/metro/issues/126
