### ISSUE TITLE
Android release build can't find renamed entry file

### ISSUE THREAD

**Issue by kdong007** [facebook/react-native#17729]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.3
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: Not Found
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.51.0 => 0.51.0
### Steps to Reproduce

(Write your steps here:)

1. rename index.android.js to index.js
2. in MainApplication.java add/modify these:
 ```
        @Override
        protected String getJSMainModuleName(){
            return "index";
        }

        @Override
        protected String getJSBundleFile() {
            return "index.bundle";
        }
```

3. app.bundle add these lines at top

```
project.ext.react = [
        // the name of the generated asset file containing your JS bundle
        bundleAssetName: "index.bundle",

        // the entry file for bundle generation
        entryFile      : "index.js",
]
```

### Expected Behavior

app loads properly

### Actual Behavior

app works in debug build, but in release build, app crash with these logs
```
01-25 00:18:31.518 3016-3034/? E/AndroidRuntime: FATAL EXCEPTION: Thread-5612
                                                 Process: com.hetao.rental, PID: 3016
                                                 com.facebook.jni.CppException: facebook::react::Recoverable: Could not open fileindex.bundle: No such file or directory
                                                     at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromFile(Native Method)
                                                     at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromFile(CatalystInstanceImpl.java:220)
                                                     at com.facebook.react.bridge.JSBundleLoader$2.loadScript(JSBundleLoader.java:55)
                                                     at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:232)
                                                     at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1131)
                                                     at com.facebook.react.ReactInstanceManager.access$800(ReactInstanceManager.java:112)
                                                     at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:927)
                                                     at java.lang.Thread.run(Thread.java:818)
```

**Comment by wuyunqiang** [comment]
Maybe you should remove
```
   @Override
       protected String getJSBundleFile() {
           return "index.bundle";
       }
```
and try again.
