### ISSUE TITLE
Stuck at  Building 59% > :app:mergeDebugResources

### ISSUE THREAD

**Issue by pankaja92** [facebook/react-native#17753]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: Linux 4.13
  Node: 9.4.0
  Yarn: Not Found
  npm: 4.6.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

### Steps to Reproduce

1.Followed official docs and started react project using `react-native init`
2.And tried to run the project on an Android device by `react-native run-android
`
### Expected Behavior

Run the app on connected Android device

### Actual Behavior

Build stucked at **`> Building 59% > :app:mergeDebugResources`**

This is the log message I'm getting.

```
Scanning folders for symlinks in /home/pankaja/Documents/Projects/react-native/firstBasic/node_modules (6ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library
:app:prepareComAndroidSupportSupportV42301Library
:app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library
:app:prepareComFacebookFrescoDrawee130Library
:app:prepareComFacebookFrescoFbcore130Library
:app:prepareComFacebookFrescoFresco130Library
:app:prepareComFacebookFrescoImagepipeline130Library
:app:prepareComFacebookFrescoImagepipelineBase130Library
:app:prepareComFacebookFrescoImagepipelineOkhttp3130Library
:app:prepareComFacebookReactReactNative0520Library
:app:prepareComFacebookSoloaderSoloader010Library
:app:prepareOrgWebkitAndroidJscR174650Library
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:mergeDebugShaders
:app:compileDebugShaders
:app:generateDebugAssets
:app:mergeDebugAssets
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
java.io.IOException: Cannot run program "/home/pankaja/Android/Sdk/build-tools/23.0.1/aapt": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_1) has a null payload
java.io.IOException: Cannot run program "/home/pankaja/Android/Sdk/build-tools/23.0.1/aapt": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
java.io.IOException: Cannot run program "/home/pankaja/Android/Sdk/build-tools/23.0.1/aapt": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
java.io.IOException: Cannot run program "/home/pankaja/Android/Sdk/build-tools/23.0.1/aapt": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
java.io.IOException: Cannot run program "/home/pankaja/Android/Sdk/build-tools/23.0.1/aapt": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
java.io.IOException: Cannot run program "/home/pankaja/Android/Sdk/build-tools/23.0.1/aapt": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
Thread(png-cruncher_2) has a null payload
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_7) has a null payload
java.io.IOException: Cannot run program "/home/pankaja/Android/Sdk/build-tools/23.0.1/aapt": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_8) has a null payload
java.io.IOException: Cannot run program "/home/pankaja/Android/Sdk/build-tools/23.0.1/aapt": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_6) has a null payload
Thread(png-cruncher_3) has a null payload
Thread(png-cruncher_4) has a null payload
Thread(png-cruncher_5) has a null payload
java.io.IOException: Cannot run program "/home/pankaja/Android/Sdk/build-tools/23.0.1/aapt": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_9) has a null payload
java.io.IOException: Cannot run program "/home/pankaja/Android/Sdk/build-tools/23.0.1/aapt": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
java.io.IOException: Cannot run program "/home/pankaja/Android/Sdk/build-tools/23.0.1/aapt": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_13) has a null payload
java.io.IOException: Cannot run program "/home/pankaja/Android/Sdk/build-tools/23.0.1/aapt": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_17) has a null payload
java.io.IOException: Cannot run program "/home/pankaja/Android/Sdk/build-tools/23.0.1/aapt": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
java.io.IOException: Cannot run program "/home/pankaja/Android/Sdk/build-tools/23.0.1/aapt": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_10) has a null payload
java.io.IOException: Cannot run program "/home/pankaja/Android/Sdk/build-tools/23.0.1/aapt": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_16) has a null payload
java.io.IOException: Cannot run program "/home/pankaja/Android/Sdk/build-tools/23.0.1/aapt": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_15) has a null payload
java.io.IOException: Cannot run program "/home/pankaja/Android/Sdk/build-tools/23.0.1/aapt": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_12) has a null payload
Thread(png-cruncher_11) has a null payload
Thread(png-cruncher_14) has a null payload
java.io.IOException: Cannot run program "/home/pankaja/Android/Sdk/build-tools/23.0.1/aapt": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_19) has a null payload
java.io.IOException: Cannot run program "/home/pankaja/Android/Sdk/build-tools/23.0.1/aapt": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_20) has a null payload
java.io.IOException: Cannot run program "/home/pankaja/Android/Sdk/build-tools/23.0.1/aapt": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_18) has a null payload
> Building 59% > :app:mergeDebugResources
```

followed [this](https://github.com/facebook/react-native/issues/15909) github issue and tried to fix it by cleaning the gradle cache using

```
cd android && ./gradlew clean
cd .. && react-native run-android
``` 

But still the same error. stucked at 59%

### Reproducible Demo

1.Followed official docs and started react project using `react-native init`
2.And tried to run the project on an Android device by `react-native run-android

Followed Official docs to create a react native app using [native code](https://facebook.github.io/react-native/docs/getting-started.html)

**Comment by pankaja92** [comment]
Fixed it by installing the libraries

```
sudo apt-get install lib32z1
sudo apt-get install zlib1g:i386
```

**Comment by NayeemUrRehman** [comment]
i am facing same issue 
this could'nt help me getting errors.. packages not available
`sudo apt-get install lib32z1
sudo apt-get install zlib1g:i386`

**Comment by gaurav321garg** [comment]
change the sdk to a a lower

**Comment by rsunil92** [comment]
i am facing same problem, in windows platform. 
how to solve ?

**Comment by ataufiq123** [comment]
## On Fedora

```
sudo dnf install zlib.i686
sudo yum install libstdc++*
```

### if there are error libgcc_s.so.1
`sudo dnf install libgcc_s.so.1`

**Comment by getinfyKiranreddy** [comment]
I got to run above commands it worked for me 
thanks
