### ISSUE TITLE
Can't debug remote JS

### ISSUE THREAD

**Issue by FourEyebrowXiake** [facebook/react-native#17780]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment
```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.2.1
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

  Target Platform: iOS (11.2)

```

### Steps to Reproduce

1. yarn start
2. input "i"
3. Click Debug Remote JS

### Expected Behavior

use chrome debug JS

### Actual Behavior

```
Google Chrome exited with error: Error: Exited with code 1
11:00:02:     at ChildProcess.<anonymous> (/Users/fourfish/Desktop/react-native/UdaciFitness/node_modules/opn/index.js:86:8)
11:00:02:     at Object.onceWrapper (events.js:318:30)
11:00:02:     at emitTwo (events.js:125:13)
11:00:02:     at ChildProcess.emit (events.js:213:7)
11:00:02:     at maybeClose (internal/child_process.js:921:16)
11:00:02:     at Socket.stream.socket.on (internal/child_process.js:348:11)
11:00:02:     at emitOne (events.js:115:13)
11:00:02:     at Socket.emit (events.js:210:7)
11:00:02:     at Pipe._handle.close [as _onclose] (net.js:549:12)
```

![image](https://user-images.githubusercontent.com/18180417/35545989-ccac7c64-05ac-11e8-8300-6b3884143592.png)

### My Way
I tried everything from #6682, such as  restart chrome,  use "REACT_NATIVE_PACKAGER_HOSTNAME='127.0.0.1' npm start" and others.  But I still can't use  "Debug  Remote JS".

**Comment by FourEyebrowXiake** [comment]
I closed vscode and reinstall chrome. I think it's a conflict between vscode and chrome.
