### ISSUE TITLE
CLI fails when Chrome is not present

### ISSUE THREAD

**Issue by neiker** [facebook/react-native#17787]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

### Steps to Reproduce

1. Run `npm start` on a computer where chrome is not installed

### Expected Behavior

Build flawless

### Actual Behavior

```
Bundling `index.ios.js`  [development, non-minified]  ▓▓░░░░░░░░░░░░░░  13.7% (81/219)Launching Dev Tools...
Bundling `index.ios.js`  [development, non-minified]  ▓▓░░░░░░░░░░░░░░  14.4% (84/221)Google Chrome exited with error: Error: Exited with code 1
    at ChildProcess.<anonymous> (/Users/[user]/code/native-ios/node_modules/opn/index.js:86:8)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

After I opened `http://localhost:8081/debugger-ui/` on Firefox, it works correctly
```
Bundling `index.ios.js`  [development, non-minified]  100.0% (1328/1328), done.
```

### Reproducible Demo

Just a fresh install

**Comment by gedeagas** [comment]
I think this is not a bug.

This maybe happens because you once enable the debugging option on the specific emulator. So when you do npm start the debugging options is triggered. 

if you start a init a new clean project and run npm start it should work flawlessly.

Please correct me if I'm wrong.

**Comment by neiker** [comment]
Thanks for your answer, @gedeagas 

If this is so, where is saved that setting?
My start script is just this:
`"start": "NODE_ENV='development' node node_modules/react-native/local-cli/cli.js start",`

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (155/150 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:61057)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-a7b0-hello=salmanwaheed.info@sgmail.github.com>)
	id 1epQUm-003IeI-Lp
	for hello@salmanwaheed.info; Fri, 23 Feb 2018 20:27:33 -0700
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=6iMl91g33PMoPFvbjKmz0GQ829Q=; b=ZU8GkubZ87o97nj1
	d2YharoOSM+AnVOuV/nDYbu7QGYdvoyu5E+lfIJgSkwgNtqmTqZF5nP0YjqQdlBo
	NZaxb/3AsmgQS/hH+FOBtBrbDatV8BbOTvmhRab3+qJUV76EEEcHJB1W6AMcB8HG
	A7k6vzNNdj6ahL5k4xaSmvNxz8s=
Received: by filter0144p1iad2.sendgrid.net with SMTP id filter0144p1iad2-24766-5A90DB94-10
        2018-02-24 03:27:16.70121636 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0007p1iad2.sendgrid.net (SG) with ESMTP id fborayXpShySa4cZKCqoKA
	for <hello@salmanwaheed.info>; Sat, 24 Feb 2018 03:27:16.675 +0000 (UTC)
Date: Sat, 24 Feb 2018 03:27:16 +0000 (UTC)

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (168/150 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:52816 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89_1)
	(envelope-from <noreply@github.com>)
	id 1epQVJ-003J8I-I2
	for hello@salmanwaheed.info; Fri, 23 Feb 2018 20:28:06 -0700
Date: Fri, 23 Feb 2018 19:22:07 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1519442870;
	bh=JiJIeG2fB9FiAnpgNjJTQu2T+DbbxLUblB0RhYEMcJ0=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Ng5s7uVf1fuVHiV/T5eEDtbVAoVCXZDeQufeBnyDVcOj60gYwLY5pGEDR8iel7TNQ
	 n7ZsrBKkhakN4MWOW2+DyMr3DkMoSjxqBveED6rJiASB+4CyRRMevy5h+3fW4HoZR8
	 6tpIOn06PJNrvVZW7Faxy9lIyLYvvu/Xyz7SiNwI=
