### ISSUE TITLE
[Packager] After upgrade to 0.6.0, watchman show unable to resolve root : path "" issue

### ISSUE THREAD

**Issue by HillLiu** [facebook/react-native#1794]
Enter npm start in react-native folder than get this issue, any one face same issue?

It's not shown on my another 0.5.0 version.

--------------------------------------

npm start

> AwesomeProject@0.0.1 start /Users/xxx/git/AwesomeProject
> node_modules/react-native/packager/packager.sh

 ===============================================================
 |  Running packager on port 8081.
 |  Keep this packager running while developing on any JS
 |  projects. Feel free to close this tab and run your own
 |  packager instance if you prefer.
 |
 |     https://github.com/facebook/react-native 
 |
 ===============================================================

Looking for JS files in
   /Users/xxx/git/AwesomeProject

React packager ready.

 ERROR  unable to resolve root : path "" must be absolute
{"watchmanResponse":{"version":"3.3.0","error":"unable to resolve root : path \"\" must be absolute"}}
Error: unable to resolve root : path "" must be absolute
    at null.<anonymous> (/Users/xxx/git/AwesomeProject/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:84:23)
    at emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Readable.push (_stream_readable.js:126:10)
    at Transform.push (_stream_transform.js:140:32)
    at JSONStream._transform (/Users/xxx/git/AwesomeProject/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/node_modules/json-stream/lib/json-stream.js:30:14)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Writable.write (_stream_writable.js:217:11)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:538:20)

**Comment by browniefed** [comment]
@HillLiu are you still having this issue. It seems there were some issues that were talked about in #1754 and also #1606 with the packager and some peerDep issues.
Although your errors seem to be slightly different so I'm not sure. Do any of the solutions mentioned in those issues solve your problems?

**Comment by brentvatne** [comment]
Will reopen if this isn't addressed by any of the above advice! Thanks @browniefed for getting back to @HillLiu!
