### ISSUE TITLE
Remote debug not working on ubuntu

### ISSUE THREAD

**Issue by sm2017** [facebook/react-native#18082]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: Linux 4.13
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: N/A
  **Android Studio: Not Found // I install 3.0.1 and think this is a bug of `info` command** 

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3

### Steps to Reproduce

Enable remote debug on ubuntu

### Actual Behavior
`Metro Bundler` echo the following error

```
Google Chrome exited with error: Error: Exited with code 1
    at ChildProcess.<anonymous> (/home/user/Developer/AwesomeProject/node_modules/opn/index.js:86:8)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```
### Reproducible Demo

`react-native init AwesomeProject`

**Comment by mhmorta** [comment]
Same problem here, using Ubuntu, react-native 0.53

**Comment by zhuanglong** [comment]
+1

**Comment by NxSxD** [comment]
+1
