### ISSUE TITLE
App crashes on startup on select environments (Samsung + Android 7 + outdated system WebView)

### ISSUE THREAD

**Issue by SeMeKh** [facebook/react-native#18322]
We were seeing a notable amount of crashes on Samsung devices, and after getting hold of a device that kept crashing, we realized that even a freshly `react-native init`ed project crashes on startup.

### Environment

```
Environment:
  OS: Linux 4.15
  Node: 9.8.0
  Yarn: 1.5.1
  npm: 5.7.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.1 => 0.54.1
```

According to our crash reporter, the crash is limited to Samsung devices running Android 7.0.0.
On these devices, "Android WebView Implementation" is installed with version 0.0.0.1 which looks suspicious.

### Workaround
Updating Android WebView Implementation from Play Store fixes the issue.

### Stacktrace
```
android.webkit.MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
    at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:270)
    at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:330)
    at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
    at android.webkit.CookieManager.getInstance(CookieManager.java:39)
    at com.facebook.react.modules.network.ForwardingCookieHandler.getCookieManager(ForwardingCookieHandler.java:158)
    at com.facebook.react.modules.network.ForwardingCookieHandler.get(ForwardingCookieHandler.java:56)
    at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.java:59)
    at com.facebook.react.modules.network.ReactCookieJarContainer.loadForRequest(ReactCookieJarContainer.java:40)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:84)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:762)
android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
    at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:371)
    at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
    at android.webkit.CookieManager.getInstance(CookieManager.java:39)
    at com.facebook.react.modules.network.ForwardingCookieHandler.getCookieManager(ForwardingCookieHandler.java:158)
    at com.facebook.react.modules.network.ForwardingCookieHandler.get(ForwardingCookieHandler.java:56)
    at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.java:59)
    at com.facebook.react.modules.network.ReactCookieJarContainer.loadForRequest(ReactCookieJarContainer.java:40)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:84)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:762)
```

**Comment by hramos** [comment]
What's the most recent version you've reproduced this on? Which WebView implementation is this?

**Comment by SeMeKh** [comment]
RN v0.54.0
No WebView implementation is available on the device. but the issue is my project (or a fresh `react-native init`ed project) isn't using a webview either.

**Comment by hramos** [comment]
Is [this](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en) the WebView you're referring to in your workaround?

**Comment by SeMeKh** [comment]
Yes, it is.

**Comment by zhuxiaogit** [comment]
hi, i also encounter this error in  Essential Products   Essential Phone(Android 7.1.1)
no use webview,just use fetch api
Environment:
  OS: Windows 10
  Node: 6.11.4
  Yarn: 1.2.1
  npm: 3.10.10
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: ^0.48.3 => 0.48.3

**Comment by SudoPlz** [comment]
Is there a way to reproduce this without a samsung s8 device? Does it also happen on let's say for example GenyMotion?

**Comment by vivek-walecha-657** [comment]
This is my issue logs:

http://crashes.to/s/090d6cdb887

**Comment by vivek-walecha-657** [comment]
Any one have its proper fix?

**Comment by jamonholmgren** [comment]
This issue has been migrated to https://github.com/react-native-community/react-native-webview/issues/14 and can be closed.
