### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by tasneembohra** [facebook/react-native#18367]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getId()' on a null object reference
       at com.facebook.react.uimanager.NativeViewHierarchyManager.getAnimationRegistry(Unknown Source:67)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.getAnimationRegistry(Unknown Source:420)
       at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(Unknown Source:14)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(Unknown Source:87)
       at com.facebook.react.uimanager.UIViewOperationQueue.setViewHierarchyUpdateDebugListener(Unknown Source:56)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(Unknown Source)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(Unknown Source:31)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(Unknown Source)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(Unknown Source:49)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(Unknown Source:2)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
       at android.view.Choreographer.doCallbacks(Choreographer.java:778)
       at android.view.Choreographer.doFrame(Choreographer.java:710)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6809)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

* RN version: 0.51.0
* OS: 8.0.0
* Device: ONEPLUS A5010
* Not able to reproduce at my end

**Comment by chuckwu0** [comment]
I have The same crash stack

**Comment by arefed** [comment]
I am facing this issue too

**Comment by Deantsui** [comment]
I have the same crash stack. it only happens android 8

**Comment by tasneembohra** [comment]
@hramos , this is all information we are getting from stacktrace , not able to reproduce at end. 

Seems like its not only me who is facing.

@chuckwu0 @arefed @Deantsui  if you people have more information regarding this exception, would be very helpful.

**Comment by jclalala** [comment]
@hramos this also happens on our end on android 8 only from firebase crash reports... we're trying to see if we can effectively reproduce this, will provide an update soon.

**Comment by mfoonirlee** [comment]
We have same crash at android 8.0.0

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getId()' on a null object reference
	at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:537)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:431)
	at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:180)
	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:819)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:926)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:47)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:986)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:718)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

Environment
react-native: 0.53.3
react: 16.2.0
os: android 8.0
