### ISSUE TITLE
Cant run android debug build without dev support

### ISSUE THREAD

**Issue by ardmn** [facebook/react-native#18400]
I need run android debug build without dev support . I don't want use dev server for js. 

### Environment

  Unrecognized command 'info'
  Run react-native --help to see list of all available commands

react-native-cli: 2.0.1
react-native: 0.44.2 (tested in 0.54.2 as well)

### Expected Behavior

run debug version of android application without dev support:

ReactNativeHost
```
@Override
        public boolean getUseDeveloperSupport() {
            return false;//BuildConfig.DEBUG;
        }
```

### Actual Behavior

app crash;
```
  java.lang.RuntimeException: Error calling AppRegistry.runApplication
                                                                            at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
                                                                            at java.lang.Thread.run(Thread.java:761)
                                                                         Caused by: com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
                                                                            at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                            at android.os.Handler.handleCallback(Handler.java:751) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                            at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                            at android.os.Looper.loop(Looper.java:154) 
                                                                            at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208) 
                                                                            at java.lang.Thread.run(Thread.java:761) 
```

### Steps to Reproduce

override method getUseDeveloperSupport of ReactNativeHost class and run debug build (installDebug gradle task)
```
        public boolean getUseDeveloperSupport() {
            return false;//BuildConfig.DEBUG;
        }
```

**Comment by hramos** [comment]
It looks like you're using an older version of React Native (indeed, that's why `react-native info` failed on your system).

You might want to expand a bit on the Steps to Reproduce, as doing so will increase the chances someone might be interested in investigating.

**Comment by ardmn** [comment]
Sorry but I can't use last version . Now I use react-native-cli: 2.0.1 , react-native: 0.44.2 .

@hramos  "expand a bit on the Steps to Reproduce" - really ?   

1) override the  method getUseDeveloperSupport of ReactNativeHost class that return false. 
2) run from console: react-native run-android 

What are you not understand ?

**Comment by hramos** [comment]
We're only tracking issues that occur on the latest stable release. 0.44.2 is several months old and unless the issue is confirmed to occur on 0.54 or newer, it's not something that can be prioritized.

According to your repro steps, this issue is not related to your project so I don't see why it wouldn't be possible to create a new project that uses 0.54 in order to verify the issue exists in latest.

**Comment by ardmn** [comment]
@hramos I have create project with react-native-cli: 2.0.1 and react-native: 0.54.2 and I have same issues

**Comment by hramos** [comment]
Great! Thanks for checking.
