### ISSUE TITLE
Show full stack trace in `local-cli/cliEntry.js > handleError`

### ISSUE THREAD

**Issue by vjpr** [facebook/react-native#18436]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

When an error occurs I see a message without a stack trace:

```
ENOENT: no such file or directory, stat 'expo'
```

If I change:

https://github.com/facebook/react-native/blob/1c534719115fc4e99da9a414cff8638a6059a948/local-cli/cliEntry.js#L35-L40

to:

```js
const handleError = (err) => {
  console.error();
  console.error(err.message || err);
  console.error('error', err) // <-- print raw error
  console.error();
  process.exit(1);
};
```

I can see the full stack trace:

```
{ Error: ENOENT: no such file or directory, stat 'expo'
    at Object.fs.statSync (fs.js:948:11)
    at Object.statSync (/Users/Vaughan/dev-live/photo-booth-ios-crna/node_modules/.registry.npmjs.org/graceful-fs/4.1.11/node_modules/graceful-fs/polyfills.js:297:22)
    at verifyRootExists (/Users/Vaughan/dev-live/photo-booth-ios-crna/node_modules/.registry.npmjs.org/metro-pnpm/0.24.7-vjpr.1/node_modules/metro-pnpm/src/Bundler/index.js:281:13)
    at Array.forEach (<anonymous>)
    at new Bundler (/Users/Vaughan/dev-live/photo-booth-ios-crna/node_modules/.registry.npmjs.org/metro-pnpm/0.24.7-vjpr.1/node_modules/metro-pnpm/src/Bundler/index.js:120:23)
    at new Server (/Users/Vaughan/dev-live/photo-booth-ios-crna/node_modules/.registry.npmjs.org/metro-pnpm/0.24.7-vjpr.1/node_modules/metro-pnpm/src/Server/index.js:171:21)
    at Object.createServer (/Users/Vaughan/dev-live/photo-booth-ios-crna/node_modules/.registry.npmjs.org/metro-pnpm/0.24.7-vjpr.1/node_modules/metro-pnpm/src/legacy.js:160:10)
    at getPackagerServer (/Users/Vaughan/dev-live/photo-booth-ios-crna/node_modules/.registry.npmjs.org/react-native/0.52.0/node_modules/react-native/local-cli/server/runServer.js:174:16)
    at runServer (/Users/Vaughan/dev-live/photo-booth-ios-crna/node_modules/.registry.npmjs.org/react-native/0.52.0/node_modules/react-native/local-cli/server/runServer.js:90:26)
    at Object.server [as func] (/Users/Vaughan/dev-live/photo-booth-ios-crna/node_modules/.registry.npmjs.org/react-native/0.52.0/node_modules/react-native/local-cli/server/server.js:53:3) errno: -2, code: 'ENOENT', syscall: 'stat', path: 'expo' }
```

NOTE: When using expo which starts `react-native` as a child process, `console.error(err)` prints nothing.

## Environment

```
react-native info

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0
```

## Steps to Reproduce

Create a new `create-react-native-app` project.

Add a project `rn-cli.config.js` file

```
module.exports = {
  getProjectRoots() {
    return ['blahblah']
  }
}
```

Add `app.json` file:

```
{
  "expo": {
    "sdkVersion": "25.0.0",
    "packagerOpts": {
      "config": "rn-cli.config.js"
    }
  }
}
```

```
npm start
```

## Expected Behavior

Show full stack trace.

## Actual Behavior

Notice the one line error.

**Comment by vjpr** [comment]
```
react-native info

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0
```
