### ISSUE TITLE
Android startup crash 0.54.2,  DevLoadingViewController.showInternal

### ISSUE THREAD

**Issue by PerspectivesLab** [facebook/react-native#18430]
- [X ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

in recently upgraded react native version to 0.54.2 in my existing android app, there is now a crash.
it seems react native want to show a message on startup with : `android.widget.PopupWindow.invokePopup`
 but the context isnt ready yet, it was working fine before.

this is how i instantiate in onCreate function : 

```
       mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setBundleAssetName("index.android.bundle")
                .setJSMainModulePath("index.android")
                .addPackage(new MainReactPackage())
                .setUseDeveloperSupport( BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();

        mReactRootView.startReactApplication(mReactInstanceManager, "AwesomeReactApp", null);

        setContentView(mReactRootView);
```

## Environment
 

Environment:
  OS: Windows 8
  Node: 6.9.5
  Yarn: 1.2.1
  npm: 3.10.10
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.3.0.0 AI-162.3934792

Packages: (wanted => installed)
  react: ^16.0.0 => 16.2.0
  react-native: ^0.54.2 => 0.54.2

D:\new\NxChromiumArReact>

## Steps to Reproduce
implement code upper

## Expected Behavior
should launch the app

## Actual Behavior
the application crashed with android error

```
03-17 14:02:04.776 8997-8997/ D/AndroidRuntime: Shutting down VM
03-17 14:02:04.782 8997-8997/ E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: myapp, PID: 8997
                                                                                  android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
                                                                                      at android.view.ViewRootImpl.setView(ViewRootImpl.java:949)
                                                                                      at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:381)
                                                                                      at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:100)
                                                                                      at android.widget.PopupWindow.invokePopup(PopupWindow.java:1467)
                                                                                      at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1235)
                                                                                      at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1202)
                                                                                      at com.facebook.react.devsupport.DevLoadingViewController.showInternal(DevLoadingViewController.java:169)
                                                                                      at com.facebook.react.devsupport.DevLoadingViewController.access$100(DevLoadingViewController.java:38)
                                                                                      at com.facebook.react.devsupport.DevLoadingViewController$1.run(DevLoadingViewController.java:70)
                                                                                      at android.os.Handler.handleCallback(Handler.java:789)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                      at android.os.Looper.loop(Looper.java:164)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6938)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by dingshaoran** [comment]
I get same error

**Comment by krmao** [comment]
got same error at 0.55..4

```

1 android.view.ViewRootImpl.setView(ViewRootImpl.java:885)
--
2 android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:372)
3 android.view.WindowManagerImpl.addView(WindowManagerImpl.java:136)
4 android.widget.PopupWindow.invokePopup(PopupWindow.java:1466)
5 android.widget.PopupWindow.showAtLocation(PopupWindow.java:1231)
6 android.widget.PopupWindow.showAtLocation(PopupWindow.java:1198)
7 com.facebook.react.devsupport.DevLoadingViewController.void showInternal()(SourceFile:167)
8 com.facebook.react.devsupport.DevLoadingViewController.access$100(SourceFile:36)
9 com.facebook.react.devsupport.DevLoadingViewController$1.void run()(SourceFile:68)
10 android.os.Handler.handleCallback(Handler.java:809)
11 android.os.Handler.dispatchMessage(Handler.java:102)
12 android.os.Looper.loop(Looper.java:166)
13 android.app.ActivityThread.main(ActivityThread.java:7377)
14 java.lang.reflect.Method.invoke(Native Method)
15 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
16 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)


```

**Comment by dingshaoran** [comment]
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:794)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1429)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1203)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1170)
	at com.facebook.react.devsupport.DevLoadingViewController.showInternal(DevLoadingViewController.java:169)
	at com.facebook.react.devsupport.DevLoadingViewController.access$100(DevLoadingViewController.java:38)
	at com.facebook.react.devsupport.DevLoadingViewController$1.run(DevLoadingViewController.java:70)
	at android.os.Handler.handleCallback(Handler.java:792)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6701)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)



same error
