### ISSUE TITLE
[ANDROID] - Released App crash

### ISSUE THREAD

**Issue by J3j3m** [facebook/react-native#18483]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

When creating a release version, the released version does not works as expected : 
```
Process: com.driversitterdriver, PID: 14863
com.facebook.react.common.JavascriptException: undefined is not a function (evaluating 'this._lazyCallableModules[e]()'), stack:
value@18:1919
value@18:3062
<unknown>@18:959
value@18:2640
value@18:931

at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
at android.os.Looper.loop(Looper.java:158)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
at java.lang.Thread.run(Thread.java:818).
```
While it works well in debug mode. 

## Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.2.0
  Yarn: 0.27.5
  npm: 5.5.1
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

## Steps to Reproduce
Create release app from android studio

## Expected Behavior
Release app should work like it works in debug.

## Actual Behavior
Released app crashed at start with the error described above.

**Comment by J3j3m** [comment]
I solved it using this : 
```
doLast {
    def moveFunc = { resSuffix ->
        File originalDir = file("${resourcesDir}/drawable-${resSuffix}")
        if (originalDir.exists()) {
            File destDir = file("${resourcesDir}/drawable-${resSuffix}-v4")
            ant.move(file: originalDir, tofile: destDir)
        }
    }
    moveFunc.curry("ldpi").call()
    moveFunc.curry("mdpi").call()
    moveFunc.curry("hdpi").call()
    moveFunc.curry("xhdpi").call()
    moveFunc.curry("xxhdpi").call()
    moveFunc.curry("xxxhdpi").call()
}
```
Android Studio generate signed apk without showing any error, between creating release app from command show another error. I fixed it with the code above. Added right after the doFirst block in node_modules/react_native/react.gradle.
The Apk generated from AndroidStudio without this fix is probably the source of the issue above.

**Comment by woshicezai** [comment]
@J3j3m this problem has resolved?

**Comment by JangoTheBond** [comment]
Not yet
