### ISSUE TITLE
App crashes - integrating react-native with skype android sdk Didn't find class "okhttp3.WebSocketListener" on path

### ISSUE THREAD

**Issue by laxmisuresh** [facebook/react-native#18508]
- [ ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ ] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS:  macOS High Sierra 10.13.1
  Node:  7.10.0
  Yarn:  1.5.1
  npm:  5.3.0
  Watchman:  4.9.0
  Xcode:  Xcode 9.2 Build version 9C40b
  Android Studio:  3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.1 => 0.48.1
## Steps to Reproduce

I am trying to integrate skype android sdk. 

build.gradle
------------
```
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 */
project.ext.react = [
  // the name of the generated asset file containing your JS bundle
  bundleAssetName: "index.android.bundle",

  // the entry file for bundle generation
  entryFile: "index.android.js",

  // whether to bundle JS and assets in debug mode
  bundleInDebug: true,

  // whether to bundle JS and assets in release mode
  bundleInRelease: true,

  // whether to bundle JS and assets in another build variant (if configured).
  // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
  // The configuration property can be in the following formats
  //         'bundleIn${productFlavor}${buildType}'
  //         'bundleIn${buildType}'
  // bundleInFreeDebug: true,
  // bundleInPaidRelease: true,
  // bundleInBeta: true,

  // the root of your project, i.e. where "package.json" lives
  root: "../../",

  // where to put the JS bundle asset in debug mode
  jsBundleDirDebug: "$buildDir/intermediates/assets/debug",

  // where to put the JS bundle asset in release mode
  jsBundleDirRelease: "$buildDir/intermediates/assets/release",

  // where to put drawable resources / React Native assets, e.g. the ones you use via
  // require('./image.png')), in debug mode
  resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",

  // where to put drawable resources / React Native assets, e.g. the ones you use via
  // require('./image.png')), in release mode
  resourcesDirRelease: "$buildDir/intermediates/res/merged/release",

  // by default the gradle tasks are skipped if none of the JS files or assets change; this means
  // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
  // date; if you have any other folders that you want to ignore for performance reasons (gradle
  // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
  // for example, you might want to remove it from here.
  inputExcludes: ["android/**", "ios/**"],

  // override which node gets called and with what additional arguments
  nodeExecutableAndArgs: ["node"],

  // supply additional arguments to the packager
  extraPackagerArgs: []
]


apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 27

    defaultConfig {
        applicationId "com.demo.activity"
        minSdkVersion 17
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        multiDexEnabled true
    }

    dexOptions {
        jumboMode true
    }
    
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }

    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a": 1, "x86": 2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:27.0.2"
    compile("com.facebook.react:react-native:0.48.1") {
        exclude group: "com.android.support"
        //exclude group: "com.android.support", module:'appcompat-v7'
        exclude group: 'javax.inject'
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
        exclude group: 'com.squareup.okio'
    }
    compile "com.android.support:multidex:1.0.1"

    compile(name: "SkypeForBusinessNative", ext: 'aar')
    compile(name: "SkypeForBusinessPlatform", ext: 'aar')
    compile(name: "SkypeForBusinessInjector", ext: 'aar')
    compile(name: "SkypeForBusiness", ext: 'aar')
    compile(name: "SkypeForBusinessNativeEnums", ext: 'aar')
    compile(name: "SkypeForBusinessTelemetryClient", ext: 'aar')
    compile(name: "SkypeForBusinessTelemetryService", ext: 'aar')
    compile(name: "android-database-sqlcipher", ext: 'aar')
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
```

MainApplication.java
---------------------
```
public class MainApplication extends MultiDexApplication implements ReactApplication {

    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.asList(
                    new ActivityStarterReactPackage(),
                    new MainReactPackage()
            );
        }
    };

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        SoLoader.init(this, /* native exopackage */ false);
    }
}
```

1. Extended the Main Application with MultiDexApplication
2.  multiDexEnabled true in build.gradle
3.   dexOptions {
        jumboMode true
    } 
in build.gradle
4. added below dependencies
 compile("com.facebook.react:react-native:0.48.1") {
        exclude group: "com.android.support"
        //exclude group: "com.android.support", module:'appcompat-v7'
        exclude group: 'javax.inject'
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
        exclude group: 'com.squareup.okio'
    }
    compile "com.android.support:multidex:1.0.1"

    compile(name: "SkypeForBusinessNative", ext: 'aar')
    compile(name: "SkypeForBusinessPlatform", ext: 'aar')
    compile(name: "SkypeForBusinessInjector", ext: 'aar')
    compile(name: "SkypeForBusiness", ext: 'aar')
    compile(name: "SkypeForBusinessNativeEnums", ext: 'aar')
    compile(name: "SkypeForBusinessTelemetryClient", ext: 'aar')
    compile(name: "SkypeForBusinessTelemetryService", ext: 'aar')
    compile(name: "android-database-sqlcipher", ext: 'aar')

## Actual Behavior
App is crashing with below error. 

03-22 20:03:57.841 17927-17943/com.demo.activity E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                   Process: com.demo.activity, PID: 17927
                                                                   java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                       at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                       at java.lang.Thread.run(Thread.java:761)
                                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/react/packagerconnection/ReconnectingWebSocket;
                                                                       at com.facebook.react.packagerconnection.JSPackagerClient.<init>(JSPackagerClient.java:77)
                                                                       at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:171)
                                                                       at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:139)
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                       at java.lang.Thread.run(Thread.java:761) 
                                                                    Caused by: java.lang.ClassNotFoundException: com.facebook.react.packagerconnection.ReconnectingWebSocket
                                                                       at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                       at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                       at com.facebook.react.packagerconnection.JSPackagerClient.<init>(JSPackagerClient.java:77) 
                                                                       at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:171) 
                                                                       at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:139) 
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:305) 
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                       at java.lang.Thread.run(Thread.java:761) 
                                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/WebSocketListener;
                                                                       at com.facebook.react.packagerconnection.JSPackagerClient.<init>(JSPackagerClient.java:77) 
                                                                       at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:171) 
                                                                       at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:139) 
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:305) 
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                       at java.lang.Thread.run(Thread.java:761) 
                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.WebSocketListener" on path: DexPathList[[zip file "/data/app/com.demo.activity-1/base.apk"],nativeLibraryDirectories=[/data/app/com.demo.activity-1/lib/arm, /data/app/com.demo.activity-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                       at com.facebook.react.packagerconnection.JSPackagerClient.<init>(JSPackagerClient.java:77) 
                                                                       at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:171) 
                                                                       at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:139) 
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:305) 
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                       at java.lang.Thread.run(Thread.java:761)

**Comment by hramos** [comment]
Debugging crashes on individual apps is not something we're necessarily tracking on this repo. This is not to say that the issue is not attributable to this project. Ideally, this would be reproducible starting off on a blank new project.
