### ISSUE TITLE
Error while updating property 'allowFontScaling' in shadow node of type: RCTText

### ISSUE THREAD

**Issue by AndroidHensen** [facebook/react-native#18563]
Hello,We found a serious problem.
When we loaded two jsbundles at the same time, the following Crash occurred.
I suspect that two threads are contributing to each other's resources.
Because the property's property is random.
The property that is reported.

```
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'allowFontScaling' in shadow node of type: RCTText
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:113)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:154)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:58)
	at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:298)
	at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:289)
	at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:364)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:154)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
	at java.lang.Thread.run(Thread.java:762)
Caused by: java.lang.IllegalArgumentException: method com.facebook.react.views.text.ReactBaseTextShadowNode.setAllowFontScaling argument 1 has type boolean, got null
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:102)
	... 15 more
```

**Comment by sometime-rock** [comment]
we also have this problem a long time , official can give us a question ?

**Comment by AndroidHensen** [comment]
version 0.46

**Comment by AnanyaAppan** [comment]
I got this error, and it was because I had called my component inside itself :p
