### ISSUE TITLE
react-native run android is not working for me

### ISSUE THREAD

**Issue by Spartan-Arun** [facebook/react-native#18560]
What is wrong?
app is not getting build in to my phone.

on running $react-native run-android on windows cmd

gradle repo is getting downloded and installed while installing application to device I'm getting this error

Exception in thread "main" java.lang.NullPointerException
at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMain
Starter.java:34)
at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.ja
va:25)
at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

Where does it happen?
it happens on graddle I guess i don't know clearly

How do we replicate the issue?
just use command react-native run-android

How important is this (1-5)?
I am not even able to create a sample hello world app because of this issue.

Expected behavior (i.e. solution)
App should open in my android device

**Comment by Spartan-Arun** [comment]
Yes all the details are present.

Regards,
Arun
