### ISSUE TITLE
Any packages I install the others are removed.

### ISSUE THREAD

**Issue by rodrigofbm** [facebook/react-native#18614]
- [x ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x ] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
```
Environment:
  OS: Linux 4.14
  Node: 8.10.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-rc.0
  react-native: 0.54.3 => 0.54.3
```

## Steps to Reproduce
Any packages I install the others are removed

## Expected Behavior
Works fine

## Actual Behavior
```
npm WARN rm not removing /home/rodrigo/Documentos/React-Native/app12/node_modules/.bin/jsesc as it wasn't installed by /home/rodrigo/Documentos/React-Native/app12/node_modules/jsesc
npm WARN rm not removing /home/rodrigo/Documentos/React-Native/app12/node_modules/.bin/esparse as it wasn't installed by /home/rodrigo/Documentos/React-Native/app12/node_modules/esprima
npm WARN rm not removing /home/rodrigo/Documentos/React-Native/app12/node_modules/.bin/esvalidate as it wasn't installed by /home/rodrigo/Documentos/React-Native/app12/node_modules/esprima
npm WARN rm not removing /home/rodrigo/Documentos/React-Native/app12/node_modules/.bin/babylon as it wasn't installed by /home/rodrigo/Documentos/React-Native/app12/node_modules/babylon
npm WARN rm not removing /home/rodrigo/Documentos/React-Native/app12/node_modules/@babel/traverse/node_modules/.bin/babylon as it wasn't installed by /home/rodrigo/Documentos/React-Native/app12/node_modules/@babel/traverse/node_modules/babylon
npm WARN rm not removing /home/rodrigo/Documentos/React-Native/app12/node_modules/@babel/template/node_modules/.bin/babylon as it wasn't installed by /home/rodrigo/Documentos/React-Native/app12/node_modules/@babel/template/node_modules/babylon
npm WARN rm not removing /home/rodrigo/Documentos/React-Native/app12/node_modules/@babel/core/node_modules/.bin/babylon as it wasn't installed by /home/rodrigo/Documentos/React-Native/app12/node_modules/@babel/core/node_modules/babylon
npm notice created a lockfile as package-lock.json. You should commit this file.
+ redux@3.7.2
added 3 packages, removed 937 packages and updated 3 packages in 5.856s

```

Yesterday all was work fine, but now I got these issues. I do not remember changing something from react-native. 

Then, if I try run the app:

```
npm start

> app12@0.0.1 start /home/rodrigo/Documentos/React-Native/app12
> node node_modules/react-native/local-cli/cli.js start

module.js:549
    throw err;
    ^

Error: Cannot find module '.../React-Native/app12/node_modules/react-native/local-cli/cli.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app12@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app12@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/pamac-build-rodrigo/popcorntime/src/npm_cache/_logs/2018-03-29T03_36_10_420Z-debug.log
```
Can anyone help me?

**Comment by yangyankang** [comment]
Have you solved it yet?

**Comment by yangyankang** [comment]
Now i have the same problem
