### ISSUE TITLE
crash: WebSocketModule.close got 1 arguments, expected 3

### ISSUE THREAD

**Issue by ThaJay** [facebook/react-native#18696]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

Closing a websocket crashes the app

## Environment

```
$ react-native info
Scanning folders for symlinks in /media/dj/dev/scan-app/node_modules (9ms)

Environment:
  OS: Linux 4.13
  Node: 9.10.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.0-rc.0 => 16.3.0-rc.0
  react-native: ^0.55.0 => 0.55.0
```

## Steps to Reproduce

close an active websocket connection with `.close()`

## Expected Behavior

the websocket connection closes, no error

## Actual Behavior

```
--------- beginning of crash
04-04 14:28:15.716 19745 19780 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
04-04 14:28:15.716 19745 19780 E AndroidRuntime: Process: com.chipta, PID: 19745
04-04 14:28:15.716 19745 19780 E AndroidRuntime: com.facebook.react.bridge.NativeArgumentsParseException: WebSocketModule.close got 1 arguments, expected 3
04-04 14:28:15.716 19745 19780 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:353)
04-04 14:28:15.716 19745 19780 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
04-04 14:28:15.716 19745 19780 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
04-04 14:28:15.716 19745 19780 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:754)
04-04 14:28:15.716 19745 19780 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-04 14:28:15.716 19745 19780 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
04-04 14:28:15.716 19745 19780 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
04-04 14:28:15.716 19745 19780 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
04-04 14:28:15.716 19745 19780 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:760)
04-04 14:28:16.322 19745 19745 D ReactNative: ReactInstanceManager.detachViewFromInstance()
```
related:
https://github.com/facebook/react-native/issues/18623

**Comment by ThaJay** [comment]
https://github.com/facebook/react-native/commit/b9be289

**Comment by ThaJay** [comment]
In my code I use `ws.close()`. According to the websocket spec there can be 2 optional arguments. Despite them being optional I tried `ws.close(1000, 'reason')` and it did not make a difference.

> close()
>
> Closes the WebSocket connection or connection attempt, if any. If the connection is already CLOSED, this method does nothing.
>
> void close(
  in optional unsigned short code,
  in optional DOMString reason
);

https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

**Comment by ThaJay** [comment]
@kelset could you maybe remove the `Old Version` tag?

Also, I have made the repro steps more clear. I think this is all it takes to reproduce. If you agree, could you remove `Needs Repro Steps`? If you can not reproduce this way I am happy to make a more complete example.

**Comment by johakr** [comment]
https://github.com/facebook/react-native/commit/b9be289 is definitely causing this issue, since `WebSocketModule.close.length` is always returning `0`, which results in passing always only 1 parameter to `close()`.

Since this really is a severe bug, causing the entire app to crash and not to respond whenever one tries to close a websocket connection, I hope someone from the react-native team is going to revert the referenced commit and publish `0.55.1` version as soon as possible.

**Comment by kelset** [comment]
To discuss cherry-picks and critical things, there's a dedicated repo with a dedicated issue ([this](https://github.com/react-native-community/react-native-releases/issues/11)).

We'll keep you updated.

In the meantime I think pinging @rozele to know more about his commit is a good approach.

**Comment by ujwal-setlur** [comment]
This is still an issue on RN-0.55.2. This is a very serious issue! Why was this closed?

**Comment by rozele** [comment]
@ujwal-setlur The fix is merged to master and a request was put in to cherry-pick it for RN 0.55.3.

**Comment by ujwal-setlur** [comment]
Thanks @rozele!

**Comment by vahanNasibyan** [comment]
@rozele do we have the release date of 0.55.3? We faced the same issue and this fix is critical for our application.

**Comment by ujwal-setlur** [comment]
While we wait,  i have a postinstall script to download the patch and apply it.

**Comment by vahanNasibyan** [comment]
@ujwal-setlur any reference to this script is appreciated.

**Comment by anhnam00** [comment]
Please release v0.55.3 to fixed this

**Comment by ujwal-setlur** [comment]
@vahanNasibyan, this is what I did:

In your package.json file, declare the postinstall script:

```
  "scripts": {
    "start": "watchman watch-del-all && (adb reverse tcp:8081 tcp:8081 || true) && node node_modules/react-native/local-cli/cli.js start --reset-cache",
    "test": "jest",
    "postinstall": "scripts/third-party-boo-boos.sh"
  },
```

In a scripts folder in root directory, I have a script ```third-party-boo-boos.sh```:

```
#!/usr/bin/env bash
# Catch all script to fix/patch boo-boos in third-party libraries

# For RN 0.55.0 and up
# Download patch file and patch Websocket.js
wget https://github.com/facebook/react-native/commit/4b6e9d3dfd213689c5b319a4efee8d4f606d6f9d.patch
patch $PWD/node_modules/react-native/Libraries/WebSocket/WebSocket.js 4b6e9d3dfd213689c5b319a4efee8d4f606d6f9d.patch
rm -f 4b6e9d3dfd213689c5b319a4efee8d4f606d6f9d.patch
```

**Comment by anhnam00** [comment]
@ujwal-setlur i'm working on Window, please help me!

**Comment by ThaJay** [comment]
@haotangio https://github.com/facebook/react-native/commit/31a1b72d73f90d9f5c78e1a194f7ee80a53e9bb0

**Comment by wrightmk** [comment]
I'm still experiencing WebSocketModule.close got 1 arguments, expected 3 on React native version 0.55.4.  Using expo sdk 28.0.1.  Anyone else having this issue?

**Comment by wrightmk** [comment]
For those using expo. If anyone one else is having this issue, I resolved it by rm -rf node_modules and then running exp publish afterwards. It seems that exp still had version 28.0.0 cached from the node_modules
