### ISSUE TITLE
Android Release Build throw com.facebook.react.common.JavascriptException: No dimension set for key window

### ISSUE THREAD

**Issue by ragar90** [facebook/react-native#18713]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
**Environment:**
  OS: macOS Sierra 10.12.6
  Node: 6.9.4
  Yarn: 1.3.2
  npm: 3.10.10
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

**Packages: (wanted => installed)**
  react: 16.3.1 => 16.3.1
  react-native: 0.54.0 => 0.54.0

**Run in device:** Google Pixel Android 8.1

## Steps to Reproduce
Build the app for release, but instead using ./gradle assambleRelease use the same task from android studio

## Expected Behavior
Not to crash upon on start and load the app

## Actual Behavior
the app crash with the following stack trace
```
04-05 17:25:45.202 1862-1864/? E/ANDR-PERF-OPTSHANDLER: Warning: Resource [2, 0] not supported for core 1. Instead use resource for core 0
04-05 17:25:45.202 1862-1864/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 2, 0]
04-05 17:25:45.218 862-2100/? E/ActivityManager: applyOptionsLocked: Unknown animationType=0
04-05 17:25:45.741 14574-14601/? E/ReactNativeJS: No dimension set for key window
04-05 17:25:45.745 14574-14601/? E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
04-05 17:25:45.750 14574-14602/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                   Process: org.givesafe.merchant, PID: 14574
                                                   com.facebook.react.common.JavascriptException: No dimension set for key window, stack:
                                                   value@77:706
                                                   value@76:228
                                                   value@76:466
                                                   <unknown>@75:95
                                                   n@2:557
                                                   i@2:348
                                                   t@2:210
                                                   StyleSheet@13:2435
                                                   <unknown>@422:739
                                                   n@2:557
                                                   i@2:348
                                                   t@2:210
                                                   <unknown>@421:79
                                                   n@2:557
                                                   i@2:348
                                                   t@2:210
                                                   <unknown>@420:90
                                                   n@2:557
                                                   i@2:348
                                                   t@2:210
                                                   <unknown>@367:226
                                                   n@2:557
                                                   i@2:348
                                                   t@2:210
                                                   <unknown>@12:38
                                                   n@2:557
                                                   i@2:278
                                                   t@2:210
                                                   global code@599:9
                                                   
                                                       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
                                                       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
                                                       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
                                                       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                       at android.os.Handler.handleCallback(Handler.java:790)
                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                       at java.lang.Thread.run(Thread.java:764)
04-05 17:25:45.959 1254-1264/? E/SpellCheckerSession: ignoring processOrEnqueueTask due to unexpected mState=TASK_CLOSE scp.mWhat=TASK_CLOSE
04-05 17:25:45.960 1254-1264/? E/SpellCheckerSession: ignoring processOrEnqueueTask due to unexpected mState=TASK_CLOSE scp.mWhat=TASK_CLOSE
04-05 17:25:46.077 14574-14601/? E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag)
```
I just want to mention that it seems this same issue was reported [here](https://github.com/facebook/react-native/issues/15495) but the bot closed it because of not having the complete template

Please Help me since i need to release this build into production as soon as possible and this problem is totally blocking me

Also i want to mention that when i built the app in debug mode this not happen, this only happen when i build it for release

**Comment by ragar90** [comment]
@react-native-bot yes i can reproduce this on release v0.55

**Comment by ragar90** [comment]
Can some human at least tell me what that error means? instead of just throwing bots to answer me?

**Comment by adielhercules** [comment]
I think that the issue is that your bundle javascript is corrupt and you may have to update it, I think maybe the React Native documentation is not clear about this, but you may have to run this command before creatinng a release apk:
`react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/`

Run it, create the signed apk and it shoukld work.
