### ISSUE TITLE
"Attempted to redefine property XXX" hangs the entire app on Android

### ISSUE THREAD

**Issue by shivawu** [facebook/react-native#18716]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Any react-native app

## Steps to Reproduce
Define a style with two duplicated style in a single style, say `borderRadius`

## Expected Behavior
The app can start successfully, with a redbox

## Actual Behavior
The app hangs, react native fails to initialize with the following error
```
04-06 02:17:24.913  5941  5991 E ReactNativeJNI: Got JS Exception: Attempted to redefine property 'borderRadius'. (http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:175550)
04-06 02:17:24.914  5941  5991 E unknown:ReactNative: Exception in native call from JS
04-06 02:17:24.914  5941  5991 E unknown:ReactNative: com.facebook.react.devsupport.JSException: Attempted to redefine property 'borderRadius'. (http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:175550)
04-06 02:17:24.914  5941  5991 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
04-06 02:17:24.914  5941  5991 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:739)
04-06 02:17:24.914  5941  5991 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-06 02:17:24.914  5941  5991 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
04-06 02:17:24.914  5941  5991 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:148)
04-06 02:17:24.914  5941  5991 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
04-06 02:17:24.914  5941  5991 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:818)
04-06 02:17:24.914  5941  5991 E unknown:ReactNative: Caused by: com.facebook.jni.CppException: Attempted to redefine property 'borderRadius'. (http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:175550)
04-06 02:17:24.914  5941  5991 E unknown:ReactNative: 	... 7 more
```

The real issue here is that this is EXTREMELY hard to debug, since with the new JS delta build, the position it points to is with `index.delta` and it's a JSON file instead of a JS file, so that lineno (175550) is not accurate anymore. It would be great that this would behave like a normal error and do not fail the entire app.

**Comment by john-osullivan** [comment]
Did you ever resolve this yourself, @shivawu ?  Running into a hard crash because we apparently rewrote `Copy` someplace, not sure where to even start with debugging it.

**Comment by iamswain25** [comment]
my problem was solved when I changed ```render = () => (...)``` to ```render(){ return (...)}``` in react component
