### ISSUE TITLE
Install local package as dependency with react-native

### ISSUE THREAD

**Issue by ivikash** [facebook/react-native#18758]
Do you want to request a feature or report a bug?
Bug

What is the current behavior?
I am trying to use a package from a relative path and I have done `npm install ../../ExamplePackage'. These packages are relative by multiple levels and not just one.

I am getting the following errors

I also tried react-native install package etc, but I have been constantly getting the following error.

```
error: bundling failed: Error: Unable to resolve module `ExamplePackage` from `/Users/vikasagr/workspace/test/ReactNative/MyPackage/src/index.js`: Module `ExamplePackage` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/vikasagr/workspace/test/ReactNative/MyPackage/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:161:1460)
    at ResolutionRequest.resolveDependency (/Users/vikasagr/workspace/test/ReactNative/MyPackage/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:91:16)
    at DependencyGraph.resolveDependency (/Users/vikasagr/workspace/test/ReactNative/MyPackage/node_modules/metro/src/node-haste/DependencyGraph.js:272:4579)
    at dependencies.map.relativePath (/Users/vikasagr/workspace/test/ReactNative/MyPackage/node_modules/metro/src/DeltaBundler/traverseDependencies.js:376:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/vikasagr/workspace/test/ReactNative/MyPackage/node_modules/metro/src/DeltaBundler/traverseDependencies.js:374:16)
    at /Users/vikasagr/workspace/test/ReactNative/MyPackage/node_modules/metro/src/DeltaBundler/traverseDependencies.js:212:33
    at Generator.next (<anonymous>)
    at step (/Users/vikasagr/workspace/test/ReactNative/MyPackage/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:313)
    at /Users/vikasagr/workspace/test/ReactNative/MyPackage/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:473
```

I tried all the steps but nothing worked. I also tried haul but that wasn't also working for me.

I also want to understand what is the best way to share components across different packages? And what if these are non-npm based package.

**Comment by ivikash** [comment]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment
Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.2.0
  Yarn: 1.5.1
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 3.1 AI-173.4670197

Packages: (wanted => installed)
  react: ^16.3.1 => 16.3.1
  react-native: ^0.55.1 => 0.55.1

## Steps to Reproduce
npm install ../../ExamplePackage

Or 

react-native install ExamplePackage


## Expected Behavior
I will be able to do this
`import {SomeComponent} from 'ExamplePackage'`

## Actual Behavior
Unable to find ExamplePackage

**Comment by mowbell** [comment]
I have the same problem

**Comment by alexlevy0** [comment]
+1
