### ISSUE TITLE
App stops abruptly after successive failed builds

### ISSUE THREAD

**Issue by sambhav2612** [facebook/react-native#18794]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I was working on RN from the morning, initially, everything worked well. Then I linked Airbnb Lottie NPM package with the app and explicitly removed the added code (to link) the library from the Android files. I found how to unlink it, and after doing so only iOS files were removed. The app did not build thereon. I thought maybe inking the same library again and unlinking it could do something, so I did it and it worked after some addition to my system environment variables. Now, I was having trouble building the app several times as I had changed some code (added routing. FABs, etc) and it wouldn't work. After a great research finally, it built and abruptly stopped. I got the stack trace of ADB with the exception:

```
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: java.lang.reflect.InvocationTargetException
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: 	at java.lang.reflect.Method.invoke(Native Method)
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:102)
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:154)
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:58)
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: 	at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:378)
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:289)
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:366)
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: 	at java.lang.reflect.Method.invoke(Native Method)
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: 	at android.os.Handler.handleCallback(Handler.java:751)
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: 	at android.os.Looper.loop(Looper.java:154)
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: 	at java.lang.Thread.run(Thread.java:761)
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: Caused by: java.lang.IllegalArgumentException: Unknown value: 64
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: 	at com.facebook.react.uimanager.LayoutShadowNode$MutableYogaValue.setFromDynamic(LayoutShadowNode.java:60)
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: 	at com.facebook.react.uimanager.LayoutShadowNode.setHeight(LayoutShadowNode.java:154)
04-11 01:19:38.892 30232 30344 E unknown:ViewManager: 	... 17 more
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: Exception in native call
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'height' in shadow node of type: RCTView
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:113)
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:154)
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:58)
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:378)
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:289)
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:366)
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	at java.lang.reflect.Method.invoke(Native Method)
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:751)
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:154)
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:761)
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: Caused by: java.lang.reflect.InvocationTargetException
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	at java.lang.reflect.Method.invoke(Native Method)
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:102)
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	... 15 more
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: Caused by: java.lang.IllegalArgumentException: Unknown value: 64
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	at com.facebook.react.uimanager.LayoutShadowNode$MutableYogaValue.setFromDynamic(LayoutShadowNode.java:60)
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	at com.facebook.react.uimanager.LayoutShadowNode.setHeight(LayoutShadowNode.java:154)
04-11 01:19:38.893 30232 30344 E unknown:ReactNative: 	... 17 more
04-11 01:19:38.919 30232 30232 D ReactNative: CatalystInstanceImpl.destroy() start
04-11 01:19:38.922 30232 30232 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
04-11 01:19:38.931 30232 30232 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
04-11 01:19:38.936 30232 30232 D AndroidRuntime: Shutting down VM
04-11 01:19:38.937 30232 30232 E AndroidRuntime: FATAL EXCEPTION: main
04-11 01:19:38.937 30232 30232 E AndroidRuntime: Process: com.pgchacha, PID: 30232
04-11 01:19:38.937 30232 30232 E AndroidRuntime: java.lang.RuntimeException: com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 4 could not be found
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:311)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:869)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:616)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6123)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: Caused by: com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 4 could not be found
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:103)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:320)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:179)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:821)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:928)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:46)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:988)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
04-11 01:19:38.937 30232 30232 E AndroidRuntime: 	... 13 more
04-11 01:19:38.939  1680  1709 W ActivityManager:   Force finishing activity com.pgchacha/.MainActivity
04-11 01:19:38.947  1680  1709 W ActivityManager:   Force finishing activity com.pgchacha/.MainActivity
04-11 01:19:38.947  1680  1709 W ActivityManager: Duplicate finish request for ActivityRecord{e2adb5 u0 com.pgchacha/.MainActivity t437 f}
04-11 01:19:38.955 30232 30357 D ReactNative: CatalystInstanceImpl.destroy() end
04-11 01:19:39.004  1680 27540 I OpenGLRenderer: Initialized EGL, version 1.4
04-11 01:19:39.004  1680 27540 D OpenGLRenderer: Swap behavior 1
04-11 01:19:39.448  1680  1754 W ActivityManager: Activity pause timeout for ActivityRecord{e2adb5 u0 com.pgchacha/.MainActivity t437 f}
```

App name is PGChacha.

## Environment

Environment:
  OS: Windows 10
  Node: 9.1.0
  Yarn: 1.5.1
  npm: 5.8.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4670197

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.1 => 0.55.1

## Steps to Reproduce

Here's the code: https://github.com/sambhav2612/chacha

## Expected Behavior

I thought it'd show the content of `./js/routes/home`.

## Actual Behavior

It crashes abruptly with message `App Stopped`.

**Comment by coderwassananmol** [comment]
Which react-native version are you using?

**Comment by sambhav2612** [comment]
@coderwassananmol 0.55.1
