### ISSUE TITLE
Android GIF Image

### ISSUE THREAD

**Issue by muhamad-rizki** [facebook/react-native#18846]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

My apps got force closed, when i open it. here is the logcat:
04-13 17:54:07.528 14030-14063/id.doyanmakan E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                               Process: id.doyanmakan, PID: 14030
                                                               java.lang.IllegalAccessError: Method 'com.facebook.imagepipeline.animated.factory.AnimatedFactory com.facebook.imagepipeline.core.ImagePipelineFactory.getAnimatedFactory()' is inaccessible to class 'com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier' (declaration of 'com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier' appears in /data/app/id.doyanmakan-punV0xA8hDlg2gUVBkFHtw==/base.apk)
                                                                   at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:60)
                                                                   at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:49)
                                                                   at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:42)
                                                                   at com.facebook.drawee.backends.pipeline.Fresco.initializeDrawee(Fresco.java:76)
                                                                   at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:69)
                                                                   at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:46)
                                                                   at com.facebook.react.modules.fresco.FrescoModule.initialize(FrescoModule.java:104)
                                                                   at com.facebook.react.bridge.ModuleHolder.doInitialize(ModuleHolder.java:198)
                                                                   at com.facebook.react.bridge.ModuleHolder.markInitializable(ModuleHolder.java:86)
                                                                   at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceInitialized(NativeModuleRegistry.java:123)
                                                                   at com.facebook.react.bridge.CatalystInstanceImpl$2.run(CatalystInstanceImpl.java:387)
                                                                   at android.os.Handler.handleCallback(Handler.java:789)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
                                                                   at android.os.Looper.loop(Looper.java:164)
                                                                   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
                                                                   at java.lang.Thread.run(Thread.java:764)
04-13 17:54:08.162 1395-1395/? E/EGL_emulation: tid 1395: eglCreateSyncKHR(1957): error 0x3004 (EGL_BAD_ATTRIBUTE)
04-13 17:54:08.285 1471-1551/? E/AudioFlinger: not enough memory for AudioTrack size=131296
04-13 17:54:08.285 1471-1551/? E/AudioFlinger: createRecordTrack_l() initCheck failed -12; no control block?
04-13 17:54:08.285 2249-26010/com.google.android.googlequicksearchbox:search E/AudioRecord: AudioFlinger could not create record track, status: -12
04-13 17:54:08.293 2249-26010/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -12.
04-13 17:54:08.293 2249-26010/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
04-13 17:54:08.295 2249-26010/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded
04-13 17:54:08.498 14030-14030/id.doyanmakan E/WindowManager: android.view.WindowLeaked: Activity id.doyanmakan.MainActivity has leaked window DecorView@49f550d[] that was originally added here
                                                                  at android.view.ViewRootImpl.<init>(ViewRootImpl.java:485)
                                                                  at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
                                                                  at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:92)
                                                                  at android.app.Dialog.show(Dialog.java:330)
                                                                  at org.devio.rn.splashscreen.SplashScreen$1.run(SplashScreen.java:36)
                                                                  at android.app.Activity.runOnUiThread(Activity.java:6152)
                                                                  at org.devio.rn.splashscreen.SplashScreen.show(SplashScreen.java:26)
                                                                  at id.doyanmakan.MainActivity.onCreate(MainActivity.java:11)
                                                                  at android.app.Activity.performCreate(Activity.java:6975)
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                  at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                  at android.os.Looper.loop(Looper.java:164)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

## Environment

> react-native info
Scanning folders for symlinks in D:\Develop\doyanmakan\node_modules (22ms)

Environment:
  OS: Windows 10
  Node: 9.9.0
  Yarn: 1.5.1
  npm: 4.6.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.2 => 0.55.2

## Steps to Reproduce

I just adding the library 'com.facebook.fresco:animated-gif:1.9.0' to my build gradle then the error is happened.
clean, rebuild, still the same

## Expected Behavior

app should loaded correctly to react page after splashscreen shown, then hidden automatically

## Actual Behavior

apps is not started correctly if I add animated-gif library to my project build gradle, after splashcreen done, apps got crash

**Comment by muhamad-rizki** [comment]
it's looks like i forgot to add compile 'com.facebook.fresco:fresco:1.9.0' to my build gradle, its fixed my issue, thanks

**Comment by Dhanraj-bidchat** [comment]
How you resolved this ?

**Comment by muhamad-rizki** [comment]
@Dhanraj-bidchat in my case i only forgot to add compile 'com.facebook.fresco:fresco:1.9.0' on my app build gradle, try clean build then reinstall app
