### ISSUE TITLE
When delete index.js. I want to use index.ios.js and index.androide.js from project.

### ISSUE THREAD

**Issue by masumbillah** [facebook/react-native#18870]
Metro Bundler ready.

Loading dependency graph, done.
error: bundling failed: NotFoundError: Cannot find entry file index.js in any of the roots: ["/Users/ms/ReactNative/chatApp"]
    at DependencyGraph.getAbsolutePath (/Users/ms/ReactNative/chatApp/node_modules/metro/src/node-haste/DependencyGraph.js:304:11)
    at /Users/ms/ReactNative/chatApp/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:265:416
    at Generator.next (<anonymous>)
    at step (/Users/ms/ReactNative/chatApp/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:13:629)
    at /Users/ms/ReactNative/chatApp/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:13:789
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

**Comment by jaycee425** [comment]
didn't try that but try to change it from the native files. This had your opposite problem

https://github.com/facebook/react-native/issues/16517#issuecomment-339501883
