### ISSUE TITLE
RNTester - red box: Error: [BABEL] /tests/react-native/local-cli/cliEntry.js: .default is not a valid Plugin property

### ISSUE THREAD

**Issue by novellizator** [facebook/react-native#18950]
## Environment

```
react-native/RNTester$ react-native info
Command `info` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.
```
however I ran in on other projects and get

```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.6.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.1
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found
```
So even react native info doesn't work in that project...
## Steps to Reproduce

checkout tester app using steps from here https://github.com/facebook/react-native/tree/master/RNTester
## Expected Behavior

it would run the application 
## Actual Behavior
get a redbox: 
```
No script url provided.[...]

unsanitizedScriptURLString=(null)
```

which makes sense, since the packager screams:
```
/react-native/node_modules/@babel/core/lib/config/full.js:139
    throw e;
    ^

Error: [BABEL] /Users/..../workspace/tests/react-native/local-cli/cliEntry.js: .default is not a valid Plugin property
    at /Users/..../workspace/tests/react-native/node_modules/@babel/core/lib/config/validation/plugins.js:54:56
    at Array.forEach (<anonymous>)
    at validatePluginObject (/Users/.../workspace/tests/react-native/node_modules/@babel/core/lib/config/validation/plugins.js:52:20)
    at /Users/.../workspace/tests/react-native/node_modules/@babel/core/lib/config/full.js:215:53
    at cachedFunction (/Users/.../workspace/tests/react-native/node_modules/@babel/core/lib/config/caching.js:42:17)
    at loadPluginDescriptor (/Users/.../workspace/tests/react-native/node_modules/@babel/core/lib/config/full.js:207:10)
    at /Users/.../workspace/tests/react-native/node_modules/@babel/core/lib/config/full.js:64:16
    at Array.map (<anonymous>)
    at recurseDescriptors (/Users/.../workspace/tests/react-native/node_modules/@babel/core/lib/config/full.js:63:36)
    at loadFullConfig (/Users/.../workspace/tests/react-native/node_modules/@babel/core/lib/config/full.js:112:6)

```

**Comment by lessthanjake328** [comment]
I'm curious what you're getting in your Metro Bundler window because I just posted a similar issue with RNTester

**Comment by novellizator** [comment]
i wrote it in the issue (I just call it "packager" instead of metro bundler)

**Comment by Shubham1993** [comment]
I also got the same issue on npm start here are the logs : 

> Perpule1PayMobileApp@0.0.1 start /Users/perpule/Documents/Github_Repo/Perpule1PayMobileApps
> node node_modules/react-native/local-cli/cli.js start

/Users/perpule/Documents/Github_Repo/Perpule1PayMobileApps/node_modules/@babel/core/lib/config/full.js:139
    throw e;
    ^

Error: [BABEL] /Users/perpule/Documents/Github_Repo/Perpule1PayMobileApps/node_modules/react-native/local-cli/cliEntry.js: .default is not a valid Plugin property
    at /Users/perpule/Documents/Github_Repo/Perpule1PayMobileApps/node_modules/@babel/core/lib/config/validation/plugins.js:54:56
    at Array.forEach (<anonymous>)
    at validatePluginObject (/Users/perpule/Documents/Github_Repo/Perpule1PayMobileApps/node_modules/@babel/core/lib/config/validation/plugins.js:52:20)
    at /Users/perpule/Documents/Github_Repo/Perpule1PayMobileApps/node_modules/@babel/core/lib/config/full.js:215:53
    at cachedFunction (/Users/perpule/Documents/Github_Repo/Perpule1PayMobileApps/node_modules/@babel/core/lib/config/caching.js:42:17)
    at loadPluginDescriptor (/Users/perpule/Documents/Github_Repo/Perpule1PayMobileApps/node_modules/@babel/core/lib/config/full.js:207:10)
    at /Users/perpule/Documents/Github_Repo/Perpule1PayMobileApps/node_modules/@babel/core/lib/config/full.js:64:16
    at Array.map (<anonymous>)
    at recurseDescriptors (/Users/perpule/Documents/Github_Repo/Perpule1PayMobileApps/node_modules/@babel/core/lib/config/full.js:63:36)
    at loadFullConfig (/Users/perpule/Documents/Github_Repo/Perpule1PayMobileApps/node_modules/@babel/core/lib/config/full.js:112:6)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Perpule1PayMobileApp@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Perpule1PayMobileApp@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/perpule/.npm/_logs/2018-04-20T03_38_55_489Z-debug.log

And react-native info is alos not working.

I am using Mac book Sierra version : 10.12.6 (16G1114)
npm version : 5.6.0
watchman version : 4.9.0
Node version : v9.11.1

**Comment by himanshuchauhan** [comment]
having the same issue

**Comment by mikaoelitiana** [comment]
I had this issue a few days ago and tryed again today after pull, it's not there anymore.

**Comment by himanshuchauhan** [comment]
Yes , Having the same issue , tried looking into babel configs but cant figure out the problem , everything looks good , this plugin it shows missing is in the configs.

**Comment by novellizator** [comment]
damn you, bot! reopened as a new issue https://github.com/facebook/react-native/issues/19195
