### ISSUE TITLE
No static method builder() Lcom/facebook/react/ReactInstanceManager$Builder; 

### ISSUE THREAD

**Issue by nadirHomeFriend** [facebook/react-native#19004]
- [ ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [ ] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [ ] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

Iam facing an issue with react)native)gem when app is killer . every thing works fine when app foreground/bacground but when app is killer the app crash when receiving the notification: 
## Environment

    "react-native": "0.44.0",
    "react": "16.0.0-alpha.6",
    "react-native-gcm-android": "^0.2.0",
    "react-native-system-notification": "^0.2.1",
## Steps to Reproduce

from react-native-gcm-android , ReactInstanceManager.builder() which is imported from import com.facebook.react.ReactInstanceManager is having trouble . 
 build.gradle of react-native-gcm-android: 
apply plugin: 'com.android.library'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.facebook.react:react-native:0.17.+'
    compile 'com.google.android.gms:play-services-gcm:8.1.0'
    compile 'com.android.support:appcompat-v7:23.0.0'
    compile project(':react-native-system-notification')
}

## Expected Behavior

android application can receive notification when it is killed
## Actual Behavior

04-24 16:14:47.858 4569-4569/? E/Zygote: v2
04-24 16:14:47.868 4569-4569/? E/Zygote: accessInfo : 0
04-24 16:14:48.588 4569-4569/com.homefriend.app.staging E/UncaughtException: java.lang.NoSuchMethodError: No static method builder()Lcom/facebook/react/ReactInstanceManager$Builder; in class Lcom/facebook/react/ReactInstanceManager; or its super classes (declaration of 'com.facebook.react.ReactInstanceManager' appears in /data/app/com.homefriend.app.staging-1/base.apk)
                                                                                 at com.oney.gcm.BackgroundService.onStartCommand(BackgroundService.java:28)
                                                                                 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4062)
                                                                                 at android.app.ActivityThread.access$2400(ActivityThread.java:221)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1897)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:158)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
04-24 16:14:48.868 4569-4569/com.homefriend.app.staging E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.homefriend.app.staging, PID: 4569
                                                                          java.lang.NoSuchMethodError: No static method builder()Lcom/facebook/react/ReactInstanceManager$Builder; in class Lcom/facebook/react/ReactInstanceManager; or its super classes (declaration of 'com.facebook.react.ReactInstanceManager' appears in /data/app/com.homefriend.app.staging-1/base.apk)
                                                                              at com.oney.gcm.BackgroundService.onStartCommand(BackgroundService.java:28)
                                                                              at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4062)
                                                                              at android.app.ActivityThread.access$2400(ActivityThread.java:221)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1897)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:158)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

thanks for helping me

**Comment by nadirHomeFriend** [comment]
i have this error when running react-native info :  Unrecognized command 'info'
  Run react-native --help to see list of all available commands****
i have never run this command
