### ISSUE TITLE
Android: OkHttpClientFactory error

### ISSUE THREAD

**Issue by denisk20** [facebook/react-native#19054]
With [this pull request](https://github.com/facebook/react-native/pull/17237) merged it should now be possible to customize OkHttp client for Android. However following the steps in the description lead to an error:

    java.lang.ClassCastException: okhttp3.CookieJar$1 cannot be cast to com.facebook.react.modules.network.CookieJarContainer
        at com.facebook.react.modules.network.NetworkingModule.<init>(NetworkingModule.java:141)
        at com.facebook.react.modules.network.NetworkingModule.<init>(NetworkingModule.java:164)
        at com.facebook.react.shell.MainReactPackage$18.get(MainReactPackage.java:245)
        at com.facebook.react.shell.MainReactPackage$18.get(MainReactPackage.java:242)
        at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:79)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1172)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1142)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1080)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:911)
        at java.lang.Thread.run(Thread.java:764)

Inspecting dependencies with `./gradlew app:dependencies` shows that I have OkHttp version `3.6.0`.

## Environment
Environment:
  OS:  macOS Sierra 10.12.6
  Node:  6.11.3
  Yarn:  1.6.0
  npm:  5.3.0
  Watchman:  4.4.0
  Xcode:  Xcode 9.2 Build version 9C40b
  Android Studio:  3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.55.3 => 0.55.3
## Steps to Reproduce
Create a class:

    public class MyOkHttpClientFactory implements OkHttpClientFactory {
        public OkHttpClient createNewNetworkModuleClient() {
            return new OkHttpClient.Builder().build();
        }
    }

In your `ReactApplication.onCreate()` add the following

    @Override
    public void onCreate() {
        super.onCreate();
        OkHttpClientProvider.setOkHttpClientFactory(new MyOkHttpClientFactory());
    }

Build and run the app

## Expected Behavior
The app works

## Actual Behavior
The app crashes with the above stacktrace.

**Comment by odemolliens** [comment]
You should try this:

    public class OKHttpOv implements OkHttpClientFactory {

       @Override
       public OkHttpClient createNewNetworkModuleClient() {
           return new OkHttpClient.Builder().cookieJar(new ReactCookieJarContainer()).build();
        }
    }

Using **.cookieJar(new ReactCookieJarContainer())** fix the problem
