### ISSUE TITLE
Error: "Use of const in strict mode." when doing a release build

### ISSUE THREAD

**Issue by grobmeier** [facebook/react-native#19101]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

I followed the guide here:
https://facebook.github.io/react-native/docs/running-on-device.html
to prepare my app for the appstore (iOS)

When I create a build, it will fail with this message:

```
node /myapp-ios.git/node_modules/react-native/local-cli/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Users/myuser/Library/Developer/Xcode/DerivedData/myapp-dfraoaivwzsccuavfyudbsliqfwd/Build/Products/Release-iphoneos/myapp.app/main.jsbundle --assets-dest /Users/myuser/Library/Developer/Xcode/DerivedData/myapp-dfraoaivwzsccuavfyudbsliqfwd/Build/Products/Release-iphoneos/myapp.app

/myapp-ios.git/node_modules/metro-core/src/formatBanner/index.js:13
const formatBanner = require('./formatBanner');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/myuser/Documents/Development/myapp/myapp-ios.git/node_modules/react-native/local-cli/server/checkNodeVersion.js:10:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
+ [[ false != true ]]
+ [[ ! -f /Users/myuser/Library/Developer/Xcode/DerivedData/myapp-dfraoaivwzsccuavfyudbsliqfwd/Build/Products/Release-iphoneos/myapp.app/main.jsbundle ]]
+ echo 'error: File /Users/myuser/Library/Developer/Xcode/DerivedData/myapp-dfraoaivwzsccuavfyudbsliqfwd/Build/Products/Release-iphoneos/myapp.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/myuser/Library/Developer/Xcode/DerivedData/myapp-dfraoaivwzsccuavfyudbsliqfwd/Build/Products/Release-iphoneos/myapp.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2

```

## Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.4.0
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

## Steps to Reproduce

Just building it with the settings above will cause this.

## Expected Behavior

It would build with the combined file.

## Actual Behavior

It does not build with the error message above.

**Comment by grobmeier** [comment]
This answer on Stackoverflow helped me:
https://stackoverflow.com/a/48431161/690771

I had to set another path to "node". When testing on CLI, the node version was correct; however it seems something inside the React environment would take the wrong node. Not sure where this is coming from.
