### ISSUE TITLE
TextInput bug on Android

### ISSUE THREAD

**Issue by AE0011** [facebook/react-native#19148]
`  <TextInput
     maxLength={5}
/>`

when ever length of text input reach to max and after that move cursor to first of text input and start typing character fatal error happen.

android os = 5.0.1

`
java.lang.IndexOutOfBoundsException: charAt: -1 < 0
                                                                              at android.text.SpannableStringBuilder.charAt(SpannableStringBuilder.java:114)
                                                                              at com.facebook.react.views.textinput.ReactEditTextInputConnectionWrapper.setComposingText(ReactEditTextInputConnectionWrapper.java:104)
                                                                              at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:340)
                                                                              at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5264)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
`

**Comment by yangbo5207** [comment]
same issue + 1
