### ISSUE TITLE
[Packager] Failed at start script './packager/packager.sh "--root" [path]'

### ISSUE THREAD

**Issue by hoseokchoi** [facebook/react-native#1914]
I'm following [this tutorial](https://facebook.github.io/react-native/docs/embedded-app.html#content), but got error in Start Development Server step. 

## Console Output
```
MacBook-Pro:MydanoCoach Hoseok$ (JS_DIR=`pwd`/ReactComponent; cd Pods/React; npm run start -- --root $JS_DIR)

> react-native@0.6.0 start /Users/Hoseok/iOS/MydanoCoach/Pods/React
> ./packager/packager.sh "--root" "/Users/Hoseok/iOS/MydanoCoach/ReactComponent"

sh: ./packager/packager.sh: Permission denied

npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "run" "start" "--" "--root" "/Users/Hoseok/iOS/MydanoCoach/ReactComponent"
npm ERR! node v2.3.3
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! react-native@0.6.0 start: `./packager/packager.sh "--root" "/Users/Hoseok/iOS/MydanoCoach/ReactComponent"`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the react-native@0.6.0 start script './packager/packager.sh "--root" "/Users/Hoseok/iOS/MydanoCoach/ReactComponent"'.
npm ERR! This is most likely a problem with the react-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./packager/packager.sh "--root" "/Users/Hoseok/iOS/MydanoCoach/ReactComponent"
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Hoseok/iOS/MydanoCoach/Pods/React/npm-debug.log
```

## npm-debug.log file
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/iojs',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--root',
1 verbose cli   '/Users/Hoseok/iOS/MydanoCoach/ReactComponent' ]
2 info using npm@2.11.3
3 info using node@v2.3.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart react-native@0.6.0
6 info start react-native@0.6.0
7 verbose unsafe-perm in lifecycle true
8 info react-native@0.6.0 Failed to exec start script
9 verbose stack Error: react-native@0.6.0 start: `./packager/packager.sh "--root" "/Users/Hoseok/iOS/MydanoCoach/ReactComponent"`
9 verbose stack Exit status 126
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:764:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid react-native@0.6.0
11 verbose cwd /Users/Hoseok/iOS/MydanoCoach/Pods/React
12 error Darwin 14.4.0
13 error argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "run" "start" "--" "--root" "/Users/Hoseok/iOS/MydanoCoach/ReactComponent"
14 error node v2.3.3
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error react-native@0.6.0 start: `./packager/packager.sh "--root" "/Users/Hoseok/iOS/MydanoCoach/ReactComponent"`
17 error Exit status 126
18 error Failed at the react-native@0.6.0 start script './packager/packager.sh "--root" "/Users/Hoseok/iOS/MydanoCoach/ReactComponent"'.
18 error This is most likely a problem with the react-native package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     ./packager/packager.sh "--root" "/Users/Hoseok/iOS/MydanoCoach/ReactComponent"
18 error You can get their info via:
18 error     npm owner ls react-native
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by brentvatne** [comment]
That's strange, I've never seen this error before. Could you push this project to Github?

**Comment by hoseokchoi** [comment]
I pushed the project. https://github.com/hoseokchoi/ReactNativeTest
[The original tutorial that I followed](https://facebook.github.io/react-native/docs/embedded-app.html) is written in Objective-C, but I rewrote it with Swift. Thanks.

**Comment by browniefed** [comment]
@hoseokchoi any update on this?

@ide @brentvatne close till more response + future packager move

**Comment by ide** [comment]
Sounds like there's something wrong with your Node setup. Try this:
```
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.26.1/install.sh | bash
# Close and reopen your terminal window
nvm install v2
nvm alias default v2
rm -rf project/node_modules
npm install
```
