### ISSUE TITLE
Hyperledger Fabric

### ISSUE THREAD

**Issue by jer117** [facebook/react-native#19181]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

**Comment by jer117** [comment]
module.js:540
    throw err;
    ^

Error: Cannot find module './api.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jeosullivan/Development/fabric-samples/fabcar/node_modules/fabric-ca-client/lib/FabricCAClientImpl.js:19:11)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by jer117** [comment]
I am just trying to run hyperledger fabrics example called marbles, using the simple set up on my localhost. When I type "node enrollAdmin.js", this was the error that I encountered.

**Comment by jer117** [comment]
Wrong area
