### ISSUE TITLE
An error when run command 'npm start'

### ISSUE THREAD

**Issue by 157688302** [facebook/react-native#1920]
ERROR  watch EMFILE
2015-07-08 20:07 node[24221] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
{"code":"EMFILE","errno":"EMFILE","syscall":"watch"}
2015-07-08 20:07 node[24221] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-07-08 20:07 node[24221] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
Error: watch EMFILE
    at errnoException (evalmachine.<anonymous>:1030:11)
    at FSWatcher.start (evalmachine.<anonymous>:1062:11)
    at Object.fs.watch (evalmachine.<anonymous>:1087:11)
    at NodeWatcher.watchdir (/Users/chaos/facebook/react-native/node_modules/sane/src/node_watcher.js:144:20)
    at Walker.<anonymous> (/Users/chaos/facebook/react-native/node_modules/sane/src/node_watcher.js:351:12)
    at Walker.emit (events.js:98:17)
    at /Users/chaos/facebook/react-native/node_modules/sane/node_modules/walker/lib/walker.js:69:16
    at ReaddirReq.Req.done (/Users/chaos/facebook/react-native/node_modules/graceful-fs/graceful-fs.js:141:5)
    at ReaddirReq.done (/Users/chaos/facebook/react-native/node_modules/graceful-fs/graceful-fs.js:88:22)
    at Object.oncomplete (evalmachine.<anonymous>:107:15)

See http://facebook.github.io/react-native/docs/troubleshooting.html
2015-07-08 20:07 node[24221] (FSEvents.framework) for common problems and solutions.
FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-07-08 20:07 node[24221] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-07-08 20:07 node[24221] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-07-08 20:07 node[24221] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-07-08 20:07 node[24221] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-07-08 20:07 node[24221] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-07-08 20:07 node[24221] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-07-08 20:07 node[24221] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-07-08 20:07 node[24221] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-07-08 20:07 node[24221] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

evalmachine.<anonymous>:438
2015-07-08 20:07 node[24221] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
2015-07-08 20:07 node[24221] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-07-08 20:07 node[24221] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-07-08 20:07 node[24221] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-07-08 20:07 node[24221] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-07-08 20:07 node[24221] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-07-08 20:07 node[24221] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
Error: EMFILE, too many open files '/Users/chaos/.babel.json'
    at Object.fs.openSync (evalmachine.<anonymous>:438:18)
    at Object.fs.writeFileSync (evalmachine.<anonymous>:977:15)
    at process.save (/Users/chaos/facebook/react-native/node_modules/babel-core/lib/babel/api/register/cache.js:36:19)
    at process.emit (events.js:95:17)
    at process.exit (node.js:711:17)
    at process.req.rawBody (/Users/chaos/facebook/react-native/packager/packager.js:151:11)
    at process.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.8
npm ERR! code ELIFECYCLE
npm ERR! react-native@0.6.0 start: `./packager/packager.sh`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the react-native@0.6.0 start script './packager/packager.sh'.
npm ERR! This is most likely a problem with the react-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./packager/packager.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chaos/facebook/react-native/Examples/SampleApp/npm-debug.log

**Comment by 157688302** [comment]
when i run command 'brew install watchman',it's ok....

**Comment by axelg12** [comment]
One question. Why do we need watchman ? I had react-native 0.6.0 and was upgrading to 0.8.0 and it failed with the same error when I didn't have watchman installed.

**Comment by achang28** [comment]
I had a similar problem -- was getting the following error within the terminal:  EMFILE: too many open files...

```brew install watchman``` also did the trick

**Comment by torgeir** [comment]
Same here.

**Comment by beeant** [comment]
me too `brew install watchman`

**Comment by iggied** [comment]
brew install watchman   Worked for me too.  Please update your docs
