### ISSUE TITLE
App crashes on old device (Android 4.1 / HTC 500)

### ISSUE THREAD

**Issue by javilumbrales** [facebook/react-native#19236]
### Issue

I'm using react-native-firebase (based on rract-native) to build a simple app and when I tried to run it on iOS simulator and my other Android devices it worked just fine until I tried to run it on my ancient HTC 500. Basically, app crashes when starting.

LogCat:

```
05-12 01:00:31.543: W/dalvikvm(12579): Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lokhttp3/internal/Util;
05-12 01:00:31.543: W/dalvikvm(12579): Exception Ljava/lang/ExceptionInInitializerError; thrown while initializing Lokhttp3/OkHttpClient;
05-12 01:00:31.543: W/dalvikvm(12579): threadid=19: thread exiting with uncaught exception (group=0x418db600)
05-12 01:00:31.653: E/Fabric(12579): Failed to retrieve settings from https://settings.crashlytics.com/spi/v2/platforms/android/apps/com.lumbralessoftware.allmemes/settings
05-12 01:00:31.653: E/Answers(12579): Failed to retrieve settings
05-12 01:00:31.793: W/CrashlyticsCore(12579): Cannot send reports. Settings are unavailable.
05-12 01:00:31.803: E/AndroidRuntime(12579): FATAL EXCEPTION: Thread-799
05-12 01:00:31.803: E/AndroidRuntime(12579): java.lang.ExceptionInInitializerError
05-12 01:00:31.803: E/AndroidRuntime(12579): 	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:453)
05-12 01:00:31.803: E/AndroidRuntime(12579): 	at com.facebook.react.modules.network.OkHttpClientProvider.createClient(OkHttpClientProvider.java:61)
05-12 01:00:31.803: E/AndroidRuntime(12579): 	at com.facebook.react.modules.network.NetworkingModule.<init>(NetworkingModule.java:166)
05-12 01:00:31.803: E/AndroidRuntime(12579): 	at com.facebook.react.shell.MainReactPackage$18.get(MainReactPackage.java:247)
05-12 01:00:31.803: E/AndroidRuntime(12579): 	at com.facebook.react.shell.MainReactPackage$18.get(MainReactPackage.java:244)
05-12 01:00:31.803: E/AndroidRuntime(12579): 	at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81)
05-12 01:00:31.803: E/AndroidRuntime(12579): 	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
05-12 01:00:31.803: E/AndroidRuntime(12579): 	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1171)
05-12 01:00:31.803: E/AndroidRuntime(12579): 	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1141)
05-12 01:00:31.803: E/AndroidRuntime(12579): 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1083)
05-12 01:00:31.803: E/AndroidRuntime(12579): 	at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
05-12 01:00:31.803: E/AndroidRuntime(12579): 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:920)
05-12 01:00:31.803: E/AndroidRuntime(12579): 	at java.lang.Thread.run(Thread.java:864)
05-12 01:00:31.803: E/AndroidRuntime(12579): Caused by: java.lang.ExceptionInInitializerError
05-12 01:00:31.803: E/AndroidRuntime(12579): 	at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:122)
05-12 01:00:31.803: E/AndroidRuntime(12579): 	... 13 more
05-12 01:00:31.803: E/AndroidRuntime(12579): Caused by: java.lang.NoClassDefFoundError: okio.Buffer
05-12 01:00:31.803: E/AndroidRuntime(12579): 	at okhttp3.ResponseBody.create(ResponseBody.java:208)
05-12 01:00:31.803: E/AndroidRuntime(12579): 	at okhttp3.internal.Util.<clinit>(Util.java:48)
05-12 01:00:31.803: E/AndroidRuntime(12579): 	... 14 more
05-12 01:00:31.803: E/EmbeddedLogger(385): App crashed! Process: com.lumbralessoftware.allmemes
05-12 01:00:31.803: E/EmbeddedLogger(385): App crashed! Package: com.lumbralessoftware.allmemes v6 (1.0.6)
05-12 01:00:31.803: E/EmbeddedLogger(385): Application Label: Memes Free Matcher Test
05-12 01:00:31.803: W/ActivityManager(385):   Force finishing activity com.lumbralessoftware.allmemes/.MainActivity
```

Seems clear that something is wrong with okhttp but not sure why, nor how to fix it, and I don't understand why it works for other android version but not this one...

### Environment

Android 4.1.2

```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.11.1
  Yarn: Not Found
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.2 => 16.3.2
  react-native: ^0.54.4 => 0.54.4
```

### Build dependencies

```
"dependencies": {
    "fbjs": "^0.8.16",
    "react": "^16.3.2",
    "react-native": "^0.54.4",
    "react-native-firebase": "^4.0.4",
    "react-native-image-picker": "^0.26.7",
    "react-native-loading-spinner-overlay": "^0.5.2",
    "react-native-progress": "^3.4.0",
    "react-native-swipe-cards": "^0.1.1"
  }
```

If you need any additional details let me know, please.

I'm not sure if issue is related to react-native or to okhttp3. I've failed to find anything about people experiencing same issue. If this is not relevant to you, then if you could point me to the right place to report it, that would be great. 

Thank you very much!

**Comment by daqiuqu** [comment]
Try add this line to build.gradle:
compile 'com.android.support:multidex:1.0.1'
and override attachBaseContext in MainApplication.java with this:
  @Override
  protected void attachBaseContext(Context base) {
    super.attachBaseContext(base);
    MultiDex.install(this);
  }

**Comment by javilumbrales** [comment]
Oops forgot to reply. Thank you very much @daqiuqu, followed your instructions and issue got fixed  😊. Cheers, J
