### ISSUE TITLE
[CI] Fix test_android failures, May 2018

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#19309]
- [X] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [X] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [X] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

[Android tests have not run](https://circleci.com/gh/facebook/react-native/42963) for a while due to various issues. Fixing this may take a while as failing tests tend to mask whenever a new issue is introduced to the codebase. I'll keep this description updated with each additional failure that is uncovered.

### ~BUCK fails to fetch Fabric Yoga dependency~

BUCK fetch is failing to install dependencies with the following error:

```
Unable to find the target xplat//yoga/java:java.
'xplat//yoga/java:java' references an unknown cell.
```

<details>
buck fetch ReactAndroid/src/test/...
2018-05-16 21:19:44,321 [WARNING][buck_tool.py:402] Not using buckd because watchman isn't installed.
Picked up _JAVA_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
BUILD FAILED: //ReactAndroid/src/test/java/com/facebook/react/fabric:fabric: parameter 'deps': Unable to find the target xplat//yoga/java:java.
'xplat//yoga/java:java' references an unknown cell.
Exited with code 1
</details>

### ~Gradle dependencies fail to download~

Once the issue above is fixed, the following issue is uncovered. It's related to the recent bump to build tools v26.

<details>
./scripts/circleci/gradle_download_deps.sh
Picked up _JAVA_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
Download https://jcenter.bintray.com/com/facebook/fresco/fresco/1.9.0/fresco-1.9.0.pom
Download https://jcenter.bintray.com/com/facebook/fresco/imagepipeline-okhttp3/1.9.0/imagepipeline-okhttp3-1.9.0.pom
Download https://jcenter.bintray.com/com/squareup/okhttp3/okhttp/3.10.0/okhttp-3.10.0.pom
Download https://jcenter.bintray.com/com/squareup/okhttp3/parent/3.10.0/parent-3.10.0.pom
Download https://jcenter.bintray.com/com/squareup/okhttp3/okhttp-urlconnection/3.10.0/okhttp-urlconnection-3.10.0.pom
Download https://jcenter.bintray.com/com/squareup/okio/okio/1.14.0/okio-1.14.0.pom
Download https://jcenter.bintray.com/com/squareup/okio/okio-parent/1.14.0/okio-parent-1.14.0.pom
Download https://jcenter.bintray.com/com/facebook/fresco/fbcore/1.9.0/fbcore-1.9.0.pom
Download https://jcenter.bintray.com/com/facebook/fresco/drawee/1.9.0/drawee-1.9.0.pom
Download https://jcenter.bintray.com/com/facebook/fresco/imagepipeline/1.9.0/imagepipeline-1.9.0.pom
Download https://jcenter.bintray.com/com/facebook/fresco/imagepipeline-base/1.9.0/imagepipeline-base-1.9.0.pom

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':ReactAndroid'.
> Failed to notify project evaluation listener.
   > Could not resolve all dependencies for configuration ':ReactAndroid:_debugPublishCopy'.
      > Could not find com.android.support:appcompat-v7:26.0.2.
        Required by:
            react-native:ReactAndroid:unspecified
   > Could not resolve all dependencies for configuration ':ReactAndroid:compile'.
      > Could not find com.android.support:appcompat-v7:26.0.2.
        Required by:
            react-native:ReactAndroid:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.005 secs
Exited with code 1
</details>

### ~Android test app fails to build~

`buck build ReactAndroid/src/main/java/com/facebook/react/shell` is [failing](https://circleci.com/gh/hramos/react-native/2156) after the bump to SDK 26:

```
Build failed: Command failed with exit code 1.
stderr: Fatal Error: Unable to find package java.lang in classpath or bootclasspath

    When running <javac>.
    When building rule //ReactAndroid/src/main/java/com/facebook/react/module/model:model.
```

### ~Android e2e tests fail~

Related to https://github.com/facebook/react-native/pull/18995#pullrequestreview-118398614

## Environment

Circle CI.

**Comment by hramos** [comment]
This failure was introduced in c10c6dbf7c808b4f69007f297afea7d6f3522612, specifically [L15](https://github.com/facebook/react-native/commit/c10c6dbf7c808b4f69007f297afea7d6f3522612#diff-2f2a855c488bca0f1213003a848731faR15).

**Comment by hramos** [comment]
I've opened an internal diff to address the Fabric/Yoga failure, and I've updated the original issue description with a new failure this has uncovered.

**Comment by hramos** [comment]
`test_android` is still failing. Will be rolling back to 23 shortly.

**Comment by hramos** [comment]
API 26 reverted in https://github.com/facebook/react-native/commit/3e0ebc76632238f21c60caa92c7a2b5ee8102b71

**Comment by hramos** [comment]
Now that the JavaScript issues have been resolved, the following error has surfaced:

```
TESTING //ReactAndroid/src/test/java/com/facebook/react/animated:animated //ReactAndroid/src/test/java/com/facebook/react/bridge:bridge //ReactAndroid/src/test/java/com/facebook/react/devsupport:devsupport //ReactAndroid/src/test/java/com/facebook/react/modules:modules //ReactAndroid/src/test/java/com/facebook/react/packagerconnection:packagerconnection //ReactAndroid/src/test/java/com/facebook/react/uimanager:uimanager //ReactAndroid/src/test/java/com/facebook/react/views:views //ReactAndroid/src/test/java/com/facebook/react:react
UNKNOWN ERROR: Path buck-out/bin/ReactAndroid/src/main/libraries/fresco/fresco-react-native/__unpack_fbcore#aar_unzip__/res is needed to run robolectric test //ReactAndroid/src/test/java/com/facebook/react/animated:animated, but was not found.
java.lang.RuntimeException: Path buck-out/bin/ReactAndroid/src/main/libraries/fresco/fresco-react-native/__unpack_fbcore#aar_unzip__/res is needed to run robolectric test //ReactAndroid/src/test/java/com/facebook/react/animated:animated, but was not found.
	at com.facebook.buck.android.RobolectricTest.lambda$11(RobolectricTest.java:282)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.buck.android.RobolectricTest.getDirs(RobolectricTest.java:294)
	at com.facebook.buck.android.RobolectricTest.getDirectoriesContent(RobolectricTest.java:262)
	at com.facebook.buck.android.RobolectricTest.addPreTestSteps(RobolectricTest.java:172)
	at com.facebook.buck.jvm.java.JavaTest.runTests(JavaTest.java:305)
	at com.facebook.buck.cli.TestRunning.runTests(TestRunning.java:275)
	at com.facebook.buck.cli.TestCommand.runTestsInternal(TestCommand.java:327)
	at com.facebook.buck.cli.TestCommand.runWithoutHelp(TestCommand.java:663)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:236)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:79)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:1123)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:407)
	at com.facebook.buck.cli.Main.main(Main.java:1823)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.buck.cli.bootstrapper.ClassLoaderBootstrapper.main(ClassLoaderBootstrapper.java:55)
Exited with code 10
```

See https://circleci.com/gh/facebook/react-native/44015
