### ISSUE TITLE
Couldn't install App on device

### ISSUE THREAD

**Issue by VivekHA** [facebook/react-native#19324]
Hello,

I'm new to react-native.
When i try to run a simple react native app from visual studio code i get below error message.
Scanning folders for symlinks in C:\Projects\MobApp\Project2\sampleapplication\node_modules (286ms)
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Downloading https://services.gradle.org/distributions/gradle-2.14.1-all.zip

Exception in thread "main" java.net.UnknownHostException: services.gradle.org
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at com.sun.net.ssl.internal.ssl.SSLSocketImpl.connect(Unknown Source)
        at com.sun.net.ssl.internal.ssl.BaseSSLSocketImpl.connect(Unknown Source)
        at sun.net.NetworkClient.doConnect(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:59)
        at org.gradle.wrapper.Install$1.call(Install.java:46)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:46)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

After searching in net i found this solution
 **chmod 755 android/gradlew**
if i run this in terminal i get this error message : 'chmod' is not recognized as an internal or external command,
operable program or batch file.
I have made sure that emulate is running which i got it from installing android studio.

Thanks for your answer

**Comment by VivekHA** [comment]
hello,
Please find below the result after running react-native info

Environment:
  OS: Windows 7
  Node: 9.11.1
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

**Comment by jianglinchun** [comment]
`Downloading https://services.gradle.org/distributions/gradle-2.14.1-all.zip

Exception in thread "main" java.net.UnknownHostException: services.gradle.org`

Please run the following command in terminal.

nslookup services.gradle.org

And you'll find the reason.

**Comment by hunterway55** [comment]
have you opened android studio and synced Gradel dependencies?

**Comment by VivekHA** [comment]
@jianglinchun after running nslookup i got below message:
DNS request timed out.
    timeout was 2 seconds.
*** xxxxx can't find services.gradle.org: Non-existent domain

I also downloaded the file like you told and copied to my project folder and i still get the same error message.Please let me know if i have to copy this zip file to a specific location. 

@hunterway55 : yes its synced

Thanks
