### ISSUE TITLE
Android: Unexpected token '.' (http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:88794) at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)

### ISSUE THREAD

**Issue by harrybui2804** [facebook/react-native#19350]
![screenshot_1526690985](https://user-images.githubusercontent.com/39423618/40263567-81247a02-5b3e-11e8-8d53-58b093d4e586.png)

package.json

> {
  "name": "Simple",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-actionsheet": "^2.4.2",
    "react-native-communications": "^2.2.1",
    "react-native-device-info": "^0.21.5",
    "react-native-fbsdk": "^0.7.0",
    "react-native-fcm": "^15.0.0",
    "react-native-google-maps-services": "^0.5.1",
    "react-native-huawei-protected-apps": "^0.1.7",
    "react-native-image-crop-picker": "^0.20.1",
    "react-native-root-toast": "^1.3.0",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.0.1"
  },
  "devDependencies": {
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.3",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }

> }

Error log

> 05-19 01:26:21.529 15124-15142/com.harrybui.simple E/FA: Discarding data. Failed to send app launch
05-19 01:26:21.530 15124-15142/com.harrybui.simple E/FA: Failed to get app instance id
05-19 01:26:21.530 15124-15142/com.harrybui.simple E/FA: Discarding data. Failed to send event to service
05-19 01:26:21.530 15124-15142/com.harrybui.simple E/FA: Failed to send current screen to service
05-19 01:26:24.748 15124-15209/com.harrybui.simple E/ReactNativeJNI: Got JS Exception: Unexpected token '.' (http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:88796)
05-19 01:26:24.749 15124-15209/com.harrybui.simple E/unknown:ReactNative: Exception in native call from JS
                                                                           com.facebook.react.devsupport.JSException: Unexpected token '.' (http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:88796)
                                                                               at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
                                                                               at java.lang.Thread.run(Thread.java:761)
                                                                            Caused by: com.facebook.jni.CppException: Unexpected token '.' (http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false:88796)
                                                                               at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                               at android.os.Handler.handleCallback(Handler.java:751) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                               at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
                                                                               at android.os.Looper.loop(Looper.java:154) 
                                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
                                                                               at java.lang.Thread.run(Thread.java:761) 
05-19 01:26:24.751 15124-15209/com.harrybui.simple E/unknown:ReactNative: Exception in native call
                                                                           java.lang.RuntimeException: Error calling AppRegistry.runApplication
                                                                               at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
                                                                               at java.lang.Thread.run(Thread.java:761)
                                                                            Caused by: com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
                                                                               at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                               at android.os.Handler.handleCallback(Handler.java:751) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                               at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
                                                                               at android.os.Looper.loop(Looper.java:154) 
                                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
                                                                               at java.lang.Thread.run(Thread.java:761) 
05-19 01:26:31.548 15124-15142/com.harrybui.simple E/FA: Discarding data. Failed to send event to service

I run command 
`adb reverse tcp:8081 tcp:8081 & react-native run-android`
then it worked on debug but when build release apk, app crashed

**Comment by xelop** [comment]
Im getting the same error but on index.android.bundle

**Comment by vance-liu** [comment]
same error! How to fix this?

**Comment by nikkwong** [comment]
Same error—showstopper. Would love some assistance, please.

**Comment by harrybui2804** [comment]
I'm fixed this issues
this error of `react-native-google-maps-services` 
1. change index.js in `node_modules/react-native-google-maps-services/lib/index.js`
`exports.createClient = function(options)`
to 
`export function createClient(options)`
2. using it
```
import {createClient} from 'react-native-google-maps-services'
var googleMapsClient = createClient({
  key: 'your API key'
});
```
if you using `google-maps-services-js`, you can fix as same

**Comment by martincarrera** [comment]
Any fix, update, workaround, something that could help prevent this issue?

Thanks!

**Comment by Ankarrr** [comment]
I encounter the error too. Then I start "Remote JS Debugging" and the error disappear.

**Comment by Rafolo78** [comment]
Same error here. Anyone solved this?

**Comment by pablen** [comment]
As I understand it, the root of these sort of problems is explained [here](https://facebook.github.io/react-native/docs/javascript-environment).

More specifically when it says (bold is mine):

> When using React Native, you're going to be running your JavaScript code **in two environments**:
> - In most cases, React Native will use JavaScriptCore, the JavaScript engine that powers Safari. [...]
> - When using Chrome debugging, all JavaScript code runs within Chrome itself, [...]. Chrome uses V8 as its JavaScript engine.
>
> While both environments are very similar, **you may end up hitting some inconsistencies**. 

So, the confusing part about getting an error if the debugger is closed and not getting it when the debugger is running may be explained by that.

Also consider the syntax error is found **by the JavaScript engine itself in the bundle and not by the compiler/bundler in your source code**, so that is the reason why the line number mentioned in the error message might not correspond to any of your source files. I think in general these errors are caused by some dependency package not being strictly transpiled ES5 code, so it will run in some environments and not in others.

What I've found useful in such scenarios is generating the bundle manually running something like

```
react-native bundle \
    --platform android \
    --dev true \
    --entry-file index.js \
    --bundle-output android-debug.bundle \
    --sourcemap-output android-debug.bundle.map
```

And then in the generated `android-debug.bundle` file looking at the line number mentioned in the error message (88794 in the OP screenshot). There you should find the offending code.

**Comment by xhirazi** [comment]
@pablen more details please
after running this command  it says 'Assets destination folder is not set'

**Comment by duycoder** [comment]
I upgraded "react-native-elements" from "0.19.0" to "1.10" then i had this problem. I had revert back to "0.19.0" then my app works fine. I did as @pablen said, but i still not found the problem.
