### ISSUE TITLE
react-native init command fails with unhandled error for numeric name

### ISSUE THREAD

**Issue by ruslan-bikkinin** [facebook/react-native#19473]
- [x] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [x] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [x] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

`react-native init` fails with unhandled error for numeric name.

## Environment

**react-native-cli: 2.0.1**

Environment:
  OS: Linux 4.13
  Node: 9.11.1
  Yarn: 1.7.0
  npm: 5.10.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

## Steps to Reproduce

Run `react-native init 123` in terminal.

## Expected Behavior

CLI gracefully stops and prompts
```shell
"123" is not a valid name for a project. Please use a valid identifier name (alphanumeric).
```

## Actual Behavior
```shell
rbikkinin@rbikkinin-work:~$ react-native init 123
/home/rbikkinin/.nvm/versions/node/v9.11.1/lib/node_modules/react-native-cli/index.js:168
  if (!name.match(/^[$A-Z_][0-9A-Z_$]*$/i)) {
            ^

TypeError: name.match is not a function
    at validateProjectName (/home/rbikkinin/.nvm/versions/node/v9.11.1/lib/node_modules/react-native-cli/index.js:168:13)
    at init (/home/rbikkinin/.nvm/versions/node/v9.11.1/lib/node_modules/react-native-cli/index.js:195:3)
    at Object.<anonymous> (/home/rbikkinin/.nvm/versions/node/v9.11.1/lib/node_modules/react-native-cli/index.js:153:7)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
```

**Comment by ruslan-bikkinin** [comment]
Hi again, I have updated my issue with all lacked info. Please let me know whether you need any more clarifications from my side.

**Comment by Glassay** [comment]
i got the same issue when i use `react-native init aa-bb`,have you fixed that?

**Comment by ruslan-bikkinin** [comment]
The issue is still persist.

**Comment by ruslan-bikkinin** [comment]
The issue is still persist.

**Comment by ruslan-bikkinin** [comment]
Just tested on 2.0.2, issue seems to be resolved.

**Comment by hakkikonu** [comment]
`[$A-Z_][0-9A-Z_$]` is the issue. Obey this name pattern
