### ISSUE TITLE
Need help in Crash log reporting on react native

### ISSUE THREAD

**Issue by GargManish** [facebook/react-native#19488]
## Actual Behavior
We are trying to integrate Crashlytic in our application (on React Native platform). It's providing complete log traces for the native side but we are facing issue in capturing JS originated exceptions. It's capturing JS exception but not providing complete information to find the crash location, file name etc.

We are getting following logs:

Fatal Exception: com.facebook.react.common.JavascriptException: undefined is not an object (evaluating '(void 0).message'), stack:
value@306:637
touchableHandlePress@165:2877
_performSideEffectsForTransition@167:8505
_receiveSignal@167:7292
touchableHandleResponderRelease@167:4757
<unknown>@165:3277
g@41:296
invokeGuardedCallback@41:519
invokeGuardedCallbackAndCatchFirstError@41:634
A@41:2433
D@41:3195
U@41:2992
<unknown>@41:15520
batchedUpdates@41:135761
Ie@41:14871
ze@41:15366
receiveTouches@41:16203
value@18:3582
<unknown>@18:1067
value@18:3009
value@18:1039

       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:164)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:764)
So it's not providing information in which class, line number and method this exception has occurred.

I have tried to integrate react-native-fabric and react-native-fabric-crashlytic but still no luck.

There is one more issue in crashlytic, all JS crashes are collating as single type of issues although issues had occurred on different lines.

ExceptionsManagerModule.java line 54#2com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError |   | 1.0 (1) | 9CRASHES | 1USER
-- | -- | -- | -- | --

**Comment by GargManish** [comment]
Yes all relevant information has been added
