### ISSUE TITLE
Error on react-native init app inside a lerna package

### ISSUE THREAD

**Issue by renatonmendes** [facebook/react-native#19537]
Environment
MacOS High Sierra
node V10.3.0
lerna 2.11.0
yarn 1.6.0

## Description
I'm trying to create a new react native application inside a lerna package structure, but I'm getting the following error:

`
```
$ react-native init app
This will walk you through creating a new React Native project in /Volumes/dev/workspace/amplifactory/packages/app
Using yarn v1.6.0
Installing react-native...
yarn add v1.6.0
(node:3689) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "workspace-aggregator-8ea62db7-5bb7-4a68-a0d4-fdec926563d9 > @monorepo/admin > babel-loader@7.1.4" has unmet peer dependency "babel-core@6".
warning "workspace-aggregator-8ea62db7-5bb7-4a68-a0d4-fdec926563d9 > @monorepo/admin > babel-preset-react-app@3.1.1" has unmet peer dependency "babel-runtime@^6.23.0".
warning "workspace-aggregator-8ea62db7-5bb7-4a68-a0d4-fdec926563d9 > @monorepo/admin > eslint-config-react-app@2.1.0" has incorrect peer dependency "babel-eslint@^7.2.3".
warning "workspace-aggregator-8ea62db7-5bb7-4a68-a0d4-fdec926563d9 > @monorepo/ux > react-datetime@2.14.0" has unmet peer dependency "moment@>=2.16.0".
warning "react-native > eslint-plugin-react-native@3.2.1" has unmet peer dependency "eslint@^3.17.0 || ^4.0.0".
warning " > react-native@0.55.4" has unmet peer dependency "react@16.3.1".
[4/4] 📃  Building fresh packages...
success Saved 7 new dependencies.
info Direct dependencies
info All dependencies
├─ @monorepo/admin@3.0.0
├─ @monorepo/auth@3.0.0
├─ @monorepo/boffice@3.0.0
├─ @monorepo/graphqlserver@3.0.0
├─ @monorepo/studio@3.0.0
├─ app@0.0.1
└─ react-native@0.55.4
✨  Done in 8.38s.
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '/Volumes/dev/workspace/amplifactory/packages/app/node_modules/react-native/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at checkNodeVersion (/usr/local/lib/node_modules/react-native-cli/index.js:306:21)
    at run (/usr/local/lib/node_modules/react-native-cli/index.js:300:3)
    at createProject (/usr/local/lib/node_modules/react-native-cli/index.js:249:3)
    at init (/usr/local/lib/node_modules/react-native-cli/index.js:200:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:153:7)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
`

```
## Steps to Reproduce
Build a lerna package from scratch, add a simple ReactJs package and then try to create a react-native app.

## Expected Behavior
No errors. I expect to use react-native package inside the lerna package.

## Actual Behavior
See error above.

EDIT:

I've created the app package outside lerna, then moved to lerna packages folder and changed the package.json file:

```
{
  "name": "@monorepo/app",
  "version": "3.0.0",
  "private": true,
  "scripts": {
    "start-dev": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.4"
  },
  "devDependencies": {
    "babel-jest": "23.0.1",
    "babel-preset-react-native": "4.0.0",
    "jest": "23.1.0",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

Issued install (lerna uses yarn):
`$ yarn install 
`
The trying to run I got the following error:
![image](https://user-images.githubusercontent.com/10373990/40867885-36c32a30-65de-11e8-8819-59bc672b64ae.png)

**Comment by 6pm** [comment]
Why it's closed? Looks like it is problem with symlinks. It haven't resolved yet. 
Facebook team please remove `react-native-bot` it is useless.
