### ISSUE TITLE
Getting error while creating a new Project

### ISSUE THREAD

**Issue by PawanManjani** [facebook/react-native#19638]
- [review ] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ yes] Use the latest React Native version: https://github.com/facebook/react-native/releases
  - [did it ] Run `react-native info` in your terminal and paste its contents under "Environment"
  - [x] Let us know how to reproduce the issue. Include a code sample, share a project, or
    share an app that reproduces the issue using https://snack.expo.io/

## Description

issue coming while creating new project 
## Actual Behavior

c:\ReactNativeProjects>react-native init AwesomeProject
This will walk you through creating a new React Native project in c:\ReactNative
Projects\AwesomeProject
Installing react-native...
Consider installing yarn to make this faster: https://yarnpkg.com
{ Error: spawnSync C:\Program Files\Java\jdk1.7.0_51 ENOENT
    at _errnoException (util.js:992:11)
    at spawnSync (child_process.js:579:20)
    at execSync (child_process.js:635:13)
    at run (C:\Users\abc\AppData\Roaming\npm\node_modules\react-native-cli\index
.js:294:5)
    at createProject (C:\Users\abc\AppData\Roaming\npm\node_modules\react-native
-cli\index.js:249:3)
    at init (C:\Users\abc\AppData\Roaming\npm\node_modules\react-native-cli\inde
x.js:200:5)
    at Object.<anonymous> (C:\Users\abc\AppData\Roaming\npm\node_modules\react-n
ative-cli\index.js:153:7)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawnSync C:\\Program Files\\Java\\jdk1.7.0_51',
  path: 'C:\\Program Files\\Java\\jdk1.7.0_51',
  spawnargs:
   [ '/d',
     '/s',
     '/c',
     '"npm install --save --save-exact react-native"' ],
  cmd: 'npm install --save --save-exact react-native',
  file: 'C:\\Program Files\\Java\\jdk1.7.0_51',
  args:
   [ 'C:\\Program Files\\Java\\jdk1.7.0_51',
     '/d',
     '/s',
     '/c',
     '"npm install --save --save-exact react-native"' ],
  options:
   { stdio: [ [Object], [Object], [Object] ],
     shell: true,
     windowsVerbatimArguments: true,
     file: 'C:\\Program Files\\Java\\jdk1.7.0_51',
     args:
      [ 'C:\\Program Files\\Java\\jdk1.7.0_51',
        '/d',
        '/s',
        '/c',
        '"npm install --save --save-exact react-native"' ],
     envPairs:
      [ 'ALLUSERSPROFILE=C:\\ProgramData',
        'APPDATA=C:\\Users\\abc\\AppData\\Roaming',
        'ChocolateyInstall=C:\\ProgramData\\chocolatey',
        'ChocolateyLastPathUpdate=Sun May 20 16:56:46 2018',
        'CLASSPATH=.;',
        'CommonProgramFiles=C:\\Program Files\\Common Files',
        'CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files',
        'CommonProgramW6432=C:\\Program Files\\Common Files',
        'COMPUTERNAME=SONIYA',
        'ComSpec=C:\\Program Files\\Java\\jdk1.7.0_51',
        'FP_NO_HOST_CHECK=NO',
        'HOMEDRIVE=C:',
        'HOMEPATH=\\Users\\abc',
        'JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_172',
        'LOCALAPPDATA=C:\\Users\\abc\\AppData\\Local',
        'LOGONSERVER=\\\\SONIYA',
        'NUMBER_OF_PROCESSORS=4',
        'OS=Windows_NT',
        'Path=C:\\Users\\abc\\AppData\\Roaming\\npm;C:\\Program Files\\nodejs\\;
C:\\Program Files (x86)\\Microsoft SQL Server\\100\\Tools\\Binn\\;C:\\Program Fi
les (x86)\\Microsoft SQL Server\\100\\DTS\\Binn\\;C:\\Program Files (x86)\\Micro
soft SQL Server\\100\\Tools\\Binn\\VSShell\\Common7\\IDE\\;C:\\Program Files (x8
6)\\Microsoft SQL Server\\90\\Tools\\binn\\;C:\\Program Files (x86)\\Yarn\\bin\\
;C:\\Program Files\\nodejs\\npm;C:\\Users\\abc\\AppData\\Roaming\\npm;C:\\Users\
\abc\\AppData\\Local\\Yarn\\bin;C:\\ProgramData\\chocolatey\\bin',
        'PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC',
        'PROCESSOR_ARCHITECTURE=AMD64',
        'PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
',
        'PROCESSOR_LEVEL=6',
        'PROCESSOR_REVISION=3a09',
        'ProgramData=C:\\ProgramData',
        'ProgramFiles=C:\\Program Files',
        'ProgramFiles(x86)=C:\\Program Files (x86)',
        'ProgramW6432=C:\\Program Files',
        'PROMPT=$P$G',
        'PSModulePath=C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\'
,
        'PUBLIC=C:\\Users\\Public',
        'SESSIONNAME=Console',
        'SystemDrive=C:',
        'SystemRoot=C:\\Windows',
        'TEMP=C:\\Users\\abc\\AppData\\Local\\Temp',
        'TMP=C:\\Users\\abc\\AppData\\Local\\Temp',
        'USERDOMAIN=SONIYA',
        'USERNAME=abc',
        'USERPROFILE=C:\\Users\\abc',
        'VBOX_INSTALL_PATH=C:\\Program Files\\Oracle\\VirtualBox\\',
        'VS110COMNTOOLS=C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\C
ommon7\\Tools\\',
        'windir=C:\\Windows' ],
     killSignal: undefined },
  envPairs:
   [ 'ALLUSERSPROFILE=C:\\ProgramData',
     'APPDATA=C:\\Users\\abc\\AppData\\Roaming',
     'ChocolateyInstall=C:\\ProgramData\\chocolatey',
     'ChocolateyLastPathUpdate=Sun May 20 16:56:46 2018',
     'CLASSPATH=.;',
     'CommonProgramFiles=C:\\Program Files\\Common Files',
     'CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files',
     'CommonProgramW6432=C:\\Program Files\\Common Files',
     'COMPUTERNAME=SONIYA',
     'ComSpec=C:\\Program Files\\Java\\jdk1.7.0_51',
     'FP_NO_HOST_CHECK=NO',
     'HOMEDRIVE=C:',
     'HOMEPATH=\\Users\\abc',
     'JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_172',
     'LOCALAPPDATA=C:\\Users\\abc\\AppData\\Local',
     'LOGONSERVER=\\\\SONIYA',
     'NUMBER_OF_PROCESSORS=4',
     'OS=Windows_NT',
     'Path=C:\\Users\\abc\\AppData\\Roaming\\npm;C:\\Program Files\\nodejs\\;C:\
\Program Files (x86)\\Microsoft SQL Server\\100\\Tools\\Binn\\;C:\\Program Files
 (x86)\\Microsoft SQL Server\\100\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsof
t SQL Server\\100\\Tools\\Binn\\VSShell\\Common7\\IDE\\;C:\\Program Files (x86)\
\Microsoft SQL Server\\90\\Tools\\binn\\;C:\\Program Files (x86)\\Yarn\\bin\\;C:
\\Program Files\\nodejs\\npm;C:\\Users\\abc\\AppData\\Roaming\\npm;C:\\Users\\ab
c\\AppData\\Local\\Yarn\\bin;C:\\ProgramData\\chocolatey\\bin',
     'PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC',
     'PROCESSOR_ARCHITECTURE=AMD64',
     'PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 58 Stepping 9, GenuineIntel',
     'PROCESSOR_LEVEL=6',
     'PROCESSOR_REVISION=3a09',
     'ProgramData=C:\\ProgramData',
     'ProgramFiles=C:\\Program Files',
     'ProgramFiles(x86)=C:\\Program Files (x86)',
     'ProgramW6432=C:\\Program Files',
     'PROMPT=$P$G',
     'PSModulePath=C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\',
     'PUBLIC=C:\\Users\\Public',
     'SESSIONNAME=Console',
     'SystemDrive=C:',
     'SystemRoot=C:\\Windows',
     'TEMP=C:\\Users\\abc\\AppData\\Local\\Temp',
     'TMP=C:\\Users\\abc\\AppData\\Local\\Temp',
     'USERDOMAIN=SONIYA',
     'USERNAME=abc',
     'USERPROFILE=C:\\Users\\abc',
     'VBOX_INSTALL_PATH=C:\\Program Files\\Oracle\\VirtualBox\\',
     'VS110COMNTOOLS=C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\Comm
on7\\Tools\\',
     'windir=C:\\Windows' ],
  stderr: null,
  stdout: null,
  pid: 0,
  output: null,
  signal: null,
  status: null,
  error: null }
Command `npm install --save --save-exact react-native` failed.

**Comment by PawanManjani** [comment]
Updated plz check.

**Comment by PawanManjani** [comment]
F:\DATA\ReactNativeProjects\AwesomeProject>react-native info
Command `info` unrecognized. Make sure that you have run `npm install` and that
you are inside a react-native project.
