### ISSUE TITLE
react-native : Unable to resolve module `tty` from ''…/node_modules/window-size/index.js": Module does not exist in the module map

### ISSUE THREAD

**Issue by hiyale** [facebook/react-native#19649]
## For Discussion
"react": "^16.3.0-alpha.1",
    "react-native": "0.54.3",
![1528709422579](https://user-images.githubusercontent.com/4327473/41224874-0c13af66-6da0-11e8-86d3-0847e541be46.jpg)

删除node_modules，清除缓存，电脑重启，xcode-clean，都试过，仍然报错。
react-native init 一个初始化项目可以正常启动。没有出现Unable to resolve module `tty` 这种错误。

loading dependency graph, done.
    error: bundling failed: Error: Unable to resolve module `tty` from `/MyWorks/rnTestTrials/myCurrencySample/node_modules/window-size/index.js`: Module does not exist in the module map

    This might be related to https://github.com/facebook/react-native/issues/4968
    To resolve try the following:
      1. Clear watchman watches: `watchman watch-del-all`.
      2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
      3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  
      4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
        at ModuleResolver.resolveDependency (/MyWorks/rnTestTrials/myCurrencySample/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:1476)
        at ResolutionRequest.resolveDependency (/MyWorks/rnTestTrials/myCurrencySample/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:92:16)
        at DependencyGraph.resolveDependency (/MyWorks/rnTestTrials/myCurrencySample/node_modules/metro/src/node-haste/DependencyGraph.js:271:4465)
        at dependencies.map.relativePath (/MyWorks/rnTestTrials/myCurrencySample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:379:19)
        at Array.map (<anonymous>)
        at resolveDependencies (/MyWorks/rnTestTrials/myCurrencySample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:378:16)
        at /MyWorks/rnTestTrials/myCurrencySample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:203:33
        at Generator.next (<anonymous>)
        at step (/MyWorks/rnTestTrials/myCurrencySample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:307)
        at /MyWorks/rnTestTrials/myCurrencySample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:467
     BUNDLE  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓░░░░░░░ 60.2% (291/375), failed.

**Comment by hiyale** [comment]
1. find node_modules -> delete window-size。
2. close the metro bundler window， run "react-native run-android or ios" again
3. the metro bundler should through an error, the error will show exactly which file in your project has a problem,  find it, delete that line of code
4. put back the window-size folder
5. run "react-native run-android or ios" again.

**Comment by hramos** [comment]
Flagging improper use of the Discussion label.

**Comment by aminekharrez** [comment]
Any update please concerning this issue.

I am getting nearly the same problem here 

> ERROR in ./node_modules/pace/node_modules/charm/index.js
> Module not found: Error: Can't resolve 'tty' in '/workspace/node_modules/pace/node_modules/charm'
