### ISSUE TITLE
View Has Same ID Issue in Scroll View

### ISSUE THREAD

**Issue by shahjahank02** [facebook/react-native#19731]
## Environment
  OS: macOS High Sierra 10.13.3
  Node: 8.8.1
  Yarn: Not Found
  npm: 5.8.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617

## Packages
  react: 16.2.0 => 16.2.0
  react-native: 0.54.4 => 0.54.4

## Logs
``` 
Fatal Exception: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.widget.ScrollView$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/0x43. Make sure other views do not use the same id.
       at android.view.View.onRestoreInstanceState(View.java:13659)
       at android.view.View.dispatchRestoreInstanceState(View.java:13635)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2896)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2896)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2896)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2896)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2896)
       at android.view.View.restoreHierarchyState(View.java:13613)
       at android.support.v4.app.Fragment.restoreViewState(Fragment.java:510)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1445)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
       at android.support.v4.app.BackStackRecord.executePopOps(BackStackRecord.java:857)
       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2577)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
       at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5253)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708)
```
## Reproducible Demo
I have two page with Scroll View and i am coming back from other screen to First screen pacing this issue.

**Comment by kelset** [comment]
Closing as stale. Please open a new issue if issue still occur.
