### ISSUE TITLE
Unbundled error: JSException Can't find variable: self

### ISSUE THREAD

**Issue by haggholm** [facebook/react-native#19744]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment

```
Environment:
  OS: Linux 4.15
  Node: 10.4.0
  Yarn: Not Found
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1
  react-native: ^0.55.0 => 0.55.4
```

## Description

I followed the instructions to unbundle JS modules (https://facebook.github.io/react-native/docs/next/performance.html) and deployed a production bundle to an Android device. The app immediately redscreens with

```
06-15 10:09:46.981 2165-2225/? E/AndroidRuntime: FATAL EXCEPTION: mqt_js
    Process: co.elk.rn, PID: 2165
    java.lang.RuntimeException: com.facebook.react.devsupport.JSException: Can't find variable: self (index.android.bundle:1)
        at com.facebook.react.bridge.DefaultNativeModuleCallExceptionHandler.handleException(DefaultNativeModuleCallExceptionHandler.java:22)
        at com.facebook.react.devsupport.DisabledDevSupportManager.handleException(DisabledDevSupportManager.java:170)
        at com.facebook.react.bridge.CatalystInstanceImpl.onNativeException(CatalystInstanceImpl.java:511)
        at com.facebook.react.bridge.CatalystInstanceImpl.access$900(CatalystInstanceImpl.java:39)
        at com.facebook.react.bridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:527)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
        at android.os.Looper.loop(Looper.java:154)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:762)
     Caused by: com.facebook.react.devsupport.JSException: Can't find variable: self (index.android.bundle:1)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:154) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
        at java.lang.Thread.run(Thread.java:762) 
     Caused by: com.facebook.jni.CppException: Can't find variable: self (index.android.bundle:1)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
        at android.os.Looper.loop(Looper.java:154) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
        at java.lang.Thread.run(Thread.java:762) 
```

Unfortunately, with proprietary code, I don’t presently have a minimal example. Any hints or clues how to pursue this issue would be welcome.

**Comment by casseds2** [comment]
Was this ever resolved? Having similar issues!

**Comment by haggholm** [comment]
Well, with no activity here, I hadn’t retried it because I assumed that it was still broken… It seems to be working now with react-native v0.57.1.

**Comment by dulmandakh** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy
