### ISSUE TITLE
NoSuchKeyException Thrown From ReadableNativeMap

### ISSUE THREAD

**Issue by Bhavik-P** [facebook/react-native#19793]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 10.3.0
  Yarn: Not Found
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.2 => 16.3.2
  react-native: 0.55.4 => 0.55.4

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.

After we recently upgraded our React Native package to 0.55.4, I’ve started to notice an Android-specific bug that is hit from within the library. Hundreds of our users hit this error daily. The bug is thrown in ReadableNativeMap:122 because the app is trying to look for a key with name “toValue” however it’s not in the config - FrameBasedAnimationDriver.java:44. We generally see this happening on slower devices, but it’s not limited to slower devices. We’ve seen majority of the events happen on these devices:
LG K20 Plus LGMP260
Samsung Galaxy S7 - SM-G930V
ZTE Blade™ Z MAX Z982

The only way I am able to recreate it on my own is by adding a debugger in the native code as the app is launching and then pressing continue to step out of debugging mode. For example, I make a call to load my in-app products by calling querySkuDetailsAsync at the start on the app. Within the onSkuDetailsResponse function, I add a debugger. After the debugger is hit and I press continue, the error is recreated. This leads me to believe it is a timing issue (race condition).

Here is the stacktrace:

```
06-18 19:26:55.111 7871-7871/app.hurdlr.com E/unknown:ReactNative: Exception in native call
    com.facebook.react.bridge.NoSuchKeyException: toValue
    	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:122)
    	at com.facebook.react.bridge.ReadableNativeMap.getDouble(ReadableNativeMap.java:147)
    	at com.facebook.react.animated.FrameBasedAnimationDriver.resetConfig(FrameBasedAnimationDriver.java:44)
    	at com.facebook.react.animated.FrameBasedAnimationDriver.<init>(FrameBasedAnimationDriver.java:31)
    	at com.facebook.react.animated.NativeAnimatedNodesManager.startAnimatingNode(NativeAnimatedNodesManager.java:204)
    	at com.facebook.react.animated.NativeAnimatedModule$13.execute(NativeAnimatedModule.java:296)
    	at com.facebook.react.animated.NativeAnimatedModule$3.execute(NativeAnimatedModule.java:150)
    	at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:512)
    	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:821)
    	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:928)
    	at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:46)
    	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:988)
    	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
    	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
    	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:872)
    	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:618)
    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
    	at android.os.Handler.handleCallback(Handler.java:751)
    	at android.os.Handler.dispatchMessage(Handler.java:95)
    	at android.os.Looper.loop(Looper.java:154)
    	at android.app.ActivityThread.main(ActivityThread.java:6119)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

```
Tech spec:
React Native Version: 0.55.4
Node version: 10.3.0
Npm version: 6.1.0
Simulator Details:
	Nexus 5X v5.2
Android 7.1.1 x86
API 25
1536 mb RAM
256 mb VM Heap
```

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

It is incredibly difficult to reproduce however I was able to reproduce it by following the steps above.
I have a video of the bug linked at:
https://drive.google.com/open?id=1vdLHwSbgPalyjTO_MMLwKK4t3vpP26_T

**Comment by Bhavik-P** [comment]
Possible fix at https://github.com/facebook/react-native/pull/19808
