### ISSUE TITLE
Error while running react-native run-android

### ISSUE THREAD

**Issue by webtids** [facebook/react-native#19802]
C:\Users\hp\myname>react-native run-android
Scanning folders for symlinks in C:\Users\hp\zazzy\zazzy\node_modules (616ms)
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Unzipping C:\Users\hp\.gradle\wrapper\dists\gradle-2.14.1-all\8bnwg5hd3w55iofp58khbp6yv\gradle-2.14.1-all.zip to C:\Users\hp\.gradle\wrapper\dists\gradle-2.14.1-all\8bnwg5hd3w55iofp58khbp6yv
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.zip.ZipFile.<init>(ZipFile.java:169)
        at org.gradle.wrapper.Install.unzip(Install.java:159)
        at org.gradle.wrapper.Install.access$500(Install.java:26)
        at org.gradle.wrapper.Install$1.call(Install.java:69)
        at org.gradle.wrapper.Install$1.call(Install.java:46)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:46)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd.exe ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

C:\Users\hp\myname>

So please help me as I am trying since 5 days.

**Comment by webtids** [comment]
O God ! thank you for replying me  so quick as I am trying to resolved this issues since 4 days .
I get this information 
Microsoft Windows [Version 10.0.16299.492]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\hp>cd zazzy

C:\Users\hp\zazzy>cd zazzy

C:\Users\hp\zazzy\zazzy>react-native info
Scanning folders for symlinks in C:\Users\hp\zazzy\zazzy\node_modules (622ms)

Environment:
  OS: Windows 10
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4


C:\Users\hp\zazzy\zazzy>

**Comment by webtids** [comment]
I have already installed android studio but as I see here -- Android Studio: Not Found

**Comment by webtids** [comment]
Could anyone help me ?

**Comment by webtids** [comment]
Even today I tried and get this error
---------------------------------------
Scanning folders for symlinks in C:\Users\hp\zazzy\zazzy\node_modules (70ms)
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Unzipping C:\Users\hp\.gradle\wrapper\dists\gradle-2.14.1-all\8bnwg5hd3w55iofp58khbp6yv\gradle-2.14.1-all.zip to C:\Users\hp\.gradle\wrapper\dists\gradle-2.14.1-all\8bnwg5hd3w55iofp58khbp6yv
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.zip.ZipFile.<init>(ZipFile.java:169)
        at org.gradle.wrapper.Install.unzip(Install.java:159)
        at org.gradle.wrapper.Install.access$500(Install.java:26)
        at org.gradle.wrapper.Install$1.call(Install.java:69)
        at org.gradle.wrapper.Install$1.call(Install.java:46)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:46)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd.exe ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

C:\Users\hp\zazzy\zazzy>react-native info
Scanning folders for symlinks in C:\Users\hp\zazzy\zazzy\node_modules (61ms)

**Comment by gengjiawen** [comment]
The download gradle file is corrupted, delete this directory `C:\Users\hp\.gradle\wrapper\dists\gradle-2.14.1-all`.

**Comment by webtids** [comment]
Thank you very much gengjiawen ! Thank you very much

**Comment by TechSatya** [comment]
Uninstalling the **react-native-cli** and again installing it will help you out for sure.
