### ISSUE TITLE
Error: EPERM: operation not permitted, open 'C:\Users\137572\.babel.json'

### ISSUE THREAD

**Issue by nikhilthanga** [facebook/react-native#19846]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
react-native info
Scanning folders for symlinks in D:\First1\node_modules (48ms)
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EPERM: operation not permitted, open 'C:\Users\137572\.babel.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1291:33)
    at save (D:\First1\node_modules\babel-register\lib\cache.js:48:16)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3.

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.

![capture32](https://user-images.githubusercontent.com/40485992/41768254-4c219f00-7629-11e8-8da0-88091a029264.PNG)

## Reproducible Demo
https://snack.expo.io/@nikhilthanga/tictat

**Comment by nikhilthanga** [comment]
> [](url)

**Comment by ansarikhurshid786** [comment]
sdfasdf
