### ISSUE TITLE
[CI] Test failure - D8450498 breaks test_end_to_end job

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#19858]
## Environment

Circle CI.

## Description

The `test_end_to_end` job is failing with the following error:

```
error: bundling failed: Error: Expected path `/private/tmp/react-native-48sC6Rdn/EndToEndTest/index.js` to be relative to one of the project roots
    at toLocalPath (/private/tmp/react-native-48sC6Rdn/EndToEndTest/node_modules/metro/src/node-haste/lib/toLocalPath.js:31:9)
    at /private/tmp/react-native-48sC6Rdn/EndToEndTest/node_modules/metro/src/Bundler.js:246:25
    at Generator.next (<anonymous>)
    at step (/private/tmp/react-native-48sC6Rdn/EndToEndTest/node_modules/metro/src/Bundler.js:11:657)
    at /private/tmp/react-native-48sC6Rdn/EndToEndTest/node_modules/metro/src/Bundler.js:11:887
    at new Promise (<anonymous>)
    at /private/tmp/react-native-48sC6Rdn/EndToEndTest/node_modules/metro/src/Bundler.js:11:568
    at Bundler.transformFile (/private/tmp/react-native-48sC6Rdn/EndToEndTest/node_modules/metro/src/Bundler.js:297:16)
    at Object.<anonymous> (/private/tmp/react-native-48sC6Rdn/EndToEndTest/node_modules/metro/src/lib/transformHelpers.js:99:30)
    at Generator.next (<anonymous>)
```

This appears to be related to the internal diff D8450498 which was synced to GitHub in https://github.com/facebook/react-native/commit/33ba5e8fa26a3e8f32e386f377107a7a03743360.

**Comment by hramos** [comment]
Fix at https://github.com/facebook/react-native/pull/19910 verified, will land shortly

**Comment by hramos** [comment]
Fixed in https://github.com/facebook/react-native/commit/c972a5c298d8da26d583bbfa0f0713ef382692ba
