### ISSUE TITLE
Bundling UIExplorer example for device fails

### ISSUE THREAD

**Issue by dancormier** [facebook/react-native#1990]
When running `npm start` in react-native root, then `curl 'http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle' -o main.jsbundle` in /Examples/UIExplorer, bundling fails with the following error in packager:

```
TypeError: Path must be a string. Received null
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:427:5)
    at /Users/dan/Developer/_projects/react-native/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/index.js:153:33
    at tryCallOne (/Users/dan/Developer/_projects/react-native/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/dan/Developer/_projects/react-native/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/dan/Developer/_projects/react-native/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
```

Bundling other examples seem to work fine.

**Comment by ide** [comment]
Fixed by https://github.com/facebook/react-native/pull/1959.

**Comment by dancormier** [comment]
Great, thanks!
