### ISSUE TITLE
App crashes when used with Cocoapods in Release mode only

### ISSUE THREAD

**Issue by abec** [facebook/react-native#19994]
## Environment
```
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.6.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
````

## Description
When clicking on a button in an App in release mode, react-native crashes. `com.facebook.react.JavaScript (9): EXC_BAD_ACCESS (code=1, address=0x1a1acd7b151)` is in the console. Here's the trace:

```
#0  0x00000001007c9268 in _dispatch_queue_push ()
#1  0x0000000100479314 in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int) at test1/node_modules/react-native/React/CxxModule/RCTNativeModule.mm:78
#2  0x00000001004229e0 in facebook::react::JsToNativeBridge::callNativeModules(facebook::react::JSExecutor&, folly::dynamic&&, bool) at test1/node_modules/react-native/ReactCommon/cxxreact/NativeToJsBridge.cpp:47
#3  0x000000010041731c in facebook::react::JSCExecutor::flushQueueImmediate(facebook::react::Value&&) at test1/node_modules/react-native/ReactCommon/cxxreact/JSCExecutor.cpp:636
#4  0x00000001004179d8 in facebook::react::JSCExecutor::nativeFlushQueueImmediate(unsigned long, OpaqueJSValue const* const*) at test1/node_modules/react-native/ReactCommon/cxxreact/JSCExecutor.cpp:689
#5  0x0000000100418850 in OpaqueJSValue const* (*facebook::react::(anonymous namespace)::exceptionWrapMethod<&(facebook::react::JSCExecutor::nativeFlushQueueImmediate(unsigned long, OpaqueJSValue const* const*))>())(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSValue*, unsigned long, OpaqueJSValue const* const*, OpaqueJSValue const**)::funcWrapper::call(OpaqueJSContext const*, OpaqueJSValue*, OpaqueJSValue*, unsigned long, OpaqueJSValue const* const*, OpaqueJSValue const**) at test1/node_modules/react-native/ReactCommon/cxxreact/JSCExecutor.cpp:64
#6  0x000000018b8e4a64 in long long JSC::APICallbackFunction::call<JSC::JSCallbackFunction>(JSC::ExecState*) ()
#7  0x000000018b237ba8 in JSC::LLInt::setUpCall(JSC::ExecState*, JSC::Instruction*, JSC::CodeSpecializationKind, JSC::JSValue, JSC::LLIntCallLinkInfo*) ()
#8  0x000000018b9cbb88 in llint_entry ()
#9  0x000000018b9cbb34 in llint_entry ()
#10 0x000000018b9cbb98 in llint_entry ()
#11 0x000000018b9cbb98 in llint_entry ()
#12 0x000000018b9c52a8 in vmEntryToJavaScript ()
#13 0x000000018b8af5b8 in JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) ()
#14 0x000000018b23bfe8 in JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) ()
#15 0x000000018b8e3804 in JSC::boundThisNoArgsFunctionCall(JSC::ExecState*) ()
#16 0x000000018b9cc564 in llint_entry ()
#17 0x000000018b9cbb98 in llint_entry ()
#18 0x000000018b9cbb98 in llint_entry ()
#19 0x000000018b9cbb98 in llint_entry ()
#20 0x000000018b9cbb98 in llint_entry ()
#21 0x000000018b9cbb98 in llint_entry ()
#22 0x000000018b9cbb98 in llint_entry ()
#23 0x000000018b9cbb98 in llint_entry ()
#24 0x000000018b9cbfd8 in llint_entry ()
#25 0x000000018b9cbb34 in llint_entry ()
#26 0x000000018b9cbb98 in llint_entry ()
#27 0x000000018b9cbb34 in llint_entry ()
#28 0x000000018b9c52a8 in vmEntryToJavaScript ()
#29 0x000000018b8af5b8 in JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) ()
#30 0x000000018b23bfe8 in JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) ()
#31 0x000000018b8e3804 in JSC::boundThisNoArgsFunctionCall(JSC::ExecState*) ()
#32 0x000000018b9c53f0 in vmEntryToNative ()
#33 0x000000018b23c02c in JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) ()
#34 0x000000018b5485ec in JSC::profiledCall(JSC::ExecState*, JSC::ProfilingReason, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) ()
#35 0x000000018b23bd5c in JSObjectCallAsFunction ()
#36 0x00000001004d0b84 in facebook::react::Object::callAsFunction(OpaqueJSValue*, int, OpaqueJSValue const* const*) const at test1/node_modules/react-native/ReactCommon/jschelpers/Value.cpp:225
#37 0x0000000100416db0 in facebook::react::JSCExecutor::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, folly::dynamic const&)::$_3::operator()() const [inlined] at test1/node_modules/react-native/ReactCommon/cxxreact/JSCExecutor.cpp:551
#38 0x0000000100416cdc in facebook::react::JSCExecutor::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, folly::dynamic const&) at test1/node_modules/react-native/ReactCommon/cxxreact/JSCExecutor.cpp:545
#39 0x0000000100423d78 in std::__1::function<void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*) const at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/functional:1921
#40 0x0000000100450b5c in facebook::react::tryAndReturnError(std::__1::function<void ()> const&) at test1/node_modules/react-native/React/CxxModule/RCTCxxUtils.mm:95
#41 0x000000010046ec74 in facebook::react::RCTMessageThread::tryFunc(std::__1::function<void ()> const&) at test1/node_modules/react-native/React/CxxBridge/RCTMessageThread.mm:60
#42 0x00000001872e1304 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ ()
#43 0x00000001872e0b20 in __CFRunLoopDoBlocks ()
#44 0x00000001872de9b4 in __CFRunLoopRun ()
#45 0x000000018720ed94 in CFRunLoopRunSpecific ()
#46 0x00000001000dfa80 in ::+[RCTCxxBridge runRunLoop]() at test1/node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm:246
#47 0x0000000187e262c8 in __NSThread__start__ ()
#48 0x00000001863f575c in _pthread_body ()
#49 0x00000001863f566c in _pthread_start ()
#50 0x00000001863f2d84 in thread_start ()
```

This is reproducible starting from scratch.

Removing the `subspecs` from `react-native` in the `Podfile` below fixes the issue in the demo. But, in practice, the `subspecs` are needs.

## Reproducible Demo

1. Run the following in a terminal:
```
react-native init test1

pushd test1/ios

cat << EOF > Gemfile
source "https://rubygems.org"
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
gem "cocoapods"
gem "cocoapods-fix-react-native"
EOF

cat << EOF > Podfile
workspace 'test1'
source 'https://github.com/CocoaPods/Specs.git'
node_modules_path = '../node_modules'
react_native_path = node_modules_path + '/react-native'
plugin 'cocoapods-fix-react-native'
platform :ios, '9.0'
target 'test1' do
  use_frameworks!
  pod 'yoga', :path => react_native_path + '/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => react_native_path + '/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'
  pod 'React', :path => react_native_path, :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTSettings',
    'RCTWebSocket',
  ]
end
EOF

bundle install --path .gems
bundle exec pod install
```

You may have to comment out the line `plugin 'cocoapods-fix-react-native'` in the `Podfile` the first time you run it. Be sure to run in again afterwards.

2. Add a button with an `onPress` prop to `App.js`
3. Open `test1/ios/test1.xcworkspace` in xcode
4. Add signing config
5. Edit scheme: change from `Debug` to `Release` mode.
5. Run

**Comment by abec** [comment]
I've looked at the others before, but #19544 seems right. I'll give it a go and report back.
