### ISSUE TITLE
Can't use react-native init to create new project

### ISSUE THREAD

**Issue by Foxhound401** [facebook/react-native#20037]
I can't use command 
`react-native init {someproject}`
to create a new project to work. this is what appear in the console

import type {CommandT} from './commands';
^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Module._compile (D:\Works\Project2\node_modules\pirates\lib\index.js:91:24)
    at Module._extensions..js (module.js:660:10)
    at Object.newLoader [as .js] (D:\Works\Project2\node_modules\pirates\lib\index.js:96:7)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

**Comment by arfaWong** [comment]
Same problem here.

**Comment by leehongqiang** [comment]
Same problem here.

**Comment by dhthong92** [comment]
Same problem

**Comment by AmeerHamzaRiaz** [comment]
same isssue here

```
{
  "name": "location",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react-native": "0.56.0"
  }
}

```

**Comment by dhthong92** [comment]
Here's workaround, this is a known bug in RN 0.56
https://stackoverflow.com/questions/51178688/error-creating-new-react-native-project

**Comment by Edison4mobile** [comment]
@dhthong92  Thanks a lot

**Comment by salmanfarisvp** [comment]
I opened a new issue based on  issue template.
https://github.com/facebook/react-native/issues/20086
