### ISSUE TITLE
AwesomeProject error with react 0.56-0.55.4

### ISSUE THREAD

**Issue by rafacharkman** [facebook/react-native#20146]
## Environment

  **OS:** Windows 10
  **Node:** 10.6.0
  **Yarn:** 1.7.0
  **npm:** 6.1.0
  **Watchman:** Not Found
  **Xcode:** N/A
  **Android Studio:** Not Found

**Packages: (wanted => installed)**
  **react:** ^16.4.1 => 16.4.1
  **react-native:** ^0.55.4 => 0.55.4

## Description
briefly i'm just trying to complete the basics lessons of react native - getting started but this not work , noway...
I did according to the tutorial and it did not work ...ok...
`react-native upgrade` ... no worked...ok...
`react-native run-android` ...no worked...ok...
i'm novice in programing react and I do not know what to do anymore...this lessons simply tires who wants to learn....
if anyone can help me I'm very happy, it's no longer a matter of giving up more kk

## Reproducible Demo
**cmd.exe or terminal**

```
C:\Windows\system32>cd /d E:\ProjectsAndroid

E:\ProjectsAndroid>react-native init AwesomeProject
This will walk you through creating a new React Native project in E:\ProjectsAndroid\AwesomeProject
Using yarn v1.7.0
Installing react-native...
yarn add v1.7.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "react-native > metro-babel-register > @babel/plugin-proposal-optional-chaining@7.0.0-beta.47" has unmet peer dependency "@babel/core@7.0.0-beta.47".
warning "react-native > metro-babel-register > @babel/plugin-proposal-optional-chaining > @babel/plugin-syntax-optional-chaining@7.0.0-beta.47" has unmet peer dependency "@babel/core@7.0.0-beta.47".
warning " > react-native@0.56.0" has unmet peer dependency "react@16.4.1".
[4/4] Building fresh packages...

success Saved lockfile.
success Saved 388 new dependencies.
info Direct dependencies
└─ react-native@0.56.0
info All dependencies
.
.
.
Done in 78.02s.
E:\ProjectsAndroid\AwesomeProject\node_modules\react-native\local-cli\cliEntry.js:30
import type {CommandT} from './commands';
       ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module._compile (E:\ProjectsAndroid\AwesomeProject\node_modules\pirates\lib\index.js:91:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (E:\ProjectsAndroid\AwesomeProject\node_modules\pirates\lib\index.js:96:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

E:\ProjectsAndroid>npm install react-native@0.55.4

E:\ProjectsAndroid>cd AwesomeProject

E:\ProjectsAndroid\AwesomeProject>npm install react-native@0.55.4
npm WARN rm not removing E:\ProjectsAndroid\AwesomeProject\node_modules\.bin\regjsparser.cmd as it wasn't installed by E:\ProjectsAndroid\AwesomeProject\node_modules\regjsparser
npm WARN rm not removing E:\ProjectsAndroid\AwesomeProject\node_modules\.bin\regjsparser as it wasn't installed by E:\ProjectsAndroid\AwesomeProject\node_modules\regjsparser
npm WARN rm not removing E:\ProjectsAndroid\AwesomeProject\node_modules\.bin\jsesc.cmd as it wasn't installed by E:\ProjectsAndroid\AwesomeProject\node_modules\jsesc
npm WARN rm not removing E:\ProjectsAndroid\AwesomeProject\node_modules\.bin\jsesc as it wasn't installed by E:\ProjectsAndroid\AwesomeProject\node_modules\jsesc
npm WARN rm not removing E:\ProjectsAndroid\AwesomeProject\node_modules\.bin\babylon.cmd as it wasn't installed by E:\ProjectsAndroid\AwesomeProject\node_modules\babylon
npm WARN rm not removing E:\ProjectsAndroid\AwesomeProject\node_modules\.bin\babylon as it wasn't installed by E:\ProjectsAndroid\AwesomeProject\node_modules\babylon
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-native@0.55.4 requires a peer of react@16.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-native@3.2.1 requires a peer of eslint@^3.17.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ react-native@0.55.4
added 89 packages from 33 contributors, removed 105 packages, updated 558 packages and audited 10480 packages in 205.544s
found 2 vulnerabilities (1 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

E:\ProjectsAndroid\AwesomeProject>react-native upgrade
Scanning folders for symlinks in E:\ProjectsAndroid\AwesomeProject\node_modules (48ms)
You should consider using the new upgrade tool based on Git. It makes upgrades easier by resolving most conflicts automatically.
To use it:
- Go back to the old version of React Native
- Run "npm install -g react-native-git-upgrade"
- Run "react-native-git-upgrade"
See https://facebook.github.io/react-native/docs/upgrading.html
Upgrading project to react-native v0.55.4
Check out the release notes and breaking changes: https://github.com/facebook/react-native/releases/tag/v0.55.0
Your "package.json" file doesn't seem to have "react" as a dependency.
"react" was changed from a dependency to a peer dependency in react-native v0.21.0.
Therefore, it's necessary to include "react" in your project's dependencies.
Please run "npm install --save react", then re-run "react-native upgrade".


E:\ProjectsAndroid\AwesomeProject>npm install --save react
npm WARN eslint-plugin-react-native@3.2.1 requires a peer of eslint@^3.17.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native@0.55.4 requires a peer of react@16.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ react@16.4.1
added 1 package and audited 10504 packages in 8.846s
found 2 vulnerabilities (1 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

E:\ProjectsAndroid\AwesomeProject>react-native upgrade
Scanning folders for symlinks in E:\ProjectsAndroid\AwesomeProject\node_modules (33ms)
You should consider using the new upgrade tool based on Git. It makes upgrades easier by resolving most conflicts automatically.
To use it:
- Go back to the old version of React Native
- Run "npm install -g react-native-git-upgrade"
- Run "react-native-git-upgrade"
See https://facebook.github.io/react-native/docs/upgrading.html
Upgrading project to react-native v0.55.4
Check out the release notes and breaking changes: https://github.com/facebook/react-native/releases/tag/v0.55.0
.
.
.
Successfully upgraded this project to react-native v0.55.4

E:\ProjectsAndroid\AwesomeProject>react-native run-android
Scanning folders for symlinks in E:\ProjectsAndroid\AwesomeProject\node_modules (55ms)
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library
:app:prepareComAndroidSupportSupportV42301Library
:app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library
:app:prepareComFacebookFrescoDrawee130Library
:app:prepareComFacebookFrescoFbcore130Library
:app:prepareComFacebookFrescoFresco130Library
:app:prepareComFacebookFrescoImagepipeline130Library
:app:prepareComFacebookFrescoImagepipelineBase130Library
:app:prepareComFacebookFrescoImagepipelineOkhttp3130Library
:app:prepareComFacebookReactReactNative0554Library
:app:prepareComFacebookSoloaderSoloader010Library
:app:prepareOrgWebkitAndroidJscR174650Library
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:mergeDebugShaders
:app:compileDebugShaders
:app:generateDebugAssets
:app:mergeDebugAssets
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest
:app:processDebugResources
:app:generateDebugSources
:app:incrementalDebugJavaCompilationSafeguard
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources
:app:transformClassesWithDexForDebug
Running dex in-process requires build tools 23.0.2.
For faster builds update this project to use the latest build tools.
:app:mergeDebugJniLibFolders
:app:transformNative_libsWithMergeJniLibsForDebug
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug
:app:validateSigningDebug
:app:packageDebug
:app:assembleDebug
:app:installDebug
Installing APK 'app-debug.apk' on 'Nexus_5X_API_28_x86(AVD) - 6.0' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 1 mins 41.946 secs
'adb' n�o � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.
Starting the app (E:\SDK_AS/platform-tools/adb shell am start -n com.awesomeproject/com.awesomeproject.MainActivity...
Starting: Intent { cmp=com.awesomeproject/.MainActivity }
```

**NODE(cli.js):**

```
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   E:\ProjectsAndroid\AwesomeProject


Metro Bundler ready.

Loading dependency graph, done.
error: bundling failed: NotFoundError: Cannot find entry file index.js in any of the roots: ["E:\\ProjectsAndroid\\AwesomeProject"]
    at DependencyGraph.getAbsolutePath (E:\ProjectsAndroid\AwesomeProject\node_modules\metro\src\node-haste\DependencyGraph.js:317:11)
    at E:\ProjectsAndroid\AwesomeProject\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:280:416
    at Generator.next (<anonymous>)
    at step (E:\ProjectsAndroid\AwesomeProject\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:11:445)
    at E:\ProjectsAndroid\AwesomeProject\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:11:605
    at process._tickCallback (internal/process/next_tick.js:68:7)
 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.
```

**Android Emulator Device**

```
The development server returned response error code: 404

URL: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
{"message":"Cannot find entry file index.js in any of the roots: [\"E:\\\\ProjectsAndroid\\\\AwesomeProject\"]","name":"NotFoundError","type":"NotFoundError","status":404,"errors":[{"description":"Cannot find entry file index.js in any of the roots: [\"E:\\\\ProjectsAndroid\\\\AwesomeProject\"]"}],"stack":"NotFoundError: Cannot find entry file index.js in any of the roots: [\"E:\\\\ProjectsAndroid\\\\AwesomeProject\"]\n    at DependencyGraph.getAbsolutePath (E:\\ProjectsAndroid\\AwesomeProject\\node_modules\\metro\\src\\node-haste\\DependencyGraph.js:317:11)\n    at E:\\ProjectsAndroid\\AwesomeProject\\node_modules\\metro\\src\\DeltaBundler\\DeltaCalculator.js:280:416\n    at Generator.next (<anonymous>)\n    at step (E:\\ProjectsAndroid\\AwesomeProject\\node_modules\\metro\\src\\DeltaBundler\\DeltaCalculator.js:11:445)\n    at E:\\ProjectsAndroid\\AwesomeProject\\node_modules\\metro\\src\\DeltaBundler\\DeltaCalculator.js:11:605\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
processBundleResult
    BundleDownloader.java:266
access$200
    BundleDownloader.java:35
onResponse
    BundleDownloader.java:153
execute
    RealCall.java:135
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1113
run
    ThreadPoolExecutor.java:588
run
    Thread.java:818

```

**Comment by ramuse** [comment]
I got the same issue on **Windows 10**

**Comment by nkabir1986** [comment]
i got the same issue when creating a clean react native 0.56 lastest stable release - [Unable to resolve module `AccessibilityInfo` .... ]

**Comment by kirkcola** [comment]
Got the same issue on `Windows 10` like the others,  just after I re-upgrading to `0.56.0` to verify the issue #20015.

A bad week for developers using Windows ☹

**Comment by cgonzalezp91** [comment]
So there is no solution by now about this? :(

**Comment by guilhermegonzaga** [comment]
I got the same issue on Windows 10 :(

**Comment by nkabir1986** [comment]
@cgonzalezp91 downgrade is not a solution , 0.56 has many bugfixes like fix bad render borders with corner radius , we need to upgrade to 0.56 .
