### ISSUE TITLE
java.lang.RuntimeException: com.facebook.react.devsupport.JSException: Can't find variable: setTimeout (index.android.bundle:798)

### ISSUE THREAD

**Issue by Nits7029** [facebook/react-native#20212]
## Environment
React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.6
      CPU: x64 Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz
      Memory: 21.85 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 0.0.6
      react-native-cli: 2.0.1
      react-native-fetch-blob: 0.10.8

## Description
`E/AndroidRuntime: FATAL EXCEPTION: mqt_js
                                                             Process: com.roarmedia, PID: 9153
                                                             java.lang.RuntimeException: com.facebook.react.devsupport.JSException: Can't find variable: setTimeout (index.android.bundle:798)
                                                                 at com.facebook.react.bridge.DefaultNativeModuleCallExceptionHandler.handleException(DefaultNativeModuleCallExceptionHandler.java:22)
                                                                 at com.facebook.react.devsupport.DisabledDevSupportManager.handleException(DisabledDevSupportManager.java:170)
                                                                 at com.facebook.react.bridge.CatalystInstanceImpl.onNativeException(CatalystInstanceImpl.java:525)
                                                                 at com.facebook.react.bridge.CatalystInstanceImpl.access$1000(CatalystInstanceImpl.java:39)
                                                                 at com.facebook.react.bridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:541)
                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
                                                                 at java.lang.Thread.run(Thread.java:818)`

debug apk is working fine, but i am getting above issue while running release apk on app start.
Above error i got it from Android Studio logcat.

Problem is, release apk crashes on app start.

Please help me to sort it out an issue, Thanks.

**Comment by keshk26** [comment]
@Nits7029 try `yarn upgrade react-native@0.56.0` That is what fixed this problem for me.

**Comment by SirNeuman** [comment]
yeah... for some reason @keshk26's solution worked for me. Not sure why

**Comment by haggholm** [comment]
I am currently seeing this with the latest version, 0.57.2.

**Comment by rickhanlonii** [comment]
Hey @Nits7029, sorry this went so long without a response

Unfortunately we can't debug issues from crash reports alone - if anyone has this issue again and can post a repro case then we're happy to re-open and take a look

**Comment by sunildate05** [comment]
@Nits7029. I'm also facing same issue. is this issue resolved?. I'm using RN 0.59.10 version.
