### ISSUE TITLE
android crash with mqt_native_modules NullPointerException

### ISSUE THREAD

**Issue by njleonzhang** [facebook/react-native#20223]
## Environment
Run `react-native info` in your terminal and paste its contents here.
```
Scanning folders for symlinks in /Users/leon/Documents/localCode/play-rn-plugin/demo/node_modules (16ms)

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 68.80 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2,26.0.3, 27.0.3
        API Levels: 10, 14, 17, 19, 21, 22, 23, 24, 25, 26
    IDEs:
      Android Studio: 3.1 AI-173.4670197
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
```

simulator: genymotion 4.1.1

## Description
The native module is a simple Toast demo by following the [doc](https://facebook.github.io/react-native/docs/native-modules-android). When I invoke the `toast.show` in js, crash occurs.

```
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                  java.lang.NullPointerException
                      at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:86)
                      at java.lang.StringBuilder.<init>(StringBuilder.java:95)
                      at com.facebook.react.devsupport.DevSupportManagerImpl$JSExceptionLogger.log(DevSupportManagerImpl.java:291)
                      at com.facebook.react.devsupport.DevSupportManagerImpl.handleException(DevSupportManagerImpl.java:275)
                      at com.facebook.react.bridge.CatalystInstanceImpl.onNativeException(CatalystInstanceImpl.java:525)
                      at com.facebook.react.bridge.CatalystInstanceImpl.access$1000(CatalystInstanceImpl.java:39)
                      at com.facebook.react.bridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:541)
                      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                      at android.os.Looper.loop(Looper.java:137)
                      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
                      at java.lang.Thread.run(Thread.java:856)
D/OpenGLRenderer: TextureCache::flush: target size: 2457
```

## Reproducible Demo
https://github.com/njleonzhang/play-rn-native-module

**Comment by njleonzhang** [comment]
I mis-write ` NativeModules.Toast.show('hello', NativeModules.Toast.LONG)` as `  NativeModules.Toast.show('hello', NativeModules.Toast.LENGTH_LONG)`.  It's mu fault, but the error is really confusing.
