### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by tapz** [facebook/react-native#20272]
- [X] Review the documentation: https://facebook.github.io/react-native
  - [X] Search for existing issues: https://github.com/facebook/react-native/issues
  - [X] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.4.1 => 16.4.1
  react-native: 0.55.4 => 0.55.4

## Description
```
Caused by java.util.ConcurrentModificationException
       at android.support.v4.util.SimpleArrayMap.put(SimpleArrayMap.java:461)
       at android.support.v7.widget.AppCompatDrawableManager.addDelegate(AppCompatDrawableManager.java:493)
       at android.support.v7.widget.AppCompatDrawableManager.installDefaultInflateDelegates(AppCompatDrawableManager.java:97)
       at android.support.v7.widget.AppCompatDrawableManager.get(AppCompatDrawableManager.java:86)
       at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
       at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:75)
       at android.support.v7.widget.SwitchCompat.<init>(SwitchCompat.java:223)
       at android.support.v7.widget.SwitchCompat.<init>(SwitchCompat.java:200)
       at android.support.v7.widget.SwitchCompat.<init>(SwitchCompat.java:189)
       at com.facebook.react.views.switchview.ReactSwitch.<init>(ReactSwitch.java:23)
       at com.facebook.react.views.switchview.ReactSwitchManager.createViewInstance(ReactSwitchManager.java:118)
       at com.facebook.react.views.switchview.ReactSwitchManager.createViewInstance(ReactSwitchManager.java:31)
       at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:42)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:223)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:152)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1012)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:983)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
       at android.view.Choreographer.doFrame(Choreographer.java:619)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

## Reproducible Demo
No idea how to reproduce as occurs randomly in release builds. The stack trace is from Crashlytics. Seems to be related on how React Native updates the UI. Our code does not have much control over the native screen updating and as JavaScript is single threaded, there isn't much we can do about concurrency.

**Comment by seanadkinson** [comment]
Seeing this in our bugsnag as well.  Same stacktrace.  Obviously seems to be related to rendering a Switch, based on the stacktrace.

**Comment by tapz** [comment]
A nice way to get rid of bugs without fixing them. As nobody has mentioned a fix in the next RN version, it probably does not exist. 

Testing with the new RN is not currently possible as it has compatibility issues with my dependencies (or for some other reason does not work at all).

**Comment by bearer-syntaxerror** [comment]
We're seeing this occasionally in our app's production crash reports as well. Unable to find deterministic repro steps.

```
com.facebook.react.views.switchview.ReactSwitch.<init>
ReactSwitch.java, line 25
java.util.ConcurrentModificationException: java.util.ConcurrentModificationException
```

```
Environment:
  OS: macOS 10.14.1
  Node: 10.9.0
  Yarn: 1.9.4
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: ^0.51.0 => 0.51.1
```

**Comment by arled** [comment]
Getting this on android only:
```
    "react": "16.4.1",
    "react-native": "0.56.0",
```
All bugs related to this end up getting closed with no without a solution!!!

**Comment by kranthijulakantiwork** [comment]
Issue:
java.util.ConcurrentModificationException: null
    at android.support.v4.util.SimpleArrayMap.put(SimpleArrayMap.java:461)
    at android.support.v7.widget.AppCompatDrawableManager.addDelegate(AppCompatDrawableManager.java:493)
    at android.support.v7.widget.AppCompatDrawableManager.installDefaultInflateDelegates(AppCompatDrawableManager.java:97)
    at android.support.v7.widget.AppCompatDrawableManager.get(AppCompatDrawableManager.java:86)
    at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
    at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:75)
    at android.support.v7.widget.SwitchCompat.<init>(SwitchCompat.java:223)
    at android.support.v7.widget.SwitchCompat.<init>(SwitchCompat.java:200)
    at android.support.v7.widget.SwitchCompat.<init>(SwitchCompat.java:189)
    at com.facebook.react.views.switchview.ReactSwitch.<init>(ReactSwitch.java:23)
    at com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode.measure(ReactSwitchManager.java:88)
    at com.facebook.yoga.YogaNode.measure(YogaNode.java:714)
    at com.facebook.yoga.YogaNode.jni_YGNodeCalculateLayout(YogaNode.java)
    at com.facebook.yoga.YogaNode.calculateLayout(YogaNode.java:254)
    at com.facebook.react.uimanager.ReactShadowNodeImpl.calculateLayout(ReactShadowNodeImpl.java:562)
    at com.facebook.react.uimanager.UIImplementation.calculateRootLayout(UIImplementation.java:952)
    at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(UIImplementation.java:700)
    at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:660)
    at com.facebook.react.uimanager.UIManagerModule.onBatchComplete(UIManagerModule.java:696)
    at com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete(NativeModuleRegistry.java:134)
    at com.facebook.react.bridge.CatalystInstanceImpl$BridgeCallback.onBatchComplete(CatalystInstanceImpl.java:145)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:815)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
    at android.os.Looper.loop(Looper.java:207)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
    at java.lang.Thread.run(Thread.java:818)

## To Reproduce
No Idea. The above issue is from production sentry stack trace

## Environment

React Native Environment Info:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
     Android 6.0
