### ISSUE TITLE
`react-native init AwesomeProject` fails

### ISSUE THREAD

**Issue by vjpr** [facebook/react-native#2028]
When following the [getting started guide](https://facebook.github.io/react-native/docs/getting-started.html#content), I get the following stack trace:-

```
This will walk you through creating a new React Native project in /Users/Vaughan/dev/AwesomeProject
npm WARN engine stacktrace-parser@0.1.1: wanted: {"node":"~0.10"} (current: {"node":"2.0.1","npm":"2.9.0"})
 
> ws@0.4.31 install /Users/Vaughan/dev/AwesomeProject/node_modules/react-native/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
 
> fsevents@0.3.6 install /Users/Vaughan/dev/AwesomeProject/node_modules/react-native/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

2015-07-17 17:46:07.818 xcodebuild[16425:449581] [MT] DVTSDK: Warning: SDK path collision for path '<DVTFilePath:0x7f816c025360:'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk'>': SDK with name 'iphonesimulator8.4' being superceded by SDK with 'iphonesimulator8.4'.
2015-07-17 17:46:07.825 xcodebuild[16425:449581] [MT] DVTSDK: Warning: SDK path collision for path '<DVTFilePath:0x7f816b4414e0:'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk'>': SDK with name 'iphoneos8.4' being superceded by SDK with 'iphoneos8.4'.
2015-07-17 17:46:08.220 xcodebuild[16425:449581] [MT] DVTPlugInManager: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for GPUDebuggerMTLSupport.ideplugin (com.apple.dt.gpu.GPUDebuggerMTLSupport) not present
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished
react-native@0.7.1 node_modules/react-native
├── absolute-path@0.0.0
├── stacktrace-parser@0.1.1
├── graceful-fs@3.0.8
├── react-timer-mixin@0.13.2
├── underscore@1.7.0
├── image-size@0.3.5
├── debug@2.1.3 (ms@0.7.0)
├── yargs@1.3.2
├── promise@7.0.3 (asap@2.0.3)
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── worker-farm@1.3.1 (xtend@4.0.0, errno@0.1.3)
├── source-map@0.1.31 (amdefine@1.0.0)
├── sane@1.1.3 (watch@0.10.0, minimist@1.1.1, fb-watchman@1.2.0, minimatch@0.2.14, exec-sh@0.2.0, walker@1.0.7)
├── bluebird@2.9.34
├── rebound@0.0.12
├── uglify-js@2.4.23 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.5.4, source-map@0.1.34)
├── connect@2.8.3 (methods@0.0.1, uid2@0.0.2, fresh@0.1.0, cookie-signature@1.0.1, pause@0.0.1, qs@0.6.5, bytes@0.2.0, buffer-crc32@0.2.1, cookie@0.1.0, send@0.1.2, formidable@1.0.14)
├── ws@0.4.31 (tinycolor@0.0.1, options@0.0.6, commander@0.6.1, nan@0.3.2)
├── module-deps@3.5.6 (inherits@2.0.1, shallow-copy@0.0.1, duplexer2@0.0.2, minimist@0.2.0, subarg@0.0.1, concat-stream@1.4.10, parents@1.0.1, resolve@0.7.4, readable-stream@1.1.13, through2@0.4.2, stream-combiner2@1.0.2, browser-resolve@1.9.0, JSONStream@0.7.4, detective@3.1.0)
├── jstransform@11.0.1 (object-assign@2.1.1, base62@1.1.0, source-map@0.4.4, esprima-fb@15001.1.0-dev-harmony-fb, commoner@0.10.3)
├── joi@5.1.0 (topo@1.0.2, isemail@1.1.1, hoek@2.14.0, moment@2.10.3)
├── babel@5.4.3 (slash@1.0.0, fs-readdir-recursive@0.1.2, path-is-absolute@1.0.0, convert-source-map@1.1.1, commander@2.8.1, source-map@0.4.4, output-file-sync@1.1.1, glob@5.0.14, lodash@3.10.0, chokidar@1.0.4)
├── react-tools@0.13.2 (commoner@0.10.3, jstransform@10.1.0)
└── babel-core@5.7.4 (slash@1.0.0, path-exists@1.0.0, fs-readdir-recursive@0.1.2, babel-plugin-remove-debugger@1.0.1, babel-plugin-remove-console@1.0.1, babel-plugin-eval@1.0.1, babel-plugin-jscript@1.0.1, babel-plugin-property-literals@1.0.1, babel-plugin-inline-environment-variables@1.0.1, babel-plugin-react-constant-elements@1.0.3, babel-plugin-member-expression-literals@1.0.1, babel-plugin-undefined-to-void@1.1.6, shebang-regex@1.0.0, to-fast-properties@1.0.1, trim-right@1.0.1, babel-plugin-react-display-name@1.0.3, path-is-absolute@1.0.0, babel-plugin-constant-folding@1.0.1, babel-plugin-proto-to-assign@1.0.3, babel-plugin-dead-code-elimination@1.0.2, strip-json-comments@1.0.2, babel-plugin-runtime@1.0.7, private@0.1.6, globals@6.4.1, estraverse@4.1.0, esutils@2.0.2, convert-source-map@1.1.1, home-or-tmp@1.0.0, babel-plugin-undeclared-variables-check@1.0.2, js-tokens@1.0.1, line-numbers@0.2.0, detect-indent@3.0.1, repeating@1.1.3, babylon@5.7.2, source-map@0.4.4, output-file-sync@1.1.1, resolve@1.1.6, minimatch@2.0.8, is-integer@1.0.4, source-map-support@0.2.10, regexpu@1.2.0, lodash@3.10.0, regenerator@0.8.34, core-js@0.9.18)
/Users/Vaughan/dev/AwesomeProject/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:102
      throw err;
            ^
SyntaxError: /Users/Vaughan/package.json: Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (/Users/Vaughan/dev/AwesomeProject/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:98:62)
    at OptionManager.findConfigs (/Users/Vaughan/dev/AwesomeProject/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:171:32)
    at OptionManager.init (/Users/Vaughan/dev/AwesomeProject/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:228:10)
    at compile (/Users/Vaughan/dev/AwesomeProject/node_modules/react-native/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/Users/Vaughan/dev/AwesomeProject/node_modules/react-native/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Vaughan/dev/AwesomeProject/node_modules/react-native/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

Why does it try to read `/Users/Vaughan/package.json`?

**Comment by vjpr** [comment]
Turns out I had an empty `package.json` file in my home dir. Looks like npm searches for `package.json` files up until it hits the root dir. Removed the file. Fixed.
