### ISSUE TITLE
Error: Cannot find module './android'

### ISSUE THREAD

**Issue by Vscarlett** [facebook/react-native#20297]
I'm having this issue when I init and react-native run-android on my First react-native project.
I'm running linux ubuntu
I've uninstalled and reinstalled react-native 
I've also done that with node, java and Android studio 
```
resilient@resilient-acer-09:~/Desktop/Bootcamp/Insta$ react-native run-android
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module './android'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/resilient/Desktop/Bootcamp/Insta/node_modules/react-native/local-cli/core/index.js:13:17)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Module._compile (/home/resilient/Desktop/Bootcamp/Insta/node_modules/pirates/lib/index.js:91:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Object.newLoader [as .js] (/home/resilient/Desktop/Bootcamp/Insta/node_modules/pirates/lib/index.js:96:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
resilient@resilient-acer-09:~/Desktop/Bootcamp/Insta$ 
```

**Comment by dashu3f** [comment]
install again your packages. not correct installed package. maybe last package
