### ISSUE TITLE
Let's fix build problem on windows

### ISSUE THREAD

**Issue by gengjiawen** [facebook/react-native#20353]
I first discover this issue in June 16 (https://github.com/facebook/metro/issues/181), which is a month ago, but got less attention on this in beggining. Then react native 0.56 released, which totally expose the problem, which bothering windows user even for now (see https://github.com/facebook/react-native/issues/20346 and https://github.com/facebook/metro/issues/200).

Here is what I want to have been achieve
## Fix debug RNTester on windows 
Related pr: https://github.com/facebook/react-native/pull/19974.
The main purpose is refactor bash script to nodejs script, so it can be cross platform. I remove some types on file simplily because they not flow-typed file. @pvdz Please merge this asap. For without it, debugging RNTester will be an unusable on windows
## Fix RNTester in release mode on windows.
Related pr: https://github.com/facebook/react-native/pull/20293.
This is a windows specific bug. And this bothered me very long time , I searched really really a lot to fix it.
Without it you will have build problem like this:
```
* What went wrong:
Failed to capture snapshot of input files for task ':RNTester:android:app:bundleReleaseJsAndAssets' property '$1' during up-to-date check.
> Failed to create MD5 hash for file content.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```
I think it's clean fix and I have appveyor log to prove my fix work, you can see detail in that pr. So I hope @hramos or anyone with merge permission can review my pr.

## Fix general problem like
Problem like `SyntaxError: Unexpected identifier` or 'Unable to resolve a haste module' or 'Unable to resolve a module' has been fixed in master branch by the help of metro team. But when I communicate with @kelset , branch 0.57 still not working. But I believe we can fix that soon.

And Many developers works on windows instead of macOS. And this has been take too long to fix. And there are many windows developer still suffer from this issue in today. 

In the end, I love react native. But dear react native official members, don't make us wait too long.

**Comment by hramos** [comment]
Reopening with "For Discussion" label. For future reference, if you use the provided "For Discussion" template, this would be done automatically by the bot.

**Comment by gengjiawen** [comment]
@hramos Can you review this pr https://github.com/facebook/react-native/pull/20293.

**Comment by kelset** [comment]
👋 Jiawen, thanks for the writeup!
Sadly as I mentioned my powers over reviewing and merging are limited.

Can I ask you a side question? You say

> Problem like SyntaxError: Unexpected identifier or 'Unable to resolve a haste module' or 'Unable to resolve a module' has been fixed in master branch [..] but [..] , branch 0.57 still not working

Do you see any commit present in the master branch that is not on the 0.57 one?

cc @grabbou any idea of why it may work on one and not the other?

**Comment by gengjiawen** [comment]
@kelset The master branch when I tested works not metro 0.42.2, I will test the latest master branch again.

**Comment by gengjiawen** [comment]
The lastest master branch is broken again.
```
import type {CommandT} from './commands';
       ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module._compile (D:\Developer\react-native\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (D:\Developer\react-native\node_modules\pirates\lib\index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by harshulsharma0000** [comment]
@gengjiawen Neither **0.42.1** nor **0.42.2** work on my machine getting 
import type {CommandT} from './commands';
On which version did you try?

**Comment by gengjiawen** [comment]
I think I am pretty clear, `0.42.1` works.

**Comment by gengjiawen** [comment]
@hramos @rafeca Can we get this done ? This has been bothering windows user for over a month.

**Comment by hramos** [comment]
@gengjiawen I'm aware of this, and other PRs. We just held a day-long event for React and React Native contributors here at the office, and we're now finishing our roadmap and a proposal to help move PRs along faster. It does require that we take a break from looking at our GitHub notifications for a bit so we can focus, but in the long term it should have a beneficial effect on the repo.

For the time being, please work with any of our other core contributors, and thank you for your patience.

**Comment by aaronschubert0** [comment]
@hramos That's awesome to hear, will the roadmap be shared publicly or just used internally? Would be very helpful to gain some insights from the roadmap.

**Comment by dinyrepo** [comment]
Hi All,

I am just beginning to work with React-Native, for training purpose can i use any old version of React-native which will work without having any build issue.

-Dinesh C R

**Comment by hramos** [comment]
@aaronschubert0 you can take a look at meetings notes from the core team, as well as any proposals, over at https://github.com/react-native-community/discussions-and-proposals. This is a work in progress, but the plan is to fill that repo out with any ongoing work from the community. As for the React Native team at Facebook, we just broadcast a tech talk this week which covers our ongoing work on the new React Native architecture codenamed "Fabric": https://www.facebook.com/hramos/videos/10101317533036249/?notif_id=1532541292178353&notif_t=feedback_reaction_generic

**Comment by aaronschubert0** [comment]
@hramos Great thanks a lot, appreciate the insights.

**Comment by Wolf00Bomber** [comment]
Any headway over the issue reported at this link below would be helpful, as we are not able to build the App using `react-native run-android` CMD:
https://github.com/facebook/react-native/issues/19953#issuecomment-407002494

**Comment by gengjiawen** [comment]
Update: 
* Metro 0.43.1 still not working, the build on master branch is still broken on windows.
* You can test RNTester release version on windows since one of my pr merged. 
* The debug fix pr still need to be merged https://github.com/facebook/react-native/pull/19974, still waiting for @pvdz 's approval. Maybe someone else can review and merge my pr, it has been there for over a month.

**Comment by gengjiawen** [comment]
Update: 
* Metro 0.43.1 still not working, the build on master branch is still broken on windows.
* You can test RNTester release version on windows since one of my pr merged. 
* The debug fix pr still need to be merged https://github.com/facebook/react-native/pull/19974, still waiting for @pvdz 's approval. Maybe someone else can review and merge my pr, it has been there for over a month.

**Comment by gengjiawen** [comment]
You can also check the appveyor log: https://ci.appveyor.com/project/gengjiawen/react-native/build/job/it491en7tm6r69cq.

**Comment by gengjiawen** [comment]
Metro `0.43.2` not working too.

**Comment by victorhugoweb** [comment]
please help us - Windows developers are human too. We need support too.

**Comment by westinyang** [comment]
mmp，这个问题耗费了我大半天的时间，原来是个bug

**Comment by fungilation** [comment]
Moving my project from my ancient MacBook to my shiny new PC, I got a whole bunch of errors while trying to build for Android on Windows 10 before I keep hitting on build issue like https://github.com/facebook/react-native/issues/14209. Which is a year old issue, so I suppose this is a case of old symptoms coming back to haunt us?

I'm on RN 0.56.0. No issue on Mac building for either iOS or Android. But all sorts of issues building on Windows for Android.

Hopefully these issues get addressed in RN 0.57 and it's ready soon.

**Comment by nicolashemonic** [comment]
Same issue, works great on MacOS and get `unexpected token` error on Windows.

**Comment by kelset** [comment]
While I understand everyone frustration with this Windows issue, let me be extremely clear on the fact that if this issue becomes a series of "me too" comments or worse I'll lock it.

As mentioned many times before, this is an open source project so you're entitled to the level of support you pay for and that's: none.

I've been personally trying to having this fixed since the first RCs of 0.56, but I'm not a Windows user so it's really hard to check the attempted fixes.

You want to help? Investigate what is causing this issue and submit PRs to fix it.

**Comment by fungilation** [comment]
Is [this ](https://stackoverflow.com/a/46375361/2322084)a viable, supported solution to officially support Windows deployment by relying on the Windows Linux subsystem? The great thing with this is the whole RN toolchain would then be the same as Mac/Linux's. The setup would obviously be more complicated to have install files on native Windows so it's exposed to the GUI code editor, but having a single Linux-like environment for RN to support instead of split with Windows' (which also breaks in all sorts of other "interesting" ways like permissions to create/delete files/folders as I've encountered trying to setup my RN env on Windows) seems very appealing. RN also doesn't need to consider alternative CI testing on Windows either.

https://stackoverflow.com/a/46375361/2322084

PS. My comment was/is not a me too comment. If you want the community to help, you have to be more specific in terms of what you need in testing. And this is a discussion thread is this not? Agreed that as long as comments aren't "just" me too.

**Comment by gengjiawen** [comment]
Reported via https://github.com/facebook/metro/issues/213.

@kelset How about we downgrade metro to 0.42.1 on branch 0.57 ?

**Comment by Parisasuchdev** [comment]
react-native init EventPlanner --version 0.55.4
npm install --save
npm install -g npm-install-peers

This worked for me :)

**Comment by Parisasuchdev** [comment]
`react-native init EventPlanner --version 0.55.4
npm install --save
npm install -g npm-install-peers`

This worked for me :)

**Comment by Parisasuchdev** [comment]
`react-native init EventPlanner --version 0.55.4`
`npm install `--save
`npm install -g npm-install-peers`

This worked for me :)

**Comment by Parisasuchdev** [comment]
`react-native init EventPlanner --version 0.55.4`
`npm install --save`
`npm install -g npm-install-peers`

This worked for me :)

**Comment by gengjiawen** [comment]
Confirmed `0.43.4` works. @kelset @grabbou we can prepair a new release. cc @rafeca .

**Comment by gengjiawen** [comment]
All my windows related pr has been merged, you can play with react native code on windows now. Have fun :)

**Comment by fungilation** [comment]
Thanks a lot @gengjiawen.

Is a 0.57 RC dropping soon so I can upgrade by `react-native-git-upgrade`?

**Comment by Dimous** [comment]
> so you're entitled to the level of support you pay for and that's: none.
I cant imagine flutter core team member saing something like this

**Comment by kelset** [comment]
Until 0.57 lands I think we should keep this open.

**Comment by hramos** [comment]
The 0.57 RC is now available. Please try it out and let us know if this is still an issue.
