### ISSUE TITLE
react-native-git-upgrade gives an error

### ISSUE THREAD

**Issue by NelGarbuzova** [facebook/react-native#20407]
After upgrading RN version to **0.56.0** running of command `react-native-git-upgrade` (instead of `react-native upgrade`) gives this error:

```
git-upgrade ERR! Error: Plugin 0 specified in "/home/misha/Work/neaktor_tablet/node_modules/babel-preset-react-native/index.js" provided an invalid property of "default" (While processing preset: "/home/misha/Work/neaktor_tablet/node_modules/babel-preset-react-native/index.js")
    at Plugin.init (/usr/lib/node_modules/react-native-git-upgrade/node_modules/babel-core/lib/transformation/plugin.js:131:13)
    at Function.normalisePlugin (/usr/lib/node_modules/react-native-git-upgrade/node_modules/babel-core/lib/transformation/file/options/option-manager.js:152:12)
    at /usr/lib/node_modules/react-native-git-upgrade/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/usr/lib/node_modules/react-native-git-upgrade/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/usr/lib/node_modules/react-native-git-upgrade/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at /usr/lib/node_modules/react-native-git-upgrade/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
    at /usr/lib/node_modules/react-native-git-upgrade/node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/usr/lib/node_modules/react-native-git-upgrade/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20) 
git-upgrade ERR! Restore initial sources 
```
Command `react-native upgrade` works without errors.

My **package.json**

```
{
  "name": "appName",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "base-64": "^0.1.0",
    "moment": "^2.22.1",
    "pouchdb-adapter-asyncstorage": "^6.4.1",
    "pouchdb-react-native": "^6.4.1",
    "react": "^16.4.1",
    "react-native": "0.56.0",
    "react-native-button": "^2.3.0",
    "react-native-cheerio": "^1.0.0-rc.4",
    "react-native-device-info": "^0.22.0",
    "react-native-document-picker": "^2.1.0",
    "react-native-dropdown-menu": "^2.0.0",
    "react-native-elements": "^0.19.1",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-file-picker": "0.0.11",
    "react-native-file-viewer": "^1.0.5",
    "react-native-fs": "^2.9.12",
    "react-native-gifted-chat": "^0.4.3",
    "react-native-html-parser": "0.0.5",
    "react-native-image-picker": "^0.26.10",
    "react-native-infinite-scroll": "^1.0.6",
    "react-native-keyboard-aware-scroll-view": "^0.5.0",
    "react-native-modal": "^6.1.0",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-permissions": "^1.1.1",
    "react-native-prompt": "^1.0.0",
    "react-native-router-flux": "^4.0.0-beta.31",
    "react-native-secure-storage": "^0.1.1",
    "react-native-simple-events": "^1.0.1",
    "react-native-vector-icons": "4.6.0",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "url": "^0.11.0",
    "xmlhttprequest": "^1.8.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.54",
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "^5.0.0",
    "del": "^3.0.0",
    "gulp": "^3.9.1",
    "gulp-clean": "^0.4.0",
    "gulp-param": "^1.0.3",
    "jest": "22.4.3",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts/"
    ]
  }
}

```

**Comment by harrydema** [comment]
Were you able to solve it?
