### ISSUE TITLE
APK doesn't work in either emulators or real devices

### ISSUE THREAD

**Issue by khuongdv** [facebook/react-native#20427]
## Environment
React Native Environment Info:
    - System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 84.90 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    - Binaries:
      Node: 9.6.1 - /usr/local/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    - SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3
        API Levels: 23, 24, 25, 26, 27
    - IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    - npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    - npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

## Description
If I run the app in IDE using this command: `react-native run-android`, it works well in emulator.

Then I build the apk (follow the guide in the official page of RN), no error.

Move the apk to my emulator and then see logcat, I got this log: (and in the emulator, it keep popping up an alert 'XXX has stopped')

```
07-27 17:49:58.928 527-613/system_process E/SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
07-27 17:49:58.928 527-611/system_process E/WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
07-27 17:50:01.655 527-544/system_process E/BluetoothAdapter: Bluetooth binder is null
07-27 17:50:01.656 527-544/system_process E/BatteryStatsService: no controller energy info supplied
07-27 17:50:01.660 527-544/system_process E/BatteryStatsService: power: Missing API
07-27 17:50:01.661 527-544/system_process E/BatteryStatsService: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}
07-27 17:50:03.930 527-613/system_process E/SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
07-27 17:50:03.930 527-611/system_process E/WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
07-27 17:50:07.082 4759-4775/com.buyerapp E/libEGL: load_driver(/system/lib/egl/libGLES_emulation.so): dlopen failed: library "/system/lib/egl/libGLES_emulation.so" not found
07-27 17:50:08.933 527-613/system_process E/SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
07-27 17:50:08.933 527-611/system_process E/WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
07-27 17:50:09.303 4759-4781/com.buyerapp E/ReactNativeJNI: Got JS Exception: Can't find variable: self (index.android.bundle:370)
07-27 17:50:09.312 4759-4781/com.buyerapp E/ReactNativeJNI: Got JS Stack: index.android.bundle:370:12134
                                                            index.android.bundle:370:12137
                                                            c@index.android.bundle:2:822
                                                            i@index.android.bundle:2:464
                                                            t@index.android.bundle:2:324
                                                            index.android.bundle:369:133
                                                            c@index.android.bundle:2:822
                                                            i@index.android.bundle:2:464
                                                            t@index.android.bundle:2:324
                                                            index.android.bundle:345:511
                                                            c@index.android.bundle:2:822
                                                            i@index.android.bundle:2:464
                                                            t@index.android.bundle:2:324
                                                            index.android.bundle:343:1999
                                                            c@index.android.bundle:2:822
                                                            i@index.android.bundle:2:464
                                                            t@index.android.bundle:2:324
                                                            index.android.bundle:342:108
                                                            c@index.android.bundle:2:822
                                                            i@index.android.bundle:2:464
                                                            t@index.android.bundle:2:324
                                                            index.android.bundle:341:133
                                                            c@index.android.bundle:2:822
                                                            i@index.android.bundle:2:464
                                                            t@index.android.bundle:2:324
                                                            index.android.bundle:340:472
                                                            c@index.android.bundle:2:822
                                                            i@index.android.bundle:2:464
                                                            t@index.android.bundle:2:324
                                                            index.android.bundle:339:155
                                                            c@index.android.bundle:2:822
                                                            i@index.android.bundle:2:464
                                                            t@index.android.bundle:2:324
                                                            index.android.bundle:12:133
                                                            c@index.android.bun
07-27 17:50:09.319 4759-4781/com.buyerapp E/AndroidRuntime: FATAL EXCEPTION: mqt_js
                                                            Process: com.buyerapp, PID: 4759
                                                            java.lang.RuntimeException: com.facebook.react.devsupport.JSException: Can't find variable: self (index.android.bundle:370)
                                                                at com.facebook.react.bridge.DefaultNativeModuleCallExceptionHandler.handleException(DefaultNativeModuleCallExceptionHandler.java:22)
                                                                at com.facebook.react.devsupport.DisabledDevSupportManager.handleException(DisabledDevSupportManager.java:170)
                                                                at com.facebook.react.bridge.CatalystInstanceImpl.onNativeException(CatalystInstanceImpl.java:525)
                                                                at com.facebook.react.bridge.CatalystInstanceImpl.access$1000(CatalystInstanceImpl.java:39)
                                                                at com.facebook.react.bridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:541)
                                                                at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                at android.os.Looper.loop(Looper.java:154)
                                                                at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
                                                                at java.lang.Thread.run(Thread.java:761)
                                                             Caused by: com.facebook.react.devsupport.JSException: Can't find variable: self (index.android.bundle:370)
                                                                at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
                                                                at android.os.Looper.loop(Looper.java:154) 
                                                                at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
                                                                at java.lang.Thread.run(Thread.java:761) 
                                                             Caused by: com.facebook.jni.CppException: Can't find variable: self (index.android.bundle:370)
                                                                at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                at android.os.Handler.handleCallback(Handler.java:751) 
                                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
                                                                at android.os.Looper.loop(Looper.java:154) 
                                                                at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
                                                                at java.lang.Thread.run(Thread.java:761) 
07-27 17:50:09.637 363-363/? E/EGL_emulation: tid 363: eglCreateSyncKHR(1285): error 0x3004 (EGL_BAD_ATTRIBUTE)
07-27 17:50:14.419 527-613/system_process E/SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
07-27 17:50:14.420 527-611/system_process E/WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
07-27 17:50:19.426 527-613/system_process E/SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
07-27 17:50:19.427 527-611/system_process E/WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
07-27 17:50:24.429 527-613/system_process E/SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
07-27 17:50:24.429 527-611/system_process E/WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
07-27 17:50:29.438 527-613/system_process E/SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
07-27 17:50:29.438 527-611/system_process E/WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
07-27 17:50:34.439 527-613/system_process E/SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
07-27 17:50:34.439 527-611/system_process E/WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
07-27 17:50:39.441 527-613/system_process E/SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
07-27 17:50:39.441 527-611/system_process E/WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
07-27 17:50:44.446 527-613/system_process E/SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
07-27 17:50:44.448 527-611/system_process E/WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
07-27 17:50:49.450 527-613/system_process E/SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
07-27 17:50:49.451 527-611/system_process E/WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
07-27 17:50:54.451 527-613/system_process E/SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
07-27 17:50:54.452 527-611/system_process E/WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
07-27 17:50:59.453 527-613/system_process E/SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
07-27 17:50:59.453 527-611/system_process E/WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
07-27 17:51:01.653 527-544/system_process E/BluetoothAdapter: Bluetooth binder is null
07-27 17:51:01.660 527-544/system_process E/BatteryStatsService: no controller energy info supplied
07-27 17:51:01.663 527-544/system_process E/BatteryStatsService: power: Missing API
07-27 17:51:01.664 527-544/system_process E/BatteryStatsService: modem info is invalid: ModemActivityInfo{ mTimestamp=0 mSleepTimeMs=0 mIdleTimeMs=0 mTxTimeMs[]=[0, 0, 0, 0, 0] mRxTimeMs=0 mEnergyUsed=0}
07-27 17:51:04.458 527-613/system_process E/SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
07-27 17:51:04.458 527-611/system_process E/WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
07-27 17:51:09.458 527-613/system_process E/SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
07-27 17:51:09.459 527-611/system_process E/WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
07-27 17:51:14.467 527-613/system_process E/SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
07-27 17:51:14.467 527-611/system_process E/WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
07-27 17:51:19.469 527-613/system_process E/SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
07-27 17:51:19.470 527-611/system_process E/WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
07-27 17:51:24.474 527-613/system_process E/SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
07-27 17:51:24.476 527-611/system_process E/WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
07-27 17:51:29.487 527-613/system_process E/SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
07-27 17:51:29.487 527-611/system_process E/WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed

```
Few days ago, my app only had some common libs such as redux, redux-thunk, react-navigation... and react-native-maps. I could build an APK that truly worked in both emulator and real device.

Until today, I added Firebase, react-native-image-picker and rn-fetch-blob. Everything worked well in DEV environment. But when I generated the signed apk. That APK did not work. See the log above.

## Reproducible Demo

-NA-

**Comment by gengjiawen** [comment]
From the stack trace, it looks like there is something wrong with you code 
```
java.lang.RuntimeException: com.facebook.react.devsupport.JSException: Can't find variable: self (index.android.bundle:370)
```
