### ISSUE TITLE
Failed resolution of: Lcom/facebook/infer/annotation/Assertions;

### ISSUE THREAD

**Issue by NameFILIP** [facebook/react-native#20433]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Environment:
  OS:  macOS High Sierra 10.13.6
  Node:  8.11.2
  Yarn:  1.7.0
  npm:  5.6.0
  Watchman:  4.9.0
  Xcode:  Xcode 9.3 Build version 9E145
  Android Studio:  3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.55.4 => 0.55.4

## Description
The app used to work, but doesn't launch right now without any code changes.
The error I found using `adb logcat *:E` is:

```
07-27 17:50:46.454 21556 21556 E AndroidRuntime: FATAL EXCEPTION: main
07-27 17:50:46.454 21556 21556 E AndroidRuntime: Process: com.placesmobile, PID: 21556
07-27 17:50:46.454 21556 21556 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/infer/annotation/Assertions;
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:90)
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:45)
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:88)
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:77)
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:52)
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7174)
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6938)
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
07-27 17:50:46.454 21556 21556 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.infer.annotation.Assertions" on path: DexPathList[[zip file "/data/app/com.placesmobile-eQv3ZITT0OuZx91A0MpfOA==/base.apk"],nativeLibraryDirectories=[/data/app/com.placesmobile-eQv3ZITT0OuZx91A0MpfOA==/lib/arm, /data/app/com.placesmobile-eQv3ZITT0OuZx91A0MpfOA==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-27 17:50:46.454 21556 21556 E AndroidRuntime: 	... 17 more
```

Any ideas why `com.facebook.infer.annotation.Assertions` is not there?

**Comment by gengjiawen** [comment]
If you are using instant run, you can try a clean build.

**Comment by webdevbyjoss** [comment]
Hi @NameFILIP, I'm facing the same issue with my React Native app Android builds after the update to latest ExpoKit 31. Not exactly sure where it comes from, as nothing changed actually in Gradle build scripts. Were you able to fix the issue?

**Comment by truongngoctuan** [comment]
the above comment magically worked for me, my case, I edited build.gradle of `react-native-gesture-handler`
