### ISSUE TITLE
[CI] Test failure - D8801217 configuration breaking change

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#20431]
Following the new configuration changes introduced in D8801217, the React Native CLI is failing with the following error when it attempts to build the test JS Bundle we use in our open source tests:

```
$ node local-cli/cli.js bundle --platform android --dev true --entry-file ReactAndroid/src/androidTest/js/TestBundle.js
Scanning folders for symlinks in /Users/hramos/git/react-native/node_modules (14ms)
(node:55190) UnhandledPromiseRejectionWarning: TypeError: Path must be a string. Received undefined
at assertPath (path.js:28:11)
at Object.resolve (path.js:1171:7)
at getCliConfig (/Users/hramos/git/react-native/local-cli/core/index.js:132:41)
at Object.<anonymous> (/Users/hramos/git/react-native/local-cli/core/index.js:158:32)
at Module._compile (module.js:652:30)
at Module._compile (/Users/hramos/git/react-native/node_modules/pirates/lib/index.js:83:24)
at Module._extensions..js (module.js:663:10)
at Object.newLoader (/Users/hramos/git/react-native/node_modules/pirates/lib/index.js:88:7)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
(node:55190) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:55190) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

$ node -v
v8.10.0
 
$ cat package.json | grep metro
"metro": "^0.43.0",
"metro-babel-register": "^0.43.0",
"metro-core": "^0.43.0",
"metro-memory-fs": "^0.43.0",
```

You can observe this in our CI at https://circleci.com/gh/facebook/react-native/48213#tests/containers/0, or reproduce locally by running `node local-cli/cli.js bundle --platform android --dev true --entry-file ReactAndroid/src/androidTest/js/TestBundle.js `

**Comment by hramos** [comment]
Fixed by https://github.com/facebook/react-native/pull/20429
