### ISSUE TITLE
Dev Menu crashes on RN 0.44.0 and API 26+

### ISSUE THREAD

**Issue by dkfl1995** [facebook/react-native#20507]
[skip envinfo]
## Environment
React-Native v. 0.44.0
MacOS: 12 Sierra
NPM: 6.1.0

## Description
Error when shaking or emulating shake w/ CRTL+M on Android SDK API 26+

## Reproducible Demo
Using following environment versions run emulator API 26+, run "react-native run-android" (Debug Build), press CRTL+M.

Error that persists due to this commits:

`FATAL EXCEPTION: main
                                                   Process: com.foolog, PID: 27284
                                                   android.view.WindowManager$BadTokenException: Unable to add 
window android.view.ViewRootImpl -- permission denied for window type 2006
                                                       at android.view.ViewRootImpl.setView(ViewRootImpl.java:789)
                                                       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
                                                       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                       at com.facebook.react.devsupport.DevLoadingViewController.setVisible(DevLoadingViewController.java:145)
                                                       at com.facebook.react.devsupport.DevLoadingViewController.access$100(DevLoadingViewController.java:34)
                                                       at com.facebook.react.devsupport.DevLoadingViewController$1.run(DevLoadingViewController.java:66)
                                                       at android.os.Handler.handleCallback(Handler.java:790)
                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
08-02 12:43:48.076 1582-1617/? W/ActivityManager:   Force finishing activity com.foolog/.MainActivity`

**Comment by hramos** [comment]
0.44 is quite old... unless this reproduces in 0.56 or master, this issue is likely to be closed.

**Comment by hramos** [comment]
[skip envinfo] is meant for issues where the RN version is irrelevant. 0.44 is quite old, however. Closing.
