### ISSUE TITLE
RN error : Unexpected token '*' (http://localhost:8081/index.delta?platform=android&dev=true&minify=false:94148)

### ISSUE THREAD

**Issue by chenlk000** [facebook/react-native#20576]
# Environment
Environment:
OS: Windows 10
Node: 10.7.0
Yarn: 1.9.4
npm: 6.1.0
Watchman: 4.9.4
Xcode: N/A
Android Studio: 3.1.3 

Packages: (wanted => installed)
react-native-cli:  2.0.1
react-native:  0.55.4

# Description
I meet this  error when I run command: **react-native run-android** . Although it show me **Build successful**. 
![image](https://user-images.githubusercontent.com/27504215/43829773-5c1d081c-9b32-11e8-9d92-3ee660b68fea.png)
![image](https://user-images.githubusercontent.com/27504215/43829752-4db27fc8-9b32-11e8-993d-7c55952efeda.png)
And in android studio ,the logcat shows words below:
```
8-08 16:41:20.296 19265-19412/com.securemail E/ReactNativeJNI: Got JS Exception: Unexpected token '*' (http://localhost:8081/index.delta?platform=android&dev=true&minify=false:94148)
08-08 16:41:20.298 19265-19412/com.securemail E/unknown:ReactNative: Exception in native call from JS
    com.facebook.react.devsupport.JSException: Unexpected token '*' (http://localhost:8081/index.delta?platform=android&dev=true&minify=false:94148)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:224)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: com.facebook.jni.CppException: Unexpected token '*' (http://localhost:8081/index.delta?platform=android&dev=true&minify=false:94148)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:815) 
        at android.os.Handler.dispatchMessage(Handler.java:104) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
        at android.os.Looper.loop(Looper.java:224) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
        at java.lang.Thread.run(Thread.java:818) 
08-08 16:41:20.300 19265-19412/com.securemail E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: Error calling AppRegistry.runApplication
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:224)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:815) 
        at android.os.Handler.dispatchMessage(Handler.java:104) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
        at android.os.Looper.loop(Looper.java:224) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
        at java.lang.Thread.run(Thread.java:818) 
```
Someone said delete the files in **assets** and run under command can help, but I tried it and no use, feeling confused. 
```
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
```
I tested other mobilephone but no use. Please help me ,thanks a lot.

**Comment by vdlindenmark** [comment]
Already searched for an `*` somewhere in your code?

**Comment by Eugnis** [comment]
Had the similar problem. You need to download http://localhost:8081/index.delta?platform=android&dev=true&minify=false directly (from browser etc.), then open in editor and search for row 94148 from which your error came from.
After that you'll see exactly the place of error and be able to find it in your project's js files.

**Comment by yernandus** [comment]
same thing for me, and searching for that column did not work. there is no *

**Comment by opiruyan** [comment]
I had very similar issue and rebooting system worked for me.

**Comment by dashu3f** [comment]
Edit android/app/build.gradle

use this

compile ("com.facebook.react:react-native:0.44.0") { force = true }

and write version of app you use instead of 0.44.0 and delete something like this compile "com.facebook.react:react-native:+" or this compile "com.facebook.react:react-native:0.44.0"

**Comment by anupgupta-arg** [comment]
please let me know the solution to this. :(

**Comment by turkyfarmawi** [comment]
from my side, I was running tomcat on port 8081 [just in case]

**Comment by mnlbox** [comment]
I have same issue. My project crash without any reason.
Any working solution?

**Comment by mnlbox** [comment]
Guys I found the problem.
I remove my `node_modules` and use `npm install` and anything works well but when I use `yarn install` it's break with this error:
```
Unexpected token '*' (http://localhost:8081/index.delta?platform=android&dev=true&minify=false:...)
```

It seems it's a yarn issue. :thinking:

**Comment by beqaMeqvabishvili** [comment]
Just fixed the problem after hours of headache. for me, the problem was one of my dependencies was using **  operator which was not recognized by my babel compiler (apologies if I misused the terms, I am not very experienced with these staff). so I went there and changed ** operator with the regular Math.pow().

for me the file that was causing the issue was
 `\node_modules\react-native-elements\src\tooltip\getTooltipCoordinate.js`
third line, in react-native-elements library.

check your last installed libraries for same operator and replace. probably not the best way to fix it but at least you'll know what's causing the issue.

**Comment by Doychev** [comment]
I just encountered a similar problem after some package updates.
Turns out if you start **Remote Debugging** (open the dev menu and press Debug JS Remotely), you get a more detailed explanation of the error - in my case, one of the new versions of my dependencies required a newer version of RN (and I'm yet to migrate that to a later version).
