### ISSUE TITLE
Android: Failing post request in react native when using OkHttp interceptor

### ISSUE THREAD

**Issue by mandrizzle** [facebook/react-native#20590]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [X] Search for existing issues: https://github.com/facebook/react-native/issues
  - [X] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 21.45 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.3, macOS 10.13, tvOS 11.3, watchOS 4.3
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 9.3/9E145 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
When making a `POST` http request with a body in react native while using a custom `OkHttp` instance with an interceptor that calls `chain.proceed(chain.request())` more than once, an `IOException` is thrown with the message "closed" with the following stack trace which causes the request to fail in react native.

```
08-08 21:18:23.245 7091-7204/com.androidbugokhttp E/NETWORK ERROR: java.io.IOException: closed
        at okio.RealBufferedSink$1.write(RealBufferedSink.java:199)
        at com.facebook.react.modules.network.CountingOutputStream.write(CountingOutputStream.java:53)
        at com.facebook.react.modules.network.ProgressRequestBody$1.write(ProgressRequestBody.java:61)
        at okio.Okio$1.write(Okio.java:79)
        at okio.RealBufferedSink.flush(RealBufferedSink.java:224)
        at com.facebook.react.modules.network.ProgressRequestBody.writeTo(ProgressRequestBody.java:54)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.androidbugokhttp.MainApplication$2$1.intercept(MainApplication.java:61)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

The custom okHttp client looks like this:

```java
        OkHttpClientProvider.setOkHttpClientFactory(new OkHttpClientFactory() {
            @Override
            public OkHttpClient createNewNetworkModuleClient() {
                return new OkHttpClient.Builder().cookieJar(new ReactCookieJarContainer()).addInterceptor(new Interceptor() {
                    @Override
                    public Response intercept(Chain chain) throws IOException {
                        try {
                            chain.proceed(chain.request());
                            return chain.proceed(chain.request());
                        } catch (IOException e) {
                            Log.e("NETWORK ERROR", Log.getStackTraceString(e));
                            throw e;
                        }

                    }
                }).build();
            }
        });
```

On the JS end the fetch call looks like this:
```js
fetch("https://api.github.com", {
  method: 'POST',
  body: '{}'      // Removing the body makes this succeed
}).then(data => {
  alert("SUCCESS: " + data)
}).catch(error => { 
  // Always end up in here :(
  alert("FAILED: " + error)
})
```

If anyone is wondering if calling `chain.proceed` more than once is misusing the okhttp api, it is not according to the [okhttp docs](https://github.com/square/okhttp/wiki/Interceptors)

> Application interceptors
> Permitted to retry and make multiple calls to Chain.proceed()
[source](https://github.com/square/okhttp/wiki/Interceptors)

## Reproducible Demo
I created a repo where this is happening
https://github.com/mandrizzle/react-native-okhttp-bug/

I started from a fresh project and added the bug, might be easier to see the 2 commits individually
https://github.com/mandrizzle/react-native-okhttp-bug/commits/master

To run the project, run `react-native run-android`
The exception can be seen in logcat

**Comment by patrickkempff** [comment]
@mandrizzle, Thank you very much for reaching out! I'm closing this issue due to inactivity. The provided information is based on v0.56. If the issue still persists in the latest version of React Native, please feel free to file a new issue report.
