### ISSUE TITLE
java.lang.IllegalArgumentException: Unexpected char 0x5e0 at 575 in Cookie value

### ISSUE THREAD

**Issue by johnreytanquinco** [facebook/react-native#20620]
## Environment
  Node: 8.9.4
  Yarn: 1.0.2
  npm: 5.6.0
  react: 16.2.0 => 16.2.0
  react-native: 0.51.0 => 0.51.0

## Description
Same issue as this https://github.com/facebook/react-native/issues/11401 when a content is displayed in webview. Posting my crash report below.

```
Fatal Exception: java.lang.IllegalArgumentException: Unexpected char 0x5e0 at 575 in Cookie value: AWSALB=XXXXX; lux_uid=XXXXX; _ga=GA1.2.XXXXX; _gid=GA1.2.XXXXX; iad=1; __adblocker=false; um=1; ud=1; uh=1; _dc_gtm_UA-XXXXX=1; landingPageCookie=https://www.XXXXX; piano_limit=1; _gat_UA-XXXXX=1; user_geo_location={"continentCode":"XX"; "countryCode":"XX"=; "country":"XXXXX"=; "region":"X=; "city":"XXXXX"}=; traffic_src={"ga_gclid":""; "ga_source":"(direct)"=; "ga_medium":"(none)"=; "ga_campaign":""=; "ga_content":""=; "ga_keyword":""=; "ga_landing_page":"https://XXXXX"=; "ga_client_id":"XXXXX"}=
       at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:320)
       at okhttp3.Headers$Builder.set(Headers.java:300)
       at okhttp3.Request$Builder.header(Request.java:164)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:86)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

```

**Comment by johnreytanquinco** [comment]
Devices where this error occurs.
- Galaxy Tab S2 : Android version 7.0
- Galaxy S6 : Android version 6.0.1

But no error on smartphone with Android version 8.1.0

**Comment by rahamin1** [comment]
I don't understand why #19430 was closed... Semms like a react native issue

**Comment by VittoriDavide** [comment]
any news on this ? I have still this error
