### ISSUE TITLE
NullPointerException for android

### ISSUE THREAD

**Issue by yaxin3690** [facebook/react-native#20708]
## Environment
mac 10.13.14  android 8.0  react-native 0.49

## Description
This is an occasional bug. Here's the exception:
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference
        at android.graphics.drawable.DrawableContainer$DrawableContainerState.createAllFutures(DrawableContainer.java:875)
        at android.graphics.drawable.DrawableContainer$DrawableContainerState.getOpacity(DrawableContainer.java:1169)
        at android.graphics.drawable.DrawableContainer.getOpacity(DrawableContainer.java:433)
        at android.graphics.drawable.InsetDrawable.getOpacity(InsetDrawable.java:258)
        at android.view.View.computeOpaqueFlags(View.java:15789)
        at android.view.View.setBackgroundDrawable(View.java:20639)
        at android.view.View.setBackground(View.java:20532)
        at android.view.View.<init>(View.java:5232)
        at android.widget.TextView.<init>(TextView.java:878)
        at android.widget.EditText.<init>(EditText.java:88)
        at android.widget.EditText.<init>(EditText.java:84)
        at android.widget.EditText.<init>(EditText.java:80)
        at android.widget.EditText.<init>(EditText.java:76)
        at com.facebook.react.views.textinput.ReactTextInputShadowNode.setThemedContext(ReactTextInputShadowNode.java:59)
        at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:198)
        at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:243)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
        at android.os.Looper.loop(Looper.java:166)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
        at java.lang.Thread.run(Thread.java:784)
## Reproducible Demo
The bug can occur when you click on the android return button (which is already available for android) or edit the page

**Comment by hramos** [comment]
This issue looks quite incomplete. Closing as it's lacking most of the information requested by the template.
