### ISSUE TITLE
[BUG] RNTester not working on master branch. 

### ISSUE THREAD

**Issue by gengjiawen** [facebook/react-native#20844]
I am on windows, not sure macOS has the same problem. 
Also captured by appveyor https://ci.appveyor.com/project/gengjiawen/react-native/build/job/71fsk8xufjt9on4w.
cc @rafeca 
```
$ node ./local-cli/cli.js start
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   D:\Developer\react-native 

Loading dependency graph, done.
error: bundling failed: SyntaxError: D:\Developer\react-native\RNTester\js\RNTesterApp.android.js: Unexpected token (36:12)

  34 | const nativeImageSource = require('nativeImageSource');
  35 | 
> 36 | import type {RNTesterNavigationState} from './RNTesterNavigationReducer';
     |             ^
  37 | 
  38 | UIManager.setLayoutAnimationEnabledExperimental(true);
  39 | 
    at Parser.raise (D:\Developer\react-native\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:3898:15)
    at Parser.unexpected (D:\Developer\react-native\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:5227:16)
    at Parser.expectContextual (D:\Developer\react-native\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:5195:41)
    at Parser.parseImport (D:\Developer\react-native\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8379:12)
    at Parser.parseStatementContent (D:\Developer\react-native\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7201:27)
    at Parser.parseStatement (D:\Developer\react-native\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7120:17)
    at Parser.parseBlockOrModuleBlockBody (D:\Developer\react-native\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7671:23)
    at Parser.parseBlockBody (D:\Developer\react-native\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7658:10)
    at Parser.parseTopLevel (D:\Developer\react-native\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7085:10)
    at Parser.parse (D:\Developer\react-native\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8471:17)
::ffff:127.0.0.1 - - [25/Aug/2018:07:21:32 +0000] "GET /RNTester/js/RNTesterApp.android.delta?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.10.0"
 BUNDLE  [android, dev] RNTester\js/RNTesterApp.android.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.
```

**Comment by gengjiawen** [comment]
Okay, I looked into the problem, it is introduced in this https://github.com/facebook/react-native/commit/e4621f4ce142c23067ef5ab83465c01ebce34ff4. Just revert `Config.js` fix the problem.
