### ISSUE TITLE
React Native App Crashes on release in Google Play Store with exception: com.facebook.react.common.JavascriptException: Object is not a function (evaluating '(0,babelHelpers.interopRequireDefault(u).default)()')

### ISSUE THREAD

**Issue by tobiloba23** [facebook/react-native#20861]
## Environment
Environment:
  OS: Windows 10
  Node: 10.6.0
  Yarn: Not Found
  npm: 6.1.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4907809

Packages: (wanted => installed)
  react: 16.4.1 => 16.4.1
  react-native: 0.55.4 => 0.55.4

## Description
App crashes on launch from the Google play store with the above mentioned exception. See stack trace from play store below:

FATAL EXCEPTION: mqt_native_modules
Process: XXXX, PID: 15893
com.facebook.react.common.JavascriptException: Object is not a function (evaluating '(0,babelHelpers.interopRequireDefault(u).default)()'), stack:
<unknown>@12:88
d@2:768
n@2:339
t@2:262
global code@622:8
	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:158)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
	at java.lang.Thread.run(Thread.java:818)

## Reproducible Demo
Issue happens on Google play store so I have no idea how to reproduce. It works perfectly on my local computer.

**Comment by abartolo** [comment]
@tobiloba23 I am having a similar issue. Whenever I run locally in android and ios it works fine. However, when I do a release build it crashes in device. 

**Error**

```
08-27 20:47:42.675 23560-23586/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: myApp.main, PID: 23560
    com.facebook.react.common.JavascriptException: Invalid attempt to spread non-iterable instance, stack:
    nonIterableSpread@11:3941
    toConsumableArray@11:4436
    <unknown>@868:215
    c@2:822
    i@2:464
    t@2:324
    <unknown>@865:520
    c@2:822
    i@2:464
    t@2:324
    <unknown>@864:338
    c@2:822
    i@2:464
    t@2:324
    <unknown>@857:235
    c@2:822
    i@2:464
    t@2:324
    <unknown>@458:296
    c@2:822
    i@2:464
    t@2:324
    <unknown>@384:197
    c@2:822
    i@2:464
    t@2:324
    <unknown>@309:246
    c@2:822
    i@2:464
    t@2:324
    <unknown>@12:77
    c@2:822
    i@2:394
    t@2:324
    global code@1026:8
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:764)
```

**React Native Info**

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 867.99 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 25.0.2, 26.0.1, 26.0.3, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by tobiloba23** [comment]
@abartolo is there a way we can escalate this issue. I am running behind on delivering my project.

**Comment by abartolo** [comment]
@tobiloba23 I am also not sure. I created https://github.com/facebook/react-native/issues/20882 in hope of some more attention.

**Comment by brenohq** [comment]
same issue here

**Comment by abartolo** [comment]
@tobiloba23 Can you "react-native info" in order to let the bot remove the "Old Version" tag. I am getting error I posted above with the following:

**react-native info**
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 266.08 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 25.0.2, 26.0.1, 26.0.3, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by tobiloba23** [comment]
I have run info but I am using RN 0.55.4, an old version. 0.56 doesn't work on Windows. I upgraded to 0.57-rc3 and I get a similar error to this on the debug apk

**Comment by hramos** [comment]
Closing as this is a report for an older version....

**Comment by amismailz** [comment]
I am facing same issue RN 0.65

**Comment by minicase** [comment]
I am facing same issue RN 0.57,only release version

**Comment by rashdan** [comment]
+1
