### ISSUE TITLE
[Android] Fatal Exception: java.lang.IncompatibleClassChangeError Couldn't find com.facebook.react.uimanager.a.a.a

### ISSUE THREAD

**Issue by Jekiwijaya** [facebook/react-native#20916]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.
```
Environment:
  OS: macOS 10.14
  Node: 8.11.3
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 10.0 Build version 10L201y
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.4.1 => 16.4.1
  react-native: 0.55.4 => 0.55.4
```

## Description
My workspace got an error after we upgrade from react-native `0.54` to `0.55`, the error come in Crashlytics.
```
Fatal Exception: java.lang.IncompatibleClassChangeError: Couldn't find com.facebook.react.uimanager.a.a.a
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
       at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
       at java.lang.reflect.Method.getAnnotation(Method.java:301)
       at com.facebook.react.uimanager.ViewManagersPropertyCache.extractPropSettersFromViewManagerClassDefinition(ViewManagersPropertyCache.java:429)
       at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForViewManagerClass(ViewManagersPropertyCache.java:320)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.(ViewManagerPropertyUpdater.java:122)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.(ViewManagerPropertyUpdater.java:116)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.findManagerSetter(ViewManagerPropertyUpdater.java:79)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.getNativeProps(ViewManagerPropertyUpdater.java:66)
       at com.facebook.react.uimanager.ViewManager.getNativeProps(ViewManager.java:203)
       at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstantsForViewManager(UIManagerModuleConstantsHelper.java:145)
       at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstants(UIManagerModuleConstantsHelper.java:92)
       at com.facebook.react.uimanager.UIManagerModule.createConstants(UIManagerModule.java:225)
       at com.facebook.react.uimanager.UIManagerModule.(UIManagerModule.java:149)
       at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:173)
       at com.facebook.react.CoreModulesPackage.access$000(CoreModulesPackage.java:53)
       at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:130)
       at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:127)
       at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:79)
       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1172)
       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1142)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1080)
       at com.facebook.react.ReactInstanceManager.access$000(ReactInstanceManager.java:113)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:911)
       at java.lang.Thread.run(Thread.java:818)
--
```
I saw the issue is look's like https://github.com/facebook/react-native/issues/9354. But that issue related to gson, and mine is uimanager from react.
- Samsung device 5.0, 5.0.1, 5.0.2.
After I search, I still didn't find the solution. It's been affect lot of users.

Please share if someone know the solution

**Comment by dulmandakh** [comment]
did you enabled proguard?

**Comment by Jekiwijaya** [comment]
@dulmandakh yes I am.

**Comment by dulmandakh** [comment]
Proguard rules are used and tested since 0.56 release, please upgrade to 0.56 or 0.57, which will be released very soon.
