### ISSUE TITLE
SyntaxError: Unexpected identifier jest & babel 7 & react-native 0.56

### ISSUE THREAD

**Issue by asimolmez** [facebook/react-native#20966]
## Environment
React Native Environment Info:
    

> System:
>       OS: macOS High Sierra 10.13.6
>       CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
>       Memory: 82.63 MB / 8.00 GB
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 10.9.0 - /usr/local/bin/node
>       Yarn: 1.9.4 - /usr/local/bin/yarn
>       npm: 6.2.0 - /usr/local/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     SDKs:
>       iOS SDK:
>         Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
>     IDEs:
>       Android Studio: 3.1 AI-173.4907809
>       Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
>     npmPackages:
>       react: ^16.4.1 => 16.4.2
>       react-native: ^0.56.0 => 0.56.0
>     npmGlobalPackages:
>       react-native-cli: 2.0.1

## Description
After upgrading react native version to 0.56, I could not run my tests. I was testing my app before upgrade. I get "SyntaxError: Unexpected identifier" 

This is my devDependencies.

```
"@babel/core": "^7.0.0",
"@babel/plugin-proposal-optional-chaining": "^7.0.0",
"babel-core": "^7.0.0-bridge.0",
"babel-jest": "^23.4.2",
"babel-preset-react-native": "^5.0.2",
"enzyme": "^3.3.0",
"enzyme-adapter-react-16": "^1.1.1",
"enzyme-to-json": "^3.3.4",
"jest": "^23.4.2",
"react-addons-test-utils": "^15.6.2",
"react-dom": "^16.4.2",
"react-test-renderer": "^16.4.2",
"regenerator-runtime": "^0.12.1",
"sinon": "^6.1.5"
```
I configured the jest in this way.

```
"jest": {
  "preset": "react-native",
  "snapshotSerializers": [
    "enzyme-to-json/serializer"
  ],
  "setupTestFrameworkScriptFile": "<rootDir>/setupTest.js"
} 
```

.babelrc

```
{
  "presets": ["react-native"],
  "plugins": [
    "@babel/plugin-proposal-optional-chaining"
  ]
}
```

Error detail - 1

```
import KeyboardAwareMixin from './lib/KeyboardAwareMixin';
       ^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier

  1 | import React from "react";
  2 | import {View} from "react-native";
> 3 | import {KeyboardAwareScrollView} from "react-native-keyboard-aware-scroll-view";
    | ^
  4 | import PropTypes from 'prop-types';
  5 |
  6 | /**

  at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
```

Error Detail - 2

```
import createIconSet from './lib/create-icon-set';
       ^^^^^^^^^^^^^

SyntaxError: Unexpected identifier

  1 | import React, {Component} from "react";
  2 | import {TouchableOpacity} from "react-native";
> 3 | import Icon from "react-native-vector-icons/FontAwesome";
    | ^
  4 | import {COLORS} from "../config/Constant";
  5 | import PropTypes from "prop-types";
  6 |

  at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
```

Error Details - 3

```
SyntaxError: /Users/----/node_modules/react-native/Libraries/Components/Touchable/TouchableOpacity.js: Unexpected token (26:12)

  24 | const flattenStyle = require('flattenStyle');
  25 |
> 26 | import type {Props as TouchableWithoutFeedbackProps} from 'TouchableWithoutFeedback';
     |             ^
  27 | import type {ViewStyleProp} from 'StyleSheet';
  28 |
  29 | type Event = Object;

  at Parser.raise (node_modules/@babel/parser/lib/index.js:3938:15)
  at Parser.unexpected (node_modules/@babel/parser/lib/index.js:5247:16)
  at Parser.expectContextual (node_modules/@babel/parser/lib/index.js:5215:41)
  at Parser.parseImport (node_modules/@babel/parser/lib/index.js:8403:12)
  at Parser.parseStatementContent (node_modules/@babel/parser/lib/index.js:7225:27)
  at Parser.parseStatement (node_modules/@babel/parser/lib/index.js:7144:17)
  at Parser.parseBlockOrModuleBlockBody (node_modules/@babel/parser/lib/index.js:7695:23)
  at Parser.parseBlockBody (node_modules/@babel/parser/lib/index.js:7682:10)
  at Parser.parseTopLevel (node_modules/@babel/parser/lib/index.js:7109:10)
  at Parser.parse (node_modules/@babel/parser/lib/index.js:8495:17)
```

MCVE: https://stackoverflow.com/questions/52169831/syntaxerror-unexpected-identifier-jest-babel-7-react-native-0-56

**Comment by dulmandakh** [comment]
Updating babel to 7 is not recommended, it'll land in 0.57. Please use babel version from RN 0.56.

**Comment by asimolmez** [comment]
It worked, thanks @dulmandakh
