### ISSUE TITLE
Module AppRegistry is not a registered callable module

### ISSUE THREAD

**Issue by gifary** [facebook/react-native#21089]
**### Environment**

> React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.2
      CPU: x64 Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
      Memory: 46.80 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.2.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.1, 25.0.0, 25.0.1, 25.0.2, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3
        API Levels: 10, 21, 23, 24, 25, 26, 27, 7
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

Hello,

I am getting trouble when BUILD signed APK . My app always crash when open. When build as DEBUG APK it works properly.

My package json file
{
  "name": "HelloBeauty",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "react-devtools": "react-devtools"
  },
  "dependencies": {
    "@expo/vector-icons": "^6.3.1",
    "axios": "^0.18.0",
    "babel-plugin-transform-inline-environment-variables": "^0.4.3",
    "native-base": "^2.7.2",
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-calendars": "^1.20.0",
    "react-native-easy-grid": "^0.2.0",
    "react-native-image-picker": "^0.26.10",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-simple-radio-button": "^2.7.2",
    "react-native-spinkit": "^1.1.1",
    "react-navigation": "^2.11.2"
  },
  "devDependencies": {
    "babel-jest": "23.4.2",
    "babel-preset-react-native": "^5",
    "jest": "23.4.2",
    "react-devtools": "^3.2.3",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts/"
    ]
  }
}

**This is error what I get in android studio**

``Module AppRegistry is not a registered callable module (calling runApplication)
09-13 11:13:21.580 30979-31060/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                   Process: com.hellobeauty, PID: 30979
                                                   com.facebook.react.common.JavascriptException: Module AppRegistry is not a registered callable module (calling runApplication), stack:
                                                   value@25:3211
                                                   <unknown>@25:935
                                                   value@25:2621
                                                   value@25:907
                                                   
                                                       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
                                                       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
                                                       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
                                                       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                       at android.os.Handler.handleCallback(Handler.java:789)
                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
                                                       at java.lang.Thread.run(Thread.java:764)

**Comment by gifary** [comment]
I put Appregistry on index.js

Then in app/build/build.gradle, change the entryFile from app.js to index.js

project.ext.react = [
    entryFile: "index.js" // was app.js"
]

**Comment by Subway19** [comment]
Still getting this issue. 

```
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz
      Memory: 316.88 MB / 7.69 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.3.0 - ~/.nvm/versions/node/v8.3.0/bin/node
      npm: 5.3.0 - ~/.nvm/versions/node/v8.3.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 24.0.1, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64
    npmPackages:
      react: ^16.8.3 => 16.8.6 
      react-native: ^0.59.10 => 0.59.10 
```
