### ISSUE TITLE
java.lang.RuntimeException: Unable to instantiate application com.mywishtree.MainApplication: java.lang.ClassNotFoundException: Didn't find class "com.mywishtree.MainApplication" on path: DexPathList[[zip file "/data/app/com.mywishtree-2/base.apk"],nativeLibraryDirectories=[/data/app/com.mywishtree-2/lib/arm, /data/app/com.mywishtree-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]] 

### ISSUE THREAD

**Issue by 12343954** [facebook/react-native#21095]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
    System:
      OS: macOS High Sierra 10.13.5
      CPU: x64 Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
      Memory: 148.55 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.2.1 - /usr/local/bin/node
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 26.0.3, 27.0.3
        API Levels: 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.4 /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-debugger-open: 0.3.17
      react-native-git-upgrade: 0.2.7
```

## Description
I am testing in real machine（OPPO A1，ColorOS 3.2，Android 7.1.1）。After install and start  the app ，it crashed immediately！
but test in emulator（Pixel 2 XL API 28） is OK！

## Reproducible Demo

```
09/13 18:46:43: Launching app
$ adb install-multiple -r -t /Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/android/app/build/intermediates/split-apk/debug/slices/slice_9.apk /Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/android/app/build/intermediates/split-apk/debug/slices/slice_3.apk /Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/android/app/build/intermediates/split-apk/debug/slices/slice_4.apk /Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/android/app/build/intermediates/split-apk/debug/dep/dependencies.apk /Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/android/app/build/intermediates/split-apk/debug/slices/slice_2.apk /Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/android/app/build/intermediates/split-apk/debug/slices/slice_5.apk /Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/android/app/build/intermediates/split-apk/debug/slices/slice_0.apk /Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/android/app/build/intermediates/split-apk/debug/slices/slice_1.apk /Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/android/app/build/intermediates/split-apk/debug/slices/slice_7.apk /Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/android/app/build/intermediates/split-apk/debug/slices/slice_6.apk /Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/android/app/build/intermediates/split-apk/debug/slices/slice_8.apk /Users/mac/iOS-Dev/MyWishTree-iOS-RN0.56/MyWishTree/android/app/build/intermediates/instant-run-apk/debug/app-debug.apk 
Split APKs installed
$ adb shell am start -n "com.mywishtree/com.mywishtree.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: com.mywishtree.test | com.mywishtree
Waiting for application to come online: com.mywishtree.test | com.mywishtree
Waiting for application to come online: com.mywishtree.test | com.mywishtree
Connecting to com.mywishtree
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/ActivityThread: Application com.mywishtree is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/art: Debugger is active
I/System.out: Debugger has connected
I/System.out: waiting for debugger to settle...
Connected to the target VM, address: 'localhost:8618', transport: 'socket'
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1384)
I/art: Starting a blocking GC HeapTrim
D/AndroidRuntime: Shutting down VM


                  --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.mywishtree, PID: 5947
                  java.lang.RuntimeException: Unable to instantiate application com.mywishtree.MainApplication: java.lang.ClassNotFoundException: Didn't find class "com.mywishtree.MainApplication" on path: DexPathList[[zip file "/data/app/com.mywishtree-2/base.apk"],nativeLibraryDirectories=[/data/app/com.mywishtree-2/lib/arm, /data/app/com.mywishtree-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                      at android.app.LoadedApk.makeApplication(LoadedApk.java:862)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5903)
                      at android.app.ActivityThread.-wrap2(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784)
                      at android.os.Handler.dispatchMessage(Handler.java:110)
                      at android.os.Looper.loop(Looper.java:232)
                      at android.app.ActivityThread.main(ActivityThread.java:6802)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mywishtree.MainApplication" on path: DexPathList[[zip file "/data/app/com.mywishtree-2/base.apk"],nativeLibraryDirectories=[/data/app/com.mywishtree-2/lib/arm, /data/app/com.mywishtree-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at android.app.Instrumentation.newApplication(Instrumentation.java:992)
                      at android.app.LoadedApk.makeApplication(LoadedApk.java:856)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5903) 
                      at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784) 
                      at android.os.Handler.dispatchMessage(Handler.java:110) 
                      at android.os.Looper.loop(Looper.java:232) 
                      at android.app.ActivityThread.main(ActivityThread.java:6802) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 
Disconnected from the target VM, address: 'localhost:8618', transport: 'socket'

```

**Comment by 12343954** [comment]
【Temporary solution】
Not the best way

![image](https://user-images.githubusercontent.com/1804003/45554205-65dea600-b868-11e8-8fe1-3eb67e2550b7.png)

**Comment by Jeijie** [comment]
any updates? I have this issue yet?

**Comment by luojin** [comment]
> 【Temporary solution】
> Not the best way
> 
> ![image](https://user-images.githubusercontent.com/1804003/45554205-65dea600-b868-11e8-8fe1-3eb67e2550b7.png)

good answer

**Comment by marco-solari** [comment]
Didn't work for me

```
$ react-native info

  React Native Environment Info:
    System:
      OS: Linux 4.18 Ubuntu 18.04.2 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i5-4460S CPU @ 2.90GHz
      Memory: 2.11 GB / 15.58 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 11.14.0 - ~/.nvm/versions/node/v11.14.0/bin/node
      Yarn: 1.16.0 - /usr/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.14.0/bin/npm
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.7 => 0.57.7 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by yestay90** [comment]
Also Didnt work for me 

 React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
      Memory: 386.03 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 26, 27, 28, 29
        Build Tools: 27.0.3, 28.0.3
        System Images: android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
