### ISSUE TITLE
react native jest cli unable to install

### ISSUE THREAD

**Issue by piyushchauhan2011** [facebook/react-native#2119]
I'm getting this error when I run `npm install jest-cli --save-dev`.

`react-native 0.8.0`
`iojs 2.4.0`

```
npm WARN engine jest-cli@0.4.17: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"2.4.0","npm":"2.13.0"})

> contextify@0.1.14 install /Users/kartikeychauhan/Documents/testcodes/react-native-test/Docit/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 response dowloading http://nodejs.org/dist/v2.4.0/node-v2.4.0.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:985:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/usr/local/Cellar/iojs/2.4.0/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kartikeychauhan/Documents/testcodes/react-native-test/Docit/node_modules/jest-cli/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v2.4.0
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/Cellar/iojs/2.4.0/bin/iojs" "/usr/local/bin/npm" "install" "jest-cli" "--save-dev"
npm ERR! node v2.4.0
npm ERR! npm  v2.13.0
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kartikeychauhan/Documents/testcodes/react-native-test/Docit/npm-debug.log
```

**Comment by ide** [comment]
> npm WARN engine jest-cli@0.4.17: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"2.4.0","npm":"2.13.0"})

There's your issue; get the 0.5.x branch of jest straight from github.
