### ISSUE TITLE
`react-native init` fails on 0.57 with missing babel plugin

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#21219]
One of React Native dependencies, Metro, [depends](https://github.com/facebook/metro/blob/master/packages/metro/src/reactNativeTransformer.js#L15) on a package that it does not specify in its package.json.

It is causing the following error:
```
Loading dependency graph, done.
error: bundling failed: Error: Cannot find module '@babel/plugin-external-helpers'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/grabbou/Repositories/DemoNewNew/node_modules/metro/src/reactNativeTransformer.js:15:31)
```
when running a new project.

To reproduce, run `react-native init Test` and then, attempt running the project.

For now, add this package as a dependency of your project explicitly and wait for a new release.

**Comment by yooouuri** [comment]
#21214

**Comment by grabbou** [comment]
Closing in favor of that one.
