### ISSUE TITLE
Error: Cannot find module 'escape-string-regexp'

### ISSUE THREAD

**Issue by xxccll** [facebook/react-native#2122]
when I run the Examples,the terminal says

module.js:338
    throw err;
          ^
Error: Cannot find module 'escape-string-regexp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/xxxx/Dev/GitHubLibrary/react-native/node_modules/chalk/index.js:2:26)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

how to fix it?

**Comment by jdstein1** [comment]
I am having same issue.  Happens when running `yo gulp-angular [app-name]`.

**Comment by wenpingzheng** [comment]
I am having same issue.
