### ISSUE TITLE
"npm start" error, Path must be a string. Received null

### ISSUE THREAD

**Issue by silentcloud** [facebook/react-native#2132]
iojs v2.4.0, react-native 0.7.1, Mac OS X 10.11 beta

iOS Simulator shows:

{"type":"InternalError","Message":"react-packager has encountered an internal error, please check your terminal error output for more details"}

<START> request:/index.ios.bundle
TypeError: Path must be a string. Received null
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:427:5)
    at /Users/silentcloud/Workspace/AntRN/react-native-homeproject/FTHome/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/index.js:152:33
    at tryCallOne (/Users/silentcloud/Workspace/AntRN/react-native-homeproject/FTHome/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/silentcloud/Workspace/AntRN/react-native-homeproject/FTHome/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/silentcloud/Workspace/AntRN/react-native-homeproject/FTHome/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)

**Comment by silentcloud** [comment]
File Path error

**Comment by fatuhoku** [comment]
@silentcloud So what was the issue?
