### ISSUE TITLE
React Packager crashes because it doesn't understand the rest spread operator.

### ISSUE THREAD

**Issue by rollokb** [facebook/react-native#2134]
The latest commit a803e3217e5aa88da4c05e96d54209444c96ebee fails to build any project.

    [rollo@Rollos-iMac my_project]$ npm start

    > my_project@0.0.1 start /Users/rollo/Developer/my_project
    > node_modules/react-native/packager/packager.sh

    /Users/rollo/Developer/my_project/node_modules/react-native/packager/react-packager/src/FileWatcher/index.js:51
    function(...args){return _this.emit.apply(_this,['all'].concat(args));});});
             ^^^
    SyntaxError: Unexpected token ...
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:413:25)
        at normalLoader (/Users/rollo/Developer/my_project/node_modules/react-native/node_modules/babel-core/lib/api/register/node.js:199:5)
        at Object.require.extensions.(anonymous function) [as .js] (/Users/rollo/Developer/my_project/node_modules/react-native/node_modules/babel-core/lib/api/register/node.js:216:7)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/Users/rollo/Developer/my_project/node_modules/react-native/packager/react-packager/src/Server/index.js:14:19)
        at Module._compile (module.js:430:26)

This problem arose at this commit 

https://github.com/facebook/react-native/commit/1109ce3b8cc43aa15f1c0b222fad8d9af4b3c13c

The packager will run if I change the `.babelrc` file https://github.com/facebook/react-native/blob/master/packager/react-packager/.babelrc

And change `es6.parameters.rest` to `es6.parameters`

The packager then runs but, it fails to transpile any rest spread operators meaning my app crashes with a syntax error in warning.js, 

    SyntaxError: Unexpected token '...'. Expected a parameter pattern or a ')' in a parameter list.

**Comment by dsibiski** [comment]
@rollokb I'm having the same issue on a fresh app. This seems to be something that is being worked on in https://github.com/facebook/react-native/pull/1753

**Comment by dsibiski** [comment]
It seems like force updating babel-core works: https://github.com/evansolomon/react-native/commit/2940387933820c8981379dcb8335ccc8c0c9db90#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R50

I'm sure this will be merged into master soon.

**Comment by dsibiski** [comment]
It seems like this is a problem with Babel and they may have fixed it in their development branch: https://github.com/babel/babel/commit/57d2323ae91d3bc3887acefd7ce74e34f8784743

**Comment by rollokb** [comment]
Thanks @dsibiski, that fixed the problem.
