### ISSUE TITLE
":CFBundleIdentifier", Does Not Exist, in Mac OSX Mojave xcode 10

### ISSUE THREAD

**Issue by kardoqadir** [facebook/react-native#21381]
After installing new OSX Mojave, when I try to run new projects the process will fail and asks that  ":CFBundleIdentifier", Does Not Exist.

```
** BUILD FAILED **
The following build commands failed:
	CompileC /Users/kardoqadir/apps/myApp/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/third-party.build/Objects-normal/x86_64/json.o /Users/kardoqadir/apps/myApp/node_modules/react-native/third-party/folly-2016.10.31.00/folly/json.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/myApp.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/myApp.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/myApp.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:13)
    at Promise.then (/Users/kardoqadir/apps/myApp/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)

```
This my system information

```
System Version: macOS 10.14 (18A391)
Kernel Version: Darwin 18.0.0
Xcode:  10.0 (10A255)
```

what is the problem? How can I fix it?

**Comment by Gaever** [comment]
I had similar issue installing react native navigation on blank project with following message:
```

The following build commands failed:

	Ld /Users/gaever/Documents/ppf/ppfmaa/ios/build/Build/Products/Debug-iphonesimulator/ReactNativeNavigationTests.xctest/ReactNativeNavigationTests normal x86_64
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/PPFAgent.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/PPFAgent.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist


Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/PPFAgent.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:13)
    at Promise.then (/Users/gaever/Documents/ppf/ppfmaa/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)
```

Excluding ReactNativeNavigationTests.xctest from "Build Phases > Link Binary With Libraries" solved problem. 

Xcode, macos, rn - everything is fresh and up to date.

**Comment by kardoqadir** [comment]
[check here](https://github.com/facebook/react-native/issues/21382)
