### ISSUE TITLE
[Flaky Test] Animated-test

### ISSUE THREAD

**Issue by TheSavior** [facebook/react-native#21517]
`Animated-test.js` has been flaky and causing CI builds to fail. Here is an example: https://circleci.com/gh/facebook/react-native/55576?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

This test was also disabled automatically at Facebook due to flakiness:
Flakiness Score: 11%

```
FAIL  Libraries/Animated/src/__tests__/Animated-test.js
  ● Animated tests › Animated › send toValue when an underdamped spring stops

    Ran 100000 timers, and there are still more! Assuming we've hit an infinite recursion and bailing out...

      140 |       anim.addListener(listener);
      141 |       Animated.spring(anim, {toValue: 15}).start();
    > 142 |       jest.runAllTimers();
          |            ^
      143 |       const lastValue =
      144 |         listener.mock.calls[listener.mock.calls.length - 2][0].value;
      145 |       expect(lastValue).not.toBe(15);

      at FakeTimers.runAllTimers (node_modules/jest-util/build/fake_timers.js:195:13)
      at Object.<anonymous> (Libraries/Animated/src/__tests__/Animated-test.js:142:12)
```

**Comment by TheSavior** [comment]
@janicduplessis, any ideas here?

**Comment by hramos** [comment]
lol @react-native-bot (@TheSavior, I'll whitelist you from these)
