### ISSUE TITLE
V0.57 runtime expception

### ISSUE THREAD

**Issue by cnscns** [facebook/react-native#21526]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.

## Description
2018-10-06 14:31:44.228 18032-18032/org.jitsi.meet E/RNImmersiveModule: emitImmersiveStateChangeEvent() failed!
    java.lang.RuntimeException: Tried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should only happen once initialize() has been called on your native module.
        at com.facebook.react.bridge.ReactContext.getJSModule(ReactContext.java:98)
        at com.rnimmersive.RNImmersiveModule.emitImmersiveStateChangeEvent(RNImmersiveModule.java:74)
        at org.jitsi.meet.sdk.BaseReactView.onWindowFocusChanged(BaseReactView.java:206)
        at android.view.View.dispatchWindowFocusChanged(View.java:10247)
        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1192)
        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1196)
        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1196)
        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1196)
        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1196)
        at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1196)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3871)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6623)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by cnscns** [comment]
Thanks! I have sloved this problem by excuting: react-native start --reset-cache
