### ISSUE TITLE
get an error when react-native init

### ISSUE THREAD

**Issue by lizhecome** [facebook/react-native#2158]
this is the error log, please check , thx
```
macdeMBP:codebox mac$ react-native init AwesomeProject111
This will walk you through creating a new React Native project in /Users/mac/codebox/AwesomeProject111
npm WARN engine stacktrace-parser@0.1.1: wanted: {"node":"~0.10"} (current: {"node":"2.0.2","npm":"2.11.3"})
 
> ws@0.4.31 install /Users/mac/codebox/AwesomeProject111/node_modules/react-native/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

 
> fsevents@0.3.6 install /Users/mac/codebox/AwesomeProject111/node_modules/react-native/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response dowloading http://nodejs.org/dist/v2.0.2/node-v2.0.2.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1142:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:414:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:304:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/usr/local/Cellar/iojs/2.0.2/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mac/codebox/AwesomeProject111/node_modules/react-native/node_modules/babel/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v2.0.2
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.3.6
react-native@0.8.0 node_modules/react-native
├── absolute-path@0.0.0
├── stacktrace-parser@0.1.1
├── graceful-fs@3.0.8
├── react-timer-mixin@0.13.2
├── wordwrap@1.0.0
├── underscore@1.7.0
├── image-size@0.3.5
├── semver@4.3.6
├── yargs@1.3.2
├── immutable@3.7.4
├── debug@2.1.3 (ms@0.7.0)
├── bluebird@2.9.34
├── promise@7.0.3 (asap@2.0.3)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── source-map@0.1.31 (amdefine@1.0.0)
├── rebound@0.0.12
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── worker-farm@1.3.1 (xtend@4.0.0, errno@0.1.3)
├── uglify-js@2.4.24 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.5.4, source-map@0.1.34)
├── sane@1.1.3 (watch@0.10.0, minimist@1.1.2, exec-sh@0.2.0, fb-watchman@1.2.0, minimatch@0.2.14, walker@1.0.7)
├── connect@2.8.3 (methods@0.0.1, uid2@0.0.2, fresh@0.1.0, pause@0.0.1, cookie-signature@1.0.1, qs@0.6.5, bytes@0.2.0, buffer-crc32@0.2.1, cookie@0.1.0, formidable@1.0.14, send@0.1.2)
├── ws@0.4.31 (tinycolor@0.0.1, options@0.0.6, commander@0.6.1, nan@0.3.2)
├── jstransform@11.0.1 (object-assign@2.1.1, base62@1.1.0, source-map@0.4.4, commoner@0.10.3, esprima-fb@15001.1.0-dev-harmony-fb)
├── module-deps@3.5.6 (inherits@2.0.1, shallow-copy@0.0.1, duplexer2@0.0.2, minimist@0.2.0, subarg@0.0.1, parents@1.0.1, concat-stream@1.4.10, resolve@0.7.4, readable-stream@1.1.13, through2@0.4.2, stream-combiner2@1.0.2, browser-resolve@1.9.0, JSONStream@0.7.4, detective@3.1.0)
├── react-tools@0.13.2 (jstransform@10.1.0, commoner@0.10.3)
├── joi@5.1.0 (topo@1.0.2, isemail@1.1.1, hoek@2.14.0, moment@2.10.6)
├── babel@5.4.3 (slash@1.0.0, path-is-absolute@1.0.0, fs-readdir-recursive@0.1.2, convert-source-map@1.1.1, source-map@0.4.4, commander@2.8.1, output-file-sync@1.1.1, glob@5.0.14, lodash@3.10.0, chokidar@1.0.5)
└── babel-core@5.8.14 (slash@1.0.0, try-resolve@1.0.1, babel-plugin-remove-debugger@1.0.1, babel-plugin-remove-console@1.0.1, babel-plugin-inline-environment-variables@1.0.1, babel-plugin-eval@1.0.1, babel-plugin-react-constant-elements@1.0.3, babel-plugin-jscript@1.0.4, babel-plugin-undefined-to-void@1.1.6, babel-plugin-property-literals@1.0.1, to-fast-properties@1.0.1, trim-right@1.0.1, babel-plugin-member-expression-literals@1.0.1, shebang-regex@1.0.0, path-is-absolute@1.0.0, babel-plugin-react-display-name@1.0.3, path-exists@1.0.0, fs-readdir-recursive@0.1.2, babel-plugin-constant-folding@1.0.1, babel-plugin-proto-to-assign@1.0.4, babel-plugin-dead-code-elimination@1.0.2, strip-json-comments@1.0.2, babel-plugin-runtime@1.0.7, private@0.1.6, globals@6.4.1, esutils@2.0.2, convert-source-map@1.1.1, js-tokens@1.0.1, babylon@5.8.13, minimatch@2.0.10, resolve@1.1.6, home-or-tmp@1.0.0, babel-plugin-undeclared-variables-check@1.0.2, line-numbers@0.2.0, detect-indent@3.0.1, output-file-sync@1.1.1, source-map@0.4.4, source-map-support@0.2.10, repeating@1.1.3, regexpu@1.2.0, is-integer@1.0.4, lodash@3.10.0, core-js@0.9.18, regenerator@0.8.34)
Setting up new React Native app in /Users/mac/codebox/AwesomeProject111
Next Steps:
   Open /Users/mac/codebox/AwesomeProject111/AwesomeProject111.xcodeproj in Xcode
   Hit Run button
```

**Comment by browniefed** [comment]
io.js and node-gyp aren't playing nicely together at the moment, however you project still got all setup and will likely work.
If you don't want to see the error you can use something like nvm and switch to using a node.js version to install. However with .80 and on io.js is the desired javascript runner for react-native.

**Comment by lizhecome** [comment]
if ignore the error, and run the demo, i will get this error
![](http://7xkda0.com1.z0.glb.clouddn.com/15-7-29/63990296.jpg)

and here is the log
```
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/mac/codebox/AwesomeProject1231 


React packager ready.

[11:25:37] <START> fs crawl
TypeError: Cannot read property 'root' of null
    at /Users/mac/codebox/AwesomeProject1231/node_modules/react-native/packager/react-packager/src/DependencyResolver/crawlers/index.js:16:84
    at tryCallOne (/Users/mac/codebox/AwesomeProject1231/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/mac/codebox/AwesomeProject1231/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/mac/codebox/AwesomeProject1231/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
[11:26:10] <START> request:/index.ios.bundle
[11:26:10] <START> find dependencies
```

**Comment by browniefed** [comment]
Ah so that's how that error manifests itself. Well try installing node, I recommend using NVM to manage your node versions. Then re-init a new app using node instead of io.js.

**Comment by ide** [comment]
@lizhecome looking at your error log, I believe none of those errors are fatal or should be affecting your React Native installation. The error is with building fsevents which is one of Babel's optional dependencies and isn't used by React Native at all. So I think `npm install` went fine for you.

The error with "Cannot read property 'root' of null" is related to Watchman in my experience. Make sure you have the most up-to-date copy of Watchman (`brew update; brew upgrade` -- you may want to put this in a nightly crontab), and then restart it with `watchman shutdown-server`. If that doesn't work, I've seen that rebooting the computer can sometimes help.

@browniefed's suggestion of getting nvm is really good though I would recommend using nvm to install io.js. Using legacy Node is going to cause issues for you in the future as it gets more outdated and npm package maintainers increasingly support only 1.x or 2.x and can't afford to support old releases like 0.12.

**Comment by lizhecome** [comment]
thanks，everything goes well after reinstall watchman

**Comment by walter211** [comment]
hey, how guy solves ,seems  i need install every node module used by react manually. I reinstall npm and watchman both make nothing works, pls help...

**Comment by mydearxym** [comment]
still have this issue after watchman reinstalled !

**Comment by idevz** [comment]
@mydearxym  you can try this
```
brew update
brew upgrade watchman
```
if you got an error when you update brew, you may need this
```
cd /usr/local
git reset --hard origin/master
git clean -f
brew update
```
