### ISSUE TITLE
[TypeScript] Unable to resolve defined paths in tsconfig

### ISSUE THREAD

**Issue by dawidk92** [facebook/react-native#21804]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
 React Native Environment Info:

    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 36.55 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash

    Binaries:
      Node: 10.4.0 - ~/.nvm/versions/node/v10.4.0/bin/node
      Yarn: 1.7.0 - ~/.nvm/versions/node/v10.4.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman

    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 27.0.3
        API Levels: 23, 25, 26, 27

    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild

    npmPackages:
      @storybook/react: ^4.0.0-alpha.22 => 4.0.0-alpha.24 
      @storybook/react-native: ^4.0.0-alpha.22 => 4.0.0-alpha.24 
      @types/react: ^16.4.11 => 16.4.16 
      @types/react-native: ^0.56.12 => 0.56.24 
      react: 16.4.0 => 16.4.0 
      react-native: 0.57.3 => 0.57.3 

    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

## Description
React Native doesn't resolve custom paths defined in `tsconfig.json` for [example](https://github.com/leebenson/reactql/blob/master/tsconfig.json) like this:
```json
{
  "paths": {
    "@/*": ["src/*"]
  }
}
````

It throws error:
```
error: bundling failed: TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo ([project_path]/node_modules/@babel/traverse/lib/scope/index.js:867:13)
    at BlockScoping.updateScopeInfo ([project_path]/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:364:17)
    at BlockScoping.run ([project_path]/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:330:12)
    at PluginPass.BlockStatementSwitchStatementProgram ([project_path]/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:70:24)
    at newFn ([project_path]/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call ([project_path]/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call ([project_path]/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit ([project_path]/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue ([project_path]/node_modules/@babel/traverse/lib/context.js:118:16)
```

**Comment by dawidk92** [comment]
Hi @rodrigoelp, I want to configure path to my src files so I could import for example my utils like this:
```js
@import { SomeUtils } from "@/utils";
```

Instead of e.g.:
```js
@import { SomeUtils } from "../../../../utils";
```

Thanks to `paths` in `tsconfig` you can configure custom absolute paths istead of using relative ones.

**Comment by dawidk92** [comment]
I found solution for this problem:
https://github.com/react-community/create-react-native-app/issues/232#issuecomment-343717596

This issue can be closed :)

**Comment by Gapur** [comment]
You can use absolute paths like in this article

https://medium.com/better-programming/using-absolute-paths-in-react-native-3be369244fb1

I hope you found this piece useful.
