### ISSUE TITLE
Can't bundle android using React Native v0.57.x

### ISSUE THREAD

**Issue by renalpraba** [facebook/react-native#21825]
- I have review the [documentation](https://facebook.github.io/react-native)
  - I have search for existing issues
  - I am using React Native version 0.57.1

## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
      Memory: 361.90 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 9.11.2 - /usr/local/bin/node
      Yarn: 1.12.0 - /usr/local/bin/yarn
      npm: 5.10.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.1 => 0.57.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
When bundling for android using

> react-native bundle --dev false --platform android --entry-file index.js --bundle-output ./android/app/build/intermediates/assets/debug/index.android.bundle --assets-dest ./android/app/build/intermediates/res/merged/debug && cd android && ./gradlew assembledebug && cd ..

 command in react native 0.57.x it always give me

```
Unable to resolve module `@babel/runtime/helpers/interopRequireDefault` from `/Users/crocodic/Desktop/Coba/index.js`: Module `@babel/runtime/helpers/interopRequireDefault` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.

Error: Unable to resolve module `@babel/runtime/helpers/interopRequireDefault` from `/Users/crocodic/Desktop/Coba/index.js`: Module `@babel/runtime/helpers/interopRequireDefault` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/crocodic/Desktop/Coba/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:209:1301)
    at ResolutionRequest.resolveDependency (/Users/crocodic/Desktop/Coba/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:83:16)
    at DependencyGraph.resolveDependency (/Users/crocodic/Desktop/Coba/node_modules/metro/src/node-haste/DependencyGraph.js:238:485)
    at Object.resolve (/Users/crocodic/Desktop/Coba/node_modules/metro/src/lib/transformHelpers.js:180:25)
    at dependencies.map.result (/Users/crocodic/Desktop/Coba/node_modules/metro/src/DeltaBundler/traverseDependencies.js:311:29)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/crocodic/Desktop/Coba/node_modules/metro/src/DeltaBundler/traverseDependencies.js:307:16)
    at /Users/crocodic/Desktop/Coba/node_modules/metro/src/DeltaBundler/traverseDependencies.js:164:33
    at Generator.next (<anonymous>)
    at step (/Users/crocodic/Desktop/Coba/node_modules/metro/src/DeltaBundler/traverseDependencies.js:266:307)
```

## Reproducible Demo
Init new project using react native 0.57.x and bundle using above command

**Comment by fantasy525** [comment]
> `npm add @babel/runtime` should resolve this issue

`npm install --save @babel/runtime`? or `npm isntall --save-dev @babel/runtime`?

**Comment by renalpraba** [comment]
@fantasy525 yeah i edited my comment to --save-dev, it works too and I prefer it because it will save the package only for development purpose
