### ISSUE TITLE
Unable to build the app successfully. Execution failed for task ':app:mergeDebugResources'.

### ISSUE THREAD

**Issue by mukherjeesrijan2** [facebook/react-native#21904]
I was just getting started with react native and I encountered some problem while building the app.

Here's the error:
(Complete log)

    Starting JS server...
    Building and installing the app on the device (cd android && ./gradlew installDebug)...
    AAPT err(Facade for 33021040): /home/srijan/Android/build-tools/27.0.3/aapt2: 1: /home/srijan/Android/build-tools/27.0.3/aapt2: Syntax error: "(" unexpected
    Slave 33021040 failed to start
    java.lang.RuntimeException: AAPT slave failed to start. Please make sure the current build tools (located at /home/srijan/Android/build-tools/27.0.3/aapt2) are not corrupted.
        at com.android.builder.png.AaptProcess.waitForReadyOrFail(AaptProcess.java:193)
        at com.android.builder.internal.aapt.AaptQueueThreadContext.creation(AaptQueueThreadContext.java:56)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:250)
        at java.lang.Thread.run(Thread.java:748)
    AAPT err(Facade for 26937763): /home/srijan/Android/build-tools/27.0.3/aapt2: 1: /home/srijan/Android/build-tools/27.0.3/aapt2: Syntax error: "(" unexpected
    Slave 26937763 failed to start
    java.lang.RuntimeException: AAPT slave failed to start. Please make sure the current build tools (located at /home/srijan/Android/build-tools/27.0.3/aapt2) are not corrupted.
        at com.android.builder.png.AaptProcess.waitForReadyOrFail(AaptProcess.java:193)
        at com.android.builder.internal.aapt.AaptQueueThreadContext.creation(AaptQueueThreadContext.java:56)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:250)
        at java.lang.Thread.run(Thread.java:748)
    Exception in thread "queued-resource-processor_2"     java.util.MissingFormatArgumentException: Format specifier '%1$s'
        at java.util.Formatter.format(Formatter.java:2525)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2940)
        at com.android.build.gradle.internal.aapt.AaptGradleFactory$FilteringLogger.shouldDowngrade(AaptGradleFactory.java:156)
        at com.android.build.gradle.internal.aapt.AaptGradleFactory$FilteringLogger.error(AaptGradleFactory.java:122)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:253)
        at java.lang.Thread.run(Thread.java:748)
    Exception in thread "queued-resource-processor_1"  

    java.util.MissingFormatArgumentException: Format specifier '%1$s'
        at java.util.Formatter.format(Formatter.java:2525)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2940)
        at com.android.build.gradle.internal.aapt.AaptGradleFactory$FilteringLogger.shouldDowngrade(AaptGradleFactory.java:156)
        at com.android.build.gradle.internal.aapt.AaptGradleFactory$FilteringLogger.error(AaptGradleFactory.java:122)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:253)
        at java.lang.Thread.run(Thread.java:748)

    > Task :app:mergeDebugResources FAILED
    Error: java.util.concurrent.ExecutionException: java.lang.RuntimeException: No server to serve request. Check logs for details.

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':app:mergeDebugResources'.
    > Error: java.util.concurrent.ExecutionException: java.lang.RuntimeException: No server to serve request. Check logs for details.

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 4s
    9 actionable tasks: 1 executed, 8 up-to-date
    Could not install the app on the device, read the error above for details.
    Make sure you have an Android emulator running or a device connected and have
    set up your Android development environment:
    https://facebook.github.io/react-native/docs/getting-started.html

So this is the error
Kindly help me troubleshoot this thing.

Also I tried, re-downloading build-tools 27.0.3 with the sdkmanager cli.

**Comment by mukherjeesrijan2** [comment]
I think I have found the solution. I was using 32bit os and the android tools supports only 64bit for linux. Upgrading the os to 64bit seems to work.
