### ISSUE TITLE
App stopping in release APK but works fine in debug APK

### ISSUE THREAD

**Issue by Ash-faq** [facebook/react-native#21920]
### Getting this error in logcat while trying to open the release APK 

2018-10-24 14:34:27.792 1161-1878/? E/ActivityManager: applyOptionsLocked: Unknown animationType=0
2018-10-24 14:34:27.813 20034-20034/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2018-10-24 14:34:27.814 20034-20034/? E/libpersona: scanKnoxPersonas
2018-10-24 14:34:27.814 20034-20034/? E/libpersona: Couldn't open the File - /data/system/users/0/personalist.xml - No such file or directory
2018-10-24 14:34:27.818 1161-1211/? E/ViewRootImpl: sendUserActionEvent() returned.
2018-10-24 14:34:28.165 1161-1219/? E/ANDR-PERF-JNI: com_qualcomm_qtiperformance_native_perf_io_prefetch_start
2018-10-24 14:34:28.294 1161-1310/? E/WindowManager: win=Window{f201cfd u0 com.google.android.apps.docs/com.google.android.apps.docs.doclist.activity.DocListActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8, caller=com.android.server.wm.AppWindowToken.destroySurfaces:748 com.android.server.wm.AppWindowToken.destroySurfaces:732 com.android.server.wm.WindowState.onExitAnimationDone:5523 com.android.server.wm.AppWindowAnimator.stepAnimationLocked:517 com.android.server.wm.AppWindowToken.stepAppWindowsAnimation:1745 
2018-10-24 14:34:28.296 1161-1310/? E/WindowManager: win=Window{107619a u0 Splash Screen com.ivycpg_product_rn_mobileapp EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0, caller=com.android.server.wm.AppWindowToken.destroySurfaces:748 com.android.server.wm.AppWindowToken.destroySurfaces:732 com.android.server.wm.WindowState.onExitAnimationDone:5523 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:553 com.android.server.wm.DisplayContent.lambda$-com_android_server_wm_DisplayContent_21292:465 
2018-10-24 14:34:29.674 20034-20058/? E/ReactNativeJS: undefined is not an object (evaluating 'p.View.propTypes.style')
2018-10-24 14:34:29.682 20034-20058/? E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
2018-10-24 14:34:29.692 20034-20059/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.ivycpg_product_rn_mobileapp, PID: 20034
    com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'p.View.propTypes.style'), stack:
    <unknown>@1050:7571
    d@2:1540
    a@2:997
    o@2:850
    <unknown>@1049:32
    d@2:1540
    a@2:997
    o@2:850
    <unknown>@1006:2426
    d@2:1540
    a@2:997
    o@2:850
    <unknown>@339:663
    d@2:1540
    a@2:997
    o@2:850
    <unknown>@338:692
    d@2:1540
    a@2:997
    o@2:850
    <unknown>@12:92
    d@2:1540
    a@2:927
    o@2:850
    global code@1079:8
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:764)
2018-10-24 14:34:30.617 1161-1310/? E/WindowManager: win=Window{eb1859f u0 com.ivycpg_product_rn_mobileapp/com.ivycpg_product_rn_mobileapp.MainActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8, caller=com.android.server.wm.AppWindowToken.destroySurfaces:748 com.android.server.wm.AppWindowToken.destroySurfaces:732 com.android.server.wm.WindowState.onExitAnimationDone:5523 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:553 com.android.server.wm.DisplayContent.lambda$-com_android_server_wm_DisplayContent_21292:465 
2018-10-24 14:34:30.641 20034-20058/? E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag)
2018-10-24 14:34:44.868 1161-1726/? E/Watchdog: !@Sync 4104 [2018-10-24 14:34:44.868]

can some one explain this..?

**Comment by Ash-faq** [comment]
@react-native-bot could you help on this
