### ISSUE TITLE
Could no connect to development server

### ISSUE THREAD

**Issue by mandala21** [facebook/react-native#22235]
I started an application in react, using the react-native init.
I configured android studios everything ok, the compilation of the right one but when I open the app I get the error of Could not connect to development server.
Already tried to start the server in the hand with the command npm start, react-native start and both return the same error:
Loading dependency graph...fs.js:1384
    throw error;
    ^

Error: watch /home/lucas/source/kerokarona2/node_modules/@babel/plugin-syntax-typescript ENOSPC
    at _errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at NodeWatcher.watchdir (/home/lucas/source/kerokarona2/node_modules/sane/src/node_watcher.js:159:22)
    at Walker.<anonymous> (/home/lucas/source/kerokarona2/node_modules/sane/src/common.js:109:31)
    at emitTwo (events.js:126:13)
    at Walker.emit (events.js:214:7)
    at /home/lucas/source/kerokarona2/node_modules/walker/lib/walker.js:69:16
    at go$readdir$cb (/home/lucas/source/kerokarona2/node_modules/graceful-fs/graceful-fs.js:162:14)
    at FSReqWrap.oncomplete (fs.js:135:15)

## Environment
npm 3.5.2
v8.10.0

## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.
  "dependencies": {
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.4"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.49.0",
    "react-test-renderer": "16.6.0-alpha.8af6728"
  }
javac 1.8.0_191
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by mandala21** [comment]
forget this, i runned react-native with sudo it is running perfect :).
