### ISSUE TITLE
RN doesn't work with yarn workspaces

### ISSUE THREAD

**Issue by samu** [facebook/react-native#22247]
## Environment
```
React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 3.36 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.2 - ~/.nvm/versions/node/v8.11.2/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v8.11.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
    IDEs:
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description
RN doesn't work with yarn workspaces. When i try to start the simulator, i get the following error: 

```
Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/rnproject.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist


Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/rnproject.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:601:13)
    at Object.execFileSync (child_process.js:621:13)
    at Promise.then (/Users/taamusa8/Code/nohoist-repro/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)
    at <anonymous>
```

## Reproducible Demo

Start in an empty folder.

1. `react-native init rnproject`
2. `rm -rf rnproject/node_modules`
3. Add package.json:
```
{
  "private": true,
  "workspaces": [
    "rnproject"
  ]
}
```
4. `yarn install`
5. `cd rnproject`
6. `yarn start`

**Comment by samu** [comment]
Closing as this should probably be on the yarn repo
