### ISSUE TITLE
Unable to run release build

### ISSUE THREAD

**Issue by isaaclem** [facebook/react-native#22335]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.

```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 26.61 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.0.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.1, 28.0.2
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.5 => 0.57.5
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7
```

## Description
Running the below command to build and hit exception:
```
xcodebuild clean build -project UdemyFastlaneXX.xcodeproj -configuration Release -scheme UdemyFastlaneXX
```

**EXCEPTIONS**
```
SHA-1 for file /Users/isaac/code/reactnative/UdemyFastlaneXX/index.js is not computed

ReferenceError: SHA-1 for file /Users/isaac/code/reactnative/UdemyFastlaneXX/index.js is not computed
    at DependencyGraph.getSha1 (/Users/isaac/code/reactnative/UdemyFastlaneXX/node_modules/metro/src/node-haste/DependencyGraph.js:201:13)
    at /Users/isaac/code/reactnative/UdemyFastlaneXX/node_modules/metro/src/DeltaBundler/Transformer.js:164:26
    at Generator.next (<anonymous>)
    at step (/Users/isaac/code/reactnative/UdemyFastlaneXX/node_modules/metro/src/DeltaBundler/Transformer.js:31:30)
    at /Users/isaac/code/reactnative/UdemyFastlaneXX/node_modules/metro/src/DeltaBundler/Transformer.js:50:14
    at new Promise (<anonymous>)
    at /Users/isaac/code/reactnative/UdemyFastlaneXX/node_modules/metro/src/DeltaBundler/Transformer.js:28:12
    at Transformer.transformFile (/Users/isaac/code/reactnative/UdemyFastlaneXX/node_modules/metro/src/DeltaBundler/Transformer.js:188:7)
    at /Users/isaac/code/reactnative/UdemyFastlaneXX/node_modules/metro/src/Bundler.js:78:34
    at Generator.next (<anonymous>)

+ [[ false != true ]]
+ [[ ! -f /Users/isaac/Library/Developer/Xcode/DerivedData/UdemyFastlaneXX-eltuekpfuqqbnmboxhdjzwuzjcis/Build/Products/Release-iphoneos/UdemyFastlaneXX.app/main.jsbundle ]]
+ echo 'error: File /Users/isaac/Library/Developer/Xcode/DerivedData/UdemyFastlaneXX-eltuekpfuqqbnmboxhdjzwuzjcis/Build/Products/Release-iphoneos/UdemyFastlaneXX.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/isaac/Library/Developer/Xcode/DerivedData/UdemyFastlaneXX-eltuekpfuqqbnmboxhdjzwuzjcis/Build/Products/Release-iphoneos/UdemyFastlaneXX.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2

GenerateDSYMFile /Users/isaac/Library/Developer/Xcode/DerivedData/UdemyFastlaneXX-eltuekpfuqqbnmboxhdjzwuzjcis/Build/Products/Release-iphoneos/UdemyFastlaneXX.app.dSYM /Users/isaac/Library/Developer/Xcode/DerivedData/UdemyFastlaneXX-eltuekpfuqqbnmboxhdjzwuzjcis/Build/Products/Release-iphoneos/UdemyFastlaneXX.app/UdemyFastlaneXX (in target: UdemyFastlaneXX)
    cd /Users/isaac/Code/ReactNative/UdemyFastlaneXX/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/isaac/Library/Developer/Xcode/DerivedData/UdemyFastlaneXX-eltuekpfuqqbnmboxhdjzwuzjcis/Build/Products/Release-iphoneos/UdemyFastlaneXX.app/UdemyFastlaneXX -o /Users/isaac/Library/Developer/Xcode/DerivedData/UdemyFastlaneXX-eltuekpfuqqbnmboxhdjzwuzjcis/Build/Products/Release-iphoneos/UdemyFastlaneXX.app.dSYM
```

**Comment by Slapbox** [comment]
I can't even build development on Windows unless I remove `watchman` from the picture. When I do that though, the build seems to time out when I include my `node_modules` folder.

**Comment by CarGuo** [comment]
https://github.com/facebook/react-native/issues/18313  may help you

**Comment by Slapbox** [comment]
@CarGuo, thanks for your response. I'm confused though, what in particular might be of help here? I'm using Expo, so it seems not applicable, but maybe I'm mistaken?

Thanks again.

**Comment by CarGuo** [comment]
Sorry，My mistake，this may help to this issue with @isaaclem  `main.jsbundle does not exist`
