### ISSUE TITLE
Unable to use React.memo in React Native app

### ISSUE THREAD

**Issue by rohit-daffodil** [facebook/react-native#22366]
I want to use React.memo for optimization in react native.

```
import React from "react";
import { View, Text } from "react-native";

const Memo = React.memo(function() {
  return (
    <View>
      <Text>Ok</Text>
    </View>
  );
});
class Demo extends React.Component {
  render() {
    return <Memo />;
  }
}

export default Demo;
```
It gives following error:

`TypeError : undefined is not a function (evaluating render(nextProps)). This error is located at : in Demo(at renderApplication.js:34) in RCTView(at View.js:44 )`

Can we use React.memo in react native?

**Comment by RageOfJustice** [comment]
same

**Comment by rsokz** [comment]
Getting the following error:

'React.memo is not a function'

**Comment by omarkhaled11** [comment]
same

**Comment by ttruongatl** [comment]
not working for me either.

**Comment by M-Jas** [comment]
It works for me on iOS, but on Android we are seeing a crash of ```Error calling RCTDeviceEventEmitter.emit Unknown```. Crash happens when we are navigating to a new screen/component that is setup with hooks and wrapped in React.memo().

React Native 0.59.3
React 16.8.3
React Native Navigation

**Comment by JensonMiralles** [comment]
Encountered the same problem, did you guys manage to fix this error?

**Comment by fmonsalvo** [comment]
I'm having the same issue with react-native 0.59.8 and React 16.8.3. Any idea how to fix it?

**Comment by JensonMiralles** [comment]
For me the fix was instead of using
```
const Component =  React.memo((props) => { ... })
```
I used
```
const Component = (props) => {...}

export default React.memo(Component)
```

and it worked magically 🤣

**Comment by broon-s** [comment]
I got an application crash on android with following code (iOS worked fine):

React Native: 0.59.10
React: 16.8.3
```
const MyFunctionComponent = React.memo(({text}) => <Text>{text}</Text>);

MyFunctionComponent.displayName = 'HarmlessComponent';

MyFunctionComponent.propTypes = {
  text: PropTypes.string.isRequired
};

export default MyFunctionComponent;
```
All i got was a Stacktrace in Logcat, the App crashed without any commet:
```
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: field operation on NULL object: 0x0
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]     in call to GetObjectField
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]     from void com.facebook.react.bridge.queue.NativeRunnable.run()
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410] "mqt_js" prio=5 tid=22 Runnable
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   | group="main" sCount=0 dsCount=0 obj=0x12ea10a0 self=0x478bc600
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   | sysTid=32326 nice=0 cgrp=default sched=0/0 handle=0x57fa0930
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   | state=R schedstat=( 0 0 0 ) utm=972 stm=47 core=1 HZ=100
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   | stack=0x57e9e000-0x57ea0000 stackSize=1038KB
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   | held mutexes= "mutator lock"(shared held)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #00 pc 0035b179  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+116)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #01 pc 0033bfdb  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEP12BacktraceMap+146)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #02 pc 0024ee4d  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+752)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #03 pc 0024f4ef  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+54)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #04 pc 000fbabd  /system/lib/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+28)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #05 pc 00112859  /system/lib/libart.so (_ZN3art11ScopedCheck16CheckFieldAccessERNS_18ScopedObjectAccessEP8_jobjectP9_jfieldIDbNS_9Primitive4TypeE+2164)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #06 pc 001139b7  /system/lib/libart.so (_ZN3art8CheckJNI8GetFieldEPKcP7_JNIEnvP8_jobjectP9_jfieldIDbNS_9Primitive4TypeE+486)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #07 pc 00114083  /system/lib/libart.so (_ZN3art8CheckJNI14GetObjectFieldEP7_JNIEnvP8_jobjectP9_jfieldID+22)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #08 pc 00060777  /data/app/my.app-1/lib/arm/libreactnativejni.so (_ZNK8facebook3jni6JFieldIPNS0_6detail8JTypeForINS2_10HybridDataENS0_7JObjectEvE11_javaobjectEE3getEP8_jobject+22)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #09 pc 000726b5  /data/app/my.app-1/lib/arm/libreactnativejni.so (_ZN8facebook3jni11HybridClassINS_5react17WritableNativeMapENS2_17ReadableNativeMapEE8JavaPart5cthisEv+88)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #10 pc 00071735  /data/app/my.app-1/lib/arm/libreactnativejni.so (_ZN8facebook5react13MethodInvoker6invokeERNSt6__ndk18weak_ptrINS0_8InstanceEEENS_3jni9alias_refIPNS7_6detail8JTypeForINS0_15JBaseJavaModuleENS7_7JObjectEvE11_javaobjectEEERKN5folly7dynamicE+900)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #11 pc 0006ad67  /data/app/my.app-1/lib/arm/libreactnativejni.so (_ZN8facebook5react16JavaNativeModule26callSerializableNativeHookEjON5folly7dynamicE+94)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #12 pc 000919bf  /data/app/my.app-1/lib/arm/libreactnativejni.so (_ZN8facebook5react14ModuleRegistry26callSerializableNativeHookEjjON5folly7dynamicE+50)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #13 pc 00093891  /data/app/my.app-1/lib/arm/libreactnativejni.so (_ZN8facebook5react16JsToNativeBridge26callSerializableNativeHookERNS0_10JSExecutorEjjON5folly7dynamicE+20)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #14 pc 00019b53  /data/app/my.app-1/lib/arm/libjscexecutor.so (_ZN8facebook5react11JSIExecutor18nativeCallSyncHookEPKNS_3jsi5ValueEj+130)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #15 pc 0001a49b  /data/app/my.app-1/lib/arm/libjscexecutor.so (???)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #16 pc 00021c73  /data/app/my.app-1/lib/arm/libjscexecutor.so (???)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #17 pc 00066a65  /data/app/my.app-1/lib/arm/libjsc.so (_ZN3JSC16JSCallbackObjectINS_20JSDestructibleObjectEE4callEPNS_9ExecStateE+280)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #18 pc 001f68bf  /data/app/my.app-1/lib/arm/libjsc.so (_ZN3JSC5LLInt9setUpCallEPNS_9ExecStateENS_22CodeSpecializationKindENS_7JSValueEPNS_17LLIntCallLinkInfoE+450)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #19 pc 001f3ca5  /data/app/my.app-1/lib/arm/libjsc.so (llint_slow_path_tail_call+152)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   native: #20 pc 001e6f3d  /data/app/my.app-1/lib/arm/libjsc.so (???)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   at com.facebook.react.bridge.queue.NativeRunnable.run(Native method)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   at android.os.Handler.handleCallback(Handler.java:739)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   at android.os.Handler.dispatchMessage(Handler.java:95)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   at android.os.Looper.loop(Looper.java:148)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Thread.run(Thread.java:818)
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/java_vm_ext.cc:410] 
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/runtime.cc:368] Runtime aborting...
08-12 18:20:43.395 32295-32326/my.app A/art: art/runtime/runtime.cc:368] 
08-12 18:20:43.395 32295-32326/my.app A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 32326 (mqt_js)
08-12 18:20:43.505 1953-1953/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-12 18:20:43.505 1953-1953/? A/DEBUG: Build fingerprint: 'samsung/kminiltexx/kminilte:6.0.1/MMB29K/G800FXXU1CRG3:user/release-keys'
08-12 18:20:43.505 1953-1953/? A/DEBUG: Revision: '6'
08-12 18:20:43.505 1953-1953/? A/DEBUG: ABI: 'arm'
08-12 18:20:43.505 1953-1953/? A/DEBUG: pid: 32295, tid: 32326, name: mqt_js  >>> my.app <<<
08-12 18:20:43.505 1953-1953/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
08-12 18:20:43.575 1953-1953/? A/DEBUG: Abort message: 'art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: field operation on NULL object: 0x0'
08-12 18:20:43.575 1953-1953/? A/DEBUG:     r0 00000000  r1 00007e46  r2 00000006  r3 57fa0978
08-12 18:20:43.575 1953-1953/? A/DEBUG:     r4 57fa0980  r5 57fa0930  r6 00000003  r7 0000010c
08-12 18:20:43.575 1953-1953/? A/DEBUG:     r8 57f9a909  r9 42c64f40  sl 42c7ee44  fp 42c330e0
08-12 18:20:43.575 1953-1953/? A/DEBUG:     ip 00000006  sp 57f9a860  lr 402ac579  pc 402ae968  cpsr 40070010
08-12 18:20:43.625 1953-1953/? A/DEBUG: backtrace:
08-12 18:20:43.625 1953-1953/? A/DEBUG:     #00 pc 00042968  /system/lib/libc.so (tgkill+12)
08-12 18:20:43.625 1953-1953/? A/DEBUG:     #01 pc 00040575  /system/lib/libc.so (pthread_kill+32)
08-12 18:20:43.625 1953-1953/? A/DEBUG:     #02 pc 0001cc6b  /system/lib/libc.so (raise+10)
08-12 18:20:43.625 1953-1953/? A/DEBUG:     #03 pc 00019ee9  /system/lib/libc.so (__libc_android_abort+34)
08-12 18:20:43.625 1953-1953/? A/DEBUG:     #04 pc 00017570  /system/lib/libc.so (abort+4)
08-12 18:20:43.625 1953-1953/? A/DEBUG:     #05 pc 0031d115  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+200)
08-12 18:20:43.625 1953-1953/? A/DEBUG:     #06 pc 000f37e9  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2092)
08-12 18:20:43.625 1953-1953/? A/DEBUG:     #07 pc 0024f157  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1530)
08-12 18:20:43.625 1953-1953/? A/DEBUG:     #08 pc 0024f4ef  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+54)
08-12 18:20:43.625 1953-1953/? A/DEBUG:     #09 pc 000fbabd  /system/lib/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+28)
08-12 18:20:43.625 1953-1953/? A/DEBUG:     #10 pc 00112859  /system/lib/libart.so (_ZN3art11ScopedCheck16CheckFieldAccessERNS_18ScopedObjectAccessEP8_jobjectP9_jfieldIDbNS_9Primitive4TypeE+2164)
08-12 18:20:43.630 1953-1953/? A/DEBUG:     #11 pc 001139b7  /system/lib/libart.so (_ZN3art8CheckJNI8GetFieldEPKcP7_JNIEnvP8_jobjectP9_jfieldIDbNS_9Primitive4TypeE+486)
08-12 18:20:43.630 1953-1953/? A/DEBUG:     #12 pc 00114083  /system/lib/libart.so (_ZN3art8CheckJNI14GetObjectFieldEP7_JNIEnvP8_jobjectP9_jfieldID+22)
08-12 18:20:43.630 1953-1953/? A/DEBUG:     #13 pc 00060777  /data/app/my.app-1/lib/arm/libreactnativejni.so (_ZNK8facebook3jni6JFieldIPNS0_6detail8JTypeForINS2_10HybridDataENS0_7JObjectEvE11_javaobjectEE3getEP8_jobject+22)
08-12 18:20:43.630 1953-1953/? A/DEBUG:     #14 pc 000726b5  /data/app/my.app-1/lib/arm/libreactnativejni.so (_ZN8facebook3jni11HybridClassINS_5react17WritableNativeMapENS2_17ReadableNativeMapEE8JavaPart5cthisEv+88)
08-12 18:20:43.630 1953-1953/? A/DEBUG:     #15 pc 00071735  /data/app/my.app-1/lib/arm/libreactnativejni.so (_ZN8facebook5react13MethodInvoker6invokeERNSt6__ndk18weak_ptrINS0_8InstanceEEENS_3jni9alias_refIPNS7_6detail8JTypeForINS0_15JBaseJavaModuleENS7_7JObjectEvE11_javaobjectEEERKN5folly7dynamicE+900)
08-12 18:20:43.630 1953-1953/? A/DEBUG:     #16 pc 0006ad67  /data/app/my.app-1/lib/arm/libreactnativejni.so (_ZN8facebook5react16JavaNativeModule26callSerializableNativeHookEjON5folly7dynamicE+94)
08-12 18:20:43.630 1953-1953/? A/DEBUG:     #17 pc 000919bf  /data/app/my.app-1/lib/arm/libreactnativejni.so (_ZN8facebook5react14ModuleRegistry26callSerializableNativeHookEjjON5folly7dynamicE+50)
08-12 18:20:43.630 1953-1953/? A/DEBUG:     #18 pc 00093891  /data/app/my.app-1/lib/arm/libreactnativejni.so (_ZN8facebook5react16JsToNativeBridge26callSerializableNativeHookERNS0_10JSExecutorEjjON5folly7dynamicE+20)
08-12 18:20:43.630 1953-1953/? A/DEBUG:     #19 pc 00019b53  /data/app/my.app-1/lib/arm/libjscexecutor.so (_ZN8facebook5react11JSIExecutor18nativeCallSyncHookEPKNS_3jsi5ValueEj+130)
08-12 18:20:43.630 1953-1953/? A/DEBUG:     #20 pc 0001a49b  /data/app/my.app-1/lib/arm/libjscexecutor.so
08-12 18:20:43.630 1953-1953/? A/DEBUG:     #21 pc 00021c73  /data/app/my.app-1/lib/arm/libjscexecutor.so
08-12 18:20:43.630 1953-1953/? A/DEBUG:     #22 pc 00066a65  /data/app/my.app-1/lib/arm/libjsc.so (_ZN3JSC16JSCallbackObjectINS_20JSDestructibleObjectEE4callEPNS_9ExecStateE+280)
08-12 18:20:43.630 1953-1953/? A/DEBUG:     #23 pc 001f68bf  /data/app/my.app-1/lib/arm/libjsc.so (_ZN3JSC5LLInt9setUpCallEPNS_9ExecStateENS_22CodeSpecializationKindENS_7JSValueEPNS_17LLIntCallLinkInfoE+450)
08-12 18:20:43.630 1953-1953/? A/DEBUG:     #24 pc 001f3ca5  /data/app/my.app-1/lib/arm/libjsc.so (llint_slow_path_tail_call+152)
08-12 18:20:43.630 1953-1953/? A/DEBUG:     #25 pc 001e6f3d  /data/app/my.app-1/lib/arm/libjsc.so
```
It took me quite some time to identify the cause, but I got it fixed with the change from @JensonMiralles. Hopefully googling the error message will lead you here and save you from going down the rabbit hole like i did =)

This is the way to go:
```
const MyFunctionComponent = ({text}) => <Text>{text}</Text>;

MyFunctionComponent.displayName = 'HarmlessComponent';

MyFunctionComponent.propTypes = {
  text: PropTypes.string.isRequired
};

export default React.memo(MyFunctionComponent);
```

**Comment by avasuro** [comment]
Same issue with RN 0.61.2, solution from @JensonMiralles works fine.

But why this bug is marked as closed? This solution looks more like a hack, I believe that this should be fixed.
