### ISSUE TITLE
Xcode emulator don't open react native application

### ISSUE THREAD

**Issue by TheGreatLebowski** [facebook/react-native#22428]
Hi,

I've started React Native and followed the Facebook tutorial, but when I run `react-native run-ios`, the emulator appears, and a few seconds after, a new terminal is open with no errors.
The problem is that no application is displayed, I've checked others Issues and the troubleshooting page, I can't find the problem ...

I'm running on MacOs 10.14.1, npm v6.4.1, node v10.13.0, Xcode 10.1, react-native-cli: 2.0.1, react-native: 0.57.6

What i'm running 
`react-native init AwesomeProject`
`cd AwesomeProject`
`react-native run-ios`

Thanks for your help !

**Comment by TheGreatLebowski** [comment]
EDIT 
When I run `npm start`, I have this error 

`events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8081
    at Server.setupListenHandle [as _listen2] (net.js:1286:14)
    at listenInCluster (net.js:1334:12)
    at Server.listen (net.js:1421:7)
    at /Users/xxxxxxxxx/Documents/Prog/native/AwesomeProject/node_modules/metro/src/index.js:205:18
    at new Promise (<anonymous>)
    at Object.<anonymous> (/Users/xxxxxxxxx/Documents/Prog/native/AwesomeProject/node_modules/metro/src/index.js:204:12)
    at Generator.next (<anonymous>)
    at step (/Users/xxxxxxxxx/Documents/Prog/native/AwesomeProject/node_modules/metro/src/index.js:58:30)
    at /Users/xxxxxxxxx/Documents/Prog/native/AwesomeProject/node_modules/metro/src/index.js:69:15
Emitted 'error' event at:
    at Server.WebSocketServer._onServerError (/Users/xxxxxxxxx/Documents/Prog/native/AwesomeProject/node_modules/ws/lib/WebSocketServer.js:82:50)
    at Server.emit (events.js:187:15)
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! AwesomeProject@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the AwesomeProject@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxxxxxxxxxx/.npm/_logs/2018-11-27T10_37_01_273Z-debug.log`
