### ISSUE TITLE
`react-native link react-native/Libraries/LinkingIOS`

### ISSUE THREAD

**Issue by ccorcos** [facebook/react-native#22436]
I'm trying to figure out how to link LinkingIOS so I can `#import "RCTLinkingManager.h"`. It would be nice if this just worked.

```
 ❯❯❯ react-native link react-native/Libraries/LinkingIOS
{ Error: Cannot find module '/Users/chet/Code/notion-next/src/mobile/node_modules/react-native/Libraries/LinkingIOS/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at getRNPMConfig (/Users/chet/Code/notion-next/src/mobile/node_modules/react-native/local-cli/core/index.js:53:1)
    at Object.getDependencyConfig (/Users/chet/Code/notion-next/src/mobile/node_modules/react-native/local-cli/core/index.js:110:18)
    at deps.reduce (/Users/chet/Code/notion-next/src/mobile/node_modules/react-native/local-cli/link/getDependencyConfig.js:18:24)
    at Array.reduce (<anonymous>)
    at getDependencyConfig (/Users/chet/Code/notion-next/src/mobile/node_modules/react-native/local-cli/link/getDependencyConfig.js:15:15)
    at Object.link [as func] (/Users/chet/Code/notion-next/src/mobile/node_modules/react-native/local-cli/link/link.js:151:24) code: 'MODULE_NOT_FOUND' }
```

**Comment by ccorcos** [comment]
Ah `#import <React/RCTLinkingManager.h>` fixes this issue
