### ISSUE TITLE
 bundling failed: Error: Unable to resolve module `stream` from ./node_modules/react-dom/cjs/react-dom-server.node.production.min.js`: Module does not exist in the module map

### ISSUE THREAD

**Issue by dev-reactnative** [facebook/react-native#22449]
## Environment
Environment:
  OS: macOS 10.14
  Node: 8.3.0
  Yarn: 1.3.2
  npm: 5.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: ^0.52.0 => 0.52.3
## Description
When I run npm start or yarn it generate following issue.
error: bundling failed: Error: Unable to resolve module `stream` from 
./node_modules/react-dom/cjs/react-dom-server.node.production.min.js`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf $TMPDIR/react-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf $TMPDIR/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/vishnukhaitan1/Documents/Sunil/my-business/frontend/native/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:311:1719)
    at ResolutionRequest.resolveDependency (/Users/vishnukhaitan1/Documents/Sunil/my-business/frontend/native/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:96:16)
    at DependencyGraph.resolveDependency (/Users/vishnukhaitan1/Documents/Sunil/my-business/frontend/native/node_modules/metro/src/node-haste/DependencyGraph.js:269:4352)
    at /Users/vishnukhaitan1/Documents/Sunil/my-business/frontend/native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:201:36
    at Generator.next (<anonymous>)
    at step (/Users/vishnukhaitan1/Documents/Sunil/my-business/frontend/native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:306)
    at /Users/vishnukhaitan1/Documents/Sunil/my-business/frontend/native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:536
    at Promise (<anonymous>)
    at /Users/vishnukhaitan1/Documents/Sunil/my-business/frontend/native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:217
    at addDependency (/Users/vishnukhaitan1/Documents/Sunil/my-business/frontend/native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:92)
 BUNDLE  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓░░░░░░ 67.3% (1306/1592), failed.

**Comment by hramos** [comment]
It looks like you pasted in the error message, but did not provide sufficient information as required in the template. Since this is for an older version, I'm closing the issue out.
