### ISSUE TITLE
"RCTImageView" was not found in the UIManager

### ISSUE THREAD

**Issue by idoor88** [facebook/react-native#22534]
## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 1.11 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
yarn install v0.15.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 58.23s. - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 28
        Build Tools: 27.0.3, 28.0.2
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
My app can be loaded into ios simulator successfully with react-native run-ios command, but when I clicked a page on the app, which has a image for a button, then it crashed with this message:
Invariant Violation: requireNativeComponent: "RCTImageView" was not found in the UIManager.

This error is located at:
    in RCTImageView (at Image.ios.js:127)
    in Image (at HeaderBackButton.js:50)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in AnimatedComponent (at TouchableOpacity.js:256)
    in TouchableOpacity (at TouchableItem.js:37)
    in TouchableItem (at HeaderBackButton.js:85)
    in HeaderBackButton (at Header.js:162)
    in RCTView (at View.js:43)
    in AnimatedComponent (at Header.js:298)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in AnimatedComponent (at index.js:134)
    in SafeView (at withOrientation.js:54)
    in withOrientation (at Header.js:433)
    in RCTView (at View.js:43)
    in AnimatedComponent (at Header.js:430)
    in Header (at withOrientation.js:30)
    in withOrientation (at StackViewLayout.js:129)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:49)
    in RCTView (at View.js:43)
    in Transitioner (at StackView.js:19)
    in StackView (at createNavigator.js:57)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at index.js:40)
    in RCTView (at View.js:43)
    in Provider (at index.js:37)
    in Application (at renderApplication.js:32)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in AppContainer (at renderApplication.js:31)

I have spent two days googling around, but could not find a solution, please help.
Thanks
Idoor

**Comment by idoor88** [comment]
After I upgraded react-native from 0.56 to 0.57.7, I also need to upgrade Babel related libraries, after I ran react-native run-ios, I got this error:
error: bundling failed: Error: [BABEL]  /Users/tester/MyApp/index.js: The 'polyfill' option has been removed. The @babel/runtime module now skips polyfilling by default. (While processing: " /Users/tester/MyApp/node_modules/@babel/plugin-transform-runtime/lib/index.js")
    at _default ( /Users/tester/MyApp/node_modules/@babel/plugin-transform-runtime/lib/index.js:131:13)
    at  /Users/tester/MyApp/node_modules/@babel/plugin-transform-runtime/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at loadDescriptor ( /Users/tester/MyApp/node_modules/metro/node_modules/@babel/core/lib/config/full.js:165:14)
    at cachedFunction ( /Users/tester/MyApp/node_modules/metro/node_modules/@babel/core/lib/config/caching.js:33:19)
    at loadPluginDescriptor ( /Users/tester/MyApp/node_modules/metro/node_modules/@babel/core/lib/config/full.js:200:28)
    at config.plugins.reduce ( /Users/tester/MyApp/node_modules/metro/node_modules/@babel/core/lib/config/full.js:69:20)
    at Array.reduce (<anonymous>)
    at recurseDescriptors ( /Users/tester/MyApp/node_modules/metro/node_modules/@babel/core/lib/config/full.js:67:38)
    at loadFullConfig  /Users/tester/MyApp/node_modules/metro/node_modules/@babel/core/lib/config/full.js:108:6)

my package.json looks like this:

"dependencies": {
    "axios": "0.18.0",
    "identicon.js": "2.3.2",
    "mobx": "5.1.0",
    "mobx-react": "5.2.5",
    "moment": "2.22.2",
    "react": "^16.6.1",
    "react-native": "^0.57.7",
    "react-native-actionsheet": "^2.4.2",
    "react-native-camera": "^1.5.0",
    "react-native-elements": "^0.19.1",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-image-crop-picker": "^0.21.3",
    "react-native-modal": "6.5.0",
    "react-native-permissions": "1.1.1",
    "react-native-qrcode-svg": "5.1.0",
    "react-native-sensitive-info": "5.2.4",
    "react-native-snackbar": "0.5.0",
    "react-native-svg": "^5.5.1",
    "react-native-table-component": "^1.1.8",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.18.2"
  },
  "devDependencies": {
    "@babel/core": "^7.2.0",
    "@babel/plugin-proposal-decorators": "^7.2.0",
    "@babel/plugin-transform-runtime": "^7.2.0",
    "@babel/runtime": "^7.2.0",
    "babel-core": "^6.26.3",
    "babel-jest": "23.4.2",
    "babel-plugin-module-resolver": "3.1.1",
    "babel-preset-react-native": "5.0.2",
    "enzyme": "3.5.0",
    "enzyme-adapter-react-16": "1.3.0",
    "eslint-config-rallycoding": "3.2.0",
    "jest": "23.5.0",
    "jsdom": "12.0.0",
    "react-native-mock-render": "0.1.1",
    "react-test-renderer": "16.4.2"
  },

**Comment by Nosherwan** [comment]
@idoor88 I am facing the same issue. Even after making the changes suggested by yourself above I am still getting the exact same error at runtime. Build succeeds but running in emulator fails.
Here is my package.json file contents:
{
  "name": "app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "build:ios": "react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'"
  },
  "dependencies": {
    "dateformat": "^3.0.3",
    "firebase": "^5.2.0",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.21",
    "native-base": "^2.7.1",
    "react": "16.6.0",
    "react-native": "0.57.8",
    "react-native-appsee": "^2.4.11",
    "react-native-audio-session": "0.0.4",
    "react-native-background-geolocation": "^2.12.2",
    "react-native-ble-manager": "^6.4.0",
    "react-native-bluetooth-serial": "^1.0.0-rc1",
    "react-native-device-info": "^0.22.2",
    "react-native-easy-toast": "^1.1.0",
    "react-native-event-listeners": "^1.0.3",
    "react-native-fabric": "^0.5.1",
    "react-native-iphone-x-helper": "^1.0.3",
    "react-native-keyboard-aware-scroll-view": "^0.6.0",
    "react-native-locale": "0.0.19",
    "react-native-maps": "^0.21.0",
    "react-native-router-flux": "^4.0.0-beta.31",
    "react-native-simple-toast": "0.0.8",
    "react-native-tab-navigator": "^0.3.4"
  },
  "devDependencies": {
    "@babel/core": "^7.2.0",
    "@babel/plugin-proposal-decorators": "^7.2.0",
    "@babel/plugin-transform-runtime": "^7.2.0",
    "@babel/runtime": "^7.2.0",
    "babel-core": "^6.26.3",
    "babel-jest": "23.4.2",
    "babel-plugin-module-resolver": "3.1.1",
    "babel-preset-react-native": "5.0.2",
    "jest": "23.4.0",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

pod file contents are as follows:
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'app' do
 rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  # If you are using React Native <0.54, you will get the following error:
  # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
  # Use the following line instead:
  #pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

 pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation'
 pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'
end

Thanks in advance.

**Comment by GreenRidingHood** [comment]
https://github.com/facebook/react-native/issues/22725 

i followed that ticket to , but it didnt work either

my env info:::>
React Native Environment Info:
System:
OS: macOS 10.14.4
CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
Memory: 55.31 MB / 8.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.3 - /usr/local/bin/node
Yarn: 1.15.2 - /usr/local/bin/yarn
npm: 6.4.1 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
iOS SDK:
Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
IDEs:
Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
npmPackages:
react: 16.8.3 => 16.8.3
react-native: ^0.59.8 => 0.59.8
npmGlobalPackages:
react-native-cli: 2.0.1

error message i am seeing, at browser dev tool and at simulator ::::>

Unhandled JS Exception: Invariant Violation: requireNativeComponent: "RCTImageView" was not found in the UIManager.

This error is located at:
in RCTImageView (at Image.ios.js:115)
in Image (at NewSession.js:58)
in RCTView (at View.js:45)
in View (at NewSession.js:57)
in RCTView (at View.js:45)
in View (at KeyboardAvoidingView.js:200)
in KeyboardAvoidingView (at NewSession.js:55)
in NewSession (created by ConnectFunction)
in ConnectFunction (at steps.js:96)
in StepManager (created by ConnectFunction)
in ConnectFunction (at Login.js:23)
in RCTView (at View.js:45)
in View (at Login.js:21)
in Login (at views.js:8)
in RCTView (at View.js:45)
in View (at ViewManager.js:13)
in ViewManager (created by ConnectFunction)
in ConnectFunction (at App.js:21)
in RCTView (at View.js:45)
in View (at App.js:20)
in Provider (at App.js:19)
in App (at renderApplication.js:35)
in RCTView (at View.js:45)
in View (at AppContainer.js:98)
in RCTView (at View.js:45)
in View (at AppContainer.js:115)
in AppContainer (at renderApplication.js:34)
reactConsoleErrorHandler @ 7e954ad7-bf1f-414a-b…-5e70fd596c9c:27283
console.error @ 7e954ad7-bf1f-414a-b…-5e70fd596c9c:68243
logToConsole @ 7e954ad7-bf1f-414a-b…-5e70fd596c9c:32780
logIfNoNativeHook @ 7e954ad7-bf1f-414a-b…-5e70fd596c9c:32763
__callFunction @ 7e954ad7-bf1f-414a-b…a-5e70fd596c9c:7265
(anonymous) @ 7e954ad7-bf1f-414a-b…a-5e70fd596c9c:7022
__guard @ 7e954ad7-bf1f-414a-b…a-5e70fd596c9c:7219
callFunctionReturnFlushedQueue @ 7e954ad7-bf1f-414a-b…a-5e70fd596c9c:7021
(anonymous) @ debuggerWorker.js:80
7e954ad7-bf1f-414a-b…-5e70fd596c9c:32984 BugReporting extraData: {AppRegistry.runApplication1: "Running application "myApp" with appParams: …warning are ON, performance optimizations are OFF"}
7e954ad7-bf1f-414a-b…-5e70fd596c9c:32984 BugReporting extraData: {AppRegistry.runApplication1: "Running application "myApp" with appParams: …warning are ON, performance optimizations are OFF"}

**Comment by GreenRidingHood** [comment]
@Nosherwan 

i added library again to xcode, maybe that can help

that is the answer from stackeverflow ::

https://stackoverflow.com/questions/52343228/problems-with-rctimage-in-react-native 

“RCTImage will be available inside node_modules/react-native/Libraries/Image. 

Copy RCTImage.xcodeproj to your Libraries folder and link it. “  

how you can link it manually::
https://facebook.github.io/react-native/docs/linking-libraries-ios 

at some point i run at terminal "react-native link"

i am not sure which one help, adding manually again or running that link thing
