### ISSUE TITLE
bundling failed: Error: unable to resolve module

### ISSUE THREAD

**Issue by idoor88** [facebook/react-native#22547]
## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 868.53 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
yarn install v0.15.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 51.14s. - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 28
        Build Tools: 27.0.3, 28.0.2
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.1 => 16.6.3 
      react-native: ^0.57.7 => 0.57.7 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

package.json:

"dependencies": {
    "@babel/polyfill": "^7.0.0",
    "@babel/runtime": "^7.0.0",
    "autobind-decorator": "^2.1.0",
    "axios": "0.18.0", 
    "firebase": "^5.6.0",
    "identicon.js": "2.3.2",
    "mobx": "5.1.0",
    "mobx-react": "5.2.5",
    "moment": "2.22.2",
    "react": "^16.6.1",
    "react-native": "^0.57.7",
    "react-native-actionsheet": "^2.4.2",
    "react-native-camera": "^1.5.0",
    "react-native-elements": "^0.19.1",
    "react-native-modal": "6.5.0",
    "react-native-permissions": "1.1.1",
    "react-native-qrcode-svg": "5.1.0",
    "react-native-sensitive-info": "5.2.4",
    "react-native-snackbar": "0.5.0",
    "react-native-svg": "^5.5.1",
    "react-native-table-component": "^1.1.8",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.18.2"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/plugin-external-helpers": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-proposal-decorators": "^7.0.0",
    "@babel/plugin-proposal-export-default-from": "^7.0.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.0.0",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^9.0.0",
    "babel-plugin-module-resolver": "^3.1.1",
    "babel-plugin-require-context-polyfill": "^1.0.0",
    "enzyme": "3.5.0",
    "enzyme-adapter-react-16": "1.3.0",
    "eslint-config-rallycoding": "3.2.0",
    "jsdom": "12.0.0",
    "metro-react-native-babel-preset": "^0.50.0",
    "react-native-mock-render": "0.1.1",
    "react-test-renderer": "16.6.1",
    "schedule": "^0.4.0"
  },

my .babelrc file:
{
  "presets": ["module:metro-react-native-babel-preset"],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }]
  ]
}

## Description
I did brutal clean as instructed in the error message many times, but it did not work, and always had the following error message after I did react-native run-ios

Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `@common/utils` from `/Users/tester/myapp2/src/common/stores/teststore.js`: Module `@common/utils` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/tester/myapp2/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:139:15)
    at ResolutionRequest.resolveDependency (/Users/tester/myapp2/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:49:18)

Please help.
Thanks
Idoor

**Comment by idoor88** [comment]
FIxed by adding module-resolver to .babelrc file
["module-resolver", {
      "alias": {
        "@assets": "./assets",
        "@common": "./src/common",
        "@components": "./src/components"
      }
    }],
