### ISSUE TITLE
ENOSPC (expo, Android 9.0 emulator)

### ISSUE THREAD

**Issue by KernelDeimos** [facebook/react-native#22554]
- [ ] Review the documentation: https://facebook.github.io/react-native
  - [ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
```
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
      Memory: 1.12 GB / 15.29 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.3.0 - ~/.nvm/versions/node/v8.3.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v8.3.0/bin/npm
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1
```

## Description
I received the following error message after following the quick start instructions, using expo, and choosing the blank template:
```
[03:17:09] fs.js:1384
[03:17:09]     throw error;
[03:17:09]     ^
[03:17:09] 
[03:17:09] Error: watch /home/eric/repos/TestReact3/node_modules/asap ENOSPC
[03:17:09]     at _errnoException (util.js:1022:11)
[03:17:09]     at FSWatcher.start (fs.js:1382:19)
[03:17:09]     at Object.fs.watch (fs.js:1408:11)
[03:17:09]     at NodeWatcher.watchdir (/home/eric/repos/TestReact3/node_modules/sane/src/node_watcher.js:175:20)                                                                                                   
[03:17:09]     at Walker.<anonymous> (/home/eric/repos/TestReact3/node_modules/sane/src/common.js:116:12)
[03:17:09]     at emitTwo (events.js:125:13)
[03:17:09]     at Walker.emit (events.js:213:7)
[03:17:09]     at /home/eric/repos/TestReact3/node_modules/walker/lib/walker.js:69:16
[03:17:09]     at go$readdir$cb (/home/eric/repos/TestReact3/node_modules/graceful-fs/graceful-fs.js:162:14)                                                                                                        
[03:17:09]     at FSReqWrap.oncomplete (fs.js:135:15)
```

This error appeared in the console after attempting to run the app on an Android emulator. The Android emulator displayed a blank white screen, or on some attempts a spinning loading indicator.

Using the solution on this StackOverflow thread fixed the problem, which is why I emphasised "ENOSPC" in the issue title: https://stackoverflow.com/questions/22475849/node-js-what-is-enospc-error-and-how-to-solve/32600959#32600959

and because I know somebody is going to ask, my hard-drive is not full. I have 156GB of free space.

## Reproducible Demo
Specific issue is reproduced by following the quickstart instructions instructions on Node.js 8.3, which was installed using nvm, and npm 6.4.1, which was upgraded from the version nvm installed, and then running a new expo project (choosing blank template when prompted) in an Android 9.0 emulator.

**Comment by bartolkaruza** [comment]
Could you post this on https://github.com/expo/expo please?

@kelset close
