### ISSUE TITLE
Cannot find module 'jest-serializer'

### ISSUE THREAD

**Issue by aniketcgi** [facebook/react-native#22612]
When I run the app, I am getting this error

Error: Cannot find module 'jest-serializer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at _load_jestSerializer (C:\Users\aniket.raut\React Native Projects\cgsdk\node_modules\jest-haste-map\build\index.js:164:52)
    at HasteMap._persist (C:\Users\aniket.raut\React Native Projects\cgsdk\node_modules\jest-haste-map\build\index.js:781:25)
    at _buildPromise._buildFileMap.then.then.hasteMap (C:\Users\aniket.raut\React Native Projects\cgsdk\node_modules\jest-haste-map\build\index.js:425:16)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

**Comment by Nagbhushan1233** [comment]
Still i am getting below issue when i run sample react native project on mac
Error: Cannot find module 'jest-serializer'

Can anyone help me on this ?

**Comment by aniketcgi** [comment]
> Still i am getting below issue when i run sample react native project on mac
> Error: Cannot find module 'jest-serializer'
> 
> Can anyone help me on this ?

I had install " npm install jest-haste-map"..
It works for me.

**Comment by Nagbhushan1233** [comment]
Thanks it got resolved buddy.
