### ISSUE TITLE
E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher     Process: com.facebook.react.uiapp, PID: 25808     java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY         at android.util.JsonReader.nextString(JsonReader.java:408)         at com.facebook.react.devsupport.BundleDeltaClient$BundleDeltaJavaClient.processDelta(BundleDeltaClient.java:103)

### ISSUE THREAD

**Issue by srikanthsunkari** [facebook/react-native#22635]
Hi , I am new to react native, haven't found an issue related to this, It looks this is a new issue, i don't find any similar issue anywhere else.

# Issue Description: 
Run react-native RNTester demo app for android tv, after the bundling, app crashes with below exception.

# Error Details
```
12-12 21:05:08.640 25808-25834/com.facebook.react.uiapp E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.facebook.react.uiapp, PID: 25808
    java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY
        at android.util.JsonReader.nextString(JsonReader.java:408)
        at com.facebook.react.devsupport.BundleDeltaClient$BundleDeltaJavaClient.processDelta(BundleDeltaClient.java:103)
        at com.facebook.react.devsupport.BundleDeltaClient.processDelta(BundleDeltaClient.java:71)
        at com.facebook.react.devsupport.BundleDownloader.processBundleResult(BundleDownloader.java:314)
        at com.facebook.react.devsupport.BundleDownloader.access$200(BundleDownloader.java:37)
        at com.facebook.react.devsupport.BundleDownloader$1.onResponse(BundleDownloader.java:174)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
```

# Device details:
The device tested on: Amazon Fire TV stick, Lenovo Yoga tab 10, Redmi 4A.
OS: Windows 10.

# Steps to reproduce
1. Cloned https://github.com/facebook/react-native project directly.
2. Ran RNTester (gradlew RNTester:android:app:installDebug).
3. Started the npm server (npm start).
4. Bundling completed 100%.
5. As soon as it finish bundling app is crashing.

 is there anyhting i am missing ?

**Comment by xuelgong** [comment]
@srikanthsunkari I encountered the same issue. Have you sorted it out?

**Comment by linglu** [comment]
I also encounter this problem, but when I try to install Release with command
```js
./gradlew :RNTester:android:app:installRelease
```
the app works without error, Hope it can help you

**Comment by xuelgong** [comment]
Thanks, @linglu. It works for me too.
