### ISSUE TITLE
Fail to import local image on Mac

### ISSUE THREAD

**Issue by cztflove** [facebook/react-native#22647]
- [ ☑️ ] Review the documentation: https://facebook.github.io/react-native
  - [ ☑️ ] Search for existing issues: https://github.com/facebook/react-native/issues
  - [ ☑️ ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
System:
      OS: macOS 10.14
      CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
      Memory: 317.41 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.2 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 26.0.3, 27.0.3, 28.0.3
        System Images: android-27 | Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
I have tried many times to run react-native run-ios
but when import an image file, the error appears below:
 
error: bundling failed: Error: Unable to resolve module `../../static/media/icon.png` from `/Users/cb/mallWS/packages/cbmms-rn/ui/base/Loading.js`: The module `../../static/media/icon.png` could not be found from `/Users/cb/mallWS/packages/cbmms-rn/ui/base/Loading.js`. Indeed, none of these files exist:
  * `icon.png`
  * `/Users/cb/mallWS/packages/cbmms-rn/static/media/icon.png/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/Users/cb/mallWS/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:120:15)
    at ResolutionRequest.resolveDependency (/Users/cb/mallWS/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:49:18)
    at DependencyGraph.resolveDependency (/Users/cb/mallWS/node_modules/metro/src/node-haste/DependencyGraph.js:219:16)
    at Object.resolve (/Users/cb/mallWS/node_modules/metro/src/lib/transformHelpers.js:141:30)
    at dependencies.map.result (/Users/cb/mallWS/node_modules/metro/src/DeltaBundler/traverseDependencies.js:373:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/cb/mallWS/node_modules/metro/src/DeltaBundler/traverseDependencies.js:369:18)
    at /Users/cb/mallWS/node_modules/metro/src/DeltaBundler/traverseDependencies.js:188:33
    at Generator.next (<anonymous>)
    at step (/Users/cb/mallWS/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:30)

## Reproducible Demo
import icon from '../../static/media/icon.png';
<Image  source={icon} />

**Comment by sunnylqm** [comment]
You can only use require('../../static/media/icon.png')

**Comment by cztflove** [comment]
> Can you run `react-native info` and edit your issue to include these results under the **Environment** section?
> 
> If you believe this information is irrelevant to the reported issue, you may write `[skip envinfo]` under **Environment** to let us know.
 
I have pasted the result of 'react-native info'

**Comment by cztflove** [comment]
>  require('../../static/media/icon.png')

i got the same issue using require
<Image source={require('../../static/media/icon.png')} />

**Comment by sunnylqm** [comment]
Better to post your fold structures with both the js file and the image file

**Comment by vovkasm** [comment]
> You can only use require('../../static/media/icon.png')

Of course you can use import for this:
```
import icon from '../../static/media/icon.png'

// ...and use
 <Image source={icon} />
```
It's totally valid syntax
