### ISSUE TITLE
Custom Targets Break react-native link

### ISSUE THREAD

**Issue by dotconnor** [facebook/react-native#22726]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
Run `react-native info` in your terminal and paste its contents here.
```
React Native Environment Info:
  System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 28.63 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5014246
    Xcode: 10.1/10O23u - /usr/bin/xcodebuild
  npmPackages:
    react: 16.6.3 => 16.6.3 
    react-native: 0.57.8 => 0.57.8
```
## Description
Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.
If you add a custom target to your iOS project, the linking process just outright fails.

```
Cannot read property 'buildConfigurationList' of undefined

TypeError: Cannot read property 'buildConfigurationList' of undefined
    at ./node_modules/react-native/local-cli/link/ios/getTargets.js:18:68
    at Array.map (<anonymous>)
    at getTargets (./node_modules/react-native/local-cli/link/ios/getTargets.js:16:18)
    at registerNativeModuleIOS (./node_modules/react-native/local-cli/link/ios/registerNativeModule.js:52:19)
    at Object.registerNativeModule [as register] (./node_modules/react-native/local-cli/link/ios/common/registerNativeModule.js:15:5)
    at Object.keys.forEach.platform (./node_modules/react-native/local-cli/link/link.js:74:16)
    at Array.forEach (<anonymous>)
    at linkDependency (./node_modules/react-native/local-cli/link/link.js:44:32)
```
## Reproducible Demo
Let us know how to reproduce the issue. Include a code sample, share a project, or     share an app that reproduces the issue using https://snack.expo.io/. Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve
Example at https://github.com/dotconnor/CustomTargets
- `react-native init myproject`
- Add a custom target in XCode, in my example i have a simple Aggregate target that updates my Info.plist with the correct version but it can just be left empty.
- `yarn add react-native-svg` or any other project that requires linking
- `react-native link react-native-svg`

**Comment by dotconnor** [comment]
Moved to react-native-community/react-native-cli#57
