### ISSUE TITLE
Something went wrong while linking. Error: Expected "*/" or [^*] but "*" found. 

### ISSUE THREAD

**Issue by chevins** [facebook/react-native#22724]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.1
      CPU: (4) x64 Intel(R) Core(TM) i5-5575R CPU @ 2.80GHz
      Memory: 28.38 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: ^0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
I want to run react-native link after I add react-native-camera, but got an error :

rnpm-install ERR! Something went wrong while linking. Error: Expected "*/" or [^*] but "*" found. 
Please file an issue here: https://github.com/facebook/react-native/issues 

Expected "*/" or [^*] but "*" found.

SyntaxError: Expected "*/" or [^*] but "*" found.
    at peg$buildStructuredError (/Users/huifu/Git/rnpay/TruvisioExpress/node_modules/xcode/lib/parser/pbxproj.js:429:12)
    at Object.peg$parse [as parse] (/Users/huifu/Git/rnpay/TruvisioExpress/node_modules/xcode/lib/parser/pbxproj.js:1903:11)
    at pbxProject.parseSync (/Users/huifu/Git/rnpay/TruvisioExpress/node_modules/xcode/lib/pbxProject.js:63:24)
    at isInstalled (/Users/huifu/Git/rnpay/TruvisioExpress/node_modules/react-native/local-cli/link/ios/isInstalled.js:19:60)
    at Object.isInstalled (/Users/huifu/Git/rnpay/TruvisioExpress/node_modules/react-native/local-cli/link/ios/common/isInstalled.js:8:5)
    at Object.keys.forEach.platform (/Users/huifu/Git/rnpay/TruvisioExpress/node_modules/react-native/local-cli/link/link.js:57:36)
    at Array.forEach (<anonymous>)
    at linkDependency (/Users/huifu/Git/rnpay/TruvisioExpress/node_modules/react-native/local-cli/link/link.js:44:32)

**Comment by rickhanlonii** [comment]
Hey @chevins, thanks for filing and sorry for the delay. This should be improved in the new cli - if you're still seeing this then please open an issue in https://github.com/react-native-community/react-native-cli ✌️
