### ISSUE TITLE
[Bug]RNTester debug break in master

### ISSUE THREAD

**Issue by gengjiawen** [facebook/react-native#22800]
Looks like introduced in https://github.com/facebook/react-native/commit/1eedf05651362b9633b2ebf5ce5da8f34ffbfcc2.
```bash
    Process: com.facebook.react.uiapp, PID: 3307
    java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY
        at android.util.JsonReader.nextString(JsonReader.java:408)
        at com.facebook.react.devsupport.BundleDeltaClient$BundleDeltaJavaClient.processDelta(BundleDeltaClient.java:103)
        at com.facebook.react.devsupport.BundleDeltaClient.processDelta(BundleDeltaClient.java:71)
        at com.facebook.react.devsupport.BundleDownloader.processBundleResult(BundleDownloader.java:314)
        at com.facebook.react.devsupport.BundleDownloader.access$200(BundleDownloader.java:37)
        at com.facebook.react.devsupport.BundleDownloader$1.onResponse(BundleDownloader.java:174)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by Jyrno42** [comment]
Also having this issue when building RN from source.

**Comment by hramos** [comment]
What are the steps to reproduce this?

**Comment by gengjiawen** [comment]
install RNTester debug version.
npm run start.

**Comment by matt-oakes** [comment]
What is the workaround to this?

I'd like to use the RNTester app to work on a change to the React Native core, however, with this issue it's not possible to run the tester in the `master` branch. What is the best way around this until a fix lands?

**Comment by osdnk** [comment]
@matt-oakes 
Thank you so much! I confirm that it helps.
Maybe it is breaking https://github.com/facebook/react-native/commit/64de0c0aef6225e72beeb479972e8e6fc88b3c2c?

**Comment by cpojer** [comment]
This should have been fixed in https://github.com/facebook/react-native/commit/845189c17de621cc5aa373503220c1c12f649c3c.
