### ISSUE TITLE
BUG  Launching app "spawn chromium ENOENT"

### ISSUE THREAD

**Issue by micaeldias** [facebook/react-native#22848]
## Environment
React Native Environment Info:
    System:
      OS: Linux 4.19 Arch Linux undefined
      CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
      Memory: 2.87 GB / 7.69 GB
      Shell: 4.4.23 - /bin/bash
    Binaries:
      Node: 11.5.0 - /usr/bin/node
      Yarn: 1.12.3 - /usr/bin/yarn
      npm: 6.5.0 - /usr/bin/npm
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native: 0.57.8

## Description
When I try to launch an application, I receive this msg;

```
Google Chrome exited with error: { Error: spawn chromium ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn chromium',
  path: 'chromium',
  spawnargs: [ 'http://192.168.1.203:19003/debugger-ui' ] }
```

**Comment by micaeldias** [comment]
I found the solution, if you don't have chromium installed just link your chrome like this:

`ln -s {/path/to/chromium} {path/to/your/chrome/version}`
