### ISSUE TITLE
When I finished configuring the environment and started running the project, the following error message was displayed to me

### ISSUE THREAD

**Issue by KGDeveloper** [facebook/react-native#22887]
+ DEST=/Users/bszh/Library/Developer/Xcode/DerivedData/huiban-daoeqngvdocbgwdmradkfcprvnja/Build/Products/Release-iphonesimulator/huiban.app
+ [[ Release = \D\e\b\u\g ]]
+ BUNDLE_FILE=/Users/bszh/Library/Developer/Xcode/DerivedData/huiban-daoeqngvdocbgwdmradkfcprvnja/Build/Products/Release-iphonesimulator/huiban.app/main.jsbundle
+ node /Users/bszh/Desktop/huibanDemo/huiban 2/node_modules/react-native/local-cli/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Users/bszh/Library/Developer/Xcode/DerivedData/huiban-daoeqngvdocbgwdmradkfcprvnja/Build/Products/Release-iphonesimulator/huiban.app/main.jsbundle --assets-dest /Users/bszh/Library/Developer/Xcode/DerivedData/huiban-daoeqngvdocbgwdmradkfcprvnja/Build/Products/Release-iphonesimulator/huiban.app
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module '/Users/bszh/Desktop/huibanDemo/huiban'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
+ [[ false != true ]]
+ [[ ! -f /Users/bszh/Library/Developer/Xcode/DerivedData/huiban-daoeqngvdocbgwdmradkfcprvnja/Build/Products/Release-iphonesimulator/huiban.app/main.jsbundle ]]
+ echo 'error: File /Users/bszh/Library/Developer/Xcode/DerivedData/huiban-daoeqngvdocbgwdmradkfcprvnja/Build/Products/Release-iphonesimulator/huiban.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/bszh/Library/Developer/Xcode/DerivedData/huiban-daoeqngvdocbgwdmradkfcprvnja/Build/Products/Release-iphonesimulator/huiban.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2

**Comment by KGDeveloper** [comment]
I need your help, I hope that someone as soon as possible under the solution, more anxious
