### ISSUE TITLE
Error: query failed: synchronization failed: Operation timed out (Mac OSX 10.10.4, 0.8)

### ISSUE THREAD

**Issue by hzhu** [facebook/react-native#2306]
Running projects under `Example` folder (following the steps in the docs) starts the app but shows the following red screen after the initial launch screen:

![screen shot 2015-08-11 at 6 05 46 pm](https://cloud.githubusercontent.com/assets/1811365/9214517/9c973b48-4053-11e5-8f48-3bca0ebbc271.png)

    Looking for JS files in  /Users/henry/Code/react-native 
    React packager ready.

    [18:01:19] <START> fs crawl
    [18:01:26] <START> request:/Examples/Movies/MoviesApp.includeRequire.runModule.bundle
    [18:01:26] <START> find dependencies
    Error: query failed: synchronization failed: Operation timed out

    at BunserBuf.<anonymous> (/Users/henry/Code/react-native/node_modules/sane/node_modules/fb-watchman/index.js:93:23)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/henry/Code/react-native/node_modules/sane/node_modules/fb-watchman/bser.js:289:10)
    at /Users/henry/Code/react-native/node_modules/sane/node_modules/fb-watchman/bser.js:244:12
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)

However, this React Native app, https://github.com/iSimar/HackerNews-React-Native, runs and starts just fine.

Watchman has been installed per brew and is version 3.7.0:
      
    {  "error": "invalid command (expected an array with some elements!)",
        "cli_validated": true,
        "version": "3.7.0" }

**Comment by chirag04** [comment]
This may sound really lame but i did get this working by just restarting the packager once.

**Comment by hzhu** [comment]
Restarting the packager didn't work for me. However, restarting my computer did. Thanks @chirag04

**Comment by chirag04** [comment]
glad it worked for you. This could be watchman or some cache. @ide ?

**Comment by HendrikPetertje** [comment]
Same error here with Node 4.1.0, Watchman 3.7.0, react-native 2.14.3 on my Macbook pro yosemite.

detailed errors:

react packager output:

    [10:14:05 PM] <START> request:/index.android.bundle?platform=android
    [10:14:05 PM] <START> find dependencies
    Error: query failed: synchronization failed: Operation timed out

        at BunserBuf.<anonymous> (/Users/path_to_user_and_app/testapp/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:93:23)
        at emitOne (events.js:77:13)
        at BunserBuf.emit (events.js:169:7)
        at BunserBuf.process (/Users/path_to_user_and_app/testapp/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/node_modules/bser/index.js:289:10)
        at /Users/path_to_user_and_app/testapp/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/node_modules/bser/index.js:244:12
        at doNTCallback0 (node.js:407:9)
        at process._tickCallback (node.js:336:13)
    Error: query failed: synchronization failed: Operation timed out

        at BunserBuf.<anonymous> (/Users/path_to_user_and_app/testapp/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:93:23)
        at emitOne (events.js:77:13)
        at BunserBuf.emit (events.js:169:7)
        at BunserBuf.process (/Users/path_to_user_and_app/testapp/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/node_modules/bser/index.js:289:10)
        at /Users/path_to_user_and_app/testapp/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/node_modules/bser/index.js:244:12
        at doNTCallback0 (node.js:407:9)
        at process._tickCallback (node.js:336:13)
    [10:17:41 PM] <START> request:/index.ios.bundle
    [10:17:41 PM] <START> find dependencies
    Error: query failed: synchronization failed: Operation timed out

        at BunserBuf.<anonymous> (/Users/path_to_user_and_app/testapp/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:93:23)
        at emitOne (events.js:77:13)
        at BunserBuf.emit (events.js:169:7)
        at BunserBuf.process (/Users/path_to_user_and_app/testapp/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/node_modules/bser/index.js:289:10)
        at /Users/path_to_user_and_app/testapp/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/node_modules/bser/index.js:244:12
        at doNTCallback0 (node.js:407:9)

output from watchman log: (username.log)

    2015-09-20T22:12:13,892: [client:fd=4] path /Users/peter/sites/private/mobile/react/testapp is on filesystem type hfs
    2015-09-20T22:12:17,894: [client:fd=31] send_error_response: fd=31 failed to parse query: must use ["allof", expr...]
    2015-09-20T22:13:36,708: [notify /Users/peter/sites/private/mobile/react/testapp] kFSEventStreamEventFlagRootChanged /Users/peter/sites/private/mobile/react/testapp, cancel watch
    2015-09-20T22:14:36,778: [client:fd=4] sync_to_now: /Users/peter/sites/private/mobile/react/testapp/.watchman-cookie-PeterPro.lan-1254-6-4 timedwait failed: Operation timed out
    2015-09-20T22:14:36,778: [client:fd=4] send_error_response: fd=4 query failed: synchronization failed: Operation timed out

Reinstalling everything didn't help, removing and recreating the project neither, restarting idem
Redoing everything in node 4.0 instead of 4.1.0 works neither.
Android emulator, my nexus 5 and ios emulators give the same problem

anyone here any idea what I can do to get stuff working=

**Comment by ide** [comment]
Try killing the watchman daemon or restarting your computer.

**Comment by HendrikPetertje** [comment]
@ide, did not working.

**Comment by HendrikPetertje** [comment]
upgrading to watchman 3.8.0 seemed to do the trick

**Comment by yunsankai** [comment]
https://github.com/facebook/react-native/issues/2191#issuecomment-143528115

**Comment by matghaleb** [comment]
same error running the `Hello World` example with node 4.21 and watchman 3.9.0.
can't find any solution so far... :(

**Comment by canaandavis** [comment]
Not sure if this is applicable for anyone else, but I was having the same issue.  Had tried upgrading / uninstalling and reinstalling watchman with no luck.  

It's a little strange, I'm using Laravel Homestead for some other projects, which is basically a pre-packaged Vagrant box, during the set up for that you map a directory to the vagrant box in my case ~/Code. Which is where I had my react native tutorial code so ~/Code/AwesomeProject

I was able to get rid of this error by moving my code base out of that directory, that is being mapped, into a different directory.

Everything seems to be working fine now and I'm not too sure why that was causing an issue... 

Hopefully that is useful for someone.  Good luck!

**Comment by yychun1217** [comment]
Same issue here, I am running the UIExplorer example inside react-native project

**Comment by ptaking** [comment]
Same issue here, watchman 4.6.0 and OS X 10.11.2. Tried reinstall, restart, reboot computer...

**Comment by ajmald** [comment]
I Did what facebook recommends us to do !
watchman shutdown-server
brew update
brew reinstall watchman

brew didn’t want to reinstall watchman, did chown and I did

sudo chown root /usr/local/bin/brew

react-native run-ios

Build succeeded,
but still got the dependency graph error and Watchman not running )

jmals-MacBook-Pro:~ ajmal$ ps -ef | grep watchman

501 5268 1 0 10:28PM ?? 0:00.95 /usr/local/Cellar/watchman/4.6.0/libexec/bin/watchman --foreground --logfile=/usr/local/var/run/watchman/ajmal-state/log --log-level=1 --sockname=/usr/local/var/run/watchman/ajmal-state/sock --statefile=/usr/local/var/run/watchman/ajmal-state/state --pidfile=/usr/local/var/run/watchman/ajmal-state/pid
0 5364 1 0 10:28PM ?? 0:00.01 /usr/local/Cellar/watchman/4.6.0/libexec/bin/watchman --foreground --logfile=/usr/local/var/run/watchman/root-state/log --log-level=1 --sockname=/usr/local/var/run/watchman/root-state/sock --statefile=/usr/local/var/run/watchman/root-state/state --pidfile=/usr/local/var/run/watchman/root-state/pid
501 5530 5502 0 10:39PM ttys000 0:00.00 grep watchma

So, Watchman is running in the foreground, where may be lying the ISSUE ?????

**Comment by ajmald** [comment]
I Did what facebook recommends us to do !
watchman shutdown-server
brew update
brew reinstall watchman

brew didn’t want to reinstall watchman, did chown and I did

sudo chown root /usr/local/bin/brew

react-native run-ios

Build succeeded,
but still got the dependency graph error and Watchman not running )

jmals-MacBook-Pro:~ ajmal$ ps -ef | grep watchman

501 5268 1 0 10:28PM ?? 0:00.95 /usr/local/Cellar/watchman/4.6.0/libexec/bin/watchman --foreground --logfile=/usr/local/var/run/watchman/ajmal-state/log --log-level=1 --sockname=/usr/local/var/run/watchman/ajmal-state/sock --statefile=/usr/local/var/run/watchman/ajmal-state/state --pidfile=/usr/local/var/run/watchman/ajmal-state/pid
0 5364 1 0 10:28PM ?? 0:00.01 /usr/local/Cellar/watchman/4.6.0/libexec/bin/watchman --foreground --logfile=/usr/local/var/run/watchman/root-state/log --log-level=1 --sockname=/usr/local/var/run/watchman/root-state/sock --statefile=/usr/local/var/run/watchman/root-state/state --pidfile=/usr/local/var/run/watchman/root-state/pid
501 5530 5502 0 10:39PM ttys000 0:00.00 grep watchma

So, Watchman is running in the foreground, where may be lying the ISSUE ?????
