### ISSUE TITLE
Crash on android 

### ISSUE THREAD

**Issue by huyhai** [facebook/react-native#23170]
i check my crashlytics report, this error happen many times on android 4 : 
Fatal Exception: java.lang.NoClassDefFoundError: com.facebook.react.CoreModulesPackage$1
       at com.facebook.react.CoreModulesPackage.getNativeModules(CoreModulesPackage.java:74)
       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:47)
       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1173)
       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1143)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1085)
       at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:117)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:916)
       at java.lang.Thread.run(Thread.java:838)

my react native version : 0.57.7 
Anyone can help me with this ? Thanks

**Comment by hramos** [comment]
This doesn't look like a bug report, please make sure to follow the template.
