### ISSUE TITLE
Release build crashes Android Exeption

### ISSUE THREAD

**Issue by kangdawei** [facebook/react-native#23182]
## Environment

Environment:
  OS: macOS 10.14.3
  Node: 11.0.0
  Yarn: 1.13.0
  npm: 6.5.0
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.51.0 => 0.51.0

## Description
android devices crash 

## Reproducible Demo
`E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules Process: com.edusoho.bankao, PID: 2901 com.facebook.react.common.JavascriptException: undefined is not a function (evaluating 'this._lazyCallableModules[e]()'), stack: value@32:1919 value@32:3062 <unknown>@32:959 value@32:2640 value@32:931 at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56) at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40) at java.lang.reflect.Method.invoke(Native Method) at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374) at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162) at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) at android.os.Handler.handleCallback(Handler.java:873) at android.os.Handler.dispatchMessage(Handler.java:99) at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) at android.os.Looper.loop(Looper.java:193) at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194) at java.lang.Thread.run(Thread.java:764)`

**Comment by kangdawei** [comment]
> Can you run `react-native info` and edit your issue to include these results under the **Environment** section?
> 
> If you believe this information is irrelevant to the reported issue, you may write `[skip envinfo]` under **Environment** to let us know.

sorry , i update

**Comment by dulmandakh** [comment]
it seems that you're trying to call undefined variable, or it's a bug in your code.

```java
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules Process: com.edusoho.bankao, PID: 2901 com.facebook.react.common.JavascriptException: undefined is not a function (evaluating 'this._lazyCallableModules[e]()'), stack: value@32:1919 value@32:3062 <unknown>@32:959 value@32:2640 value@32:931 at 
```

**Comment by arieldll** [comment]
Hi all,

I am receiving the same error just in RELEASE mode. Android crashes application with error:
2019-12-07 10:50:37.151 14841-14911/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.rasterrn, PID: 14841
    com.facebook.react.common.JavascriptException: Error: Requiring unknown module "undefined"., stack:
    v@2:1306
    d@2:876
    value@1169:8427
    pi@89:51757
    Ml@89:70036
    Ul@89:67144
    Ul@-1
    Pl@89:65839
    Pl@-1
    <unknown>@89:25495
    unstable_runWithPriority@168:3915
    sn@89:25442
    cn@89:25377
    _e@89:88686
    Ne@89:13582
    Ue@89:13755
    receiveEvent@89:14164
    value@25:3685
    <unknown>@25:841
    value@25:2939
    value@25:813
    value@-1
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:176)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)

package.json
```
{"version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/netinfo": "^4.6.1",
    "acorn": "^7.0.0",
    "babel": "^6.23.0",
    "eslint": "^6.7.2",
    "expo": "^35.0.1",
    "moment": "^2.21.0",
    "moment-duration-format": "^2.2.2",
    "moment-timezone": "^0.5.14",
    "native-base": "^2.13.8",
    "native-base-shoutem-theme": "^0.3.1",
    "platform": "^1.3.5",
    "react": "^16.9.0",
    "react-native": "^0.61.5",
    "react-native-background-fetch": "^2.7.1",
    "react-native-background-job": "^2.3.1",
    "react-native-background-task": "^0.2.1",
    "react-native-background-timer": "^2.0.1",
    "react-native-battery": "^0.1.15",
    "react-native-cli": "^2.0.1",
    "react-native-cookies": "^3.3.0",
    "react-native-datepicker": "^1.7.1",
    "react-native-device-battery": "^2.0.0",
    "react-native-device-info": "^5.3.1",
    "react-native-drawer": "^2.5.0",
    "react-native-dropdownalert": "^4.2.0",
    "react-native-flexi-radio-button": "^0.2.2",
    "react-native-geolocation-service": "^3.1.0",
    "react-native-gps-state": "^2.0.3",
    "react-native-image-picker": "^1.1.0",
    "react-native-linear-gradient": "^2.4.0",
    "react-native-local-mongodb": "^2.0.0",
    "react-native-maps-osmdroid": "^0.23.0-rc4",
    "react-native-masked-text": "^1.6.5",
    "react-native-material-dropdown": "^0.11.0",
    "react-native-modal-datetime-picker": "^7.6.0",
    "react-native-modal-dropdown": "^0.7.0",
    "react-native-netinfo": "^1.1.0",
    "react-native-permissions": "^2.0.6",
    "react-native-picker-select": "^6.3.3",
    "react-native-progress": "^4.0.2",
    "react-native-push-notification": "^3.0.2",
    "react-native-queue": "^1.0.1",
    "react-native-responsive-image": "^2.2.1",
    "react-native-router-flux": "^4.0.0-beta.28",
    "react-native-side-menu": "^1.1.3",
    "react-native-sidebar": "^0.3.0",
    "react-native-simple-dialogs": "^1.2.1",
    "react-native-smart-splash-screen": "^2.3.5",
    "react-native-snap-carousel": "^3.7.0",
    "react-native-spinkit": "^1.1.1",
    "react-native-swiper": "^1.5.13",
    "react-native-timer": "^1.3.1",
    "react-native-vector-icons": "^6.6.0",
    "react-native-version-number": "^0.3.6",
    "realm": "^3.5.0",
    "url": "^0.11.0",
    "xmlhttprequest": "^1.8.0"
  },
  "devDependencies": {
    "babel-jest": "^24.9.0",
    "babel-preset-react-native": "^4.0.1",
    "jest": "^24.9.0",
    "react-native-signature-capture": "^0.4.10",
    "react-test-renderer": "^16.12.0",
    "script-loader": "^0.7.2"
  }
```

react-native info
```
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 6.68 GB / 15.90 GB
  Binaries:
    Node: 8.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Users\ariel.dallacosta\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.1 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3, 28.0.0, 28.0.1, 28.0.3, 29.0.2
      System Images: android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-25 | Android Wear ARM EABI v7a, android-25 | Android Wear Intel x86 Atom, android-25 | Google APIs ARM 64 v8a, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: ^16.9.0 => 16.9.0
    react-native: ^0.61.5 => 0.61.5
```

android/build.gradle
```
buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.2'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        google()
    }

    subprojects {
        afterEvaluate {
            project ->
                if (project.hasProperty("android")) {
                    android {
                        compileSdkVersion = 28
                        buildToolsVersion = "28.0.3"
                        defaultConfig {
                            targetSdkVersion 28
                        }
                    }
                }
        }
    }
}
```

app/build.gradle
```
apply plugin: "com.android.application"

import com.android.build.OutputFile

def useIntlJsc = false

project.ext.react = [
        entryFile: "index.js",
        jsBundleDirRelease: "$buildDir/intermediates/merged_assets/release/out",
        enableHermes: false,  // clean and rebuild if changing
        hermesCommand: "../../node_modules/hermes-engine/%OS-BIN%/hermes",
]


def jscFlavor = 'org.webkit:android-jsc:+'
def enableHermes = project.ext.react.get("enableHermes", false);

apply from: "../../node_modules/react-native/react.gradle"

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

android {


    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
        exclude 'META-INF/MANIFEST.MF'
    }

    compileSdkVersion 28
    buildToolsVersion "28.0.3"

    defaultConfig {
        applicationId "com.rasterrn"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 20
        versionName "1.2.14"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
    ext {
        compileSdkVersion   = 28
        targetSdkVersion    = 28
        minSdkVersion = 16
        buildToolsVersion   = "28.0.3"
        androidXCore = "1.0.2"
        googlePlayServicesVersion = "11.8.0"
        androidMapsUtilsVersion = "0.5+"
    }
}

dependencies {
    implementation project(':react-native-maps-osmdroid')
    //implementation project(':react-native-community_geolocation')
    implementation project(':react-native-permissions')
    implementation project(':react-native-version-number')
    implementation project(':react-native-gps-state')
    implementation project(':react-native-device-battery')
    implementation project(':react-native-background-job')
    implementation project(':react-native-image-picker')
    implementation project(':react-native-signature-capture')
    implementation project(':react-native-cookies')
    implementation project(':react-native-push-notification')
    implementation project(':react-native-background-timer')
    implementation project(':realm')
    implementation project(':@react-native-community_geolocation')
    implementation project(':@react-native-community_netinfo')
    implementation project(':react-native-background-task')
    implementation project(':react-native-device-info')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-spinkit')
    implementation project(':react-native-smart-splashscreen')
    implementation project(':react-native-battery')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation(project(':react-native-geolocation-service')) {
        exclude group: 'com.google.android.gms', module: 'play-services-location'
    }
    implementation 'com.google.android.gms:play-services-location:17.0.0'

    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'androidx.appcompat:appcompat:1.0.0'
    implementation "com.facebook.react:react-native:+"  // From node_modules
    /*implementation (project(':react-native-maps')) {
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }*/

    //implementation 'com.google.android.gms:play-services-base:17.0.0'
    //implementation 'com.google.android.gms:play-services-maps:17.0.0'
    implementation 'com.google.android.gms:play-services-base:+'
    implementation 'com.google.android.gms:play-services-maps:+'


    if (enableHermes) {
        def hermesPath = "../../node_modules/hermesvm/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
```

Any idea?

Best Regards
