### ISSUE TITLE
[Packager] Cannot read property 'mtime' of undefined

### ISSUE THREAD

**Issue by MattFoley** [facebook/react-native#2324]
After pulling in the latest master, I'm getting an error and the React Packager will not launch.

```
 ERROR  Cannot read property 'mtime' of undefined
TypeError: Cannot read property 'mtime' of undefined
    at /Users/tfallon/react_proj/node_modules/react-native/packager/react-packager/src/Cache/index.js:190:51
    at Array.forEach (native)
    at Cache._loadCacheSync (/Users/tfallon/react_proj/node_modules/react-native/packager/react-packager/src/Cache/index.js:184:30)
    at new Cache (/Users/tfallon/react_proj/node_modules/react-native/packager/react-packager/src/Cache/index.js:49:19)
    at new Packager (/Users/tfallon/react_proj/node_modules/react-native/packager/react-packager/src/Packager/index.js:88:32)
    at new Server (/Users/tfallon/react_proj/node_modules/react-native/packager/react-packager/src/Server/index.js:111:20)
    at Object.exports.middleware (/Users/tfallon/react_proj/node_modules/react-native/packager/react-packager/index.js:21:16)
    at getAppMiddleware (/Users/tfallon/react_proj/node_modules/react-native/packager/packager.js:229:24)
    at runServer (/Users/tfallon/react_proj/node_modules/react-native/packager/packager.js:256:10)
    at Object.<anonymous> (/Users/tfallon/react_proj/node_modules/react-native/packager/packager.js:159:14)
```

I attempted an `rm -rf node_modules` and an `npm install --force`, but no luck. Anyone else experiencing this issue?

**Comment by chirag04** [comment]
+1

**Comment by MattFoley** [comment]
I've wrapped the `mtime` conditional at ln190 of Cache/index.js in this, seems to clear up the issue.

```
if (!!stat && !!record.metadata) {

}
```

**Comment by jaygarcia** [comment]
+1 I hit this just now with the latest commit on master.

**Comment by sghiassy** [comment]
I've bumped into this too

**Comment by alejomendoza** [comment]
Me too +1

**Comment by browniefed** [comment]
This still happening @MattFoley even without the fix landing?

**Comment by brentvatne** [comment]
Will reopen if this issue persists :smile:
