### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by 74io** [facebook/react-native#2348]
When trying to run the examples from the react-natve master repo I get:
```
Looking for JS files in
   /Users/Air/Sites/reactjs/react-native/examples/react-native 


React packager ready.

 ERROR  shutdown ENOTCONN
{"code":"ENOTCONN","errno":"ENOTCONN","syscall":"shutdown"}
Error: shutdown ENOTCONN
    at exports._errnoException (util.js:812:11)
    at Socket.onSocketFinish (net.js:210:26)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at finishMaybe (_stream_writable.js:468:14)
    at endWritable (_stream_writable.js:478:3)
    at Socket.Writable.end (_stream_writable.js:443:5)
    at Socket.end (net.js:399:31)
    at ChildProcess.<anonymous> (/Users/Air/Sites/reactjs/react-native/examples/react-native/node_modules/sane/node_modules/fb-watchman/index.js:163:17)
    at emitTwo (events.js:87:13)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.

npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/Air/.nvm/versions/io.js/v2.5.0/bin/iojs" "/Users/Air/.nvm/versions/io.js/v2.5.0/bin/npm" "start"
npm ERR! node v2.5.0
npm ERR! npm  v2.13.2
npm ERR! code ELIFECYCLE
npm ERR! react-native@0.8.0 start: `./packager/packager.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-native@0.8.0 start script './packager/packager.sh'.
npm ERR! This is most likely a problem with the react-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./packager/packager.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Air/Sites/reactjs/react-native/examples/react-native/npm-debug.log```

**Comment by grabbou** [comment]
This is fb-watchman issue (1.3.0) version as `sane` uses `^1.1.0`. Temporary workaround: 
```
npm shrinkwrap
```
and edit shrinkwrap.json to set 1.2.0 of fb-watchman explicitly.

**Comment by 74io** [comment]
Many thanks. Works a treat now.

**Comment by grabbou** [comment]
For further reference https://github.com/facebook/watchman/issues/134

**Comment by wez** [comment]
Pushed a speculative fix in fb-watchman 1.4.0.

**Comment by jsierles** [comment]
The speculative fix works for me. I installed fb-watchman 1.4.0 and removed the 1.3.0 version from react-native's node_modules.

**Comment by AbrahamAlcaina** [comment]
Still not working for me.
What are the steps to fix it?

**Comment by browniefed** [comment]
@ide @brentvatne linked https://github.com/facebook/watchman/issues/134 is closed and fixed.

@AbrahamAlcaina need more information to determine your exact issue.

**Comment by ide** [comment]
Try uninstalling and reinstalling watchman.
