### ISSUE TITLE
Huge list of errors when updated to 0.9

### ISSUE THREAD

**Issue by tnguyen42** [facebook/react-native#2353]
Hi,

When updating to 0.9 (npm update), I got a huge list of errors and I don't know if these really matter... But I'm kind of concerned:

```
npm WARN engine stacktrace-parser@0.1.1: wanted: {"node":"~0.10"} (current: {"node":"2.3.4","npm":"2.12.1"})

> utf-8-validate@1.1.0 install /Users/tnguyen/JibberJabber/JibberJabber/node_modules/react-native/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 response dowloading http://nodejs.org/dist/v2.3.4/node-v2.3.4.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:985:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/usr/local/Cellar/iojs/2.3.4/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tnguyen/JibberJabber/JibberJabber/node_modules/react-native/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v2.3.4
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok

> bufferutil@1.1.0 install /Users/tnguyen/JibberJabber/JibberJabber/node_modules/react-native/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 response dowloading http://nodejs.org/dist/v2.3.4/node-v2.3.4.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:985:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/usr/local/Cellar/iojs/2.3.4/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tnguyen/JibberJabber/JibberJabber/node_modules/react-native/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v2.3.4
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0

> fsevents@0.3.8 install /Users/tnguyen/JibberJabber/JibberJabber/node_modules/react-native/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 response dowloading http://nodejs.org/dist/v2.3.4/node-v2.3.4.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:985:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/usr/local/Cellar/iojs/2.3.4/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tnguyen/JibberJabber/JibberJabber/node_modules/react-native/node_modules/babel/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v2.3.4
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.1.0
npm WARN optional dep failed, continuing fsevents@0.3.8
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/Cellar/iojs/2.3.4/bin/iojs" "/usr/local/bin/npm" "update"
npm ERR! node v2.3.4
npm ERR! npm  v2.12.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-native does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-fbsdkcore@0.0.3 wants react-native@^0.8.0
npm ERR! peerinvalid Peer react-native-fbsdklogin@0.0.3 wants react-native@^0.8.0
npm ERR! peerinvalid Peer react-native-fbsdkshare@0.0.3 wants react-native@^0.8.0
npm ERR! peerinvalid Peer react-native-orientation@1.3.0 wants react-native@>=0.5
npm ERR! peerinvalid Peer react-native-scrollable-tab-view@0.1.10 wants react-native@>=0.8.0 || 0.8.0-rc
npm ERR! peerinvalid Peer react-native-svg@0.2.1 wants react-native@>=0.4.4

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tnguyen/JibberJabber/JibberJabber/npm-debug.log
```

Also now, I have this message when I `npm list`:
```
npm ERR! peer invalid: react-native@0.9.0 /Users/tnguyen/JibberJabber/JibberJabber/node_modules/react-native
```

Am I the only one?
Is there anything to do to solve this?

Thanks in advance!

**Comment by chirag04** [comment]
Everything worked fine for me.  One problem is with peerDependency. make sure the modules you use support 0.9.

**Comment by tnguyen42** [comment]
That must be it. Thanks!

**Comment by lazing** [comment]
i have the same issue, and the init hello world app cannot work,
