### ISSUE TITLE
Android App crashed at startup Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by cubeking** [facebook/react-native#23574]
"react": "16.0.0-alpha.6",
"react-native": "0.44.3",
Here is the crash log.

02-21 10:46:53.097 32661-32681/com.zongchuang E/dalvikvm: Could not find class 'android.hardware.camera2.CameraManager', referenced from method com.umeng.commonsdk.internal.utils.j.e
02-21 10:46:53.257 32661-32661/com.zongchuang E/dalvikvm: Could not find class 'com.facebook.react.shell.MainReactPackage$1', referenced from method com.facebook.react.shell.MainReactPackage.getNativeModules
02-21 10:46:53.293 32661-32661/com.zongchuang E/dalvikvm: Could not find class 'okhttp3.OkHttpClient$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.<init>
02-21 10:46:53.297 32661-32661/com.zongchuang E/dalvikvm: Could not find class 'okhttp3.Request$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.enqueueOnChangeEndpointLongPolling
02-21 10:46:53.301 32661-32661/com.zongchuang E/dalvikvm: Could not find class 'okhttp3.Request$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.downloadBundleFromURL
02-21 10:46:53.305 32661-32661/com.zongchuang E/dalvikvm: Could not find class 'okhttp3.Request$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.downloadBundleResourceFromUrlSync
02-21 10:46:53.305 32661-32661/com.zongchuang E/dalvikvm: Could not find class 'okhttp3.Request$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.isPackagerRunning
02-21 10:46:53.309 32661-32661/com.zongchuang E/dalvikvm: Could not find class 'okhttp3.Request$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.launchJSDevtools
02-21 10:46:53.309 32661-32661/com.zongchuang E/dalvikvm: Could not find class 'okhttp3.OkHttpClient$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.startPollingOnChangeEndpoint
02-21 10:46:53.317 32661-32661/com.zongchuang E/MobclickAgent: onPause called before onResume
02-21 10:46:53.353 32661-32661/com.zongchuang E/AndroidRuntime: FATAL EXCEPTION: main
                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zongchuang/com.zongchuang.MainActivity}: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
                                                                    at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                    at android.os.Looper.loop(Looper.java:137)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:525)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                    at dalvik.system.NativeStart.main(Native Method)
                                                                 Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
                                                                    at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:79)
                                                                    at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:336)
                                                                    at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:233)
                                                                    at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:84)
                                                                    at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
                                                                    at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:111)
                                                                    at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:100)
                                                                    at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54)
                                                                    at com.zongchuang.MainActivity.onCreate(MainActivity.java:37)
                                                                    at android.app.Activity.performCreate(Activity.java:5133)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261) 
                                                                    at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                    at android.os.Looper.loop(Looper.java:137) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                    at dalvik.system.NativeStart.main(Native Method) 
                                                                 Caused by: java.lang.reflect.InvocationTargetException
                                                                    at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                    at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:72)
                                                                    at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:336) 
                                                                    at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:233) 
                                                                    at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:84) 
                                                                    at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41) 
                                                                    at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:111) 
                                                                    at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:100) 
                                                                    at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54) 
                                                                    at com.zongchuang.MainActivity.onCreate(MainActivity.java:37) 
                                                                    at android.app.Activity.performCreate(Activity.java:5133) 
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261) 
                                                                    at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                    at android.os.Looper.loop(Looper.java:137) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                    at dalvik.system.NativeStart.main(Native Method) 
                                                                 Caused by: java.lang.NoClassDefFoundError: okhttp3.OkHttpClient$Builder
                                                                    at com.facebook.react.devsupport.DevServerHelper.<init>(DevServerHelper.java:118)
                                                                    at com.facebook.react.devsupport.DevSupportManagerImpl.<init>(DevSupportManagerImpl.java:193)
                                                                    at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                    at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:72) 
                                                                    at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:336) 
                                                                    at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:233) 
                                                                    at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:84) 
                                                                    at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41) 
                                                                    at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:111) 
                                                                    at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:100) 
                                                                    at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54) 
                                                                    at com.zongchuang.MainActivity.onCreate(MainActivity.java:37) 
                                                                    at android.app.Activity.performCreate(Activity.java:5133) 
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261) 
                                                                    at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                    at android.os.Looper.loop(Looper.java:137) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                    at dalvik.system.NativeStart.main(Native Method)

**Comment by hramos** [comment]
0.44 is quite old, and opening an issue that's simply a crash log is not helpful. Please take a look at the template so we can help you.
