### ISSUE TITLE
Android App crashed at startup Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by cubeking** [facebook/react-native#23582]
## 🐛 Bug Report
Android App crashed  when startup
here is crash log in android

02-21 10:46:53.097 32661-32681/com.zongchuang E/dalvikvm: Could not find class 'android.hardware.camera2.CameraManager', referenced from method com.umeng.commonsdk.internal.utils.j.e
02-21 10:46:53.257 32661-32661/com.zongchuang E/dalvikvm: Could not find class 'com.facebook.react.shell.MainReactPackage$1', referenced from method com.facebook.react.shell.MainReactPackage.getNativeModules
02-21 10:46:53.293 32661-32661/com.zongchuang E/dalvikvm: Could not find class 'okhttp3.OkHttpClient$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.
02-21 10:46:53.297 32661-32661/com.zongchuang E/dalvikvm: Could not find class 'okhttp3.Request$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.enqueueOnChangeEndpointLongPolling
02-21 10:46:53.301 32661-32661/com.zongchuang E/dalvikvm: Could not find class 'okhttp3.Request$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.downloadBundleFromURL
02-21 10:46:53.305 32661-32661/com.zongchuang E/dalvikvm: Could not find class 'okhttp3.Request$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.downloadBundleResourceFromUrlSync
02-21 10:46:53.305 32661-32661/com.zongchuang E/dalvikvm: Could not find class 'okhttp3.Request$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.isPackagerRunning
02-21 10:46:53.309 32661-32661/com.zongchuang E/dalvikvm: Could not find class 'okhttp3.Request$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.launchJSDevtools
02-21 10:46:53.309 32661-32661/com.zongchuang E/dalvikvm: Could not find class 'okhttp3.OkHttpClient$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.startPollingOnChangeEndpoint
02-21 10:46:53.317 32661-32661/com.zongchuang E/MobclickAgent: onPause called before onResume
02-21 10:46:53.353 32661-32661/com.zongchuang E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zongchuang/com.zongchuang.MainActivity}: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
at android.app.ActivityThread.access$600(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5103)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:79)
at com.facebook.react.ReactInstanceManager.(ReactInstanceManager.java:336)
at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:233)
at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:84)
at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:111)
at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:100)
at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54)
at com.zongchuang.MainActivity.onCreate(MainActivity.java:37)
at android.app.Activity.performCreate(Activity.java:5133)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261) 
at android.app.ActivityThread.access$600(ActivityThread.java:141) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at android.os.Looper.loop(Looper.java:137) 
at android.app.ActivityThread.main(ActivityThread.java:5103) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:525) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
at dalvik.system.NativeStart.main(Native Method) 
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.constructNative(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:72)
at com.facebook.react.ReactInstanceManager.(ReactInstanceManager.java:336) 
at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:233) 
at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:84) 
at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41) 
at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:111) 
at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:100) 
at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54) 
at com.zongchuang.MainActivity.onCreate(MainActivity.java:37) 
at android.app.Activity.performCreate(Activity.java:5133) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261) 
at android.app.ActivityThread.access$600(ActivityThread.java:141) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at android.os.Looper.loop(Looper.java:137) 
at android.app.ActivityThread.main(ActivityThread.java:5103) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:525) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
at dalvik.system.NativeStart.main(Native Method) 
Caused by: java.lang.NoClassDefFoundError: okhttp3.OkHttpClient$Builder
at com.facebook.react.devsupport.DevServerHelper.(DevServerHelper.java:118)
at com.facebook.react.devsupport.DevSupportManagerImpl.(DevSupportManagerImpl.java:193)
at java.lang.reflect.Constructor.constructNative(Native Method) 
at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:72) 
at com.facebook.react.ReactInstanceManager.(ReactInstanceManager.java:336) 
at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:233) 
at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:84) 
at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41) 
at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:111) 
at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:100) 
at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54) 
at com.zongchuang.MainActivity.onCreate(MainActivity.java:37) 
at android.app.Activity.performCreate(Activity.java:5133) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261) 
at android.app.ActivityThread.access$600(ActivityThread.java:141) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at android.os.Looper.loop(Looper.java:137) 
at android.app.ActivityThread.main(ActivityThread.java:5103) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:525) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
at dalvik.system.NativeStart.main(Native Method)

## To Reproduce
Unknown

## Expected Behavior
Behaving normally, without crashing...

## Code Example
    compileSdkVersion 27
    buildToolsVersion "27.0.3"
    defaultConfig {
        applicationId "projectname"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true

    }

dependencies {
    compile project(':jmessage-react-plugin')
    compile project(':jcore-react-native')
    compile (project(':aurora-imui-react-native')) {
        exclude group: 'com.android.support'
    }
    compile fileTree(include: ['*.jar'], dir: 'libs')
    // Add your support libraries, versions must match compileSdkVersion.
    compile 'com.android.support:appcompat-v7:27.1.0'
    compile 'com.facebook.react:react-native:+'
    ...
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.squareup.okhttp3:okhttp:3.3.1'

## Environment
{
	"name": "projectname",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"aurora-imui-react-native": "^0.4.12",
		"babel-plugin-transform-decorators-legacy": "^1.3.5",
		"babel-preset-react-native-stage-0": "^1.0.1",
		"jcore-react-native": "^1.2.11",
		"jmessage-react-plugin": "^3.1.1",
		"lodash": "^4.17.11",
		"mobx": "^5.9.0",
		"mobx-react": "^5.4.3",
		"query-string": "^6.2.0",
		"react": "16.0.0-alpha.6",
		"react-native": "0.44.3",
		"react-native-vector-icons": "^4.4.2",
		"react-navigation": "^1.5.2",
		"react-timer-mixin": "^0.13.3",
		"teaset": "^0.5.10",
		"xmldom": "^0.1.27"
	},

}

skip envinfo

**Comment by cubeking** [comment]
> Can you run `react-native info` and edit your issue to include these results under the **Environment** section?
> 
> If you believe this information is irrelevant to the reported issue, you may write `[skip envinfo]` under **Environment** to let us know.

has done it.

**Comment by hramos** [comment]
Tracking individual crashes is out of scope for this repository, especially without a solid minimal repro case. The version of React Native you're using is 0.44 which is quite old at this time. I'm not sure we will be able to help you, I am afraid.
