### ISSUE TITLE
react-native run-android doesn't work on mac os

### ISSUE THREAD

**Issue by huuthinh245** [facebook/react-native#23619]
## 🐛 Bug Report

BUILD FAILED in 6s
106 actionable tasks: 6 executed, 100 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: ./gradlew installDebug

Error: Command failed: ./gradlew installDebug
    at checkExecSyncError (child_process.js:637:11)
    at Object.execFileSync (child_process.js:655:13)
    at runOnAllDevices (/Users/thinh/Documents/RNFramework/node_modules/react-native/local-cli/runAndroid/runAndroid.js:299:19)
    at buildAndRun (/Users/thinh/Documents/RNFramework/node_modules/react-native/local-cli/runAndroid/runAndroid.js:135:12)
    at isPackagerRunning.then.result (/Users/thinh/Documents/RNFramework/node_modules/react-native/local-cli/runAndroid/runAndroid.js:65:12)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

## Environment

  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 71.45 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.0 - ~/.nvm/versions/node/v11.10.0/bin/node
      Yarn: 1.13.0 - ~/.nvm/versions/node/v11.10.0/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Google Play Intel x86 Atom
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.5 => 0.58.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by huuthinh245** [comment]
Hello the issue solved sovled, the error throw by missing multiDexEnabled: true in android project.
