### ISSUE TITLE
React Native Release APK crash on Android Device - Could not get BatchedBridge, make sure your bundle is packaged correctly

### ISSUE THREAD

**Issue by jasonlee910** [facebook/react-native#23649]
App is running well on Android emulator but not working on my device.
I exported app-release.apk using `./gradlew assemblerelease'.
App is crashing when I open it on my device.
I tried to know crash reason with debugging on Android Studio.

Here's its logcat detail:
`E/AndroidRuntime: FATAL EXCEPTION: mqt_js
    Process: com.pjapp, PID: 19063
    java.lang.RuntimeException: com.facebook.react.devsupport.JSException: Could not get BatchedBridge, make sure your bundle is packaged correctly
        at com.facebook.react.bridge.DefaultNativeModuleCallExceptionHandler.handleException(DefaultNativeModuleCallExceptionHandler.java:24)
        at com.facebook.react.devsupport.DisabledDevSupportManager.handleException(DisabledDevSupportManager.java:158)
        at com.facebook.react.cxxbridge.CatalystInstanceImpl.onNativeException(CatalystInstanceImpl.java:431)
        at com.facebook.react.cxxbridge.CatalystInstanceImpl.access$400(CatalystInstanceImpl.java:51)
        at com.facebook.react.cxxbridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:447)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:33)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.facebook.react.devsupport.JSException: Could not get BatchedBridge, make sure your bundle is packaged correctly
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
        at android.os.Looper.loop(Looper.java:164) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: com.facebook.jni.CppException: Could not get BatchedBridge, make sure your bundle is packaged correctly
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
        at android.os.Looper.loop(Looper.java:164) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
        at java.lang.Thread.run(Thread.java:764) 
2019-02-26 05:10:41.278 3779-3822/? E/PhoneWindow_APM :: sendNotificationForAppPermissionMonitor callingPid = 3779, uid = 1000
2019-02-26 05:10:41.278 3779-3822/? E/PhoneWindow_APM :: sendNotificationForAppPermissionMonitor 2
2019-02-26 05:10:41.278 3779-3822/? E/PhoneWindow_APM :: sendNotificationForAppPermissionMonitor 21000_3779
2019-02-26 05:10:41.278 3779-3822/? E/PhoneWindow_APM :: isCalledPackage return true
2019-02-26 05:10:41.395 5292-5447/? E/PBSessionCacheImpl: sessionId[23276013193869089] not persisted.
2019-02-26 05:10:41.430 4311-4332/? E/ApplicationPackageManager: checkSettingsForIconTray value : 0
2019-02-26 05:10:41.436 4311-4332/? E/ApplicationPackageManager: checkSettingsForIconTray value : 0
2019-02-26 05:10:41.645 3414-3686/? E/IptablesRestoreController: [iptables debug]iptables-restore execute *filter`

I really hope to get your talented answers:)

**Comment by zhanglianfang** [comment]
I had the same problem ，How to solve the problem in the end?

**Comment by tgensol** [comment]
I am getting this error when using the new **HermesEngine** with RN 0.60.3.. Any idea ?
