### ISSUE TITLE
while react-native link react-native-razorpay error coming

### ISSUE THREAD

**Issue by raja91735** [facebook/react-native#23706]
## To Reproduce

sudo react-native link react-native-razorpay
rnpm-install info Linking react-native-razorpay ios dependency 
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'buildConfigurationList' of undefined 
Please file an issue here: https://github.com/facebook/react-native/issues 

Cannot read property 'buildConfigurationList' of undefined

TypeError: Cannot read property 'buildConfigurationList' of undefined
    at /home/admin1/Documents/supersevanew/node_modules/react-native/local-cli/link/ios/getTargets.js:18:68
    at Array.map (<anonymous>)
    at getTargets (/home/admin1/Documents/supersevanew/node_modules/react-native/local-cli/link/ios/getTargets.js:16:18)
    at registerNativeModuleIOS (/home/admin1/Documents/supersevanew/node_modules/react-native/local-cli/link/ios/registerNativeModule.js:56:3)
    at Object.registerNativeModule [as register] (/home/admin1/Documents/supersevanew/node_modules/react-native/local-cli/link/ios/common/registerNativeModule.js:15:5)
    at Object.keys.forEach.platform (/home/admin1/Documents/supersevanew/node_modules/react-native/local-cli/link/link.js:74:16)
    at Array.forEach (<anonymous>)
    at linkDependency (/home/admin1/Documents/supersevanew/node_modules/react-native/local-cli/link/link.js:44:32)
    at <anonymous>

**Comment by raja91735** [comment]
My Environment

React Native Environment Info:
    System:
      OS: Linux 4.4 Linux Mint 18.1 (Serena)
      CPU: x64 Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz
      Memory: 513.99 MB / 7.71 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/bin/node
      Yarn: 1.7.0 - /usr/bin/yarn
      npm: 5.6.0 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.2 => 0.57.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by raja91735** [comment]
where i need to write   [skip envinfo]   bro

**Comment by hramos** [comment]
The CLI has since been moved, please file an issue here: https://github.com/react-native-community/react-native-cli/issues
