### ISSUE TITLE
when i run react-native run-android (how to solve this problem)

### ISSUE THREAD

**Issue by jackytallow** [facebook/react-native#23741]
D:\tools\nodejs\node_cache>cd D:\tools\nodejs\node_cache\FirstProject

D:\tools\nodejs\node_cache\FirstProject>react-native run-android
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'D:\tools\nodejs\node_cache\FirstProject\node_modules\react-native-cli\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by jackytallow** [comment]
also,I find my system 's module I have
