### ISSUE TITLE
react-native-git-upgrade: Error Couldn't Find Match

### ISSUE THREAD

**Issue by karltaylor** [facebook/react-native#23842]
## 🐛 Bug Report

Can't use `react-native-git-upgrade` because it throws an error:

It is reference a commit sha pointing to [apache/cordova-node-xcode](https://github.com/apache/cordova-node-xcode/commits/e7646f0680d509b590b839e567c217590451505b)

## To Reproduce
```
$ react-native-git-upgrade
```

## Expected Behavior
Should update.

## Code Example
```
$ react-native-git-upgrade
git-upgrade info Check for updates
git-upgrade info Using yarn 1.13.0
git-upgrade info Read package.json files
git-upgrade info Check declared version
git-upgrade info Check matching versions
git-upgrade info Check React peer dependency
git-upgrade info Check that Git is installed
git-upgrade info Get information from NPM registry
git-upgrade info Upgrading to React Native 0.58.6, React 16.6.3
git-upgrade info Setup temporary working directory
git-upgrade info Configure Git environment
git-upgrade info Init Git repository
git-upgrade info Add all files to commit
git-upgrade info Commit current project sources
git-upgrade info Create a tag before updating sources
git-upgrade info Generate old version template
git-upgrade info Add updated files to commit
git-upgrade info Commit old version template
git-upgrade info Install the new version
error Couldn't find match for "e7646f0680d509b590b839e567c217590451505b" in "refs/heads/1.0.x,refs/heads/1.1.x,refs/heads/2.0.x,refs/heads/brodybits-introduce-eslint,refs/heads/master,refs/tags/1.0.0,refs/tags/1.1.0,refs/tags/2.0.0,refs/tags/rel/1.0.0,refs/tags/rel/1.1.0,refs/tags/rel/2.0.0" for "https://github.com/apache/cordova-node-xcode.git".
git-upgrade ERR! An error occurred during upgrade:
git-upgrade ERR! Error: Command 'yarn add react-native@0.58.6 react@16.6.3' exited with code 1:
stderr: undefinederror Couldn't find match for "e7646f0680d509b590b839e567c217590451505b" in "refs/heads/1.0.x,refs/heads/1.1.x,refs/heads/2.0.x,refs/heads/brodybits-introduce-eslint,refs/heads/master,refs/tags/1.0.0,refs/tags/1.1.0,refs/tags/2.0.0,refs/tags/rel/1.0.0,refs/tags/rel/1.1.0,refs/tags/rel/2.0.0" for "https://github.com/apache/cordova-node-xcode.git".

stdout: yarn add v1.13.0
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

    at ChildProcess.child.on.code (/Users/karltaylor/.nvm/versions/node/v10.15.1/lib/node_modules/react-native-git-upgrade/cliEntry.js:58:18)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
git-upgrade ERR! Restore initial sources
Note: checking out 'project-snapshot'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 1521300 Project snapshot
```

## Environment
```

  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
      Memory: 32.34 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: ^0.57.7 => 0.57.7
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7
```

**Comment by karltaylor** [comment]
@react-native-bot lol

**Comment by 3luyka** [comment]
@react-native-bot lol xD

**Comment by karltaylor** [comment]
I updated manually and it was an absolutely awful experience. Thanks.
