### ISSUE TITLE
RNTester doesn't work

### ISSUE THREAD

**Issue by tipoc123** [facebook/react-native#23936]
## 🐛 Bug Report
I can't force to work your sample RNTester according to manual https://github.com/facebook/react-native/tree/master/RNTester

## To Reproduce
1. `git clone https://github.com/facebook/react-native.git`. It's OK!
2. `cd react-native`
3. `npm install`. It's OK, but shows some warnings:
```
npm WARN @react-native-community/cli@1.4.2 requires a peer of react-native@^0.59.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-fbjs@2.0.1 requires a peer of babel-eslint@^7.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-fbjs@2.0.1 requires a peer of eslint@^4.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-fbjs@2.0.1 requires a peer of eslint-plugin-babel@^4.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-fb-strict@22.1.0 requires a peer of babel-eslint@^7.2.3 || ^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-fb-strict@22.1.0 requires a peer of eslint@^4.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-fb-strict@22.1.0 requires a peer of eslint-plugin-babel@^4.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.8.2 requires a peer of eslint@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-jsx-a11y@6.0.3 requires a peer of eslint@^3 || ^4 but none is installed. You must install peer dependencies yourself.
npm WARN jest-resolve-dependencies@24.5.0 requires a peer of jest-haste-map@^24.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN jest-snapshot@24.5.0 requires a peer of jest-haste-map@^24.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN jest-resolve@24.5.0 requires a peer of jest-haste-map@^24.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package jest-junit is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```
4. Prerequisites steps (https://facebook.github.io/react-native/docs/building-from-source.html#android):
a) Set ANDROID_SDK and ANDROID_NDK (in ~/.bash_profile).
b) Create RNTester/android/local.properties (with sdk.dir and ndk.dir properties within).
5. `./gradlew :RNTester:android:app:installDebug`. It's OK. Apk was installed on my android STB device.
6. `./scripts/packager.sh`. It's FAILED. Output:
`error Unable to find React Native files. Make sure "react-native" module is installed in your project dependencies.`

Then I open installed RNTesterApp on my device:
![screen](https://user-images.githubusercontent.com/15922591/54389395-05aeac80-46b1-11e9-8b20-f31ef021c04b.png)

Logcat error:
```
03-14 23:09:49.718 E/unknown:ReactNative(20905): Exception in native call
03-14 23:09:49.718 E/unknown:ReactNative(20905): java.lang.RuntimeException: Unable to load script. Make sure you're either running a Metro server (run 'react-native start') or that your bundle 'RNTesterApp.android.bundle' is packaged correctly for release.
03-14 23:09:49.718 E/unknown:ReactNative(20905): 	at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
03-14 23:09:49.718 E/unknown:ReactNative(20905): 	at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:218)
03-14 23:09:49.718 E/unknown:ReactNative(20905): 	at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:31)
03-14 23:09:49.718 E/unknown:ReactNative(20905): 	at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:247)
03-14 23:09:49.718 E/unknown:ReactNative(20905): 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1152)
03-14 23:09:49.718 E/unknown:ReactNative(20905): 	at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:123)
03-14 23:09:49.718 E/unknown:ReactNative(20905): 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:943)
03-14 23:09:49.718 E/unknown:ReactNative(20905): 	at java.lang.Thread.run(Thread.java:818)
```

Then I close RNTesterApp and run it again. It shows only white screen. Logcat:
```
03-14 23:31:21.125 W/unknown:ReconnectingWebSocket(20905): Couldn't connect to "ws://localhost:8081/message?device=p212%20-%206.0.1%20-%20API%2023&app=com.facebook.react.uiapp&clientid=DevSupportManagerImpl", will silently retry

```

## Environment

Ubuntu 18.04.2 LTS
Android 6.0.1

**Comment by tipoc123** [comment]
I run next command in cloned repository:
```
tipoc@tipoc-MS-7817:~/Desktop/react-native$ react-native info
Command `info` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.
```

**Comment by Automobileengineeringservices** [comment]
#23936

**Comment by grabbou** [comment]
Thanks. I am on it.

**Comment by tipoc123** [comment]
Still doesn't work. The same errors.

Did you try to install RNTester by yourself?

**Comment by cdskill** [comment]
any solution ? I encounter probably the same issue ... 
![image](https://user-images.githubusercontent.com/12627583/54680580-7f5bf580-4b0a-11e9-9176-7994aea16785.png)

**Comment by JserJser** [comment]
> any solution ? I encountered probably the same issue ...
> ![image](https://user-images.githubusercontent.com/12627583/54680580-7f5bf580-4b0a-11e9-9176-7994aea16785.png)



> Thanks. I am on it.

![image](https://user-images.githubusercontent.com/30041386/55317080-62c4a380-54a2-11e9-9b4b-c1dfbdc49d11.png)
i also have this problem。your answer can not help me . you  use docker? i don not use it .and some text in package.json can not find

**Comment by sunnylqm** [comment]
ping @grabbou

**Comment by grabbou** [comment]
Have you started packager? Run `yarn start` from root of React Native.
