### ISSUE TITLE
react-native run-ios --simulator without empty spaces

### ISSUE THREAD

**Issue by matteomatassoni** [facebook/react-native#23947]
## 🐛 Bug Report

React Native is unable to launch apps on an iOS simulator instance if its name does not contain any empty spaces.

## To Reproduce

1. create an iOS Simulator instance with a name that does not contain any empty spaces (e.g. `aSimulator`)
  ```shell
  xcrun simctl create aSimulator com.apple.CoreSimulator.SimDeviceType.iPhone-SE com.apple.CoreSimulator.SimRuntime.iOS-12-1
  ```
2. create a new React Native app
3. Lanch the app created in the second step on the iOS simulator instance created in the first step.
  ```shell
  react-native run-ios --simulator="aSimulator"
  ```

### Output  
```
react-native run-ios --simulator="aSimulator"
Found Xcode project themoviedb.xcodeproj

Cannot read property '2' of null

TypeError: Cannot read property '2' of null
    at findMatchingSimulator (/Users/matax/Developer/ReactNative/themoviedb/node_modules/react-native/local-cli/runIOS/findMatchingSimulator.js:34:26)
    at resolve (/Users/matax/Developer/ReactNative/themoviedb/node_modules/react-native/local-cli/runIOS/runIOS.js:147:31)
    at new Promise (<anonymous>)
    at runOnSimulator (/Users/matax/Developer/ReactNative/themoviedb/node_modules/react-native/local-cli/runIOS/runIOS.js:134:10)
    at Object.runIOS [as func] (/Users/matax/Developer/ReactNative/themoviedb/node_modules/react-native/local-cli/runIOS/runIOS.js:106:12)
    at Promise.resolve.then (/Users/matax/Developer/ReactNative/themoviedb/node_modules/react-native/local-cli/cliEntry.js:117:22)
```

## Expected Behavior

React Native should launch apps on iOS simulator instances regardless of their name.

## Environment

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
      Memory: 3.89 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.10.1 - /usr/local/bin/node
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 28.0.3
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.6 => 0.58.6 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

```

**Comment by ferrannp** [comment]
Hello there 👋

Could you try with the latest RN version 0.59.x? If the issue persist, can you post an issue into https://github.com/react-native-community/react-native-cli ? (CLI has been extracted).
