### ISSUE TITLE
 For security reasons, WebView is not allowed in privileged processes

### ISSUE THREAD

**Issue by aihui109** [facebook/react-native#23948]
RN:0.58.1
OS:android 8.1

if AndroidManifest.xml set android:sharedUserId="android.uid.system",
I see the following error (on react-native run-android):

java.lang.UnsupportedOperationException: For security reasons, WebView is not allowed in privileged processes
  at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:96)
  at android.webkit.WebView.getFactory(WebView.java:2194)
  at android.webkit.WebView.ensureProviderCreated(WebView.java:2189)
  at android.webkit.WebView.setOverScrollMode(WebView.java:2248)
  at android.view.View.<init>(View.java:3588)
  at android.view.View.<init>(View.java:3682)
  at android.view.ViewGroup.<init>(ViewGroup.java:497)
  at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
  at android.webkit.WebView.<init>(WebView.java:544)
  at android.webkit.WebView.<init>(WebView.java:489)
  at android.webkit.WebView.<init>(WebView.java:472)
  at android.webkit.WebView.<init>(WebView.java:459)
  at android.webkit.WebView.<init>(WebView.java:449)

**Comment by dulmandakh** [comment]
WebView in React Native is deprecated and will be removed in the future. It's forked and maintained at https://github.com/react-native-community/react-native-webview, please use it and file an issue there.
