### ISSUE TITLE
Can't use react-native init Project . Why?   Node -v 11.11.0   Npm -v 6.9.0

### ISSUE THREAD

**Issue by Alicoo1907** [facebook/react-native#24093]
C:\ReactNative>react-native init MyProject
This will walk you through creating a new React Native project in C:\ReactNative\MyProject
'yarn' is not recognized as an internal or external command,
operable program or batch file.
Installing react-native...
Consider installing yarn to make this faster: https://yarnpkg.com
npm ERR! Unexpected end of JSON input while parsing near '..."_hasShrinkwrap":fals'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alico\AppData\Roaming\npm-cache\_logs\2019-03-21T16_33_09_718Z-debug.log
{ Error: Command failed: npm install --save --save-exact react-native
    at checkExecSyncError (child_process.js:637:11)
    at execSync (child_process.js:674:13)
    at run (C:\Users\alico\AppData\Roaming\npm\node_modules\react-native-cli\index.js:294:5)
    at createProject (C:\Users\alico\AppData\Roaming\npm\node_modules\react-native-cli\index.js:249:3)
    at init (C:\Users\alico\AppData\Roaming\npm\node_modules\react-native-cli\index.js:200:5)
    at Object.<anonymous> (C:\Users\alico\AppData\Roaming\npm\node_modules\react-native-cli\index.js:153:7)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 9476,
  stdout: null,
  stderr: null }
Command `npm install --save --save-exact react-native` failed.

**Comment by patrickkempff** [comment]
@Alicoo1907 it seems you dont have yarn installed, can you verify this?

**Comment by patrickkempff** [comment]
@Alicoo1907 did you find a solution?

**Comment by Alicoo1907** [comment]
Yes

**Comment by devs4522** [comment]
@Alicoo1907 Then what is the solution ? I m still facing same issue. node -v: 10.15.3, npm -v: 6.9.0

**Comment by Alicoo1907** [comment]
I dont remember solution now. I can check my computer and tell you

**Comment by devs4522** [comment]
Please let me know the solution asap. Appreciation in advance.:)

**Comment by Alicoo1907** [comment]
my udemy teacher send this link 
https://github.com/npm/npm/issues/13345
