### ISSUE TITLE
[Android] java.net.SocketException: Software caused connection abort 

### ISSUE THREAD

**Issue by quy-thi** [facebook/react-native#24142]
## 🐛 Bug Report
 ```
 Caused by com.facebook.react.bridge.JavaJSExecutor$ProxyExecutorException: java.net.SocketException: Software caused connection abort
       at com.facebook.react.devsupport.WebsocketJavaScriptExecutor.loadApplicationScript(WebsocketJavaScriptExecutor.java:167)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:154)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:762)
```
## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 36.82 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 21, 22, 23, 26, 27, 28
        Build Tools: 23.0.1, 27.0.3, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.3 => 16.8.4 
      react-native: ^0.58.6 => 0.58.6 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-camera: 1.12.0
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2

I face this crash on Android and I have no idea why this happens, seem like core issue of RN

**Comment by dusan-dragon** [comment]
I am getting this error too on the newest version of RN (v0.59.1)
