### ISSUE TITLE
Android crashes when opened on Release when upgraded from 0.55.2 to RN 0.57.1 and RN 0.59.3 (evaluating 'u.context')

### ISSUE THREAD

**Issue by eduardo-schork** [facebook/react-native#24259]
## 🐛 Bug Report

App crashes when opened in Android release **(debug works fine)** after I upgraded it RN to 0.57.1, this happened too in RN 0.55.2 so I upgraded to RN to 0.57.1 to try to fix it. 🤷‍ 

## 🕵️ To Reproduce 🐱‍👤

1. Setup release configurations.
2. Connect a device and run `react-native run-android --variant=release` or `cd android && gradlew assembleRelease`.
3. And this exception occurs:

```
null is not an object (evaluating 'u.context')
ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
FATAL EXCEPTION: mqt_native_modules
Process: com.nelson, PID: 5227
com.facebook.react.common.JavascriptException: null is not an object (evaluating 'u.context'), stack:
default@755:9356
<unknown>@751:177
v@2:1489
d@2:949
o@2:435
<unknown>@337:284
v@2:1489
d@2:949
o@2:435
<unknown>@12:58
v@2:1489
d@2:879
o@2:435
global code@1301:4
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:193)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:764)
ActivityManager:   Force finishing activity com.nelson/.MainActivity
ActivityManager: Showing crash dialog for package com.nelson u0
BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
```

## 🔥 Expected Behavior 🔥
  Generate a working Release APK. 🧙‍♂

## 📚 My package.json 📖

```
{
  "name": "nelson",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@babel/preset-react": "^7.0.0",
    "axios": "^0.18.0",
    "babel-preset-react-native": "^2.1.0",
    "lodash": "^4.17.11",
    "native-base": "^2.10.0",
    "npm": "^6.4.1",
    "react": "16.3.1",
    "react-native": "0.57.1",
    "react-native-animate-number": "^0.1.2",
    "react-native-collapsible": "^0.13.0",
    "react-native-hyperlink": "0.0.14",
    "react-native-image-picker": "^0.28.0",
    "react-native-image-resizer": "^1.0.0",
    "react-native-keyboard-aware-scroll-view": "^0.7.4",
    "react-native-masked-text": "^1.10.1",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-onesignal": "^3.2.12",
    "react-native-router-flux": "^4.0.6",
    "react-native-sqlite-storage": "^3.3.10",
    "react-native-swiper": "^1.5.14",
    "react-native-tab-view": "^1.3.1",
    "react-native-thumbnail-video": "^0.1.2",
    "react-native-vector-icons": "^6.4.0",
    "react-native-youtube": "^1.1.0",
    "react-redux": "^6.0.0",
    "reactotron-redux": "^2.1.3",
    "reactotron-redux-saga": "^4.0.1",
    "redux": "^4.0.1",
    "redux-saga": "^1.0.1",
    "rn-fetch-blob": "^0.10.15",
    "rnpm": "^1.9.0",
    "xcode": "^1.1.0"
  },
  "devDependencies": {
    "@babel/plugin-external-helpers": "^7.2.0",
    "babel-plugin-root-import": "^6.1.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "babel-root-import": "^4.0.1",
    "jest-react-native": "^18.0.0",
    "metro-react-native-babel-preset": "^0.53.1",
    "react-test-renderer": "16.3.1",
    "reactotron-react-native": "^2.1.4",
    "schedule": "0.4.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

```
## 👩‍💻 Environment 👩‍💻

React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz
      Memory: 2.39 GB / 7.95 GB
    Binaries:
      Yarn: 1.10.1 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - ~\AppData\Roaming\npm\npm.CMD

😃 **Thank you in advance** 🙏🤙

##  ✍ **EDIT** ✍

I upgrade my RN to version 0.59.3 but the same error persists (only in Release mode, debug works fine)

`null is not an object (evaluating 'u.context')`

my new package.json: 

```
{
  "name": "nelson",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@babel/preset-react": "^7.0.0",
    "axios": "^0.18.0",
    "babel-preset-react-native": "^2.1.0",
    "lodash": "^4.17.11",
    "native-base": "^2.12.1",
    "npm": "^6.9.0",
    "react": "16.8.3",
    "react-native": "0.59.3",
    "react-native-animate-number": "^0.1.2",
    "react-native-collapsible": "^0.13.0",
    "react-native-hyperlink": "0.0.14",
    "react-native-image-picker": "^0.28.1",
    "react-native-image-resizer": "^1.0.1",
    "react-native-keyboard-aware-scroll-view": "^0.7.4",
    "react-native-masked-text": "^1.11.1",
    "react-native-modal-datetime-picker": "^6.1.0",
    "react-native-onesignal": "^3.2.12",
    "react-native-router-flux": "^4.0.6",
    "react-native-sqlite-storage": "^3.3.10",
    "react-native-swiper": "^1.5.14",
    "react-native-tab-view": "^1.3.4",
    "react-native-thumbnail-video": "^0.1.2",
    "react-native-vector-icons": "^6.4.0",
    "react-native-youtube": "^1.1.0",
    "react-redux": "^6.0.1",
    "reactotron-redux": "^2.1.3",
    "reactotron-redux-saga": "^4.2.1",
    "redux": "^4.0.1",
    "redux-saga": "^1.0.2",
    "rn-fetch-blob": "^0.10.15",
    "rnpm": "^1.9.0",
    "xcode": "^1.1.0"
  },
  "devDependencies": {
    "@babel/plugin-external-helpers": "^7.2.0",
    "babel-plugin-root-import": "^6.1.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "babel-root-import": "^4.0.1",
    "jest-react-native": "^18.0.0",
    "metro-react-native-babel-preset": "^0.53.1",
    "react-test-renderer": "16.3.1",
    "reactotron-react-native": "^2.2.0",
    "schedule": "0.4.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by FibreFoX** [comment]
Did you compare your android-files to a complete new RN 0.59.3 project? Maybe some older changes like a custom webkit-core was added in that project? Did you try to make a full clean of the gradle-folders (gradle does a lot of caching)?

**Comment by eduardo-schork** [comment]
@FibreFoX Thanks for answer

I found the problem in my Redux's store index, in my store creator I had this line to instance my saga monitor:

`const sagaMonitor = __DEV__ ? console.tron.createSagaMonito() : null`

so, when I build the app in release mode it start's the `sagaMonitor` with `null` and throws an error.

I changed the line to: 

`const sagaMonitor = console.tron.createSagaMonitor()` 

and it works fine. 😅
