### ISSUE TITLE
Cannot start react native app from service.

### ISSUE THREAD

**Issue by seunlanlege** [facebook/react-native#24280]
## 🐛 Bug Report

When I launch my application from a service, adb logs show that the app fails to find some shared libs and as a result the app fails to launch

## To Reproduce
Launch the MainActivity from a service

## Expected Behavior
The app should launch

## Code Example
```java
        String packageName = mContext.getApplicationContext().getPackageName();
        Intent launchIntent = mContext.getPackageManager().getLaunchIntentForPackage(packageName);

        launchIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        launchIntent.putExtra("data", data.getString("data"));
        mContext.startActivity(launchIntent);
```

## Environment
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
      Memory: 590.04 MB / 15.55 GB
      Shell: 5.4.2 - /bin/zsh
    Binaries:
      Node: 11.10.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 16, 23, 24, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-25 | Google APIs Intel x86 Atom
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.5 => 0.58.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

adb logs

```

04-02 21:47:37.856  3589  4559 I ActivityManager: Killing 25127:ng.gosquare.dispatch/u0a252 (adj 900): remove task
04-02 21:47:37.957  3589  3771 W InputDispatcher: channel 'd049f4a ng.gosquare.dispatch/ng.gosquare.dispatch.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
04-02 21:47:37.957  3589  3771 E InputDispatcher: channel 'd049f4a ng.gosquare.dispatch/ng.gosquare.dispatch.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
04-02 21:47:37.960  3589  9440 I WindowManager: WIN DEATH: Window{d049f4a u0 ng.gosquare.dispatch/ng.gosquare.dispatch.MainActivity}
04-02 21:47:37.961  3589  9440 W InputDispatcher: Attempted to unregister already unregistered input channel 'd049f4a ng.gosquare.dispatch/ng.gosquare.dispatch.MainActivity (server)'
04-02 21:47:40.030  3589  3619 I ActivityManager: Start proc 25395:ng.gosquare.dispatch/u0a252 for broadcast ng.gosquare.dispatch/com.google.firebase.iid.FirebaseInstanceIdReceiver
04-02 21:47:40.176 25395 25418 I FA      :   adb shell setprop debug.firebase.analytics.app ng.gosquare.dispatch
04-02 21:47:40.314 25395 25395 D SoLoader: adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/lib/arm64 flags = 0]
04-02 21:47:40.314 25395 25395 D SoLoader: adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/ng.gosquare.dispatch/lib-main flags = 1]
04-02 21:47:40.315 25395 25395 D SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/lib/arm64 flags = 0]
04-02 21:47:40.315 25395 25395 D SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/ng.gosquare.dispatch/lib-main flags = 1]
04-02 21:47:40.316 25395 25395 V fb-UnpackingSoSource: locked dso store /data/user/0/ng.gosquare.dispatch/lib-main
04-02 21:47:40.318 25395 25395 I fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/ng.gosquare.dispatch/lib-main
04-02 21:47:40.318 25395 25395 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/ng.gosquare.dispatch/lib-main
04-02 21:47:40.381 25395 25395 D SoLoader: libreactnativejni.so not found on /data/data/ng.gosquare.dispatch/lib-main
04-02 21:47:40.381 25395 25395 D SoLoader: libreactnativejni.so found on /data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/lib/arm64
04-02 21:47:40.410 25395 25395 D SoLoader: libfb.so not found on /data/data/ng.gosquare.dispatch/lib-main
04-02 21:47:40.410 25395 25395 D SoLoader: libfb.so found on /data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/lib/arm64
04-02 21:47:40.413 25395 25395 D SoLoader: libfb.so not found on /data/data/ng.gosquare.dispatch/lib-main
04-02 21:47:40.413 25395 25395 D SoLoader: libfb.so found on /data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/lib/arm64
04-02 21:47:40.413 25395 25395 I zygote64: Thread[1,tid=25395,Native,Thread*=0x70edcc2a00,peer=0x73dc9630,"main"] recursive attempt to load library "/data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/lib/arm64/libfb.so"
04-02 21:47:40.508 25395 25441 D SoLoader: libjscexecutor.so not found on /data/data/ng.gosquare.dispatch/lib-main
04-02 21:47:40.509 25395 25441 D SoLoader: libjscexecutor.so found on /data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/lib/arm64
04-02 21:47:45.825 25395 25453 E unknown:ReactNative:   at ng.gosquare.dispatch.Ring.showNewDeliveryRequestDialogue(Ring.java:40)
04-02 21:47:53.349  3589  4556 I ActivityManager: START u0 {flg=0x20000000 cmp=ng.gosquare.dispatch/.MainActivity (has extras)} from uid 10252
04-02 21:47:53.350  3589  4556 W ActivityManager: startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { flg=0x20000000 cmp=ng.gosquare.dispatch/.MainActivity (has extras) }
04-02 21:47:53.399 25395 25395 W Bundle  :      at ng.gosquare.dispatch.MainActivity$ActivityDelegate.onCreate(MainActivity.java:37)
04-02 21:47:53.407 25395 25395 D SoLoader: libyoga.so not found on /data/data/ng.gosquare.dispatch/lib-main
04-02 21:47:53.408 25395 25395 D SoLoader: libyoga.so found on /data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/lib/arm64
04-02 21:47:53.412 25395 25395 W MessageQueue:  at ng.gosquare.dispatch.MainActivity$ActivityDelegate.onCreate(MainActivity.java:39)
04-02 21:47:53.444 25395 25395 I zygote64: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/base.apk"],nativeLibraryDirectories=[/data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/lib/arm64, /data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
04-02 21:47:53.444 25395 25395 I zygote64: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/base.apk"],nativeLibraryDirectories=[/data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/lib/arm64, /data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
04-02 21:47:53.445 25395 25395 I zygote64: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/base.apk"],nativeLibraryDirectories=[/data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/lib/arm64, /data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
04-02 21:47:53.562  3589  3631 I ActivityManager: Displayed ng.gosquare.dispatch/.MainActivity: +200ms
04-02 21:48:01.819  3589 17217 I ActivityManager: Killing 25395:ng.gosquare.dispatch/u0a252 (adj 900): remove task
04-02 21:48:01.893  3589  3771 W InputDispatcher: channel 'b73da55 ng.gosquare.dispatch/ng.gosquare.dispatch.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
04-02 21:48:01.893  3589  3771 E InputDispatcher: channel 'b73da55 ng.gosquare.dispatch/ng.gosquare.dispatch.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
04-02 21:48:01.904  3589  3943 I WindowManager: WIN DEATH: Window{b73da55 u0 ng.gosquare.dispatch/ng.gosquare.dispatch.MainActivity}
04-02 21:48:01.904  3589  3943 W InputDispatcher: Attempted to unregister already unregistered input channel 'b73da55 ng.gosquare.dispatch/ng.gosquare.dispatch.MainActivity (server)'
04-02 21:48:11.118  3589  3589 I ActivityManager: Start proc 25544:ng.gosquare.dispatch/u0a252 for service ng.gosquare.dispatch/com.transistorsoft.locationmanager.scheduler.ScheduleJobService
04-02 21:48:11.290 25544 25567 I FA      :   adb shell setprop debug.firebase.analytics.app ng.gosquare.dispatch
04-02 21:48:11.437 25544 25544 D SoLoader: adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/lib/arm64 flags = 0]
04-02 21:48:11.438 25544 25544 D SoLoader: adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/ng.gosquare.dispatch/lib-main flags = 1]
04-02 21:48:11.439 25544 25544 D SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/lib/arm64 flags = 0]
04-02 21:48:11.439 25544 25544 D SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/ng.gosquare.dispatch/lib-main flags = 1]
04-02 21:48:11.440 25544 25544 V fb-UnpackingSoSource: locked dso store /data/user/0/ng.gosquare.dispatch/lib-main
04-02 21:48:11.443 25544 25544 I fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/ng.gosquare.dispatch/lib-main
04-02 21:48:11.443 25544 25544 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/ng.gosquare.dispatch/lib-main
04-02 21:48:12.117 25544 25544 D SoLoader: libreactnativejni.so not found on /data/data/ng.gosquare.dispatch/lib-main
04-02 21:48:12.117 25544 25544 D SoLoader: libreactnativejni.so found on /data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/lib/arm64
04-02 21:48:12.139 25544 25544 D SoLoader: libfb.so not found on /data/data/ng.gosquare.dispatch/lib-main
04-02 21:48:12.139 25544 25544 D SoLoader: libfb.so found on /data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/lib/arm64
04-02 21:48:12.141 25544 25544 D SoLoader: libfb.so not found on /data/data/ng.gosquare.dispatch/lib-main
04-02 21:48:12.141 25544 25544 D SoLoader: libfb.so found on /data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/lib/arm64
04-02 21:48:12.141 25544 25544 I zygote64: Thread[1,tid=25544,Native,Thread*=0x70edcc2a00,peer=0x73dc9630,"main"] recursive attempt to load library "/data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/lib/arm64/libfb.so"
04-02 21:48:12.205 25544 25591 D SoLoader: libjscexecutor.so not found on /data/data/ng.gosquare.dispatch/lib-main
04-02 21:48:12.205 25544 25591 D SoLoader: libjscexecutor.so found on /data/app/ng.gosquare.dispatch-AP6NoSk1Ycc0MMOWBEH3qg==/lib/arm64
```

**Comment by ripern** [comment]
When I was getting those problems, this solved it: https://stackoverflow.com/questions/56038027/react-native-make-sure-your-bundle-is-packaged-correctly-or-youre-running-a-p
