### ISSUE TITLE
App crashes while building 

### ISSUE THREAD

**Issue by ShridharCodewave** [facebook/react-native#24369]
Hey,
Iam working on an app which was working fine and suddenly the app is getting crashed with following log. There were couple of updates when I ran react-native run-android . And the react native version is "react-native": "~0.55.2",

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/appevents/InternalAppEventsLogger;
at com.facebook.marketing.internal.MarketingLogger.<init>(MarketingLogger.java:47)
at com.facebook.marketing.internal.MarketingInitProvider.setupCodeless(MarketingInitProvider.java:68)
at com.facebook.marketing.internal.MarketingInitProvider.onCreate(MarketingInitProvider.java:49)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1761)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1736)
at android.app.ActivityThread.installProvider(ActivityThread.java:6093)
at android.app.ActivityThread.installContentProviders(ActivityThread.java:5572)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5511)
at android.app.ActivityThread.-wrap2(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1611)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:165)
at android.app.ActivityThread.main(ActivityThread.java:6375)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.appevents.InternalAppEventsLogger" on path: DexPathList[[zip file "/data/app/com.scoutnex-1/base.apk"],nativeLibraryDirectories=[/data/app/com.scoutnex-1/lib/arm, /data/app/com.scoutnex-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:74)
at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 16 more`

**Comment by ronastlelobo** [comment]
Even I am facing the same issue. The same bug some up. App doesn't load.

**Comment by mfentross** [comment]
@ShridharCodewave @ronastlelobo Did you guys find a solution? We are having the same problem.

**Comment by ShridharCodewave** [comment]
@mfentross I found that we were getting the error due to react-native-fbsdk library. After updating the react-native-fbsdk library to its latest version the app started working.
