### ISSUE TITLE
[Android] react-native bundle crashes on loading with com.facebook.infer.annotation.Assertions.assertNotNull

### ISSUE THREAD

**Issue by tretyakdnua** [facebook/react-native#24371]
## 🐛 Bug Report

When android app tries to load react-native bundle -> app crashes with:
Caused by java.lang.AssertionError
at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:28)
at com.facebook.react.devsupport.DevSupportManagerImpl.handleReloadJS(DevSupportManagerImpl.java:782)
at com.facebook.react.devsupport.RedBoxDialog$3.onClick(RedBoxDialog.java:282)
at android.view.View.performClick(View.java:6605)
at android.view.View.performClickInternal(View.java:6582)
at android.view.View.access$3100(View.java:778)
at android.view.View$PerformClick.run(View.java:25897)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6762)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

## To Reproduce

1) Open android app
2) Try to load react-native .js bundle

## Expected Behavior

.js bundle must be loaded

**Comment by kelset** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗
