### ISSUE TITLE
unable to resolve path outside root directory

### ISSUE THREAD

**Issue by abanik0831** [facebook/react-native#24416]
## 🐛 Bug Report
 
our project has shared logic for Web and Native where the business logic is outside native's root dir. JS files inside native directory is able to resolve path inside the root dir (within native), however when we try to access any file outside the native folder we see an error. 

## To Reproduce

create a react native project (all folders inside native directory). Create a new `src` directory sibling to `native`. Create any JS file within the `src` folder` 

Now, inside `App.js` file inside your native folder try accessing the JS file from `src` dir --

```
import file from '../src/file.js'
```

error seen:

```
error: bundling failed: Error: Unable to resolve module `../src/help/me` from `/Users/abanik/project/react-native-starter/native/App.js`: The module `../src/help/me` could not be found from `/Users/abanik/project/react-native-starter/native/App.js`. Indeed, none of these files exist:
  * `/Users/abanik/project/react-native-starter/src/help/me(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `/Users/abanik/project/react-native-starter/src/help/me/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/Users/abanik/project/react-native-starter/native/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/abanik/project/react-native-starter/native/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/abanik/project/react-native-starter/native/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at Object.resolve (/Users/abanik/project/react-native-starter/native/node_modules/metro/src/lib/transformHelpers.js:261:42)
    at dependencies.map.result (/Users/abanik/project/react-native-starter/native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/abanik/project/react-native-starter/native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
    at /Users/abanik/project/react-native-starter/native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/abanik/project/react-native-starter/native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)

```

## Expected Behavior

able to resolve path

## Code Example

  ```
import React from 'react';
import { View, StyleSheet, Text } from 'react-native';
import me from '../src/help/me'

export default function App() {
  return (
    <View>
      <Text>
        hello world
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
});

```

## Environment
```
 React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 64.96 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.4 => 0.59.4
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by Salakar** [comment]
Hey @abanik0831 thanks for filing this issue.

This is the correct default behaviour for metro. You can, however, update your `metro.config.js` to support multiple roots using the [`watchFolders`](https://facebook.github.io/metro/docs/en/configuration.html#watchfolders) configuration property. Here's an example:

```js
const { resolve } = require('path');

const config = {
  // ... other config items
  watchFolders: [
    resolve(__dirname, '.'),        // your 'native' directory
    resolve(__dirname, '../src'),   // your '../src' directory
  ],
};

module.exports = config;
```

Hope this helps. Thanks.

**Comment by yang200258** [comment]
hi friends,i have same issue,how to fix this?

**Comment by yeegr** [comment]
RN 0.61.2, tried

```
module.exports = {
  resolver: {
    sourceExts: ['ts', 'tsx', 'js', 'jsx']
  },
  projectRoot: path.resolve(__dirname),
  watchFolders: [
    path.resolve(__dirname, '../common')
  ],
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
}
```

does **not** work, need a fix ASAP.
