### ISSUE TITLE
java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found 

### ISSUE THREAD

**Issue by MrDatastorage** [facebook/react-native#24427]
## Information
Hi,

After searching google, Github issue etc..., I didn't find the answer to resolve this issue.
It is bug in react native 59.4

## My React 59.4 setup
React Native: 59.4
buildToolsVersion: 28.03
minSdkVersion: 16
compileSdkVersion: 28
targetSdkVersion: 28
Gradle: 3.3.1

- This error comes wit ADB install signed apk package on a REAL device.
- Debugging and release run in react native works without problem.

## Expected Behavior
That the signed packages, work fine.

## To Reproduce
I don't know to explain. Is a big app.

## Bug Error:
```04-09 16:53:02.841 22070 22093 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
04-09 16:53:02.841 22070 22093 E AndroidRuntime: Process: com.app_app, PID: 22070
04-09 16:53:02.841 22070 22093 E AndroidRuntime: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
04-09 16:53:02.841 22070 22093 E AndroidRuntime: 	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1333)
04-09 16:53:02.841 22070 22093 E AndroidRuntime: 	at okhttp3.HttpUrl.get(HttpUrl.java:916)
04-09 16:53:02.841 22070 22093 E AndroidRuntime: 	at okhttp3.Request$Builder.url(Request.java:165)
04-09 16:53:02.841 22070 22093 E AndroidRuntime: 	at com.facebook.react.modules.websocket.WebSocketModule.connect(WebSocketModule.java:93)
04-09 16:53:02.841 22070 22093 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-09 16:53:02.841 22070 22093 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
04-09 16:53:02.841 22070 22093 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
04-09 16:53:02.841 22070 22093 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
04-09 16:53:02.841 22070 22093 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
04-09 16:53:02.841 22070 22093 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
04-09 16:53:02.841 22070 22093 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
04-09 16:53:02.841 22070 22093 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
04-09 16:53:02.841 22070 22093 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
04-09 16:53:02.841 22070 22093 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
04-09 16:53:02.856 22070 22075 I zygote64: Do partial code cache collection, code=236KB, data=142KB
04-09 16:53:02.857 17048 25342 W ActivityManager:   Force finishing activity com.app_app/.MainActivity
04-09 16:53:02.857 22070 22075 I zygote64: After code cache collection, code=231KB, data=140KB
04-09 16:53:02.857 22070 22075 I zygote64: Increasing code cache capacity to 1024KB
04-09 16:53:02.863 17048 17163 I ActivityManager: Showing crash dialog for package com.app_app u0

Environment:

React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 163.18 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.11.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 26.0.2, 27.0.2, 27.0.3, 28.0.2, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.4 => 16.8.4 
      react-native: 0.59.1 => 0.59.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-debugger: 1.1.0```

**Comment by MrDatastorage** [comment]
> Thanks for submitting your issue. Can you take another look at your description and make sure the issue template has been filled in its entirety?
> 
> 👉 [Click here if you want to take another look at the Bug Report issue template.](https://github.com/facebook/react-native/issues/new?template=bug_report.md)

Updated

**Comment by dulmandakh** [comment]
I looks like you have an issue in your code, please look into your code and search for network requests, make sure URLs are valid.
