### ISSUE TITLE
Error in Android while display alert

### ISSUE THREAD

**Issue by sarikabhimre18** [facebook/react-native#24646]
## 🐛 Bug Report
E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.openmed, PID: 20378
                                                             java.lang.NoSuchMethodError: No virtual method isStateSaved()Z in class Landroid/support/v4/app/FragmentManager; or its super classes (declaration of 'android.support.v4.app.FragmentManager' appears in /data/app/com.openmed-S74HYt-_hZFzp7xAPpmo3A==/base.apk)
                                                                 at com.facebook.react.modules.dialog.DialogModule$FragmentManagerHelper.showNewAlert(DialogModule.java:132)
                                                                 at com.facebook.react.modules.dialog.DialogModule$1.run(DialogModule.java:258)
                                                                 at android.os.Handler.handleCallback(Handler.java:789)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                 at android.os.Looper.loop(Looper.java:164)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

## Environment
"react": "16.8.3",
 "react-native": "0.59.4",

ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 26
        supportLibVersion = "28.0.0"
}

React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-3475S CPU @ 2.90GHz
      Memory: 85.87 MB / 12.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.4.1 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.4 => 0.59.4 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-sms: 1.8.0

**Comment by sarikabhimre18** [comment]
@react-native-bot I am getting this error after upgrade react-native version 0.53.3 to 0.59.4 or 0.59.5

**Comment by JKCooper2** [comment]
Have you followed the upgrade process? Just jumping up that many versions can't be done directly. See https://github.com/react-native-community/rn-diff-purge for how to upgrade
