### ISSUE TITLE
react-native-git-upgrade illegal operation on a directory, read

### ISSUE THREAD

**Issue by AJamesPhillips** [facebook/react-native#24694]
I am trying to upgrade react-native by running `react-native-git-upgrade` but it errors with `illegal operation on a directory, read`

```
$ npm install -g react-native-git-upgrade 
+ react-native-git-upgrade@0.2.7

$ react-native-git-upgrade
git-upgrade info Check for updates 
git-upgrade info Using yarn 1.10.1 
git-upgrade info Read package.json files 
git-upgrade info Check declared version 
git-upgrade info Check matching versions 
git-upgrade info Check React peer dependency 
git-upgrade info Check that Git is installed 
git-upgrade info Get information from NPM registry 
git-upgrade info Upgrading to React Native 0.59.5, React 16.8.3 
git-upgrade info Setup temporary working directory 
git-upgrade info Configure Git environment 
git-upgrade info Init Git repository 
git-upgrade info Add all files to commit 
git-upgrade info Commit current project sources 
git-upgrade info Create a tag before updating sources 
git-upgrade info Generate old version template 
git-upgrade ERR! An error occurred during upgrade: 
git-upgrade ERR! Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:491:3)
    at tryReadSync (fs.js:330:20)
    at Object.readFileSync (fs.js:367:19)
    at ConfigChainBuilder.addConfig (/Users/user1/.nvm/versions/node/v10.14.1/lib/node_modules/react-native-git-upgrade/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
    at ConfigChainBuilder.findConfigs (/Users/user1/.nvm/versions/node/v10.14.1/lib/node_modules/react-native-git-upgrade/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:102:30)
    at buildConfigChain (/Users/user1/.nvm/versions/node/v10.14.1/lib/node_modules/react-native-git-upgrade/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
    at OptionManager.init (/Users/user1/.nvm/versions/node/v10.14.1/lib/node_modules/react-native-git-upgrade/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
    at compile (/Users/user1/.nvm/versions/node/v10.14.1/lib/node_modules/react-native-git-upgrade/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/user1/.nvm/versions/node/v10.14.1/lib/node_modules/react-native-git-upgrade/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/user1/.nvm/versions/node/v10.14.1/lib/node_modules/react-native-git-upgrade/node_modules/babel-register/lib/node.js:154:7) 
git-upgrade ERR! Restore initial sources 
Note: checking out 'project-snapshot'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at b2eda88... Project snapshot

```

## To Reproduce
See above

## Expected Behavior
Expected it to work

## Environment

```
$ react-native info

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
      Memory: 305.69 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 2.3 AI-162.3871768
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.7.0 => 16.7.0 
      react-native: 0.57.0 => 0.57.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

```

**Comment by AJamesPhillips** [comment]
I am going to ignore that message for obvious reasons.

**Comment by matt-oakes** [comment]
👋 @AJamesPhillips. Thanks for reporting this.

`react-native-git-upgrade` has actually been deprecated and replaced with `react-native upgrade` from 0.59 onwards. To upgrade to that version, I recommend you take a look at the diffs in the [`rn-diff-purge` repository](https://github.com/pvinis/rn-diff-purge). The one you need is here:

https://github.com/react-native-community/rn-diff-purge/compare/release/0.57.0..release/0.59.8

If you follow the diff and make the changes manually this time, you will be able to use the new upgrade command from 0.59 onwards.

More details about the upgrade process can be found here:

https://facebook.github.io/react-native/docs/upgrading

---

@kelset Should we keep this open to look into the issue with `react-native-git-upgrade` or close it?

**Comment by kelset** [comment]
No, let's close it. `react-native-git-upgrade` has been "dead" for some time now (we have been saying it both in issues and in the blogposts), so there is nothing actionable.

@AJamesPhillips I'm sorry you have been experiencing pain in upgrading, and I can tell you that we know this has been a [long lasting pain for the community](https://github.com/react-native-community/discussions-and-proposals/issues/68) so starting v0.59 we have introduced a new flow via the [new CLI](https://facebook.github.io/react-native/blog/#cli-improvements). So hopefully following @matt-oakes's approach (which is the one I do every time) you'll be able to overcome your issues 🤗
