### ISSUE TITLE
react-native/android: ReactNativeRenderer-prod: getting undefined is not an object (evaluating 't.validAttributes')

### ISSUE THREAD

**Issue by mgenov** [facebook/react-native#24801]
React Native version:
```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
      Memory: 20.75 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.npm-packages/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6
      react-native: 0.59.5 => 0.59.5
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native: 0.55.4
```

## Steps To Reproduce
This error happens rarely and in most cases when some amount of traffic is sent through the bridge from the react-native-firebase library. 

The code of the application

## Crash Error

```
Fatal Exception: com.facebook.react.common.JavascriptException TypeError: undefined is not an object (evaluating 't.validAttributes'), stack:
  at validAttributes (./s/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:1648:22)
  at instance (./s/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:5516:12)
  at nextEffect (./s/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:5725:19)
  at commitAllHostEffects (./s/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:5956:6)
  at root (./s/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:6942:17)
  at b (./s/scheduler/cjs/scheduler.production.min.js:18:162)
  at scheduler (./s/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:6940:4)
  at root (./s/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:6918:25)
  at nextFlushedRoot (./s/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:6855:24)
  at ./s/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:7082:18
  at fn (./s/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:1025:31)
  at ./s/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:1045:17
  at rootNodeID (./s/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:1079:28)
  at moduleMethods (./s/react-native/Libraries/BatchedBridge/MessageQueue.js:366:47)
  at module (./s/react-native/Libraries/BatchedBridge/MessageQueue.js:106:26)
  at fn (./s/react-native/Libraries/BatchedBridge/MessageQueue.js:314:8)
  at ./s/react-native/Libraries/BatchedBridge/MessageQueue.js:105:17

```

**Comment by kelset** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗
