### ISSUE TITLE
error: bundling failed: Error: ENOENT: no such file or directory, scandir '/Users/myuser/MyProject/mycomponents/node_modules/private-dependency/images'

### ISSUE THREAD

**Issue by remigarcia** [facebook/react-native#25005]
Hello,

I'm facing this error when trying to build for iOS :
```
error: bundling failed: Error: ENOENT: no such file or directory, scandir '/Users/remigarcia/Projets/MobileApp/component/navigation/node_modules/private-dependency/images'
    at Object.readdirSync (fs.js:779:3)
    at Object.getDirFiles (/Users/remigarcia/Projets/MobileApp/node_modules/metro/src/node-haste/DependencyGraph.js:103:34)
    at Map._factory (/Users/remigarcia/Projets/MobileApp/node_modules/metro/src/node-haste/AssetResolutionCache.js:41:36)
    at Map.get (/Users/remigarcia/Projets/MobileApp/node_modules/metro/src/node-haste/lib/MapWithDefaults.js:23:24)
    at AssetResolutionCache.resolve (/Users/remigarcia/Projets/MobileApp/node_modules/metro/src/node-haste/AssetResolutionCache.js:91:43)
    at resolveAsset (/Users/remigarcia/Projets/MobileApp/node_modules/metro/src/node-haste/DependencyGraph.js:229:36)
    at resolveAssetFiles (/Users/remigarcia/Projets/MobileApp/node_modules/metro-resolver/src/resolve.js:463:22)
    at resolveFile (/Users/remigarcia/Projets/MobileApp/node_modules/metro-resolver/src/resolve.js:349:20)
    at resolveFileOrDir (/Users/remigarcia/Projets/MobileApp/node_modules/metro-resolver/src/resolve.js:262:22)
    at Object.resolve (/Users/remigarcia/Projets/MobileApp/node_modules/metro-resolver/src/resolve.js:155:20)
```

So, I have a private dependency "private-dependency" with an `images` folder in it.
In a component located in `/Users/remigarcia/Projets/MobileApp/component/navigation/` i'm trying to import one of this images :
`import logo from 'private-dependency/images/logo.png'`
The bundler seems to look for the image in the folder of the component (see the error) : `/Users/remigarcia/Projets/MobileApp/component/navigation/node_modules/private-dependency/images` and not in the module folder.

Do I imported badly the image ?

React Native version: 0.59.8
```
info 
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
      Memory: 367.96 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.3.1 - /usr/local/Cellar/node/12.3.1/bin/node
      Yarn: 1.16.0 - /usr/local/Cellar/node/12.3.1/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by guhungry** [comment]
Err, you need import logo from `./private-dependency/images/logo.png`.

**Comment by remigarcia** [comment]
@guhungry by doing this I explicitly tell to look in the path of the current component, the error is the same

**Comment by guhungry** [comment]
@remigarcia Always use relative path to files unless import library.

**Comment by remigarcia** [comment]
@guhungry yeah, the only working method seems to be : 
```
<Image source={require('../../node_modules/private-dependency/images/image.png')} />
```

Closing this, thanks.

**Comment by artalat** [comment]
Facing the same issue, after upgrading from 0.57.8. Pretty sure this is a bug

**Comment by ShamshadSani** [comment]
ENOENT: no such file or directory, scandir 'D:\React Js\camera\screens\assets' 
 anyone please help me...i dont know why is this happening

**Comment by Mnabawy** [comment]
alweys use  ../../whatever/private-dependency/images/image.png to import and asset
[../../] => that what i mean start your path with it
