### ISSUE TITLE
react-native link error "Failed to get dependency config" (RN 0.59.8)

### ISSUE THREAD

**Issue by goneale** [facebook/react-native#25149]
React Native version:
```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
      Memory: 9.86 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25
        Build Tools: 25.0.1, 25.0.2
        System Images: a...pis | Google APIs ARM EABI v7a Syste..., a...google_apis | Google APIs Intel x86 Atom Sys...
    IDEs:
      Android Studio: 2.3 AI-162.3764568
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.2.2
```

## Steps To Reproduce
Pretty sure this is an issue with react-native link, as I have tried a few different packages, still resulting in the same error.

npm install @aws-amplify/pushnotification --save
then
react-native link @aws-amplify/pushnotification
results in error:
```
debug Available platforms: iOS, Android
debug Targeted platforms: iOS, Android
debug Getting project config for iOS...
debug Getting project config for Android...
debug Package to link: @aws-amplify/pushnotificaton
error Failed to get dependency config
debug Error: Failed to get dependency config
    at getDependencyConfig (/Users/goneale/Projects/rag-apps/WowApps/WowManager/node_modules/@react-native-community/cli/build/commands/link/getDependencyConfig.js:49:11)
    at Object.link [as func] (/Users/goneale/Projects/rag-apps/WowApps/WowManager/node_modules/@react-native-community/cli/build/commands/link/link.js:97:61)
```
Can't get any linking to function.

**Comment by goneale** [comment]
Closing issue. Spelling mistake while running command!

**Comment by manpreetsingh3215** [comment]
I run this command:
`react-native link realm --verbose`

and get this issue:
```
error Failed to get dependency config
debug Error: Failed to get dependency config
    at getDependencyConfig (/Users/ankushrishi/Documents/echoheart-mobile/node_modules/@react-native-community/cli/build/commands/link/getDependencyConfig.js:49:11)
    at Object.link [as func] (/Users/ankushrishi/Documents/echoheart-mobile/node_modules/@react-native-community/cli/build/commands/link/link.js:97:61)
    at /Users/ankushrishi/Documents/echoheart-mobile/node_modules/@react-native-community/cli/build/cliEntry.js:152:22
```
