### ISSUE TITLE
Building React Native from source failed

### ISSUE THREAD

**Issue by holmeshe** [facebook/react-native#25173]
1) The following error is found in gradle sync phase:
```
ERROR: Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-117 to override.
```

It could be fixed by adding the following two lines,
```
android.useAndroidX=true
android.enableJetifier=true
```
to `gradle.properties` of the app project

2) Then comes to the second error,
```
06-06 17:59:17.698 26292-26336/com.fromsource E/dalvikvm: dlopen("/data/app-lib/com.fromsource-1/libjscexecutor.so") failed: dlopen failed: 
06-06 17:59:17.698 26292-26336/com.fromsource E/SoLoader: couldn't find DSO to load: libjscexecutor.so caused by: dlopen failed: 
06-06 17:59:17.698 26292-26336/com.fromsource W/dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/facebook/react/jscexecutor/JSCExecutor;
06-06 17:59:17.698 26292-26336/com.fromsource W/dalvikvm: threadid=18: thread exiting with uncaught exception (group=0x418ccc68)
06-06 17:59:17.708 26292-26336/com.fromsource E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.fromsource, PID: 26292
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so caused by: dlopen failed: 
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.react.jscexecutor.JSCExecutor.<clinit>(JSCExecutor.java:19)
        at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:29)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:956)
        at java.lang.Thread.run(Thread.java:841)
06-06 17:59:17.768 26292-26292/com.fromsource W/linker: library "libmaliinstr.so" not found
```

Which can be fixed by removing the following line (271)
```
task packageReactNdkLibs(dependsOn: buildReactNdkLib, type: Copy) {
    from("$buildDir/react-ndk/all")
    into("$buildDir/react-ndk/exported")
    exclude("**/libjsc.so")  <-----------------------remove this line
}
```

in `build.gradle` of `ReactAndroid` project

React Native version: master
react-native-cli version: 2.0.1

## Steps To Reproduce

1. Create a React Native app using `react-native-cli` (version as indicated above)
2. Follow the instructions from https://github.com/facebook/react-native/wiki/Building-from-source

Describe what you expected to happen (next):
1. Add **AndroidX** related instructions to the https://github.com/facebook/react-native/wiki/Building-from-source
2. Not sure why `exclude("**/libjsc.so")` is there. If it is not intentional (for another deployment path), then it is required to be removed.

**Comment by nhunzaker** [comment]
I hit this as well and was able to resolve the issue by following the instructions above.

Thanks @holmeshe! You saved me a lot of time!

**Comment by felansu** [comment]
I get a

```
> Task :lottie-react-native:compileDebugJavaWithJavac FAILED
/Users/ferrangonzalezalonso/cloq/orion/node_modules/lottie-react-native/src/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewManager.java:8: error: package android.support.v4.view does not exist
import android.support.v4.view.ViewCompat;
                              ^

```

For resolve that [see that](https://github.com/react-native-community/lottie-react-native/issues/443#issuecomment-461663224)

Next!

```
> Task :react-native-camera:compileGeneralDebugJavaWithJavac FAILED
/Users/ferrangonzalezalonso/cloq/orion/node_modules/react-native-camera/android/src/main/java/org/reactnative/camera/RNCameraView.java:10: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;

```


Resolving...

**Comment by nguyenhose** [comment]
@felansu lol I got that `react-native-camera` too. wonder if upgrade to androidx is correct path or not

**Comment by kelset** [comment]
cc @hramos

**Comment by felansu** [comment]
@nguyenhose this night i test and comment the result :P thanks

**Comment by songoten28** [comment]
@felansu 
upgrade your dependence to
 "react-native-camera": "^1.13.1"

**Comment by paruckerr** [comment]
@felansu you renamed all this packages?

```
import android.support.v4.content.ContextCompat;
import android.support.annotation.IntDef;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.v4.os.ParcelableCompat;
import android.support.v4.os.ParcelableCompatCreatorCallbacks;
import android.support.v4.util.SparseArrayCompat;
import android.support.media.ExifInterface;
import android.support.v4.util.Pools;
import android.support.v4.util.ArrayMap;
```
I face the same issue, but where did you change?

android/app/build.gradle? MainApplication.java?

**Comment by felansu** [comment]
@paruckerr you need change all that packages in node_modules.
I replace manually with intellij idea, but can test [that lib](https://www.npmjs.com/package/ns-androidx-migrate) (i don't test yet)

**Comment by paruckerr** [comment]
@felansu so, I change all packages...

But now when App is build, this crash happen..

**adb logcat**

```
AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/my-app-2/base.apk"],nativeLibraryDirectories=[/data/app/my-app-2/lib/arm, /data/app/my-app-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
```

This was generated after BUILD SUCCESSFUL

I remove all those files...
![image](http://bit.ly/2ISUJGT)

But after run-android this was regenerate...

Any ideas?

**Comment by paruckerr** [comment]
I found the problem...

react-native-image-crop-picker > manifests > AndroidManifest.xml

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.reactnative.ivpusic.imagepicker">

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    <application>

        <provider
            android:name="androidx.core.content.FileProvider" //Change here
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
        </provider>

        <activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar" />
    </application>

</manifest>
```

**Comment by felansu** [comment]
>  "react-native-camera": "^1.13.1"

I have  "react-native-camera": "^2.9.0"

**Comment by songoten28** [comment]
@felansu You can find solution here
https://github.com/facebook/react-native/issues/25307#issuecomment-503516458
