### ISSUE TITLE
Question: Can't run after updating to 0.59

### ISSUE THREAD

**Issue by Alireza-Ta** [facebook/react-native#25311]
React Native version: 0.59.9

## Steps To Reproduce
I've updated my app to the latest version and now it does not work and give me following error after hitting ```react-native run-android``` command :

```The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
{"originModulePath":"/Users/admin/Desktop/rn59/node_modules/istanbul-reports/index.js","targetModuleName":"path","message":"Unable to resolve module `path` from `/Users/admin/Desktop/rn59/node_modules/istanbul-reports/index.js`: Module `path` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.\n  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.","errors":[{"description":"Unable to resolve module `path` from `/Users/admin/Desktop/rn59/node_modules/istanbul-reports/index.js`: Module `path` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.\n  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`."}],"name":"Error","stack":"Error: Unable to resolve module `path` from `/Users/admin/Desktop/rn59/node_modules/istanbul-reports/index.js`: Module `path` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.\n  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.\n    at ModuleResolver.resolveDependency (/Users/admin/Desktop/rn59/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:183:15)\n    at ResolutionRequest.resolveDependency (/Users/admin/Desktop/rn59/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)\n    at DependencyGraph.resolveDependency (/Users/admin/Desktop/rn59/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)\n    at Object.resolve (/Users/admin/Desktop/rn59/node_modules/metro/src/lib/transformHelpers.js:261:42)\n    at dependencies.map.result (/Users/admin/Desktop/rn59/node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31)\n    at Array.map (<anonymous>)\n    at resolveDependencies (/Users/admin/Desktop/rn59/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)\n    at /Users/admin/Desktop/rn59/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (/Users/admin/Desktop/rn59/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)"}
processBundleResult
    BundleDownloader.java:296
access$200
    BundleDownloader.java:37
onResponse
    BundleDownloader.java:174
execute
    RealCall.java:206
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1167
run
    ThreadPoolExecutor.java:641
run
    Thread.java:764

```

Describe what you expected to happen:
to see it's working properly!

Snack, code example, or link to a repository:

package.json

```
{
  "name": "rn59",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-elements": "^1.1.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-vector-icons": "^6.5.0",
    "react-navigation": "^3.11.0"
  },
  "devDependencies": {
    "@babel/core": "7.4.5",
    "@babel/runtime": "7.4.5",
    "babel-jest": "24.8.0",
    "jest": "24.8.0",
    "metro-react-native-babel-preset": "0.54.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

info

```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
      Memory: 5.30 GB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 23, 24, 25, 26, 28
        Build Tools: 23.0.1, 23.0.3, 26.0.3, 28.0.3, 29.0.0
        System Images: android-24 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      create-react-native-app: 0.0.6
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-vector-icons: 3.0.0

```

**Comment by ldco2016** [comment]
@Alireza-Ta , you are not the only one experiencing this issue. I have been trying to resolve this for a week now. My application no longer boots up, it simply crashes after splash screen appears. 

The Metro Bundler gives me no messages, it does absolutely nothing when I click on the app, doesn't tell me why its crashed. On the localhost:8081/debugger-ui all I get is this `WebSocket connection to 'ws://localhost:8081/debugger-proxy?role=debugger&name=Chrome' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`, but that is not very helpful at all since I ensured that 8081 is not already in use.

This is my environment:

```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 35.21 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.1 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.3
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

There is just a lot of noise out there that leads nowhere except going around in circles.

This is my `package.json` file:

```
"scripts": {
    "start": "nps",
    "test": "nps setup && nps test",
    "build": "nps build",
    "prepare": "nps patcher",
    "setup": "nps setup && nps appcenter",
    "react-devtools": "react-devtools"
  },
  "dependencies": {
    "appcenter": "2.0.0",
    "appcenter-analytics": "2.0.0",
    "appcenter-crashes": "2.0.0",
    "axios": "0.16.2",
    "date-fns": "^1.29.0",
    "lodash": "4.17.4",
    "moment": "2.20.1",
    "payment": "2.3.0",
    "prop-types": "15.6.0",
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-autoheight-webview": "0.6.1",
    "react-native-calendar-events": "1.6.1",
    "react-native-device-info": "0.21.5",
    "react-native-exception-handler": "2.8.9",
    "react-native-image-progress": "1.0.1",
    "react-native-immediate-phone-call": "1.0.0",
    "react-native-keyboard-aware-scroll-view": "0.4.4",
    "react-native-keyboard-manager": "4.0.13-12",
    "react-native-material-buttons": "0.5.0",
    "react-native-material-dropdown": "0.5.2",
    "react-native-material-tabs": "3.5.0",
    "react-native-material-textfield": "0.10.0",
    "react-native-onesignal": "3.0.7",
    "react-native-popup-menu": "0.8.3",
    "react-native-sentry": "0.32.0",
    "react-native-size-matters": "0.1.0",
    "react-native-splash-screen": "3.0.6",
    "react-native-svg": "6.3.1",
    "react-native-swipe-view": "https://github.com/jjd314/react-native-swipe-view",
    "react-native-tab-view": "1.3.2",
    "react-native-vector-icons": "6.1.0",
    "react-native-xcode-packager": "0.1.0",
    "react-navigation": "1.5.11",
    "react-redux": "5.0.6",
    "reactotron-react-native": "3.5.0",
    "reactotron-redux": "3.1.0",
    "recompose": "0.26.0",
    "redux": "4.0.1",
    "redux-thunk": "2.2.0",
    "replace-in-file": "3.1.1"
  },
  "devDependencies": {
    "@babel/core": "7.4.5",
    "@babel/plugin-proposal-optional-chaining": "7.2.0",
    "@babel/runtime": "7.4.5",
    "async": "2.6.0",
    "babel-cli": "6.24.1",
    "babel-eslint": "8.0.2",
    "babel-jest": "23.0.0",
    "babel-plugin-module-resolver": "3.0.0",
    "babel-preset-env": "1.4.0",
    "babel-preset-flow": "6.23.0",
    "babel-preset-stage-2": "6.24.1",
    "babel-watch": "2.0.6",
    "chalk": "1.1.3",
    "detox": "8.2.3",
    "eslint": "4.12.0",
    "eslint-import-resolver-babel-module": "4.0.0-beta.3",
    "eslint-plugin-import": "2.8.0",
    "eslint-plugin-prettier": "2.3.1",
    "eslint-plugin-react": "7.5.1",
    "flow-bin": "0.46.0",
    "fs-extra": "5.0.0",
    "jest": "23.0.0",
    "metro-react-native-babel-preset": "0.54.1",
    "nps": "5.7.1",
    "nps-utils": "^1.5.0",
    "patch-package": "5.1.1",
    "postinstall-prepare": "1.0.1",
    "prettier": "1.8.2",
    "prettier-eslint": "8.2.2",
    "react-devtools": "3.6.1",
    "react-test-renderer": "16.2.0",
    "redux-mock-store": "1.3.0",
    "yargs": "8.0.1"
  },
  "jest": {
    "preset": "react-native",
    "setupTestFrameworkScriptFile": "./jest-setup.js",
    "transformIgnorePatterns": [
      "/node_modules/(?!parse)/"
    ],
    "unmockedModulePathPatterns": [
      "react",
      "react-navigation",
      "axios",
      "redux",
      "redux-thunk",
      "lodash",
      "date-fns"
    ],
    "verbose": true
  },
  "detox": {
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/NFIBEngage.app",
        "build": "xcodebuild -workspace ios/NFIBEngage.xcworkspace -configuration Debug -scheme NFIBEngage -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 6"
      }
    },
    "test-runner": "jest"
  }
}

```

So is it an issue with dependencies? What is going on? Last time I heard from anyone here, I was told I needed to upgrade my RN project from 0.53.3 to 0.59.9 and I have done so and I now I get an app that crashes silently. 

`react-native log-ios` does not tell me anything except some message about respawning in 5 seconds. I am at my wits end here. It would be great if I knew why my app was crashing and I attempted to install `bugsnag` only to find it has its own problems so I did not want to continue down that rabbit hole.

Any surefire way of at least knowing why the app crashes upon splash screen without installing yet another package for monitoring?

**Comment by Alireza-Ta** [comment]
I was just working with ```App.js``` file and found there was an import statement like ```import {create} from 'istanbul-reports';```.I've never heard of this library and it was added to my code base unexpectedly but I don't know how!!!
After all removed that line and app works just like before.

**Comment by ldco2016** [comment]
@Alireza-Ta , my case is not even a version upgrade. The problem exists in the old version of 0.53.3, after reviewing my MacOS logs, this is the error I am getting:

`Unhandled JS Exception: Cannot create styled-component for component: [object Object]`

This is how my app is utilizing `styled-components`:

```
Environment:
      OS: macOS High Sierra 10.13.6
      Node: 11.10.1
      Yarn: 1.10.1
      npm: 6.7.0
      Watchman: 4.7.0
      Xcode: Xcode 10.1 Build version 10B61
      Android Studio: 3.4 AI-183.5429.30.34.5452501
    
    Packages: (wanted => installed)
      react: 16.2.0 => 16.2.0
      react-native: 0.53.3 => 0.53.3
```

From the MacOS `console` I was able to obtain this error message:

`Unhandled JS Exception: Cannot create styled-component for component: [object Object]`

The only place in this application where `styled-component` is being utilized is here `package-lock.json`:

   ```
 "styled-components": {
          "version": "2.4.1",
          "resolved": "https://registry.npmjs.org/styled-components/-/styled-components-2.4.1.tgz",
          "integrity": "sha1-ZjvQSF1LarRvlGIQ3APSOY0a3nQ=",
          "requires": {
            "buffer": "^5.0.3",
            "css-to-react-native": "^2.0.3",
            "fbjs": "^0.8.9",
            "hoist-non-react-statics": "^1.2.0",
            "is-plain-object": "^2.0.1",
            "prop-types": "^15.5.4",
            "stylis": "^3.4.0",
            "supports-color": "^3.2.3"
          },

```
and here:

    "react-native-material-tabs": {
          "version": "3.5.0",
          "resolved": "https://registry.npmjs.org/react-native-material-tabs/-/react-native-material-tabs-3.5.0.tgz",
          "integrity": "sha512-OSni2m2rcxiIYd082fjjroRrU8o/8pZlP3Ok/m244Gl9vUmhyj5WVeTgSYODjmHksQ9IIF2/sZurZcy3DawF7A==",
          "requires": {
            "prop-types": "^15.5.10",
            "styled-components": "^2.3.0"
          }
        },

It seems that it could be a dependency of `react-native-material-tabs`? That is the only library that is actually being used, specifically, `MaterialTabs`:

   ` import MaterialTabs from 'react-native-material-tabs';`

And implemented here:

   ```
 render() {
        return (
          <View style={styles.container}>
            {Platform.OS === 'android' && (
              <MaterialTabs
                uppercase={false}
                items={this.props.tabNames}
                selectedIndex={this.state.selectedIndex}
                onChange={this._selectTab}
                barColor={v2Colors.charcoalDark}
                indicatorColor={v2Colors.green}
                activeTextColor={v2Colors.white}
                inactiveTextColor={v2Colors.gray}
                textStyle={{
                  fontSize: moderateScale(14, 0.2),
                  ...v2Fonts.GothamRegular,
                }}
              />
            )}
            {Platform.OS === 'ios' && (
              <View style={styles.iOSTabsWrapper}>
                {this.props.tabNames.map((tabName, index) => {
                  const tabWrapperStyles = [styles.tabWrapper];
                  const tabTextStyles = [styles.tabText];
                  if (index === 0) {
                    tabWrapperStyles.push(styles.tabWrapperFirst);
                  } else if (index === this.props.tabNames.length - 1) {
                    tabWrapperStyles.push(styles.tabWrapperLast);
                  }
```

The app crashes so there is no console logging I can do as far as I know. I am honestly not sure if I am on the right track. Has anyone had this issue before? Or can you suggest a way to debug if the problem is indeed with the props inside of `MaterialTabs` being that I don't have access to console due to the app just crashing natively.

**Comment by aminlatifi** [comment]
I have the same issue. 
It's my `package.json` file:
```
{
  "name": "rncourse",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.0",
    "react-redux": "^6.0.1",
    "redux": "^4.0.1"
  },
  "devDependencies": {
    "@babel/core": "7.5.0",
    "@babel/runtime": "7.5.1",
    "@react-native-community/eslint-config": "0.0.3",
    "babel-jest": "24.8.0",
    "eslint": "6.0.1",
    "jest": "24.8.0",
    "metro-react-native-babel-preset": "0.54.1",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by aminlatifi** [comment]
> I have the same issue.
> It's my `package.json` file:
> 
> ```
> {
>   "name": "rncourse",
>   "version": "0.0.1",
>   "private": true,
>   "scripts": {
>     "start": "react-native start",
>     "test": "jest",
>     "lint": "eslint ."
>   },
>   "dependencies": {
>     "react": "16.8.6",
>     "react-native": "0.60.0",
>     "react-redux": "^6.0.1",
>     "redux": "^4.0.1"
>   },
>   "devDependencies": {
>     "@babel/core": "7.5.0",
>     "@babel/runtime": "7.5.1",
>     "@react-native-community/eslint-config": "0.0.3",
>     "babel-jest": "24.8.0",
>     "eslint": "6.0.1",
>     "jest": "24.8.0",
>     "metro-react-native-babel-preset": "0.54.1",
>     "react-test-renderer": "16.8.6"
>   },
>   "jest": {
>     "preset": "react-native"
>   }
> }
> ```

I solved the issue by just installing `path` module manually. As you know by this command `npm i --save path`

**Comment by prabakarviji** [comment]
Please add `android:usesCleartextTraffic="true"` to your manifest may help this. 

Like below,

```
<application
      android:name=".MainApplication"
      android:usesCleartextTraffic="true"
     .....
```
