### ISSUE TITLE
Exception in thread "main" java.net.SocketException: Unexpected end of file from server

### ISSUE THREAD

**Issue by Gusabary** [facebook/react-native#25453]
I'm newcomer for React Native. I wanted to run a helloworld but encountered following bugs when I run `react-native run-android`:
```
info JS server already running.
info Building and installing the app on the device (cd android && gradlew.bat app:installDebug)...
Downloading https://services.gradle.org/distributions/gradle-5.4.1-all.zip

Exception in thread "main" java.net.SocketException: Unexpected end of file from server
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:862)
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2074)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:67)
        at org.gradle.wrapper.Download.download(Download.java:52)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug. Run CLI with --verbose flag for more details.
```

React Native version:

```
info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
      Memory: 1.30 GB / 7.87 GB
    Binaries:
      Node: 10.15.0 - E:\Node.js\node.EXE
      Yarn: 1.16.0 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - E:\Node.js\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
```

## Steps To Reproduce
It's really just a helloworld
1. react-native init myhellow
2. cd myhello
3. react-native run-android

Describe what you expected to happen:

> I want to see something (like greetings) in my phone connected to computer

**Comment by dulmandakh** [comment]
It seems that your network connection is lost while downloading gradle-5.4.1-all.zip, which is a very large file. Please try again.
