### ISSUE TITLE
ERROR: [Errno 2] No such file or directory: 'add'

### ISSUE THREAD

**Issue by sagarrs** [facebook/react-native#25507]
React Native version:

## Steps To Reproduce

1. react-native init newProj

    unable to create a react-native app using the "react-native init" command i am getting the 
    error as shown below 

    info Setting up new React Native app in /home/sagar/Desktop/rn-prac/newProj
    info Adding required dependencies
    ERROR: [Errno 2] No such file or directory: 'add'
    (node:1961) UnhandledPromiseRejectionWarning: Error: Command failed: yarn add 
    react@16.8.6
    at makeError (/home/sagar/Desktop/rn-prac/newProj/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/home/sagar/Desktop/rn- 
    prac/newProj/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    (node:1961) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error 
    originated either by throwing inside of an async function without a catch block, or by rejecting 
    a promise which was not handled with .catch(). (rejection id: 2)
    (node:1961) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. 
    In the future, promise rejections that are not handled will terminate the Node.js process with a 
    non-zero exit code.

    react-native cli version = 2.0.1,
    node version = 10.16.0,
    npm version = 6.9.0,
    yarn version = 1.3.2

Snack, code example, or link to a repository:
![Screenshot from 2019-07-05 10-36-49](https://user-images.githubusercontent.com/17675875/60699273-c383d200-9f10-11e9-9bff-5b2c548a0c48.png)

**Comment by thymikee** [comment]
Can you update your Yarn version to the latest and try again?

**Comment by jpgarcia** [comment]
@sagarrs Could you make it work? I got a similar error running with the following versions:

react-native cli version = **2.0.1**
node version = **11.9.0**
npm version = **6.10.0**
yarn version = **1.16.0**

The solution was updating **node** as per the following error : 

```bash
error eslint@6.0.1: The engine "node" is incompatible with this module. Expected version "^8.10.0 || ^10.13.0 || >=11.10.1". Got "11.9.0"
```

Original failing output:

```bash
react-native init androidxsample
This will walk you through creating a new React Native project in /Users/myusername/Projects/examples/androidxsample
Using yarn v1.16.0
Installing react-native...
yarn add v1.16.0
warning ../../../package.json: No license field
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning react-native > create-react-class > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-native > metro-react-native-babel-transformer@0.54.1" has unmet peer dependency "@babel/core@*".
warning " > react-native@0.60.0" has unmet peer dependency "react@16.8.6".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 410 new dependencies.
info Direct dependencies
└─ react-native@0.60.0
info All dependencies
├─ @babel/generator@7.5.0
├─ ...
└─ yargs-parser@7.0.0
✨  Done in 10.18s.
info Setting up new React Native app in /Users/myusername/Projects/examples/androidxsample
info Adding required dependencies
yarn add v1.16.0
warning ../../../package.json: No license field
[1/4] 🔍  Resolving packages...
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @react-native-community/eslint-config@0.0.3" has unmet peer dependency "eslint@>=5".
warning "@react-native-community/eslint-config > babel-eslint@10.0.1" has unmet peer dependency "eslint@>= 4.12.1".
warning "@react-native-community/eslint-config > eslint-plugin-react-native@3.6.0" has unmet peer dependency "eslint@^3.17.0 || ^4 || ^5".
warning "@react-native-community/eslint-config > eslint-plugin-flowtype@2.50.3" has unmet peer dependency "eslint@>=2.0.0".
warning "@react-native-community/eslint-config > eslint-plugin-eslint-comments@3.1.2" has unmet peer dependency "eslint@>=4.19.1".
warning "@react-native-community/eslint-config > eslint-plugin-react-hooks@1.6.1" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
warning "@react-native-community/eslint-config > eslint-plugin-react@7.12.4" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0".
warning "@react-native-community/eslint-config > eslint-plugin-jest@22.4.1" has unmet peer dependency "eslint@>=5".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 142 new dependencies.
info Direct dependencies
├─ @react-native-community/eslint-config@0.0.3
├─ ...
└─ xml-name-validator@3.0.0
✨  Done in 11.77s.
info Adding required dev dependencies
yarn add v1.16.0
warning ../../../package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning Pattern ["@babel/core@^7.5.0"] is trying to unpack in the same destination "/Users/myusername/Library/Caches/Yarn/v4/npm-@babel-core-7.5.0-6ed6a2881ad48a732c5433096d96d1b0ee5eb734/node_modules/@babel/core" as pattern ["@babel/core@^7.0.0","@babel/core@^7.0.0","@babel/core@^7.0.0","@babel/core@^7.0.0","@babel/core@^7.0.0","@babel/core@^7.1.0","@babel/core@^7.1.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@babel/runtime@^7.5.1"] is trying to unpack in the same destination "/Users/myusername/Library/Caches/Yarn/v4/npm-@babel-runtime-7.5.1-51b56e216e87103ab3f7d6040b464c538e242888/node_modules/@babel/runtime" as pattern ["@babel/runtime@^7.0.0"]. This could result in non-deterministic behavior, skipping.
error eslint@6.0.1: The engine "node" is incompatible with this module. Expected version "^8.10.0 || ^10.13.0 || >=11.10.1". Got "11.9.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
(node:46742) UnhandledPromiseRejectionWarning: Error: Command failed: yarn add -D @babel/core @babel/runtime @react-native-community/eslint-config eslint jest babel-jest metro-react-native-babel-preset react-test-renderer@16.8.6
    at makeError (/Users/myusername/Projects/examples/androidxsample/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/myusername/Projects/examples/androidxsample/node_modules/execa/index.js:278:16)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:46742) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:46742) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by GregLovesCoding** [comment]
@jpgarcia: had the same error. Updating my node version helped me solve the error.

Here is how you do it: https://stackoverflow.com/questions/8191459/how-do-i-update-node-js

**Comment by meinou** [comment]
I have both updated and still have this error which is no sense: eslint@6.1.0: The engine "node" is incompatible with this module. Expected version "^8.10.0 || ^10.13.0 || >=11.10.1". Got "11.9.0"
