### ISSUE TITLE
node_modules/react-native/packager/launchPackager.command ; exit;

### ISSUE THREAD

**Issue by yangaqi** [facebook/react-native#2550]
2015-09-04 10:33:21.666 [warn][tid:NSOperationQueue 0x7fd4c5801130 :: NSOperation 0x7fd4c5bb5760 (QOS: UTILITY)][RCTDevMenu.m:211] RCTSourceCode module scriptURL has not been set
2015-09-04 10:33:21.672 [error][tid:NSOperationQueue 0x7fd4c5801130 :: NSOperation 0x7fd4c5bb5760 (QOS: UTILITY)][RCTBatchedBridge.m:127] Error Domain=JSServer Code=500 "{"type":"InternalError","message":"react-packager has encountered an internal error, please check your terminal error output for more details"}" UserInfo=0x7fd4c36264a0 {NSLocalizedDescription={"type":"InternalError","message":"react-packager has encountered an internal error, please check your terminal error output for more details"}}

**Comment by yangaqi** [comment]
1.react-native init sample
2.open project in Xcode  hit run button
3.TypeError: Cannot read property 'root' of null
 at /xxx/node_modules/react-native/packager/react-packager/src/DependencyResolver/crawlers/index.js:16:84
    at tryCallOne (/xxx/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /xxx/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/xxx/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at process._tickCallback (node.js:355:11)

**Comment by yangaqi** [comment]
watchman。。。

**Comment by sany620** [comment]
cannot find index.ios.js,cocoadpos，
