### ISSUE TITLE
Error while running react native run ios

### ISSUE THREAD

**Issue by koutily** [facebook/react-native#25533]
When i am running react-native run-ios i  am getting the error 

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'prompt'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:43:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

React Native version:
react-native:0.58.6
react:16.6.3

## Steps To Reproduce

1.
2.

Describe what you expected to happen:

Snack, code example, or link to a repository:

**Comment by donkasun** [comment]
I get this error when running `react-native start` or `react-native run-android`

`Error: Cannot find module '../../tools/PackageManager'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/don/Dialog/integreation-retailerhub/dialog-ssa/mobile/node_modules/@react-native-community/cli/build/commands/install/uninstall.js:10:46)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
`

**Comment by donkasun** [comment]
> I get this error when running `react-native start` or `react-native run-android`
> 
> `internal/modules/cjs/loader.js:638
> throw err;
> ^
> 
> Error: Cannot find module '../../tools/PackageManager'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
> at Function.Module._load (internal/modules/cjs/loader.js:562:25)
> at Module.require (internal/modules/cjs/loader.js:690:17)
> at require (internal/modules/cjs/helpers.js:25:18)
> at Object. (/home/don/Dialog/integreation-retailerhub/dialog-ssa/mobile/node_modules/@react-native-community/cli/build/commands/install/uninstall.js:10:46)
> at Module._compile (internal/modules/cjs/loader.js:776:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
> at Module.load (internal/modules/cjs/loader.js:653:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
> at Function.Module._load (internal/modules/cjs/loader.js:585:3)
> `

Removing the node modules and reinstalling did not work

**Comment by donkasun** [comment]
` '../../tools/PackageManager'` file is `packageManager` instead of `PackageManager` in my case. Replaced the module @react-native community/cli with version 1.10.0.
