### ISSUE TITLE
Can't install the app by any means

### ISSUE THREAD

**Issue by naderabdalghani** [facebook/react-native#25550]
I can't seem to deploy my app on a device/emulator using the only two ways that I know of as both aren't working.

### Running `react-native run-android`:

As soon as the BUNDLE process in the Metro Bundler reaches 100% the app crashes.

![image](https://user-images.githubusercontent.com/33901325/60837952-dd037300-a1c9-11e9-808d-68df8ef5bf62.png)

Notice that I had the following things done, which may or may not be of involvement in this error: 

- I manually modified the launchPackager.bat file located in `node_modules/react-native/scripts/` according to the following diff:

``` diff
+cd ../../../
+node "%~dp0..\cli.js" start
-node "%~dp0..\cli.js" --projectRoot ../../../ start
```
- I downgraded Node.js from 12.6.0 to 12.40 due to a memory issue
- I updated @react-native-community/cli to 2.1.2
- I migrated to AndroidX

**Steps To Reproduce**
1.`react-native run-android`

### Generating an APK file using `./gradlew assembleRelease` in the android directory:

The following is generated after running `./gradlew assembleRelease`

```
> Configure project :react-native-webview
:react-native-webview:reactNativeAndroidRoot I:\Upwork\south-point-pizza-react-native\node_modules\react-native\android

> Configure project :react-native-onesignal
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Configure project :react-native-admob
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Task :app:bundleReleaseJsAndAssets
warn Package react-native-onesignal has been ignored because it contains invalid configuration. Reason: Unknown option dependency.platforms.ios.sourceDir with value ""./ios"" was found. This is either a typing error or a user mistake. Fixing it will remove this message.
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-vector-icons: https://github.com/oblador/react-native-vector-icons
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
warning: the transform cache was reset.
warn Package react-native-onesignal has been ignored because it contains invalid configuration. Reason: Unknown option dependency.platforms.ios.sourceDir with value ""./ios"" was found. This is either a typing error or a user mistake. Fixing it will remove this message.
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-vector-icons: https://github.com/oblador/react-native-vector-icons
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
Loading dependency graph, done.
error SyntaxError: I:\Upwork\south-point-pizza-react-native\src\components\LeftMenu\MenuOverlay.js: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (12:1):

  10 |
  11 |
> 12 | @withTheme
     | ^
  13 | class MenuOverlay extends PureComponent {
  14 |   static propTypes = {
  15 |     goToScreen: PropTypes.func,. Run CLI with --verbose flag for more details.
SyntaxError: I:\Upwork\south-point-pizza-react-native\src\components\LeftMenu\MenuOverlay.js: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (12:1):

  10 |
  11 |
> 12 | @withTheme
     | ^
  13 | class MenuOverlay extends PureComponent {
  14 |   static propTypes = {
  15 |     goToScreen: PropTypes.func,
    at Object.raise (I:\Upwork\south-point-pizza-react-native\node_modules\@babel\parser\lib\index.js:6325:17)
    at Object.expectOnePlugin (I:\Upwork\south-point-pizza-react-native\node_modules\@babel\parser\lib\index.js:7657:18)
    at Object.parseDecorator (I:\Upwork\south-point-pizza-react-native\node_modules\@babel\parser\lib\index.js:10011:10)
    at Object.parseDecorators (I:\Upwork\south-point-pizza-react-native\node_modules\@babel\parser\lib\index.js:9993:30)
    at Object.parseStatement (I:\Upwork\south-point-pizza-react-native\node_modules\@babel\parser\lib\index.js:9826:12)
    at Object.parseStatement (I:\Upwork\south-point-pizza-react-native\node_modules\@babel\parser\lib\index.js:2021:26)
    at Object.parseBlockOrModuleBlockBody (I:\Upwork\south-point-pizza-react-native\node_modules\@babel\parser\lib\index.js:10405:25)
    at Object.parseBlockBody (I:\Upwork\south-point-pizza-react-native\node_modules\@babel\parser\lib\index.js:10392:10)
    at Object.parseTopLevel (I:\Upwork\south-point-pizza-react-native\node_modules\@babel\parser\lib\index.js:9758:10)
    at Object.parseTopLevel (I:\Upwork\south-point-pizza-react-native\node_modules\@babel\parser\lib\index.js:2849:28)

> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 57s
119 actionable tasks: 1 executed, 118 up-to-date
```

I've tried running `npm i --save-dev @babel/plugin-proposal-class-properties @babel/plugin-proposal-decorators` and `./gradlew --stop` but both were of no use.

I also added `["@babel/plugin-proposal-class-properties", { "loose": true}]` in the .babelrc file but nothing has changed.

My .babelrc:

```
{
  "presets": ["module:metro-react-native-babel-preset"],
  "env": {
    "production": {
      "plugins": [
        "transform-remove-console", 
        ["@babel/plugin-proposal-decorators", { "legacy": true}],
        ["@babel/plugin-proposal-class-properties", { "loose": true}]
      ]
    },
    "development": {
      "plugins": [
        "transform-remove-console", 
        ["@babel/plugin-proposal-decorators", { "legacy": true}],
        ["@babel/plugin-proposal-class-properties", { "loose": true}]
      ]
    }
  }
}

```

My package.json:

```
{
  "name": "SouthPointPizza",
  "version": "3.8.0",
  "description": "React Native mobile app for WooCommerce",
  "author": "InspireUI",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "build:ios": "node node_modules/react-native/local-cli/cli.js bundle --entry-file='index.js' --bundle-output='./ios/mstore/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios'",
    "setup": "./scripts/setup.sh",
    "setup:android": "./scripts/setup_android.sh",
    "reset": "./scripts/reset.sh",
    "postinstall": "patch-package",
    "devtools": "react-devtools",
    "reverseADB": "adb reverse tcp:8097 tcp:8097",
    "buildAndroid": "cd android && gradlew assembleRelease"
  },
  "dependencies": { ... },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.5.0",
    "@babel/plugin-proposal-decorators": "^7.4.4",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "24.8.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "jest": "24.8.0",
    "metro-react-native-babel-preset": "0.54.0",
    "reactotron-react-native": "3.5.0",
    "reactotron-redux": "3.1.0"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts/"
    ]
  }
}
```
**Steps To Reproduce**
1.`cd android`
2.`./gradlew assembleRelease`

React Native version: 0.60.0

System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz
    Memory: 965.77 MB / 7.89 GB
  Binaries:
    Node: 12.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156

**Comment by jonathangreco** [comment]
Please provide the code referenced in the Syntax Error :

> error SyntaxError: I:\Upwork\south-point-pizza-react-native\src\components\LeftMenu\MenuOverlay.js: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (12:1):

This is pretty clear to me.

**Comment by naderabdalghani** [comment]
```
  10 |
  11 |
> 12 | @withTheme
     | ^
  13 | class MenuOverlay extends PureComponent {
  14 |   static propTypes = {
  15 |     goToScreen: PropTypes.func,
```

**Comment by jonathangreco** [comment]
Well what is that ?

`@withTheme`

It's coming from what package ? And why you post an issue here ? :)

Plus your notation is quite invalid in react native, use Higher Order component, or props to configure a theme.

This should be closed as it's off topic.

**Comment by naderabdalghani** [comment]
> It's coming from what package ? And why you post an issue here ? :)

It's coming from a package named react-native-paper. I posted this issue here because I could build the app without a hassle before the new React Native 0.60.0 update, and the only way I could get around this problem was by downgrading to an older version of React Native 0.59.8

> Plus your notation is quite invalid in react native, use Higher Order component, or props to configure a theme.

I don't think so. As I just mentioned, the app now is built without any error whatsoever using React Native 0.59.8.

**Comment by jonathangreco** [comment]
@naderabdalghani So react-native-paper is may not compatible with react native 0.60 it can be that.

Still I don't think maintainers will take a look at this since it's not related directly to react native itself, did you try to post an issue in react-native-paper package to see if it can be reproduced on their side ?

**Comment by naderabdalghani** [comment]
To be honest, no I haven't posted there as I hadn't thought of this possibility. Thanks for putting it in front of my eyes.
