### ISSUE TITLE
in react js if i implement webpack then facing this issue how i its resolved 

### ISSUE THREAD

**Issue by vinodjoshi11** [facebook/react-native#25596]
$ npm start

> myapp@1.0.0 start D:\myapp
> webpack-dev-server --open --port 4000 -compress --mode development

internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean
    at validateString (internal/validators.js:125:11)
    at Object.isAbsolute (path.js:399:5)
    at module.exports (D:\myapp\node_modules\webpack-cli\bin\utils\convert-argv.js:36:13)
    at Object.<anonymous> (D:\myapp\node_modules\webpack-dev-server\bin\webpack-dev-server.js:79:40)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myapp@1.0.0 start: `webpack-dev-server --open --port 4000 -compress --mode development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myapp@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DEEL\AppData\Roaming\npm-cache\_logs\2019-07-11T16_01_04_703Z-debug.log

**Comment by dulmandakh** [comment]
Webpack is not supported, please use webpackat you own risk. Thank you
