### ISSUE TITLE
"type":"InternalError","message":"react-packager has encountered an internal error

### ISSUE THREAD

**Issue by stormtea123** [facebook/react-native#2564]
```text
{"type":"InternalError","message":"react-packager has encountered an internal error, please check your terminal error output for more details"}
```
```text
[05:17:09] <START> fs crawl
Error: query failed: synchronization failed: Permission denied

    at BunserBuf.<anonymous> (/Library/WebServer/Documents/Elephant/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:93:23)
    at BunserBuf.emit (events.js:107:17)
    at BunserBuf.process (/Library/WebServer/Documents/Elephant/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/node_modules/bser/index.js:289:10)
    at /Library/WebServer/Documents/Elephant/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/node_modules/bser/index.js:244:12
    at process._tickCallback (node.js:355:11)
[05:17:36] <START> request:/index.ios.bundle
[05:17:36] <START> find dependencies
```

**Comment by stormtea123** [comment]
I have resolved

    chmod -R 777 *

**Comment by bernalmurcia** [comment]
Did you run chmod in the root of your project? I get the same error still after running it.

**Comment by bernalmurcia** [comment]
Ok, I just needed to update watchman.
