### ISSUE TITLE
Fatal Exception: java.lang.AssertionError: Pausing an activity that is not the current activity, this is incorrect!

### ISSUE THREAD

**Issue by Andoridswordsman** [facebook/react-native#25860]
**Stacktrace**
Fatal Exception: java.lang.AssertionError: Pausing an activity that is not the current activity, this is incorrect! Current activity: GSReactActivity Paused activity: GSReactActivity
       at com.facebook.infer.annotation.Assertions.assertCondition + 72(Assertions.java:72)
       at com.facebook.react.ReactInstanceManager.onHostPause + 511(ReactInstanceManager.java:511)
       at com.facebook.react.ReactActivityDelegate.onPause + 94(ReactActivityDelegate.java:94)
       at com.gsbaselib.base.rn.GSReactActivityDelegate.onPause + 79(GSReactActivityDelegate.java:79)
       at com.gsbaselib.base.rn.GSBaseReactActivity.onPause + 80(GSBaseReactActivity.java:80)
       at android.app.Activity.performPause + 7663(Activity.java:7663)
       at android.app.Instrumentation.callActivityOnPause + 1536(Instrumentation.java:1536)
       at com.qiyukf.unicorn.i.a.callActivityOnPause(a.java:2)
       at android.app.ActivityThread.performPauseActivityIfNeeded + 4726(ActivityThread.java:4726)
       at android.app.ActivityThread.performPauseActivity + 4691(ActivityThread.java:4691)
       at android.app.ActivityThread.handlePauseActivity + 4626(ActivityThread.java:4626)
       at android.app.servertransaction.PauseActivityItem.execute + 45(PauseActivityItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState + 145(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute + 70(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage + 2199(ActivityThread.java:2199)
       at android.os.Handler.dispatchMessage + 112(Handler.java:112)
       at android.os.Looper.loop + 216(Looper.java:216)
       at android.app.ActivityThread.main + 7625(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 524(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main + 987(ZygoteInit.java:987)

**environment**
react-native: 0.59.9

**device info**
![image](https://user-images.githubusercontent.com/15956290/62034311-6255d280-b220-11e9-825e-cef80a89ddd9.png)

The problem for a long time ...

**Comment by dimlksin2** [comment]
phone_model: SM-J600F
android_version: 9

java.lang.AssertionError: Pausing an activity that is not the current activity, this is incorrect! Current activity: MainActivity Paused activity: MainActivity
	at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:72)
	at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:511)
	at com.facebook.react.ReactActivityDelegate.onPause(ReactActivityDelegate.java:94)
	at com.facebook.react.ReactActivity.onPause(ReactActivity.java:58)
	at android.app.Activity.performPause(Activity.java:7619)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1469)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4257)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4222)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4174)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:187)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1960)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7076)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by john1jan** [comment]
Getting the same crash for me as well

```java.lang.AssertionError Pausing an activity that is not the current activity, this is incorrect! Current activity: MainActivity Paused activity: ExampleActivity 
    Assertions.java:72 com.facebook.infer.annotation.Assertions.assertCondition
    ReactInstanceManager.java:511 com.facebook.react.ReactInstanceManager.onHostPause
    ReactActivityDelegate.java:94 com.facebook.react.ReactActivityDelegate.onPause
    ReactActivity.java:58 com.facebook.react.ReactActivity.onPause
    Activity.java:7232 android.app.Activity.performPause
    Instrumentation.java:1409 android.app.Instrumentation.callActivityOnPause
    ActivityThread.java:3952 android.app.ActivityThread.performPauseActivityIfNeeded
    ActivityThread.java:3929 android.app.ActivityThread.performPauseActivity
    ActivityThread.java:3903 android.app.ActivityThread.performPauseActivity
    ActivityThread.java:3874 android.app.ActivityThread.handlePauseActivity
    Unknown android.app.ActivityThread.-wrap15
    ActivityThread.java:1630 android.app.ActivityThread$H.handleMessage
    Handler.java:106 android.os.Handler.dispatchMessage
    Looper.java:176 android.os.Looper.loop
    ActivityThread.java:6651 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:547 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:824 com.android.internal.os.ZygoteInit.main```

**Comment by felansu** [comment]
```
Fatal Exception: java.lang.AssertionError: Pausing an activity that is not the current activity, this is incorrect! Current activity: MainActivity Paused activity: MainActivity
       at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:72)
       at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:549)
       at com.facebook.react.ReactDelegate.onHostPause(ReactDelegate.java:63)
       at com.facebook.react.ReactActivityDelegate.onPause(ReactActivityDelegate.java:95)
       at com.facebook.react.ReactActivity.onPause(ReactActivity.java:51)
       at android.app.Activity.performPause(Activity.java:8142)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1508)
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4726)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4687)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4639)
       at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7814)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Comment by firstfloordigital** [comment]
any fix, I am also facing the same issue?
