### ISSUE TITLE
Fatal Exception: java.lang.AssertionError: Pausing an activity that is not the current activity, this is incorrect!

### ISSUE THREAD

**Issue by Andoridswordsman** [facebook/react-native#25861]
Fatal Exception: java.lang.AssertionError: Pausing an activity that is not the current activity, this is incorrect! Current activity: GSReactActivity Paused activity: GSReactActivity
at com.facebook.infer.annotation.Assertions.assertCondition + 72(Assertions.java:72)
at com.facebook.react.ReactInstanceManager.onHostPause + 511(ReactInstanceManager.java:511)
at com.facebook.react.ReactActivityDelegate.onPause + 94(ReactActivityDelegate.java:94)
at com.gsbaselib.base.rn.GSReactActivityDelegate.onPause + 79(GSReactActivityDelegate.java:79)
at com.gsbaselib.base.rn.GSBaseReactActivity.onPause + 80(GSBaseReactActivity.java:80)
at android.app.Activity.performPause + 7663(Activity.java:7663)
at android.app.Instrumentation.callActivityOnPause + 1536(Instrumentation.java:1536)
at com.qiyukf.unicorn.i.a.callActivityOnPause(a.java:2)
at android.app.ActivityThread.performPauseActivityIfNeeded + 4726(ActivityThread.java:4726)
at android.app.ActivityThread.performPauseActivity + 4691(ActivityThread.java:4691)
at android.app.ActivityThread.handlePauseActivity + 4626(ActivityThread.java:4626)
at android.app.servertransaction.PauseActivityItem.execute + 45(PauseActivityItem.java:45)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState + 145(TransactionExecutor.java:145)
at android.app.servertransaction.TransactionExecutor.execute + 70(TransactionExecutor.java:70)
at android.app.ActivityThread$H.handleMessage + 2199(ActivityThread.java:2199)
at android.os.Handler.dispatchMessage + 112(Handler.java:112)
at android.os.Looper.loop + 216(Looper.java:216)
at android.app.ActivityThread.main + 7625(ActivityThread.java:7625)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 524(RuntimeInit.java:524)
at com.android.internal.os.ZygoteInit.main + 987(ZygoteInit.java:987)

React Native version:
0.59.9

Describe what you expected to happen:
![image](https://user-images.githubusercontent.com/15956290/62036687-da25fc00-b224-11e9-89ab-e9dc7f07977d.png)

Snack, code example, screenshot, or link to a repository:

**Comment by Andoridswordsman** [comment]
anybody here?

**Comment by chakrihacker** [comment]
Can you provide more details about GSReactActivity??

**Comment by Andoridswordsman** [comment]
> Can you provide more details about GSReactActivity??

There are many such problem， it' s nothing to do with GSReactActivity

**Comment by dimlksin2** [comment]
phone_model: SM-J600F
android_version: 9

java.lang.AssertionError: Pausing an activity that is not the current activity, this is incorrect! Current activity: MainActivity Paused activity: MainActivity
	at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:72)
	at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:511)
	at com.facebook.react.ReactActivityDelegate.onPause(ReactActivityDelegate.java:94)
	at com.facebook.react.ReactActivity.onPause(ReactActivity.java:58)
	at android.app.Activity.performPause(Activity.java:7619)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1469)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4257)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4222)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4174)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:187)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1960)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7076)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by HelloJack0** [comment]
Huawei HUAWEI P30 lite (HWMAR), Android 9
java.lang.AssertionError: 
  at com.facebook.infer.annotation.Assertions.assertCondition (Assertions.java:72)
  at com.facebook.react.ReactInstanceManager.onHostPause (ReactInstanceManager.java:511)
  at com.facebook.react.ReactActivityDelegate.onPause (ReactActivityDelegate.java:94)
  at com.facebook.react.ReactActivity.onPause (ReactActivity.java:58)
  at com.alpha.app.MainActivity.onPause (MainActivity.java:75)
  at android.app.Activity.performPause (Activity.java:7646)
  at android.app.Instrumentation.callActivityOnPause (Instrumentation.java:1536)
  at android.app.ActivityThread.performPauseActivityIfNeeded (ActivityThread.java:4650)
  at android.app.ActivityThread.performPauseActivity (ActivityThread.java:4615)
  at android.app.ActivityThread.handlePauseActivity (ActivityThread.java:4550)
  at android.app.servertransaction.PauseActivityItem.execute (PauseActivityItem.java:45)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:145)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:70)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2155)
  at android.os.Handler.dispatchMessage (Handler.java:109)
  at android.os.Looper.loop (Looper.java:207)
  at android.app.ActivityThread.main (ActivityThread.java:7539)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:958)

**Comment by Grom-S** [comment]
What are the steps to reproduce this issue? I am getting the same crash reports, but not sure how to reproduce it locally?
