### ISSUE TITLE
While generating the android and ios file in react-native 

### ISSUE THREAD

**Issue by manjupriyajaintm** [facebook/react-native#26026]
Package <dependency> has been ignored because it contains invalid configuration. Reason: Cannot find module '<dependency>\package.json'
{
  "name": "ddma",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "jetifier": "^1.6.3",
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-fade-in-image": "^1.5.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-image-picker": "^1.0.1",
    "react-native-maps": "0.25.0",
    "react-native-material-ui": "^1.30.1",
    "react-native-materialui-textfield": "^0.13.2",
    "react-native-otp-inputs": "^3.2.0",
    "react-native-radio-buttons": "^1.0.0",
    "react-native-ratings": "^6.3.1",
    "react-native-responsive-screen": "^1.2.2",
    "react-native-simple-radio-button": "^2.7.3",
    "react-native-textarea": "^1.0.3",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^3.11.1"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.8.0",
    "eslint": "^6.1.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.55.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

Require stack:
- D:\ddma\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\config\resolveNodeModuleDir.js
- D:\ddma\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\releaseChecker\index.js                                                                                                - D:\ddma\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\server\runServer.js
- D:\ddma\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\server\server.js
- D:\ddma\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\index.js    - D:\ddma\node_modules\react-native\node_modules\@react-native-community\cli\build\cliEntry.js
- D:\ddma\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js             - D:\ddma\node_modules\react-native\cli.js
- C:\Users\manju\AppData\Roaming\npm\node_modules\react-native-cli\index.js                             warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-maps: https://github.com/react-native-community/react-native-maps#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
error The "path" argument must be of type string. Received type undefined. Run CLI with --verbose flag for more details.
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Object.basename (path.js:668:5)                                                                      at D:\ddma\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\link\linkAll.js:56:87
    at baseUniq (D:\ddma\node_modules\lodash\lodash.js:4276:35)                                             at uniqBy (D:\ddma\node_modules\lodash\lodash.js:8418:40)
    at dedupeAssets (D:\ddma\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\link\linkAll.js:56:53)
    at linkAll (D:\ddma\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\link\linkAll.js:87:20)
    at Object.link [as func] (D:\ddma\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\link\link.js:80:33)                                                                         at Command.handleAction (D:\ddma\node_modules\react-native\node_modules\@react-native-community\cli\build\cliEntry.js:160:21)                                                                                   at Command.listener (D:\ddma\node_modules\commander\index.js:315:8)
React Native version:

## Steps To Reproduce

1.
2.

Describe what you expected to happen:
I want generate the android and ios file in react native 

Snack, code example, screenshot, or link to a repository:

**Comment by radko93** [comment]
Please create a new issue using the template.
