### ISSUE TITLE
[Android] Crash when lunch after upgrading RN 0.60

### ISSUE THREAD

**Issue by yelkamel** [facebook/react-native#26041]
Hello,
After upgrading react native to get it work when build 64Bits (for the last GooglePlay requirement)
I follow the guideline for upgrade, now I'm crashing at start with the following logcat error 
Android application crash on start.

**Logcat**

`7724-7788 E/CrashLogHandler: Stack trace: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/react/views/webview/ReactWebViewManager;
        at com.planet.planetpv.MainApplication$1.getPackages(MainApplication.java:53)
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:78)
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:91)
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:80)
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:52)
        at com.planet.planetpv.MainActivity.onCreate(MainActivity.java:32)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.react.views.webview.ReactWebViewManager" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.planet.planetpv.debug-kl4UVs7kB1DjwIuGzZwG2w==/base.apk", zip file "/data/app/com.planet.planetpv`

Just in case, regarding org.apache.http.legacy, I added  
`<uses-library android:name="org.apache.http.legacy" android:required="false"/>`
in the AndroidManifest to get react-native-maps work with android 9 (it was working before the upgrade process).

**Environment:**
 - OS: Android
 - OS version: 9 
 - react-native version: ^0.60.4
 - react-native-webview version: ^6.9.0

**Comment by j-wang** [comment]
You'll want to take a look at the tombstone, but I've seen this particular log when the issue in https://github.com/facebook/react-native/issues/25494 occurs—given that it came from building in 64-bit, that also makes it more likely it's this.

That being said, check for something that looks like `signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x20` or traces related to `libjsc.so`.

**Comment by ahmadalfy** [comment]
This issue is still happening, I just upgraded a new project to the latest version of RN and I am facing that issue
