### ISSUE TITLE
Metro Bundler failed

### ISSUE THREAD

**Issue by KingAmo** [facebook/react-native#26073]
1. run `react native start`:
```
Loading dependency graph...jest-haste-map: Haste module naming collision: hermes-inspector-msggen
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/node_modules/react-native/ReactCommon/hermes/inspector/tools/msggen/package.json
    * <rootDir>/ios/Pods/react-native/ReactCommon/hermes/inspector/tools/msggen/package.json

Failed to construct transformer:  DuplicateError: Duplicated files or mocks. Please check the console for more info
    at setModule (/Users/qinshuai/Documents/ReactNativeProj/kjkDoctor/node_modules/jest-haste-map/build/index.js:620:17)
    at workerReply (/Users/qinshuai/Documents/ReactNativeProj/kjkDoctor/node_modules/jest-haste-map/build/index.js:691:9)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Promise.all (index 25) {
  mockPath1: 'node_modules/react-native/ReactCommon/hermes/inspector/tools/msggen/package.json',
  mockPath2: 'ios/Pods/react-native/ReactCommon/hermes/inspector/tools/msggen/package.json'
}
(node:48224) UnhandledPromiseRejectionWarning: Error: Duplicated files or mocks. Please check the console for more info
    at setModule (/Users/qinshuai/Documents/ReactNativeProj/kjkDoctor/node_modules/jest-haste-map/build/index.js:620:17)
    at workerReply (/Users/qinshuai/Documents/ReactNativeProj/kjkDoctor/node_modules/jest-haste-map/build/index.js:691:9)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Promise.all (index 25)
(node:48224) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:48224) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: Duplicated files or mocks. Please check the console for more info
    at setModule (/Users/qinshuai/Documents/ReactNativeProj/kjkDoctor/node_modules/jest-haste-map/build/index.js:620:17)
    at workerReply (/Users/qinshuai/Documents/ReactNativeProj/kjkDoctor/node_modules/jest-haste-map/build/index.js:691:9)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Promise.all (index 25)
```

React Native version:

```
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 186.87 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 21, 23, 26, 27, 28
      Build Tools: 23.0.1, 26.0.1, 28.0.3
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
```
## Steps To Reproduce

1. run `react native start`

Describe what you expected to happen:

 Metro Bundler success

Snack, code example, screenshot, or link to a repository:

**Comment by KingAmo** [comment]
## UPDATE

resolved this issue by remove CocoaPods in my project using [cocoapods-deintegrate](https://github.com/CocoaPods/cocoapods-deintegrate)，and then run `pod install`

**Comment by sudhiryadav** [comment]
For me there was a duplicate folder node_module_bak probably created by a script from different library.
