### ISSUE TITLE
ANDROID CRASHES BY  couldn't find DSO to load

### ISSUE THREAD

**Issue by Ekhui** [facebook/react-native#26122]
0.60.5 app on android crashes on Android 5.1.1 

React Native version:
0.60.5

1.react-native init newProject
2.react-native run android

 E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.newProject, PID: 25851
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:27)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:949)
        at java.lang.Thread.run(Thread.java:818)

**Comment by Zloka** [comment]
I "solved" a similar issue, see if that helps you.

https://github.com/facebook/react-native/issues/25986#issuecomment-520424504

**Comment by Ekhui** [comment]
unwork for me ..

**Comment by daidaishuiping** [comment]
I "solved" a similar issue, see if that helps you.

**Comment by daidaishuiping** [comment]
I "solved" a similar issue, see if that helps you.

**Comment by forJrking** [comment]
i fix it https://github.com/facebook/react-native/issues/25537#issuecomment-568446732
