### ISSUE TITLE
另一个程序已锁定文件的一部分，进程无法访问

### ISSUE THREAD

**Issue by sixiaobing** [facebook/react-native#26150]
Caused by: org.gradle.api.UncheckedIOException: Failed to capture fingerprint of input files for task ':app:bundle360store_2ReleaseJsAndAssets' property '$1' during up-to-date check.
	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.fingerprintTaskFiles(CacheBackedTaskHistoryRepository.java:360)
	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.createExecution(CacheBackedTaskHistoryRepository.java:163)
Caused by: org.gradle.api.UncheckedIOException: Failed to create MD5 hash for file content.
	at org.gradle.internal.hash.DefaultStreamHasher.hash(DefaultStreamHasher.java:40)
	at org.gradle.internal.hash.DefaultFileHasher.hash(DefaultFileHasher.java:40)
	at org.gradle.api.internal.changedetection.state.CachingFileHasher.snapshot(CachingFileHasher.java:89)
	at org.gradle.api.internal.changedetection.state.CachingFileHasher.hash(CachingFileHasher.java:67)
	at org.gradle.api.internal.changedetection.state.SplitFileHasher.hash(SplitFileHasher.java:64)
	at 
Caused by: java.io.IOException: 另一个程序已锁定文件的一部分，进程无法访问。
	at java.io.FileInputStream.readBytes(Native Method)

**Comment by woai146886** [comment]
Is it resolved?
