### ISSUE TITLE
Cannot read property '_text' of undefined

### ISSUE THREAD

**Issue by SilverFoxA** [facebook/react-native#26203]
```
Abhijits-MacBook-Pro:ts-react-native Avi$ react-native link --verbose
debug Available platforms: iOS, Android
debug Targeted platforms: iOS, Android
debug Getting project config for iOS...
debug Getting project config for Android...
error No package found. Are you sure this is a React Native project?
error Cannot read property '_text' of undefined
debug TypeError: Cannot read property '_text' of undefined
    at SAXParser.parser_text [as ontext] (/Volumes/.../ts-react-native/node_modules/@react-native-community/cli/node_modules/xmldoc/lib/xmldoc.js:235:39)
    at emit (/Volumes/.../ts-react-native/node_modules/@react-native-community/cli/node_modules/sax/lib/sax.js:639:35)
    at closeText (/Volumes/.../ts-react-native/node_modules/@react-native-community/cli/node_modules/sax/lib/sax.js:649:26)
    at emitNode (/Volumes/.../ts-react-native/node_modules/@react-native-community/cli/node_modules/sax/lib/sax.js:643:26)
    at SAXParser.write (/Volumes/.../ts-react-native/node_modules/@react-native-community/cli/node_modules/sax/lib/sax.js:1195:15)
    at new XmlDocument (/Volumes/.../ts-react-native/node_modules/@react-native-community/cli/node_modules/xmldoc/lib/xmldoc.js:199:15)
    at readManifest (/Volumes/.../ts-react-native/node_modules/@react-native-community/cli/build/tools/android/readManifest.js:44:10)
    at Object.projectConfig (/Volumes/.../ts-react-native/node_modules/@react-native-community/cli/build/tools/android/index.js:66:46)
    at Object.keys.forEach.platform (/Volumes/.../ts-react-native/node_modules/@react-native-community/cli/build/commands/link/getProjectConfig.js:25:62)
    at Array.forEach (<anonymous>)

```

React Native version:

```
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 1005.64 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.3.0 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 24, 25, 26, 27, 28, 29
        Build Tools: 27.0.1, 27.0.2, 27.0.3, 28.0.3, 29.0.1
        System Images: android-20 | Android Wear Intel x86 Atom, android-26 | Google Play Intel x86 Atom
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.3.1 => 16.3.1 
      react-native: 0.59.3 => 0.59.3 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

## Steps To Reproduce

1. Upgraded react version `55.3` to `59.1`
2. `react-native link` in terminal

Describe what you expected to happen:

The above command should link all the libraries and other assets linked to the project.

Snack, code example, screenshot, or link to a repository:

`package.json`

```
{
  "name": "...",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "android": "react-native run-android",
    "prod:build": "cd android && ./gradlew assembleRelease",
    "test": "jest"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "lodash": "^4.17.11",
    "md5": "^2.2.1",
    "native-base": "^2.4.4",
    "react": "16.3.1",
    "react-native": "0.59.3",
    "react-native-app-intro": "^1.1.5",
    "react-native-facebook-login": "^1.6.1",
    "react-native-fbsdk": "^0.8.0",
    "react-native-firebase": "3.2.0",
    "react-native-flash-message": "^0.1.9",
    "react-native-gesture-handler": "^1.0.0-alpha.43",
    "react-native-gifted-chat": "^0.4.3",
    "react-native-google-places": "^2.5.2",
    "react-native-google-signin": "^0.12.0",
    "react-native-image-crop-picker": "^0.21.3",
    "react-native-image-zoom-viewer": "^2.2.5",
    "react-native-immersive": "^1.1.2",
    "react-native-infinite-scroll": "^1.0.6",
    "react-native-localization": "^1.0.7",
    "react-native-maps": "^0.21.0",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-modal-wrapper": "^3.1.0",
    "react-native-parallax-header": "^1.0.6",
    "react-native-popup-dialog": "^0.11.46",
    "react-native-scrollable-tab-view": "^0.10.0",
    "react-native-sha256": "^1.1.1",
    "react-native-simple-dialogs": "^0.4.1",
    "react-native-snackbar": "^0.5.1",
    "react-native-stars": "^1.1.4",
    "react-native-svg": "^6.3.1",
    "react-native-swiper": "^1.5.13",
    "react-native-swiper-flatlist": "^1.0.7",
    "react-native-tab-view": "0.0.77",
    "react-native-uuid-generator": "^4.0.1",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.18.2",
    "react-navigation-transitions": "^1.0.5",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.3",
    "react-native-debugger-open": "^0.3.17",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by kashifaliquazi** [comment]
Hi 

Instead of migrating our project to .59(As we had written very less native code) we created the new fresh project on .59 and migrated all of our code to it.
Every thing seems to work fine expect react-native link command.
we are facing exactly the same issue
whenever we run react-native link command.

Also @SilverFoxA have you solved it.

Any help would be appreciable.
Thanks,

**Comment by SilverFoxA** [comment]
@kashifaliquazi Hello,

We had to delete the `android` and `ios` directory and eject them using the react-native command. After doing so re-configured the services like facebook, google

Hope that helps

**Comment by waqaramjad** [comment]
is there any other way if we not want to upgrade react version ?
