### ISSUE TITLE
Loading dependency graph...jest-haste-map: Haste module naming collision

### ISSUE THREAD

**Issue by deepakgupta7403** [facebook/react-native#26229]
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-3340 CPU @ 3.10GHz
    Memory: 838.14 MB / 7.68 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

Hello Dev's
m new to React Native
i m using react-native CLI not expo
When i hit the **npm start** on the terminal, am getting the error 

**Error Start From below**

Loading dependency graph...jest-haste-map: Haste module naming collision: HelloWorld
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/package.json
    * <rootDir>/node_modules/react-native/template/package.json

Failed to construct transformer:  { Error: Duplicated files or mocks. Please check the console for more info
    at setModule (/home/deepak/ReactNativeProject/HelloWorld/node_modules/jest-haste-map/build/index.js:620:17)
    at workerReply (/home/deepak/ReactNativeProject/HelloWorld/node_modules/jest-haste-map/build/index.js:691:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  mockPath1: 'package.json',
  mockPath2: 'node_modules/react-native/template/package.json' }
(node:30995) UnhandledPromiseRejectionWarning: Error: Duplicated files or mocks. Please check the console for more info
    at setModule (/home/deepak/ReactNativeProject/HelloWorld/node_modules/jest-haste-map/build/index.js:620:17)
    at workerReply (/home/deepak/ReactNativeProject/HelloWorld/node_modules/jest-haste-map/build/index.js:691:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:30995) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30995) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Error End Here**
i try many solutuion but didnt work for me 
Please help me

**Comment by deepakgupta7403** [comment]
> I had this error, it was cause by bad Pod imports syntax. I fixed it by running a fresh new react-native project and copying the correct syntax from their clean Podfile for the pods I was using.

Where i found the Syntax and what i do
