### ISSUE TITLE
Build Failed in react native 0.60

### ISSUE THREAD

**Issue by ashish76** [facebook/react-native#26220]
Hi

I have migrated my application to RN 0.57 to RN 0.60. I have made the changes according to the Upgrade Helper document. 
When I issue a command react-native run-android, the build gets failed due to react-native-contacts
Below are the output 
`warn Your project is using deprecated "rnpm" config that will stop working from next release. Please use a "react-native.config.js" file to configure the React Native CLI. Migration guide: https://github.com/react-native-community/cli/blob/master/docs/configuration.md
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-fetch-blob: https://github.com/wkh237/react-native-fetch-blob#readme
  - realm: https://realm.io
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-shared-preferences (to unlink run: "react-native unlink react-native-shared-preferences")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1214 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
info Installing the app...

> Configure project :app
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Configure project :react-native-fetch-blob
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.4.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Configure project :react-native-geocoder
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (25.0.2) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.4.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Configure project :react-native-shared-preferences
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Task :react-native-share:processDebugManifest
/Users/iffort/Documents/work_related/Projects/Wanteedo/Code/wanteedo-mobile/node_modules/react-native-share/android/src/main/AndroidManifest.xml:8:9-18:20 Warning:
        provider#cl.json.RNShareFileProvider@android:authorities was tagged at AndroidManifest.xml:8 to replace other declarations but no other declaration present
/Users/iffort/Documents/work_related/Projects/Wanteedo/Code/wanteedo-mobile/node_modules/react-native-share/android/src/main/AndroidManifest.xml:14:13-17:52 Warning:
        meta-data#android.support.FILE_PROVIDER_PATHS@android:resource was tagged at AndroidManifest.xml:14 to replace other declarations but no other declaration present

> Task :app:processDebugGoogleServices
Parsing json file: /Users/iffort/Documents/work_related/Projects/Wanteedo/Code/wanteedo-mobile/android/app/google-services.json

> Task :react-native-camera:compileGeneralDebugJavaWithJavac

> Task :react-native-contacts:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
65 actionable tasks: 61 executed, 4 up-to-date
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/iffort/Documents/work_related/Projects/Wanteedo/Code/wanteedo-mobile/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/Camera2.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
/Users/iffort/Documents/work_related/Projects/Wanteedo/Code/wanteedo-mobile/node_modules/react-native-contacts/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java:50: error: ContactsManager is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
public class ContactsManager extends ReactContextBaseJavaModule implements ActivityEventListener {
       ^
/Users/iffort/Documents/work_related/Projects/Wanteedo/Code/wanteedo-mobile/node_modules/react-native-contacts/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java:1053: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/iffort/Documents/work_related/Projects/Wanteedo/Code/wanteedo-mobile/node_modules/react-native-contacts/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java:1099: error: method does not override or implement a method from a supertype
    @Override
    ^
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-contacts:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 22s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/iffort/Documents/work_related/Projects/Wanteedo/Code/wanteedo-mobile/node_modules/react-native-camera/android/src/main/java/com/google/android/cameraview/Camera2.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
/Users/iffort/Documents/work_related/Projects/Wanteedo/Code/wanteedo-mobile/node_modules/react-native-contacts/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java:50: error: ContactsManager is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
public class ContactsManager extends ReactContextBaseJavaModule implements ActivityEventListener {
       ^
/Users/iffort/Documents/work_related/Projects/Wanteedo/Code/wanteedo-mobile/node_modules/react-native-contacts/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java:1053: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/iffort/Documents/work_related/Projects/Wanteedo/Code/wanteedo-mobile/node_modules/react-native-contacts/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java:1099: error: method does not override or implement a method from a supertype
    @Override
    ^
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-contacts:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 22s

    at checkExecSyncError (child_process.js:611:11)
    at execFileSync (child_process.js:629:13)
    at runOnAllDevices (/Users/iffort/Documents/work_related/Projects/Wanteedo/Code/wanteedo-mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:74:39)
    at buildAndRun (/Users/iffort/Documents/work_related/Projects/Wanteedo/Code/wanteedo-mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at then.result (/Users/iffort/Documents/work_related/Projects/Wanteedo/Code/wanteedo-mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

I am struggling with this issue from the last 2 days. Any help will be highly appreciated.

**package.json**

`{
  "name": "Wanteedo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "amazon-cognito-identity-js": "^3.0.15",
    "aws-amplify": "^1.1.36",
    "aws-amplify-react-native": "^2.1.16",
    "aws-appsync": "^1.8.1",
    "buffer": "^5.4.0",
    "core-js": "^3.2.1",
    "graphql-tag": "^2.10.1",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "native-base": "^2.13.5",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-animatable": "^1.3.2",
    "react-native-app-intro-slider": "^3.0.0",
    "react-native-cached-image": "^1.4.3",
    "react-native-camera": "^3.3.0",
    "react-native-check-box": "^2.1.7",
    "react-native-contacts": "^5.0.2",
    "react-native-crypto-js": "^1.0.0",
    "react-native-dash": "0.0.9",
    "react-native-device-info": "^2.3.2",
    "react-native-elements": "^1.1.0",
    "react-native-extended-stylesheet": "^0.12.0",
    "react-native-fast-image": "^7.0.2",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-fs": "^2.14.1",
    "react-native-geocoder": "^0.5.0",
    "react-native-geolocation-service": "^3.0.0",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-image-picker": "^1.0.2",
    "react-native-loading-spinner-overlay": "^1.0.1",
    "react-native-modest-checkbox": "^3.3.0",
    "react-native-popup-menu": "^0.15.6",
    "react-native-progress-bar-animated": "^1.0.6",
    "react-native-reanimated": "^1.2.0",
    "react-native-responsive-fontsize": "^0.2.1",
    "react-native-responsive-screen": "^1.2.2",
    "react-native-router-flux": "^4.0.6",
    "react-native-select-multiple": "^2.0.0",
    "react-native-share": "^2.0.0",
    "react-native-shared-preferences": "^1.0.1",
    "react-native-simple-accordian": "^1.0.2",
    "react-native-simple-events": "^1.0.1",
    "react-native-simple-radio-button": "^2.7.3",
    "react-native-smooth-pincode-input": "^1.0.7",
    "react-native-svg": "^9.7.0",
    "react-native-svg-uri": "^1.2.3",
    "react-native-swipeout": "^2.3.6",
    "react-native-tab-view": "^2.10.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-viewport-units": "0.0.5",
    "react-navigation": "^3.12.0",
    "realm": "^2.29.2",
    "rn-round-checkbox": "^0.3.4",
    "rn-viewpager": "^1.2.9",
    "toggle-switch-react-native": "^2.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.8.0",
    "eslint": "^6.1.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.8.6"
  },
  "rnpm": {
    "assets": [
      "./assests/fonts/"
    ]
  },
  "jest": {
    "preset": "react-native"
  }
}
`
**android\app\build.gradle**
apply plugin: "com.android.application"
apply plugin: 'com.google.gms.google-services'

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // https://facebook.github.io/react-native/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js",
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'
/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.wanteedo"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 10
        versionName "1.0"
        missingDimensionStrategy 'react-native-camera', 'general'
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
        // applicationVariants are e.g. debug, release
        applicationVariants.all { variant ->
            variant.outputs.each { output ->
                // For each separate APK per architecture, set a unique version code as described here:
                // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
                def versionCodes = ["armeabi-v7a":1, "x86":2]
                def abi = output.getFilter(OutputFile.ABI)
                if (abi != null) {  // null for the universal-debug, universal-release variants
                    output.versionCodeOverride =
                            versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
                }
            }
        }
        packagingOptions {
            pickFirst '**/armeabi-v7a/libc++_shared.so'
            pickFirst '**/x86/libc++_shared.so'
            pickFirst '**/arm64-v8a/libc++_shared.so'
            pickFirst '**/x86_64/libc++_shared.so'
            pickFirst '**/x86/libjsc.so'
            pickFirst '**/armeabi-v7a/libjsc.so'
        }
    }
    
}

dependencies {
    
    def supportLibMajorVersion = supportLibVersion.split('\\.')[0] as int
    def appCompatLibName =  (supportLibMajorVersion < 20) ? "androidx.appcompat:appcompat" : "com.android.support:appcompat-v7"

    implementation "$appCompatLibName:$supportLibVersion"

    //compile project(":react-native-shared-preferences")
    implementation fileTree(dir: "libs", include: ["*.jar"])
    
    implementation ('com.facebook.react:react-native:+'){
        exclude group: 'com.android.support'
    }  // From node_modules

    implementation project(':react-native-shared-preferences') 

    //implementation "com.android.support:appcompat-v7:${safeExtGet('supportLibVersion', '28.0.0')}"

    if (enableHermes) {
      def hermesPath = "../../node_modules/hermesvm/android/";
      debugImplementation files(hermesPath + "hermes-debug.aar")
      releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
      implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

android\build.gradle
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "11.6.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1'
        classpath 'com.google.gms:google-services:4.2.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url '$rootDir/../node_modules/react-native/android'
        }
        maven {            
            // Android JSC is installed from npm
            url('$rootDir/../node_modules/jsc-android/dist')
        }
        maven {
            url 'https://maven.google.com'
        }
    }
}
`
**gradle.properties**
`android.useAndroidX=true
android.enableJetifier=true`

**settings.gradle**
`rootProject.name = 'Wanteedo'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')
include ':react-native-geocoder', ':app'
project(':react-native-geocoder').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-geocoder/android')
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')
include ':react-native-shared-preferences', ':app'
project(':react-native-shared-preferences').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-shared-preferences/android')
include ':react-native-contacts', ':app'
project(':react-native-contacts').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-contacts/android')

include ':app'`

**Comment by hernanbruno97** [comment]
i have same issue

**Comment by LAITONEN** [comment]
Ok, I got it. Had issues setting-up a new project after not using React-Native for a lot of time.

My system:

macOS High Sierra 10.13.6
XCode 9.4
Had to reinstall the project in order to use the installation guide from version 0.59.0, because the installation guide from 0.61 uses approach with npx react-native ..., which disallows the usage of react-native below 0.60 (quite totalitarian). 0.59.0 was still using the global version of react-native installed through npm.

In other words:
Reinstall the project by removing the old one and use the steps mentioned in the "Getting Started" guide of React-Native 0.59.0 (or any other version compatible with your version of OS and XCode) to install your project again. No need to delete any build or node_modules or installing pods again and so forth, just pick the version of React-Native compatible with your macOS and Xcode (by downgrading and reinstalling the project until you get it) and no need to upgrade to the latest versions, they are developed for the latest systems, if you don't want to buy the latest devices to support the latest software (OS) or you can't afford them, just stay with the old ones - it's totally fine :)
