### ISSUE TITLE
Couldn't find DSO to load: libhermes.so

### ISSUE THREAD

**Issue by AlessioCamm** [facebook/react-native#26244]
I try to launch my app but she stop instantly on my phone (or emulator). I recently update **React Native** to **0.60.5**, and now this appear on _Android Studio_ :

`2019-08-28 17:15:04.204 2307-2389/com.test E/SoLoader: couldn't find DSO to load: libhermes.so`
`--------- beginning of crash`
`2019-08-28 17:15:04.205 2307-2389/com.test E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.test, PID: 2307
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:27)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:949)
        at java.lang.Thread.run(Thread.java:764)`

I work with React Native but I launch Android Studio to find more error. I try a lot of things I found on the web but it still not work. Someone as a solution ? Sorry for my bad English.

**Comment by praveenkumarr88** [comment]
Did u solved the issue??
i got the exact same issue. please provide solution

**Comment by daidaishuiping** [comment]
Did u solved the issue??
i got the exact same issue.

**Comment by zhubinsheng** [comment]
这个问题无法被社区解决啊？
