### ISSUE TITLE
UIManager.showPopupMenu crash in android 4.4 (sdk 19)

### ISSUE THREAD

**Issue by cassioseffrin** [facebook/react-native#26270]
I found an issue with android UIManager.showPopupMenu in android 4.4 (sdk 19) using RN above version 0.60 

For RN 0.59 and below the popup menu work in android 4.4 sdk19. In  RN0.60 and above this crash in android 4.4 happen  in class NativeViewHierachyManage.java line 853, there is a cast issue the class androidx.appcompat.widget.TintContextWrapper cannot be cast to com.facebook.react.uimanager.ThemedReactContext.

```
/**
@return Themed React context for view with a given {@param reactTag} - it gets the
context directly from the view using {@link View#getContext}.
*/
private ThemedReactContext getReactContextForView(int reactTag) {
View view = mTagsToViews.get(reactTag);
if (view == null) {
throw new JSApplicationIllegalArgumentException("Could not find view with tag " + reactTag);
}
return (ThemedReactContext) view.getContext(); // here  
}
```

React Native version:
```
info Fetching system and libraries information...
 
  Binaries:
    Node: 11.10.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3
      System Images: android-19 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-alert-async: 1.0.3
    react-native-clean-project: 3.2.4
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native-html-to-pdf: 0.8.0
    react-native-navigation: 2.16.0
    react-native-rename: 2.4.1
    react-native-share: 1.1.3
```

## Steps To Reproduce

Class PopupMenu.js
```
import React, { Component } from 'react';
import { View, UIManager, findNodeHandle, TouchableOpacity, Text } from 'react-native';

class PopupMenu extends Component {
	constructor(props) {
		super(props);
	}
	handleShowPopupError = () => {};
	handleMenuPress = () => {
		const { actions, onPress } = this.props;
		UIManager.showPopupMenu(findNodeHandle(this.refs.menu), actions, this.handleShowPopupError, onPress);
	};

	render() {
		return (
			<View>
				{this.props.children}
				<TouchableOpacity onPress={this.handleMenuPress}>
					<Text ref="menu">test</Text>
				</TouchableOpacity>
			</View>
		);
	}
}
export default PopupMenu;

```

Class App.js
```
 import React, { Component } from 'react';
import { StyleSheet, Text, View, requireNativeComponent } from 'react-native';
import PopupMenu from './PopupMenu';
export default class App extends Component {
	constructor(props) {
		super(props);
	}

	render() {
		return (
			<View style={styles.container}>
				<PopupMenu
					actions={[ '1', '2' ]}
					onPress={() => {
						console.log('pressed');
					}}
				>
					<Text>ITEM DO MENU</Text>
				</PopupMenu>
			</View>
		);
	}
}

const styles = StyleSheet.create({
	container: { flex: 1, backgroundColor: '#F5FCFF' },
	top: { flex: 1, alignItems: 'center', justifyContent: 'center' },
	bottom: { flex: 1, alignItems: 'center', justifyContent: 'center' }
});

```

adb logcat *:E
```
E/unknown:ReactNative( 2213): Exception in native call
E/unknown:ReactNative( 2213): java.lang.ClassCastException: androidx.appcompat.widget.TintContextWrapper cannot be cast to com.facebook.react.uimanager.ThemedReactContext
E/unknown:ReactNative( 2213): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.getReactContextForView(NativeViewHierarchyManager.java:853)
E/unknown:ReactNative( 2213): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.showPopupMenu(NativeViewHierarchyManager.java:792)
E/unknown:ReactNative( 2213): 	at com.facebook.react.uimanager.UIViewOperationQueue$ShowPopupMenuOperation.execute(UIViewOperationQueue.java:334)
E/unknown:ReactNative( 2213): 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:844)
E/unknown:ReactNative( 2213): 	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:952)
E/unknown:ReactNative( 2213): 	at com.facebook.react.uimanager.UIViewOperationQueue.access$2200(UIViewOperationQueue.java:44)
E/unknown:ReactNative( 2213): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1012)
E/unknown:ReactNative( 2213): 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
E/unknown:ReactNative( 2213): 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:172)
E/unknown:ReactNative( 2213): 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
E/unknown:ReactNative( 2213): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:759)
E/unknown:ReactNative( 2213): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
E/unknown:ReactNative( 2213): 	at android.view.Choreographer.doFrame(Choreographer.java:543)
E/unknown:ReactNative( 2213): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
E/unknown:ReactNative( 2213): 	at android.os.Handler.handleCallback(Handler.java:733)
E/unknown:ReactNative( 2213): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/unknown:ReactNative( 2213): 	at android.os.Looper.loop(Looper.java:136)
E/unknown:ReactNative( 2213): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/unknown:ReactNative( 2213): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/unknown:ReactNative( 2213): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/unknown:ReactNative( 2213): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/unknown:ReactNative( 2213): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/unknown:ReactNative( 2213): 	at dalvik.system.NativeStart.main(Native Method)
E/EGL_emulation( 2213): tid 2213: eglSurfaceAttrib(1199): error 0x3009 (EGL_BAD_MATCH)

```

 
Describe what you expected to happen:

The popup menu must to work like in RN older then 0.60

**Comment by joaosilvamaestro** [comment]
Any update?

**Comment by cassioseffrin** [comment]
I Have solved my issue updating the component as follow (little tricky however works):

PopupMenu.js
```
import React, { Component } from 'react';
import { View, UIManager, findNodeHandle, TouchableOpacity, Text } from 'react-native';

class PopupMenu extends Component {
	constructor(props) {
		super(props);
	}
	handleShowPopupError = () => {};
	handleMenuPress = () => {
		const { actions, onPress } = this.props;
		UIManager.showPopupMenu(findNodeHandle(this.menu), actions, this.handleShowPopupError, onPress);
	};

	render() {
		return (
			<View>
				<TouchableOpacity onPress={this.handleMenuPress}>{this.props.children}</TouchableOpacity>
				<View
					ref={(c) => (this.menu = c)}
					style={{
						backgroundColor: 'transparent',
						width: 1,
						height: 1,
						marginBottom: 10
					}}
				/>
			</View>
		);
	}
}
export default PopupMenu;


```


App.js

```
import React, { Component } from 'react';
import { StyleSheet, Text, View, requireNativeComponent } from 'react-native';
import PopupMenu from './PopupMenu';
export default class App extends Component {
	constructor(props) {
		super(props);
	}

	render() {
		return (
			<View style={styles.container}>
				<PopupMenu
					actions={[ '1', '2' ]}
					onPress={() => {
						console.log('pressed');
					}}
				>
					<Text>ITEM DO MENU</Text>
				</PopupMenu>
				<PopupMenu
					actions={[ '1', '2' ]}
					onPress={() => {
						console.log('pressed');
					}}
				>
					<Text>ITEM DO MENU2</Text>
				</PopupMenu>
				<PopupMenu
					actions={[ '1', '2' ]}
					onPress={() => {
						console.log('pressed');
					}}
				>
					<Text>ITEM DO MENU3</Text>
				</PopupMenu>
			</View>
		);
	}
}

const styles = StyleSheet.create({
	container: { flex: 1, backgroundColor: '#F5FCFF' },
	top: { flex: 1, alignItems: 'center', justifyContent: 'center' },
	bottom: { flex: 1, alignItems: 'center', justifyContent: 'center' }
});

```

**Comment by cassioseffrin** [comment]
PS: In RN 61+ it's possible to dismiss the popup with: UIManager.dismissPopupMenu();

**Comment by rassemdev** [comment]
@cassioseffrin thanks for sharing this code. But can you explain how should we trigger some event based on what user pressed from that popup menu! I mean the popup menu will contain 2 button (from your example: 1 and 2), right! i want to trigger one event when user pressed 1 and another if user pressed 2.
