### ISSUE TITLE
ClassCastException: com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by Ilario17** [facebook/react-native#26306]
After migrating the project to AndroidX the app shows me this error at startup.

I have no clues about where to look for this error, I also tried to load an initial blank page to eliminate all the possible code written by me, but the problem persists.

This error only appears on Android (tested on Android 5.1 and 6.0), everything works correctly on iOS

React Native version:
0.59.10

```
E/unknown:ReactNative: Exception in native call
    java.lang.ClassCastException: com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String
        at com.facebook.react.bridge.ReadableNativeArray.getString(ReadableNativeArray.java:135)
        at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:73)
        at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:69)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:359)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:194)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by dulmandakh** [comment]
RN 0.60 migrated to AndroidX, could you please try to upgrade to it, and check if it works?

**Comment by Ilario17** [comment]
@dulmandakh there are no other solutions to try first? I'm afraid of making the situation worse, given the breaking changes introduced

**Comment by bartolkaruza** [comment]
AndroidX is not supported by React Native < 0.60 so you will probably run into all kinds of hard to debug issues if you try to run older versions of RN on AndroidX. I recommend upgrading.

**Comment by clementinoux** [comment]
Hey everyone @Ilario17  @bartolkaruza @dulmandakh ! I just upgraded to RN 0.60 and migrated to AndroidX. Then, I experience the same error. For the record, I haven't been able to get my project to work since the migration. Thanks if you've any clue !

**Comment by Ilario17** [comment]
Hi @clementinoux after hours of testing I discovered that the error comes from an incompatible library, in my case the library is `react-native-default-preference`.

If I comment on the snippet in which I use this lib the error disappears
