### ISSUE TITLE
After installing react-navigation4.x, the app starts to crash.

### ISSUE THREAD

**Issue by haiya6** [facebook/react-native#26361]
# React Native version: **0.60.5**

## React Native info
```
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 6.59 GB / 15.89 GB
  Binaries:
    Node: 10.16.3 - D:\nodejs\node.EXE
    Yarn: 1.12.3 - C:\Users\55202\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - D:\nodejs\npm.CMD
```

## Steps To Reproduce

1. `react-native init ...`，then install `react-navigation`(4.x).
2. Run `react-native run-android` , app crash.
3. It works fine when react-navigation is not installed.

## Logcat
```
2019-09-06 22:15:40.882 7563-7614/com.rnapp2 E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
2019-09-06 22:15:40.883 7563-7614/com.rnapp2 E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
2019-09-06 22:15:45.470 7563-7621/com.rnapp2 E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.rnapp2, PID: 7563
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/swiperefreshlayout/widget/SwipeRefreshLayout;
        at com.facebook.react.shell.MainReactPackage.createViewManagers(MainReactPackage.java:339)
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:775)
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:187)
        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:155)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:123)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:111)
        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:189)
        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:154)
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:429)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:38)
        at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1049)
        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1008)
        at com.facebook.react.ReactInstanceManager.access$1300(ReactInstanceManager.java:124)
        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:969)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:193)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.swiperefreshlayout.widget.SwipeRefreshLayout" on path: DexPathList[[zip file "/data/app/com.rnapp2-OiaYdQt86VxDmsm1G4OQrA==/base.apk"],nativeLibraryDirectories=[/data/app/com.rnapp2-OiaYdQt86VxDmsm1G4OQrA==/lib/x86, /data/app/com.rnapp2-OiaYdQt86VxDmsm1G4OQrA==/base.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.facebook.react.shell.MainReactPackage.createViewManagers(MainReactPackage.java:339) 
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:775) 
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:187) 
        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:155) 
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:123) 
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:111) 
        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:189) 
        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:154) 
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148) 
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:429) 
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:38) 
        at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1049) 
        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1008) 
        at com.facebook.react.ReactInstanceManager.access$1300(ReactInstanceManager.java:124) 
        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:969) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
        at android.os.Looper.loop(Looper.java:193) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by fabalcu97** [comment]
You should see [this](https://github.com/react-navigation/react-navigation/issues/6267)

**Comment by haiya6** [comment]
> You should see [this](https://github.com/react-navigation/react-navigation/issues/6267)
Thank you very much！
