### ISSUE TITLE
 [0.60.5] [With Hermes Engine]gradlew bundleRelease -> Process 'command 'cmd'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by franznkemaka** [facebook/react-native#26476]
I am getting an error as

`
P:\ReactNative\Projects\MyApp\android\app>undefined:1
var __BUNDLE_START_TIME__=this.nativePerformanceNow?nativePerformanceNow():Date.now(),__DEV__=false,process=this.process||{};process.env=process.env||{};process.env.NODE_ENV=process.env.NODE_ENV||"production";
^

SyntaxError: Unexpected token v in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (P:\ReactNative\Projects\MyApp\node_modules\react-native\scripts\compose-source-maps.js:33:34)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:308:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:878:3)

> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* Where:
Script 'P:\ReactNative\Projects\MyApp\node_modules\react-native\react.gradle' line: 166

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1`

React Native version: 0.60.5

System:
    OS: Windows 10

## Steps To Reproduce

1. Create react native project 
2. run react-native run-android --variant=release

Describe what you expected to happen:

I expected to have an aab file. The debug app works very well it is only the release version.

**Comment by franznkemaka** [comment]
Hi developers,
I'm closing this issue not because it is really solved but simply because  I was able to make an app release with **hermes engine not enabled** . Maybe there is a bug, but for the moment I see no necessity with the issue since **react-native 0.61** might solve it.
Thanks
