### ISSUE TITLE
[init] Error during init on Mac - No .xcodeproj file created

### ISSUE THREAD

**Issue by kilometers** [facebook/react-native#2659]
Fails during `node-gyp rebuild` -- Python is installed and appears to be working properly. `npm install -g node-gyp` causes no errors. Using Mac OS X Yosemite.

----------------------------
```
$ react-native init test
This will walk you through creating a new React Native project in /Users/david/Documents/Game/Tests/test
-
> bufferutil@1.1.0 install /Users/david/Documents/Game/Tests/test/node_modules/react-native/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: connect ECONNREFUSED
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/david/Documents/Game/Tests/test/node_modules/react-native/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
 
> utf-8-validate@1.1.0 install /Users/david/Documents/Game/Tests/test/node_modules/react-native/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: connect ECONNREFUSED
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/david/Documents/ Game/Tests/test/node_modules/react-native/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing bufferutil@1.1.0
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
|
> fsevents@0.3.8 install /Users/david/Documents/Game/Tests/test/node_modules/react-native/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: connect ECONNREFUSED
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/david/Documents/Game/Tests/test/node_modules/react-native/node_modules/babel/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.3.8

.
.
.
```

**Comment by kilometers** [comment]
The initialization completes, but there is no .xcodeproj file.

**Comment by brentvatne** [comment]
It seems like there must be a problem with your internet connection or firewall, does `npm install` work for you at all?

**Comment by ide** [comment]
It looks like you are using Node 0.12. Can you try 2.x (or 4.0 with react-native@master)?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/init-error-during-init-on-mac-no-xcodeproj-file-created

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix. We rely on the community to provide
bugfixes as the core team is heavily focused working on performance.
