### ISSUE TITLE
Debug not working

### ISSUE THREAD

**Issue by elkinjosetm** [facebook/react-native#26659]
As soon as I turn on the debug mode on the app, the server crash right away.

Result
```
node_modules/metro/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:177
    if (this instanceof ReadStream)
             ^

RangeError: Maximum call stack size exceeded
    at Function.[Symbol.hasInstance] (<anonymous>)
    at ReadStream (node_modules/metro/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:177:14)
    at ReadStream (node_modules/metro/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:178:28)
    at ReadStream (node_modules/metro/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:178:28)
    at ReadStream (node_modules/metro/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:178:28)
    at ReadStream (node_modules/metro/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:178:28)
    at ReadStream (node_modules/metro/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:178:28)
    at ReadStream (node_modules/metro/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:178:28)
    at ReadStream (node_modules/metro/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:178:28)
    at ReadStream (node_modules/metro/node_modules/jsonfile/node_modules/graceful-fs/graceful-fs.js:178:28)
error Command failed with exit code 1.
```

React Native version:
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 176.78 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 29
      Build Tools: 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.1 => 0.61.1
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-rename: 2.4.1
```

## Steps To Reproduce

1. Open developer menu
2. Turn on **Debug** mode
3. Server crashes right away

**Comment by alexfoxy** [comment]
I also have this issue when I refresh the app, when debugger is enabled.

**Comment by nysamnang** [comment]
+1

**Comment by nysamnang** [comment]
@elkinjosetm Did you solve this problem yet?

**Comment by nysamnang** [comment]
After spending a couple of hours, I resolved my issue by:

- Delete `node_modules` , `yarn.lock`, `package.lock.json`

- Run `yarn` to re-install node_modules

- Run `watchman watch-del-all && rm -rf /tmp/metro-bundler-cache-* && rm -rf /tmp/haste-map-react-native-packager-*` to clear cache

- Re-build project and Turn on debug mode again. Then it worked!

**Comment by kelset** [comment]
It really looks like something related to caches: I can't repro locally, sorry. If you manage to create a more reliable repro we can reopen it, if not I would recommend what @nysamnang mentioned above.

**Comment by elkinjosetm** [comment]
> After spending a couple of hours, I resolved my issue by:
> 
> * Delete `node_modules` , `yarn.lock`, `package.lock.json`
> * Run `yarn` to re-install node_modules
> * Run `watchman watch-del-all && rm -rf /tmp/metro-bundler-cache-* && rm -rf /tmp/haste-map-react-native-packager-*` to clear cache
> * Re-build project and Turn on debug mode again. Then it worked!

Thanks, this worked!

> It really looks like something related to caches: I can't repro locally, sorry. If you manage to create a more reliable repro we can reopen it, if not I would recommend what @nysamnang mentioned above.

It's ok, that's all I needed to do, thanks!
