### ISSUE TITLE
App Crash when swipe from left to right(react native swiper)-After updated to 60.5 version

### ISSUE THREAD

**Issue by Murugeshrockey-RN** [facebook/react-native#26718]
E/ReactNativeJS: Can't find variable: _this
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.unlimited_movies_in_com, PID: 13264
    com.facebook.react.common.JavascriptException: Can't find variable: _this, stack:
    onMomentumScrollEnd@255:7008

Thanks in Advance.

**Comment by Murugeshrockey-RN** [comment]
E/ReactNativeJS: Can't find variable: _this
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.unlimited_movies_in_com, PID: 13264
    com.facebook.react.common.JavascriptException: Can't find variable: _this, stack:
    onMomentumScrollEnd@255:7008
    E@82:1233
    z@82:1376
    U@82:1430
    D@82:1721
    H@82:2497
    j@82:2312
    <unknown>@82:13831
    Ue@82:81479
    Me@82:13499
    Fe@82:13672
    receiveEvent@82:14058
    value@23:3518
    <unknown>@23:822
    value@23:2772
    value@23:794
    value@-1
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:193)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)
