### ISSUE TITLE
[android] [yosemite] EMFILE, too many open files

### ISSUE THREAD

**Issue by adelnizamutdinov** [facebook/react-native#2689]
Hello, running `react-native run-android` yields this error.
Setting `ulimit -n 65536` (which is maximum) does not help
What may I be doing wrong?

Full error log:
```
React packager ready.

[00:25:23] <START> Building Dependency Graph
[00:25:23] <START> Crawling File System
 ERROR  watch EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"watch"}
Error: watch EMFILE
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at NodeWatcher.watchdir (/Users/adelnizamutdinov/Projects/HelloAndroid/node_modules/react-native/node_modules/sane/src/node_watcher.js:144:20)
    at Walker.<anonymous> (/Users/adelnizamutdinov/Projects/HelloAndroid/node_modules/react-native/node_modules/sane/src/node_watcher.js:351:12)
    at Walker.emit (events.js:110:17)
    at /Users/adelnizamutdinov/Projects/HelloAndroid/node_modules/react-native/node_modules/sane/node_modules/walker/lib/walker.js:69:16
    at /Users/adelnizamutdinov/Projects/HelloAndroid/node_modules/react-native/node_modules/graceful-fs/graceful-fs.js:140:16
    at FSReqWrap.oncomplete (fs.js:95:15)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
fs.js:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
Error: EMFILE, too many open files '/Users/adelnizamutdinov/.babel.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at process.save (/Users/adelnizamutdinov/Projects/HelloAndroid/node_modules/react-native/node_modules/babel-core/lib/api/register/cache.js:35:19)
    at process.emit (events.js:107:17)
    at process.exit (node.js:600:17)
    at process.<anonymous> (/Users/adelnizamutdinov/Projects/HelloAndroid/node_modules/react-native/packager/packager.js:151:11)
    at process.emit (events.js:107:17)
    at process._fatalException (node.js:236:26)
    at Walker.<anonymous> (/Users/adelnizamutdinov/Projects/HelloAndroid/node_modules/react-native/node_modules/sane/src/node_watcher.js:351:12)
Process terminated. Press <enter> to close the window
```

**Comment by ide** [comment]
Try installing watchman.

**Comment by adelnizamutdinov** [comment]
I somehow missed that part in the tutorial
`brew install watchman` did the job, thanks!
