### ISSUE TITLE
React Native Failed for iOS Build 

### ISSUE THREAD

**Issue by techinn** [facebook/react-native#26989]
Build gone successful and load the iOS Launcher Page but after that when it loads react-native following errors start coming. 

Failed to construct transformer:  { DuplicateError: Duplicated files or mocks. Please check the console for more info
    at setModule (/Users/MQ/pinnacle/node_modules/jest-haste-map/build/index.js:620:17)
    at workerReply (/Users/MQ/pinnacle/node_modules/jest-haste-map/build/index.js:691:9)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  mockPath1:
   'node_modules/react-native/ReactCommon/hermes/inspector/tools/msggen/package.json',
  mockPath2:
   'pinnacle/node_modules/react-native/ReactCommon/hermes/inspector/tools/msggen/package.json' }
(node:79696) UnhandledPromiseRejectionWarning: Error: Duplicated files or mocks. Please check the console for more info
    at setModule (/Users/MQ/pinnacle/node_modules/jest-haste-map/build/index.js:620:17)
    at workerReply (/Users/MQ/pinnacle/node_modules/jest-haste-map/build/index.js:691:9)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:79696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:79696) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: Duplicated files or mocks. Please check the console for more info
    at setModule (/Users/MQ/pinnacle/node_modules/jest-haste-map/build/index.js:620:17)
    at workerReply (/Users/MQ/pinnacle/node_modules/jest-haste-map/build/index.js:691:9)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

**Comment by hramos** [comment]
Closing after several months without followup from the author. Please make sure to fill in the issue template if you decide to file a new issue.
