### ISSUE TITLE
Debug mode can be used,Release error  with Hermes

### ISSUE THREAD

**Issue by chuanhaisoft** [facebook/react-native#27040]
win server 2008 r2
 android studio 3.4.1
node 10.16.0
react naitve 0.61.2

project.ext.react = [
    entryFile: "index.js",
    enableHermes: true,  // clean and rebuild if changing
]

Debug mode can be used,Release error：
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:bundleReleaseJsAndAssets'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:148)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:145)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:138)
	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:75)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command '..\..\node_modules\hermes-engine\win64-bin\hermes''
	at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:232)
	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:209)
	at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:356)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:86)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	... 6 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not start '..\..\node_modules\hermes-engine\win64-bin\hermes'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:97)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:70)
	... 7 more
Caused by: java.io.IOException: Cannot run program "..\..\node_modules\hermes-engine\win64-bin\hermes" (in directory "G:\reactapp\android\app"): CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 11 more
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 12 more

run：G:\reactapp\android\app>..\..\node_modules\he
rmes-engine\win64-bin\hermes -emit-binary -out G:\reactapp\android\app\build\generated\assets\react\release\index.android.bun
dle.hbc G:\reactapp\android\app\build\generat
ed\assets\react\release\index.android.bundle -O -output-source-map
G:\reactapp\android\app\build\generated\asset
s\react\release\index.android.bundle:13:134: warning: the variable "Promise" was
 not declared in function "isBoldTextEnabled"
...BoldTextEnabled:function(){return Promise.resolve(!1)},isGrayscaleEnabled:...

                                     ^~~~~~~
G:\reactapp\android\app\build\generated\asset
s\react\release\index.android.bundle:25:3047: warning: the variable "DebuggerInt
ernal" was not declared in function "value 14#"
...(){return'undefined'!=typeof DebuggerInternal&&!0===DebuggerInternal.shoul...

                                ^~~~~~~~~~~~~~~~
G:\reactapp\android\app\build\generated\asset
s\react\release\index.android.bundle:92:57098: warning: the variable "setTimeout
" was not declared in function "Pi"
...console.error(n.error)}catch(e){setTimeout(function(){throw e})}}function ...

                                   ^~~~~~~~~~
G:\reactapp\android\app\build\generated\asset
s\react\release\index.android.bundle:92:83621: warning: the variable "__REACT_DE
VTOOLS_GLOBAL_HOOK__" was not declared in function "Xl"
...f("undefined"==typeof __REACT_DEVTOOLS_GLOBAL_HOOK__)return!1;var t=__REAC...

                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
G:\reactapp\android\app\build\generated\asset
s\react\release\index.android.bundle:92:22512: warning: the variable "clearTimeo
ut" was not declared in function " 205#"
...Tag,t),!1}var yt=setTimeout,bt=clearTimeout,Tt=/^(.*)[\\\/]/;function Et(e...

React Native version:

System:
    OS: Windows 7
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Memory: 9.80 GB / 15.90 GB
  Binaries:
    Node: 10.16.0 - D:\nodejs\node.EXE
    Yarn: 1.17.3 - D:\nodejs\yarn.CMD
    npm: 6.11.3 - D:\nodejs\npm.CMD
  SDKs:
    Android SDK:
      Android NDK: 20.0.5594570

## Steps To Reproduce

1.Release 

Generate apk success

**Comment by kumold** [comment]
I'm having same problem, how did you solve it?

**Comment by abouquet** [comment]
fixed in react-native 0.61.4

https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#0614

**Comment by SuhairZain** [comment]
@abouquet It seems like it's a fix for another issue, not the one OP and I are having.

**Comment by MayoudP** [comment]
I got more or less the same issue and log on ` "react-native": "0.60.5",`. 
Using Hermes in debug mode works fine, and is not building in `release mode`. 
And I'm on MacOS.

**Comment by eyale** [comment]
I had same issue. But my problem was in sorting Reducers this way
`  combineReducers(Object.fromEntries(
    Object.entries({...reducers }).sort())
`

Changed it to Ramda sorting and its fixed my issue.
Maybe look at some JS functions and unpredictable code?

I hope this advice will help you
