### ISSUE TITLE
native-test-renderer shallow properties have disappeared due to react-native after upgrade from 0.60.0-rc2 to 0.61.2

### ISSUE THREAD

**Issue by nuKs** [facebook/react-native#27042]
Environment:
[skip envinfo]

Have tested on two folders, with only difference in package.json:

```diff
<     "react-native": "0.60.0-rc.2",
---
>     "react-native": "0.61.2",
```

Both projects have been set to same react version etc.

```json
    "native-base": "2.13.8",
    "react": "16.9.0",
    "jest": "25.0.0",
    "metro-react-native-babel-preset": "0.56.0",
    "react-native-testing-library": "1.11.1",
    "react-test-renderer": "16.9.0",
```

Considering simple test such as:

```js
// Given the menu is setup.
const { queryByA11yLabel } = render(<Menu activeButton={'home'} onButtonClicked={jest.fn()} />);

// Then the Graph button should be disabled.
const button: any = queryByA11yLabel('menu-infobutton');
expect(button.props.disabled).toBeTruthy();
```

The diff between test files and relevant source files is empty.

- tests results for `"react-native": "0.60.0-rc.2"`:

```
 PASS  test-unitary/Menu.spec.js (7.796s)

Tests:       11 passed, 11 total
```

- tests results for `"react-native": "0.61.2"`:

```
 FAIL  test-unitary/Menu.spec.js
  Menu
    ✓ should not throw given correct attributes (71ms)
    ✓ should throw given incorrect attributes (26ms)
    ✓ should display the 4 buttons (27ms)
    ✕ should only highlight one button at a time (21ms)
    Home button
      ✓ should display Home button (18ms)
      ✓ should let the user click on Home button to go to Home section (30ms)
      ✕ should highlight Home button when the user is in Home section (21ms)
    Graph button
      ✓ should display Graph button (18ms)
      ✕ should disable Graph button (16ms)
    Info button
      ✓ should display Info button (24ms)
      ✕ should disable Info button (15ms)

  ● Menu › should only highlight one button at a time

    expect(received).toBeTruthy()

    Received: undefined

      81 |
      82 |         // Then the home button should be highlighted.
    > 83 |         expect(homeButton.props.active).toBeTruthy();
         |                                         ^
      84 |
      85 |         // And the other button should not.
      86 |         expect(graphsButton.props.active).toBeFalsy();

      at toBeTruthy (test-unitary/Menu.spec.js:83:41)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (node_modules/regenerator-runtime/runtime.js:135:20)
      at node_modules/regenerator-runtime/runtime.js:170:11
      at tryCallTwo (node_modules/promise/lib/core.js:45:5)
      at doResolve (node_modules/promise/lib/core.js:200:13)
      at new Promise (node_modules/promise/lib/core.js:66:3)

... (always similar error for failed test, both with xxx.props.active and xxx.props.disable (probably generalize to all props).
```

**When I log props, it only shows native-based view props in the newest react-native version, shallow ones have completely disappeared!**

```diff
1,3c1
<       { accessible: true,
<         accessibilityLabel: 'menu-homebutton',
<         style:
---
>       { style:
5,6c3,4
<            borderRadius: 5,
<            backgroundColor: '#cde1f9',
---
>            borderRadius: 2,
>            backgroundColor: '#3F51B5',
24,25c22,45
<            flex: 1,
<            opacity: 1 },
---
>            flex: 1 },
>         onPress: [Function: onPress],
>         accessibilityLabel: 'menu-homebutton',
>         vertical: true,
>         active: true,
>         badge: false,
>         children:
>          [ { '$$typeof': Symbol(react.element),
>              type: [Function],
>              key: '.1',
>              ref: null,
>              props: [Object],
>              _owner: [FiberNode],
>              _store: {} },
>            { '$$typeof': Symbol(react.element),
>              type: [Function],
>              key: '.2',
>              ref: null,
>              props: [Object],
>              _owner: [FiberNode],
>              _store: {} } ],
>         nativeBackgroundAndroid:
>          { type: 'RippleAndroid', color: 1308622847, borderless: false },
>         accessible: true,
27c47
<         focusable: true,
---
>         clickable: true,
39a60,61
>               touchableHandleFocus: [Function],
>               touchableHandleBlur: [Function],
53,59d74
<               measure: [Function],
<               measureInWindow: [Function],
<               measureLayout: [Function],
<               setNativeProps: [Function],
<               focus: [Function],
<               blur: [Function],
<               setOpacityTo: [Function],
62,63d76
<               touchableHandleFocus: [Function],
<               touchableHandleBlur: [Function],
71,73c84,86
<               _opacityActive: [Function],
<               _opacityInactive: [Function],
<               _getChildStyleOpacityWithDefault: [Function],
---
>               _handleResponderMove: [Function],
>               _dispatchHotspotUpdate: [Function],
>               _dispatchPressedStateChange: [Function],
96a110,111
>               touchableHandleFocus: [Function],
>               touchableHandleBlur: [Function],
110,116d124
<               measure: [Function],
<               measureInWindow: [Function],
<               measureLayout: [Function],
<               setNativeProps: [Function],
<               focus: [Function],
<               blur: [Function],
<               setOpacityTo: [Function],
119,120d126
<               touchableHandleFocus: [Function],
<               touchableHandleBlur: [Function],
128,130c134,136
<               _opacityActive: [Function],
<               _opacityInactive: [Function],
<               _getChildStyleOpacityWithDefault: [Function],
---
>               _handleResponderMove: [Function],
>               _dispatchHotspotUpdate: [Function],
>               _dispatchPressedStateChange: [Function],
153a160,161
>               touchableHandleFocus: [Function],
>               touchableHandleBlur: [Function],
167,173d174
<               measure: [Function],
<               measureInWindow: [Function],
<               measureLayout: [Function],
<               setNativeProps: [Function],
<               focus: [Function],
<               blur: [Function],
<               setOpacityTo: [Function],
176,177d176
<               touchableHandleFocus: [Function],
<               touchableHandleBlur: [Function],
185,187c184,186
<               _opacityActive: [Function],
<               _opacityInactive: [Function],
<               _getChildStyleOpacityWithDefault: [Function],
---
>               _handleResponderMove: [Function],
>               _dispatchHotspotUpdate: [Function],
>               _dispatchPressedStateChange: [Function],
210a210,211
>               touchableHandleFocus: [Function],
>               touchableHandleBlur: [Function],
224,230d224
<               measure: [Function],
<               measureInWindow: [Function],
<               measureLayout: [Function],
<               setNativeProps: [Function],
<               focus: [Function],
<               blur: [Function],
<               setOpacityTo: [Function],
233,234d226
<               touchableHandleFocus: [Function],
<               touchableHandleBlur: [Function],
242,244c234,236
<               _opacityActive: [Function],
<               _opacityInactive: [Function],
<               _getChildStyleOpacityWithDefault: [Function],
---
>               _handleResponderMove: [Function],
>               _dispatchHotspotUpdate: [Function],
>               _dispatchPressedStateChange: [Function],
257c249
<          { [Function: bound touchableHandleResponderMove]
---
>          { [Function: bound _handleResponderMove]
267c259,261
<               touchableHandleResponderMove: [Circular],
---
>               touchableHandleResponderMove: [Function],
>               touchableHandleFocus: [Function],
>               touchableHandleBlur: [Function],
281,287d274
<               measure: [Function],
<               measureInWindow: [Function],
<               measureLayout: [Function],
<               setNativeProps: [Function],
<               focus: [Function],
<               blur: [Function],
<               setOpacityTo: [Function],
290,291d276
<               touchableHandleFocus: [Function],
<               touchableHandleBlur: [Function],
299,301c284,286
<               _opacityActive: [Function],
<               _opacityInactive: [Function],
<               _getChildStyleOpacityWithDefault: [Function],
---
>               _handleResponderMove: [Circular],
>               _dispatchHotspotUpdate: [Function],
>               _dispatchPressedStateChange: [Function],
310c295
<            __reactBoundMethod: [Function: touchableHandleResponderMove],
---
>            __reactBoundMethod: [Function: _handleResponderMove],
324a310,311
>               touchableHandleFocus: [Function],
>               touchableHandleBlur: [Function],
338,344d324
<               measure: [Function],
<               measureInWindow: [Function],
<               measureLayout: [Function],
<               setNativeProps: [Function],
<               focus: [Function],
<               blur: [Function],
<               setOpacityTo: [Function],
347,348d326
<               touchableHandleFocus: [Function],
<               touchableHandleBlur: [Function],
356,358c334,336
<               _opacityActive: [Function],
<               _opacityInactive: [Function],
<               _getChildStyleOpacityWithDefault: [Function],
---
>               _handleResponderMove: [Function],
>               _dispatchHotspotUpdate: [Function],
>               _dispatchPressedStateChange: [Function],
381a360,361
>               touchableHandleFocus: [Function],
>               touchableHandleBlur: [Function],
395,401d374
<               measure: [Function],
<               measureInWindow: [Function],
<               measureLayout: [Function],
<               setNativeProps: [Function],
<               focus: [Function],
<               blur: [Function],
<               setOpacityTo: [Function],
404,405d376
<               touchableHandleFocus: [Function],
<               touchableHandleBlur: [Function],
413,415c384,386
<               _opacityActive: [Function],
<               _opacityInactive: [Function],
<               _getChildStyleOpacityWithDefault: [Function],
---
>               _handleResponderMove: [Function],
>               _dispatchHotspotUpdate: [Function],
>               _dispatchPressedStateChange: [Function],
426,428c397
<            bind: [Function] },
<         children: [ [ false, [Object], [Object] ], null ] }
<
---
>            bind: [Function] } }
```

**Comment by TheSavior** [comment]
Can you provide a simple repro that changed? Something that doesn't rely on external libraries? I'm not sure what `Menu` is.

It is likely that this changed due to usage of forwardRef and that the component being rendered now *is* a native component, instead of something using NativeMethodsMixin with local functions of `measure`. Now they exist on the prototype, so they don't show up in the snapshot.
