### ISSUE TITLE
[Android]  [react-native run-android] error 

### ISSUE THREAD

**Issue by WG-Com** [facebook/react-native#2708]
```sh
react-native run-android
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Downloading https://services.gradle.org/distributions/gradle-2.4-all.zip
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

```

```sh
React packager ready.

[13:45:03] <START> Building Dependency Graph
[13:45:03] <START> Crawling File System
 ERROR  watch EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"watch"}
Error: watch EMFILE
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at NodeWatcher.watchdir (/usr/local/var/lib/android-sdk/extras/intel/Hardware_Accelerated_Execution_Manager/AwesomeProject/node_modules/react-native/node_modules/sane/src/node_watcher.js:144:20)
    at Walker.<anonymous> (/usr/local/var/lib/android-sdk/extras/intel/Hardware_Accelerated_Execution_Manager/AwesomeProject/node_modules/react-native/node_modules/sane/src/node_watcher.js:351:12)
    at Walker.emit (events.js:110:17)
    at /usr/local/var/lib/android-sdk/extras/intel/Hardware_Accelerated_Execution_Manager/AwesomeProject/node_modules/react-native/node_modules/sane/node_modules/walker/lib/walker.js:69:16
    at /usr/local/var/lib/android-sdk/extras/intel/Hardware_Accelerated_Execution_Manager/AwesomeProject/node_modules/react-native/node_modules/graceful-fs/graceful-fs.js:140:16
    at FSReqWrap.oncomplete (fs.js:95:15)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
fs.js:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
Error: EMFILE, too many open files '/Users/username/.babel.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at process.save (/usr/local/var/lib/android-sdk/extras/intel/Hardware_Accelerated_Execution_Manager/AwesomeProject/node_modules/react-native/node_modules/babel-core/lib/api/register/cache.js:35:19)
    at process.emit (events.js:107:17)
    at process.exit (node.js:600:17)
    at process.<anonymous> (/usr/local/var/lib/android-sdk/extras/intel/Hardware_Accelerated_Execution_Manager/AwesomeProject/node_modules/react-native/packager/packager.js:151:11)
    at process.emit (events.js:107:17)
    at process._fatalException (node.js:236:26)
    at Walker.<anonymous> (/usr/local/var/lib/android-sdk/extras/intel/Hardware_Accelerated_Execution_Manager/AwesomeProject/node_modules/react-native/node_modules/sane/src/node_watcher.js:351:12)
Process terminated. Press <enter> to close the window

```

**Comment by brentvatne** [comment]
Make sure you have watchman installed, as per the getting started guide :smile:

**Comment by WG-Com** [comment]
3Q
