### ISSUE TITLE
[Android] Connection refused from Gradle when behind a proxy

### ISSUE THREAD

**Issue by nadeemshaik** [facebook/react-native#2726]
Well, I am getting this error when I am trying to run "react-native run-android". Seems to be a simple error but I can't figure it out a solution.

Can this be because of a proxy server (University restrictions) : Does react-native-cli accept proxy params ?

Just in case:

```
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Downloading https://services.gradle.org/distributions/gradle-2.4-all.zip

Exception in thread "main" java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:649)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1103)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:997)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1511)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:59)
	at org.gradle.wrapper.Install$1.call(Install.java:46)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:46)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Could not install the app on the device, see the error above.
```

**Comment by mkonicek** [comment]
Looks like a proxy error indeed (org.gradle.wrapper.Download.downloadInternal).

Can you change into your app's folder and run the Gradle command (`cd android && ./gradlew installDebug`) manually to get more output?

**Comment by mkonicek** [comment]
Might be related to the proxy indeed.

    Building and installing the app on the device (cd android && ./gradlew installDebug)...
    Downloading https://services.gradle.org/distributions/gradle-2.4-all.zip

Can you fetch it using your browser as well as `wget`?

**Comment by mkonicek** [comment]
The CLI doesn't accept proxy params.

**Comment by nadeemshaik** [comment]
Hey @mkonicek , I tried that, but gives the exact same error. After googling a bit more about gradle settings, just found out the solution though.I just set the following in gradle.properties in the android folder

```
systemProp.http.proxyHost=10.3.100.207
systemProp.http.proxyPort=8080

systemProp.https.proxyHost=10.3.100.207
systemProp.https.proxyPort=8080
```

**Comment by kmagiera** [comment]
great to hear you've found the solution

**Comment by dharmesh-kh24** [comment]
@nadeemshaik Thanks, I had the same issue. Fixed by setting proxy in gradle properties.

**Comment by s0nskar** [comment]
If your proxy uses authentication add these line too

```
systemProp.http.proxyUser=YOUR_USERNAME
systemProp.http.proxyPassword=YOUR_PASSWORD
```

**Comment by tassoman** [comment]
I've edited project's `android/settings.gradle` file adding systemProp.* variables, but weren't recognized. Maybe I should set them system wide? In which file? 

> Could not find property 'systemProp' on settings 'MyProjectName'.

**Comment by adrianovieira** [comment]
Can I do these proxy settings as a global settings or only by project as `<AwesomeProject>android/gradle.proprieties`?

**Comment by husainkhan** [comment]
Still not Working.
I did set the proxy and the port but still it gives the same error.

**Comment by botdotcom** [comment]
Not working for me either!

**Comment by sujitpk-perennial** [comment]
No luck for me. I am facing this problem for all projects now.

**Comment by bpatel444** [comment]
You can set the proxy to automatic and rerun the android studio and it worked for me. 

Thank you!!
