### ISSUE TITLE
Question: Build 0.55.4   stuck app:mergeDebugResources

### ISSUE THREAD

**Issue by superzhy** [facebook/react-native#27390]
new project RN V0.55.4,  run `reacft-native run-android ` building  stuck  app:mergeDebugResources

##### Android Studio `V3.5`

run `reacft-native run-android ` get:
```
myApp react-native run-android
Scanning folders for symlinks in /Users/macbook/Desktop/myApp/node_modules (28ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library
:app:prepareComAndroidSupportSupportV42301Library
:app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library
:app:prepareComFacebookFrescoDrawee130Library
:app:prepareComFacebookFrescoFbcore130Library
:app:prepareComFacebookFrescoFresco130Library
:app:prepareComFacebookFrescoImagepipeline130Library
:app:prepareComFacebookFrescoImagepipelineBase130Library
:app:prepareComFacebookFrescoImagepipelineOkhttp3130Library
:app:prepareComFacebookReactReactNative0554Library
:app:prepareComFacebookSoloaderSoloader010Library
:app:prepareOrgWebkitAndroidJscR174650Library
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:mergeDebugShaders
:app:compileDebugShaders
:app:generateDebugAssets
:app:mergeDebugAssets
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
Thread(png-cruncher_6) has a null payload
        ... 4 more
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
Thread(png-cruncher_2) has a null payload
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
Thread(png-cruncher_4) has a null payload
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
Thread(png-cruncher_8) has a null payload
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
Thread(png-cruncher_1) has a null payload
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_5) has a null payload
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_7) has a null payload
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_3) has a null payload
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_9) has a null payload
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_10) has a null payload
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_11) has a null payload
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_15) has a null payload
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_13) has a null payload
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_12) has a null payload
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_16) has a null payload
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_14) has a null payload
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_19) has a null payload
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_17) has a null payload
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_18) has a null payload
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_21) has a null payload
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_20) has a null payload
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_24) has a null payload
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_22) has a null payload
java.io.IOException: Cannot run program "/Users/macbook/Library/Android/sdk/build-tools/23.0.1/aapt": error=86, Bad CPU type in executable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.android.builder.png.AaptProcess$Builder.start(AaptProcess.java:167)
        at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:118)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 4 more
Thread(png-cruncher_23) has a null payload
Building 59% > :app:mergeDebugResources
```
Any idea on how to resolve this problem?

**Comment by zzetao** [comment]
me too
macOS 10.15.1

**Comment by k-daw2** [comment]
I think it has to do with react-native version, as I had a simple project with the latest version of rn. the project was exported successfully to the simulator. However an older, more complicated project resulted in the same error.

**Comment by zzetao** [comment]
I upgraded the gradle version to v3.5.0. it worked.
My react-native version is 0.44.2

**Comment by as27543035** [comment]
me too
macOS 10.15.2
react-native 0.48.4

**Comment by boonook** [comment]
me too
macOS 10.15.4
react-native 0.44.3

**Comment by boonook** [comment]
问题关闭了？怎么没看到解决方案呢？
