### ISSUE TITLE
NativeViewHiearchyOptimizer Assertions.assertCondition causes crash on Android

### ISSUE THREAD

**Issue by HarleyCoegil** [facebook/react-native#27511]
I have an application and I am getting crashes only on Android under some conditions.

Here is the stack trace I am getting.
Unexpected Native error java.lang.AssertionError
	at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:66)
	at com.facebook.react.uimanager.NativeViewHierarchyOptimizer.transitionLayoutOnlyViewToNativeView(NativeViewHierarchyOptimizer.java:463)
	at com.facebook.react.uimanager.NativeViewHierarchyOptimizer.handleForceViewToBeNonLayoutOnly(NativeViewHierarchyOptimizer.java:240)
	at com.facebook.react.views.text.ReactBaseTextShadowNode.spannedFromShadowNode(ReactBaseTextShadowNode.java:276)
	at com.facebook.react.views.text.ReactTextShadowNode.onBeforeLayout(ReactTextShadowNode.java:205)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:897)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(UIImplementation.java:895)
	at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(UIImplementation.java:670)
	at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:635)
	at com.facebook.react.uimanager.UIManagerModule.onBatchComplete(UIManagerModule.java:750)
	at com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete(NativeModuleRegistry.java:118)
	at com.facebook.react.bridge.CatalystInstanceImpl$BridgeCallback.onBatchComplete(CatalystInstanceImpl.java:157)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:159)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
	at java.lang.Thread.run(Thread.java:761)

## React Native version:
System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Memory: 117.51 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.16.0 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native: 0.61.5

## Steps To Reproduce

The application has a chat feature. Here is the sequence of events that cause this:
1. The user hits the home button to navigate to a different application.
2. The user receives a notification of a new message.
3. The user clicks the notification which causes the app to return to the foreground.
4. The application processes the initial notification event handler to navigate to the messages screen.
5. The messages screen renders and the exception below is thrown causing my application to crash.

The messages screen is implemented as a bunch of flat lists, one for each day. 
The crash only happens when returning to the foreground state. During regular operation, it never happens. Additionally, this happens if the message components are not a uniform size. Some messages have images that make them a different size. When coming back to a chat conversation with images is how I've reproduced the crash reliably. I thought perhaps it had to do with the asynchronous nature of loading the images, but when I replaced the images with plain <View> components that are 200 x 200, it still happens.

Describe what you expected to happen:
I didn't expect the application to crash.

Snack, code example, screenshot, or link to a repository:
TBD

**Comment by HarleyCoegil** [comment]
Upgraded to 0.61.5 - Still happening.
