### ISSUE TITLE
Unable to run react-native app in android emulator or physical device

### ISSUE THREAD

**Issue by daani786** [facebook/react-native#27587]
I followed all the documentation form https://facebook.github.io/react-native/docs/getting-started `React Native CLI Quickstart`
but got error

installed
`choco install -y nodejs.install python2 jdk8`

create project
`npx react-native init AwesomeProject`

create virtual device of `Pie API Level 28 image`

and run project
`npx react-native run-android`

and face this error, the package json is also showing in the image 

![image](https://user-images.githubusercontent.com/8912869/71304677-cb1a3300-23eb-11ea-9092-87c53c17ae01.png)

**Comment by daani786** [comment]
1. create directory  android/app/src/main/assets
2. run following command from project root directory

`$ npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`

```
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.
SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (E:\www\react_native\app2\node_modules\metro-config\src\defaults\blacklist.js:34:10)
    at getBlacklistRE (E:\www\react_native\app2\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:66:59)
    at getDefaultConfig (E:\www\react_native\app2\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:82:20)
    at load (E:\www\react_native\app2\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:118:25)
    at buildBundle (E:\www\react_native\app2\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\bundle\buildBundle.js:69:53)
    at Object.bundleWithOutput (E:\www\react_native\app2\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\bundle\bundle.js:27:35)
    at Command.handleAction (E:\www\react_native\app2\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:164:23)
    at Command.listener (E:\www\react_native\app2\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:219:5)
```

3. To resolve this error, modify the following file:-
`node_modules\metro-config\src\defaults\blacklist.js`
Replace follwing
```
var sharedBlacklist = [
  /node_modules[/\\]react[/\\]dist[/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];
```
with
```
var sharedBlacklist = [
  /node_modules[\/\\]react[\/\\]dist[\/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];
```

4. run following command from project root directory
`$ npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`
```
response
Loading dependency graph, done.
info Writing bundle output to:, android/app/src/main/assets/index.android.bundle
info Done writing bundle output
info Copying 2 asset files
info Done copying assets
```
5. now run the command
`$ npx react-native run-android`

6. Finally the output shows in emulator

![image](https://user-images.githubusercontent.com/8912869/71305064-509fe200-23f0-11ea-8a2b-597aa171f169.png)

**Comment by woodThunder** [comment]
node_modules\metro-config\src\defaults\blacklist.js What can I do without this directory
