### ISSUE TITLE
if using the latest version of react native 0.61.5,must we migrate the old project to androidx

### ISSUE THREAD

**Issue by caiyonglong** [facebook/react-native#27642]
React Native version:

## Steps To Reproduce

1.upgrade react native to 0.61.5
2.android project does not use androidx

Describe what you expected to happen:
open react native page
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxxxx.activity, PID: 18802
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/view/ViewCompat;
        at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:560)
        at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:538)
        at com.xxx.xxx.react.BaseReactNativeActivity.onResume(BaseReactNativeActivity.java:69)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
        at android.app.Activity.performResume(Activity.java:7495)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4118)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4163)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2026)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7270)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:903)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.view.ViewCompat" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.xxxxx.activity-uSbtdhEzpFON_s6WDJ9EsA==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxxxx.activity-uSbtdhEzpFON_s6WDJ9EsA==/lib/arm, /data/app/com.xxxxx.activity-uSbtdhEzpFON_s6WDJ9EsA==/base.apk!/lib/armeabi, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:560) 
        at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:538) 
        at com.xxx.xxx.react.BaseReactNativeActivity.onResume(BaseReactNativeActivity.java:69) 
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413) 
        at android.app.Activity.performResume(Activity.java:7495) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4118) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4163) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2026) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:227) 
        at android.app.ActivityThread.main(ActivityThread.java:7270) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:903) 
2019-12-31 09:05:26.158 18802-18802/com.xxxxx.activity D/>>AppException<<: crashString = java.lang.ClassNotFoundException: Didn't find class "androidx.core.view.ViewCompat" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.xxxxx.activity-uSbtdhEzpFON_s6WDJ9EsA==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxxxx.activity-uSbtdhEzpFON_s6WDJ9EsA==/lib/arm, /data/app/com.xxxxx.activity-uSbtdhEzpFON_s6WDJ9EsA==/base.apk!/lib/armeabi, /system/lib]]
2019-12-31 09:05:26.159 18802-18802/com.xxxxx.activity E/>>AppException<<: uncaughtException
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/view/ViewCompat;
        at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:560)
        at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:538)
        at com.xxx.xxx.react.BaseReactNativeActivity.onResume(BaseReactNativeActivity.java:69)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
        at android.app.Activity.performResume(Activity.java:7495)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4118)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4163)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2026)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7270)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:903)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.view.ViewCompat" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.xxxxx.activity-uSbtdhEzpFON_s6WDJ9EsA==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxxxx.activity-uSbtdhEzpFON_s6WDJ9EsA==/lib/arm, /data/app/com.xxxxx.activity-uSbtdhEzpFON_s6WDJ9EsA==/base.apk!/lib/armeabi, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:560) 
        at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:538) 
        at com.xxx.xxx.react.BaseReactNativeActivity.onResume(BaseReactNativeActivity.java:69) 
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413) 
        at android.app.Activity.performResume(Activity.java:7495) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4118) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4163) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2026) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:227) 
        at android.app.ActivityThread.main(ActivityThread.java:7270) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:903) 

```

Snack, code example, screenshot, or link to a repository:

**Comment by cliffgor** [comment]
@caiyonglong I belive so I also had the same issue but when I migrated to androidx it worked
