### ISSUE TITLE
npm start fails with too many open files error

### ISSUE THREAD

**Issue by buraks** [facebook/react-native#2771]
```
[19:40:06] <START> Building Dependency Graph
[19:40:06] <START> Crawling File System
[19:40:09] <START> request:/index.ios.bundle
[19:40:09] <START> find dependencies
 ERROR  watch EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"watch"}
Error: watch EMFILE
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at NodeWatcher.watchdir (/Users/burak/firebase/project/node_modules/react-native/node_modules/sane/src/node_watcher.js:144:20)
    at Walker.<anonymous> (/Users/burak/firebase/project/node_modules/react-native/node_modules/sane/src/node_watcher.js:351:12)
    at Walker.emit (events.js:110:17)
    at /Users/burak/firebase/project/node_modules/react-native/node_modules/sane/node_modules/walker/lib/walker.js:69:16
    at /Users/burak/firebase/project/node_modules/react-native/node_modules/graceful-fs/graceful-fs.js:140:16
    at FSReqWrap.oncomplete (fs.js:95:15)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
fs.js:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
Error: EMFILE, too many open files '/Users/burak/.babel.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at process.save (/Users/burak/firebase/project/node_modules/react-native/node_modules/babel-core/lib/api/register/cache.js:35:19)
    at process.emit (events.js:107:17)
    at process.exit (node.js:600:17)
    at process.<anonymous> (/Users/burak/firebase/project/node_modules/react-native/packager/packager.js:151:11)
    at process.emit (events.js:107:17)
    at process._fatalException (node.js:236:26)
    at Walker.<anonymous> (/Users/burak/firebase/project/node_modules/react-native/node_modules/sane/src/node_watcher.js:351:12)
```

**Comment by buraks** [comment]
```
[project]$ npm start

> project@0.0.1 start /Users/burak/firebase/project
> node_modules/react-native/packager/packager.sh

node_modules/react-native/packager/packager.sh: line 16: ulimit: open files: cannot modify limit: Operation not permitted
```

**Comment by ide** [comment]
Did you install Watchman?

**Comment by mkonicek** [comment]
See https://facebook.github.io/react-native/docs/getting-started.html

**Comment by mkonicek** [comment]
Closing, please reopen if you still see this.
