### ISSUE TITLE
FlatList cannot be tested

### ISSUE THREAD

**Issue by sutbult** [facebook/react-native#27724]
It does not work to render a FlatList with react-test-renderer. This error appears:
```
$ jest flatList.js
 FAIL  __tests__/flatList.js
  FlatList
    ✕ renders (276ms)

  ● FlatList › renders

    TypeError: Cannot read property 'Consumer' of undefined



      at VirtualizedList.render (node_modules/react-native/Libraries/Lists/VirtualizedList.js:1044:29)
      at finishClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7693:31)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7648:24)
      at beginWork$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9159:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12981:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12955:22)
      at renderRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12648:11)
      at runRootCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12420:20)
      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1935:24
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:643:12)
      at runWithPriority (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1887:10)
      at flushSyncCallbackQueueImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1931:7)
      at flushSyncCallbackQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1920:3)
      at scheduleUpdateOnFiber (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12297:9)
      at scheduleRootUpdate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15087:3)
      at updateContainerAtExpirationTime (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15115:10)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15134:10)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15824:5)
      at Object.<anonymous> (__tests__/flatList.js:35:25)

  console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10695
    The above error occurred in the <VirtualizedList> component:
        in VirtualizedList (created by FlatList)
        in FlatList
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

```

React Native version: 0.61.4

```
$ react-native info
info Fetching system and libraries information...
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 2.23 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.12.3 - ~/.yarn/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 25.0.2, 27.0.1, 28.0.3
      System Images: android-27 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.4 => 0.61.4
```
`react-dom` and `react-test-renderer` are also version 16.9.0.
## Steps To Reproduce

1. Create a test suite with this content:
```
import React from "react"
import {
    Text,
    FlatList,
} from "react-native"
import renderer from "react-test-renderer"

describe("FlatList", () => {
    it("renders", () => {
        expect(renderer.create(
            <FlatList
                data={["foo"]}
                renderItem={item => <Text>{item.item}</Text>}
                keyExtractor={(item, index) => item + index}
            />
        )).toMatchSnapshot();
    });
});
```
2. Run `jest flatList.js`.

Describe what you expected to happen: I expected the test to create a DOM tree that then would be compared against a snapshot.
This problem arose when I updated React Native from 0.55.3. In the earlier version, it worked fine.

Snack, code example, screenshot, or link to a repository: See above. This problem exists with a proprietary project, so I cannot disclose exact details about how FlatList is used. However, it is not much more complicated than the example.

**Comment by sutbult** [comment]
I have circumvented the problem by mocking FlatList in this manner:
```
jest.mock("react-native", () => {
    const React = require.requireActual("react");
    const actual = require.requireActual("react-native");
    const View = actual.View;
    function MockedFlatList(props) {
        const items = props.data.map(item => {
            const key = props.keyExtractor(item);
            return (
                <View key={key}>
                    {props.renderItem(item)}
                </View>
            );
        });
        return (
            <View>
                {items}
            </View>
        );
    }
    Object.defineProperty(actual, "FlatList", {
        get: () => MockedFlatList,
    });
    return actual;
});
```

When this mock is used, the test passes and this is output instead:
```
$ jest flatList.js
 PASS  __tests__/flatList.js
  FlatList
    ✓ renders (212ms)
```

The snapshot file contains this:
```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`FlatList renders 1`] = `
<View>
  <View>
    <Text>
      foo
    </Text>
  </View>
</View>
`;
```
