### ISSUE TITLE
 [ArrayIndexOutOfBoundsException] android.text.StaticLayout.getLineStart() 

### ISSUE THREAD

**Issue by maggialejandro-rp** [facebook/react-native#27763]
### React Native version:
> System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 412.97 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.12.0 - ~/.nvm/versions/node/v12.12.0/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.12.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.2, 28.0.3
      System Images: android-27 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

### Stacktrace for Android 9
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=53; index=-5
       at android.text.StaticLayout.getLineStart(StaticLayout.java:1226)
       at android.text.Layout.getLineEnd(Layout.java:1599)
       at android.widget.TextView.onProvideAutoStructureForAssistOrAutofill(TextView.java:10682)
       at android.widget.TextView.onProvideAutofillStructure(TextView.java:10609)
       at android.view.View.dispatchProvideStructureForAssistOrAutofill(View.java:8644)
       at android.view.View.dispatchProvideAutofillStructure(View.java:8637)
       at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3584)
       at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3584)
       at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:517)
       at android.app.assist.AssistStructure.<init>(AssistStructure.java:2047)
       at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3403)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1942)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:215)
       at android.app.ActivityThread.main(ActivityThread.java:6939)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```

### Stacktrace for Android 8.1.0
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=763; index=-204
       at android.text.StaticLayout.getLineStart(StaticLayout.java:1207)
       at android.text.Layout.getLineEnd(Layout.java:1572)
       at android.widget.TextView.onProvideAutoStructureForAssistOrAutofill(TextView.java:10275)
       at android.widget.TextView.onProvideAutofillStructure(TextView.java:10212)
       at android.view.View.dispatchProvideStructureForAssistOrAutofill(View.java:8132)
       at android.view.View.dispatchProvideAutofillStructure(View.java:8125)
       at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3509)
       at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3509)
       at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:510)
       at android.app.assist.AssistStructure.<init>(AssistStructure.java:1912)
       at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3098)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6647)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

<img width="439" alt="Screen Shot 2020-01-14 at 15 15 48" src="https://user-images.githubusercontent.com/50118796/72370342-ce4dc980-36e0-11ea-9ac6-747749f910dc.png">

styles:

```javascript
const styles = {
  platform: 'android',
  accordionBorderColor: 'transparent',
  accordionContentPadding: 10,
  accordionIconFontSize: 18,
  contentStyle: '#f5f4f5',
  expandedIconStyle: '#000',
  headerStyle: '#edebed',
  iconStyle: '#000',
  elevation: 4,
  containerTouchableBackgroundColor: 'rgba(0,0,0,0.4)',
  innerTouchableBackgroundColor: '#fff',
  listItemHeight: 56.8,
  listItemBorderColor: 'transparent',
  marginHorizontal: -15,
  marginLeft: 14,
  marginTop: 15,
  minHeight: 56,
  padding: 15,
  touchableTextColor: '#757575',
  androidRipple: true,
  androidRippleColor: 'rgba(256, 256, 256, 0.3)',
  androidRippleColorDark: 'rgba(0, 0, 0, 0.08)',
  buttonUppercaseAndroidText: false,
  badgeBg: '#FD8832',
  badgeColor: '#fff',
  badgePadding: 8.114285714285714,
  buttonFontFamily: 'Roboto_medium',
  buttonDisabledBg: '#FECEAA',
  buttonPadding: 12.17142857142857,
  buttonDefaultActiveOpacity: 0.5,
  buttonDefaultFlex: 1,
  buttonDefaultBorderRadius: 2,
  buttonDefaultBorderWidth: 1,
  buttonPrimaryBg: '#FD8832',
  buttonPrimaryColor: '#fff',
  buttonInfoBg: '#3785d3',
  buttonInfoColor: '#fff',
  buttonSuccessBg: '#1CB448',
  buttonSuccessColor: '#fff',
  buttonDangerBg: '#DB3A32',
  buttonDangerColor: '#fff',
  buttonWarningBg: '#FDB132',
  buttonWarningColor: '#fff',
  buttonTextSize: 13.2,
  buttonTextSizeLarge: 21.299999999999997,
  buttonTextSizeSmall: 11.36,
  borderRadiusLarge: 53.959999999999994,
  iconSizeLarge: 48.68571428571428,
  iconSizeSmall: 19.474285714285713,
  cardDefaultBg: '#fff',
  cardBorderColor: '#E3E7E8',
  cardBorderRadius: 4.057142857142857,
  cardItemPadding: 16.228571428571428,
  CheckboxRadius: 0,
  CheckboxBorderWidth: 2,
  CheckboxPaddingLeft: 2,
  CheckboxPaddingBottom: 5,
  CheckboxIconSize: 16,
  CheckboxIconMarginTop: 1,
  CheckboxFontSize: 17,
  checkboxBgColor: '#039BE5',
  checkboxSize: 20,
  checkboxTickColor: '#fff',
  checkboxDefaultColor: 'transparent',
  checkboxTextShadowRadius: 0,
  brandPrimary: '#FD8832',
  brandInfo: '#3785d3',
  brandSuccess: '#1CB448',
  brandDanger: '#DB3A32',
  brandWarning: '#FDB132',
  brandDark: '#364D55',
  brandLight: '#fff',
  containerBgColor: '#fff',
  datePickerFlex: 1,
  datePickerPadding: 10,
  datePickerTextColor: '#000',
  datePickerBg: 'transparent',
  fabBackgroundColor: 'blue',
  fabBorderRadius: 28,
  fabBottom: 0,
  fabButtonBorderRadius: 20,
  fabButtonHeight: 40,
  fabButtonLeft: 7,
  fabButtonMarginBottom: 10,
  fabContainerBottom: 20,
  fabDefaultPosition: 20,
  fabElevation: 4,
  fabIconColor: '#fff',
  fabIconSize: 24,
  fabShadowColor: '#000',
  fabShadowOffsetHeight: 2,
  fabShadowOffsetWidth: 0,
  fabShadowOpacity: 0.4,
  fabShadowRadius: 2,
  fabWidth: 56,
  DefaultFontSize: 14.2,
  fontFamily: 'Barlow-Regular',
  fontSizeBase: 14.2,
  fontSizeH1: 25.56,
  fontSizeH2: 22.72,
  fontSizeH3: 19.88,
  footerHeight: 52.74285714285714,
  footerDefaultBg: '#F7F9FA',
  footerPaddingBottom: 0,
  tabBarTextColor: '#6D868F',
  tabBarTextSize: 12.17142857142857,
  activeTab: '#fff',
  sTabBarActiveTextColor: '#007aff',
  tabBarActiveTextColor: '#3785d3',
  tabActiveBgColor: 'transparent',
  toolbarBtnColor: '#364D55',
  toolbarDefaultBg: '#fff',
  toolbarHeight: 56.8,
  toolbarSearchIconSize: 23,
  toolbarInputColor: '#fff',
  searchBarHeight: 40,
  searchBarInputHeight: 50,
  toolbarBtnTextColor: '#364D55',
  toolbarDefaultBorder: '#fff',
  iosStatusbar: 'dark-content',
  statusBarColor: '#CCCCCC',
  darkenHeader: '#000000',
  iconFamily: 'MaterialCommunityIcons',
  iconFontSize: 32.457142857142856,
  iconHeaderSize: 24.34285714285714,
  inputFontSize: 16.228571428571428,
  inputBorderColor: '#94A7AE',
  inputSuccessBorderColor: '#1CB448',
  inputErrorBorderColor: '#DB3A32',
  inputHeightBase: 30.428571428571427,
  inputColor: '#364D55',
  inputColorPlaceholder: '#575757',
  buttonLineHeight: 19,
  lineHeightH1: 26.37142857142857,
  lineHeightH2: 20.285714285714285,
  lineHeightH3: 20.285714285714285,
  lineHeight: 20.285714285714285,
  listItemSelected: '#3F51B5',
  listBg: 'transparent',
  listBorderColor: 'rgba(54, 77, 85, 0.14)',
  listDividerBg: '#F7F9FA',
  listBtnUnderlayColor: '#DDD',
  listItemPadding: 12.17142857142857,
  listNoteColor: '#6D868F',
  listNoteSize: 14.2,
  defaultProgressColor: '#E4202D',
  inverseProgressColor: '#1A191B',
  radioBtnSize: 24.34285714285714,
  radioSelectedColorAndroid: '#FD8832',
  radioBtnLineHeight: 24.34285714285714,
  radioColor: '#FD8832',
  segmentBackgroundColor: '#3F51B5',
  segmentActiveBackgroundColor: '#fff',
  segmentTextColor: '#fff',
  segmentActiveTextColor: '#3F51B5',
  segmentBorderColor: '#fff',
  segmentBorderColorMain: '#3F51B5',
  defaultSpinnerColor: '#FD8832',
  inverseSpinnerColor: '#FFFFFF',
  tabBarDisabledTextColor: '#C0CBCF',
  tabDefaultBg: '#ffffff',
  topTabBarTextColor: '#6D878F',
  topTabBarActiveTextColor: '#364D55',
  topTabBarBorderColor: '#C0CBCF',
  topTabBarActiveBorderColor: '#3785d3',
  tabBgColor: 'transparent',
  tabFontSize: 14.2,
  textColor: '#364D55',
  inverseTextColor: '#fff',
  noteFontSize: 14.2,
  defaultTextColor: '#364D55',
  titleFontfamily: 'Barlow-Medium',
  titleFontSize: 20.285714285714285,
  subTitleFontSize: 14.2,
  subtitleColor: '#6D868F',
  titleFontColor: '#364D55',
  borderRadiusBase: 2.0285714285714285,
  borderWidth: 0.5142857142857142,
  contentPadding: 16.228571428571428,
  dropdownLinkColor: '#414142',
  inputLineHeight: 20.285714285714285,
  deviceWidth: 360,
  deviceHeight: 688,
  isIphoneX: false,
  inputGroupRoundedBorderRadius: 30,
  Inset: {
    portrait: { topInset: 24, leftInset: 0, rightInset: 0, bottomInset: 16 },
    landscape: { topInset: 0, leftInset: 44, rightInset: 44, bottomInset: 21 }
  },
  btnFontFamily: 'Barlow-Medium',
  btnTextSize: 14.2,
  btnTextSizeLarge: 16.228571428571428,
  btnTextSizeSmall: 12.17142857142857,
  emptyFooterHeight: 20.285714285714285,
  btnLineHeight: 20.285714285714285,
  brandInfoBright: '#1da4fc',
  brandInfoDark: '#316ab0',
  brandInfoDarker: '#2C5F9E',
  brandDarker: '#0C2229',
  brandInfoBg: '#E8F6FF',
  brandWarningBg: '#FDE0AF',
  containerBgColorDim: '#F7F9FA',
  containerBgColorMuted: '#E3E7E8',
  inputRoundedBgColor: '#F2F4F5',
  containerBgColorDarken: 'rgba(0, 0, 0, 0.5)',
  fontFamilyMedium: 'Barlow-Medium',
  fontFamilyBold: 'Barlow-Bold',
  fontSizeDisplay: 44.628571428571426,
  lineHeightDisplay: 44.628571428571426,
  fontSizeHeadline: 28.4,
  lineHeightHeadline: 32.457142857142856,
  fontSizeTitle: 20.285714285714285,
  lineHeightTitle: 24.34285714285714,
  fontSizeSubtitle: 16.228571428571428,
  lineHeightSubtitle: 20.285714285714285,
  fontSizeLarge: 16.228571428571428,
  lineHeightLarge: 22.314285714285713,
  captionFontSize: 12.17142857142857,
  captionLineHeight: 18.257142857142856,
  footnoteFontSize: 10.142857142857142,
  footnoteLineHeight: 14.2,
  badgeFontSize: 10.142857142857142,
  badgeLineHeight: 16.228571428571428,
  secondaryTextColor: '#6D878F',
  disabledTextColor: '#C0CBCF',
  contentPaddingXXSmall: 2.0285714285714285,
  contentPaddingXSmall: 4.057142857142857,
  contentPaddingSmall: 8.114285714285714,
  contentPaddingLarge: 24.34285714285714,
  contentPaddingXLarge: 40.57142857142857,
  formLargePaddingHorizontal: 40.57142857142857,
  buttonContainerFixedPadding: 16.228571428571428,
  buttonContainerFixedPaddingSlim: 8.114285714285714,
  h1MarginBottom: 8.114285714285714,
  h2MarginBottom: 8.114285714285714,
  h3MarginBottom: 8.114285714285714,
  pMarginBottom: 4.057142857142857,
  borderWidthThick: 1.0579591836734692,
  listItemHeightSmall: 48.68571428571428,
  listItemHeightLarge: 73.02857142857142,
  listItemLineHeight: 20.285714285714285,
  listBorderColorInverse: 'rgba(255, 255, 255, 0.4)',
  gridItemsNum: 3,
  gridItemWidth: 120,
  itemHomeGridWidth: 109.18095238095238,
  gridItemsDataNum: 2,
  gridItemsDataWidth: 180,
  gridItemsHomeHeader: 4,
  gridItemHomeHeaderWidth: 90,
  itemGridFontSize: 14.2,
  itemGridLineHeight: 20.285714285714285,
  gridHalfWidth: 180,
  listItemBannerHeight: 48.68571428571428,
  iconColorPrimary: '#FD8832',
  iconColorSecondary: '#6D868F',
  iconFontSizeLarge: 40.57142857142857,
  iconFontSizeSmall: 24.34285714285714,
  iconFontSizeXSmall: 20.285714285714285,
  iconFontSizeXXSmall: 12.17142857142857,
  imgXXXSmallHeight: 48.68571428571428,
  imgXXSmallHeight: 60.857142857142854,
  imgXSmallHeight: 73.02857142857142,
  imgSmallHeight: 97.37142857142857,
  imgMediumHeight: 129.82857142857142,
  imgLargeHeight: 146.05714285714285,
  imgXLargeHeight: 194.74285714285713,
  imgXXLargeHeight: 243.42857142857142,
  imgXXXLargeHeight: 316.45714285714286,
  btnHeight: 32.457142857142856,
  btnHeightSmall: 24.34285714285714,
  btnHeightLarge: 48.68571428571428,
  btnFontSize: 14.2,
  btnFontSizeLarge: 16.228571428571428,
  btnFontSizeSmall: 12.17142857142857,
  roundedButtonWidth: 121.71428571428571,
  inputBorderWidth: 0.5142857142857142,
  inputHeightDisplay: 48.68571428571428,
  inputFontSizeLarge: 28.4,
  inputHeightLarge: 40.57142857142857,
  cardBorderRadiusLarge: 8.114285714285714,
  modalBorderRadius: 16.228571428571428,
  homeBannerWidth: 146.05714285714285,
  tooltipWidthPrepaidCard: 315.76163265306116,
  tooltipMaxWidthPrepaidCard: 324.57142857142856,
  tooltipHeightPrepaidCard: 131.94448979591837,
  tooltipHeightCashInNotice: 162.28571428571428,
  tooltipMaxWidthCashInNotice: 324.57142857142856,
  tooltipWidthCashInNotice: 324.57142857142856,
  tooltipBGCashInNotice: 'white',
  tooltipHeightWrapperCashInNotice: 135,
  bannerLargeWidth: 328.1069387755102,
  bannerLargeHeight: 93.31428571428572,
  progressCircleThickness: 6.085714285714285,
  darkenToolbarBg: '#666666'
};
```

**Comment by maggialejandro** [comment]
Fixed by adding `android/app/src/main/res/values-v28`
```xml
<style name="EditText" parent="AppBaseEditText">
    <item name="android:importantForAutofill">noExcludeDescendants</item>
</style>
```

inside `<resources>` tag

**Comment by maggialejandro-rp** [comment]
Fixed by adding `android/app/src/main/res/values-v28`
```xml
<style name="EditText" parent="AppBaseEditText">
    <item name="android:importantForAutofill">noExcludeDescendants</item>
</style>
```

inside `<resources>` tag
