### ISSUE TITLE
App crashes upon app launch on some Android devices only.

### ISSUE THREAD

**Issue by IvanPaulBOB** [facebook/react-native#27823]
React Native Android app will crash upon app launch on some Android devices only. So far, we've encountered it in Nexus 6P, Samsung Galaxy S7 and Galaxy S6 only. However, there will be times where it will not be reproducible. Also, in other devices (like Samsung Galaxy A7), I never encountered the crash.

React Native version:
    "react": "16.9.0",
    "react-native": "0.61.5",

Steps To Reproduce
1. Launch react native app on Nexus 6P, Samsung Galaxy S7 or Galaxy S6

Expected Result:
Should launch the react native app successfully

Actual Result:
React Native Android app crashed. 

Crash logs captured. For privacy purposes, I replaced our app's package name with "********":
```
2020-01-21 14:40:18.260 13084-13120/? D/SoLoader: About to load: libreactnativeblob.so
2020-01-21 14:40:18.261 13084-13120/? D/SoLoader: libreactnativeblob.so not found on /data/data/com.********/lib-main
2020-01-21 14:40:18.261 13084-13120/? D/SoLoader: libreactnativeblob.so found on /data/app/com.********-fVcI4lOhD7w2f6EzYi4J4g==/lib/arm64
2020-01-21 14:40:18.261 13084-13120/? D/SoLoader: Not resolving dependencies for libreactnativeblob.so
2020-01-21 14:40:18.262 13084-13120/? D/SoLoader: Loaded: libreactnativeblob.so
2020-01-21 14:40:18.735 13084-13120/? I/ReactNativeJS: Running "********App" with {"rootTag":1}
2020-01-21 14:40:18.847 13084-13143/? D/SoLoader: About to load: libimagepipeline.so
2020-01-21 14:40:18.847 13084-13143/? D/SoLoader: libimagepipeline.so not found on /data/data/com.********/lib-main
2020-01-21 14:40:18.848 13084-13143/? D/SoLoader: libimagepipeline.so found on /data/app/com.********-fVcI4lOhD7w2f6EzYi4J4g==/lib/arm64
2020-01-21 14:40:18.848 13084-13143/? D/SoLoader: Not resolving dependencies for libimagepipeline.so
2020-01-21 14:40:18.852 13084-13143/? D/SoLoader: Loaded: libimagepipeline.so
2020-01-21 14:40:18.892 13084-13120/? E/ReactNativeJS: Error: A network error (such as timeout, interrupted connection or unreachable host) has occurred.
    
    --------- beginning of crash
2020-01-21 14:40:18.903 13084-13121/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.********, PID: 13084
    com.facebook.react.common.JavascriptException: Error: A network error (such as timeout, interrupted connection or unreachable host) has occurred., stack:
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)
2020-01-21 14:40:18.906 4629-7619/? W/ActivityManager:   Force finishing activity com.********/.MainActivity
2020-01-21 14:40:18.915 4629-4810/? I/ActivityManager: Showing crash dialog for package com.******** u0
```

**Comment by IvanPaulBOB** [comment]
Following up on this.

**Comment by vojeda** [comment]
Same problem. Any solution for this?.

**Comment by dotcoo** [comment]
Same problem. Any solution for this?

**Comment by avonipenti** [comment]
@IvanPaulBOB Did you figure out what the problem was? We upgraded Firebase module and android has been having this issue.

**Comment by PaulDuong1** [comment]
> @IvanPaulBOB Did you figure out what the problem was? We upgraded our Firebase module and now the android app crashes on splash scree. on Pixel and other emulators as well.

Same here. Did you solve the problem?
