### ISSUE TITLE
Unable to run project in android..

### ISSUE THREAD

**Issue by devtechvalens** [facebook/react-native#27889]
Getting error when run project in run time.
 
  Exception in native call
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.Class.getInterfaces()' on a null object reference

  "react": "16.6.1",
   "react-native": "^0.59.9",

![2020-01-28](https://user-images.githubusercontent.com/25582828/73263888-8d34d980-41f7-11ea-8b2c-289944b6a841.jpg)

Exception in native call
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.Class.getInterfaces()' on a null object reference
        at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForShadowNodeClass(ViewManagersPropertyCache.java:336)
        at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForShadowNodeClass(ViewManagersPropertyCache.java:347)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.<init>(ViewManagerPropertyUpdater.java:150)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.<init>(ViewManagerPropertyUpdater.java:144)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.findNodeSetter(ViewManagerPropertyUpdater.java:97)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.getNativeProps(ViewManagerPropertyUpdater.java:70)
        at com.facebook.react.uimanager.ViewManager.getNativeProps(ViewManager.java:208)
        at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstantsForViewManager(UIManagerModuleConstantsHelper.java:148)
        at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstants(UIManagerModuleConstantsHelper.java:95)
        at com.facebook.react.uimanager.UIManagerModule.createConstants(UIManagerModule.java:275)
        at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:181)
        at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:142)
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:182)
        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:150)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:123)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:111)
        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:189)
        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:154)
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:427)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:38)
        at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1044)
        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1003)
        at com.facebook.react.ReactInstanceManager.access$1300(ReactInstanceManager.java:123)
        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:964)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:224)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)
2020-01-29 17:43:38.984 4026-4026/com.leavemark E/BackgroundFallback: initVivoBgFallback callstackcom.android.internal.policy.DecorView.<init>:389 com.android.internal.policy.PhoneWindow.generateDecor:2441 com.android.internal.policy.PhoneWindow.installDecor:2820 com.android.internal.policy.PhoneWindow.setContentView:453 android.app.Dialog.setContentView:592 com.facebook.react.devsupport.RedBoxDialog.<init>:269 com.facebook.react.devsupport.DevSupportManagerImpl$5.run:429 android.os.Handler.handleCallback:873 android.os.Handler.dispatchMessage:99 android.os.Looper.loop:224

**Comment by hramos** [comment]
Can you provide an example using [Snack](https://snack.expo.io/)?
