### ISSUE TITLE
Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException 

### ISSUE THREAD

**Issue by haddad-yacine** [facebook/react-native#27900]
React Native version:
System:
    OS: Windows 10
  Binaries:
    Node: 12.4.0
    Yarn: 1.21.1 
    npm: 6.9.0 
    Watchman: 4.9.4 
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

Device info:
Marque : samsung
Modèle : Galaxy A7 (2018)
System Version : 9 

```
Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'transform' of a view managed by: RCTView at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:98)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:134)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:54)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:145)
       at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:289)
       at com.facebook.react.uimanager.UIManagerModule.synchronouslyUpdateViewOnUIThread(UIManagerModule.java:397)
       at com.facebook.react.animated.PropsAnimatedNode.updateView(PropsAnimatedNode.java:98)
       at com.facebook.react.animated.NativeAnimatedNodesManager.updateNodes(NativeAnimatedNodesManager.java:547)
       at com.facebook.react.animated.NativeAnimatedNodesManager.runUpdates(NativeAnimatedNodesManager.java:456)
       at com.facebook.react.animated.NativeAnimatedModule$1.doFrameGuarded(NativeAnimatedModule.java:101)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:693)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7078)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:134)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:54)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:145)
       at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:289)
       at com.facebook.react.uimanager.UIManagerModule.synchronouslyUpdateViewOnUIThread(UIManagerModule.java:397)
       at com.facebook.react.animated.PropsAnimatedNode.updateView(PropsAnimatedNode.java:98)
       at com.facebook.react.animated.NativeAnimatedNodesManager.updateNodes(NativeAnimatedNodesManager.java:547)
       at com.facebook.react.animated.NativeAnimatedNodesManager.runUpdates(NativeAnimatedNodesManager.java:456)
       at com.facebook.react.animated.NativeAnimatedModule$1.doFrameGuarded(NativeAnimatedModule.java:101)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:693)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7078)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

Caused by java.lang.IllegalArgumentException: Cannot set 'scaleX' to Float.NaN
       at android.view.View.sanitizeFloatPropertyValue(View.java:16986)
       at android.view.View.sanitizeFloatPropertyValue(View.java:16960)
       at android.view.View.setScaleX(View.java:16349)
       at com.facebook.react.uimanager.BaseViewManager.setTransformProperty(BaseViewManager.java:314)
       at com.facebook.react.uimanager.BaseViewManager.setTransform(BaseViewManager.java:76)
       at com.facebook.react.views.view.ReactViewManager.setTransform(ReactViewManager.java:278)
       at com.facebook.react.views.view.ReactViewManager.setTransform(ReactViewManager.java:37)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:134)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:54)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:145)
       at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:289)
       at com.facebook.react.uimanager.UIManagerModule.synchronouslyUpdateViewOnUIThread(UIManagerModule.java:397)
       at com.facebook.react.animated.PropsAnimatedNode.updateView(PropsAnimatedNode.java:98)
       at com.facebook.react.animated.NativeAnimatedNodesManager.updateNodes(NativeAnimatedNodesManager.java:547)
       at com.facebook.react.animated.NativeAnimatedNodesManager.runUpdates(NativeAnimatedNodesManager.java:456)
       at com.facebook.react.animated.NativeAnimatedModule$1.doFrameGuarded(NativeAnimatedModule.java:101)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:693)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7078)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

**Comment by hramos** [comment]
Can you make sure the entire issue template is filled out? An error message without any context might not get you a useful response.

**Comment by avnerI** [comment]
Hey,  I'm having the same problem. 
Is there any news on the issue?

**Comment by haddad-yacine** [comment]
> Hey, I'm having the same problem.
> Is there any news on the issue?

Nop, I can't even detect the source of the problem.

**Comment by raultunduc** [comment]
Hi there! I do encounter the same problem.
From what I've seen from the log tracker, this issue is related to devices running Android 9 (SDK 28).
Could somebody check how are computed the `scale` values from `MatrixDecompositionContext` (uimanager/MatrixMathHelper.java) ?
From my point of view, in that array are stored `NaN` values and this case is handled nowhere.

**Comment by bachlongkocanh** [comment]
Same issue.
![Screen Shot 2020-05-14 at 16 00 46](https://user-images.githubusercontent.com/28125294/81914974-2bf51280-95fc-11ea-8a58-862ae0071a8b.png)

**Comment by fontesrp** [comment]
I believe this is the same issue as https://github.com/facebook/react-native/issues/21755 

We get a a lot of these errors on crashlitcs, but are unable to reproduce them in debug mode

For us, it started on RN 0.60.4 and is still occurring in RN 0.62.2

**Comment by fontesrp** [comment]
If it helps...

## Description

We are getting reports of random JSApplicationIllegalArgumentException in our production builds, but are not able to reproduce the issue in our devices. 

## React Native version:
```
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 969.98 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - /var/folders/ts/48vtw6y57470j_gnv8wx20gh0000gp/T/yarn--1590415080068-0.9793758036588522/node
    Yarn: 1.22.4 - /var/folders/ts/48vtw6y57470j_gnv8wx20gh0000gp/T/yarn--1590415080068-0.9793758036588522/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.2 - /Users/rfontes/.rvm/gems/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /Users/rfontes/.sdkman/candidates/java/current/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:

We were unable to reproduce the issue, but crashlitics shows a lot of reports with this error. The property that causes the error seem to be random and changes for every event.

Here is an example:

```
java.lang.IllegalArgumentException: method com.facebook.react.views.text.ReactBaseTextShadowNode.setAllowFontScaling argument 1 has type boolean, got com.facebook.react.bridge.DynamicFromObject
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:109)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:161)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:65)
    at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:320)
    at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:250)
    at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:469)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:214)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
    at java.lang.Thread.run(Thread.java:764)
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'allowFontScaling' in shadow node of type: RCTText
    at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:123)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:161)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:65)
    at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:320)
    at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:250)
    at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:469)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:214)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
    at java.lang.Thread.run(Thread.java:764)
```

**Comment by stefkampen** [comment]
We get these errors in our crash reporting as well. Although from what I can see it only happens after the android activity ondestroy is triggered. So probably nobody will notice this.

**Comment by robleds** [comment]
Same here ... looks in Google Play Console: 

`com.facebook.react.bridge.UnexpectedNativeTypeException
com.airbnb.android.react.maps.AirMapView.setRegion`

`com.facebook.react.bridge.JSApplicationIllegalArgumentException: 
  at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp (ViewManagersPropertyCache.java:102)
  at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty (ViewManagerPropertyUpdater.java:136)
  at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps (ViewManagerPropertyUpdater.java:56)
  at com.facebook.react.uimanager.ViewManager.updateProperties (ViewManager.java:49)
  at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties (NativeViewHierarchyManager.java:137)
  at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute (UIViewOperationQueue.java:94)
  at com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:917)
  at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:1028)
  at com.facebook.react.uimanager.UIViewOperationQueue.access$2600 (UIViewOperationQueue.java:48)
  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:1088)
  at com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:29)
  at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:175)
  at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:85)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1060)
  at android.view.Choreographer.doCallbacks (Choreographer.java:884)
  at android.view.Choreographer.doFrame (Choreographer.java:810)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1047)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:226)
  at android.app.ActivityThread.main (ActivityThread.java:7592)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)
Caused by: java.lang.reflect.InvocationTargetException: 
  at java.lang.reflect.Method.invoke (Native Method)
  at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp (ViewManagersPropertyCache.java:87)
Caused by: com.facebook.react.bridge.UnexpectedNativeTypeException: 
  at com.facebook.react.bridge.ReadableNativeMap.checkInstance (ReadableNativeMap.java:140)
  at com.facebook.react.bridge.ReadableNativeMap.getValue (ReadableNativeMap.java:115)
  at com.facebook.react.bridge.ReadableNativeMap.getDouble (ReadableNativeMap.java:151)
  at com.airbnb.android.react.maps.AirMapView.setRegion (AirMapView.java:467)
  at com.airbnb.android.react.maps.AirMapView.setInitialRegion (AirMapView.java:452)
  at com.airbnb.android.react.maps.AirMapManager.setInitialRegion (AirMapManager.java:105)`

**Comment by invyctus92** [comment]
P20 lite (ANE-LX1) android 9
"react-native": "0.64.2",

`com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'transform' of a view managed by: RCTView         at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:102)         at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)         at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)         at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:49)         at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:290)         at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:188)         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1103)         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1074)         at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)         at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)         at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090)         at android.view.Choreographer.doCallbacks(Choreographer.java:893)         at android.view.Choreographer.doFrame(Choreographer.java:809)         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)         at android.os.Handler.handleCallback(Handler.java:907)         at android.os.Handler.dispatchMessage(Handler.java:105)         at android.os.Looper.loop(Looper.java:216)         at android.app.ActivityThread.main(ActivityThread.java:7625)         at java.lang.reflect.Method.invoke(Method.java:-2)         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)  Caused by: java.lang.reflect.InvocationTargetException         at java.lang.reflect.Method.invoke(Method.java:-2)         at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:87)         at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)         at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)         at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:49)         at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:290)         at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:188)         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1103)         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1074)         at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)         at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)         at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090)         at android.view.Choreographer.doCallbacks(Choreographer.java:893)         at android.view.Choreographer.doFrame(Choreographer.java:809)         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)         at android.os.Handler.handleCallback(Handler.java:907)         at android.os.Handler.dispatchMessage(Handler.java:105)         at android.os.Looper.loop(Looper.java:216)         at android.app.ActivityThread.main(ActivityThread.java:7625)         at java.lang.reflect.Method.invoke(Method.java:-2)         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)  Caused by: java.util.NoSuchElementException         at java.util.HashMap$HashIterator.nextNode(HashMap.java:1444)         at java.util.HashMap$KeyIterator.next(HashMap.java:1466)         at com.facebook.react.bridge.ReadableNativeMap$ReadableNativeMapKeySetIterator.nextKey(ReadableNativeMap.java:254)         at com.facebook.react.uimanager.TransformHelper.processTransform(TransformHelper.java:64)         at com.facebook.react.uimanager.BaseViewManager.setTransformProperty(BaseViewManager.java:330)         at com.facebook.react.uimanager.BaseViewManager.setTransform(BaseViewManager.java:82)         at com.facebook.react.views.view.ReactViewManager.setTransform(ReactViewManager.java:274)         at com.facebook.react.views.view.ReactViewManager.setTransform(ReactViewManager.java:37)         at java.lang.reflect.Method.invoke(Method.java:-2)         at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:87)         at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)         at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)         at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:49)         at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:290)         at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:188)         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1103)         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1074)         at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)         at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)         at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090)         at android.view.Choreographer.doCallbacks(Choreographer.java:893)         at android.view.Choreographer.doFrame(Choreographer.java:809)         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)         at android.os.Handler.handleCallback(Handler.java:907)         at android.os.Handler.dispatchMessage(Handler.java:105)         at android.os.Looper.loop(Looper.java:216)         at android.app.ActivityThread.main(ActivityThread.java:7625)         at java.lang.reflect.Method.invoke(Method.java:-2)         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)`
