### ISSUE TITLE
Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException

### ISSUE THREAD

**Issue by ProMasoud** [facebook/react-native#27959]
Description:
Hello every one. my app crash in release mode with this error in Android 6,7 that I tested but in android 9 is ok.
Also this error just occur in **RELEASE** mode and in debug is ok.
I get error log from firebase crashlytics 

```
Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'defaultSrc' of a view managed by: RCTImageView
       at com.facebook.react.uimanager.oa$j.a()
       at com.facebook.react.uimanager.la$b.a()
       at com.facebook.react.uimanager.la.a()
       at com.facebook.react.uimanager.ViewManager.updateProperties()
       at com.facebook.react.uimanager.m.a()
       at com.facebook.react.uimanager.ea$c.execute()
       at com.facebook.react.uimanager.ea$g.c()
       at com.facebook.react.uimanager.ea$g.b()
       at com.facebook.react.uimanager.c.a()
       at com.facebook.react.modules.core.i$b.a()
       at com.facebook.react.modules.core.a.doFrame()
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:957)
       at android.view.Choreographer.doCallbacks(Choreographer.java:734)
       at android.view.Choreographer.doFrame(Choreographer.java:667)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```
 

React Native version:

```
System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 2.31 GB / 7.65 GB
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    npm: 6.13.6 - ~/.nvm/versions/node/v10.17.0/bin/npm
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google Play Intel x86 Atom
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4
```

**Comment by hramos** [comment]
Can you provide more details? Without seeing the code, it's unlikely folks will be able to help.

**Comment by ProMasoud** [comment]
problem fixed.
the problem is from `<ImageBackground />` component with `defaultSource` prop.
I removed that and problem fixed.
seems that `defaultSource` not worked in lower android versions.

**Comment by juanamd** [comment]
I'm experiencing the same issue when using `defaultSource` prop on `<ImageBackground />`.
Got some production crash reports, all from Android 7.0.
Currently using React Native version 0.62.2. This exception was not logged on previous versions of my app using React Native 0.61.5, so it may be something related to a change made in the latest version.
I would appreciate if the issue is reopened as "excluding it from lower android versions" is not an ideal fix.
