### ISSUE TITLE
Error during deployement

### ISSUE THREAD

**Issue by rafibhatty** [facebook/react-native#27987]
After running the command "react-native run-android" I've got an error:
"warn The following packages use deprecated "rnpm" config that will stop working from next release:   - react-native-maps: https://github.com/react-native-community/react-native-maps#readme Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide. info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag. Jetifier found 1579 file(s) to forward-jetify. Using 4 workers... info Starting JS server... info Installing the app... The system cannot find the path specified. Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain  error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details. Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 The system cannot find the path specified. Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain      at checkExecSyncError (child_process.js:616:11)     at execFileSync (child_process.js:634:13)     at runOnAllDevices (G:\VW & MT\VW\Parent App\vw\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:74:39)     at buildAndRun (G:\VW & MT\VW\Parent App\vw\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)     at then.result (G:\VW & MT\VW\Parent App\vw\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12)     at process._tickCallback (internal/process/next_tick.js:68:7)" 
then I run the command "./gradlew clean" which shows the error: 
"The system cannot find the path specified. Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain". 
Kindly tell me how can I fix this issue, react-native version 0.6, also I can't upgrade my version due to some reason

**Comment by rafibhatty** [comment]
After running the command react-native info:
React native version 0.6
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-maps: https://github.com/react-native-community/react-native-maps#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
info Fetching system and libraries information...
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 3.75 GB / 7.92 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832
