### ISSUE TITLE
Changing Bundle Location results in Crash and an unlaunchable Application that keeps crashing

### ISSUE THREAD

**Issue by danhil1981** [facebook/react-native#28184]
## Description:

When I try to change bundle location from within my application in the debug menu, my application immediately crashes. Restarting the App also will not work, as it basically crashes on startup. Sometimes I will even get an android system message saying that the App keeps crashing.

The only way to get it working again is to recompile using react-native run-android another time.

Note: This stopped working a couple of weeks ago, and worked fine up to that point.

## React Native version:

info Fetching system and libraries information...
System:
    OS: Windows 10
    CPU: (2) x64 AMD A9-9410 RADEON R5, 5 COMPUTE CORES 2C+3G
    Memory: 2.40 GB / 6.91 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2

## Steps To Reproduce

1. run react-native run-android --variant==debug
2. Once the app  has loaded, shake the device
3. Select the "Change Bundle Location" option from the menu
4. Input IP Address of Dev Machine (both the Phone and the Dev Machine are utilizing the same WiFi network)
5. Crash

## Expected Results

I expect the application to load my code from the bundle via WiFi

**Comment by danhil1981** [comment]
Output of adb logcat *:E

02-27 12:13:40.563  5441  5441 E ProActiveLaunch: Sending Broadcast
02-27 12:13:40.567  4078  4333 E ActivityManager: TouchDown intent received, starting ActiveLaunch
02-27 12:13:40.585  5441  5441 E TrayManager: TrayManagerImp:trayMoveStart()
02-27 12:13:40.590  5441  5441 E LiveIconManager: createLiveIconBitmap : com.sec.android.app.clockpackage apps size 1
02-27 12:13:40.590 21247 21247 E Zygote  : isWhitelistProcess - Process is Whitelisted
02-27 12:13:40.591 21247 21247 E Zygote  : accessInfo : 5
02-27 12:13:40.591 21247 21247 E Zygote  : isSdpEnabledProcess - SDP enabled
02-27 12:13:40.591 21247 21247 E Zygote  : setSDPgroupsIntarray[pid]: 0 / [gid]: 10164 / [uid]: 10164
02-27 12:13:40.605 21247 21247 E id.app.sbrowse: Not starting debugger since process cannot load the jdwp agent.
02-27 12:13:40.625  5441  5441 E LiveIconManager: createLiveIconBitmap : com.samsung.android.calendar apps size 1
02-27 12:13:40.732 21247 21247 E ReflectField: Incorrect type : Fallback exception
02-27 12:13:40.732 21247 21247 E ReflectField: Incorrect type : Fallback exception
02-27 12:13:40.736 21247 21247 E ReflectMethod: Cannot load method: com.samsung.android.feature.SemCscFeature.getEnableStatus [class java.lang.String]
02-27 12:13:40.736 21247 21247 E ReflectMethod: Cannot load method: com.samsung.android.feature.SemCscFeature.getEnableStatus [class java.lang.String, boolean]
02-27 12:13:40.737 21247 21247 E ReflectMethod: Cannot load method: com.samsung.android.feature.SemFloatingFeature.getEnableStatus [class java.lang.String]
02-27 12:13:40.760  5441  5441 E TrayManager: TrayManagerImp:trayMoveEnd() stageMode: 2
02-27 12:13:40.768 19824 20839 E DeviceStateChecker: DeviceStateChecker cancelled
02-27 12:13:40.797 19824 19980 E AudioSource: Stop listening is called on already closed AudioSource
02-27 12:13:44.074  5441  5441 E LiveIconManager: createLiveIconBitmap : com.sec.android.app.clockpackage apps size 1
02-27 12:13:44.100 21278 21278 E Zygote  : isWhitelistProcess - Process is Whitelisted
02-27 12:13:44.103 21278 21278 E Zygote  : accessInfo : 1
02-27 12:13:44.125 21278 21278 E droid.apps.doc: Not starting debugger since process cannot load the jdwp agent.
02-27 12:13:44.128 21285 21285 E Zygote  : isWhitelistProcess - Process is Whitelisted
02-27 12:13:44.130 21285 21285 E Zygote  : accessInfo : 1
02-27 12:13:44.157 21285 21285 E id.partnersetu: Not starting debugger since process cannot load the jdwp agent.
02-27 12:13:44.274  5441  5441 E ProActiveLaunch: Sending Broadcast
02-27 12:13:44.280  4078  4333 E ActivityManager: TouchDown intent received, starting ActiveLaunch
02-27 12:13:44.300 21315 21315 E Zygote  : isWhitelistProcess - Process is Whitelisted
02-27 12:13:44.301 21315 21315 E Zygote  : accessInfo : 1
02-27 12:13:44.452  5311  5430 E SDHMS:SDHMS_UTIL_IO: e = /sys/class/input_booster/touchkey/time (Permission denied)
02-27 12:13:44.453  5311  5430 E SDHMS:SDHMS_UTIL_IO: e = /sys/class/input_booster/touchkey/time (Permission denied)
02-27 12:13:44.455  5311  5430 E SDHMS:SDHMS_UTIL_IO: e = /sys/class/input_booster/touchkey/time (Permission denied)
02-27 12:13:44.644  3657  5880 E BufferQueueProducer: [com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity[5441]#0] disconnect: not connected (req=1)
02-27 12:13:44.653  4078  7696 E WindowManager: win=Window{18f5d77 u0 com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8 caller=com.android.server.wm.WindowManagerService.tryStartExitingAnimation:2759 com.android.server.wm.WindowManagerService.relayoutWindow:2456 com.android.server.wm.Session.relayoutForTranslate:302 android.view.IWindowSession$Stub.onTransact:518 com.android.server.wm.Session.onTransact:186 android.os.Binder.execTransact:739 <bottom of call stack>
02-27 12:13:45.070 21315 21387 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
02-27 12:13:45.070 21315 21387 E AndroidRuntime: Process: com.traceapp, PID: 21315
02-27 12:13:45.070 21315 21387 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
02-27 12:13:45.070 21315 21387 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:354)
02-27 12:13:45.070 21315 21387 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
02-27 12:13:45.070 21315 21387 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
02-27 12:13:45.070 21315 21387 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
02-27 12:13:45.070 21315 21387 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-27 12:13:45.070 21315 21387 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-27 12:13:45.070 21315 21387 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
02-27 12:13:45.070 21315 21387 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Invalid URL port: " 8081"
02-27 12:13:45.070 21315 21387 E AndroidRuntime:        at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1397)
02-27 12:13:45.070 21315 21387 E AndroidRuntime:        at okhttp3.HttpUrl.get(HttpUrl.java:916)
02-27 12:13:45.070 21315 21387 E AndroidRuntime:        at okhttp3.Request$Builder.url(Request.java:165)
02-27 12:13:45.070 21315 21387 E AndroidRuntime:        at com.facebook.react.packagerconnection.ReconnectingWebSocket.connect(ReconnectingWebSocket.java:70)
02-27 12:13:45.070 21315 21387 E AndroidRuntime:        at com.facebook.react.packagerconnection.JSPackagerClient.init(JSPackagerClient.java:88)
02-27 12:13:45.070 21315 21387 E AndroidRuntime:        at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:209)
02-27 12:13:45.070 21315 21387 E AndroidRuntime:        at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:156)
02-27 12:13:45.070 21315 21387 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:333)
02-27 12:13:45.070 21315 21387 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-27 12:13:45.070 21315 21387 E AndroidRuntime:        ... 3 more
02-27 12:13:45.076 21315 21315 E AndroidRuntime: FATAL EXCEPTION: main
02-27 12:13:45.076 21315 21315 E AndroidRuntime: Process: com.traceapp, PID: 21315
02-27 12:13:45.076 21315 21315 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.traceapp/com.traceapp.MainActivity}: java.lang.IllegalArgumentException: Invalid URL port: " 8081"
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7078)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
02-27 12:13:45.076 21315 21315 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Invalid URL port: " 8081"
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1397)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at okhttp3.HttpUrl.get(HttpUrl.java:916)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at okhttp3.Request$Builder.url(Request.java:165)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at com.facebook.react.devsupport.DevServerHelper.isPackagerRunning(DevServerHelper.java:485)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at com.facebook.react.devsupport.DevSupportManagerImpl.isPackagerRunning(DevSupportManagerImpl.java:870)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.recreateReactContextInBackgroundInner(ReactInstanceManager.java:378)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.createReactContextInBackground(ReactInstanceManager.java:344)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:397)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:363)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:102)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:88)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:83)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:44)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7327)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7318)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101)
02-27 12:13:45.076 21315 21315 E AndroidRuntime:        ... 11 more
02-27 12:13:45.888 21420 21420 E Zygote  : isWhitelistProcess - Process is Whitelisted
02-27 12:13:45.889 21420 21420 E Zygote  : accessInfo : 1
02-27 12:13:45.898 21420 21420 E .android.video: Not starting debugger since process cannot load the jdwp agent.
02-27 12:13:46.188 21455 21455 E Zygote  : isWhitelistProcess - Process is Whitelisted
02-27 12:13:46.189 21455 21455 E Zygote  : accessInfo : 1
02-27 12:13:46.198 21455 21455 E e.process.gapp: Not starting debugger since process cannot load the jdwp agent.
02-27 12:13:46.267  4078  4099 E libprocessgroup: Failed to kill process cgroup uid 10048 pid 18163 in 215ms, 1 processes remain
02-27 12:13:46.376  3656  3656 E lmkd    : Error writing /proc/18163/oom_score_adj; errno=22
02-27 12:13:46.860  4078  4099 E libprocessgroup: Failed to kill process cgroup uid 5004 pid 20624 in 209ms, 1 processes remain
02-27 12:13:47.411 21496 21496 E Zygote  : isWhitelistProcess - Process is Whitelisted
02-27 12:13:47.412 21496 21496 E Zygote  : accessInfo : 1
02-27 12:13:48.038 21496 21516 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
02-27 12:13:48.038 21496 21516 E AndroidRuntime: Process: com.traceapp, PID: 21496
02-27 12:13:48.038 21496 21516 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
02-27 12:13:48.038 21496 21516 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:354)
02-27 12:13:48.038 21496 21516 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
02-27 12:13:48.038 21496 21516 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
02-27 12:13:48.038 21496 21516 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
02-27 12:13:48.038 21496 21516 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-27 12:13:48.038 21496 21516 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-27 12:13:48.038 21496 21516 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
02-27 12:13:48.038 21496 21516 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Invalid URL port: " 8081"
02-27 12:13:48.038 21496 21516 E AndroidRuntime:        at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1397)
02-27 12:13:48.038 21496 21516 E AndroidRuntime:        at okhttp3.HttpUrl.get(HttpUrl.java:916)
02-27 12:13:48.038 21496 21516 E AndroidRuntime:        at okhttp3.Request$Builder.url(Request.java:165)
02-27 12:13:48.038 21496 21516 E AndroidRuntime:        at com.facebook.react.packagerconnection.ReconnectingWebSocket.connect(ReconnectingWebSocket.java:70)
02-27 12:13:48.038 21496 21516 E AndroidRuntime:        at com.facebook.react.packagerconnection.JSPackagerClient.init(JSPackagerClient.java:88)
02-27 12:13:48.038 21496 21516 E AndroidRuntime:        at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:209)
02-27 12:13:48.038 21496 21516 E AndroidRuntime:        at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:156)
02-27 12:13:48.038 21496 21516 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:333)
02-27 12:13:48.038 21496 21516 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-27 12:13:48.038 21496 21516 E AndroidRuntime:        ... 3 more
02-27 12:13:48.040 21496 21496 E AndroidRuntime: FATAL EXCEPTION: main
02-27 12:13:48.040 21496 21496 E AndroidRuntime: Process: com.traceapp, PID: 21496
02-27 12:13:48.040 21496 21496 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.traceapp/com.traceapp.MainActivity}: java.lang.IllegalArgumentException: Invalid URL port: " 8081"
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7078)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
02-27 12:13:48.040 21496 21496 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Invalid URL port: " 8081"
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1397)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at okhttp3.HttpUrl.get(HttpUrl.java:916)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at okhttp3.Request$Builder.url(Request.java:165)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at com.facebook.react.devsupport.DevServerHelper.isPackagerRunning(DevServerHelper.java:485)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at com.facebook.react.devsupport.DevSupportManagerImpl.isPackagerRunning(DevSupportManagerImpl.java:870)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.recreateReactContextInBackgroundInner(ReactInstanceManager.java:378)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.createReactContextInBackground(ReactInstanceManager.java:344)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:397)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:363)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:102)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:88)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:83)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:44)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7327)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7318)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101)
02-27 12:13:48.040 21496 21496 E AndroidRuntime:        ... 11 more
02-27 12:13:48.069 21521 21521 E Zygote  : isWhitelistProcess - Process is Whitelisted
02-27 12:13:48.070 21521 21521 E Zygote  : accessInfo : 1
02-27 12:13:48.427 21537 21537 E Zygote  : isWhitelistProcess - Process is Whitelisted
02-27 12:13:48.428 21537 21537 E Zygote  : accessInfo : 1
02-27 12:13:48.449 21537 21537 E ng.storyservic: Not starting debugger since process cannot load the jdwp agent.
02-27 12:13:48.708 21521 21521 E AndroidRuntime: FATAL EXCEPTION: main
02-27 12:13:48.708 21521 21521 E AndroidRuntime: Process: com.traceapp, PID: 21521
02-27 12:13:48.708 21521 21521 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.traceapp/com.traceapp.MainActivity}: java.lang.IllegalArgumentException: Invalid URL port: " 8081"
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7078)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
02-27 12:13:48.708 21521 21521 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Invalid URL port: " 8081"
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1397)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at okhttp3.HttpUrl.get(HttpUrl.java:916)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at okhttp3.Request$Builder.url(Request.java:165)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at com.facebook.react.devsupport.DevServerHelper.isPackagerRunning(DevServerHelper.java:485)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at com.facebook.react.devsupport.DevSupportManagerImpl.isPackagerRunning(DevSupportManagerImpl.java:870)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.recreateReactContextInBackgroundInner(ReactInstanceManager.java:378)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.createReactContextInBackground(ReactInstanceManager.java:344)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:397)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:363)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:102)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:88)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:83)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:44)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7327)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7318)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101)
02-27 12:13:48.708 21521 21521 E AndroidRuntime:        ... 11 more
02-27 12:13:48.715 21521 21560 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
02-27 12:13:48.715 21521 21560 E AndroidRuntime: Process: com.traceapp, PID: 21521
02-27 12:13:48.715 21521 21560 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
02-27 12:13:48.715 21521 21560 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:354)
02-27 12:13:48.715 21521 21560 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
02-27 12:13:48.715 21521 21560 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
02-27 12:13:48.715 21521 21560 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
02-27 12:13:48.715 21521 21560 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-27 12:13:48.715 21521 21560 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-27 12:13:48.715 21521 21560 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
02-27 12:13:48.715 21521 21560 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Invalid URL port: " 8081"
02-27 12:13:48.715 21521 21560 E AndroidRuntime:        at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1397)
02-27 12:13:48.715 21521 21560 E AndroidRuntime:        at okhttp3.HttpUrl.get(HttpUrl.java:916)
02-27 12:13:48.715 21521 21560 E AndroidRuntime:        at okhttp3.Request$Builder.url(Request.java:165)
02-27 12:13:48.715 21521 21560 E AndroidRuntime:        at com.facebook.react.packagerconnection.ReconnectingWebSocket.connect(ReconnectingWebSocket.java:70)
02-27 12:13:48.715 21521 21560 E AndroidRuntime:        at com.facebook.react.packagerconnection.JSPackagerClient.init(JSPackagerClient.java:88)
02-27 12:13:48.715 21521 21560 E AndroidRuntime:        at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:209)
02-27 12:13:48.715 21521 21560 E AndroidRuntime:        at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:156)
02-27 12:13:48.715 21521 21560 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:333)
02-27 12:13:48.715 21521 21560 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-27 12:13:48.715 21521 21560 E AndroidRuntime:        ... 3 more
02-27 12:13:48.740  3656  3656 E lmkd    : Error writing /proc/21521/oom_score_adj; errno=22
02-27 12:13:48.750  4078  5419 E WindowManager: win=Window{2032a0b u0 Splash Screen com.traceapp EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:870 com.android.server.wm.AppWindowToken.destroySurfaces:851 com.android.server.wm.WindowState.onExitAnimationDone:5443 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.AppWindowToken.onAnimationFinished:2398 com.android.server.wm.AppWindowToken.setVisibility:551
02-27 12:13:48.783  5311  5423 E SDHMS:SDHMS_UTIL_IO: e = /sys/class/input_booster/touchkey/time (Permission denied)
02-27 12:13:48.784  5311  5423 E SDHMS:SDHMS_UTIL_IO: e = /sys/class/input_booster/touchkey/time (Permission denied)
02-27 12:13:48.787  5311  5423 E SDHMS:SDHMS_UTIL_IO: e = /sys/class/input_booster/touchkey/time (Permission denied)
