### ISSUE TITLE
react-native init error in cmd prompt

### ISSUE THREAD

**Issue by sanketmehta7** [facebook/react-native#2846]
D:\projects>react-native init ghh
This will walk you through creating a new React Native project in D:\projects\gh
h
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)
    at node.js:951:3

**Comment by mkonicek** [comment]
React Native is not supported on Windows yet, see http://stackoverflow.com/questions/32589965/will-react-native-be-supported-by-windows
