### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: "/system/app/Chrome/Chrome.apk!/lib/armeabi-v7a/libmonochrome.so" is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by ashish12s3** [facebook/react-native#28497]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
Run `react-native info` in your terminal and copy the results here.

`react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 184.00 MB / 16.00 GB
    Shell: 3.1.0 - /usr/local/bin/fish
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6200805
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
`
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

100 % reproducible on Redmi note 4,
Android 7 

sed by java.lang.UnsatisfiedLinkError: dlopen failed: "/system/app/Chrome/Chrome.apk!/lib/armeabi-v7a/libmonochrome.so" is 32-bit instead of 64-bit
       at java.lang.Runtime.loadLibrary0(Runtime.java:977)
       at java.lang.System.loadLibrary(System.java:1530)
       at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:89)
       at org.chromium.base.library_loader.LibraryLoader.loadNowOverrideApplicationContext(LibraryLoader.java:35)
       at com.android.webview.chromium.WebViewChromiumFactoryProvider.I(WebViewChromiumFactoryProvider.java:61)
       at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(WebViewChromiumFactoryProvider.java:31)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:198)
       at android.webkit.CookieManager.getInstance(CookieManager.java:39)
       at com.facebook.react.modules.network.ForwardingCookieHandler.getCookieManager(SourceFile:3)
       at com.facebook.react.modules.network.ForwardingCookieHandler.get(SourceFile:1)
       at okhttp3.JavaNetCookieJar.loadForRequest(SourceFile:2)
       at com.facebook.react.modules.network.ReactCookieJarContainer.loadForRequest(SourceFile:2)
       at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:17)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:10)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:9)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:10)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:1)
       at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:13)
       at okhttp3.RealCall$AsyncCall.execute(SourceFile:2)
       at okhttp3.internal.NamedRunnable.run(SourceFile:3)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:760)

**Comment by zilan920** [comment]
https://github.com/facebook/react-native/issues/25923#issuecomment-594047945 
try this

**Comment by theMasix** [comment]
We have this issue on top of the Sentry crashes list! Why does it happen?
