### ISSUE TITLE
when run npx react-native run-android error shows

### ISSUE THREAD

**Issue by vimalraj9423** [facebook/react-native#28524]
## Description
I create new project by using npx react-native awesomeproject then i started run npx react-native run android

## React Native version:

error: Error: Unable to resolve module `./YellowBoxImageSource` from `node_modules\react-native\Libraries\YellowBox\UI\YellowBoxInspectorHeader.js`:

None of these files exist:
  * node_modules\react-native\Libraries\YellowBox\UI\YellowBoxImageSource(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\react-native\Libraries\YellowBox\UI\YellowBoxImageSource\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (H:\JS\react\react native\withoutexport\AwesomeProject\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (H:\JS\react\react native\withoutexport\AwesomeProject\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (H:\JS\react\react native\withoutexport\AwesomeProject\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)
    at Object.resolve (H:\JS\react\react native\withoutexport\AwesomeProject\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at H:\JS\react\react native\withoutexport\AwesomeProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (H:\JS\react\react native\withoutexport\AwesomeProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:431:18)
    at H:\JS\react\react native\withoutexport\AwesomeProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (H:\JS\react\react native\withoutexport\AwesomeProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)

## Expected Results
I want react project should run

**Comment by guhungry** [comment]
duplicated with https://github.com/facebook/react-native/issues/28519

**Comment by safaiyeh** [comment]
Hi @vimalraj9423 could you check out the issue @guhungry to see if the solution from there works for you>

**Comment by guhungry** [comment]
@safaiyeh yes, it works for me. Thanks.

**Comment by vimalraj9423** [comment]
I created new project so that is working for me. So I am not able run my
old project
