### ISSUE TITLE
Android crashed while launching after running headless task

### ISSUE THREAD

**Issue by dehypnosis** [facebook/react-native#28553]
## Description
- when app is entirely closed state
- headless task is invoked (by background notification in this case).
- trying to open the app manually crashes

### 1. headless task invoked
```
[12:50:20] D | ReactNative ▶︎ ReactInstanceManager.createReactContextInBackground()
                           └ ReactInstanceManager.attachRootViewToInstance()

[12:50:26] D | ReactNative ▶︎ [CodePush] Loading JS bundle from "assets://index.android.bundle"

[12:50:26] D | ReactNative ▶︎ ReactInstanceManager.ctor()

[12:50:26] D | ReactNative ▶︎ ReactInstanceManager.createReactContextInBackground()
                           └ ReactInstanceManager.recreateReactContextInBackgroundInner()

[12:50:27] D | ReactNative ▶︎ ReactInstanceManager.recreateReactContextInBackground()
                           └ ReactInstanceManager.runCreateReactContextOnNewThread()

[12:50:27] D | ReactNative ▶︎ ReactInstanceManager.createReactContext()

[12:50:27] D | ReactNative ▶︎ Initializing React Xplat Bridge.

[12:50:27] D | ReactNative ▶︎ Initializing React Xplat Bridge before initializeBridge

[12:50:27] D | ReactNative ▶︎ Initializing React Xplat Bridge after initializeBridge

[12:50:27] D | ReactNative ▶︎ CatalystInstanceImpl.runJSBundle()
                           └ ReactInstanceManager.setupReactContext()

[12:50:27] D | ReactNative ▶︎ CatalystInstanceImpl.initialize()

[12:50:29] D | ReactNative ▶︎ CatalystInstanceImpl.destroy() start
                           └ CatalystInstanceImpl.destroyV1() start

[12:50:30] D | ReactNativeJS ▶︎ 'notification background msg', { sentTime: 1586231426509,
                             │ ttl: 2419200,
                             │ data:
                             │ { title: '안녕 title from server',
                             │ time: '13:50:26',
                             │ body: 'body from server' },
                             │ messageId: '0:1586231427108277%686395e72087b7d4',
                             │ from: '490321196875',
                             └ collapseKey: 'PBmao4recL/kfD1kTBkUkj0IwJg=' }

[12:50:30] I | ReactNativeJS ▶︎ 'global background handler', { sentTime: 1586231426509,
                             │ ttl: 2419200,
                             │ data:
                             │ { title: '안녕 title from server',
                             │ time: '13:50:26',
                             │ body: 'body from server' },
                             │ messageId: '0:1586231427108277%686395e72087b7d4',
                             │ from: '490321196875',
                             └ collapseKey: 'PBmao4recL/kfD1kTBkUkj0IwJg=' }

[12:50:30] D | ReactNativeJS ▶︎ 'notification post', { title: '안녕 title from server (global)',
                             └ message: 'body from server' }

[12:50:30] D | ReactNative ▶︎ CatalystInstanceImpl.destroy() end
```

headless task runs successfully.

### 2. open the app.
```
[12:50:33] D | ReactNative ▶︎ ReactInstanceManager.createReactContextInBackground()

[12:50:33] D | ReactNative ▶︎ ReactInstanceManager.attachRootViewToInstance()
```

Here app crashes with below ADB log.
Seems that UIManager is not ready to attach the root view...

https://github.com/facebook/react-native/blob/v0.62.1/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java#L1103-L1121

```
04-07 12:50:33.116 17661 17661 E AndroidRuntime: FATAL EXCEPTION: main
04-07 12:50:33.116 17661 17661 E AndroidRuntime: Process: com.qmit.plco.debug, PID: 17661
04-07 12:50:33.116 17661 17661 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qmit.plco.debug/com.qmit.plco.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int com.facebook.react.bridge.UIManager.addRootView(android.view.View, com.facebook.react.bridge.WritableMap, java.lang.String)' on a null object reference
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3092)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3235)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6986)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int com.facebook.react.bridge.UIManager.addRootView(android.view.View, com.facebook.react.bridge.WritableMap, java.lang.String)' on a null object reference
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1116)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.attachRootView(ReactInstanceManager.java:796)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at com.facebook.react.ReactRootView.attachToReactInstanceManager(ReactRootView.java:620)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:407)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:370)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:103)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:90)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:85)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at com.qmit.plco.MainActivity.onCreate(MainActivity.java:23)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7326)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7317)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
04-07 12:50:33.116 17661 17661 E AndroidRuntime: 	... 11 more
```

## React Native version:
```
System:
    OS: macOS 10.15.3
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 2.68 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    react: 16.13.1
    react-native: 0.62.1
  npmGlobalPackages:
    *react-native*: Not Found
```
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. invoke headless task while app is in closed state
2. open the app

## Expected Results
app should be launched

**Comment by dehypnosis** [comment]
Headless task seems to kill catalyst right after the task finished but not the react native instance.
so launching the app while catalyst is inactive crashes...
Anyway I found a tricky workaround. for some travelers:

```
AppRegistry.registerComponent("noop", () => () => null);
let uiManagerInitialized = false;
AppRegistry.registerHeadlessTask(async () => {
  // any background logic here
  // .....

  // running empty component with tag null shows an exception
  // but the Catalyst and UIManager instances are ready by this
  if (!uiManagerInitialized) {
    AppRegistry.runApplication("noop", {rootTag: null});
    uiManagerInitialized = true;
  }
});
```

**Comment by jpudysz** [comment]
@dehypnosis thanks! Your solution worked for me. I was able to run the app from Headless task.

Still, can we get official support for this feature?

**Comment by dehypnosis** [comment]
@jpudysz i think so.. as you can see.
