### ISSUE TITLE
Impossible to run my App from usb device: Failed to install the app. Make sure you have the Android deve

### ISSUE THREAD

**Issue by mostafalaravel** [facebook/react-native#28594]
I try to run my project on my android device (S8) but I receive this error message : 
````
sudo react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 960 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...
info Installing the app...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installDebug' not found in project ':app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at makeError (/home/mostafa/code/zabbi/node_modules/execa/index.js:174:9)
    at /home/mostafa/code/zabbi/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (/home/mostafa/code/zabbi/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/usr/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:186:9)
mostafa@mostafa-XPS-L322X:~/code/zabbi$ 

````
The device is connected ! 
````
 adb devices 
List of devices attached
ce0118218c5cacd00c	device

````
But from Android studion It works very well ! I can debug using my S8 device .

Environment Information:
```
System:
OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
CPU: (4) x64 Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz
Memory: 782.87 MB / 7.35 GB
Shell: 4.4.20 - /bin/bash
Binaries:
Node: 13.12.0 - /usr/bin/node
Yarn: Not Found
npm: 6.14.4 - /usr/bin/npm
Watchman: Not Found
SDKs:
Android SDK: Not Found
IDEs:
Android Studio: Not Found
Languages:
Java: 11.0.6 - /usr/bin/javac
Python: 2.7.17 - /usr/bin/python
npmPackages:
@react-native-community/cli: Not Found
react: 16.11.0 => 16.11.0
react-native: 0.62.2 => 0.62.2
npmGlobalPackages:
react-native: Not Found
```

**Comment by Kunalpaul12** [comment]
check adb devices see if the device is listing in or not
