### ISSUE TITLE
bundling failed: Error: Unable to resolve module `module` from `/Users/MyProject/node_modules/source-map-support/source-map-support.js`: Module `module` does not exist in the Haste module map

### ISSUE THREAD

**Issue by pavanMude** [facebook/react-native#28618]
error: bundling failed: Error: Unable to resolve module module from /Users/Folder/MyProject/node_modules/source-map-support/source-map-support.js: Module module does not exist in the Haste module map

> Clear watchman watches: watchman watch-del-all.
> Delete the node_modules folder: rm -rf node_modules && npm install.
> Reset Metro Bundler cache: rm -rf /tmp/metro-bundler-cache-* or npm start -- --reset-cache.
> Remove haste cache: rm -rf /tmp/haste-map-react-native-packager-*.
> at ModuleResolver.resolveDependency (/Users/Folder/MyProject/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:183:15) at ResolutionRequest.resolveDependency (/Users/Folder/MyProject/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
> at DependencyGraph.resolveDependency (/Users/Folder/MyProject/node_modules/metro/src/node-haste/DependencyGraph.js:283:16) at Object.resolve (/Users/Folder/MyProject/node_modules/metro/src/lib/transformHelpers.js:261:42)
> at dependencies.map.result (/Users/Folder/MyProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31) at Array.map (<anonymous>) at resolveDependencies (/Users/Folder/MyProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
> at /Users/Folder/MyProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33 at Generator.next (<anonymous>) at asyncGeneratorStep (/Users/Folder/MyProject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)

I tried all the solution like the following:

- Clear watchman watches: watchman watch-del-all.
- Delete the node_modules folder: rm -rf node_modules && npm install.
- Reset Metro Bundler cache: rm -rf /tmp/metro-bundler-cache-* or npm start -- --reset-cache.
- Remove haste cache: rm -rf /tmp/haste-map-react-native-packager-*.

I even downgraded babel/core(to 7.4.4 from 7.7.7) and source-map-support(to 0.4.3 from 0.5.4 version) as per the suggestions posted in the GitHub channel, however I tried all the possible ways and of no use, still it won't seems to work. I hope I will find the solution with this question.

"react-native": "^0.59.9",
"react": "^16.8.6",

**Comment by pavanMude** [comment]
React Native Environment Info:
    System:
      OS: macOS 10.15.2
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 3.51 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v10.17.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.2, 28.0.3, 29.0.2
        System Images: android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.6 => 16.8.6 
      react-native: ^0.59.9 => 0.59.10 
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7
