### ISSUE TITLE
Not available in nexus4 Android 4.4

### ISSUE THREAD

**Issue by i7soft** [facebook/react-native#28678]
Initializing the react native new project, an error occurred under nexus 4 (Android 4.4)
Error:

> Unable to create application com.aaa.MainApplication: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created

I try issue([https://github.com/facebook/react-native/issues/9043](https://github.com/facebook/react-native/issues/9043),[https://github.com/react-native-community/react-native-camera/issues/893](https://github.com/react-native-community/react-native-camera/issues/893)),but not work for me .

## Description
```
04-18 13:45:16.151 6743-6743/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.aaa, PID: 6743
    java.lang.RuntimeException: Unable to create application com.aaa.MainApplication: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4347)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(:90)
        at d.a.m.r.<init>(:238)
        at d.a.m.s.a(:281)
        at d.a.m.u.a(:87)
        at d.a.m.u.h(:39)
        at com.aaa.MainApplication.onCreate(:53)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(:80)
        at d.a.m.r.<init>(:238) 
        at d.a.m.s.a(:281) 
        at d.a.m.u.a(:87) 
        at d.a.m.u.h(:39) 
        at com.aaa.MainApplication.onCreate(:53) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.ExceptionInInitializerError
        at okhttp3.OkHttpClient.newSslSocketFactory(:263)
        at okhttp3.OkHttpClient.<init>(:229)
        at okhttp3.OkHttpClient$Builder.build(:1015)
        at com.facebook.react.devsupport.DevServerHelper.<init>(:132)
        at com.facebook.react.devsupport.DevSupportManagerImpl.<init>(:183)
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(:80) 
        at d.a.m.r.<init>(:238) 
        at d.a.m.s.a(:281) 
        at d.a.m.u.a(:87) 
        at d.a.m.u.h(:39) 
        at com.aaa.MainApplication.onCreate(:53) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 19
        at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(:238)
        at okhttp3.internal.platform.Platform.findPlatform(:202)
        at okhttp3.internal.platform.Platform.<clinit>(:79)
        at okhttp3.OkHttpClient.newSslSocketFactory(:263) 
        at okhttp3.OkHttpClient.<init>(:229) 
        at okhttp3.OkHttpClient$Builder.build(:1015) 
        at com.facebook.react.devsupport.DevServerHelper.<init>(:132) 
        at com.facebook.react.devsupport.DevSupportManagerImpl.<init>(:183) 
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(:80) 
        at d.a.m.r.<init>(:238) 
        at d.a.m.s.a(:281) 
        at d.a.m.u.a(:87) 
        at d.a.m.u.h(:39) 
        at com.aaa.MainApplication.onCreate(:53) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
```

## React Native version:
```
System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 223.64 MB / 48.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.3 - /Users/shiqiren/.rvm/gems/ruby-2.3.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 7, 8, 9
      Build Tools: 22.0.1, 23.0.1, 26.0.2, 28.0.3, 29.0.2
      System Images: android-19 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 20.1.5948944
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_172 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.react native init aaa
2.open with android studio
3.conneted to nexus4(android 4.4)

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
example:
https://github.com/i7soft/react-native-demo-aaa

**Comment by i7soft** [comment]
I use `react native init aaa --version 0.61.2` is work for me,but not 0.62

**Comment by farwayer** [comment]
Duplicate #28481

**Comment by safaiyeh** [comment]
> Duplicate #28481

From this thread it seems that Flipper is the root cause of this. Have you tried disabling Flipper @i7soft
