### ISSUE TITLE
error: bundling failed: Error: Unable to resolve module `warnOnce` from `node_modules\react-native\Libraries\react-native\react-native-implementation.js`: warnOnce could not be found within the project.

### ISSUE THREAD

**Issue by sryze** [facebook/react-native#28681]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description

I'm trying to run a react-native app on an Android emulator/device on Windows. Every time I run it I get this error:

```
error: bundling failed: Error: Unable to resolve module `warnOnce` from `node_modules\react-native\Libraries\react-native\react-native-implementation.js`: warnOnce could not be found within the project.
```

and the app fails to load.

I tried clearing the cache and editing metro config as suggested in comments in #24065 but none of that helped.

Full output:

```
Loading dependency graph, done.

To reload the app press "r"
To open developer menu press "d"

error: bundling failed: Error: Unable to resolve module `warnOnce` from `node_modules\react-native\Libraries\react-native\react-native-implementation.js`: warnOnce could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (C:\Users\user\AppData\Roaming\npm\node_modules\react-native\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (C:\Users\user\AppData\Roaming\npm\node_modules\react-native\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (C:\Users\user\AppData\Roaming\npm\node_modules\react-native\node_modules\metro\src\node-haste\DependencyGraph.js:282:16)
    at Object.resolve (C:\Users\user\AppData\Roaming\npm\node_modules\react-native\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at dependencies.map.result (C:\Users\user\AppData\Roaming\npm\node_modules\react-native\node_modules\metro\src\DeltaBundler\traverseDependencies.js:426:31)
    at Array.map (<anonymous>)
    at resolveDependencies (C:\Users\user\AppData\Roaming\npm\node_modules\react-native\node_modules\metro\src\DeltaBundler\traverseDependencies.js:423:18)
    at C:\Users\user\AppData\Roaming\npm\node_modules\react-native\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\user\AppData\Roaming\npm\node_modules\react-native\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
 DELTA  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 1.8% (39/493), failed.
```

## React Native version:

```
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 2.91 GB / 15.94 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 19, 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 20.0.0, 21.1.2, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.2
      System Images: android-19 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 21.0.6113669
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
  npmPackages:
    react: ^16.8.3 => 16.9.0
    react-native: 0.59.0 => 0.59.0
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by sryze** [comment]
I had react-native installed globally, that was the problem
