### ISSUE TITLE
Expected URL scheme 'http' or 'https' but no colon was found

### ISSUE THREAD

**Issue by fabiocosta88** [facebook/react-native#28702]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I developed an application that through some requests by AXIOS to certain apis it presents data, the app is very simple, I have checked all links and they all start with HTTP or HTTPS .. The application works perfectly if I generate the apk in DEBUG mode , but if I create an apk release the error comes ...

```
04-20 23:11:18.022 10873 10896 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
04-20 23:11:18.022 10873 10896 E AndroidRuntime: Process: com.radarcorona, PID: 10873
04-20 23:11:18.022 10873 10896 E AndroidRuntime: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
04-20 23:11:18.022 10873 10896 E AndroidRuntime:        at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1333)
04-20 23:11:18.022 10873 10896 E AndroidRuntime:        at okhttp3.HttpUrl.get(HttpUrl.java:916)
04-20 23:11:18.022 10873 10896 E AndroidRuntime:        at okhttp3.Request$Builder.url(Request.java:165)
04-20 23:11:18.022 10873 10896 E AndroidRuntime:        at expo.modules.updates.loader.FileDownloader.addHeadersToManifestUrl(FileDownloader.java:190)
04-20 23:11:18.022 10873 10896 E AndroidRuntime:        at expo.modules.updates.loader.FileDownloader.downloadManifest(FileDownloader.java:79)
04-20 23:11:18.022 10873 10896 E AndroidRuntime:        at expo.modules.updates.loader.RemoteLoader.start(RemoteLoader.java:56)
04-20 23:11:18.022 10873 10896 E AndroidRuntime:        at expo.modules.updates.UpdatesController.lambda$start$0$UpdatesController(UpdatesController.java:307)
04-20 23:11:18.022 10873 10896 E AndroidRuntime:        at expo.modules.updates.-$$Lambda$UpdatesController$cVwvsx9XXcX6YuWbf7IvrVkJAiA.run(Unknown Source:6)
04-20 23:11:18.022 10873 10896 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)04-20 23:11:18.022 10873 10896 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-20 23:11:18.022 10873 10896 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-20 23:11:18.022 10873 10896 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:919)
04-20 23:11:18.024 10873 10894 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
04-20 23:11:18.036  2039  2882 W ActivityTaskManager:   Force finishing activity com.radarcorona/.MainActivity
```

## React Native version:
```
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
    Memory: 763.94 MB / 7.96 GB
  Binaries:
    Node: 13.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.1 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 25, 27, 28, 29
      Build Tools: 23.0.1, 25.0.2, 27.0.3, 28.0.3, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-native: ~0.61.5 => 0.61.5
```

## Expected Results
I just wanted the apk release to work just like the debug works

**Comment by fabiocosta88** [comment]
it is worth mentioning that this is a project ejected from the expo
