### ISSUE TITLE
[0.63-rc.0] Android release builds fail on new init projects

### ISSUE THREAD

**Issue by owinter86** [facebook/react-native#28700]
## Description
Building release version of the new 0.63 RC fails at the bundling JS assets

## React Native version:
Run `react-native info` in your terminal and copy the results here.
```
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 5.29 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.19.0 - /var/folders/hp/k_htq1bs5hj6lfgznwqjkk240000gn/T/yarn--1587410192816-0.5526998840886992/node
    Yarn: 1.22.4 - /var/folders/hp/k_htq1bs5hj6lfgznwqjkk240000gn/T/yarn--1587410192816-0.5526998840886992/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /Users/oliverwinter/.rvm/rubies/ruby-2.6.1/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.0-rc.0 => 0.63.0-rc.0
  npmGlobalPackages:
    *react-native*: Not Found
```
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. `npx react-native init RN063 --version 0.63.0-rc.0`
2. `yarn react-native run-android --variant=release`

```
> Task :app:bundleReleaseJsAndAssets FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
6 actionable tasks: 3 executed, 3 up-to-date
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/Users/oliverwinter/Documents/work/RN063/node_modules/@react-native-community/cli/build/bin.js
'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1
```
3. `npx react-native init RN062`
4. `yarn react-native run-android --variant=release`

Works and builds fine

## Expected Results
Building a release version of the new RC0.63 should be successful.

## Snack, code example, screenshot, or link to a repository:
Simple reproduction shown above.

**Comment by palkerecsenyi** [comment]
I'm getting an almost identical issue: https://github.com/react-native-community/upgrade-support/issues/60

**Comment by grabbou** [comment]
Definitely a regression after recent change. Has something to do with the `release` mode in Gradle. Potential place to look: https://github.com/facebook/react-native/commit/992e0ce922cee91b079f8da7ce0e03ee2780b8c8

**Comment by grabbou** [comment]
Just submitted a PR to fix this issue.
