### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfbjni.so caused by: Error: Cannot load /data/app/com.awesomeproject-pYV-AfnIEI4qPzKaeWl98Q==/lib/arm64/libfbjni.so

### ISSUE THREAD

**Issue by huaSoftware** [facebook/react-native#28750]
0.61 update to 0.62

## Description
```
04-25 17:04:32.159 13842 13869 E AndroidRuntime: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfbjni.so caused by: Error: Cannot load /data/app/com.awesomeproject-pYV-AfnIEI4qPzKaeWl98Q==/lib/arm64/libfbjni.so
04-25 17:04:32.159 13842 13869 E AndroidRuntime:        at com.facebook.soloader.SoLoader.b(Unknown Source:368)
04-25 17:04:32.159 13842 13869 E AndroidRuntime:        at com.facebook.soloader.SoLoader.a(Unknown Source:106)
04-25 17:04:32.159 13842 13869 E AndroidRuntime:        at com.facebook.soloader.SoLoader.a(Unknown Source:108)
04-25 17:04:32.159 13842 13869 E AndroidRuntime:        at com.facebook.soloader.SoLoader.a(Unknown Source:1)
04-25 17:04:32.159 13842 13869 E AndroidRuntime:        at com.facebook.soloader.l.a(Unknown Source:0)
04-25 17:04:32.159 13842 13869 E AndroidRuntime:        at com.facebook.soloader.a.a.a(Unknown Source:10)
04-25 17:04:32.159 13842 13869 E AndroidRuntime:        at com.facebook.jni.HybridData.<clinit>(Unknown Source:2)
04-25 17:04:32.159 13842 13869 E AndroidRuntime:        at com.facebook.react.bridge.WritableNativeMap.initHybrid(Native Method)
04-25 17:04:32.159 13842 13869 E AndroidRuntime:        at com.facebook.react.bridge.WritableNativeMap.<init>(Unknown Source:0)
04-25 17:04:32.159 13842 13869 E AndroidRuntime:        at com.facebook.react.jscexecutor.a.create(Unknown Source:2)
04-25 17:04:32.159 13842 13869 E AndroidRuntime:        at com.facebook.react.E.run(Unknown Source:58)
04-25 17:04:32.159 13842 13869 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:784)
```
## React Native version:
0.62

**Comment by huaSoftware** [comment]
I don't kown where is 'lib/arm64/libfbjni.so' path , debug is normal，bug release will broken

**Comment by huaSoftware** [comment]
```
 react-native info

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 1.22 GB / 7.90 GB
  Binaries:
    Node: 12.13.1 - D:\nodejs\node.EXE
    Yarn: 1.22.1 - ~\AppData\Roaming\npm\yarn.CMD        
    npm: 6.14.2 - D:\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 18, 23, 24, 26, 28
      Build Tools: 23.0.1, 27.0.3, 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom       
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
    Python: 3.7.3 - C:\Users\hua\AppData\Local\Programs\Python\Python37-32\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0
    react-native: 0.62.0 => 0.62.0
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by lgalant** [comment]
Had the same issue, in my case it was RN cache.
Fixed it by
cd android
./gradlew clean

As explained in [https://github.com/facebook/react-native/issues/28163](url)
