### ISSUE TITLE
iOS: XCode release build fails with error on @hapi/joi

### ISSUE THREAD

**Issue by azuxx** [facebook/react-native#28848]
## Description

Hello,
I am using RN 0.62.2, iOS build debug works successfully but when it comes to iOS release build with xCode I got this issue:

```
+ [[ -d /Users/andrea/.anyenv/bin ]]
+ source /Users/andrea/Documents/MyReactNativeApp/node_modules/react-native/scripts/node-binary.sh
++ '[' -z node ']'
++ type node
+ '[' -z '' ']'
+ export NODE_ARGS=
+ NODE_ARGS=
+ '[' -z '' ']'
+ export CLI_PATH=/Users/andrea/Documents/MyReactNativeApp/node_modules/react-native/cli.js
+ CLI_PATH=/Users/andrea/Documents/MyReactNativeApp/node_modules/react-native/cli.js
+ '[' -z '' ']'
+ BUNDLE_COMMAND=bundle
+ [[ -z '' ]]
+ CONFIG_ARG=
+ BUNDLE_FILE=/Users/andrea/Library/Developer/Xcode/DerivedData/MyReactNativeApp-drqnfnvotxyslbbhryzxjusahhim/Build/Products/Release-iphoneos/MyReactNativeApp.app/main.jsbundle
+ node /Users/andrea/Documents/MyReactNativeApp/node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Users/andrea/Library/Developer/Xcode/DerivedData/MyReactNativeApp-drqnfnvotxyslbbhryzxjusahhim/Build/Products/Release-iphoneos/MyReactNativeApp.app/main.jsbundle --assets-dest /Users/andrea/Library/Developer/Xcode/DerivedData/MyReactNativeApp-drqnfnvotxyslbbhryzxjusahhim/Build/Products/Release-iphoneos/MyReactNativeApp.app
/Users/andrea/Documents/MyReactNativeApp/node_modules/@hapi/joi/lib/types/object/index.js:255
                        !pattern.schema._validate(key, state, { ...options, abortEarly:true }).errors) {
                                                                ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/andrea/Documents/MyReactNativeApp/node_modules/@hapi/joi/lib/types/func/index.js:5:20)
+ [[ false != true ]]
+ [[ ! -f /Users/andrea/Library/Developer/Xcode/DerivedData/MyReactNativeApp-drqnfnvotxyslbbhryzxjusahhim/Build/Products/Release-iphoneos/MyReactNativeApp.app/main.jsbundle ]]
+ echo 'error: File /Users/andrea/Library/Developer/Xcode/DerivedData/MyReactNativeApp-drqnfnvotxyslbbhryzxjusahhim/Build/Products/Release-iphoneos/MyReactNativeApp.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/andrea/Library/Developer/Xcode/DerivedData/MyReactNativeApp-drqnfnvotxyslbbhryzxjusahhim/Build/Products/Release-iphoneos/MyReactNativeApp.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2
```

## React Native version:

```
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 556.32 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /Users/andrea/.rvm/rubies/ruby-2.5.7/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_92 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Open app .xcodeproj with XCode
2. Select target > edit scheme e set settings for Release

<img width="465" alt="Screenshot 2020-05-07 at 16 38 59" src="https://user-images.githubusercontent.com/16132913/81307789-55082700-9081-11ea-8e22-48b19888f9e5.png">

3. Click Run

## Expected Results

Build for release should succeed.

RN project package.json

```
{
  "name": "MyReactNativeApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "graphql-init": "graphql-codegen init",
    "codegen": "graphql-codegen --config codegen.yml"
  },
  "dependencies": {
    "@airbrake/browser": "^1.1.1",
    "@apollo/client": "^3.0.0-beta.44",
    "@apollo/link-error": "^2.0.0-beta.3",
    "@react-native-community/async-storage": "^1.8.1",
    "@react-native-community/datetimepicker": "^2.3.2",
    "@react-native-community/masked-view": "^0.1.7",
    "@react-navigation/bottom-tabs": "^5.2.6",
    "@react-navigation/native": "^5.1.5",
    "@react-navigation/stack": "^5.2.10",
    "babel-plugin-module-resolver": "^4.0.0",
    "base-64": "^0.1.0",
    "jetifier": "^1.6.5",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-background-timer": "^2.2.0",
    "react-native-ble-plx": "^2.0.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-localization": "^2.1.6",
    "react-native-localize": "^1.3.4",
    "react-native-paper": "^3.8.0",
    "react-native-reanimated": "^1.7.1",
    "react-native-restart": "^0.0.15",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.4.0",
    "react-native-vector-icons": "^6.6.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@graphql-codegen/cli": "^1.13.1",
    "@graphql-codegen/fragment-matcher": "1.13.1",
    "@graphql-codegen/introspection": "1.13.1",
    "@graphql-codegen/typescript": "1.13.1",
    "@graphql-codegen/typescript-operations": "1.13.1",
    "@graphql-codegen/typescript-react-apollo": "1.13.1",
    "@react-native-community/eslint-config": "^1.0.0",
    "@types/base-64": "^0.1.3",
    "@types/graphql": "14.2.3",
    "@types/jest": "^24.0.24",
    "@types/react": "^16.9.32",
    "@types/react-native": "^0.62.0",
    "@types/react-native-background-timer": "^2.0.0",
    "@types/react-native-dotenv": "^0.2.0",
    "@types/react-test-renderer": "16.9.2",
    "@typescript-eslint/eslint-plugin": "^2.25.0",
    "@typescript-eslint/parser": "^2.25.0",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "eslint-import-resolver-babel-module": "^5.1.2",
    "eslint-plugin-import": "^2.20.2",
    "graphql-tag": "^2.10.3",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "prettier": "^2.0.2",
    "react-native-dotenv": "^0.2.0",
    "react-test-renderer": "16.11.0",
    "typescript": "^3.8.3"
  },
  "resolutions": {
    "graphql": "^14.5.8"
  },
  "postinstall": "npx jetify",
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}
```

Let me know if more information is needed and I will try to add detail the best that I can.
Thank you very much

**Comment by azuxx** [comment]
Tried the tentative fix suggested but I am still running the issue

**Comment by azuxx** [comment]
Do you have any updates about this? I cannot release the app to my client 😞
