### ISSUE TITLE
App crash in release mode

### ISSUE THREAD

**Issue by C4i81** [facebook/react-native#28869]
## Description
App crash in release mode,I am using ViewPropTypes.style

## React Native version:

System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.16 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/opt/node@12/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/opt/node@12/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 15, 20, 22, 23, 25, 26, 27, 28, 29
      Build Tools: 25.0.0, 25.0.3, 26.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 30.0.0
      System Images: android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_77 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.9.0 => 16.13.1 
    react-native: ^0.62.0 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
debug package are good,release package will crash,crash info:

2020-05-11 15:15:02.501 18315-18342/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: XXX.XXXX.XXXX, PID: 18315
    com.facebook.react.common.JavascriptException: TypeError: undefined is not an object (evaluating 'P.default.propTypes.style'), stack:
    <unknown>@1383:4526
    v@2:1473
    <unknown>@1373:241
    v@2:1473
    <unknown>@1372:254
    v@2:1473
    <unknown>@1369:325
    v@2:1473
    <unknown>@1367:339
    v@2:1473
    <unknown>@1363:156
    v@2:1473
    <unknown>@451:189
    v@2:1473
    <unknown>@396:143
    v@2:1473
    <unknown>@6:57
    v@2:1473
    d@2:875
    global code@1429:3
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:79)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:201)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:764)

## Expected Results
release package runs good.

**Comment by hasgardee** [comment]
any fix?

**Comment by C4i81** [comment]
> any fix?
