### ISSUE TITLE
[CI] - test-android-run-instrumentation various errors

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [facebook/react-native#28870]
## Description
[`yarn run test-android-run-instrumentation`](https://github.com/facebook/react-native/blob/master/.circleci/DockerTests.md) fails with the following error:

```shell
Installing apk on emulator-5554 (2PW3dRC1).
Parsing buck files: finished in 2.0 sec
Creating action graph: finished in 0.6 sec
Building: finished in 27.5 sec (100%) 518/518 jobs, 243 updated
  Total time: 29.1 sec
Installing... 7.4 sec
BUILD FAILED: Failed to install apk on emulator-5554 (2PW3dRC1).
com.android.ddmlib.InstallException: Unknown failure 
(Error: Could not access the Package Manager.  Is the system running?)
```

The below code may be related to following script:
https://github.com/facebook/react-native/blob/b65b00ab6b3f414c57604bba5f91240caa0b8e72/.circleci/Dockerfiles/scripts/run-android-docker-instrumentation-tests.sh#L13-L17

I replaced the code above, which would not work (errors `-t` option invalid, package does not exist). I replaced in `AVD_PACKAGE` the value `default` with `google_apis` to solve error `This AVD’s configuration is missing a kernel file!`.

```shell
AVD_ABI="armeabi-v7a"
AVD_PACKAGE="system-images;android-19;google_apis;$AVD_ABI"
# create virtual device
sdkmanager --install "$AVD_PACKAGE"
echo no | avdmanager create avd --name "$AVD_UUID" --force --package "$AVD_PACKAGE"
# emulator setup
emulator -avd $AVD_UUID -no-audio -no-window -no-boot-anim &
```

I also tried to follow this approach to run tests, none of the worked for the Android Buck tests:

1. Install react-native from master and running the tests. Several Android tests fail after following [the instructions](https://github.com/facebook/react-native/wiki/Tests#running-tests) (I gave up troubleshooting the scripts in favour of Docker).
2. Install `circleci` locally and run tests, experienced issues with this configuration. 
https://github.com/facebook/react-native/blob/b65b00ab6b3f414c57604bba5f91240caa0b8e72/.circleci/config.yml#L14
CircleCI can not create a folder in `./reports` (I give up in favour of Docker solution).
https://github.com/facebook/react-native/blob/b65b00ab6b3f414c57604bba5f91240caa0b8e72/.circleci/config.yml#L68-L72
3. Add `circleci` to my github fork, but android test require me to Upgrade my CircleCI membership (I'll consider upgrading).
4. I am also trying the Docker solution on MacOS.

I decided to open this issue to receive some feedback, keep track of the changes I did to the docker scripts and analyze log errors. Hopefully I'll fix these and write myself the pull request, in the meanwhile I'll use `react-native` github repo to run the test suite.

## React Native version:
```
System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 1.08 GB / 15.53 GB
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 12.16.3 - /tmp/yarn--1589202475501-0.4262218330483851/node
    Yarn: 1.22.4 - /tmp/yarn--1589202475501-0.4262218330483851/yarn
    npm: 6.14.4 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 19, 22, 23, 28, 29
      Build Tools: 20.0.0, 23.0.1, 28.0.3, 29.0.2, 29.0.3
      System Images: android-19 | ARM EABI v7a, android-19 | Google APIs ARM EABI v7a, android-19 | Google APIs Intel x86 Atom, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: 17.2.4988734
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
  Languages:
    Java: 11.0.7 - /usr/bin/javac
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.7.0 => 4.7.0
    react: 16.13.1 => 16.13.1
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
Done in 5.18s.
```

## Steps To Reproduce
The steps are the same explained in the [docs](https://github.com/facebook/react-native/blob/master/.circleci/DockerTests.md)

1. Install Docker
2. `git clone https://github.com/facebook/react-native`
3. `cd react-native`
4. `yarn run docker-setup-android`
5. `yarn run docker-build-android`
6. `yarn run test-android-run-instrumentation`

## Expected Results
No Errors - Test Pass

## Actual Result/Log Output

The output of running `yarn run test-android-run-instrumentation` triggers the following errors:

```
mount: cannot remount shm read-write, is write-protected
```
https://github.com/facebook/react-native/blob/b65b00ab6b3f414c57604bba5f91240caa0b8e72/.circleci/Dockerfiles/scripts/run-android-docker-instrumentation-tests.sh#L8

Emulator starts without any serious issue
```shell
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Warning: File /opt/android/.android/repositories.cfg could not be loaded.
[=======================================] 100% Unzipping... armeabi-v7a/system.i
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Auto-selecting single ABI armeabi-v7a===] 100% Fetch remote repository...
Do you wish to create a custom hardware profile? [no] statvfs('/opt/android/.android/avd/2PW3dRC1.avd/snapshots/default_boot/ram.img') failed: No such file or directory
emulator: WARNING: encryption is off
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"
```
Boot Animation ends
```shell
boot animation status=* daemon not running; starting now at tcp:5037
* daemon started successfully
error: device offline
boot animation status=
boot animation status=stopped
```
The below commands fail because **watchman is not installed in the docker image**.
```shell
+ echo 65536
+ tee -a /proc/sys/fs/inotify/max_user_watches
tee: /proc/sys/fs/inotify/max_user_watches: Read-only file system
65536
+ watchman shutdown-server
.circleci/Dockerfiles/scripts/run-android-docker-instrumentation-tests.sh: line 34: watchman: command not found
```

Integration tests
Build JS bundle for instrumentation tests
ReactNative installed sucessfully.
```shell
+ node cli.js bundle --platform android --dev true --entry-file ReactAndroid/src/androidTest/js/TestBundle.js --bundle-output ReactAndroid/src/androidTest/assets/AndroidTestBundle.js
                 Welcome to React Native!
                Learn once, write anywhere
info Writing bundle output to:, ReactAndroid/src/androidTest/assets/AndroidTestBundle.js
info Done writing bundle output
warn Assets destination folder is not set, skipping...
+ source ./scripts/android-setup.sh
++ source scripts/.tests.env
+++ export ANDROID_SDK_BUILD_TOOLS_REVISION=29.0.2
+++ ANDROID_SDK_BUILD_TOOLS_REVISION=29.0.2
+++ export ANDROID_SDK_BUILD_API_LEVEL=28
+++ ANDROID_SDK_BUILD_API_LEVEL=28
+++ export ANDROID_GOOGLE_API_LEVEL=23
+++ ANDROID_GOOGLE_API_LEVEL=23
+++ export ANDROID_SDK_TARGET_API_LEVEL=19
+++ ANDROID_SDK_TARGET_API_LEVEL=19
+++ export AVD_NAME=testAVD
+++ AVD_NAME=testAVD
+++ export AVD_ABI=x86
+++ AVD_ABI=x86
+++ export IOS_TARGET_OS=13.3
+++ IOS_TARGET_OS=13.3
+++ export 'IOS_DEVICE=iPhone 8'
+++ IOS_DEVICE='iPhone 8'
+++ export 'TVOS_DEVICE=Apple TV'
+++ TVOS_DEVICE='Apple TV'
+++ export SDK_IOS=iphonesimulator
+++ SDK_IOS=iphonesimulator
+++ '[' ']'
+ NO_BUCKD=1
+ retry3 buck install ReactAndroid/src/androidTest/buck-runner:instrumentation-tests --config build.threads=1
+ local n=1
+ local max=3
+ local delay=1
+ true
+ buck install ReactAndroid/src/androidTest/buck-runner:instrumentation-tests --config build.threads=1
Not using buckd because NO_BUCKD is set.
...MORE IRRELEVANT LOGS
```
**Failed to build install the app in the emulator**, 
**ERROR Could not access the Package Manager.**

```shell
Installing apk on emulator-5554 (2PW3dRC1).
Parsing buck files: finished in 2.0 sec
Creating action graph: finished in 0.6 sec
Building: finished in 27.5 sec (100%) 518/518 jobs, 243 updated
  Total time: 29.1 sec
Installing... 7.4 sec
BUILD FAILED: Failed to install apk on emulator-5554 (2PW3dRC1).
com.android.ddmlib.InstallException: 
Unknown failure (Error: Could not access the Package Manager.  Is the system running?)
        at com.android.ddmlib.Device.installRemotePackage(Device.java:978)
        at com.android.ddmlib.Device.installPackage(Device.java:885)
        at com.facebook.buck.android.exopackage.RealAndroidDevice.installApkOnDevice(RealAndroidDevice.java:535)
        at com.facebook.buck.android.exopackage.AndroidDevice.installApkOnDevice(AndroidDevice.java:29)
        at com.facebook.buck.android.AdbHelper.lambda$installApkDirectly$7(AdbHelper.java:666)
        at com.facebook.buck.android.AdbHelper.lambda$adbCall$0(AdbHelper.java:181)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:127)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Failed to install apk //ReactAndroid/src/androidTest/buck-runner:instrumentation-tests on 1 device(s).
```
The error is caused from the command [`buck install`](https://buck.build/command/install.html)

```
NO_BUCKD=1 retry3 buck install ReactAndroid/src/androidTest/buck-runner:instrumentation-tests --config build.threads=1
```

**Comment by fabriziobertoglio1987** [comment]
I changed the script as follow, in brief I am using the latest `android-29` image `x86_64` as I read that `buck install` does not work properly with older versions

```
#!/bin/bash
AVD_UUID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)
AVD_ABI="x86_64"
AVD_PACKAGE="system-images;android-29;google_apis;$AVD_ABI"
sdkmanager --install "$AVD_PACKAGE"
echo no | avdmanager create avd --name "$AVD_UUID" --force --package "$AVD_PACKAGE"
emulator -avd $AVD_UUID -no-audio -no-window -no-boot-anim &
bootanim=""
until [[ "$bootanim" =~ "stopped" ]]; do
    sleep 5
    bootanim=$(adb -e shell getprop init.svc.bootanim 2>&1)
    echo "boot animation status=$bootanim"
done

set -x

# solve issue with max user watches limit
echo 65536 | tee -a /proc/sys/fs/inotify/max_user_watches
watchman shutdown-server

# integration tests
# build JS bundle for instrumentation tests
node cli.js bundle --platform android --dev true --entry-file ReactAndroid/src/androidTest/js/TestBundle.js --bundle-output ReactAndroid/src/androidTest/assets/AndroidTestBundle.js
# shellcheck disable=SC1091
buck fetch ReactAndroid/src/test/...
source ./scripts/android-setup.sh && NO_BUCKD=1 retry3 buck install ReactAndroid/src/androidTest/buck-runner:instrumentation-tests --config build.threads=1
buck install ReactAndroid/src/androidTest/buck-runner:instrumentation-tests
# run installed apk with tests
node ./.circleci/Dockerfiles/scripts/run-android-ci-instrumentation-tests.js "$*"
exit $?
```
The Following Output is green 
```
Installing apk on emulator-5554 (7A6oZAmE).
Successfully ran install apk //ReactAndroid/src/androidTest/buck-runner:instrumentation-tests on 1 device(s)
Parsing buck files: finished in 2.1 sec
Creating action graph: finished in 0.7 sec
Building: finished in 1.0 sec (100%) 3/3 jobs, 0 updated
  Total time: 2.6 sec
Installing: finished in 27.8 sec
+ break
+ buck install ReactAndroid/src/androidTest/buck-runner:instrumentation-tests
Invalidating internal cached state: Buck configuration options changed between invocations. This may cause slower builds.
  Removed value download.in_build='true'
Installing apk on emulator-5554 (7A6oZAmE).
Successfully ran install apk //ReactAndroid/src/androidTest/buck-runner:instrumentation-tests on 1 device(s)
Parsing buck files: finished in 1.2 sec
Building: finished in 0.1 sec (100%) 3/3 jobs, 0 updated
  Total time: 0.8 sec
Installing: finished in 13.7 sec
```
Then `./.circleci/Dockerfiles/scripts/run-android-ci-instrumentation-tests.js` crashes with error ` Error=Unable to find instrumentation info for: ComponentInfo{com.facebook.react.tests/android.support.test.runner.AndroidJUnitRunner}`
```
+ node ./.circleci/Dockerfiles/scripts/run-android-ci-instrumentation-tests.js ''
android.util.AndroidException: INSTRUMENTATION_FAILED: com.facebook.react.tests/android.support.test.runner.AndroidJUnitRunner
        at com.android.commands.am.Instrument.run(Instrument.java:514)
        at com.android.commands.am.Am.runInstrument(Am.java:196)
        at com.android.commands.am.Am.onRun(Am.java:80)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:56)
        at com.android.commands.am.Am.main(Am.java:50)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)

INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.facebook.react.tests/android.support.test.runner.AndroidJUnitRunner}
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS_CODE: -1

--------- beginning of main
05-11 17:13:38.167  5248  5307 E PhenotypeFlagCommitter: Retrieving snapshot for com.google.android.calendar failed
05-11 17:13:38.167  5248  5307 E PhenotypeFlagCommitter: java.util.concurrent.TimeoutException: Timed out waiting for Task
05-11 17:13:38.167  5248  5307 E PhenotypeFlagCommitter:        at com.google.android.gms.tasks.Tasks.await(Tasks.java:127)

```
