### ISSUE TITLE
Doing npx react-native init AwesomeProject and then npm install fails.

### ISSUE THREAD

**Issue by tanapaydin** [facebook/react-native#28908]
Following this page: https://reactnative.dev/docs/environment-setup

## Description
An empty project initialization fails. This probably is related to fsevents but I don't know which library in ReactNative initialization uses it, and needs to update the dependency version or something..

# XCode 11.4.1
# MacOS Catalina
  OS 10.15.4

## React Native version:
info Fetching system and libraries information...
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 7.25 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.12.0 - ~/.nvm/versions/node/v10.12.0/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.12.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_181 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. npx react-native init AwesomeProject 
2. npm install ===> Fails!!!

## Expected Results
Run successfully

## Snack, code example, screenshot, or link to a repository:

Here is the partially output:

ld: warning: building for macOS, but linking in .tbd file (/usr/lib/system/libsystem_kernel.dylib) built for iOS Simulator
ld: warning: building for macOS, but linking in .tbd file (/usr/lib/system/libsystem_platform.dylib) built for iOS Simulator
ld: warning: building for macOS, but linking in .tbd file (/usr/lib/system/libsystem_pthread.dylib) built for iOS Simulator
  CXX(target) Release/obj.target/fse/fsevents.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
In file included from ../fsevents.cc:72:
../src/thread.cc:36:25: error: unknown type name 'ConstFSEventStreamRef'
void HandleStreamEvents(ConstFSEventStreamRef stream, void *ctx, size_t numEvents, void *eventPaths, const FSEventStreamEventFlags eventFlags[], const FSEventStreamEventId eventIds[]) {
                        ^
../src/thread.cc:36:108: error: unknown type name 'FSEventStreamEventFlags'
void HandleStreamEvents(ConstFSEventStreamRef stream, void *ctx, size_t numEvents, void *eventPaths, const FSEventStreamEventFlags eventFlags[], const FSEventStreamEventId eventIds[]) {
                                                                                                           ^
../src/thread.cc:36:152: error: unknown type name 'FSEventStreamEventId'
void HandleStreamEvents(ConstFSEventStreamRef stream, void *ctx, size_t numEvents, void *eventPaths, const FSEventStreamEventFlags eventFlags[], const FSEventStreamEventId eventIds[]) {
                                                                                                                                                       ^
../src/thread.cc:54:3: error: unknown type name 'FSEventStreamContext'
  FSEventStreamContext context = { 0, ctx, NULL, NULL, NULL };
  ^
../src/thread.cc:56:3: error: unknown type name 'FSEventStreamRef'
  FSEventStreamRef stream = FSEventStreamCreate(NULL, &HandleStreamEvents, &context, fse->paths, kFSEventStreamEventIdSinceNow, (CFAbsoluteTime) 0.1, kFSEventStreamCreateFlagNone | kFSEventStreamCreateFlagWatchRoot | kFSEventStreamCreateFlagFileEvents | kFSEvent...
  ^
../src/thread.cc:56:98: error: use of undeclared identifier 'kFSEventStreamEventIdSinceNow'
  FSEventStreamRef stream = FSEventStreamCreate(NULL, &HandleStreamEvents, &context, fse->paths, kFSEventStreamEventIdSinceNow, (CFAbsoluteTime) 0.1, kFSEventStreamCreateFlagNone | kFSEventStreamCreateFlagWatchRoot | kFSEventStreamCreateFlagFileEvents | kFSEvent...
                                                                                                 ^
6 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/tan/.nvm/versions/node/v10.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Users/tan/.nvm/versions/node/v10.12.0/bin/node" "/Users/tan/.nvm/versions/node/v10.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tan/git/react_learning/BBN_T2test/node_modules/fsevents
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> core-js@2.6.11 postinstall /Users/tan/git/react_learning/BBN_T2test/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> react-native-router-flux@4.2.0 postinstall /Users/tan/git/react_learning/BBN_T2test/node_modules/react-native-router-flux
> opencollective postinstall || exit 0

**Comment by tanapaydin** [comment]
Looks like if I delete the package-lock.json file, and then npm install again, the issue is resolved.
