### ISSUE TITLE
No bundle URL present with react-native init app inside a lerna monorepo.

### ISSUE THREAD

**Issue by tettoffensive** [facebook/react-native#28903]
Creating a brand new react-native project in my root folder and launching the iOS app in the simulator works fine on my system. But when I try to create a fresh project the same way inside my monorepo which uses [lerna](https://github.com/lerna/lerna), I get an error when trying to launch the iOS app - `No bundle URL present` I've seen this error mentioned in other issues, but the solutions they've tried don't seem to apply here.

```shell
react-native info
warn Package react-test-renderer has been ignored because it contains invalid configuration. Reason: Cannot find module 'react-test-renderer/package.json'
Require stack:
- ~/my-monorepo/packages/mobile/node_modules/@react-native-community/cli/build/tools/config/resolveNodeModuleDir.js
- ~/my-monorepo/packages/mobile/node_modules/@react-native-community/cli/build/tools/releaseChecker/index.js
- ~/my-monorepo/packages/mobile/node_modules/@react-native-community/cli/build/commands/server/runServer.js
- ~/my-monorepo/packages/mobile/node_modules/@react-native-community/cli/build/commands/server/server.js
- ~/my-monorepo/packages/mobile/node_modules/@react-native-community/cli/build/commands/index.js
- ~/my-monorepo/packages/mobile/node_modules/@react-native-community/cli/build/index.js
- ~/my-monorepo/packages/mobile/node_modules/react-native/cli.js
- ~/.nvm/versions/node/v14.0.0/lib/node_modules/react-native-cli/index.js
info Fetching system and libraries information...
(node:31193) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 1.79 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.0.0 - ~/.nvm/versions/node/v14.0.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v14.0.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description
When launching the ios app from a fresh install inside a monorepo configured with lerna, the simulator launches and displays an error message:

![Simulator Screen Shot - iPhone 11 - 2020-05-14 at 19 26 13](https://user-images.githubusercontent.com/5884119/82005061-4689b480-9619-11ea-916c-4602f7414704.png)

**Iterm output:**
```shell
Last login: Thu May 14 18:39:56 on ttys006

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
~ $ ~/my-monorepo/packages/mobile/node_modules/react-native/scripts/launchPackager.command ; exit;




arn Package react-test-renderer has been ignored because it contains invalid configuration. Reason: Cannot find module 'react-test-renderer/package.json'
Require stack:
- ~/my-monorepo/packages/mobile/node_modules/@react-native-community/cli/build/tools/config/resolveNodeModuleDir.js
- ~/my-monorepo/packages/mobile/node_modules/@react-native-community/cli/build/tools/releaseChecker/index.js
- ~/my-monorepo/packages/mobile/node_modules/@react-native-community/cli/build/commands/server/runServer.js
- ~/my-monorepo/packages/mobile/node_modules/@react-native-community/cli/build/commands/server/server.js
- ~/my-monorepo/packages/mobile/node_modules/@react-native-community/cli/build/commands/index.js
- ~/my-monorepo/packages/mobile/node_modules/@react-native-community/cli/build/index.js
- ~/my-monorepo/packages/mobile/node_modules/react-native/cli.js
error Cannot find module './assets/empty-module.js'
Require stack:
- ~/my-monorepo/packages/mobile/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js
- ~/my-monorepo/packages/mobile/node_modules/metro/src/node-haste/DependencyGraph.js
- ~/my-monorepo/packages/mobile/node_modules/metro/src/Bundler.js
- ~/my-monorepo/packages/mobile/node_modules/metro/src/IncrementalBundler.js
- ~/my-monorepo/packages/mobile/node_modules/metro/src/index.js
- ~/my-monorepo/packages/mobile/node_modules/@react-native-community/cli/build/commands/server/runServer.js
- ~/my-monorepo/packages/mobile/node_modules/@react-native-community/cli/build/commands/server/server.js
- ~/my-monorepo/packages/mobile/node_modules/@react-native-community/cli/build/commands/index.js
- ~/my-monorepo/packages/mobile/node_modules/@react-native-community/cli/build/index.js
- ~/my-monorepo/packages/mobile/node_modules/react-native/cli.js. Run CLI with --verbose flag for more details.
Error: Cannot find module './assets/empty-module.js'
Require stack:
- ~/my-monorepo/packages/mobile/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js
- ~/my-monorepo/packages/mobile/node_modules/metro/src/node-haste/DependencyGraph.js
- ~/my-monorepo/packages/mobile/node_modules/metro/src/Bundler.js
- ~/my-monorepo/packages/mobile/node_modules/metro/src/IncrementalBundler.js
- ~/my-monorepo/packages/mobile/node_modules/metro/src/index.js
- ~/my-monorepo/packages/mobile/node_modules/@react-native-community/cli/build/commands/server/runServer.js
- ~/my-monorepo/packages/mobile/node_modules/@react-native-community/cli/build/commands/server/server.js
- ~/my-monorepo/packages/mobile/node_modules/@react-native-community/cli/build/commands/index.js
- ~/my-monorepo/packages/mobile/node_modules/@react-native-community/cli/build/index.js
- ~/my-monorepo/packages/mobile/node_modules/react-native/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)
    at Object.<anonymous> (~/my-monorepo/packages/mobile/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:253:11)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (~/my-monorepo/packages/mobile/node_modules/metro/src/node-haste/DependencyGraph.js:76:18)
Process terminated. Press <enter> to close the window
```

## React Native version:
Run `react-native info` in your terminal and copy the results here.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. `git clone https://github.com/tettoffensive/react-native-monorepo.git`
2. `cd react-native-monorepo`
3. `npm install --global lerna`
4. `lerna bootstrap`
5. `cd packages`
6. `npx react-native init mobile`
7. `cd mobile`
8. `npx react-native run-ios`

## Expected Results
I expect the simulator to start up and launch the mobile app without displaying any errors.

**Comment by fabriziobertoglio1987** [comment]
https://www.google.com/search?client=ubuntu&channel=fs&q=yarn++Cannot+find+module+%27.%2Fassets%2Fempty-module.js%27&ie=utf-8&oe=utf-8

**Comment by christian-smith** [comment]
I encountered this same problem, however on the Android emulator it was working correctly.  This workaround fixed it for me: https://github.com/facebook/react-native/issues/22140#issuecomment-495304399

**Comment by stackia** [comment]
https://github.com/facebook/react-native/blob/master/scripts/packager.sh#L11
So if your `react-native` package is hoisted to the project root, the packager will run from the project root dir.

My workaround:

```json
  // package.json
  "scripts": {
    "android": "npm run packager && react-native run-android --no-packager",
    "ios": "npm run packager && react-native run-ios --no-packager",
    "packager": "open start-packager.command",
    "start": "react-native start"
  }
```

Create a new file named `start-packager.command` in your RN project dir:

```shell
#!/bin/bash
# Set terminal title
cd `dirname $0`
echo -en "\\033]0;Metro\\a"
clear

# shellcheck source=/dev/null
npm start

if [[ -z "$CI" ]]; then
  echo "Process terminated. Press <enter> to close the window"
  read -r
fi
```

And run with `npm run ios` or `npm run android`.

**Comment by JBerendes** [comment]
I've found that watchman won't trigger a build of the bundle.
Try removing the watchman you have already installed.
then `yarn add watchman`
And see if you end up with a working bundle
