### ISSUE TITLE
Android 4.1 RN 0.62.2 fatal runtime exception running in debug mode with Flipper enabled

### ISSUE THREAD

**Issue by info-bit** [facebook/react-native#28924]
Running a clean project on Android 4.1 in debug mode isn't possible. Probably same as #9043 and  #28481 and #28940. The app seems to work in release mode.

<details>
<summary>The app chrashes with this fatal before it can even start (expand):</summary>
<p>

```
FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to create application com.reactnativecleanproject.MainApplication: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4154)
	at android.app.ActivityThread.access$1300(ActivityThread.java:130)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4745)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
	at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:90)
	at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:238)
	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:281)
	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87)
	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)
	at com.reactnativecleanproject.MainApplication.onCreate(MainApplication.java:47)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4151)
	... 10 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
	at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:80)
	... 17 more
Caused by: java.lang.NoClassDefFoundError: java.util.Objects
	at okhttp3.CertificatePinner.withCertificateChainCleaner(CertificatePinner.java:231)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:238)
	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015)
	at com.facebook.react.devsupport.DevServerHelper.<init>(DevServerHelper.java:132)
	at com.facebook.react.devsupport.DevSupportManagerImpl.<init>(DevSupportManagerImpl.java:183)
	... 20 more
```

</p>
</details>

## React Native version:
System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 3.14 GB / 15.86 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-16 | Google APIs ARM EABI v7a, android-16 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom, android-R | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
  Languages:
    Java: 1.8.0_231
    Python: 2.7.17
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

0. Start an Android 4.1 (api 16) emulator
1. `react-native init CleanProject`
2. `cd CleanProject`
3. `yarn`
4. `yarn start`
5. `yarn android`

## Expected Results
The app runs fine in debug mode with all Android versions.

## Snack, code example, screenshot, or link to a repository:
This repo can be used to reproduce the issue: https://github.com/info-bit/react-native-clean-project.

**Comment by Fedex2791999** [comment]
👍

**Comment by AnOptimistSeePessimist** [comment]
the same issue, tested in android 4.3 & 4.4.

**Comment by winardis** [comment]
are there any updates on this topic?

**Comment by info-bit** [comment]
I will close this issue since we are not using this version of RN anymore.

**Comment by info-bit** [comment]
I will close this issue since we are not using this version of RN anymore.
