### ISSUE TITLE
Gradle sync failed: Base: GRADLE_USER_HOME is unknown

### ISSUE THREAD

**Issue by IsmetGlumcevic** [facebook/react-native#28947]
## Description
After update android studio gets issue:

Exception in thread "main" java.lang.RuntimeException: Base: GRADLE_USER_HOME  is unknown
        at org.gradle.wrapper.PathAssembler.getBaseDir(PathAssembler.java:97)
        at org.gradle.wrapper.PathAssembler.getDistribution(PathAssembler.java:43)
        at org.gradle.wrapper.Install.createDist(Install.java:44)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)

Is this issue of react-native or android studio.

## React Native version:
System:
    OS: macOS 10.15.4
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.4.0 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.0, 30.0.0, 30.0.0
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5

## Expected Results
The app worked before the update android studio, I don't get any error in my code.

**Comment by kpradeepkumarreddy** [comment]
which version of android studio are you using ??  Is it version 4.0.0 ?  I'm also facing the same issue.
