### ISSUE TITLE
FAILURE: Build failed with an exception.  * Where: Script...

### ISSUE THREAD

**Issue by Cuadros99** [facebook/react-native#29022]
FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\danie\OneDrive\�rea de Trabalho\IME\Iniciativas\IME Jr\BECOMP\Capacita��o\React Native\Curso_React_Native\final_chance\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 195

* What went wrong:
A problem occurred evaluating script.
> internal/modules/cjs/loader.js:1032  throw err;  ^Error: Cannot find module 'C:\Users\danie\OneDrive\Ã�rea de Trabalho\IME\Iniciativas\IME Jr\BECOMP\CapacitaÃ§Ã£o\React Native\Curso_React_Native\final_chance\node_modules\@react-native-community\cli\build\bin.js'    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)    at Function.Module._load (internal/modules/cjs/loader.js:898:27)    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)    at internal/main/run_main_module.js:17:47 {  code: 'MODULE_NOT_FOUND',  requireStack: []}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
:ReactNative:Unexpected empty result of running '[node, C:\Users\danie\OneDrive\�?rea de Trabalho\IME\Iniciativas\IME Jr\BECOMP\Capacitação\React Native\Curso_React_Native\final_chance\node_modules\@react-native-community\cli\build\bin.js, config]' command.
:ReactNative:Running '[node, C:\Users\danie\OneDrive\�?rea de Trabalho\IME\Iniciativas\IME Jr\BECOMP\Capacitação\React Native\Curso_React_Native\final_chance\node_modules\@react-native-community\cli\build\bin.js, config]' command failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\danie\OneDrive\�rea de Trabalho\IME\Iniciativas\IME Jr\BECOMP\Capacita��o\React Native\Curso_React_Native\final_chance\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 195

* What went wrong:
A problem occurred evaluating script.
> internal/modules/cjs/loader.js:1032  throw err;  ^Error: Cannot find module 'C:\Users\danie\OneDrive\Ã�rea de Trabalho\IME\Iniciativas\IME Jr\BECOMP\CapacitaÃ§Ã£o\React Native\Curso_React_Native\final_chance\node_modules\@react-native-community\cli\build\bin.js'    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)    at Function.Module._load (internal/modules/cjs/loader.js:898:27)    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)    at internal/main/run_main_module.js:17:47 {  code: 'MODULE_NOT_FOUND',  requireStack: []}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at makeError (C:\Users\danie\OneDrive\Área de Trabalho\IME\Iniciativas\IME Jr\BECOMP\Capacitação\React Native\Curso_React_Native\final_chance\node_modules\execa\index.js:174:9)
    at C:\Users\danie\OneDrive\Área de Trabalho\IME\Iniciativas\IME Jr\BECOMP\Capacitação\React Native\Curso_React_Native\final_chance\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runOnAllDevices (C:\Users\danie\OneDrive\Área de Trabalho\IME\Iniciativas\IME Jr\BECOMP\Capacitação\React Native\Curso_React_Native\final_chance\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (C:\Users\danie\OneDrive\Área de Trabalho\IME\Iniciativas\IME Jr\BECOMP\Capacitação\React Native\Curso_React_Native\final_chance\node_modules\@react-native-community\cli\build\index.js:186:9)

**Comment by Cuadros99** [comment]
> ⚠️	Missing Environment Information
> ℹ️	Your issue may be missing information about your development environment. You can obtain the missing information by running `react-native info` in a console.

info Fetching system and libraries information...
(node:8668) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 1.37 GB / 7.88 GB
  Binaries:
    Node: 14.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 21.1.2, 28.0.1, 28.0.3, 29.0.3, 30.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
  Languages:
    Java: 1.8.0_211
    Python: 2.7.18
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
