### ISSUE TITLE
Error while updating property 'flex' in shadow node of type: RCTView

### ISSUE THREAD

**Issue by kevin-zhaotk** [facebook/react-native#29238]
we have come across too many similar crashes during last few days. following are 4 logs of them. 
1, Error while updating property 'flex' in shadow node of type: RCTView
     method com.facebook.react.uimanager.LayoutShadowNode.setFlex argument 1 has type float, got null

2, Error while updating property 'collapsable' in shadow node of type: RCTView
    method com.facebook.react.uimanager.LayoutShadowNode.setCollapsable argument 1 has type boolean, got java.lang.Integer

3, Error while updating property 'overflow' in shadow node of type: RCTScrollView
    method com.facebook.react.uimanager.LayoutShadowNode.setOverflow argument 1 has type java.lang.String, got com.facebook.react.bridge.DynamicFromObject
     com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp

4, Error while updating property 'justifyContent' in shadow node of type: RCTView
    method com.facebook.react.uimanager.LayoutShadowNode.setJustifyContent argument 1 has type java.lang.String, got java.lang.Integer

## React Native version:
"dependencies": {
    "@sentry/react-native": "^1.3.3",
    "babel-preset-react-native": "^2.1.0",
    "deprecated-react-native-listview": "0.0.6",
    "lottie-react-native": "3.3.2",
    "react": "16.11.0",
    "react-native": "^0.62.2",
    "react-native-code-push": "^5.6.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-lahk-marquee-label": "^1.1.4",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-progress": "^4.0.2",
    "react-native-progress-circle": "^2.1.0",
    "react-native-screens": "^2.0.0-beta.2",
    "react-native-scrollable-tab-view": "^0.8.0",
    "react-native-swiper": "^1.5.13",
    "react-native-vector-icons": "^4.5.0",
    "react-native-webview": "^9.4.0",
    "react-navigation": "^3.6.1",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5"
  },

## Steps To Reproduce
1. we have no operation  path to reproduce these crashes. 
2. From Firebase crash logs,  we found that all these crashes happened at starting phase of React-Native module

**Comment by luatnd** [comment]
I have same issue and cannot reproduce it, it appears on some random devices.

From Crashlytics:
> Error while updating property 'flexWrap' in shadow node of type: RCTView
> Error while updating property 'left' in shadow node of type: RCTView
> Error while updating property '<so many other props here>' in shadow node of type: RCTView

From AppCenter:
> java.lang.IllegalArgumentException: method com.facebook.react.uimanager.LayoutShadowNode.setPositionValues argument 1 has type int, got null
> java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.facebook.react.bridge.Dynamic.isNull()' on a null object reference
> java.lang.IllegalArgumentException: method com.facebook.react.uimanager.LayoutShadowNode.setFlexWrap argument 1 has type java.lang.String, got java.lang.Boolean
> 

react-native info:
```
System:
    OS: macOS 10.16
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 24.36 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
    Yarn: 1.23.0-20200615.1917 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 20.0, macOS 10.16, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 25, 26, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 12.0/12A6159 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
```

**Comment by chrisglein** [comment]
Without a standalone repro or more context on the places in your app where you think the problem in RN core is there's not much that can be done with this issue. It doesn't seem like there's a way to know if it's app code or core just based on this. I'm not saying you're imagining things, just that it's hard for anyone else to investigate as is - looking at app crashes is generally out of scope for issues logged against this repo.

**Comment by jordangrant** [comment]
For me it was calling the RNRestart library to reload the app soon after app launch (for some arabic users) avishayil/react-native-restart#144

**Comment by webraptor** [comment]
> For me it was calling the RNRestart library to reload the app soon after app launch (for some arabic users) [avishayil/react-native-restart#144](https://github.com/avishayil/react-native-restart/issues/144)

why would you want to restart the app as soon as it launches?

**Comment by jordangrant** [comment]
@webraptor To force left to right (LTR) text for Arabic users, it only renders as such on subsequent launches

**Comment by 1Ajay** [comment]
is it possible to solve without RNRestart?

**Comment by luatnd** [comment]
FYI, We need to use a custom react-native core to solve this problem:
You can see how I've done here:
https://github.com/mobiletechvn/react-native/commit/9be880e39ee2e97b6c31061db8bf225bc366bf91#diff-eff5941efbad2c12a91cdca5bba1ee1ec305b8146f692e8c50b6ad8cbeb5ec03

**Comment by kuldeepworkid** [comment]
**i im also facing the same issue App crashes after calling RNRestart.Restart() in webview.
Below is mr crash report .**

2021-07-05 18:29:46.971 22990-24054/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
Process: com.app.packageName, PID: 22990
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'collapsable' in shadow node of type: RCTView
at com.facebook.react.uimanager.b1$k.a(Unknown Source:113)
at com.facebook.react.uimanager.z0$b.a(Unknown Source:10)
at com.facebook.react.uimanager.z0.a(Unknown Source:36)
at com.facebook.react.uimanager.b0.a(Unknown Source:0)
at com.facebook.react.uimanager.o0.a(Unknown Source:71)
at com.facebook.react.uimanager.UIManagerModule.createView(Unknown Source:53)
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:149)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
at android.os.Looper.loop(Looper.java:236)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalArgumentException: method com.facebook.react.uimanager.i.setCollapsable argument 1 has type boolean, got java.lang.Float
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.uimanager.b1$k.a(Unknown Source:18)
at com.facebook.react.uimanager.z0$b.a(Unknown Source:10) 
at com.facebook.react.uimanager.z0.a(Unknown Source:36) 
at com.facebook.react.uimanager.b0.a(Unknown Source:0) 
at com.facebook.react.uimanager.o0.a(Unknown Source:71) 
at com.facebook.react.uimanager.UIManagerModule.createView(Unknown Source:53) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:149) 
at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21) 
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
at android.os.Handler.handleCallback(Handler.java:938) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0) 
at android.os.Looper.loop(Looper.java:236) 
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37) 
at java.lang.Thread.run(Thread.java:923) 
2021-07-05 18:29:46.975 22990-24054/? D/OOMEventManagerFK: checkEventAndDumpForJE: 0
2021-07-05 18:29:46.989 1436-24081/? I/DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2

**Comment by thanh90** [comment]
i'm not sure but in my case when checking for a condition i forgot to convert value to boolean type

**Comment by XiaoweiLiu0812** [comment]
facing same error on andorid

com.facebook.react.bridge.JSApplicationIllegalArgumentException:Error while updating property 'alignItems' in shadow node of type: RCTView

Error while updating property 'flexDirection' in shadow node of type: RCTView

how to solve?

**Comment by SaiSriRamSathwik** [comment]
Facing same issue on android devices 

Error while updating property flex in shadow node of type:RCTView

java.lang.String cannot be cast to java.lang.Double

Any suggestions to rectify this error.
