### ISSUE TITLE
What is Fatal Exception: com.facebook.react.bridge.NoSuchKeyException: value issue?

### ISSUE THREAD

**Issue by rahulje9** [facebook/react-native#29280]
I have a react native application in production and it is crashing. I have added crashlytics to the app which gave this crash report.
`Fatal Exception: com.facebook.react.bridge.NoSuchKeyException: value`

attaching full crash report.

```
Fatal Exception: com.facebook.react.bridge.NoSuchKeyException: value
       at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:109)
       at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:113)
       at com.facebook.react.bridge.ReadableNativeMap.getDouble(ReadableNativeMap.java:150)
       at com.facebook.react.animated.ValueAnimatedNode.<init>(ValueAnimatedNode.java:27)
       at com.facebook.react.animated.NativeAnimatedNodesManager.createAnimatedNode(NativeAnimatedNodesManager.java:85)
       at com.facebook.react.animated.NativeAnimatedModule$4.execute(NativeAnimatedModule.java:208)
       at com.facebook.react.animated.NativeAnimatedModule$3.execute(NativeAnimatedModule.java:154)
       at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:498)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:779)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:888)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2200(UIViewOperationQueue.java:42)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:948)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:997)
       at android.view.Choreographer.doCallbacks(Choreographer.java:797)
       at android.view.Choreographer.doFrame(Choreographer.java:728)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8016)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

```

React and React Native versions
```
        "react": "16.9.0",
        "react-native": "0.61.5",
```

Edit:
React Native info
```
info Fetching system and libraries information...
System:
    OS: macOS 10.15
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 731.53 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by rahulje9** [comment]
does anyone know about this?

**Comment by hattat-34** [comment]
I had the same issue with 0.61.5.

**Comment by markjoseultra** [comment]
Hi are you still having the same issue? I also logged this error with sentry today
