### ISSUE TITLE
Error: EPERM: operation not permitted, chmod node_modules/@react-native-community/cli/build/commands/server/external/xsel

### ISSUE THREAD

**Issue by ravichandran18390** [facebook/react-native#29409]
## Description
The below error is thrown while first time running the app & metro bundler not started.
internal/fs/utils.js:230
    throw err;
    ^
Error: EPERM: operation not permitted, chmod '/Users/user/Documents/projects/projectRepo/NewApp/node_modules/@react-native-community/cli/build/commands/server/external/xsel'
    at Object.chmodSync (fs.js:1198:3)
    at Object.<anonymous> (/Users/user/Documents/projects/projectRepo/NewApp/node_modules/@react-native-community/cli/build/commands/server/copyToClipBoard.js:50:15)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/user/Documents/projects/projectRepo/NewApp/node_modules/@react-native-community/cli/build/commands/server/middleware/copyToClipBoardMiddleware.js:8:47)
    at Module._compile (internal/modules/cjs/loader.js:1138:30) {
  errno: -1,
  syscall: 'chmod',
  code: 'EPERM',
  path: '/Users/user/Documents/projects/projectRepo/NewApp/node_modules/@react-native-community/cli/build/commands/server/external/xsel'
}
Process terminated. Press <enter> to close the window

## React Native version:
`react-native info`:
System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 3.20 GB / 16.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 25.0.0, 25.0.1, 25.0.2, 26.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.3, 29.0.2
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom_64, android-26 | Android TV Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.1 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-log-ios: 1.5.0

1. react-native run-android --variant=debug / react-native run-android
causes this this issue. every first time, im manually starting the metro-bunder using react-native start or react-native start --reset-cache

## Expected Results
metro-bundler has to start automatically & load the app

package.json used
"dependencies": {
		"@react-native-community/cli-platform-ios": "3.0.0",
		"@react-native-community/netinfo": "^4.6.1",
		"@react-native-community/slider": "^2.0.9",
		"@react-native-community/viewpager": "^3.3.0",
......
}
"devDependencies": {
		"@babel/core": "^7.6.2",
		"@babel/runtime": "^7.6.2",
		"@react-native-community/eslint-config": "^0.0.5",
.......
}

Please help to resolve a solution

Thanks in Advance

**Comment by ravichandran18390** [comment]
sudo yarn cache clean
rm -rf yarn.lock
yarn install

After executing above mentioned commands, while react-native run-android command first time, terminal is not opened with "Error: EPERM: operation not permitted, chmod '/Users/user/Documents/projects/projectRepo/NewApp/node_modules/@react-native-community/cli/build/commands/server/external/xsel'"

usual metro bundler opened & loads the bundle. works fine!!
