### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Command failed: yarn add react-native-template-react-native-template-typescript

### ISSUE THREAD

**Issue by jgcmarins** [facebook/react-native#29411]
ref https://github.com/react-native-community/cli/issues/1224

## Description

I am trying to start a new project with typescript template and it's failing on the step `Removing module react-native-template-react-native-template-typescript...` with error `error This module isn't specified in a package.json file.`, followed by this error `UnhandledPromiseRejectionWarning: Error: Command failed: yarn add react-native-template-react-native-template-typescript`.

This is the command I am running:
`npx react-native init MyAwesomeApp --template react-native-template-typescript`

## React Native version:
`0.63`

## Steps To Reproduce

1. run `npx react-native init MyAwesomeApp --template react-native-template-typescript`
2. watch it fails

## Expected Results
Successfully creates a new RN project

## Snack, code example, screenshot, or link to a repository:
Full stack trace:
```
[1/4] 🔍  Resolving packages...
warning jest > @jest/core > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-template-react-native-template-typescript: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/path/to/project/MyAwesomeApp/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
yarn remove v1.22.4
[1/2] 🗑  Removing module react-native-template-react-native-template-typescript...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
warn Failed to clean up template temp files in node_modules/react-native-template-react-native-template-typescript. This is not a critical error, you can work on your app.
(node:68507) UnhandledPromiseRejectionWarning: Error: Command failed: yarn add react-native-template-react-native-template-typescript
    at makeError (/path/to/project/MyAwesomeApp/node_modules/execa/index.js:174:9)
    at /path/to/project/MyAwesomeApp/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async createFromRemoteTemplate (/path/to/project/MyAwesomeApp/node_modules/@react-native-community/cli/build/tools/generator/templates.js:115:5)
    at async createProjectFromTemplate (/path/to/project/MyAwesomeApp/node_modules/@react-native-community/cli/build/tools/generator/templates.js:88:3)
    at async generateProject (/path/to/project/MyAwesomeApp/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:118:3)
    at async Object.initCompat (/path/to/project/MyAwesomeApp/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:105:3)
(node:68507) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:68507) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Let me know if I should open this on https://github.com/react-native-community/cli

**Comment by DevHabit** [comment]
Please use npx react-native init MyAwesomeApp --template typescript.

**Comment by cortinico** [comment]
Closing as the upstream issue is also closed. Please open a separate issue if the problem persists
