### ISSUE TITLE
Unable to resolve module debugger-ui after upgrading (rebuild) to 0.63.1

### ISSUE THREAD

**Issue by emclab** [facebook/react-native#29415]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html
After upgrading to 0.63.1 from 0.62.2 by rebuilding the project from ground up, there is error about module debugger-ui:

`[Fri Jul 17 2020 16:26:17.494]  BUNDLE  ./index.js ░░░░░░░░░░░░░░░░ 0.6% (1/13)Error: Unable to resolve module `./debugger-ui/ui.bcd3f9d1.js` from ``:

None of these files exist:
  * debugger-ui\ui.bcd3f9d1.js(.native|.native.js|.js|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx)
  * debugger-ui\ui.bcd3f9d1.js\index(.native|.native.js|.js|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (C:\D\code\js\xyz_app\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (C:\D\code\js\xyz_app\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (C:\D\code\js\xyz_app\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)
    at C:\D\code\js\xyz_app\node_modules\metro\src\lib\transformHelpers.js:267:42
    at Server.<anonymous> (C:\D\code\js\xyz_app\node_modules\metro\src\Server.js:841:41)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\D\code\js\xyz_app\node_modules\metro\src\Server.js:99:24)
    at _next (C:\D\code\js\xyz_app\node_modules\metro\src\Server.js:119:9)`

## React Native version:0.63.1
Run `react-native info` in your terminal and copy the results here.

System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 584.20 MB / 7.76 GB
  Binaries:
    Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0, 29.0.0, 29.0.2, 29.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
      Android NDK: 21.0.6113669
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
  Languages:
    Java: 1.8.0_201
    Python: 2.7.15
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.1 => 0.63.1
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. create a react-native package and install the following modules from package.json

"scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.7.0",
    "@react-navigation/stack": "^5.7.0",
    "native-base": "^2.13.12",
    "react": "16.13.1",
    "react-native": "0.63.1",
    "react-native-confirmation-code-field": "^6.5.0",
    "react-native-device-info": "^5.6.2",
    "react-native-easy-grid": "^0.2.2",
    "react-native-fast-image": "^8.3.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-image-crop-picker": "^0.32.2",
    "react-native-image-pan-zoom": "^2.1.12",
    "react-native-keychain": "^6.1.1",
    "react-native-reanimated": "^1.9.0",
    "react-native-responsive-screen": "^1.4.1",
    "react-native-safe-area-context": "^3.1.1",
    "react-native-screens": "^2.9.0",
    "react-native-tag-autocomplete": "^1.0.22",
    "react-native-vector-icons": "^7.0.0",
    "socket.io-client": "2.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.10.5",
    "@babel/runtime": "^7.10.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.1.0",
    "eslint": "^7.4.0",
    "jest": "^26.1.0",
    "metro-react-native-babel-preset": "^0.60.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-navigation|react-navigation-redux-helpers|@react-navigation/.*)",
      "node_modules/(?!(react-native|react-native-button|native-base-.*|react-native-.*)/)"
    ]
  }

2. change minSDKversion to 21 from 16 in bundle.gradle. run npx react-native run-android and check the error.

## Expected Results
Describe what you expected to happen.
no error

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by emclab** [comment]
![Capture](https://user-images.githubusercontent.com/946013/87842893-e277ac80-c864-11ea-91c5-43b2cd3a496d.JPG)

Here is another error for RN 0.63.1
