### ISSUE TITLE
Android Strict Mode LeakedClosableViolation: Explicit termination method 'release' not called

### ISSUE THREAD

**Issue by aravikanti** [facebook/react-native#29430]
## Description
I am trying to integrate react native 0.59.8 into our existing app and seeing a strict mode violation of 
 "LeakedClosableViolation"  when trying to add ReactRootView to my activity.
This only happens on a x64 variant of android mobile.
Here is the stacktrace:
```
D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1910)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:286)
        at android.view.SurfaceControl.finalize(SurfaceControl.java:951)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
        at java.lang.Daemons$Daemon.run(Daemons.java:139)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.Throwable: Explicit termination method 'release' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:237)
        at android.view.SurfaceControl.<init>(SurfaceControl.java:870)
        at android.view.SurfaceControl.<init>(SurfaceControl.java:78)
        at android.view.SurfaceControl$1.createFromParcel(SurfaceControl.java:936)
        at android.view.SurfaceControl$1.createFromParcel(SurfaceControl.java:934)
        at android.os.Parcel.readParcelable(Parcel.java:3187)
        at android.view.InsetsSourceControl.<init>(InsetsSourceControl.java:69)
        at android.view.InsetsSourceControl$1.createFromParcel(InsetsSourceControl.java:100)
        at android.view.InsetsSourceControl$1.createFromParcel(InsetsSourceControl.java:98)
        at android.os.Parcel.readTypedObject(Parcel.java:3025)
        at android.os.Parcel.createTypedArray(Parcel.java:2986)
        at android.view.IWindow$Stub.onTransact(IWindow.java:388)
        at android.os.Binder.execTransactInternal(Binder.java:1138)
        at android.os.Binder.execTransact(Binder.java:1102)
```
I have setup a demo app with react native version of 0.59.8 and see the same violation when I enable strict mode.
I also verified this violation doesn't happen while using the latest version of react native and installing it on a x64 android device.

## React Native version:
0.59.8

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Use react-native-cli to setup a sample app with react native version 0.59.8
2. Enable strict mode in the demo app with penaltyLogging enabled
3. Deploy the app on android x64 variant simulator
4. Check the stacktrace to verify that you see the above similar stacktrace.

## Expected Results
The above violation should not happen.

**Comment by aravikanti** [comment]
Any update on this? If anyone can point me to which area of the code this error happens, I can try to investigate and submit a pull request.

**Comment by sbatikeri** [comment]
I am also having same issue. I am using react-native 0.61.5
