### ISSUE TITLE
What are the reasons for the react-native application crash?

### ISSUE THREAD

**Issue by a1005342094** [facebook/react-native#29432]
## Error:
java.lang.IllegalStateException: closed
	at okio.RealBufferedSink.write(RealBufferedSink.java:39)
	at okio.ForwardingSink.write(ForwardingSink.java:35)
	at com.facebook.react.modules.network.ProgressRequestBody$1.write(ProgressRequestBody.java:58)
	at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
	at com.facebook.react.modules.network.ProgressRequestBody.writeTo(ProgressRequestBody.java:48)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:62)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)

## React-Native dependencies & version:
{
    "buffer": "^4.0.0",
    "react": "16.0.0",
    "react-dedux": "^0.4.0-beta.4",
    "react-native": "0.51.0",
    "react-native-animatable": "^1.3.1",
    "react-native-bluetooth-serial": "^1.0.0-rc1",
    "react-native-camera": "^1.4.1",
    "react-native-exception-handler": "^2.10.8",
    "react-native-image-crop-picker": "^0.21.3",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-page-scrollview": "^1.0.2",
    "react-native-restart": "0.0.13",
    "react-native-secharts": "^1.4.5",
    "react-native-swipe-list-view": "^1.5.3",
    "react-native-swiper": "^1.5.13",
    "react-navigation": "^2.12.1",
    "react-navigation-redux-helpers": "^3.0.2",
    "realm": "^3.0.0-beta.1",
    "redux-thunk": "^2.3.0"
  }

**Comment by a1005342094** [comment]
> ⚠️	缺少环境信息
> ℹ️	您的问题可能缺少有关开发环境的信息。您可以通过运行`react-native info`在控制台里。

This is a crash error caught by the application running after release packaging.

**Comment by Symous** [comment]
@a1005342094  any progress here?
