### ISSUE TITLE
get error when run the pod commands 

### ISSUE THREAD

**Issue by imansalhi** [facebook/react-native#29486]
## Description
I install cocoapods with `sudo gem install cocoapods` how ever i get this error when i do `pod install` or every command starts with **pod**

```
/Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.13.1/lib/ffi_c.bundle, 9): no suitable image found.  Did find: (LoadError)
        /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.13.1/lib/ffi_c.bundle: code signature in (/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.13.1/lib/ffi_c.bundle) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed. - /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.13.1/lib/ffi_c.bundle
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.13.1/lib/ffi.rb:6:in `rescue in <top (required)>'
        from /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.13.1/lib/ffi.rb:3:in `<top (required)>'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/sources_manager.rb:5:in `<top (required)>'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/core_overrides.rb:1:in `<top (required)>'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods.rb:75:in `<module:Pod>'
        from /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods.rb:17:in `<top (required)>'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.9.3/bin/pod:36:in `<top (required)>'
        from /Applications/MAMP/Library/bin/pod:22:in `load'
        from /Applications/MAMP/Library/bin/pod:22:in `<main>'
```

## React Native version:
 react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
 Managers:
    CocoaPods: Not Found   
mac-os: catalina 

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. sudo gem install cocoapods
2. cd ios pod install 

## Expected Results
it should run pod install but i get above error when i use `pod` in command

**Comment by imansalhi** [comment]
Actually the problem is with mac-os: Catalina.
```
 brew install cocoapods --build-from-source
then: brew link --overwrite cocoapods
```

thanks to [CathyXian](https://github.com/CocoaPods/CocoaPods/issues/8955#issuecomment-539267256)

**Comment by amitrana22** [comment]
Same issue, tried @imansalhi solution but not working for me.

**Comment by safaiyeh** [comment]
Closing as this is an environment issue not related to React Native.
