### ISSUE TITLE
Couldn't find package "@react-native-community/cli@^4.7.0" required by "react-native" on the "npm" registry

### ISSUE THREAD

**Issue by T00rk** [facebook/react-native#29575]
## Description
I tried to create a new application using `npx react-native init myapp`

## React Native version:
Version 2.0.1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. `npx react-native init myapp`

## Expected Results
```
Using yarn v1.22.4
Installing react-native...
yarn add v1.22.4
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find package "@react-native-community/cli@^4.7.0" required by "react-native" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
warning react-native > fbjs > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native > fbjs-scripts > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
Error: Couldn't find package "@react-native-community/cli-platform-android@^4.7.0" required by "react-native" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/share/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/share/yarn/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:310:30)
    at /usr/share/yarn/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@jest/types@^24.9.0" required by "pretty-format@^24.9.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/share/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/share/yarn/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:310:30)
    at /usr/share/yarn/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@react-native-community/cli-platform-ios@^4.7.0" required by "react-native" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/share/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/share/yarn/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:310:30)
    at /usr/share/yarn/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Command failed: yarn add react-native --exact
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at run (/usr/local/lib/node_modules/react-native-cli/index.js:294:5)
    at createProject (/usr/local/lib/node_modules/react-native-cli/index.js:249:3)
    at /usr/local/lib/node_modules/react-native-cli/index.js:217:7
    at /usr/local/lib/node_modules/react-native-cli/node_modules/prompt/lib/prompt.js:316:32
    at /usr/local/lib/node_modules/react-native-cli/node_modules/async/lib/async.js:142:25
    at assembler (/usr/local/lib/node_modules/react-native-cli/node_modules/prompt/lib/prompt.js:313:9)
    at /usr/local/lib/node_modules/react-native-cli/node_modules/prompt/lib/prompt.js:322:32
    at /usr/local/lib/node_modules/react-native-cli/node_modules/prompt/lib/prompt.js:597:5 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 15314,
  stdout: null,
  stderr: null
}
Command `yarn add react-native --exact` failed.
```

**Comment by sandy2196** [comment]
The same issue, can anyone fix it!

**Comment by genie09** [comment]
same issue here...

**Comment by todorone** [comment]
@T00rk It was npm registry outage, now it works correctly...

**Comment by safaiyeh** [comment]
> @T00rk It was npm registry outage, now it works correctly...

Thanks for the context. Closing now as it is resolved. Feel free to file another issue if this comes up again.
