### ISSUE TITLE
pointerIndex out of range

### ISSUE THREAD

**Issue by zhuyongjun18** [facebook/react-native#29642]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native release to make sure your issue has not already been fixed: https://reactnative.dev/docs/upgrading.html

## React Native version:
react-native-version: 0.62

## Steps To Reproduce
**I didn't do anything, but the following exception occurred** 

handleException===>**pointerIndex out of range**
at android.view.MotionEvent.nativeGetAxisValue(Native Method)
	at android.view.MotionEvent.getY(MotionEvent.java:2137)
	at android.widget.ScrollView.onTouchEvent(ScrollView.java:758)
	at com.facebook.react.views.scroll.ReactScrollView.onTouchEvent(ReactScrollView.java:299)
	at com.swmansion.gesturehandler.NativeViewGestureHandler.onHandle(NativeViewGestureHandler.java:92)
	at com.swmansion.gesturehandler.GestureHandler.handle(GestureHandler.java:315)
	at com.swmansion.gesturehandler.GestureHandlerOrchestrator.deliverEventToGestureHandler(GestureHandlerOrchestrator.java:301)
	at com.swmansion.gesturehandler.GestureHandlerOrchestrator.deliverEventToGestureHandlers(GestureHandlerOrchestrator.java:259)
	at com.swmansion.gesturehandler.GestureHandlerOrchestrator.onTouchEvent(GestureHandlerOrchestrator.java:101)
	at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.dispatchTouchEvent(RNGestureHandlerRootHelper.java:126)
	at com.swmansion.gesturehandler.react.RNGestureHandlerRootView.dispatchTouchEvent(RNGestureHandlerRootView.java:63)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:547)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1811)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3091)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:509)
	at android.view.View.dispatchPointerEvent(View.java:10243)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4450)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4318)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3861)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3914)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3880)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4007)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3888)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4064)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3861)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3914)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3880)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3888)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3861)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6259)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6233)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6194)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6362)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:6141)
	at java.lang.reflect.Method.invoke(Native Method)

**Comment by luatnd** [comment]
I also have this issue.

Plz follow up here: https://github.com/facebook/react-native/issues/30320
