### ISSUE TITLE
Can't upload ReactNative to App Store, error with javax.xml.stream.XMLStreamException

### ISSUE THREAD

**Issue by mylesshie** [facebook/react-native#29660]
hello, there is a question for my reactnative app.When I uploading my app to App Store,I get an error:

```
[2020-08-16 15:52:50 CST] <main>  INFO: ParseError at [row,col]:[4709,110]
Message: XML 文档结构必须从头至尾包含在同一个实体内。 Exception's name: javax.xml.stream.XMLStreamException, Exception's message: ParseError at [row,col]:[4709,110]
Message: XML 文档结构必须从头至尾包含在同一个实体内。
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.apple.transporter.launcher.Application.start(Application.java:220)
	at com.apple.transporter.launcher.Application.main(Application.java:658)
Caused by: com.apple.transporter.bootstrap.BundleNotFoundException: bundle=[org.apache.felix.configadmin] version=[1.9.10,2.0.0) not found.
	at com.apple.transporter.bootstrap.BootstrapperPhase1.downloadNeededBundles(BootstrapperPhase1.java:269)
	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:97)
	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:59)
	at com.apple.transporter.launcher.Launcher.launchBootstrapper(Launcher.java:37)
	... 6 more

```

I can't find where the error happened, please help

react-native: 0.62.2
java: 8

**Comment by mylesshie** [comment]
> sport_app@0.0.1 info /Users/myles/Documents/self/sport_app
> react-native info

info Fetching system and libraries information...
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 35.86 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.3/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.1, 29.0.2, 30.0.0
      System Images: android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_261 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by safaiyeh** [comment]
Hi @mylesshie we need a bit more information.

Could you follow the template and provide a repro? Thanks!
