### ISSUE TITLE
java.lang.RuntimeException: java.lang.IllegalArgumentException: Unknown event: getProfilingStatus in the android logs when opening react devtools

### ISSUE THREAD

**Issue by allan-simon** [facebook/react-native#29729]
## Description

When I try to open the react devtools, either through flipper or directly with `npx react-devtools` , and connect my app to it
I DO see the "Devtools 4.6.0 etc."  Screen appearing but it keeps on refreshing 

and if I look in my android logs I keep on getting again and again this exception

```
Error occurred, shutting down websocket connection: Websocket exception
java.lang.RuntimeException: java.lang.IllegalArgumentException: Unknown event: getProfilingStatus
	at com.facebook.react.devsupport.InspectorPackagerConnection$Connection.onMessage(InspectorPackagerConnection.java:223)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalArgumentException: Unknown event: getProfilingStatus
	at com.facebook.react.devsupport.InspectorPackagerConnection.handleProxyMessage(InspectorPackagerConnection.java:78)
	at com.facebook.react.devsupport.InspectorPackagerConnection$Connection.onMessage(InspectorPackagerConnection.java:221)
	... 10 more

```

## React Native version:

```
System:
    OS: Linux 5.3 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 730.96 MB / 15.48 GB
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 14.8.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.7 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.8 - /usr/bin/javac
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.12.0 => 4.12.0 
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. launch app
2. launch react devtools

the devtools don't finish to initiailize and keep on reseting

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by safaiyeh** [comment]
Hi @allan-simon thanks for the issue. Could you provide a repro that demonstrates this issue?

**Comment by allan-simon** [comment]
hello thanks for your reply,  I will try to do that during the day
