### ISSUE TITLE
Release app crashes instantly when run. Debug version is fine

### ISSUE THREAD

**Issue by Danielgb23** [facebook/react-native#29727]
## Description
I can run my app fine on my phone while debugging but by running npx react-native run-android --variant=release
or making a release apk through android studio it crashes as soon as I open it.
adb logcat *:E

```
p(Looper.java:193)
08-20 23:46:52.037 21966 22003 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
08-20 23:46:52.037 21966 22003 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
08-20 23:47:04.089 22076 22133 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
08-20 23:47:04.089 22076 22133 E AndroidRuntime: Process: com.perkunos.daily_dharma, PID: 22076
08-20 23:47:04.089 22076 22133 E AndroidRuntime: java.lang.IllegalStateException: You need to call create() at least once to create the singleton
08-20 23:47:04.089 22076 22133 E AndroidRuntime: 	at com.evernote.android.job.JobManager.instance(JobManager.java:159)
08-20 23:47:04.089 22076 22133 E AndroidRuntime: 	at com.jamesisaac.rnbackgroundtask.BackgroundTaskModule.initialize(BackgroundTaskModule.java:52)
08-20 23:47:04.089 22076 22133 E AndroidRuntime: 	at com.facebook.react.bridge.ModuleHolder.doInitialize(ModuleHolder.java:236)
08-20 23:47:04.089 22076 22133 E AndroidRuntime: 	at com.facebook.react.bridge.ModuleHolder.markInitializable(ModuleHolder.java:100)
08-20 23:47:04.089 22076 22133 E AndroidRuntime: 	at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceInitialized(NativeModuleRegistry.java:103)
08-20 23:47:04.089 22076 22133 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl$4.run(CatalystInstanceImpl.java:542)
08-20 23:47:04.089 22076 22133 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
08-20 23:47:04.089 22076 22133 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-20 23:47:04.089 22076 22133 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
08-20 23:47:04.089 22076 22133 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
08-20 23:47:04.089 22076 22133 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
08-20 23:47:04.089 22076 22133 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
08-20 23:47:05.064  1211  1365 E storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
08-20 23:47:07.842 22161 22194 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
08-20 23:47:07.842 22161 22194 E AndroidRuntime: Process: com.perkunos.daily_dharma, PID: 22161
08-20 23:47:07.842 22161 22194 E AndroidRuntime: java.lang.IllegalStateException: You need to call create() at least once to create the singleton
08-20 23:47:07.842 22161 22194 E AndroidRuntime: 	at com.evernote.android.job.JobManager.instance(JobManager.java:159)

``` 

## React Native version:

```
System:
    OS: Linux 4.17 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (4) x64 Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
    Memory: 1.68 GB / 7.70 GB
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 12.18.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_201 - /usr/bin/javac
    Python: 2.7.16 - /home/daniel/anaconda2/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ~16.11.0 => 16.11.0 
    react-native: ~0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.Run 'npx react-native run-android --variant=release'

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
I have no idea which part of the code is to blame so I will post wathever is asked for

**Comment by safaiyeh** [comment]
Hi @Danielgb23, it looks like the cash is due to react-native-background-task. Unfortunately that library is no longer maintained. Could you find an alternative and figure out if the crash continues to happen?

**Comment by Danielgb23** [comment]
It was the react-native-background-task unistallation that was causing problems, either I did it wrong or something went bad. Installing it again with all the steps did the trick.

**Comment by safaiyeh** [comment]
@Danielgb23 great! Glad you found a solution, closing
