### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by kangfenmao** [facebook/react-native#29759]
## Description
java.util.ConcurrentModificationException at java.util.ArrayList$Itr.next(ArrayList.java:860)

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at com.facebook.react.uimanager.events.EventDispatcher.dispatchEvent(EventDispatcher.java:113)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:914)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.applyUpdatesRecursive(UIImplementation.java:899)
	at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(UIImplementation.java:639)
	at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:594)
	at com.facebook.react.uimanager.UIManagerModule.onBatchComplete(UIManagerModule.java:799)
	at com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete(NativeModuleRegistry.java:119)
	at com.facebook.react.bridge.CatalystInstanceImpl$BridgeCallback.onBatchComplete(CatalystInstanceImpl.java:171)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:201)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:764)
```

## React Native version:

```
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.32 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.5 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.13.1 
    react-native: ^0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## screenshot

![image](https://user-images.githubusercontent.com/8253512/91142875-2b344800-e6e4-11ea-8ff1-227b71e53d18.png)

**Comment by safaiyeh** [comment]
Hi @kangfenmao we need more information to investigate this. Can you provide a repro that demonstrates this crash? a 28% crash rate is not good, hopefully we can find you a solution

**Comment by kangfenmao** [comment]
I did not find a way to reproduce the exception. This error from error monitoring log. I will pay attention to this problem. @safaiyeh

**Comment by kangfenmao** [comment]
The following code will cause ConcurrentModificationException

```java
public class Test {
    public static void main(String[] args)  {
        ArrayList<Integer> list = new ArrayList<Integer>();
        list.add(2);
        Iterator<Integer> iterator = list.iterator();
        while(iterator.hasNext()){
            Integer integer = iterator.next();
            if(integer==2)
                list.remove(integer);
        }
    }
}
```

**Comment by dulmandakh** [comment]
Where is the Test class come from? Your custom native code?

**Comment by gbalduzzi** [comment]
I have the same problem as OP. In my crash analytics (I use bugsnag) I receive a lot of this errors, but I'm unable to reproduce. 

My Stacktrace:

```
java.util.ConcurrentModificationException    MainActivity
--
ArrayList.java:860    java.util.ArrayList$Itr.next
UIManagerModule.java:795    com.facebook.react.uimanager.UIManagerModule.onBatchComplete
NativeModuleRegistry.java:119    com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete
CatalystInstanceImpl.java:171    com.facebook.react.bridge.CatalystInstanceImpl$BridgeCallback.onBatchComplete
NativeRunnable.java:-2    com.facebook.react.bridge.queue.NativeRunnable.run
Handler.java:790    android.os.Handler.handleCallback
Handler.java:99    android.os.Handler.dispatchMessage
MessageQueueThreadHandler.java:27    com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage
Looper.java:175    android.os.Looper.loop
MessageQueueThreadImpl.java:226    com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run
Thread.java:764    java.lang.Thread.run
```

**Comment by kangfenmao** [comment]
Update an array list while it is rendering will cause this exception. I fixed this issue in my project. @gbalduzzi

**Comment by gbalduzzi** [comment]
I'm not sure which part of my javascript code maps to an arraylist though. I will try to debug this, thanks

**Comment by safaiyeh** [comment]
Seems like @kangfenmao found a solution. @gbalduzzi if this is still an issue for you, could you create a new issue with details specific to your implementation. Thanks!

**Comment by ouoru** [comment]
@kangfenmao could you please share an example of how you fixed this crash?

**Comment by tiggem1993** [comment]
Getting this crash in my Firebase Crashlytics.

`Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at android.view.View.registerPendingFrameMetricsObservers(View.java:6565)
       at android.view.View.dispatchAttachedToWindow(View.java:18484)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3441)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1866)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1561)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7453)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1071)
       at android.view.Choreographer.doCallbacks(Choreographer.java:882)
       at android.view.Choreographer.doFrame(Choreographer.java:814)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1057)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7107)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:511)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)`

**Comment by mohity777** [comment]
getting similar crash-

![Screenshot 2021-06-29 at 12 11 53 PM](https://user-images.githubusercontent.com/56041802/123749648-48710e80-d8d3-11eb-9f12-b265e6b32db8.png)

**Comment by Daha62** [comment]
Having the same issue
