### ISSUE TITLE
com.facebook.react.bridge.NoSuchKeyException: springDamping

### ISSUE THREAD

**Issue by harveyconnor** [facebook/react-native#29826]
## Description
I was wondering if anyone else is getting the same issue as it is throwing up a red error screen everytime I launch the app, I can dismiss it with no issue. Let me know if anyone knows how to solve this. Thanks.

I get the follow stack error in Logcat when running my application on Android.
```
2020-09-02 11:40:44.330 28856-28856/com.example.android E/unknown:ReactNative: Exception in native call
    com.facebook.react.bridge.NoSuchKeyException: springDamping
        at com.facebook.react.bridge.ReadableNativeMap.getType(ReadableNativeMap.java:180)
        at com.facebook.react.uimanager.layoutanimation.SimpleSpringInterpolator.getSpringDamping(SimpleSpringInterpolator.java:23)
        at com.facebook.react.uimanager.layoutanimation.AbstractLayoutAnimation.getInterpolator(AbstractLayoutAnimation.java:107)
        at com.facebook.react.uimanager.layoutanimation.AbstractLayoutAnimation.initializeFromConfig(AbstractLayoutAnimation.java:72)
        at com.facebook.react.uimanager.layoutanimation.LayoutAnimationController.initializeFromConfig(LayoutAnimationController.java:51)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.configureLayoutAnimation(NativeViewHierarchyManager.java:754)
        at com.facebook.react.uimanager.UIViewOperationQueue$ConfigureLayoutAnimationOperation.execute(UIViewOperationQueue.java:433)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:917)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1028)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:48)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1088)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:965)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:722)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

## React Native version:
```
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 107.24 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
    Yarn: Not Found
    npm: 6.14.5 - ~/.nvm/versions/node/v12.17.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ^0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

I start the app and it does it right away.

## Expected Results

App starts without error.

**Comment by harveyconnor** [comment]
Here's a screenshot of the error:
![Screenshot_20200902-191225](https://user-images.githubusercontent.com/10123441/91962971-96b78e80-ed50-11ea-8fe8-8292b20fef27.png)

**Comment by safaiyeh** [comment]
Hi @harveyconnor, thanks for the issue! That is odd, and you said if you dismiss the app still works accordingly?

Can you provide a repo that demonstrates this error on a fresh React Native template? It might have to do with LayoutAnimation https://reactnative.dev/docs/layoutanimation#parameters

**Comment by harveyconnor** [comment]
Problem solved!
I had a layout animation config:
```js
create: {
    type: LayoutAnimation.Types.spring,
    property: LayoutAnimation.Properties.scaleXY,
  },
```
It was missing the key "springDamping", adding it did the trick
```js
create: {
    type: LayoutAnimation.Types.spring,
    property: LayoutAnimation.Properties.scaleXY,
    springDamping: 1,
  },
```
