### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.kitchendisplay.debug.androidx" 

### ISSUE THREAD

**Issue by pczar1** [facebook/react-native#29862]
Hi,

I'd like to migrate from react-native 0.58.6 to 0.63.2.

I stucked in the place when I can install application on emulator and bundler do not give me any errors, but when I try to open application it's immediately crashing with following exception:

```
2020-09-04 12:53:02.194 17921-17921/com.kitchendisplay.debug E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "com.kitchendisplay.debug.androidx" on path: DexPathList[[zip file "/data/app/~~ciLDEohGnX7RVfFPzgqM5A==/com.kitchendisplay.debug-V7lq6JEjD-L1rsfQyN7Dow==/base.apk"],nativeLibraryDirectories=[/data/app/~~ciLDEohGnX7RVfFPzgqM5A==/com.kitchendisplay.debug-V7lq6JEjD-L1rsfQyN7Dow==/lib/x86, /data/app/~~ciLDEohGnX7RVfFPzgqM5A==/com.kitchendisplay.debug-V7lq6JEjD-L1rsfQyN7Dow==/base.apk!/lib/x86, /system/lib, /system_ext/lib, /product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:260)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:905)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:958)
        at android.app.LoadedApk.getResources(LoadedApk.java:1190)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2659)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2651)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6595)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2020-09-04 12:53:02.352 17921-17921/com.kitchendisplay.debug E/SoLoader: couldn't find DSO to load: libjscexecutor.so caused by: dlopen failed: library "libjsc.so" not found: needed by /data/app/~~ciLDEohGnX7RVfFPzgqM5A==/com.kitchendisplay.debug-V7lq6JEjD-L1rsfQyN7Dow==/lib/x86/libjscexecutor.so in namespace classloader-namespace result: 0
2020-09-04 12:53:02.577 17921-17962/com.kitchendisplay.debug E/SoLoader: couldn't find DSO to load: libhermes.so result: 0
    
    --------- beginning of crash
2020-09-04 12:53:02.578 17921-17962/com.kitchendisplay.debug E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.kitchendisplay.debug, PID: 17921
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:825)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:673)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:611)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:559)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:29)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1017)
        at java.lang.Thread.run(Thread.java:923)
2020-09-04 12:53:02.587 391-391/? E/Layer: [Surface(name=Task=81)/@0x62529bd - animation-leash#0] No local sync point found
2020-09-04 12:53:02.587 391-391/? E/Layer: [Surface(name=Task=81)/@0x62529bd - animation-leash#0] No local sync point found
2020-09-04 12:53:02.587 391-391/? E/Layer: [Surface(name=Task=1)/@0xb0fe141 - animation-leash#0] No local sync point found
2020-09-04 12:53:02.587 391-391/? E/Layer: [Surface(name=Task=1)/@0xb0fe141 - animation-leash#0] No local sync point found
2020-09-04 12:53:02.674 200-204/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup34: Permission denied
2020-09-04 12:53:02.678 200-204/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup35: Permission denied
```

**Comment by safaiyeh** [comment]
Hi @pczar1 thanks for the issue, please checkout the comment from the bot to handle upgrade issues! Thanks

**Comment by pczar1** [comment]
Hi,

So indeed I was able to fix the problem with that upgrade helper tool. Honestly speaking without it, that would be really challenging.
