### ISSUE TITLE
App crashes in production and error logged is not understandable

### ISSUE THREAD

**Issue by emil-keyvalue** [facebook/react-native#29905]
We send our app into production and on the crashlytics console it's showing this error message which I can't understand for the life in me.

## React Native version:
react-native: ^0.63.2 => 0.63.2 

```
Fatal Exception: com.facebook.react.common.JavascriptException: TypeError: c is not a function. (In 'c(R)', 'c' is false), stack:
value@228:7659
value@228:6915
onResponderRelease@228:5669
p@93:384
b@93:527
T@93:581
w@93:876
ke@93:12621
forEach@-1
_@93:2057
<unknown>@93:12968
xe@93:89817
Ee@93:12419
Re@93:12808
receiveTouches@93:13600
value@27:3350
<unknown>@27:747
value@27:2610
value@27:719
value@-1

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:237)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by SvenJonsson** [comment]
@emil-keyvalue: Got this crash in production as well. Any leads?

**Comment by emil-keyvalue** [comment]
@SvenJonsson Nope no leads, haven't been able to look into it.

**Comment by xiesw** [comment]
same problem
`Fatal Exception: RCTFatalException: Unhandled JS Exception: TypeError: v is not a function. (In 'v(t)', 'v' is false)
Unhandled JS Exception: TypeError: v is not a function. (In 'v(t)', 'v' is false), stack: value@230:7077 value@230:6333 onResponderRelease@230:5082 p@99:384 b@99:527 T@99:581 w@99:876 ke@99:12621 forEach@(null):(null) _@99:2057 <unknown>@99:12968 xe@99:89236 Se@99:12419 Re@99:12808 receiveTouches@99:13600 value@39:3350 <unknown>@39:747 value@39:2610 value@39:719 value@(null):(null)
RCTFormatError`

**Comment by nmanvitha** [comment]
Same problem. Any solution for this?
Fatal Exception: RCTFatalException: Unhandled JS Exception: TypeError: v is not a function. (In 'v(!1)', 'v' is undefined)
Unhandled JS Exception: TypeError: v is not a function. (In 'v(!1)', 'v' is undefined), stack: <unknown>@722:1144 <unknown>@78:1286 p@78:529 callTimers@78:2676 value@54:3579 <unknown>@54:758 value@54:2582 value@54:730 value@(null):(null)
