### ISSUE TITLE
App is crashing in android 

### ISSUE THREAD

**Issue by ShubhamC78** [facebook/react-native#29960]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Release build is crashing in andorid API 30 or Android R.

Error i am getting 

2020-09-16 15:09:04.988 11895-11895/? E/SoLoader: couldn't find DSO to load: libjscexecutor.so caused by: couldn't find DSO to load: libfb.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/user/0/com.microsoft.virtuosoV2Dev/lib-main/libc++_shared.so" is for EM_ARM (40) instead of EM_386 (3)

020-09-16 15:09:05.074 11895-11916/? E/SoLoader: couldn't find DSO to load: libhermes.so
    
    --------- beginning of crash
2020-09-16 15:09:05.075 11895-11916/? E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.microsoft.virtuosoV2Dev, PID: 11895
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:789)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:29)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:997)
        at java.lang.Thread.run(Thread.java:923)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by huytq98** [comment]
you can try delete build file in android/app/build then react-native run-android

**Comment by chiennv97** [comment]
Do follow below link, I try and success.
https://medium.com/@shreyasnisal/solved-packing-error-in-react-native-release-apk-f887687edc4f

**Comment by cortinico** [comment]
This and all the "couldn't find DSO to load" bugs have been fixed in React Native 0.71.

The issue on previous versions was a "too aggressive" clean-up logic in the `react.gradle` file. In 0.71 the clean-up logic has been rewritten to be more Android friendly and is now living inside the React Native Gradle Plugin.

I'm closing this, please update to 0.71 and open a new issue if the "couldn't find DSO to load" crash is still happening on 0.71+.
