### ISSUE TITLE
"FATAL EXCEPTION: mqt_native_modules" in release version of android app

### ISSUE THREAD

**Issue by pyataevsv** [facebook/react-native#29985]
## Description
I'm trying to test **release version** of my app on **Android** but getting and error while fetching a data
**Debug version works fine.**

## Steps To Reproduce
`npx react-native run-android --variant=release`

JS code which cause the error:
```
let url = 'http://XXX.XXX.XXX.XX:99/app/all'

 fetch(url, { mode: 'no-cors' })
        .catch(err => {
            dispatch(fetchErrText(JSON.stringify(err))) // {"line"115,"column":7258,"sourceURL":"index.android.bundle"}
        })
```

**JSON.stringify(err):**

`{"line"115,"column":7258,"sourceURL":"index.android.bundle"}`

Adb bugreport beginning of crash:

```
--------- beginning of crash
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: Process: com.mightio.signal, PID: 20734
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 20734, callerPackage: com.mightio.signal
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:1961)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1921)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1871)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.registerReceiver(IActivityManager.java:3732)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1498)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1459)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1447)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:633)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at com.android.billingclient.api.BillingBroadcastManager$BillingBroadcastReceiver.register(BillingBroadcastManager.java:81)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at com.android.billingclient.api.BillingBroadcastManager.registerReceiver(BillingBroadcastManager.java:53)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at com.android.billingclient.api.BillingClientImpl.startConnection(BillingClientImpl.java:298)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at com.dooboolab.RNIap.RNIapModule.initConnection(RNIapModule.java:138)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:201)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.registerReceiver(ActivityManagerService.java:21653)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact$registerReceiver$(IActivityManager.java:10227)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:155)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3400)
09-09 01:05:38.286 10350 20734 21089 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:726)
```

##  Environment:
OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 800.93 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ~16.11.0 => 16.11.0 
    react-native: ~0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by pyataevsv** [comment]
My it be from my not-secure URL http?

**Comment by nicastelo** [comment]
@pyataevsv Did you solve it?

**Comment by pyataevsv** [comment]
@nicastelo Yes the problem was in http connection and it can be solved via ssl or via changing android manifest file

**Comment by hanifmhd** [comment]
i'm still facing this issue on RN.0.64.0, any solution about it?
