### ISSUE TITLE
couldn't find DSO to load: libyoga.so caused by: couldn't find DSO to load: libfb.so caused by:.........

### ISSUE THREAD

**Issue by Mohammad-Adam** [facebook/react-native#30035]
this happens if I publish the app to the play store and then install the app from the play store, but if I install the apk directly to the phone then things are fine;

### case of play store then phone [app crashes]:

> data/data/com.myapp/lib -> doesn't exist
> data/data/com.myapp/lib-0 -> .so files are here
> data/data/com.myapp/[lib-1, lib-2, lib-main] -> empty
> data/app/com.myapp/lib/arm64 -> empty

### case of apk to phone directly [app working]:

> data/data/com.myapp/[lib, lib-0, lib-1, lib-2, lib-main] -> doesn't exist
> data/app/com.myapp/lib/arm64 -> .so files are here

## stacktrace
```
msg: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libyoga.so caused by: couldn't find DSO to load: libfb.so caused by: Didn't find class "com.facebook.jni.HybridData$Destructor" on path: DexPathList[[zip file "/data/app/com.*******-*****************==/base.apk", zip file "/data/app/com.**************-*****************==/split_config.arm64_v8a.apk", zip file "/data/app/com.***********-*************==/split_config.en.apk", zip file "/data/app/com.********-*******************==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.*********-***************==/lib/arm64, /data/app/com.********-*******************==/base.apk!/lib/arm64-v8a, /data/app/com.********-*******************==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.********-*******************==/split_config.en.apk!/lib/arm64-v8a, /data/app/com.********-*******************==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64]] result: 0 result: 0
stacktrace: com.facebook.litho.a0: RecyclerCollectionComponent
Caused by: com.facebook.litho.a0: Column
Caused by: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libyoga.so caused by: couldn't find DSO to load: libfb.so caused by: Didn't find class "com.facebook.jni.HybridData$Destructor" on path: DexPathList[[zip file "/data/app/com.********-*******************==/base.apk", zip file "/data/app/com.********-*******************==/split_config.arm64_v8a.apk", zip file "/data/app/com.********-*******************==/split_config.en.apk", zip file "/data/app/com.********-*******************==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.********-*******************==/lib/arm64, /data/app/com.********-*******************==/base.apk!/lib/arm64-v8a, /data/app/com.********-*******************==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.********-*******************==/split_config.en.apk!/lib/arm64-v8a, /data/app/com.********-*******************==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64]] result: 0 result: 0
	at com.facebook.j0.l.c(Unknown Source:343)
	at com.facebook.j0.l.o(Unknown Source:104)
	at com.facebook.j0.l.n(Unknown Source:2)
	at com.facebook.j0.l.l(Unknown Source:106)
	at com.facebook.j0.l.k(Unknown Source:1)
	at com.facebook.yoga.YogaNative.<clinit>(Unknown Source:2)
	at com.facebook.yoga.YogaNative.jni_YGConfigNew(Native Method)
	at com.facebook.yoga.a.<init>(Unknown Source:3)
	at com.facebook.yoga.b.a(Unknown Source:2)
	at com.facebook.litho.d6.a.a(Unknown Source:0)
	at com.facebook.litho.o3.<clinit>(Unknown Source:0)
	at com.facebook.litho.n2.a(Unknown Source:0)
	at com.facebook.litho.h.J1(Unknown Source:0)
	at com.facebook.litho.p2.g(Unknown Source:83)
	at com.facebook.litho.p2.f(Unknown Source:1)
	at com.facebook.litho.p2.g(Unknown Source:126)
	at com.facebook.litho.p2.f(Unknown Source:1)
	at com.facebook.litho.p2.i(Unknown Source:23)
	at com.facebook.litho.s2.z(Unknown Source:286)
	at com.facebook.litho.ComponentTree$e.d(Unknown Source:111)
	at com.facebook.litho.ComponentTree$e.c(Unknown Source:0)
	at com.facebook.litho.ComponentTree$e$a.a(Unknown Source:17)
	at com.facebook.litho.ComponentTree$e$a.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.facebook.litho.ComponentTree$e.m(Unknown Source:15)
	at com.facebook.litho.ComponentTree.y(Unknown Source:82)
	at com.facebook.litho.ComponentTree.x(Unknown Source:96)
	at com.facebook.litho.ComponentTree.P0(Unknown Source:287)
	at com.facebook.litho.ComponentTree.T0(Unknown Source:13)
	at com.facebook.litho.ComponentTree.y0(Unknown Source:104)
	at com.facebook.litho.LithoView.onMeasure(Unknown Source:177)
	at android.view.View.measure(View.java:23233)
	at androidx.constraintlayout.widget.ConstraintLayout$c.b(Unknown Source:405)
	at e.c.b.k.m.b.a(Unknown Source:114)
	at e.c.b.k.m.b.b(Unknown Source:72)
	at e.c.b.k.m.b.d(Unknown Source:284)
	at e.c.b.k.f.Y0(Unknown Source:23)
	at androidx.constraintlayout.widget.ConstraintLayout.o(Unknown Source:135)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(Unknown Source:31)
	at android.view.View.measure(View.java:23233)
	at androidx.viewpager.widget.ViewPager.onMeasure(Unknown Source:234)
	at android.view.View.measure(View.java:23233)
	at androidx.constraintlayout.widget.ConstraintLayout$c.b(Unknown Source:405)
	at e.c.b.k.m.b.a(Unknown Source:114)
	at e.c.b.k.m.b.d(Unknown Source:594)
	at e.c.b.k.f.Y0(Unknown Source:23)
	at androidx.constraintlayout.widget.ConstraintLayout.o(Unknown Source:135)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(Unknown Source:31)
	at android.view.View.measure(View.java:23233)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6748)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23233)
	at androidx.constraintlayout.widget.ConstraintLayout$c.b(Unknown Source:405)
	at e.c.b.k.m.b.a(Unknown Source:114)
	at e.c.b.k.m.b.d(Unknown Source:594)
	at e.c.b.k.f.Y0(Unknown Source:23)
	at androidx.constraintlayout.widget.ConstraintLayout.o(Unknown Source:135)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(Unknown Source:31)
	at android.view.View.measure(View.java:23233)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6748)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:154)
	at android.view.View.measure(View.java:23233)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6748)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23233)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6748)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23233)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6748)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
	at android.view.View.measure(View.java:23233)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6748)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:729)
	at android.view.View.measure(View.java:23233)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2769)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1619)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1902)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1507)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7431)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1019)
	at android.view.Choreographer.doCallbacks(Choreographer.java:830)
	at android.view.Choreographer.doFrame(Choreographer.java:765)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1005)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6698)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
```

**Comment by cortinico** [comment]
This and all the "couldn't find DSO to load" bugs have been fixed in React Native 0.71.

The issue on previous versions was a "too aggressive" clean-up logic in the `react.gradle` file. In 0.71 the clean-up logic has been rewritten to be more Android friendly and is now living inside the React Native Gradle Plugin.

I'm closing this, please update to 0.71 and open a new issue if the "couldn't find DSO to load" crash is still happening on 0.71+.
