### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.animated.NativeAnimatedNodesManager.createAnimatedNode(int, com.facebook.react.bridge.ReadableMap)' on a null object reference

### ISSUE THREAD

**Issue by b3hz4d** [facebook/react-native#30115]
Hi
I have problem with some devices that crashes on app startup

## Description
Here is the stack trace of crash
```
Fatal Exception: java.lang.IllegalStateException: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.react.animated.NativeAnimatedNodesManager.createAnimatedNode(int, com.facebook.react.bridge.ReadableMap)' on a null object reference
       at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:390)
       at com.facebook.react.bridge.ReactContext$ExceptionHandlerWrapper.handleException(ReactContext.java:397)
       at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:33)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6864)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

## React Native version:
```
System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 14.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 4, 7, 8
      Build Tools: 17.0.0, 18.0.1, 18.1.0, 18.1.1, 19.0.0, 19.0.1, 19.0.2, 19.0.3, 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.0, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.2, 29.0.3
      System Images: android-19 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  Languages:
    Java: Not Found
    Python: 2.7.16
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by tijs** [comment]
Yeah we have the same issue in Crashlytics. Not much to go on with that stack trace i'm afraid. My current theory is that we are using a `nativeDrive: true` in an animation somewhere where we should not. See the caveat here for instance which seems to mostly be an issue on Android: https://reactnative.dev/blog/2017/02/14/using-native-driver-for-animated#caveats

**Comment by Sheharyar566** [comment]
Any progress on this? I am salso getting the same logs on sentry

**Comment by r1jsheth** [comment]
Facing similar issue!
