### ISSUE TITLE
[question]react native android

### ISSUE THREAD

**Issue by cangku** [facebook/react-native#3021]
```
>react-native init MyProject
This will walk you through creating a new React Native project in d:\www\project
\MyProject
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn npm ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by cangku** [comment]
Has been resolved

**Comment by cangku** [comment]
Has been resolved
