### ISSUE TITLE
React-native/hermes bui;d error. no such file or directory: index.android.bundle.packager.map

### ISSUE THREAD

**Issue by rahamin1** [facebook/react-native#30223]
#### Getting the following messages during buld with hermesEnabled set to true:
*('...' represent removed text):*

```
android\app\build\generated\assets\react\release\index.android.bundle:13:134: warning: the variable "Promise" was not declared in function "isBoldTextEnabled"
    ...
    android\app\build\generated\assets\react\release\index.android.bundle:27:2907: warning: the variable "DebuggerInternal" was not declared in function "value 14#"
    ...
    android\app\build\generated\assets\react\release\index.android.bundle:92:57773: warning: the variable "setTimeout" was not declared in function "wi"
    ...

fs.js:114
    throw err;
    ^
    Error: ENOENT: no such file or directory, open 'android\app\build\intermediates\sourcemaps\react\release\index.android.bundle.packager.map'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (C:\esites-grocery\test2.hermes\plumpclient\node_modules\react-native\scripts\compose-source-maps.js:33:43)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)

    FAILURE: Build failed with an exception.

    * Where:
    Script 'node_modules\react-native\react.gradle' line: 191
    
    * What went wrong:
    Execution failed for task ':app:bundleReleaseJsAndAssets'.
    > Process 'command 'cmd'' finished with non-zero exit value 1
```
(The referenced file exists, at least after the build failed).

## React Native version:
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 3.33 GB / 15.87 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 25.0.2, 28.0.3, 29.0.2, 29.0.3
      System Images: android-25 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  2.3.0.0 AI-162.3764568
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_112-release
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2

## What I tried to do
- Tried to bump soLoader to 0.8.0 and to 0.8.2 (although this is not supposed to be needed in RN 0.62.2) as suggested in https://github.com/facebook/react-native/issues/25927#issuecomment-539415154

## Steps To Reproduce
Large app, difficult to create a small example. 
I hope, as it happened in similar issues, that somebody has an idea without it.

## Expected Results
Build successfully.

**Comment by rahamin1** [comment]
Modifying the following extra packages definition in build.gradle:

    extraPackagerArgs: ["--sourcemap-output", "$buildDir/intermediates/assets/release/index.android.bundle.map"]

to 

    extraPackagerArgs: ["--sourcemap-output", "$buildDir/intermediates/sourcemaps/react/release/index.android.bundle.packager.map"]

Fixed the error (the warnings are still there).  
An APK is created and is running..
