### ISSUE TITLE
"type":"InternalError","message":"react-packager has encountered an internal error

### ISSUE THREAD

**Issue by hlddn** [facebook/react-native#3022]
[14:06:48] <START> Building Dependency Graph
[14:06:48] <START> Crawling File System
TypeError: Cannot read property 'root' of null
    at /Users/hl/Desktop/AwesomeProject/node_modules/react-native/packager/react-packager/src/DependencyResolver/crawlers/index.js:16:84
    at tryCallOne (/Users/hl/Desktop/AwesomeProject/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/hl/Desktop/AwesomeProject/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/hl/Desktop/AwesomeProject/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
[14:06:49] <START> request:/index.ios.bundle
[14:06:49] <START> find dependencies

**Comment by mauriciord** [comment]
Same problem here.

**Comment by pruhstal** [comment]
Likewise. I've updated watchman, and am on HEAD for all other dependencies.

**Comment by mauriciord** [comment]
I've installed nvm and latest node, and after i used:

brew update && brew upgrade watchman

Working 100% now

Enviado do iPhone
Mauricio R Duarte
[mauriciord@me.com | mauriciotem@gmail.com]

**Comment by hlddn** [comment]
THX mauriciord !
I'm upgraded the node to 4.1.1 and watchman to 3.8.0,it's working now!!!
