### ISSUE TITLE
[Example Movies][Android] Crashes with TypeError on OSX

### ISSUE THREAD

**Issue by GerritWanderer** [facebook/react-native#3033]
HI folks,
I followed the guidelines to setup Android development with react-native on Mac OSX and a new initialized HelloWorld Application runs successfully inside the simulator.
However, when I try to start the movies example app, I get the following error screen:
**TypeError: expected dynamic type 'string', but had type 'int64'.**

The application has been configured and installed with the following steps:
```javascript
npm install
./gradlew :Examples:Movies:android:app:installDebug
./packager/packager.sh
```

![bildschirmfoto 2015-09-25 um 14 46 41](https://cloud.githubusercontent.com/assets/226185/10103080/60f02ace-63a2-11e5-955e-4ab5a96814c3.png)

Is this issue already known? Can I provide somehow a better crashreport?

**Comment by xslim** [comment]
I have the same issue with `Movies` and `UIExplorer` example apps. No matter what I try.
Tested on Google Android API `22` & `23` emulator

**Comment by chirag04** [comment]
I just got the same error for UIExplorer

**Comment by luisbebop** [comment]
Got the same error with `Movies` and `UIExplorer` when I install it on a device running Android 5.0. Both apps close before load the JS application bundle.

Following the log error captured with `adb logcat`:

```shel
E/unknown:React( 4614): Exception in native call from JS
E/unknown:React( 4614): com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `string', but had type `int64'
E/unknown:React( 4614): 	at com.facebook.react.bridge.ReadableNativeMap.getString(Native Method)
E/unknown:React( 4614): 	at com.facebook.react.uimanager.CatalystStylesDiffMap.getString(CatalystStylesDiffMap.java:72)
E/unknown:React( 4614): 	at com.facebook.react.views.text.ReactTextShadowNode.updateProperties(ReactTextShadowNode.java:310)
E/unknown:React( 4614): 	at com.facebook.react.views.textinput.ReactTextInputShadowNode.updateProperties(ReactTextInputShadowNode.java:102)
E/unknown:React( 4614): 	at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:256)
E/unknown:React( 4614): 	at java.lang.reflect.Method.invoke(Native Method)
E/unknown:React( 4614): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/unknown:React( 4614): 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:106)
E/unknown:React( 4614): 	at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:126)
E/unknown:React( 4614): 	at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:64)
E/unknown:React( 4614): 	at com.facebook.react.bridge.CatalystInstance$NativeModulesReactCallback.call(CatalystInstance.java:326)
E/unknown:React( 4614): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E/unknown:React( 4614): 	at android.os.Handler.handleCallback(Handler.java:739)
E/unknown:React( 4614): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/unknown:React( 4614): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
E/unknown:React( 4614): 	at android.os.Looper.loop(Looper.java:135)
E/unknown:React( 4614): 	at com.facebook.react.bridge.queue.MessageQueueThread$1.run(MessageQueueThread.java:137)
E/unknown:React( 4614): 	at java.lang.Thread.run(Thread.java:831)
I/PhoneStatusBar( 3355): hw_status_bar_operators = true, setSystemUIVisibily(SHOW_OPERATOR = false)
E/AndroidRuntime( 4614): FATAL EXCEPTION: main
E/AndroidRuntime( 4614): Process: com.facebook.react.movies, PID: 4614
E/AndroidRuntime( 4614): com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `string', but had type `int64'
E/AndroidRuntime( 4614): 	at com.facebook.react.bridge.ReadableNativeMap.getString(Native Method)
E/AndroidRuntime( 4614): 	at com.facebook.react.uimanager.CatalystStylesDiffMap.getString(CatalystStylesDiffMap.java:72)
E/AndroidRuntime( 4614): 	at com.facebook.react.uimanager.BaseViewPropertyApplicator.applyCommonViewProperties(BaseViewPropertyApplicator.java:77)
E/AndroidRuntime( 4614): 	at com.facebook.react.uimanager.ViewGroupManager.updateView(ViewGroupManager.java:28)
E/AndroidRuntime( 4614): 	at com.facebook.react.views.view.ReactViewManager.updateView(ReactViewManager.java:87)
E/AndroidRuntime( 4614): 	at com.facebook.react.views.view.ReactViewManager.updateView(ReactViewManager.java:40)
E/AndroidRuntime( 4614): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:182)
E/AndroidRuntime( 4614): 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:137)
E/AndroidRuntime( 4614): 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:574)
E/AndroidRuntime( 4614): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:622)
E/AndroidRuntime( 4614): 	at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
E/AndroidRuntime( 4614): 	at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:114)
E/AndroidRuntime( 4614): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
E/AndroidRuntime( 4614): 	at android.view.Choreographer.doCallbacks(Choreographer.java:606)
E/AndroidRuntime( 4614): 	at android.view.Choreographer.doFrame(Choreographer.java:574)
E/AndroidRuntime( 4614): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:779)
E/AndroidRuntime( 4614): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 4614): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 4614): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 4614): 	at android.app.ActivityThread.main(ActivityThread.java:5538)
E/AndroidRuntime( 4614): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4614): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 4614): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
E/AndroidRuntime( 4614): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
W/System.err( 2925): java.lang.NullPointerException: Attempt to invoke virtual method 'int com.huawei.lcagent.client.LogCollectManager.getUserType()' on a null object reference
W/System.err( 2925): 	at huawei.com.android.server.util.ReportTool.getUserType(ReportTool.java:86)
W/System.err( 2925): 	at huawei.com.android.server.util.ReportTool.isBetaUser(ReportTool.java:73)
W/System.err( 2925): 	at huawei.com.android.server.util.ReportTool.report(ReportTool.java:58)
W/System.err( 2925): 	at huawei.com.android.server.util.UserBehaviourRecord.appExitRecord(UserBehaviourRecord.java:65)
W/System.err( 2925): 	at com.android.server.am.ActivityManagerService$MainHandler.handleMessage(ActivityManagerService.java:1425)
W/System.err( 2925): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 2925): 	at android.os.Looper.loop(Looper.java:135)
W/System.err( 2925): 	at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err( 2925): 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
E/ReportTools( 2925): This is not beta user build
I/Process ( 4614): Sending signal. PID: 4614 SIG: 9l
```

**Comment by luisbebop** [comment]
Fixed the problem.

I needed to update the version of the react-native library on the .gradle file at `Examples/Movies/android/app/build.gradle` and  `Examples/UIExplorer/android/app/build.gradle` setting the react-native library to `compile 'com.facebook.react:react-native:0.12.+'` instead of 0.11._

I forced the installation of the newest version of react `npm i react-native@0.12.0-rc` as well.

Now the `Movies` app is working. 

Additionally, to make the `UIExplorer` work you should comment the lines `logo={require('image!launcher_icon')}` and `navIcon={require('image!ic_menu_black_24dp')}` at `UIExplorerApp.android.js` to get it running. There is a problem with these properties and these examples. Still haven't figured out though what is happening, but the example is functional.

https://github.com/facebook/react-native/pull/3286

**Comment by GerritWanderer** [comment]
Thanks @luisbebop! I'll give your instructions a try.

**Comment by satya164** [comment]
Closing this as this should be fixed with recent versions. Lets reopen if still an issue.
