### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'void android.widget.Editor$InsertionPointCursorController.hide()' on a null object reference com.facebook.react.views.textinput.ReactEditText.setInputType

### ISSUE THREAD

**Issue by KamranKhn** [facebook/react-native#30346]
Description : - 
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Editor$InsertionPointCursorController.hide()' on a null object reference
       at android.widget.Editor.stopTextActionMode(Editor.java:2687)
       at android.widget.Editor.prepareCursorControllers(Editor.java:822)
       at android.widget.TextView.nullLayouts(TextView.java:9161)
       at android.widget.TextView.setTypeface(TextView.java:4295)
       at android.widget.TextView.setTypeface(TextView.java:2474)
       at android.widget.TextView.resolveStyleAndSetTypeface(TextView.java:2367)
       at android.widget.TextView.setTypefaceFromAttrs(TextView.java:2354)
       at android.widget.TextView.setInputType(TextView.java:6650)
       at com.facebook.react.views.textinput.ReactEditText.setInputType(ReactEditText.java:333)
       at com.facebook.react.views.textinput.ReactEditText.commitStagedInputType(ReactEditText.java:325)
       at com.facebook.react.views.textinput.ReactTextInputManager.onAfterUpdateTransaction(ReactTextInputManager.java:744)
       at com.facebook.react.views.textinput.ReactTextInputManager.onAfterUpdateTransaction(ReactTextInputManager.java:65)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:38)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:136)
       at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:95)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:917)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1025)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:46)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1085)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:693)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7089)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

## React Native version:
"react-native": "0.63.3"

##Device:-
Brand: samsung
Model: Galaxy A70
Orientation: Portrait
RAM free: 1.71 GB
Disk free: 89.5 GB
Version: 9
Orientation: Portrait

**Comment by fabriziobertoglio1987** [comment]
Last time I read this issues I got here, but I think it is hard to solve as we don't know how to reproduce it.
https://github.com/aosp-mirror/platform_frameworks_base/blob/10eb5d0fafa033e35f8d4bbbd06a2d4701ff35e1/core/java/android/widget/TextView.java#L8890-L8907
```java
    /** @hide */
    @VisibleForTesting
    @UnsupportedAppUsage
    public void nullLayouts() {
        if (mLayout instanceof BoringLayout && mSavedLayout == null) {
            mSavedLayout = (BoringLayout) mLayout;
        }
        if (mHintLayout instanceof BoringLayout && mSavedHintLayout == null) {
            mSavedHintLayout = (BoringLayout) mHintLayout;
        }

        mSavedMarqueeModeLayout = mLayout = mHintLayout = null;

        mBoring = mHintBoring = null;

        // Since it depends on the value of mLayout
        if (mEditor != null) mEditor.prepareCursorControllers();
    }
```

**Comment by OrkhanAlikhanov** [comment]
Just for information

### React native
Version: 0.67.2

### Device
Brand: samsung
Model: Galaxy J8
Orientation: Portrait
RAM free: 867 MB
Disk free: 728.23 MB

### Operating System
Version: Android 9
Orientation: Portrait
Rooted:No

<details>
<summary>
Click to see <b>stack trace</b>
</summary>

```SaltStack
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Editor$InsertionPointCursorController.hide()' on a null object reference
       at android.widget.Editor.stopTextActionMode(Editor.java:2687)
       at android.widget.Editor.prepareCursorControllers(Editor.java:822)
       at android.widget.TextView.nullLayouts(TextView.java:9174)
       at android.widget.TextView.setTypeface(TextView.java:4308)
       at android.widget.TextView.setTypeface(TextView.java:2491)
       at android.widget.TextView.resolveStyleAndSetTypeface(TextView.java:2384)
       at android.widget.TextView.setTypefaceFromAttrs(TextView.java:2371)
       at android.widget.TextView.setInputType(TextView.java:6663)
       at com.facebook.react.views.textinput.ReactEditText.setInputType(ReactEditText.java:435)
       at com.facebook.react.views.textinput.ReactEditText.commitStagedInputType(ReactEditText.java:427)
       at com.facebook.react.views.textinput.ReactTextInputManager.onAfterUpdateTransaction(ReactTextInputManager.java:927)
       at com.facebook.react.views.textinput.ReactTextInputManager.onAfterUpdateTransaction(ReactTextInputManager.java:81)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:49)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:142)
       at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:93)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:693)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7078)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
```
</details>
