### ISSUE TITLE
[Android 4.4 Crash] Focus TextInput Make Crash on android 4.4

### ISSUE THREAD

**Issue by NguyenHoangMinhkkkk** [facebook/react-native#30368]
[Android 4.4 Crash] Focus TextInput Make Crash Only On Android 4.4

## Description
E/unknown:ReactNative: Exception in native call com.facebook.react.uimanager.IllegalViewOperationException

## React Native version:
 OS: macOS 10.15.6
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 4.77 GB / 24.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 16, 18, 19, 21, 22, 23, 24, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0
      System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-22 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
  npmGlobalPackages:
    react-native-macos-cli: 2.0.1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

Using emulator or real device with android version 4.4
- react-native init MyApp --version 0.63.3
- cd MyApp
- react-native run-android
- focus on TextInput

![Screen Shot 2020-11-12 at 12 24 25](https://user-images.githubusercontent.com/30792140/98899498-3aa47f80-24e2-11eb-83a9-6435fa72e1c6.png)

E/unknown:ReactNative: Exception in native call
    com.facebook.react.uimanager.IllegalViewOperationException
        at com.facebook.react.ReactRootView.handleException(ReactRootView.java:615)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:711)
        at android.view.View.draw(View.java:15245)
        at android.view.View.getDisplayList(View.java:14136)
        at android.view.View.getDisplayList(View.java:14178)
        at android.view.View.draw(View.java:14956)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.getDisplayList(View.java:14131)
        at android.view.View.getDisplayList(View.java:14178)
        at android.view.View.draw(View.java:14956)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.getDisplayList(View.java:14131)
        at android.view.View.getDisplayList(View.java:14178)
        at android.view.View.draw(View.java:14956)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
        at android.view.View.draw(View.java:15245)
        at android.widget.FrameLayout.draw(FrameLayout.java:472)
        at android.widget.HorizontalScrollView.draw(HorizontalScrollView.java:2059)
        at com.facebook.react.views.scroll.ReactHorizontalScrollView.draw(ReactHorizontalScrollView.java:578)
        at android.view.View.getDisplayList(View.java:14136)
        at android.view.View.getDisplayList(View.java:14178)
        at android.view.View.draw(View.java:14956)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:15245)
        at android.view.View.getDisplayList(View.java:14136)
        at android.view.View.getDisplayList(View.java:14178)
        at android.view.View.draw(View.java:14956)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:15245)
        at android.view.View.getDisplayList(View.java:14136)
        at android.view.View.getDisplayList(View.java:14178)
        at android.view.View.draw(View.java:14956)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.getDisplayList(View.java:14131)
        at android.view.View.getDisplayList(View.java:14178)
        at android.view.View.draw(View.java:14956)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
        at android.view.View.draw(View.java:15245)
        at android.widget.FrameLayout.draw(FrameLayout.java:472)
        at android.widget.ScrollView.draw(ScrollView.java:2184)
        at com.facebook.react.views.scroll.ReactScrollView.draw(ReactScrollView.java:465)
        at android.view.View.getDisplayList(View.java:14136)
        at android.view.View.getDisplayList(View.java:14178)
        at android.view.View.draw(View.java:14956)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3153)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:15245)
        at android.view.View.getDisplayList(View.java:14136)
        at android.view.View.getDisplayList(View.java:14178)
        at android.view.View.draw(View.java:14956)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3309)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3146)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:15245)
    	at android.vi

**Comment by damirjuretic** [comment]
Hi @NguyenHoangMinhkkkk, I solved it by removing enableScreens(), lib react-native-screens.

**Comment by NguyenHoangMinhkkkk** [comment]
> Hi @NguyenHoangMinhkkkk, I solved it by removing enableScreens(), lib react-native-screens.

Hi damirjuretic, thanks for your attention and solution.
Some days ago, i was doing some solution to prevent this case happen but doesnt facing this problem.
i'll give it a try.

Best regards.

**Comment by AbdullahAsendar** [comment]
@NguyenHoangMinhkkkk were you able to fix the issue?

**Comment by NguyenHoangMinhkkkk** [comment]
> @NguyenHoangMinhkkkk were you able to fix the issue?

Dear. we desided to increase our android app minVersion to Lollipop instead of Jelly Bean for some reasons.
So that we avoided a lot of issue include this issue.

**Comment by fabriziobertoglio1987** [comment]
android 4.4 is not supported, this issue should be closed

**Comment by HessiPard** [comment]
have this problem too ... but exactly in inputs where exists in nested tab view inside another tab view ... [issue](https://github.com/satya164/react-native-tab-view/issues/1129)

**Comment by HessiPard** [comment]
> Hi @NguyenHoangMinhkkkk, I solved it by removing enableScreens(), lib react-native-screens.

how did you exactly do that? thanks
