### ISSUE TITLE
fetch request no response/error, memory leak 

### ISSUE THREAD

**Issue by xbaker** [facebook/react-native#30394]
sending a request with Axios or fetch in Android to any API

**no response, no error, no warning and memory use get increase !!!**

## Description
Start  new react-native project, send post/get request to any api using axios/fetch
```
fetch('https://reactnative.dev/movies.json')
    .then((response) => response.json())
    .then((json) => {
       console.log(json);
    })
    .catch((error) => {
      console.error(error);
    });
```

## React Native version:
```
System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
    Memory: 3.10 GB / 22.77 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 15.2.0 - /usr/bin/node
    Yarn: Not Found
    npm: 7.0.8 - /usr/bin/npm
    Watchman: 20200920.192359.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 24.0.1, 25.0.3, 26.0.2, 27.0.3, 28.0.0, 28.0.3, 29.0.2
      System Images: android-23 | Android TV ARM EABI v7a, android-23 | Android TV Intel x86 Atom, android-23 | Android Wear ARM EABI v7a, android-23 | Android Wear Intel x86 Atom, android-23 | ARM EABI v7a, android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom
      Android NDK: 21.3.6528147
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.7 - /usr/bin/javac
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.13.0 => 4.13.0 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.Start  new react-native project, 
2.send post/get request to any api using axios/fetch

## Expected Results
get the result, normal memory use.

**Comment by xbaker** [comment]
my be this debug can help
## Requirement 

1. install node 
2. start console
3. install whatwg-fetch

> start node console

```
tarik@tarik-HP-ZBook-15:/media/tarik/dev/mobile$ node
Welcome to Node.js v15.2.0.
Type ".help" for more information.
> require('whatwg-fetch')
{
  DOMException: [Function (anonymous)],
  Headers: [Function: Headers],
  Request: [Function: Request],
  Response: [Function: Response] {
    error: [Function (anonymous)],
    redirect: [Function (anonymous)]
  },
  fetch: [Function: fetch] { polyfill: true }
}
> fetch('https://reactnative.dev/movies.json').then((response) => response.json()).then((json) => {console.log(json);}) .catch((error) => {console.error(error); });
Promise { <pending> }
> ReferenceError: XMLHttpRequest is not defined
    at /media/tarik/bf398058-3504-42ee-9149-38ac2105b845/project/workspace/xfantome/restoration/mobile/node_modules/whatwg-fetch/dist/fetch.umd.js:506:17
    at new Promise (<anonymous>)
    at fetch (/media/tarik/bf398058-3504-42ee-9149-38ac2105b845/project/workspace/xfantome/restoration/mobile/node_modules/whatwg-fetch/dist/fetch.umd.js:499:12)
    at REPL2:1:1
    at Script.runInThisContext (node:vm:132:18)
    at REPLServer.defaultEval (node:repl:474:29)
    at bound (node:domain:413:15)
    at REPLServer.runBound [as eval] (node:domain:424:12)
    at REPLServer.onLine (node:repl:793:10)
    at REPLServer.emit (node:events:341:22)




```

**Comment by xbaker** [comment]
```
 [11:48:15] W | ReactNativeJS ▶︎ Require cycle: node_modules/whatwg-fetch/dist/fetch.umd.js -> node_modules/react-native/Libraries/Network/fetch.js -> node_modules/whatwg-fetch/dist/fetch.umd.js
                             │ 
                             └ Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

[11:48:15] W | ReactNativeJS ▶︎ Require cycle: node_modules/react-native/Libraries/Network/fetch.js -> node_modules/react-native/Libraries/Network/fetch.js
                             │ 
                             │ Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
                             │ Require cycle: node_modules/react-native/Libraries/Network/fetch.js -> node_modules/react-native/Libraries/Network/fetch.js
                             │ 
                             │ Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
                             │ Require cycle: node_modules/react-native/Libraries/Network/fetch.js -> node_modules/react-native/Libraries/Network/fetch.js
                             │ 
                             └ Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

```


Any time :)

**Comment by xbaker** [comment]
remove this 

```

    [
      "@babel/plugin-proposal-class-properties",
      {
        "loose": false
      }
    ]
````
from .babelrc its work again
