### ISSUE TITLE
Running 'yarn lint --fix' fails

### ISSUE THREAD

**Issue by rectified95** [facebook/react-native#30408]
## Summary
Running the linter on master fails (latest commit from Nov 16th - 68a476103a95be77f4fc7c582e52cc94946de1b4).

```
Oops! Something went wrong! :(
 
ESLint: 7.12.0
 
D:\react1\react-native\packages\react-native-codegen\src\parsers\flow\modules\index.js:13
import type {
^^^^^^
 
SyntaxError: Cannot use import statement outside a module
    at new Script (node:vm:100:7)
    at NativeCompileCache._moduleCompile (D:\react1\react-native\node_modules\v8-compile-cache\v8-compile-cache.js:242:18)
    at Module._compile (D:\react1\react-native\node_modules\v8-compile-cache\v8-compile-cache.js:186:36)
    at Module._compile (D:\react1\react-native\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Object.newLoader [as .js] (D:\react1\react-native\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (D:\react1\react-native\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
error Command failed with exit code 2.
```

## React Native version:
System:
    OS: Windows 10 10.0.21257
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 17.45 GB / 31.79 GB
  Binaries:
    Node: 15.1.0 - C:\Program Files\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: 19.2.5345600
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 15.9.28307.1274 (Visual Studio Enterprise 2017), 16.7.30503.244 (Visual Studio Enterprise 2019)
  Languages:
    Java: 1.8.0_272
    Python: 2.7.17
  npmPackages:
    @react-native-community/cli: ^4.13.0 => 4.13.0
    react: 17.0.1 => 17.0.1
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by dulmandakh** [comment]
sorry, the issue is not related to RN, but ESLint. please check your config.

**Comment by rectified95** [comment]
I believe it has to do
