### ISSUE TITLE
App instantly crashes on release build, but works in dev mode

### ISSUE THREAD

**Issue by densi97** [facebook/react-native#30443]
App is working in dev mode, but instantly crashes on release mode.

## React Native version:
react-native: ~0.62.2 => 0.62.2

## Steps To Reproduce
react-native run-android --variant=release 

Build runs without issues but when opening the app it instantly crashes with the following error (adb logcat):
```
11-20 16:00:16.772 12720 12763 E AndroidRuntime: FATAL EXCEPTION: create_react_context
11-20 16:00:16.772 12720 12763 E AndroidRuntime: Process: de.nextlevelshopping.app, PID: 12720
11-20 16:00:16.772 12720 12763 E AndroidRuntime: com.facebook.jni.CppException: facebook::react::Recoverable: Could not open fileapp.bundle: No such file or directory
11-20 16:00:16.772 12720 12763 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromFile(Native Method)
11-20 16:00:16.772 12720 12763 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromFile(CatalystInstanceImpl.java:241)
11-20 16:00:16.772 12720 12763 E AndroidRuntime: 	at com.facebook.react.bridge.JSBundleLoader$2.loadScript(JSBundleLoader.java:48)
11-20 16:00:16.772 12720 12763 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:259)
11-20 16:00:16.772 12720 12763 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1243)
11-20 16:00:16.772 12720 12763 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:132)
11-20 16:00:16.772 12720 12763 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:996)
11-20 16:00:16.772 12720 12763 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
```

Content of build.gradle:
```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 24
        compileSdkVersion = 28
        targetSdkVersion = 28
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.google.gms:google-services:4.3.3'
        classpath('com.android.tools.build:gradle:3.5.1')

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
         maven { 
            url "https://github.com/jitsi/jitsi-maven-repository/raw/master/releases"
        }
        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}
```

Content of app/build.gradle:
```
apply plugin: "com.android.application"
apply plugin: 'com.google.gms.google-services'

import com.android.build.OutputFile

project.ext.react = [
    enableHermes: false,
    entryFile: "index.js",
    bundleAssetName:"app.bundle",
]

apply from: '../../node_modules/react-native-unimodules/gradle.groovy'
apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/expo-updates/scripts/create-manifest-android.gradle"

def enableSeparateBuildPerCPUArchitecture = false
def enableProguardInReleaseBuilds = false
def jscFlavor = 'org.webkit:android-jsc:+'
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId 'de.nextlevelshopping.app'
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 2
        versionName "1.0.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }

    packagingOptions {
        pickFirst "lib/armeabi-v7a/libc++_shared.so"
        pickFirst "lib/arm64-v8a/libc++_shared.so"
        pickFirst "lib/x86/libc++_shared.so"
        pickFirst "lib/x86_64/libc++_shared.so"
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"
    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }
    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }
    addUnimodulesDependencies()

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
    implementation (project(':react-native-jitsi-meet')) {
        exclude group: 'com.facebook.react', module:'react-native-community-async-storage'
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

apply plugin: 'com.google.gms.google-services'
```

**Comment by SConaway** [comment]
@densi97 

Not sure if this will help, but here's my idea: remove the `bundleAssetName:"app.bundle",` from `android/app/build.gradle`

```
project.ext.react = [
    enableHermes: false,
    entryFile: "index.js",
    bundleAssetName:"app.bundle",
]
```

Also, it wouldn't hurt to upgrade your build dependencies in `android/app/build.gradle` and `android/build.gradle`:
```
// android/app/build.gradle
implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.2.0-alpha01'
```

```
// android/build.gradle
classpath('com.android.tools.build:gradle:4.2.0-alpha16')
classpath('com.google.gms:google-services:4.3.4')
```

(you might need to upgrade your gradle version in `android/gradle/wrapper/gradle-wrapper.properties` to 6.7.1)

**Comment by densi97** [comment]
@SConaway 

Thanks for your suggestion, but it did not solve the problem.
After hours of investigation we identified the problem comes from this method in `MainApplication.java`:
```
    @Override
    protected @Nullable String getJSBundleFile() {
      return "app.bundle";
    }
```

Unfortunately we mistakenly changed this method when implementing Jitsi SDK.

**Comment by SConaway** [comment]
That would do it!
