### ISSUE TITLE
Production app crashes on devices with Android 11 on startup

### ISSUE THREAD

**Issue by abhishek-kushwaha-dsl** [facebook/react-native#30613]
Production app crashes on devices with Android 11 on startup with below crash logs:-

java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3779)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3943)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:85)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2276)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8414)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:596)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
Caused by: java.lang.RuntimeException: 
  at co.sam.test.app.sample.MainActivity.onCreate (MainActivity.java:49)
  at android.app.Activity.performCreate (Activity.java:8171)
  at android.app.Activity.performCreate (Activity.java:8155)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1309)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3752)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3943)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:85)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2276)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8414)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:596)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)

**Comment by abhishek-kushwaha-dsl** [comment]
React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 1.86 GB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 23, 25, 26, 28, 29
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-23 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.11.0 => 16.11.0 
      react-native: 0.62.2 => 0.62.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-schemes-manager: 2.0.0

**Comment by sagargheewala** [comment]
Hello,

I have getting same issue on production app crashes on devices with Android 11 on startup.

```
2021-01-25 03:41:50.287 10650-10650/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.suryatex.mobile, PID: 10650
    java.lang.RuntimeException: Unable to create application com.suryatex.mobile.MainApplication: java.lang.RuntimeException: java.io.IOException: cannot mkdir: /mnt/expand/a0de15c9-e80d-48f6-b175-53e915e32ded/user/0/com.suryatex.mobile/lib-main
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6736)
        at android.app.ActivityThread.access$1300(ActivityThread.java:238)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
     Caused by: java.lang.RuntimeException: java.io.IOException: cannot mkdir: /mnt/expand/a0de15c9-e80d-48f6-b175-53e915e32ded/user/0/com.suryatex.mobile/lib-main
        at com.facebook.soloader.SoLoader.init(SoLoader.java:209)
        at com.suryatex.mobile.MainApplication.onCreate(MainApplication.java:46)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1193)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6731)
        at android.app.ActivityThread.access$1300(ActivityThread.java:238) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7698) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952) 
     Caused by: java.io.IOException: cannot mkdir: /mnt/expand/a0de15c9-e80d-48f6-b175-53e915e32ded/user/0/com.suryatex.mobile/lib-main
        at com.facebook.soloader.SysUtil.mkdirOrThrow(SysUtil.java:189)
        at com.facebook.soloader.UnpackingSoSource.prepare(UnpackingSoSource.java:409)
        at com.facebook.soloader.SoLoader.initSoSources(SoLoader.java:317)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:195)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:177)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:207)
        at com.suryatex.mobile.MainApplication.onCreate(MainApplication.java:46) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1193) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6731) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:238) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7698) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952) 
 ```
 
Can you please share your solution?

**Comment by AlanSl** [comment]
@abhishek-kushwaha-dsl I see you self-closed this. Did you find and fix the cause of this crash, and if so, can you please share what you found?

**Comment by nghiant96** [comment]
> Hello,
> 
> I have getting same issue on production app crashes on devices with Android 11 on startup.
> 
> ```
> 2021-01-25 03:41:50.287 10650-10650/? E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.suryatex.mobile, PID: 10650
>     java.lang.RuntimeException: Unable to create application com.suryatex.mobile.MainApplication: java.lang.RuntimeException: java.io.IOException: cannot mkdir: /mnt/expand/a0de15c9-e80d-48f6-b175-53e915e32ded/user/0/com.suryatex.mobile/lib-main
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6736)
>         at android.app.ActivityThread.access$1300(ActivityThread.java:238)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:223)
>         at android.app.ActivityThread.main(ActivityThread.java:7698)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
>      Caused by: java.lang.RuntimeException: java.io.IOException: cannot mkdir: /mnt/expand/a0de15c9-e80d-48f6-b175-53e915e32ded/user/0/com.suryatex.mobile/lib-main
>         at com.facebook.soloader.SoLoader.init(SoLoader.java:209)
>         at com.suryatex.mobile.MainApplication.onCreate(MainApplication.java:46)
>         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1193)
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6731)
>         at android.app.ActivityThread.access$1300(ActivityThread.java:238) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914) 
>         at android.os.Handler.dispatchMessage(Handler.java:106) 
>         at android.os.Looper.loop(Looper.java:223) 
>         at android.app.ActivityThread.main(ActivityThread.java:7698) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952) 
>      Caused by: java.io.IOException: cannot mkdir: /mnt/expand/a0de15c9-e80d-48f6-b175-53e915e32ded/user/0/com.suryatex.mobile/lib-main
>         at com.facebook.soloader.SysUtil.mkdirOrThrow(SysUtil.java:189)
>         at com.facebook.soloader.UnpackingSoSource.prepare(UnpackingSoSource.java:409)
>         at com.facebook.soloader.SoLoader.initSoSources(SoLoader.java:317)
>         at com.facebook.soloader.SoLoader.init(SoLoader.java:195)
>         at com.facebook.soloader.SoLoader.init(SoLoader.java:177)
>         at com.facebook.soloader.SoLoader.init(SoLoader.java:207)
>         at com.suryatex.mobile.MainApplication.onCreate(MainApplication.java:46) 
>         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1193) 
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6731) 
>         at android.app.ActivityThread.access$1300(ActivityThread.java:238) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914) 
>         at android.os.Handler.dispatchMessage(Handler.java:106) 
>         at android.os.Looper.loop(Looper.java:223) 
>         at android.app.ActivityThread.main(ActivityThread.java:7698) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952) 
> ```
> 
> Can you please share your solution?

you can show how to fix it

**Comment by sagargheewala** [comment]
@nghiant96 Still open

**Comment by nghiant96** [comment]
I think it error on xiaomi phone.Or some phone from china

**Comment by sagargheewala** [comment]
@nghiant96 
Yes, I have an issue face in MI A3 phone.
