### ISSUE TITLE
Fatal Exception: com.facebook.react.common.JavascriptException: SyntaxError: JSON Parse error: Unexpected token: u, js engine: hermes

### ISSUE THREAD

**Issue by vgvishal538** [facebook/react-native#30772]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
```Fatal Exception: com.facebook.react.common.JavascriptException: SyntaxError: JSON Parse error: Unexpected token: u, js engine: hermes, stack:
anonymous@1:1085626
anonymous@1:1029886
value@1:78749
value@1:73356
anonymous@1:71996
value@1:72952
value@1:71954

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:214)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:919)```

## React Native version:
"react-native": "0.63.3",
"react": "16.13.1",

## Steps To Reproduce
I Upgraded react version to 0.63.3 and started getting this issue I have enabled Hermes I tried debugging but got no luck .

**Comment by AlphaJuliettOmega** [comment]
@vgvishal538 I've seen this error before when attempting to JSON.parse an object that's `undefined`.

Think about it, A JSON object starts like "{someKey:'val'...}"
If the string you want to parse is undefined, this error happens.

**Comment by shubhamdeol** [comment]
@vgvishal538 how you fixed this error?
I think this is coming where from inside react native. 
I also have same RN version.
I am not using JSON parse on undefined value.
