### ISSUE TITLE
Error crash

### ISSUE THREAD

**Issue by Zhangyinbi** [facebook/react-native#30780]
java.lang.IndexOutOfBoundsException: getChildDrawingOrder() returned invalid index 3 (child count is 3)
at android.view.ViewGroup.getAndVerifyPreorderedIndex(ViewGroup.java:2045)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4246)
at android.view.View.draw(View.java:20620)
at android.view.View.updateDisplayListIfDirty(View.java:19444)
at android.view.View.draw(View.java:20325)
at android.view.ViewGroup.drawChild(ViewGroup.java:4508)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4264)
at android.view.View.updateDisplayListIfDirty(View.java:19435)
at android.view.View.draw(View.java:20325)
at android.view.ViewGroup.drawChild(ViewGroup.java:4508)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4264)
at com.dcloud.android.widget.AbsoluteLayout.dispatchDraw(Unknown Source:57)
at android.view.View.updateDisplayListIfDirty(View.java:19435)
at android.view.View.draw(View.java:20325)
at android.view.ViewGroup.drawChild(ViewGroup.java:4508)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4264)
at com.dcloud.android.widget.AbsoluteLayout.dispatchDraw(Unknown Source:57)
at android.view.View.updateDisplayListIfDirty(View.java:19435)
at android.view.View.draw(View.java:20325)
at android.view.ViewGroup.drawChild(ViewGroup.java:4508)
at io.dcloud.common.core.ui.l.drawChild(Unknown Source:7)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4264)
at io.dcloud.common.core.ui.b$b.dispatchDraw(Unknown Source:0)
at android.view.View.draw(View.java:20620)
at android.view.View.updateDisplayListIfDirty(View.java:19444)
at android.view.View.draw(View.java:20325)
at android.view.ViewGroup.drawChild(ViewGroup.java:4508)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4264)
at android.view.View.updateDisplayListIfDirty(View.java:19435)
at android.view.View.draw(View.java:20325)
at android.view.ViewGroup.drawChild(ViewGroup.java:4508)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4264)
at android.view.View.updateDisplayListIfDirty(View.java:19435)
at android.view.View.draw(View.java:20325)
at android.view.ViewGroup.drawChild(ViewGroup.java:4508)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4264)
at android.view.View.updateDisplayListIfDirty(View.java:19435)
at android.view.View.draw(View.java:20325)
at android.view.ViewGroup.drawChild(ViewGroup.java:4508)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4264)
at android.view.View.draw(View.java:20620)
at com.android.internal.policy.DecorView.draw(DecorView.java:916)
at android.view.View.updateDisplayListIfDirty(View.java:19444)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:690)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:696)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:805)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:3984)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3759)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3055)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1815)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8237)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:995)
at android.view.Choreographer.doCallbacks(Choreographer.java:807)
at android.view.Choreographer.doFrame(Choreographer.java:739)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:226)
at android.app.ActivityThread.main(ActivityThread.java:7212)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:956)

**Comment by Zhangyinbi** [comment]
This is an exception that happened when we did cloud survey in testIn
