### ISSUE TITLE
crash error

### ISSUE THREAD

**Issue by Zhangyinbi** [facebook/react-native#30785]
Description:
java.lang.IndexOutOfBoundsException: getChildDrawingOrder() returned invalid index 3 (child count is 3)
at android.view.ViewGroup.getAndVerifyPreorderedIndex(ViewGroup.java:2045)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4246)
at android.view.View.draw(View.java:20620)
at android.view.View.updateDisplayListIfDirty(View.java:19444)
at android.view.View.draw(View.java:20325)
at android.view.ViewGroup.drawChild(ViewGroup.java:4508)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4264)
at android.view.View.updateDisplayListIfDirty(View.java:19435)
at android.view.View.draw(View.java:20325)
at android.view.ViewGroup.drawChild(ViewGroup.java:4508)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4264)
at com.dcloud.android.widget.AbsoluteLayout.dispatchDraw(Unknown Source:57)
at android.view.View.updateDisplayListIfDirty(View.java:19435)
at android.view.View.draw(View.java:20325)
at android.view.ViewGroup.drawChild(ViewGroup.java:4508)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4264)
at com.dcloud.android.widget.AbsoluteLayout.dispatchDraw(Unknown Source:57)
at android.view.View.updateDisplayListIfDirty(View.java:19435)
at android.view.View.draw(View.java:20325)
at android.view.ViewGroup.drawChild(ViewGroup.java:4508)
at io.dcloud.common.core.ui.l.drawChild(Unknown Source:7)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4264)
at io.dcloud.common.core.ui.b$b.dispatchDraw(Unknown Source:0)
at android.view.View.draw(View.java:20620)
at android.view.View.updateDisplayListIfDirty(View.java:19444)
at android.view.View.draw(View.java:20325)
at android.view.ViewGroup.drawChild(ViewGroup.java:4508)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4264)
at android.view.View.updateDisplayListIfDirty(View.java:19435)
at android.view.View.draw(View.java:20325)
at android.view.ViewGroup.drawChild(ViewGroup.java:4508)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4264)
at android.view.View.updateDisplayListIfDirty(View.java:19435)
at android.view.View.draw(View.java:20325)
at android.view.ViewGroup.drawChild(ViewGroup.java:4508)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4264)
at android.view.View.updateDisplayListIfDirty(View.java:19435)
at android.view.View.draw(View.java:20325)
at android.view.ViewGroup.drawChild(ViewGroup.java:4508)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4264)
at android.view.View.draw(View.java:20620)
at com.android.internal.policy.DecorView.draw(DecorView.java:916)
at android.view.View.updateDisplayListIfDirty(View.java:19444)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:690)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:696)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:805)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:3984)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3759)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3055)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1815)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8237)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:995)
at android.view.Choreographer.doCallbacks(Choreographer.java:807)
at android.view.Choreographer.doFrame(Choreographer.java:739)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:226)
at android.app.ActivityThread.main(ActivityThread.java:7212)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:956)
React Native version:
version : 0.50.1
Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
This is an exception that happened when we did cloud survey,we don't know the exact scene.
Expected Results
i want to know what happened and how to solve it 
Snack, code example, screenshot, or link to a repository:
nothing

**Comment by dulmandakh** [comment]
Hello, you please check if the issue persists in the latest version. I'm closing this until we have more information.

**Comment by Zhangyinbi** [comment]
At present, we have a wide range of influence and there is no way to upgrade the version. Now,i just want to know  has a similar case happened before

**Comment by dulmandakh** [comment]
Your version is way too old, RN developers support only latest version which is 0.63. You can search issue tracker for same issue, instead of filing an issue. I would recommend to upgrade RN.

**Comment by pbassut** [comment]
I'm using 0.63.1 and I can confirm this is happening. App closes out of nowhere. What info can I give to help diagnose the issue?

**Comment by jocoders** [comment]
I have the same issue on "react-native": "0.63.2"

**Comment by aardvarkk** [comment]
I ran into this problem recently. In my case it was triggered by a `<RefreshControl>` element that was just sitting in the component tree (as opposed to being the `refreshControl` prop of a `ScrollView`). After adding a `ScrollView` and passing the `RefreshControl` to it, the crash went away.
