### ISSUE TITLE
[RN 0.63.3] main.jsbundle does not exist.

### ISSUE THREAD

**Issue by SohaibKtb** [facebook/react-native#30795]
when I tried to build a bundle app using Xcode I got the error down here, with react native version  [RN 0.63.2], so I searched for a solution and I saw that it had been solved in [RN 0.63.3], and then I upgraded react native to the latest version, but the issue still persists.

 **Environment:**
```
System:
    OS: macOS 11.1
    CPU: (8) arm64 Apple M1
    Memory: 105.41 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.4.0 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 29, 30
      Build Tools: 29.0.2, 30.0.3
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

1. When I tried to archive app in Xcode I got this error:
```
error: File /Users/sohaib/Library/Developer/Xcode/DerivedData/test-bvztmcrighttuoceblsiwoeawquk/Build/Intermediates.noindex/ArchiveIntermediates/Nadeera/BuildProductsPath/Release-iphoneos/Nadeera.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
```
2. Some of the solution written in similar issues before is to create a main.jsbundle using this command:
```jsx
react-native bundle --entry-file index.ios.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios
```
then to navigate to "Build Phases" tab and add it in "Copy bundle resources" section.
the app will work but without assets, and sometimes it is crashing.

3. and also one of the solutions is:
   a. In Xcode, go to Build Phases -> Bundle React Native code and images
   b. Change this part of the script `../node_modules/react-native/scripts/react-native-xcode.sh` to `ENTRY_FILE=index.ios.js ../node_modules/react-native/scripts/react-native-xcode.sh`

it did not work with me, and I tried all the solutions posted on GitHub and Stackoverflow. 

this is my bundle react native code and images:
```jsx
export NODE_BINARY=node
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
export SENTRY_PROPERTIES=sentry.properties
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode
../node_modules/react-native/scripts/react-native-xcode.sh
```

**EDIT:**
here is some debug code:

```
+ DEST=/Users/sohaib/Library/Developer/Xcode/DerivedData/Nadeera-bvztmcrighttuoceblsiwoeawquk/Build/Intermediates.noindex/ArchiveIntermediates/Nadeera/BuildProductsPath/Release-iphoneos/Nadeera.app
+ [[ Release = *Debug* ]]
+ [[ -n '' ]]
+ case "$CONFIGURATION" in
+ DEV=false
+++ dirname /Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/react-native/scripts/react-native-xcode.sh
++ cd /Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/react-native/scripts/..
++ pwd
+ REACT_NATIVE_DIR=/Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/react-native
+ PROJECT_ROOT=/Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/react-native/../..
+ cd /Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/react-native/../..
+ '[' -z '' ']'
+ export NVM_DIR=/Users/sohaib/.nvm
+ NVM_DIR=/Users/sohaib/.nvm
+ [[ -n '' ]]
+ [[ -s index.ios.js ]]
+ ENTRY_FILE=index.js
+ [[ -s /Users/sohaib/.nvm/nvm.sh ]]
++ command -v brew
+ [[ -x '' ]]
+ [[ -x /Users/sohaib/.nodenv/bin/nodenv ]]
++ command -v brew
+ [[ -x '' ]]
+ [[ ! -x node ]]
+ [[ -d /Users/sohaib/.anyenv/bin ]]
+ source /Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/react-native/scripts/node-binary.sh
++ '[' -z /Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/@sentry/cli/sentry-cli ']'
++ type /Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/@sentry/cli/sentry-cli
+ '[' -z '' ']'
+ export NODE_ARGS=
+ NODE_ARGS=
+ '[' -z '' ']'
+ export CLI_PATH=/Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/react-native/cli.js
+ CLI_PATH=/Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/react-native/cli.js
+ '[' -z '' ']'
+ BUNDLE_COMMAND=bundle
+ [[ -z '' ]]
+ CONFIG_ARG=
+ BUNDLE_FILE=/Users/sohaib/Library/Developer/Xcode/DerivedData/Nadeera-bvztmcrighttuoceblsiwoeawquk/Build/Intermediates.noindex/ArchiveIntermediates/Nadeera/BuildProductsPath/Release-iphoneos/Nadeera.app/main.jsbundle
+ /Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/@sentry/cli/sentry-cli /Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Users/sohaib/Library/Developer/Xcode/DerivedData/Nadeera-bvztmcrighttuoceblsiwoeawquk/Build/Intermediates.noindex/ArchiveIntermediates/Nadeera/BuildProductsPath/Release-iphoneos/Nadeera.app/main.jsbundle --assets-dest /Users/sohaib/Library/Developer/Xcode/DerivedData/Nadeera-bvztmcrighttuoceblsiwoeawquk/Build/Intermediates.noindex/ArchiveIntermediates/Nadeera/BuildProductsPath/Release-iphoneos/Nadeera.app --sourcemap-output /Users/sohaib/Library/Developer/Xcode/DerivedData/Nadeera-bvztmcrighttuoceblsiwoeawquk/Build/Intermediates.noindex/ArchiveIntermediates/Nadeera/IntermediateBuildFilesPath/Nadeera.build/Release-iphoneos/Nadeera.build/DerivedSources/main.jsbundle.map
warning: the transform cache was reset.
                 Welcome to React Native!
                Learn once, write anywhere


events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:178:28)
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.checkedEmitError (/Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/sane/src/node_watcher.js:143:12)
    at FSWatcher.emit (events.js:315:20)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:184:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}
+ [[ false != true ]]
+ [[ ! -f /Users/sohaib/Library/Developer/Xcode/DerivedData/Nadeera-bvztmcrighttuoceblsiwoeawquk/Build/Intermediates.noindex/ArchiveIntermediates/Nadeera/BuildProductsPath/Release-iphoneos/Nadeera.app/main.jsbundle ]]
+ echo 'error: File /Users/sohaib/Library/Developer/Xcode/DerivedData/Nadeera-bvztmcrighttuoceblsiwoeawquk/Build/Intermediates.noindex/ArchiveIntermediates/Nadeera/BuildProductsPath/Release-iphoneos/Nadeera.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/sohaib/Library/Developer/Xcode/DerivedData/Nadeera-bvztmcrighttuoceblsiwoeawquk/Build/Intermediates.noindex/ArchiveIntermediates/Nadeera/BuildProductsPath/Release-iphoneos/Nadeera.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2
+ DEST=/Users/sohaib/Library/Developer/Xcode/DerivedData/Nadeera-bvztmcrighttuoceblsiwoeawquk/Build/Intermediates.noindex/ArchiveIntermediates/Nadeera/BuildProductsPath/Release-iphoneos/Nadeera.app
+ [[ Release = *Debug* ]]
+ [[ -n '' ]]
+ case "$CONFIGURATION" in
+ DEV=false
+++ dirname ../node_modules/react-native/scripts/react-native-xcode.sh
++ cd ../node_modules/react-native/scripts/..
++ pwd
+ REACT_NATIVE_DIR=/Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/react-native
+ PROJECT_ROOT=/Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/react-native/../..
+ cd /Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/react-native/../..
+ '[' -z '' ']'
+ export NVM_DIR=/Users/sohaib/.nvm
+ NVM_DIR=/Users/sohaib/.nvm
+ [[ -n '' ]]
+ [[ -s index.ios.js ]]
+ ENTRY_FILE=index.js
+ [[ -s /Users/sohaib/.nvm/nvm.sh ]]
++ command -v brew
+ [[ -x '' ]]
+ [[ -x /Users/sohaib/.nodenv/bin/nodenv ]]
++ command -v brew
+ [[ -x '' ]]
+ [[ ! -x node ]]
+ [[ -d /Users/sohaib/.anyenv/bin ]]
+ source /Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/react-native/scripts/node-binary.sh
++ '[' -z node ']'
++ type node
+ '[' -z '' ']'
+ export NODE_ARGS=
+ NODE_ARGS=
+ '[' -z '' ']'
+ export CLI_PATH=/Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/react-native/cli.js
+ CLI_PATH=/Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/react-native/cli.js
+ '[' -z '' ']'
+ BUNDLE_COMMAND=bundle
+ [[ -z '' ]]
+ CONFIG_ARG=
+ BUNDLE_FILE=/Users/sohaib/Library/Developer/Xcode/DerivedData/Nadeera-bvztmcrighttuoceblsiwoeawquk/Build/Intermediates.noindex/ArchiveIntermediates/Nadeera/BuildProductsPath/Release-iphoneos/Nadeera.app/main.jsbundle
+ node /Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Users/sohaib/Library/Developer/Xcode/DerivedData/Nadeera-bvztmcrighttuoceblsiwoeawquk/Build/Intermediates.noindex/ArchiveIntermediates/Nadeera/BuildProductsPath/Release-iphoneos/Nadeera.app/main.jsbundle --assets-dest /Users/sohaib/Library/Developer/Xcode/DerivedData/Nadeera-bvztmcrighttuoceblsiwoeawquk/Build/Intermediates.noindex/ArchiveIntermediates/Nadeera/BuildProductsPath/Release-iphoneos/Nadeera.app --sourcemap-output /Users/sohaib/Library/Developer/Xcode/DerivedData/Nadeera-bvztmcrighttuoceblsiwoeawquk/Build/Intermediates.noindex/ArchiveIntermediates/Nadeera/IntermediateBuildFilesPath/Nadeera.build/Release-iphoneos/Nadeera.build/DerivedSources/main.jsbundle.map
warning: the transform cache was reset.
                 Welcome to React Native!
                Learn once, write anywhere


events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:178:28)
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.checkedEmitError (/Users/sohaib/Nadeera/Nadeera-Users-App/node_modules/sane/src/node_watcher.js:143:12)
    at FSWatcher.emit (events.js:315:20)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:184:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}
+ [[ false != true ]]
+ [[ ! -f /Users/sohaib/Library/Developer/Xcode/DerivedData/Nadeera-bvztmcrighttuoceblsiwoeawquk/Build/Intermediates.noindex/ArchiveIntermediates/Nadeera/BuildProductsPath/Release-iphoneos/Nadeera.app/main.jsbundle ]]
+ echo 'error: File /Users/sohaib/Library/Developer/Xcode/DerivedData/Nadeera-bvztmcrighttuoceblsiwoeawquk/Build/Intermediates.noindex/ArchiveIntermediates/Nadeera/BuildProductsPath/Release-iphoneos/Nadeera.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/sohaib/Library/Developer/Xcode/DerivedData/Nadeera-bvztmcrighttuoceblsiwoeawquk/Build/Intermediates.noindex/ArchiveIntermediates/Nadeera/BuildProductsPath/Release-iphoneos/Nadeera.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2
```

Thank you. 🙏

**Comment by SohaibKtb** [comment]
I upgraded react native to [RN 0.63.4] and same error appears. 🙁

**Comment by SohaibKtb** [comment]
I am so sorry, I found the error, it was with node, Xcode can't find node, so what I did was searching for node path: `which node` and then export it in the `NODE_BINARY` this way:

```jsx
export NODE_BINARY=/opt/homebrew/bin/node
```

thanks🙏

**Comment by SaeedSyedAli96** [comment]
How did you debug it?
@SohaibKtb

**Comment by ithustle** [comment]
Same here... I can't build on physical device
