### ISSUE TITLE
Can't retrieve log messages

### ISSUE THREAD

**Issue by jkpubsrc** [facebook/react-native#30803]
## Description

I run `react-native log-android` on primitive Hello-World-like project and I get the following error message:

```
info Starting logkitty
(node:1091) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
error spawnSync adb ENOENT. Run CLI with --verbose flag for more details.
Error: spawnSync adb ENOENT
    at spawnLogcatProcess (/home/woodoo/DevExperiments/ReactNative/JKCalculator/node_modules/logkitty/build/android/adb.js:36:11)
    at runAndroidLoggingProcess (/home/woodoo/DevExperiments/ReactNative/JKCalculator/node_modules/logkitty/build/android/adb.js:21:10)
    at logkitty (/home/woodoo/DevExperiments/ReactNative/JKCalculator/node_modules/logkitty/build/api.js:137:85)
    at Object.logAndroid [as func] (/home/woodoo/DevExperiments/ReactNative/JKCalculator/node_modules/@react-native-community/cli-platform-android/build/commands/logAndroid/index.js:37:44)
    at Command.handleAction (/home/woodoo/DevExperiments/ReactNative/JKCalculator/node_modules/@react-native-community/cli/build/index.js:186:23)
    at Command.listener (/home/woodoo/DevExperiments/ReactNative/JKCalculator/node_modules/@react-native-community/cli/node_modules/commander/index.js:315:8)
    at Command.emit (node:events:379:20)
    at Command.parseArgs (/home/woodoo/DevExperiments/ReactNative/JKCalculator/node_modules/@react-native-community/cli/node_modules/commander/index.js:651:12)
    at Command.parse (/home/woodoo/DevExperiments/ReactNative/JKCalculator/node_modules/@react-native-community/cli/node_modules/commander/index.js:474:21)
    at setupAndRun (/home/woodoo/DevExperiments/ReactNative/JKCalculator/node_modules/@react-native-community/cli/build/index.js:267:24)
```

Versions:

```
System:
    OS: Linux 4.4 Ubuntu 16.04.7 LTS (Xenial Xerus)
    CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
    Memory: 2.93 GB / 30.39 GB
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 15.6.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.4.0 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_162 - /usr/bin/javac
    Python: 3.5.2 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
  npmGlobalPackages:
    *react-native*: Not Found
```

Expo on my smartphone is most recent as well: I installed it two days ago.

**Comment by safaiyeh** [comment]
Hi @jkpubsrc this seems to be an issue with `logkitty`, please open an issue with them. If this issue comes up on a clean blank React Native template, feel free to reopen
