### ISSUE TITLE
Void android.content.res.StringBlock.close() error when using react-native-code-push

### ISSUE THREAD

**Issue by rajeshmarotu** [facebook/react-native#30908]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Hi, I am able to create a build successfully but the app is getting crashed on opening the app with above error description when checking using logcat.

## React Native version:
react-native-cli: 2.0.1
react-native: 0.59.10
react-native-code-push:5.6.1

## Error in console

E/System: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.res.StringBlock.close()' on a null object reference
     at android.content.res.ApkAssets.close(ApkAssets.java:201)
     at android.content.res.ApkAssets.finalize(ApkAssets.java:191)
     at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
     at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
     at java.lang.Daemons$Daemon.run(Daemons.java:137)
     at java.lang.Thread.run(Thread.java:929)

**Comment by dulmandakh** [comment]
Please open an issue at code push.
