### ISSUE TITLE
com.facebook.infer.annotation.Assertions.assertNotNull (Assertions.java:28)

### ISSUE THREAD

**Issue by firstfloordigital** [facebook/react-native#30920]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
Carshing with com.facebook.infer.annotation.Assertions.assertNotNull (Assertions.java:28) 

## React Native version:
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 1600X Six-Core Processor
    Memory: 3.92 GB / 15.95 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - E:\AndroidLearning\react_native\dev\hc-mvp\node_modules\.bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 27.0.3, 28.0.3, 29.0.0, 29.0.2, 30.0.0, 30.0.0, 30.0.2
      System Images: android-24 | Google Play Intel x86 Atom, android-25 | Google APIs ARM 64 v8a, android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: ^0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Open the app
2. put the app into the background
3. open the app again from the system tray, and tada it crashes

## Expected Results
Open the app normally where the user left or restart the session

## Snack, code example, screenshot, or link to a repository:

Fatal Exception: java.lang.AssertionError
       at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:28)
       at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:510)
       at com.facebook.react.ReactDelegate.onHostPause(ReactDelegate.java:62)
       at com.facebook.react.ReactActivityDelegate.onPause(ReactActivityDelegate.java:93)
       at com.facebook.react.ReactActivity.onPause(ReactActivity.java:50)
       at android.app.Activity.performPause(Activity.java:8169)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1508)
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4494)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4455)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4407)
       at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7397)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
![image](https://user-images.githubusercontent.com/52122775/107374598-c6dc3800-6b0d-11eb-8c8a-80d6dd8701af.png)

**Comment by YouginaCh** [comment]
im facing the same issue , is there any updates  plz

**Comment by gyoung-panopto** [comment]
I'm facing the same issue as well, unable to track it down

**Comment by minhchienwikipedia** [comment]
Any update?

**Comment by firstfloordigital** [comment]
still facing the same issue, not able track down the cause

**Comment by jarredt** [comment]
Just started seeing this as well, after upgrading to 0.64.3.
