### ISSUE TITLE
java.lang.UnsatisfiedLinkError:    at com.facebook.soloader.SoLoader.doLoadLibraryBySoName

### ISSUE THREAD

**Issue by seleziomar** [facebook/react-native#30921]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When: "react-native run-android --variant=release" its work, but when I do download of Google Play Store, happens it.:

java.lang.UnsatisfiedLinkError: 
  at com.facebook.soloader.SoLoader.doLoadLibraryBySoName (SoLoader.java:825)
  at com.facebook.soloader.SoLoader.loadLibraryBySoName (SoLoader.java:673)
  at com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:611)
  at com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:559)
  at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit> (HermesExecutor.java:20)
  at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create (HermesExecutorFactory.java:29)
  at com.facebook.react.ReactInstanceManager$5.run (ReactInstanceManager.java:1017)
  at java.lang.Thread.run (Thread.java:764)

## React Native version:

System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 1.51 GB / 7.88 GB
    Binaries:
    Node: 12.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
    SDKs:
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Android TV Intel x86 Atom, android-28 | China version of Wear OS Intel x86 Atom, android-28 | 
   Wear OS Intel x86 
   Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | 
   Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
   Android NDK: Not Found
   Windows SDK:
   AllowAllTrustedApps: Enabled
   Versions: 10.0.17763.0
   IDEs:
   Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
   Visual Studio: Not Found
  Languages:
    Java: Not Found
    Python: 2.7.17
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce

1. Download de app for Google Play Store
2. Link App: https://play.google.com/store/apps/details?id=com.openpag_contadigital

**Comment by VittoriDavide** [comment]
I am having this issue too on app bundle using RN 0.64

**Comment by aleppos** [comment]
Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
	SoSource 0: com.facebook.soloader.a[root = /data/data/com.alghad/lib-main flags = 1]
	SoSource 1: com.facebook.soloader.c[root = /data/app/com.alghad-Yh0rj5OxfZhcSzZq49_JCw==/lib/arm64 flags = 0]
	SoSource 2: com.facebook.soloader.c[root = /vendor/lib64 flags = 2]
	SoSource 3: com.facebook.soloader.c[root = /system/lib64 flags = 2]
	Native lib dir: /data/app/com.alghad-Yh0rj5OxfZhcSzZq49_JCw==/lib/arm64
 result: 0
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:262)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:99)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:2)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:100)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:1)
       at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:2)
       at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:58)
       at java.lang.Thread.run(Thread.java:764)

**Comment by roots-ai** [comment]
This issue seems to be open everywhere on the web
