### ISSUE TITLE
Getting Invariant Violation: eventType argument is required with no course of action

### ISSUE THREAD

**Issue by mgenev** [facebook/react-native#31008]
## Description
We are getting a lot of this invariant error message on Android (log below)

`com.facebook.react.common.JavascriptException: Invariant Violation: eventType argument is required.`

We don't know where it's coming from. We can't tell from the log what part of our code is causing it. Searching google produces nothing for it...

## React Native version:
Run `react-native info` in your terminal and copy the results here.

`React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
      Memory: 301.43 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 23, 28, 29
        Build Tools: 23.0.1, 28.0.3, 29.0.1, 29.0.2
        System Images: android-26 | Google Play Intel x86 Atom, android-28 | Android TV Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.12.0 => 16.13.1
      react-native: 0.59.8 => 0.59.8
    npmGlobalPackages:
      react-native-cli: 2.0.1`

## Steps To Reproduce

We don't know how.

## Expected Results
Actionable way to fix the reason for the warning

## Snack, code example, screenshot, or link to a repository:
`[Events]
com.facebook.react.common.JavascriptException: Invariant Violation: eventType argument is required.

This error is located at:
    in S
    in P
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in s
    in RCTView
    in Unknown
    in y
    in Root
    in RCTView
    in b, stack:
value@129:866
<unknown>@731:1240
Ei@91:61027
Ri@91:63391
qi@91:66801
ea@91:69555
<unknown>@91:81296
unstable_runWithPriority@166:3915
ja@91:81253
Oa@91:81007
Wa@91:80310
Aa@91:79323
sa@91:78013
Ba@91:82505
unmountComponentAtNode@91:85275
unmountComponentAtNodeAndRemoveContainer@91:85393
unmountApplicationComponentAtRootTag@335:2686
value@30:3311
<unknown>@30:822
value@30:2565
value@30:794
value@-1

	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:135)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:247)
	at java.lang.Thread.run(Thread.java:818)`

**Comment by mrarronz** [comment]
I have encountered same issue, I'm using react-native 0.61.5, here is the crash log from Firebase console:
```
Fatal Exception: com.facebook.react.common.JavascriptException: Invariant Violation: eventType argument is required.

This error is located at:
    in n
    in h
    in RCTView
    in RCTView
    in S
    in RCTView
    in h, stack:
value@129:463
value@394:1714
Ri@91:57222
Ui@91:57947
Di@91:60412
Fl@91:76347
<unknown>@179:3915
Dl@91:74615
Pl@91:65839
<unknown>@91:25495
<unknown>@179:3915
sn@91:25442
cn@91:25377
kl@91:64831
la@91:87813
unmountComponentAtNode@91:90791
unmountComponentAtNodeAndRemoveContainer@91:90909
unmountApplicationComponentAtRootTag@345:2367
value@25:3685
<unknown>@25:841
value@25:2939
value@25:813

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:914)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
       at android.os.Looper.loop(Looper.java:225)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by mrarronz** [comment]
My reproduce steps are:

1. Open app
2. Click Android back button or use back gesture to exit app
3. Open app again, observe that the app crashes

It is weird that when I kill the app from multi-task screen of the phone and reopen the app, it runs normally without crash. But when click Android back button exit the app, it always crashes for the first time, after that reopen the app, it won't crash. Looks like the crash only happens if the app is not totally killed from the Android system.

**Comment by mrarronz** [comment]
This issue is resolved in my project, this would happen when you remove some instances or event listener in the `componentWillUnmount`, but forget to add the event type. For example:
```
componentWillUnmount(){
    XXX.removeListener(EventTypeName);
  }
```
if `EventTypeName` is missing, then this crash will occur, it's easy to reproduce on Android when clicking the virtual back button on Android OS, which will trigger the `componentWillUnmount` function.

**Comment by mgenev** [comment]
> This issue is resolved in my project, this would happen when you remove some instances or event listener in the `componentWillUnmount`, but forget to add the event type. For example:
> 
> ```
> componentWillUnmount(){
>     XXX.removeListener(EventTypeName);
>   }
> ```
> 
> if `EventTypeName` is missing, then this crash will occur, it's easy to reproduce on Android when clicking the virtual back button on Android OS, which will trigger the `componentWillUnmount` function.

Thank you, that's good information. We'll try that out
