### ISSUE TITLE
Fatal Exception: Failed to load WebView provider: No WebView installed

### ISSUE THREAD

**Issue by RodolfoGS** [facebook/react-native#31253]
## Description
Crash on Android when `Android System WebView` is disabled.

Here is a PR that fix the issue: https://github.com/facebook/react-native/pull/29089

```
Fatal Exception: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:435)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:252)
       at android.webkit.CookieManager.getInstance(CookieManager.java:47)
       at com.facebook.react.modules.network.ForwardingCookieHandler.getCookieManager(ForwardingCookieHandler.java:180)
       at com.facebook.react.modules.network.ForwardingCookieHandler.get(ForwardingCookieHandler.java:58)
       at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.java:61)
       at com.facebook.react.modules.network.ReactCookieJarContainer.loadForRequest(ReactCookieJarContainer.java:44)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:84)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

## React Native version:
```
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 382.56 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.6.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ~0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. Go to Settings in your phone (Android)
2. Application manager (or apps)
3. Downloaded / all apps
4. Search for `Android System WebView` and just disable it.
5. Open your `react-native` app
6. Your app will crash

## Expected Results
No crash

## Snack, code example, screenshot, or link to a repository:

Here is a PR that fix the issue: https://github.com/facebook/react-native/pull/29089

**Comment by kyunkakata** [comment]
We need this pull request. Hope that it will be merged soon.

**Comment by RodolfoGS** [comment]
Anyone know someone from the react-native team to merge this PR (https://github.com/facebook/react-native/pull/29089)? It's a super simple PR (https://github.com/facebook/react-native/pull/29089) that fix an easy reproducible crash and are opened for about 1 year ago ¯\_(ツ)_/¯

**Comment by capezzbr** [comment]
Experiencing the same issue, the message in my case is `Fatal Exception: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed`

**Comment by punksta** [comment]
got this when testing my app on android 11 beta.

```
android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
    at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:366)
    at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:431)
    at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:286)
    at android.webkit.CookieManager.getInstance(CookieManager.java:50)
    at com.facebook.react.modules.network.c.i(ForwardingCookieHandler.java:3)
    at com.facebook.react.modules.network.c.get(ForwardingCookieHandler.java:1)
    at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.java:2)
    at com.facebook.react.modules.network.l.loadForRequest(ReactCookieJarContainer.java:2)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:17)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:9)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:13)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:2)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:3)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)

android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
    at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:470)
    at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:286)
    at android.webkit.CookieManager.getInstance(CookieManager.java:50)
    at com.facebook.react.modules.network.c.i(ForwardingCookieHandler.java:3)
    at com.facebook.react.modules.network.c.get(ForwardingCookieHandler.java:1)
    at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.java:2)
    at com.facebook.react.modules.network.l.loadForRequest(ReactCookieJarContainer.java:2)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:17)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:9)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:13)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:2)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:3)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)

android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
    at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:301)
    at android.webkit.CookieManager.getInstance(CookieManager.java:50)
    at com.facebook.react.modules.network.c.i(ForwardingCookieHandler.java:3)
    at com.facebook.react.modules.network.c.get(ForwardingCookieHandler.java:1)
    at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.java:2)
    at com.facebook.react.modules.network.l.loadForRequest(ReactCookieJarContainer.java:2)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:17)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:9)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:13)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:2)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:3)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)
```

**Comment by TaeHyungK** [comment]
Same here..!
Is there a version with this issue fixed?

**Comment by exploIF** [comment]
Same here on 0.63.3

**Comment by williamgurzoni** [comment]
Was it fixed? I'm on RN 0.67.1 and experiencing it 😮‍💨

**Comment by exploIF** [comment]
@williamgurzoni make sure you really have WebView installed. I used some device without is and got this error. If not it's possible to install it manually, in most cases.

**Comment by williamgurzoni** [comment]
@exploIF Thank you for answering, but it's happening with user's phone, so I can't really enforce it. And actually in my personal phone (Asus), it was disabled by default and no issues. I'm wondering whether it's just for samsung phones.

**Comment by alejodiloreto** [comment]
Any solution here? I'm facing this issue in v0.71.18

**Comment by ravindra-marwadi-globant** [comment]
I m facing this on React Native 0.75
