### ISSUE TITLE
Android app bundle crashes of soloader

### ISSUE THREAD

**Issue by Desintegrator** [facebook/react-native#31350]
All of ours Android apps provided with app bundle (.aab) experiencing with much amount of soloader crashes.
Different devices, different OS versions. Can not reproduce it on our testing devices
Switching to separate apps is not an options since starting from August 2021 app bundle is required.

react versions:
`
"react": "17.0.1",
"react-native": "0.64.0",
`

Environment Info:
```
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 923.96 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio
    Xcode: 12.3/12C33
  Languages:
    Java: 11.0.9.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Stacktrace 1:
```
java.io.IOException at (Unknown Source)
com.facebook.soloader.g.<init> (or com.facebook.soloader.FileLocker.<init>)
java.lang.RuntimeException: Unable to create application chat.roulette.MainApplication: java.lang.RuntimeException: java.io.IOException: Resource deadlock would occur
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6853)
	at android.app.ActivityThread.access$1400(ActivityThread.java:246)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7876)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.RuntimeException: java.io.IOException: Resource deadlock would occur
	at com.facebook.soloader.SoLoader.g(Unknown Source)
	at chat.roulette.MainApplication.onCreate(Unknown Source)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1193)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6848)
	... 8 more
Caused by: java.io.IOException: Resource deadlock would occur
	at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:115)
	at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1139)
	at java.nio.channels.FileChannel.lock(FileChannel.java:1053)
	at com.facebook.soloader.g.<init>(Unknown Source)
	at com.facebook.soloader.g.c(Unknown Source)
	at com.facebook.soloader.n.b(Unknown Source)
	at com.facebook.soloader.SoLoader.i(Unknown Source)
	at com.facebook.soloader.SoLoader.f(Unknown Source)
	at com.facebook.soloader.SoLoader.e(Unknown Source)
	at com.facebook.soloader.SoLoader.g(Unknown Source)
	... 11 more
```

Stacktrace 2: (little bit different)
```
java.lang.RuntimeException: Unable to create application chat.roulette.MainApplication: java.lang.RuntimeException: java.io.IOException: Resource deadlock would occur
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5506)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6251)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1073)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
Caused by: java.lang.RuntimeException: java.io.IOException: Resource deadlock would occur
	at com.facebook.soloader.SoLoader.g(Unknown Source)
	at chat.roulette.MainApplication.onCreate(Unknown Source)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5503)
	... 8 more
Caused by: java.io.IOException: Resource deadlock would occur
	at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:99)
	at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1026)
	at java.nio.channels.FileChannel.lock(FileChannel.java:875)
	at com.facebook.soloader.g.<init>(Unknown Source)
	at com.facebook.soloader.g.c(Unknown Source)
	at com.facebook.soloader.n.b(Unknown Source)
	at com.facebook.soloader.SoLoader.i(Unknown Source)
	at com.facebook.soloader.SoLoader.f(Unknown Source)
	at com.facebook.soloader.SoLoader.e(Unknown Source)
	... 12 more
```

**Comment by Desintegrator** [comment]
> ⚠️	Missing Environment Information
> ℹ️	Your issue may be missing information about your development environment. You can obtain the missing information by running `react-native info` in a console.

fixed

**Comment by cortinico** [comment]
Hey,
We're cleaning up the React Native issue tracker to make sure we focus on the most important issues first.

I'm closing this one because it's stale and related to a version of React Native we no longer support. If the issue persists on the latest version, please re-open a new issue and reference this one.

Moreover, we generally can't fix issues just by looking at a stacktrace reported from your crash reporting platform. Please provide a reproducer in your future reports.

Thank you.
