### ISSUE TITLE
[Android] Debugger problems - Catalyst Instance has already disappeared: requested by WebSocketModule 

### ISSUE THREAD

**Issue by oviedo97fer** [facebook/react-native#31397]
Hello everyone. I know this is possibly a duplicate of [#28992](https://github.com/facebook/react-native/issues/28992), but that thread is inactive and here I can offer more information.

## Description
First, the application compiles fine, but the error starts when the metro package starts.
Application gets stuck on splash screen and there are no logs, errors and nothing. Only loop on metro-bundler 

![image](https://user-images.githubusercontent.com/37948156/115587717-5d626d80-a2a4-11eb-81c5-881c22dcf95b.png)

When I run 'npx react-native log-android' I get the following:
```
[12:23:24] D | ReactNative ▶︎ ReactInstanceManager.onReloadWithJSDebugger()
                           │ ReactInstanceManager.recreateReactContextInBackground()
                           │ ReactInstanceManager.runCreateReactContextOnNewThread()
                           └ ReactInstanceManager.tearDownReactContext()

[12:23:24] D | ReactNative ▶︎ CatalystInstanceImpl.destroy() start
                           └ CatalystInstanceImpl.destroyV1() start

[12:23:24] I | ReactNativeJS ▶︎ Running "xxx" with {"rootTag":41}

[12:23:24] D | ReactNative ▶︎ ReactInstanceManager.createReactContext()

[12:23:24] D | ReactNative ▶︎ Initializing React Xplat Bridge.

[12:23:24] D | ReactNative ▶︎ Initializing React Xplat Bridge before initializeBridge

[12:23:24] D | ReactNative ▶︎ Initializing React Xplat Bridge after initializeBridge
                           │ CatalystInstanceImpl.runJSBundle()
                           │ ReactInstanceManager.setupReactContext()
                           └ CatalystInstanceImpl.initialize()

[12:23:24] D | ReactNative ▶︎ ReactInstanceManager.attachRootViewToInstance()

[12:23:25] I | ReactNative ▶︎ [GESTURE HANDLER] Initialize gesture handler for root v
iew com.facebook.react.ReactRootView{2f067f V.E...... ......ID 0,0-1080,1962 #51}    

[12:23:25] D | ReactNative ▶︎ ReactInstanceManager.createReactContextInBackground()
                           └ ReactInstanceManager.attachRootViewToInstance()

[12:23:25] D | ReactNative ▶︎ CatalystInstanceImpl.destroy() end

[12:24:26] D | ReactNative ▶︎ ReactInstanceManager.onReloadWithJSDebugger()
                           │ ReactInstanceManager.recreateReactContextInBackground() 
                           │ ReactInstanceManager.runCreateReactContextOnNewThread() 
                           └ ReactInstanceManager.tearDownReactContext()

[12:24:26] D | ReactNative ▶︎ CatalystInstanceImpl.destroy() start
                           └ CatalystInstanceImpl.destroyV1() start

[12:24:26] D | ReactNative ▶︎ ReactInstanceManager.createReactContext()

[12:24:26] D | ReactNative ▶︎ Initializing React Xplat Bridge.

[12:24:26] D | ReactNative ▶︎ Initializing React Xplat Bridge before initializeBridge

[12:24:26] D | ReactNative ▶︎ Initializing React Xplat Bridge after initializeBridge 
                           │ CatalystInstanceImpl.runJSBundle()
                           │ ReactInstanceManager.setupReactContext()
                           └ CatalystInstanceImpl.initialize()

[12:24:26] D | ReactNative ▶︎ ReactInstanceManager.attachRootViewToInstance()        

[12:24:26] D | ReactNative ▶︎ ReactInstanceManager.attachRootViewToInstance()        

[12:24:26] D | ReactNative ▶︎ ReactInstanceManager.detachViewFromInstance()

[12:24:27] D | ReactNative ▶︎ ReactInstanceManager.createReactContextInBackground()  
                           └ ReactInstanceManager.attachRootViewToInstance()

[12:24:31] D | ReactNative ▶︎ ReactInstanceManager.onReloadWithJSDebugger()

[12:24:31] D | ReactNative ▶︎ ReactInstanceManager.recreateReactContextInBackground()
                           │ ReactInstanceManager.runCreateReactContextOnNewThread() 
                           └ ReactInstanceManager.tearDownReactContext()

[12:24:31] D | ReactNative ▶︎ CatalystInstanceImpl.destroy() start
                           └ CatalystInstanceImpl.destroyV1() start

[12:24:31] D | ReactNative ▶︎ ReactInstanceManager.createReactContext()

[12:24:31] D | ReactNative ▶︎ Initializing React Xplat Bridge.

[12:24:31] D | ReactNative ▶︎ Initializing React Xplat Bridge before initializeBridge

[12:24:31] D | ReactNative ▶︎ Initializing React Xplat Bridge after initializeBridge 
                           └ CatalystInstanceImpl.runJSBundle()

[12:24:31] D | ReactNative ▶︎ ReactInstanceManager.attachRootViewToInstance()        

[12:24:32] D | ReactNative ▶︎ ReactInstanceManager.createReactContextInBackground()  
                           └ ReactInstanceManager.attachRootViewToInstance()
```

** consider these logs repeat on every loop

Then, when I see logcat I get the following error: 

```
2021-04-21 10:29:28.625 2665-2769/com.xxx.app.development E/unknown:ReactContextBaseJavaModule: Unhandled SoftException
    java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
        at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:67)
        at com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:62)
        at com.facebook.react.modules.websocket.WebSocketModule.access$100(WebSocketModule.java:40)
        at com.facebook.react.modules.websocket.WebSocketModule$1.onOpen(WebSocketModule.java:153)
        at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:208)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2021-04-21 10:29:29.030 2665-2766/com.xxx.app.development E/unknown:ReactContextBaseJavaModule: Unhandled SoftException
    java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
        at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:67)
        at com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:62)
        at com.facebook.react.modules.websocket.WebSocketModule.notifyWebSocketFailed(WebSocketModule.java:337)
        at com.facebook.react.modules.websocket.WebSocketModule.access$200(WebSocketModule.java:40)
        at com.facebook.react.modules.websocket.WebSocketModule$1.onFailure(WebSocketModule.java:172)
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570)
        at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:211)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

OBSERVATION: 
When I'm on the splash screen (stuck) and I tap the Overview button, the app zooms out, I tap the app again, I tap Overview btn again and tap the app again (the app never closed) the app opens "correctly" but it shows some rn warning logs (like 'deprecated componentWillMount warn', nothing relevant with this error) but those logs aren't working properly and I can't click it or on 'Dismiss all' btn. If I press 'R' on metro-bundler console the app stucked again on splash screen. 

## React Native version:
```
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Memory: 2.81 GB / 11.90 GB
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203
  Languages:
    Java: 11.0.2
    Python: 2.7.17
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found 
```

## Expected Results
Run ok!

**Comment by oviedo97fer** [comment]
### Our solution:
delete/handle with correct dependency this code line: 
```
if (__DEV__) {
  NativeModules.DevSettings.setIsDebuggingRemotely(true)
}
```

**Comment by tkserver** [comment]
THANK YOU THANK YOU!  I was stuck in an infinite loop when launching on android.  Commenting out this code in my App.js fixed the problem:

`if (__DEV__) {
  NativeModules.DevSettings.setIsDebuggingRemotely(true)
}`

**Comment by SanjanaTailor** [comment]
@tkserver  : where is this line written In my case not able to see this line and app is getting crashed.

**Comment by tkserver** [comment]
@SanjanaTailor in App.js for me. If you don't have this line, you may not have the same problem.

**Comment by juanda2222** [comment]
Not really true, I am having this issue without any `if (__DEV__) { NativeModules.DevSettings.setIsDebuggingRemotely(true) }` line on App.js

**Comment by mwegener-com** [comment]
same problem. How did you solve it @juanda2222 ?

**Comment by sayurimizuguchi** [comment]
I am experiencing the same issue

**Comment by Pavel-Ananich** [comment]
I have the same issue after updating from android sdk version 29 to 30

**Comment by AjayShivanagol** [comment]
same here I have the same issue after updating from android sdk version 29 to 30
