### ISSUE TITLE
Android app crash com.facebook.react.ReactRootView.setAllowImmediateUIOperationExecution 

### ISSUE THREAD

**Issue by itskris84** [facebook/react-native#31393]
getting few crashes in crashlytics with below crash logs. it seems like it is happening on screen orienetaion. but i can see that the screen orientation is locked  in "portrait" mode. So what could be the reason for this issue ? 

## Description
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.UIManager.setAllowImmediateUIOperationExecution(boolean)' on a null object reference
       at com.facebook.react.ReactRootView.setAllowImmediateUIOperationExecution(ReactRootView.java:480)
       at com.facebook.react.ReactRootView.onMeasure(ReactRootView.java:130)
       at android.view.View.measure(View.java:23287)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6823)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
       at android.view.View.measure(View.java:23287)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6823)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
       at android.view.View.measure(View.java:23287)

## React Native version:
RN version : 0.62.2

## Steps To Reproduce
We can see this is mainly happening in samsung & LGE devices with android os 11 & 10 devices. 84 % issues are happening in android 11 os.

**Comment by ColdBlooded-Fan** [comment]
I have encountered the same problem. Is there anyone who can solve it 
RN version : 0.62.2
