### ISSUE TITLE
Failed to construct transformer:  Error: Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by sachin3072004** [facebook/react-native#31430]
## Description
When I use 'react-native run-android --variant=release' command to build project I get the following error.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings
117 actionable tasks: 2 executed, 115 up-to-date
Failed to construct transformer:  Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (buffer.js:608:37)
    at Buffer.toString (buffer.js:805:14)
    at Object.readFileSync (fs.js:421:41)
    at getContent (/Users/sachin/Desktop/mobile-app/album/node_modules/jest-haste-map/build/worker.js:149:41)
    at Object.<anonymous> (/Users/sachin/Desktop/mobile-app/album/node_modules/jest-haste-map/build/worker.js:178:25)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/sachin/Desktop/mobile-app/album/node_modules/jest-haste-map/build/worker.js:78:24)
    at _next (/Users/sachin/Desktop/mobile-app/album/node_modules/jest-haste-map/build/worker.js:98:9)
    at /Users/sachin/Desktop/mobile-app/album/node_modules/jest-haste-map/build/worker.js:103:7
    at new Promise (<anonymous>) {
  type: 'Error',
  code: 'ERR_STRING_TOO_LONG'
}
Error: @build-script-error-begin
Error loading assets JSON from Metro. Ensure you've followed all expo-updates installation steps correctly. Cannot create a string longer than 0x1fffffe8 characters
@build-script-error-end

    at /Users/sachin/Desktop/mobile-app/album/node_modules/expo-updates/scripts/createManifest.js:39:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

But if I use 'react-native --variant=debug' then I do not see any build issue.

## React Native version:
sachins-MacBook-Pro:album sachin$ react-native info
info Fetching system and libraries information...
(node:4602) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 438.84 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.10.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-30 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
It is happening on my local machine all the times. I am not sure how to reproduce it on snack. I can provide the needed info.

## Expected Results
release build should be built.

**Comment by sachin3072004** [comment]
After checking the size of the whole directory I found an unrelated file of size 600 MB. By mistake I copied that file to the react-native project. After deletion build started to work fine.
