### ISSUE TITLE
0.61.5 android app rejected because of stability issues(StrictMode policy violation)

### ISSUE THREAD

**Issue by sbatikeri** [facebook/react-native#31477]
Our android app rejected because of these two StrictMode policy violation

API (fully restricted)
	•	 error Error Issue 1 of 11Called once during testing
API
Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V
Stack trace #1
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V

Show less
expand_less
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V
	at android.os.StrictMode.lambda$static$1(StrictMode.java:416)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
	at java.lang.Class.getMethod(Class.java:2066)
	at java.lang.Class.getMethod(Class.java:1693)
	at okhttp3.internal.platform.OptionalMethod.getPublicMethod(OptionalMethod.java:1)
	at okhttp3.internal.platform.OptionalMethod.getMethod(OptionalMethod.java:2)
	at okhttp3.internal.platform.OptionalMethod.invokeOptional(OptionalMethod.java:1)
	at okhttp3.internal.platform.OptionalMethod.invokeOptionalWithoutCheckedException(OptionalMethod.java:1)
	at okhttp3.internal.platform.AndroidPlatform.configureTlsExtensions(AndroidPlatform.java:2)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:10)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:9)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:15)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:36)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:1)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:6)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:5)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:22)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:22)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:9)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:13)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:2)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:3)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

content_copy
API (fully restricted)
	•	 error Error Issue 2 of 11Called once during testing
API
Lcom/android/org/conscrypt/ConscryptEngineSocket;->setUseSessionTickets(Z)V
Stack trace #1
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lcom/android/org/conscrypt/ConscryptEngineSocket;->setUseSessionTickets(Z)V

Show less
expand_less
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lcom/android/org/conscrypt/ConscryptEngineSocket;->setUseSessionTickets(Z)V
	at android.os.StrictMode.lambda$static$1(StrictMode.java:416)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
	at java.lang.Class.getMethod(Class.java:2066)
	at java.lang.Class.getMethod(Class.java:1693)
	at okhttp3.internal.platform.OptionalMethod.getPublicMethod(OptionalMethod.java:1)
	at okhttp3.internal.platform.OptionalMethod.getMethod(OptionalMethod.java:2)
	at okhttp3.internal.platform.OptionalMethod.invokeOptional(OptionalMethod.java:1)
	at okhttp3.internal.platform.OptionalMethod.invokeOptionalWithoutCheckedException(OptionalMethod.java:1)
	at okhttp3.internal.platform.AndroidPlatform.configureTlsExtensions(AndroidPlatform.java:1)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:10)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:9)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:15)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:36)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:1)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:6)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:5)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:22)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:22)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:9)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:13)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:2)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:3)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

content_copy

## React Native version:
0.61.5
 
##package.json
{
    "name": "myapp",
    "version": "0.0.1",
    "private": true,
    "scripts": {
        "ios": "react-native run-ios",
        "start": "react-native start",
        "android-clean": "echo 'CLEANING ...' && cd android/ && ./gradlew clean && cd ..",
        "android-build-all": "build_scripts/start_build_android.sh",
        "android-bundle": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res",
        "android": "react-native run-android --variant=devDebug",
        "android-prod": "react-native run-android --variant=prodRelease",
        "android-qa": "react-native run-android --variant=qaRelease",
        "android-qa-debug": "react-native run-android --variant=qaDebug",
        "android-uat": "react-native run-android --variant=uatRelease",
       
        "test": "jest",
        "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
        "postinstall": "npx patch-package"
    },
    "dependencies": {
        "@b9/react-native-autocomplete-search": "^1.2.0",
        "@react-native-community/async-storage": "^1.8.1",
        "@react-native-community/masked-view": "^0.1.6",
        "@react-native-community/netinfo": "^5.9.9",
        "@react-native-community/push-notification-ios": "^1.7.3",
        "@react-native-community/toolbar-android": "0.1.0-rc.2",
        "@react-native-firebase/analytics": "11.2.0",
        "@react-native-firebase/app": "11.2.0",
        "@react-native-firebase/crashlytics": "11.2.0",
        "@react-native-firebase/firestore": "11.2.0",
        "@react-native-firebase/messaging": "11.2.0",
        "@react-native-firebase/perf": "11.2.0",
        "@react-navigation/bottom-tabs": "^5.0.7",
        "@react-navigation/drawer": "^5.0.7",
        "@react-navigation/native": "^5.0.7",
        "@react-navigation/stack": "^5.0.8",
        "add": "^2.0.6",
        "aws-sdk": "^2.897.0",
        "axios": "^0.21.1",
        "axios-retry": "^3.1.9",
        "enzyme": "^3.11.0",
        "enzyme-adapter-react-16": "^1.15.2",
        "geolib": "^3.2.1",
        "google-libphonenumber": "^3.2.10",
        "haversine": "^1.1.1",
        "immutable": "^4.0.0-rc.12",
        "install": "^0.13.0",
        "jwt-decode": "^3.1.2",
        "moment": "^2.29.1",
        "moment-duration-format": "^2.3.2",
        "moment-timezone": "^0.5.32",
        "patch-package": "^6.2.2",
        "react": "16.13.1",
        "react-devtools": "^4.4.0",
        "react-dom": "^16.13.1",
        "react-jwt-store": "^1.7.0",
        "react-native": "^0.61.5",
        "react-native-app-auth": "^6.2.0",
        "react-native-autocomplete-input": "^4.2.0",
        "react-native-config": "^0.12.0",
        "react-native-device-info": "^7.2.1",
        "react-native-elements": "^1.2.7",
        "react-native-fix-image": "^2.1.0",
        "react-native-geocoder-reborn": "^0.9.0",
        "react-native-geolocation-service": "^4.0.0",
        "react-native-gesture-handler": "^1.6.1",
        "react-native-inappbrowser-reborn": "^3.4.0",
        "react-native-keyboard-aware-scroll-view": "^0.9.1",
        "react-native-maps": "0.27.1",
        "react-native-orientation-loading-overlay": "^0.1.6",
        "react-native-picker-select": "^6.6.0",
        "react-native-push-notification": "^6.1.3",
        "react-native-ratings": "^6.5.0",
        "react-native-reanimated": "^1.7.0",
        "react-native-safe-area-context": "^0.7.3",
        "react-native-screens": "^2.2.0",
        "react-native-scrolling-menu": "^0.1.1",
        "react-native-secure-key-store": "^2.0.9",
        "react-native-sendgrid": "^1.0.1",
        "react-native-sha256": "^1.3.6",
        "react-native-splash-screen": "^3.2.0",
        "react-native-text-input-mask": "^2.0.0",
        "react-native-timer": "^1.3.6",
        "react-native-tiny-toast": "^1.0.7",
        "react-native-vector-icons": "^6.7.0",
        "react-navigation": "^4.2.1",
        "react-navigation-stack": "^1.10.3",
        "react-redux": "^7.2.0",
        "react-swipeable-views-native": "^0.13.2",
        "react-use": "^13.27.1",
        "redux": "^4.0.5",
        "redux-devtools-extension": "^2.13.8",
        "redux-persist": "^6.0.0",
        "redux-persist-transform-immutable": "^5.0.0",
        "redux-saga": "^1.1.3",
        "redux-saga-jwt": "^1.0.4-beta.0",
        "redux-thunk": "^2.3.0",
        "toggle-switch-react-native": "^2.1.0"
    },
    "devDependencies": {
        "@babel/core": "^7.9.0",
        "@babel/preset-env": "^7.9.0",
        "@babel/runtime": "^7.8.4",
        "@react-native-community/eslint-config": "^0.0.5",
        "@types/jest": "^24.0.24",
        "@types/node": "^14.11.10",
        "@types/react-native": "^0.60.25",
        "@types/react-test-renderer": "16.9.1",
        "@typescript-eslint/eslint-plugin": "^2.12.0",
        "@typescript-eslint/parser": "^2.12.0",
        "babel-core": "^6.26.3",
        "babel-jest": "^25.1.0",
        "babel-preset-env": "^1.7.0",
        "eslint": "^5.16.0",
        "jest": "^25.1.0",
        "metro-react-native-babel-preset": "^0.56.0",
        "react-native-obfuscating-transformer": "^1.0.0",
        "react-test-renderer": "16.9.0",
        "remote-redux-devtools": "^0.5.16",
        "typescript": "^3.7.3"
    },
    "jest": {
        "preset": "react-native",
        "moduleFileExtensions": [
            "ts",
            "tsx",
            "js",
            "jsx",
            "json",
            "node"
        ]
    }
}

**Comment by sclavijo93** [comment]
I have the same issue with play store with RN 0.63.1

**Comment by sandy0096** [comment]
https://stackoverflow.com/q/67409917/7939330
