### ISSUE TITLE
Catalyst Instance has already disappeared crashes android build on first start in production

### ISSUE THREAD

**Issue by TheRogue76** [facebook/react-native#31521]
## Description
Hi. I'm using reanimated 2 on Android and iOS and it uses the new JSI and Turbo modules under the hood. In production, the first launch of the app results in a crash with the following error:
```
Unhandled SoftException
java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by Timing
	at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(Unknown Source:40)
	at com.facebook.react.modules.core.TimingModule.access$000(Unknown Source:0)
	at com.facebook.react.modules.core.TimingModule$a.callTimers(Unknown Source:2)
	at com.facebook.react.modules.core.d.q(Unknown Source:55)
	at com.facebook.react.modules.core.TimingModule.createTimer(Unknown Source:6)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:147)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
	at android.os.Looper.loop(Looper.java:214)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
	at java.lang.Thread.run(Thread.java:919)

JNI ERROR (app bug): accessed stale Global 0x65636166  (index 106313238 in a table of size 771)

java_vm_ext.cc:570] JNI DETECTED ERROR IN APPLICATION: use of deleted global reference 0x65636166

java_vm_ext.cc:570]     from void com.swmansion.reanimated.NativeProxy$EventHandler.receiveEvent(java.lang.String, com.facebook.react.bridge.WritableMap)
```
and in iOS it will flat out not work on its first launch. Everything becomes OK the second time around but that first launch is terrible. I have already posted it on their side, but it has been weeks and no answers. So i have come here asking for your help.

## React Native version:
```
System:
    OS: macOS 11.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 914.43 MB / 16.00 GB
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 22.0.7026061
  IDEs:
    Android Studio: 4.1.3 4.1.3
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1) install reanimated as per the documentation. (adding with yarn, add babel plugin, enable hermes, Add in MainApplication.Java and add proguard)
2) create a small collapsible Header with animation using ScrollView
3) cd android && ./gradlew assembleRelease
4) install on simulator or physical device
5) crash on first launch and get the following Errors:

## Expected Results

For the app to open correctly on first Launch. Or at least to get an ETA on when JSI and Turbo modules will be implemented correctly so as to avoid it till that point.

## Snack, code example, screenshot, or link to a repository:
```

const scrollY = useSharedValue<number>(0)

const headerHeight = useDerivedValue<number>(() => {
    return value based on header
  });

const heightStyle = useAnimatedStyle(() => {
    return {height: headerHeight.value};
});


const scrollHandler = useAnimatedScrollHandler(event => {
    gets scrollview position
});
.
.
.

<Animated.View
  style={[...,heightStyle]}>
  <Text>{title}</Text>
</Animated.View>
 <Animated.ScrollView onScroll={scrollHandler}>
{sth}
</Animated.ScrollView>
```

**Comment by carloscurcino** [comment]
How did you seved this?? I'm having the same error, but i'm not doing any animation. But react-native-animated comes installed on expo template

**Comment by TheRogue76** [comment]
In the trace that you get, it mentions what function exactly triggered it. For mine, you can see it was com.swmansion.reanimated.NativeProxy. Find what yours is pointing to, if it is even Software mansion, and then raise the proper issue with that repo and mention the function that triggered it.
