### ISSUE TITLE
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes-executor-release.so caused by: dlopen failed: library "libjsinspector.so" not found result: 0

### ISSUE THREAD

**Issue by liyanfang** [facebook/react-native#31565]
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes-executor-release.so caused by: dlopen failed: library "libjsinspector.so" not found result: 0

	at com.facebook.soloader.SoLoader.c(SoLoader.java:46)

	at com.facebook.soloader.SoLoader.o(SoLoader.java:16)

	at com.facebook.soloader.SoLoader.n(SoLoader.java:1)

	at com.facebook.soloader.SoLoader.l(SoLoader.java:18)

	at com.facebook.soloader.SoLoader.k(SoLoader.java:1)
	at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:4)
	at com.facebook.hermes.reactexecutor.a.create(HermesExecutorFactory.java:1)
	at com.facebook.react.ReactInstanceManager$d.run(ReactInstanceManager.java:10)
	at java.lang.Thread.run(Thread.java:784)
	
	
	rn version：com.facebook.react:react-native:0.63.4
	The project has "Hermes" enabled.

**Comment by liyanfang** [comment]
Mobile phone models：
华为荣耀：LLD-AL20，系统：8.0.0
华为荣耀畅玩6X：BLN-AL40，系统：8.0.0

**Comment by cortinico** [comment]
This and all the "couldn't find DSO to load" bugs have been fixed in React Native 0.71.

The issue on previous versions was a "too aggressive" clean-up logic in the `react.gradle` file. In 0.71 the clean-up logic has been rewritten to be more Android friendly and is now living inside the React Native Gradle Plugin.

I'm closing this, please update to 0.71 and open a new issue if the "couldn't find DSO to load" crash is still happening on 0.71+.
