### ISSUE TITLE
Build app crash in android. 

### ISSUE THREAD

**Issue by nghiant96** [facebook/react-native#31586]
I am init project with npx react-native init and run with npx react-native run-android
device xiaomi mi 9, android 10, miui 12.0.4
   

--------- beginning of crash
2021-05-25 16:19:56.877 22991-22991/com.oncallermobile E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.oncallermobile, PID: 22991
    java.lang.RuntimeException: Unable to create application .MainApplication: java.lang.RuntimeException: java.io.IOException: cannot mkdir: /data/user/0/{bundle}/lib-main
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6585)
        at android.app.ActivityThread.access$1400(ActivityThread.java:224)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7560)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.RuntimeException: java.io.IOException: cannot mkdir: /data/user/0/{bundle}/lib-main
        at com.facebook.soloader.SoLoader.init(SoLoader.java:214)
        at com.oncallermobile.MainApplication.onCreate(MainApplication.java:48)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6580)
        at android.app.ActivityThread.access$1400(ActivityThread.java:224) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7560) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
     Caused by: java.io.IOException: cannot mkdir: /data/user/0/com.oncallermobile/lib-main
        at com.facebook.soloader.SysUtil.mkdirOrThrow(SysUtil.java:237)
        at com.facebook.soloader.UnpackingSoSource.prepare(UnpackingSoSource.java:409)
        at com.facebook.soloader.SoLoader.initSoSources(SoLoader.java:322)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:200)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:182)
        at com.facebook.soloader.SoLoader.init(SoLoader.java:212)
        at com.oncallermobile.MainApplication.onCreate(MainApplication.java:48) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6580) 
        at android.app.ActivityThread.access$1400(ActivityThread.java:224) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7560) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 

react-native info 
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
    Memory: 70.55 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.14.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_251 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by lezinx** [comment]
Same here.
Device: Samsung A11, android 10.
STR:
1. npx react-native init AwesomeProject
2. npx react-native run-android

Error:
2021-05-25 17:44:31.809 9926-10110/com.awesomeproject E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.awesomeproject, PID: 9926
    java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
        at java.util.regex.Matcher.reset(Matcher.java:280)
        at java.util.regex.Matcher.<init>(Matcher.java:186)
        at java.util.regex.Pattern.matcher(Pattern.java:1034)
        at com.facebook.react.devsupport.BundleDownloader$1.onResponse(BundleDownloader.java:144)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by nghiant96** [comment]
i think error of rom xiaomi. I am have reset my phone. It working
