### ISSUE TITLE
 Landroid/media/AudioTrack;->getLatency(

### ISSUE THREAD

**Issue by medonagy45** [facebook/react-native#31594]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description

> StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/media/AudioTrack;->getLatency()I
	at android.os.StrictMode.lambda$static$1(StrictMode.java:416)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
	at java.lang.Class.getMethod(Class.java:2066)
	at java.lang.Class.getMethod(Class.java:1693)
	at com.google.android.gms.ads.exoplayer3.audio.s.<init>(:com.google.android.gms.policy_ads_fdr_dynamite@211512000@211512000057.367949677.367949677:2)
	at com.google.android.gms.ads.exoplayer3.audio.v.<init>(:com.google.android.gms.policy_ads_fdr_dynamite@211512000@211512000057.367949677.367949677:4)
	at com.google.android.gms.ads.internal.video.exoplayer3.ab.<init>(:com.google.android.gms.policy_ads_fdr_dynamite@211512000@211512000057.367949677.367949677:4)
	at com.google.android.gms.ads.internal.video.exoplayer3.m.D(:com.google.android.gms.policy_ads_fdr_dynamite@211512000@211512000057.367949677.367949677:2)
	at com.google.android.gms.ads.internal.video.exoplayer3.m.H(:com.google.android.gms.policy_ads_fdr_dynamite@211512000@211512000057.367949677.367949677:15)
	at com.google.android.gms.ads.internal.video.exoplayer3.m.onSurfaceTextureAvailable(:com.google.android.gms.policy_ads_fdr_dynamite@211512000@211512000057.367949677.367949677:4)
	at android.view.TextureView.getTextureLayer(TextureView.java:402)
	at android.view.TextureView.draw(TextureView.java:351)
	at android.view.View.updateDisplayListIfDirty(View.java:21226)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.View.draw(View.java:22081)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at com.facebook.react.views.view.f.dispatchDraw(ReactViewGroup.java:3)
	at android.view.View.updateDisplayListIfDirty(View.java:21217)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21186)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21186)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21186)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21186)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21186)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4500)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4473)
	at android.view.View.updateDisplayListIfDirty(View.java:21186)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4106)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3833)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3104)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

## React Native version:
^0.64.0

## Steps To Reproduce
it is shown on google play console Pre-launch report details

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
not found

**Comment by cortinico** [comment]
Hey,
We're cleaning up the React Native issue tracker to make sure we focus on the most important issues first.

I'm closing this one because it's stale and related to a version of React Native we no longer support. If the issue persists on the latest version, please re-open a new issue and reference this one.

Thank you.
