### ISSUE TITLE
ReactNative app fails Java 8 desugaring in release mode

### ISSUE THREAD

**Issue by kioli** [facebook/react-native#31625]
## Description
I have a problem when running my sample app (targeting Android APIs 19 to 30) which uses a library I made which in turns makes use of Java 8 classes.
I followed the [official Google guidelines](https://developer.android.com/studio/write/java8-support) to allow Java 8 compatibility both in the app and in the library, and that works when I launch my app in debug mode, but when I try to run its  release version it fails

## Steps To Reproduce

WORKING
1. execute ./android/gradlew -p android clean :app:**assembleDebug**
2. install .apk in android emulator API 30
3. launch app

FAILING
1. execute ./android/gradlew -p android clean :app:**assembleRelease**
2. install .apk in android emulator API 30
3. launch app

I obtain the following error

```logcat
E: CatalystInstanceImpl caught native exception
    java.lang.RuntimeException: Could not invoke UsabillaBridge.initialize
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:223) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lj$/time/OffsetDateTime;
        at com.usabilla.sdk.ubform.utils.DateUtilsKt.getDateFromMilliseconds$default(DateUtils.kt:9)
        at com.usabilla.sdk.ubform.telemetry.ReleaseTelemetryRecorder.record(ReleaseTelemetryRecorder.kt:90)
        at com.usabilla.sdk.ubform.telemetry.ReleaseTelemetryRecorder.start(ReleaseTelemetryRecorder.kt:16)
        at com.usabilla.sdk.ubform.UsabillaInternal.initialize(UsabillaInternal.kt:248)
        at com.usabilla.sdk.ubform.Usabilla.initialize(Usabilla.kt:64)
        at com.usabilla.sdk.ubform.Usabilla.initialize$default(Usabilla.kt:62)
        at com.usabilla.sdk.ubform.Usabilla.initialize(Unknown Source:8)
        at com.usabilla.reactnative.ubform.UsabillaBridge.initialize(UsabillaBridge.java:112)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:223) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: java.lang.ClassNotFoundException: j$.time.OffsetDateTime
        at com.usabilla.sdk.ubform.utils.DateUtilsKt.getDateFromMilliseconds$default(DateUtils.kt:9) 
        at com.usabilla.sdk.ubform.telemetry.ReleaseTelemetryRecorder.record(ReleaseTelemetryRecorder.kt:90) 
        at com.usabilla.sdk.ubform.telemetry.ReleaseTelemetryRecorder.start(ReleaseTelemetryRecorder.kt:16) 
        at com.usabilla.sdk.ubform.UsabillaInternal.initialize(UsabillaInternal.kt:248) 
        at com.usabilla.sdk.ubform.Usabilla.initialize(Usabilla.kt:64) 
        at com.usabilla.sdk.ubform.Usabilla.initialize$default(Usabilla.kt:62) 
        at com.usabilla.sdk.ubform.Usabilla.initialize(Unknown Source:8) 
        at com.usabilla.reactnative.ubform.UsabillaBridge.initialize(UsabillaBridge.java:112) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:223) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:923) 
E: Caught exception
    java.lang.RuntimeException: Could not invoke UsabillaBridge.initialize
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:223) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lj$/time/OffsetDateTime;
        at com.usabilla.sdk.ubform.utils.DateUtilsKt.getDateFromMilliseconds$default(DateUtils.kt:9)
        at com.usabilla.sdk.ubform.telemetry.ReleaseTelemetryRecorder.record(ReleaseTelemetryRecorder.kt:90)
        at com.usabilla.sdk.ubform.telemetry.ReleaseTelemetryRecorder.start(ReleaseTelemetryRecorder.kt:16)
        at com.usabilla.sdk.ubform.UsabillaInternal.initialize(UsabillaInternal.kt:248)
        at com.usabilla.sdk.ubform.Usabilla.initialize(Usabilla.kt:64)
        at com.usabilla.sdk.ubform.Usabilla.initialize$default(Usabilla.kt:62)
        at com.usabilla.sdk.ubform.Usabilla.initialize(Unknown Source:8)
        at com.usabilla.reactnative.ubform.UsabillaBridge.initialize(UsabillaBridge.java:112)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:223) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: java.lang.ClassNotFoundException: j$.time.OffsetDateTime
        at com.usabilla.sdk.ubform.utils.DateUtilsKt.getDateFromMilliseconds$default(DateUtils.kt:9) 
        at com.usabilla.sdk.ubform.telemetry.ReleaseTelemetryRecorder.record(ReleaseTelemetryRecorder.kt:90) 
        at com.usabilla.sdk.ubform.telemetry.ReleaseTelemetryRecorder.start(ReleaseTelemetryRecorder.kt:16) 
        at com.usabilla.sdk.ubform.UsabillaInternal.initialize(UsabillaInternal.kt:248) 
        at com.usabilla.sdk.ubform.Usabilla.initialize(Usabilla.kt:64) 
        at com.usabilla.sdk.ubform.Usabilla.initialize$default(Usabilla.kt:62) 
        at com.usabilla.sdk.ubform.Usabilla.initialize(Unknown Source:8) 
        at com.usabilla.reactnative.ubform.UsabillaBridge.initialize(UsabillaBridge.java:112) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:223) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:923) 
E: FATAL EXCEPTION: mqt_native_modules
    Process: com.rnusabilla, PID: 11142
    java.lang.RuntimeException: Could not invoke UsabillaBridge.initialize
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:223) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lj$/time/OffsetDateTime;
        at com.usabilla.sdk.ubform.utils.DateUtilsKt.getDateFromMilliseconds$default(DateUtils.kt:9)
        at com.usabilla.sdk.ubform.telemetry.ReleaseTelemetryRecorder.record(ReleaseTelemetryRecorder.kt:90)
        at com.usabilla.sdk.ubform.telemetry.ReleaseTelemetryRecorder.start(ReleaseTelemetryRecorder.kt:16)
        at com.usabilla.sdk.ubform.UsabillaInternal.initialize(UsabillaInternal.kt:248)
        at com.usabilla.sdk.ubform.Usabilla.initialize(Usabilla.kt:64)
        at com.usabilla.sdk.ubform.Usabilla.initialize$default(Usabilla.kt:62)
        at com.usabilla.sdk.ubform.Usabilla.initialize(Unknown Source:8)
        at com.usabilla.reactnative.ubform.UsabillaBridge.initialize(UsabillaBridge.java:112)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:223) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: java.lang.ClassNotFoundException: j$.time.OffsetDateTime
        at com.usabilla.sdk.ubform.utils.DateUtilsKt.getDateFromMilliseconds$default(DateUtils.kt:9) 
        at com.usabilla.sdk.ubform.telemetry.ReleaseTelemetryRecorder.record(ReleaseTelemetryRecorder.kt:90) 
        at com.usabilla.sdk.ubform.telemetry.ReleaseTelemetryRecorder.start(ReleaseTelemetryRecorder.kt:16) 
        at com.usabilla.sdk.ubform.UsabillaInternal.initialize(UsabillaInternal.kt:248) 
        at com.usabilla.sdk.ubform.Usabilla.initialize(Usabilla.kt:64) 
        at com.usabilla.sdk.ubform.Usabilla.initialize$default(Usabilla.kt:62) 
        at com.usabilla.sdk.ubform.Usabilla.initialize(Unknown Source:8) 
        at com.usabilla.reactnative.ubform.UsabillaBridge.initialize(UsabillaBridge.java:112) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:223) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:923) 

```

My app `build.gradle` files are the following

MAIN FOLDER LEVEL
```
buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.0.1")
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}
```

APP FOLDER LEVEL

```
apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"

def enableSeparateBuildPerCPUArchitecture = false
def enableProguardInReleaseBuilds = false
def jscFlavor = 'org.webkit:android-jsc:+'
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.rnusabilla"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Also making the two buildtypes identical to what i now debug doesn't solve the problem
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }
    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }

    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.0.9'
}

task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

```

**Comment by vasuagrawal84** [comment]
I was seeing this stack trace only for devices running devices on Android 7 or below in my application. I believe it was because `OffsetDateTime` was added in API 26 (Android 8) and the Usabilla React Native lib doesn't have a safety check for it. https://developer.android.com/reference/java/time/OffsetDateTime

Resolved by adding a system version check before calling the initialise function. Not too sure why you'd be getting it on API 30 though

**Comment by kioli** [comment]
Hi @vasuagrawal84 , what do you mean precisely by `the Usabilla React Native lib doesn't have a safety check for it`? How would you implement it? (besides the compatibility with desugaring explained by the Google guidelines)

And about your solving it, which kind of version check did you put? Something that circumvent the usage of `OffsetDateTime` when it's running on Android below 26?

**Comment by cortinico** [comment]
You can now use Java 11 in your project, and AGP is offering native desugaring capabilities:
https://developer.android.com/studio/write/java8-support-table
