### ISSUE TITLE
Crash under SecDroidFuzz

### ISSUE THREAD

**Issue by erich04** [facebook/react-native#31655]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
We recently scan the RN application using a fuzz tool named ScedroidFuzz, and got crash events like this.
We are not pretty sure if this is a bug or security risk, thx for the clarification。

java.lang.UnsupportedOperationException: This method is not supported for ReactViewGroup instances
at com.facebook.react.views.view.ReactViewGroup.setBackground(:180)
at android.view.View.<init>(View.java:5872)
at android.view.ViewGroup.<init>(ViewGroup.java:707)
at android.view.ViewGroup.<init>(ViewGroup.java:703)
at android.view.ViewGroup.<init>(ViewGroup.java:699)
at android.view.ViewGroup.<init>(ViewGroup.java:695)
at com.facebook.react.views.view.ReactViewGroup.<init>(:125)
at com.facebook.react.views.view.ReactViewManager.createViewInstance(:289)
at com.facebook.react.views.view.ReactViewManager.createViewInstance(:37)
at com.facebook.react.uimanager.ViewManager.createViewInstance(:139)
at com.facebook.react.uimanager.ViewManager.createView(:82)
at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(:269)
at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(:179)
at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(:972)
at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(:943)
at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(:28)
at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(:174)
at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(:84)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1253)
at android.view.Choreographer.doCallbacks(Choreographer.java:991)
at android.view.Choreographer.doFrame(Choreographer.java:879)

## React Native version:
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 5.40 GB / 15.93 GB
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - D:\wheel\RN_Tool\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 25.0.2, 26.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.0
      System Images: android-25 | Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom, android-27 | Android TV Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-Q | Android TV Intel x86 Atom, android-Q | Intel x86 Atom, android-Q | Intel x86 Atom_64, android-Q | Google APIs Intel x86 Atom, android-Q | Google APIs Intel x86 Atom_64, android-Q | Google Play Intel x86 Atom, android-Q | Google Play Intel x86 Atom_64
      Android NDK: 19.2.5345600
  npmPackages:
    react: ^16.13.0 => 16.14.0
    react-native: ^0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
## Steps To Reproduce

1.Connect the mobile phone to the PC
2.Start ScedroidFuzz and wait for minutes
3.that's all

## Expected Results
No crash happened during the scan.

## Snack, code example, screenshot, or link to a repository:
No code can be provided.

**Comment by hey99xx** [comment]
You should provide JS code you use to build the application as the 1st step in repro steps. Without it, noone can diagnose this issue. The issue should be closed unless you'll provide the code sample you use for testing.

**Comment by xiaoyi848699** [comment]
Can the exception be changed to log output?

**Comment by xiaoyi848699** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
