### ISSUE TITLE
How to build the property finder app on Android

### ISSUE THREAD

**Issue by oren** [facebook/react-native#3167]
I am trying to build a project that was written for iOS on my android phone - http://www.raywenderlich.com/99473/introducing-react-native-building-apps-javascript. 
This is the codebase: https://github.com/ColinEberhardt/ReactNative-PropertyFinder

I took the following steps:

1. Update the react-native in package.json to `"^0.11.4"`
1. `npm instal`
1. `react-native android`
1. `npm start` (That's the way to run packager on Ubuntu)
1. `adb reverse tcp:8081 tcp:8081 && react-native run-android`

The app is running on my phone but it's the wrong app! it's the 'hello world' app from the getting started tutorial instead of the property finder app. When looking at the content of index.android.js I see the hello world app.

Any advice?

**Comment by ide** [comment]
Are you running the packager in the right directory? Also try uninstalling the app from your phone. On Android it currently caches the bundle.

**Comment by oren** [comment]
I just deleted all previous apps and it's still showing the 'welcome to react native!' text.
the app name is correct - PropertyFinder.

```
git status -s

 M .gitignore
 M package.json
?? .flowconfig
?? .watchmanconfig
?? android/
?? index.android.js
```

notice that `react-native android` created index.android.js (which contain the hello world component)

**Comment by mkonicek** [comment]
Hi @oren, thanks for reporting! Your `MainActivity.java` probably says to load the `index.android.js`. It's what `react-native android` does by default. Can you edit `setBundleAssetName` and `setJSMainModuleName` in your `MainActivity.java` to point to the name of your JS file?

**Comment by foghina** [comment]
What @mkonicek said. Furthermore, instead of changing `MainActivity` to load a different file, you can edit `index.android.js` to render your app instead. Even better, you can rename `index.ios.js` to `index.js` and remove `index.android.js` completely. It's just scaffolding.

**Comment by oren** [comment]
I followed @foghina 's suggestion and I see the red screen with 'unable to download JS bundle' message.

```
rm index.android.js
mv index.ios.js index.js
adb reverse tcp:8081 tcp:8081 && react-native run-android

JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72300Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42300Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee061Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore061Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco061Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline061Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp061Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0110Library UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:preDexDebug UP-TO-DATE
:app:dexDebug UP-TO-DATE
:app:validateDebugSigning
:app:packageDebug UP-TO-DATE
:app:zipalignDebug UP-TO-DATE
:app:assembleDebug UP-TO-DATE
:app:installDebug
Installing APK 'app-debug.apk' on 'XT1094 - 5.1'
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 1 mins 17.773 secs

This build could be faster, please consider using the Gradle Daemon: http://gradle.org/docs/2.4/userguide/gradle_daemon.html
Starting the app (adb shell am start -n com.propertyfinder/.MainActivity)...
Starting: Intent { cmp=com.propertyfinder/.MainActivity }
```

Packager log:
```
React packager ready.

[09:31:44] <START> Building Dependency Graph
[09:31:44] <START> Crawling File System
[09:31:47] <END>   Crawling File System (3066ms)
[09:31:47] <START> Building in-memory fs for JavaScript
[09:31:54] <END>   Building in-memory fs for JavaScript (6699ms)
[09:31:54] <START> Building in-memory fs for Assets
[09:31:57] <END>   Building in-memory fs for Assets (3817ms)
[09:31:57] <START> Building Haste Map
[09:32:01] <START> Building (deprecated) Asset Map
[09:32:02] <END>   Building (deprecated) Asset Map (1670ms)
[09:32:02] <END>   Building Haste Map (4812ms)
[09:32:02] <END>   Building Dependency Graph (18400ms)
[09:34:21] <START> request:/index.android.bundle?platform=android
[09:34:21] <START> find dependencies
[09:35:10] <START> request:/index.android.bundle?platform=android
[09:35:10] <START> find dependencies
[09:35:17] <START> request:/index.android.bundle?platform=android
[09:35:17] <START> find dependencies
```

**Comment by foghina** [comment]
Are you using an emulator (SDK or Genymotion)? You don't need to run the `adb reverse` command if you're using an emulator. On the contrary, that will break reloading. If that is the case, please try restarting the emulator.

**Comment by oren** [comment]
I am using my phone.

**Comment by foghina** [comment]
Ah, yes. The app is still requesting `index.android.bundle`, but `index.android.js` doesn't exist anymore. You need to edit `MainActivity.java` and change:

    .setJSMainModuleName("index.android")

to:

    .setJSMainModuleName("index")

**Comment by oren** [comment]
now I got this error - https://github.com/facebook/react-native/issues/3199
):

I'll report back when i'll fix it.

**Comment by oren** [comment]
I was able to run the watchman (not sure what changed, maybe my laptop's CPU/Memory is lower).
Now I see a white screen when I open the app.
Here is the watchman output:
```
React packager ready.

[14:19:41] <START> Building Dependency Graph
[14:19:41] <START> Crawling File System
[14:19:43] <END>   Crawling File System (1463ms)
[14:19:43] <START> Building in-memory fs for JavaScript
[14:19:43] <END>   Building in-memory fs for JavaScript (593ms)
[14:19:43] <START> Building in-memory fs for Assets
[14:19:44] <END>   Building in-memory fs for Assets (551ms)
[14:19:44] <START> Building Haste Map
[14:19:44] <START> Building (deprecated) Asset Map
[14:19:45] <END>   Building (deprecated) Asset Map (251ms)
[14:19:45] <END>   Building Haste Map (981ms)
[14:19:45] <END>   Building Dependency Graph (3589ms)
transforming [==                                      ] 6% 18/313[14:25:04] <START> request:/index.bundle?platform=android
[14:25:04] <START> find dependencies
[14:25:05] <END>   find dependencies (267ms)
[14:25:05] <START> transform
transforming [========================================] 100% 313/313
[14:25:11] <END>   transform (5991ms)
[14:25:11] <END>   request:/index.bundle?platform=android (6279ms)
::ffff:127.0.0.1 - - [Sat, 03 Oct 2015 21:25:12 GMT] "GET /flow/ HTTP/1.1" 404 - "-" "okhttp/2.4.0"
::ffff:127.0.0.1 - - [Sat, 03 Oct 2015 21:25:30 GMT] "GET /flow/ HTTP/1.1" 404 - "-" "okhttp/2.4.0"
```

**Comment by foghina** [comment]
Can you run `adb logcat` and post the output that gets generated when you try to start the app / reload JS?

**Comment by oren** [comment]
```
W/unknown:React(24329): You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
E/unknown:React(24329): Unable to download JS bundle
E/unknown:React(24329): java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 8081) after 5000ms: isConnected failed: ECONNREFUSED (Connection refused)
E/unknown:React(24329):         at libcore.io.IoBridge.isConnected(IoBridge.java:238)
E/unknown:React(24329):         at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
E/unknown:React(24329):         at libcore.io.IoBridge.connect(IoBridge.java:122)
E/unknown:React(24329):         at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
E/unknown:React(24329):         at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
E/unknown:React(24329):         at java.net.Socket.connect(Socket.java:882)
E/unknown:React(24329):         at com.squareup.okhttp.internal.Platform$Android.connectSocket(Platform.java:190)
E/unknown:React(24329):         at com.squareup.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
E/unknown:React(24329):         at com.squareup.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67)
E/unknown:React(24329):         at com.squareup.okhttp.Connection.connect(Connection.java:152)
E/unknown:React(24329):         at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:185)
E/unknown:React(24329):         at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
E/unknown:React(24329):         at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
E/unknown:React(24329):         at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
E/unknown:React(24329):         at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
E/unknown:React(24329):         at com.squareup.okhttp.Call.getResponse(Call.java:273)
E/unknown:React(24329):         at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
E/unknown:React(24329):         at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
E/unknown:React(24329):         at com.squareup.okhttp.Call.access$100(Call.java:36)
E/unknown:React(24329):         at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:164)
E/unknown:React(24329):         at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
E/unknown:React(24329):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/unknown:React(24329):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/unknown:React(24329):         at java.lang.Thread.run(Thread.java:818)
E/unknown:React(24329): Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
E/unknown:React(24329):         at libcore.io.IoBridge.isConnected(IoBridge.java:223)
E/unknown:React(24329):         ... 23 more
I/Keyboard.Facilitator( 2374): onFinishInput()
I/Keyboard.Facilitator( 2374): onFinishInput()
I/SFPerfTracer(  297):      triggers: (rate: 0:38) (3632413 sw vsyncs) (0 skipped) (23:2471965 vsyncs) (25:6267071)
E/WifiStateMachine(  953):  ConnectedState !CMD_RSSI_POLL 720 0 "pinkelephant" 48:f8:b3:77:2d:1c rssi=-38 f=5240 sc=60 link=150 tx=0.3, 0.0, 0.0  rx=0.3 bcn=0 [on:0 tx:0 rx:0 period:3004] from screen [on:0 period:995146796] gl hn rssi=-33 ag=0 hr ls-=0 [56,56,56,56,61] brc=0 lrc=0
E/WifiStateMachine(  953):  L2ConnectedState !CMD_RSSI_POLL 720 0 "pinkelephant" 48:f8:b3:77:2d:1c rssi=-38 f=5240 sc=60 link=150 tx=0.3, 0.0, 0.0  rx=0.3 bcn=0 [on:0 tx:0 rx:0 period:5] from screen [on:0 period:995146801] gl hn rssi=-33 ag=0 hr ls-=0 [56,56,56,56,61] brc=0 lrc=0
D/WifiNative-wlan0(  953): doString: [SIGNAL_POLL]
E/WifiStateMachine(  953): fetchRssiLinkSpeedAndFrequencyNative rssi=-38 linkspeed=150
E/WifiConfigStore(  953): updateConfiguration freq=5240 BSSID=48:f8:b3:77:2d:1c RSSI=-37 "pinkelephant"WPA_PSK
E/WifiStateMachine(  953): calculateWifiScore freq=5240 speed=150 score=60 highRSSI  -> txbadrate=0.00 txgoodrate=0.13 txretriesrate=0.00 rxrate=0.13 userTriggerdPenalty0
E/WifiStateMachine(  953):  good link -> stuck count =0
E/WifiStateMachine(  953):  badRSSI count0 lowRSSI count0 --> score 56
E/WifiStateMachine(  953):  isHighRSSI       ---> score=61
I/MotoNetwCtrlr( 2198): onReceive: Received intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } Action=android.net.wifi.RSSI_CHANGED
I/MotoNetwCtrlr.MotoWifiSignalCtrlr( 2198): handleBroadcast: Entered: Intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has ex
tras) } Action=android.net.wifi.RSSI_CHANGED
I/MotoNetwCtrlr.MotorolaWifiSignalController( 2198): isDirty: returns false
I/MotoNetwCtrlr.MotoWifiSignalCtrlr( 2198): handleBroadcast: Completed
I/MotoNetwCtrlr( 2198): onReceive: Completed intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) } Action=android.net.wifi.RSSI_CHANGED
I/MotoNetwCtrlr.MotoWifiHndlr( 2198): handleMessage: Entered msg.what=1
I/MotoNetwCtrlr.MotorolaWifiSignalController( 2198): isDirty: returns true
I/MotoNetwCtrlr.MotorolaWifiSignalController( 2198): notifyListeners: calling SB [0] setWifiIndicators (Motorola api): UseMotoUI=true Vis=true SBSig=0x7f02014c=stat_sys_wifi_signal_4_fully SBAct=( none ) DescSig="Wifi signal full." DescAct="wifi in" NetName=""pinkelephant""
I/MotoNetwCtrlr.MotorolaWifiSignalController( 2198): notifyListeners: calling SB [1] setWifiIndicators (Motorola api): UseMotoUI=true Vis=true SBSig=0x7f02014c=stat_sys_wifi_signal_4_fully SBAct=( none ) DescSig="Wifi signal full." DescAct="wifi in" NetName=""pinkelephant""
I/MotoNetwCtrlr.MotorolaWifiSignalController( 2198): notifyListeners: calling SB [2] setWifiIndicators (Motorola api): UseMotoUI=true Vis=true SBSig=0x7f02014c=stat_sys_wifi_signal_4_fully SBAct=( none ) DescSig="Wifi signal full." DescAct="wifi in" NetName=""pinkelephant""
I/MotoNetwCtrlr.MotoWifiHndlr( 2198): handleMessage: Completed
I/MotoNetwCtrlr.MotoWifiHndlr( 2198): handleMessage: Entered msg.what=1
I/MotoNetwCtrlr.MotorolaWifiSignalController( 2198): isDirty: returns true
I/MotoNetwCtrlr.MotorolaWifiSignalController( 2198): notifyListeners: calling SB [0] setWifiIndicators (Motorola api): UseMotoUI=true Vis=true SBSig=0x7f02014c=stat_sys_wifi_signal_4_fully SBAct=( none ) DescSig="Wifi signal full." DescAct="wifi idle" NetName=""pinkelephant""
I/MotoNetwCtrlr.MotorolaWifiSignalController( 2198): notifyListeners: calling SB [1] setWifiIndicators (Motorola api): UseMotoUI=true Vis=true SBSig=0x7f02014c=stat_sys_wifi_signal_4_fully SBAct=( none ) DescSig="Wifi signal full." DescAct="wifi idle" NetName=""pinkelephant""
I/MotoNetwCtrlr.MotorolaWifiSignalController( 2198): notifyListeners: calling SB [2] setWifiIndicators (Motorola api): UseMotoUI=true Vis=true SBSig=0x7f02014c=stat_sys_wifi_signal_4_fully SBAct=( none ) DescSig="Wifi signal full." DescAct="wifi idle" NetName=""pinkelephant""
I/MotoNetwCtrlr.MotoWifiHndlr( 2198): handleMessage: Completed
E/WifiStateMachine(  953):  ConnectedState !CMD_START_SCAN -2 5779 ic=0 proc(ms):20004 dur:104 cnt=5779 rssi=-38 f=5240 sc=60 link=150 tx=0.1, 0.0, 0.0  rx=0.1 list=2457,5240 [on:0 tx:0 rx:0 period:1984] from screen [on:0 period:995148807]
E/WifiStateMachine(  953):  L2ConnectedState !CMD_START_SCAN -2 5779 ic=0 proc(ms):20008 dur:104 cnt=5779 rssi=-38 f=5240 sc=60 link=150 tx=0.1, 0.0, 0.0  rx=0.1 list=2457,5240 [on:0 tx:0 rx:0 period:4] from screen [on:0 period:995148811]
E/WifiStateMachine(  953): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.13 rxSuccessRate=0.13 targetRoamBSSID=any RSSI=-38
E/WifiStateMachine(  953): startDelayedScan send -> 5780 milli 20000
E/WifiStateMachine(  953): WifiStateMachine CMD_START_SCAN with age=40020 interval=45000 maxinterval=300000
E/WifiStateMachine(  953): WifiStateMachine CMD_START_SCAN full=false
E/WifiConfigStore(  953): makeChannelList age=3600000 for "pinkelephant"WPA_PSK max=6 bssids=1 linked=1
E/WifiConfigStore(  953): has 48:f8:b3:77:2d:1c freq=5240 age=1995 ?=true
E/WifiConfigStore(  953): has link: 48:f8:b3:77:2d:1a freq=2457 age=19813
E/WifiStateMachine(  953): WifiStateMachine starting scan for "pinkelephant"WPA_PSK with 2457,5240
D/WifiNative-wlan0(  953): doBoolean: SCAN TYPE=ONLY freq=2457,5240
D/WifiMonitor(  953): Event [IFNAME=wlan0 CTRL-EVENT-SCAN-STARTED ]
E/WifiMonitor(  953): WifiMonitor:wlan0 cnt=42885 dispatchEvent: CTRL-EVENT-SCAN-STARTED 
E/WifiMonitor(  953): handleEvent 14  CTRL-EVENT-SCAN-STARTED 
E/WifiMonitor(  953): handleEvent unknown: 14  CTRL-EVENT-SCAN-STARTED 
D/WifiNative-wlan0(  953): SCAN TYPE=ONLY freq=2457,5240: returned true
E/WifiStateMachine(  953): [1,444,104,160,274 ms] noteScanstart no scan source uid -2
```

**Comment by foghina** [comment]
You need to run the `adb reverse` command every time you connect your device, and you need to keep the device connected via USB.
