### ISSUE TITLE
No Support for Logical OR Assignment ||= 

### ISSUE THREAD

**Issue by ArshanKhanifar** [facebook/react-native#31704]
## Description
In my code I'm using a Logical OR Assignment, and it results into a low-level bundle parsing error. 
```
let a = "";
a ||= "happy"; // Logical OR Assignment
```
And in the app I see this: 
![image](https://user-images.githubusercontent.com/10492324/121614150-1a16b680-ca2c-11eb-8bb8-870d8822c861.png)

And in Logcat I see this: 
![image](https://user-images.githubusercontent.com/10492324/121614180-2995ff80-ca2c-11eb-9725-85895f00e7ac.png)

Here's the log dump: 
```
2021-06-10 20:40:01.058 18883-6084/com.waveform.walk_test E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    com.facebook.jni.CppException: Unexpected token '='
    
    no stack
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
2021-06-10 20:40:01.058 18883-6084/com.waveform.walk_test E/unknown:ReactNative: Exception in native call
    com.facebook.jni.CppException: Unexpected token '='
    
    no stack
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
2021-06-10 20:40:01.058 18883-6084/com.waveform.walk_test E/ReactNativeJNI: Attempting to call JS function on a bad application bundle: HMRClient.setup()
2021-06-10 20:40:01.059 18883-6084/com.waveform.walk_test E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: HMRClient.setup()
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
2021-06-10 20:40:01.059 18883-6084/com.waveform.walk_test E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: HMRClient.setup()
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
2021-06-10 20:40:01.059 18883-6084/com.waveform.walk_test E/ReactNativeJNI: Attempting to call JS function on a bad application bundle: AppRegistry.runApplication()
2021-06-10 20:40:01.059 18883-6084/com.waveform.walk_test E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: AppRegistry.runApplication()
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
2021-06-10 20:40:01.059 18883-6084/com.waveform.walk_test E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: AppRegistry.runApplication()
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
```

## React Native version:
Run `react-native info` in your terminal and copy the results here.
```
System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 614.80 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.5.1 - /usr/local/Cellar/node/15.5.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.3.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 10.0.1 - /usr/bin/javac
    Python: 3.7.3 - /Users/arshankhanifar/miniconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
1. Create a react native application
2. Put this code block in any JS file
```
let a = "";
a ||= "happy"; // Logical OR Assignment
```

## Expected Results
Javascript should compile and upon running should assign `"happy"` to the variable `a`.

## Snack, code example, screenshot, or link to a repository:
Here's a snack that easily shows this issue:
https://snack.expo.io/@arshankhanifar/react-native-logical-or-assignment-demo

I just simply added this right after the App Component declaration: 
```
export default function App() {
  let i = 0;
   i ||= 2;
  // ..etc etc 
```

**Comment by ArshanKhanifar** [comment]
Turns out logical or assignment is a new feature and it's [been added as a plugin in babel](https://babeljs.io/docs/en/babel-plugin-proposal-logical-assignment-operators). 

My temporary fix for this is as follows: 
```
yarn add --dev @babel/plugin-proposal-logical-assignment-operators
```

Then I had to add it to my `babel.config.js`: 
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['@babel/plugin-proposal-logical-assignment-operators'], // I added this line
};
```

Then I had to do a `yarn start --reset-cache` and it fixed the problem. 

Should I keep this PR open? I guess the fix for this is to add the `'@babel/plugin-proposal-logical-assignment-operators'` plugin into the `metro-react-native-babel-preset` package.

**Comment by clarkology56** [comment]
@ArshanKhanifar can you create a PR for this?

**Comment by jonthysell** [comment]
This is also necessary to resolve the use of null coalescing assignment, i.e. `??=`. This was used (for a short time) in `ListMetricsAggregator.js` (and just happened to be removed in this commit on 8/4): https://github.com/facebook/react-native/commit/ace0a80dead59d552ed16872de05cd9e977fc6b2.

This was causing us at `react-native-windows` confusion as we integrated up to 7/22 and got the new operator without the plugin added by default and needed to be fixed in our code. See https://github.com/microsoft/react-native-windows/pull/11970
