### ISSUE TITLE
Upgrade 0.63.4 to 0.64.2  - TypeError: Network request failed - Android

### ISSUE THREAD

**Issue by quachdev** [facebook/react-native#31703]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When making any network request using `fetch` on Android I am immediately receiving `TypeError: Network request failed` and the app crashes.

This works fine on iOS and seems to be Android specific. 

Downgrading to 0.63.4 works fine.

From the release notes, the error looks to be related to this PR [updating okhttp](https://github.com/facebook/react-native/commit/0f6fcb2c2788dc7150f6c3673a8f4f9d8f929441). How would downgrade it to test this?

From flipper logs: 

```
FATAL EXCEPTION: OkHttp Dispatcher

java.lang.NoSuchMethodError: No virtual method toString(Z)Ljava/lang/String; in class Lokhttp3/Cookie; or its super classes (declaration of 'okhttp3.Cookie' appears in /data/app/~~MpYZ_TQ66BEt9s5EWN7J8w==/com.myapp-7OHSdQhHSKPSzxLGYKEDgg==/base.apk!classes4.dex)

FATAL EXCEPTION: OkHttp Dispatcher
Process: com.myapp, PID: 8581
java.lang.NoSuchMethodError: No virtual method toString(Z)Ljava/lang/String; in class Lokhttp3/Cookie; or its super classes (declaration of 'okhttp3.Cookie' appears in /data/app/~~MpYZ_TQ66BEt9s5EWN7J8w==/com.myapp-7OHSdQhHSKPSzxLGYKEDgg==/base.apk!classes4.dex)
	at okhttp3.JavaNetCookieJar.saveFromResponse(JavaNetCookieJar.java:45)
	at com.facebook.react.modules.network.ReactCookieJarContainer.saveFromResponse(ReactCookieJarContainer.java:37)
	at okhttp3.internal.http.HttpHeaders.receiveHeaders(HttpHeaders.kt:207)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:85)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

## React Native version:

System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 67.71 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.6.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.4.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3, 31.0.0
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create a new project
2. Make a network request using `fetch`.

## Expected Results
App should be able to make the network request and not crash from the result.

**Comment by quachdev** [comment]
Closing as I am certain I have managed to isolate this [issue](https://github.com/plaid/react-native-plaid-link-sdk/issues/388) from a dependency that the project is using and added it there:
