### ISSUE TITLE
java.lang.IllegalArgumentException: Unable to find JSIModule for class interface com.facebook.react.bridge.UIManager

### ISSUE THREAD

**Issue by zhengyanGit** [facebook/react-native#31761]
react-native 版本从0.55.4 升级到版本0.57.8 时 ， 开发模式运行没问题，打release包报错
 java.lang.IllegalArgumentException: Unable to find JSIModule for class interface com.facebook.react.bridge.UIManager
        at com.facebook.react.bridge.JSIModuleRegistry.getModule(JSIModuleRegistry.java:17)
        at com.facebook.react.bridge.CatalystInstanceImpl.getJSIModule(CatalystInstanceImpl.java:478)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:30)
        at com.facebook.react.uimanager.UIManagerModule.dispatchViewManagerCommand(UIManagerModule.java:631)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:219)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:929)

问题原因：由于项目用了热更新，热包更新服务器那边版本是0.55.4 ，和现最新的0.57.8版本对应不上，所以只要热更新就报上面那个错误。
以上问题是俩个版本不一致产生的，出现类似问题可以去官网提供的俩个版本比较诧异点：https://react-native-community.github.io/upgrade-helper/

**Comment by cortinico** [comment]
Hey,
We're cleaning up the React Native issue tracker to make sure we focus on the most important issues first.

I'm closing this one because it's stale and related to a version of React Native we no longer support. If the issue persists on the latest version, please re-open a new issue and reference this one.

Moreover, we generally can't fix issues just by looking at a stacktrace reported from your crash reporting platform. Please provide a reproducer in your future reports.

Thank you.
