### ISSUE TITLE
Android Release build crashes after upgrading to 0.64.2 (hermes enabled)

### ISSUE THREAD

**Issue by AkashBabu** [facebook/react-native#31799]
Ours is an Android only Application.

## Description
We upgraded our App from 0.61.5 to 0.64.2(hermes enabled) and debug build seemed to work fine, while the release fails with the following error:
```
2021-07-02 14:14:34.946 29256-29467/com.flipkart.seller E/ReactNativeJS: TypeError: Cannot read property 'style' of undefined, js engine: hermes
2021-07-02 14:14:34.963 29256-29467/com.flipkart.seller E/ReactNativeJS: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
          This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
2021-07-02 14:14:35.047 29256-29469/com.flipkart.seller E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.flipkart.seller, PID: 29256
    com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'style' of undefined, js engine: hermes, stack:
    anonymous@1:454110
    h@1:82260
    d@1:81930
    o@1:81558
    anonymous@1:451031
    h@1:82260
    d@1:81930
    o@1:81558
    get TextInput@1:103370
    anonymous@1:709972
    h@1:82260
    d@1:81930
    o@1:81558
    anonymous@1:684543
    h@1:82260
    d@1:81930
    o@1:81558
    anonymous@1:1000552
    h@1:82260
    d@1:81930
    o@1:81558
    anonymous@1:954864
    h@1:82260
    d@1:81930
    o@1:81558
    anonymous@1:953733
    h@1:82260
    d@1:81930
    o@1:81558
    anonymous@1:951784
    h@1:82260
    d@1:81930
    o@1:81558
    anonymous@1:731714
    h@1:82260
    d@1:81930
    o@1:81558
    anonymous@1:724156
    h@1:82260
    d@1:81930
    o@1:81558
    anonymous@1:606677
    h@1:82260
    d@1:81930
    o@1:81558
    anonymous@1:89062
    h@1:82260
    d@1:81930
    o@1:81558
    anonymous@1:88728
    h@1:82260
    d@1:81887
    o@1:81558
    global@1:81246
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(SourceFile:12)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(SourceFile:18)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(SourceFile:2)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:1)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(SourceFile:8)
        at java.lang.Thread.run(Thread.java:923)
```

## React Native version:
```
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 90.14 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    Yarn: Not Found
    npm: 7.18.1 - ~/.nvm/versions/node/v12.22.1/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Upgrade the App from 0.61.5 to 0.64.2
2. Install release build with Hermes enabled

## Expected Results
Expect the App to run fine without any errors (just like in Debug build)

## Snack, code example, screenshot, or link to a repository:
NA

**Comment by AkashBabu** [comment]
My Bad found a deprecated usage in node_modules. Hence closing this thread.
