### ISSUE TITLE
AbstractMethodError

### ISSUE THREAD

**Issue by Ankushds** [facebook/react-native#31800]
2021-07-02 14:38:07.616 15221-15221/com.jio.testapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jio.testapp, PID: 15221
    java.lang.AbstractMethodError: abstract method "boolean com.facebook.react.ReactActivity.getUseDeveloperSupport()"
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:130)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Describe what you expected to happen.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve
![image](https://user-images.githubusercontent.com/18578103/124251787-eb2fc400-db43-11eb-8735-238bc6991f36.png)

**Comment by Noeipan** [comment]
Bang gmana cara nya ya

**Comment by cortinico** [comment]
Hey,
We're cleaning up the React Native issue tracker to make sure we focus on the most important issues first.

I'm closing this one because it's stale and related to a version of React Native we no longer support. If the issue persists on the latest version, please re-open a new issue and reference this one.

Thank you.
