### ISSUE TITLE
[Android] StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/widget/ScrollView;->mScroller:Landroid/widget/OverScroller;

### ISSUE THREAD

**Issue by gavdix** [facebook/react-native#31869]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
This issue was raised earlier also, here is the link: https://github.com/facebook/react-native/issues/25120
Hi guys,

I guess everyone knows by now that starting with Android Pie Google enforces restrictions on usage of non-sdk interfaces. I looked through the issues on this repo, and though some were raised about these interfaces, they were closed without a proper fix.

I would like to highlight a specific one, that I've been getting warning for in Google Play Console.

## React Native version:
63.2

## Steps To Reproduce
This issue is found when I uploaded React-Native app in Google Playstore.
Google enforces restrictions on usage of non-sdk interfaces and react-native library is using mScroller from `android.widget.OverScroller;` in `ReactScrollView.java`

1. Upload react-native app in google play store
2. Check pre-launch report

## Expected Results
React-native android class `ReactScrollView.java` should not use non-sdk interfaces so that Google Play store will not throw this warning. 

## Snack, code example, screenshot, or link to a repository: Here is logs from Google play store
`StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/widget/ScrollView;->mScroller:Landroid/widget/OverScroller;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at com.facebook.react.views.scroll.ReactScrollView.getOverScrollerFromParent(ReactScrollView.java:99)
	at com.facebook.react.views.scroll.ReactScrollView.<init>(ReactScrollView.java:87)
	at com.facebook.react.views.scroll.ReactScrollViewManager.createViewInstance(ReactScrollViewManager.java:64)
	at com.facebook.react.views.scroll.ReactScrollViewManager.createViewInstance(ReactScrollViewManager.java:37)
	at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:83)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:270)
	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:180)
	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:786)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:903)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$2400(UIViewOperationQueue.java:43)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:963)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:693)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadForAtLeast(UiControllerImpl.java:8)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:4)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:19)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by gavdix** [comment]
@reactjs-bot , guys, can anyone address this?

**Comment by Kazion500** [comment]
@gavdix did you find a fix for this?

**Comment by gavdix** [comment]
@Kazion500 , no i didn't find.
