### ISSUE TITLE
Unhandled MotionEvent action

### ISSUE THREAD

**Issue by nklhrstv** [facebook/react-native#31866]
## Description
in the crashlytics i got this crash report:

```
java.lang.RuntimeException: Unhandled MotionEvent action: 12
	at com.facebook.react.uimanager.events.TouchEvent.init(TouchEvent.java:98)
	at com.facebook.react.uimanager.events.TouchEvent.obtain(TouchEvent.java:45)
	at com.facebook.react.uimanager.JSTouchDispatcher.dispatchCancelEvent(JSTouchDispatcher.java:183)
	at com.facebook.react.uimanager.JSTouchDispatcher.onChildStartedNativeGesture(JSTouchDispatcher.java:48)
	at com.facebook.react.ReactRootView.onChildStartedNativeGesture(ReactRootView.java:205)
	at com.facebook.react.uimanager.events.NativeGestureUtil.notifyNativeGestureStarted(NativeGestureUtil.java:26)
	at com.facebook.react.views.drawer.ReactDrawerLayout.onInterceptTouchEvent(ReactDrawerLayout.java:37)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2573)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3400)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
	at android.view.View.dispatchPointerEvent(View.java:12752)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5119)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4922)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4439)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4492)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4458)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4598)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4466)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4655)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4439)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4492)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4458)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4466)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4439)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7105)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7074)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7035)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7208)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:326)
	at android.os.Looper.loop(Looper.java:160)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

the device is UGOOS-AM6, uses api level 28
the exception is thrown from [here](https://github.com/facebook/react-native/blob/421df262661ad5ade7c190618d4a5b5bb71fef30/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/TouchEvent.java#L123)

## React Native version:
react-native: 0.64.0

## Expected Results
not to crash

**Comment by cortinico** [comment]
Hey,
We're cleaning up the React Native issue tracker to make sure we focus on the most important issues first.

I'm closing this one because it's stale and related to a version of React Native we no longer support. If the issue persists on the latest version, please re-open a new issue and reference this one.

Moreover, we generally can't fix issues just by looking at a stacktrace reported from your crash reporting platform. Please provide a reproducer in your future reports.

Thank you.
