### ISSUE TITLE
Error: Cannot find module 'react-native-codegen/package.json'

### ISSUE THREAD

**Issue by stoneioslife** [facebook/react-native#31908]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
When i bulid my project. i will get 'Cannot find module 'react-native-codegen/package.json'.
this is my profile:
install! 'cocoapods',
        disable_input_output_paths: true,
        generate_multiple_pod_projects: true
platform :ios, '10.0'

# 公有仓库
source 'https://github.com/CocoaPods/Specs.git'

# 记录target名字的全局变量
$target_Arr = Array.new

# 组件路径
$module_dir = ENV['EASYDOCTOR_MODULE_DIR']

$rn_node_moudles_dir = $module_dir + '/ngarirnlib/node_modules'
$rn_react_pod_dir =  $rn_node_moudles_dir+'/react-native/'

#忽略pod里面警告
inhibit_all_warnings!

def ngarirnlib_pod
   pod 'FBLazyVector', :path => $rn_react_pod_dir + "Libraries/FBLazyVector"
   pod 'FBReactNativeSpec', :path => $rn_react_pod_dir + "React/FBReactNativeSpec"
   pod 'RCTRequired', :path => $rn_react_pod_dir + "Libraries/RCTRequired"
   pod 'RCTTypeSafety', :path => $rn_react_pod_dir + "Libraries/TypeSafety"
   pod 'React', :path => $rn_react_pod_dir
   pod 'React-Core', :path => $rn_react_pod_dir
   pod 'React-CoreModules', :path => $rn_react_pod_dir + 'React/CoreModules'
   pod 'React-Core/DevSupport', :path => $rn_react_pod_dir
   pod 'React-RCTActionSheet', :path => $rn_react_pod_dir + 'Libraries/ActionSheetIOS'
   pod 'React-RCTAnimation', :path => $rn_react_pod_dir + 'Libraries/NativeAnimation'
   pod 'React-RCTBlob', :path => $rn_react_pod_dir + 'Libraries/Blob'
   pod 'React-RCTImage', :path => $rn_react_pod_dir + 'Libraries/Image'
   pod 'React-RCTLinking', :path => $rn_react_pod_dir + 'Libraries/LinkingIOS'
   pod 'React-RCTNetwork', :path => $rn_react_pod_dir + 'Libraries/Network'
   pod 'React-RCTSettings', :path => $rn_react_pod_dir + 'Libraries/Settings'
   pod 'React-RCTText', :path => $rn_react_pod_dir + 'Libraries/Text'
   pod 'React-RCTVibration', :path => $rn_react_pod_dir + 'Libraries/Vibration'
   pod 'React-Core/RCTWebSocket', :path => $rn_react_pod_dir

   pod 'React-cxxreact', :path => $rn_react_pod_dir + 'ReactCommon/cxxreact'
   pod 'React-runtimeexecutor', :path => $rn_react_pod_dir + 'ReactCommon/runtimeexecutor'
   pod 'React-jsi', :path => $rn_react_pod_dir + 'ReactCommon/jsi'
   pod 'React-jsiexecutor', :path => $rn_react_pod_dir + 'ReactCommon/jsiexecutor'
   pod 'React-perflogger', :path => $rn_react_pod_dir + 'ReactCommon/reactperflogger'
   pod 'React-jsinspector', :path => $rn_react_pod_dir + 'ReactCommon/jsinspector'
   pod 'React-callinvoker', :path => $rn_react_pod_dir + "ReactCommon/callinvoker"
   pod 'ReactCommon/turbomodule/core', :path => $rn_react_pod_dir + "ReactCommon"
   
   pod 'Yoga', :path => $rn_react_pod_dir + 'ReactCommon/yoga'
   pod 'DoubleConversion', :podspec => $rn_react_pod_dir + 'third-party-podspecs/DoubleConversion.podspec'
   pod 'glog', :podspec => $rn_react_pod_dir + 'third-party-podspecs/glog.podspec'
   pod 'RCT-Folly', :podspec => $rn_react_pod_dir + 'third-party-podspecs/RCT-Folly.podspec'
end

def debug_pods
    pod 'NDDataFramework',:path => $module_dir + '/ios-tools-module'
    pod 'NDToolsFramework',:path => $module_dir + '/ios-tools-module'
    pod 'NDObjectFramework',:path => $module_dir + '/ios-tools-module'
    pod 'NDSocketFramework',:path => $module_dir + '/ios-tools-module'
    pod 'NgariDoctorBaseUI',:path => $module_dir + '/NgariDoctorBaseUI'
    pod 'NgariDoctorPatient',:path => $module_dir + '/NgariDoctorPatient'
    pod 'NDPublicLogicLib',:path => $module_dir + '/NDPublicLogicLib'
    pod 'NgariDoctorSelectDoctorLib',:path => $module_dir + '/NgariDoctorSelectDoctorLib'
    pod 'NgariDoctorRecipe',:path => $module_dir + '/NgariDoctorRecipe'
    pod 'NgariDoctorAppoint',:path => $module_dir + '/NgariDoctorAppoint'
    pod 'NgariDoctorEaseIM',:path => $module_dir + '/NgariDoctorEaseIM'
    pod 'NgariDoctorMedicalCheck',:path => $module_dir + '/NgariDoctorMedicalExam'
    pod 'NgariDoctorMeeting',:path => $module_dir + '/NgariDoctorMeeting'
    pod 'NDNemoSDK', :path => $module_dir + '/NDNemoSDK'
    pod 'NgariDoctorVideo', :path => $module_dir + '/NgariDoctorVideo'
    pod 'NgariDoctorConsult',:path => $module_dir + '/NgariDoctorConsult'
    pod 'NgariDoctorInfo',:path => $module_dir + '/NgariDoctorInfo'
    pod 'NgariDoctorFollowUp',:path => $module_dir + '/NgariDoctorFollowUp'
    pod 'NgariDoctorCloudClinic', :path => $module_dir + '/NgariDoctorCloudClinic'
    pod 'NgariDoctorChatLive', :path => $module_dir + '/NgariDoctorChatLive'
    pod 'NgariAnalyzes', :path => $module_dir + '/NgariAnalyzes'
    pod 'NgariDoctorGroup', :path => $module_dir + '/NgariDoctorGroup'
    pod 'WinningModuleLibs',:git => 'https://e.coding.net/mobiledoctor/WinningModuleLibs.git'
    pod 'NgariDoctorRevisit', :path => $module_dir + '/NgariDoctorRevisit'
    pod 'NgariDoctorPrescribe', :path => $module_dir + '/NgariDoctorPrescribe'
    pod 'NgariDoctorNurse', :path => $module_dir + '/NgariDoctorNurse'
    pod 'NgariDoctorCA', :subspecs => ['Common', 'XinBuYunCA'] , :path => $module_dir + '/NgariDoctorCA'
#      pod 'WinningModuleLibs', '~> 0.1.9'
    pod 'NgariDoctorEvaluate', :path => $module_dir + '/NgariDoctorEvaluate'
    #pod 'LookinServer', :configurations => ['Debug']
end

target 'easydoctor_appstore' do
    debug_pods
     ngarirnlib_pod
    $target_Arr << 'easydoctor_appstore'
end

post_install do |installer|
    for target in installer.aggregate_targets
        copy_pods_resources_path = "Pods/Target Support Files/#{target.name}/#{target.name}-resources.sh"
        string_to_replace = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"'
        assets_compile_with_app_icon_arguments = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}" --app-icon "${ASSETCATALOG_COMPILER_APPICON_NAME}" --output-partial-info-plist "${BUILD_DIR}/assetcatalog_generated_info.plist"'
        text = File.read(copy_pods_resources_path)
        new_contents = text.gsub(string_to_replace, assets_compile_with_app_icon_arguments)
        File.open(copy_pods_resources_path, "w") {|file| file.puts new_contents }
    end
  
end

## React Native version:
Run `react-native info` in your terminal and copy the results here.
info Fetching system and libraries information...
(node:67634) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 93.78 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_73 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.my project location: /Users/stone/Documents/ngariDoctor/easydoctor
2.package.json : /Users/stone/Documents/ngariDoctor/easydoctor/RNUtils
3.node_modules:  /Users/stone/Documents/ngariDoctor/ngarirnlib/node_modules

## Expected Results
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'react-native-codegen/package.json'
Require stack:
- /Users/stone/Documents/ngariDoctor/easydoctor/Pods/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:98:19)
    at [eval]:1:45
    at Script.runInThisContext (vm.js:134:12)
    at Object.runInThisContext (vm.js:311:38)
    at internal/process/execution.js:77:19
    at [eval]-wrapper:6:22
    at evalScript (internal/process/execution.js:76:60)
    at internal/main/eval_string.js:23:3 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/stone/Documents/ngariDoctor/easydoctor/Pods/[eval]' ]
}
Command /bin/sh failed with exit code 1

## Snack, code example, screenshot, or link to a repository:
package.json
{
  "name": "NgariRNLib",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "17.0.1",
    "react-native": "0.64.2"
  }
}

**Comment by stoneioslife** [comment]
https://github.com/pnpm/pnpm/issues/3325

i resolve by this link
