### ISSUE TITLE
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'collapsable' in shadow node of type: RCTView

### ISSUE THREAD

**Issue by kai0726shanxi** [facebook/react-native#31964]
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'collapsable' in shadow node of type: RCTView
  at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:125)
  at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:161)
  at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:65)
  at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:320)
  at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:251)
  at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:469)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
  at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
  at android.os.Handler.handleCallback(Handler.java:873)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
  at android.os.Looper.loop(Looper.java:201)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
  at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.reflect.InvocationTargetException
  at java.lang.reflect.Method.invoke(Native Method)
  at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:116)
  at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:161)
  at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:65)
  at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:320)
  at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:251)
  at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:469)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
  at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
  at android.os.Handler.handleCallback(Handler.java:873)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
  at android.os.Looper.loop(Looper.java:201)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
  at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.facebook.react.bridge.Dynamic.isNull()' on a null object reference
  at com.facebook.react.uimanager.LayoutShadowNode$MutableYogaValue.setFromDynamic(LayoutShadowNode.java:51)
  at com.facebook.react.uimanager.LayoutShadowNode.setPositionValues(LayoutShadowNode.java:741)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:116)
  at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:161)
  at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:65)
  at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:320)
  at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:251)
  at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:469)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
  at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
  at android.os.Handler.handleCallback(Handler.java:873)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
  at android.os.Looper.loop(Looper.java:201)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
  at java.lang.Thread.run(Thread.java:764)

**Comment by toby-lei** [comment]
same issue,  rn:0.63 react:16.13

**Comment by safaiyeh** [comment]
closing as you did not follow the issue template.

**Comment by hi-zp** [comment]
maybe this repo can help you：https://github.com/hi-zp/rn-multiple-instance-crash

**Comment by hrupesh** [comment]
For someone coming here for a fix for this issue.
It is caused due to multiple instances of shadow thread, the fix is already given for this here https://github.com/facebook/react-native/commit/9d71b166a6c9d9afec7186c6a33aedc6975aa43c

Cheers!
