### ISSUE TITLE
Error when running watchman

### ISSUE THREAD

**Issue by oren** [facebook/react-native#3199]
```
npm start

> PropertyFinder@0.0.1 start /home/oren/projects/react-native/ReactNative-PropertyFinder
> node_modules/react-native/packager/packager.sh

 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /home/oren/projects/react-native/ReactNative-PropertyFinder 


React packager ready.

[12:00:54] <START> Building Dependency Graph
[12:00:54] <START> Crawling File System
 ERROR  A non-recoverable condition has triggered.  Watchman needs your help!
The triggering condition was at timestamp=1443812455: inotify-add-watch(/home/oren/projects/react-native/ReactNative-PropertyFinder/node_modules/react-native/node_modules/module-deps/node_modules/detective/node_modules/escodegen/node_modules/.bin) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl
All requests will continue to fail with this message until you resolve
the underlying problem.  You will find more information on fixing this at
https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch

{"watchmanResponse":{"version":"3.7.0","error":"A non-recoverable condition has triggered.  Watchman needs your help!\nThe triggering condition was at timestamp=1443812455: inotify-add-watch(/home/oren/projects/react-native/ReactNative-PropertyFinder/node_modules/react-native/node_modules/module-deps/node_modules/detective/node_modules/escodegen/node_modules/.bin) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl\nAll requests will continue to fail with this message until you resolve\nthe underlying problem.  You will find more information on fixing this at\nhttps://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch\n"}}
Error: A non-recoverable condition has triggered.  Watchman needs your help!
The triggering condition was at timestamp=1443812455: inotify-add-watch(/home/oren/projects/react-native/ReactNative-PropertyFinder/node_modules/react-native/node_modules/module-deps/node_modules/detective/node_modules/escodegen/node_modules/.bin) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl
All requests will continue to fail with this message until you resolve
the underlying problem.  You will find more information on fixing this at
https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch

    at ChildProcess.<anonymous> (/home/oren/projects/react-native/ReactNative-PropertyFinder/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:202:17)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

```

I tried `echo 524288 | sudo tee -a /proc/sys/fs/inotify/max_user_watches` but it didn't help.
i guess i'll have to spend the time here - https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch
btw, I am on ubuntu, not mac.

if anyone got a quick solution, please comment here.

**Comment by oren** [comment]
posted it on watchman's repo - https://github.com/facebook/watchman/issues/163

**Comment by oren** [comment]
```
echo 256 | sudo tee -a /proc/sys/fs/inotify/max_user_instances
echo 32768 | sudo tee -a /proc/sys/fs/inotify/max_queued_events
echo 65536 | sudo tee -a /proc/sys/fs/inotify/max_user_watches
watchman shutdown-server
```

the last command solved it.

**Comment by Geequlim** [comment]
The same problem.Thanks for your sharing oren!

**Comment by Thirumal-Sakthivel** [comment]
+1. Thanks for your sharing.

**Comment by zaihuishou** [comment]
@oren It is work for me ,Thanks!

**Comment by rahul7977** [comment]
@oren Thanks!

**Comment by Amosiper** [comment]
Many Thanks! @oren

**Comment by karkb** [comment]
Thanks!! work for me :+1:

**Comment by fasibio** [comment]
For Info: I Reboot my Mashine at now it works

**Comment by leonarandres** [comment]
Thanks...!!

**Comment by manish-shrivastava** [comment]
Thanks @oren !

**Comment by Mahluleli-Goodson** [comment]
@oren dude I dont know how to thank you, but you are a genius!

**Comment by fredcampos** [comment]
Thank you @oren.

**Comment by xuanvan229** [comment]
many thanks @oren

**Comment by dennisobel** [comment]
I tried orens way, got rid of the error, but then when i tried runnin the app, i got a scary red screen with  "Could not get BatchedBridge, make sure your bundle is packaged correctly" written on it. Help

**Comment by viviannysdiaz** [comment]
@dennisobel use "react-native start" in the root of your project and then (in other terminal) "react-native run-android" or "run-ios"

**Comment by gustavorozolin** [comment]
Thanks for reply,

I've made 3 new tests and I got this result:

![screenshot_2017-04-28-14-24-43](https://cloud.githubusercontent.com/assets/1047333/25539805/3aa5267a-2c1f-11e7-8b8b-55ce27cf819c.png)
![screenshot_2017-04-28-14-24-32](https://cloud.githubusercontent.com/assets/1047333/25539804/3aa4afec-2c1f-11e7-84a1-06086e24c21f.png)
![screenshot_2017-04-28-14-23-34](https://cloud.githubusercontent.com/assets/1047333/25539803/3aa3c99c-2c1f-11e7-949b-41e58e74f39e.png)

**Comment by Shohan494** [comment]
Thanks @oren

**Comment by AndreiCalazans** [comment]
Thanks @oren

**Comment by AndreiCalazans** [comment]
Does anyone have a permanent solution for this?,
I did use the following command and it works fine, but every time i restart my pc it resets the values.

I have tried editing the maximum queued file itself but i again it always resets.
I am running a Ubuntu 16.10.

**Comment by dark1991** [comment]
Thanks @oren

**Comment by conormuldoon** [comment]
@AndreiCalazans a hack I use is to add `echo 256 | sudo tee -a /proc/sys/fs/inotify/max_user_instances
echo 32768 | sudo tee -a /proc/sys/fs/inotify/max_queued_events
echo 65536 | sudo tee -a /proc/sys/fs/inotify/max_user_watches
` to /etc/rc.local prior to `exit 0`. /etc/rc.local is executed at startup.

**Comment by bugsenpai** [comment]
Thank you @oren and @viviannysdiaz

**Comment by blazevignesh** [comment]
Thanks @oren

**Comment by conormuldoon** [comment]
@AndreiCalazans on Ubuntu 16.04 (not sure about 16.10) `fs.inotify.max_user_watches` in `/etc/sysctl.conf `needs to be changed and then run `watchman shutdown-server && sudo sysctl -p` for a permanent fix.
