### ISSUE TITLE
Unit tests failing with latest react native 0.64.2 & Jest 

### ISSUE THREAD

**Issue by nikhilk1993** [facebook/react-native#32005]
## Description
Upgraded to react native version "0.64.2"
Jest Version: "26.6.3"

getting following error while running tests:

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at Object.get BackHandler [as BackHandler] (node_modules/react-native/index.js:186:12)
      at node_modules/@react-native-community/hooks/lib/useBackHandler.js:15:29
      at Object.invokeGuardedCallbackProd (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11308:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11499:31)
      at flushPassiveEffectsImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14560:11)

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at Object.get Dimensions [as Dimensions] (node_modules/react-native/index.js:208:12)
      at node_modules/@react-native-community/hooks/lib/useDimensions.js:31:29
      at Object.invokeGuardedCallbackProd (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11308:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11499:31)
      at flushPassiveEffectsImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14560:11)
 PASS  src/payments/PaymentDetails/__tests__/PaymentDetails.test.js (36.1 s)

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at Object.get Keyboard [as Keyboard] (node_modules/react-native/index.js:233:12)
      at src/auth/useKeyboard/index.tsx:51:20
      at Object.invokeGuardedCallbackProd (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11308:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11499:31)
      at flushPassiveEffectsImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14560:11)

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      159 |   useEffect(() => {
      160 |     return (): void => {
    > 161 |       if (authenticated) {
          |                    ^
      162 |         resetLockTimeout();
      163 |       }
      164 |     };

      at Object.get AppState [as AppState] (node_modules/react-native/index.js:177:12)
      at src/auth/Lock/useDeviceLock/useDeviceLock.tsx:161:20
      at Object.invokeGuardedCallbackProd (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11308:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11499:31)
      at flushPassiveEffectsImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14560:11)

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at Object.get Linking [as Linking] (node_modules/react-native/index.js:241:12)
      at node_modules/@react-navigation/native/lib/commonjs/useLinking.native.js:186:27
      at Object.invokeGuardedCallbackProd (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11308:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11499:31)
      at flushPassiveEffectsImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14560:11)

## React Native version:
0.64.2

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Expected Results
Jest Tests should pass 

## Snack, code example, screenshot, or link to a repository:
<img width="754" alt="Screenshot 2021-08-11 at 6 28 43 PM" src="https://user-images.githubusercontent.com/8143942/129032790-50d55318-2b64-47f8-bbee-af80612c1312.png">

My jest.config file

```
const ignores = ['/node_modules/', '__mocks__', 'e2e/'];
process.env.TZ = 'GMT';

module.exports = {
  preset: 'react-native',
  transform: { '^.+\\.(ts|tsx|js|jsx)$': './jest-preprocess.js' },
  setupFiles: ['./jest-setup.js', './node_modules/react-native-gesture-handler/jestSetup.js'],
  transformIgnorePatterns: [
    'node_modules/(?!(@?react-native|react-native.*|@?react-navigation.*|@?react-navigation-stack|@?react-native-community/*|@razorpay/blade-old|victory-.*|@universe|@sentry|@razorpay|clevertap-react-native)/)',
  ],
  testPathIgnorePatterns: [...ignores],
  collectCoverageFrom: ['./src/**/*.{ts,tsx,js,jsx}'],
  coverageReporters: ['json', 'html'],
  coverageThreshold: {
    global: {
      branches: 75,
      functions: 75,
      lines: 75,
      statements: 75,
    },
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
};
```

**Comment by matfin** [comment]
I saw quite a few of these too as part of an upgrade to React Native 0.64.2.

A suggested approach that worked for me was to run a cleanup after each test.

To fix it, try doing the following:

```
import {
  // whatever other imports there are
  cleanup
} from '@testing-library/react-native';

describe('<MyComponent />', (): void => {
  afterEach(cleanup);

  it('does something', (): void => {
    // test code goes in here
  });
});
```

**Comment by safaiyeh** [comment]
Closing as not an issue for core React Native
