### ISSUE TITLE
Unable to build React Native 0.65-rc4 from source

### ISSUE THREAD

**Issue by makserge** [facebook/react-native#32011]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
I got an error when tried to build React-native 0.65-rc4 from sources

## React Native version:
System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 3.30 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.1.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.11.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1, 30.0.2, 30.0.3
      System Images: android-23 | Google APIs Intel x86 Atom_64, android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-S | Google APIs ARM 64 v8a, android-S | Google APIs Intel x86 Atom_64
      Android NDK: 21.4.7075529
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.0-rc.3 => 0.65.0-rc.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Created empty RN project using command
npx react-native init AwesomeProject

2. Upgraded project to 065-rc4 using upgrade helper

https://react-native-community.github.io/upgrade-helper/?from=0.64.2&to=0.65.0-rc.4

2. Prepared project for building from source as described here
https://github.com/facebook/react-native/wiki/Building-from-source

3. Got react native sources 

git clone -b 0.65-stable https://github.com/facebook/react-native.git

4. From react native sources folder copy packages/react-native-codegen to node_modules/react-native/packages

5. Tried to build and start app

$npx react-native run-android

## Expected Results

app should build and run on phone

Got error

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 936 file(s) to forward-jetify. Using 16 workers...
info JS server already running.
info Installing the app...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':ReactAndroid'.
> Could not resolve all artifacts for configuration ':ReactAndroid:classpath'.
   > Could not find com.android.tools.build:gradle:4.2.1.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/android/tools/build/gradle/4.2.1/gradle-4.2.1.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :ReactAndroid > project :gradlePlugin-build:gradlePlugin

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':ReactAndroid'.
> Could not resolve all artifacts for configuration ':ReactAndroid:classpath'.
   > Could not find com.android.tools.build:gradle:4.2.1.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/android/tools/build/gradle/4.2.1/gradle-4.2.1.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :ReactAndroid > project :gradlePlugin-build:gradlePlugin

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

    at makeError (/Users/sergey/kamino/AwesomeProject/node_modules/execa/index.js:174:9)
    at /Users/sergey/kamino/AwesomeProject/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/sergey/kamino/AwesomeProject/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:106:5)
    at async Command.handleAction (/Users/sergey/kamino/AwesomeProject/node_modules/@react-native-community/cli/build/index.js:186:9)
info Run CLI with --verbose flag for more details

Tried to cleanup Gradle cache (.gradle) in both android and user home folder without success
Tried to open https://plugins.gradle.org/m2/com/android/tools/build/gradle/4.2.1/gradle-4.2.1.pom and it leads to broken Jcenter repo 
Project doesn't have any Jcenter repo added at all
It seems ReactAndroid have hardcoded Jcenter reference somewhere but search in Github repo for ReactAndroid doesn't return any Jcenter references

Now I stuck on this error and have no ideas how to fix it.

**Comment by makserge** [comment]
Fixed this issue by adding 

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenLocal()
        google()
    }
}

to settings.gradle at top of file
