### ISSUE TITLE
RN 0.65.0 crashes the app

### ISSUE THREAD

**Issue by tapz** [facebook/react-native#32045]
## Description

Our Android app crashes at startup.

```
08-19 11:52:10.686		24442	27119	D	SoLoader	 Loaded: libhermes-inspector.so	
08-19 11:52:10.687		24442	27119	D	SoLoader	 Loaded: libhermes-executor-common-debug.so	
08-19 11:52:10.688		24442	27119	D	SoLoader	 Loaded: libhermes-executor-debug.so	
08-19 11:52:10.689	surfaceflinger	634	-	I	Layer   	 id=295[1] Destroyed 211410f PopupWindow:d8991ec#0	
08-19 11:52:10.689		24442	27119	E	AndroidRuntime	 FATAL EXCEPTION: create_react_context	
08-19 11:52:10.689		24442	27119	E	AndroidRuntime	 Process: my.app, PID: 24442	
08-19 11:52:10.689		24442	27119	E	AndroidRuntime	 java.lang.AbstractMethodError: abstract method "boolean com.facebook.soloader.nativeloader.NativeLoaderDelegate.loadLibrary(java.lang.String, int)"	
08-19 11:52:10.689		24442	27119	E	AndroidRuntime	 	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:51)	
08-19 11:52:10.689		24442	27119	E	AndroidRuntime	 	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)	
08-19 11:52:10.689		24442	27119	E	AndroidRuntime	 	at com.facebook.jni.HybridData.<clinit>(HybridData.java:34)	
08-19 11:52:10.689		24442	27119	E	AndroidRuntime	 	at com.facebook.hermes.reactexecutor.HermesExecutor.initHybrid(Native Method)	
08-19 11:52:10.689		24442	27119	E	AndroidRuntime	 	at com.facebook.hermes.reactexecutor.HermesExecutor.<init>(HermesExecutor.java:31)	
08-19 11:52:10.689		24442	27119	E	AndroidRuntime	 	at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:29)	
08-19 11:52:10.689		24442	27119	E	AndroidRuntime	 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1054)	
08-19 11:52:10.689		24442	27119	E	AndroidRuntime	 	at java.lang.Thread.run(Thread.java:923)	
08-19 11:52:10.692	system_server	1009	27120	I	DropBoxManagerService	 add tag=data_app_crash isTagEnabled=true flags=0x2	
08-19 11:52:10.692	system_server	1009	6013	D	Debug   	 low && ship && 3rdparty app crash, do not dump	
08-19 11:52:10.692	system_server	1009	6013	W	ActivityManager	 crash : my.app,10323	
08-19 11:52:10.693	system_server	1009	6013	W	ContextImpl	 Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1162 com.android.server.am.AppErrors.crashApplicationInner:579 com.android.server.am.AppErrors.crashApplication:443 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:12323 com.android.server.am.ActivityManagerService.handleApplicationCrash:12258 	
08-19 11:52:10.693	system_server	1009	6013	W	ActivityTaskManager	   Force finishing activity my.app/.MainActivity
```	

## React Native version:

```
System:
    OS: macOS 11.5
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 94.95 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/opt/node@14/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 25, 26, 27, 28, 29, 30
      Build Tools: 29.0.3, 30.0.2
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.0 => 0.65.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Build and start the app in Android

## Expected Results

The app should start without crashing.

**Comment by kabus202** [comment]
Same here, did you manage to solve it @Isaacmeedinaa ?

**Comment by byudaniel** [comment]
@tapz I'm having this same issue, how were you able to solve it?

**Comment by nolife08021** [comment]
Facing same issue with version 0.66.3

**Comment by javi10823** [comment]
hey Facing same issue with version 0.66.4 did you manage to solve it @Isaacmeedinaa ?

**Comment by franciscofernandez0** [comment]
Same problem here after upgrading from RN 64 to 66.4 (also updated JDK to 11)

Any ideas?

**Comment by DylanMay** [comment]
same problem with version 0.66.1

**Comment by wyqhywjj601** [comment]
Hello, what was the fix?

**Comment by lakhman** [comment]
Has a slightly different error upgrading to 0.66.4, fixed it by upgrading soloader:soloader in `android/app/build.gradle`

```
force "com.facebook.soloader:soloader:0.8.2"  // Caused crash/whitescreen on boot
force "com.facebook.soloader:soloader:0.9.0+" // Fixed issue and app boots
```

**Comment by wyqhywjj601** [comment]
> 升级到 0.66.4 有一个稍微不同的错误，通过升级 soloader:soloader 来修复它`android/app/build.gradle`
> 
> ```
> force "com.facebook.soloader:soloader:0.8.2"  // Caused crash/whitescreen on boot
> force "com.facebook.soloader:soloader:0.9.0+" // Fixed issue and app boots
> ```

Saved me!, Thanks!

**Comment by LevinhsangSSKPIs** [comment]
> Had a slightly different error upgrading to 0.66.4, fixed it by upgrading soloader:soloader in `android/app/build.gradle`
> 
> ```
> force "com.facebook.soloader:soloader:0.8.2"  // Caused crash/whitescreen on boot
> force "com.facebook.soloader:soloader:0.9.0+" // Fixed issue and app boots
> ```

Thanks, it work for me.
