### ISSUE TITLE
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/widget/HorizontalScrollView;->mScroller:Landroid/widget/OverScroller;

### ISSUE THREAD

**Issue by Levin-nik** [facebook/react-native#32065]
Hi guys,

I'm getting warning for in Google Play Console.

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/widget/HorizontalScrollView;->mScroller:Landroid/widget/OverScroller;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:416)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at com.facebook.react.views.scroll.ReactHorizontalScrollView.getOverScrollerFromParent(ReactHorizontalScrollView.java:106)
	at com.facebook.react.views.scroll.ReactHorizontalScrollView.<init>(ReactHorizontalScrollView.java:96)
	at com.facebook.react.views.scroll.ReactHorizontalScrollViewManager.createViewInstance(ReactHorizontalScrollViewManager.java:65)
	at com.facebook.react.views.scroll.ReactHorizontalScrollViewManager.createViewInstance(ReactHorizontalScrollViewManager.java:38)
	at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:83)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:261)
	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:186)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1112)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1083)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:727)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

How do i get rid of this error?

**Comment by smoothdvd** [comment]
Same here, React native version: 0.66.3.

**Comment by hsib19** [comment]
+1

**Comment by mckubisiak** [comment]
Can you confirm this is still an issue?
