### ISSUE TITLE
Failed to start the app. Error: spawnSync adb ENOENT

### ISSUE THREAD

**Issue by LumiProj** [facebook/react-native#32116]
I am using Mac latest version.

##  On Android I am getting this error.

/bin/sh: adb: command not found
info Launching emulator...
error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.
info Installing the app...
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :app:installDebug
Installing APK 'app-debug.apk' on 'SM-A022F - 10' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL in 25s
31 actionable tasks: 2 executed, 29 up-to-date
info Connecting to the development server...
warn Failed to connect to development server using "adb reverse": spawnSync adb ENOENT
info Starting the app...
error Failed to start the app.
Error: spawnSync adb ENOENT
    at Object.spawnSync (internal/child_process.js:1074:20)
    at Object.spawnSync (child_process.js:746:24)
    at Function.module.exports.sync (/Users/impro/Desktop/testapp/MyApp/node_modules/execa/index.js:334:30)
    at tryLaunchAppOnDevice (/Users/impro/Desktop/testapp/MyApp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/tryLaunchAppOnDevice.js:58:22)
    at /Users/impro/Desktop/testapp/MyApp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:116:39
    at Array.forEach (<anonymous>)
    at runOnAllDevices (/Users/impro/Desktop/testapp/MyApp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:114:48)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Command.handleAction (/Users/impro/Desktop/testapp/MyApp/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:186:9)
info Run CLI with --verbose flag for more details.
impro@atifs-mbp myapp % 

## React Native version:
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Apple M1
    Memory: 17.84 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.14 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
## Steps To Reproduce
Getting error when I debug app using React Cli
npx react-native run-android    
 
## Expected Results
App run in device in debug mode.

**Comment by nguyen95** [comment]
me too
