### ISSUE TITLE
Fetching large json data results in OutOfMemoryError

### ISSUE THREAD

**Issue by curtisy1** [facebook/react-native#32134]
## Description
Using `fetch` to get several Megabytes (currently happens for me at around 80Mb) of JSON data causes Android to panic and throw an OutOfMemoryError. This is due to the fact that the whole response is being read as bytes, quickly filling up the heap.

Stacktrace:
```
09-01 21:32:21.035  5480  5555 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 98836368 byte allocation with 25165824 free bytes and 88MB until OOM, target footprint 133385952, growth limit 201326592
09-01 21:32:21.035  5480  5555 E AndroidRuntime: 	at okio.Buffer.readByteArray(Buffer.kt:1429)
09-01 21:32:21.035  5480  5555 E AndroidRuntime: 	at okio.Buffer.readByteArray(Buffer.kt:1424)
09-01 21:32:21.035  5480  5555 E AndroidRuntime: 	at okio.RealBufferedSource.readByteArray(RealBufferedSource.kt:238)
09-01 21:32:21.035  5480  5555 E AndroidRuntime: 	at okhttp3.ResponseBody.bytes(ResponseBody.kt:124)
09-01 21:32:21.035  5480  5555 E AndroidRuntime: 	at com.facebook.react.modules.blob.BlobModule$4.toResponseData(BlobModule.java:134)
09-01 21:32:21.035  5480  5555 E AndroidRuntime: 	at com.facebook.react.modules.network.NetworkingModule$2.onResponse(NetworkingModule.java:512)
09-01 21:32:21.035  5480  5555 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
09-01 21:32:21.035  5480  5555 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-01 21:32:21.035  5480  5555 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-01 21:32:21.035  5480  5555 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
```

## React Native version:
```
System:
    OS: Linux 5.13 Solus 4.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 1.39 GB / 15.52 GB
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 14.17.5 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.14 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_302-solus - /usr/lib64/openjdk-8/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
I created a [test repository](https://github.com/curtisy1/ReactNativeFetchRepro) that shows the aforementioned behaviour. It also includes a 100Mb JSON file for testing, that you can serve locally or access via [GitHub directly](https://github.com/curtisy1/ReactNativeFetchRepro/raw/master/data.json).
Steps are as follows

1. Tap on the load data button
2. Wait for the app to crash

## Expected Results
Getting an out of memory error shouldn't really happen with this size of data in my opinion. Sure 100Mb sounds a lot at first, but in enterprise-grade apps this is probably a common scenario. In any case I think there should be a possibility to dynamically switch to streaming the response since okhttp offers [bytestream](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-response-body/byte-stream/) and charstream as well. I'm not that well versed in Java but it would probably help reduce all of the 150Mb landing on the heap at once?

## Snack, code example, screenshot, or link to a repository:
https://github.com/curtisy1/ReactNativeFetchRepro

**Comment by 452MJ** [comment]
Try add `android:largeHeap` label to your AndroidManifest.xml.

```diff
<application
   ...
+    android:largeHeap="true"
   ...
```/>

**Comment by curtisy1** [comment]
Thanks for trying to help @452MJ!

I am aware of that option but that's pretty much my last resort as I think there must be another way. 

Simply put, there's probably thousands of apps - and among those a few RN apps as well - on the market fetching something (once, hence not directly streaming) with a size over 100Mb and I highly doubt they all have `android:largeHeap` set to true. Not to mention Google also does not [directly recommend it](https://developer.android.com/guide/topics/manifest/application-element) as a fix to increasing performance or OOM errors. 

There's also a very informative [StackOverflow question](https://stackoverflow.com/questions/27396892/what-are-advantages-of-setting-largeheap-to-true) with the general answer being "do not use if you absolutely have to"

**Comment by 452MJ** [comment]
I think this is a must for RN apps. Some of the apps I worked on in the past sometimes caused OOM crash due to downloading web images. Unlike native projects whose memory footprint rarely reaches 100MB, it is common for RN projects to hit 200-300MB. This is also a weak term in RN. So I set largeHeap to true for each project.

Maybe you can try run on `Hermes` jsengine.😬

**Comment by curtisy1** [comment]
>Unlike native projects whose memory footprint rarely reaches 100MB, it is common for RN projects to hit 200-300MB

I completely agree with this one. But most of it is probably the JS overhead and not any native implementation. In this case, however, the issue is that [the bytes are accessed directly](https://github.com/facebook/react-native/blob/main/ReactAndroid/src/main/java/com/facebook/react/modules/blob/BlobModule.java#L134), so we get the total size of our response added to our heap. OkHttp actually [warns about this](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-response-body/bytes/#bytes) and advises streaming the response. I'm not experienced enough in native Android development to tell if this would be applicable in this case, but it sounds better than having an OOM or a large heap that might cause other side effects.

That's actually why I'm interested in what the react-native team has to say about this, because setting largeHeap seems like some workaround for a bigger issue to me

**Comment by 452MJ** [comment]
Maybe you can try  using `axios` to replace `fetch`

**Comment by curtisy1** [comment]
This probably wouldn't change anything as both fetch and axios work by sending XMLHttpRequests under the hood, which then get converted to a native call to OkHttp, causing the behavior above. The only thing it would probably change is that the JSON parsing would be up to the JS side of things. But if the request in itself fails (or more accurately, the initial response conversion on Android's native side), I won't even get to parsing any JSON.

**Comment by curtisy1** [comment]
Definitely not stale. But if I have the freedom to label it, I'll gladly add it to the backlog 😉

**Comment by TommysG** [comment]
Exactly the same problem here. I have offline-first architecture in my app and i need to fetch some big data on startup. @curtisy1  did you find any solution to this problem?

**Comment by curtisy1** [comment]
@TommysG We didn't find any solution to this. What we tried doing was reduce the size of our responses and optimize them in a way that this issue is more unlikely to happen for our use case. That is more of a bandaid solution, however and I'm fairly certain we will easily reach that cap in production where larger data is quite common

**Comment by TommysG** [comment]
@curtisy1 I found this library [react-native-fetch-api](https://github.com/react-native-community/fetch). It's overriding the default implementation of react native's fetch and let you stream the data. But I don't know how to check, if the data I received is a valid JSON and how to parse it in chunks. Also I think this will be very slow with large data.

Lastly, you said that you have this problem working with 80mb or maybe 100mb of response body, but I have this problem working with 21mb response.

**Comment by curtisy1** [comment]
Seems like we are now also facing this in production.

@shergin Seeing as you're not on the React Native Core team anymore but still the codeowner according to the codeowners file. Do you know who's the right person to mention here, so this issue gets some love maybe?

**Comment by curtisy1** [comment]
Very sorry to necro-bump this but it's been two years with the only reply being from another react-native user trying to help and one having the same issue. Since then, the CODEOWNERS got removed as well, for staleness like dear stale bot once tried to do with this issue (until... well it was removed as well).

To clarify, this is probably a fairly niche issue but I don't really consider leaving an issue alone for two years a good thing.
In my attempt to get _someone_ to actually look at this,  I, as a user don't have any other choice but randomly bump this and ping people I think might know how to help.

For future reference, maybe you folks could implement some kind of policy on what "Triage" actually means for you? When I filter for the tag, I get 46 pages with almost 1.3k issues back, the oldest being from 2020 (that's ~81% of all open issues!). I doubt any issue would be triaged this long considering you have tags for pretty much anything.

And before you ask, yes, I know this is a community project but it still runs under the Facebook/Meta umbrella so I would expect at least a bit of dedication towards issues opened by the community. Especially when I take the time to catch a stack trace and fill out the issue template.

Microsoft does a lot better than you in that regard, so please step up your game and actually respond to issues  :smile:  (fwiw I'd also accept a won't fix with a detailed explanation and way to move forward).

Ping @cortinico because you accepted the CODEOWNERS removal, so you're the only straw I can hold onto for this year

**Comment by cortinico** [comment]
Hey @curtisy1 
I can mention that our team looks at new issues every day. I personally go over most of them on a daily basis. The reality is that our team is just so small, and we can't answer to everyone, and also we can't fix every bug. We try to prioritize those that have most upvotes or are affecting the highest number of people.

Issues that gets picked up by the community and receive a PR, are the ones that most likely to get fixed and end in a release.

As for your specific issue, the problem you're having is that your response gets processed by the `BlobModule`, which is loading the full response in memory. I guess the problem is that you should not be using the `BlobModule` at for this specific request as it should be of type `json`. I'm unsure why this is happening and would need further investigation.

**Comment by tkserver** [comment]
Same issue for me. I'm reading large JSON files up to 150mb.  On ios all works fine. I can load the entire JSON file and work with it. On anrdoid, anything over 15-20MB produces out of memory errors. Also looking to resolve this!

**Comment by devpedrofurquim** [comment]
Does anyone knows how to solve this? I'm still having the same problem when fetching a large response from the backend. It breaks on Out of Memory. Im using axios to do the request

`
const response = await api.get(
      "/endPoint/" + group + "?date=" + date,
      {
        headers: {
          Accept: "application/json",
          "XX-TOKEN-XX-TK-HH-HEADER": token,
        },
        responseType: "json",
      },
    );

    if (response.status === 200) {
      console.log("Fetch LastPosition Status", response.status);
      return response.data.results as IPositions[];
`

It breaks when I fetch an response around 100 to 200MB.

**Comment by tkserver** [comment]
> Does anyone knows how to solve this? I'm still having the same problem when fetching a large response from the backend. It breaks on Out of Memory. Im using axios to do the request
> 
> ` const response = await api.get( "/endPoint/" + group + "?date=" + date, { headers: { Accept: "application/json", "XX-TOKEN-XX-TK-HH-HEADER": token, }, responseType: "json", }, );
> 
> ```
> if (response.status === 200) {
>   console.log("Fetch LastPosition Status", response.status);
>   return response.data.results as IPositions[];
> ```
> 
> `
> 
> It breaks when I fetch an response around 100 to 200MB.

I ended up having to create native modules to get around the OOM errors. It was very painful.

**Comment by Alliance-MikeCheung** [comment]
Having the same issue here for <= android API 34 [seems ok in API 35]

<= API 34, when fetch-> can fetch -> but run result.json() -> OOM
API 35, can run result.json() -> JSON OBJECT

No luck - add android:largeHeap="true" to AndroidManifest.xml

Somebody help?

**Comment by PwGawzynski** [comment]
Same issue here — fetching a JSON response (about 90 MB) results in massive memory usage, and without android:largeHeap="true", the app crashes.

I’m using this code in a clean new app created with npx create-expo-app@latest NAME.

```
useEffect(() => {
    (async () => {
      const data = '{"datefrom": "T2025-03-20 12:18", "dateto": "T2025-06-20 12:33"}';
      const response = await axios.post('URL', data,{
        headers: {
          Cookie: `SOME_SESSON_COOKIE`,
        },
        withCredentials: false,
      } );
      console.log('RESPONSE', response.data?.[0]);
    })();
  }, []);
```

Memory usage caused:

<img width="677" alt="Image" src="https://github.com/user-attachments/assets/bb2d2af1-0e49-41f3-8be5-b0af08757d90" />

**Comment by devpedrofurquim** [comment]
Which app did you used to check to the RAM usage of the app? I'd like to try it out on my apps too @PwGawzynski

**Comment by PwGawzynski** [comment]
> on

Flashlight - https://flashlight.dev

**Comment by fardad-dev** [comment]
An empty RN App grows up memory usage without any reason in RN 0.85, 
I created a simple component in a screen, after unmounting it, the memory doesn't release.
Does anyone have this issue?
