### ISSUE TITLE
`EISDIR: illegal operation on a directory` error on React Native debug

### ISSUE THREAD

**Issue by ccarcaci** [facebook/react-native#32234]
## Description

Hi, I've a problem with embedded Metro bundler dependency when I launch the debug in a completely fresh React Native application.

## React Native version:
```
$ react-native info
info Fetching system and libraries information...
System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz
    Memory: 4.46 GB / 15.52 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    Yarn: Not Found
    npm: 7.22.0 - ~/.nvm/versions/node/v14.17.5/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 15.0.1 - /home/ccarcaci/jdks/jdk-15.0.1/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Expo version:

```
$ expo --version
4.11.0
```

## Steps To Reproduce

1. I've started a fresh project following the guide [Environment Setup with Expo](https://reactnative.dev/docs/environment-setup).
2. My project sources are [here](https://github.com/ccarcaci/eisdir-error-investigation).
3. I've created a new Android AVD.
4. Then I launched the application using `$ npm run android` command.
5. Application is running (see screenshot below).
6. No errors in the console log (see related console log section below).
7. When I open the debugger I get an EISDIR error in Expo console log and no debugger worker is shown (see related console log section below).
8. Browser debugger is displaying some mapping problems (see screenshot below).

## Expected Results

I'd like to be able to debug my code.

### Application is running:

![Screenshot from 2021-09-19 10-48-56](https://user-images.githubusercontent.com/7973726/133922773-8f30db9a-3553-4702-9bcf-2fd54c364263.png)

### No errors at first:
```
$ npm run android

> android
> expo start --android

Starting project at /home/ccarcaci/git/EisdirErrorInvestigation
Developer tools running on http://localhost:19002
Opening developer tools in the browser...
Starting Metro Bundler
› Opening exp://192.168.1.53:19000 on Pixel

  (QR Code)

 › Waiting on exp://192.168.1.53:19000
 › Scan the QR code above with Expo Go (Android) or the Camera app (iOS)

 › Press a │ open Android
 › Press w │ open web

 › Press r │ reload app
 › Press m │ toggle menu
 › Press d │ show developer tools
 › shift+d │ toggle auto opening developer tools on startup (enabled)

 › Press ? │ show all commands

Logs for your project will appear below. Press Ctrl+C to exit.
info Launching Dev Tools...
Android Bundling complete 29039ms
Android Running app on sdk_gphone64_x86_64(image)
```

### EISDIR error is displayed:

```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:614:3)
    at tryReadSync (fs.js:383:20)
    at Object.readFileSync (fs.js:420:19)
    at UnableToResolveError.buildCodeFrameMessage (/home/ccarcaci/git/EisdirErrorInvestigation/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:304:17)
    at new UnableToResolveError (/home/ccarcaci/git/EisdirErrorInvestigation/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:290:35)
    at ModuleResolver.resolveDependency (/home/ccarcaci/git/EisdirErrorInvestigation/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:168:15)
    at DependencyGraph.resolveDependency (/home/ccarcaci/git/EisdirErrorInvestigation/node_modules/metro/src/node-haste/DependencyGraph.js:353:43)
    at /home/ccarcaci/git/EisdirErrorInvestigation/node_modules/metro/src/lib/transformHelpers.js:271:42
    at Server.<anonymous> (/home/ccarcaci/git/EisdirErrorInvestigation/node_modules/metro/src/Server.js:842:41)
    at Generator.next (<anonymous>)
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:614:3)
    at tryReadSync (fs.js:383:20)
    at Object.readFileSync (fs.js:420:19)
    at UnableToResolveError.buildCodeFrameMessage (/home/ccarcaci/git/EisdirErrorInvestigation/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:304:17)
    at new UnableToResolveError (/home/ccarcaci/git/EisdirErrorInvestigation/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:290:35)
    at ModuleResolver.resolveDependency (/home/ccarcaci/git/EisdirErrorInvestigation/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:168:15)
    at DependencyGraph.resolveDependency (/home/ccarcaci/git/EisdirErrorInvestigation/node_modules/metro/src/node-haste/DependencyGraph.js:353:43)
    at /home/ccarcaci/git/EisdirErrorInvestigation/node_modules/metro/src/lib/transformHelpers.js:271:42
    at Server.<anonymous> (/home/ccarcaci/git/EisdirErrorInvestigation/node_modules/metro/src/Server.js:842:41)
    at Generator.next (<anonymous>)
```

### Browser debugger screen:

![Screenshot from 2021-09-19 10-53-45](https://user-images.githubusercontent.com/7973726/133922784-4395cfad-9282-4683-b43b-0d773124f37f.png)

## Further investigations done on my own:

I've added the `console.log(this.originModulePath);` call before [this line](https://github.com/facebook/metro/blob/v0.59.0/packages/metro/src/node-haste/DependencyGraph/ModuleResolution.js#L317) in my dependencies. The Expo console output is:

```
/home/ccarcaci/git/EisdirErrorInvestigation/.
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:614:3)
    at tryReadSync (fs.js:383:20)
    at Object.readFileSync (fs.js:420:19)
    at UnableToResolveError.buildCodeFrameMessage (/home/ccarcaci/git/EisdirErrorInvestigation/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:305:17)
    at new UnableToResolveError (/home/ccarcaci/git/EisdirErrorInvestigation/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:290:35)
    at ModuleResolver.resolveDependency (/home/ccarcaci/git/EisdirErrorInvestigation/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:168:15)
    at DependencyGraph.resolveDependency (/home/ccarcaci/git/EisdirErrorInvestigation/node_modules/metro/src/node-haste/DependencyGraph.js:353:43)
    at /home/ccarcaci/git/EisdirErrorInvestigation/node_modules/metro/src/lib/transformHelpers.js:271:42
    at /home/ccarcaci/git/EisdirErrorInvestigation/node_modules/metro/src/Server.js:1097:37
    at Generator.next (<anonymous>)
```

It seems that Metro is unable to package correctly the debugger worker .js files.

I don't know how to proceed to enable debugging.

**Comment by askumar1** [comment]
Unsubcribe
