### ISSUE TITLE
Error:  TypeError: (0 , _native.createNavigatorFactory) is not a function

### ISSUE THREAD

**Issue by WRsraina** [facebook/react-native#32254]
![Screenshot 2021-09-22 at 18 30 42](https://user-images.githubusercontent.com/75982948/134392775-749eea72-1110-4188-ab6a-23ac52e512a2.png)
## React Native version:
Run `react-native info` in your terminal and copy the results here.

`"react-native": "0.64.2",`

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. When I run my test using `yarn jest filepath`
2. I get the below error 
```$ /Users/sraina/Desktop/hybrid-rn-app/node_modules/.bin/jest src/screens/expressCheckout/ExpressCheckoutScreen.test
 FAIL  src/screens/expressCheckout/ExpressCheckoutScreen.test.tsx
  ● Test suite failed to run

    TypeError: (0 , _native.createNavigatorFactory) is not a function

      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/navigators/createStackNavigator.tsx:96:16)
      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/index.tsx:9:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.11 s
Ran all test suites matching /src\/screens\/expressCheckout\/ExpressCheckoutScreen.test/i.
error Command failed with exit code 1.
```

## Expected Results
I would like to see if test failed or passed.

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by WRsraina** [comment]
Solution: 
https://stackoverflow.com/questions/66955048/typeerror-0-native-createnavigatorfactory-is-not-a-function/69297952#69297952
