### ISSUE TITLE
APK doesn't build: Unexpected token name

### ISSUE THREAD

**Issue by IDjinn** [facebook/react-native#32339]
## Description
I'm trying do build my app but I can't. When it try build throws error ` Unexpected token name ┬½_000┬╗, expected punc ┬½,┬╗` and build fails. I will share all errors but the problem react-native doesn't building with charset UTF-8 because all these errors throws in some line with special characters. 

Full Error:
```

Error: Unexpected token name ┬½_000┬╗, expected punc ┬½,┬╗ in file src\views\login\register\index.js at 352:28
    at minifyCode (C:\Users\SomeName\Desktop\myApp\node_modules\metro-transform-worker\src\index.js:99:13)
    at transformJS (C:\Users\SomeName\Desktop\myApp\node_modules\metro-transform-worker\src\index.js:317:28)
    at transformJSWithBabel (C:\Users\SomeName\Desktop\myApp\node_modules\metro-transform-worker\src\index.js:408:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.transform (C:\Users\SomeName\Desktop\myApp\node_modules\metro-transform-worker\src\index.js:569:12)
info Run CLI with --verbose flag for more details.

> Task :app:bundleReleaseJsAndAssets FAILED
```

Error throws here
```js
<View style={styles.ultraShortInput}>
  /*  ---> this line */   <FloatingLabelInput
                                label={'Número'}
                                value={this.state.address.number}
                                keyboardType={'number-pad'}
                                onChangeText={value => this.setState({ 'address.number': value })}
                            />
</View>
```

## React Native version:
PS: I have tested two versions of same code, that explains the difference between info's
```
System:
    OS: Windows 10 10.0.21996
    CPU: (4) x64 Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
    Memory: 1.51 GB / 7.89 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found  **************** Using Android SDK 28, 29 and 30
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7486908
    Visual Studio: 16.10.31424.327 (Visual Studio Community 2019), 16.10.31424.327 (Visual Studio Professional 2019)
  Languages:
    Java: 12.0.2
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2
    react-native: ^0.65.1 => 0.65.1
    react-native-windows: Not Found
  npmPackages:  **************** other version of same code, but with rn updated
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2
    react-native: ^0.65.1 => 0.66.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

``` 

## Steps To Reproduce
I don't know what is exactly what's wrong but if it's utf-8 problem I think try build any APK with some non-ordinary characters will not work

## Expected Results
I expect solve this so I can build my own app. I can do tests with debug mode but I need release this app as well.

**Comment by ruziev-dev** [comment]
@IDjinn 
Did you solve the problem?
I have the same error.

```
error src\api.ts: Unexpected token name ┬л_000┬╗, expected punc ┬л,┬╗ in file src\api.ts at 33:15.
Error: Unexpected token name ┬л_000┬╗, expected punc ┬л,┬╗ in file src\api.ts at 33:15
```

```

const checkNetworkConnection = async () => {
	const netState = await NetInfo.fetch()
	if (!netState.isConnected) {
		throw new Error(I18n.t('device_isnot_connected_to_network'))
	}
	return false
}

type IMaximoAPI = {		// <- this row
	authData: TAuthData
	serverURL: string
}

export class MaximoAPI {
	private authData: TAuthData
	private BASE_URL: string
	private cookie: string = ''
	constructor(params: IMaximoAPI) {
		this.authData = params.authData
		this.BASE_URL = params.serverURL
	}
// some methods
}
```

My code at this line doent have any specific symbols, and I don't know how to fix it
