### ISSUE TITLE
Android app started crashing in last few hours on production | Fatal Exception: com.facebook.react.common.c

### ISSUE THREAD

**Issue by shrmaky** [facebook/react-native#32374]
## Description
We deployed our application last week on production and there have been absolutely no deployment/changes. However, we saw an immediate spike on android app crashing in last 

## React Native version:
RN Version - `0.65`

## Fatal Error:
```
Fatal Exception: com.facebook.react.common.c: TypeError: Cannot read property 'then' of undefined, js engine: hermes, stack:
startHeadlessTask@355:3233
value@59:3492
anonymous@59:747
value@59:2538
value@59:719

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:246)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:923)

```
## Not Fatal Error

```
Non-fatal Exception: io.invertase.firebase.crashlytics.b: Cannot read property 'then' of undefined
       at .startHeadlessTask(.java)
       at .apply(.java)
       at .value(.java)
       at .anonymous(.java)
       at .value(.java)
       at .value(.java)
```

## Below are the images for Firebase Crashlytics:
![image](https://user-images.githubusercontent.com/39021707/136713417-e8b54793-180f-4269-8459-c3c334ac872a.png)

![image](https://user-images.githubusercontent.com/39021707/136713535-a93b46eb-9545-45db-b519-d7d7572f0298.png)

## As there have been no deployment and these crashes appeared abruptly, to resolve this, have been performing certain actions
- Upgrading RN version to `0.66`
- Upgrading RN Firebase packages from ''12.0.0" to "12.9.1"

If anyone have better idea for this problem, feel free to suggest.

Thanks all.

**Comment by ydv0121** [comment]
@shrmaky
same issue i am facing it in production version when notification show up when app is in background mode.
using notifee for notification plugin.

```
"@react-native-firebase/app": "^12.7.1",
"@react-native-firebase/crashlytics": "^12.8.0",
"@react-native-firebase/messaging": "^13.0.1",
"react-native": "0.64.2"
```

any idea how to resolve it without upgrading react-native version?
