### ISSUE TITLE
Error upgrading 0.64 -> 0.66 CocoaPods could not find compatible versions for pod "RCT-Folly"

### ISSUE THREAD

**Issue by 1mike12** [facebook/react-native#32423]
## Description
trying to upgrade to latest version to have access to `RippleConfig.foreground` in 0.66 but running into this issue on the ios side

## React Native version:
```
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 255.71 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.3 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/opt/node@14/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242-release - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.1 => 0.66.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. have 0.64 ejected project
2. try to update to latest 0.66
3. run `npx react-native upgrade`

## Expected Results
successful upgrade

## Snack, code example, screenshot, or link to a repository:
```
Auto-linking React Native modules for target `mobile`: RNCAsyncStorage, RNCMaskedView, RNGestureHandler, RNKeychain, RNScreens, RNVectorIcons, react-native-image-picker, and react-native-safe-area-context
Analyzing dependencies
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
[!] CocoaPods could not find compatible versions for pod "RCT-Folly":
  In snapshot (Podfile.lock):
    RCT-Folly (from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`)

  In Podfile:
    FBReactNativeSpec (from `../node_modules/react-native/React/FBReactNativeSpec`) was resolved to 0.66.1, which depends on
      RCT-Folly (= 2021.06.28.00-v2)

    RCT-Folly (from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

    at makeError (/Users/x/go/y/mobile/node_modules/execa/index.js:174:9)
    at /Users/x/go/y/mobile/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async installDeps (/Users/x/go/y/mobile/node_modules/@react-native-community/cli/build/commands/upgrade/upgrade.js:208:3)
    at async Object.upgrade [as func] (/Users/x/go/y/mobile/node_modules/@react-native-community/cli/build/commands/upgrade/upgrade.js:346:9)
    at async Command.handleAction (/Users/x/go/y/mobile/node_modules/@react-native-community/cli/build/index.js:186:9)
info Run CLI with --verbose flag for more details.
```

**Comment by ammarahm-ed** [comment]
Try running `pod update && pod install` in ios folder  to fix this issue.

**Comment by kennyledet** [comment]
Removing `Podfile.lock` and running `pod deintegrate` helped

**Comment by mojvan** [comment]
[!] CocoaPods could not find compatible versions for pod "React-RCTAnimation":
  In Podfile:
    React-RCTAnimation (from `../node_modules/react-native/Libraries/NativeAnimation`)

Specs satisfying the `React-RCTAnimation (from `../node_modules/react-native/Libraries/NativeAnimation`)` dependency were found, but they required a higher minimum deployment target.

In my case I deleted pods folder and podfile.lock file also updated the ios version from 11.0 to 14.0 in podfile and it worked for me.
