### ISSUE TITLE
Babel/Strict error - 2048 Example

### ISSUE THREAD

**Issue by AlexHandy1** [facebook/react-native#3243]
Cloned repo, successfully npm installed, go to run example from opening Xcode (have run other app set-ups fine included Movies tutorial) and get below error.
Also fails on same error when run ```` npm start ````
Tried ````brew update```` and commenting out 'strict mode' but no luck.
Running on a MacBook Pro Yosemite (10.10.5)

````
/Users/alexanderhandy/Documents/react-native/packager/transformer.js:13
const babel = require('babel-core');
^^^^^
SyntaxError: Use of const in strict mode.
````

**Comment by towkaynew** [comment]
Same issue here!

**Comment by ide** [comment]
What version of Node are you using? (Make sure it's at least 4.)

**Comment by TowkayNew** [comment]
Fixed after updating Node to the latest version! Thank you @ide ! :smile:

**Comment by mikearmstrong001** [comment]
@TowkayNew are you ok to close

**Comment by TowkayNew** [comment]
This issue is opened by @AlexHandy1 , think we will wait for him to reply before we close this issue! Cheers!

**Comment by AlexHandy1** [comment]
@TowkayNew @mikearmstrong001 - worked for me too, thanks for responding so quickly!

**Comment by AlexHandy1** [comment]
and @ide, thanks

**Comment by YoungElPaso** [comment]
Just an FYI, for Linux, I had to update nodejs via *nvm* to 4.1.1, although my normal version of nodejs (installed via official package) was 4.1.2

Something to note as I guess react is using the nvm version.

**Comment by clocksmith** [comment]
I am getting the same issue on OSX Yosemite 10.10.5 . I have updated node:

$ node -v
v0.12.7

Partial stack trace:

/Users/me/git/multiply/Multiply/node_modules/react-native/packager/transformer.js:13
const babel = require('babel-core');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at process.<anonymous> (/Users/me/git/multiply/Multiply/node_modules/react-native/node_modules/worker-farm/lib/child/index.js:45:34)
    at process.emit (events.js:110:17)
    at handleMessage (child_process.js:324:10)
.
.
.
See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EMFILE, too many open files '/Users/me/.babel.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at process.save (/Users/me/git/multiply/Multiply/node_modules/react-native/node_modules/babel-core/lib/api/register/cache.js:35:19)
    at process.emit (events.js:107:17)
    at process.exit (node.js:600:17)
    at process.<anonymous> (/Users/me/git/multiply/Multiply/node_modules/react-native/packager/packager.js:149:11)
    at process.emit (events.js:107:17)
    at process._fatalException (node.js:236:26)
    at Walker.<anonymous> (/Users/me/git/multiply/Multiply/node_modules/react-native/node_modules/sane/src/node_watcher.js:351:12)
Process terminated. Press <enter> to close the window

**Comment by ide** [comment]
@clocksmith Node 0.12.7 is not supported. Please upgrade to Node 4.

**Comment by sriraman** [comment]
I'm also getting the same error in Yosemite 10.10.5 after update it to 4.x also.

    $ node -v
    v4.2.1

Stack Trace :

    ..........
    
    node_modules/react-native/packager/transformer.js:13
    const babel = require('babel-core');
    ^^^^^
    SyntaxError: Use of const in strict mode.
        at exports.runInThisContext (vm.js:73:16)
        at Module._compile (module.js:443:25)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at process.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/witworks/react-native/myFirstHelloWorld/node_modules/react-native/node_modules/worker-farm/lib/child/index.js:45:34)
        at process.emit (events.js:110:17)
        at handleMessage (child_process.js:324:10)
    
    React packager ready.
    
    /Applications/XAMPP/xamppfiles/htdocs/witworks/react-native/myFirstHelloWorld/node_modules/react-native/packager/transformer.js:13
    const babel = require('babel-core');
    ^^^^^
    SyntaxError: Use of const in strict mode.
    
    ..........

**Comment by JonathanWi** [comment]
Same error here with node 5.0.0 on osx 10.11.1 El Capitan. Any news?

**Comment by lupugabriel1** [comment]
+1

**Comment by donmullen** [comment]
Seeing similar issue with node v4.1.2.

**Comment by shioju** [comment]
if you are using nvm, make sure the default node version is 4 or above. That's the version that xcode will use, no matter what your current node version is.

Just run `nvm alias default 4` to set the default to v4.x.x

**Comment by Robdel12** [comment]
That fixed my issue ^

**Comment by iMoreApps** [comment]
"nvm alias default 5" solved my issue. Thanks.

**Comment by deanius** [comment]
yup - defaulting to 4 or higher makes things :)

**Comment by GerryFudd** [comment]
@shioju that fixed my issue as well
