### ISSUE TITLE
react-native link is giving error 

### ISSUE THREAD

**Issue by ShashankEd** [facebook/react-native#32437]
Hi Team/ @react-native-bot 

I'm facing one error while running the command "react-naitve link", and the which is as follows:

error The "path" argument must be of type string. Received undefined.
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.basename (node:path:1309:5)
    at /Users/demo/Documents/hermes-oct-19/myproj/Demo/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/link/linkAll.js:62:78
    at baseUniq (/Users/demo/Documents/hermes-oct-19/myproj/Demo/node_modules/lodash/lodash.js:4338:35)
    at uniqBy (/Users/demo/Documents/hermes-oct-19/myproj/Demo/node_modules/lodash/lodash.js:8482:40)
    at dedupeAssets (/Users/demo/Documents/hermes-oct-19/myproj/Demo/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/link/linkAll.js:62:53)
    at linkAll (/Users/demo/Documents/hermes-oct-19/myproj/Demo/node_modules/react-native/node_modules/@react-native-community/cli/build/co

React native and react natve cli versions in my system: 

**react-native-cli: 2.0.1
react-native: 0.64.**2

Would you please help me to resolve this issue, as this is a blocker for my client, I am not able to run/build my app.

**Looking for resolution from your end ASAP.**

**Comment by ShashankEd** [comment]
> react-native info

The following is my dev env:

System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.24 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.6.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.20.3 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 26, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_301 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Would you please let me know if this explains anything?
