### ISSUE TITLE
Unable to create a new react native app

### ISSUE THREAD

**Issue by Onibenjo** [facebook/react-native#32631]
### Description

```internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '@react-native-community/cli-tools'
Require stack:
- /Users/benjo/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/tools/config/resolveNodeModuleDir.js
- /Users/benjo/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/tools/config/resolveReactNativePath.js
- /Users/benjo/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/tools/config/index.js
- /Users/benjo/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/install/install.js
- /Users/benjo/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/index.js
- /Users/benjo/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/index.js
- /Users/benjo/.npm/_npx/7930a8670f922cdb/node_modules/react-native/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at _cliTools (/Users/benjo/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/tools/config/resolveNodeModuleDir.js:9:16)
    at Object.<anonymous> (/Users/benjo/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/tools/config/resolveNodeModuleDir.js:18:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/benjo/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/tools/config/resolveNodeModuleDir.js',
    '/Users/benjo/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/tools/config/resolveReactNativePath.js',
    '/Users/benjo/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/tools/config/index.js',
    '/Users/benjo/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/install/install.js',
    '/Users/benjo/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/index.js',
    '/Users/benjo/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/index.js',
    '/Users/benjo/.npm/_npx/7930a8670f922cdb/node_modules/react-native/cli.js'
  ]
}
```

### Version

0.66.3

### Output of `react-native info`

nothing

### Steps to reproduce

npx react-native init daba-mobile-v2 --template react-native-template-typescript

**Comment by chefk5** [comment]
Maybe try " npm install @react-native-community/cli-tools"

**Comment by Onibenjo** [comment]
where? I can't initialise a new app
