### ISSUE TITLE
[!] Couldn't determine repo type for URL: `https://cdn.cocoapods.org/`: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)

### ISSUE THREAD

**Issue by kanei0415** [facebook/react-native#32803]
### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [arm64-darwin21]
    RubyGems : 3.2.32
        Host : macOS 12.1 (21C52)
       Xcode : 13.2.1 (13C100)
         Git : git version 2.32.0 (Apple Git-132)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.0.3/lib
Repositories : 
```

### Installation Source

```
Executable Path: /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

npx pod-install
Scanning for pods...
1.11.2 > pod install
Auto-linking React Native modules for target `emepartners`: RNCAsyncStorage, RNDeviceInfo, RNImageCropPicker, RNScreens, lottie-ios, lottie-react-native, and react-native-safe-area-context
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] Couldn't determine repo type for URL: `https://cdn.cocoapods.org/`: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)

Aborting run
An unexpected error was encountered. Please report it as a bug:
CocoaPodsError: Command `pod install` failed.
└─ Cause: pod exited with non-zero code: 1
    at CocoaPodsPackageManager._installAsync (/Users/kanei/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:92213)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async CocoaPodsPackageManager.installAsync (/Users/kanei/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:90176)
    at async runAsync (/Users/kanei/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:106198)
    at async /Users/kanei/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:106284 {
  code: 'COMMAND_FAILED',
  cause: Error: pod exited with non-zero code: 1
      at ChildProcess.h (/Users/kanei/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:1073)
      at Object.onceWrapper (events.js:520:26)
      at ChildProcess.emit (events.js:400:28)
      at maybeClose (internal/child_process.js:1055:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
      ...
      at Object.spawnAsync [as default] (/Users/kanei/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:558)
      at CocoaPodsPackageManager._runAsync (/Users/kanei/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:92995)
      at CocoaPodsPackageManager._installAsync (/Users/kanei/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:90499)
      at CocoaPodsPackageManager.installAsync (/Users/kanei/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:90187)
      at runAsync (/Users/kanei/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:106206)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async /Users/kanei/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:106284 {
    pid: 39311,
    output: [ '', '' ],
    stdout: '',
    stderr: '',
    status: 1,
    signal: null
  },
  isPackageManagerError: true
}

### Version

0.66.1

### Output of `npx react-native info`

System:
    OS: macOS 12.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 1.20 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.6/bin/yarn
    npm: 7.23.0 - ~/node_modules/.bin/npm
    Watchman: 2021.12.20.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 27, 29, 30, 32
      Build Tools: 29.0.2, 30.0.2, 32.0.0
      System Images: android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.1 => 0.66.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Error occurs when npx pod install is executed in a terminal.

**Comment by jjaaxx44** [comment]
@kanei0415 did you find any solution

**Comment by kanei0415** [comment]
yes, I deleted brew and reinstall with rosetta terminal
