### ISSUE TITLE
[turtle-cli] NDK installation being skipped and APK isn't being generated. NDK side-by-side from android studio is installed

### ISSUE THREAD

**Issue by tejavoo** [facebook/react-native#32824]
### Description

I am not able to locally build react native app using turtle-cli. Please help me with the problem. The NDK is installed using Android studio but isn't being recognised by turtle

### Version

0.64.3

### Output of `npx react-native info`

Jan 2 23:34:51 turtle[5461] INFO:  FAILURE: Build failed with an exception.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:51 turtle[5461] INFO:  * Where:
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:51 turtle[5461] INFO:  Build file '/Users/tejavu/.turtle/workingdir/android/sdk44/packages/expo-gl-cpp/android/build.gradle' line: 309
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:51 turtle[5461] INFO:  * What went wrong:
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:51 turtle[5461] INFO:  Default side-by-side NDK installation is not found.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:51 turtle[5461] INFO:  Set $ANDROID_NDK_HOME environment variable correctly or setup ndk.dir in local.properties.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:51 turtle[5461] INFO:  > NDK is not installed
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:51 turtle[5461] INFO:  * Try:
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:51 turtle[5461] INFO:  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:51 turtle[5461] INFO:  * Get more help at https://help.gradle.org
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:51 turtle[5461] INFO:  Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
  platform: "android"
  buildPhase: "running gradle"
  source: "stdout"
Jan 2 23:34:51 turtle[5461] INFO:  Use '--warning-mode all' to show the individual deprecation warnings.
  platform: "android"
  buildPhase: "running gradle"
  source: "stdout"
Jan 2 23:34:51 turtle[5461] INFO:  See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
  platform: "android"
  buildPhase: "running gradle"
  source: "stdout"
Jan 2 23:34:51 turtle[5461] INFO:  BUILD FAILED in 28s
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:52 turtle[5461] ERROR: Error: ./gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:514:26)
    at ChildProcess.emit (node:events:394:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    ...
    at spawnAsync (/Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnAsyncThrowError (/@expo/xdl@59.1.7/src/detach/ExponentTools.ts:111:19)
    at buildShellAppAsync (/@expo/xdl@59.1.7/src/detach/AndroidShellApp.js:1493:11)
    at Object.createAndroidShellAppAsync (/@expo/xdl@59.1.7/src/detach/AndroidShellApp.js:381:5)
    at runShellAppBuilder (/Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/src/builders/android.ts:99:5)
    at buildAndroid (/Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/src/builders/android.ts:31:26)
    at /Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:87:7
    at Command.<anonymous> (/Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "android"
Jan 2 23:34:52 turtle[5461] ERROR: Failed to build standalone app
  err: Error: ./gradlew exited with non-zero code: 1
      at ChildProcess.completionListener (/Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (node:events:514:26)
      at ChildProcess.emit (node:events:394:28)
      at ChildProcess.emit (node:domain:475:12)
      at maybeClose (node:internal/child_process:1064:16)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
      ...
      at spawnAsync (/Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at spawnAsyncThrowError (/@expo/xdl@59.1.7/src/detach/ExponentTools.ts:111:19)
      at buildShellAppAsync (/@expo/xdl@59.1.7/src/detach/AndroidShellApp.js:1493:11)
      at Object.createAndroidShellAppAsync (/@expo/xdl@59.1.7/src/detach/AndroidShellApp.js:381:5)
      at runShellAppBuilder (/Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/src/builders/android.ts:99:5)
      at buildAndroid (/Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/src/builders/android.ts:31:26)
      at /Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:87:7
      at Command.<anonymous> (/Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "android"

### Steps to reproduce

Jan 2 23:34:51 turtle[5461] INFO:  FAILURE: Build failed with an exception.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:51 turtle[5461] INFO:  * Where:
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:51 turtle[5461] INFO:  Build file '/Users/tejavu/.turtle/workingdir/android/sdk44/packages/expo-gl-cpp/android/build.gradle' line: 309
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:51 turtle[5461] INFO:  * What went wrong:
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:51 turtle[5461] INFO:  Default side-by-side NDK installation is not found.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:51 turtle[5461] INFO:  Set $ANDROID_NDK_HOME environment variable correctly or setup ndk.dir in local.properties.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:51 turtle[5461] INFO:  > NDK is not installed
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:51 turtle[5461] INFO:  * Try:
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:51 turtle[5461] INFO:  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:51 turtle[5461] INFO:  * Get more help at https://help.gradle.org
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:51 turtle[5461] INFO:  Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
  platform: "android"
  buildPhase: "running gradle"
  source: "stdout"
Jan 2 23:34:51 turtle[5461] INFO:  Use '--warning-mode all' to show the individual deprecation warnings.
  platform: "android"
  buildPhase: "running gradle"
  source: "stdout"
Jan 2 23:34:51 turtle[5461] INFO:  See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
  platform: "android"
  buildPhase: "running gradle"
  source: "stdout"
Jan 2 23:34:51 turtle[5461] INFO:  BUILD FAILED in 28s
  platform: "android"
  buildPhase: "running gradle"
  source: "stderr"
Jan 2 23:34:52 turtle[5461] ERROR: Error: ./gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:514:26)
    at ChildProcess.emit (node:events:394:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    ...
    at spawnAsync (/Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnAsyncThrowError (/@expo/xdl@59.1.7/src/detach/ExponentTools.ts:111:19)
    at buildShellAppAsync (/@expo/xdl@59.1.7/src/detach/AndroidShellApp.js:1493:11)
    at Object.createAndroidShellAppAsync (/@expo/xdl@59.1.7/src/detach/AndroidShellApp.js:381:5)
    at runShellAppBuilder (/Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/src/builders/android.ts:99:5)
    at buildAndroid (/Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/src/builders/android.ts:31:26)
    at /Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:87:7
    at Command.<anonymous> (/Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "android"
Jan 2 23:34:52 turtle[5461] ERROR: Failed to build standalone app
  err: Error: ./gradlew exited with non-zero code: 1
      at ChildProcess.completionListener (/Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (node:events:514:26)
      at ChildProcess.emit (node:events:394:28)
      at ChildProcess.emit (node:domain:475:12)
      at maybeClose (node:internal/child_process:1064:16)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
      ...
      at spawnAsync (/Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at spawnAsyncThrowError (/@expo/xdl@59.1.7/src/detach/ExponentTools.ts:111:19)
      at buildShellAppAsync (/@expo/xdl@59.1.7/src/detach/AndroidShellApp.js:1493:11)
      at Object.createAndroidShellAppAsync (/@expo/xdl@59.1.7/src/detach/AndroidShellApp.js:381:5)
      at runShellAppBuilder (/Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/src/builders/android.ts:99:5)
      at buildAndroid (/Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/src/builders/android.ts:31:26)
      at /Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/src/bin/utils/builder.ts:87:7
      at Command.<anonymous> (/Users/tejavu/.nvm/versions/node/v16.8.0/lib/node_modules/turtle-cli/src/bin/index.ts:23:12)
  platform: "android"

**Comment by cortinico** [comment]
> I am not able to locally build react native app using turtle-cli. Please help me with the problem. The NDK is installed using Android studio but isn't being recognised by turtle.

Please move this issue over to https://github.com/expo/turtle/issues as this is most likely unrelated to react-native itself.
