### ISSUE TITLE
Android Instacrash with 0.67.1, hermes, and bundled build variant other than 'release'

### ISSUE THREAD

**Issue by bradstiff** [facebook/react-native#32994]
### Description

I'm using hermes. Not using proguard. 

I have a 'Staging' variant that is based on the Release variant. I have the following bits in app build.gradle:

project.ext.react = [
    enableHermes: true,  // clean and rebuild if changing
    **bundleInStaging: true, // react-native build.gradle needs this flag with suffix matching build config**
]

...and...

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        stagingImplementation files(hermesPath + "hermes-release.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }

Up through v 0.66.3, it worked fine. Today I upgraded to 0.67.1 and the Staging build variant crashes on startup.

The Release build variant works fine.

2022-01-28 18:37:31.641 3398-3398/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xovation.weski.staging, PID: 3398
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so
    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.xovation.weski.staging/lib-main flags = 1]
    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/~~0fimjIq8iSV2Mcs_oa5VIQ==/com.xovation.weski.staging-bpUR-INIMuqW8m_-iw8lIw==/lib/arm64 flags = 0]
    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
    	Native lib dir: /data/app/~~0fimjIq8iSV2Mcs_oa5VIQ==/com.xovation.weski.staging-bpUR-INIMuqW8m_-iw8lIw==/lib/arm64
     result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1098)
        at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:914)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:826)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:773)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:743)
        at com.facebook.react.jscexecutor.JSCExecutor.loadLibrary(JSCExecutor.java:24)
        at com.facebook.react.jscexecutor.JSCExecutor.<clinit>(JSCExecutor.java:20)
        at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:352)
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:319)
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:95)
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
        at com.xovation.weski.MainApplication.onCreate(MainApplication.java:59)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7429)
        at android.app.ActivityThread.access$1700(ActivityThread.java:309)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2268)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8582)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

**Just above this is the following error:**
2022-01-28 18:37:31.641 3398-3398/? E/SoLoader: couldn't find DSO to load: libhermes-executor-release.so
    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.xovation.weski.staging/lib-main flags = 1]
    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/~~0fimjIq8iSV2Mcs_oa5VIQ==/com.xovation.weski.staging-bpUR-INIMuqW8m_-iw8lIw==/lib/arm64 flags = 0]
    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
    	Native lib dir: /data/app/~~0fimjIq8iSV2Mcs_oa5VIQ==/com.xovation.weski.staging-bpUR-INIMuqW8m_-iw8lIw==/lib/arm64
     result: 0

### Version

0.67.1

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 2.87 GB / 23.86 GB
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.0.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7935034
    Visual Studio: 16.11.31729.503 (Visual Studio Community 2019), 15.9.28307.1259 (Visual Studio Enterprise 2017)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.1 => 0.67.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Build bundled variant other than release and start.

**Comment by cortinico** [comment]
Yup that happens because the `deleteDebugFilesForVariant` is defaulting to a function that returns "true" only if the variant name is `release`.

https://github.com/facebook/react-native/blob/6239e2f5ce82f7c2e683eb4699b9ce3ff1b58ac5/react.gradle#L119-L123

You should be able to specify a `deleteDebugFilesForVariant` function inside your `project.ext.react` to return true if the variant name is either `release` or `staging`.

**Comment by bradstiff** [comment]
Thanks for the reply. I decided I was encountering this problem because my config was unusual. I switched to Product Flavors. I can now build the StagingRelease variant with no special adjustments to build.gradle.

Closing this.

**Comment by draperunner** [comment]
Seems like another case of this issue: https://github.com/facebook/react-native/issues/30788

I had the same issue as @bradstiff. Adding `deleteDebugFilesForVariant` as shown below seems to fix it for me. Feels hacky though.

```diff
project.ext.react = [
   bundleInStaging: true,
   devDisabledInStaging: true,
   enableHermes: true,  // clean and rebuild if changing
+  deleteDebugFilesForVariant: {
+    def variant -> variant.name.toLowerCase().contains("release") || variant.name.toLowerCase().contains("staging")
+  }
]
```

**Comment by cortinico** [comment]
> Feels hacky though.

It's not hacky actually. It's part of the public API of `react.gradle`: 
https://github.com/facebook/react-native/blob/669cd0257cfa6a8a1d5c8d6c741786b1abd62b41/react.gradle#L119-L123
