### ISSUE TITLE
App Package step fails

### ISSUE THREAD

**Issue by wolfcode** [facebook/react-native#33066]
### Description

FAILURE: Build failed with an exception.

* Where:
Script '/Users/mahendran.m/workspace/ekart-cl-ui-native-apps/node_modules/react-native/react.gradle' line: 291

* What went wrong:
Execution failed for task ':app:packageStormtrooperPreprodDebug'.
> react_bvgpnjnqjjtzjyz4kq99f9rh1$_run_closure4$_closure6$_closure10$_closure18

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 48s

    at checkExecSyncError (child_process.js:616:11)
    at execFileSync (child_process.js:634:15)
    at runOnAllDevices (/Users/mahendran.m/workspace/ekart-cl-ui-native-apps/node_modules/react-native/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/Users/mahendran.m/workspace/ekart-cl-ui-native-apps/node_modules/react-native/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:179:41)
    at /Users/mahendran.m/workspace/ekart-cl-ui-native-apps/node_modules/react-native/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:133:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.handleAction (/Users/mahendran.m/workspace/ekart-cl-ui-native-apps/node_modules/@react-native-community/cli/build/index.js:182:9)

### Version

0.61.4

### Output of `npx react-native info`

System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 105.75 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  SDKs:
    Android SDK:
      API Levels: 23, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 31.0.0
      System Images: android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

### Steps to reproduce

private repo, we can connect for more details.

**Comment by cortinico** [comment]
> 0.61.4

That's a really old version of RN. Consider updating and test again as this is most likely already solved.
