### ISSUE TITLE
Metro has encountered an error: cannot read property of undefined (reading 'transformfile') at bundler.transformfile...

### ISSUE THREAD

**Issue by cieldon32** [facebook/react-native#33107]
### Description

I got error :
Metro has encountered an error: cannot read property of undefined (reading 'transformfile') at bundler.transformfile...

and then I change the node to 16.00, 16.14.0, 14.00, 14.18.1
but the error is not miss.

please tell me how to fix

### Version

0.67.2

### Output of `npx react-native info`

System:
    OS: macOS 12.2.1
    CPU: (8) x64 Apple M1
    Memory: 24.41 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: Not Found
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: 2022.02.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

TypeError: Cannot read properties of undefined (reading 'transformFile')
    at Bundler.transformFile (/Users/cieldon/demo/demoA/node_modules/metro/src/Bundler.js:48:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.transform (/Users/cieldon/demo/demoA/node_modules/metro/src/lib/transformHelpers.js:101:12)
    at async processModule (/Users/cieldon/demo/demoA/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:18)
    at async traverseDependenciesForSingleFile (/Users/cieldon/demo/demoA/node_modules/metro/src/DeltaBundler/traverseDependencies.js:131:3)
    at async Promise.all (index 0)
    at async initialTraverseDependencies (/Users/cieldon/demo/demoA/node_modules/metro/src/DeltaBundler/traverseDependencies.js:114:3)
    at async DeltaCalculator._getChangedDependencies (/Users/cieldon/demo/demoA/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:164:25)
    at async DeltaCalculator.getDelta (/Users/cieldon/demo/demoA/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:94:16)
    at async DeltaBundler.buildGraph (/Users/cieldon/demo/demoA/node_modules/metro/src/DeltaBundler.js:50:5)

**Comment by cieldon32** [comment]
I had fixed.

**Comment by cieldon32** [comment]
I had fixed.
1. My mac is M1, so follow this: https://zhuanlan.zhihu.com/p/356820165
2. node17 update the OpenSSl, so use: export NODE_OPTIONS=--openssl-legacy-provider
