### ISSUE TITLE
Android app is crashing in release mode

### ISSUE THREAD

**Issue by cakesoft-shashank** [facebook/react-native#33407]
### Description

```
2022-03-11 11:24:42.820 31283-9433/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: io.hexawallet.hexa.development, PID: 31283
    com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'h.exec'), stack:
    value@1970:787
    _@1985:314
    c@1985:953
    _checkDone@1985:1449
    <unknown>@1982:724
    h@1976:279
    run@14:1233
    y@14:923
    k@124:657
    callTimers@124:2699
    value@37:3311
    <unknown>@37:822
    value@37:2565
    value@37:794
    value@-1
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:49)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:233)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
```

### Version

0.63.3

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 118.31 MB / 10.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.11.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.0.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1, 30.0.2, 30.0.3
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Try building [this](https://github.com/bithyve/hexa/tree/feature/2.0.75) branch in release mode

### Snack, code example, screenshot, or link to a repository

https://github.com/bithyve/hexa/tree/feature/2.0.75

**Comment by cortinico** [comment]
Not much we can do here sadly. You're using a really old version of React Native so it makes hard to provide any support.

**Comment by vitorcont** [comment]
@cakesoft-shashank have you found any solutions to this issue?
