### ISSUE TITLE
npm install -g react-native-cli  Error: Cannot find module './lib/cookies'

### ISSUE THREAD

**Issue by iDrummer** [facebook/react-native#3359]
localhost:~ iDrummer$ npm install -g react-native-cli
Error: Cannot find module './lib/cookies'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/index.js:18:29)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "-g" "react-native-cli"
npm ERR! node v2.4.0
npm ERR! npm  v2.13.0
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module './lib/cookies'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by iDrummer** [comment]
upgraded to node v4.2.0. solved
