### ISSUE TITLE
newArchEnabled=true not working

### ISSUE THREAD

**Issue by whyamsx** [facebook/react-native#33693]
### Description

Hello!

I tried to switch my project to New Architecture and it was not successful for me for an android app.

The build of the application goes without problems,
but trying to open it in the emulator shows me Splash Screen and then immediately closes, this is the whole problem.

### Version

0.68.0

### Output of `npx react-native info`

```System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 90.55 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 2022.03.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: javac 18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Create project with npx command: `npx react-native init MyApp`.
2. On Android I set `newArchEnabled=true` in `android/gradle.properties` file.
3. Then I just run the project on Android with the command: `yarn android`.

### Snack, code example, screenshot, or link to a repository

The code, except for the steps above to reproduce the error, remains unchanged.

**Comment by whyamsx** [comment]
> Please show the error log

```04-25 23:29:15.807   343   432 E android.hardware.audio@7.0-impl.ranchu: device/generic/goldfish/audio/stream_out.cpp:updateSourceMetadata:377 failure: Result::NOT_SUPPORTED
04-25 23:29:15.886   382   479 E SurfaceFlinger: Only WindowManager is allowed to use eEarlyWakeup[Start|End] flags
04-25 23:29:15.927  1440  1440 E HwDetectorWithState: a: 3
04-25 23:29:15.942   343   432 E android.hardware.audio@7.0-impl.ranchu: device/generic/goldfish/audio/stream_out.cpp:updateSourceMetadata:377 failure: Result::NOT_SUPPORTED
04-25 23:29:16.088  9238  9238 E unknown:ReactRootView: Unable to update root layout specs for ReactRootView: no rootViewTag set yet
04-25 23:29:16.353   382   479 E SurfaceFlinger: Only WindowManager is allowed to use eEarlyWakeup[Start|End] flags
04-25 23:29:16.475  9238  9238 E AndroidRuntime: Error reporting crash
04-25 23:29:16.475  9238  9238 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 319681440 byte allocation with 4245510 free bytes and 187MB until OOM, target footprint 8491022, growth limit 201326592
04-25 23:29:16.475  9238  9238 E AndroidRuntime: 	at java.util.Arrays.copyOf(Arrays.java:3257)
04-25 23:29:16.475  9238  9238 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
04-25 23:29:16.475  9238  9238 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
04-25 23:29:16.475  9238  9238 E AndroidRuntime: 	at java.lang.StringBuilder.append(StringBuilder.java:137)
04-25 23:29:16.475  9238  9238 E AndroidRuntime: 	at java.lang.Throwable.toString(Throwable.java:493)
04-25 23:29:16.475  9238  9238 E AndroidRuntime: 	at java.lang.String.valueOf(String.java:2924)
04-25 23:29:16.475  9238  9238 E AndroidRuntime: 	at java.io.PrintWriter.println(PrintWriter.java:754)
04-25 23:29:16.475  9238  9238 E AndroidRuntime: 	at java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:778)
04-25 23:29:16.475  9238  9238 E AndroidRuntime: 	at java.lang.Throwable.printStackTrace(Throwable.java:667)
04-25 23:29:16.475  9238  9238 E AndroidRuntime: 	at java.lang.Throwable.printStackTrace(Throwable.java:735)
04-25 23:29:16.475  9238  9238 E AndroidRuntime: 	at android.app.ApplicationErrorReport$CrashInfo.<init>(ApplicationErrorReport.java:354)
04-25 23:29:16.475  9238  9238 E AndroidRuntime: 	at android.app.ApplicationErrorReport$ParcelableCrashInfo.<init>(ApplicationErrorReport.java:484)
04-25 23:29:16.475  9238  9238 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:157)
04-25 23:29:16.475  9238  9238 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
04-25 23:29:16.475  9238  9238 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
04-25 23:29:16.475  9238  9238 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2200)
04-25 23:29:16.499   382   382 E ClientCache: failed to get buffer, invalid process token
04-25 23:29:16.499   382   382 E BpTransactionCompletedListener: Failed to transact (-32)```

**Comment by cortinico** [comment]
> 04-25 23:29:16.475  9238  9238 E AndroidRuntime: Error reporting crash
> 04-25 23:29:16.475  9238  9238 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 319681440 byte allocation with 4245510 free bytes and 187MB until OOM, target footprint 8491022, growth limit 201326592

Duplicates https://github.com/facebook/react-native/issues/33640

I see you're running with Java 18. Downgrading to Java 11 would fix the issue.
Thanks for reporting this 🙏
