### ISSUE TITLE
In order to use RNScreens components your app`s activity need to extend ReactActivity - Android

### ISSUE THREAD

**Issue by SherMish** [facebook/react-native#33722]
### Description

I get the following error when I try to use react native navigation. This is the full error:
```
E/unknown:ReactNative: Exception in native call
    java.lang.IllegalStateException: In order to use RNScreens components your app's activity need to extend ReactActivity
        at com.swmansion.rnscreens.ScreenContainer.setupFragmentManager(ScreenContainer.kt:169)
        at com.swmansion.rnscreens.ScreenContainer.onAttachedToWindow(ScreenContainer.kt:199)
        at android.view.View.dispatchAttachedToWindow(View.java:21304)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4239)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4246)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:6001)
        at android.view.ViewGroup.addView(ViewGroup.java:5777)
        at android.view.ViewGroup.addView(ViewGroup.java:5717)
        at com.facebook.react.uimanager.ViewGroupManager.addView(ViewGroupManager.java:37)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:533)
        at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:217)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:997)
        at android.view.Choreographer.doCallbacks(Choreographer.java:797)
        at android.view.Choreographer.doFrame(Choreographer.java:728)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```
I tried the following potential solutions but unfortunately the app still crashes:
1. Extended ReactNativeActivity.java (which loads a bundle): _public class RNActivity extends **ReactActivity** {...}_
2. Extended MainActivity.java:  _public class TempMainActivity extends **ReactActivity** {...}_
3. Implemented ReactApplication: 
```
public class CompanyApplication extends Application implements ReactApplication {
...
private final ReactNativeHost mReactNativeHost =
            new ReactNativeHost(this) {
                    @Override
                    public boolean getUseDeveloperSupport() {
                        return BuildConfig.DEBUG;
                    }
                    @Override
                    protected List<ReactPackage> getPackages() {
                        @SuppressWarnings("UnnecessaryLocalVariable")
                        List<ReactPackage> packages = new PackageList(this).getPackages();
                        // Packages that cannot be autolinked yet can be added manually here, for example:
                        // packages.add(new MyReactNativePackage());
                        packages.add(new NsClientAPIPackager());
                        return packages;
                    }
                    @Override
                    protected String getJSMainModuleName() {
                        return "MyReactNativeApp";
                    }
                };

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
    }
...
}
```

### Version

0.67.3

### Output of `npx react-native info`

System:
    OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 215.89 MB / 15.36 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 21, 23, 27, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 30.0.2, 31.0.0, 32.0.0
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Described in the first section.

**Comment by cortinico** [comment]
> I get the following error when I try to use react native navigation. This is the full error:

This should be moved to https://github.com/software-mansion/react-native-screens/issues as it's not related to React Native per-se
