### ISSUE TITLE
Can't run iOS app with terminal

### ISSUE THREAD

**Issue by IlanZ93** [facebook/react-native#33979]
### Description

Hi, i can't run iOS with npm **npx react-native run-ios --scheme='AdhCeresiaAppMobile'**

I was able to do it last week and now i dont know why i cant.

I've tried delete build, delete pods and Podfile.lock, reinstall pods, change for legacy build. Nothing works.

I know i can launch it through xCode, but there is no fast refresh, kind of annoying when i have to solve a design issue... 

(i have multiple scheme for multiple Application with the same code. I have 2 app with this system, the second one have no issue for launching through vscode terminal.)

Here what the log file contain : 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'ceresia-ios' ]
2 info using npm@6.9.0
3 info using node@v12.0.0
4 verbose run-script [ 'preceresia-ios', 'ceresia-ios', 'postceresia-ios' ]
5 info lifecycle AdhNoriapAppMobile@0.0.1~preceresia-ios: AdhNoriapAppMobile@0.0.1
6 info lifecycle AdhNoriapAppMobile@0.0.1~ceresia-ios: AdhNoriapAppMobile@0.0.1
7 verbose lifecycle AdhNoriapAppMobile@0.0.1~ceresia-ios: unsafe-perm in lifecycle true
8 verbose lifecycle AdhNoriapAppMobile@0.0.1~ceresia-ios: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/macdev/Documents/Travail/AdhNoriapAppMobile/node_modules/.bin:/Users/macdev/.yarn/bin:/Users/macdev/.config/yarn/global/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/macdev/.yarn/bin:/Users/macdev/.config/yarn/global/node_modules/.bin:/Users/macdev/Library/Android/sdk/emulator:/Users/macdev/Library/Android/sdk/tools:/Users/macdev/Library/Android/sdk/tools/bin:/Users/macdev/Library/Android/sdk/platform-tools:/Users/macdev/Library/Android/sdk/emulator:/Users/macdev/Library/Android/sdk/tools:/Users/macdev/Library/Android/sdk/tools/bin:/Users/macdev/Library/Android/sdk/platform-tools
9 verbose lifecycle AdhNoriapAppMobile@0.0.1~ceresia-ios: CWD: /Users/macdev/Documents/Travail/AdhNoriapAppMobile
10 silly lifecycle AdhNoriapAppMobile@0.0.1~ceresia-ios: Args: [ '-c', "npx react-native run-ios --scheme='AdhCeresiaAppMobile'" ]
11 silly lifecycle AdhNoriapAppMobile@0.0.1~ceresia-ios: Returned: code: 1  signal: null
12 info lifecycle AdhNoriapAppMobile@0.0.1~ceresia-ios: Failed to exec ceresia-ios script
13 verbose stack Error: AdhNoriapAppMobile@0.0.1 ceresia-ios: `npx react-native run-ios --scheme='AdhCeresiaAppMobile'`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:196:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:196:13)
13 verbose stack     at maybeClose (internal/child_process.js:1000:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
14 verbose pkgid AdhNoriapAppMobile@0.0.1
15 verbose cwd /Users/macdev/Documents/Travail/AdhNoriapAppMobile
16 verbose Darwin 20.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ceresia-ios"
18 verbose node v12.0.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error AdhNoriapAppMobile@0.0.1 ceresia-ios: `npx react-native run-ios --scheme='AdhCeresiaAppMobile'`
22 error Exit status 1
23 error Failed at the AdhNoriapAppMobile@0.0.1 ceresia-ios script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

And here whats in terminal when i run the command : https://pastebin.com/kZFzp4VA

### Version

0.61.5

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 212.85 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.0.0 - /usr/local/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-27 | Intel x86 Atom_64, android-28 | Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

### Steps to reproduce

Run npx react-native run-ios --scheme='AdhCeresiaAppMobile'

### Snack, code example, screenshot, or link to a repository

No public repository.

**Comment by rnike** [comment]
Have you tried building your app with Xcode?

- `open ./ios/AdhNoriapAppMobile.xcworkspace`

The build output is more detailed in Xcode, maybe you can find what's actually causing the failure.

**Comment by AmirDiafi** [comment]
the same issue here

**Comment by IlanZ93** [comment]
I dont have the error anymore.

I just got a new iMac with M1 chip, re install everything and the build through the terminal end well BUT the app launch and crash instantly... without error message

If someone have some solution or any way to debug and find the problem.

Build to an emulator or for TestFlight from Xcode : there is no problem.

The only problem is for npm run ios (for me i use a scheme)
