### ISSUE TITLE
Error regarding `generateCodegenArtifactsFromSchema` when running Android Codegen

### ISSUE THREAD

**Issue by friyiajr** [facebook/react-native#34000]
### Description

I have been experimenting with TurboModules with Codegen and created an empty project. I was able to get iOS working with few issues. When I try to go through the steps for Android though I get the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preBuild'.
> Task with path 'generateCodegenArtifactsFromSchema' not found in project ':app'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

    at makeError (/Users/friyia/Desktop/turbo/MyAwesomeProject/node_modules/execa/index.js:174:9)
    at /Users/friyia/Desktop/turbo/MyAwesomeProject/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (/Users/friyia/Desktop/turbo/MyAwesomeProject/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/friyia/Desktop/turbo/MyAwesomeProject/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I think this file may be missing from the React Native Project. Please advise.

### Version

0.68.2

### Output of `npx react-native info`

```
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 22.57 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Generate a new React-Native Project
2. Set `newArchEnabled=true` in `gradle.properties` 
3. Uncomment these lines in the `Android.mk` file

```
LOCAL_C_INCLUDES := $(LOCAL_PATH)
LOCAL_SRC_FILES := $(wildcard $(LOCAL_PATH)/*.cpp)
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)
```

4. Sync Gradle and try to run a build

### Snack, code example, screenshot, or link to a repository

You can find my sample code by cloning this project and going to the `android-attempt` branch:

https://github.com/friyiajr/turbomoodule-sample-scratchpad

**Comment by friyiajr** [comment]
Update, I also experience this issue on 0.69.0-rc6. Everything works great until you uncomment this line:

```
       afterEvaluate {
            // If you wish to add a custom TurboModule or component locally,
            // you should uncomment this line.
            preBuild.dependsOn("generateCodegenArtifactsFromSchema")
```

I want to try and create some custom modules so I can't do much without this being turned on

**Comment by cortinico** [comment]
Thanks for flagging this. 

The issue is that you'll need to include also this line on your of your `android/app/build.gradle` file:

```
apply plugin: "com.facebook.react"
```

That plugin is providing the task `generateCodegenArtifactsFromSchema` that Gradle is complaining about.

**Comment by cortinico** [comment]
Can you confirm that this works? If so, I will update the default template to add a small comment about this.

**Comment by friyiajr** [comment]
@cortinico the app compiles after that change thanks for the help!
