### ISSUE TITLE
Linking.openUrl with a telephone number leads to a system error on some Android devices

### ISSUE THREAD

**Issue by grevtsovna** [facebook/react-native#34016]
### Description

Linking.openUrl with a telephone number leads to a system error on some Android devices.
Screenshot:
![Screenshot_20220616-122913](https://user-images.githubusercontent.com/36564314/173998788-4dd08705-725d-4f5e-af8a-33a436a9cdae.png)

### Version

0.67.3

### Output of `npx react-native info`

System:
    OS: macOS 12.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.77 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.6.0 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-21 | Google APIs Intel x86 Atom_64, android-22 | Google APIs Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-24 | ARM EABI v7a, android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play ARM 64 v8a, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

In a RN app, add a button that triggers a Linking interface to open a dialer app on Android. The error occurs only on some devices, e.g. on Xiaomi Mi A2

`<Button title="Test" onPress={() => Linking.openURL('tel://+71234567890')}/>`

### Snack, code example, screenshot, or link to a repository

Snack: https://snack.expo.dev/@n_grevtsov/linking-error

Device Logs:
```
06-16 12:29:06.577 20024 20024 E AndroidRuntime: FATAL EXCEPTION: main
06-16 12:29:06.577 20024 20024 E AndroidRuntime: Process: system:ui, PID: 20024
06-16 12:29:06.577 20024 20024 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.widget.AbsListView.getCheckedItemPosition()' on a null object reference
06-16 12:29:06.577 20024 20024 E AndroidRuntime: 	at com.android.internal.app.ResolverActivity.resetButtonBar(ResolverActivity.java:1353)
06-16 12:29:06.577 20024 20024 E AndroidRuntime: 	at com.android.internal.app.ResolverActivity.access$700(ResolverActivity.java:102)
06-16 12:29:06.577 20024 20024 E AndroidRuntime: 	at com.android.internal.app.ResolverActivity$ResolveListAdapter$2.run(ResolverActivity.java:1896)
06-16 12:29:06.577 20024 20024 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
06-16 12:29:06.577 20024 20024 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
06-16 12:29:06.577 20024 20024 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
06-16 12:29:06.577 20024 20024 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7403)
06-16 12:29:06.577 20024 20024 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-16 12:29:06.577 20024 20024 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
06-16 12:29:06.577 20024 20024 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by grevtsovna** [comment]
The same problem on Huawei Nexus 6P (Android 8.1)

```
2022-06-21 10:22:47.490 28810-28835/? E/DialerDialerBaseApplication: com.android.dialer.DialerBaseApplication.getResources:45 getResources() called before resources are initialized
    java.lang.IllegalStateException: Resources are not initialized yet. Do not call getResource() in constructors of injected classes
        at stm.L(Unknown Source:7)
        at bmu.getResources(PG:2)
        at lur.a(PG:1)
        at lua.h(Unknown Source:0)
        at lwp.d(PG:8)
        at lwt.j(PG:5)
        at lwt.handleMessage(PG:60)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2022-06-21 10:22:47.507 28810-28835/? E/DialerDialerBaseApplication: com.android.dialer.DialerBaseApplication.getResources:45 getResources() called before resources are initialized
    java.lang.IllegalStateException: Resources are not initialized yet. Do not call getResource() in constructors of injected classes
        at stm.L(Unknown Source:7)
        at bmu.getResources(PG:2)
        at lur.a(PG:1)
        at lua.h(Unknown Source:0)
        at lwp.d(PG:8)
        at lwt.j(PG:5)
        at lwt.handleMessage(PG:60)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2022-06-21 10:22:48.337 28810-28855/? W/DialerPostCallDao: com.android.dialer.postcall.impl.storage.PostCallDao.lambda$isPostCall$2:75 received null call connect time, returning false
```
