### ISSUE TITLE
libcallinvoker.a: no archive symbol table (run ranlib)

### ISSUE THREAD

**Issue by PritishSawant** [facebook/react-native#34041]
### Description

I am trying to create a turbo module for android but I get this below error 

```
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1093 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
info Installing the app...

> Configure project :app
Unable to detect AGP versions for included builds. All projects in the build should use the same AGP version. Class name for the included build object: org.gradle.composite.internal.DefaultIncludedBuild$IncludedBuildImpl_Decorated.

> Task :ReactAndroid:buildNdkBuildDebug
C/C++: /Users/transformhub/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/build/intermediates/cxx/Debug/6t2i5mp6/obj/local/armeabi-v7a/libcallinvoker.a: no archive symbol table (run ranlib)
C/C++: clang++: error: linker command failed with exit code 1 (use -v to see invocation)
C/C++: make: *** [/Users/transformhub/Library/Android/sdk/ndk/21.4.7075529/build/core/build-binary.mk:725: /Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/build/intermediates/cxx/Debug/6t2i5mp6/obj/local/armeabi-v7a/libreact_render_runtimescheduler.so] Error 1
C/C++: make: *** Waiting for unfinished jobs....

> Task :ReactAndroid:buildNdkBuildDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
25 actionable tasks: 2 executed, 23 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:buildNdkBuildDebug'.
> Build command failed.
  Error while executing process /Users/transformhub/Library/Android/sdk/ndk/21.4.7075529/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/src/main/jni/react/jni/Android.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=/Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/build/intermediates/cxx/Debug/6t2i5mp6/obj NDK_LIBS_OUT=/Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/build/intermediates/cxx/Debug/6t2i5mp6/lib NDK_APPLICATION_MK=/Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/src/main/jni/Application.mk THIRD_PARTY_NDK_DIR=/Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/build/third-party-ndk REACT_COMMON_DIR=/Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/../ReactCommon REACT_GENERATED_SRC_DIR=/Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/build/generated/source REACT_SRC_DIR=/Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react -j8 --output-sync=none butter fabricjni fb folly_futures folly_json glog glog_init hermes-executor-debug hermes-executor-release jscexecutor jsi jsijniprofiler jsinspector logger mapbufferjni react_codegen_rncore react_config react_debug react_nativemodule_core react_render_animations react_render_attributedstring react_render_componentregistry react_render_core react_render_debug react_render_graphics react_render_imagemanager react_render_leakchecker react_render_mapbuffer react_render_mounting react_render_runtimescheduler react_render_scheduler react_render_telemetry react_render_templateprocessor react_render_textlayoutmanager react_render_uimanager react_utils reactnativeblob reactnativejni reactnativeutilsjni reactperfloggerjni rrc_image rrc_root rrc_text rrc_unimplementedview rrc_view runtimeexecutor turbomodulejsijni yoga}
  make: Nothing to be done for 'butter'.
  [armeabi-v7a] SharedLibrary  : librrc_root.so
  [armeabi-v7a] SharedLibrary  : libreact_render_runtimescheduler.so
  [armeabi-v7a] SharedLibrary  : librrc_unimplementedview.so
  make: Nothing to be done for 'fb'.
  make: Nothing to be done for 'folly_futures'.
  make: Nothing to be done for 'folly_json'.
  make: Nothing to be done for 'glog'.
  make: Nothing to be done for 'glog_init'.
  [armeabi-v7a] SharedLibrary  : libreact_render_attributedstring.so
  make: Nothing to be done for 'jsi'.
  make: Nothing to be done for 'jsinspector'.
  make: Nothing to be done for 'logger'.
  make: Nothing to be done for 'mapbufferjni'.
  make: Nothing to be done for 'react_config'.
  make: Nothing to be done for 'react_debug'.
  make: Nothing to be done for 'react_render_componentregistry'.
  make: Nothing to be done for 'react_render_core'.
  make: Nothing to be done for 'react_render_debug'.
  make: Nothing to be done for 'react_render_graphics'.
  make: Nothing to be done for 'react_render_leakchecker'.
  make: Nothing to be done for 'react_render_mapbuffer'.
  make: Nothing to be done for 'react_utils'.
  make: Nothing to be done for 'reactperfloggerjni'.
  make: Nothing to be done for 'rrc_view'.
  make: Nothing to be done for 'runtimeexecutor'.
  make: Nothing to be done for 'yoga'.
  [armeabi-v7a] StaticLibrary  : libhermes-inspector.a
  
  /Users/transformhub/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/build/intermediates/cxx/Debug/6t2i5mp6/obj/local/armeabi-v7a/libcallinvoker.a: no archive symbol table (run ranlib)
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  make: *** [/Users/transformhub/Library/Android/sdk/ndk/21.4.7075529/build/core/build-binary.mk:725: /Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/build/intermediates/cxx/Debug/6t2i5mp6/obj/local/armeabi-v7a/libreact_render_runtimescheduler.so] Error 1
  make: *** Waiting for unfinished jobs....


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:buildNdkBuildDebug'.
> Build command failed.
  Error while executing process /Users/transformhub/Library/Android/sdk/ndk/21.4.7075529/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/src/main/jni/react/jni/Android.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=/Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/build/intermediates/cxx/Debug/6t2i5mp6/obj NDK_LIBS_OUT=/Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/build/intermediates/cxx/Debug/6t2i5mp6/lib NDK_APPLICATION_MK=/Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/src/main/jni/Application.mk THIRD_PARTY_NDK_DIR=/Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/build/third-party-ndk REACT_COMMON_DIR=/Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/../ReactCommon REACT_GENERATED_SRC_DIR=/Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/build/generated/source REACT_SRC_DIR=/Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react -j8 --output-sync=none butter fabricjni fb folly_futures folly_json glog glog_init hermes-executor-debug hermes-executor-release jscexecutor jsi jsijniprofiler jsinspector logger mapbufferjni react_codegen_rncore react_config react_debug react_nativemodule_core react_render_animations react_render_attributedstring react_render_componentregistry react_render_core react_render_debug react_render_graphics react_render_imagemanager react_render_leakchecker react_render_mapbuffer react_render_mounting react_render_runtimescheduler react_render_scheduler react_render_telemetry react_render_templateprocessor react_render_textlayoutmanager react_render_uimanager react_utils reactnativeblob reactnativejni reactnativeutilsjni reactperfloggerjni rrc_image rrc_root rrc_text rrc_unimplementedview rrc_view runtimeexecutor turbomodulejsijni yoga}
  make: Nothing to be done for 'butter'.
  [armeabi-v7a] SharedLibrary  : librrc_root.so
  [armeabi-v7a] SharedLibrary  : libreact_render_runtimescheduler.so
  [armeabi-v7a] SharedLibrary  : librrc_unimplementedview.so
  make: Nothing to be done for 'fb'.
  make: Nothing to be done for 'folly_futures'.
  make: Nothing to be done for 'folly_json'.
  make: Nothing to be done for 'glog'.
  make: Nothing to be done for 'glog_init'.
  [armeabi-v7a] SharedLibrary  : libreact_render_attributedstring.so
  make: Nothing to be done for 'jsi'.
  make: Nothing to be done for 'jsinspector'.
  make: Nothing to be done for 'logger'.
  make: Nothing to be done for 'mapbufferjni'.
  make: Nothing to be done for 'react_config'.
  make: Nothing to be done for 'react_debug'.
  make: Nothing to be done for 'react_render_componentregistry'.
  make: Nothing to be done for 'react_render_core'.
  make: Nothing to be done for 'react_render_debug'.
  make: Nothing to be done for 'react_render_graphics'.
  make: Nothing to be done for 'react_render_leakchecker'.
  make: Nothing to be done for 'react_render_mapbuffer'.
  make: Nothing to be done for 'react_utils'.
  make: Nothing to be done for 'reactperfloggerjni'.
  make: Nothing to be done for 'rrc_view'.
  make: Nothing to be done for 'runtimeexecutor'.
  make: Nothing to be done for 'yoga'.
  [armeabi-v7a] StaticLibrary  : libhermes-inspector.a
  
  /Users/transformhub/Library/Android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/build/intermediates/cxx/Debug/6t2i5mp6/obj/local/armeabi-v7a/libcallinvoker.a: no archive symbol table (run ranlib)
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  make: *** [/Users/transformhub/Library/Android/sdk/ndk/21.4.7075529/build/core/build-binary.mk:725: /Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/react-native/ReactAndroid/build/intermediates/cxx/Debug/6t2i5mp6/obj/local/armeabi-v7a/libreact_render_runtimescheduler.so] Error 1
  make: *** Waiting for unfinished jobs....


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

    at makeError (/Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/execa/index.js:174:9)
    at /Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/transformhub/Desktop/NewArchitecture/new/firstapp/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
```

The entire code for android turbo module can be found here https://github.com/PritishSawant/reactnativeandroidturbomodules/tree/android-turbomodules-v3

### Version

0.68.2

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.4
    CPU: (8) x64 Apple M1
    Memory: 46.45 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: javac 16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Clone 
https://github.com/PritishSawant/reactnativeandroidturbomodules/tree/android-turbomodules-v3

and try running it on an android simulator

### Snack, code example, screenshot, or link to a repository

https://github.com/PritishSawant/reactnativeandroidturbomodules/tree/android-turbomodules-v3

**Comment by cortinico** [comment]
I quickly tested and I was able to build:
![Screenshot_1655942023](https://user-images.githubusercontent.com/3001957/175182342-54463b54-1c8a-4641-8144-3f40f12551f0.png)

> CPU: (8) x64 Apple M1

I think you're problem is that you're on a M1 and you're using the wrong NDK version (21). You should be on 24.

Are you overriding the NDK version in any form locally?

**Comment by PritishSawant** [comment]
<img width="748" alt="Screenshot 2022-06-23 at 8 18 21 AM" src="https://user-images.githubusercontent.com/24708929/175196383-4fa90d84-152f-4947-a69a-453c4cd5910a.png">
I am using M1 Mac. I have both version 21 and 24 of NDK. Check screenshot. Also attached in screenshot is the check in build.gradle, so it should automatically take the desired ndk, correct? In my case it should be version 24 according to my understanding. This is by default generated when you create react native project.

I don't understand what you mean by  overriding the NDK version in any form locally.


<img width="775" alt="Screenshot 2022-06-23 at 8 19 44 AM" src="https://user-images.githubusercontent.com/24708929/175196584-78037843-757b-4d25-81e5-5c60f494d540.png">

**Comment by cortinico** [comment]
> I don't understand what you mean by overriding the NDK version in any form locally.

I'm wondering if you have some environment variable or local setup that might interfere with the logic you just showed

**Comment by PritishSawant** [comment]
@cortinico  I just noticed v0.69 is out and it has improved support for m1, will this https://github.com/facebook/react-native/commit/c5babd993a2bed2994ecc4710fa9e424b3e6cfc2 solve my issue?

**Comment by PritishSawant** [comment]
Just tried v0.69, I started facing some really weird issues

**Comment by cortinico** [comment]
> I tried running my app in release mode and got it working but I get undefined exactly like the screenshot which you posted. Can you at please help in understanding why I am not getting the value from native side using turbo modules?

Let's keep the conversation focused on a single issue, the `(run ranlib)` one here.

> @cortinico I just noticed v0.69 is out and it has improved support for m1, will this https://github.com/facebook/react-native/commit/c5babd993a2bed2994ecc4710fa9e424b3e6cfc2 solve my issue?

Not necessarily as the change you're referring to has been shipped on 0.68.x as well.

> Just tried v0.69, I started facing some really weird issues

Which specifically? We can't help without error messages/reproducers.

Unless you can provide a reproducer that works on either a CI or a local machine, we can't support any furhter

**Comment by PritishSawant** [comment]
For v0.69 I am facing this issue https://github.com/facebook/react-native/issues/34059

**Comment by cortinico** [comment]
> For v0.69 I am facing this issue https://github.com/facebook/react-native/issues/34059

I'll close this then, and I'll follow over to the other issue.
