### ISSUE TITLE
Error: failed to parse query: must use ["allof", expr...]

### ISSUE THREAD

**Issue by changfuguo** [facebook/react-native#3405]
#  when visit:localhost:8081/index.android.bundle?xxxx,console throw the error below ,how to resolve it ?

Error: failed to parse query: must use ["allof", expr...]
    at BunserBuf.<anonymous> (/Users/baidu/PROJECTS/doukanmv/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:93:23)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/baidu/PROJECTS/doukanmv/node_modules/react-native/node_modules/bser/index.js:289:10)
    at /Users/baidu/PROJECTS/doukanmv/node_modules/react-native/node_modules/bser/index.js:244:12
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

**Comment by changfuguo** [comment]
watchman version is  3.9.0

**Comment by changfuguo** [comment]
delete  nvm watchman  flow ,

reinstall :nvm  node  watchman flow 

restart my computer ,then it is ok
