### ISSUE TITLE
0.12: transformer.js syntax error: Unexpected token ,

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#3408]
I'm getting this syntax error after upgrading to 0.12. 

	/Users/Shared/project/node_modules/react-native/packager/transformer.js:32
		filename,
				^
	SyntaxError: Unexpected token ,
		at exports.runInThisContext (vm.js:53:16)
		at Module._compile (module.js:411:25)
		at Object.Module._extensions..js (module.js:446:10)
		at Module.load (module.js:353:32)
		at Function.Module._load (module.js:308:12)
		at Module.require (module.js:363:17)
		at require (module.js:382:17)
		at process.<anonymous> (/Users/Shared/project/node_modules/react-native/node_modules/worker-farm/lib/child/index.js:45:34)
		at emitTwo (events.js:87:13)
		at process.emit (events.js:169:7)

Very weird. It's stumbling over es6 object literals, which I'm also using myself in the project code. Seems like some babel configuration is not updated properly somewhere

**Comment by mkonicek** [comment]
Can you share your code?

**Comment by mkonicek** [comment]
Can you provide a few lines around where this happens (`/Users/Shared/project/node_modules/react-native/packager/transformer.js:32`)?

**Comment by mschipperheyn** [comment]
I think it's resolved. It was probably related to some non up to date contextual libraries such as nvm. I went back to the basic setup instructions, upgraded everything and I was set

**Comment by ide** [comment]
Closing this out ^
