### ISSUE TITLE
Android Build Failed 

### ISSUE THREAD

**Issue by Victorvikson1996** [facebook/react-native#34119]
### Description

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.eightbitlab:blurview:1.6.3.
     Searched in the following locations:
       - file:/Users/chukwuebuka/Native/Damini/PreBetaMobile/node_modules/react-native/android/com/eightbitlab/blurview/1.6.3/blurview-1.6.3.pom
       - file:/Users/chukwuebuka/Native/Damini/PreBetaMobile/node_modules/jsc-android/dist/com/eightbitlab/blurview/1.6.3/blurview-1.6.3.pom
       - https://repo.maven.apache.org/maven2/com/eightbitlab/blurview/1.6.3/blurview-1.6.3.pom
       - https://dl.google.com/dl/android/maven2/com/eightbitlab/blurview/1.6.3/blurview-1.6.3.pom
       - https://www.jitpack.io/com/eightbitlab/blurview/1.6.3/blurview-1.6.3.pom
     Required by:
         project :app > project :react-native-community_blur

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.eightbitlab:blurview:1.6.3.
     Searched in the following locations:
       - file:/Users/chukwuebuka/Native/Damini/PreBetaMobile/node_modules/react-native/android/com/eightbitlab/blurview/1.6.3/blurview-1.6.3.pom
       - file:/Users/chukwuebuka/Native/Damini/PreBetaMobile/node_modules/jsc-android/dist/com/eightbitlab/blurview/1.6.3/blurview-1.6.3.pom
       - https://repo.maven.apache.org/maven2/com/eightbitlab/blurview/1.6.3/blurview-1.6.3.pom
       - https://dl.google.com/dl/android/maven2/com/eightbitlab/blurview/1.6.3/blurview-1.6.3.pom
       - https://www.jitpack.io/com/eightbitlab/blurview/1.6.3/blurview-1.6.3.pom
     Required by:
         project :app > project :react-native-community_blur

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

    at makeError (/Users/chukwuebuka/Native/Damini/PreBetaMobile/node_modules/execa/index.js:174:9)
    at /Users/chukwuebuka/Native/Damini/PreBetaMobile/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/chukwuebuka/Native/Damini/PreBetaMobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/chukwuebuka/Native/Damini/PreBetaMobile/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
```

### Version

0.68.0

### Output of `npx react-native info`

npx react-native run-android 

### Steps to reproduce

No steps 

### Snack, code example, screenshot, or link to a repository

no code just command

**Comment by GouravNainwaya** [comment]
https://youtu.be/A3--3Ozxz6o?t=180 bro you can watch this

**Comment by cortinico** [comment]
> > Could not find com.eightbitlab:blurview:1.6.3.

Your build is failing as Gradle is not able to find this package.
This issue is not related to React Native core and should be moved to the specific package which is raising it `react-native-blur:` https://github.com/Kureev/react-native-blur
