### ISSUE TITLE
[SOLVED] Android crash on start, missing index.android.bundle, incompatible with gradle > 7.0.4

### ISSUE THREAD

**Issue by nschild** [facebook/react-native#34231]
### Description

Just wanted this on the radar, I couldnt find it with a quick search. 

I ran into this issue today where index.android.bundle was not bieng included in release builds. Turns out someone else had the same issue and had a solution. They suggested to downgrade gradle to 7.0.4 (i had upgraded it to the latest while upgrading RN) and my app is now running.

https://stackoverflow.com/questions/71847922/index-android-bundle-missing-in-apk-after-upgrading-to-rn-0-68

android/build.gradle

    buildscript {
        dependencies {
             classpath('com.android.tools.build:gradle:7.0.4') // must be 7.0.4 or index.android.bundle will not be included in the release apk
        }
    }

### Version

0.66

### Output of `npx react-native info`

N/A

### Steps to reproduce

N/A

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by cortinico** [comment]
Thanks for reporting

> They suggested to downgrade gradle to 7.0.4

Still this is not a "solution". It's a workaround that will create more problem the next time you try to update the React Native version.

I'll close this issue as it's on 0.66. If the issue happens again on 0.69, this should be fixed as it's quite critical

**Comment by Noitham** [comment]
(React Native v0.68.2)

I get the same crash when building an Android app on release mode:

```
2022-08-01 11:09:58.564 6521-6585/? E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.---------------, PID: 6521
    java.lang.RuntimeException: Unable to load script. Make sure you're either running Metro (run 'npx react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.
        at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
        at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:248)
        at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:29)
        at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:277)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1422)
        at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:138)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1111)
        at java.lang.Thread.run(Thread.java:923)

```

**Comment by EvertV** [comment]
I had a similar issue on RN v0.66.5 with gradle 'com.android.tools.build:gradle:7.2.2'. I fixed it by upgrading gradle to 'com.android.tools.build:gradle:7.3.1' (in `android/build.gradle`) and updating this the distributionUrl from 7.3.3 to 7.6.1 `distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.1-all.zip` (in `android/gradle/wrapper/gradle-wrapper.properties`)
