### ISSUE TITLE
Android app is crashing when lauch

### ISSUE THREAD

**Issue by bobfrontdev** [facebook/react-native#34334]
### Description

The app crashes when the user launches the app

### Version

4.14.0

### Output of `npx react-native info`

System:
    OS: macOS 12.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 33.46 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: javac 18 - /usr/bin/javac
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ~0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

//

### Snack, code example, screenshot, or link to a repository

Ijava.lang.RuntimeException: Unable to pause activity {com.app.companyapp/com.company.companyapp.MainActivity}: java.lang.IllegalArgumentException: No view found for id 0x179 (unknown) for fragment h{231f5e9} (3649cfda-7234-463e-8279-d818d877b77c) id=0x179}

at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5557)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5508)
at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6312)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6212)
at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:65)
at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6301)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2448)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.IllegalArgumentException: No view found for id 0x179 (unknown) for fragment h{231f5e9} (3649cfda-7234-463e-8279-d818d877b77c) id=0x179}
at androidx.fragment.app.u.f(FragmentStateManager.java:12)
at androidx.fragment.app.u.m(FragmentStateManager.java:20)
at androidx.fragment.app.v.r(FragmentStore.java:3)
at androidx.fragment.app.n.P0(FragmentManager.java:6)
at androidx.fragment.app.n.U(FragmentManager.java:3)
at androidx.fragment.app.n.O(FragmentManager.java:1)
at androidx.fragment.app.i.m(FragmentController.java:1)
at androidx.fragment.app.e.onPause(FragmentActivity.java:3)
at com.facebook.d1.m.onPause(ReactActivity.java:1)
at android.app.Activity.performPause(Activity.java:8485)
at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1530)
at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5547)

**Comment by cortinico** [comment]
Closing as:

> 4.14.0

This is not a version of React Native.

The reproducer is missing also, there is no way to debug this.
