### ISSUE TITLE
[npm3] Requiring unknown module "regenerator/runtime"

### ISSUE THREAD

**Issue by chentsulin** [facebook/react-native#3434]
It works in npm@2, but not works in npm@3 (in node 4.2.1). Remove node_modules and install twice got same result.

Here is the demo project https://github.com/chentsulin/react-native-counter-ios-android.

Error stack : 

```
Error: 
 stack: Error: Requiring unknown module "regenerator/runtime". If you are sure the module is there, try restarting the packager.
    at Error (native)
    at new ModuleError (http://localhost:8081/index.ios.bundle?platform=ios:109:14)
    at require (http://localhost:8081/index.ios.bundle?platform=ios:213:7)
    at http://localhost:8081/index.ios.bundle?platform=ios:5189:1
    at require (http://localhost:8081/index.ios.bundle?platform=ios:254:15)
    at http://localhost:8081/index.ios.bundle?platform=ios:5070:1
    at require (http://localhost:8081/index.ios.bundle?platform=ios:254:15)
    at http://localhost:8081/index.ios.bundle?platform=ios:1588:33
    at require (http://localhost:8081/index.ios.bundle?platform=ios:254:15)
    at http://localhost:8081/index.ios.bundle?platform=ios:1566:18
 line: undefined
 message: Requiring unknown module "regenerator/runtime". If you are sure the module is there, try restarting the packager. 
```

And `regenerator/runtime` exists in node_modules with it's `runtime.js`

```
Error: 
 stack: Error: Invariant Violation: ReactUpdates: must inject a reconcile transaction class and batching strategy
    at invariant (http://localhost:8081/index.ios.bundle?platform=ios:2021:9)
    at ensureInjected (http://localhost:8081/index.ios.bundle?platform=ios:6329:1)
    at Object.batchedUpdates (http://localhost:8081/index.ios.bundle?platform=ios:6406:1)
    at http://localhost:8081/index.ios.bundle?platform=ios:5528:14
    at guard (http://localhost:8081/index.ios.bundle?platform=ios:5487:1)
    at MessageQueue.processBatch (http://localhost:8081/index.ios.bundle?platform=ios:5527:1)
    at messageHandlers.executeJSCall (http://localhost:8081/debuggerWorker.js:25:73)
    at DedicatedWorkerGlobalScope.onmessage (http://localhost:8081/debuggerWorker.js:42:5)
 line: undefined
 message: Invariant Violation: ReactUpdates: must inject a reconcile transaction class and batching strategy Error: Invariant Violation: ReactUpdates: must inject a reconcile transaction class and batching strategy(…)
```

**Comment by jsierles** [comment]
Still seeing this issue?

**Comment by christopherdro** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

If you'd like you can create an issue on [Product Pains](https://productpains.com/product/react-native).
ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. 

Also, if this issue is a bug, please consider sending a PR with a fix. Thanks!
