### ISSUE TITLE
com.facebook.react.modules.core.ExceptionsManagerModule.reportException(Unknown Source:134)

### ISSUE THREAD

**Issue by bodrius** [facebook/react-native#34361]
### Description

```
FATAL EXCEPTION: mqt_native_modules
Process: com.online.vdf, PID: 31389
f7.c: TypeError: null is not an object (evaluating 'c.SIGN_IN_CANCELLED'), stack:
<unknown>@503:3985
h@2:1585
d@2:958
get@502:215
<unknown>@10:1338
Ul@64:66789
Ha@64:84456
<unknown>@64:82784
Y@180:2883
e@180:400
<unknown>@90:1256
k@90:499
callTimers@90:2652
value@45:3556
<unknown>@45:673
value@45:2503
value@45:645
value@-1
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(Unknown Source:134)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:148)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:147)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
	at java.lang.Thread.run(Thread.java:920)
```

[logcat.txt](https://github.com/facebook/react-native/files/9275670/logcat.txt)

### Version

0.66.4

### Output of `npx react-native info`

```
System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 102.95 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.13.2 - /opt/homebrew/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 32.0.0, 33.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

run command - ./gradlew bundleRelease
deploy bundle to Google Play Console
test on 10 devices and get crash

```
"dependencies": {
    "@fawazahmed/react-native-read-more": "2.3.5",
    "@react-native-async-storage/async-storage": "1.15.11",
    "@react-native-community/clipboard": "1.5.1",
    "@react-native-community/netinfo": "7.1.2",
    "@react-native-community/push-notification-ios": "1.10.1",
    "@react-native-community/viewpager": "5.0.11",
    "@react-native-firebase/analytics": "15.2.0",
    "@react-native-firebase/app": "15.0.2",
    "@react-native-firebase/dynamic-links": "15.0.2",
    "@react-native-firebase/messaging": "15.0.2",
    "@react-native-masked-view/masked-view": "0.2.6",
    "@react-navigation/bottom-tabs": "6.0.9",
    "@react-navigation/drawer": "6.1.8",
    "@react-navigation/native": "6.0.6",
    "@react-navigation/native-stack": "6.2.5",
    "@react-navigation/stack": "6.0.11",
    "@types/react-native-dotenv": "^0.2.0",
    "@types/react-native-keep-awake": "2.0.3",
    "@types/react-native-material-ripple": "0.9.2",
    "@types/react-native-push-notification": "8.1.0",
    "@types/react-native-snap-carousel": "3.8.5",
    "@types/react-native-vector-icons": "6.4.10",
    "@types/react-native-version-check": "3.4.3",
    "@types/react-native-video-player": "0.10.2",
    "@types/shortid": "0.0.29",
    "axios": "0.24.0",
    "dayjs": "1.10.7",
    "formik": "2.2.9",
    "i18next": "21.5.3",
    "lottie-ios": "3.2.3",
    "lottie-react-native": "5.0.1",
    "moment": "2.29.1",
    "react": "17.0.2",
    "react-i18next": "11.14.3",
    "react-native": "0.66.4",
    "react-native-action-button": "2.8.5",
    "react-native-animatable": "1.3.3",
    "react-native-collapsible": "1.6.0",
    "react-native-compressor": "1.5.2",
    "react-native-confetti-cannon": "1.5.2",
    "react-native-dotenv": "3.3.1",
    "react-native-draggable-flatlist": "3.1.2",
    "react-native-element-dropdown": "1.5.10",
    "react-native-fast-image": "8.5.11",
    "react-native-fbsdk-next": "10.0.0",
    "react-native-geocoding": "0.5.0",
    "react-native-gesture-handler": "2.5.0",
    "react-native-gifted-chat": "0.16.3",
    "react-native-hide-with-keyboard": "1.2.1",
    "react-native-iap": "8.0.7",
    "react-native-image-crop-picker": "0.37.3",
    "react-native-image-picker": "4.3.0",
    "react-native-image-slider-box": "1.1.20",
    "react-native-image-viewing": "0.2.1",
    "react-native-keep-awake": "4.0.0",
    "react-native-keyboard-aware-scroll-view": "0.9.5",
    "react-native-localize": "2.1.5",
    "react-native-maps": "0.30.1",
    "react-native-material-menu": "2.0.0",
    "react-native-material-ripple": "0.9.1",
    "react-native-modal": "13.0.0",
    "react-native-modalize": "2.0.13",
    "react-native-permissions": "3.1.0",
    "react-native-portalize": "1.0.7",
    "react-native-push-notification": "8.1.1",
    "react-native-reanimated": "2.9.1",
    "react-native-responsive-screen": "1.4.2",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "3.9.0",
    "react-native-scrollable-tab-view": "git+https://github.com/ptomasroos/react-native-scrollable-tab-view.git",
    "react-native-share": "7.3.5",
    "react-native-shimmer": "0.6.0",
    "react-native-snap-carousel": "3.9.1",
    "react-native-splash-screen": "3.2.0",
    "react-native-store-review": "0.2.1",
    "react-native-svg": "12.1.1",
    "react-native-swipeable": "0.6.0",
    "react-native-text-input-mask": "3.1.4",
    "react-native-text-ticker": "1.14.0",
    "react-native-toast-message": "2.1.1",
    "react-native-vector-icons": "9.0.0",
    "react-native-version-check": "3.4.3",
    "react-native-video": "5.2.0",
    "react-native-video-player": "0.12.0",
    "react-native-walkthrough-tooltip": "1.3.0",
    "react-redux": "7.2.6",
    "redux-devtools-extension": "2.13.9",
    "redux-persist": "6.0.0",
    "redux-thunk": "2.4.0",
    "rn-fetch-blob": "0.12.0",
    "rn-placeholder": "^3.0.3",
    "shortid": "2.2.16",
    "socket.io-client": "4.5.0",
    "yup": "0.32.11"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.23",
    "@types/react-native": "^0.66.4",
    "@types/react-test-renderer": "^17.0.1",
    "@typescript-eslint/eslint-plugin": "^5.7.0",
    "@typescript-eslint/parser": "^5.7.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2",
    "typescript": "^4.4.4"
  },
  "resolutions": {
    "@types/react": "^17"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
```

### Snack, code example, screenshot, or link to a repository

<img width="1423" alt="Screenshot 2022-08-06 at 22 48 53" src="https://user-images.githubusercontent.com/57833393/183264115-bdb78527-6b54-46c1-8df1-a1814f69cd59.png">

**Comment by viv3kk** [comment]
Facing same issue on android, where app just crashed on touch of a button.
