### ISSUE TITLE
Upgrade from 0.61 -> 0.63 fails to create JS Bundle | SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by rishabh876** [facebook/react-native#34422]
### New Version

0.63.4

### Old Version

0.61.4

### Build Target(s)

Android in release mode

### Output of `react-native info`

System:
    OS: macOS 12.4
    CPU: (10) x64 Apple M1 Pro
    Memory: 21.46 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.5.0/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

Debug builds seems to be working fine. But release builds are throwing 1 error in gradle task
:app:bundleReleaseJsAndAssets

**Stacktrace**
> (node:77926) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
> (Use `node --trace-warnings ...` to show where the warning was created)
> /Users/me/Documents/GitHub/MyProject/android/react-native/node_modules/react-native/index.js:13
> import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
> at wrapSafe (internal/modules/cjs/loader.js:1117:16)
> at Module._compile (internal/modules/cjs/loader.js:1165:27)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
> at Module.load (internal/modules/cjs/loader.js:1050:32)
> at Function.Module._load (internal/modules/cjs/loader.js:938:14)
> at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
> at internal/main/run_main_module.js:17:47

**Steps to reproduce:**
Note: _This is also happening on fresh project as well if I Move my React Native root inside Android root folder._
- Download the Sample project (Fresh project I made with just root folder changes)
- cd react-native
- npm i
- npx react-native run-android --variant=release
[Sample Project.zip](https://github.com/facebook/react-native/files/9337858/Sample.Project.zip)
 
 Also posted on [Stackoverflow](https://stackoverflow.com/questions/73304298/syntaxerror-cannot-use-import-statement-outside-a-module-on-android-appbund)

**Comment by rishabh876** [comment]
Ok I figured it out. It was the CLI path that was wrong in app/build.gradle
replaced 
`cliPath          : "node_modules/react-native",`
with 
`cliPath          : "node_modules/react-native/cli.js",`
