### ISSUE TITLE
unable to run the app - npm start fails with watchman --no-pretty error

### ISSUE THREAD

**Issue by aakashlpin** [facebook/react-native#3443]
Started facing this issue today where trying to run `npm start` throws this error. It seems to be related to watchman.

Here's the error
```
Watchman:  watchman--no-pretty get-sockname returned with exit code 1 ERROR: Unknown option --no-pretty
```

Here's the stack trace
```
at ChildProcess.<anonymous> (/Users/aakashlpin/projects/cheapassApp/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:194:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

Any leads on the issue here?

**Comment by aakashlpin** [comment]
Figured the issue. https://github.com/facebook/watchman/issues/167

Closing.
