### ISSUE TITLE
error notarget No matching version found for fontkit@^2.0.2.

### ISSUE THREAD

**Issue by chirup** [facebook/react-native#34545]
### Description

Hello, I have this issue when I am trying to install react-pdf. 

verbose stack fontkit: No matching version found for fontkit@^2.0.2.
204 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
204 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:126:26
204 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
205 verbose cwd /Users/UK45378423/Documents/GitHub/uk-pwa-react-incident-reporting
206 verbose Darwin 21.6.0
207 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@react-pdf/renderer" "--save" "--legacy-peer-dep"
208 verbose node v16.15.0
209 verbose npm  v8.5.5
210 error code ETARGET
211 error notarget No matching version found for fontkit@^2.0.2.
212 error notarget In most cases you or one of your dependencies are requesting
212 error notarget a package version that doesn't exist.
213 verbose exit 1
214 timing npm Completed in 4305ms
215 verbose unfinished npm timer reify 1661953039556
216 verbose unfinished npm timer reify:loadTrees 1661953039561
217 verbose code 1

### Version

3

### Output of `npx react-native info`

N/A

### Steps to reproduce

install react pdf with the latest react version.

### Snack, code example, screenshot, or link to a repository

0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   '@react-pdf/renderer',
0 verbose cli   '--save',
0 verbose cli   '--legacy-peer-dep'
0 verbose cli ]
1 info using npm@8.5.5
2 info using node@v16.15.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/UK45378423/Documents/GitHub/uk-pwa-react-incident-reporting/.npmrc Completed in 1ms
10 timing config:load:project Completed in 4ms
11 timing config:load:file:/Users/__/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 9ms
19 timing npm:load:configload Completed in 9ms
20 timing npm:load:setTitle Completed in 5ms
21 timing config:load:flatten Completed in 1ms
22 timing npm:load:display Completed in 2ms
23 verbose logfile /Users/--/.npm/_logs/2022-08-31T13_37_19_383Z-debug-0.log
24 timing npm:load:logFile Completed in 3ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 19ms
28 timing arborist:ctor Completed in 0ms
29 silly logfile start cleaning logs, removing 1 files
30 timing idealTree:init Completed in 470ms
31 timing idealTree:userRequests Completed in 5ms
32 silly idealTree buildDeps
33 silly fetch manifest @react-pdf/renderer@*
34 timing arborist:ctor Completed in 0ms
35 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/@react-pdf%2frenderer 612ms (cache skip)
36 silly placeDep ROOT @react-pdf/renderer@3.0.0 OK for: safer-stores-pwa@2.0.0 want: *
37 silly fetch manifest @babel/runtime@^7.16.4
38 silly fetch manifest @react-pdf/font@^2.3.0
39 silly fetch manifest @react-pdf/layout@^3.2.0
40 silly fetch manifest @react-pdf/pdfkit@^3.0.0
41 silly fetch manifest @react-pdf/primitives@^3.0.0
42 silly fetch manifest @react-pdf/render@^3.2.1
43 silly fetch manifest @react-pdf/types@^2.1.0
44 silly fetch manifest queue@^6.0.1
45 silly fetch manifest react-reconciler@^0.23.0
46 silly fetch manifest scheduler@^0.17.0
47 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/@react-pdf%2fpdfkit 190ms (cache skip)
48 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/@react-pdf%2ftypes 195ms (cache skip)
49 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/@react-pdf%2fprimitives 231ms (cache skip)
50 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/@react-pdf%2frender 233ms (cache skip)
51 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/@react-pdf%2flayout 240ms (cache skip)
52 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/queue 244ms (cache skip)
53 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/@react-pdf%2ffont 254ms (cache skip)
54 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/@babel%2fruntime 342ms (cache skip)
55 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/scheduler 632ms (cache skip)
56 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/react-reconciler 1201ms (cache skip)
57 timing idealTree:#root Completed in 1930ms
58 silly placeDep ROOT @babel/runtime@7.18.9 REPLACE for: @react-pdf/renderer@3.0.0 want: ^7.16.4
59 silly placeDep ROOT @react-pdf/font@2.3.0 OK for: @react-pdf/renderer@3.0.0 want: ^2.3.0
60 silly placeDep ROOT @react-pdf/layout@3.2.0 OK for: @react-pdf/renderer@3.0.0 want: ^3.2.0
61 silly placeDep ROOT @react-pdf/pdfkit@3.0.0 OK for: @react-pdf/renderer@3.0.0 want: ^3.0.0
62 silly placeDep ROOT @react-pdf/primitives@3.0.1 OK for: @react-pdf/renderer@3.0.0 want: ^3.0.0
63 silly placeDep ROOT @react-pdf/render@3.2.1 OK for: @react-pdf/renderer@3.0.0 want: ^3.2.1
64 silly placeDep ROOT @react-pdf/types@2.1.0 OK for: @react-pdf/renderer@3.0.0 want: ^2.1.0
65 silly placeDep ROOT queue@6.0.2 OK for: @react-pdf/renderer@3.0.0 want: ^6.0.1
66 silly placeDep ROOT react-reconciler@0.23.0 OK for: @react-pdf/renderer@3.0.0 want: ^0.23.0
67 silly placeDep node_modules/@react-pdf/renderer scheduler@0.17.0 OK for: @react-pdf/renderer@3.0.0 want: ^0.17.0
68 silly fetch manifest base64-to-uint8array@^1.0.0
69 silly fetch manifest cross-fetch@^3.1.5
70 silly fetch manifest fontkit@^2.0.2
71 silly fetch manifest is-url@^1.2.4
72 silly fetch manifest @react-pdf/fns@2.0.0
73 silly fetch manifest @react-pdf/image@^2.2.0
74 silly fetch manifest @react-pdf/stylesheet@^4.0.0
75 silly fetch manifest @react-pdf/textkit@^4.1.0
76 silly fetch manifest @react-pdf/yoga@^3.0.0
77 silly fetch manifest @react-pdf/png-js@^2.2.0
78 silly fetch manifest crypto-js@^4.0.0
79 silly fetch manifest vite-compatible-readable-stream@^3.6.1
80 silly fetch manifest abs-svg-path@^0.1.1
81 silly fetch manifest color-string@^1.5.3
82 silly fetch manifest normalize-svg-path@^1.1.0
83 silly fetch manifest parse-svg-path@^0.1.2
84 silly fetch manifest svg-arc-to-cubic-bezier@^3.2.0
85 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/base64-to-uint8array 77ms (cache skip)
86 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/@react-pdf%2ffns 88ms (cache skip)
87 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/@react-pdf%2fyoga 104ms (cache skip)
88 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/fontkit 108ms (cache skip)
89 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/@react-pdf%2fpng-js 110ms (cache skip)
90 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/is-url 112ms (cache skip)
91 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/@react-pdf%2fimage 119ms (cache skip)
92 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/@react-pdf%2fstylesheet 123ms (cache skip)
93 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/cross-fetch 134ms (cache skip)
94 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/parse-svg-path 165ms (cache skip)
95 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/@react-pdf%2ftextkit 176ms (cache skip)
96 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/svg-arc-to-cubic-bezier 179ms (cache skip)
97 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/abs-svg-path 184ms (cache skip)
98 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/color-string 188ms (cache skip)
99 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/vite-compatible-readable-stream 198ms (cache skip)
100 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/normalize-svg-path 242ms (cache skip)
101 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/crypto-js 252ms (cache skip)
102 timing idealTree:node_modules/@react-pdf/renderer Completed in 267ms
103 timing idealTree:node_modules/@babel/runtime Completed in 0ms
104 silly placeDep ROOT base64-to-uint8array@1.0.0 OK for: @react-pdf/font@2.3.0 want: ^1.0.0
105 silly placeDep ROOT cross-fetch@3.1.5 OK for: @react-pdf/font@2.3.0 want: ^3.1.5
106 silly placeDep node_modules/@react-pdf/font fontkit@ OK for: @react-pdf/font@2.3.0 want: ^2.0.2
107 silly placeDep ROOT is-url@1.2.4 OK for: @react-pdf/font@2.3.0 want: ^1.2.4
108 silly fetch manifest node-fetch@2.6.7
109 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/node-fetch 251ms (cache skip)
110 timing idealTree:node_modules/@react-pdf/font Completed in 266ms
111 silly placeDep ROOT @react-pdf/fns@2.0.0 OK for: @react-pdf/layout@3.2.0 want: 2.0.0
112 silly placeDep ROOT @react-pdf/image@2.2.0 OK for: @react-pdf/layout@3.2.0 want: ^2.2.0
113 silly placeDep ROOT @react-pdf/stylesheet@4.0.0 OK for: @react-pdf/layout@3.2.0 want: ^4.0.0
114 silly placeDep ROOT @react-pdf/textkit@4.1.0 OK for: @react-pdf/layout@3.2.0 want: ^4.1.0
115 silly placeDep ROOT @react-pdf/yoga@3.0.0 OK for: @react-pdf/layout@3.2.0 want: ^3.0.0
116 silly fetch manifest hsl-to-hex@^1.0.0
117 silly fetch manifest media-engine@^1.0.3
118 silly fetch manifest hyphen@^1.6.4
119 silly fetch manifest unicode-properties@^1.4.1
120 silly fetch manifest @types/yoga-layout@^1.9.3
121 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/@types%2fyoga-layout 100ms (cache skip)
122 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/hsl-to-hex 104ms (cache skip)
123 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/media-engine 110ms (cache skip)
124 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/hyphen 136ms (cache skip)
125 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/unicode-properties 353ms (cache skip)
126 timing idealTree:node_modules/@react-pdf/layout Completed in 383ms
127 timing idealTree:node_modules/@react-pdf/fns Completed in 1ms
128 silly placeDep ROOT @react-pdf/png-js@2.2.0 OK for: @react-pdf/image@2.2.0 want: ^2.2.0
129 timing idealTree:node_modules/@react-pdf/image Completed in 4ms
130 silly placeDep ROOT crypto-js@4.1.1 OK for: @react-pdf/pdfkit@3.0.0 want: ^4.0.0
131 silly placeDep node_modules/@react-pdf/pdfkit fontkit@ OK for: @react-pdf/pdfkit@3.0.0 want: ^2.0.2
132 silly placeDep ROOT vite-compatible-readable-stream@3.6.1 OK for: @react-pdf/pdfkit@3.0.0 want: ^3.6.1
133 timing idealTree:node_modules/@react-pdf/pdfkit Completed in 4ms
134 timing idealTree:node_modules/@react-pdf/png-js Completed in 0ms
135 timing idealTree:node_modules/@react-pdf/primitives Completed in 0ms
136 silly placeDep ROOT abs-svg-path@0.1.1 OK for: @react-pdf/render@3.2.1 want: ^0.1.1
137 silly placeDep ROOT color-string@1.9.1 OK for: @react-pdf/render@3.2.1 want: ^1.5.3
138 silly placeDep ROOT normalize-svg-path@1.1.0 OK for: @react-pdf/render@3.2.1 want: ^1.1.0
139 silly placeDep ROOT parse-svg-path@0.1.2 OK for: @react-pdf/render@3.2.1 want: ^0.1.2
140 silly placeDep ROOT svg-arc-to-cubic-bezier@3.2.0 OK for: @react-pdf/render@3.2.1 want: ^3.2.0
141 silly fetch manifest simple-swizzle@^0.2.2
142 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/simple-swizzle 84ms (cache skip)
143 timing idealTree:node_modules/@react-pdf/render Completed in 91ms
144 silly placeDep ROOT hsl-to-hex@1.0.0 OK for: @react-pdf/stylesheet@4.0.0 want: ^1.0.0
145 silly placeDep ROOT media-engine@1.0.3 OK for: @react-pdf/stylesheet@4.0.0 want: ^1.0.3
146 silly fetch manifest hsl-to-rgb-for-reals@^1.1.0
147 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/hsl-to-rgb-for-reals 101ms (cache skip)
148 timing idealTree:node_modules/@react-pdf/stylesheet Completed in 107ms
149 silly placeDep ROOT hyphen@1.6.4 OK for: @react-pdf/textkit@4.1.0 want: ^1.6.4
150 silly placeDep node_modules/@react-pdf/textkit unicode-properties@ OK for: @react-pdf/textkit@4.1.0 want: ^1.4.1
151 timing idealTree:node_modules/@react-pdf/textkit Completed in 4ms
152 timing idealTree:node_modules/@react-pdf/types Completed in 0ms
153 silly placeDep ROOT @types/yoga-layout@1.9.4 OK for: @react-pdf/yoga@3.0.0 want: ^1.9.3
154 timing idealTree:node_modules/@react-pdf/yoga Completed in 2ms
155 timing idealTree:node_modules/@types/yoga-layout Completed in 0ms
156 timing idealTree:node_modules/abs-svg-path Completed in 0ms
157 timing idealTree:node_modules/base64-to-uint8array Completed in 0ms
158 silly placeDep ROOT simple-swizzle@0.2.2 OK for: color-string@1.9.1 want: ^0.2.2
159 silly fetch manifest is-arrayish@^0.3.1
160 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/is-arrayish 82ms (cache skip)
161 timing idealTree:node_modules/color-string Completed in 85ms
162 silly placeDep ROOT node-fetch@2.6.7 OK for: cross-fetch@3.1.5 want: 2.6.7
163 silly fetch manifest whatwg-url@^5.0.0
164 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/whatwg-url 154ms (cache skip)
165 timing idealTree:node_modules/cross-fetch Completed in 163ms
166 timing idealTree:node_modules/crypto-js Completed in 0ms
167 silly placeDep ROOT hsl-to-rgb-for-reals@1.1.1 OK for: hsl-to-hex@1.0.0 want: ^1.1.0
168 timing idealTree:node_modules/hsl-to-hex Completed in 4ms
169 timing idealTree:node_modules/hsl-to-rgb-for-reals Completed in 0ms
170 timing idealTree:node_modules/hyphen Completed in 0ms
171 timing idealTree:node_modules/is-url Completed in 0ms
172 timing idealTree:node_modules/media-engine Completed in 0ms
173 silly placeDep node_modules/node-fetch whatwg-url@5.0.0 OK for: node-fetch@2.6.7 want: ^5.0.0
174 silly fetch manifest tr46@~0.0.3
175 silly fetch manifest webidl-conversions@^3.0.0
176 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/webidl-conversions 111ms (cache skip)
177 http fetch GET 200 https://nexus.ourtesco.com/repository/online-web-group/tr46 312ms (cache skip)
178 timing idealTree:node_modules/node-fetch Completed in 315ms
179 timing idealTree:node_modules/normalize-svg-path Completed in 0ms
180 timing idealTree:node_modules/parse-svg-path Completed in 0ms
181 timing idealTree:node_modules/queue Completed in 0ms
182 silly placeDep node_modules/react-reconciler scheduler@0.17.0 OK for: react-reconciler@0.23.0 want: ^0.17.0
183 timing idealTree:node_modules/react-reconciler Completed in 1ms
184 silly placeDep node_modules/simple-swizzle is-arrayish@0.3.2 OK for: simple-swizzle@0.2.2 want: ^0.3.1
185 timing idealTree:node_modules/simple-swizzle Completed in 1ms
186 timing idealTree:node_modules/svg-arc-to-cubic-bezier Completed in 0ms
187 timing idealTree:node_modules/vite-compatible-readable-stream Completed in 0ms
188 timing idealTree:node_modules/@react-pdf/font/node_modules/fontkit Completed in 0ms
189 timing idealTree:node_modules/@react-pdf/pdfkit/node_modules/fontkit Completed in 0ms
190 timing idealTree:node_modules/@react-pdf/renderer/node_modules/scheduler Completed in 0ms
191 timing idealTree:node_modules/@react-pdf/textkit/node_modules/unicode-properties Completed in 0ms
192 silly placeDep node_modules/node-fetch tr46@0.0.3 OK for: whatwg-url@5.0.0 want: ~0.0.3
193 silly placeDep node_modules/node-fetch webidl-conversions@3.0.1 OK for: whatwg-url@5.0.0 want: ^3.0.0
194 timing idealTree:node_modules/node-fetch/node_modules/whatwg-url Completed in 2ms
195 timing idealTree:node_modules/node-fetch/node_modules/tr46 Completed in 0ms
196 timing idealTree:node_modules/node-fetch/node_modules/webidl-conversions Completed in 0ms
197 timing idealTree:node_modules/react-reconciler/node_modules/scheduler Completed in 0ms
198 timing idealTree:node_modules/simple-swizzle/node_modules/is-arrayish Completed in 0ms
199 timing idealTree:buildDeps Completed in 3633ms
200 timing idealTree:fixDepFlags Completed in 16ms
201 timing idealTree Completed in 4124ms
202 timing command:install Completed in 4130ms
203 verbose type range
204 verbose stack fontkit: No matching version found for fontkit@^2.0.2.
204 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
204 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:126:26
204 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
205 verbose cwd /Users/--/Documents/GitHub/uk-pwa-react-incident-reporting
206 verbose Darwin 21.6.0
207 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@react-pdf/renderer" "--save" "--legacy-peer-dep"
208 verbose node v16.15.0
209 verbose npm  v8.5.5
210 error code ETARGET
211 error notarget No matching version found for fontkit@^2.0.2.
212 error notarget In most cases you or one of your dependencies are requesting
212 error notarget a package version that doesn't exist.
213 verbose exit 1
214 timing npm Completed in 4305ms
215 verbose unfinished npm timer reify 1661953039556
216 verbose unfinished npm timer reify:loadTrees 1661953039561
217 verbose code 1
218 error A complete log of this run can be found in:
218 error     /Users/--/.npm/_logs/2022-08-31T13_37_19_383Z-debug-0.log

**Comment by chirup** [comment]
sorry I accidentally raised this in wrong repo
