### ISSUE TITLE
npx react-native init fails

### ISSUE THREAD

**Issue by crayne** [facebook/react-native#34584]
### Description

I ran "npx react-native init Test"
````
 Downloading template
✔ Copying template
✔ Processing template
ℹ Installing dependencies
✔ CocoaPods (https://cocoapods.org/) is not installed. CocoaPods is necessary for the iOS project to run correctly. Do you want to install it? › Yes, with Homebrew
✔ Installing CocoaPods
✖ Installing CocoaPods dependencies (this may take a few minutes)
✖ Installing CocoaPods dependencies (this may take a few minutes)
error Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template.
````
but CocoaPods is installed:
pod --version returns 1.11.3

### Version

8.0.6

### Output of `npx react-native info`

````
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-native-info - Not found
npm ERR! 404 
npm ERR! 404  'react-native-info@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/susancrayne/.npm/_logs/2022-09-02T19_18_29_413Z-debug.log
Install for [ 'react-native-info@latest' ] failed with code 1
````

### Steps to reproduce

see Description above

### Snack, code example, screenshot, or link to a repository

See Description above

**Comment by DoctorJohn** [comment]
Hey, can you post the output of `npx react-native info` again. It looks like you ran `npx react-native-info` instead of `npx react-native info`. Thanks

**Comment by crayne** [comment]
Thank you for your reply.  I am on vacation now without my computer.  I will be back 9/14 and will send you what you requested then.Susan

Sent from Yahoo Mail on Android 
 
  On Mon, Sep 5, 2022 at 9:55 PM, Jonathan ***@***.***> wrote:   


Hey, can you post the output of npx react-native info again. It looks like you ran npx react-native-info instead of npx react-native info. Thanks

**Comment by cortinico** [comment]
Can you run `pod install --verbose` inside the `ios/` folder and post the output?

**Comment by crayne** [comment]
OK, will do shortly
    On Friday, September 16, 2022 at 09:49:51 AM EDT, Nicola Corti ***@***.***> wrote:  
 
 


Can you run pod install --verbose inside the ios/ folder and post the output?

**Comment by crayne** [comment]
npx react-native info
error Unrecognized command "info".

**Comment by crayne** [comment]
pod install --verbose
Traceback (most recent call last):
	4: from /Users/susancrayne/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	3: from /Users/susancrayne/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	2: from /Users/susancrayne/.rvm/gems/ruby-2.6.3/bin/pod:23:in `<main>'
	1: from /Users/susancrayne/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
/Users/susancrayne/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems.rb:284:in `find_spec_for_exe': can't find gem cocoapods (>= 0.a) with executable pod (Gem::GemNotFoundException)

**Comment by crayne** [comment]
Hey, are there any insights on this?

**Comment by crayne** [comment]
Thank you for you reply.  Here is what happens when I try to install ruby 2.7.5:
````
MacBook-Pro:glurg susancrayne$ rvm install "ruby-2.7.5"
Warning, new version of rvm available '1.29.12', you are using older version '1.29.10'.
You can disable this warning with:   echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable auto-update with:     echo rvm_autoupdate_flag=2 >> ~/.rvmrc
You can update manually with:        rvm get VERSION                         (e.g. 'rvm get stable')

ruby-2.7.5 - #removing src/ruby-2.7.5..
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/12.0/x86_64/ruby-2.7.5.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
opencl-icd-loader

You have 27 outdated formulae and 1 outdated cask installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

==> Upgrading 2 outdated packages:
libksba 1.6.0 -> 1.6.1
zlib 1.2.12 -> 1.2.12_1
==> Downloading https://ghcr.io/v2/homebrew/core/zlib/manifests/1.2.12_1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/zlib/blobs/sha256:bdfd57b2672b1
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libksba/manifests/1.6.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libksba/blobs/sha256:1f6a8d0652
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Upgrading zlib
  1.2.12 -> 1.2.12_1 

==> Pouring zlib--1.2.12_1.monterey.bottle.tar.gz
==> Caveats
zlib is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

For compilers to find zlib you may need to set:
  export LDFLAGS="-L/usr/local/opt/zlib/lib"
  export CPPFLAGS="-I/usr/local/opt/zlib/include"

==> Summary
🍺  /usr/local/Cellar/zlib/1.2.12_1: 12 files, 407.9KB
==> Running `brew cleanup zlib`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /usr/local/Cellar/zlib/1.2.12... (12 files, 407KB)
==> Upgrading libksba
  1.6.0 -> 1.6.1 

==> Pouring libksba--1.6.1.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/libksba/1.6.1: 18 files, 492.2KB
==> Running `brew cleanup libksba`...
Removing: /usr/local/Cellar/libksba/1.6.0... (18 files, 488.9KB)
Removing: /Users/susancrayne/Library/Caches/Homebrew/libksba--1.6.0... (170.3KB)
==> Upgrading 1 dependent of upgraded formulae:
Disable this behaviour by setting HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
mysql 8.0.30 -> 8.0.30_1
==> Downloading https://ghcr.io/v2/homebrew/core/icu4c/manifests/71.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/icu4c/blobs/sha256:87617a04333c
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/protobuf/manifests/21.6
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/protobuf/blobs/sha256:a2896da73
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/mysql/manifests/8.0.30_1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/mysql/blobs/sha256:084a01b67a7b
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Upgrading mysql
  8.0.30 -> 8.0.30_1 

==> Installing dependencies for mysql: icu4c and protobuf
==> Installing mysql dependency: icu4c
==> Pouring icu4c--71.1.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/icu4c/71.1: 262 files, 76.2MB
==> Installing mysql dependency: protobuf
==> Pouring protobuf--21.6.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/protobuf/21.6: 279 files, 19MB
==> Installing mysql
==> Pouring mysql--8.0.30_1.monterey.bottle.tar.gz
==> Caveats
We've installed your MySQL database without a root password. To secure it run:
    mysql_secure_installation

MySQL is configured to only allow connections from localhost by default

To connect run:
    mysql -uroot

To restart mysql after an upgrade:
  brew services restart mysql
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/mysql/bin/mysqld_safe --datadir=/usr/local/var/mysql
==> Summary
🍺  /usr/local/Cellar/mysql/8.0.30_1: 312 files, 296.2MB
==> Running `brew cleanup mysql`...
Removing: /usr/local/Cellar/mysql/8.0.30... (312 files, 296.2MB)
==> Checking for dependents of upgraded formulae...
==> No broken dependents to reinstall!
==> `brew cleanup` has not been run in the last 30 days, running now...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /usr/local/Cellar/autoconf/2.69... (70 files, 3.0MB)
Removing: /usr/local/Cellar/freetype/2.10.1... (61 files, 2.2MB)
Removing: /usr/local/Cellar/freetype/2.10.2... (61 files, 2.3MB)
Removing: /usr/local/Cellar/freetype/2.6_1... (61 files, 2.5MB)
Removing: /usr/local/Cellar/freetype/2.8... (63 files, 2.6MB)
Removing: /usr/local/Cellar/gettext/0.19.5.1... (1,926 files, 16.2MB)
Removing: /usr/local/Cellar/gettext/0.19.8.1... (1,934 files, 16.9MB)
Removing: /usr/local/Cellar/gettext/0.20.2_1... (1,929 files, 18.7MB)
Removing: /usr/local/Cellar/ghostscript/9.16... (720 files, 57.9MB)
Removing: /usr/local/Cellar/ghostscript/9.52... (671 files, 87.6MB)
Removing: /Users/susancrayne/Library/Caches/Homebrew/glib--2.72.3... (6MB)
Removing: /usr/local/Cellar/gnu-getopt/2.36... (10 files, 166.2KB)
Removing: /usr/local/Cellar/icu4c/58.2... (242 files, 65MB)
Removing: /usr/local/Cellar/icu4c/63.1... (254 files, 68.4MB)
Removing: /usr/local/Cellar/icu4c/67.1... (258 files, 71.4MB)
Removing: /usr/local/Cellar/icu4c/70.1... (261 files, 74.4MB)
Removing: /Users/susancrayne/Library/Caches/Homebrew/icu4c--70.1... (27.8MB)
Removing: /Users/susancrayne/Library/Caches/Homebrew/imagemagick--7.1.0-45... (10.2MB)
Removing: /usr/local/Cellar/jbig2dec/0.12... (11 files, 274.0KB)
Removing: /usr/local/Cellar/libde265/1.0.5... (22 files, 2MB)
Removing: /usr/local/Cellar/libevent/2.1.8... (847 files, 2.2MB)
Removing: /Users/susancrayne/Library/Caches/Homebrew/libffi--3.4.2... (186.6KB)
Removing: /usr/local/Cellar/libgpg-error/1.38... (26 files, 913.5KB)
Removing: /Users/susancrayne/Library/Caches/Homebrew/libheif--1.12.0_2... (1.3MB)
Removing: /usr/local/Cellar/libomp/10.0.0... (9 files, 1.3MB)
Removing: /usr/local/Cellar/libtiff/4.0.4... (259 files, 3.4MB)
Removing: /usr/local/Cellar/libtiff/4.1.0... (247 files, 3.6MB)
Removing: /usr/local/Cellar/little-cms2/2.11... (21 files, 1MB)
Removing: /usr/local/Cellar/little-cms2/2.7... (17 files, 1MB)
Removing: /Users/susancrayne/Library/Caches/Homebrew/node--18.8.0... (13.2MB)
Removing: /usr/local/Cellar/openexr/2.5.2... (152 files, 6.6MB)
Removing: /usr/local/Cellar/openjpeg/2.3.1... (516 files, 13.9MB)
Removing: /usr/local/Cellar/pcre/8.42... (204 files, 5.3MB)
Removing: /usr/local/Cellar/pcre/8.44... (204 files, 5.5MB)
Removing: /usr/local/Cellar/protobuf/21.5... (279 files, 19MB)
Removing: /Users/susancrayne/Library/Caches/Homebrew/protobuf--21.5... (4.9MB)
Removing: /Users/susancrayne/Library/Caches/Homebrew/python@3.8--3.8.13_2... (18.4MB)
Removing: /usr/local/Cellar/readline/8.0.4... (48 files, 1.5MB)
Removing: /usr/local/Cellar/readline/8.1... (48 files, 1.6MB)
Removing: /Users/susancrayne/Library/Caches/Homebrew/ruby-build--20220726... (60KB)
Removing: /usr/local/Cellar/shared-mime-info/2.0... (86 files, 4.4MB)
Removing: /Users/susancrayne/Library/Caches/Homebrew/sqlite--3.39.2... (2MB)
Removing: /usr/local/Cellar/webp/1.1.0... (39 files, 2.1MB)
Removing: /usr/local/Cellar/x265/3.4... (11 files, 35.5MB)
Removing: /usr/local/Cellar/xz/5.2.1... (91 files, 1.4MB)
Removing: /usr/local/Cellar/xz/5.2.4... (92 files, 1MB)
Removing: /usr/local/Cellar/xz/5.2.5... (92 files, 1.1MB)
Removing: /Users/susancrayne/Library/Caches/Homebrew/fmt--9.0.0... (291.6KB)
Removing: /Users/susancrayne/Library/Caches/Homebrew/folly--2022.08.15.00... (5.8MB)
Removing: /Users/susancrayne/Library/Caches/Homebrew/portable-ruby-2.6.8.yosemite.bottle.tar.gz... (8.8MB)
Removing: /Users/susancrayne/Library/Caches/Homebrew/fizz--2022.08.15.00... (1MB)
Removing: /Users/susancrayne/Library/Caches/Homebrew/Cask/adoptopenjdk11--11.0.11,9.pkg... (182.4MB)
Removing: /Users/susancrayne/Library/Logs/Homebrew/libheif... (203B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/libtiff... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/libtool... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/coreutils... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/gmp... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/libksba... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/ilmbase... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/little-cms2... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/ghostscript... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/gdbm... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/gnu-getopt... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/freetype... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/imath... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/liblqr... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/openjpeg... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/xmlto... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/brotli... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/icu4c... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/shared-mime-info... (210B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/glib... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/readline... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/aom... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/libde265... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/lz4... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/webp... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/ruby-build... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/sqlite... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/libgpg-error... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/yarn... (100B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/zlib... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/xz... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/openexr... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/fontconfig... (76.3KB)
Removing: /Users/susancrayne/Library/Logs/Homebrew/giflib... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/docbook-xsl... (28 files, 5.5KB)
Removing: /Users/susancrayne/Library/Logs/Homebrew/libfido2... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/libvmaf... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/ca-certificates... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/gettext... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/libcbor... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/zstd... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/mysql... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/jbig2dec... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/autoconf... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/m4... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/libraw... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/libevent... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/openssl@1.1... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/pcre... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/jpeg-xl... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/libidn... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/docbook... (15 files, 2.6KB)
Removing: /Users/susancrayne/Library/Logs/Homebrew/x265... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/node... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/libomp... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/python@3.8... (3 files, 5.3KB)
Removing: /Users/susancrayne/Library/Logs/Homebrew/imagemagick... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/jasper... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/protobuf... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/rbenv... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/automake... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/libffi... (64B)
Removing: /Users/susancrayne/Library/Logs/Homebrew/jpeg-turbo... (64B)
Removing: /usr/local/lib/python3.8/site-packages/__pycache__/easy_install.cpython-38.pyc... (287B)
Removing: /usr/local/lib/python3.8/site-packages/__pycache__/sitecustomize.cpython-38.pyc... (1.4KB)
Pruned 86 symbolic links and 70 directories from /usr/local
==> Caveats
==> zlib
zlib is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

For compilers to find zlib you may need to set:
  export LDFLAGS="-L/usr/local/opt/zlib/lib"
  export CPPFLAGS="-I/usr/local/opt/zlib/include"

==> mysql
We've installed your MySQL database without a root password. To secure it run:
    mysql_secure_installation

MySQL is configured to only allow connections from localhost by default

To connect run:
    mysql -uroot

To restart mysql after an upgrade:
  brew services restart mysql
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/mysql/bin/mysqld_safe --datadir=/usr/local/var/mysql
Updating certificates bundle '/usr/local/etc/openssl@1.1/cert.pem'
Requirements installation successful.
Installing Ruby from source to: /Users/susancrayne/.rvm/rubies/ruby-2.7.5, this may take a while depending on your cpu(s)...
ruby-2.7.5 - #downloading ruby-2.7.5, this may take a while depending on your connection...
ruby-2.7.5 - #extracting ruby-2.7.5 to /Users/susancrayne/.rvm/src/ruby-2.7.5..|
ruby-2.7.5 - #configuring......................................................|
ruby-2.7.5 - #post-configuration.
ruby-2.7.5 - #compiling....................
Error running '__rvm_make -j8',
please read /Users/susancrayne/.rvm/log/1663763386_ruby-2.7.5/make.log

There has been an error while running make. Halting the installation.
````

**Comment by crayne** [comment]
BTW my react-native version is 0.66.2

**Comment by cortinico** [comment]
> Thank you for you reply. Here is what happens when I try to install ruby 2.7.5:

I don't know what's going on with your setup and we can't offer support for every specific configuration sadly. This seems like an issue specific to your setup.

```
Error running '__rvm_make -j8',
please read /Users/susancrayne/.rvm/log/1663763386_ruby-2.7.5/make.log
```

Have you tried googling for this error?
A simple Github Search brings this up: https://github.com/rvm/rvm/issues/5202

**Comment by cortinico** [comment]
> Have you tried googling for this error?

Closing as I received no further responses
