### ISSUE TITLE
Upgrade to 0.70.0 Js Bundle Error

### ISSUE THREAD

**Issue by lvlrSajjad** [facebook/react-native#34604]
### New Version

0.70.0

### Old Version

0.69.5

### Build Target(s)

Android 11/ iOS 15-16

### Output of `react-native info`

```
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 39.60 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.06.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/lvlrx/.rvm/rubies/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.70.0 => 0.70.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Issue and Reproduction Steps

After upgrading to 0.70.0 (Hermes enabled)
I can build for both Operating Systems but I encounter this error in the metro terminal after it bundles the js:
```
 ERROR  SyntaxError: 474881:28:Invalid regular expression: Quantifier has nothing to repeat, js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
Error: ENOENT: no such file or directory, open '/path/to/my/project/unknown'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at getCodeFrame (/path/to/my/project/node_modules/metro/src/Server.js:1028:18)
    at Server._symbolicate (/path/to/my/project/node_modules/metro/src/Server.js:1101:22)
```
I think it basically has some issues with finding the entry file. 
Do I miss something?
It was fine with 0.69.5 (Hermes enabled)

I also cannot build release for android using `./gradlew bundleRelease`
Encountering this error:
```
> Task :app:bundleReleaseJsAndAssets
info Writing bundle output to:, /path/to/my/project/android/app/build/generated/assets/react/release/index.android.bundle
info Writing sourcemap output to:, /path/to/my/project/android/app/build/intermediates/sourcemaps/react/release/index.android.bundle.packager.map
info Done writing bundle output
info Done writing sourcemap output
info Copying 8 asset files
info Done copying assets
/path/to/my/project/android/app/build/generated/assets/react/release/index.android.bundle:404637:28: error: Invalid regular expression: Quantifier has nothing to repeat
  var RFC3339 = new RegExp(/^(?<Y>\d{4})-(?<M>\d{2})-(?<D>\d{2})[tT](?<H>\d{2}):(?<m>\d{2}):(?<s>\d{2})(?:\.(?<frac>\d+))?[zZ]$/);
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/my/project/android/app/build/generated/assets/react/release/index.android.bundle:404661:32: error: Invalid regular expression: Quantifier has nothing to repeat
  var IMF_FIXDATE = new RegExp(/^(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun), (?<D>\d{2}) (?<M>Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) (?<Y>\d{4}) (?<H>\d{2}):(?<m>\d{2}):(?<s>\d{2})(?:\.(?<frac>\d+))? GMT$/);
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/my/project/android/app/build/generated/assets/react/release/index.android.bundle:404662:33: error: Invalid regular expression: Quantifier has nothing to repeat
  var RFC_850_DATE = new RegExp(/^(?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday), (?<D>\d{2})-(?<M>Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)-(?<Y>\d{2}) (?<H>\d{2}):(?<m>\d{2}):(?<s>\d{2})(?:\.(?<frac>\d+))? GMT$/);
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/my/project/android/app/build/generated/assets/react/release/index.android.bundle:404663:29: error: Invalid regular expression: Quantifier has nothing to repeat
  var ASC_TIME = new RegExp(/^(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun) (?<M>Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) (?<D> [1-9]|\d{2}) (?<H>\d{2}):(?<m>\d{2}):(?<s>\d{2})(?:\.(?<frac>\d+))? (?<Y>\d{4})$/);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

> Task :app:bundleReleaseJsAndAssets FAILED

> Task :react-native-reanimated:buildCMakeRelWithDebInfo[x86]
C/C++: ninja: Entering directory `/path/to/my/project/node_modules/react-native-reanimated/android/.cxx/RelWithDebInfo/59173z65/x86'
C/C++: ../../../../src/main/cpp/NativeProxy.cpp:357:11: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
C/C++: ../../../../src/main/cpp/NativeProxy.cpp:357:11: note: remove std::move call here
C/C++: ../../../../src/main/cpp/NativeProxy.cpp:360:11: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
C/C++: ../../../../src/main/cpp/NativeProxy.cpp:360:11: note: remove std::move call here

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script '/path/to/my/project/node_modules/react-native/react.gradle' line: 286

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command '/path/to/my/project/node_modules/react-native/sdks/hermesc/osx-bin/hermesc'' finished with non-zero exit value 2

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 2 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 4m 40s
940 actionable tasks: 32 executed, 908 up-to-date

```

**Comment by lvlrSajjad** [comment]
I just fixed it by editing my `metro.config.js` by setting `inlineRequires` to `true` as it was `false` before.

**Comment by rranjan14** [comment]
@lvlrSajjad I tried your solution. It didn't work for me.
