### ISSUE TITLE
Upgrade 0.70 RN | Android | E/ReactNativeJS: TypeError: _.default.createNode is not a function.

### ISSUE THREAD

**Issue by mantmartini** [facebook/react-native#34945]
### New Version

0.70

### Old Version

0.64.2

### Build Target(s)

Emulator Android 12 Google Play | x86_64

### Output of `react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 1.04 GB / 31.69 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.19.2 - ~\AppData\Roaming\npm\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, 
android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64      
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9014738
    Visual Studio: Not Found
  Languages:
    Java: 11.0.15
  npmPackages:
    @react-native-community/cli: ^9.0.0 => 9.1.3
    react: ^18.1.0 => 18.1.0
    react-native: ^0.70.0 => 0.70.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

When I try to build the app and run it in the android emulator, I get the following error in the logcat: 

**E/ReactNativeJS: TypeError: _.default.createNode is not a function. (In '_.default.createNode(this.__nodeID,Object.assign({},this.__nodeConfig))', '_.default.createNode' is undefined)**

I would appreciate any help. Thanks!

Error: 

2022-10-11 11:54:37.042 11329-11454/com.restlessnetwork E/ReactNativeJS: TypeError: _.default.createNode is not a function. (In '_.default.createNode(this.__nodeID,Object.assign({},this.__nodeConfig))', '_.default.createNode' is undefined)
2022-10-11 11:54:37.050 11329-11454/com.restlessnetwork E/ReactNativeJS: Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
            A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
2022-10-11 11:54:37.056 11329-11455/com.restlessnetwork E/unknown:ReactNative: Exception in native call
    com.facebook.react.common.JavascriptException: TypeError: _.default.createNode is not a function. (In '_.default.createNode(this.__nodeID,Object.assign({},this.__nodeConfig))', '_.default.createNode' is undefined), stack:
    value@1775:2148
    value@1775:1366
    _@1787:1448
    <unknown>@1787:163
    <unknown>@1785:211
    <unknown>@1781:896
    h@2:1707
    <unknown>@1776:195
    h@2:1707
    <unknown>@1774:278
    h@2:1707
    <unknown>@1769:8018
    h@2:1707
    <unknown>@1768:988
    h@2:1707
    <unknown>@1767:571
    h@2:1707
    <unknown>@1741:386
    h@2:1707
    <unknown>@1739:602
    h@2:1707
    <unknown>@1738:1230
    h@2:1707
    <unknown>@1737:126
    h@2:1707
    <unknown>@383:641
    h@2:1707
    <unknown>@382:167
    h@2:1707
    <unknown>@6:57
    h@2:1707
    d@2:1080
    global code@3376:3
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.jni.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:920)
2022-10-11 11:54:37.060 11329-11455/com.restlessnetwork E/unknown:ReactNative: Exception in native call
    com.facebook.react.common.JavascriptException: Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
            A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., stack:
    <unknown>@29:289
    value@53:3310
    <unknown>@53:759
    value@53:2583
    value@53:731
    value@-1
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.jni.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:920)

**Comment by PedroHSodre** [comment]
same issue, any updates ?

**Comment by Yandamuri** [comment]
facing same error with


```
"react": "18.2.0",
 "react-native": "0.71.8",

```

**Comment by Quintis1212** [comment]
same issue

**Comment by Shizerq** [comment]
Found fix that worked for me after updating to 0.72.5

https://github.com/facebook/react-native/issues/38535#issuecomment-1740839067

**Comment by percyavaur** [comment]
Same here, any solutions?

**Comment by OxamaHxn** [comment]
Same issue with react native 0.70.6

**Comment by cortinico** [comment]
Closing as this issue is related to a version of React Native that we're not supporting anymore (0.70.x). I'd suggest you seek support on StackOverflow or other forums
