### ISSUE TITLE
Error when load js

### ISSUE THREAD

**Issue by tyro668** [facebook/react-native#3507]
[12:31:23] <START> find dependencies
TypeError: Cannot read property 'root' of null
    at /Users/richie/Desktop/AwesomeProject/node_modules/react-native/packager/react-packager/src/DependencyResolver/crawlers/index.js:16:84
    at tryCallOne (/Users/richie/Desktop/AwesomeProject/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/richie/Desktop/AwesomeProject/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/richie/Desktop/AwesomeProject/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

**Comment by foghina** [comment]
We need more info, like what OS you are running, how you are starting the packager server, what node modules you are using etc...

**Comment by chenchen1008** [comment]
you should update your watchman.

**Comment by tyro668** [comment]
@chenchen1008 tks，after update watchman， I have resoved the problem
