### ISSUE TITLE
Didn't find class "com.facebook.imagepipeline.debug.FlipperImageTracker"

### ISSUE THREAD

**Issue by Yandamuri** [facebook/react-native#35269]
### Description

React-Native app crash is happening while app is in run time. Here is the log from Android Studio,

```
2022-11-09 10:55:50.497 8798-8924/<packagename> E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: <packagename>, PID: 8798
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/imagepipeline/debug/FlipperImageTracker;
        at com.facebook.flipper.plugins.fresco.FrescoFlipperPlugin.<init>(FrescoFlipperPlugin.java:113)
        at <packagename>.ReactNativeFlipper$2$1.run(ReactNativeFlipper.java:62)
        at android.os.Handler.handleCallback(Handler.java:978)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:238)
        at android.os.Looper.loop(Looper.java:357)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:1012)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.imagepipeline.debug.FlipperImageTracker" on path: DexPathList[[zip file "/data/app/~~wHGnpzND6d8FdPD7k_mang==/<packagename>-kUqfbrWNs5hKMm5LpIt-kw==/base.apk"],nativeLibraryDirectories=[/data/app/~~wHGnpzND6d8FdPD7k_mang==/<packagename>-kUqfbrWNs5hKMm5LpIt-kw==/lib/arm64, /data/app/~~wHGnpzND6d8FdPD7k_mang==/<packagename>-kUqfbrWNs5hKMm5LpIt-kw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.facebook.flipper.plugins.fresco.FrescoFlipperPlugin.<init>(FrescoFlipperPlugin.java:113) 
        at <packagename>.ReactNativeFlipper$2$1.run(ReactNativeFlipper.java:62) 
        at android.os.Handler.handleCallback(Handler.java:978) 
        at android.os.Handler.dispatchMessage(Handler.java:104) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loopOnce(Looper.java:238) 
        at android.os.Looper.loop(Looper.java:357) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:1012) 
```

### Version

React Native: "0.62.2"

### Output of `npx react-native info`

```
System:
    OS: macOS 12.5
    CPU: (8) x64 Apple M1
    Memory: 49.55 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.0.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

I observed app crash few seconds after starting the app. Hence, I am unable to produce the exact reproducible steps

### Snack, code example, screenshot, or link to a repository

I am unable to provide the reproducible demo.

Other Details:

```
Android Studio: Android Studio Dolphin | 2021.3.1 Patch 1
Android Version: 11
Device: Moto Edge 20 Fusion
React Native: "0.62.2"
```

**Comment by cortinico** [comment]
>     java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/imagepipeline/debug/FlipperImageTracker;

That's unrelated to React Native but that's related to Flipper:
Please open this issue against this other repository:

https://github.com/facebook/flipper/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
