### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so

### ISSUE THREAD

**Issue by ankitagnihotri** [facebook/react-native#35323]
### Description

The app is crashing when anyone tries to rename the package of the release build with the cloner app & launching it. In firebase, issue is reported several times with a rooted package name.

### Version

0.66.5

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Apple M1
    Memory: 27.25 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.19.1 - /opt/homebrew/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-30 | ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs ARM 64 v8a
      Android NDK: 25.0.8775105
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.5 => 0.66.5
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Install the release build,
2. Try to clone the app with any clone app. I am checking with 'App Cloner',
3. After cloning, Launch the cloned app. It is crashing

### Snack, code example, screenshot, or link to a repository

Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so
	SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/~~W5UKy_NhWL8_GfKnhlz_-w==/com.dealsharh-iaGWcq1hRCBtTdXYG3nNZw==/lib/arm64 flags = 0]
	SoSource 1: com.facebook.soloader.DirectApkSoSource[root = (/data/app/~~W5UKy_NhWL8_GfKnhlz_-w==/com.dealsharh-iaGWcq1hRCBtTdXYG3nNZw==/base.apk!/lib/arm64-v8a, )]
	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
	Native lib dir: /data/app/~~W5UKy_NhWL8_GfKnhlz_-w==/com.dealsharh-iaGWcq1hRCBtTdXYG3nNZw==/lib/arm64
 result: 0
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1127)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:943)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:855)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:802)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:772)
       at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:34)
       at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:17)
       at com.facebook.react.bridge.Arguments.createMap(Arguments.java:159)
       at io.invertase.firebase.messaging.ReactNativeFirebaseMessagingSerializer.remoteMessageToWritableMap(ReactNativeFirebaseMessagingSerializer.java:69)
       at io.invertase.firebase.messaging.ReactNativeFirebaseMessagingStoreImpl.storeFirebaseMessage(ReactNativeFirebaseMessagingStoreImpl.java:28)
       at io.invertase.firebase.messaging.ReactNativeFirebaseMessagingReceiver.onReceive(ReactNativeFirebaseMessagingReceiver.java:33)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4628)
       at android.app.ActivityThread.access$1900(ActivityThread.java:284)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2295)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:334)
       at android.app.ActivityThread.main(ActivityThread.java:8396)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

**Comment by ankitagnihotri** [comment]
Tried with following soLoader library version:

  implementation 'com.facebook.soloader:soloader:0.10.4'

It is still not working

**Comment by kirannk-1306** [comment]
Hi Team, I am facing similar crash issue. Any workarounds to resolve the issue? Thanks.

**Comment by SoohyungJung** [comment]
I'm facing the same issue as well :(

**Comment by cortinico** [comment]
This and all the "couldn't find DSO to load" bugs have been fixed in React Native 0.71.

The issue on previous versions was a "too aggressive" clean-up logic in the `react.gradle` file. In 0.71 the clean-up logic has been rewritten to be more Android friendly and is now living inside the React Native Gradle Plugin.

I'm closing this, please update to 0.71 and open a new issue if the "couldn't find DSO to load" crash is still happening on 0.71+.
