### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by chatofking** [facebook/react-native#35330]
### Description

it show source code instead
& when i try 
npm start >> press w
it shows 
```
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\User\Projects\robinhacks\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\User\Projects\robinhacks\node_modules\webpack\lib\NormalModule.js:417:16)
    at Array.<anonymous> (C:\Users\User\Projects\robinhacks\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\User\Projects\robinhacks\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\User\Projects\robinhacks\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Users\User\Projects\robinhacks\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

### Version

18.2.0

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400F
    Memory: 8.31 GB / 15.86 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npx create-expo-app robinhacks --template
npx expo install @expo/webpack-config@^0.17.2
npm run web

### Snack, code example, screenshot, or link to a repository

-

**Comment by Jamal-ReachFirst** [comment]
Reopen this issue
