### ISSUE TITLE
Error: Command failed: yarn add react-native@latest

### ISSUE THREAD

**Issue by GouravNainwaya** [facebook/react-native#35437]
### Description

this error was when comes i was init a new react native project this error comes

### Log: 

× Downloading template
error Error: Command failed: yarn add react-native@latest
warning ..\..\..\..\package.json: No license field
warning react-native > @react-native-community/cli > @react-native-community/cli-plugin-metro > metro > metro-minify-uglify > uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
error An unexpected error occurred: "https://registry.yarnpkg.com/react-native/-/react-native-0.70.6.tgz: ENOSPC: no space left on device, write".
yarn add v1.22.18
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\goura\\AppData\\Local\\Temp\\rncli-init-template-BsW1lL\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
.
Error: Error: Command failed: yarn add react-native@latest
warning ..\..\..\..\package.json: No license field
warning react-native > @react-native-community/cli > @react-native-community/cli-plugin-metro > metro > metro-minify-uglify > uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
error An unexpected error occurred: "https://registry.yarnpkg.com/react-native/-/react-native-0.70.6.tgz: ENOSPC: no space left on device, write".
yarn add v1.22.18
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\goura\\AppData\\Local\\Temp\\rncli-init-template-BsW1lL\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

    at createFromTemplate (C:\Users\goura\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\@react-native-community\cli\build\commands\init\init.js:169:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.initialize [as func] (C:\Users\goura\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\@react-native-community\cli\build\commands\init\init.js:222:3)
    at async Command.handleAction (C:\Users\goura\AppData\Local\npm-cache\_npx\7930a8670f922cdb\node_modules\@react-native-community\cli\build\index.js:140:9)
info Run CLI with --verbose flag for more details.

### Version

0.70.6

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 610.34 MB / 3.89 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29, 30, 31
      Build Tools: 23.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.2, 31.0.0
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.8-internal - C:\Program Files\OpenJDK\jdk-11.0.8.10-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

...

### Snack, code example, screenshot, or link to a repository

...

**Comment by cortinico** [comment]
Essentially a duplicate of https://github.com/react-native-community/cli/issues/946
Please find the suggested solution over there

**Comment by estebansabo** [comment]
Check if your "C:\Users\YourUser" has a folder named "node_modules" and/or some files named "package.json, package.lock, yarn.lock". Move that to another folder and try.

**Comment by yunusaslancan** [comment]
@estebansabo  Hi, I have moved the files under the directory you specified to another folder, but the error continues as follows:
rror Error: Command failed: yarn add react-native@latest
warning react-native > @react-native-community/cli > @react-native-community/cli-plugin-metro > metro > metro-minify-uglify > uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated

can you help me ?

**Comment by Developer-34** [comment]
Install the latest version of Node and Yarn or Npm

**Comment by ljhs88** [comment]
安装最新的Node

**Comment by AND-GORNIY** [comment]
nvm use 18

**Comment by matthart-com** [comment]
Getting on the latest node version fixed this for me `nvm use stable`
