### ISSUE TITLE
i can not  run success with  default code  &&  i get a  message  

### ISSUE THREAD

**Issue by cxh80301983** [facebook/react-native#3559]
error
react-packager has encountered an internal error, please check your terminal error output for more details

Terminal:

/Users/willclass/Documents/DemoProject/node_modules/react-native/packager/transformer.js:13
const babel = require('babel-core');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at process.<anonymous> (/Users/willclass/Documents/DemoProject/node_modules/react-native/node_modules/worker-farm/lib/child/index.js:45:34)
    at process.emit (events.js:110:17)
    at handleMessage (child_process.js:324:10)

**Comment by ide** [comment]
You are probably using an old version of Node. Make sure you are using Node 4 or newer, according to the Getting Started instructions.
