### ISSUE TITLE
执行npx react-native run-android时报错

### ISSUE THREAD

**Issue by qushushu** [facebook/react-native#35749]
### Description

![image](https://user-images.githubusercontent.com/8609923/210046628-f4402ba3-ce9c-4a38-a8fa-412b69a61f45.png)

### Version

0.64.1

### Output of `npx react-native info`

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s

    at makeError (D:\wamp\wamp\www\Pro\Pyq\Py\node_modules\execa\index.js:174:9)
    at D:\wamp\wamp\www\Pro\Pyq\Py\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (D:\wamp\wamp\www\Pro\Pyq\Py\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (D:\wamp\wamp\www\Pro\Pyq\Py\node_modules\@react-native-community\cli\build\index.js:186:9)
info Run CLI with --verbose flag for more details.

### Steps to reproduce

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s

    at makeError (D:\wamp\wamp\www\Pro\Pyq\Py\node_modules\execa\index.js:174:9)
    at D:\wamp\wamp\www\Pro\Pyq\Py\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (D:\wamp\wamp\www\Pro\Pyq\Py\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (D:\wamp\wamp\www\Pro\Pyq\Py\node_modules\@react-native-community\cli\build\index.js:186:9)
info Run CLI with --verbose flag for more details.

### Snack, code example, screenshot, or link to a repository

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s

    at makeError (D:\wamp\wamp\www\Pro\Pyq\Py\node_modules\execa\index.js:174:9)
    at D:\wamp\wamp\www\Pro\Pyq\Py\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (D:\wamp\wamp\www\Pro\Pyq\Py\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (D:\wamp\wamp\www\Pro\Pyq\Py\node_modules\@react-native-community\cli\build\index.js:186:9)
info Run CLI with --verbose flag for more details.

**Comment by cortinico** [comment]
The issue you're having is that you don't have enough storage on your Android device to install a new app. You need to remove some apps to make space for the new one
