### ISSUE TITLE
Error: While resolving module, the Haste package was found. the module could not be found within the package

### ISSUE THREAD

**Issue by PritishSawant** [facebook/react-native#35832]
### Description

I am trying the new arch of react native. I have enabled it in my gradle.properties file. This error is for android only and I have not tried iOS yet.

I am following the exact sample of Calculator mentioned over [here](https://reactnative.dev/docs/next/the-new-architecture/pillars-turbomodules).

I get an error saying

```
error: Error: While resolving module `rtn-calculator/js/NativeCalculator.js`, the Haste package `rtn-calculator` was found. However the module `js/NativeCalculator.js` could not be found within the package. Indeed, none of these files exist:

  * `/Users/transformhub/Desktop/rnapp/RTNCalculator/js/NativeCalculator.js(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `/Users/transformhub/Desktop/rnapp/RTNCalculator/js/NativeCalculator.js/index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at resolveHasteName (/Users/transformhub/Desktop/rnapp/node_modules/metro-resolver/src/resolve.js:173:9)
    at Object.resolve (/Users/transformhub/Desktop/rnapp/node_modules/metro-resolver/src/resolve.js:63:20)
    at ModuleResolver.resolveDependency (/Users/transformhub/Desktop/rnapp/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:111:31)
    at DependencyGraph.resolveDependency (/Users/transformhub/Desktop/rnapp/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
    at Object.resolve (/Users/transformhub/Desktop/rnapp/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/Users/transformhub/Desktop/rnapp/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/Users/transformhub/Desktop/rnapp/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Graph._addDependency (/Users/transformhub/Desktop/rnapp/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 2)
```

The complete repo is [here](https://github.com/PritishSawant/RnMyAppNewArch)

### Version

0.71.0

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: macOS 13.1
    CPU: (8) x64 Apple M1
    Memory: 41.52 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: javac 16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.0 => 0.71.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Download the repo from [here](https://github.com/PritishSawant/RnMyAppNewArch)
2. Do `npm install`
3. Run `yarn react-native run-android --active-arch-only`

### Snack, code example, screenshot, or link to a repository

[Repo](https://github.com/PritishSawant/RnMyAppNewArch)

<img width="1439" alt="Screenshot 2023-01-14 at 4 01 11 PM" src="https://user-images.githubusercontent.com/24708929/212472074-c9915695-563d-484d-846c-410c4dad30a3.png">

**Comment by cortinico** [comment]
Can you try to wipe Metro cache with `yarn start --reset-cache`?

**Comment by PritishSawant** [comment]
Same error

```
error: Error: While resolving module `rtn-calculator/js/NativeCalculator.js`, the Haste package `rtn-calculator` was found. However the module `js/NativeCalculator.js` could not be found within the package. Indeed, none of these files exist:

  * `/Users/transformhub/Desktop/rnapp/RTNCalculator/js/NativeCalculator.js(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `/Users/transformhub/Desktop/rnapp/RTNCalculator/js/NativeCalculator.js/index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at resolveHasteName (/Users/transformhub/Desktop/rnapp/node_modules/metro-resolver/src/resolve.js:173:9)
    at Object.resolve (/Users/transformhub/Desktop/rnapp/node_modules/metro-resolver/src/resolve.js:63:20)
    at ModuleResolver.resolveDependency (/Users/transformhub/Desktop/rnapp/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:111:31)
    at DependencyGraph.resolveDependency (/Users/transformhub/Desktop/rnapp/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
    at Object.resolve (/Users/transformhub/Desktop/rnapp/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/Users/transformhub/Desktop/rnapp/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/Users/transformhub/Desktop/rnapp/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at async Graph._addDependency (/Users/transformhub/Desktop/rnapp/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 2)
    at async Graph._processModule (/Users/transformhub/Desktop/rnapp/node_modules/metro/src/DeltaBundler/Graph.js:263:5)
```

**Comment by huntie** [comment]
Hi @PritishSawant! I believe this is because you have located the `rtn-calculator` package outside of a `node_modules` directory or npm/Yarn workspace. Therefore, for some internal reasons (Metro treats the directory as a legacy "Haste package") the import is handled slightly differently, and fails.

Specifically, this legacy package resolution substitutes all import subpaths based on `sourceExts`, and does not try the explicitly given file extension.

The fix in this case is to omit the source extension:

```diff
- import RTNCalculator from 'rtn-calculator/js/NativeCalculator.js';
+ import RTNCalculator from 'rtn-calculator/js/NativeCalculator';
```

I've tested this workaround locally against your repro using `yarn react-native bundle`, and it should be good to go.

**Comment by PritishSawant** [comment]
After doing the required changes I am getting RTNCalculator as null. I changed my import to 

`import RTNCalculator from 'rtn-calculator/js/NativeCalculator';`

I can see the `rtn-calculator` in my node-modules

<img width="438" alt="Screenshot 2023-01-20 at 8 36 34 AM" src="https://user-images.githubusercontent.com/24708929/213609361-a24d8497-3e3e-4a62-b165-4c280a46f0d0.png">

**Comment by huntie** [comment]
Can you confirm you've run the [TurboModule codegen for Android](https://reactnative.dev/docs/next/the-new-architecture/pillars-turbomodules#android)? Particularly these parts:

<img width="855" alt="image" src="https://user-images.githubusercontent.com/2547783/213684842-c35a2e8a-2de5-429c-87e6-1e74eb85a46e.png">

This is because I don't observe the `rtn-calculator/android/build/generated/` directory in your test repo: https://github.com/PritishSawant/RnMyAppNewArch/tree/34521ea/RTNCalculator/android

**Comment by PritishSawant** [comment]
<img width="985" alt="Screenshot 2023-01-20 at 6 35 44 PM" src="https://user-images.githubusercontent.com/24708929/213701740-bf7b7fae-097d-4eae-afdf-c4ce1dde489a.png">
I ran `./gradlew generateCodegenArtifactsFromSchema` again and it was successful but I don't see the build folder as well. The only change which I did was change the location `RTNCalculator`. It is part of my project so every time I use `yarn add ./RTNCalculator`

**Comment by cortinico** [comment]
> again and it was successful but I don't see the build folder as well. The only change which I did was change the location `RTNCalculator`.

Please note that once you run `generateCodegenArtifactsFromSchema` the build folder you'll be looking for is: `node_modules/RTNCalculator/android/build/generated/source/codegen` and not the one inside your top level `../RTNCalculator` folder.

If the issue persists, could you share a reproducer?

**Comment by PritishSawant** [comment]
Yup I am looking in the node_modules folder. I don't see build folder in android. Below is the screenshot
<img width="482" alt="Screenshot 2023-01-20 at 7 37 12 PM" src="https://user-images.githubusercontent.com/24708929/213716350-8c8f4445-e6c5-40e2-813e-1ba2d2cf5a75.png">

The repo is [here](https://github.com/PritishSawant/RnMyAppNewArch)

**Comment by PritishSawant** [comment]
@cortinico Do you want me to open another issue?

**Comment by cortinico** [comment]
Nope sorry. The issue you're facing now has already been addressed and is solved in React Native 0.71.1
If you bump the React Native version to 0.71.1 it will be solved.

Reference to the underlying issue is:
https://github.com/react-native-community/cli/pull/1800

**Comment by YoungLea30** [comment]
> Hi @PritishSawant! I believe this is because you have located the `rtn-calculator` package outside of a `node_modules` directory or npm/Yarn workspace. Therefore, for some internal reasons (Metro treats the directory as a legacy "Haste package") the import is handled slightly differently, and fails.
> 
> Specifically, this legacy package resolution suffixes all import subpaths based on `sourceExts`, and does not try the explicitly given file extension.
> 
> The fix in this case is to omit the source extension:
> 
> ```diff
> - import RTNCalculator from 'rtn-calculator/js/NativeCalculator.js';
> + import RTNCalculator from 'rtn-calculator/js/NativeCalculator';
> ```
> 
> I've tested this workaround locally against your repro using `yarn react-native bundle`, and it should be good to go.

it helped me, thankyou!
