### ISSUE TITLE
[iOS] Unable to connect to development server

### ISSUE THREAD

**Issue by djchie** [facebook/react-native#3591]
I'm running into issues where when I test on my iPhone 6s device, it's not able to connect to the development server. I have the correct IP address setup in the AppDelegate.m and RCTWebSocketExecutor.m file and it was working fine earlier today. The server seems to be running based on the terminal logs, but when after digging around, I found this error on 'http://10.8.1.222:8081/debug/graph': 

500 TypeError: this._depGraph.getDebugInfo is not a function
   at HasteDependencyResolver.getDebugInfo (/Users/derrickjchie/Desktop/Chew/ChewApp/node_modules/react-native/packager/react-packager/src/DependencyResolver/index.js:162:25)
   at Bundler.getGraphDebugInfo (/Users/derrickjchie/Desktop/Chew/ChewApp/node_modules/react-native/packager/react-packager/src/Bundler/index.js:224:27)
   at Server._processDebugRequest (/Users/derrickjchie/Desktop/Chew/ChewApp/node_modules/react-native/packager/react-packager/src/Server/index.js:251:28)
   at Server.processRequest (/Users/derrickjchie/Desktop/Chew/ChewApp/node_modules/react-native/packager/react-packager/src/Server/index.js:305:12)
   at next (/Users/derrickjchie/Desktop/Chew/ChewApp/node_modules/react-native/node_modules/connect/lib/proto.js:174:15)
   at Object.cpuProfileMiddleware [as handle] (/Users/derrickjchie/Desktop/Chew/ChewApp/node_modules/react-native/packager/packager.js:262:5)
   at next (/Users/derrickjchie/Desktop/Chew/ChewApp/node_modules/react-native/node_modules/connect/lib/proto.js:174:15)
   at Object.systraceProfileMiddleware [as handle] (/Users/derrickjchie/Desktop/Chew/ChewApp/node_modules/react-native/packager/packager.js:224:5)
   at next (/Users/derrickjchie/Desktop/Chew/ChewApp/node_modules/react-native/node_modules/connect/lib/proto.js:174:15)
   at Object.statusPageMiddleware [as handle] (/Users/derrickjchie/Desktop/Chew/ChewApp/node_modules/react-native/packager/packager.js:218:5)

Does anyone know what would cause the app to behave differently? Any help would be much appreciated!

**Comment by jaygarcia** [comment]
have you tried connecting to the packager from your phone's browser?  I'd suggest doing that.  There are a slew of network things that can cause this, including firewall being enabled on your host.

**Comment by yychun1217** [comment]
I git reset the package to about 3 days from now, and it works fine then

**Comment by djchie** [comment]
@jaygarcia It was a really simple mistake. My device and server weren't on the same wifi network -.- Thanks everyone for your help!

**Comment by ide** [comment]
Anyone want to help out by adding these to the Troubleshooting page in the docs? https://github.com/facebook/react-native/issues/3622
