### ISSUE TITLE
New app, fails see existing cocoapods or install fresh via gem install

### ISSUE THREAD

**Issue by raldred** [facebook/react-native#35980]
### Description

When trying to create a brand new app it fails a to install CocoaPods
Despite me already have CocoaPods installed, it doesn't seem to recognise.

I have tried completely removing it and still no luck.

```
✔ CocoaPods (https://cocoapods.org/) is not installed. CocoaPods is necessary for the iOS project to run correctly. Do you want to install it? › Yes, with gem (may require sudo)
error
error Error: An error occured while trying to install CocoaPods, which is required by this template.
Please try again manually: sudo gem install cocoapods.
```

I have tried as it says, manually installing it and it installs fine

```
❯ sudo gem install cocoapods
Fetching cocoapods-1.11.3.gem
Fetching cocoapods-trunk-1.6.0.gem
Fetching cocoapods-try-1.2.0.gem
Fetching cocoapods-plugins-1.0.0.gem
Fetching cocoapods-downloader-1.6.3.gem
Fetching cocoapods-search-1.0.1.gem
Fetching cocoapods-core-1.11.3.gem
Successfully installed cocoapods-core-1.11.3
Successfully installed cocoapods-downloader-1.6.3
Successfully installed cocoapods-plugins-1.0.0
Successfully installed cocoapods-search-1.0.1
Successfully installed cocoapods-trunk-1.6.0
Successfully installed cocoapods-try-1.2.0
Successfully installed cocoapods-1.11.3
Parsing documentation for cocoapods-core-1.11.3
Installing ri documentation for cocoapods-core-1.11.3
Parsing documentation for cocoapods-downloader-1.6.3
Installing ri documentation for cocoapods-downloader-1.6.3
Parsing documentation for cocoapods-plugins-1.0.0
Installing ri documentation for cocoapods-plugins-1.0.0
Parsing documentation for cocoapods-search-1.0.1
Installing ri documentation for cocoapods-search-1.0.1
Parsing documentation for cocoapods-trunk-1.6.0
Installing ri documentation for cocoapods-trunk-1.6.0
Parsing documentation for cocoapods-try-1.2.0
Installing ri documentation for cocoapods-try-1.2.0
Parsing documentation for cocoapods-1.11.3
Installing ri documentation for cocoapods-1.11.3
Done installing documentation for cocoapods-core, cocoapods-downloader, cocoapods-plugins, cocoapods-search, cocoapods-trunk, cocoapods-try, cocoapods after 1 seconds
7 gems installed
```

However when a run `react-native init` against, it still says `Cocoapods` is not installed

### Version

0.71.0

### Output of `npx react-native info`

❯ npx react-native info
Need to install the following packages:
  react-native
Ok to proceed? (y) y
error: unknown command 'info'
(Did you mean init?)

### Steps to reproduce

1. Run `npx react-native init AwesomeProject --verbose`
2. Choose install cocoapods via gem install
3. Enter sudo password
4. Observe error

### Snack, code example, screenshot, or link to a repository

Full verbose log

```
❯ npx react-native init AwesomeProject --verbose
Need to install the following packages:
  react-native
Ok to proceed? (y) y
debug We couldn't find a package.json in your project. Are you sure you are running it inside a React Native project?
debug Failed to load configuration of your project. Only a subset of commands will be available.
debug Initializing new project

               ######                ######
             ###     ####        ####     ###
            ##          ###    ###          ##
            ##             ####             ##
            ##             ####             ##
            ##           ##    ##           ##
            ##         ###      ###         ##
             ##  ########################  ##
          ######    ###            ###    ######
      ###     ##    ##              ##    ##     ###
   ###         ## ###      ####      ### ##         ###
  ##           ####      ########      ####           ##
 ##             ###     ##########     ###             ##
  ##           ####      ########      ####           ##
   ###         ## ###      ####      ### ##         ###
      ###     ##    ##              ##    ##     ###
          ######    ###            ###    ######
             ##  ########################  ##
            ##         ###      ###         ##
            ##           ##    ##           ##
            ##             ####             ##
            ##             ####             ##
            ##          ###    ###          ##
             ###     ####        ####     ###
               ######                ######


                  Welcome to React Native!
                 Learn once, write anywhere

debug Installing template from react-native@latest
Wrote to /private/var/folders/nw/hx81s5nn0ql095c_6g7rz5dw0000gn/T/rncli-init-template-IZZ74P/package.json:

{
  "name": "rncli-init-template-izz74p",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0

added 691 packages, and audited 692 packages in 4s

37 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
debug Getting config from /var/folders/nw/hx81s5nn0ql095c_6g7rz5dw0000gn/T/rncli-init-template-IZZ74P/node_modules/react-native/template.config.js
debug Copying template from /var/folders/nw/hx81s5nn0ql095c_6g7rz5dw0000gn/T/rncli-init-template-IZZ74P/node_modules/react-native/template
debug Changing HelloWorld for AwesomeProject in template
debug Replacing in /Users/robaldred/Code/AwesomeProject/tsconfig.json
debug Replacing in /Users/robaldred/Code/AwesomeProject/tsconfig.json
debug Replacing in /Users/robaldred/Code/AwesomeProject/package.json
debug Replacing in /Users/robaldred/Code/AwesomeProject/package.json
debug Replacing in /Users/robaldred/Code/AwesomeProject/metro.config.js
debug Replacing in /Users/robaldred/Code/AwesomeProject/metro.config.js
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/_xcode.env
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/_xcode.env
debug Renaming /Users/robaldred/Code/AwesomeProject/ios/_xcode.env -> file:/Users/robaldred/Code/AwesomeProject/ios/.xcode.env
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/Podfile
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/Podfile
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorldTests/Info.plist
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorldTests/Info.plist
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorldTests/HelloWorldTests.m
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorldTests/HelloWorldTests.m
debug Renaming /Users/robaldred/Code/AwesomeProject/ios/HelloWorldTests/HelloWorldTests.m -> file:/Users/robaldred/Code/AwesomeProject/ios/HelloWorldTests/AwesomeProjectTests.m
debug Renaming /Users/robaldred/Code/AwesomeProject/ios/HelloWorldTests -> file:/Users/robaldred/Code/AwesomeProject/ios/AwesomeProjectTests
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorld.xcodeproj/xcshareddata/xcschemes/HelloWorld.xcscheme
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorld.xcodeproj/xcshareddata/xcschemes/HelloWorld.xcscheme
debug Renaming /Users/robaldred/Code/AwesomeProject/ios/HelloWorld.xcodeproj/xcshareddata/xcschemes/HelloWorld.xcscheme -> file:/Users/robaldred/Code/AwesomeProject/ios/HelloWorld.xcodeproj/xcshareddata/xcschemes/AwesomeProject.xcscheme
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorld.xcodeproj/project.pbxproj
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorld.xcodeproj/project.pbxproj
debug Renaming /Users/robaldred/Code/AwesomeProject/ios/HelloWorld.xcodeproj -> file:/Users/robaldred/Code/AwesomeProject/ios/AwesomeProject.xcodeproj
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorld/main.m
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorld/main.m
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorld/LaunchScreen.storyboard
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorld/LaunchScreen.storyboard
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorld/Info.plist
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorld/Info.plist
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorld/Images.xcassets/Contents.json
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorld/Images.xcassets/Contents.json
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorld/Images.xcassets/AppIcon.appiconset/Contents.json
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorld/Images.xcassets/AppIcon.appiconset/Contents.json
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorld/AppDelegate.mm
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorld/AppDelegate.mm
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorld/AppDelegate.h
debug Replacing in /Users/robaldred/Code/AwesomeProject/ios/HelloWorld/AppDelegate.h
debug Renaming /Users/robaldred/Code/AwesomeProject/ios/HelloWorld -> file:/Users/robaldred/Code/AwesomeProject/ios/AwesomeProject
debug Replacing in /Users/robaldred/Code/AwesomeProject/index.js
debug Replacing in /Users/robaldred/Code/AwesomeProject/index.js
debug Replacing in /Users/robaldred/Code/AwesomeProject/babel.config.js
debug Replacing in /Users/robaldred/Code/AwesomeProject/babel.config.js
debug Replacing in /Users/robaldred/Code/AwesomeProject/app.json
debug Replacing in /Users/robaldred/Code/AwesomeProject/app.json
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/settings.gradle
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/settings.gradle
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/gradlew.bat
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/gradlew.bat
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/gradlew
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/gradlew
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/gradle.properties
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/gradle.properties
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/gradle/wrapper/gradle-wrapper.properties
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/gradle/wrapper/gradle-wrapper.properties
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/gradle/wrapper/gradle-wrapper.jar
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/gradle/wrapper/gradle-wrapper.jar
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/build.gradle
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/build.gradle
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/release/java/com/helloworld/ReactNativeFlipper.java
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/release/java/com/helloworld/ReactNativeFlipper.java
debug Renaming /Users/robaldred/Code/AwesomeProject/android/app/src/release/java/com/helloworld -> file:/Users/robaldred/Code/AwesomeProject/android/app/src/release/java/com/awesomeproject
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/values/styles.xml
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/values/styles.xml
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/values/strings.xml
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/values/strings.xml
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/drawable/rn_edit_text_material.xml
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/res/drawable/rn_edit_text_material.xml
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/java/com/helloworld/MainApplication.java
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/java/com/helloworld/MainApplication.java
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/java/com/helloworld/MainActivity.java
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/java/com/helloworld/MainActivity.java
debug Renaming /Users/robaldred/Code/AwesomeProject/android/app/src/main/java/com/helloworld -> file:/Users/robaldred/Code/AwesomeProject/android/app/src/main/java/com/awesomeproject
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/AndroidManifest.xml
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/main/AndroidManifest.xml
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/debug/java/com/helloworld/ReactNativeFlipper.java
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/debug/java/com/helloworld/ReactNativeFlipper.java
debug Renaming /Users/robaldred/Code/AwesomeProject/android/app/src/debug/java/com/helloworld -> file:/Users/robaldred/Code/AwesomeProject/android/app/src/debug/java/com/awesomeproject
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/debug/AndroidManifest.xml
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/src/debug/AndroidManifest.xml
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/proguard-rules.pro
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/proguard-rules.pro
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/debug.keystore
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/debug.keystore
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/build.gradle
debug Replacing in /Users/robaldred/Code/AwesomeProject/android/app/build.gradle
debug Replacing in /Users/robaldred/Code/AwesomeProject/_watchmanconfig
debug Replacing in /Users/robaldred/Code/AwesomeProject/_watchmanconfig
debug Renaming /Users/robaldred/Code/AwesomeProject/_watchmanconfig -> file:/Users/robaldred/Code/AwesomeProject/.watchmanconfig
debug Replacing in /Users/robaldred/Code/AwesomeProject/_ruby-version
debug Replacing in /Users/robaldred/Code/AwesomeProject/_ruby-version
debug Renaming /Users/robaldred/Code/AwesomeProject/_ruby-version -> file:/Users/robaldred/Code/AwesomeProject/.ruby-version
debug Replacing in /Users/robaldred/Code/AwesomeProject/_prettierrc.js
debug Replacing in /Users/robaldred/Code/AwesomeProject/_prettierrc.js
debug Renaming /Users/robaldred/Code/AwesomeProject/_prettierrc.js -> file:/Users/robaldred/Code/AwesomeProject/.prettierrc.js
debug Replacing in /Users/robaldred/Code/AwesomeProject/_node-version
debug Replacing in /Users/robaldred/Code/AwesomeProject/_node-version
debug Renaming /Users/robaldred/Code/AwesomeProject/_node-version -> file:/Users/robaldred/Code/AwesomeProject/.node-version
debug Replacing in /Users/robaldred/Code/AwesomeProject/_gitignore
debug Replacing in /Users/robaldred/Code/AwesomeProject/_gitignore
debug Renaming /Users/robaldred/Code/AwesomeProject/_gitignore -> file:/Users/robaldred/Code/AwesomeProject/.gitignore
debug Replacing in /Users/robaldred/Code/AwesomeProject/_eslintrc.js
debug Replacing in /Users/robaldred/Code/AwesomeProject/_eslintrc.js
debug Renaming /Users/robaldred/Code/AwesomeProject/_eslintrc.js -> file:/Users/robaldred/Code/AwesomeProject/.eslintrc.js
debug Replacing in /Users/robaldred/Code/AwesomeProject/_bundle/config
debug Replacing in /Users/robaldred/Code/AwesomeProject/_bundle/config
debug Renaming /Users/robaldred/Code/AwesomeProject/_bundle/config -> file:/Users/robaldred/Code/AwesomeProject/_bundle/config
debug Renaming /Users/robaldred/Code/AwesomeProject/_bundle -> file:/Users/robaldred/Code/AwesomeProject/.bundle
debug Replacing in /Users/robaldred/Code/AwesomeProject/__tests__/App-test.tsx
debug Replacing in /Users/robaldred/Code/AwesomeProject/__tests__/App-test.tsx
debug Replacing in /Users/robaldred/Code/AwesomeProject/Gemfile
debug Replacing in /Users/robaldred/Code/AwesomeProject/Gemfile
debug Replacing in /Users/robaldred/Code/AwesomeProject/App.tsx
debug Replacing in /Users/robaldred/Code/AwesomeProject/App.tsx
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'write-file-atomic@5.0.0',
npm WARN EBADENGINE   required: { node: '^14.17.0 || ^16.13.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.10.0', npm: '7.24.0' }
npm WARN EBADENGINE }
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0

added 1271 packages, and audited 1272 packages in 7s

119 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
✔ CocoaPods (https://cocoapods.org/) is not installed. CocoaPods is necessary for the iOS project to run correctly. Do you want to install it? › Yes, with gem (may require sudo)
error
error Error: An error occured while trying to install CocoaPods, which is required by this template.
Please try again manually: sudo gem install cocoapods.
CocoaPods documentation: https://cocoapods.org/
Error: Error: An error occured while trying to install CocoaPods, which is required by this template.
Please try again manually: sudo gem install cocoapods.
CocoaPods documentation: https://cocoapods.org/
    at createFromTemplate (/Users/robaldred/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/init/init.js:169:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.initialize [as func] (/Users/robaldred/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/init/init.js:222:3)
    at async Command.handleAction (/Users/robaldred/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/index.js:140:9)

~/Code
❯ sudo gem install cocoapods
Fetching cocoapods-1.11.3.gem
Fetching cocoapods-trunk-1.6.0.gem
Fetching cocoapods-try-1.2.0.gem
Fetching cocoapods-plugins-1.0.0.gem
Fetching cocoapods-downloader-1.6.3.gem
Fetching cocoapods-search-1.0.1.gem
Fetching cocoapods-core-1.11.3.gem
Successfully installed cocoapods-core-1.11.3
Successfully installed cocoapods-downloader-1.6.3
Successfully installed cocoapods-plugins-1.0.0
Successfully installed cocoapods-search-1.0.1
Successfully installed cocoapods-trunk-1.6.0
Successfully installed cocoapods-try-1.2.0
Successfully installed cocoapods-1.11.3
Parsing documentation for cocoapods-core-1.11.3
Installing ri documentation for cocoapods-core-1.11.3
Parsing documentation for cocoapods-downloader-1.6.3
Installing ri documentation for cocoapods-downloader-1.6.3
Parsing documentation for cocoapods-plugins-1.0.0
Installing ri documentation for cocoapods-plugins-1.0.0
Parsing documentation for cocoapods-search-1.0.1
Installing ri documentation for cocoapods-search-1.0.1
Parsing documentation for cocoapods-trunk-1.6.0
Installing ri documentation for cocoapods-trunk-1.6.0
Parsing documentation for cocoapods-try-1.2.0
Installing ri documentation for cocoapods-try-1.2.0
Parsing documentation for cocoapods-1.11.3
Installing ri documentation for cocoapods-1.11.3
Done installing documentation for cocoapods-core, cocoapods-downloader, cocoapods-plugins, cocoapods-search, cocoapods-trunk, cocoapods-try, cocoapods after 1 seconds
7 gems installed
```

**Comment by cl3i550n** [comment]
@raldred Do you use MACOS?

Try this

1 - `sudo gem uninstall cocoapods`
2 - `gem install cocoapods`
3 - put in your .bash_profile or .zshrc the environments below

```
export GEM_HOME=$HOME/.gem
export PATH=$GEM_HOME/bin:$PATH
```

4 - Reload your terminal ( close all, and try again )
4.1 - source ~/.zshrc ( mac )

**Comment by raldred** [comment]
Hey yes, I'm on an M1 I use rbenv so those variables should already be exported to the shell, nevertheless, I'll give it a try.
Thanks

**Comment by raldred** [comment]
@cl3i550n No such luck unfortunately.
Same error.

```
~/Code
❯ gem install cocoapods
Fetching cocoapods-1.11.3.gem
Successfully installed cocoapods-1.11.3
Parsing documentation for cocoapods-1.11.3
Installing ri documentation for cocoapods-1.11.3
Done installing documentation for cocoapods after 1 seconds
1 gem installed

~/Code
❯ code ~/.zshrc

~/Code
❯ source ~/.zshrc

~/Code
❯ which pod
/Users/robaldred/.rbenv/shims/pod

~/Code
❯ pod --version
1.11.3
```

<details>
<summary>
`npx react-native init AwesomeProject`
</summary>

```
~/Code
❯ npx react-native init AwesomeProject
Need to install the following packages:
  react-native
Ok to proceed? (y) y

               ######                ######
             ###     ####        ####     ###
            ##          ###    ###          ##
            ##             ####             ##
            ##             ####             ##
            ##           ##    ##           ##
            ##         ###      ###         ##
             ##  ########################  ##
          ######    ###            ###    ######
      ###     ##    ##              ##    ##     ###
   ###         ## ###      ####      ### ##         ###
  ##           ####      ########      ####           ##
 ##             ###     ##########     ###             ##
  ##           ####      ########      ####           ##
   ###         ## ###      ####      ### ##         ###
      ###     ##    ##              ##    ##     ###
          ######    ###            ###    ######
             ##  ########################  ##
            ##         ###      ###         ##
            ##           ##    ##           ##
            ##             ####             ##
            ##             ####             ##
            ##          ###    ###          ##
             ###     ####        ####     ###
               ######                ######


                  Welcome to React Native!
                 Learn once, write anywhere

✔ Downloading template
✔ Copying template
✔ Processing template
ℹ Installing dependencies
✔ CocoaPods (https://cocoapods.org/) is not installed. CocoaPods is necessary for the iOS project to run correctly. Do you want to install it? › Yes, with gem (may require sudo)
✖ Installing CocoaPods
error
✖ Installing CocoaPods
error Error: An error occured while trying to install CocoaPods, which is required by this template.
Please try again manually: sudo gem install cocoapods.
CocoaPods documentation: https://cocoapods.org/.
Error: Error: An error occured while trying to install CocoaPods, which is required by this template.
Please try again manually: sudo gem install cocoapods.
CocoaPods documentation: https://cocoapods.org/
    at createFromTemplate (/Users/robaldred/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/init/init.js:169:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.initialize [as func] (/Users/robaldred/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/init/init.js:222:3)
    at async Command.handleAction (/Users/robaldred/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/index.js:140:9)
info Run CLI with --verbose flag for more details.
```
</details>

**Comment by raldred** [comment]
I thought I'd try 70.6 and yep, that still works. 
So something not right with 0.71.0 on mac.

```
❯ npx react-native init AwesomeProject --version 0.70.6
Need to install the following packages:
  react-native
Ok to proceed? (y) y

               ######                ######
             ###     ####        ####     ###
            ##          ###    ###          ##
            ##             ####             ##
            ##             ####             ##
            ##           ##    ##           ##
            ##         ###      ###         ##
             ##  ########################  ##
          ######    ###            ###    ######
      ###     ##    ##              ##    ##     ###
   ###         ## ###      ####      ### ##         ###
  ##           ####      ########      ####           ##
 ##             ###     ##########     ###             ##
  ##           ####      ########      ####           ##
   ###         ## ###      ####      ### ##         ###
      ###     ##    ##              ##    ##     ###
          ######    ###            ###    ######
             ##  ########################  ##
            ##         ###      ###         ##
            ##           ##    ##           ##
            ##             ####             ##
            ##             ####             ##
            ##          ###    ###          ##
             ###     ####        ####     ###
               ######                ######


                  Welcome to React Native!
                 Learn once, write anywhere

✔ Downloading template
✔ Copying template
✔ Processing template
✔ Installing Bundler
✔ Installing CocoaPods dependencies (this may take a few minutes)


  Run instructions for Android:
    • Have an Android emulator running (quickest way to get started), or a device connected.
    • cd "/Users/robaldred/Code/AwesomeProject" && npx react-native run-android

  Run instructions for iOS:
    • cd "/Users/robaldred/Code/AwesomeProject" && npx react-native run-ios
    - or -
    • Open AwesomeProject/ios/AwesomeProject.xcworkspace in Xcode or run "xed -b ios"
    • Hit the Run button

  Run instructions for macOS:
    • See https://aka.ms/ReactNativeGuideMacOS for the latest up-to-date instructions.

```

**Comment by cl3i550n** [comment]
@raldred 

Don't use sudo to install any dependencies

I unistalling all, literally...
And install all again winthout sudo!!!!

i installed some dependencies with sudo and any rubys versions and etc......
delete all cache or folders, and start of zero inside of opt/homebrew erease all

now go your folder
now use cmd + shift + .

your see hide folders
delete all... caution this!
delete only what you are sure are remnants of a bad installation of the environment

try install all again winthout sudo

homebrew
watchman
node (lts)
Zulu11 (Java)
Rbenv
cocoapods gem

Only in my .zshrc path envrioments
Rbenv
homebrew
gem (see docs)

My OS

macOS 13.2 Ventura
Apple Silicon M2
Tools of Xode 14.x (lts)

**See my post** 
https://github.com/facebook/react-native/issues/35836

**Comment by cl3i550n** [comment]
@raldred 

try install cocoapods with homebrew

**Comment by raldred** [comment]
Sorted, I manually installed cocoapods without sudo as you say, before running `react-native init`
So there must be something wrong with the cli tools, because it fails to install cocoapods itself. 🤷 

Thanks for your help @cl3i550n

**Comment by cortinico** [comment]
> Sorted, I manually installed cocoapods without sudo as you say, before running `react-native init`

Closing

**Comment by raldred** [comment]
@cortinico Sure, i guess, but it's still a bug if you don't have cocoapods it doesn't install it for you despite the options to.

**Comment by cortinico** [comment]
> there must be something wrong with the cli tools, because it fails to install cocoapods itself. 🤷

Thanks for mentioning nthis @raldred.
Don't you mind opening an issue here: https://github.com/react-native-community/cli/issues
