### ISSUE TITLE
error warn Multiple Podfiles were found: ios/Podfile,vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/Podfile while initializing a new react native project

### ISSUE THREAD

**Issue by anisamirouche** [facebook/react-native#36081]
### Description

```js
✖ Installing CocoaPods dependencies (this may take a few minutes)
error warn Multiple Podfiles were found: ios/Podfile,vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/Podfile. Choosing ios/Podfile automatically. If you would like to select a different one, you can configure it via "project.ios.sourceDir". You can learn more about it here: https://github.com/react-native-community/cli/blob/master/docs/configuration.md

✖ Installing CocoaPods dependencies (this may take a few minutes)
error Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
Error: Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
    at createFromTemplate (/Users/anis/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/init/init.js:169:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.initialize [as func] (/Users/anis/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/init/init.js:222:3)
    at async Command.handleAction (/Users/anis/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/index.js:140:9)
info Run CLI with --verbose flag for more details.
```

### Version

0.70.2

### Output of `npx react-native info`

```js
System:
    OS: macOS 12.6.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 483.90 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    Watchman: 2023.01.09.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/anis/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1 - /usr/local/opt/openjdk/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.2 => 0.71.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

```js
npx react-native init newProject
```

### Snack, code example, screenshot, or link to a repository

![Screenshot 2023-02-07 at 5 48 03 PM](https://user-images.githubusercontent.com/36996198/217277645-fdd4566b-c6bc-49b0-a78c-9bf629b551f1.png)

**Comment by anisamirouche** [comment]
> Yes, I'm facing similar problem albeit successfully building the app.
> 
> I got this warning when I run `pod install`:
> 
> ![Screenshot 2023-02-09 at 5 27 46 PM](https://user-images.githubusercontent.com/232541/217772737-a8be0b94-6934-4ba8-a8a7-8e8d8485c3a8.png)

Which React native version are you using ?

**Comment by cipolleschi** [comment]
Hi there! 

The warning about multiple Podfile should not stop you from building the app. However, I put up a PR to fix this for new apps.

@anisamirouche, your problem is a misconfiguration of the environment, probably you have the wrong version of Ruby installed. To make sure of it, could you try to manually install the pods by (from a Terminal):
1. navigate to your app folder
2. `cd ios`
3. `bundle install` (you need to run this only once)
4. `bundle exec pod install`

This should give us a better diagnostic of your problem.

Thank you so much.
