### ISSUE TITLE
Error: Requiring module "374", which threw an exception: TypeError: null is not an object (evaluating 'o.multiMerge')

### ISSUE THREAD

**Issue by hamidpak013** [facebook/react-native#36151]
### Description

2023-02-14 21:17:14.780 25720-25781/? E/ReactNativeJS: Error: Requiring module "374", which threw an exception: TypeError: null is not an object (evaluating 'o.multiMerge')
2023-02-14 21:17:14.789 25720-25720/? I/ReactNative: [GESTURE HANDLER] Initialize gesture handler for root view com.facebook.react.ReactRootView{73c63a V.E...... ......ID 0,0-1080,2156 #b}
2023-02-14 21:17:14.790 25720-25782/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.onexfort, PID: 25720
    com.facebook.react.common.JavascriptException: Error: Requiring module "374", which threw an exception: TypeError: null is not an object (evaluating 'o.multiMerge'), stack:
    v@2:1364
    d@2:875
    <unknown>@1751:463
    y@9:586
    <unknown>@9:1889
    y@9:586
    o@9:1065
    <unknown>@9:1422
    c@128:204
    X@128:1585
    _@128:483
    h@9:1406
    _invoke@9:1458
    async@9:3847
    <unknown>@1751:381
    mi@96:60764
    Dl@96:79128
    unstable_runWithPriority@212:3882
    <unknown>@96:78748
    G@212:2821
    n@212:194
    y@133:580
    callTimers@133:2629
    value@32:3350
    <unknown>@32:747
    value@32:2610
    value@32:719
    value@-1
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.jni.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:1012)

### Version

0.63.3

### Output of `npx react-native info`

npx react-native run-android

### Steps to reproduce

my current project running on 0.63.3, it was modified months ago, when I remove some deprecated libraries and tried to run it on android it returns this error Error: Requiring module "374", which threw an exception: TypeError: null is not an object (evaluating 'o.multiMerge'). I'm not facing any issue on iOS

### Snack, code example, screenshot, or link to a repository

<img width="1515" alt="Screenshot 2023-02-14 at 9 42 14 PM" src="https://user-images.githubusercontent.com/58320612/218801267-d3871a10-18cb-4a33-90bd-8f3f523a703e.png">

**Comment by adityaparsai** [comment]
- delete everything from node_modules
- delete the package-lock.json file
- clear all data/cache from expo go app
- use "@react-native-async-storage/async-storage": "1.15.0" or higher
- npm install again
- npm run android
