### ISSUE TITLE
[ios] Error failed to load configuration of your project.

### ISSUE THREAD

**Issue by Ahmedhamed77** [facebook/react-native#36396]
### New Version

0.67.4

### Old Version

0.71.1

### Build Target(s)

xcode

### Output of `react-native info`

error Failed to load configuration of your project.
`Config Validation Error: "dependencies.react-native-interactable.platforms.android.folder" is not allowed
    at readConfigFromDisk (/Users/ahmedhamed/Desktop/Ninja_Work/vibe-mobile/node_modules/@react-native-community/cli-config/build/readConfigFromDisk.js:52:11)
    at loadConfig (/Users/ahmedhamed/Desktop/Ninja_Work/vibe-mobile/node_modules/@react-native-community/cli-config/build/loadConfig.js:46:65)
    at setupAndRun (/Users/ahmedhamed/Desktop/Ninja_Work/vibe-mobile/node_modules/@react-native-community/cli/build/index.js:156:45)
    at Object.run (/Users/ahmedhamed/Desktop/Ninja_Work/vibe-mobile/node_modules/@react-native-community/cli/build/index.js:124:11)
    at Object.<anonymous> (/Users/ahmedhamed/Desktop/Ninja_Work/vibe-mobile/node_modules/react-native/cli.js:16:7)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
info Run CLI with --verbose flag for more details.`

### Issue and Reproduction Steps

I'm just upgrading from version `0.67.4` to `0.71.1` and when I try to install pods I get this error and cant build the project even I tried to remove `node-modules` and tried this command `npm uninstall -g react-native-cli @react-native-community/cli`

but none of this solved the problem, any ideas?

**Comment by cortinico** [comment]
> Config Validation Error: "dependencies.react-native-interactable.platforms.android.folder" is not allowed at readConfigFromDisk

The error is telling you what's the problem.
Specifically the library `react-native-interactable` is causing this issue.
You should probably update that library or open an issue on their issue tracker here:
https://github.com/wix/react-native-interactable/issues
