### ISSUE TITLE
Error when updating to v0.71.3 from 0.70.7

### ISSUE THREAD

**Issue by darkbasic** [facebook/react-native#36393]
### Description

I'm upgrading a very old 0.64 codebase originally created with the typescript template to latest 0.71.3.
To start I've upgraded just to 0.68 because the Android build didn't succeed anymore in 2023 with react-native 0.64: everything went smoothly and I've got a working 0.68 Android build.
At this point I've tried to upgrade to 0.71.3 but it failed, so I've gone through each and every major version up to 0.70.7. I didn't try to build the application with react-native 0.70 yet (this isn't the focus of this bug report), but `npx react-native upgrade` went smoothly up to 0.70.7.
Unfortunately as soon as I try to upgrade to 0.71.3 I get the following:

```
$ npx react-native upgrade 0.71.3
warn Package react-native-vector-icons contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching diff between v0.70.7 and v0.71.3...
info Applying diff...
warn Excluding files that exist in the template, but not in your project:
  - App.js
  - __tests__/App-test.js
error Automatically applying diff failed. We did our best to automatically upgrade as many files as possible
error Patch failed to apply for unknown reason. Please fall back to manual way of upgrading
info You may find these resources helpful:
• Release notes: https://github.com/facebook/react-native/releases/tag/v0.71.3
• Manual Upgrade Helper: https://react-native-community.github.io/upgrade-helper/?from=0.70.7&to=0.71.3
• Git diff: https://raw.githubusercontent.com/react-native-community/rn-diff-purge/diffs/diffs/0.70.7..0.71.3.diff
error Upgrade failed. Please see the messages above for details.
info Run CLI with --verbose flag for more details.
```

`package.json` has already been updated with `npx @rnx-kit/align-deps --requirements react-native@0.71 --write` as I did with previous updates.

Verbose:

```
$ npx react-native upgrade 0.71.3 --verbose
warn Package react-native-vector-icons contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching diff between v0.70.7 and v0.71.3...
info Applying diff...
warn Excluding files that exist in the template, but not in your project:
  - App.js
  - __tests__/App-test.js
debug "git apply" failed. Error output:
Falling back to direct application...
Falling back to direct application...
Applied patch to '.gitignore' with conflicts.
Applied patch to '.node-version' cleanly.
Applied patch to '.ruby-version' cleanly.
error: App.js: does not exist in index
Applied patch to 'Gemfile' cleanly.
error: __tests__/App-test.js: does not exist in index
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Applied patch to 'android/build.gradle' cleanly.
Applied patch to 'android/gradle.properties' cleanly.
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
Applied patch to 'ios/client/AppDelegate.h' cleanly.
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
Performing three-way merge...
Applied patch to 'tsconfig.json' with conflicts.

error Automatically applying diff failed. We did our best to automatically upgrade as many files as possible
error Patch failed to apply for unknown reason. Please fall back to manual way of upgrading
info You may find these resources helpful:
• Release notes: https://github.com/facebook/react-native/releases/tag/v0.71.3
• Manual Upgrade Helper: https://react-native-community.github.io/upgrade-helper/?from=0.70.7&to=0.71.3
• Git diff: https://raw.githubusercontent.com/react-native-community/rn-diff-purge/diffs/diffs/0.70.7..0.71.3.diff
error Upgrade failed. Please see the messages above for details
```

My theory is that this is due to the 0.71 Typescript by default migration. Somehow since my project already used Typescript it fails. Just a theory though.

P.S.
Please also ignore the fact that I'm on ppc64le. I've set up a separate `LD_PREFIX` for `x86_64` binaries and I'm dynamically translating the `x86_64` Android SDK (which works like a charm) but this bug report is just about the upgrade process and not the Android build.

### React Native Version

0.71.3

### Output of `npx react-native info`

```
warn Package react-native-vector-icons contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
    OS: Linux 6.2 Gentoo Linux
    CPU: (32) ppc64 POWER9, altivec supported
    Memory: 48.87 GB / 62.37 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
    Watchman: 2023.02.06.00 - /usr/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 29, 31, 32, 33, 33
      Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.2
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.1.0 
    react-native: 0.71.3 => 0.70.7 
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

I'd say try to create a 0.64 react-native app with the typescript template and try to upgrade it to 0.71, but I didn't try that yet.

### Snack, code example, screenshot, or link to a repository

Unfortunately I cannot share the app I'm currently trying to upgrade. If I will manage to pinpoint the issue to something specific I'll include a repro. In the meantime I'm opening this to get some feedback about the possible causes.

**Comment by darkbasic** [comment]
> You will have to update your project manually to use TS, if you wish.

My project did already use Typescript, that's why I thought it might have been the issue.

> What is the problem of this issue though? Is the app not building or are you just reporting npx react-native upgrade not working well?

`npx react-native upgrade` doesn't work at all: it silently fails without creating any merge conflict.

**Comment by darkbasic** [comment]
**I have a repro**:

1. Create a react-native 0.70 app using the typescript template: `npx react-native init client --template react-native-template-typescript@6.12.10`
2. Try to upgrade it: `npx react-native upgrade 0.71.3`
3. See error

```
info Fetching diff between v0.70.6 and v0.71.3...
info Applying diff...
warn Excluding files that exist in the template, but not in your project:
  - .flowconfig
  - App.js
  - __tests__/App-test.js
error Excluding files that failed to apply the diff:
  - android/app/src/main/java/com/client/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  - android/app/src/main/jni/CMakeLists.txt
Please make sure to check the actual changes after the upgrade command is finished.
You can find them in our Upgrade Helper web app: https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.71.3
error Automatically applying diff failed. We did our best to automatically upgrade as many files as possible
error Patch failed to apply for unknown reason. Please fall back to manual way of upgrading
info You may find these resources helpful:
• Release notes: https://github.com/facebook/react-native/releases/tag/v0.71.3
• Manual Upgrade Helper: https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.71.3
• Git diff: https://raw.githubusercontent.com/react-native-community/rn-diff-purge/diffs/diffs/0.70.6..0.71.3.diff
error Upgrade failed. Please see the messages above for details.
info Run CLI with --verbose flag for more details.
```

Verbose:

```
$ npx react-native upgrade 0.71.3 --verbose
info Fetching diff between v0.70.6 and v0.71.3...
info Applying diff...
warn Excluding files that exist in the template, but not in your project:
  - .flowconfig
  - App.js
  - __tests__/App-test.js
error Excluding files that failed to apply the diff:
  - android/app/src/main/java/com/client/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  - android/app/src/main/jni/CMakeLists.txt
Please make sure to check the actual changes after the upgrade command is finished.
You can find them in our Upgrade Helper web app: https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.71.3
debug "git apply" failed. Error output:
Falling back to direct application...
Applied patch to '.gitignore' cleanly.
Applied patch to '.node-version' cleanly.
Applied patch to '.ruby-version' cleanly.
error: App.js: does not exist in index
Applied patch to 'Gemfile' cleanly.
error: __tests__/App-test.js: does not exist in index
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Applied patch to 'android/build.gradle' cleanly.
Applied patch to 'android/gradle.properties' cleanly.
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
Applied patch to 'ios/client/AppDelegate.h' cleanly.
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
Performing three-way merge...
Applied patch to 'tsconfig.json' with conflicts.

error Automatically applying diff failed. We did our best to automatically upgrade as many files as possible
error Patch failed to apply for unknown reason. Please fall back to manual way of upgrading
info You may find these resources helpful:
• Release notes: https://github.com/facebook/react-native/releases/tag/v0.71.3
• Manual Upgrade Helper: https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.71.3
• Git diff: https://raw.githubusercontent.com/react-native-community/rn-diff-purge/diffs/diffs/0.70.6..0.71.3.diff
error Upgrade failed. Please see the messages above for details
```

**Comment by darkbasic** [comment]
**I have a repro**:

1. Create a react-native 0.70 app using the typescript template: `npx react-native init client --template react-native-template-typescript@6.12.10`
2. Try to upgrade it: `npx react-native upgrade 0.71.3`
3. See error

```
info Fetching diff between v0.70.6 and v0.71.3...
info Applying diff...
warn Excluding files that exist in the template, but not in your project:
  - .flowconfig
  - App.js
  - __tests__/App-test.js
error Excluding files that failed to apply the diff:
  - android/app/src/main/java/com/client/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  - android/app/src/main/jni/CMakeLists.txt
Please make sure to check the actual changes after the upgrade command is finished.
You can find them in our Upgrade Helper web app: https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.71.3
error Automatically applying diff failed. We did our best to automatically upgrade as many files as possible
error Patch failed to apply for unknown reason. Please fall back to manual way of upgrading
info You may find these resources helpful:
• Release notes: https://github.com/facebook/react-native/releases/tag/v0.71.3
• Manual Upgrade Helper: https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.71.3
• Git diff: https://raw.githubusercontent.com/react-native-community/rn-diff-purge/diffs/diffs/0.70.6..0.71.3.diff
error Upgrade failed. Please see the messages above for details.
info Run CLI with --verbose flag for more details.
```

Verbose:

```
$ npx react-native upgrade 0.71.3 --verbose
info Fetching diff between v0.70.6 and v0.71.3...
info Applying diff...
warn Excluding files that exist in the template, but not in your project:
  - .flowconfig
  - App.js
  - __tests__/App-test.js
error Excluding files that failed to apply the diff:
  - android/app/src/main/java/com/client/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  - android/app/src/main/jni/CMakeLists.txt
Please make sure to check the actual changes after the upgrade command is finished.
You can find them in our Upgrade Helper web app: https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.71.3
debug "git apply" failed. Error output:
Falling back to direct application...
Applied patch to '.gitignore' cleanly.
Applied patch to '.node-version' cleanly.
Applied patch to '.ruby-version' cleanly.
error: App.js: does not exist in index
Applied patch to 'Gemfile' cleanly.
error: __tests__/App-test.js: does not exist in index
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Falling back to direct application...
Applied patch to 'android/build.gradle' cleanly.
Applied patch to 'android/gradle.properties' cleanly.
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
Applied patch to 'ios/client/AppDelegate.h' cleanly.
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
error: repository lacks the necessary blob to perform 3-way merge.
Falling back to direct application...
Performing three-way merge...
Applied patch to 'tsconfig.json' with conflicts.

error Automatically applying diff failed. We did our best to automatically upgrade as many files as possible
error Patch failed to apply for unknown reason. Please fall back to manual way of upgrading
info You may find these resources helpful:
• Release notes: https://github.com/facebook/react-native/releases/tag/v0.71.3
• Manual Upgrade Helper: https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.71.3
• Git diff: https://raw.githubusercontent.com/react-native-community/rn-diff-purge/diffs/diffs/0.70.6..0.71.3.diff
error Upgrade failed. Please see the messages above for details
```

**Comment by cortinico** [comment]
> What is the problem of this issue though?

As it seems you're reporting a failure with `react-native upgrade`, you should open this issue against the CLI:

https://github.com/react-native-community/cli/issues

Moreover, upgrading from an external template to the default template is not supported (that's also the reason why it failed for you).

**Comment by darkbasic** [comment]
Closing in favor of https://github.com/react-native-community/cli/issues/1866

**Comment by Sagargajul41** [comment]
Hi @cortinico ,
I am getting below error after my react native version moved from 0.64 to 0.70 in my current project.
New Version
0.70.13
Old Version
0.64.2
Can anyone help me with this issue?

error: Error: Unable to resolve module ./app.json from D:\VR-Setup\UI-Projects\newproject\index.js:

None of these files exist:

app.json(.native|.android.jsx|.native.jsx|.jsx|.android.js|.native.js|.js)
app.json\index(.native|.android.jsx|.native.jsx|.jsx|.android.js|.native.js|.js)
5 | import {AppRegistry} from 'react-native';
6 | import App from './App';
7 | import {name as appName} from './app.json';
| ^
8 | import 'react-native-gesture-handler';
9 | AppRegistry.registerComponent(appName, () => App);
10 |
at ModuleResolver.resolveDependency (D:\VR-Setup\UI-Projects\newproject\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:152:15)
at DependencyGraph.resolveDependency (D:\VR-Setup\UI-Projects\newproject\node_modules\metro\src\node-haste\DependencyGraph.js:264:43)
at Object.resolve (D:\VR-Setup\UI-Projects\newproject\node_modules\metro\src\lib\transformHelpers.js:170:21)
at resolveDependencies (D:\VR-Setup\UI-Projects\newproject\node_modules\metro\src\DeltaBundler\graphOperations.js:466:33)
at processModule (D:\VR-Setup\UI-Projects\newproject\node_modules\metro\src\DeltaBundler\graphOperations.js:232:31) at runMicrotasks ()
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async traverseDependenciesForSingleFile (D:\VR-Setup\UI-Projects\newproject\node_modules\metro\src\DeltaBundler\graphOperations.js:221:3)
at async Promise.all (index 0)
at async initialTraverseDependencies (D:\VR-Setup\UI-Projects\newproject\node_modules\metro\src\DeltaBundler\graphOperations.js:204:3)
