### ISSUE TITLE
Failed to load configuration of your project.

### ISSUE THREAD

**Issue by Sajid-Ali** [facebook/react-native#36761]
### New Version

0.70.2

### Old Version

0.64.2

### Build Target(s)

33

### Output of `react-native info`

Failed to load configuration of your project.
Config Validation Error: "project.ios.project" is not allowed
    at readConfigFromDisk (/Users/apple/Desktop/Projects/AION/kfhk.onboarding.rn/node_modules/@react-native-community/cli-config/build/readConfigFromDisk.js:68:11)
    at loadConfig (/Users/apple/Desktop/Projects/AION/kfhk.onboarding.rn/node_modules/@react-native-community/cli-config/build/loadConfig.js:59:65)
    at setupAndRun (/Users/apple/Desktop/Projects/AION/kfhk.onboarding.rn/node_modules/@react-native-community/cli/build/index.js:200:45)
    at run (/Users/apple/Desktop/Projects/AION/kfhk.onboarding.rn/node_modules/@react-native-community/cli/build/index.js:162:11)
    at Object.<anonymous> (/Users/apple/Desktop/Projects/AION/kfhk.onboarding.rn/node_modules/@react-native-community/cli/build/bin.js:8:11)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
info Run CLI with --verbose flag for more details.

### Issue and Reproduction Steps

I have upgraded react native version, I think the upgrade failed or was not complete I am struggling with the above-provided issue. I have updated all the files I followed this  https://react-native-community.github.io/upgrade-helper/?from=0.64.2&to=0.70.2

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/20899703/229323949-6596d75d-c232-49c1-bb31-07b94bb4c9c3.png">

**Comment by cortinico** [comment]
> Config Validation Error: "project.ios.project" is not allowed

You have `project.ios.project` specified somewhere inside a `react-native.config.js` (of either your project or a dependency of yours). You'll have to either remove it from your project or update your dependency so that `project.ios.project` is not used.

**Comment by Sajid-Ali** [comment]
> > Config Validation Error: "project.ios.project" is not allowed
> 
> You have `project.ios.project` specified somewhere inside a `react-native.config.js` (of either your project or a dependency of yours). You'll have to either remove it from your project or update your dependency so that `project.ios.project` is not used.

I have figured out the issue, it was because of the delta. I was trying to migrate from v0.64.X to v0.70.X I read the document, in v0.68.X react native introduced new architecture which was causing an issue cannot upgrade directly to 0.70.X. 
For me, the solution is first to upgrade to v0.68.X to make the project work with the new architecture then upgrade to a higher version in my case v0.70.X

**Comment by wkwyatt** [comment]
Do you have a link to the document you read?

> > > Config Validation Error: "project.ios.project" is not allowed
> > 
> > 
> > You have `project.ios.project` specified somewhere inside a `react-native.config.js` (of either your project or a dependency of yours). You'll have to either remove it from your project or update your dependency so that `project.ios.project` is not used.
> 
> I have figured out the issue, it was because of the delta. I was trying to migrate from v0.64.X to v0.70.X I read the document, in v0.68.X react native introduced new architecture which was causing an issue cannot upgrade directly to 0.70.X. For me, the solution is first to upgrade to v0.68.X to make the project work with the new architecture then upgrade to a higher version in my case v0.70.X
