### ISSUE TITLE
dlopen failed: library "libjscexecutor.so" not found

### ISSUE THREAD

**Issue by ramble-lo** [facebook/react-native#36807]
### New Version

0.71.4

### Old Version

0.64.1

### Build Target(s)

Android studio emulator Pixel C API 31

### Output of `react-native info`

System:

    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 61.41 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh

  Binaries:

    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    Watchman: 2023.03.20.00 - /usr/local/bin/watchman

  Managers:

    CocoaPods: Not Found

  SDKs:

    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-32 | Google APIs Intel x86_64 Atom
      Android NDK: 22.1.7171670

  IDEs:

    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild

  Languages:

    Java: javac 20 - /usr/bin/javac

  npmPackages:

    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
    react-native-macos: Not Found

  npmGlobalPackages:

    *react-native*: Not Found

### Steps to reproduce
App build successful;
Display the splash screen;
App crash and popup these error message;

### error log

```
E/ReactNativeJS: Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjscexecutor.so" not found: needed by /data/app/~~IL2fKASijY8JtkQUphdDZQ==/com.appName-mgHok4PpIXTwPk02dNMMew==/base.apk!/lib/x86_64/libreanimated.so in namespace classloader-namespace, js engine: hermes
I/ReactNativeJS: Running "appName
E/ReactNativeJS: Invariant Violation: "appName" has not been registered. This can happen if:
    * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
    * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
E/unknown:ReactNative: Exception in native call
    com.facebook.react.common.JavascriptException: Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjscexecutor.so" not found: needed by /data/app/~~IL2fKASijY8JtkQUphdDZQ==/com.appName-mgHok4PpIXTwPk02dNMMew==/base.apk!/lib/x86_64/libreanimated.so in namespace classloader-namespace, js engine: hermes, stack:
    callNativeSyncHook@1:150874
    nonPromiseMethodWrapper@1:148358
    NativeReanimated@1:794835
    anonymous@1:788104
    loadModuleImplementation@1:107286
    guardedLoadModule@1:106835
    metroRequire@1:106463
    anonymous@1:832390
    loadModuleImplementation@1:107286
    guardedLoadModule@1:106835
    metroRequire@1:106463
    anonymous@1:796625
    loadModuleImplementation@1:107286
    guardedLoadModule@1:106835
    metroRequire@1:106463
    anonymous@1:783332
    loadModuleImplementation@1:107286
    guardedLoadModule@1:106835
    metroRequire@1:106463
    anonymous@1:781926
    loadModuleImplementation@1:107286
    guardedLoadModule@1:106835
    metroRequire@1:106463
    anonymous@1:3775015
    loadModuleImplementation@1:107286
    guardedLoadModule@1:106835
    metroRequire@1:106463
    anonymous@1:3774314
    loadModuleImplementation@1:107286
    guardedLoadModule@1:106835
    metroRequire@1:106463
    anonymous@1:3769817
    loadModuleImplementation@1:107286
    guardedLoadModule@1:106835
    metroRequire@1:106463
    anonymous@1:3616269
    loadModuleImplementation@1:107286
    guardedLoadModule@1:106835
    metroRequire@1:106463
    anonymous@1:3610373
    loadModuleImplementation@1:107286
    guardedLoadModule@1:106835
    metroRequire@1:106463
    anonymous@1:3129924
    loadModuleImplementation@1:107286
    guardedLoadModule@1:106835
    metroRequire@1:106463
    anonymous@1:3127115
    loadModuleImplementation@1:107286
    guardedLoadModule@1:106835
    metroRequire@1:106463
    anonymous@1:1066601
    loadModuleImplementation@1:107286
    guardedLoadModule@1:106835
    metroRequire@1:106463
    anonymous@1:1051496
    loadModuleImplementation@1:107286
    guardedLoadModule@1:106835
    metroRequire@1:106463
    anonymous@1:113645
    loadModuleImplementation@1:107286
    guardedLoadModule@1:106792
    metroRequire@1:106463
    global@1:106047
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.jni.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:920)
E/unknown:ReactNative: Exception in native call
    com.facebook.react.common.JavascriptException: Invariant Violation: "appName" has not been registered. This can happen if:
    * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
    * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes, stack:
    invariant@1:146748
    runApplication@1:300140
    __callFunction@1:152067
    anonymous@1:150437
    __guard@1:151387
    callFunctionReturnFlushedQueue@1:150395
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.jni.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:920)
```

### android/build.gradle
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 23
        compileSdkVersion = 33
        targetSdkVersion = 33
        ndkVersion = "23.1.7779620"
        supportLibVersion = "29.0.2"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'
        classpath 'com.facebook.react:react-native-gradle-plugin'
        classpath 'com.google.gms:google-services:4.3.15'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    configurations.all {
        resolutionStrategy {
            force 'androidx.core:core-ktx:1.6.0'
        }
    }

    repositories {
    }
}
```

### android/app/build.gradle
```
apply plugin: "com.android.application"
apply plugin: "com.facebook.react"
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

import com.android.build.OutputFile

/**
 * This is the configuration block to customize your React Native Android app.
 * By default you don't need to apply any configuration, just uncomment the lines you need.
 */
react {
    /* Folders */
    //   The root of your project, i.e. where "package.json" lives. Default is '..'
    // root = file("../")
    //   The folder where the react-native NPM package is. Default is ../node_modules/react-native
    // reactNativeDir = file("../node_modules/react-native")
    //   The folder where the react-native Codegen package is. Default is ../node_modules/react-native-codegen
    // codegenDir = file("../node_modules/react-native-codegen")
    //   The cli.js file which is the React Native CLI entrypoint. Default is ../node_modules/react-native/cli.js
    // cliFile = file("../node_modules/react-native/cli.js")

    /* Variants */
    //   The list of variants to that are debuggable. For those we're going to
    //   skip the bundling of the JS bundle and the assets. By default is just 'debug'.
    //   If you add flavors like lite, prod, etc. you'll have to list your debuggableVariants.
    // debuggableVariants = ["liteDebug", "prodDebug"]

    /* Bundling */
    //   A list containing the node command and its flags. Default is just 'node'.
    // nodeExecutableAndArgs = ["node"]
    //
    //   The command to run when bundling. By default is 'bundle'
    // bundleCommand = "ram-bundle"
    //
    //   The path to the CLI configuration file. Default is empty.
    // bundleConfig = file(../rn-cli.config.js)
    //
    //   The name of the generated asset file containing your JS bundle
    // bundleAssetName = "MyApplication.android.bundle"
    //
    //   The entry file for bundle generation. Default is 'index.android.js' or 'index.js'
    // entryFile = file("../js/MyApplication.android.js")
    //
    //   A list of extra flags to pass to the 'bundle' commands.
    //   See https://github.com/react-native-community/cli/blob/main/docs/commands.md#bundle
    // extraPackagerArgs = []

    /* Hermes Commands */
    //   The hermes compiler command to run. By default it is 'hermesc'
    // hermesCommand = "$rootDir/my-custom-hermesc/bin/hermesc"
    //
    //   The list of flags to pass to the Hermes compiler. By default is "-O", "-output-source-map"
    // hermesFlags = ["-O", "-output-source-map"]
}

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Private function to get the list of Native Architectures you want to build.
 * This reads the value from reactNativeArchitectures in your gradle.properties
 * file and works together with the --active-arch-only flag of react-native run-android.
 */
def reactNativeArchitectures() {
    def value = project.getProperties().get("reactNativeArchitectures")
    return value ? value.split(",") : ["armeabi-v7a", "x86", "x86_64", "arm64-v8a"]
}

android {
    ndkVersion rootProject.ext.ndkVersion

    compileSdkVersion rootProject.ext.compileSdkVersion

    signingConfigs {
        config {
            keyAlias KEYALIAS
            keyPassword KEYPASSWORD
            storeFile file('app_release.key')
            storePassword STOREPASSWORD
        }
    }

    namespace "com.appName"
    defaultConfig {
        versionCode getIncrementingVersionCode()
        applicationId "com.appName"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionName project.property('versionName')
        resValue "string", "CodePushDeploymentKey", project.property('codePushDeploymentKey')
        manifestPlaceholders = [
            appAuthRedirectScheme: 'com.okta.app'
        ]

    }

    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include (*reactNativeArchitectures())
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.config
            buildConfigField("String","CERTIFICATE_KEY_HASH","\"${CERTIFICATE_KEY_HASH}\"")
            firebaseCrashlytics {
                nativeSymbolUploadEnabled true
                unstrippedNativeLibsDir 'build/intermediates/merged_native_libs/release/out/lib'
            }
        }
        debug {
            buildConfigField("String","CERTIFICATE_KEY_HASH","\"${CERTIFICATE_KEY_HASH}\"")
        }
    }

    flavorDimensions "env"
    productFlavors {
        dev {
            dimension "env"
        }
        stage {
            dimension "env"
            applicationIdSuffix ".stg"
        }
        preProd {
            dimension "env"
            applicationIdSuffix ".prod"
        }
        prod {
            dimension "env"
        }
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            // Example: versionCode 1 will generate 1001 for armeabi-v7a, 1002 for x86, etc.
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        defaultConfig.versionCode * 1000 + versionCodes.get(abi)
            }
        }
    }

    packagingOptions {
        pickFirst '**/armeabi-v7a/libc++_shared.so'
        pickFirst '**/x86/libc++_shared.so'
        pickFirst '**/arm64-v8a/libc++_shared.so'
        pickFirst '**/x86_64/libc++_shared.so'
        pickFirst '**/x86/libjsc.so'
        pickFirst '**/armeabi-v7a/libjsc.so'
    }
}

dependencies {
    implementation "com.facebook.react:react-android"
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    //noinspection GradleDynamicVersion
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation 'com.facebook.react:react-native:+'

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

    implementation 'com.google.firebase:firebase-core:17.0.0'
    implementation project(':react-native-fs')
    // From node_modules
    implementation 'com.scottyab:rootbeer-lib:0.0.8'
//    implementation("com.squareup.okhttp3:okhttp:4.9.1")

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}")
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }
    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }
}

task incrementVersionCode {
    description = "Increments the version code in the version.properties file"

    doLast {
        File versionPropsFile = file('version.properties')

        if (versionPropsFile.canRead()) {
            def Properties versionProps = new Properties()

            versionProps.load(new FileInputStream(versionPropsFile))

            def code = versionProps['VERSION_CODE'].toInteger() + 1

            versionProps['VERSION_CODE'] = code.toString()
            versionProps.store(versionPropsFile.newWriter(), null)
            println "VERSION_CODE incremented to "+code
        } else {
            throw new GradleException("Could not read version.properties!")
        }
    }
}

//can call this from your android DSL
int getIncrementingVersionCode() {
    def versionPropsFile = file('version.properties')

    if (versionPropsFile.canRead()) {
        def Properties versionProps = new Properties()

        versionProps.load(new FileInputStream(versionPropsFile))

        def code = versionProps['VERSION_CODE'].toInteger()
        return code
    } else {
        throw new GradleException("Could not read version.properties!")
    }
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

```

**Comment by cortinico** [comment]
Can you create a reproducer? I see you're using Reanimated. I believe some of your library is trying to load JSC while it should not. I can't tell which one though without having a reproducer.

You can use this template: https://github.com/react-native-community/reproducer-react-native

**Comment by pottercomuneo** [comment]
I'm having the same issue in RN 0.69.8, Reanimated 2.10.0, after installing RN Vision Camera, and the issue is only on Android physical device, no problem in emulator

**Comment by yberstad** [comment]
This fixed it for me, https://github.com/facebook/react-native/issues/35693#issuecomment-1362700965
