### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1 at java.util.ArrayList.get(ArrayList.java:437)

### ISSUE THREAD

**Issue by iamrohitagg** [facebook/react-native#36915]
### Description

I am getting crash on my Android device in production releases for some devices. The log I got from crashlytics is
```
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
       at java.util.ArrayList.get(ArrayList.java:437)
       at com.facebook.react.uimanager.ReactShadowNodeImpl.getChildAt(ReactShadowNodeImpl.java:266)
       at com.facebook.react.uimanager.ReactShadowNodeImpl.getChildAt(ReactShadowNodeImpl.java:55)
       at com.facebook.react.uimanager.UIImplementation.manageChildren(UIImplementation.java:382)
       at com.facebook.react.uimanager.UIManagerModule.manageChildren(UIManagerModule.java:555)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:1012)
```
One of the issue on [stackoverflow](https://stackoverflow.com/questions/59492646/java-lang-arrayindexoutofboundsexception-in-facebook-react-uimanager-viewgroupdr) recommended removing zIndex from ActivityIndicator and I tried removing that too.

### React Native Version

0.68.2

### Output of `npx react-native info`

```System:
    OS: macOS 13.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 2.78 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.4.2 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 7.18.1 - /usr/local/bin/npm
    Watchman: 2022.09.12.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.9 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Occasionally

### Snack, code example, screenshot, or link to a repository

Happens on my application ocassionally. So got no code to share.

**Comment by arnab-xd** [comment]
I am also facing the same, And the issue in sharing code is, there is not enough details in logs that can give me an idea which module is creating this issues, and it is thrown from native sides, not from JS thread.

```
05-16 12:56:28.330  7542  7542 E OplusBracketLog: [OplusViewMirrorManager] updateHostViewRootIfNeeded, not support android.view.ViewRootImpl@c722a2a
05-16 12:56:28.365  7542  7542 E AndroidRuntime: FATAL EXCEPTION: main
05-16 12:56:28.365  7542  7542 E AndroidRuntime: Process: com.ChingChingbyAkon, PID: 7542
05-16 12:56:28.365  7542  7542 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.getAndVerifyPreorderedView(ViewGroup.java:3816)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4357)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.View.draw(View.java:23464)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.View.draw(View.java:23318)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4610)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4363)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:685)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.View.draw(View.java:23464)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.View.draw(View.java:23318)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4610)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4363)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:685)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.View.draw(View.java:23464)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.View.draw(View.java:23318)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4610)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4363)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:685)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.View.draw(View.java:23316)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4610)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4363)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:685)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.View.draw(View.java:23316)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4610)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4363)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:685)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.View.draw(View.java:23316)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4610)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4363)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:685)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.View.draw(View.java:23464)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.View.draw(View.java:23318)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4610)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4363)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:685)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.View.draw(View.java:23316)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4610)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4363)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:685)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.View.draw(View.java:23316)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4610)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4363)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:685)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.View.draw(View.java:23316)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4610)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4363)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at com.facebook.react.ReactRootView.dispatchDraw(ReactRootView.java:225)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.View.draw(View.java:23316)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4610)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4363)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.View.draw(View.java:23464)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at eightbitlab.com.blurview.BlockingBlurController.updateBlur(BlockingBlurController.java:149)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at eightbitlab.com.blurview.BlockingBlurController$1.onPreDraw(BlockingBlurController.java:61)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3728)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2458)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9478)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1412)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1420)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1047)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:451)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:918)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1395)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:240)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:351)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8399)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
05-16 12:56:28.365  7542  7542 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

So far, I can produce this only on OnePlus devices, app working properly on my Xiaomi devices (A12, and A13).
- Android 13
- OnePlus Nord CE3 Lite
- OxygenOS 13.1

**Comment by iliapnmrv** [comment]
@iamrohitagg Hey! Did you manage to find a solution?

I also get this error in production, Sentry and crashlytics.
Environments:
```
Android 10, SM-G960U1
Android 13, sdk_gphone64_arm64
```
```json
"react-native": "0.75.4"
```

And I dont have react-native-blur
