### ISSUE TITLE
  java.lang.NullPointerException: Attempt to invoke virtual method 'int org.json.JSONArray.length()' on a null object reference

### ISSUE THREAD

**Issue by andreipatza** [facebook/react-native#36951]
### Description

I've got an react-native application in production. In the last few days (5-7 days) it crashes on android. The error logs are related to facebook-android-sdk.

### React Native Version

0.70.6

### Output of `npx react-native info`

info Fetching system and libraries information...
(node:94779) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 124.97 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/Documents/WORK/FE_NATIVE/dsu-fe/node_modules/.bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    Watchman: 2023.04.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.4.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: ^0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

There is no step to reproduce the error. This simply appeared in production.

### Snack, code example, screenshot, or link to a repository

This is the stack trace of the error:

` java.lang.NullPointerException: Attempt to invoke virtual method 'int org.json.JSONArray.length()' on a null object reference
        at com.facebook.internal.FacebookRequestErrorClassification$Companion.parseJSONDefinition(FacebookRequestErrorClassification.kt:118)
        at com.facebook.internal.FacebookRequestErrorClassification$Companion.createFromJSON(FacebookRequestErrorClassification.kt:166)
        at com.facebook.internal.FetchedAppSettingsManager.parseAppSettingsFromJSON$facebook_core_release(FetchedAppSettingsManager.kt:225)
        at com.facebook.internal.FetchedAppSettingsManager.loadAppSettingsAsync$lambda-0(FetchedAppSettingsManager.kt:129)
        at com.facebook.internal.FetchedAppSettingsManager.$r8$lambda$0Zs5KScD9YcdRdfqSQiSgW_MgdQ(Unknown Source:0)
        at com.facebook.internal.FetchedAppSettingsManager$$ExternalSyntheticLambda0.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)`

It appears to crash at line 118 in the FacebookRequestErrorClassification.kt
![Screenshot 2023-04-18 at 13 56 52](https://user-images.githubusercontent.com/57939307/232756759-aec34576-76c1-4c4d-84b8-3240d4a947ca.png)

**Comment by gdeusdara** [comment]
I am having the same issue here
