### ISSUE TITLE
library "libjsi.so" not found

### ISSUE THREAD

**Issue by mohitarora777** [facebook/react-native#36971]
### New Version
0.71.6

### Old Version
0.66.3

### Build Target(s)

Android 13 simulator release build

### Output of `react-native info`

<img width="451" alt="Screenshot 2023-04-19 at 12 08 47 PM" src="https://user-images.githubusercontent.com/107910744/232987630-72df720d-d437-4406-b3c0-da758a58a7c3.png">

### Issue and Reproduction Steps

 I have a brownfield app where react native resides as a submodule and is a part of DFM. As soon as DFM is installed app crashes with the following error:-

```
 FATAL EXCEPTION: main
                                                                                                    Process: in.mohalla.video, PID: 12611
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsi.so" not found: needed by /data/app/~~FBWqsEXiVrZEQBNAGRpuLg==/in.mohalla.video-Iro1c6OplDT4BYbzDJIizw==/lib/arm64/libhermes.so in namespace classloader-namespace
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at mf.c.loadLibrary(Unknown Source:0)
                                                                                                    	at mf.a.b(SourceFile:9)
                                                                                                    	at com.facebook.soloader.SoLoader.k(SourceFile:10)
                                                                                                    	at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(SourceFile:7)
                                                                                                    	at com.facebook.react.x.d(SourceFile:290)
                                                                                                    	at vp1.n.a(SourceFile:77)
                                                                                                    	at vp1.n$a.invokeSuspend(Unknown Source:11)
                                                                                                    	at dv0.a.resumeWith(SourceFile:9)
                                                                                                    	at gy0.a0.E0(Unknown Source:6)
                                                                                                    	at by0.a.resumeWith(SourceFile:23)
                                                                                                    	at dv0.a.resumeWith(SourceFile:37)
                                                                                                    	at by0.t0.run(SourceFile:111)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7898)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    	Suppressed: by0.r0: [k2{Cancelling}@a254e1b, Dispatchers.Main]
```

On Reopening it works fine. Happening on some devices, not all.

**Comment by cortinico** [comment]
> I have a brownfield app where react native resides as a submodule and is a part of DFM. As soon as DFM is installed app crashes with the following error:-

What is DFM?

**Comment by cortinico** [comment]
We can't help you much here sadly. The best would be for you to ask on StackOverflow or on other venues.
The apps needs `libjsi.so` to run. It's included inside the React Native library. If your setup is stripping it, that's outside of our control.

**Comment by mohitarora777** [comment]
I don't think this is the issue with the setup, a lot of other folks are also reporting the similar issues which has been closed with the comment that these issues are fixed in v0.71. But these are still occurring after upgrading.

https://github.com/facebook/react-native/issues/35374#issuecomment-1435488550

**Comment by cortinico** [comment]
> I don't think this is the issue with the setup, a lot of other folks are also reporting the similar issues which has been closed with the comment that these issues are fixed in v0.71. But these are still occurring after upgrading.

Can you share a reproducer using this template?
https://github.com/react-native-community/reproducer-react-native

I'll be more than happy to fix this crash if it's happening consistently

**Comment by pkpardeep482** [comment]
I am facing the same issues and using the React-native app as a dynamic module. 
Getting same error : java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsi.so" not found


Even when I analyse the bundle, my module contains libjsi.so inside lib folder. 
Let me know if there is any solution

**Comment by shubhangisuman** [comment]
Any resolution for this? Facing the same issue with dfm.
