### ISSUE TITLE
Upgrading to 0.71.6 crashes app on startup in Android

### ISSUE THREAD

**Issue by kanishk-anar** [facebook/react-native#37100]
### Description

When I upgraded my app from 0.70.6 to 0.71.6, it is crashing on startup. This is the same issue we faced when enabled new acrchitecture on 0.70.6 and had to disable it.

### React Native Version

0.71.6

### Output of `npx react-native info`

System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 91.11 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/kanishk/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Open the app and it crashes on startup in android.

### Snack, code example, screenshot, or link to a repository

`2023-04-26 15:09:52.316 20193-20193 AndroidRuntime          biz.anar                             E  FATAL EXCEPTION: main
                                                                                                    Process: biz.anar, PID: 20193
                                                                                                    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
                                                                                                    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/biz.anar/lib-main flags = 1]
                                                                                                    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/~~5Dh_sxJjioNg-0MmITBC8g==/biz.anar-iCFZvYAkg4O3DYeUJexiOg==/lib/arm64 flags = 0]
                                                                                                    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
                                                                                                    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
                                                                                                    	Native lib dir: /data/app/~~5Dh_sxJjioNg-0MmITBC8g==/biz.anar-iCFZvYAkg4O3DYeUJexiOg==/lib/arm64
                                                                                                     result: 0
                                                                                                    	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1127)
                                                                                                    	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:943)
                                                                                                    	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:855)
                                                                                                    	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:802)
                                                                                                    	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:772)
                                                                                                    	at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:26)
                                                                                                    	at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
                                                                                                    	at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:24)
                                                                                                    	at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:369)
                                                                                                    	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:316)
                                                                                                    	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:94)
                                                                                                    	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
                                                                                                    	at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:104)
                                                                                                    	at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:111)
                                                                                                    	at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:106)
                                                                                                    	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:46)
                                                                                                    	at biz.anar.ui.MainActivity.onCreate(MainActivity.kt:62)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8290)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8270)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4085)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4277)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8751)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)`

**Comment by AstrOOnauta** [comment]
Same problem here!
Update a project from RN 0.68.4 to 0.71.6 and I received same comportament.

**Comment by cortinico** [comment]
1. Can you create a reproducer?
2. Are you using build flavors?
3. Can you share your `build.gradle` file?

**Comment by AstrOOnauta** [comment]
Hey @kanishk-anar
I solved my problem (like your problem) by downgrading the version of lib "react-native-reanimated" to version 2.17.0.
I hope this solves your problems.

**Comment by pietro-marrone-dka** [comment]
Same issue here

**Comment by cortinico** [comment]
Closing as the original author @kanishk-anar is unresponsive.
@pietro-marrone-dka please open a separate issue and we can support you there
