### ISSUE TITLE
npm 3 support for running website locally

### ISSUE THREAD

**Issue by hswolff** [facebook/react-native#3718]
Mostly cross-linking to [this issue on the react-page-middleware](https://github.com/facebookarchive/react-page-middleware/issues/28), but I found the bug by trying to run the website locally to see what an update to docs looks like. 

But just FYI, that you cannot `npm start` in the `website/` directory to start a local server of the website with npm 3.

**Comment by mkonicek** [comment]
Good to know, thanks for reporting! I probably won't get to this any time soon (lots of other issues, conference, PTO).

**Comment by mkonicek** [comment]
I still have Node 4 and npm 2.7.1.

**Comment by mkonicek** [comment]
@ide Have you tried using npm 3 for RN development in general? What will we have to change? E.g. the shrinkwrap file, what else?

**Comment by ide** [comment]
I haven't tried npm 3 for building the website. For general development I believe it works already. Not sure how shrinkwrap affects the behavior of npm 3's deduping of packages, however.

**Comment by mkonicek** [comment]
OK, thank you!

**Comment by doochik** [comment]
I still have the issue when running website locally (current react-native master)
OSX 10.11.1
npm@3.3.12
node@5.1.0

Index page works well but any `/docs` page generate error
```
Connect
500 Error: TypeError: Cannot read property '__reactAutoBindMap' of undefined

    at ..mypath../react-native/website/node_modules/react-page-middleware/src/guard.js:27:12
    at onOutputGenerated (..mypath../react-native/website/node_modules/react-page-middleware/src/index.js:96:9)
    at Object.renderReactPage.done (..mypath../react-native/website/node_modules/react-page-middleware/src/DefaultRouter.js:345:7)
    at renderReactPage (..mypath../react-native/website/node_modules/react-page-middleware/src/renderReactPage.js:130:17)
    at renderComponentPackage (..mypath../react-native/website/node_modules/react-page-middleware/src/DefaultRouter.js:331:3)
    at routePackageHandler (..mypath../react-native/website/node_modules/react-page-middleware/src/DefaultRouter.js:274:5)
    at onComputePackage (..mypath../react-native/website/node_modules/react-page-middleware/src/index.js:100:9)
    at ..mypath../react-native/website/node_modules/react-page-middleware/src/guard.js:29:10
    at onWarmed (..mypath../react-native/website/node_modules/react-page-middleware/src/Packager.js:270:9)
    at ..mypath../react-native/website/node_modules/react-page-middleware/node_modules/async/lib/async.js:116:25

```

**Comment by udnisap** [comment]
It does work on 
OSX - 10.10.5
npm - 3.3.6
node - v5.0.0

**Comment by janicduplessis** [comment]
I'm pretty sure #5080 fixed this.
