### ISSUE TITLE
com.google.android.webview update restarts RN android app when fetch() is used

### ISSUE THREAD

**Issue by serge-sky** [facebook/react-native#37211]
### Description

Typically Android RN app is not getting killed when **com.google.android.webview** updates as RN no longer has Webview dependency in the code. But as soon as you add a usage of `fetch` in the app, every **com.google.android.webview** update kills Android RN App. 

Any reasons why it's like this?

### React Native Version

0.71.7

reproducible at least on 0.64 and 0.71

### Output of `npx react-native info`

Log from logcat:

04-13 23:19:55.846   607   659 I ActivityManager: Force stopping com.google.android.webview appid=10049 user=-1: installPackageLI
04-13 23:19:55.850   607   675 I PackageManager: Update system package com.google.android.webview code path from /data/app/~~mQ2d4l8yqS2st2z2aevwMg==/com.google.android.webview-EPT7Y8so2jQ3QyMiExJLEA== to /data/app/~~suhrCwXm1S6841kvUupmxQ==/com.google.android.webview-PgY_Q092Wu7M3Z68SvyCWg==; Retain data and using new
04-13 23:19:55.850   607   675 I PackageManager: Update system package com.google.android.webview resource path from /data/app/~~mQ2d4l8yqS2st2z2aevwMg==/com.google.android.webview-EPT7Y8so2jQ3QyMiExJLEA== to /data/app/~~suhrCwXm1S6841kvUupmxQ==/com.google.android.webview-PgY_Q092Wu7M3Z68SvyCWg==; Retain data and using new
04-13 23:19:55.852   607   659 I ActivityManager: Killing 14731:{package_name}/u0a17 (adj 0): stop

### Steps to reproduce

**com.google.android.webview** update restarts **RN Android app** when **fetch()** is used

This is standard AwesomeProject with an additional fetch call in `App.tsx.` Check line **66** in `App.tsx`
``` 
    fetch("http://example.com/movies.json").then(response => {
      return response.json();
    }).then(res => {
      console.log('res', res)
    }).catch(err => console.error(err));
```
**This issue is not happening when this code is not used!!!**

# Steps to reproduce

1. yarn install
2. yarn release
3. Connect your Android device via adb
4. yarn install-release-apk
5. Launch AwesomeProject app from Android phone
5. Go to Android settings, find the WebView app, uninstall updates
6. Open  AwesomeProject app from Android phone again
7. Observe that AwesomeProject app started again rather than keeping the previous state

The same can be seen when updating to the latest **com.google.android.webview** or by manually installing different versions of Webview using the link below.

# Web view versions
https://android-system-webview.en.uptodown.com/android/versions

### Snack, code example, screenshot, or link to a repository

https://github.com/skytvnz/AwesomeProject

**Comment by serge-sky** [comment]
Here is the crash log I get when call  static WebView.disableWebView()
```
java.lang.IllegalStateException: WebView.disableWebView() was called: WebView is disabled
                                                                                                    	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:246)
                                                                                                    	at android.webkit.CookieManager.getInstance(CookieManager.java:50)
                                                                                                    	at com.facebook.react.modules.network.ForwardingCookieHandler.getCookieManager(ForwardingCookieHandler.java:136)
                                                                                                    	at com.facebook.react.modules.network.ForwardingCookieHandler.get(ForwardingCookieHandler.java:53)
                                                                                                    	at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.java:61)
                                                                                                    	at com.facebook.react.modules.network.ReactCookieJarContainer.loadForRequest(ReactCookieJarContainer.java:44)
                                                                                                    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:84)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                                    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                                                    	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
                                                                                                    	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
                                                                                                    	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
```

**Comment by jar0s** [comment]
I encountered it too. It's very annoying.
Looking forward to seeing a fix.

**Comment by mwasiel78** [comment]
> WebView.disableWebView()

This worked for me.

**Comment by freeboub** [comment]
I reproduce similar issue with the demo project (no need to fetch):
$ npx react-native@latest init AwesomeProject     # (this is currently 0.74.5)
$ cd AwesomeProject && yarn android
$ adb shell am force-stop com.google.android.webview # this will kill android webview package and cause the same issue

**Comment by rastapasta** [comment]
Can confirm @freeboub 's assumptions - sucessfully tested in current RN v0.72.7 and finally mitigated the "random" nightly crashes 🙏 Full additions needed in the MainActivity.java when coming from a vanilla setup:

```java
import android.webkit.WebView;
import android.os.Bundle;

/// ...

  @Override
  public void onCreate(Bundle bundle) {
    super.onCreate(null);
    WebView.disableWebView();
  }
```
