### ISSUE TITLE
Sample App crashes with Macro benchmark library in 0.69.1.  Working fine with react-native 0.71.1

### ISSUE THREAD

**Issue by shubhamguptadream11** [facebook/react-native#37215]
### Description

In order to improve Startup Time we started working on Baseline Profiling as they guarantee to improve startup time by 30%. 
They recommend to use Macro Benchmark library in order to generate optimised baseline profile.

One can refer this docs to learn more about baseline: https://developer.android.com/topic/performance/baselineprofiles/create-baselineprofile

While running the app in benchmark variant app crashes with libhermes-execuotr.so not found. This is happening when I am on react-native 0.69.1 with react-native 0.71.6 it works fine and we are also seeing improvements of about 7% in app startup.

We are expecting it to be run on 0.69.1 as well. I would appreciate any help, thank you!

### React Native Version

0.69.1

### Output of `npx react-native info`

System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 279.68 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.2.0 - /usr/local/bin/npm
    Watchman: 2023.02.27.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.1, 29.0.2, 29.0.3, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 31.0.0
      System Images: android-24 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Intel x86_64 Atom, android-31 | Google Play Intel x86 Atom_64
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_281 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.69.1 => 0.69.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Initiate New Project
    Open terminal
    run `npx react-native@0.69.1 init D11Baseline --version 0.69.1 --template react-native-template-typescript`
    cd D11Baseline
2. Create an emulator
     Open Android Virtual Device Manager
     Create virtual device
     Launch the emulator
3. Setup Macrobenchmark library
     Open AndroidStdio with D11Baseline/android directory
     Create a Macrobenchmark module within android directory make sure to select correct package name
     Change the build variant to benchmark mode for app module
4. Try Running the test and app will crash
     run ./gradlew :benchmark:connectedCheck 
     App Crash with below logs

2023-05-02 14:04:03.300  3430-3430  SoLoader                pid-3430                             E  couldn't find DSO to load: libjscexecutor.so
                                                                                                    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.d11baseline/lib-main flags = 1]
                                                                                                    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/~~C4d5rla9TpXeuF41EhML6A==/com.d11baseline-763bnN2YxzTM-ZV2_61XTw==/lib/x86_64 flags = 0]
                                                                                                    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
                                                                                                    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
                                                                                                    	Native lib dir: /data/app/~~C4d5rla9TpXeuF41EhML6A==/com.d11baseline-763bnN2YxzTM-ZV2_61XTw==/lib/x86_64
                                                                                                     result: 0
2023-05-02 14:04:03.427  3430-3430  SoLoader                pid-3430                             E  couldn't find DSO to load: libhermes-executor-debug.so
                                                                                                    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.d11baseline/lib-main flags = 1]
                                                                                                    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/~~C4d5rla9TpXeuF41EhML6A==/com.d11baseline-763bnN2YxzTM-ZV2_61XTw==/lib/x86_64 flags = 0]
                                                                                                    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
                                                                                                    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
                                                                                                    	Native lib dir: /data/app/~~C4d5rla9TpXeuF41EhML6A==/com.d11baseline-763bnN2YxzTM-ZV2_61XTw==/lib/x86_64
                                                                                                     result: 0
2023-05-02 14:04:03.429  3430-3430  SoLoader                pid-3430                             E  couldn't find DSO to load: libhermes-executor-release.so
                                                                                                    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.d11baseline/lib-main flags = 1]
                                                                                                    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/~~C4d5rla9TpXeuF41EhML6A==/com.d11baseline-763bnN2YxzTM-ZV2_61XTw==/lib/x86_64 flags = 0]
                                                                                                    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
                                                                                                    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
                                                                                                    	Native lib dir: /data/app/~~C4d5rla9TpXeuF41EhML6A==/com.d11baseline-763bnN2YxzTM-ZV2_61XTw==/lib/x86_64
                                                                                                     result: 0
2023-05-02 14:04:03.442  3430-3430  AndroidRuntime          pid-3430                             E  FATAL EXCEPTION: main
                                                                                                    Process: com.d11baseline, PID: 3430
                                                                                                    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so
                                                                                                    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.d11baseline/lib-main flags = 1]
                                                                                                    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/~~C4d5rla9TpXeuF41EhML6A==/com.d11baseline-763bnN2YxzTM-ZV2_61XTw==/lib/x86_64 flags = 0]
                                                                                                    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
                                                                                                    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
                                                                                                    	Native lib dir: /data/app/~~C4d5rla9TpXeuF41EhML6A==/com.d11baseline-763bnN2YxzTM-ZV2_61XTw==/lib/x86_64
                                                                                                     result: 0
                                                                                                    	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1098)
                                                                                                    	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:914)
                                                                                                    	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:826)
                                                                                                    	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:773)
                                                                                                    	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:743)
                                                                                                    	at com.facebook.react.jscexecutor.JSCExecutor.loadLibrary(JSCExecutor.java:24)
                                                                                                    	at com.facebook.react.jscexecutor.JSCExecutor.<clinit>(JSCExecutor.java:20)
                                                                                                    	at com.facebook.react.jscexecutor.JSCExecutor.loadLibrary(Unknown Source:0)
                                                                                                    	at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:351)
                                                                                                    	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:318)
                                                                                                    	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:95)
                                                                                                    	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
                                                                                                    	at com.d11baseline.MainApplication.onCreate(MainApplication.java:58)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6725)
                                                                                                    	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

### Snack, code example, screenshot, or link to a repository

Sample App link for `react native` 0.69.1 version: https://we.tl/t-qMcH0vHQBz
On react native 0.71.7 things are working fine👍🏻

**Comment by cortinico** [comment]
> Sample App link for `react native` 0.69.1 version: [we.tl/t-qMcH0vHQBz](https://we.tl/t-qMcH0vHQBz)
> On react native 0.71.7 things are working fine👍🏻

If things are fixed in 0.71, why can't you just use it?

> [we.tl/t-qMcH0vHQBz](https://we.tl/t-qMcH0vHQBz)

Can you upload it on a Github Repo instead?

**Comment by cortinico** [comment]
> @cortinico But since this is a major version upgrade we can't do it right now. Can you suggest any patch related to this?

I understand, but we're focusing most of our development effort on the latest versions. 0.72 is about to be released, which means that 0.69 will get out of support.

As you mentioned that this issue is fixed in 0.71, I invite you to consider updating rather than asking the React Native team to fix bugs in previous versions which have already been addressed. I hope you can understand as our team is really limited in capacity.

**Comment by shubhamguptadream11** [comment]
Okay. But there seems to be some performance issue in 0.71.x (https://github.com/facebook/react-native/issues/36123).
Are the fixed now?

**Comment by cortinico** [comment]
Closing as this is auto resolved. Please follow-up on the other issue if you want an update
