### ISSUE TITLE
error: package com.lugg.RNCConfig does not exist

### ISSUE THREAD

**Issue by Arthurmtro** [facebook/react-native#37257]
### Description

I've started a fresh new project
This is a Monorepo app built with NX.
I have a empty web project and my new react-native one.

The build works well with my iPhone emulator, but I can't manage to make it work on my android physical device !

it always throw this error when I run nx run-android

```
info Opening the app on Android...
info JS server already running.
info Installing the app...
> Task :react-native-gradle-plugin:compileKotlin UP-TO-DATE
> Task :react-native-gradle-plugin:compileJava NO-SOURCE
> Task :react-native-gradle-plugin:pluginDescriptors UP-TO-DATE
> Task :react-native-gradle-plugin:processResources UP-TO-DATE
> Task :react-native-gradle-plugin:classes UP-TO-DATE
> Task :react-native-gradle-plugin:inspectClassesForKotlinIC UP-TO-DATE
> Task :react-native-gradle-plugin:jar UP-TO-DATE
> Task :app:buildCodegenCLI SKIPPED
> Task :app:generateCodegenSchemaFromJavaScript SKIPPED
> Task :app:generateCodegenArtifactsFromSchema SKIPPED
> Task :app:generatePackageList
> Task :app:preBuild
> Task :app:preDebugBuild
> Task :react-native-gesture-handler:assertNoMultipleInstances
> Task :react-native-gesture-handler:preBuild
> Task :react-native-gesture-handler:preDebugBuild
> Task :react-native-gesture-handler:compileDebugAidl NO-SOURCE
> Task :react-native-safe-area-context:preBuild UP-TO-DATE
> Task :react-native-safe-area-context:preDebugBuild UP-TO-DATE
> Task :react-native-safe-area-context:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :react-native-gesture-handler:packageDebugRenderscript NO-SOURCE
> Task :react-native-safe-area-context:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :react-native-gesture-handler:writeDebugAarMetadata UP-TO-DATE
> Task :react-native-safe-area-context:writeDebugAarMetadata UP-TO-DATE
> Task :app:checkDebugAarMetadata UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :react-native-gesture-handler:compileDebugRenderscript NO-SOURCE
> Task :react-native-gesture-handler:generateDebugResValues UP-TO-DATE
> Task :react-native-gesture-handler:generateDebugResources UP-TO-DATE
> Task :react-native-gesture-handler:packageDebugResources UP-TO-DATE
> Task :react-native-safe-area-context:compileDebugRenderscript NO-SOURCE
> Task :react-native-safe-area-context:generateDebugResValues UP-TO-DATE
> Task :react-native-safe-area-context:generateDebugResources UP-TO-DATE
> Task :react-native-safe-area-context:packageDebugResources UP-TO-DATE
> Task :app:mapDebugSourceSetPaths UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-gesture-handler:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-gesture-handler:processDebugManifest UP-TO-DATE
> Task :react-native-safe-area-context:extractDeepLinksDebug UP-TO-DATE
> Task :react-native-safe-area-context:processDebugManifest UP-TO-DATE
> Task :app:processDebugMainManifest UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugManifestForPackage UP-TO-DATE
> Task :react-native-gesture-handler:compileDebugLibraryResources UP-TO-DATE
> Task :react-native-gesture-handler:parseDebugLocalResources UP-TO-DATE
> Task :react-native-gesture-handler:generateDebugRFile UP-TO-DATE
> Task :react-native-safe-area-context:compileDebugLibraryResources UP-TO-DATE
> Task :react-native-safe-area-context:parseDebugLocalResources UP-TO-DATE
> Task :react-native-safe-area-context:generateDebugRFile UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :react-native-gesture-handler:generateDebugBuildConfig UP-TO-DATE
> Task :react-native-gesture-handler:compileDebugKotlin UP-TO-DATE
> Task :react-native-gesture-handler:javaPreCompileDebug UP-TO-DATE
> Task :react-native-gesture-handler:compileDebugJavaWithJavac UP-TO-DATE
> Task :react-native-gesture-handler:bundleLibCompileToJarDebug UP-TO-DATE
> Task :react-native-safe-area-context:generateDebugBuildConfig UP-TO-DATE
> Task :react-native-safe-area-context:compileDebugKotlin UP-TO-DATE
> Task :react-native-safe-area-context:javaPreCompileDebug UP-TO-DATE
> Task :react-native-safe-area-context:compileDebugJavaWithJavac UP-TO-DATE
> Task :react-native-safe-area-context:bundleLibCompileToJarDebug UP-TO-DATE

> Task :app:compileDebugJavaWithJavac FAILED
46 actionable tasks: 3 executed, 43 up-to-date
/Users/arthurmtro/Developer/projects/studentz-platform/apps/studentz-mobile/android/app/src/main/java/com/studentzmobile/MainApplication.java:12: error: package com.lugg.RNCConfig does not exist
import com.lugg.RNCConfig.RNCConfigPackage;
                         ^
Note: /Users/arthurmtro/Developer/projects/studentz-platform/apps/studentz-mobile/android/app/src/main/java/com/studentzmobile/MainActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/arthurmtro/Developer/projects/studentz-platform/apps/studentz-mobile/android/app/src/main/java/com/studentzmobile/MainApplication.java:12: error: package com.lugg.RNCConfig does not exist
import com.lugg.RNCConfig.RNCConfigPackage;
                         ^
Note: /Users/arthurmtro/Developer/projects/studentz-platform/apps/studentz-mobile/android/app/src/main/java/com/studentzmobile/MainActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

    at makeError (/Users/arthurmtro/Developer/projects/studentz-platform/node_modules/execa/index.js:174:9)
    at /Users/arthurmtro/Developer/projects/studentz-platform/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/arthurmtro/Developer/projects/studentz-platform/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:82:7)
    at async Command.handleAction (/Users/arthurmtro/Developer/projects/studentz-platform/node_modules/@react-native-community/cli/build/index.js:108:9)
info Run CLI with --verbose flag for more details.

```

Please Help me :( 

### React Native Version

0.71.6

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.28 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2023.04.17.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/arthurmtro/.rvm/gems/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 28, 31, 32, 33
      Build Tools: 29.0.3, 30.0.3
      System Images: android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: 10.2.2 => 10.2.2 
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

setup a fresh react native app

run start

press a for open on android device

### Snack, code example, screenshot, or link to a repository

Sorry didn't have

**Comment by cortinico** [comment]
```
/Users/arthurmtro/Developer/projects/studentz-platform/apps/studentz-mobile/android/app/src/main/java/com/studentzmobile/MainApplication.java:12: error: package com.lugg.RNCConfig does not exist
import com.lugg.RNCConfig.RNCConfigPackage;
```

The error is clear, this package you're importing at line 12 of `MainApplication.java` doesn't exist. 

> setup a fresh react native app

I believe this is not the case. Can you share your project?

**Comment by zahinafsar** [comment]
It's actually related to Nx react-native template

How I fixed it:
1. Remove `import com.lugg.RNCConfig.RNCConfigPackage;` this line.
2. Create an empty react-native project using react-native CLI
3. Replace the **debug.keystore** from Nx project with react-native CLI project

**Comment by cortinico** [comment]
> How I fixed it:

@Arthurmtro can you check if the solution provided by @zahinafsar works for you?

**Comment by Arthurmtro** [comment]
Yeah, this solution works,
I have checked, and the fact is that @nx/react-native is not up-to-date, and you have to build your native app yourself so thanks @zahinafsar
