### ISSUE TITLE
getting this error on android 

### ISSUE THREAD

**Issue by mrsants** [facebook/react-native#37674]
### Description

Exception com.facebook.react.common.JavascriptException:
  at com.facebook.react.modules.core.ExceptionsManagerModule.reportException (ExceptionsManagerModule.java:72)
  at java.lang.reflect.Method.invoke
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:188)
  at com.facebook.react.bridge.queue.NativeRunnable.run
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:27)
  at android.os.Looper.loop (Looper.java:154)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (MessageQueueThreadImpl.java:226)
  at java.lang.Thread.run (Thread.java:762)

### React Native Version

0.71.8

### Output of `npx react-native info`

System:
    OS: macOS 13.4
    CPU: (12) x64 Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
    Memory: 40.75 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /Users/mrsants/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/local/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

    "expo": "~48.0.18",
    "react-native": "0.71.8"

**Comment by cortinico** [comment]
Not enough information to debug this. You need to provide a reproducer, codesnippet or a Snack. We can't just support with basically just a stacktrace.

**Comment by shubhamdeol** [comment]
I opened the related issue here bit more info, yes stack trace is not clear but this is certainly an issue. 
with just 5% rollout we got 5 devices facing this issue and those users are completly blocked
https://github.com/facebook/react-native/issues/37821

**Comment by rabiaah** [comment]
Issue still there just right after trying to upgrade the Android to use the targetSdkVersion = 33
I've tried many options but the APK keep crashing, when connecting the same device with USB cable it's not crashing at all.

Where I can have more details about such bug? it's not printed anywhere.

Anyone have some directions here?

Thanks in advance,

**Comment by hotaryuzaki** [comment]
same issue here.

**Comment by habibaamri** [comment]
Same issue here! @mrsants  did you fix it or not yet

**Comment by TomasPintoKramer** [comment]
Same issue

**Comment by JaosnHsieh** [comment]
same here

**Comment by rabiaah** [comment]
Fast way to resolve it and it's actually worked fine for me.

Access Android studio, Search for "DeviceModule.kt" file,

**In the file, search for the below line:**
"deviceName" to Settings.Secure.getString(mContext.contentResolver, "bluetooth_name")

**Replace it with the below lines:**
"deviceName" to run {
      if (Build.VERSION.SDK_INT <= 31)
        Settings.Secure.getString(mContext.contentResolver, "bluetooth_name")
      else
        Settings.Global.getString(mContext.contentResolver, Settings.Global.DEVICE_NAME)
    },

**Source:** https://github.com/expo/expo/pull/19666/files

I've tested the APK version from Google play and working fine.

**Comment by burakkilinc11** [comment]
I still have this problem. Is there a solution?

**Comment by rabiaah** [comment]
> I still have this problem. Is there a solution?

Please elaborate on your issue? What you’re facing exactly?

**Comment by burakkilinc11** [comment]
at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
at android.os.Looper.loopOnce(Looper.java:211)
at android.os.Looper.loop(Looper.java:300)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
at java.lang.Thread.run(Thread.java:1012)
I'm getting this crashing issue on android, I tried several solutions but it didn't work.

**Comment by rabiaah** [comment]
Can you share the file content of "DeviceModule.kt"?

Path: packages/expo-device/android/src/main/java/expo/modules/device/DeviceModule.kt
(Inside the Android Studio).

**Comment by FrancoTanzarellaEviivo** [comment]
I'm seeing an increase in this issue on play console. I'm not using expo so not sure if above fixes are valid for my case.

```Exception com.facebook.react.common.JavascriptException:
  at com.facebook.react.modules.core.ExceptionsManagerModule.reportException (ExceptionsManagerModule.java:65)
  at java.lang.reflect.Method.invoke
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:149)
  at com.facebook.jni.NativeRunnable.run (NativeRunnable.java)
  at android.os.Handler.handleCallback (Handler.java:958)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:29)
  at android.os.Looper.loopOnce (Looper.java:230)
  at android.os.Looper.loop (Looper.java:319)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (MessageQueueThreadImpl.java:234)
  at java.lang.Thread.run (Thread.java:1012)

**Comment by Sahil-zet** [comment]
@FrancoTanzarellaEviivo did you find the root cause of this issue?

**Comment by FrancoTanzarellaEviivo** [comment]
> @FrancoTanzarellaEviivo did you find the root cause of this issue?

I have not, unfortunately.

**Comment by eliot-ye** [comment]
Same issue

**Comment by Pardeep03315** [comment]
I am also facing same issue after upgrading 33 to 34 , my google play console's anr and crashes  display this error below

Exception com.facebook.react.common.JavascriptException:
  at com.facebook.react.modules.core.ExceptionsManagerModule.reportException (ExceptionsManagerModule.java:65)
  at java.lang.reflect.Method.invoke
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:146)
  at com.facebook.jni.NativeRunnable.run
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:27)
  at android.os.Looper.loopOnce (Looper.java:233)
  at android.os.Looper.loop (Looper.java:344)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (MessageQueueThreadImpl.java:235)
  at java.lang.Thread.run (Thread.java:1012)

**Comment by rabiaah** [comment]
Hi,

It's not related only to expo, simply access Android, try search for the below code in all your files 

"deviceName" to Settings.Secure.getString(mContext.contentResolver, "bluetooth_name")

If you have found it, try replace it with the below:

"deviceName" to run {
      if (Build.VERSION.SDK_INT <= 31)
        Settings.Secure.getString(mContext.contentResolver, "bluetooth_name")
      else
        Settings.Global.getString(mContext.contentResolver, Settings.Global.DEVICE_NAME)
    },


Try and share results.

**Comment by ManuelLamon** [comment]
Hi, mi app in google play have this error many times 
Exception com.facebook.react.common.JavascriptException:
  at com.facebook.react.modules.core.ExceptionsManagerModule.reportException (ExceptionsManagerModule.java:65)
  at java.lang.reflect.Method.invoke
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:149)
  at com.facebook.jni.NativeRunnable.run
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:29)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (MessageQueueThreadImpl.java:234)
  at java.lang.Thread.run (Thread.java:1012)

**Comment by vanditmehta** [comment]
Same issue

**Comment by ALamm** [comment]
+1 same issue here for Android, and increasing number of users having app crash.

I'm using Expo (Version 51)

The only stack trace info is:
```Exception com.facebook.react.common.JavascriptException:
  at com.facebook.react.modules.core.ExceptionsManagerModule.reportException (ExceptionsManagerModule.java:65)
  at java.lang.reflect.Method.invoke
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:146)
  at com.facebook.jni.NativeRunnable.run
  at android.os.Handler.handleCallback (Handler.java:958)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:27)
  at android.os.Looper.loopOnce (Looper.java:243)
  at android.os.Looper.loop (Looper.java:338)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (MessageQueueThreadImpl.java:233)
  at java.lang.Thread.run (Thread.java:1012)```

**Comment by aamagda** [comment]
+1 same issue

- bare RN project
- expo@51.0.39
- react-native@0.74.5

**Comment by yjxiao123** [comment]
+1 com.facebook.react.bridge.JavaModuleWrapper.invoke(int, com.facebook.react.bridge.ReadableNativeArray) on null object


focus on [https://github.com/facebook/react-native/blob/eba38b831c06675bb3a9089fc0b081f573aa3d10/packages/react-native/ReactAndroid/src/main/jni/react/jni/JavaModuleWrapper.cpp#L115](url) ,

`void JavaNativeModule::invoke(
    unsigned int reactMethodId,
    folly::dynamic&& params,
    int callId) {
  messageQueueThread_->runOnQueue(
      [this, reactMethodId, params = std::move(params), callId] {
        static auto invokeMethod =
            wrapper_->getClass()
                ->getMethod<void(jint, ReadableNativeArray::javaobject)>(
                    "invoke");
#ifdef WITH_FBSYSTRACE
        if (callId != -1) {
          fbsystrace_end_async_flow(TRACE_TAG_REACT, "native", callId);
        }
#endif
        invokeMethod(
            wrapper_,
            static_cast<jint>(reactMethodId),
            ReadableNativeArray::newObjectCxxArgs(params).get());
      });
}`

Null pointer protection for Java objects should be implemented.

**Comment by deflexable** [comment]
any update on this 😕..?

**Comment by Shasikhan** [comment]
still facing same issue with bare expo, any update?

"react": "19.0.0",
"react-native": "0.79.6",
"expo": "~53.0.23",

**Comment by dhairyasenjaliya** [comment]
Hi, facing similar issues, with no clear logs any one resolved it yet !

**Comment by rabiaah** [comment]
> Hi, facing similar issues, with no clear logs any one resolved it yet !

Please share something to check and try help, even try connect device with debug mode and see what you have in the logs...

**Comment by dhairyasenjaliya** [comment]
On debug mode no crash
On sentry no trace for this 

On Google play console crash and ARN console below error log for few users 

RN version : 0.79.4
newArchEnabled: true 

<img width="1281" height="222" alt="Image" src="https://github.com/user-attachments/assets/6a84ee35-b26a-4fea-bae5-63828ff9aca9" />

**Comment by rabiaah** [comment]
> On debug mode no crash On sentry no trace for this
> 
> On Google play console crash and ARN console below error log for few users
> 
> RN version : 0.79.4 newArchEnabled: true
> 
> <img alt="Image" width="1281" height="222" src="https://private-user-images.githubusercontent.com/47522946/526986724-6a84ee35-b26a-4fea-bae5-63828ff9aca9.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU4Nzg5ODUsIm5iZiI6MTc2NTg3ODY4NSwicGF0aCI6Ii80NzUyMjk0Ni81MjY5ODY3MjQtNmE4NGVlMzUtYjI2YS00ZmVhLWJhZTUtNjM4MjhmZjlhY2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjE2VDA5NTEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjN2Q3Nzc1ODQ3MTljMDY4YmY4MDIyYTBlNTMxOTJkYjBmYmE2ZWM1NDAzZmViYTdjZjA5MmIzZTI1NWJiNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rT-KXyGp7Ea1X3kTnO3AnuNlQ_hPjfjJepxF7MaVTg0">

On which Device you're testing? in general old devices will not show this full Error, try to use Device with at least Android 13 Device then only you can able to see the exact error as below for an example:

**com.facebook.react.common.JavascriptException: Error: Exception in HostObject::get(propName:NativeUnimoduleProxy): java.lang.SecurityException: Settings key: <bluetooth_name> is only readable to apps with targetSdkVersion lower than or equal to: 31, stack:**
@403:125
h@2:1585
@21:1245
h@2:1585
@12:466
h@2:1585
@11:482
h@2:1585
@9:54
h@2:1585
@8:204
h@2:1585
@6:45
h@2:1585
d@2:958
global code@3211:3
...
...
...

Try check my replies if can help you, like:
https://github.com/facebook/react-native/issues/37674#issuecomment-2018455025

**Comment by Shasikhan** [comment]
@rabiaah This solution is already there but still having crash reports.

**Comment by dhairyasenjaliya** [comment]
@rabiaah  not using expo

**Comment by rabiaah** [comment]
Not sure if it can help you out, please try download **Antigravity AI**, and let it scan your project and help to resolve the issue.
Without having a proper exception it will really be hard to identify the issue.

or 

To debug this, you need the full exception message and the JavaScript stack trace. Here's how to get it:
The recommended Option is to Check Logcat:
`adb logcat *:E | grep -E "(ReactNative|JS|JavaScript)"`

**Comment by dhairyasenjaliya** [comment]
hi anyone found any useful thing to fix yet ?
