### ISSUE TITLE
Cannot find DatePickerIOS module for 'react-native-date-picker' on only IOS.

### ISSUE THREAD

**Issue by smiley717** [facebook/react-native#37817]
### Description

Hey everyone, Hope you are doing very well! I am using 'react-native-date=picker@4.2.13' module for my application.
I am not entirely sure it's good to share here for this specific module, but I couldn't find a solution from main collaborator or others, so that I just wanted to share the issue directly here to get help from react-native exports as well as native exports to get any insights.
It works well on Android platform, but when I try to use it on IOS platform, I face below issue so that I cannot use it (not crashed app, but modal doesn't open). Could anyone tell me what may be the issue or how to resolve it. I am thinking about using community library (@react-native-community/datetimepicker), but before doing that, I hope what is the reason of this issue or hope to get resolved as it's also good one though.

![image](https://github.com/facebook/react-native/assets/80674675/8a17f96d-e6e4-4b5f-90b5-e68b5f9556c2)

### React Native Version

 0.71.4

### Output of `npx react-native info`

```
System:
    OS: macOS 13.4
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
    Memory: 1018.90 MB / 31.63 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: 2023.05.22.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/user/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

### Steps to reproduce

import DatePicker from 'react-native-date-picker';

```
<DatePicker
        modal
        open={dateOpen}
        date={date
        mode="date"
        onConfirm={date => {setDate(date)}}
        onCancel={() => {
          setDateOpen(false);
        }}
      />
```

### Snack, code example, screenshot, or link to a repository

```
None of these files exist:
  * node_modules/react-native/Libraries/Components/DatePicker/DatePickerIOS(.native|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx)
  * node_modules/react-native/Libraries/Components/DatePicker/DatePickerIOS/index(.native|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx)
  15 | import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
  16 | import typeof Button from './Libraries/Components/Button';
> 17 | import typeof DatePickerIOS from './Libraries/Components/DatePicker/DatePickerIOS';
     |                                   ^
  18 | import typeof DrawerLayoutAndroid from './Libraries/Components/DrawerAndroid/DrawerLayoutAndroid';
  19 | import typeof FlatList from './Libraries/Lists/FlatList';
  20 | import typeof Image from './Libraries/Image/Image';
    at ModuleResolver.resolveDependency (/Users/user/Desktop/Work/synkbooks_app_v1/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:137:15)
    at DependencyGraph.resolveDependency (/Users/user/Desktop/Work/synkbooks_app_v1/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
    at Object.resolve (/Users/user/Desktop/Work/synkbooks_app_v1/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/Users/user/Desktop/Work/synkbooks_app_v1/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/Users/user/Desktop/Work/synkbooks_app_v1/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Graph._addDependency (/Users/user/Desktop/Work/synkbooks_app_v1/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 0)
    at async Graph._processModule (/Users/user/Desktop/Work/synkbooks_app_v1/node_modules/metro/src/DeltaBundler/Graph.js:263:5)
    at async Graph._traverseDependenciesForSingleFile (/Users/user/Desktop/Work/synkbooks_app_v1/node_modules/metro/src/DeltaBundler/Graph.js:207:5)
Error: Unable to resolve module ./Libraries/Components/DatePicker/DatePickerIOS from /Users/user/Desktop/Work/synkbooks_app_v1/node_modules/react-native/index.js: 
```

**Comment by smiley717** [comment]
Still exist this issue when i try to use another library [react-native-modal-datetime-picker](https://www.npmjs.com/package/react-native-modal-datetime-picker). Do I need to upgrade / downgrade react-native version?

**Comment by smiley717** [comment]
It was happened when I am using IOS 16.4 simulator, not sure why this is happening on and how to solve it. In order to keep going, I needed to downgrade IOS simulator version(15) and worked for me.

**Comment by cortinico** [comment]
Hi @smiley717 
Thanks for reporting this issue.

Please report this issue against `react-native-date-picker` first:
https://github.com/henninghall/react-native-date-picker/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.

**Comment by JovanSr** [comment]
Why is this closed, where is the issue created in react-native-date-picker.

**Comment by cortinico** [comment]
> This issue is related to react native itself (potentially only an older version). See stacktrace in the original post

Can you elaborate? Also why only on older version?

**Comment by henninghall** [comment]
Stacktrace originates from `node_modules/react-native/index.js` and errors on DatePickerIOS which was earlier included (and deprecated) in React Native. DatePickerIOS component is not being used within `react-native-date-picker`.

I have not seen this being reported from a user on react native 0.73 which could suggest that this has already been fixed. I haven't verified it.

**Comment by cortinico** [comment]
@smiley717 have you solved this issues? Could you still reproduce on 0.73? If yes, let's create a reproducer using https://github.com/react-native-community/reproducer-react-native and we can re-open this issue

**Comment by srithar21** [comment]
Same issue exist in react native version 0.69. Any solution?

**Comment by Lourguioui** [comment]
> @smiley717 have you solved this issues? Could you still reproduce on 0.73? If yes, let's create a reproducer using https://github.com/react-native-community/reproducer-react-native and we can re-open this issue

the issue still exists and i verified, it's react-native xcode related, i don't even have react-native-date-picker package in my app and i still get that error message, so please can you reopen the issue for people to collaborate. Also this happened when i upgraded my xcode to 15.4.

**Comment by miteshdevg** [comment]
> > @smiley717 have you solved this issues? Could you still reproduce on 0.73? If yes, let's create a reproducer using https://github.com/react-native-community/reproducer-react-native and we can re-open this issue
> 
> @cortinico the issue still exists and i verified, it's react-native xcode related, i don't even have react-native-date-picker package in my app and i still get that error message, so please can you reopen the issue for people to collaborate. Also this happened when i upgraded my xcode to 15.4.

+1 same here

**Comment by davewang** [comment]
> > > @smiley717 have you solved this issues? Could you still reproduce on 0.73? If yes, let's create a reproducer using https://github.com/react-native-community/reproducer-react-native and we can re-open this issue
> > 
> > 
> > @cortinico the issue still exists and i verified, it's react-native xcode related, i don't even have react-native-date-picker package in my app and i still get that error message, so please can you reopen the issue for people to collaborate. Also this happened when i upgraded my xcode to 15.4.
> 
> +1 same here

+1 same here
But the issue happens in react-native-macos, ios is Ok!

**Comment by sa1utep1z** [comment]
> Reference in n

+1, my heart is broken:(

**Comment by sa1utep1z** [comment]
> > > > @smiley717 have you solved this issues? Could you still reproduce on 0.73? If yes, let's create a reproducer using https://github.com/react-native-community/reproducer-react-native and we can re-open this issue
> > > 
> > > 
> > > @cortinico the issue still exists and i verified, it's react-native xcode related, i don't even have react-native-date-picker package in my app and i still get that error message, so please can you reopen the issue for people to collaborate. Also this happened when i upgraded my xcode to 15.4.
> > 
> > 
> > +1 same here
> 
> +1 same here But the issue happens in react-native-macos, ios is Ok!

+1

**Comment by henninghall** [comment]
macOS is unsupported

**Comment by RaguRam1991** [comment]
same error

None of these files exist:
node_modules/react-native/Libraries/Components/DatePicker/DatePickerIOS(.native|.native.jsx|.jsx|.native.js|.js|.native.ts|.ts|.native.tsx|.tsx|.native.cjs|.cjs|.native.json|.json)

**Comment by mensonones** [comment]
1 - Open your terminal and navigate to the **node_modules/react-native/Libraries/Components/DatePicker/** directory
2 - Create a new file named **DatePickerIOS.js** in the current directory
3 - Open the **DatePickerIOS.js** file in a text editor and add the following code:

```javascript
import { Platform } from 'react-native';

const DatePickerIOS = Platform.select({
  ios: require('./DatePickerIOS.ios').default,
  android: require('./DatePickerIOS.android').default,
});

export default DatePickerIOS;
```

Tested only iOS
