### ISSUE TITLE
My React Native Android app crashes in production on launch.

### ISSUE THREAD

**Issue by Madhu02** [facebook/react-native#37823]
### Description

My React Native android application crashing on launch, dyntrace have captured the crash logs and its looks as below.

java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
       at com.facebook.react.bridge.ReadableNativeArray.getDouble(ReadableNativeArray.java:114)
       at com.facebook.react.bridge.JavaMethodWrapper$4.extractArgument(JavaMethodWrapper.java:64)
       at com.facebook.react.bridge.JavaMethodWrapper$4.extractArgument(JavaMethodWrapper.java:60)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:359)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:164)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:764)

Unable to figure out which library causing this issue. Looked into react-native-reanimted and using version 2.15.0 and react-native.maps with version 0.26.1.

What might be the issue from the above crash log ?

### React Native Version

0.66.5

### Output of `npx react-native info`

Package lerna has been ignored because it contains invalid configuration.
Beta/node_modules/lerna/package.json
info Fetching system and libraries information...
System:
0S: macOS 13.3.1
CPU: (18) arm64 Apple MI Pro
Memory: 3.79 GB / 32.88 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 16.14.2 - /us/local/bin/node
Yarn: 1.22.19 - /usr/local/bin/yarn pm: 8.5.8 - /us/local/bin/rpm
Watchman: 2822.11.14.88 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
SDKs:
105 SDK:
Platforms: Driverkit 22.4, 105 16.4, macOS 13.3, tvOS 16.4, watchos 9.
Android SOK: Not Found
4
IDEs:
Android Studio: 3.5 AI-191.8826.42.35.6818548
Xcode: 14.3.1/14E388c - /usr/bin/scodebuild
Languages:
Java: Not Found opmPackages:
@react-native-community/cli: Not Found react: Not Found react-native: Not Found react-native-macos: Not Found npmGlobalPackages:
treact-natives: Not Found

### Steps to reproduce

Unable to reproduce this issue in debug mode. Only few crashes were reported on the production app which is live.

### Snack, code example, screenshot, or link to a repository

No problem with debug code.

**Comment by Madhu02** [comment]
Does upgrading to the latest react-native version will solve this issue ?

**Comment by cortinico** [comment]
Not enough information to debug this sadly. We would need a minimal reproducer or any insights on which library is causing this.

Also you're on an unsupported React Native version so there is not much we can do here, sadly.
