### ISSUE TITLE
ReactFragment in android and app crashing on react-native 0.71.7

### ISSUE THREAD

**Issue by hmhdworks** [facebook/react-native#37940]
### Description

I am building an app where I need to use both native screens and some parts of React Native. I decided to use fragments in Android for this purpose. React Native is loading, but when I click on the fragment, the app crashes. Additionally, the log shows 'Running "app" with {"initialProps":{"message":"test message"},"rootTag":11}', and fabric is not enabled. How can I enable fabric? I couldn't find the class 'import com.facebook.react.defaults.DefaultReactFragment'.

### React Native Version

0.71.7

### Output of `npx react-native info`

FATAL EXCEPTION: main
                                                                                                    Process: com.mayowish, PID: 12064
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.swmansion.reanimated.NativeProxy.performOperations()' on a null object reference
                                                                                                    	at com.swmansion.reanimated.NodesManager.performOperations(NodesManager.java:188)
                                                                                                    	at com.swmansion.reanimated.NodesManager.onEventDispatch(NodesManager.java:283)
                                                                                                    	at com.facebook.react.uimanager.events.EventDispatcherImpl.dispatchEvent(EventDispatcherImpl.java:116)
                                                                                                    	at com.facebook.react.uimanager.JSTouchDispatcher.handleTouchEvent(JSTouchDispatcher.java:80)
                                                                                                    	at com.facebook.react.ReactRootView.dispatchJSTouchEvent(ReactRootView.java:385)
                                                                                                    	at com.facebook.react.ReactRootView.onInterceptTouchEvent(ReactRootView.java:263)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2653)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
                                                                                                    	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
                                                                                                    	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
                                                                                                    	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
                                                                                                    	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1905)
                                                                                                    	at android.app.Activity.dispatchTouchEvent(Activity.java:4263)
                                                                                                    	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
                                                                                                    	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
                                                                                                    	at android.view.View.dispatchPointerEvent(View.java:15262)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6654)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6454)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5910)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5967)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5933)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6098)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5941)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6155)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5914)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5967)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5933)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5941)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5914)
                                                                                                    	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8996)
                                                                                                    	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8947)
                                                                                                    	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8916)
                                                                                                    	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9119)
                                                                                                    	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:161)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
2023-06-16 21:47:40.512 12064-12064 AndroidRuntime          com.mayowish                         E  	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

### Steps to reproduce

integrate react-native in android fragment and click on fragment anywhere. app will crash.

### Snack, code example, screenshot, or link to a repository

package com.app;

import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.Fragment;

import android.app.Application;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;

import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactFragment;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.defaults.DefaultReactNativeHost;
import com.facebook.react.modules.core.DefaultHardwareBackBtnHandler;
import com.facebook.soloader.SoLoader;

import java.util.List;

public class MainActivity2 extends AppCompatActivity implements ReactApplication, DefaultHardwareBackBtnHandler {
    private MainApplication mainApplication;
    private Button mButton;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mainApplication = (MainApplication) getApplication();
        SoLoader.init(this, false);
        setContentView(R.layout.activity_main);
        mButton = findViewById(R.id.button);
        mButton.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                Fragment reactNativeFragment = new ReactFragment.Builder()
                        .setComponentName("app")
                        .setLaunchOptions(getLaunchOptions("test message"))
                        .build();

                getSupportFragmentManager()
                        .beginTransaction()
                        .add(R.id.reactNativeFragment, reactNativeFragment)
                        .commit();

            }
        });
    }

    private Bundle getLaunchOptions(String message) {
        Bundle initialProperties = new Bundle();
        initialProperties.putString("message", message);
        return initialProperties;
    }
//    private final ReactNativeHost mReactNativeHost = new DefaultReactNativeHost(MainActivity2.this) {
//        @Override
//        public boolean getUseDeveloperSupport() {
//            return BuildConfig.DEBUG;
//        }
//
//        protected List<ReactPackage> getPackages() {
//            List<ReactPackage> packages = new PackageList(this).getPackages();
//            // Packages that cannot be autolinked yet can be added manually here
//            return packages;
//        }
//    };

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mainApplication.getReactNativeHost();
    }

    @Override
    public void invokeDefaultOnBackPressed() {

    }
}

**Comment by cortinico** [comment]
> Additionally, the log shows 'Running "app" with {"initialProps":{"message":"test message"},"rootTag":11}', and fabric is not enabled. How can I enable fabric? I couldn't find the class 'import com.facebook.react.defaults.DefaultReactFragment'.

Let's not mix things and consider those as two separate things. Could you provide a reproducer using the tools linked above?

**Comment by hmhdworks** [comment]
@cortinico  I have fixed the crash issue that is not related to react-native, but the new architecture is still not enabled in the fragment, which is causing low frame rates. How can I enable the new architecture in the android fragment?

**Comment by cortinico** [comment]
> How can I enable the new architecture in the android fragment?

You can use the `setFabricEnabled` property in the `ReactFragment.Builder` class:
https://github.com/facebook/react-native/blob/995bb3e995e47c389db421d5658d3336053e0d10/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactFragment.java#L179-L221
