### ISSUE TITLE
MainApplication.onCreate: java.lang.UnsatisfiedLinkError - dlopen failed: "/data/data/com.patenteapp/lib-3/libc++_shared.so" is for EM_AARCH64 (183) instead of EM_X86_64 (62)

### ISSUE THREAD

**Issue by Robiullah2244** [facebook/react-native#37943]
### Description

Fatal Exception: java.lang.UnsatisfiedLinkError
couldn't find DSO to load: libhermes.so caused by: couldn't find DSO to load: libjsi.so caused by: couldn't find DSO to load: libfolly_runtime.so caused by: couldn't find DSO to load: libglog.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.patenteapp/lib-3/libc++_shared.so" is for EM_AARCH64 (183) instead of EM_X86_64 (62) result: 0 result: 0 result: 0 result: 0 result: 0

### React Native Version

0.70.10

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 76.67 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - /opt/homebrew/bin/npm
    Watchman: 2023.03.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/mdrobiullah/.rvm/gems/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.10 => 0.70.10 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

It randomly happens in my live app.

<img width="1272" alt="image" src="https://github.com/facebook/react-native/assets/33126665/b96c37f8-b3a3-481f-947a-e021e62ab379">

### Snack, code example, screenshot, or link to a repository

What code do I have to paste here?

**Comment by rvasseur31** [comment]
For information, I too have this bug report on Firebase Crashlytics.
While analyzing the bug, I noticed that it had occurred 6 times in total, even though my application had not been officially validated by Google.
Validation date and time: June 5, 15:45
Date and time of first crash: May 31, 15:51:47
Date and time of last crash: June 1, 13:12:07

NB. This is the same version and the same build version, and I had activated managed publication.

**Comment by anniewey** [comment]
Same with @rvasseur31 . Observing this error is Firebase Crashlytics on rooted OnePlus8Pro (Android 11)

**Comment by bgchaudhary** [comment]
> Same with @rvasseur31 . Observing this error on Firebase Crashlytics on rooted OnePlus8Pro (Android 11)

Got the same error for the same device OnePlus8Pro (Android 11).

**Comment by Robiullah2244** [comment]
I updated the React native version to 0.70.10. But still the same issue

**Comment by BuiHung1612** [comment]
> > Same with @rvasseur31 . Observing this error on Firebase Crashlytics on rooted OnePlus8Pro (Android 11)
> 
> Got the same error for the same device OnePlus8Pro (Android 11).

![image](https://github.com/facebook/react-native/assets/63986782/6c937320-abcd-4a2d-a551-443a374988e7)
Same toooo

**Comment by Robiullah2244** [comment]
I am experiencing issues on the following device models: Galaxy A12, OnePlus8Pro, Redmi 9, MED-LX9N, Mi 9X

**Comment by Artem99-debug** [comment]
Experiencing the same thing on oneplus8Pro.
I did try using my app with oneplus8pro and even though i get this error in firebase nothing happens when using the app.
I wonder what's going on.

**Comment by nscerrimt** [comment]
did anyone manage to find a fix for this please?

**Comment by dannyhw** [comment]
Getting this in react native 0.72 too anyone know what this is? I can share logs or stack traces if needed.

**Comment by RijanFedo** [comment]
Any update on this issue ??

**Comment by RijanFedo** [comment]
Facing the same issue with oneplus8pro(Android 11).Please update the if there is any fix for this !

**Comment by nmateo** [comment]
Getting the same issue on some devices: 

Nexus5X
OnePlus8Pro

React-Native 0.72.4

**Comment by yernandus** [comment]
same thing here

**Comment by vital-33** [comment]
same error

**Comment by limariea** [comment]
Occurs on OnePlus8Pro and Nexus 5X devices. Errors are sent to the crashlytics on the production environment

 Device OnePlus8Pro:
 ```
Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.myapp/lib-3/libc++_shared.so" is for EM_AARCH64 (183) instead of EM_X86_64 (62) result: 0 result: 0
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:896)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:725)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:649)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:629)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
       at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
       at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:29)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1017)
       at java.lang.Thread.run(Thread.java:923)
```

 Device Nexus 5X:
```
Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.myapp/lib-main flags = 1]
	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/com.myapp-fd7YdPXtHMgkfGyy4U2kUg==/lib/x86 flags = 0]
	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
	Native lib dir: /data/app/com.myapp-fd7YdPXtHMgkfGyy4U2kUg==/lib/x86
 result: 0
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:896)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:725)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:649)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:629)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
       at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
       at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:29)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1017)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by hungtooc** [comment]
same issue,
```
java.lang.UnsatisfiedLinkError - dlopen failed: "/data/data/com.***.***/lib-3/libc++_shared.so" is for EM_AARCH64 (183) instead of EM_X86_64 (62)
```
 
Devices:
Vivo:
-  V2142

Google:
- Nexus 5X
- Nexus 5

Xiaomi:
- Redmi 9
- Redmi Note 8 Pro

Samsung:
- Galaxy A12

Other:
- Oppo
- OnePlus

**Comment by marcus-menezes** [comment]
Same issue

**Comment by namti** [comment]
> Occurs on OnePlus8Pro and Nexus 5X devices. Errors are sent to the crashlytics on the production environment
> 
> Device OnePlus8Pro:
> 
> ```
> Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.myapp/lib-3/libc++_shared.so" is for EM_AARCH64 (183) instead of EM_X86_64 (62) result: 0 result: 0
>       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:896)
>       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:725)
>       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:649)
>       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:629)
>       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
>       at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
>       at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:29)
>       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1017)
>       at java.lang.Thread.run(Thread.java:923)
> ```
> 
> Device Nexus 5X:
> 
> ```
> Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
> 	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.myapp/lib-main flags = 1]
> 	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/com.myapp-fd7YdPXtHMgkfGyy4U2kUg==/lib/x86 flags = 0]
> 	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
> 	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
> 	Native lib dir: /data/app/com.myapp-fd7YdPXtHMgkfGyy4U2kUg==/lib/x86
>  result: 0
>        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:896)
>        at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:725)
>        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:649)
>        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:629)
>        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
>        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
>        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:29)
>        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1017)
>        at java.lang.Thread.run(Thread.java:764)
> ```

Same as yours. I wonder if they are test devices from Google?

**Comment by nonam4** [comment]
+1

**Comment by bkhan932** [comment]
+1

**Comment by shivarajpu** [comment]
please solve the error

**Comment by pieterreuse** [comment]
+1 - one of my users has this on a OnePlus8Pro

**Comment by FernandoAOborges** [comment]
> +1 - one of my users has this on a OnePlus8Pro

same here: "react-native": "0.71.8",

**Comment by FernandaKPeron** [comment]
same on React Native 0.73.4

**Comment by isnolan** [comment]
+1

**Comment by Mahmoudz11** [comment]
same OnePlus8Pro

**Comment by manjubhatt** [comment]
same issue on Android 13

**Comment by wahidshadab** [comment]
+1

**Comment by Brunonascdev** [comment]
+1

**Comment by interstates21** [comment]
+1

**Comment by dmytrokhomenko** [comment]
same issue

**Comment by VictorGanenco1** [comment]
same issue

**Comment by cw-saptarshi-das** [comment]
Has anyone found a solution to this issue yet?

**Comment by SaadBinWaheed-og** [comment]
+1 OnePlus8Pro

<img width="515" alt="Image" src="https://github.com/user-attachments/assets/b8febc49-5393-410e-8be2-20ef0cb58fcb" />

**Comment by benedusi** [comment]
Was anyone able to reproduce this on a real device?

**Comment by Vadko** [comment]
+1

**Comment by zaferatli** [comment]
+1 same as for oneplus and huawei devices.

problem is the soloader had wrong implementation on detect os arch for x64 in this line https://github.com/facebook/SoLoader/commit/3311e1ab34d4a7abdd681e33682a5fe700c0feac#diff-142b4aed21418c4f1369ab94e804cd2846e901451e049870e8bb04660d1ae28dR138 loader assume that arm64 is x64 arch and trying import wrong so file.

and its fixed on solader 0.9.0+ version

related google paper: https://support.google.com/faqs/answer/12576726

@cortinico this issue may closed as my opinion

linked issue for https://github.com/facebook/SoLoader/issues/59

> I was running into the same issue but wasn't able to simply upgrade react-native because of some other dependencies.
> 
> The fix for this issue is part of **SoLoader 0.8.1**, you only need to force this dependency to a version higher than 0.8.0.
> 
> Root level `build.gradle`
> 
> ```
> allprojects {
>     repositories {
>         google()
>         center()
> 		...
> 
>         // force dependency versions on all subprojects
>         configurations.all {
>             resolutionStrategy {
> 
>                 // use 0.9.0 to fix crash on Android 11
>                 force "com.facebook.soloader:soloader:0.9.0"
> 			}
> 		}
> 	}
> }
> ```

**Comment by cortinico** [comment]
Thanks for the clarification @zaferatli. Closing then

**Comment by abhishek160598** [comment]
we are using react-native 0.74.5 and it has his inbuild soloader version 0.10.5 but we are still facing the same crash. @zaferatli , @cortinico 

[stacktrace.txt](https://github.com/user-attachments/files/24797224/stacktrace.txt)
