### ISSUE TITLE
Intent links opened from GMAIL cause java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by adammarr** [facebook/react-native#38023]
### Description

Intents from links (we are using Branch.io for deeplinking), and while links from the browser or Messages, etc (and anything on iOS) work fine, links from android GMAIL cause a crash. App crashes in react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/Arguments.java in the fromBundle method. Adding some logs, it looks like in the case of GMail, the intent in including a value that is of Uri type (these are the key and value values from fromBundle):

` System.out              com.sippd.dev                        I  key: org.chromium.chrome.browser.eenp value type: class java.util.ArrayList val: []
System.out              com.sippd.dev                  I  key: android.intent.extra.REFERRER value type: class android.net.Uri$StringUri val: android-app://com.google.android.gm/`

Because this intent value is not a String or Boolean or Array/List, it is throwing
java.lang.IllegalArgumentException: Could not convert class android.net.Uri$StringUri : android-app://com.google.android.gm/

### React Native Version

0.71.6

### Output of `npx react-native info`

System:
    OS: macOS 13.3.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 3.03 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v14.21.3/bin/yarn
    npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
    Watchman: 2023.04.10.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/adammarr/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

I'm not fully sure on the technical aspects of branch and what might be different from branch vs another type of app link from GMail, but in this case it happens simply by opening the link in GMail that then turns into the app link Intent that causes RN to crash.

### Snack, code example, screenshot, or link to a repository

Happens prior to any application code running.

**Comment by Pranav-yadav** [comment]
@adammarr sure. Someone will take a look into it :)
Cc: @cortinico

**Comment by cortinico** [comment]
> System.out com.sippd.dev I key: org.chromium.chrome.browser.eenp value type: class java.util.ArrayList val: [] System.out com.sippd.dev I key: android.intent.extra.REFERRER value type: class android.net.Uri$StringUri val: android-app://com.google.android.gm/

Could you share the full stacktrace @adammarr ?

**Comment by adammarr** [comment]
Not trying to be a pain (honestly), but is that necessary? The failure is 
`java.lang.IllegalArgumentException: Could not convert class android.net.Uri$StringUri`
and from what I can tell, any Intent calls run through that fromBundle method in Arguments.java, at least any of our Intents. My guess is there are not a lot of ways to get to that fromBundle method, and its probably a pretty standard/linear path from Messaging. If you really do need it, let me know and I'll remove the patch, rebuild and retest, but that takes time and I don't really see the benefit in this case, though maybe I'm missing something, I'm certain not familiar with the RN sdk code.

**Comment by adammarr** [comment]
Found somewhere I had copied the log text from by previous debug sess:

`2023-06-22 09:40:13.352  6821-7055  unknown:ReactNative     com.sippd.dev                        E  ReactInstanceManager caught exception in setupReactContext
                                                                                                    java.lang.IllegalArgumentException: Could not convert class android.net.Uri$StringUri : android-app://com.google.android.gm/
                                                                                                    	at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:317)
                                                                                                    	at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1271)
                                                                                                    	at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1183)
                                                                                                    	at com.facebook.react.ReactInstanceManager.access$1600(ReactInstanceManager.java:135)
                                                                                                    	at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:1137)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2023-06-22 09:40:13.352  6821-7055  unknown:ReactNative     com.sippd.dev                        E  Exception in native call
                                                                                                    java.lang.IllegalArgumentException: Could not convert class android.net.Uri$StringUri : android-app://com.google.android.gm/
                                                                                                    	at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:317)
                                                                                                    	at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1271)
                                                                                                    	at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1183)
                                                                                                    	at com.facebook.react.ReactInstanceManager.access$1600(ReactInstanceManager.java:135)
                                                                                                    	at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:1137)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)`

**Comment by cortinico** [comment]
> Found somewhere I had copied the log text from by previous debug sess:

Thanks for the stacktrace.
You should be able to update the `Bundle` in your MainActivity like this:

```java
public class MainActivity extends ReactActivity {
  public static class MainActivityDelegate extends DefaultReactActivityDelegate {
    private Bundle updatedBundle = null;
    private final @Nullable ReactActivity mActivity;

    public MainActivityDelegate(ReactActivity activity, String mainComponentName) {
      super(activity, mainComponentName, DefaultNewArchitectureEntryPoint.getFabricEnabled());
      this.mActivity = activity;
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
      Bundle bundle = mActivity.getIntent().getExtras();
      if (bundle != null && bundle.containsKey("...")) {
        Bundle updatedBundle = new Bundle();
        updatedBundle.putString("key", "value");
      }
      super.onCreate(savedInstanceState);
    }

    @Nullable
    @Override
    protected Bundle getLaunchOptions() {
      return updatedBundle;
    }
  }

  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new MainActivityDelegate(this, getMainComponentName());
  }

  @Override
  protected String getMainComponentName() {
    return "MainApp";
  }
}
```

**Comment by adammarr** [comment]
@cortinico  Ahh, OK, thats better than me patching RN and having to build it with every build (which is honestly causing headaches). Thanks, much appreciated.  That said, bundle.get returns an Object, so throwing an exception and crashing the app instead of logging a warning seems overly harsh in this scenario, especially when the cause is somewhat esoteric for those of us who aren't as fluent on the native side of mobile dev, not to mention somewhat harmless probably if the bundle contains an object the Arguments.java code hasn't accounted for. Also, bundle.get() is apparently deprecated anyway [https://developer.android.com/reference/android/os/BaseBundle#get(java.lang.String)] though I'm not sure how you would get around it given the way the fromBundle method works.

**Comment by cortinico** [comment]
> Ahh, OK, thats better than me patching RN and having to build it with every build (which is honestly causing headaches). Thanks, much appreciated

Closing then 👍

**Comment by adammarr** [comment]
Kinda forgot the last part of the message... you guys are crashing people's applications when they aren't passing specific types to an untyped Object in Bundle. This should be a warning, not something that crashes people's application, its been quite a headache the last month to figure this error out.

**Comment by cortinico** [comment]
> you guys are crashing people's applications when they aren't passing specific types to an untyped Object in Bundle.

Yup this change is totally doable, are you up for sendign a PR to add a fallback for non supported types?

**Comment by Pranav-yadav** [comment]
>you guys are crashing people's applications when they aren't passing specific types to an untyped Object in Bundle. This should be a warning, not something that crashes people's application, its been quite a headache the last month to figure this error out.

Definitely, this is _not_ a good DX. And, it needs to be fixed at some point in time.
<details><summary>Sidenote/Tip:</summary>

I always follow 2hr rule while debugging, If I can't figure it out on my own I just ask for help without wasting much time :)

</details> 

>Yup this change is totally doable, are you up for sendign a PR to add a fallback for non supported types?

How about we open a new issue (or convert this) to fix this w/ "Help Wanted" label so "anyone" interested can send a PR for the same? WDYT Nicola?

**Comment by cortinico** [comment]
> How about we open a new issue (or convert this) to fix this w/ "Help Wanted" label so "anyone" interested can send a PR for the same? WDYT Nicola?

Yup we can open a follow-up here
