### ISSUE TITLE
Podfile: undefined local variable or method `config' 

### ISSUE THREAD

**Issue by tapz** [facebook/react-native#38087]
### Description

```
Generating Pods project
[!] An error occurred while processing the post-install hook of the Podfile.

undefined local variable or method `config' for #<Pod::Podfile:0x000000010623b688 @defined_in_file=#<Pathname:/Users/me/projects/MyApp/ios/Podfile>, @internal_hash={"installation_method"=>{"name"=>"cocoapods", "options"=>{:deterministic_uuids=>false}}}, @root_target_definitions=[#<Pod::Podfile::TargetDefinition label=Pods>], @current_target_definition=#<Pod::Podfile::TargetDefinition label=Pods>, @post_install_callback=#<Proc:0x0000000106194b30 /Users/me/projects/MyApp/ios/Podfile:92>, @installation_options=#<Pod::Installer::InstallationOptions:0x00000001062f6280 @clean=true, @deduplicate_targets=true, @deterministic_uuids=false, @integrate_targets=true, @lock_pod_sources=true, @warn_for_multiple_pod_sources=true, @warn_for_unused_master_specs_repo=true, @share_schemes_for_development_pods=false, @disable_input_output_paths=false, @preserve_pod_file_structure=false, @generate_multiple_pod_projects=false, @incremental_installation=false, @skip_pods_project_generation=false, @parallel_pod_downloads=false, @parallel_pod_download_thread_pool_size=40>>

/Users/me/projects/MyApp/ios/Podfile:98:in `block (2 levels) in from_ruby'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-core-1.12.1/lib/cocoapods-core/podfile.rb:196:in `post_install!'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:1013:in `run_podfile_post_install_hook'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:1001:in `block in run_podfile_post_install_hooks'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:149:in `message'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:1000:in `run_podfile_post_install_hooks'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:337:in `block (2 levels) in create_and_save_projects'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:336:in `block in create_and_save_projects'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:315:in `create_and_save_projects'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:307:in `generate_pods_project'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:183:in `integrate'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:170:in `install!'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/command/update.rb:63:in `run'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/bin/pod:25:in `<main>'
2023-06-27 09:13:05.814 xcodebuild[28980:5823219] DVTCoreDeviceEnabledState:
```

### React Native Version

0.72.0

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 13.4.1
  CPU: (12) arm64 Apple M2 Max
  Memory: 4.21 GB / 96.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.15.0
    path: ~/.nvm/versions/node/v18.15.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.5.0
    path: ~/.nvm/versions/node/v18.15.0/bin/npm
  Watchman:
    version: 2023.05.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "33"
    Build Tools:
      - 33.0.0
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 19.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 11.3.3
    wanted: ^11.3.3
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.0
    wanted: 0.72.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

pod update

### Snack, code example, screenshot, or link to a repository

Updated to RN 0.72.0 and changed these lines in the podfile:

```
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
```

```
  # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false
  )
```

**Comment by tapz** [comment]
The problem seems to be that the `config` variable is local inside the target, but `post_install` cannot be inside a target when there are multiple targets (causes "Specifying multiple `post_install` hooks is unsupported."). I tried to create a global config variable, but that did not work. My ruby skills are basically non-existing, so some help would be appreciated.

**Comment by BrianCodeItUp** [comment]
I encounter the same issue when having multiple target. I comment that  `config` line out. The build was succeed. I think this  is the temp solution for now.

**Comment by BrianCodeItUp** [comment]
@tapz I store the config as global variable. And it worked.
```ruby
def share_pods (target_name)
  # If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
  # because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
  #
  # To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
  # ```js
  # module.exports = {
  #   dependencies: {
  #     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
  # ```
  flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

  linkage = ENV['USE_FRAMEWORKS']
  if linkage != nil
    Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
    use_frameworks! :linkage => linkage.to_sym
  end

  target target_name do
    $config = use_native_modules!
  
    # Flags change depending on the env values.
    flags = get_default_flags()
  
    use_react_native!(
      :path => $config[:reactNativePath],
      # Hermes is now enabled by default. Disable by setting this flag to false.
      # Upcoming versions of React Native may rely on get_default_flags(), but
      # we make it explicit here to aid in the React Native upgrade process.
      :hermes_enabled => ENV['ENABLE_HERMES'],
      :fabric_enabled => flags[:fabric_enabled],
      # Enables Flipper.
      #
      # Note that if you have use_frameworks! enabled, Flipper will not work and
      # you should disable the next line.
      :flipper_configuration => flipper_config,
      # An absolute path to your application root.
      :app_path => "#{Pod::Config.instance.installation_root}/.."
    )
  end
end

share_pods('target1')
share_pods('target2') 
share_pods('target3')

post_install do |installer|
  # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  react_native_post_install(
    installer,
      $config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end
```

**Comment by tnguyen42** [comment]
@BrianCodeItUp After applying your fix, I don't have the original error anymore, but now I have:
```
wrong number of arguments (given 3, expected 1)

path/node_modules/react-native/scripts/react_native_pods.rb:244:in `react_native_post_install'
path/ios/Podfile:140:in `block (2 levels) in from_ruby
```

And the rest of the error log seems similar. Is there something I'm missing?

**Comment by tnguyen42** [comment]
@BrianCodeItUp Applying your fix fixes the first error, but then I am getting the following error:

```
wrong number of arguments (given 3, expected 1)

path/node_modules/react-native/scripts/react_native_pods.rb:244:in `react_native_post_install'
path/ios/Podfile:140:in `block (2 levels) in from_ruby'
```

The rest of the errors is similar. Am I missing something?

**Comment by tnguyen42** [comment]
My bad, I just didn't updated react-native as I should have!

**Comment by PriyanshuPandey-github** [comment]
i upgraded my react-native project from 0.68.5 to 0.74.0 
the ios config comes null
 `"healthChecks": [],
  "platforms": {
    "ios": {},
    "android": {}
  },
  "project": {
    "ios": null,
    "android": {
      "sourceDir": "/Users/priyanshu/hps/mobileapp_ios_pre/android",
      "appName": "app",
      "packageName": "com.ajjas",
      "applicationId": "com.ajjas",
      "mainActivity": ".MainActivity"
    }
  }
}`

**Comment by WangLongONE** [comment]
> flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

How to use the react-native.config.js file? Where should I create it? How should I write its content? And how to make it take effect when starting the project?
