### ISSUE TITLE
[0.72] yarn start : node:internal/fs/watchers:255     throw error;

### ISSUE THREAD

**Issue by Productivix** [facebook/react-native#38134]
### Description

in a console , I start as usual a "yarn start" ,  a physical Android being well connected.
On another console / terminal , I type a yarn run android.
Sometime in the  config phase , the yarn start terminal displays : 
"node:internal/fs/watchers:255
    throw error;
    ^

Error: ENOENT: no such file or directory, watch '/home/william/logiciels/logiciels-windows/dev_RN-Node-GIT/prodRnScCsv/node_modules/react-native-safe-area-context/android/build/kotlin/compileDebugKotlin/cacheable/caches-jvm'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2315:34)
    at NodeWatcher._watchdir (/home/william/logiciels/logiciels-windows/dev_RN-Node-GIT/prodRnScCsv/node_modules/metro-file-map/src/watchers/NodeWatcher.js:145:24)
    at /home/william/logiciels/logiciels-windows/dev_RN-Node-GIT/prodRnScCsv/node_modules/metro-file-map/src/watchers/NodeWatcher.js:264:22
    at Walker.<anonymous> (/home/william/logiciels/logiciels-windows/dev_RN-Node-GIT/prodRnScCsv/node_modules/metro-file-map/src/watchers/common.js:127:31)
    at Walker.emit (node:events:513:28)
    at /home/william/logiciels/logiciels-windows/dev_RN-Node-GIT/prodRnScCsv/node_modules/walker/lib/walker.js:69:16
    at FSReqCallback.oncomplete (node:fs:197:23) {
  errno: -2,
  syscall: 'watch',
  code: 'ENOENT',
  path: '/home/william/logiciels/logiciels-windows/dev_RN-Node-GIT/prodRnScCsv/node_modules/react-native-safe-area-context/android/build/kotlin/compileDebugKotlin/cacheable/caches-jvm',
  filename: '/home/william/logiciels/logiciels-windows/dev_RN-Node-GIT/prodRnScCsv/node_modules/react-native-safe-area-context/android/build/kotlin/compileDebugKotlin/cacheable/caches-jvm'
}

Node.js v18.14.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
"
Then I type again "yarn start" and I get a "BUILD SUCCESSFUL" in the other terminal , and all is correct.

This same project was running well in every version from RN V0.68.2 to 0.71.11

### React Native Version

0.72.0

### Output of `npx react-native info`

Fetching system and libraries information...
System:
  OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Memory: 4.64 GB / 7.65 GB
  Shell:
    version: 5.1.4
    path: /bin/bash
Binaries:
  Node:
    version: 18.14.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.6.0
    path: /usr/local/bin/npm
  Watchman:
    version: 4.9.0
    path: /usr/bin/watchman
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 11.0.18
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.0
    wanted: 0.72.0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

in a console , I start as usual a "yarn start" ,  a physical Android being well connected.
On another console / terminal , I type a yarn run android.

### Snack, code example, screenshot, or link to a repository

the project is too big for that , and again  :
This same project was running well in every version from RN V0.68.2 to 0.71.11

**Comment by Productivix** [comment]
retested in Rn 0.72.1 : no more problems ! good

**Comment by Productivix** [comment]
think about completing the tool https://react-native-community.github.io/upgrade-helper/ for RN 0.72.1 please - very useful

**Comment by Productivix** [comment]
bug comes back with  "@react-native/metro-config": "^0.72.7", in RN 0.72.1 !
