### ISSUE TITLE
Can't build app on Android Simulator - Mac OS

### ISSUE THREAD

**Issue by AlbanW** [facebook/react-native#38603]
### Description

When i try to build app on Android Simulator using metro i got this error:

    at module.exports (/Users/albanweill/Documents/Supporters/AppFront/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:205:26)
    at runOnAllDevices (/Users/albanweill/Documents/Supporters/AppFront/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:82:34)
    at buildAndRun (/Users/albanweill/Documents/Supporters/AppFront/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:122:41)
    at Object.runAndroid [as func] (/Users/albanweill/Documents/Supporters/AppFront/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:69:10)
    
<img width="1350" alt="Capture d’écran 2023-07-25 à 01 16 58" src="https://github.com/facebook/react-native/assets/69081308/113740d1-1c2e-4e91-b378-59a82be4adac">

    
    
    

### React Native Version

10.2.2

### Output of `npx react-native info`

System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.04 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.5.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 9.8.0 - /opt/homebrew/bin/npm
    Watchman: 2023.07.24.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 19.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.8 => 0.71.8
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

just run npx react-native start

### Snack, screenshot, or link to a repository

<img width="1350" alt="Capture d’écran 2023-07-25 à 01 16 58" src="https://github.com/facebook/react-native/assets/69081308/113740d1-1c2e-4e91-b378-59a82be4adac">

**Comment by pnthach95** [comment]
Try downgrading nodejs to version 16 or 18
