### ISSUE TITLE
Unable to build iOS and Android apps since RN0.72 (AppCenter & Monorepo)

### ISSUE THREAD

**Issue by TomCorvus** [facebook/react-native#38620]
### Description

Before contacting AppCenter for this.

Since RN 0.72, can't build iOS app on AppCenter.
This error appears:
iOS :
```
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /Users/runner/work/_temp/ae1183b6-2a5e-47f4-95d8-f5efb12ffd28.sh
Found index.js for ReactNative index.
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '/Users/runner/work/1/s/packages/project1/node_modules/react-native/local-cli/cli.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.17.0
##[error]Bash exited with code '1'.
```

Android:
```
> Task :app:createBundleReleaseJsAndAssets
warning: the transform cache was reset.
                Welcome to Metro v0.76.7
              Fast - Scalable - Integrated


Error: Unable to resolve module react-native from /Users/runner/work/1/s/packages/project1/index.js: react-native could not be found within the project or in these directories:
  node_modules
  ../../node_modules
  ../../../../node_modules
[0m[31m[1m>[22m[39m[90m 1 |[39m [36mimport[39m { [33mAppRegistry[39m } [36mfrom[39m [32m'react-native'[39m[33m;[39m[0m
[0m [90m   |[39m                              [31m[1m^[22m[39m[0m
[0m [90m 2 |[39m[0m
[0m [90m 3 |[39m [36mimport[39m [33mApp[39m [36mfrom[39m [32m'@mobile/core'[39m[33m;[39m[0m
[0m [90m 4 |[39m[0m
Error: Unable to resolve module react-native from /Users/runner/work/1/s/packages/project1/index.js: react-native could not be found within the project or in these directories:
  node_modules
  ../../node_modules
  ../../../../node_modules
[0m[31m[1m>[22m[39m[90m 1 |[39m [36mimport[39m { [33mAppRegistry[39m } [36mfrom[39m [32m'react-native'[39m[33m;[39m[0m
[0m [90m   |[39m                              [31m[1m^[22m[39m[0m
[0m [90m 2 |[39m[0m
[0m [90m 3 |[39m [36mimport[39m [33mApp[39m [36mfrom[39m [32m'@mobile/core'[39m[33m;[39m[0m
[0m [90m 4 |[39m[0m
    at ModuleResolver.resolveDependency (/Users/runner/work/1/s/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:139:15)
    at DependencyGraph.resolveDependency (/Users/runner/work/1/s/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
    at Object.resolve (/Users/runner/work/1/s/node_modules/metro/src/lib/transformHelpers.js:169:21)
    at Graph._resolveDependencies (/Users/runner/work/1/s/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
    at Graph._processModule (/Users/runner/work/1/s/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Graph._traverseDependenciesForSingleFile (/Users/runner/work/1/s/node_modules/metro/src/DeltaBundler/Graph.js:249:5)
    at async Promise.all (index 0)
    at async Graph.initialTraverseDependencies (/Users/runner/work/1/s/node_modules/metro/src/DeltaBundler/Graph.js:233:5)
    at async DeltaCalculator._getChangedDependencies (/Users/runner/work/1/s/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:229:25)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:createBundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1
```

### React Native Version

0.72.3

### Output of `npx react-native info`

From AppCenter

```
System:
  OS: macOS 13.4
  CPU: (4) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
  Memory: 7.77 GB / 14.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 18.17.0
    path: ~/.nvm/versions/node/v18.17.0/bin/node
  Yarn:
    version: 3.6.1
    path: ~/.yarn/bin/yarn
  npm:
    version: 9.2.0
    path: ~/.nvm/versions/node/v18.17.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/lib/ruby/gems/3.0.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK:
    API Levels:
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "33"
      - "33"
      - "34"
    Build Tools:
      - 27.0.0
      - 27.0.1
      - 27.0.2
      - 27.0.3
      - 28.0.0
      - 28.0.1
      - 28.0.2
      - 28.0.3
      - 29.0.0
      - 29.0.1
      - 29.0.2
      - 29.0.3
      - 30.0.0
      - 30.0.1
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 34.0.0
    Android NDK: 25.2.9519653
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.7
    path: /usr/bin/javac
  Ruby:
    version: 3.0.6
    path: /usr/local/opt/ruby@3.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
 ```

### Steps to reproduce

- Init a monorepo
- Init a project1 inside packages folder
- Try to build iOS or Android app on AppCenter

### Snack, screenshot, or link to a repository

https://github.com/TomCorvus/RNMonorepo

**Comment by cortinico** [comment]
> * Try to build iOS or Android app on AppCenter

Have you reported this to AppCenter?

**Comment by TomCorvus** [comment]
Hi @cortinico, thanks for your reply.

Yes, I discuss with AppCenter support since 2 weeks but for now, they don't find the problem.
There are quite a few changes with RN0.72 including the need to use NodeJS 18.
Their backend team takes over.

It was mainly to know if anyone had an idea about this problem. It seems there were similar issues in the past.

**Comment by cortinico** [comment]
Great thanks for the context

> It was mainly to know if anyone had an idea about this problem. It seems there were similar issues in the past.

I'll close this for now as this seems specific to AppCenter.
If someone has similar issue can comment over here.

Also I would suggest you to open a question on StackOverflow

**Comment by fxamauri** [comment]
@TomCorvus any update on this issue?

I am facing the same problem.

**Comment by TomCorvus** [comment]
@fxamauri No, not now, I'm still in contact with AppCenter team to fix the problem. I'll tell you if I have news.
