### ISSUE TITLE
[Android] Open React native's Android folder in Android studio showing build failed error.

### ISSUE THREAD

**Issue by kuldeep-IT** [facebook/react-native#39083]
### Description

I've created new react native project on latest version. And opened its android folder in Android studio. I got this error as mentioned.

Error:
FAILURE: Build failed with an exception.

* Where:
Script '/home/x/x/MovieApp2Codex/MovieApp2/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 389

* What went wrong:
A problem occurred evaluating script.
> /home/x/x/MovieApp2Codex/MovieApp2/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:124    cmd.option(opt.name, opt.description ?? '', opt.parse || (val => val), typeof opt.default === 'function' ? opt.default(config) : opt.default);                                          ^SyntaxError: Unexpected token '?'    at wrapSafe (internal/modules/cjs/loader.js:915:16)    at Module._compile (internal/modules/cjs/loader.js:963:27)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)    at Module.load (internal/modules/cjs/loader.js:863:32)    at Function.Module._load (internal/modules/cjs/loader.js:708:14)    at Module.require (internal/modules/cjs/loader.js:887:19)    at require (internal/modules/cjs/helpers.js:74:18)    at Object.<anonymous> (/home/x/x/MovieApp2Codex/MovieApp2/node_modules/react-native/cli.js:13:11)    at Module._compile (internal/modules/cjs/loader.js:999:30)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

### React Native Version

 0.72.3

### Output of `npx react-native info`

npx react-native info
info Fetching system and libraries information...
System:
  OS: Linux 6.2 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Memory: 6.20 GB / 15.30 GB
  Shell:
    version: 5.1.16
    path: /bin/bash
Binaries:
  Node:
    version: 18.17.1
    path: ~/.nvm/versions/node/v18.17.1/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/bin/yarn
  npm:
    version: 9.6.7
    path: ~/.nvm/versions/node/v18.17.1/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

- Create new react native project using latest version.
- open its android folder in Android studio.
- You may find that Build failed with an exception.
- I'm using JDK 17.
- Gradle version 8.3

### Snack, screenshot, or link to a repository

![image](https://github.com/facebook/react-native/assets/60247603/2821b279-ee3d-4db9-9da7-f6b2d385fb26)

Github repo link: https://github.com/kuldeep-IT/MovieAppRN.git

**Comment by kuldeep-tatvic** [comment]
> ⚠️	Newer Version of React Native is Available!
> ℹ️	You are on a supported minor version, but it looks like there's a newer patch available - 0.72.4. Please [upgrade](https://reactnative.dev/docs/upgrading) to the highest patch for your minor or latest and verify if the issue persists (alternatively, create a new project and repro the issue in it). If it does not repro, please let us know so we can close out this issue. This helps us ensure we are looking at issues that still exist in the most recent releases.

Also facing the same issues in latest version.

**Comment by cortinico** [comment]
I'm not able to reproduce.

@kuldeep-tatvic are you able to build locally?
Also which version of Android Studio are you using?

**Comment by kuldeep-tatvic** [comment]
> I'm not able to reproduce.
> 
> @kuldeep-tatvic are you able to build locally? Also which version of Android Studio are you using?

Currently, I'm using latest version of android studio 2022.3.1 
and I'm not able to build locally

**Comment by kuldeep-tatvic** [comment]
Solved by

1. manually removing an old version of node (in /usr/local/bin/) that was apparently used by the sh shell (default shell used by xcode)
2. linking the nvm node installation by running ln -s $(which node) /usr/local/bin/node in a sh shell
