### ISSUE TITLE
Fatal Exception: com.facebook.react.bridge.NoSuchKeyException: longitude

### ISSUE THREAD

**Issue by Youssef-Durgham** [facebook/react-native#39168]
### Description

the error for crash report from firebase is
Fatal Exception: com.facebook.react.bridge.NoSuchKeyException: longitude
at com.facebook.react.bridge.ReadableNativeMap.getValue(:27)
at com.facebook.react.bridge.ReadableNativeMap.getValue()
at com.facebook.react.bridge.ReadableNativeMap.getDouble(:2)
at com.rnmaps.maps.MapView.moveToRegion(MapView.java:5)
at com.rnmaps.maps.MapView.applyBridgedProps(MapView.java:5)
at com.rnmaps.maps.MapView.onMapReady(MapView.java:90)
at com.google.android.gms.maps.zzaf.zzb(zzaf.java:7)
at com.google.android.gms.maps.internal.zzaq.zza(zzaq.java:31)
at com.google.android.gms.internal.maps.zzb.onTransact(zzb.java:20)
at android.os.Binder.transact(Binder.java:921)
at m.fn.c(:com.google.android.gms.dynamite_mapsdynamite@233116028@23.31.16 (100400-0):8)
at com.google.maps.api.android.lib6.impl.bg.run(:com.google.android.gms.dynamite_mapsdynamite@233116028@23.31.16 (100400-0):19)
at android.os.Handler.handleCallback(Handler.java:900)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:219)
at android.app.ActivityThread.main(ActivityThread.java:8676)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

### React Native Version

0.71.6

### Output of `npx react-native info`

it works fine in developer mode the error happen I production

### Steps to reproduce

some of users device faced this issues and som not

### Snack, screenshot, or link to a repository

no link or photo because the app crash direct when this happen so this is the log of error that I got it from crash report from firebase 
Fatal Exception: com.facebook.react.bridge.NoSuchKeyException: longitude
       at com.facebook.react.bridge.ReadableNativeMap.getValue(:27)
       at com.facebook.react.bridge.ReadableNativeMap.getValue()
       at com.facebook.react.bridge.ReadableNativeMap.getDouble(:2)
       at com.rnmaps.maps.MapView.moveToRegion(MapView.java:5)
       at com.rnmaps.maps.MapView.applyBridgedProps(MapView.java:5)
       at com.rnmaps.maps.MapView.onMapReady(MapView.java:90)
       at com.google.android.gms.maps.zzaf.zzb(zzaf.java:7)
       at com.google.android.gms.maps.internal.zzaq.zza(zzaq.java:31)
       at com.google.android.gms.internal.maps.zzb.onTransact(zzb.java:20)
       at android.os.Binder.transact(Binder.java:1072)
       at m.fh.c(:com.google.android.gms.dynamite_mapsdynamite@233116044@23.31.16 (190400-0):8)
       at com.google.maps.api.android.lib6.impl.bg.run(:com.google.android.gms.dynamite_mapsdynamite@233116044@23.31.16 (190400-0):19)
       at android.os.Handler.handleCallback(Handler.java:978)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loopOnce(Looper.java:238)
       at android.os.Looper.loop(Looper.java:357)
       at android.app.ActivityThread.main(ActivityThread.java:8089)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

**Comment by cortinico** [comment]
Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core. Please open this issue against this other repository:

https://github.com/react-native-maps/react-native-maps/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.

**Comment by Hatsuya1993** [comment]
ERROR  Your app just crashed. See the error below.
com.facebook.react.bridge.NoSuchKeyException: longitude

I got the same issue too. I simply waited  for the variable that sets longitude to be available before rendering the page. Something like this 

if (location === nul) {
return (
<View>
<Text>Loading</Text>
</View>
)

return (
<View>
Add your main code here
</View>
)
