### ISSUE TITLE
Calling Appearance.setColorScheme crashes on ROG Phone 3

### ISSUE THREAD

**Issue by rrebase** [facebook/react-native#39530]
### Description

There's a device specific crash when calling `setColorScheme`. Seen only on "Asus ROG Phone 3" according to crash reports.

### React Native Version

0.72.1

### Output of `npx react-native info`

_Not relevant_

### Steps to reproduce

```tsx
import { Appearance } from 'react-native';

useEffect(() => {
  Appearance.setColorScheme('light');
}, []);
```

### Snack, screenshot, or link to a repository

Crash stracktrace:

```
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8480)
        at android.view.ViewRootImpl.recomputeViewAttributes(ViewRootImpl.java:4344)
        at android.view.View.setSystemUiVisibility(View.java:25676)
        at com.android.internal.policy.DecorView.setSystemUiVisibility(DecorView.java:2783)
        at com.android.internal.policy.DecorView.setOverrideSystemUiVisibility(DecorView.java:2788)
        at com.android.internal.policy.PhoneWindow.dispatchNavigationColor(PhoneWindow.java:4002)
        at com.android.internal.policy.DecorView.updateColorViewInt(DecorView.java:1454)
        at com.android.internal.policy.DecorView.updateColorViews(DecorView.java:1170)
        at com.android.internal.policy.PhoneWindow.updateNavigationColor(PhoneWindow.java:4030)
        at com.android.internal.policy.PhoneWindow.onConfigurationChanged(PhoneWindow.java:758)
        at android.app.Activity.onConfigurationChanged(Activity.java:2871)
        at androidx.activity.ComponentActivity.onConfigurationChanged(ComponentActivity.java:865)
        at androidx.fragment.app.FragmentActivity.onConfigurationChanged(FragmentActivity.java:262)
        at androidx.appcompat.app.AppCompatActivity.onConfigurationChanged(AppCompatActivity.java:229)
        at com.facebook.react.ReactActivity.onConfigurationChanged(ReactActivity.java:127)
        at com.example.MainActivity.onConfigurationChanged(MainActivity.java:112)
        at androidx.appcompat.app.AppCompatDelegateImpl.updateActivityConfiguration(AppCompatDelegateImpl.java:2925)
        at androidx.appcompat.app.AppCompatDelegateImpl.updateResourcesConfiguration(AppCompatDelegateImpl.java:2914)
        at androidx.appcompat.app.AppCompatDelegateImpl.updateAppConfiguration(AppCompatDelegateImpl.java:2843)
        at androidx.appcompat.app.AppCompatDelegateImpl.applyApplicationSpecificConfig(AppCompatDelegateImpl.java:2561)
        at androidx.appcompat.app.AppCompatDelegateImpl.applyApplicationSpecificConfig(AppCompatDelegateImpl.java:2522)
        at androidx.appcompat.app.AppCompatDelegateImpl.applyDayNight(AppCompatDelegateImpl.java:2501)
        at androidx.appcompat.app.AppCompatDelegate.applyDayNightToActiveDelegates(AppCompatDelegate.java:1053)
        at androidx.appcompat.app.AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.java:654)
        at com.facebook.react.modules.appearance.AppearanceModule.setColorScheme(AppearanceModule.java:74)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.jni.NativeRunnable.run(NativeRunnable.java:-2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:239)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by cortinico** [comment]
> Seen only on "Asus ROG Phone 3" according to crash reports.

Are you able to reproduce on emulator or other devices?

**Comment by rrebase** [comment]
> Are you able to reproduce on emulator or other devices?

Unfortunately haven't been able to reproduce it on emulator or any other device so far.

**Comment by cortinico** [comment]
Closing as we can't provide further support here sadly

**Comment by dubiao** [comment]
Dont anyone facing this problem? I am using 0.75.4 and The app crash when calling Appearance.setColorScheme on Android. ( iOS version works fine )
