### ISSUE TITLE
Crash on 0.72.4, Android, UnsatisfiedLinkError

### ISSUE THREAD

**Issue by TheRogue76** [facebook/react-native#39579]
### Description

Similar to https://github.com/wordpress-mobile/WordPress-Android/issues/18540 and https://github.com/facebook/react-native/issues/35895, the app sometimes crashes on devices, with the following error:
```
UnsatisfiedLinkError java.lang.Runtime in loadLibrary0
dlopen failed: library "libhermes.so" not found
```
I have validated that none of our dependencies are trying to call react.gradle in their gradle files (no `apply from: "../../node_modules/react-native/react.gradle"` in any of them) and they are up to date.

We previously had a script at the bottom of the gradle file:
```
packagingOptions {
        pickFirst "lib/armeabi-v7a/libc++_shared.so"
        pickFirst "lib/arm64-v8a/libc++_shared.so"
        pickFirst "lib/x86/libc++_shared.so"
        pickFirst "lib/x86_64/libc++_shared.so"
    }
```
But from what i read from the template, this is no longer required. Please let me know if there is anything else i can provide.

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: macOS 13.5.2
  CPU: (10) arm64 Apple M1 Max
  Memory: 437.86 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.14.0
    path: ~/.nvm/versions/node/v16.14.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/Desktop/rnapp/node_modules/.bin/yarn
  npm:
    version: 8.3.1
    path: ~/.nvm/versions/node/v16.14.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/Parsa/.rvm/gems/ruby-2.7.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "26"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 32.1.0
      - 33.0.0
    System Images:
      - android-33 | Google APIs ARM 64 v8a
      - android-33 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.7
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/Parsa/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

1. ./gradlew clean
2. ./gradlew  bundleProdRelease
3. Release
4. Crashes on certain devices

### Snack, screenshot, or link to a repository

<img width="1661" alt="Screenshot 2023-09-21 at 13 23 32" src="https://github.com/facebook/react-native/assets/40071952/3398e855-7421-4d1e-978e-3cfcd080aa23">

**Comment by cortinico** [comment]
> But from what i read from the template, this is no longer required. Please let me know if there is anything else i can provide.

Please provide a reproducer as suggested by the bot just above

**Comment by TheRogue76** [comment]
Unfortunately, i can not. This is not happening on all devices in a reproducible manner, just a very small segment, and i have no way of reproducing what is happening there, i just have the sentry logs.

**Comment by cortinico** [comment]
> Unfortunately, i can not. This is not happening on all devices in a reproducible manner, just a very small segment, and i have no way of reproducing what is happening there, i just have the sentry logs.

Then we can't help further here sadly.
Closing as this is inactionable for us. I suggest you ask this on StackOverflow and try to seek for help there

**Comment by pavangoyal42** [comment]
@TheRogue76 we are also facing same crash. with crashlytics we don't get the information about apk/aab is sideloaded or not. from the screenshot you shared isSideLoaded is true. can you please check if this happening for all the crash logs ?

**Comment by TheRogue76** [comment]
I'll throw in what we found about this. It was Sentry, specifically Sentry Native's native bits causing a cascading failure, that ended up with the original error. Google had released a new update to Google play services back then, and the problem wasn't RN. https://github.com/getsentry/sentry-java/issues/2955. My recommendation? Check what native low-level dependencies you might have (dependencies that might have C/C++ code) and see if it was any of them.

**Comment by SukumarRN7** [comment]
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.cars24.uaeusedcars-1/base.apk"],nativeLibraryDirectories=[/data/app/com.cars24.uaeusedcars-1/lib/arm, /system/lib, /vendor/lib]]] couldn't find "libhermes.so"


**Raw Text LOG!!**


java.lang.Runtime.loadLibrary0 (Runtime.java:984)
java.lang.System.loadLibrary (System.java:1530)
com.facebook.soloader.nativeloader.SystemDelegate.loadLibrary (SystemDelegate.java:1)
com.facebook.soloader.nativeloader.NativeLoader.loadLibrary (NativeLoader.java:52)
com.facebook.soloader.nativeloader.NativeLoader.loadLibrary (NativeLoader.java:2)
com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:11)
com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary (HermesExecutor.java:26)
com.facebook.hermes.reactexecutor.HermesExecutor.<clinit> (HermesExecutor.java:1)
com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary (HermesExecutor.java:24)
com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory (ReactInstanceManagerBuilder.java:379)
com.facebook.react.ReactInstanceManagerBuilder.build (ReactInstanceManagerBuilder.java:329)
com.facebook.react.ReactNativeHost.createReactInstanceManager (ReactNativeHost.java:96)
com.facebook.react.ReactNativeHost.getReactInstanceManager (ReactNativeHost.java:42)
com.cars24.uaeusedcars.MainApplication.onCreate (MainApplication.java:143)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1024)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:5403)
android.app.ActivityThread.-wrap2 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1545)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6119)
java.lang.reflect.Method.invoke (Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:886)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:776)

Image 
<img width="1114" alt="image" src="https://github.com/facebook/react-native/assets/115766773/c8ea8f90-dcca-4226-9462-b4a407d9e25a">

We are currently at RN .  0.72.0

The crash was on a production
Device : Samsung Galaxy S6
App State : Background
OS Version :  7.1.1


Can anyone help over here please ??

**Comment by abdymm** [comment]
we also faced this issue after we upgrade our RN from 0.70 to 0.72.13 , on our Crashlytics its only happened on Pixel devices

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.goshuttle-9Gk3UkIX8wjQxzhOPIzWNg==/base.apk"],nativeLibraryDirectories=[/data/app/com.goshuttle-9Gk3UkIX8wjQxzhOPIzWNg==/lib/arm64, /system/lib64]]] couldn't find "libhermes.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
       at java.lang.System.loadLibrary(System.java:1669)
       at com.facebook.soloader.nativeloader.SystemDelegate.loadLibrary(SystemDelegate.java:24)
       at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:52)
       at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:869)
       at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:26)
       at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
       at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:24)
       at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:379)
       at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:325)
       at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:96)
       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
       at com.goshuttle.MainApplication.onCreate(MainApplication.java:71)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
       at com.elderdrivers.riru.edxp._hooker.yahfa.HandleBindAppHooker.hook(HandleBindAppHooker.java:21)
       at android.app.ActivityThread.access$1100(ActivityThread.java:200)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6718)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

do you guys have any clue on this?

**Comment by cblaze22** [comment]
This basically happens on every upgrade to the version of an app and doesn't appear anymore.  We are on 0.73.6.

```
          Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libhermes.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
       at java.lang.Runtime.loadLibrary0(Runtime.java:998)
       at java.lang.System.loadLibrary(System.java:1656)
       at com.facebook.soloader.nativeloader.SystemDelegate.loadLibrary(SystemDelegate.java:24)
       at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:52)
       at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:869)
       at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:26)
       at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
       at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary()
       at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:391)
       at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:335)
       at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:104)
       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:48)
       at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:292)
       at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:129)
       at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:124)
       at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:47)
       at com.exposure.MainActivity.onCreate(MainActivity.kt:19)
       at android.app.Activity.performCreate(Activity.java:8054)
       at android.app.Activity.performCreate(Activity.java:8034)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
        ```
