### ISSUE TITLE
watchman issue - xcode build fails

### ISSUE THREAD

**Issue by ashee** [facebook/react-native#3973]
Here's my environment - started from scratch.
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F1021

$ nvm list
->       v4.2.2
         v5.0.0
default -> 4.2.2 (-> v4.2.2)
stable -> 4.2.2 (-> v4.2.2)
node -> stable (-> v4.2.2) (default)
iojs -> N/A (default)

$ node -v
v4.2.2

$ npm -v
2.14.7

$ brew info watchman
watchman: stable 4.1.0 (bottled), HEAD
Watch files and take action when they change
https://github.com/facebook/watchman
/usr/local/Cellar/watchman/HEAD (25 files, 368K) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/watchman.rb
==> Dependencies
Build: autoconf ✔, automake ✔
Required: pcre ✔

```

After I create a fresh project
```
$ npm install -g react-native-cli
$ react-native init ss
$ cd ss
$ open ios/ss.xcodeproject
```
xcode fails to build with the following error
```
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/amitava/Projects/react/ss 

[10:18:49 AM] <START> Building Dependency Graph
[10:18:49 AM] <START> Crawling File System
[10:18:49 AM] <START> Loading bundles layout
[10:18:49 AM] <END>   Loading bundles layout (0ms)

React packager ready.

Error building DepdendencyGraph:
 Error: failed to parse query: must use ["allof", expr...]
    at BunserBuf.<anonymous> (/Users/amitava/Projects/react/ss/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:93:23)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/amitava/Projects/react/ss/node_modules/react-native/node_modules/bser/index.js:289:10)
    at /Users/amitava/Projects/react/ss/node_modules/react-native/node_modules/bser/index.js:244:12
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
Process terminated. Press <enter> to close the window

**Comment by christopherdro** [comment]
Seems related to https://github.com/facebook/watchman/issues/118

**Comment by ashee** [comment]
https://github.com/facebook/watchman/issues/118 - not a watchman issue. This seems to be a react-native issue. Any workarounds?

**Comment by christopherdro** [comment]
@ashee Were you able to find a solution?

**Comment by frantic** [comment]
cc @amasad @martinbigio - from discussion on https://github.com/facebook/watchman/issues/118 seems like the packager sends an invalid query to the watchman, could you please check if it's a packager or `sane`'s problem?

**Comment by martinbigio** [comment]
@amasad could you point me to where the query is generated? couldn't find out (checked FileWatcher and fastfs) and I'm not very familiar with this part of the codebase.

**Comment by amasad** [comment]
@martinbigio the query is generated here: https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/crawlers/watchman.js#L40-L44

**Comment by jsierles** [comment]
Closing this out due to inactivity. Feel free to reopen if the issue persists!

**Comment by dojiboy9** [comment]
In case anyone is still seeing this issue. I was getting:

```
Failed to build DependencyGraph: Watchman error: failed to parse query: must use ["allof", expr...]. Make sure watchman
is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.html.
Error: Watchman error: failed to parse query: must use ["allof", expr...]. Make sure watchman is running for this projec
t. See https://facebook.github.io/watchman/docs/troubleshooting.html.
    at c:\Users\dojiboy9\my-app\src\mobile\node_modules\react-native\node_modules\node-haste\lib\crawlers\watchman.js:63:11
    at process._tickCallback (node.js:377:9)
```

In my case it was indeed the invalid query (there is an empty `['anyof']` expression). I added a work-around in this [gist](https://gist.github.com/dojiboy9/1dc95ecddd2d6092d3296dc7eb70a809#file-react-native-node_modules-node-haste-lib-crawlers-watchman-js-L41-L43)

**Comment by braco** [comment]
Just started happening with RN 0.33.0

**Comment by aleclarson** [comment]
For me, I had a package that did `require('retry')` when I had renamed the dependency to `Retry`.
So, while Watchman resolved `watchedRoot` into the correct casing, the `roots` array still contained the invalid, lowercase `retry` path.
This led to `isDescendant(watchedRoot, roots[i])` never passing, resulting in `dirExpr.length === 1` (which is not allowed in Watchman currently).
