### ISSUE TITLE
No Prebuilt ARM64 Binary for Linux

### ISSUE THREAD

**Issue by leymytel** [facebook/react-native#39814]
When running Hermes on an ARM64 architecture (aarch64) Linux system, the process fails with an "Exec format error." This is likely due to the fact that the prebuilt Hermes binary for Linux is designed for x86-64, causing incompatibility issues on ARM64 systems.

This issue initially surfaced while using eas update with the Expo CLI. The error output is as follows:
```
eas update --branch playground --non-interactive --auto
[expo-cli] Starting Metro Bundler
[expo-cli] Android Bundling complete 49086ms
[expo-cli] iOS Bundling complete 49089ms
[expo-cli] iOS Building Hermes bytecode for the bundle
[expo-cli] 
[expo-cli] Error: /home/ubuntu/<APP_NAME>/node_modules/react-native/sdks/hermesc/linux64-bin/hermesc -emit-binary -out /tmp/expo-bundler-631188/index.hbc /tmp/expo-bundler-631188/index.bundle -output-source-map -O exited with non-zero code: 2
[expo-cli] Error: /home/ubuntu/<APP_NAME>/node_modules/react-native/sdks/hermesc/linux64-bin/hermesc -emit-binary -out /tmp/expo-bundler-631188/index.hbc /tmp/expo-bundler-631188/index.bundle -output-source-map -O exited with non-zero code: 2
[expo-cli]     at ChildProcess.completionListener (/home/ubuntu/<APP_NAME>/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
[expo-cli]     at Object.onceWrapper (node:events:628:26)
[expo-cli]     at ChildProcess.emit (node:events:513:28)
[expo-cli]     at maybeClose (node:internal/child_process:1091:16)
[expo-cli]     at Socket.<anonymous> (node:internal/child_process:449:11)
[expo-cli]     at Socket.emit (node:events:513:28)
[expo-cli]     at Pipe.<anonymous> (node:net:313:12)
[expo-cli]     ...
[expo-cli]     at spawnAsync (/home/ubuntu/<APP_NAME>/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
[expo-cli]     at Object.buildHermesBundleAsync (/home/ubuntu/<APP_NAME>/node_modules/@expo/dev-server/build/HermesBundler.js:88:37)
[expo-cli]     at async maybeAddHermesBundleAsync (/home/ubuntu/<APP_NAME>/node_modules/@expo/cli/build/src/export/fork-bundleAsync.js:108:40)
[expo-cli]     at async Object.bundleAsync (/home/ubuntu/<APP_NAME>/node_modules/@expo/cli/build/src/export/fork-bundleAsync.js:121:32)
[expo-cli]     at async Object.createBundlesAsync (/home/ubuntu/<APP_NAME>/node_modules/@expo/cli/build/src/export/createBundles.js:39:21)
[expo-cli]     at async Object.exportAppAsync (/home/ubuntu/<APP_NAME>/node_modules/@expo/cli/build/src/export/exportApp.js:64:21)
[expo-cli]     at async exportAsync (/home/ubuntu/<APP_NAME>/node_modules/@expo/cli/build/src/export/exportAsync.js:45:5)
✖ Export failed
/home/ubuntu/<APP_NAME>/node_modules/expo/bin/cli exited with non-zero code: 1
```

Hermes version:  hermes-2023-08-07-RNv0.72.4-813b2def12bc9df02654b3e3653ae4a68d0572e0
React Native version: 0.72.5
OS version: Ubuntu 22.04.1 LTS
Platform: arm64

The output of `file ./node_modules/react-native/sdks/hermesc/linux64-bin/hermesc` shows that it is an x86-64 binary:

```
ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=d98c8b4fb3a539f24ae3dde4bab6698eb0e339b5, for GNU/Linux 3.2.0, stripped
```

**Comment by cortinico** [comment]
That's expected, as we produce prebuilt binaries for Hermes only for Win, MacOS, and Linux using the CircleCI runners (so that's what decides the final architecture).

I don't believe we have capacity to distribute another prebuilt (also due to sizing constraint that we'll be imposing to everyone as those binaries are shipped inside the NPM package).

The alternative for you @leymytel is to prebuilt hermesc for ARM and use the `hermesCommand` config in Gradle to specify your own binary.

**Comment by leymytel** [comment]
Thank you @tmikov for moving the issue here and @cortinico for your quick reply!
