### ISSUE TITLE
React Native 0.71.4 Release Build Crash FATAL EXCEPTION: create_react_context

### ISSUE THREAD

**Issue by sridharvthink** [facebook/react-native#39831]
### Description

Issue:
We upgraded to react native version 0.71.4 from 0.70.6
All works good in debug mode for android but if we take apk or aab or build varient changed to release mode app got crashed 
Expected Behaviour:
It should work debug and release mode

### React Native Version

0.71.4

### Output of `npx react-native info`

System:
    OS: macOS 13.5.1
    CPU: (8) x64 Apple M2
    Memory: 9.66 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 9.6.7 - /usr/local/bin/npm
    Watchman: 0.0.0 - /opt/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10671973
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: javac 21 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: 9.2.1 => 9.2.1 
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Step 1:
Upgrade the react native version from 0.70.6 to 0.71.4
Step 2:
Change your android build varient to release
Step 3:
It will crash when launching on device 

### Snack, screenshot, or link to a repository

<img width="1029" alt="Screenshot 2023-10-05 at 6 59 05 PM" src="https://github.com/facebook/react-native/assets/15279044/3011e45f-799e-4667-a606-5c87eabdf2ab">

**Comment by cortinico** [comment]
Please provide the crash report with the stacktrace

**Comment by sridharvthink** [comment]
FATAL EXCEPTION: create_react_context

java.lang.RuntimeException: Unable to load script. Make sure you're either running Metro (run 'npx react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.

FATAL EXCEPTION: create_react_context
Process: com.testreleasebuild, PID: 8291
java.lang.RuntimeException: Unable to load script. Make sure you're either running Metro (run 'npx react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.
    at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
    at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:248)
    at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:29)
    at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:277)
    at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1422)
    at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:138)
    at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1111)
    at java.lang.Thread.run(Thread.java:923)

**Comment by sridharvthink** [comment]
> ⚠️	Newer Version of React Native is Available!
> ℹ️	You are on a supported minor version, but it looks like there's a newer patch available - 0.71.13. Please [upgrade](https://reactnative.dev/docs/upgrading) to the highest patch for your minor or latest and verify if the issue persists (alternatively, create a new project and repro the issue in it). If it does not repro, please let us know so we can close out this issue. This helps us ensure we are looking at issues that still exist in the most recent releases.

Still the issue eixst even updated to 0.7.1.13

 pid-26940                            E  FATAL EXCEPTION: create_react_context
                                                                                                    Process: com.ts.ecsite.app.fieldnotesdev, PID: 26940
                                                                                                    java.lang.RuntimeException: Unable to load script. Make sure you're either running Metro (run 'npx react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.
                                                                                                    	at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
                                                                                                    	at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:239)
                                                                                                    	at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:29)
                                                                                                    	at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:268)
                                                                                                    	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1402)
                                                                                                    	at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:135)
                                                                                                    	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1109)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)

**Comment by cortinico** [comment]
Can you share your `android/app/build.gradle` file?

**Comment by mubashiralisiddiqui** [comment]
@cortinico I have upgraded my react native version which is working fine on debug mode but crashes on release mode
here is what logcat says
<img width="1371" alt="image" src="https://github.com/facebook/react-native/assets/16689214/e386467c-61ac-4a00-90ca-c6477c8d5b20">

trying for so many days to resolve this can you or someone please suggest what i need to do
here is my build.gradle file
<img width="561" alt="image" src="https://github.com/facebook/react-native/assets/16689214/e62bdd77-f564-49ad-8986-da74e4a44fb4">

**Comment by LouisJS** [comment]
I have the same issue. It seems like bundle app acts like a debug release ?
It doesn't make sense

**Comment by mubashiralisiddiqui** [comment]
> @mubashiralisiddiqui Sorry, but did you find some solution? I have the same problem after upgrading from 0.68.5 to 0.72.9. I used react-native cli to init a new project from 0.72.9 template, and after I just copied all js-files and all dependencies and Android modules

I fiexd it by creating a new cli and move my code into it after that it resolved

**Comment by danilvalov** [comment]
@mubashiralisiddiqui
I solved it already when I found the following code in `MainApplication.java` file and removed it:
```java
        @Override
        protected @Nullable
        String getBundleAssetName() {
            return "app.bundle";
        }
```
Previously I used some [Jitsi library](https://www.npmjs.com/package/react-native-jitsi-meet#android-install) inside my project, and I forgot to delete this code after switching to different Jitsi library in my project, so I had the problem with crashing.

So I think the main reason of this bug is some code added before that breaks Android logic to render activities

**Comment by mubashiralisiddiqui** [comment]
> @mubashiralisiddiqui I solved it already when I found the following code in `MainApplication.java` file and removed it:
> 
> ```java
>         @Override
>         protected @Nullable
>         String getBundleAssetName() {
>             return "app.bundle";
>         }
> ```
> 
> Previously I used some [Jitsi library](https://www.npmjs.com/package/react-native-jitsi-meet#android-install) inside my project, and I forgot to delete this code after switching to different Jitsi library in my project, so I had the problem with crashing.
> 
> So I think the main reason of this bug is some code added before that breaks Android logic to render activities

Yes I am using jitsi library could be the reason thanks
