### ISSUE TITLE
react-native bundle not working on windows 10

### ISSUE THREAD

**Issue by elinac** [facebook/react-native#3997]
react-native bundle --entry-file index.android.js --platform android --bundle-output android\app\src\main\res\asserts\index.android.bundle
E:\dev\AwesomeProject\node_modules\react-native\node_modules\promise\lib\done.js:10
      throw err;
      ^

Error: Took too long to start server. Server logs:
Sat, 07 Nov 2015 14:37:37 GMT ReactNativePackager:SocketServer server got ipc message { type: 'createSocketServer',
  data:
   { sockPath: 'C:\\Users\\donald\\AppData\\Local\\Temp\\react-packager-9248a9803ac72b509b389b456696850d',
     options:
      { projectRoots: [Object],
        assetRoots: [],
        blacklistRE: [Object],
        transformModulePath: 'E:\\dev\\AwesomeProject\\node_modules\\react-native\\packager\\transformer.js' } } }
[22:37:37] <START> Building Dependency Graph
[22:37:37] <START> Crawling File System
[22:37:37] <START> Loading bundles layout
[22:37:37] <END>   Loading bundles layout (0ms)
Sat, 07 Nov 2015 14:37:37 GMT ReactNativePackager:SocketServer error creating server EACCES
Sat, 07 Nov 2015 14:37:37 GMT ReactNativePackager:SocketServer uncaught error Error: listen EACCES C:\Users\donald\AppData\Local\Temp\react-packager-9248a9803ac72b509b389b456696850d
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1218:19)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1357:5)
    at new SocketServer (E:/dev/AwesomeProject/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketServer.js:24:18)
    at process.<anonymous> (E:/dev/AwesomeProject/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketServer.js:177:7)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
Sat, 07 Nov 2015 23:17:52 GMT ReactNativePackager:SocketServer server got ipc message { type: 'createSocketServer',
  data:
   { sockPath: 'C:\\Users\\donald\\AppData\\Local\\Temp\\react-packager-9248a9803ac72b509b389b456696850d',
     options:
      { projectRoots: [Object],
        assetRoots: [],
        blacklistRE: [Object],
        transformModulePath: 'E:\\dev\\AwesomeProject\\node_modules\\react-native\\packager\\transformer.js' } } }
[07:17:52] <START> Building Dependency Graph
[07:17:52] <START> Crawling File System
[07:17:52] <START> Loading bundles layout
[07:17:52] <END>   Loading bundles layout (0ms)
Sat, 07 Nov 2015 23:17:52 GMT ReactNativePackager:SocketServer error creating server EACCES
Sat, 07 Nov 2015 23:17:52 GMT ReactNativePackager:SocketServer uncaught error Error: listen EACCES C:\Users\donald\AppData\Local\Temp\react-packager-9248a9803ac72b509b389b456696850d
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1218:19)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1357:5)
    at new SocketServer (E:/dev/AwesomeProject/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketServer.js:24:18)
    at process.<anonymous> (E:/dev/AwesomeProject/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketServer.js:177:7)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
Sat, 07 Nov 2015 23:29:12 GMT ReactNativePackager:SocketServer server got ipc message { type: 'createSocketServer',
  data:
   { sockPath: 'C:\\Users\\donald\\AppData\\Local\\Temp\\react-packager-9248a9803ac72b509b389b456696850d',
     options:
      { projectRoots: [Object],
        assetRoots: [],
        blacklistRE: [Object],
        transformModulePath: 'E:\\dev\\AwesomeProject\\node_modules\\react-native\\packager\\transformer.js' } } }
[07:29:12] <START> Building Dependency Graph
[07:29:12] <START> Crawling File System
[07:29:12] <START> Loading bundles layout
[07:29:12] <END>   Loading bundles layout (0ms)
Sat, 07 Nov 2015 23:29:13 GMT ReactNativePackager:SocketServer error creating server EACCES
Sat, 07 Nov 2015 23:29:13 GMT ReactNativePackager:SocketServer uncaught error Error: listen EACCES C:\Users\donald\AppData\Local\Temp\react-packager-9248a9803ac72b509b389b456696850d
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1218:19)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1357:5)
    at new SocketServer (E:/dev/AwesomeProject/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketServer.js:24:18)
    at process.<anonymous> (E:/dev/AwesomeProject/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketServer.js:177:7)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
Sun, 08 Nov 2015 03:20:04 GMT ReactNativePackager:SocketServer server got ipc message { type: 'createSocketServer',
  data:
   { sockPath: 'C:\\Users\\donald\\AppData\\Local\\Temp\\react-packager-9248a9803ac72b509b389b456696850d',
     options:
      { projectRoots: [Object],
        assetRoots: [],
        blacklistRE: [Object],
        transformModulePath: 'E:\\dev\\AwesomeProject\\node_modules\\react-native\\packager\\transformer.js' } } }
[11:20:04] <START> Building Dependency Graph
[11:20:04] <START> Crawling File System
[11:20:04] <START> Loading bundles layout
[11:20:04] <END>   Loading bundles layout (0ms)
Sun, 08 Nov 2015 03:20:04 GMT ReactNativePackager:SocketServer error creating server EACCES
Sun, 08 Nov 2015 03:20:04 GMT ReactNativePackager:SocketServer uncaught error Error: listen EACCES C:\Users\donald\AppData\Local\Temp\react-packager-9248a9803ac72b509b389b456696850d
    at Object.exports._errnoException (util.js:860:11)
    at exports._exceptionWithHostPort (util.js:883:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1360:5)
    at new SocketServer (E:/dev/AwesomeProject/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketServer.js:24:18)
    at process.<anonymous> (E:/dev/AwesomeProject/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketServer.js:177:7)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)
Sun, 08 Nov 2015 03:20:52 GMT ReactNativePackager:SocketServer server got ipc message { type: 'createSocketServer',
  data:
   { sockPath: 'C:\\Users\\donald\\AppData\\Local\\Temp\\react-packager-9248a9803ac72b509b389b456696850d',
     options:
      { projectRoots: [Object],
        assetRoots: [],
        blacklistRE: [Object],
        transformModulePath: 'E:\\dev\\AwesomeProject\\node_modules\\react-native\\packager\\transformer.js' } } }
[11:20:52] <START> Building Dependency Graph
[11:20:52] <START> Crawling File System
[11:20:52] <START> Loading bundles layout
[11:20:52] <END>   Loading bundles layout (0ms)
Sun, 08 Nov 2015 03:20:52 GMT ReactNativePackager:SocketServer error creating server EACCES
Sun, 08 Nov 2015 03:20:52 GMT ReactNativePackager:SocketServer uncaught error Error: listen EACCES C:\Users\donald\AppData\Local\Temp\react-packager-9248a9803ac72b509b389b456696850d
    at Object.exports._errnoException (util.js:860:11)
    at exports._exceptionWithHostPort (util.js:883:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1360:5)
    at new SocketServer (E:/dev/AwesomeProject/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketServer.js:24:18)
    at process.<anonymous> (E:/dev/AwesomeProject/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketServer.js:177:7)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)
Mon, 09 Nov 2015 13:22:47 GMT ReactNativePackager:SocketServer server got ipc message { type: 'createSocketServer',
  data:
   { sockPath: 'C:\\Users\\donald\\AppData\\Local\\Temp\\react-packager-9248a9803ac72b509b389b456696850d',
     options:
      { projectRoots: [Object],
        assetRoots: [],
        blacklistRE: [Object],
        transformModulePath: 'E:\\dev\\AwesomeProject\\node_modules\\react-native\\packager\\transformer.js' } } }
Mon, 09 Nov 2015 13:22:47 GMT ReactNativePackager:SocketServer sockPath:C:\Users\donald\AppData\Local\Temp\react-packager-9248a9803ac72b509b389b456696850d
[21:22:47] <START> Building Dependency Graph
[21:22:47] <START> Crawling File System
[21:22:47] <START> Loading bundles layout
[21:22:47] <END>   Loading bundles layout (0ms)
Mon, 09 Nov 2015 13:22:47 GMT ReactNativePackager:SocketServer error creating server EACCES
Mon, 09 Nov 2015 13:22:47 GMT ReactNativePackager:SocketServer uncaught error Error: listen EACCES C:\Users\donald\AppData\Local\Temp\react-packager-9248a9803ac72b509b389b456696850d
    at Object.exports._errnoException (util.js:860:11)
    at exports._exceptionWithHostPort (util.js:883:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1360:5)
    at new SocketServer (E:/dev/AwesomeProject/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketServer.js:24:18)
    at process.<anonymous> (E:/dev/AwesomeProject/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketServer.js:178:7)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)

    at [object Object]._onTimeout (E:/dev/AwesomeProject/node_modules/react-native/packager/react-packager/src/SocketInterface/index.js:82:7)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by bramstieperaere** [comment]
The problem is that the socket server cannot create the socket:

Mon, 09 Nov 2015 13:22:47 GMT ReactNativePackager:SocketServer uncaught error Error: listen EACCES C:\Users\donald\AppData\Local\Temp\react-packager-9248a9803ac72b509b389b456696850d

cfr  https://gist.github.com/domenic/2790533  the socket name is not a valid windows socket name.

if you change <your project>\node_modules\react-native\packager\react-packager\src\SocketInterface\index.js, line 38-41 to

      let sockPath = path.join(
        tmpdir,
        'react-packager-' + hash.digest('hex')
      );
      if (process.platform==='win32'){
        sockPath = sockPath.replace(/^\//, '')
        sockPath = sockPath.replace(/\//g, '-')
        sockPath = '\\\\.\\pipe\\' + sockPath
      }

it works.

**Comment by elinac** [comment]
Thanks @bramstieperaere ,it's works.
