### ISSUE TITLE
Babel error on run UIExplorer example

### ISSUE THREAD

**Issue by lionelvon** [facebook/react-native#4030]
/Users/XmacZone/node_modules/babel-core/lib/transformation/file/logger.js:43
    throw new Constructor(this._buildMessage(msg));
    ^

ReferenceError: [BABEL] /Users/XmacZone/MyProjects/react-native/packager/react-packager/src/Activity/index.js: Unknown option: /Users/XmacZone/MyProjects/react-native/packager/react-packager/.babelrc.whitelist
    at Logger.error (/Users/XmacZone/node_modules/babel-core/lib/transformation/file/logger.js:43:11)
    at OptionManager.mergeOptions (/Users/XmacZone/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:18)
    at OptionManager.addConfig (/Users/XmacZone/node_modules/babel-core/lib/transformation/file/options/option-manager.js:206:10)
    at OptionManager.findConfigs (/Users/XmacZone/node_modules/babel-core/lib/transformation/file/options/option-manager.js:347:16)
    at OptionManager.init (/Users/XmacZone/node_modules/babel-core/lib/transformation/file/options/option-manager.js:392:12)
    at File.initOptions (/Users/XmacZone/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/Users/XmacZone/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/Users/XmacZone/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at Object.transformFileSync (/Users/XmacZone/node_modules/babel-core/lib/api/node.js:113:10)
    at compile (/Users/XmacZone/node_modules/babel-core/lib/api/register/node.js:111:20)

**Comment by ide** [comment]
Looks like you are using Babel 6 somewhere.

**Comment by lionelvon** [comment]
@ide I downgraded Babel from 6 to 5, this issue gone. Thanks!
Now I met a new issue.

Unable to resolve module LinkedStateMixin
Invalid directory /Users/node_modules/LinkedStateMixin

in react-native.js

**Comment by christopherdro** [comment]
@lionelvon Did you already try restarting the packager?

**Comment by lionelvon** [comment]
@christopherdro Yes. I even restarted the computer. 
Please see the attach file.
![2015-11-11_1003](https://cloud.githubusercontent.com/assets/14068852/11081885/8ef76454-885b-11e5-8d32-06ee50f1702c.png)

**Comment by lionelvon** [comment]
I deleted the whole react-native folder then git clone from github.com again. 
After run the npm install, I met a new issue:

![2015-11-11_1159](https://cloud.githubusercontent.com/assets/14068852/11083572/aabebf06-886b-11e5-8271-a1ca3eb2923a.png)

**Comment by admmasters** [comment]
Same issue as lionelvon with the latest master.

**Comment by elrikdante** [comment]
Delete your ~/.babelrc

And rerun your packager. 

It's a cache of all new loaded modules... Doesn't get recompiled properly it seems. 

Regards,
Dante Elrik

**Comment by ajwhite** [comment]
Will `v0.16.0` address this since it's introducing [babel-core@6.1.20](https://github.com/facebook/react-native/blob/v0.16.0-rc/package.json#L58-L83)? I came across this problem before going back down to `0.15.0`

**Comment by jsierles** [comment]
@facebook-github-bot answered
