### ISSUE TITLE
npm run start -- --root $JS_DIR failed

### ISSUE THREAD

**Issue by sapphirezzz** [facebook/react-native#4035]
Zack:react-native double$ pwd
/Users/double/Desktop/mooyoo_github/Meijiabang/meijiabang-ios/code/node_modules/react-native
Zack:react-native double$ npm run start -- --root /Users/double/Desktop/mooyoo_github/Meijiabang/meijiabang-ios/code/ReactComponent/

> react-native@0.14.2 start /Users/double/Desktop/mooyoo_github/Meijiabang/meijiabang-ios/code/node_modules/react-native
> ./packager/packager.sh || true "--root" "/Users/double/Desktop/mooyoo_github/Meijiabang/meijiabang-ios/code/ReactComponent/"

 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/double/Desktop/mooyoo_github/Meijiabang/meijiabang-ios/code 

[16:31:25] <START> Building Dependency Graph
[16:31:25] <START> Crawling File System
[16:31:25] <START> Loading bundles layout
[16:31:25] <END>   Loading bundles layout (0ms)

React packager ready.

[16:31:28] <END>   Crawling File System (2829ms)
[16:31:28] <START> Building in-memory fs for JavaScript
[16:31:29] <END>   Building in-memory fs for JavaScript (579ms)
[16:31:29] <START> Building Haste Map
Error building DepdendencyGraph:
 Error: Naming collision detected: /Users/double/Desktop/mooyoo_github/Meijiabang/meijiabang-ios/code/node_modules/react-tools/src/renderers/shared/event/eventPlugins/ResponderSyntheticEvent.js collides with /Users/double/Desktop/mooyoo_github/Meijiabang/meijiabang-ios/code/node_modules/react-native/node_modules/react-tools/src/renderers/shared/event/eventPlugins/ResponderSyntheticEvent.js
    at HasteMap._updateHasteMap (/Users/double/Desktop/mooyoo_github/Meijiabang/meijiabang-ios/code/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:123:13)
    at /Users/double/Desktop/mooyoo_github/Meijiabang/meijiabang-ios/code/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:95:28
    at tryCallOne (/Users/double/Desktop/mooyoo_github/Meijiabang/meijiabang-ios/code/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/double/Desktop/mooyoo_github/Meijiabang/meijiabang-ios/code/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/double/Desktop/mooyoo_github/Meijiabang/meijiabang-ios/code/node_modules/react-native/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)

**Comment by jpapillon** [comment]
I have the same issue with react-native 0.13.0.

**Comment by jpapillon** [comment]
@sapphirezzz : Check my comment on [this issue](https://github.com/facebook/react-native/issues/3558#issuecomment-155557172).

**Comment by sapphirezzz** [comment]
@jpapillon Mine is v5.0.0 . I have fixed this by using (JS_DIR=`pwd`; cd node_modules/react-native; npm run start -- --root $JS_DIR) . I put the .js file and node_modules in current folder .
