### ISSUE TITLE
[Android] 'Origin is not allowed by Access-Control-Allow-Origin' when making request

### ISSUE THREAD

**Issue by edcs** [facebook/react-native#4039]
I'm using Superagent to make requests to my API, this works fine on iOS but when I make an XMLHttpRequest on Android I get the following error:

```
Error: Origin is not allowed by Access-Control-Allow-Origin
    at Request.crossDomainError (http://localhost:8081/index.android.bundle?platform=android&dev=true:63560:9)
    at xhr.onreadystatechange (http://localhost:8081/index.android.bundle?platform=android&dev=true:63625:13)
    at XMLHttpRequest.setReadyState (http://localhost:8081/index.android.bundle?platform=android&dev=true:7812:1)
    at XMLHttpRequest.callback (http://localhost:8081/index.android.bundle?platform=android&dev=true:7792:6)
    at MessageQueue.__invokeCallback (http://localhost:8081/index.android.bundle?platform=android&dev=true:2557:10)
    at http://localhost:8081/index.android.bundle?platform=android&dev=true:2469:8
    at guard (http://localhost:8081/index.android.bundle?platform=android&dev=true:2419:1)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.android.bundle?platform=android&dev=true:2468:1)
    at messageHandlers.executeJSCall (http://localhost:8081/debuggerWorker.js:25:73)
    at DedicatedWorkerGlobalScope.onmessage (http://localhost:8081/debuggerWorker.js:42:5)
```

I've got the internet permission enabled in the Android Manifest like this:

```xml
 <uses-permission android:name="android.permission.INTERNET" />
```

And the code to make the API request is just basic Superagent stuff:

```javascript
var superagent = require('superagent');

superagent.get(this._buildUrl())
                  .send(this._params)
                  .set('User-Agent', this._userAgent)
                  .set('Authorization',  this._signature)
                  .set('Accept', 'application/json').end(function (error, response) {
                      callback(error, response);
                  });
```

I've also set this header on my API to see if that fixes the issue:

```
Access-Control-Allow-Origin:*
```

Is this some kind of Android bug or have I missed something out?

**Comment by edcs** [comment]
The Android emulator works in a different way to the iOS one - I need to access my API via 10.0.2.2 for default AVD and 10.0.3.2 for Genymotion.

**Comment by ACCTFORGH** [comment]
@edcs when I do adb devices in console, I get my device address at 192.168.57.101:5555. Would you elaborate a little more on how to solve this issue? How do we change the address of the emulator? I encountered the same issue even when trying on a physical device. Thanks!
