### ISSUE TITLE
Packager fails to launch when running the iOS UIExplorer 

### ISSUE THREAD

**Issue by ide** [facebook/react-native#4055]
Haven't looked into this deeply but this is what I get in the packager terminal window when running the UIExplorer on master. Interestingly, `npm start` works fine. Also running `launchPackager.command` from the shell works fine. Just something about launching it from a non-shell process seems broken.

I don't think it is related to PATH because when I source my `.bash_profile` in packager.sh, the error is still there.

cc @tadeuzagallo 

```
/Users/ide/Code/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i));
          ^

ReferenceError: Unknown plugin "syntax-async-functions" specified in "foreign" at 0
    at /Users/ide/Code/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/ide/Code/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:161:20)
    at OptionManager.mergeOptions (/Users/ide/Code/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:254:36)
    at compile (/Users/ide/Code/react-native/node_modules/babel-core/lib/api/register/node.js:95:15)
    at loader (/Users/ide/Code/react-native/node_modules/babel-core/lib/api/register/node.js:136:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ide/Code/react-native/node_modules/babel-core/lib/api/register/node.js:146:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
Process terminated. Press <enter> to close the window
```

**Comment by ide** [comment]
Looks like the problem is related to the the cwd: when I run `launchPackager.command` from my home directory, for example, I get the error. But when I run it from my react-native checkout, it runs fine. I bet if we set cwd in packager.sh, it'd be fine.

**Comment by tadeuzagallo** [comment]
The script hasn't been working for me because of my shell configuration, so I missed this... :(

I just created a diff for that, should be out soon.

**Comment by ide** [comment]
Thanks @tadeuzagallo. This fixes the issue for me, in case you want to compare it with your fix: https://github.com/exponentjs/react-native/commit/68d01a257c76425436c3d2c557c6a2a7f366d3c4

**Comment by kingnight** [comment]
I have  try exponentjs@68d01a2 ,  fail


   > react-native@0.12.0 start /Users/jinkai/reactnative/react-native-master
> /usr/bin/env bash -c './packager/packager.sh "$@" || true' --

          /Users/jinkai/node_modules/babel-core/lib/transformation/file/options/option-manager.js:193
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

         ReferenceError: Unknown plugin "syntax-async-functions" specified in "base" at 0, attempted to resolve relative to "/Users/jinkai/reactnative/react-native-master/local-cli/bundle"
    at /Users/jinkai/node_modules/babel-core/lib/transformation/file/options/option-manager.js:193:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/jinkai/node_modules/babel-core/lib/transformation/file/options/option-manager.js:173:20)
    at OptionManager.mergeOptions (/Users/jinkai/node_modules/babel-core/lib/transformation/file/options/option-manager.js:271:36)
    at compile (/Users/jinkai/node_modules/babel-core/node_modules/babel-register/lib/node.js:85:15)
    at loader (/Users/jinkai/node_modules/babel-core/node_modules/babel-register/lib/node.js:127:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jinkai/node_modules/babel-core/node_modules/babel-register/lib/node.js:137:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

**Comment by kingnight** [comment]
at end ,  in  root path of react-native-master
after run

    npm install   

ok

**Comment by timzaak** [comment]
If someone builds project with react-native master branch. and also has the same problem. The following may help you
```sh 
rm  -fr yourProject/node_modules/react-native/node_modules/*
#in other place
react-native init tmpProject
cp -r tmpProject/node_modules/react-native/node_modules/* yourProject/node_modules/react-native/node_modules/
```
it will success.  there may have some conflicts between the devDependencies and dependencies.
And use `react-native start` instead of `npm start` to run react-native server in command. Good luck!

**Comment by chaoslawful** [comment]
Your home directory maybe contains the file `.babelrc` and referenced plugin `syntax-async-functions` in it. It is the case in my development environment.
