### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long android.text.Layout.getLineRangeForDraw(android.graphics.Canvas)' on a null object reference

### ISSUE THREAD

**Issue by chengweibo** [facebook/react-native#40723]
### Description

Sumsung Galaxy A71 , Sumsung Galaxy A32, Sumsung Galaxy A53 happen below problem , hope to give me solution，thanks

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long android.text.Layout.getLineRangeForDraw(android.graphics.Canvas)' on a null object reference
       at android.widget.Editor.drawHardwareAccelerated(Editor.java:2340)
       at android.widget.Editor.onDraw(Editor.java:2331)
       at android.widget.TextView.onDraw(TextView.java:8887)
       at android.view.View.draw(View.java:24406)
       at android.view.View.updateDisplayListIfDirty(View.java:23267)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4732)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4704)
       at android.view.View.updateDisplayListIfDirty(View.java:23214)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4732)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4704)
       at android.view.View.updateDisplayListIfDirty(View.java:23214)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4732)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4704)
       at android.view.View.updateDisplayListIfDirty(View.java:23214)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4732)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4704)
       at android.view.View.updateDisplayListIfDirty(View.java:23214)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4732)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4704)
       at android.view.View.updateDisplayListIfDirty(View.java:23214)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4732)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4704)
       at android.view.View.updateDisplayListIfDirty(View.java:23214)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4732)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4704)
       at android.view.View.updateDisplayListIfDirty(View.java:23214)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4732)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4704)
       at android.view.View.updateDisplayListIfDirty(View.java:23214)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4732)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4704)
       at android.view.View.updateDisplayListIfDirty(View.java:23214)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4732)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4704)
       at android.view.View.updateDisplayListIfDirty(View.java:23214)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:777)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:783)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:881)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:5647)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5330)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4486)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
       at android.view.Choreographer.doCallbacks(Choreographer.java:923)
       at android.view.Choreographer.doFrame(Choreographer.java:852)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

### React Native Version

0.64.2

### Output of `npx react-native info`

react native app

### Steps to reproduce

react native app

### Snack, screenshot, or link to a repository

react native app

**Comment by cuongnguyeneh** [comment]
Got same issue with react native 0.76.9
