### ISSUE TITLE
 ReferenceError: process is not defined

### ISSUE THREAD

**Issue by klausbreyer** [facebook/react-native#4073]
Hey, strange error. 

I updated to 0.14.2 (from 0.13.2) and build my app. 

The simulator screen stays white and chrome debug shows me this: 

```
index.ios.bundle:712 Error: 
 stack: ReferenceError: process is not defined
    at Object.ReactPerf.measureMethods (http://localhost:8081/index.ios.bundle:56298:4)
    at http://localhost:8081/index.ios.bundle:55576:11
    at requireImpl (http://localhost:8081/index.ios.bundle:64:13)
    at require (http://localhost:8081/index.ios.bundle:26:8)
    at http://localhost:8081/index.ios.bundle:55338:27
    at requireImpl (http://localhost:8081/index.ios.bundle:64:13)
    at require (http://localhost:8081/index.ios.bundle:26:8)
    at http://localhost:8081/index.ios.bundle:55216:27
    at requireImpl (http://localhost:8081/index.ios.bundle:64:13)
    at require (http://localhost:8081/index.ios.bundle:26:8)
 line: undefined
 message: process is not defined ReferenceError: process is not defined
    at Object.ReactPerf.measureMethods (http://localhost:8081/index.ios.bundle:56298:4)
    at http://localhost:8081/index.ios.bundle:55576:11
    at requireImpl (http://localhost:8081/index.ios.bundle:64:13)
    at require (http://localhost:8081/index.ios.bundle:26:8)
    at http://localhost:8081/index.ios.bundle:55338:27
    at requireImpl (http://localhost:8081/index.ios.bundle:64:13)
    at require (http://localhost:8081/index.ios.bundle:26:8)
    at http://localhost:8081/index.ios.bundle:55216:27
    at requireImpl (http://localhost:8081/index.ios.bundle:64:13)
    at require (http://localhost:8081/index.ios.bundle:26:8)onError @ index.ios.bundle:712
index.ios.bundle:712 Error: 
 stack: ReferenceError: process is not defined
    at http://localhost:8081/index.ios.bundle:57041:4
    at requireImpl (http://localhost:8081/index.ios.bundle:64:13)
    at require (http://localhost:8081/index.ios.bundle:26:8)
    at http://localhost:8081/index.ios.bundle:2839:13
    at requireImpl (http://localhost:8081/index.ios.bundle:64:13)
    at require (http://localhost:8081/index.ios.bundle:26:8)
    at http://localhost:8081/index.ios.bundle:2367:23
    at requireImpl (http://localhost:8081/index.ios.bundle:64:13)
    at require (http://localhost:8081/index.ios.bundle:26:8)
    at http://localhost:8081/index.ios.bundle:2341:18
 line: undefined
 message: process is not defined ReferenceError: process is not defined(…)onError @ index.ios.bundle:712
debuggerWorker.js:25 Uncaught TypeError: Cannot read property 'flushedQueue' of undefined
index.ios.bundle:712 Error: 
 stack: Error: Requiring module "BatchedBridge" which threw an exception
    at requireImpl (http://localhost:8081/index.ios.bundle:52:7)
    at requireImpl (http://localhost:8081/index.ios.bundle:34:27)
    at require (http://localhost:8081/index.ios.bundle:26:8)
    at messageHandlers.executeJSCall (http://localhost:8081/debuggerWorker.js:25:23)
    at DedicatedWorkerGlobalScope.onmessage (http://localhost:8081/debuggerWorker.js:42:5)
 line: undefined
 message: Requiring module "BatchedBridge" which threw an exception Error: Requiring module "BatchedBridge" which threw an exception(…)onError @ index.ios.bundle:712
debuggerWorker.js:25 Uncaught TypeError: Cannot read property 'callFunctionReturnFlushedQueue' of undefined
index.ios.bundle:712 Error: 
 stack: Error: Requiring module "BatchedBridge" which threw an exception
    at requireImpl (http://localhost:8081/index.ios.bundle:52:7)
    at requireImpl (http://localhost:8081/index.ios.bundle:34:27)
    at require (http://localhost:8081/index.ios.bundle:26:8)
    at messageHandlers.executeJSCall (http://localhost:8081/debuggerWorker.js:25:23)
    at DedicatedWorkerGlobalScope.onmessage (http://localhost:8081/debuggerWorker.js:42:5)
 line: undefined
 message: Requiring module "BatchedBridge" which threw an exception Error: Requiring module "BatchedBridge" which threw an exception(…)onError @ index.ios.bundle:712
debuggerWorker.js:25 Uncaught TypeError: Cannot read property 'callFunctionReturnFlushedQueue' of undefined
27debugger-ui:71 WebSocket connection to 'ws://localhost:8081/debugger-proxy' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

```

when I downgrade to 0.13.2 and rm -rf node_modules/ && npm  it works. again. 

What I did: removed every stain of system node and io.js and reinstalled nvm. My only global installed node module is now react-native-cli.

```
{
  "name": "Fierce",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh"
  },
  "dependencies": {
    "hoek": "^3.0.1",
    "immutable": "^3.7.5",
    "immutable-reducers": "^1.1.0",
    "isemail": "^2.1.0",
    "keymirror": "^0.1.1",
    "moment": "^2.10.6",
    "native": "^0.2.0",
    "react": "^0.14.0",
    "react-native": "^0.13.2",
    "react-native-simple-store": "^0.1.0",
    "react-redux": "^3.1.0",
    "redux": "^3.0.3",
    "redux-storage": "^1.3.2",
    "redux-thunk": "^1.0.0",
    "topo": "^2.0.0"
  }
}

```

I guess some issues with babel. But don't know for sure. But babel complains when I do npm i. 

```
Nevada3:MoveEngine kb1$ rm -rf node_modules/ && npm i
npm WARN deprecated babel-core@5.8.33: Babel 5 is no longer being maintained. Upgrade to Babel 6.
```

In a completly new react-native init project it seems to work fine. 

Where are points I can start debugging?

**Comment by klausbreyer** [comment]
narrowed it down to a react-redux issue. 
https://github.com/rackt/react-redux/issues/184
