### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'void android.view.View.dispatchCancelPendingInputEvents()

### ISSUE THREAD

**Issue by edstbbz** [facebook/react-native#41077]
### Description

[Android]
An exception is thrown periodically when requesting permissions:
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.dispatchCancelPendingInputEvents()' on a null object reference
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.ViewGroup.dispatchCancelPendingInputEvents(ViewGroup.java:3893)
    at android.view.View.cancelPendingInputEvents(View.java:15729)
    at android.app.Activity.cancelInputsAndStartExitTransition(Activity.java:4337)
    at android.app.Activity.startActivityForResult(Activity.java:4956)
    at android.app.Activity.requestPermissions(Activity.java:4193)
    at com.facebook.react.ReactActivityDelegate.requestPermissions(ReactActivityDelegate.java:191)
    at com.facebook.react.ReactActivity.requestPermissions(ReactActivity.java:110)
    at com.facebook.react.modules.permissions.PermissionsModule.requestPermission(PermissionsModule.java:126)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
    at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:154)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
    at java.lang.Thread.run(Thread.java:761)

### React Native Version

0.72.5

### Output of `npx react-native info`

System:
  OS: macOS 13.5.2
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 50.72 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.1
    path: /private/var/folders/7m/rj94pv291918l94_rmpgg9jm0000gn/T/xfs-7be70c02/node
  Yarn:
    version: 3.2.1
    path: /private/var/folders/7m/rj94pv291918l94_rmpgg9jm0000gn/T/xfs-7be70c02/yarn
  npm:
    version: 9.6.7
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.10.09.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 21.4
      - iOS 16.0
      - macOS 12.3
      - tvOS 16.0
      - watchOS 9.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 14.0.1/14A400
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.5
    path: /Users/user/.rvm/rubies/ruby-2.6.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false

### Steps to reproduce

call https://reactnative.dev/docs/next/permissionsandroid#request

### Snack, screenshot, or link to a repository

-

**Comment by cortinico** [comment]
Can you provide a repro?

**Comment by edstbbz** [comment]
I don't know what kind of reproduction can be provided, since this happens when calling "PermissionsAndroid.request" and it can't be reproduced on purpose, I see that there are errors in production

**Comment by cortinico** [comment]
> I don't know what kind of reproduction can be provided, since this happens when calling "PermissionsAndroid.request" and it can't be reproduced on purpose, I see that there are errors in production

As the bot suggested, you should use either a Snack or this template: https://github.com/new?template_name=reproducer-react-native&template_owner=react-native-community
And create a project where the app crashes by invoking the function you mentioned

**Comment by pe1ros** [comment]
@edstbbz  you have problem with implementation permission method but not react native( dont create issue before read docs...)))  )
1) add pemission to AndroidManifest
2) 
use someth ike that 

```
import { isAndroid } from '@app/constants/Device';
import { PermissionsAndroid } from 'react-native';

export const requestPermissions = async () => {
  try {
    if (isAndroid) {
      return await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS);
    } else {
      return Promise.resolve();
    }
  } catch (error) {
    console.error('requestPermissions: [ERROR] =>', error);
  }
};

```

3) You can use also this library 
https://github.com/zoontek/react-native-permissions

**Comment by edstbbz** [comment]
@cortinico https://snack.expo.dev/@edstubbz/great-blue-peanut
It's all about the usual request for permission, how to reproduce it 100% I do not know, since the problem occurs for users with a normal request for permissions (this can be seen by the exception), I was not able to reproduce it on purpose

**Comment by edstbbz** [comment]
On sentry im catch: 
<img width="1136" alt="screen" src="https://github.com/facebook/react-native/assets/75758285/d603159a-46d2-48ef-a049-d4e2da1f51ab">

**Comment by pe1ros** [comment]
@edstbbz Let me your code please, it will be faster that "pick finger to the sky"
If you request more than one permissions, provide all code place where it is.
I will try to help...

**Comment by edstbbz** [comment]
@pe1ros how can I give you the code? This is not an open source project with a huge code base. And most importantly, I don't understand what you want, because the permission request is used the same everywhere, according to the official api (   const status = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.CAMERA)  ). An exception occurs on the native api side

**Comment by DylanTet** [comment]
So if im reading this right @edstbbz, you're saying that the exception isn't being thrown 100% of the time for you?

**Comment by khayym** [comment]
I'm facing this same problem.

![44f0afc9702e20fcfcb964b6a181a8ae](https://github.com/facebook/react-native/assets/68564696/2aaadd3e-4e39-4c79-af98-4c783cab7a27)

**Comment by SwhiteMHC** [comment]
I am also experiencing this same problem.

**Comment by mayank-gera** [comment]
Hi Still facing the issues, any fix ?

**Comment by rsainiWin** [comment]
Facing the same

**Comment by trucuit** [comment]
same issue: RN 0.63.5
![Screenshot 2024-06-20 at 18 15 26](https://github.com/facebook/react-native/assets/28841825/8907458d-795d-4ce5-99c7-354bdd5f32b7)

**Comment by sanduluca** [comment]
We also have this issue using https://github.com/invertase/notifee

**Comment by EwaGuziejko** [comment]
Same problem here on react-native 0.74.3 -permissions randomly crashes

**Comment by SKHRAPP** [comment]
Any Update from this issue ?

**Comment by rsainiWin** [comment]
Same problem here on react-native 0.74.3

**Comment by cblaze22** [comment]
Same problem here on react-native 0.74.3

**Comment by wangchongwei** [comment]
Same problem here on react-native 0.74.3.
PermissionsAndroid.PERMISSIONS.CAMERA

**Comment by Felipe-G-Melo** [comment]
Any solution? I'm having the same problem with RN 0.76.3

**Comment by Felipe-G-Melo** [comment]
Updates on the bug:

I discovered that the cause of the bug was not the camera library.
Before opening my camera, I was showing a loading indicator. What was happening is that sometimes the loading was completing so quickly that the View didn’t have enough time to render, and when it tried to access the View, it no longer existed, causing the error.

To fix this, I wrapped the camera in a setTimeout with a delay of 1 second. This gives the View enough time to load, preventing the error from happening.

Here’s an example of my code:

const takePhoto = async () => {
   setIsLoading(true);
 
  setTimeout(async () => {
      const photo = await launchCamera();
      //my code...
   }, 1000);
}
