### ISSUE TITLE
couldn't find DSO to load: libhermes.so caused by: couldn't find DSO to load: libjsi.so caused by: couldn't find DSO to load: libfolly_runtime.so caused by: couldn't find DSO to load: libglog.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: is 64-bit instead of 32-bit 

### ISSUE THREAD

**Issue by sanjeevyadavIT** [facebook/react-native#41372]
### Description

We have an App which is also available on Xiaomi app store called [GetApps](https://global.app.mi.com/?lo=IN&la=en), when Xiaomi user is downloading or upgrading the app from GetApps store, we are getting the crash of SoLoader file mismatch because of 64 Bit version was provided instead of 32 bit. 

We cross verified the device in which these crashes are occurring(for example Redmi Note 11) they are 64 bit architecture only, but despite that if app is from getApps it is saying expected 32 bit, which I have no clue why

Also we have added Explicit soLoader aar in our app which is (0.10.3) , like this because react is dfm in our code
```
implementation(files("src/main/libs/soloader-0.10.3.aar"))

// https://github.com/facebook/SoLoader/issues/19
implementation(libs.react.library) {
        exclude(group = "com.facebook.soloader", module = "soloader")
}
```

**How do we know the crashes are occuring from app download from Xiaomi app store?** 

In crashlytics, you can see `INSTALL_PACKAGE_NAME` which is optioning to `com.xiaomi.mipicks`,  if crash is happening if app is download from google play store, then `INSTALL_PACKAGE_NAME` points to `com.android.vendor`

### StackTrace
```
# Crashlytics - Stack trace
# Application: com.demo.myapp
# Platform: android
# Version: 2023.21.4 (232104)
# Issue: 3fe50f2a72e37c101c90fd49e5803e3a
# Session: 654B23A500D100017281870DFE4C7D52_DNE_4_v2
# Date: Wed Nov 08 2023 11:29:23 GMT+0530 (India Standard Time)

Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so caused by: couldn't find DSO to load: libjsi.so caused by: couldn't find DSO to load: libfolly_runtime.so caused by: couldn't find DSO to load: libglog.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.demo.myapp/files/splitcompat/232104/native-libraries/config.arm64_v8a/libc++_shared.so" is 64-bit instead of 32-bit result: 0 result: 0 result: 0 result: 0 result: 0
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1132)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:860)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:807)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:777)
       at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:26)
       at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
       at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1110)
       at java.lang.Thread.run(Thread.java:764)

Caused by java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjsi.so caused by: couldn't find DSO to load: libfolly_runtime.so caused by: couldn't find DSO to load: libglog.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.demo.myapp/files/splitcompat/232104/native-libraries/config.arm64_v8a/libc++_shared.so" is 64-bit instead of 32-bit result: 0 result: 0 result: 0 result: 0
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1132)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:846)
       at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:177)
       at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:103)
       at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1072)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:860)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:807)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:777)
       at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:26)
       at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
       at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1110)
       at java.lang.Thread.run(Thread.java:764)

Caused by java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfolly_runtime.so caused by: couldn't find DSO to load: libglog.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.demo.myapp/files/splitcompat/232104/native-libraries/config.arm64_v8a/libc++_shared.so" is 64-bit instead of 32-bit result: 0 result: 0 result: 0
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1132)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:846)
       at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:177)
       at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:103)
       at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1072)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:846)
       at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:177)
       at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:103)
       at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1072)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:860)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:807)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:777)
       at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:26)
       at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
       at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1110)
       at java.lang.Thread.run(Thread.java:764)

Caused by java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libglog.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.demo.myapp/files/splitcompat/232104/native-libraries/config.arm64_v8a/libc++_shared.so" is 64-bit instead of 32-bit result: 0 result: 0
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1132)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:846)
       at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:177)
       at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:103)
       at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1072)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:846)
       at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:177)
       at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:103)
       at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1072)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:846)
       at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:177)
       at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:103)
       at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1072)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:860)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:807)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:777)
       at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:26)
       at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
       at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1110)
       at java.lang.Thread.run(Thread.java:764)

Caused by java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.demo.myapp/files/splitcompat/232104/native-libraries/config.arm64_v8a/libc++_shared.so" is 64-bit instead of 32-bit result: 0
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1132)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:846)
       at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:177)
       at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:103)
       at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1072)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:846)
       at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:177)
       at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:103)
       at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1072)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:846)
       at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:177)
       at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:103)
       at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1072)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:846)
       at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:177)
       at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:103)
       at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1072)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:860)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:807)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:777)
       at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:26)
       at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
       at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1110)
       at java.lang.Thread.run(Thread.java:764)

Caused by java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.demo.myapp/files/splitcompat/232104/native-libraries/config.arm64_v8a/libc++_shared.so" is 64-bit instead of 32-bit
       at java.lang.Runtime.load0(Runtime.java:928)
       at java.lang.System.load(System.java:1633)
       at com.facebook.soloader.SoLoader$1.load(SoLoader.java:563)
       at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:110)
       at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1072)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:846)
       at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:177)
       at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:103)
       at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1072)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:846)
       at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:177)
       at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:103)
       at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1072)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:846)
       at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:177)
       at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:103)
       at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1072)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:846)
       at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:177)
       at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:103)
       at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1072)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:948)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:860)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:807)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:777)
       at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:26)
       at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
       at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1110)
       at java.lang.Thread.run(Thread.java:764)

```

### React Native Version

0.71.13

### Output of `npx react-native info`

```
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.15 GB / 32.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
    Watchman: 2022.12.19.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10406996
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.13 => 0.71.13 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Upload your App your on Google Play Store
2. If Xiaomi GetApps also list your app on their play store, download or upgrade from there
3. Make sure you have Xiaomi phone(example Redmi Note 11)
4. Open React Native Screen 

### Snack, screenshot, or link to a repository

The issue is related to when people are downloading same app on Xiaomi app store(GetApps) rather than Google Play store
<img width="1350" alt="Screenshot 2023-11-08 at 11 55 16 AM" src="https://github.com/facebook/react-native/assets/13250741/17c68dd2-28e3-4ca1-935a-ff05d00fbfc9">
<img width="518" alt="Screenshot 2023-11-08 at 11 58 00 AM" src="https://github.com/facebook/react-native/assets/13250741/68c45f12-dd49-4128-ba2e-6a9eb048f716">

**Comment by tfuchsmartin** [comment]
I have observed a similar spike also around 5th till 8th of November in our app's crashlytics for `Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so` 

Something is happening here.  RN version `0.75.2`

**Comment by extrackercchambers** [comment]
I'm seeing this too. Users with Google Pixel 8 and Pixel 8 pro were reporting crashes on their devices and I traced it back to this same error message. My app is on 0.63.3 though. Anyone have any idea what this is? Pixel 7 with Android 14 works fine but on Pixel 8 with Android 14 the app crashes.

**Comment by extrackercchambers** [comment]
Possibly related to https://github.com/facebook/react-native/issues/35374

**Comment by caleblawrence** [comment]
I'm also seeing this in an app that is downloaded from VMware Workstation One. It works fine when downloaded from the Play Store though.

**Comment by extrackercchambers** [comment]
Updating the soloader is what fixed it for me:
   implementation 'com.facebook.soloader:soloader:0.10.4+'

**Comment by caleblawrence** [comment]
> Updating the soloader is what fixed it for me: implementation 'com.facebook.soloader:soloader:0.10.4+'

Thanks a lot for the tip, this solved my issue!

**Comment by avyasradicle** [comment]
I am facing the same issue. My react-native version is 0.73.0
I don't see the reference of com.facebook.soloader:soloader other than in the file- node_modules/react-native/gradle/libs.versions.toml
And the version there is soloader = "0.10.5"
soloader = { module = "com.facebook.soloader:soloader", version.ref = "soloader" }

Please suggest what changes should I make to fix the issue.

**Comment by extrackercchambers** [comment]
> soloader
It was in android/app/src/main/java/com/{appName}/MainApplication.java. If it's not there trying adding it with the other imports at the top.

**Comment by flyskywhy** [comment]
I fix it by add below into <https://github.com/flyskywhy/GCanvasRNExamples/blob/e47ef389c43a4bc3f4fdb0ac0c2afd1ed78c5960/android/settings.gradle>
```
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
```

**Comment by rahuljeevan-experion** [comment]
> Updating the soloader is what fixed it for me: implementation 'com.facebook.soloader:soloader:0.10.4+'

is this to be added in `android/app/build.gradle`, I checked the current version in `node_modules/react-native/ReactAndroid/build.gradle` and it was `SO_LOADER_VERSION=0.10.5`. 
Do I need to make the above mentioned change if the current version showing is `0.10.5`

My React Native version is  `0.72.12`

**Comment by cortinico** [comment]
Closing as the "couldn't find DSO to load: libhermes.so" is caused by a variety of different reasons. The comments in this thread are misleading and we invite you to open a new issue with your specific environment where we can help you further.

**Comment by MichelBahl** [comment]
Create an API 35 emulator without [16 kb Page Size Google APIs PlayStore](https://developer.android.com/guide/practices/page-sizes?hl=en)  solved my problem:

![androidapi35](https://github.com/user-attachments/assets/62025465-3168-4a55-b64e-fcfdcf9a7f1a)

**Comment by manjuy124** [comment]
> Create an API 35 emulator without [16 kb Page Size Google APIs PlayStore](https://developer.android.com/guide/practices/page-sizes?hl=en) solved my problem:
> 
> ![androidapi35](https://private-user-images.githubusercontent.com/11231563/387291705-62025465-3168-4a55-b64e-fcfdcf9a7f1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODUxNTgsIm5iZiI6MTczMjg4NDg1OCwicGF0aCI6Ii8xMTIzMTU2My8zODcyOTE3MDUtNjIwMjU0NjUtMzE2OC00YTU1LWI2NGUtZmNmZGNmOWE3ZjFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDEyNTQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0ODE2NmViOTQxMmVlMTEzNTg2MDE3M2E1NTBlZDUwYzFlOTE4ZTdhMjgyMzkzZTllMGI2ZDk5MzdjMWIxNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xqYM8dRCxwDNSfUfzAVhoXRJaXxsCw-u9IFXsajnh1o)

@MichelBahl It's worked for me. Do you know the reason why it didn't work with 16kb api version?

**Comment by MichelBahl** [comment]
> 
> @MichelBahl It's worked for me. Do you know the reason why it didn't work with 16kb api version?

No, I have no clue. But I m concerned about this will become an issue in the future.

**Comment by stdiodavid** [comment]
> I am facing the same issue. My react-native version is 0.73.0 I don't see the reference of com.facebook.soloader:soloader other than in the file- node_modules/react-native/gradle/libs.versions.toml And the version there is soloader = "0.10.5" soloader = { module = "com.facebook.soloader:soloader", version.ref = "soloader" }
> 
> Please suggest what changes should I make to fix the issue.

Same.Add `implementation 'com.facebook.soloader:soloader:0.10.4+'` fixed your issues?

**Comment by kanghyeji94** [comment]
> Create an API 35 emulator without [16 kb Page Size Google APIs PlayStore](https://developer.android.com/guide/practices/page-sizes?hl=en) solved my problem:
> 
> ![androidapi35](https://github.com/user-attachments/assets/62025465-3168-4a55-b64e-fcfdcf9a7f1a)

The 16kb page size feature will officially be released in November. 
I hit the above issue while testing if the app builds well on a 16kb page size emulator device.
Is there a fundamental solution?

**Comment by eyaydin** [comment]
@kanghyeji94 I'm in the same situation like yours. I was trying to test our app for the upcoming policy regarding "16 KB memory page sizes" and encounter this error.
React Native version 0.76.9, AGP 8.6.0 and NDK 28.2.13676358.

Anyone have any solution for this?

**Comment by serdarde** [comment]
Does anyone have a solution for Expo apps? I receive hundreds of crash alerts, but neither the internet nor LLMs have any answers.

**Comment by MichelBahl** [comment]
The problem might be fixed with this [commit](https://github.com/expo/expo/commit/91ea2f9a96281e4cb3e9a9d7c1340bf9ca9b5707)

```com.facebook.soloader.SoLoader``` has been removed.

**Comment by RajatSatashiya** [comment]
@eyaydin i don't have the solution for the actual error but for starters you can move to 0.77 or above. The react native support for 16kb page size was added in 0.77

**Comment by thisisadarshjaiswal** [comment]
Earlier I had this in mycode base force `"com.facebook.soloader:soloader:0.10.4"` which was helping to solve this issue. But with the upgraded version I am not able to use this as this gives me build error

```/Users/lsn-adarsh/Work/titan-rider-app/android/app/src/main/java/com/loadshare/deliveryapp/MainApplication.java:184: error: no suitable method found for init(MainApplication,OpenSourceMergedSoMapping)
            SoLoader.init(this, OpenSourceMergedSoMapping.INSTANCE);
                    ^
    method SoLoader.init(Context,int) is not applicable
      (argument mismatch; OpenSourceMergedSoMapping cannot be converted to int)
    method SoLoader.init(Context,boolean) is not applicable
      (argument mismatch; OpenSourceMergedSoMapping cannot be converted to boolean)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/lsn-adarsh/Work/titan-rider-app/android/app/src/main/java/com/loadshare/deliveryapp/ScannerActivity/SecondaryQCActivity.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error```

**Comment by thisisadarshjaiswal** [comment]
I solve the build error by using the same version of SoLoader (12.1)  smae as what rn-77 uses internally. I don't know if that makes any sense and is that safe to do and will this solve the issue?
