### ISSUE TITLE
Cannot read property 'root' of null

### ISSUE THREAD

**Issue by nsisodiya** [facebook/react-native#4139]
$ react-native start
 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   /Users/narendrasisodiya/Desktop/play/nativeTodo

[6:36:02 PM] <START> Building Dependency Graph
[6:36:02 PM] <START> Crawling File System
[6:36:02 PM] <START> Loading bundles layout
[6:36:02 PM] <END>   Loading bundles layout (0ms)

React packager ready.

Error building DepdendencyGraph:
 TypeError: Cannot read property 'root' of null
    at /Users/narendrasisodiya/Desktop/play/nativeTodo/node_modules/react-native/packager/react-packager/src/DependencyResolver/crawlers/index.js:16:84
    at tryCallOne (/Users/narendrasisodiya/Desktop/play/nativeTodo/node_modules/promise/lib/core.js:37:12)
    at /Users/narendrasisodiya/Desktop/play/nativeTodo/node_modules/promise/lib/core.js:103:15
    at flush (/Users/narendrasisodiya/Desktop/play/nativeTodo/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)

============

Let me know what information you need ?

**Comment by nsisodiya** [comment]
My problem was solved by remove macports completely and reinstalling watchman
Thanks
https://github.com/facebook/react-native/issues/1875#issuecomment-141766323
