### ISSUE TITLE
App Crash in Release Build --- AndroidRuntime: FATAL EXCEPTION: create_react_context

### ISSUE THREAD

**Issue by bonti370** [facebook/react-native#41878]
### Description

I am facing crash issue in Release build. Build generation is success and able to install the build but as soon as I open the app it crashes. In debug build its working fine. Only in release mode the crash issue is happening. Can anyone help me here.

React Native Version : 0.72.0
Node version : 18.17.0

### Steps to reproduce

1. react-native run-android --mode release
2. Try to open the installed app
3. It will crash as soon as you open the app

### React Native Version

0.72.0

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text

Binaries:
  Node:
    version: 18.17.0
    path: ~/.nvm/versions/node/v18.17.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/node_modules/.bin/yarn
  npm:
    version: 9.6.7
    path: ~/.nvm/versions/node/v18.17.0/bin/npm

Managers:
  CocoaPods:
    version: 1.12.0
    path: /usr/local/bin/pod

IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  
Android:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
12-08 15:43:02.931 21701 21754 E AndroidRuntime: FATAL EXCEPTION: create_react_context
12-08 15:43:02.931 21701 21754 E AndroidRuntime: Process: com.xx.com
12-08 15:43:02.931 21701 21754 E AndroidRuntime: java.lang.RuntimeException: Unable to load script. Make sure you're either running Metro (run 'npx react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.
12-08 15:43:02.931 21701 21754 E AndroidRuntime:        at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
12-08 15:43:02.931 21701 21754 E AndroidRuntime:        at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:239)
12-08 15:43:02.931 21701 21754 E AndroidRuntime:        at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:29)
12-08 15:43:02.931 21701 21754 E AndroidRuntime:        at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:268)
12-08 15:43:02.931 21701 21754 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1413)
12-08 15:43:02.931 21701 21754 E AndroidRuntime:        at 
```

### Reproducer

https://github.com/react-native-community/reproducer-react-native

**Comment by bonti370** [comment]
> ⚠️	Newer Version of React Native is Available!
> ℹ️	You are on a supported minor version, but it looks like there's a newer patch available - 0.72.7. Please [upgrade](https://reactnative.dev/docs/upgrading) to the highest patch for your minor or latest and verify if the issue persists (alternatively, create a new project and repro the issue in it). If it does not repro, please let us know so we can close out this issue. This helps us ensure we are looking at issues that still exist in the most recent releases.

its not working

**Comment by cortinico** [comment]
@bonti370 can you provide a reproducer?

**Comment by LeQuy-123** [comment]
i also have the same problem when update to version 0.72.7. it only crash in prod, the dev work fine
this is my build.gradle after update
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 24
        compileSdkVersion = 33
        targetSdkVersion = 33
        playServicesVersion = "17.0.0" // or find latest version
        supportLibVersion = "28.0.0"
        androidMapsUtilsVersion = "2.2.2"
        ndkVersion = "23.1.7779620"
        kotlinVersion = '1.6.0'
    }
    repositories {
        google()
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
    }

    dependencies {
        classpath('com.android.tools.build:gradle:7.0.4')
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:4.3.15'
        classpath("com.facebook.react:react-native-gradle-plugin")
    }
} 
```

**Comment by LeQuy-123** [comment]
somehow update getBundleAssetName in MainApplication.java to return index.android.bundle make it work
 @bonti370 make be you should try

 ```
@Override
        protected @Nullable String getBundleAssetName() {
          return "index.android.bundle";
        }
```

**Comment by monilraycha** [comment]
Has anyone solved this issue? I tried downgrading of build-tools-gradle but it is not work for me

**Comment by vlad-audiri** [comment]
Still the case. I am going insane.
