### ISSUE TITLE
Upgraded from 0.72.5 to 0.73.1 - now pods wont install.

### ISSUE THREAD

**Issue by tyhudson** [facebook/react-native#42070]
### Old Version

0.72.5

### New Version

0.73.1

### Description

Pod install is not installing pods. 

### Steps to reproduce

npx pod-install 
-- or --
cd ios
pod install 

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
  OS: macOS 13.4
  CPU: (10) arm64 Apple M1 Pro
  Memory: 53.41 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 19.4.0
    path: ~/.nvm/versions/node/v19.4.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nvm/versions/node/v19.4.0/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/tyhudson/.rubies/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "30"
      - "31"
      - "33"
      - "33"
    Build Tools:
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
    System Images:
      - android-31 | Google APIs ARM 64 v8a
      - android-31 | Google Play ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.18
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/tyhudson/.rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.1
    wanted: 0.73.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
tyhudson@Tys-M1 Tys % npx pod-install
Scanning for pods...
1.14.3
> pod install
Auto-linking React Native modules for target `Tys`: RNCAsyncStorage, RNCMaskedView, RNGestureHandler, RNReanimated, RNScreens, RNVectorIcons, react-native-safe-area-context, and react-native-webview
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
[Codegen] generating an empty RCTThirdPartyFabricComponentsProvider
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
[Codegen] Found rncore
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using release tarball from URL: https://repo1.maven.org/maven2/com/facebook/react/react-native-artifacts/0.73.1/react-native-artifacts-0.73.1-hermes-ios-debug.tar.gz
Downloading dependencies
Installing CocoaAsyncSocket (7.6.5)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.73.1)
Installing FBReactNativeSpec (0.73.1)
Installing Flipper (0.201.0)
Installing Flipper-Boost-iOSX (1.76.0.1.11)
Installing Flipper-DoubleConversion (3.2.0.1)
Installing Flipper-Fmt (7.1.7)
Installing Flipper-Folly (2.6.10)
Installing Flipper-Glog (0.5.0.5)
Installing Flipper-PeerTalk (0.0.4)
Installing FlipperKit (0.201.0)
Installing OpenSSL-Universal (1.1.1100)
Installing RCT-Folly (2022.05.16.00)
Installing RCTRequired (0.73.1)
Installing RCTTypeSafety (0.73.1)
Installing RNCAsyncStorage (1.19.3)
Installing RNCMaskedView (0.3.0)
Installing RNGestureHandler (2.13.1)
Installing RNReanimated (3.5.4)
Installing RNScreens (3.25.0)
Installing RNVectorIcons (10.0.0)
Installing React (0.73.1)
Installing React-Codegen (0.73.1)
Installing React-Core (0.73.1)
Installing React-CoreModules (0.73.1)
Installing React-Fabric (0.73.1)
Installing React-FabricImage (0.73.1)
Installing React-ImageManager (0.73.1)
Installing React-Mapbuffer (0.73.1)
Installing React-NativeModulesApple (0.73.1)
Installing React-RCTActionSheet (0.73.1)
Installing React-RCTAnimation (0.73.1)
Installing React-RCTAppDelegate (0.73.1)
Installing React-RCTBlob (0.73.1)
Installing React-RCTFabric (0.73.1)
Installing React-RCTImage (0.73.1)
Installing React-RCTLinking (0.73.1)
Installing React-RCTNetwork (0.73.1)
Installing React-RCTSettings (0.73.1)
Installing React-RCTText (0.73.1)
Installing React-RCTVibration (0.73.1)
Installing React-callinvoker (0.73.1)
Installing React-cxxreact (0.73.1)
Installing React-debug (0.73.1)
Installing React-graphics (0.73.1)
Installing React-hermes (0.73.1)
Installing React-jserrorhandler (0.73.1)
Installing React-jsi (0.73.1)
Installing React-jsiexecutor (0.73.1)
Installing React-jsinspector (0.73.1)
Installing React-logger (0.73.1)
Installing React-nativeconfig (0.73.1)
Installing React-perflogger (0.73.1)
Installing React-rendererdebug (0.73.1)
Installing React-rncore (0.73.1)
Installing React-runtimeexecutor (0.73.1)
Installing React-runtimescheduler (0.73.1)
Installing React-utils (0.73.1)
Installing ReactCommon (0.73.1)
Installing SocketRocket (0.6.1)
Installing Yoga (1.14.0)
Installing boost (1.83.0)
Installing fmt (6.2.1)
Installing glog (0.3.5)
Installing hermes-engine (0.73.1)
Installing libevent (2.1.12)
Installing react-native-safe-area-context (4.7.2)
Installing react-native-webview (13.6.2)
Generating Pods project
Setting USE_HERMES build settings
Setting REACT_NATIVE build settings
Setting CLANG_CXX_LANGUAGE_STANDARD to c++20 on /Users/tyhudson/projects/Tys/ios/Tys.xcodeproj
Pod install took 20 [s] to run
[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `__apply_Xcode_12_5_M1_post_install_workaround' for #<Pod::Podfile:0x000000013f2bf698>

/Users/tyhudson/projects/Tys/ios/Podfile:60:in `block (3 levels) in from_ruby'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/podfile.rb:196:in `post_install!'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:1013:in `run_podfile_post_install_hook'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:1001:in `block in run_podfile_post_install_hooks'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:149:in `message'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:1000:in `run_podfile_post_install_hooks'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:337:in `block (2 levels) in create_and_save_projects'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:336:in `block in create_and_save_projects'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:315:in `create_and_save_projects'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:307:in `generate_pods_project'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:183:in `integrate'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:170:in `install!'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/command.rb:52:in `run'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/bin/pod:55:in `<top (required)>'
/Users/tyhudson/.rubies/ruby-2.7.6/bin/pod:23:in `load'
/Users/tyhudson/.rubies/ruby-2.7.6/bin/pod:23:in `<main>'
Couldn't install Pods. Updating the Pods project and trying again...
> pod install --repo-update
Auto-linking React Native modules for target `Tys`: RNCAsyncStorage, RNCMaskedView, RNGestureHandler, RNReanimated, RNScreens, RNVectorIcons, react-native-safe-area-context, and react-native-webview
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
[Codegen] generating an empty RCTThirdPartyFabricComponentsProvider
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
[Codegen] Found rncore
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using release tarball from URL: https://repo1.maven.org/maven2/com/facebook/react/react-native-artifacts/0.73.1/react-native-artifacts-0.73.1-hermes-ios-debug.tar.gz
Downloading dependencies
Installing CocoaAsyncSocket (7.6.5)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.73.1)
Installing FBReactNativeSpec (0.73.1)
Installing Flipper (0.201.0)
Installing Flipper-Boost-iOSX (1.76.0.1.11)
Installing Flipper-DoubleConversion (3.2.0.1)
Installing Flipper-Fmt (7.1.7)
Installing Flipper-Folly (2.6.10)
Installing Flipper-Glog (0.5.0.5)
Installing Flipper-PeerTalk (0.0.4)
Installing FlipperKit (0.201.0)
Installing OpenSSL-Universal (1.1.1100)
Installing RCT-Folly (2022.05.16.00)
Installing RCTRequired (0.73.1)
Installing RCTTypeSafety (0.73.1)
Installing RNCAsyncStorage (1.19.3)
Installing RNCMaskedView (0.3.0)
Installing RNGestureHandler (2.13.1)
Installing RNReanimated (3.5.4)
Installing RNScreens (3.25.0)
Installing RNVectorIcons (10.0.0)
Installing React (0.73.1)
Installing React-Codegen (0.73.1)
Installing React-Core (0.73.1)
Installing React-CoreModules (0.73.1)
Installing React-Fabric (0.73.1)
Installing React-FabricImage (0.73.1)
Installing React-ImageManager (0.73.1)
Installing React-Mapbuffer (0.73.1)
Installing React-NativeModulesApple (0.73.1)
Installing React-RCTActionSheet (0.73.1)
Installing React-RCTAnimation (0.73.1)
Installing React-RCTAppDelegate (0.73.1)
Installing React-RCTBlob (0.73.1)
Installing React-RCTFabric (0.73.1)
Installing React-RCTImage (0.73.1)
Installing React-RCTLinking (0.73.1)
Installing React-RCTNetwork (0.73.1)
Installing React-RCTSettings (0.73.1)
Installing React-RCTText (0.73.1)
Installing React-RCTVibration (0.73.1)
Installing React-callinvoker (0.73.1)
Installing React-cxxreact (0.73.1)
Installing React-debug (0.73.1)
Installing React-graphics (0.73.1)
Installing React-hermes (0.73.1)
Installing React-jserrorhandler (0.73.1)
Installing React-jsi (0.73.1)
Installing React-jsiexecutor (0.73.1)
Installing React-jsinspector (0.73.1)
Installing React-logger (0.73.1)
Installing React-nativeconfig (0.73.1)
Installing React-perflogger (0.73.1)
Installing React-rendererdebug (0.73.1)
Installing React-rncore (0.73.1)
Installing React-runtimeexecutor (0.73.1)
Installing React-runtimescheduler (0.73.1)
Installing React-utils (0.73.1)
Installing ReactCommon (0.73.1)
Installing SocketRocket (0.6.1)
Installing Yoga (1.14.0)
Installing boost (1.83.0)
Installing fmt (6.2.1)
Installing glog (0.3.5)
Installing hermes-engine (0.73.1)
Installing libevent (2.1.12)
Installing react-native-safe-area-context (4.7.2)
Installing react-native-webview (13.6.2)
Generating Pods project
Setting USE_HERMES build settings
Setting REACT_NATIVE build settings
Setting CLANG_CXX_LANGUAGE_STANDARD to c++20 on /Users/tyhudson/projects/Tys/ios/Tys.xcodeproj
Pod install took 21 [s] to run
[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `__apply_Xcode_12_5_M1_post_install_workaround' for #<Pod::Podfile:0x0000000138e4b7e8>

/Users/tyhudson/projects/Tys/ios/Podfile:60:in `block (3 levels) in from_ruby'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/podfile.rb:196:in `post_install!'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:1013:in `run_podfile_post_install_hook'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:1001:in `block in run_podfile_post_install_hooks'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:149:in `message'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:1000:in `run_podfile_post_install_hooks'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:337:in `block (2 levels) in create_and_save_projects'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:336:in `block in create_and_save_projects'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:315:in `create_and_save_projects'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:307:in `generate_pods_project'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:183:in `integrate'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:170:in `install!'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/command.rb:52:in `run'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/bin/pod:55:in `<top (required)>'
/Users/tyhudson/.rubies/ruby-2.7.6/bin/pod:23:in `load'
/Users/tyhudson/.rubies/ruby-2.7.6/bin/pod:23:in `<main>'
Couldn't install Pods. Updating the Pods project and trying again...
Command `pod install` failed.
└─ Cause: An error occurred while processing the post-install hook of the Podfile.

undefined method `__apply_Xcode_12_5_M1_post_install_workaround' for #<Pod::Podfile:0x0000000138e4b7e8>

/Users/tyhudson/projects/Tys/ios/Podfile:60:in `block (3 levels) in from_ruby'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/podfile.rb:196:in `post_install!'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:1013:in `run_podfile_post_install_hook'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:1001:in `block in run_podfile_post_install_hooks'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:149:in `message'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:1000:in `run_podfile_post_install_hooks'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:337:in `block (2 levels) in create_and_save_projects'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:336:in `block in create_and_save_projects'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:315:in `create_and_save_projects'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:307:in `generate_pods_project'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:183:in `integrate'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:170:in `install!'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/lib/cocoapods/command.rb:52:in `run'
/Users/tyhudson/.rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.14.3/bin/pod:55:in `<top (required)>'
/Users/tyhudson/.rubies/ruby-2.7.6/bin/pod:23:in `load'
/Users/tyhudson/.rubies/ruby-2.7.6/bin/pod:23:in `<main>'
```

### Reproducer

I don't have a public version of this repo there is no way I could share that. 

### Screenshots and Videos

<img width="1052" alt="image" src="https://github.com/facebook/react-native/assets/118188666/7303f1bd-4e87-458c-9535-0bb5b8386e63">

<img width="1053" alt="image" src="https://github.com/facebook/react-native/assets/118188666/ffa5e44e-b3aa-499e-a10d-2da2497b5748">

If anyone could point me in the right direction that would be great. 

Thank you,
Ty.

**Comment by tyhudson** [comment]
Well it's Ruby gem issues so that is OS.

**Comment by vargajacint** [comment]
Remove the `__apply_Xcode_12_5_M1_post_install_workaround` call from your Pofile

**Comment by r3nya** [comment]
Agreed with [vargajacint](https://github.com/vargajacint), looks like your `Podfile` has `_apply_Xcode_12_5_M1_post_install_workaround`

**Comment by cortinico** [comment]
> Remove the `__apply_Xcode_12_5_M1_post_install_workaround` call from your Pofile

That's the correct answer. Closing

**Comment by tyhudson** [comment]
No, the solution was to return to the other react version.

**Comment by nonam4** [comment]
Also having the same problem after upgrading RN version from 0.72.6 to 0.73.2. Pods are not beeing installed because of `__apply_Xcode_12_5_M1_post_install_workaround` line inside auto generated inside Podfile in expo managed workflow.

**Comment by longnguyen2508** [comment]
This method has already been removed in 0.73

https://github.com/facebook/react-native/commit/0ab8b40fd64ad86b4598293faa0b77e71fc9d349

**Comment by mahesh970098** [comment]
> Remove the `__apply_Xcode_12_5_M1_post_install_workaround` call from your Pofile

Thanks its works !

**Comment by AkilUnik** [comment]
```
post_install do |installer|
    react_native_post_install(installer)
    

    # Added code below
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
```

**Comment by Francis-nova** [comment]
> __apply_Xcode_12_5_M1_post_install_workaround

This works and solves the problem
