### ISSUE TITLE
RCTEventEmitter is deprecated and RCTModernEventEmitter crashing with method overloading unsupported

### ISSUE THREAD

**Issue by vemarav** [facebook/react-native#42761]
### Description

**java.lang.AssertionError: Method overloading is unsupported: com.facebook.react.uimanager.events.RCTModernEventEmitter#receiveEvent**

```
class MyEventEmitter(private val reactContext: ReactContext) {
    private val emitter = reactContext.getJSModule(RCTEventEmitter::class.java)
    private var viewId = View.NO_ID

    fun setViewId(viewId: Int) {
        this.viewId = viewId
    }

    fun onReceiveFrame(bitmap: Bitmap, height: Int) {
        val buffer: ByteBuffer = ByteBuffer.allocateDirect(bitmap.rowBytes * height);
        bitmap.copyPixelsToBuffer(buffer)
        val bufferArray = buffer.array()
        val jsonArray = JSONArray(bufferArray)
        val jsonString = jsonArray.toString(0)
        val data = Arguments.createMap()
        data.putString("frame", jsonString)
        receiveEvent(EVENT_PROP_FRAME_CHANGE, data)
    }

    @Suppress("DEPRECATION")
    private fun receiveEvent(type: String, data: WritableMap) {
        if(viewId != View.NO_ID) {
            emitter.receiveEvent(viewId, type, data)
        }
    }

    companion object {
        private const val EVENT_PROP_FRAME_CHANGE = "onFrameChange"
        val Events = arrayOf(EVENT_PROP_FRAME_CHANGE)
    }
}
```

### Steps to reproduce

1. Add ReactViewManager
2. Add ReactView
3. Assign eventEmitter with context

then this error happens

### React Native Version

0.71.3

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 74.73 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - /opt/homebrew/bin/npm
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.14.3 - /Users/vemarav/.asdf/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK:
      Android NDK: 25.2.9519653
  IDEs:
    Android Studio: 2023.1 AI-231.9392.1.2311.11330709
    Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Stacktrace or Logs

```text
FATAL EXCEPTION: main
                                                                                                    Process: com.gabitrn, PID: 19032
                                                                                                    java.lang.AssertionError: Method overloading is unsupported: com.facebook.react.uimanager.events.RCTModernEventEmitter#receiveEvent
                                                                                                    	at com.facebook.react.bridge.JavaScriptModuleRegistry$JavaScriptModuleInvocationHandler.<init>(JavaScriptModuleRegistry.java:66)
                                                                                                    	at com.facebook.react.bridge.JavaScriptModuleRegistry.getJavaScriptModule(JavaScriptModuleRegistry.java:41)
                                                                                                    	at com.facebook.react.bridge.CatalystInstanceImpl.getJSModule(CatalystInstanceImpl.java:455)
                                                                                                    	at com.facebook.react.bridge.ReactContext.getJSModule(ReactContext.java:160)
                                                                                                    	at com.gabitrn.nativecode.fitbot.react.FitbotEventEmitter.<init>(FitbotEventEmitter.kt:10)
                                                                                                    	at com.gabitrn.nativecode.fitbot.react.ReactFitbotView.<init>(ReactFitbotView.kt:8)
                                                                                                    	at com.gabitrn.nativecode.fitbot.react.ReactFitbotViewManager.createViewInstance(ReactFitbotViewManager.kt:12)
                                                                                                    	at com.gabitrn.nativecode.fitbot.react.ReactFitbotViewManager.createViewInstance(ReactFitbotViewManager.kt:8)
                                                                                                    	at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:183)
                                                                                                    	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:115)
                                                                                                    	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1110)
                                                                                                    	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1081)
                                                                                                    	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
                                                                                                    	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
                                                                                                    	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:792)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8663)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Reproducer

https://github.com/vemarav/react-native-examples

**Comment by cortinico** [comment]
> **java.lang.AssertionError: Method overloading is unsupported: com.facebook.react.uimanager.events.RCTModernEventEmitter#receiveEvent**

What are you trying to achieve?

**Comment by vemarav** [comment]
@cortinico closing this as I have changed implementation

**Comment by vegaro** [comment]
What did you end up doing @cortinico I am facing the same
