### ISSUE TITLE
buildCodegenCLI Error when building from source on Windows

### ISSUE THREAD

**Issue by ipatavatsizz** [facebook/react-native#43087]
### Description

Because of lacking `nmake` on Windows, which is not accessible without using the Developer Command Prompt for VS 2022, I could not build the source. Gradle gives a `> Task :packages:react-native:ReactAndroid:buildCodegenCLI FAILED` error. As a developer who has a history of making Android apps, SDK or env-related variable problems shouldn't be the case. I found that the project uses nmake to build Codegen files in Windows but `nmake` is not accessible. Adding its path to the system envs does not change anything so it raises errors again. What should I do in this situation now?

I just noticed that sometimes using `yarn build` also raises module errors. `yarn prettier` fixes the problem

```
HUAWEI ~\Documents\GitHub\react-native  10.055s  ~ yarn lint
yarn run v1.22.21
$ eslint .

Oops! Something went wrong! :(

ESLint: 8.23.1

C:\Users\HUAWEI\Documents\GitHub\react-native\packages\react-native-codegen\src\parsers\flow\modules\index.js:13
import type {
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1287:20)
    at Module._compile (node:internal/modules/cjs/loader:1339:27)
    at Module._compile (C:\Users\HUAWEI\Documents\GitHub\react-native\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Object.newLoader [as .js] (C:\Users\HUAWEI\Documents\GitHub\react-native\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1234:19)
    at require (node:internal/modules/helpers:176:18)
error Command failed with exit code 2.```

### Steps to reproduce

1. Forked the repository (main branch).
2. Created a new branch and switched.
3. Type `yarn` to cmd.
4. To test the bare project, I typed `yarn android` but it raised a Codegen error on the Windows (11)

### React Native Version

1000.0.0 in packages but I assume it is latest

### Affected Platforms

Build - Windows

### Output of `npx react-native info`

```text
HUAWEI ~\Documents\GitHub\react-native  9.84s  ~ npx react-native info
info Fetching system and libraries information...
System:
  OS: Windows 11 10.0.22631
  CPU: "(12) x64 AMD Ryzen 5 4600H with Radeon Graphics         "
  Memory: 1.08 GB / 7.37 GB
Binaries:
  Node:
    version: 21.5.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.21
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 10.2.5
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "30"
      - "31"
      - "33"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.1
      - 34.0.0
    System Images:
      - android-33 | Google Play Intel x86_64 Atom
    Android NDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: AI-231.9392.1.2311.11330709
  Visual Studio:
    - 17.9.34607.119 (Visual Studio Community 2022)
Languages:
  Java:
    version: 17.0.9
    path: /c/Program Files/Amazon Corretto/jdk17.0.9_8/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
HUAWEI ~\Documents\GitHub\react-native  11.023s  ~ yarn android --verbose
yarn run v1.22.21
$ cd packages/rn-tester && npm run android --verbose
npm verb cli C:\Program Files\nodejs\node.exe C:\Users\HUAWEI\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm info using npm@10.2.5
npm info using node@v21.5.0
npm info found workspace root at C:\Users\HUAWEI\Documents\GitHub\react-native
npm verb title npm run android
npm verb argv "run" "android" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:C:\Users\HUAWEI\AppData\Local\npm-cache\_logs\2024-02-19T09_50_21_823Z-
npm verb logfile C:\Users\HUAWEI\AppData\Local\npm-cache\_logs\2024-02-19T09_50_21_823Z-debug-0.log

> @react-native/tester@0.0.1 android
> react-native run-android --mode HermesDebug

(node:26456) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info Installing the app...
> Task :packages:react-native:ReactAndroid:buildCodegenCLI FAILED

> Task :packages:react-native:ReactAndroid:hermes-engine:downloadHermes UP-TO-DATE
Download https://github.com/facebook/hermes/tarball/main

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.    

For more on this, please refer to https://docs.gradle.org/8.6/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
8 actionable tasks: 3 executed, 5 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':packages:react-native:ReactAndroid:buildCodegenCLI'.
> A problem occurred starting process 'command 'null''

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.

BU�LD FAILED in 4s
error Failed to install the app. Command failed with exit code 1: gradlew.bat installHermesDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':packages:react-native:ReactAndroid:buildCodegenCLI'. > A problem occurred starting process 'command 'null'' * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Get more help at https://help.gradle.org. BU�LD FAILED in 4s.
info Run CLI with --verbose flag for more details.
npm ERR! Lifecycle script `android` failed with error: 
npm ERR! Error: command failed
npm ERR!   in workspace: @react-native/tester@0.0.1
npm ERR!   at location: C:\Users\HUAWEI\Documents\GitHub\react-native\packages\rn-tester
npm verb exit 1
npm verb code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproducer

https://github.com/react-native-community/reproducer-react-native

### Screenshots and Videos

![image](https://github.com/facebook/react-native/assets/37545799/f4edb506-730e-46fc-a795-4955ad532f83)
![image](https://github.com/facebook/react-native/assets/37545799/f430244c-d426-4bc8-a4a5-e9f086fe1693)
![image](https://github.com/facebook/react-native/assets/37545799/12ea0972-d3f0-4a3b-b475-795cc6534aae)

**Comment by cortinico** [comment]
> Because of lacking `nmake` on Windows, which is not accessible without using the Developer Command Prompt for VS 2022, I could not build the source

@ipatavatsizz  You need to use the Developer Command Prompt for VS 2022 to build from source, that's a requirement if you're using Windows to build

**Comment by ipatavatsizz** [comment]
```
PS C:\users\HUAWEI\Documents\GitHub\react-native> nmake

Microsoft (R) Program Maintenance Utility Version 14.39.33519.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1064: MAKEFILE not found and no target specified
Stop.
PS C:\users\HUAWEI\Documents\GitHub\react-native> yarn android --stacktrace
yarn run v1.22.21
$ cd packages/rn-tester && npm run android --stacktrace

> @react-native/tester@0.0.1 android
> react-native run-android --mode HermesDebug

(node:25788) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info A dev server is already running for this project on port 8081.
info Installing the app...
> Task :packages:react-native:ReactAndroid:buildCodegenCLI FAILED

> Task :packages:react-native:ReactAndroid:hermes-engine:downloadHermes UP-TO-DATE
Download https://github.com/facebook/hermes/tarball/main

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.6/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
8 actionable tasks: 3 executed, 5 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':packages:react-native:ReactAndroid:buildCodegenCLI'.
> A problem occurred starting process 'command 'null''

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.

BU�LD FAILED in 3s
error Failed to install the app. Command failed with exit code 1: gradlew.bat installHermesDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':packages:react-native:ReactAndroid:buildCodegenCLI'. > A problem occurred starting process 'command 'null'' * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Get more help at https://help.gradle.org. BU�LD FAILED in 3s.
info Run CLI with --verbose flag for more details.
npm ERR! Lifecycle script `android` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @react-native/tester@0.0.1
npm ERR!   at location: C:\Users\HUAWEI\Documents\GitHub\react-native\packages\rn-tester
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Still getting the same error. I could run the Developer Command Prompt for VS 2022 containing nmake executable but the twist is Gradle cannot do the same I guess.

**Comment by cortinico** [comment]
> Still getting the same error. I could run the Developer Command Prompt for VS 2022 containing nmake executable but the twist is Gradle cannot do the same I guess.

I see. Sadly we the support for building from source on Windows is really limited. It used to work for a bit, but as we're all developing on MacOS/Linux, we don't have the capacity to fix and support this long term. 

We'll be happy to receive a PR that fixes the problems for building from source on windows if anyone is interested.

**Comment by ipatavatsizz** [comment]
I believe there is a problem with the way the React Native Gradle plugin gets the command prompt. Maybe it is getting the standard cmd, not the developer variant so nmake is not found. In some desktops, nmake and other developer tools might be added to the environment but it is not suggested to use these tools outside the developer console by Windows at [here](https://learn.microsoft.com/en-us/cpp/build/reference/nmake-reference?view=msvc-170#:~:text=NMAKE%20must%20run%20in%20a%20Developer%20Command%20Prompt%20window.). If I can fix the problem, I will inform as soon as possible.
