### ISSUE TITLE
Collision during packer startup using 0.15.0

### ISSUE THREAD

**Issue by sethx** [facebook/react-native#4370]
Hello, 
after updating to 0.15.0 i get this:

Error building DepdendencyGraph:
 Error: Naming collision detected: /Users/d/Desktop/radar/node_modules/react-native/Libraries/vendor/core/immediate/setImmediate.js collides with /Users/d/Desktop/radar/node_modules/react-native/Libraries/vendor/react/core/clamp.js
    at HasteMap._updateHasteMap (/Users/d/Desktop/radar/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:123:13)
    at /Users/d/Desktop/radar/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:95:28
    at tryCallOne (/Users/d/Desktop/radar/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/d/Desktop/radar/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/d/Desktop/radar/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
Process terminated. Press <enter> to close the window

**Comment by christopherdro** [comment]
@sethx Could you try taking a look at issue #3558 and see if any of the answers posted help solve your problem? Thanks!

**Comment by sethx** [comment]
@christopherdro yes, thanks! `./node_modules/react-native/packager/packager.sh --resetCache` fixed it for me

**Comment by christopherdro** [comment]
:+1:

**Comment by QuantumInformation** [comment]
![image](https://cloud.githubusercontent.com/assets/216566/11452719/f2920532-95e9-11e5-81fa-2980ab7b769f.png)

**Comment by QuantumInformation** [comment]
npm prune fixed it for me
