### ISSUE TITLE
how import js module using npm

### ISSUE THREAD

**Issue by zrhzhouronghui** [facebook/react-native#4383]
i have a question here, i want import a wrapper about protocol buffer,here is this git :https://github.com/dcodeIO/protobuf.js/wiki/Installation,i install it using  
npm install protobufjs
/Users/ronghui/Desktop/ReactNative/APRNCore_0_15_0/node_modules/react-native/node_modules/protobufjs
,here is the full path, when i require it 
var protobuf = require('./node_modules/react-native/node_modules/protobufjs')
but i got below errors, can someone help me?
+ react-native bundle --entry-file index.ios.js --platform ios --dev true --bundle-output /Users/ronghui/Library/Developer/Xcode/DerivedData/APRNCore_0_15_0-gbizrllfunlwznhbngwepnjazfqm/Build/Products/Debug-iphonesimulator/APRNCore_0_15_0.app/main.jsbundle --assets-dest /Users/ronghui/Library/Developer/Xcode/DerivedData/APRNCore_0_15_0-gbizrllfunlwznhbngwepnjazfqm/Build/Products/Debug-iphonesimulator/APRNCore_0_15_0.app
bundle: Created ReactPackager
uncaught error Error: UnableToResolveError: Unable to resolve module fs from /Users/ronghui/Desktop/ReactNative/APRNCore_0_15_0/node_modules/react-native/node_modules/protobufjs/dist/ProtoBuf.js: Invalid directory /Users/node_modules/fs
    at /Users/ronghui/Desktop/ReactNative/APRNCore_0_15_0/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/ResolutionRequest.js:323:15
    at tryCallOne (/Users/ronghui/Desktop/ReactNative/APRNCore_0_15_0/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/ronghui/Desktop/ReactNative/APRNCore_0_15_0/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/ronghui/Desktop/ReactNative/APRNCore_0_15_0/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
See logs /var/folders/vl/fm6gkbrx1f5b8_yrnfpkyjv00000gn/T/react-packager.log
    at SocketClient._handleMessage (/Users/ronghui/Desktop/ReactNative/APRNCore_0_15_0/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketClient.js:131:23)
    at BunserBuf.<anonymous> (/Users/ronghui/Desktop/ReactNative/APRNCore_0_15_0/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketClient.js:52:42)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/ronghui/Desktop/ReactNative/APRNCore_0_15_0/node_modules/react-native/node_modules/bser/index.js:289:10)
    at /Users/ronghui/Desktop/ReactNative/APRNCore_0_15_0/node_modules/react-native/node_modules/bser/index.js:244:12
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
Command /bin/sh failed with exit code 1

**Comment by satya164** [comment]
@zrhzhouronghui You're using a module which uses node native modules. It won't work under React Native.

**Comment by satya164** [comment]
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

If you think StackOverflow works for you please consider posting there instead and closing this issue.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

**Comment by satya164** [comment]
@zrhzhouronghui You're using a module which uses node native modules. It won't work under React Native.
