### ISSUE TITLE
Headless JS fails after 1 minute of usage

### ISSUE THREAD

**Issue by friyiajr** [facebook/react-native#43950]
### Description

I have an application where I am trying to wake up the app to send a notification every 30 seconds. It will send notifications twice then after that fail with an error. 

I get an almost identical warning about starting a service in the background if I use this code instead of the broadcast receiver I tried to use

https://github.com/friyiajr/HeadlessJsReproducer/blob/main/android/app/src/main/java/com/wa2goose/BackgroundBLE/MainActivity.kt#L48

### Steps to reproduce

Ignore anything related to BLE, it doesn't affect this bug whatsoever. The problem is that the Android app won't wake up to send the actual notification

1. run `npx expo run:android --device` and choose your physical android device
2. Open the app and say yes to the permission for push notifications
3. Background the app but don't kill it
4. Watch a Push notification come in and clear it
5. Watch a Second Push notification come in and clear it
6. No notifications will surface after this

### React Native Version

0.73.6

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
  OS: macOS 14.3.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 105.41 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.4
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.03.18.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /Users/danielfriyia/.rvm/gems/ruby-3.0.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11567975
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 3.0.0
    path: /Users/danielfriyia/.rvm/rubies/ruby-3.0.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
2024-04-06 14:01:25.727 13792-13792 AndroidRuntime          com.wa2goose.BackgroundBLE           E  FATAL EXCEPTION: main
                                                                                                    Process: com.wa2goose.BackgroundBLE, PID: 13792
                                                                                                    java.lang.RuntimeException: Unable to start receiver com.wa2goose.BackgroundBLE.PulseReceiver: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.wa2goose.BackgroundBLE/.PulseCheck (has extras) }: app is in background uid UidRecord{dc8cd64 u0a336 RCVR bg:+1m53s629ms idle change:uncachedprocstateprocadj procs:0 seq(69826,68965)} caps=------
                                                                                                    	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4672)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2357)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8501)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
                                                                                                    Caused by: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.wa2goose.BackgroundBLE/.PulseCheck (has extras) }: app is in background uid UidRecord{dc8cd64 u0a336 RCVR bg:+1m53s629ms idle change:uncachedprocstateprocadj procs:0 seq(69826,68965)} caps=------
                                                                                                    	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1946)
                                                                                                    	at android.app.ContextImpl.startService(ContextImpl.java:1901)
                                                                                                    	at android.content.ContextWrapper.startService(ContextWrapper.java:826)
                                                                                                    	at android.content.ContextWrapper.startService(ContextWrapper.java:826)
                                                                                                    	at com.wa2goose.BackgroundBLE.PulseReceiver.onReceive(PulseReceiver.java:21)
                                                                                                    	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4663)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2357) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232) 
                                                                                                    	at android.os.Looper.loop(Looper.java:317) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8501) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878) 
```

### Reproducer

https://github.com/friyiajr/HeadlessJsReproducer

### Screenshots and Videos

https://github.com/facebook/react-native/assets/48887088/fa81efb9-894c-4a87-9756-74df932a88c2

**Comment by cortinico** [comment]
Thanks for providing a reproducer @friyiajr this really helps to understand where is the problem.

The problem is here:
https://github.com/friyiajr/HeadlessJsReproducer/blob/c09cfc83df5e1f509c50111a77d58dac15f2b93d/android/app/src/main/java/com/wa2goose/BackgroundBLE/PulseReceiver.java#L21

For Android 8.0 devices, you have to call `startForegroundService`, as suggested here:
https://stackoverflow.com/a/47654126

**Comment by friyiajr** [comment]
Thanks @cortinico would it make sense to update the React-Native documentation on this since the docs say?

> Headless JS is a way to run tasks in JavaScript while your app is in the background. It can be used, for example, to sync fresh data, handle push notifications, or play music.

And this is impossible on modern Android without using `startForegroundService`.

I haven't had a chance to look into this much yet. But it does seem like it has a much different set or rituals and boilerplate then just calling `startService` does.

**Comment by cortinico** [comment]
> And this is impossible on modern Android without using `startForegroundService`.

I don't understand why you say that the documentation needs to be updated. Android has changed and requires different APIs to do computation in the background but the statement about about Headless JS still holds true

**Comment by friyiajr** [comment]
First, thanks for being so responsive on this! I really appreciate it. 

The example provided [in the documentation](https://reactnative.dev/docs/headless-js-android#the-platform-api) uses `startService` in this section instead of `startForegroundService`. If you want to do what the first sentence of the article is describing which is:

> Headless JS is a way to run tasks in JavaScript while your app is in the background. It can be used, for example, to sync fresh data, handle push notifications, or play music.

This is not possible unless you update the example to use `startForegroundService`. 

I don't have as much context as others who have come from a pure Android background and I am sure I am not alone in this. Its very easy for others who've done mostly React-Native or Expo to follow this documentation as-is and come away with the impression that Headless JS has regressed or doesn't work because they are trying to use `startService` like the documentation tells them to do.

To do exactly what is described in that first sentence there are a lot of permissions to add and steps to take in your Android code. See: https://medium.com/@domen.lanisnik/guide-to-foreground-services-on-android-9d0127dc8f9a#:~:text=To%20make%20the%20service%20run,work%20done%20by%20the%20service

**Comment by cortinico** [comment]
> First, thanks for being so responsive on this! I really appreciate it.

<3

> The example provided [in the documentation](https://reactnative.dev/docs/headless-js-android#the-platform-api) uses `startService` in this section instead of `startForegroundService`. If you want to do what the first sentence of the article is describing which is:

Ah yes you're right, the snippets needs to be adapted. Don't you mind opening an issue on https://github.com/facebook/react-native-website/issues/ ?
If you're up also for sending a PR that updates them we can take the conversation forward over there

**Comment by friyiajr** [comment]
Sounds good to me! I'll create an issue later today. I am going to start working on a documentation update soon! This sounds like fun. 

It will probably take a few weeks since I need to figure this out myself 😅 and this is a side project. If you feel like this is easy for you though and you want to pick it up ahead of me I won't be offended.

**Comment by friyiajr** [comment]
So @cortinico it looks like this could be an actual bug in React-Native after all. I made changes so that I could use `startForegroundService` instead of `startService`. And the `HeadlessJsTaskService` no longer wakes up the JavaScript code at all. 

I created a [new branch and have a diff here](https://github.com/friyiajr/HeadlessJsReproducer/compare/main...some-important-items) that hopefully is useful. It could be a code error on my part or a lack of knowledge in Android. Please let me know.

**Comment by cortinico** [comment]
> android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.wa2goose.BackgroundBLE/.PulseCheck

This is again an issue with Android and not an issue with React Native itself.
See here for more context: https://stackoverflow.com/a/72131422

**Comment by friyiajr** [comment]
Thanks @cortinico, I think I'll just create that documentation issue at this point. I won't be the one to pick it up though.

I've spent probably 15 hours on this now and I feel like I am not getting anywhere 😅. I don't think I am going to figure this out on my own. The Android solutions I keep seeing are increasingly complex and I can't figure out how to integrate them all.  

Thank you for your patience though, sorry I couldn't help more. Here is the issue: https://github.com/facebook/react-native-website/issues/4079

**Comment by mensonones** [comment]
Hey, @cortinico! 

About HeadlessJsTaskService and Service, its possible create Service running in Background  with TurboModules? 

I found nothing about the new architecture
