### ISSUE TITLE
[0.74.0] AppState module has an error on android

### ISSUE THREAD

**Issue by NiuGuohui** [facebook/react-native#44251]
### Description

After I migrated to 0.74, I found that Logcat was reporting an error: 
``
Unhandled SoftException
com. Facebook. react. bridge ReactNoCrashSoftException: Tried to access onWindowFocusChange while context is not ready
``

### Steps to reproduce

1. `index.js`
AppState.addEventListener('change', state => {
  console.log(state);
});
2. run app (android)
3. make app to the background

### React Native Version

0.74.0

### Affected Platforms

Runtime - Android, Build - MacOS

### Areas

JSI - Javascript Interface, Bridgeless - The New Initialization Flow

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.3.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 2.73 GB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v18.19.0/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v18.19.0/bin/npm
  Watchman:
    version: 2021.11.15.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.10.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 21.4
      - iOS 16.0
      - macOS 12.3
      - tvOS 16.0
      - watchOS 9.0
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11567975
  Xcode:
    version: 14.0.1/14A400
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found


(Because I am using PNPM, it shows none `Not found`)
```

### Stacktrace or Logs

```text
ReactHost{0}.onWindowFocusChange(hasFocus = "false")
Unhandled SoftException
                                                                                                    com.facebook.react.bridge.ReactNoCrashSoftException: Tried to access onWindowFocusChange while context is not ready
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.onWindowFocusChange(ReactHostImpl.java:664)
                                                                                                    	at com.facebook.react.ReactDelegate.onWindowFocusChanged(ReactDelegate.java:193)
                                                                                                    	at com.facebook.react.ReactActivityDelegate.onWindowFocusChanged(ReactActivityDelegate.java:175)
                                                                                                    	at com.facebook.react.ReactActivity.onWindowFocusChanged(ReactActivity.java:128)
                                                                                                    	at androidx.appcompat.view.WindowCallbackWrapper.onWindowFocusChanged(WindowCallbackWrapper.java:125)
                                                                                                    	at com.android.internal.policy.DecorView.onWindowFocusChanged(DecorView.java:2422)
                                                                                                    	at android.view.View.dispatchWindowFocusChanged(View.java:15279)
                                                                                                    	at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1566)
                                                                                                    	at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:4981)
                                                                                                    	at android.view.ViewRootImpl.access$1400(ViewRootImpl.java:270)
                                                                                                    	at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(ViewRootImpl.java:7115)
                                                                                                    	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:7009)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:117)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:293)
                                                                                                    	at android.app.ActivityThread.loopProcess(ActivityThread.java:9961)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9950)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)
```

### Reproducer

none

**Comment by cortinico** [comment]
@NiuGuohui Just to confirm, you're on New Architecture right?

**Comment by NiuGuohui** [comment]
> @NiuGuohui Just to confirm, you're on New Architecture right?

I tried again. Now AppState seems to be working properly. But I found that this error still occurs when enable bridgeless, and after disabled bridgeless, it no longer reports an error.

**Comment by alanjhughes** [comment]
@cortinico can confirm that I have run into this. I meant to reach out about it but I wanted to investigate myself first as it doesn't repro reliably and I'm not sure of the cause

**Comment by cortinico** [comment]
> @cortinico can confirm that I have run into this. I meant to reach out about it but I wanted to investigate myself first as it doesn't repro reliably and I'm not sure of the cause

Great thanks for confirming it 👍

**Comment by cortinico** [comment]
@alanjhughes @NiuGuohui can we isolate what's the problem here?

I've tried to reproduce, and yes, the:
```
Unhandled SoftException
  com.facebook.react.bridge.ReactNoCrashSoftException: Tried to access onWindowFocusChange while context is not ready
```

gets fired but that's unrelated. I was able to successfully use the `AppState` API with the provided reproducer.

https://github.com/facebook/react-native/assets/3001957/5d544f60-81d1-44f1-bee2-04fb6f86351f

**Comment by NiuGuohui** [comment]
> @alanjhughes @NiuGuohui can we isolate what's the problem here?
> 
> I've tried to reproduce, and yes, the:
> 
> ```
> Unhandled SoftException
>   com.facebook.react.bridge.ReactNoCrashSoftException: Tried to access onWindowFocusChange while context is not ready
> ```
> 
> gets fired but that's unrelated. I was able to successfully use the `AppState` API with the provided reproducer.
> 
>  repro.mov

I think `AppState` works fine now.
But the error still occurred.
I tried to open ReactHostImpl.class (the built-in decompilation tool in Android Studio) and noticed that it seems not quite consistent with the [code in the repository](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/ReactHostImpl.java#L687). I'm not sure if this decompiled code is reliable for reference.
This is my decompiled ReactHostImpl.class content:
```
@ThreadConfined("UI")
  public void onWindowFocusChange(boolean hasFocus) {
    String method = "onWindowFocusChange(hasFocus = \"" + hasFocus + "\")";
    this.log(method);
    ReactContext currentContext = this.getCurrentReactContext();
    if (currentContext != null) {
      currentContext.onWindowFocusChange(hasFocus);
    }

    ReactSoftExceptionLogger.logSoftException("ReactHost", new ReactNoCrashSoftException("Tried to access onWindowFocusChange while context is not ready"));
  }
```

**Comment by cortinico** [comment]
> I tried to open ReactHostImpl.class (the built-in decompilation tool in Android Studio) and noticed that it seems not quite consistent with the [code in the repository](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/ReactHostImpl.java?rgh-link-date=2024-04-26T01%3A13%3A10Z#L687). I'm not sure if this decompiled code is reliable for reference.

That's because you're looking at the class in `main` while you should be looking at the same class on the 0.74-stable branch:

https://github.com/facebook/react-native/blob/0.74-stable/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/ReactHostImpl.java

@alanjhughes what was the error you were facing?

**Comment by alanjhughes** [comment]
@cortinico its this error but it's only happening on app launch and not every time. Kudo reproduced in a RN project without expo. I'll speak to him today and see if he found a reliable way to reproduce.

**Comment by NiuGuohui** [comment]
> > I tried to open ReactHostImpl.class (the built-in decompilation tool in Android Studio) and noticed that it seems not quite consistent with the [code in the repository](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/ReactHostImpl.java?rgh-link-date=2024-04-26T01%3A13%3A10Z#L687). I'm not sure if this decompiled code is reliable for reference.
> 
> That's because you're looking at the class in `main` while you should be looking at the same class on the 0.74-stable branch:
> 
> https://github.com/facebook/react-native/blob/0.74-stable/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/ReactHostImpl.java

So, should an `else` or `return` statement be added to line 664 in [0.74-stable ReactHostImpl.java](https://github.com/facebook/react-native/blob/0.74-stable/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/ReactHostImpl.java#L663)？

**Comment by cortinico** [comment]
> > > I tried to open ReactHostImpl.class (the built-in decompilation tool in Android Studio) and noticed that it seems not quite consistent with the [code in the repository](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/ReactHostImpl.java?rgh-link-date=2024-04-26T09%3A08%3A54Z#L687). I'm not sure if this decompiled code is reliable for reference.
> > 
> > 
> > That's because you're looking at the class in `main` while you should be looking at the same class on the 0.74-stable branch:
> > [`0.74-stable`/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/ReactHostImpl.java](https://github.com/facebook/react-native/blob/0.74-stable/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/ReactHostImpl.java?rgh-link-date=2024-04-26T09%3A08%3A54Z)
> 
> So, should an `else` or `return` statement be added to line 664 in [0.74-stable ReactHostImpl.java](https://github.com/facebook/react-native/blob/0.74-stable/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/ReactHostImpl.java?rgh-link-date=2024-04-26T09%3A08%3A54Z#L663)？

We could pick https://github.com/facebook/react-native/commit/ac3261ff608768ff43736b413c5a5ad67668af61 on the 0.74 release branch that would solve this

**Comment by bennysalewski** [comment]
It seems this issue is still present in 0.74.1 (tried also 0.74.1-rc.0)

> Unhandled SoftException
                                                                                                    com.facebook.react.bridge.ReactNoCrashSoftException: Tried to access onWindowFocusChange while context is not ready
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.onWindowFocusChange(ReactHostImpl.java:664)
                                                                                                    	at com.facebook.react.ReactDelegate.onWindowFocusChanged(ReactDelegate.java:193)
                                                                                                    	at com.facebook.react.ReactActivityDelegate.onWindowFocusChanged(ReactActivityDelegate.java:175)
                                                                                                    	at com.facebook.react.ReactActivity.onWindowFocusChanged(ReactActivity.java:128)
                                                                                                    	at androidx.appcompat.view.WindowCallbackWrapper.onWindowFocusChanged(WindowCallbackWrapper.java:125)
                                                                                                    	at com.android.internal.policy.DecorView.onWindowFocusChanged(DecorView.java:1810)
                                                                                                    	at android.view.View.dispatchWindowFocusChanged(View.java:16171)
                                                                                                    	at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1510)
                                                                                                    	at android.view.ViewRootImpl.dispatchFocusEvent(ViewRootImpl.java:4283)
                                                                                                    	at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:4187)
                                                                                                    	at android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged(Unknown Source:0)
                                                                                                    	at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(ViewRootImpl.java:6315)
                                                                                                    	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:6223)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8501)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by duguyihou** [comment]
I see the same error in 0.74.1 as well.
```
  Unable to match the desired swap behavior.
  Unable to match the desired swap behavior.
  Unhandled SoftException
  com.facebook.react.bridge.ReactNoCrashSoftException: Tried to access onWindowFocusChange while context is not ready
	at com.facebook.react.runtime.ReactHostImpl.onWindowFocusChange(ReactHostImpl.java:674)
	at com.facebook.react.ReactDelegate.onWindowFocusChanged(ReactDelegate.java:194)
	at com.facebook.react.ReactActivityDelegate.onWindowFocusChanged(ReactActivityDelegate.java:175)
	at com.facebook.react.ReactActivity.onWindowFocusChanged(ReactActivity.java:128)
	at androidx.appcompat.view.WindowCallbackWrapper.onWindowFocusChanged(WindowCallbackWrapper.java:125)
	at com.android.internal.policy.DecorView.onWindowFocusChanged(DecorView.java:1788)
	at android.view.View.dispatchWindowFocusChanged(View.java:15933)
	at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1509)
	at android.view.ViewRootImpl.dispatchFocusEvent(ViewRootImpl.java:4059)
	at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:3963)
	at android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged(Unknown Source:0)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(ViewRootImpl.java:5954)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:5862)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
  [0518/133752.908692:ERROR:variations_seed_loader.cc(37)] Seed missing signature.
```

**Comment by C2418M31** [comment]
I have the same issue but this is from RN as AAR and uploaded to the Android native

`Unhandled SoftException
                                                                                       com.facebook.react.bridge.ReactNoCrashSoftException: Tried to access onWindowFocusChange while context is not ready
                                                                                       	at com.facebook.react.runtime.ReactHostImpl.onWindowFocusChange(ReactHostImpl.java:674)
                                                                                       	at com.facebook.react.ReactDelegate.onWindowFocusChanged(ReactDelegate.java:194)
                                                                                       	at com.facebook.react.ReactActivityDelegate.onWindowFocusChanged(ReactActivityDelegate.java:175)
                                                                                       	at com.facebook.react.ReactActivity.onWindowFocusChanged(ReactActivity.java:128)
                                                                                       	at androidx.appcompat.view.WindowCallbackWrapper.onWindowFocusChanged(WindowCallbackWrapper.java:125)
                                                                                       	at com.android.internal.policy.DecorView.onWindowFocusChanged(DecorView.java:2320)
                                                                                       	at android.view.View.dispatchWindowFocusChanged(View.java:16490)
                                                                                       	at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1517)
                                                                                       	at android.view.ViewRootImpl.dispatchFocusEvent(ViewRootImpl.java:5003)
                                                                                       	at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:4887)
                                                                                       	at android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged(Unknown Source:0)
                                                                                       	at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(ViewRootImpl.java:7150)
                                                                                       	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:7051)
                                                                                       	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                       	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                       	at android.os.Looper.loop(Looper.java:319)
                                                                                       	at android.app.ActivityThread.main(ActivityThread.java:8893)
                                                                                       	at java.lang.reflect.Method.invoke(Native Method)
                                                                                       	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                                                                                       	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)`

**Comment by NiuGuohui** [comment]
https://github.com/facebook/react-native/commit/ac3261ff608768ff43736b413c5a5ad67668af61
I think it will be merge in the future.

**Comment by cortinico** [comment]
This will be picked in 0.74.2 here:
- https://github.com/reactwg/react-native-releases/issues/291

**Comment by raphaeladams** [comment]
@cortinico I'm using `"react-native": "0.74.2"` and still seeing this error. Are there any other dependencies that could cause this?

```
E  Unhandled SoftException
com.facebook.react.bridge.ReactNoCrashSoftException: Tried to access onWindowFocusChange while context is not ready
	at com.facebook.react.runtime.ReactHostImpl.onWindowFocusChange(ReactHostImpl.java:675)
	at com.facebook.react.ReactDelegate.onWindowFocusChanged(ReactDelegate.java:194)
	at com.facebook.react.ReactActivityDelegate.onWindowFocusChanged(ReactActivityDelegate.java:175)
	at com.facebook.react.ReactActivity.onWindowFocusChanged(ReactActivity.java:128)
	at androidx.appcompat.view.WindowCallbackWrapper.onWindowFocusChanged(WindowCallbackWrapper.java:125)
	at com.android.internal.policy.DecorView.onWindowFocusChanged(DecorView.java:2767)
	at android.view.View.dispatchWindowFocusChanged(View.java:15880)
	at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1518)
	at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:4713)
	at android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged(Unknown Source:0)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(ViewRootImpl.java:6866)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:6775)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by cortinico** [comment]
> and still seeing this error

Do you mean you see the app crashing or is it appearing in the log?

**Comment by raphaeladams** [comment]
> > and still seeing this error
> 
> Do you mean you see the app crashing or is it appearing in the log?

@cortinico the error appears in the log, and the app just shows a blank screen and fails to render its loading screen, but does not crash.

Let me know if it's expected that this error will still appear in logs without crashing. That could indicate some other issue in my code that isn't related to this.

**Comment by cortinico** [comment]
> Let me know if it's expected that this error will still appear in logs without crashing. That could indicate some other issue in my code that isn't related to this.

It's expected that it appears in the logs, as we're raising a soft exception. It shouldn't cause your app to crash though

**Comment by NetPumi2** [comment]
i still have it on RN 0.76.1

**Comment by yyyyyyyysssss** [comment]
i still have it on RN 0.76.3

**Comment by Deatsilence** [comment]
I still have the error on RN 0.76.3, I can not understand the react native team. How can they release that while the versions has lots of problem ? isn't there any QA team ?

**Comment by munkhorgil** [comment]
Hi @cortinico getting the same error on v0.76.3 is there any workaround for now?

**Comment by ndu-aspira** [comment]
facing this issue on RN 0.74.5

**Comment by Qdafengzi** [comment]
Android crash ，new  architecture ,  What can I do ?
"react-native": "0.76.6"

**Comment by grkemtneri** [comment]
i still have it on RN 0.77.1

**Comment by husnaintahir** [comment]
Still an on RN 0.78

**Comment by matildatrodin** [comment]
I still have this issue on 0.77.1. I changed 

`newArchEnabled=false`

in `gradle.properties` which at least lets me launch the app now without crashing on android. But the app is now slow and freezes in certain views with a lot of computations.

**Comment by tominou** [comment]
Still have it on 0.79.2 with newArchEnabled

**Comment by cobasajaxinpho** [comment]
i use 0.80.0, still same issue with archEnable=true

**Comment by LahmerIlyas** [comment]
I experienced the same issue, and when I cleaned/rebuilt the app on Android, it got fixed.

**Comment by Josh2941** [comment]
I am getting this on 0.81.0 as well on Android in Production. And my App is on New Architecture.

**Comment by bijia351** [comment]
Still exist

**Comment by amir18160** [comment]
i have the same issue on "react-native": "0.79.5".
any solution yet?

**Comment by CMLCNL** [comment]
still facing same issue. any update for this issue

**Comment by DoHue97** [comment]
Hello All, any new for this issue, im using react-native 0.77.3. When open the app, app crashed

com.facebook.react.bridge.ReactNoCrashSoftException: raiseSoftException(onWindowFocusChange(hasFocus = "true")): Tried to access onWindowFocusChange while context is not ready
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.raiseSoftException(ReactHostImpl.java:1025)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.raiseSoftException(ReactHostImpl.java:1018)
                                                                                                    	at com.facebook.react.runtime.ReactHostImpl.onWindowFocusChange(ReactHostImpl.java:790)
                                                                                                    	at com.facebook.react.ReactDelegate.onWindowFocusChanged(ReactDelegate.java:199)
                                                                                                    	at com.facebook.react.ReactActivityDelegate.onWindowFocusChanged(ReactActivityDelegate.java:207)
                                                                                                    	at com.facebook.react.ReactActivity.onWindowFocusChanged(ReactActivity.java:138)
                                                                                                    	at androidx.appcompat.view.WindowCallbackWrapper.onWindowFocusChanged(WindowCallbackWrapper.java:124)
                                                                                                    	at com.android.internal.policy.DecorView.onWindowFocusChanged(DecorView.java:1818)
                                                                                                    	at android.view.View.dispatchWindowFocusChanged(View.java:16952)
                                                                                                    	at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1530)
                                                                                                    	at android.view.ViewRootImpl.dispatchFocusEvent(ViewRootImpl.java:4872)
                                                                                                    	at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:4776)
                                                                                                    	at android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged(Unknown Source:0)
                                                                                                    	at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(ViewRootImpl.java:7016)
                                                                                                    	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:6926)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:248)
                                                                                                    	at android.os.Looper.loop(Looper.java:338)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9067)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)

**Comment by robinlindhout** [comment]
We have the same problem on latest expo version and new arch enabled..

**Comment by sahajarora1286** [comment]
Could we please get a resolution to this? I upgraded to 0.81.4 from 0.74.0 and I am now getting this error (wasn't getting it before the upgrade).

**Comment by vijendrakiko** [comment]
I have same error please share any solution

**Comment by lordkiz** [comment]
Still an issue on 0.82.0

**Comment by jamesmcn1** [comment]
Yup i'm also getting this after upgrade from 0.76.9 to 0.81.5. Might be time to reopen this issue?

**Comment by ZandercraftGames** [comment]
Getting this issue on 0.82.1 with new architecture.

EDIT: For the time being, to prevent crashes, I've added the following to my `MainActivity.kt`.
```
override fun onWindowFocusChanged(hasFocus: Boolean) {
    try {
      super.onWindowFocusChanged(hasFocus)
    } catch (e: Exception) {
      // This is to prevent a crash when the window focus changes before the React context is ready.
    }
  }
```

**Comment by YueLiXing** [comment]
try "react-native-svg": "15.15.0"

**Comment by guistrutzki** [comment]
For me, after upgrading from Expo 52 to 53, and enabled new arch, it starts to crash only in Android < 9.
I believe it can be some compatibility issue

Android 8.1 Emulator:

<img width="1793" height="898" alt="Image" src="https://github.com/user-attachments/assets/7f483159-76ec-436b-b576-cf21494fbd00" />

Android 15 Emulator:

<img width="1810" height="898" alt="Image" src="https://github.com/user-attachments/assets/8976cedb-1d45-432f-86ed-066fcabbb06c" />

**Comment by yagiz2000** [comment]
still happens

**Comment by mendrixsebas** [comment]
> try "react-native-svg": "15.15.0"

@YueLiXing thanks, this fixed it for me

**Comment by oluyoung** [comment]
> Getting this issue on 0.82.1 with new architecture.
> 
> EDIT: For the time being, to prevent crashes, I've added the following to my `MainActivity.kt`.
> 
> ```
> override fun onWindowFocusChanged(hasFocus: Boolean) {
>     try {
>       super.onWindowFocusChanged(hasFocus)
>     } catch (e: Exception) {
>       // This is to prevent a crash when the window focus changes before the React context is ready.
>     }
>   }
> ```

Thank you @ZandercraftGames this worked for me
