### ISSUE TITLE
couldn't find DSO to load: libhermes.so SoSource 0: com.facebook.soloader.ApkSoSource

### ISSUE THREAD

**Issue by sudhanshu-busy** [facebook/react-native#44279]
### Description

Issue coming in Firebase 

### Steps to reproduce

Issue is in production

### React Native Version

0.70.3

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
    OS: macOS 14.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 987.02 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 10.2.4 - /opt/homebrew/bin/npm
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2023.1 AI-231.9392.1.2311.11255304
    Xcode: 15.2/15C500b - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.9 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.3 => 0.70.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Stacktrace or Logs

```text
Fatal Exception: java.lang.UnsatisfiedLinkError
couldn't find DSO to load: libhermes.so SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-main flags = 1] SoSource 1: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-0 flags = 1] SoSource 2: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-1 flags = 1] SoSource 3: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-2 flags = 1] SoSource 4: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-3 flags = 1] SoSource 5: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-4 flags = 1] SoSource 6: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-5 flags = 1] SoSource 7: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-6 flags = 1] SoSource 8: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-7 flags = 1] SoSource 9: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-8 flags = 1] SoSource 10: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-9 flags = 1] SoSource 11: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-10 flags = 1] SoSource 12: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-11 flags = 1] SoSource 13: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-12 flags = 1] SoSource 14: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-13 flags = 1] SoSource 15: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-14 flags = 1] SoSource 16: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-15 flags = 1] SoSource 17: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-16 flags = 1] SoSource 18: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-17 flags = 1] SoSource 19: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-18 flags = 1] SoSource 20: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-19 flags = 1] SoSource <truncated: 6671 chars>


Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-main flags = 1]
	SoSource 1: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-0 flags = 1]
	SoSource 2: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-1 flags = 1]
	SoSource 3: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-2 flags = 1]
	SoSource 4: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-3 flags = 1]
	SoSource 5: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-4 flags = 1]
	SoSource 6: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-5 flags = 1]
	SoSource 7: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-6 flags = 1]
	SoSource 8: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-7 flags = 1]
	SoSource 9: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-8 flags = 1]
	SoSource 10: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-9 flags = 1]
	SoSource 11: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-10 flags = 1]
	SoSource 12: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-11 flags = 1]
	SoSource 13: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-12 flags = 1]
	SoSource 14: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-13 flags = 1]
	SoSource 15: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-14 flags = 1]
	SoSource 16: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-15 flags = 1]
	SoSource 17: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-16 flags = 1]
	SoSource 18: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-17 flags = 1]
	SoSource 19: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-18 flags = 1]
	SoSource 20: com.facebook.soloader.ApkSoSource[root = /data/data/in.busy.app/lib-19 flags = 1]
	SoSource <truncated: 6671 chars>
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1127)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:943)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:855)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:802)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:772)
       at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:25)
       at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:19)
       at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:23)
       at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:393)
       at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:343)
       at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:96)
       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
       at in.busy.app.MainApplication.onCreate(MainApplication.java:69)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1194)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6735)
       at android.app.ActivityThread.access$1300(ActivityThread.java:239)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1915)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7680)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

### Reproducer

N/A

### Screenshots and Videos

<img width="1244" alt="Screenshot 2024-04-25 at 10 26 47 AM" src="https://github.com/facebook/react-native/assets/137474524/9d4393c7-b69a-4239-86df-43022d8f5b81">

**Comment by cortinico** [comment]
Closing as there are so many similar issues already answered like this one:
https://github.com/facebook/react-native/issues?q=is%3Aissue+sort%3Aupdated-desc+%22couldn%27t+find+DSO%22+is%3Aclosed

**Comment by Abhishek-Khanduri** [comment]
@sudhanshu-busy Any luck on this?
I am also getting the same error

This is the output of `npx react-native info` for me:
```
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 121.06 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    Watchman: 2024.04.08.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.11090377
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.22 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by Abhishek-Khanduri** [comment]
@sudhanshu-busy Then how are you managing your app? Do you know any workarounds?

**Comment by sudhanshu-busy** [comment]
@Abhishek-Khanduri no solution yet don't no what to do. Right now just ignoring it and searching for solution.

**Comment by SMKH-PRO** [comment]
Same error
