### ISSUE TITLE
Unable to run the app on Android 14.

### ISSUE THREAD

**Issue by gkasireddy202** [facebook/react-native#44736]
### Description

Unable to run the app on Android 14.
Previous my project running on Android 12,13.
FATAL EXCEPTION: main
Process: com.appname, PID: 22654
 java.lang.SecurityException: com.khameleonapp.test: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
                                                                          at android.os.Parcel.createException(Parcel.java:3053)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3036)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2978)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6137)
                                                                                                    	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1913)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1841)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
                                                                                                    	at com.github.yamill.orientation.OrientationModule.onHostResume(OrientationModule.java:153)
                                                                                                    	at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:308)
                                                                                                    	at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:765)
                                                                                                    	at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:800)
                                                                                                    	at com.facebook.react.ReactInstanceManager.lambda$setupReactContext$3(ReactInstanceManager.java:1174)
                                                                                                    	at com.facebook.react.ReactInstanceManager.$r8$lambda$iHpnDjhPTftdZc2HP9iD9hTDvL4(Unknown Source:0)
                                                                                                    	at com.facebook.react.ReactInstanceManager$$ExternalSyntheticLambda0.run(Unknown Source:6)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8913)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:16590)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:11530)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2928)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3195)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1375)

### Steps to reproduce

react-native run-android

### React Native Version

0.73.7

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.2.1
  CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Memory: 274.48 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.7.3
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 10.5.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.03.13.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/gopi/.rvm/gems/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "23"
      - "24"
      - "25"
      - "26"
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 29.0.2
      - 30.0.3
      - 33.0.1
      - 34.0.0
    System Images:
      - android-29 | Google APIs Intel x86 Atom
      - android-29 | Google Play Intel x86 Atom
      - android-30 | Google APIs Intel x86 Atom
      - android-32 | Google APIs Intel x86 Atom_64
      - android-32 | Google Play Intel x86 Atom_64
      - android-33 | Google APIs Intel x86 Atom_64
      - android-33 | Google Play Intel x86 Atom_64
    Android NDK: Not Found
IDEs:
  Android Studio: 2021.2 AI-212.5712.43.2112.8609683
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 18.0.2.1
    path: /Library/Java/JavaVirtualMachines/jdk-18.0.2.1.jdk/Contents/Home/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/gopi/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.7
    wanted: 0.73.7
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
FATAL EXCEPTION: main
Process: com.appname, PID: 22654
 java.lang.SecurityException: com.khameleonapp.test: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
                                                                          at android.os.Parcel.createException(Parcel.java:3053)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3036)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2978)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6137)
                                                                                                    	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1913)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1841)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
                                                                                                    	at com.github.yamill.orientation.OrientationModule.onHostResume(OrientationModule.java:153)
                                                                                                    	at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:308)
                                                                                                    	at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:765)
                                                                                                    	at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:800)
                                                                                                    	at com.facebook.react.ReactInstanceManager.lambda$setupReactContext$3(ReactInstanceManager.java:1174)
                                                                                                    	at com.facebook.react.ReactInstanceManager.$r8$lambda$iHpnDjhPTftdZc2HP9iD9hTDvL4(Unknown Source:0)
                                                                                                    	at com.facebook.react.ReactInstanceManager$$ExternalSyntheticLambda0.run(Unknown Source:6)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8913)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:16590)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:11530)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2928)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3195)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1375)
```

### Reproducer

https://github.com/gopikrishnacse55/UIExample.git

### Screenshots and Videos

![shared image](https://github.com/facebook/react-native/assets/90603484/ed4818ba-07cf-43e6-a7fd-69fef0ae6e7d)

**Comment by gkasireddy202** [comment]
I provided the repo.

**Comment by gkasireddy202** [comment]
I see the code merge changes for my project below.
https://github.com/discord/react-native/pull/47/files/72576a373484bcdf64564daa8a961dc34635b21a

**Comment by gkasireddy202** [comment]
Fixed this issue.Issue with react-native-orientation.

**Comment by write2lloyd** [comment]
@gkasireddy202 Would be great to understand how you fixed this issue?

**Comment by gkasireddy202** [comment]
Issue with react-native-orientation npm.
I replaced with react-native-orientation-locker.

Get Outlook for iOS<https://aka.ms/o0ukef>

Gopi Kasireddy
Khameleon Software
e: ***@***.***
a: 12802 Tampa Oaks Boulevard, Suite 100 
Temple Terrace 
FL 
33637
________________________________

**Comment by spsaucier** [comment]
Is there any way to know which package is causing the issue? Otherwise we have to audit every single package.
