### ISSUE TITLE
Production Crash - Fatal Exception: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by NikhilMasurkar** [facebook/react-native#44867]
### Description

I got a Crash on my Firebase crashlytics log 
Fatal Exception: java.lang.UnsatisfiedLinkError

`couldn't find DSO to load: libhermes.so SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/com.indigolearn.fin1-jmjxuOhkSLFVaK45lY84zQ==/lib/arm64 flags = 0] SoSource 1: com.facebook.soloader.DirectApkSoSource[root = ()] SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2] SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2] Native lib dir: /data/app/com.indigolearn.fin1-jmjxuOhkSLFVaK45lY84zQ==/lib/arm64 result: 0`

### Steps to reproduce

-

### React Native Version

0.74.1

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: Windows 11 10.0.22631
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Memory: 847.61 MB / 7.73 GB
Binaries:
  Node:
    version: 21.6.2
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.22
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 10.2.4
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "23"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-28 | Intel x86 Atom_64
      - android-28 | Google APIs ARM 64 v8a
      - android-28 | Google APIs Intel x86 Atom
      - android-28 | Google Play Intel x86 Atom
      - android-33 | Google APIs Intel x86 Atom_64
    Android NDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-231.9392.1.2311.11330709
  Visual Studio: Not Found
Languages:
  Java: 21.0.3
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.74.1
    wanted: 0.74.1
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
	SoSource 0: com.facebook.soloader.DirectorySoSource[root = /data/app/com.indigolearn.fin1-jmjxuOhkSLFVaK45lY84zQ==/lib/arm64 flags = 0]
	SoSource 1: com.facebook.soloader.DirectApkSoSource[root = ()]
	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
	Native lib dir: /data/app/com.indigolearn.fin1-jmjxuOhkSLFVaK45lY84zQ==/lib/arm64
 result: 0
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1127)
       at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:943)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:855)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:802)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:772)
       at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:26)
       at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
       at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:369)
       at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:316)
       at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:94)
       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
       at com.indigolearn.fin1.MainApplication.onCreate(MainApplication.java:70)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
       at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7184)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7134)
       at android.app.ActivityThread.access$1600(ActivityThread.java:274)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

### Reproducer

-

### Screenshots and Videos

![Screenshot 2024-06-11 100613](https://github.com/facebook/react-native/assets/101415426/6f4bf576-ab7e-4369-ab63-7dd113bfed32)
![Screenshot 2024-06-11 100606](https://github.com/facebook/react-native/assets/101415426/ae289686-7de2-442b-9a7c-06e7c077d435)

**Comment by cortinico** [comment]
Duplicates of https://github.com/facebook/react-native/issues?q=is%3Aissue+sort%3Aupdated-desc+%22couldn%27t+find+DSO+to+load%3A+libhermes.so%22+
