### ISSUE TITLE
TypeError in RCTNetworking.sendRequest for android for 0.16.0-rc

### ISSUE THREAD

**Issue by yychun1217** [facebook/react-native#4488]
I encountered the error in android when using 0.16.0-rc

TypeError: expected dynamic type 'double', but had type 'boolean' (constructing arguments for RCTNetworking.sendRequest at argument index 5)

**Comment by andycaramba** [comment]
@yychun1217 Please see [this issue](https://github.com/binggg/mrn/issues/11). May be it gets some help.

**Comment by yychun1217** [comment]
@andersryanc But in my case, even if I init a new project, and run in android device straight away, the same error occurs

**Comment by satya164** [comment]
@yychun1217 Can you share the code which causes this issue?

**Comment by jforaker** [comment]
Same thing for me. Installing `react-native@latest` is a complete bomb. I get the same red screen as the above issue mentioned. Trying to upgrade so we can close out https://github.com/facebook/react-native/issues/4132#issuecomment-161307414 but no luck

And this from the console:
![image](https://cloud.githubusercontent.com/assets/2042031/11553363/d3630bd2-9942-11e5-9ca6-2cbc767988a2.png)

**Comment by jasonals** [comment]
@jforaker @yychun1217  Try running ```react-native upgrade``` after updating. Just solved this problem for me.

**Comment by jforaker** [comment]
Interesting. However it did not work for me :/

**Comment by jasonals** [comment]
@jforaker Restarted packager?

**Comment by mlaval** [comment]
I had the same issue on a real device after upgrading to 0.16.0
Uninstalling the app completely and redeploying it solved the issue.

**Comment by christopherdro** [comment]
This is fixed in 0.16.0

**Comment by jforaker** [comment]
By what commit @christopherdro?

**Comment by christopherdro** [comment]
@jforaker I was testing a few issues on android today and came across this. 
I tested @jasonals suggestion but then came across issue #4573. 

After taking another look I was still using 0.16.0-rc so I updated to the latest stable release and everything worked smoothly.

**Comment by jforaker** [comment]
@christopherdro just started a brand new project with `react-native init App` and it throws this error in Android. 

`TypeError: expected dynamic type 'double', but had type 'boolean' (constructing arguments for RCTNetworking.sendRequest at argument index 5)`

**Comment by jforaker** [comment]
I was able to resolve the issue for a brand new project by doing the following:

1. `brew update && brew upgrade`
2. `android update sdk --no-ui --filter 'platform-tools'`
3. running `android` and using the SDK Manager to update to the latest api 23
4. restart the project/packager

**Comment by christopherdro** [comment]
@jforaker :+1: Glad you got it working!

**Comment by satya164** [comment]
I seem to be facing the issue in release builds, and it happens after second time only.

```java
12-08 17:46:13.031 30787-30838/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                   Process: io.scrollback.neighborhoods, PID: 30787
                                                   com.facebook.react.bridge.NativeArgumentsParseException: TypeError: expected dynamic type `boolean', but had type `int64' (constructing arguments for RCTNetworking.sendRequest at argument index 5)
                                                       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:240)
                                                       at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:143)
                                                       at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:64)
                                                       at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:405)
                                                       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                       at android.os.Handler.handleCallback(Handler.java:746)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:137)
                                                       at java.lang.Thread.run(Thread.java:818)
                                                    Caused by: com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `boolean', but had type `int64'
                                                       at com.facebook.react.bridge.ReadableNativeArray.getBoolean(Native Method)
                                                       at com.facebook.react.bridge.BaseJavaModule$1.extractArgument(BaseJavaModule.java:68)
                                                       at com.facebook.react.bridge.BaseJavaModule$1.extractArgument(BaseJavaModule.java:64)
                                                       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:235)
                                                       at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:143) 
                                                       at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:64) 
                                                       at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:405) 
                                                       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                       at android.os.Handler.handleCallback(Handler.java:746) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:137) 
                                                       at java.lang.Thread.run(Thread.java:818) 

```

**Comment by satya164** [comment]
I seem to be facing the issue in release builds, and it happens after second time only.

```java
12-08 17:46:13.031 30787-30838/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
   Process: io.scrollback.neighborhoods, PID: 30787
   com.facebook.react.bridge.NativeArgumentsParseException: TypeError: expected dynamic type `boolean', but had type `int64' (constructing arguments for RCTNetworking.sendRequest at argument index 5)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:240)
       at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:143)
       at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:64)
       at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:405)
       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:135)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:137)
       at java.lang.Thread.run(Thread.java:818)
    Caused by: com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `boolean', but had type `int64'
       at com.facebook.react.bridge.ReadableNativeArray.getBoolean(Native Method)
       at com.facebook.react.bridge.BaseJavaModule$1.extractArgument(BaseJavaModule.java:68)
       at com.facebook.react.bridge.BaseJavaModule$1.extractArgument(BaseJavaModule.java:64)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:235)
       at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:143) 
       at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:64) 
       at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:405) 
       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
       at android.os.Handler.handleCallback(Handler.java:746) 
       at android.os.Handler.dispatchMessage(Handler.java:95) 
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
       at android.os.Looper.loop(Looper.java:135) 
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:137) 
       at java.lang.Thread.run(Thread.java:818) 

```

**Comment by satya164** [comment]
cc @mkonicek

**Comment by Ehesp** [comment]
I did have this issue, but following @jforaker instructions I can't start the build anymore:

```
BUILD FAILED

Total time: 3.267 secs
Could not install the app on the device, see the error above.
```
Probably another issue, but just warning. Not sure what to do now.

**Comment by jforaker** [comment]
@Ehesp what is the error in `see the error above`? Keep in mind that my solution was to start a brand new project using `react-native init NewProject`. And then when I saw the issue occuring I performed the steps above.

**Comment by Ehesp** [comment]
Ah, my bad I didn't have `23.0.1` build tools installed, just `23.0.2` - no clue whether your instructions remove it, been working fine previously.

Anyway, I installed that `23.0.1`, did a new project and get that error - not touched anything else:

![image](https://cloud.githubusercontent.com/assets/842078/11660010/f1bbdc06-9dc2-11e5-965e-3d4f12183774.png)

**Comment by satya164** [comment]
cc @mkonicek

**Comment by christopherdro** [comment]
@Ehesp Could you try wiping out your `node_modules` directory and running `npm install` again?`

Almost make sure that your on the latest stable release, 0.16

**Comment by mkonicek** [comment]
Can you paste the contents of your package.json and android/app/build.gradle somewhere?

**Comment by 116205035** [comment]
i did have this error too.
follow is my package.json and build.gradle 
=====================================
package.json :
{
  "name": "myreactapplication",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react-native": "^0.16.0"
  }
}

============================
build.gradle is :
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "react.squire.com.myreactapplication"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.1.0'
    compile 'com.facebook.react:react-native:0.13.0'
}



======================================
I did this from this page for Integrating with Existing Apps：
https://facebook.github.io/react-native/docs/embedded-app-android.html#content

**Comment by satya164** [comment]
@116205035 You have an old version of RN. Please run the command `react-native upgrade` to update your project.

@mkonicek Here are my `package.json` and `build.gradle`,

https://github.com/scrollback/io.scrollback.neighborhoods/blob/dialog/package.json#L34
https://github.com/scrollback/io.scrollback.neighborhoods/blob/dialog/android/app/build.gradle#L128

**Comment by 116205035** [comment]
@satya164  i got it， thank you， when i changed my build.gradle to compile 'com.facebook.react:react-native:0.16.+'  ,it fixed!  so, the version of RN  is the key to this issue.

**Comment by Ehesp** [comment]
@christopherdro @mkonicek So based on the above, it turns out it was that line in the `app/build.gradle`.  Although it was adding that in on new projects, so running `npm install -g react-native-cli` and trying again worked. Thanks for the help.

**Comment by mkonicek** [comment]
No problem. Glad it worked! Closing.

**Comment by WaKeMaTTa** [comment]
Thanks @jforaker `react-native upgrade` works on to me. :+1:

**Comment by jihopark** [comment]
solved by changing the version of build.gradle.
