### ISSUE TITLE
 ERROR  connect.compress is not a function

### ISSUE THREAD

**Issue by devjiangzhou** [facebook/react-native#4489]
TypeError: connect.compress is not a function
    at runServer (runServer.js:28:18)
    at startServer (server.js:144:3)
    at _server (server.js:140:3)
    at server.js:24:5
    at tryCallTwo (/Users/jiangzhou/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/jiangzhou/node_modules/promise/lib/core.js:171:13)
    at new Promise (/Users/jiangzhou/node_modules/promise/lib/core.js:65:3)
    at Array.server (server.js:23:10)
    at run (/Users/jiangzhou/Documents/Github/JavaScript/react-native/local-cli/cli.js:85:13)
    at Object.<anonymous> (/Users/jiangzhou/Documents/Github/JavaScript/react-native/local-cli/cli.js:162:3)

**Comment by satya164** [comment]
Can you give some info on when does it happen?

**Comment by devjiangzhou** [comment]
thanks， I forget run "npm install" in react nitive folder
