### ISSUE TITLE
0.72: Backport fix for privacy manifest generation path being nil

### ISSUE THREAD

**Issue by miallo** [facebook/react-native#45036]
### Description

The commit https://github.com/facebook/react-native/commit/4ad65ac59a2491db598abb7b32fb793e9693d5ac needs to be back ported to the branch for 0.72

### Steps to reproduce

1. add a ".strings"-group to the Xcode project
2. run `pod install`

### React Native Version

0.72.15

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.5
  CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Memory: 56.76 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: /nix/store/0ckf6nnx5hxn365x45sd70va0v7yv0f8-nodejs-18.19.0/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.3
    path: /nix/store/0ckf6nnx5hxn365x45sd70va0v7yv0f8-nodejs-18.19.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    Android NDK: 23.1.7779620
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby:
    version: 3.1.4
    path: /nix/store/b38w7v9r3zf5cnc1ci8kbw9fdf68a7qb-wrapped-ruby-fastlane/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.15
    wanted: ^0.72.15
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false
```

### Stacktrace or Logs

```text
[Privacy Manifest Aggregation] Appending aggregated reasons to existing PrivacyInfo.xcprivacy file.
[Privacy Manifest Aggregation] Reading .xcprivacy files to aggregate all used Required Reason APIs.
[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `end_with?' for nil:NilClass

        reference_exists = target.resources_build_phase.files_references.any? { |file_ref| file_ref.path.end_with? "PrivacyInfo.xcprivacy" }
                                                                                                        ^^^^^^^^^^

/Users/michael/src/Salus/projectName/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:70:in `block in ensure_reference'
/Users/michael/src/Salus/projectName/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:70:in `any?'
/Users/michael/src/Salus/projectName/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:70:in `ensure_reference'
/Users/michael/src/Salus/projectName/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:48:in `block in add_aggregated_privacy_manifest'
/Users/michael/src/Salus/projectName/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:47:in `each'
/Users/michael/src/Salus/projectName/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:47:in `add_aggregated_privacy_manifest'
/Users/michael/src/Salus/projectName/node_modules/react-native/scripts/react_native_pods.rb:259:in `react_native_post_install'
/Users/michael/src/Salus/projectName/ios/Podfile:33:in `block (3 levels) in from_ruby'
/nix/store/sjxa64sq00pl6a6air155py1hh8w8syz-ruby3.1.4-cocoapods-core-1.14.3/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/podfile.rb:196:in `post_install!'
/nix/store/6k9q7m5rg1liam588s2d0hbin1nmykri-ruby3.1.4-cocoapods-1.14.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:1013:in `run_podfile_post_install_hook'
/nix/store/6k9q7m5rg1liam588s2d0hbin1nmykri-ruby3.1.4-cocoapods-1.14.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:1001:in `block in run_podfile_post_install_hooks'
/nix/store/6k9q7m5rg1liam588s2d0hbin1nmykri-ruby3.1.4-cocoapods-1.14.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:149:in `message'
/nix/store/6k9q7m5rg1liam588s2d0hbin1nmykri-ruby3.1.4-cocoapods-1.14.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:1000:in `run_podfile_post_install_hooks'
/nix/store/6k9q7m5rg1liam588s2d0hbin1nmykri-ruby3.1.4-cocoapods-1.14.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:337:in `block (2 levels) in create_and_save_projects'
/nix/store/6k9q7m5rg1liam588s2d0hbin1nmykri-ruby3.1.4-cocoapods-1.14.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/nix/store/6k9q7m5rg1liam588s2d0hbin1nmykri-ruby3.1.4-cocoapods-1.14.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:336:in `block in create_and_save_projects'
/nix/store/6k9q7m5rg1liam588s2d0hbin1nmykri-ruby3.1.4-cocoapods-1.14.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/nix/store/6k9q7m5rg1liam588s2d0hbin1nmykri-ruby3.1.4-cocoapods-1.14.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:315:in `create_and_save_projects'
/nix/store/6k9q7m5rg1liam588s2d0hbin1nmykri-ruby3.1.4-cocoapods-1.14.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:307:in `generate_pods_project'
/nix/store/6k9q7m5rg1liam588s2d0hbin1nmykri-ruby3.1.4-cocoapods-1.14.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:183:in `integrate'
/nix/store/6k9q7m5rg1liam588s2d0hbin1nmykri-ruby3.1.4-cocoapods-1.14.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:170:in `install!'
/nix/store/6k9q7m5rg1liam588s2d0hbin1nmykri-ruby3.1.4-cocoapods-1.14.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.3/lib/cocoapods/command/install.rb:52:in `run'
/nix/store/dxwb1abv78xd9v4dqyi1pwqgn2ca4sgk-ruby3.1.4-claide-1.1.0/lib/ruby/gems/3.1.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/nix/store/6k9q7m5rg1liam588s2d0hbin1nmykri-ruby3.1.4-cocoapods-1.14.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.3/lib/cocoapods/command.rb:52:in `run'
/nix/store/6wp4p3hsycgi7vqi25xqwhf1yr5x1pgk-fastlane-2.219.0/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.3/bin/pod:55:in `<top (required)>'
/nix/store/6wp4p3hsycgi7vqi25xqwhf1yr5x1pgk-fastlane-2.219.0/lib/ruby/gems/3.1.0/bin/pod:25:in `load'
/nix/store/6wp4p3hsycgi7vqi25xqwhf1yr5x1pgk-fastlane-2.219.0/lib/ruby/gems/3.1.0/bin/pod:25:in `<top (required)>'
/nix/store/pgn6913migijv8shz5s1kz9f549h76sp-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:58:in `load'
/nix/store/pgn6913migijv8shz5s1kz9f549h76sp-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
/nix/store/pgn6913migijv8shz5s1kz9f549h76sp-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler/cli/exec.rb:23:in `run'
/nix/store/pgn6913migijv8shz5s1kz9f549h76sp-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler/cli.rb:492:in `exec'
/nix/store/pgn6913migijv8shz5s1kz9f549h76sp-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/nix/store/pgn6913migijv8shz5s1kz9f549h76sp-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/nix/store/pgn6913migijv8shz5s1kz9f549h76sp-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/nix/store/pgn6913migijv8shz5s1kz9f549h76sp-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler/cli.rb:34:in `dispatch'
/nix/store/pgn6913migijv8shz5s1kz9f549h76sp-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/nix/store/pgn6913migijv8shz5s1kz9f549h76sp-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler/cli.rb:28:in `start'
/nix/store/6wp4p3hsycgi7vqi25xqwhf1yr5x1pgk-fastlane-2.219.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/exe/bundle:37:in `block in <top (required)>'
/nix/store/pgn6913migijv8shz5s1kz9f549h76sp-bundler-2.4.22/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/nix/store/6wp4p3hsycgi7vqi25xqwhf1yr5x1pgk-fastlane-2.219.0/lib/ruby/gems/3.1.0/gems/bundler-2.4.22/exe/bundle:29:in `<top (required)>'
/nix/store/xz4lv6n1ncs39drkjmzh4yfx4llf41qb-ruby-3.1.4/bin/bundle:25:in `load'
/nix/store/xz4lv6n1ncs39drkjmzh4yfx4llf41qb-ruby-3.1.4/bin/bundle:25:in `<main>'
```

### Reproducer

https://github.com/miallo/rn-privacy-manifest-example

**Comment by cortinico** [comment]
Please open a pick request as described here:
https://github.com/reactwg/react-native-releases/blob/main/docs/faq.md#what-is-a-pick-request

**Comment by miallo** [comment]
For reference here it is: https://github.com/reactwg/react-native-releases/issues/326
