### ISSUE TITLE
Add support for Gradle Configuration Cache

### ISSUE THREAD

**Issue by pvdmde** [facebook/react-native#45154]
### Description

Using Gradle 8.2 or newer with stable config cache support, enabling it with org.gradle.configuration-cache=true I'm getting this error:

```
4 problems were found storing the configuration cache, 2 of which seem unique.
- Script '/Users/..../node_modules/@react-native-community/cli-platform-android/native_modules.gradle': external process started 'node -e try {console.log(require('@react-native-community/cli').bin);} catch (e) {console.log(require('react-native/cli').bin);}'
  See https://docs.gradle.org/8.2.1/userguide/configuration_cache.html#config_cache:requirements:external_processes
```
```
org.gradle.api.InvalidUserCodeException: Starting an external process 'node -e try {console.log(require('@react-native-community/cli').bin);} catch (e) {console.log(require('react-native/cli').bin);}' during configuration time is unsupported.
	at org.gradle.configurationcache.initialization.DefaultConfigurationCacheProblemsListener.onExternalProcessStarted(ConfigurationCacheProblemsListener.kt:117)
	at org.gradle.configurationcache.InstrumentedInputAccessListener.externalProcessStarted(InstrumentedInputAccessListener.kt:110)
	at org.gradle.internal.classpath.Instrumented.externalProcessStarted(Instrumented.java:501)
```

Currently we're wasting 30s to 1 minute on configuration step every time we build, also locally. 
I reported it almost a year ago in https://github.com/react-native-community/cli/issues/2058, now it being closed there I should recreate it here.

### Steps to reproduce

Using Gradle 8.2 or newer with stable config cache support, enabling it with org.gradle.configuration-cache=true I'm getting this error:

### React Native Version

0.74.0

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
irrelevant
```

### Stacktrace or Logs

```text
4 problems were found storing the configuration cache, 2 of which seem unique.
- Script '/Users/..../node_modules/@react-native-community/cli-platform-android/native_modules.gradle': external process started 'node -e try {console.log(require('@react-native-community/cli').bin);} catch (e) {console.log(require('react-native/cli').bin);}'
  See https://docs.gradle.org/8.2.1/userguide/configuration_cache.html#config_cache:requirements:external_processes
```
```
org.gradle.api.InvalidUserCodeException: Starting an external process 'node -e try {console.log(require('@react-native-community/cli').bin);} catch (e) {console.log(require('react-native/cli').bin);}' during configuration time is unsupported.
	at org.gradle.configurationcache.initialization.DefaultConfigurationCacheProblemsListener.onExternalProcessStarted(ConfigurationCacheProblemsListener.kt:117)
	at org.gradle.configurationcache.InstrumentedInputAccessListener.externalProcessStarted(InstrumentedInputAccessListener.kt:110)
	at org.gradle.internal.classpath.Instrumented.externalProcessStarted(Instrumented.java:501)
```
```


### Reproducer

irrelevant, issue is clear in the description

### Screenshots and Videos

_No response_

**Comment by cortinico** [comment]
Yup this is a known issue. I believe that 0.75 should bring support for Gradle Configuration cache but I need a bit more time testing it.

I'll provide more updates on this issue once I have them

**Comment by pvdmde** [comment]
Did it make into 0.75? I didn't see it in the changelog directly.

**Comment by cortinico** [comment]
Nope sadly I wasn't able to work on this for 0.75 (and 0.76 will also be unlikely). If someone is willing to send a PR for it, I'm happy to support reviewing and merging.

**Comment by FilDevTronic** [comment]
Is this here still the most likely solution approach or have more recent changes in React Native and Gradle changed that?
https://github.com/react-native-community/cli/issues/2058#issuecomment-1682265416

**Comment by cortinico** [comment]
> Is this here still the most likely solution approach or have more recent changes in React Native and Gradle changed that? [react-native-community/cli#2058 (comment)](https://github.com/react-native-community/cli/issues/2058#issuecomment-1682265416)

There is still work to be done to support Configuration Caching. Any help or PR going in that direction are more than welcome

**Comment by FilDevTronic** [comment]
I just asked you if your last recommended approach to creating a solution is still the "direction" to take, or if that's no longer valid.

**Comment by cortinico** [comment]
> I just asked you if your last recommended approach to creating a solution is still the "direction" to take, or if that's no longer valid.

Yup that's still the recommended approach. With 0.74 we reworked a lot of the internals of RNGP so it should be easier to implement config caching, however I just haven't found the time.
The culprit is those `exec` invocations we're doing to run CLI commands.

**Comment by FilDevTronic** [comment]
Perfect, thank you for the pointer!
