### ISSUE TITLE
v0.15.0 - Typo "Error building DepdendencyGraph"

### ISSUE THREAD

**Issue by niftylettuce** [facebook/react-native#4516]
```log
[10:24:49 PM] <END>   Crawling File System (1960ms)
[10:24:49 PM] <START> Building in-memory fs for JavaScript
[10:24:56 PM] <END>   Building in-memory fs for JavaScript (6299ms)
[10:24:56 PM] <START> Building in-memory fs for Assets
[10:25:02 PM] <END>   Building in-memory fs for Assets (6143ms)
[10:25:02 PM] <START> Building Haste Map
[10:25:02 PM] <START> Building (deprecated) Asset Map
Error building DepdendencyGraph:
 RangeError: Maximum call stack size exceeded
    at /Users/nexus/Public/superagent_test/node_modules/react-native/packager/react-packager/src/DependencyResolver/fastfs.js:282:19
    at Array.forEach (native)
    at File.getFiles (/Users/nexus/Public/superagent_test/node_modules/react-native/packager/react-packager/src/DependencyResolver/fastfs.js:279:32)
    at /Users/nexus/Public/superagent_test/node_modules/react-native/packager/react-packager/src/DependencyResolver/fastfs.js:65:54
    at Array.map (native)
    at Fastfs.getAllFiles (/Users/nexus/Public/superagent_test/node_modules/react-native/packager/react-packager/src/DependencyResolver/fastfs.js:65:37)
    at Fastfs.findFilesByExt (/Users/nexus/Public/superagent_test/node_modules/react-native/packager/react-packager/src/DependencyResolver/fastfs.js:69:17)
    at HasteMap.build (/Users/nexus/Public/superagent_test/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:27:33)
    at /Users/nexus/Public/superagent_test/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/index.js:132:33
    at tryCallOne (/Users/nexus/Public/superagent_test/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
```

**Comment by niftylettuce** [comment]
This also seems to be a weird error I received after installing a new package to `package.json`.

**Comment by niftylettuce** [comment]
Oh, this is because I'm using a symlinked `npm` package via `npm link mypackage` since I'm working locally.

**Comment by satya164** [comment]
@niftylettuce Symlinks are not supported by the packager. #637

**Comment by cancan101** [comment]
I am getting this error on 0.17.0-rc and I don't use sym links:
```
[5:42:11 PM] <START> Building (deprecated) Asset Map
Error building DependencyGraph:
 RangeError: Maximum call stack size exceeded
    at fastfs.js:300:19
    at Array.forEach (native)
    at File.getFiles (fastfs.js:297:32)
    at fastfs.js:79:54
    at Array.map (native)
    at Fastfs.getAllFiles (fastfs.js:79:37)
    at Fastfs.findFilesByExts (fastfs.js:87:17)
    at HasteMap.build (HasteMap.js:27:33)
    at index.js:125:33
    at tryCallOne (/Users/alex/git/Mobile-RN/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
```
