### ISSUE TITLE
[Android] [ToolbarAndroid] Error while updating property 'actions' of a view managed by: ToolbarAndroid

### ISSUE THREAD

**Issue by atom992** [facebook/react-native#4554]
React Native 0.13.2
React Native cli 0.1.7

My Code:
```
var toolbarActions = [
  {title: '提醒', icon: require('image!launcher_icon'), show: 'always'},
  {title: '夜间模式', show: 'never'},
  {title: '设置选项', show: 'never'},
];

<ToolbarAndroid
          logo={require("image!ic_menu_black_24dp")}
          navIcon = {require("image!ic_menu_black_24dp")}
          actions={toolbarActions}

          style={styles.toolbar}
          title="TITLE"
        />
``` 

The error
```
E/unknown:React( 4028): Exception in native call from JS
E/unknown:React( 4028): com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'actions' of a view managed by: ToolbarAndroid
E/unknown:React( 4028): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateProp(ViewManagersPropertyCache.java:66)
E/unknown:React( 4028): 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:47)
E/unknown:React( 4028): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:182)
E/unknown:React( 4028): 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:137)
E/unknown:React( 4028): 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:574)
E/unknown:React( 4028): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:622)
E/unknown:React( 4028): 	at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
E/unknown:React( 4028): 	at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:114)
E/unknown:React( 4028): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
E/unknown:React( 4028): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/unknown:React( 4028): 	at android.view.Choreographer.doFrame(Choreographer.java:549)
E/unknown:React( 4028): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/unknown:React( 4028): 	at android.os.Handler.handleCallback(Handler.java:739)
E/unknown:React( 4028): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/unknown:React( 4028): 	at android.os.Looper.loop(Looper.java:135)
E/unknown:React( 4028): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
E/unknown:React( 4028): 	at java.lang.reflect.Method.invoke(Native Method)
E/unknown:React( 4028): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/unknown:React( 4028): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/unknown:React( 4028): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
E/unknown:React( 4028): Caused by: java.lang.reflect.InvocationTargetException
E/unknown:React( 4028): 	at java.lang.reflect.Method.invoke(Native Method)
E/unknown:React( 4028): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/unknown:React( 4028): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$ArrayPropSetter.updateProperty(ViewManagersPropertyCache.java:160)
E/unknown:React( 4028): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateProp(ViewManagersPropertyCache.java:63)
E/unknown:React( 4028): 	... 19 more
E/unknown:React( 4028): Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class <unknown>
E/unknown:React( 4028): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
E/unknown:React( 4028): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
E/unknown:React( 4028): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
E/unknown:React( 4028): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
E/unknown:React( 4028): 	at android.support.v7.internal.view.menu.BaseMenuPresenter.createItemView(BaseMenuPresenter.java:161)
E/unknown:React( 4028): 	at android.support.v7.internal.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:180)
E/unknown:React( 4028): 	at android.support.v7.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:194)
E/unknown:React( 4028): 	at android.support.v7.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:453)
E/unknown:React( 4028): 	at android.support.v7.internal.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1138)
E/unknown:React( 4028): 	at android.support.v7.internal.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:91)
E/unknown:React( 4028): 	at android.support.v7.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:231)
E/unknown:React( 4028): 	at android.support.v7.internal.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:284)
E/unknown:React( 4028): 	at android.support.v7.internal.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1030)
E/unknown:React( 4028): 	at android.support.v7.internal.view.menu.MenuBuilder.onItemActionRequestChanged(MenuBuilder.java:1076)
E/unknown:React( 4028): 	at android.support.v7.internal.view.menu.MenuItemImpl.setShowAsAction(MenuItemImpl.java:603)
E/unknown:React( 4028): 	at com.facebook.react.views.toolbar.ReactToolbar.setActions(ReactToolbar.java:211)
E/unknown:React( 4028): 	at com.facebook.react.views.toolbar.ReactToolbarManager.setActions(ReactToolbarManager.java:94)
E/unknown:ViewManager( 4028): Error while updating prop actions
E/unknown:ViewManager( 4028): java.lang.reflect.InvocationTargetException
E/unknown:ViewManager( 4028): 	at java.lang.reflect.Method.invoke(Native Method)
E/unknown:ViewManager( 4028): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/unknown:ViewManager( 4028): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$ArrayPropSetter.updateProperty(ViewManagersPropertyCache.java:160)
E/unknown:ViewManager( 4028): 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateProp(ViewManagersPropertyCache.java:63)
E/unknown:ViewManager( 4028): 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:47)
E/unknown:ViewManager( 4028): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:182)
E/unknown:ViewManager( 4028): 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:137)
E/unknown:ViewManager( 4028): 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:574)
E/unknown:ViewManager( 4028): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:622)
E/unknown:ViewManager( 4028): 	at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
E/unknown:ViewManager( 4028): 	at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:114)
E/unknown:ViewManager( 4028): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
E/unknown:ViewManager( 4028): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/unknown:ViewManager( 4028): 	at android.view.Choreographer.doFrame(Choreographer.java:549)
E/unknown:ViewManager( 4028): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/unknown:ViewManager( 4028): 	at android.os.Handler.handleCallback(Handler.java:739)
E/unknown:ViewManager( 4028): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/unknown:ViewManager( 4028): 	at android.os.Looper.loop(Looper.java:135)
E/unknown:ViewManager( 4028): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
E/unknown:ViewManager( 4028): 	at java.lang.reflect.Method.invoke(Native Method)
E/unknown:ViewManager( 4028): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/unknown:ViewManager( 4028): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/unknown:ViewManager( 4028): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
E/unknown:ViewManager( 4028): Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class <unknown>
E/unknown:ViewManager( 4028): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
E/unknown:ViewManager( 4028): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
E/unknown:ViewManager( 4028): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
E/unknown:ViewManager( 4028): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
E/unknown:ViewManager( 4028): 	at android.support.v7.internal.view.menu.BaseMenuPresenter.createItemView(BaseMenuPresenter.java:161)
E/unknown:ViewManager( 4028): 	at android.support.v7.internal.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:180)
E/unknown:ViewManager( 4028): 	at android.support.v7.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:194)
E/unknown:ViewManager( 4028): 	at android.support.v7.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:453)
E/unknown:ViewManager( 4028): 	at android.support.v7.internal.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1138)
E/unknown:ViewManager( 4028): 	at android.support.v7.internal.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:91)
E/unknown:ViewManager( 4028): 	at android.support.v7.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:231)
E/unknown:ViewManager( 4028): 	at android.support.v7.internal.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:284)
E/unknown:ViewManager( 4028): 	at android.support.v7.internal.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1030)
E/unknown:ViewManager( 4028): 	at android.support.v7.internal.view.menu.MenuBuilder.onItemActionRequestChanged(MenuBuilder.java:1076)
E/unknown:ViewManager( 4028): 	at android.support.v7.internal.view.menu.MenuItemImpl.setShowAsAction(MenuItemImpl.java:603)
E/unknown:ViewManager( 4028): 	at com.facebook.react.views.toolbar.ReactToolbar.setActions(ReactToolbar.java:211)
E/unknown:ViewManager( 4028): 	at com.facebook.react.views.toolbar.ReactToolbarManager.setActions(ReactToolbarManager.java:94)
E/unknown:ViewManager( 4028): 	... 23 more
E/unknown:ViewManager( 4028): Caused by: java.lang.reflect.InvocationTargetException
E/unknown:ViewManager( 4028): 	at java.lang.reflect.Constructor.newInstance(Native Method)
E/unknown:ViewManager( 4028): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
E/unknown:ViewManager( 4028): 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
E/unknown:ViewManager( 4028): 	... 39 more
E/unknown:ViewManager( 4028): Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 5
E/unknown:ViewManager( 4028): 	at android.content.res.TypedArray.getColorStateList(TypedArray.java:425)
E/unknown:ViewManager( 4028): 	at android.widget.TextView.<init>(TextView.java:987)
E/unknown:ViewManager( 4028): 	at an
```

It looks like the "always" value of show have some problem.

**Comment by christopherdro** [comment]
@facebook-github-bot close
