### ISSUE TITLE
Specifying Flag for Context Broadcast Receiver in Android 14 (sdk >= 34)

### ISSUE THREAD

**Issue by GuptaAman08** [facebook/react-native#45773]
### Description

I had recently changed the following things in my apps root level build.gradle file
    buildToolsVersion = "33.0.0" => "34.0.0"
    minSdkVersion = 21 => 30
    compileSdkVersion = 33 => 34
    targetSdkVersion = 33 => 34
    
  Changing to this gave me error related to following two packages which indeed required me to upgrade their versions
    "react-native-safe-area-context": "^4.4.1" => "^4.5.1",
    "react-native-screens": "^3.18.2" => "^3.22.0"

After all of these changes, I was able to build the app successfully but as soon as its launched on the android 14 emulator it crashed.

I encountered below error logs
<details><summary>Logs</summary>

```
07-26 15:34:53.353 15553 15553 E AndroidRuntime: FATAL EXCEPTION: main
07-26 15:34:53.353 15553 15553 E AndroidRuntime: Process: com.proximity.deliverysolutions, PID: 15553
07-26 15:34:53.353 15553 15553 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.proximity.deliverysolutions.MainApplication: java.lang.RuntimeException: Requested enabled DevSupportManager, but BridgeDevSupportManager class was not found or could not be created
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7003)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8177)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but BridgeDevSupportManager class was not found or could not be created
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.devsupport.DefaultDevSupportManagerFactory.create(DefaultDevSupportManagerFactory.java:97)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:255)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:330)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:94)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.proximity.deliverysolutions.MainApplication.onCreate(MainApplication.java:60)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6998)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	... 9 more
07-26 15:34:53.353 15553 15553 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.devsupport.DefaultDevSupportManagerFactory.create(DefaultDevSupportManagerFactory.java:86)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	... 16 more
07-26 15:34:53.353 15553 15553 E AndroidRuntime: Caused by: java.lang.SecurityException: com.proximity.deliverysolutions: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3041)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3024)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2966)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.devsupport.DevSupportManagerBase.reload(DevSupportManagerBase.java:1101)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.devsupport.DevSupportManagerBase.reloadSettings(DevSupportManagerBase.java:721)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.devsupport.DevSupportManagerBase.setDevSupportEnabled(DevSupportManagerBase.java:593)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.devsupport.DevSupportManagerBase.<init>(DevSupportManagerBase.java:206)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.devsupport.BridgeDevSupportManager.<init>(BridgeDevSupportManager.java:78)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	... 19 more
07-26 15:34:53.353 15553 15553 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13927)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1339)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:1275)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 
07-26 15:34:53.358   551 15575 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
07-26 15:34:53.359   551  2338 W ActivityTaskManager:   Force finishing activity com.proximity.deliverysolutions/.MainActivity
07-26 15:34:53.360   771   829 V WindowManagerShell: Transition requested: android.os.BinderProxy@f880e07 TransitionRequestInfo { type = CLOSE, triggerTask = null, remoteTransition = null, displayChange = null }
07-26 15:34:53.363 15553 15553 I Process : Sending signal. PID: 15553 SIG: 9
07-26 15:34:53.372   551  2338 I ActivityManager: Process com.proximity.deliverysolutions (pid 15553) has died: fg  TOP 
07-26 15:34:53.372   551   583 I libprocessgroup: Successfully killed process cgroup uid 10200 pid 15553 in 0ms
07-26 15:34:53.373   551   571 D DisplayManagerService: Drop pending events for gone uid 10200
07-26 15:34:53.383  1593  1593 I GsaVoiceInteractionSrv: Handling ACTION_START_HOTWORD
07-26 15:34:53.387   387   387 I BpBinder: onLastStrongRef automatically unlinking death recipients: 
07-26 15:34:53.389  1593  2408 I GsaVoiceInteractionSrv: (REDACTED) disregardVoiceMatch: %b
07-26 15:34:53.390  1593  2408 I GsaVoiceInteractionSrv: Cannot start hotword, hotword has been explicitly disabled.
07-26 15:34:53.391  1526  1772 I AiAiEcho: Predicting[0]: 
07-26 15:34:53.391  1526  1772 I AiAiEcho: EchoTargets: 
07-26 15:34:53.391  1526  1772 I AiAiEcho: Filtered by AiAi flag check: 
07-26 15:34:53.391  1526  1772 I AiAiEcho: Ranked targets strategy: SORT, count: 0, ranking metadata: 
07-26 15:34:53.392  1526  1772 I AiAiEcho: #postPredictionTargets: Sending updates to UISurface home with targets# 0 (types=[])
07-26 15:34:53.392   551  1604 W AppSearchIcing: icing-search-engine.cc:283: Error: 5, Message: Document (com.google.android.googlequicksearchbox$OneSearchZeroStateGoogleSuggestions/default, zp) not found.
```
</details>

Being having one underlying third party package (transistorsoft) in the suspect list, i upgraded its version to the one in which the author claims that this issue is fixed.
But I am still facing the same issue.

I then followed the [github issue ](https://github.com/facebook/react-native/issues/41288) and one medium [link](https://medium.com/@techAzeem/reac-native-android-app-crash-after-upgrade-targetsdkversion-34-e521f0dd0e19) and finally managed to get my app working.

But, my question is even if the app is not listening to any broadcast receiver then too is it mandatory to include the above custom piece of code in the react-native app's MainApplication.java, when targeting for sdk >= 34 ??

If its not mandatory then can someone help me understand where am going wrong ??
 

### Steps to reproduce

- Change the build.gradle file to include the changes mentioned in the above description
- Upgrade the version of the two packages as mentioned in the above description.
- Make the android build 
- Observe adb logs during the launch

### React Native Version

0.71.4

### Affected Platforms

Runtime - Android, Build - MacOS

### Output of `npx react-native info`

```text
System:
    OS: macOS 14.5
    CPU: (8) x64 Apple M1
    Memory: 43.34 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
    Yarn: Not Found
    npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
    Watchman: 2024.07.01.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2023.2 AI-232.10300.40.2321.11668458
    Xcode: 15.4/15F31d - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Stacktrace or Logs

```text
07-26 15:34:53.353 15553 15553 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.proximity.deliverysolutions.MainApplication: java.lang.RuntimeException: Requested enabled DevSupportManager, but BridgeDevSupportManager class was not found or could not be created
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7003)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8177)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but BridgeDevSupportManager class was not found or could not be created
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.devsupport.DefaultDevSupportManagerFactory.create(DefaultDevSupportManagerFactory.java:97)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:255)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:330)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:94)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.proximity.deliverysolutions.MainApplication.onCreate(MainApplication.java:60)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6998)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	... 9 more
07-26 15:34:53.353 15553 15553 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.devsupport.DefaultDevSupportManagerFactory.create(DefaultDevSupportManagerFactory.java:86)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	... 16 more
07-26 15:34:53.353 15553 15553 E AndroidRuntime: Caused by: java.lang.SecurityException: com.proximity.deliverysolutions: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3041)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3024)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2966)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.devsupport.DevSupportManagerBase.reload(DevSupportManagerBase.java:1101)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.devsupport.DevSupportManagerBase.reloadSettings(DevSupportManagerBase.java:721)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.devsupport.DevSupportManagerBase.setDevSupportEnabled(DevSupportManagerBase.java:593)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.devsupport.DevSupportManagerBase.<init>(DevSupportManagerBase.java:206)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.facebook.react.devsupport.BridgeDevSupportManager.<init>(BridgeDevSupportManager.java:78)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	... 19 more
07-26 15:34:53.353 15553 15553 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13927)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1339)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:1275)
07-26 15:34:53.353 15553 15553 E AndroidRuntime: 
07-26 15:34:53.358   551 15575 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
07-26 15:34:53.359   551  2338 W ActivityTaskManager:   Force finishing activity com.proximity.deliverysolutions/.MainActivity
07-26 15:34:53.360   771   829 V WindowManagerShell: Transition requested: android.os.BinderProxy@f880e07 TransitionRequestInfo { type = CLOSE, triggerTask = null, remoteTransition = null, displayChange = null }
```

### Reproducer

Not possible since its a private repository

**Comment by cortinico** [comment]
> If its not mandatory then can someone help me understand where am going wrong ??

We added support for targetSdk 14 in React Native 0.73:
- https://github.com/facebook/react-native/pull/39103

As you're using RN 0.71, that't the reason why you're experiencing this crash

**Comment by GuptaAman08** [comment]
@cortinico, 
Its tough to upgrade the react-native version. Hence, we were for some fix which indeed forced us to implement the patch code piece mentioned in the [github issue](https://github.com/facebook/react-native/issues/41288).

>But, my question is even if the app is not listening to any broadcast receiver then too is it mandatory to include the above custom piece of code in the react-native app's MainApplication.java, when targeting for sdk >= 34 ??


What I am trying to ask here was, if for some reason i dont want to upgrade the react-native version then is it mandatory for every react-native application, with version < 0.73, to implement this fix or shouldn't be required for every react-native app

**Comment by GuptaAman08** [comment]
Folks I got a better solution now.

@cortinico upgrading the RN from 0.71.4 to 0.71.18 also fixed this issue to me. So, I will be following this instead of adding a patch fix in my code
