### ISSUE TITLE
'TypeError: Object.assign is not a function' in the packager

### ISSUE THREAD

**Issue by kriskelly** [facebook/react-native#4583]
Just tried setting up a new project via `react-native init` today and I get this error in Xcode:

```
+ react-native bundle --entry-file index.ios.js --platform ios --dev true --bundle-output /Users/kriskelly/Library/Developer/Xcode/DerivedData/Autoscrolling-gbloxkveqsoptkfqzdjnuhpavcsm/Build/Products/Debug-iphonesimulator/Autoscrolling.app/main.jsbundle --assets-dest /Users/kriskelly/Library/Developer/Xcode/DerivedData/Autoscrolling-gbloxkveqsoptkfqzdjnuhpavcsm/Build/Products/Debug-iphonesimulator/Autoscrolling.app
bundle: Created ReactPackager
uncaught error Error: TypeError: Object.assign is not a function
    at transform (/Users/kriskelly/Projects/gtd-panic-react-native/react-native-drag-drop/examples/Autoscrolling/node_modules/react-native/packager/transformer.js:33:25)
    at module.exports (/Users/kriskelly/Projects/gtd-panic-react-native/react-native-drag-drop/examples/Autoscrolling/node_modules/react-native/packager/transformer.js:66:14)
    at handle (/Users/kriskelly/Projects/gtd-panic-react-native/react-native-drag-drop/examples/Autoscrolling/node_modules/react-native/node_modules/worker-farm/lib/child/index.js:41:8)
    at process.<anonymous> (/Users/kriskelly/Projects/gtd-panic-react-native/react-native-drag-drop/examples/Autoscrolling/node_modules/react-native/node_modules/worker-farm/lib/child/index.js:47:3)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:169:7)
    at handleMessage (child_process.js:276:10)
TransformError: /Users/kriskelly/Projects/gtd-panic-react-native/react-native-drag-drop/examples/Autoscrolling/node_modules/react-native/packager/react-packager/src/Resolver/polyfills/prelude_dev.js: Object.assign is not a function
See logs /var/folders/p8/tsl3pzfn03zbd72b_c47tjvh0000gp/T/react-packager.log
    at SocketClient._handleMessage (SocketClient.js:139:23)
    at BunserBuf.<anonymous> (SocketClient.js:53:42)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:166:7)
    at BunserBuf.process (/Users/kriskelly/Projects/gtd-panic-react-native/react-native-drag-drop/examples/Autoscrolling/node_modules/react-native/node_modules/bser/index.js:289:10)
    at /Users/kriskelly/Projects/gtd-panic-react-native/react-native-drag-drop/examples/Autoscrolling/node_modules/react-native/node_modules/bser/index.js:244:12
    at doNTCallback0 (node.js:415:9)
    at process._tickCallback (node.js:344:13)
Command /bin/sh failed with exit code 1
```

I think I've tracked the failure to this commit: `21bae9b294014d178b014cd53655da0ef13eab49`, but not totally sure.

**Comment by kriskelly** [comment]
Ok false alarm, must have been a hiccup in the project initialization somewhere. Tried it again later on and it worked.

**Comment by joewood** [comment]
I just did the same, and got the same error. I'll try again, maybe an intermittent error?

**Comment by joewood** [comment]
I tried this a few times and eventually it just worked. I made some changes, one thing that may have triggered the fix was that I had a global install of babel. I removed that and it seemed to start working (although I haven't repeated it).  Just adding a note if anybody else hits this.

**Comment by mvayngrib** [comment]
also hit this using iojs 2.x, went away after switching to node 4

**Comment by mhollweck** [comment]
+1 (got this error even after switching to node 4). any other idea?

**Comment by christopherdro** [comment]
@mhollweck Did you restart the packager after upgrading to Node 4?

Also could you just try and restart your system and see if that changes anything?

**Comment by tlins** [comment]
@mhollweck 
I got the same issue yesterday!
Please try to check your Node Version -> 
      
     tobiaslins$ node -v
     v2.0.2

I had an old version on it (2.0.2)
After upgrading to 5.2.0 everything was working!

**Comment by tannewt** [comment]
The packager was warning me I was still using iojs. Running ```nvm alias default node``` fixed it because my node is 4.1.1.

**Comment by jondot** [comment]
+1, don't forget that the packager may run in a different terminal which is not wired to a specific node version.

**Comment by vitonzhang** [comment]
@tlins is right !! 

After upgrading to 5.2.0 everything was working!

**Comment by oojr** [comment]
had the same issue and my node was up-to-date, updating react-native-cli fixed it for me

`npm install -g react-native-cli`
