### ISSUE TITLE
npx @react-native-community/cli@latest init MyProject –-version latest, I got latest is not a valid version.

### ISSUE THREAD

**Issue by Hao-yiwen** [facebook/react-native#46089]
### Description

I see the upgrade doc, I get use `npx @react-native-community/cli@latest init MyProject –-version latest` to create 0.75.1 react native project.But I got follow error info. And I use `npx @react-native-community/cli@latest init MyProject –-version 0.75.1` is work ok.
<img width="831" alt="截屏2024-08-19 15 31 43" src="https://github.com/user-attachments/assets/17194e87-69d2-4f0e-9f08-f05623780eaf">

```
➜ npx @react-native-community/cli@latest init MyProject –-version latest
npm error arg Argument starts with non-ascii dash, this is probably invalid: –-version
error Invalid Version: latest.
TypeError: Invalid Version: latest
    at new SemVer (/Users/yw.hao/.npm/_npx/2788f5fbd47acb89/node_modules/semver/classes/semver.js:38:13)
    at compare (/Users/yw.hao/.npm/_npx/2788f5fbd47acb89/node_modules/semver/functions/compare.js:3:3)
    at Object.lt (/Users/yw.hao/.npm/_npx/2788f5fbd47acb89/node_modules/semver/functions/lt.js:2:29)
    at createTemplateUri (/Users/yw.hao/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/commands/init/init.js:334:47)
    at createProject (/Users/yw.hao/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/commands/init/init.js:371:29)
    at Object.initialize [as func] (/Users/yw.hao/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/commands/init/init.js:452:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.handleAction (/Users/yw.hao/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/index.js:116:9)
info Run CLI with --verbose flag for more details.
```

### Steps to reproduce

npx @react-native-community/cli@latest init MyProject –-version latest

### React Native Version

0.75.1

### Affected Platforms

Runtime - Android, Runtime - iOS

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
  OS: macOS 14.2.1
  CPU: (8) arm64 Apple M2
  Memory: 63.02 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.14.0
    path: ~/.nvm/versions/node/v20.14.0/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.nvm/versions/node/v20.14.0/bin/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v20.14.0/bin/npm
  Watchman:
    version: 2024.07.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/yw.hao/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 3.0.0
    path: /Users/yw.hao/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
npm error arg Argument starts with non-ascii dash, this is probably invalid: –-version
error Invalid Version: latest.
TypeError: Invalid Version: latest
    at new SemVer (/Users/yw.hao/.npm/_npx/2788f5fbd47acb89/node_modules/semver/classes/semver.js:38:13)
    at compare (/Users/yw.hao/.npm/_npx/2788f5fbd47acb89/node_modules/semver/functions/compare.js:3:3)
    at Object.lt (/Users/yw.hao/.npm/_npx/2788f5fbd47acb89/node_modules/semver/functions/lt.js:2:29)
    at createTemplateUri (/Users/yw.hao/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/commands/init/init.js:334:47)
    at createProject (/Users/yw.hao/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/commands/init/init.js:371:29)
    at Object.initialize [as func] (/Users/yw.hao/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/commands/init/init.js:452:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.handleAction (/Users/yw.hao/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/index.js:116:9)
info Run CLI with --verbose flag for more details.
```

### Reproducer

no url.

**Comment by onmotion** [comment]
a valid dash symbol should be used in the argument 

❌ `–-version`
✅ `--version`

**Comment by Hao-yiwen** [comment]
Yes, doc has this question. But change fix this error also get latest is not a invlid version.

**Comment by Hao-yiwen** [comment]
https://reactnative.dev/blog/2024/08/12/release-0.75

**Comment by Hao-yiwen** [comment]
Use npx @react-native-community/cli@latest init MyProject --version 0.75.2, Don't use latest.
