### ISSUE TITLE
[Android] Crash - Caused by: java.lang.NoClassDefFoundError: com.facebook.react.modules.core.Timing$FrameCallback

### ISSUE THREAD

**Issue by Richard-Cao** [facebook/react-native#4617]
```
E/dalvikvm: Could not find class 'com.facebook.react.modules.debug.FpsDebugFrameCallback', referenced from method com.facebook.react.modules.debug.AnimationsDebugModule.startRecordingFps
```
```
E/dalvikvm: Could not find class 'com.facebook.react.modules.core.Timing$FrameCallback', referenced from method com.facebook.react.modules.core.Timing.<init>
```
```
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                   java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                       at android.os.AsyncTask$3.done(AsyncTask.java:278)
                                                                       at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
                                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
                                                                       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:137)
                                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                                       at java.lang.Thread.run(Thread.java:856)
                                                                    Caused by: java.lang.NoClassDefFoundError: com.facebook.react.modules.core.Timing$FrameCallback
                                                                       at com.facebook.react.modules.core.Timing.<init>(Timing.java:94)
                                                                       at com.facebook.react.CoreModulesPackage.createNativeModules(CoreModulesPackage.java:56)
                                                                       at com.facebook.react.ReactInstanceManagerImpl.processPackage(ReactInstanceManagerImpl.java:622)
                                                                       at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:591)
                                                                       at com.facebook.react.ReactInstanceManagerImpl.access$600(ReactInstanceManagerImpl.java:76)
                                                                       at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:163)
                                                                       at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:149)
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:264)
```

**Comment by amaqkit** [comment]
Got this when I try to run on Android 4.0.1(API 15), I know it needs Android 4.1(API 16), but in my country there are still so many devices based on Android below 4.1.

**Comment by Richard-Cao** [comment]
@amaqkit yes, me too, but do not solve this problem

**Comment by brentvatne** [comment]
Sorry @amaqkit - there are no plans to support API 15 :(
