### ISSUE TITLE
[Android] Bundle build failed

### ISSUE THREAD

**Issue by gstausnow** [facebook/react-native#4630]
When i build android bundle on window 7(x64), errors occurred:

C:\Users\''\AwesomeProject>react-native bundle --platform android --entry-file i
ndex.android.js --bundle-output aa.apk
C:\Users\''\AwesomeProject\node_modules\react-native\node_modules\promise\lib\do
ne.js:10
      throw err;
      ^

Error: Took too long to start server. Server logs:
Tue, 08 Dec 2015 01:24:20 GMT ReactNativePackager:SocketServer server got ipc me
ssage { type: 'createSocketServer',
  data:
   { sockPath: 'C:\\Users\\\'\'\\AppData\\Local\\Temp\\react-packager-d2842dbcce
3dad34f24db3dbe4ef63b1',
     options:
      { projectRoots: [Object],
        assetRoots: [Object],
        blacklistRE: [Object],
        transformModulePath: 'C:\\Users\\\'\'\\AwesomeProject\\node_modules\\rea
ct-native\\packager\\transformer.js' } } }
[09:24:20] <START> Building Dependency Graph
[09:24:20] <START> Crawling File System
[09:24:20] <START> Loading bundles layout
[09:24:20] <END>   Loading bundles layout (1ms)
Tue, 08 Dec 2015 01:24:20 GMT ReactNativePackager:SocketServer error creating se
rver EACCES
Tue, 08 Dec 2015 01:24:20 GMT ReactNativePackager:SocketServer uncaught error Er
ror: listen EACCES C:\Users\''\AppData\Local\Temp\react-packager-d2842dbcce3dad3
4f24db3dbe4ef63b1
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1360:5)
    at new SocketServer (SocketServer.js:24:18)
    at process.<anonymous> (SocketServer.js:185:7)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)
Tue, 08 Dec 2015 01:30:10 GMT ReactNativePackager:SocketServer server got ipc me
ssage { type: 'createSocketServer',
  data:
   { sockPath: 'C:\\Users\\\'\'\\AppData\\Local\\Temp\\react-packager-d2842dbcce
3dad34f24db3dbe4ef63b1',
     options:
      { projectRoots: [Object],
        assetRoots: [Object],
        blacklistRE: [Object],
        transformModulePath: 'C:\\Users\\\'\'\\AwesomeProject\\node_modules\\rea
ct-native\\packager\\transformer.js' } } }
[09:30:10] <START> Building Dependency Graph
[09:30:10] <START> Crawling File System
[09:30:10] <START> Loading bundles layout
[09:30:10] <END>   Loading bundles layout (1ms)
Tue, 08 Dec 2015 01:30:10 GMT ReactNativePackager:SocketServer error creating se
rver EACCES
Tue, 08 Dec 2015 01:30:10 GMT ReactNativePackager:SocketServer uncaught error Er
ror: listen EACCES C:\Users\''\AppData\Local\Temp\react-packager-d2842dbcce3dad3
4f24db3dbe4ef63b1
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1360:5)
    at new SocketServer (SocketServer.js:24:18)
    at process.<anonymous> (SocketServer.js:185:7)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)
Tue, 08 Dec 2015 01:36:20 GMT ReactNativePackager:SocketServer server got ipc me
ssage { type: 'createSocketServer',
  data:
   { sockPath: 'C:\\Users\\\'\'\\AppData\\Local\\Temp\\react-packager-d2842dbcce
3dad34f24db3dbe4ef63b1',
     options:
      { projectRoots: [Object],
        assetRoots: [Object],
        blacklistRE: [Object],
        transformModulePath: 'C:\\Users\\\'\'\\AwesomeProject\\node_modules\\rea
ct-native\\packager\\transformer.js' } } }
[09:36:20] <START> Building Dependency Graph
[09:36:20] <START> Crawling File System
[09:36:20] <START> Loading bundles layout
[09:36:20] <END>   Loading bundles layout (0ms)
Tue, 08 Dec 2015 01:36:20 GMT ReactNativePackager:SocketServer error creating se
rver EACCES
Tue, 08 Dec 2015 01:36:20 GMT ReactNativePackager:SocketServer uncaught error Er
ror: listen EACCES C:\Users\''\AppData\Local\Temp\react-packager-d2842dbcce3dad3
4f24db3dbe4ef63b1
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1360:5)
    at new SocketServer (SocketServer.js:24:18)
    at process.<anonymous> (SocketServer.js:185:7)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)

    at [object Object]._onTimeout (index.js:82:7)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by Creemli** [comment]
createSocketServer error ?? Maybe your chrome is not open~~

**Comment by brentvatne** [comment]
Please post to StackOverflow :)
