### ISSUE TITLE
React native error on init new project on windows

### ISSUE THREAD

**Issue by mihirjoshi21** [facebook/react-native#4640]
I started working on react native. I started by creating a new project through the steps mentioned in the official documentation -

```react-native init AwesomeProject```

I get this error.

```
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to
load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_module
s\npm\node_modules\node-gyp\lib\configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mihirj\Desktop\Desktop\MOTO\ReactNative\AwesomeProject1\no
de_modules\react-native\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
The system cannot find the path specified.
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to
load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_module
s\npm\node_modules\node-gyp\lib\configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mihirj\Desktop\Desktop\MOTO\ReactNative\AwesomeProject1\no
de_modules\react-native\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing fsevents@1.0.5
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "react-native"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! path C:\Users\mihirj\AppData\Roaming\npm-cache\readable-stream\2.0.4\pa
ckage\package.json.e304aeeb7d55672bcc47b1dac342c402
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\mihirj\AppData\
Roaming\npm-cache\readable-stream\2.0.4\package\package.json.e304aeeb7d55672bcc4
7b1dac342c402' -> 'C:\Users\mihirj\AppData\Roaming\npm-cache\readable-stream\2.0
.4\package\package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\mihirj\AppD
ata\Roaming\npm-cache\readable-stream\2.0.4\package\package.json.e304aeeb7d55672
bcc47b1dac342c402' -> 'C:\Users\mihirj\AppData\Roaming\npm-cache\readable-stream
\2.0.4\package\package.json']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\mihirj\\AppData\\Roaming\\npm-cache\\readable-strea
m\\2.0.4\\package\\package.json.e304aeeb7d55672bcc47b1dac342c402',
npm ERR!   dest: 'C:\\Users\\mihirj\\AppData\\Roaming\\npm-cache\\readable-strea
m\\2.0.4\\package\\package.json',
npm ERR!   parent: 'through2' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mihirj\Desktop\Desktop\MOTO\ReactNative\AwesomeProject1\np
m-debug.log

`npm install --save react-native` failed```

[npm-debug.txt](https://github.com/facebook/react-native/files/55220/npm-debug.txt)

**Comment by rmevans9** [comment]
This isn't a fix but a workaround if you go delete everything in the npm-cache directory referenced in the error about the operation not being permitted then try again it usually works. I have seen this a time or two.

**Comment by mihirjoshi21** [comment]
@rmevans9 Still not working

**Comment by rmevans9** [comment]
I believe this is an issue with NPM, not React Native.

See: https://github.com/npm/npm/issues/10649 This report has basically the same error message.

**Comment by bsamadi** [comment]
@rmevans9 It worked for me. Thank you!
@mihirjoshi21 Have you installed react-native with this command?
    npm install -g react-native-cli

**Comment by mihirjoshi21** [comment]
@rmevans9 
It worked for me as well few days back, and I did absolutely nothing. I think maybe because of the new update.

**Comment by stanhe** [comment]
you should run CMD with administrator permission
