### ISSUE TITLE
Android sdk 34 java.lang.RuntimeException:Requested enabled DevSupportManager, but BridgeDevSupportManager class was not found or could not be created

### ISSUE THREAD

**Issue by vaish8529** [facebook/react-native#46569]
### Description

After upgrading the Android SDK from version 33 to 34, the app crashes on Android 34, although it runs smoothly on Android 33.
the following changes have been made:
`buildscript {
ext {
    googlePlayServicesVersion = "+" 
    firebaseMessagingVersion = "21.1.0" 
    buildToolsVersion = "34.0.0"
    minSdkVersion = 21
    compileSdkVersion = 34
    targetSdkVersion = 34
    androidXAnnotation = "1.1.0"
    androidXBrowser = "1.0.0"
    pdfViewer = "3.1.0-beta.1"
}`
My current React Native version is 0.68.6.

Error in Android 34:
`FATAL EXCEPTION: 
java.lang.RuntimeException: Unable to create application com.poi.MainApplication: java.lang.RuntimeException: Requested enabled DevSupportManager, but BridgeDevSupportManager class was not found or could not be created
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7716)
    at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8919)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but BridgeDevSupportManager class was not found or could not be created
    at `
    
    However, upon launching the application, I encountered an issue where the App Crashes immediately on the launch. To investigate this, I pulled a Bug Report, which provided the following insights:

1. Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but BridgeDevSupportManager class was not found or could not be created.
2. Caused by: java.lang.SecurityException: : One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts.
3. Caused by: java.lang.reflect.InvocationTargetException.
4. Caused by: android.os.RemoteException: Remote stack trace.

### Steps to reproduce

react-native run-android after running command its crashing

### React Native Version

 0.68.6.

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-12650H
    Memory: 6.42 GB / 15.68 GB
  Binaries:
    Node: 14.20.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 33, 34
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 34.0.0
      System Images: android-26 | Intel x86_64 Atom, android-28 | Intel x86_64 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86_64 Atom, android-33 | Google Play Intel x86_64 Atom, android-34 | Intel x86_64 Atom, android-34 | Google APIs ARM 64 v8a, android-34 | Google APIs Intel x86_64 Atom, android-34 | Google Play ARM 64 v8a, android-34 | Google Play Intel x86_64 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9014738
    Visual Studio: Not Found
  Languages:
    Java: 11.0.16.1 - C:\Program Files\Microsoft\jdk-11.0.16.101-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.0 => 0.70.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Stacktrace or Logs

```text
FATAL EXCEPTION: 
java.lang.RuntimeException: Unable to create application com.poi.MainApplication: java.lang.RuntimeException: Requested enabled DevSupportManager, but BridgeDevSupportManager class was not found or could not be created
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7716)
    at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8919)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but BridgeDevSupportManager class was not found or could not be created
    at
```

### Reproducer

https://github.com/facebook/react-native/issues/new?assignees=&labels=Needs%3A+Triage+%3Amag%3A&projects=&template=bug_report.yml

**Comment by vaish8529** [comment]
I wanted to stick with React Version 0.68.6., as my code runs for both Android and iOS.

In my project, 0.68.6. is compatible for both iOS and Android

**Comment by vaish8529** [comment]
I have tried upgrading react native version, but After upgrading react native 0.68 to 0.70 still i am facing issue

**Comment by cortinico** [comment]
On this issue tracker we offer support only for the supported versions of React Native:
https://github.com/reactwg/react-native-releases/blob/main/docs/support.md#what-versions-are-currently-supported

You can seek support for older versions of React Native on StackOverflow
