### ISSUE TITLE
App crashes when sent to Background (onPause)

### ISSUE THREAD

**Issue by oliveirac-ppb** [facebook/react-native#46791]
### Description

After following [this tutorial](https://reactnative.dev/docs/integration-with-existing-apps) to load a React Native bundle inside a Native Application, the app crashes every time the app is sent to Background (onPause()).

To give more context, our `MainActivity` starts the `ReactNativeActivity` which is starting a bundle of a react native application. When the app is in the foreground both activities are working as expected, except when the app is sent to background.

### Steps to reproduce

1. Create a native project.
2. Follow the steps in this documentation to load a React Native bundle.
3. Start the React Native Activity through the Main Activity.
4. Open the app.
5. Send the app to the background.
6. Check the logs on Android Studio.
7. A crash on `ReactInstanceManager.onHostPause` will appear

### React Native Version

0.73.8

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.6.1
  CPU: (12) arm64 Apple M3 Pro
  Memory: 317.23 MB / 36.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.17.0
    path: /opt/homebrew/opt/node@20/bin/node
  Yarn:
    version: 3.2.1
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.8.2
    path: /opt/homebrew/opt/node@20/bin/npm
  Watchman:
    version: 2024.09.09.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/oliveirac/.gem/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK:
    API Levels:
      - "23"
      - "26"
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-30 | Google Play ARM 64 v8a
      - android-33 | Google Play ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11255304
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.7.4
    path: /Users/oliveirac/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.8
    wanted: 0.73.8
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
java.lang.AssertionError
  at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:82)
  at com.facebook.react.ReactInstanceManager.onHostPause(ReactInstanceManager.java:581)
  at com.facebook.react.ReactDelegate.onHostPause(ReactDelegate.java:107)
  at com.facebook.react.ReactActivityDelegate.onPause(ReactActivityDelegate.java:128)
  at com.facebook.react.ReactActivity.onPause(ReactActivity.java:52)
  at com.skybet.app.skybet.ui.ReactNativeActivity.onPause(ReactNativeActivity.kt:54)
  at android.app.Activity.performPause(Activity.java:8168)
  at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1510)
  at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4735)
  at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4696)
  at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4647)
  at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:223)
  at android.app.ActivityThread.main(ActivityThread.java:7656)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

### Reproducer

can't use this

**Comment by cortinico** [comment]
> After following [this tutorial](https://reactnative.dev/docs/integration-with-existing-apps) to load a React Native bundle inside a Native Application

That tutorial is sadly out of date.

I've rewrote it from scratch last week, you can find it here: https://reactnative.dev/docs/next/integration-with-existing-apps

Please follow the new instructions and report back if you still have issues.
