### ISSUE TITLE
react-native init project is Error

### ISSUE THREAD

**Issue by fov42550564** [facebook/react-native#4690]
when I run react-native init Vaccinum
```
This will walk you through creating a new React Native project in /Users/fang/react/Vaccinum
Installing react-native package from npm...
/Users/fang/react/Vaccinum/node_modules/react-native/node_modules/babel-core/lib/transformation/file/logger.js:41
    throw new Constructor(this._buildMessage(msg));
    ^

ReferenceError: [BABEL] /Users/fang/react/Vaccinum/node_modules/react-native/local-cli/bundle/bundle.js: Unknown option: base.whitelist
    at Logger.error (/Users/fang/react/Vaccinum/node_modules/react-native/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/fang/react/Vaccinum/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:262:18)
    at OptionManager.init (/Users/fang/react/Vaccinum/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:416:10)
    at File.initOptions (/Users/fang/react/Vaccinum/node_modules/react-native/node_modules/babel-core/lib/transformation/file/index.js:190:75)
    at new File (/Users/fang/react/Vaccinum/node_modules/react-native/node_modules/babel-core/lib/transformation/file/index.js:121:22)
    at Pipeline.transform (/Users/fang/react/Vaccinum/node_modules/react-native/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at Object.transformFileSync (/Users/fang/react/Vaccinum/node_modules/react-native/node_modules/babel-core/lib/api/node.js:116:10)
    at compile (/Users/fang/react/Vaccinum/node_modules/react-native/node_modules/babel-core/node_modules/babel-register/lib/node.js:102:20)
    at loader (/Users/fang/react/Vaccinum/node_modules/react-native/node_modules/babel-core/node_modules/babel-register/lib/node.js:130:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/fang/react/Vaccinum/node_modules/react-native/node_modules/babel-core/node_modules/babel-register/lib/node.js:140:7)
```

**Comment by pkpower** [comment]
Hi, can you please tell the OS platform on which you are getting this error ?

**Comment by fov42550564** [comment]
$node -v
v4.1.1
$npm -v
2.14.4
$react-native -v
0.1.7
OS X Yosemite 10.10.5
thanks

**Comment by AndreyNikiforov** [comment]
Same issue. Followed instructions from RN Getting Started page to get latest node (v5.2) and latest brew and then initialize new project. El Captain.

**Comment by fov42550564** [comment]
I update node but has the same error
$node -v
v5.2.0

**Comment by Ehesp** [comment]
Do you have the latest CLI tool? `npm install -g react-native-cli`

**Comment by Dynom** [comment]
I have the same issue, I'll follow along. My details:
$ node -v
v4.2.3
$ npm -v
2.14.7
$ react-native -v
0.1.7

**Comment by oney** [comment]
I have `.babelrc` in root directory, file content is
```json
{
  "whitelist": [
    "es6.modules"
  ]
}
```
Remove whitelist part and it's working.
Be sure to remove all part of packages in node_modules

**Comment by skevy** [comment]
@fov42550564 can you confirm that you fixed your original issue by following instructions in this thread?

I was just able to generate a new project using the CLI using RN master...can you provide more instructions to reproduce?

**Comment by fov42550564** [comment]
I found the problem, In my root dir: cd ~, there is a file .babelrc, delete it will work well.
thank oney
