### ISSUE TITLE
release apk can't run on android

### ISSUE THREAD

**Issue by fov42550564** [facebook/react-native#4695]
debug apk is ok, but release apk can not run on android
```
I/dalvikvm(16127): threadid=1: recursive native library load attempt (/data/app-lib/com.remobile-1/libreactnativejni.so)
E/dalvikvm(16127): ERROR: couldn't find native method
E/dalvikvm(16127): Requested: Lcom/facebook/react/bridge/WritableNativeMap;.mergeNativeMap:(Lcom/facebook/react/bridge/ReadableNativeMap;)V
W/dalvikvm(16127): Exception Ljava/lang/NoSuchMethodError; thrown while initializing Lcom/facebook/react/bridge/JSCJavaScriptExecutor;
D/AndroidRuntime(16127): Shutting down VM
W/dalvikvm(16127): threadid=1: thread exiting with uncaught exception (group=0x4166ed58)
I/WhetstoneService( 1241): Receive am_crash event for pid: 16127
W/KloServer( 1241): Aborted broadcast does not supprt for: com.remobile
E/AndroidRuntime(16127): FATAL EXCEPTION: main
E/AndroidRuntime(16127): Process: com.remobile, PID: 16127
E/AndroidRuntime(16127): java.lang.NoSuchMethodError: no static or non-static method "Lcom/facebook/react/bridge/WritableNativeMap;.mergeNativeMap(Lcom/facebook/react/bridge/ReadableNativeMap;)V"
E/AndroidRuntime(16127):    at java.lang.Runtime.nativeLoad(Native Method)
E/AndroidRuntime(16127):    at java.lang.Runtime.doLoad(Runtime.java:421)
E/AndroidRuntime(16127):    at java.lang.Runtime.load(Runtime.java:331)
E/AndroidRuntime(16127):    at java.lang.System.load(System.java:512)
E/AndroidRuntime(16127):    at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
E/AndroidRuntime(16127):    at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:209)
E/AndroidRuntime(16127):    at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:178)
E/AndroidRuntime(16127):    at com.facebook.react.bridge.JSCJavaScriptExecutor.<clinit>(JSCJavaScriptExecutor.java:19)
E/AndroidRuntime(16127):    at com.facebook.react.ReactInstanceManager.createReactContextInBackground(ReactInstanceManager.java:246)
E/AndroidRuntime(16127):    at com.facebook.react.ReactInstanceManager.attachMeasuredRootView(ReactInstanceManager.java:367)
E/AndroidRuntime(16127):    at com.facebook.react.ReactRootView$1.run(ReactRootView.java:105)
E/AndroidRuntime(16127):    at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(16127):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(16127):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(16127):    at android.app.ActivityThread.main(ActivityThread.java:5111)
E/AndroidRuntime(16127):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(16127):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(16127):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
E/AndroidRuntime(16127):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
E/AndroidRuntime(16127):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  943):   Force finishing activity com.remobile/.MainActivity
```

**Comment by lawgimenez** [comment]
If you set minifyEnabled true, this error will occur. False, otherwise.

**Comment by brentvatne** [comment]
cc @mkonicek

**Comment by fov42550564** [comment]
new version have no problem

**Comment by yipengmu** [comment]
@lawgimenez @fov42550564  i saw the same problem v0.19.0 in maven ,how to solve this problem without by  set minifyEnabled false in gradle.

no static or non-static method "Lcom/facebook/react/bridge/ProxyJavaScriptExecutor;.initialize(Lcom/facebook/react/bridge/ProxyJavaScriptExecutor$JavaJSExecutor;)V"

**Comment by ZhangChengD** [comment]
I have some error when Jump to RNActivity
JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.NoSuchMethodError: no static or non-static method "Lcom/facebook/react/bridge/ProxyJavaScriptExecutor;.initHybrid(Lcom/facebook/react/bridge/JavaJSExecutor;)Lcom/facebook/jni/HybridData;"
and this is my version .
react-native-cli: 2.0.1
npm -v 5.6.0
buildToolsVersion gradle 24.0.3
