### ISSUE TITLE
React packager failing - SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by ColinEberhardt** [facebook/react-native#47]
Unfortunately I am having issues with getting the movies example app working :-(

I have installed watchman as per the instructions, and already had node v0.10.36 installed.

On running `npm start` all seems well. However when I load the movies example it fails.

Testing via the URL:

```
http://localhost:8081/Examples/Movies/MoviesApp.includeRequire.runModule.bundle
```

Yields the following error:

```
{"type":"InternalError","message":"React packager has encountered an internal error, please check your terminal error output for more details"}
```

And here is the terminal output:

```
$ npm start

> react-native@0.0.1 start /Users/colineberhardt/Projects/react-native
> ./packager/packager.sh


 ===============================================================
 |  Running packager on port 8081.       
 |  Keep this packager running while developing on any JS         
 |  projects. Feel free to close this tab and run your own      
 |  packager instance if you prefer.                              
 |                                                              
 |     https://github.com/facebook/react-native                 
 |                                                              
 ===============================================================


React packager ready.

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /Users/colineberhardt/Projects/react-native/packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js:270:32
    at _fulfilled (/Users/colineberhardt/Projects/react-native/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/colineberhardt/Projects/react-native/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/colineberhardt/Projects/react-native/node_modules/q/q.js:749:13)
    at /Users/colineberhardt/Projects/react-native/node_modules/q/q.js:557:44
    at flush (/Users/colineberhardt/Projects/react-native/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:442:13)
[17:52:41] <START> find dependencies
```

I've had a poke around `DependencyGraph` and tried to add some logging but haven't made much progress.

Has anyone else ecountered (and maybe solved!) this issue?

**Comment by Haroenv** [comment]
I have this error message without a path, did something get reverted?

**Comment by joshkarges** [comment]
I have @Haroenv's same issue.

**Comment by yemarnevets** [comment]
I did a complete fresh install from the guide: https://facebook.github.io/react-native/docs/getting-started.html and I'm still running into this issue. The error message is quite cryptic. I'd hope for more detail in development mode.
