### ISSUE TITLE
com.facebook.jni.CppException: facebook::react::Recoverable: Could not open file/data/user/0/.../main.jsbundle: No such file or directory

### ISSUE THREAD

**Issue by aLittleGreens** [facebook/react-native#47107]
### Description

```
com.facebook.jni.CppException: facebook::react::Recoverable: Could not open file/data/user/0/com.philips.ph.babymonitorplus/files/deletable/rn/000000kt5n_5.79_1.0.20/main.jsbundle: No such file or directory
--
  | at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromFile(Native Method)
  | at com.facebook.react.bridge.CatalystInstanceImpl.void loadScriptFromFile(java.lang.String,java.lang.String,boolean)(CatalystInstanceImpl.java:6)
  | at com.facebook.react.bridge.JSBundleLoader$2.java.lang.String loadScript(com.facebook.react.bridge.JSBundleLoaderDelegate)(JSBundleLoader.java:20)
  | at com.facebook.react.bridge.CatalystInstanceImpl.void runJSBundle()(CatalystInstanceImpl.java:12)
  | at com.facebook.react.ReactInstanceManager.com.facebook.react.bridge.ReactApplicationContext createReactContext(com.facebook.react.bridge.JavaScriptExecutor,com.facebook.react.bridge.JSBundleLoader)(ReactInstanceManager.java:302)
  | at com.facebook.react.ReactInstanceManager.com.facebook.react.bridge.ReactApplicationContext access$900(com.facebook.react.ReactInstanceManager,com.facebook.react.bridge.JavaScriptExecutor,com.facebook.react.bridge.JSBundleLoader)(ReactInstanceManager.java:1)
  | at com.facebook.react.ReactInstanceManager$5.void run()(ReactInstanceManager.java:244)
  | at java.lang.Thread.run(Thread.java:1012)
```

### Steps to reproduce

Android crash

### React Native Version

0.73.0

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
com.facebook.jni.CppException: facebook::react::Recoverable: Could not open file/data/user/0/com.philips.ph.babymonitorplus/files/deletable/rn/000000kt5n_5.79_1.0.20/main.jsbundle: No such file or directory
--
  | at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromFile(Native Method)
  | at com.facebook.react.bridge.CatalystInstanceImpl.void loadScriptFromFile(java.lang.String,java.lang.String,boolean)(CatalystInstanceImpl.java:6)
  | at com.facebook.react.bridge.JSBundleLoader$2.java.lang.String loadScript(com.facebook.react.bridge.JSBundleLoaderDelegate)(JSBundleLoader.java:20)
  | at com.facebook.react.bridge.CatalystInstanceImpl.void runJSBundle()(CatalystInstanceImpl.java:12)
  | at com.facebook.react.ReactInstanceManager.com.facebook.react.bridge.ReactApplicationContext createReactContext(com.facebook.react.bridge.JavaScriptExecutor,com.facebook.react.bridge.JSBundleLoader)(ReactInstanceManager.java:302)
  | at com.facebook.react.ReactInstanceManager.com.facebook.react.bridge.ReactApplicationContext access$900(com.facebook.react.ReactInstanceManager,com.facebook.react.bridge.JavaScriptExecutor,com.facebook.react.bridge.JSBundleLoader)(ReactInstanceManager.java:1)
  | at com.facebook.react.ReactInstanceManager$5.void run()(ReactInstanceManager.java:244)
  | at java.lang.Thread.run(Thread.java:1012)
```

### Stacktrace or Logs

```text
com.facebook.jni.CppException: facebook::react::Recoverable: Could not open file/data/user/0/com.philips.ph.babymonitorplus/files/deletable/rn/000000kt5n_5.79_1.0.20/main.jsbundle: No such file or directory
--
  | at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromFile(Native Method)
  | at com.facebook.react.bridge.CatalystInstanceImpl.void loadScriptFromFile(java.lang.String,java.lang.String,boolean)(CatalystInstanceImpl.java:6)
  | at com.facebook.react.bridge.JSBundleLoader$2.java.lang.String loadScript(com.facebook.react.bridge.JSBundleLoaderDelegate)(JSBundleLoader.java:20)
  | at com.facebook.react.bridge.CatalystInstanceImpl.void runJSBundle()(CatalystInstanceImpl.java:12)
  | at com.facebook.react.ReactInstanceManager.com.facebook.react.bridge.ReactApplicationContext createReactContext(com.facebook.react.bridge.JavaScriptExecutor,com.facebook.react.bridge.JSBundleLoader)(ReactInstanceManager.java:302)
  | at com.facebook.react.ReactInstanceManager.com.facebook.react.bridge.ReactApplicationContext access$900(com.facebook.react.ReactInstanceManager,com.facebook.react.bridge.JavaScriptExecutor,com.facebook.react.bridge.JSBundleLoader)(ReactInstanceManager.java:1)
  | at com.facebook.react.ReactInstanceManager$5.void run()(ReactInstanceManager.java:244)
  | at java.lang.Thread.run(Thread.java:1012)
```

### Reproducer

https://github.com/aLittleGreens

### Screenshots and Videos

```
com.facebook.jni.CppException: facebook::react::Recoverable: Could not open file/data/user/0/com.philips.ph.babymonitorplus/files/deletable/rn/000000kt5n_5.79_1.0.20/main.jsbundle: No such file or directory
--
  | at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromFile(Native Method)
  | at com.facebook.react.bridge.CatalystInstanceImpl.void loadScriptFromFile(java.lang.String,java.lang.String,boolean)(CatalystInstanceImpl.java:6)
  | at com.facebook.react.bridge.JSBundleLoader$2.java.lang.String loadScript(com.facebook.react.bridge.JSBundleLoaderDelegate)(JSBundleLoader.java:20)
  | at com.facebook.react.bridge.CatalystInstanceImpl.void runJSBundle()(CatalystInstanceImpl.java:12)
  | at com.facebook.react.ReactInstanceManager.com.facebook.react.bridge.ReactApplicationContext createReactContext(com.facebook.react.bridge.JavaScriptExecutor,com.facebook.react.bridge.JSBundleLoader)(ReactInstanceManager.java:302)
  | at com.facebook.react.ReactInstanceManager.com.facebook.react.bridge.ReactApplicationContext access$900(com.facebook.react.ReactInstanceManager,com.facebook.react.bridge.JavaScriptExecutor,com.facebook.react.bridge.JSBundleLoader)(ReactInstanceManager.java:1)
  | at com.facebook.react.ReactInstanceManager$5.void run()(ReactInstanceManager.java:244)
  | at java.lang.Thread.run(Thread.java:1012)
```

**Comment by aLittleGreens** [comment]
Thanks for your message

**Comment by shubhamguptadream11** [comment]
@aLittleGreens Without a valid reproducer we can't do anything about this. You use this [template](https://github.com/react-native-community/reproducer-react-native/generate).

Also provide exact steps to repro it.
