### ISSUE TITLE
Fresco WebP dependency causes build error

### ISSUE THREAD

**Issue by vincentsartoko** [facebook/react-native#47204]
### Description

I want to support animated webp images on my app. Following this [documentation](https://reactnative.dev/docs/image#gif-and-webp-support-on-android), I added this line on the build.gradle dependencies block:

```
implementation 'com.facebook.fresco:animated-webp:3.1.3'
implementation 'com.facebook.fresco:webpsupport:3.1.3'
```

When running `npx react-native build-android --mode=release`, this error showed up:

```
> Task :app:minifyReleaseWithR8 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable       
   > Compilation failed to complete
```

### Steps to reproduce

1. Add Fresco dependencies for WebP support
2. Run npx react-native build-android --mode=release
3. It seems like proguard fails

### React Native Version

0.75.4

### Affected Platforms

Build - Windows

### Output of `npx react-native info`

```text
System:
  OS: Windows 10 10.0.19045
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 1.95 GB / 15.85 GB
Binaries:
  Node:
    version: 20.14.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 10.8.1
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowAllTrustedApps: Disabled
    Versions:
      - 10.0.18362.0
IDEs:
  Android Studio: AI-241.15989.150.2411.11948838
  Visual Studio:
    - 16.4.29806.167 (Visual Studio Community 2019)
Languages:
  Java: 17.0.8
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.4
    wanted: 0.75.4
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable       
   > Compilation failed to complete

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 46s
510 actionable tasks: 19 executed, 491 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

error Failed to build the app.
Error: Command failed with exit code 1: gradlew.bat app:bundleRelease
    at makeError (C:\Users\Vincent\Desktop\Lahelu\Codebase\Client\node_modules\execa\lib\error.js:60:11)
    at module.exports.sync (C:\Users\Vincent\Desktop\Lahelu\Codebase\Client\node_modules\execa\index.js:194:17)
    at build (C:\Users\Vincent\Desktop\Lahelu\Codebase\Client\node_modules\@react-native-community\cli-platform-android\build\commands\buildAndroid\index.js:68:22)
    at Object.buildAndroid [as func] (C:\Users\Vincent\Desktop\Lahelu\Codebase\Client\node_modules\@react-native-community\cli-platform-android\build\commands\buildAndroid\index.js:60:10)
    at Command.handleAction (C:\Users\Vincent\Desktop\Lahelu\Codebase\Client\node_modules\@react-native-community\cli\build\index.js:118:23)
    at Command.listener [as _actionHandler] (C:\Users\Vincent\Desktop\Lahelu\Codebase\Client\node_modules\commander\lib\command.js:482:17)
    at C:\Users\Vincent\Desktop\Lahelu\Codebase\Client\node_modules\commander\lib\command.js:1283:65 
    at Command._chainOrCall (C:\Users\Vincent\Desktop\Lahelu\Codebase\Client\node_modules\commander\lib\command.js:1177:12)
    at Command._parseCommand (C:\Users\Vincent\Desktop\Lahelu\Codebase\Client\node_modules\commander\lib\command.js:1283:27)
    at C:\Users\Vincent\Desktop\Lahelu\Codebase\Client\node_modules\commander\lib\command.js:1081:27
```

### Reproducer

-

**Comment by vincentsartoko** [comment]
Solution: add these lines on your `proguard-rules.pro`
-dontwarn com.facebook.imagepipeline.cache.AnimatedCache
-dontwarn com.facebook.imagepipeline.cache.AnimationFrames
-dontwarn com.facebook.imagepipeline.nativecode.WebpTranscoder
