### ISSUE TITLE
Operation Not permitted while archiving.

### ISSUE THREAD

**Issue by riteshshukla04** [facebook/react-native#47259]
### Description

We are currently facing this issue while Archiving our App. If we run the script(replace_hermes_version.js) as standalone through node it works fine. The permission denied issue is thrown only when it runs through Xcode.Tried with sudo and chmod . Nothing works

Thanks in Advance

PS:- This issue arrived recently. We archived two days ago with same codebase and it worked fine 

### Steps to reproduce

Archive the project directly using Xcode or using fastlane

### React Native Version

0.75.2

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.6.1
  CPU: (8) arm64 Apple M2
  Memory: 211.41 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.7.0
    path: ~/.nvm/versions/node/v22.7.0/bin/node
  Yarn:
    version: 1.22.10
    path: ~/Desktop/BFHL/DRxMobile/node_modules/.bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v22.7.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2412.12266719
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/riteshshukla2/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.2
    wanted: 0.75.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
Node found at: /Users/riteshshukla2/.nvm/versions/node/v22.7.0/bin/node
Preparing the final location
node:fs:1502
  const result = binding.readdir(
                         ^

Error: EPERM: operation not permitted, scandir 'hermes-engine'
    at readdirSync (node:fs:1502:26)
    at _rmdirSync (node:internal/fs/rimraf:249:29)
    at rimrafSync (node:internal/fs/rimraf:199:14)
    at Object.rmSync (node:fs:1247:10)
    at replaceHermesConfiguration (/Users/riteshshukla2/Desktop/BFHL/DRxMobile/node_modules/react-native/sdks/hermes-engine/utils/replace_hermes_version.js:60:6)
    at main (/Users/riteshshukla2/Desktop/BFHL/DRxMobile/node_modules/react-native/sdks/hermes-engine/utils/replace_hermes_version.js:79:3)
    at Object.<anonymous> (/Users/riteshshukla2/Desktop/BFHL/DRxMobile/node_modules/react-native/sdks/hermes-engine/utils/replace_hermes_version.js:106:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32) {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: 'hermes-engine'
}

Node.js v22.7.0
Command PhaseScriptExecution failed with a nonzero exit code
```

### Reproducer

N/A

### Screenshots and Videos

<img width="911" alt="Screenshot 2024-10-28 at 11 13 28 PM" src="https://github.com/user-attachments/assets/8ab2b21d-cc41-44af-911b-81819dfa657f">

**Comment by riteshshukla04** [comment]
https://github.com/CocoaPods/Xcodeproj/issues/989

This fixed the issue. Closing this
