### ISSUE TITLE
java.lang.UnsatisfiedLinkError - dlopen failed: library "libhermes.so" not found

### ISSUE THREAD

**Issue by Nader-CS** [facebook/react-native#47274]
### Description

i have this crash on crashlytics , it only happen in Nexus 5X
<img width="1087" alt="Screen Shot 2024-10-29 at 10 58 40 AM" src="https://github.com/user-attachments/assets/700064bb-f63e-4045-80e9-3b2afe6bd4c5">

### Steps to reproduce

1. download app
2. install app
3. open app
4. crash happen

### React Native Version

0.75.4

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 12.7.5
  CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Memory: 34.82 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 20.15.0
    path: ~/.nvm/versions/node/v20.15.0/bin/node
  Yarn:
    version: 4.5.0
    path: ~/.nvm/versions/node/v20.15.0/bin/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v20.15.0/bin/npm
  Watchman:
    version: 2024.07.15.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 21.4
      - iOS 16.0
      - macOS 12.3
      - tvOS 16.0
      - watchOS 9.0
  Android SDK:
    API Levels:
      - "25"
      - "30"
      - "31"
      - "33"
      - "34"
      - "35"
    Build Tools:
      - 24.0.0
      - 24.0.1
      - 24.0.2
      - 24.0.3
      - 30.0.2
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 34.0.0
      - 35.0.0
    System Images:
      - android-26 | Google Play Intel x86 Atom
      - android-34 | Intel x86_64 Atom
      - android-34 | Google APIs Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12169540
  Xcode:
    version: 14.0/14A309
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.4
    wanted: 0.75.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.fnb.ca.ths-y2EOXZSqLqXe8mXJsuizvw==/base.apk"],nativeLibraryDirectories=[/data/app/com.fnb.ca.ths-y2EOXZSqLqXe8mXJsuizvw==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libhermes.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1657)
       at com.facebook.soloader.nativeloader.SystemDelegate.loadLibrary(SystemDelegate.java:24)
       at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:52)
       at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:774)
       at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:26)
       at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
       at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:24)
       at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:407)
       at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:349)
       at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:80)
       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:51)
       at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:294)
       at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:137)
       at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:132)
       at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:47)
       at com.fnb.ca.ths.MainActivity.onCreate(MainActivity.kt:27)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

### Reproducer

i can't produce it

**Comment by Nader-CS** [comment]
```
buildscript {
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 23
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "26.1.10909125"
        kotlinVersion = "1.9.24"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
        classpath 'com.google.gms:google-services:4.4.2'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.2'
    }
}

apply plugin: "com.facebook.react.rootproject"

```

**Comment by ertugruldogan** [comment]
The source of the problem is in the MainActivity.kt file.
Paste the MainActivity.kt file content here.

**Comment by CVHOANG-coder** [comment]
i'm facing same problem
MainActivity.java here:

```
package com.....;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint;
import com.facebook.react.defaults.DefaultReactActivityDelegate;
import android.os.Bundle;
import org.devio.rn.splashscreen.SplashScreen;

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "AI_MUSIC";
  }
  @Override
  protected void onCreate(Bundle savedInstanceState) {
      SplashScreen.show(this);
      // super.onCreate(savedInstanceState);
      super.onCreate(null);//fix react-native-screens and react-navigation
  }

  /**
   * Returns the instance of the {@link ReactActivityDelegate}. Here we use a util class {@link
   * DefaultReactActivityDelegate} which allows you to easily enable Fabric and Concurrent React
   * (aka React 18) with two boolean flags.
   */
  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new DefaultReactActivityDelegate(
        this,
        getMainComponentName(),
        // If you opted-in for the New Architecture, we enable the Fabric Renderer.
        DefaultNewArchitectureEntryPoint.getFabricEnabled());
  }

}
```

and MainApplication.java here:
```
package com.....;

import android.app.Application;
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint;
import com.facebook.react.defaults.DefaultReactNativeHost;
import com.facebook.soloader.SoLoader;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost =
      new DefaultReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
          return packages;
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }

        @Override
        protected boolean isNewArchEnabled() {
          return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
        }

        @Override
        protected Boolean isHermesEnabled() {
          return BuildConfig.IS_HERMES_ENABLED;
        }
      };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      // If you opted-in for the New Architecture, we load the native entry point for this app.
      DefaultNewArchitectureEntryPoint.load();
    }
    ReactNativeFlipper.initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
  }
}
```

**Comment by ertugruldogan** [comment]
> i'm facing same problem MainActivity.java here:
------
These rules are from the old RN version before 0.73.x. If your RN version is 0.73.x or later, you should definitely use these.

It translates the software into Kotlin language for easy understanding.

https://react-native-community.github.io/upgrade-helper/?from=0.72.17&to=0.73.10

MainActivity.java = MainActivity.kt
MainApplication.java = MainApplication.kt

**Comment by Nader-CS** [comment]
this is my own


```
package com.fnb.ca.ths

import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate
import android.os.Bundle;
import com.zoontek.rnbootsplash.RNBootSplash;

class MainActivity : ReactActivity() {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  override fun getMainComponentName(): String = "TimHortons"

  /**
   * Returns the instance of the [ReactActivityDelegate]. We use [DefaultReactActivityDelegate]
   * which allows you to enable New Architecture with a single boolean flags [fabricEnabled]
   */
  override fun createReactActivityDelegate(): ReactActivityDelegate =
      DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)

  override fun onCreate(savedInstanceState: Bundle?) {
      RNBootSplash.init(this, R.style.BootTheme) // ⬅️ initialize the splash screen
      super.onCreate(null)
  }
}
```


```

package com.fnb.ca.ths

import android.app.Application
import com.facebook.react.PackageList
import com.facebook.react.ReactApplication
import com.facebook.react.ReactHost
import com.facebook.react.ReactNativeHost
import com.facebook.react.ReactPackage
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.load
import com.facebook.react.defaults.DefaultReactHost.getDefaultReactHost
import com.facebook.react.defaults.DefaultReactNativeHost
import com.facebook.soloader.SoLoader
import com.microsoft.codepush.react.CodePush

class MainApplication : Application(), ReactApplication {

  override val reactNativeHost: ReactNativeHost =
      object : DefaultReactNativeHost(this) {
        override fun getPackages(): List<ReactPackage> =
            PackageList(this).packages.apply {
              // Packages that cannot be autolinked yet can be added manually here, for example:
              // add(MyReactNativePackage())
            }

        override fun getJSMainModuleName(): String = "index"
        override fun getUseDeveloperSupport(): Boolean = BuildConfig.DEBUG
        override fun getJSBundleFile(): String {
          return CodePush.getJSBundleFile() 
        }
        override val isNewArchEnabled: Boolean = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED
        override val isHermesEnabled: Boolean = BuildConfig.IS_HERMES_ENABLED
      }

  override val reactHost: ReactHost
    get() = getDefaultReactHost(applicationContext, reactNativeHost)

  override fun onCreate() {
    super.onCreate()
    SoLoader.init(this, false)
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      // If you opted-in for the New Architecture, we load the native entry point for this app.
      load()
    }
  }
}
```

**Comment by ertugruldogan** [comment]
I think these files belong to the RN version 0.75.x configuration.

MainActivity.kt
If you want notification permission for Android 13 and above, I added it.
super.onCreate(null) illogical
My advice is to remove "fabricEnabled" completely from the MainActivity.kt file if not used.

```kotlin
package com.fnb.ca.ths

import android.Manifest
import androidx.core.app.ActivityCompat
import android.content.pm.PackageManager
import android.os.Build
import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate
import android.os.Bundle
import com.zoontek.rnbootsplash.RNBootSplash

class MainActivity : ReactActivity() {

  override fun getMainComponentName(): String = "TimHortons"

  override fun createReactActivityDelegate(): ReactActivityDelegate =
      DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)

  override fun onCreate(savedInstanceState: Bundle?) {
      super.onCreate(savedInstanceState)
      RNBootSplash.init(this, R.style.BootTheme)
      setNotifications()
  }

  private fun setNotifications() {
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
          if (ActivityCompat.checkSelfPermission(this, Manifest.permission.POST_NOTIFICATIONS) != PackageManager.PERMISSION_GRANTED) {
              requestPermissions(arrayOf(Manifest.permission.POST_NOTIFICATIONS), REQUEST_CODE_NOTIFICATIONS)
          }
      }
  }

  companion object {
      private const val REQUEST_CODE_NOTIFICATIONS = 1
  }
}

``` 


MainApplication.kt

```kotlin
package com.fnb.ca.ths

import android.app.Application
import com.facebook.react.PackageList
import com.facebook.react.ReactApplication
import com.facebook.react.ReactHost
import com.facebook.react.ReactNativeHost
import com.facebook.react.ReactPackage
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.load
import com.facebook.react.defaults.DefaultReactHost.getDefaultReactHost
import com.facebook.react.defaults.DefaultReactNativeHost
import com.facebook.soloader.SoLoader
import com.microsoft.codepush.react.CodePush

class MainApplication : Application(), ReactApplication {

  override val reactNativeHost: ReactNativeHost =
      object : DefaultReactNativeHost(this) {
        override fun getPackages(): List<ReactPackage> =
            PackageList(this).packages.apply {
            }

        override fun getJSMainModuleName(): String = "index"
        
        override fun getUseDeveloperSupport(): Boolean = BuildConfig.DEBUG

        override fun getJSBundleFile(): String {
          return CodePush.getJSBundleFile() 
        }

        override val isNewArchEnabled: Boolean = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED

        override val isHermesEnabled: Boolean = BuildConfig.IS_HERMES_ENABLED
      }

  override val reactHost: ReactHost
    get() = getDefaultReactHost(applicationContext, reactNativeHost)

  override fun onCreate() {
    super.onCreate()
    SoLoader.init(this, false)
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      load() 
    }
  }
}

```

**Comment by cortinico** [comment]
Closing as duplicate of a lot of similar issues that got already opened and resolved:
https://github.com/facebook/react-native/issues?q=library+%22libhermes.so%22+not+found

**Comment by Nader-CS** [comment]
> I think these files belong to the RN version 0.75.x configuration.
> 
> MainActivity.kt If you want notification permission for Android 13 and above, I added it. super.onCreate(null) illogical My advice is to remove "fabricEnabled" completely from the MainActivity.kt file if not used.
> 
> ```kotlin
> package com.fnb.ca.ths
> 
> import android.Manifest
> import androidx.core.app.ActivityCompat
> import android.content.pm.PackageManager
> import android.os.Build
> import com.facebook.react.ReactActivity
> import com.facebook.react.ReactActivityDelegate
> import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
> import com.facebook.react.defaults.DefaultReactActivityDelegate
> import android.os.Bundle
> import com.zoontek.rnbootsplash.RNBootSplash
> 
> class MainActivity : ReactActivity() {
> 
>   override fun getMainComponentName(): String = "TimHortons"
> 
>   override fun createReactActivityDelegate(): ReactActivityDelegate =
>       DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)
> 
>   override fun onCreate(savedInstanceState: Bundle?) {
>       super.onCreate(savedInstanceState)
>       RNBootSplash.init(this, R.style.BootTheme)
>       setNotifications()
>   }
> 
>   private fun setNotifications() {
>       if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
>           if (ActivityCompat.checkSelfPermission(this, Manifest.permission.POST_NOTIFICATIONS) != PackageManager.PERMISSION_GRANTED) {
>               requestPermissions(arrayOf(Manifest.permission.POST_NOTIFICATIONS), REQUEST_CODE_NOTIFICATIONS)
>           }
>       }
>   }
> 
>   companion object {
>       private const val REQUEST_CODE_NOTIFICATIONS = 1
>   }
> }
> ```
> 
> MainApplication.kt
> 
> ```kotlin
> package com.fnb.ca.ths
> 
> import android.app.Application
> import com.facebook.react.PackageList
> import com.facebook.react.ReactApplication
> import com.facebook.react.ReactHost
> import com.facebook.react.ReactNativeHost
> import com.facebook.react.ReactPackage
> import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.load
> import com.facebook.react.defaults.DefaultReactHost.getDefaultReactHost
> import com.facebook.react.defaults.DefaultReactNativeHost
> import com.facebook.soloader.SoLoader
> import com.microsoft.codepush.react.CodePush
> 
> class MainApplication : Application(), ReactApplication {
> 
>   override val reactNativeHost: ReactNativeHost =
>       object : DefaultReactNativeHost(this) {
>         override fun getPackages(): List<ReactPackage> =
>             PackageList(this).packages.apply {
>             }
> 
>         override fun getJSMainModuleName(): String = "index"
>         
>         override fun getUseDeveloperSupport(): Boolean = BuildConfig.DEBUG
> 
>         override fun getJSBundleFile(): String {
>           return CodePush.getJSBundleFile() 
>         }
> 
>         override val isNewArchEnabled: Boolean = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED
> 
>         override val isHermesEnabled: Boolean = BuildConfig.IS_HERMES_ENABLED
>       }
> 
>   override val reactHost: ReactHost
>     get() = getDefaultReactHost(applicationContext, reactNativeHost)
> 
>   override fun onCreate() {
>     super.onCreate()
>     SoLoader.init(this, false)
>     if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
>       load() 
>     }
>   }
> }
> ```

thanks , but in react native screen documentation is typed  super.onCreate(null)

**Comment by Nader-CS** [comment]
> > i'm facing same problem MainActivity.java here:
> 
> These rules are from the old RN version before 0.73.x. If your RN version is 0.73.x or later, you should definitely use these.
> 
> It translates the software into Kotlin language for easy understanding.
> 
> https://react-native-community.github.io/upgrade-helper/?from=0.72.17&to=0.73.10
> 
> MainActivity.java = MainActivity.kt MainApplication.java = MainApplication.kt

.

> Closing as duplicate of a lot of similar issues that got already opened and resolved: https://github.com/facebook/react-native/issues?q=library+%22libhermes.so%22+not+found

is still exist and there no defined solution

**Comment by anil-punchh** [comment]
Yes please define any solution, for me using RN version 0.73.8, pleas confirm if it's fixed in latest RN version.

**Comment by benohiit** [comment]
In my case I forgot to add this in app/build/gradle

```
dependencies {
....
    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }
}
```
