### ISSUE TITLE
android suddenly stuck on network error

### ISSUE THREAD

**Issue by mtaher1996** [facebook/react-native#47370]
### Description

I am encountering an issue with my React Native application where some devices are experiencing network errors despite being connected to a Wi-Fi network. This problem persists for approximately one day before the devices resume normal functionality.

Attempts to resolve this issue have proven unsuccessful. The following steps have been taken without success:

1. Restarting the network.
2. Reinstalling the application.
3. Rebooting the device.
4. Switching to cellular data instead of Wi-Fi.

The affected devices remain in this state for around 24 hours before returning to normal operation.

### Steps to reproduce

This issue occurred unexpectedly on production for certain Android devices and cannot be replicated consistently. However, it appears to occur when the device switches networks or when the internet connection is slow.

### React Native Version

0.74.1

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 15.0.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 127.36 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.10.0
    path: ~/.nvm/versions/node/v22.10.0/bin/node
  Yarn:
    version: 3.6.4
    path: ~/Documents/work/ukkera/projects/ukkera_student_app/node_modules/.bin/yarn
  npm:
    version: 10.9.0
    path: ~/.nvm/versions/node/v22.10.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/mtaher/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12169540
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.8
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/mtaher/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
{
  "message": "Network Error",
  "name": "AxiosError",
  "stack": "AxiosError: Network Error\n    at anonymous (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:1556:1290)\n    at call (native)\n    at dispatchEvent (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:136:5650)\n    at value (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:129:8891)\n    at value (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:129:4822)\n    at apply (native)\n    at anonymous (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:129:7606)\n    at apply (native)\n    at value (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:52:789)\n    at apply (native)\n    at anonymous (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:49:906)\n    at value (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:49:915)\n    at apply (native)\n    at value (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:37:3898)\n    at anonymous (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:37:694)\n    at value (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:37:2529)\n    at value (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:37:665)\n    at ?anon_0_ (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:1532:629)\n    at throw (native)\n    at n (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:7:74)\n    at s (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:7:322)\n    at tryCallOne (address at InternalBytecode.js:1:1180)\n    at anonymous (address at InternalBytecode.js:1:1874)\n    at apply (native)\n    at anonymous (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:123:1668)\n    at k (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:123:499)\n    at w (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:123:889)\n    at callReactNativeMicrotasks (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:123:3059)\n    at value (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:37:2897)\n    at anonymous (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:37:984)\n    at value (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:37:2529)\n    at value (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:37:942)\n    at value (/data/user/0/com.ukkera.student/files/CodePush/44b7e2c3628b0100789c76ed4c664c5d0f2862ce56c593bf4044d93ed26de5c3/CodePush/index.android.bundle:37:722)",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "adapter": [
      "xhr",
      "http",
      "fetch"
    ],
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {},
    "headers": {
      "Accept": "application/json",
      "Content-Type": "application/json",
      "lang": "ar"
    },
    "method": "post",
    "url": "https://apis.ukkera.com/api/v1/student/private/gate",
    "data": "{\"user\":\"01032176793\",\"password\":\"\",\"password_confirmation\":\"\",\"device_id\":\"dde318d99ccc05f3\",\"device_type\":\"RMX3261 application\"}"
  },
  "code": "ERR_NETWORK"
}
```

### Reproducer

private repo

**Comment by SatyamBansal** [comment]
We're encountering a similar issue in our production environment after upgrading React Native from `0.72.4` to `0.75.3` . Since the update, we've received numerous user reports where network requests fail entirely, never reaching our servers.

In Sentry, I noticed that other XHR requests are also failing during these periods, including requests to https://clients3.google.com made by the [react-native-netinfo](https://github.com/react-native-netinfo/react-native-netinfo) library. When this happens, users are completely blocked, and the issue seems to resolve on its own after anywhere between 30 minutes to a full day.

**Comment by Shasikhan** [comment]
We also faced this issue on our Live Android App from Google play store. Strange thing is that our STAGING and PRE-RELEASE endpoints were getting hit but not LIVE. So it was real pain because our users were getting effected. After debugging and testing many things whole day, Play store app started working again from nowwhere. 

So if this issue occurs to any of you again, don't panic, just check from your side that everything is OK e.g., server, app code. If thats OK than you should not worry.

**Comment by Nader-CS** [comment]
happened to me , please any advice ?

**Comment by Shasikhan** [comment]
@Nader-CS I think there is nothing you can do, because in same code base, other domain apis were working fine for us but prductuon domain api were having this issue, it got solved after 1 day.
