### ISSUE TITLE
bundler: failed to load command: pod (/Users/runner/work/1/s/vendor/bundle/ruby/3.3.0/bin/pod)

### ISSUE THREAD

**Issue by hoanghai9650** [facebook/react-native#47584]
### Description

I already have an React Native project before and already setup CI/CD for it by using Azure DevOps. But now when I upgraded to new arch 0.76, it failed when pod install.

My script for pod install: (I already have a script for bundle install inside this file)

```
- script: |
      export RUBY_THREAD_VM_STACK_SIZE=1000000
      export RCT_NEW_ARCH_ENABLED=1
      bundle exec pod install
    displayName: 'iOS | CocoaPods packages installing with new architecture'
    workingDirectory: '$(Build.SourcesDirectory)/ios'
    condition: ne(variables['cache_pods_restored'], 'true')
```
activesupport 7.0.8.6
ruby 3.3.0
algoliasearch 1.27.5
cocoapods-core 1.14.3

### Steps to reproduce

 run  bundle exec pod install in Azure DevOps pipeline

### React Native Version

0.76.1

### Affected Platforms

Build - MacOS

### Areas

Bridgeless - The New Initialization Flow, Codegen

### Output of `npx react-native info`

```text
System:
  OS: macOS 15.1
  CPU: (11) arm64 Apple M3 Pro
  Memory: 7.25 GB / 36.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.9.0
    path: ~/.nvm/versions/node/v22.9.0/bin/node
  Yarn:
    version: 4.5.1
    path: ~/Desktop/Catalogue-Solutions-Mobile/node_modules/.bin/yarn
  npm:
    version: 10.8.3
    path: ~/.nvm/versions/node/v22.9.0/bin/npm
  Watchman:
    version: 2024.10.07.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.21829.142.2421.12409432
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.3.5
    path: /opt/homebrew/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.0
    wanted: 15.0.0
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.1
    wanted: ^0.76.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
bundler: failed to load command: pod (/Users/runner/work/1/s/vendor/bundle/ruby/3.3.0/bin/pod)
SystemStackError: stack level too deep
  /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/stub_specification.rb:230:in `loaded_spec'
  /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/stub_specification.rb:186:in `spec'
  /Users/runner/work/1/s/vendor/bundle/ruby/3.3.0/gems/bundler-2.1.4/lib/bundler/stub_specification.rb:78:in `_remote_specification'
  /Users/runner/work/1/s/vendor/bundle/ruby/3.3.0/gems/bundler-2.1.4/lib/bundler/remote_specification.rb:104:in `method_missing'
  /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/stub_specification.rb:231:in `loaded_spec'
  /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/stub_specification.rb:186:in `spec'
  /Users/runner/work/1/s/vendor/bundle/ruby/3.3.0/gems/bundler-2.1.4/lib/bundler/stub_specification.rb:78:in `_remote_specification'
  /Users/runner/work/1/s/vendor/bundle/ruby/3.3.0/gems/bundler-2.1.4/lib/bundler/remote_specification.rb:104:in `method_missing'
  /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/stub_specification.rb:231:in `loaded_spec'
  /usr/local/lib/ruby/site_ruby/3.3.0/rubygems/stub_specification.rb:186:in `spec'
```

### Reproducer

donthave

**Comment by indapublic** [comment]
@hoanghai9650 I have same issue with 0.76 (but not for 0.75), could you attach your solution?
