### ISSUE TITLE
Android build issue using RN version: 0.76.3 and Expo version 52.0.11

### ISSUE THREAD

**Issue by abdulwahid211** [facebook/react-native#47961]
### Description

After updating to the package React native: 0.76.3 and Expo 52.0.11, i'm not able to build android locally using the Expo command `npx expo run:android`. This also wont work for  `./gradlew build` when you run in the android folder. 

These are my dependencies from package.json
```
  "dependencies": {
    "@microsoft/signalr": "^8.0.0",
    "@react-native-async-storage/async-storage": "1.23.01",
    "@react-native-community/geolocation": "^3.2.1",
    "@react-native-community/hooks": "^3.0.0",
    "@react-native-masked-view/masked-view": "^0.3.2",
    "@react-native-vector-icons/fontawesome": "^4.7.0-alpha.32",
    "@react-navigation/drawer": "^7.0.7",
    "@react-navigation/native": "^7.0.4",
    "@react-navigation/native-stack": "7.1.1",
    "@reduxjs/toolkit": "^2.3.0",
    "@shopify/flash-list": "^1.7.2",
    "axios": "^1.6.7",
    "expo": "^52.0.11",
    "expo-camera": "16.0.7",
    "expo-dev-client": "^4.0.28",
    "expo-file-system": "~17.0.1",
    "expo-linking": "^6.3.1",
    "expo-location": "^17.0.1",
    "expo-sharing": "^12.0.1",
    "expo-status-bar": "~1.12.1",
    "expo-task-manager": "~11.8.2",
    "expo-updates": "^0.25.27",
    "haversine-distance": "^1.2.3",
    "moment": "^2.30.1",
    "node-signalr": "^3.0.0-alpha.1",
    "react": "18.2.0",
    "react-native": "0.76.3",
    "react-native-bouncy-checkbox": "^3.0.7",
    "react-native-element-dropdown": "^2.12.1",
    "react-native-gesture-handler": "2.20.2",
    "react-native-get-random-values": "~1.11.0",
    "react-native-maps": "1.18.0",
    "react-native-maps-directions": "^1.9.0",
    "react-native-maps-routes": "^1.0.3",
    "react-native-modal": "^13.0.1",
    "react-native-pager-view": "6.3.0",
    "react-native-safe-area-context": "^4.14.0",
    "react-native-screens": "^4.0.0",
    "react-native-tab-view": "^3.5.2",
    "react-native-url-polyfill": "^2.0.0",
    "react-native-vector-icons": "^10.2.0",
    "react-redux": "^9.1.2"
  },
```

Platform: WIndows 
Java:  ```java 17.0.12 2024-07-16 LTS```

### Steps to reproduce

1) Make sure you are using the React Native: 0.76.3 and Expo  52.0.11

2) npx expo prebuild

3) npx expo run:android

### React Native Version

0.76.3

### Affected Platforms

Build - Windows

### Areas

TurboModule - The New Native Module System

### Output of `npx react-native info`

```text
"devDependencies": {
    "@react-native-community/cli": "latest",
  }
```

### Stacktrace or Logs

```text
npx expo run:android 

› Building app...
Configuration on demand is an incubating feature.

> Configure project :app
 ??  Applying gradle plugin 'expo-dev-launcher-gradle-plugin' (expo-dev-launcher@4.0.28)
 ??  Applying gradle plugin 'expo-updates-gradle-plugin' (expo-updates@0.25.27)

> Configure project :expo

Using expo modules
  - expo-asset (11.0.1)
  - expo-camera (16.0.7)
  - expo-constants (16.0.2)
  - expo-dev-client (4.0.28)
  - expo-dev-launcher (4.0.28)
  - expo-dev-menu (5.0.22)
  - expo-eas-client (0.12.0)
  - expo-file-system (17.0.1)
  - expo-font (13.0.1)
  - expo-json-utils (0.13.1)
  - expo-keep-awake (14.0.1)
  - expo-location (17.0.1)
  - expo-manifests (0.14.3)
  - expo-modules-core (2.0.6)
  - expo-sharing (12.0.1)
  - expo-structured-headers (3.8.0)
  - expo-task-manager (11.8.2)
  - expo-updates (0.25.27)
  - unimodules-app-loader (4.6.0)


> Task :expo-task-manager:compileDebugJavaWithJavac FAILED
C:\dev\TrackingProject\client\mobile\node_modules\expo-task-manager\android\src\main\java\expo\modules\taskManager\TaskManagerUtils.java:30: error: TaskManagerUtils is not abstract and does not override abstract method executeTask(TaskInterface,Bundle) in TaskManagerUtilsInterface
public class TaskManagerUtils implements TaskManagerUtilsInterface {
       ^
Note: C:\dev\TrackingProject\client\mobile\node_modules\expo-task-manager\android\src\main\java\expo\modules\taskManager\TaskService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

> Task :expo-dev-menu-interface:compileDebugKotlin FAILED
e: file:///C:/dev/TrackingProject/client/mobile/node_modules/expo-dev-menu-interface/android/src/main/java/expo/interfaces/devmenu/ReactHostWrapper.kt:79:30 Unresolved reference: jsEngineResolutionAlgorithm

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':expo-task-manager:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':expo-dev-menu-interface:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 36s
452 actionable tasks: 37 executed, 415 up-to-date
Error: C:\dev\TrackingProject\client\mobile\android\gradlew.bat app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a,armeabi-v7a exited with non-zero code: 1
Error: C:\dev\TrackingProject\client\mobile\android\gradlew.bat app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a,armeabi-v7a exited with non-zero code: 1
    at ChildProcess.completionListener (C:\dev\TrackingProject\client\mobile\node_modules\@expo\spawn-async\src\spawnAsync.ts:67:13)
    at Object.onceWrapper (node:events:634:26)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess.cp.emit (C:\dev\TrackingProject\client\mobile\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1105:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (C:\dev\TrackingProject\client\mobile\node_modules\@expo\spawn-async\src\spawnAsync.ts:28:21)
    at spawnGradleAsync (C:\dev\TrackingProject\client\mobile\node_modules\@expo\cli\src\start\platforms\android\gradle.ts:134:28)
    at assembleAsync (C:\dev\TrackingProject\client\mobile\node_modules\@expo\cli\src\start\platforms\android\gradle.ts:83:16)
    at runAndroidAsync (C:\dev\TrackingProject\client\mobile\node_modules\@expo\cli\src\run\android\runAndroidAsync.ts:48:24)
```

### Reproducer

n/A

**Comment by abdulwahid211** [comment]
soleved! 

updating the relevant dependecies using `npx expo-doctor@latest` did help :)
