### ISSUE TITLE
[Android] App crashes when scrolling in a ListView

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#4842]
Transformed `ListView` crashes when scrolling and reaches the end. It doesn't happen consistently though. In smaller lists, it doesn't crash at all.

Android 5.0, React Native 0.17.0-rc.

Here is the stack trace.

```java
12-17 18:27:32.765 10855-10855/io.scrollback.neighborhoods E/AndroidRuntime: FATAL EXCEPTION: main
 Process: io.scrollback.neighborhoods, PID: 10855
 java.lang.AssertionError
     at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:21)
     at com.facebook.react.uimanager.RootViewUtil.getRootView(RootViewUtil.java:29)
     at com.facebook.react.uimanager.NativeViewHierarchyManager.measure(NativeViewHierarchyManager.java:469)
     at com.facebook.react.uimanager.UIViewOperationQueue$MeasureOperation.execute(UIViewOperationQueue.java:372)
     at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:673)
     at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:723)
     at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
     at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:120)
     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
     at android.view.Choreographer.doCallbacks(Choreographer.java:580)
     at android.view.Choreographer.doFrame(Choreographer.java:549)
     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
     at android.os.Handler.handleCallback(Handler.java:746)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:135)
     at android.app.ActivityThread.main(ActivityThread.java:5343)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
```

**Comment by satya164** [comment]
cc @ide since you've experience with transformed list views

**Comment by ide** [comment]
I get this error with non-transformed list views too.

**Comment by satya164** [comment]
@ide Oh, it was hard to say, as it doesn't always happen. I changed the title.

**Comment by satya164** [comment]
@ide Have you found the reason, or any workarounds?

**Comment by Geequlim** [comment]
The same issue. 0.16 and 0.14 doesn't appeared.

**Comment by ide** [comment]
This is fixed in https://github.com/facebook/react-native/commit/e6d498b99b984187a56991c112c6d5df160ad538

**Comment by satya164** [comment]
May be we should cherry-pick this to 0.17.1? @mkonicek

**Comment by Kudo** [comment]
Facing the same issue and would like to see this would be a patch for 0.17

**Comment by hugoh1995** [comment]
Facing same issue
