### ISSUE TITLE
Failed to start project if .babelrc is added

### ISSUE THREAD

**Issue by am5a03** [facebook/react-native#4882]
I've added a .babelrc in my project's root directory
```
{
  "whitelist": [
    "es7.classProperties",
    "es7.decorators"
  ]
}

```
It cannot be started, I got the same error message as in https://github.com/facebook/react-native/issues/4690
```
C:\Users\Raymond\workspace\ReactNativeProjs\JGolden\node_modules\babel-core\lib\transformation\file\logger.js:41
    throw new Constructor(this._buildMessage(msg));
    ^

ReferenceError: [BABEL] C:\Users\Raymond\workspace\ReactNativeProjs\JGolden\node_modules\react-native\local-cli\bundle\bundle.js: Unknown option: base.whitelist
    at Logger.error (C:\Users\Raymond\workspace\ReactNativeProjs\JGolden\node_modules\babel-core\lib\transformation\file\logger.js:41:11)
    at OptionManager.mergeOptions (C:\Users\Raymond\workspace\ReactNativeProjs\JGolden\node_modules\babel-core\lib\transformation\file\options\option-manager.js:262:18)
    at OptionManager.init (C:\Users\Raymond\workspace\ReactNativeProjs\JGolden\node_modules\babel-core\lib\transformation\file\options\option-manager.js:416:10)
    at File.initOptions (C:\Users\Raymond\workspace\ReactNativeProjs\JGolden\node_modules\babel-core\lib\transformation\file\index.js:191:75)
    at new File (C:\Users\Raymond\workspace\ReactNativeProjs\JGolden\node_modules\babel-core\lib\transformation\file\index.js:122:22)
    at Pipeline.transform (C:\Users\Raymond\workspace\ReactNativeProjs\JGolden\node_modules\babel-core\lib\transformation\pipeline.js:42:16)
    at Object.transformFileSync (C:\Users\Raymond\workspace\ReactNativeProjs\JGolden\node_modules\babel-core\lib\api\node.js:116:10)
    at compile (C:\Users\Raymond\workspace\ReactNativeProjs\JGolden\node_modules\babel-register\lib\node.js:102:20)
    at loader (C:\Users\Raymond\workspace\ReactNativeProjs\JGolden\node_modules\babel-register\lib\node.js:130:14)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Raymond\workspace\ReactNativeProjs\JGolden\node_modules\babel-register\lib\node.js:140:7)
```

However, this .babelrc works in one of my previous projects, which is using react-native 0.14.2
Here is an excerpt of the dependency of this new project:

```
PS C:\Users\Raymond\workspace\ReactNativeProjs\JGolden> npm ls
JGolden@0.0.1 C:\Users\Raymond\workspace\ReactNativeProjs\JGolden
└─┬ react-native@0.17.0
  ├── absolute-path@0.0.0
  ├── art@0.10.0
  ├─┬ babel-core@6.3.21
  │ ├─┬ babel-code-frame@6.3.13
```

And the dependency of my old project
```
├─┬ react-native@0.14.2
│ ├── absolute-path@0.0.0
│ ├─┬ babel@5.8.34
```

Both are using exactly the same .babelrc, but the new project simply doesn't start. 
I tried to copy `node_modules` to my new project, and it starts.

**Comment by ms88privat** [comment]
@am5a03 since v0.16.0 React Native uses BABEL6, which currently does not support decorators, so they will not work. From the Release notes: `JS decorators won't work until` [T2645](https://phabricator.babeljs.io/T2645) `lands in Babel. It's being worked on. The proposal for decorators is not final and therefore Babel 6 left decorator support out for now.`

And since then also .barbelrc are not supported anymore. You have to remove them from any other node_module too. Please have a look at this related issue https://github.com/facebook/react-native/issues/4062

**Comment by christopherdro** [comment]
Closing for #4062
