### ISSUE TITLE
[Error: Watcher took too long to load]

### ISSUE THREAD

**Issue by LeezQ** [facebook/react-native#490]
![image](https://cloud.githubusercontent.com/assets/972813/6895584/6187397a-d714-11e4-9a11-95ac82e7a17b.png)

this error often happen in my computer, how can I avoid this ?

**Comment by ksmithut** [comment]
From the [docs](http://facebook.github.io/react-native/docs/getting-started.html) try step 5:

>  `brew install watchman`. We recommend installing watchman, otherwise you might hit a node file watching bug.

**Comment by amasad** [comment]
Does it happen only some of time?
I'll increase the timeout

**Comment by LeezQ** [comment]
@amasad , yes , some of time ... and I think it's watchman's problem. because when I have no process to run watchman, it also tell me  `please shut down any existing instances that are already running`

**Comment by cxfeng1** [comment]
same here

**Comment by chucai** [comment]
I got the same error on my macbook. Is there any solution to fix it?

**Comment by amasad** [comment]
Can you try the steps in the troubleshooting? 

http://facebook.github.io/react-native/docs/troubleshooting.html#watchman-took-too-long-to-load

**Comment by chucai** [comment]
Hi @amasad, 

The solution didn't fix my issue ... :sob: 
```
[Error: Watcher took too long to load
Try running `watchman` from your terminal
https://facebook.github.io/watchman/docs/troubleshooting.html]
Error: Watcher took too long to load
Try running `watchman` from your terminal
https://facebook.github.io/watchman/docs/troubleshooting.html
    at null._onTimeout (/Users/xdhe/Documents/projects/react/react-native/HackerNews-React-Native/node_modules/react-native/packager/react-packager/src/FileWatcher/index.js:71:16)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

  >>> ERROR: could not create packager - please shut down any existing instances that are already running.

```
I got the message after I run the command `watchman` in my terminal. 
```
$ watchman
{
    "error": "invalid command (expected an array with some elements!)",
    "cli_validated": true,
    "version": "3.1.0"
}
```

**Comment by amasad** [comment]
@chucai There are some steps here to help you debug https://github.com/facebook/watchman/issues/90#issuecomment-87427749
cc @wez

**Comment by chucai** [comment]
Hi @amasad  & @wez ,

Thanks for you comments. This is my debug log. 

```
1428027461: tid=2142380816 Using watcher mechanism fsevents
1428027461: tid=2142380816 file limit is 256 kern.maxfilesperproc=10240
1428027461: tid=2142380816 raised file limit to 10240
1428027461: tid=2142380816 Using socket from launchd as listening socket
1428027461: tid=2142380816 failed to parse json from /usr/local/Cellar/watchman/HEAD/var/run/watchman/xdhe.state: unable to open /usr/local/Cellar/watchman/HEAD/var/run/watchman/xdhe.state: No such file or directory
1428046836: tid=2142380816 Using watcher mechanism fsevents
1428046836: tid=2142380816 file limit is 256 kern.maxfilesperproc=10240
1428046836: tid=2142380816 raised file limit to 10240
1428046836: tid=2142380816 Using socket from launchd as listening socket
1428046836: tid=2142380816 failed to parse json from /usr/local/Cellar/watchman/HEAD/var/run/watchman/xdhe.state: unable to open /usr/local/Cellar/watchman/HEAD/var/run/watchman/xdhe.state: No such file or directory
1428047359: tid=2142380816 Using watcher mechanism fsevents
1428047359: tid=2142380816 file limit is 256 kern.maxfilesperproc=20480
1428047359: tid=2142380816 raised file limit to 20480
1428047359: tid=2142380816 Using socket from launchd as listening socket
1428047359: tid=2142380816 failed to parse json from /usr/local/Cellar/watchman/HEAD/var/run/watchman/xdhe.state: unable to open /usr/local/Cellar/watchman/HEAD/var/run/watchman/xdhe.state: No such file or directory
1428047413: tid=2142380816 Using watcher mechanism fsevents
1428047413: tid=2142380816 file limit is 256 kern.maxfilesperproc=20480
1428047413: tid=2142380816 raised file limit to 20480
1428047413: tid=2142380816 Using socket from launchd as listening socket
1428047413: tid=2142380816 failed to parse json from /usr/local/Cellar/watchman/HEAD/var/run/watchman/xdhe.state: '[' or '{' expected near end of file
1428047495: tid=2142380816 Using watcher mechanism fsevents
1428047495: tid=2142380816 file limit is 256 kern.maxfilesperproc=20480
1428047495: tid=2142380816 raised file limit to 20480
1428047495: tid=2142380816 Using socket from launchd as listening socket
1428047536: tid=2142380816 Using watcher mechanism fsevents
1428047536: tid=2142380816 file limit is 256 kern.maxfilesperproc=20480
1428047536: tid=2142380816 raised file limit to 20480
1428047536: tid=2142380816 Using socket from launchd as listening socket
```

The `xdhe.state` file is created by myself. Its content is very simple:
```
#xdhe.state
{}
```

**Comment by chucai** [comment]
I fixed my issue with the following commands.

```
brew uninstall watchman

brew install --HEAD watchman 

watchman watch-list 

sudo chmod +x /usr/local/Cellar/watchman/HEAD/bin/watchman
```

Thanks @amasad .

**Comment by holyspectral** [comment]
I had the same issue, but later I found somehow /Users/XXX/Library/LaunchAgents/ is belonged to root.
After chown, everything works.

**Comment by raichur** [comment]
Thanks, @chucai. That solved it for me.

**Comment by amasad** [comment]
Seems to be resolved, closing for now. Feel free to reopen if you're still seeing the issue.
