### ISSUE TITLE
Error building DependencyGraph: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by cancan101** [facebook/react-native#4905]
I am on RN 0.17 and I get the following when running `react-native start --reset-cache`:
```
<START> Building Haste Map
[1:00:05 AM] <START> Building (deprecated) Asset Map
Error building DependencyGraph:
 RangeError: Maximum call stack size exceeded
    at fastfs.js:300:19
    at Array.forEach (native)
    at File.getFiles (fastfs.js:297:32)
    at fastfs.js:79:54
    at Array.map (native)
    at Fastfs.getAllFiles (fastfs.js:79:37)
    at Fastfs.findFilesByExts (fastfs.js:87:17)
    at HasteMap.build (HasteMap.js:27:33)
    at index.js:125:33
    at tryCallOne (/Users/alex/git/Mobile-RN/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
```
This might be related to https://github.com/facebook/react-native/issues/4516 but I am not using symlinks.

my `.babelrc` files looks like:
```
{
  "presets": ["es2015"],
  "plugins": [
    "transform-decorators-legacy",
    "transform-es2015-classes",
    "transform-export-extensions",
    "transform-runtime"
  ]
}
```

**Comment by cancan101** [comment]
This issue went away when I `rm -rf node_modeules`.

**Comment by ide** [comment]
Good chance that this will be addressed by https://github.com/facebook/react-native/pull/4880

**Comment by philikon** [comment]
Totes. I think we can close this.
