### ISSUE TITLE
uncaught error Error: TypeError: Object.assign is not a function

### ISSUE THREAD

**Issue by PWDream** [facebook/react-native#4930]
I use this command "react-native bundle $OPTS --bundle-output ios.jsbundle --minify --entry-file index.ios.js --platform ios" ReactPackager,but error :
 Created ReactPackager
uncaught error Error: TypeError: Object.assign is not a function
    at transform (/Users/panwei/Desktop/Mall/react/node_modules/react-native/packager/transformer.js:33:25)
    at module.exports (/Users/panwei/Desktop/Mall/react/node_modules/react-native/packager/transformer.js:66:14)
    at handle (/Users/panwei/Desktop/Mall/react/node_modules/react-native/node_modules/worker-farm/lib/child/index.js:41:8)
    at process.<anonymous> (/Users/panwei/Desktop/Mall/react/node_modules/react-native/node_modules/worker-farm/lib/child/index.js:47:3)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:632:10)
TransformError: /Users/panwei/Desktop/Mall/react/node_modules/react-native/packager/react-packager/src/Resolver/polyfills/prelude_dev.js: Object.assign is not a function
See logs /var/folders/yl/_sv0db5x7bl5tb0z5hy6rzcw0000gn/T/react-packager.log
    at SocketClient._handleMessage (SocketClient.js:139:23)
    at BunserBuf.<anonymous> (SocketClient.js:53:42)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/panwei/Desktop/Mall/react/node_modules/react-native/node_modules/bser/index.js:289:10)
    at /Users/panwei/Desktop/Mall/react/node_modules/react-native/node_modules/bser/index.js:244:12
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)

**Comment by satya164** [comment]
@PWDream What version of Node are you using? You need at least Node 4.

**Comment by oojr** [comment]
had the same issue and my node was up-to-date, updating react-native-cli fixed it for me

`npm install -g react-native-cli`

**Comment by TylerYang** [comment]
+1 
It will work if I replace all the `Object.assign`(Guess this might be babel object assign env error) statement to `object-assign` module.

**Comment by jsierles** [comment]
@facebook-github-bot answered
