### ISSUE TITLE
UnableToResolveError: Unable to resolve module react-transform-hmr

### ISSUE THREAD

**Issue by nowaits** [facebook/react-native#5016]
error on Master:

bundle: Created ReactPackager
uncaught error Error: UnableToResolveError: Unable to resolve module react-transform-hmr from /Users/dev/Desktop/tadpole/react_js/node_modules/react-native/Libraries/JavaScriptAppEngine/Initialization/InitializeJavaScriptAppEngine.js: Invalid directory /Users/node_modules/react-transform-hmr
    at ResolutionRequest.js:351:15
    at tryCallOne (/Users/dev/Desktop/tadpole/react_js/node_modules/promise/lib/core.js:37:12)
    at /Users/dev/Desktop/tadpole/react_js/node_modules/promise/lib/core.js:123:15
    at flush (/Users/dev/Desktop/tadpole/react_js/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
See logs /var/folders/cv/yskqh6vj78zgy4l6bt_rxnqm0000gn/T/react-packager.log
    at SocketClient._handleMessage (SocketClient.js:139:23)
    at BunserBuf.<anonymous> (SocketClient.js:53:42)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/dev/Desktop/tadpole/react_js/node_modules/bser/index.js:289:10)
    at /Users/dev/Desktop/tadpole/react_js/node_modules/bser/index.js:244:12
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)

**Comment by christopherdro** [comment]
Duplicate #4968
