### ISSUE TITLE
Exception when running 'init' [Windows] started with 0.1.8

### ISSUE THREAD

**Issue by leemac** [facebook/react-native#5185]
I just started to get up and running with React-Native for the first time with windows/Android and kept receiving this error with the latest release (v0.1.8) when I tried to initialize the project:

```
$ react-native init MyFirstMobileApp
This will walk you through creating a new React Native project in C:\projects\MyFirstMobileApp
Installing react-native package from npm...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:478:9)
    at process._tickCallback (node.js:392:17)
    at Function.Module.runMain (module.js:432:11)
    at startup (node.js:141:18)
    at node.js:1003:3

```
With the help of a colleague who had it working fine on his machine, we found he had 0.1.7 by comparing our installed packages (npm -g ls).

I downgraded to 0.1.7 and it works fine now. I looked at the changeset for the 0.1.8 release and nothing jumps out at me. Figured this might help someone in the meantime.

**Comment by verdammelt** [comment]
Perhaps this is same/similar to #5159? (I submitted that bug where init hangs when run on MacOSX)

**Comment by leemac** [comment]
I went back to 0.1.8 to see if passing those flags made a difference, but unfortunately I got the same error. 

```
$ react-native init MobileAppFixTwo --verbose --debug
This will walk you through creating a new React Native project in C:\projects\LedgexMobile\MobileAppFixTwo
Installing react-native package from npm...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:478:9)
    at process._tickCallback (node.js:392:17)
    at Function.Module.runMain (module.js:432:11)
    at startup (node.js:141:18)
    at node.js:1003:3
```
I'll poke around that line number though, could be a good lead.

**Comment by verdammelt** [comment]
How about #5169? That does seem like the same as this one.

**Comment by mkonicek** [comment]
This should be the same as https://github.com/facebook/react-native/issues/5169

Can you try upgrading to 0.1.9?

    npm uninstall -g react-native-cli
    npm install -g react-native-cli

**Comment by leemac** [comment]
Thanks @mkonicek , seems to have fixed it.
