### ISSUE TITLE
Android build fails if project directory is named 'foo'

### ISSUE THREAD

**Issue by verdammelt** [facebook/react-native#5186]
I ran into an odd situation where my test project  android build was failing but a differently named project was working. I narrowed it down to two test commands:

```
rm -rf foo && react-native init foo && (cd foo/android && ./gradlew app:bundleReleaseJsAndAssets)
```

This will fail with the following error:
```
:app:bundleReleaseJsAndAssets
bundle: Created ReactPackager
bundle: start
[11:02:42 AM] <START> Whole Program Optimisations
uncaught error SyntaxError: unknown: Assigning to rvalue (2893:0)
  2891 | if(onFail||onSucc){
  2892 | 
> 2893 | this._callbackID>1<<5&&
       | ^
  2894 | this._debugInfo[this._callbackID>>5]=null;
  2895 | 
  2896 | this._debugInfo[this._callbackID>>1]=[module,method];
    at Parser.pp.raise (/Users/mjs/SRC/foo/node_modules/babylon/index.js:1413:13)
    at Parser.pp.toAssignable (/Users/mjs/SRC/foo/node_modules/babylon/index.js:1501:14)
    at Parser.pp.parseMaybeAssign (/Users/mjs/SRC/foo/node_modules/babylon/index.js:362:61)
    at Parser.pp.parseExpression (/Users/mjs/SRC/foo/node_modules/babylon/index.js:321:19)
    at Parser.pp.parseStatement (/Users/mjs/SRC/foo/node_modules/babylon/index.js:1938:19)
    at Parser.pp.parseBlockBody (/Users/mjs/SRC/foo/node_modules/babylon/index.js:2282:21)
    at Parser.pp.parseBlock (/Users/mjs/SRC/foo/node_modules/babylon/index.js:2263:8)
    at Parser.pp.parseStatement (/Users/mjs/SRC/foo/node_modules/babylon/index.js:1902:19)
    at Parser.pp.parseIfStatement (/Users/mjs/SRC/foo/node_modules/babylon/index.js:2075:26)
    at Parser.pp.parseStatement (/Users/mjs/SRC/foo/node_modules/babylon/index.js:1880:19)
:app:bundleReleaseJsAndAssets FAILED
```

But if I rename the project directory from 'foo' to 'bar' it works:
```
rm -rf foo && react-native init foo && mv foo bar && (cd bar/android && ./gradlew app:bundleReleaseJsAndAssets)
```

This completes successfully.

Versions:
* react-native-cli: 0.1.7 (globally installed)
* react-native: 0.17.0
* node: v5.3.0
* npm: 3.3.12

**Comment by ravirdv** [comment]
Hi,

I tried the same command and it works on my machine, please share the version of RN you're use. I'm on 0.17.0 on OSX.

```
:app:bundleReleaseJsAndAssets
bundle: Created ReactPackager
bundle: start
[11:10:47 PM] <START> Whole Program Optimisations
[11:10:57 PM] <END>   Whole Program Optimisations (9689ms)
[11:10:57 PM] <START> minify
[11:11:02 PM] <END>   minify (5584ms)
bundle: finish
bundle: Writing bundle output to: /Users/ravi/apps/foo/android/app/build/intermediates/assets/release/index.android.bundle
bundle: Closing client
bundle: Done writing bundle output

BUILD SUCCESSFUL
```

**Comment by verdammelt** [comment]
Ah, sorry I left out that info. I'll edit the initial report above.

**Comment by ide** [comment]
Might be related to https://github.com/facebook/react-native/issues/5165. tl;dr clear your npm and react native caches and try from scratch.

**Comment by verdammelt** [comment]
I ran `npm cache clean` and then create a new react-native project named 'foo' and it surprisingly worked!

I guess I will close this ticket.

Thanks @ide!
