### ISSUE TITLE
Android - Fatal Exception in ForwardingCookieHandler and WebView

### ISSUE THREAD

**Issue by ajwhite** [facebook/react-native#5187]
This crash report came in today. It appears to have an issue with resolving the webview package name

```
Fatal Exception: android.util.AndroidRuntimeException: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
       at android.webkit.WebViewFactory.getFactoryClass(WebViewFactory.java:161)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:101)
       at android.webkit.CookieManager.getInstance(CookieManager.java:46)
       at com.facebook.react.modules.network.ForwardingCookieHandler.getCookieManager(ForwardingCookieHandler.java:158)
       at com.facebook.react.modules.network.ForwardingCookieHandler.get(ForwardingCookieHandler.java:56)
       at com.squareup.okhttp.internal.http.HttpEngine.networkRequest(HttpEngine.java:714)
       at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:222)
       at com.squareup.okhttp.Call.getResponse(Call.java:267)
       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
       at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
       at com.squareup.okhttp.Call.access$100(Call.java:34)
       at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
       at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:114)
       at android.webkit.WebViewFactory.getFactoryClass(WebViewFactory.java:133)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:101)
       at android.webkit.CookieManager.getInstance(CookieManager.java:46)
       at com.facebook.react.modules.network.ForwardingCookieHandler.getCookieManager(ForwardingCookieHandler.java:158)
       at com.facebook.react.modules.network.ForwardingCookieHandler.get(ForwardingCookieHandler.java:56)
       at com.squareup.okhttp.internal.http.HttpEngine.networkRequest(HttpEngine.java:714)
       at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:222)
       at com.squareup.okhttp.Call.getResponse(Call.java:267)
       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
       at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
       at com.squareup.okhttp.Call.access$100(Call.java:34)
```

[full crashlytics report](http://crashes.to/s/0b5b87665e2/details)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-fatal-exception-in-forwardingcookiehandler-and-webview

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by rayshih** [comment]
Just facing same issue here

**Comment by teyou** [comment]
I had the same issue which running on RN 0.38
Device: OPPO X9079
OS: Android 5.1.1

Totally no idea why this happened

**Comment by ckitterl** [comment]
The project created by 'create-react-native-app' also crashed with the same issue at android 8.0
Device: Nexus 6P
OS: android 8.0

**Comment by K-Leon** [comment]
Seeing this also very often ( android 5.1 )

**Comment by ckitterl** [comment]
The problem of mine war caused by security software. After I uninstalled the security software, it looked to all right. I think the answer of quest is some one blocked the acquiring of Provider. Hopes to be help @ajwhite @rayshih @teyou @K-Leon
