### ISSUE TITLE
react-native bundle failed with --dev false

### ISSUE THREAD

**Issue by JakeRawr** [facebook/react-native#5207]
I'm currently on React Native v0.17

I am trying to re-generate the static bundle by running

`react-native bundle --entry-file index.ios.js --bundle-output iOS/main.jsbundle --platform 'ios' --minify --dev false`

this gives me the error:
```
bundle: Created ReactPackager
bundle: start
[3:50:13 PM] <START> Whole Program Optimisations
uncaught error TypeError: unknown: Property id of VariableDeclarator expected node to be of a type ["LVal"] but instead got "BooleanLiteral"
    at Object.validate (/Users/Tsunghan/oioi-reactnative/node_modules/react-native/node_modules/babel-types/lib/definitions/index.js:101:13)
    at Object.validate (/Users/Tsunghan/oioi-reactnative/node_modules/react-native/node_modules/babel-types/lib/index.js:268:9)
    at NodePath._replaceWith (/Users/Tsunghan/oioi-reactnative/node_modules/react-native/node_modules/babel-core/node_modules/babel-traverse/lib/path/replacement.js:201:7)
    at NodePath.replaceWith (/Users/Tsunghan/oioi-reactnative/node_modules/react-native/node_modules/babel-core/node_modules/babel-traverse/lib/path/replacement.js:179:8)
    at firstPass.Identifier (dead-module-elimination.js:96:14)
    at NodePath._call (/Users/Tsunghan/oioi-reactnative/node_modules/react-native/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:74:18)
    at NodePath.call (/Users/Tsunghan/oioi-reactnative/node_modules/react-native/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:46:17)
    at NodePath.visit (/Users/Tsunghan/oioi-reactnative/node_modules/react-native/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:104:12)
    at TraversalContext.visitQueue (/Users/Tsunghan/oioi-reactnative/node_modules/react-native/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitSingle (/Users/Tsunghan/oioi-reactnative/node_modules/react-native/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:113:19)
    at TraversalContext.visit (/Users/Tsunghan/oioi-reactnative/node_modules/react-native/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:197:19)
    at Function.traverse.node (/Users/Tsunghan/oioi-reactnative/node_modules/react-native/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:139:17)
```
The problem seems to be in `Whole Program Optimisations`

If I do `--dev true`, the bundle is build fine. But I want to build my bundle for production and would like to set `--dev false`.

Anyone has a fix for this?

**Comment by tomauty** [comment]
Make sure there are no references to `global.__DEV__` in your code. I had this problem until I removed references to `global.__DEV__`  and replaced with `__DEV__`.

**Comment by JakeRawr** [comment]
@tomauty I've only found `global.__DEV__` in env.js and environment.js. And I replaced those with `__DEV__`. Still didn't work. Are there more at other places?

**Comment by jaygarcia** [comment]
@JakeRawr, for iOS, as of 0.14, there is a build step that executes a script to automatically create the bundle for you.  It's quite a relief to not have to build manually anymore to do iOS testing/deploys.

https://facebook.github.io/react-native/docs/upgrading.html


![](https://cloud.githubusercontent.com/assets/192222/11050052/8f098252-86f7-11e5-994a-364aabbaa7d1.png)

**Comment by JakeRawr** [comment]
@jaygarcia Thanks, but in that .sh file it is still executing the same code with `--dev false`

I still have the same issue. Unable to bundle with --dev set to true.

I also upgraded react native to v0.18. 
Problem is not resolved

-Jake

**Comment by JakeRawr** [comment]
Update:

I think the bug has some to do with 
line 95 in dead-module-elimination.js

```javascript
      if (node.name in globals) {
        path.replaceWith(t.booleanLiteral(globals[node.name]));
      }
```

Seems to me that it's converting all globals[node.name] into a 'BooleanLiteral' type. Thus cause an error 

```
uncaught error TypeError: unknown: Property id of VariableDeclarator expected node to be of a type ["LVal"] but instead got "BooleanLiteral"
```

**Comment by JakeRawr** [comment]
Fixed the problem!!

I have `__Dev__` in my code, and tried to set it `true`

so.. don't do that
