### ISSUE TITLE
Cannot run react-native start OR react-native init project

### ISSUE THREAD

**Issue by gay-carson-andrew** [facebook/react-native#5260]
when I run 'react-native start' in the project directory I receive this error (This project runs on other machines)

module.js:339
    throw err;
    ^
```error
Error: Cannot find module './packager/babelRegisterOnly'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\andrew.gay\Projects\prologic_ofs3mobile\node
_modules\react-native\cli.js:11:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

When I type 'react-native init projectname' the project init hangs and never loads.

**Comment by jaygarcia** [comment]
@gay-carson-andrew , it's because you're using windows. **kidding!!** :)

My first step in this situation would be to verify that all dependencies are installed.     :(

**Comment by jsierles** [comment]
@facebook-github-bot no-reply
