### ISSUE TITLE
Bundling gets error

### ISSUE THREAD

**Issue by mjhlybmwq** [facebook/react-native#5511]
I tried: ```react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output main.jsbundle``` and ```react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output main.jsbundle```, which got the same error:
```
bundle: Created ReactPackager
uncaught error Error: ReferenceError: [BABEL] I:\rn\rnapp\node_modules\react-nat
ive\node_modules\react-transform-hmr\node_modules\react-proxy\node_modules\react
-deep-force-update\lib\index.js: Unknown option: I:\rn\rnapp\node_modules\react-
native\node_modules\react-transform-hmr\node_modules\react-proxy\node_modules\re
act-deep-force-update\.babelrc.stage
    at Logger.error (I:\rn\rnapp\node_modules\react-native\node_modules\babel-co
re\lib\transformation\file\logger.js:41:11)
    at OptionManager.mergeOptions (I:\rn\rnapp\node_modules\react-native\node_mo
dules\babel-core\lib\transformation\file\options\option-manager.js:262:18)
    at OptionManager.addConfig (I:\rn\rnapp\node_modules\react-native\node_modul
es\babel-core\lib\transformation\file\options\option-manager.js:221:10)
    at OptionManager.findConfigs (I:\rn\rnapp\node_modules\react-native\node_mod
ules\babel-core\lib\transformation\file\options\option-manager.js:364:16)
    at OptionManager.init (I:\rn\rnapp\node_modules\react-native\node_modules\ba
bel-core\lib\transformation\file\options\option-manager.js:412:12)
    at File.initOptions (I:\rn\rnapp\node_modules\react-native\node_modules\babe
l-core\lib\transformation\file\index.js:191:75)
    at new File (I:\rn\rnapp\node_modules\react-native\node_modules\babel-core\l
ib\transformation\file\index.js:122:22)
    at Pipeline.transform (I:\rn\rnapp\node_modules\react-native\node_modules\ba
bel-core\lib\transformation\pipeline.js:42:16)
    at transform (I:\rn\rnapp\node_modules\react-native\packager\transformer.js:
59:24)
TransformError: I:\rn\rnapp\node_modules\react-native\node_modules\react-transfo
rm-hmr\node_modules\react-proxy\node_modules\react-deep-force-update\lib\index.j
s: [BABEL] I:\rn\rnapp\node_modules\react-native\node_modules\react-transform-hm
r\node_modules\react-proxy\node_modules\react-deep-force-update\lib\index.js: Un
known option: I:\rn\rnapp\node_modules\react-native\node_modules\react-transform
-hmr\node_modules\react-proxy\node_modules\react-deep-force-update\.babelrc.stag
e
See logs C:\Users\mwq\AppData\Local\Temp\react-packager.log
    at SocketClient._handleMessage (SocketClient.js:139:23)
    at BunserBuf.<anonymous> (SocketClient.js:53:42)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (I:\rn\rnapp\node_modules\react-native\node_modules\bse
r\index.js:289:10)
    at I:\rn\rnapp\node_modules\react-native\node_modules\bser\index.js:244:12
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)

```
I tried ```rm -rf node_modules;npm clean cache; npm i;```, which still got the same problem. Hmmm... What can I do?

**Comment by jevakallio** [comment]
This appears to be a duplicate of https://github.com/facebook/react-native/issues/5393 - see discussion and workarounds there.

**Comment by mjhlybmwq** [comment]
Thank you. It's hard to search.

**Comment by 3riccc** [comment]
I have met the same problem...
