### ISSUE TITLE
_matchGestureAction error when clicking button inside a list

### ISSUE THREAD

**Issue by lawgimenez** [facebook/react-native#5573]
This error happens when clicking a button inside a ListView in Android. It crashes most on Samsung's Note 4 devices. I believe this has something to do with touch gestures only generated in devices using pen not detected by React Native.

Fatal Exception: com.facebook.react.modules.core.JavascriptException: _matchGestureAction
    index.android.bundle:31129:17
_handleMoveShouldSetPanResponder
    index.android.bundle:30954:55
onMoveShouldSetResponder
    index.android.bundle:39394:35
executeDispatchesInOrderStopAtTrueImpl
    index.android.bundle:16728:24
executeDispatchesInOrderStopAtTrue
    index.android.bundle:16744:47
setResponderAndExtractTransfer
    index.android.bundle:19916:56
extractEvents
    index.android.bundle:20073:31
extractEvents
    index.android.bundle:16251:49
handleTopLevel
    index.android.bundle:21821:40
_receiveRootNodeIDEvent
    index.android.bundle:21688:39
receiveTouches
    index.android.bundle:21773:48
__callFunction
    index.android.bundle:6434:21
<unknown>
    index.android.bundle:6374:46
guard
    index.android.bundle:6311:3
callFunctionReturnFlushedQueue
    index.android.bundle:6374:6

       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:68)
       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:56)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:106)
       at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:140)
       at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:64)
       at com.facebook.react.bridge.CatalystInstance$NativeModulesReactCallback.call(CatalystInstance.java:378)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:145)
       at com.facebook.react.bridge.queue.MessageQueueThread$1.run(MessageQueueThread.java:137)
       at java.lang.Thread.run(Thread.java:818)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/matchgestureaction-error-when-clicking-button-inside-a-list

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
