### ISSUE TITLE
unable to download JS bundel

### ISSUE THREAD

**Issue by TangSirOnGit** [facebook/react-native#5618]
http://7xjtzg.com1.z0.glb.clouddn.com/uploads/default/original/2X/8/8e9ebec486f0373d70b315db53a6967546236ffc.png

I did the practice (AwesomeProject) on osx with a huawei phone(android 5.1), but the app can not run correctly.

I have tried:
1 adb reverse tcp:8081 tcp:8081      ----> not work
2 modify the dev server host on the device ------>not work.

what can i do next?
thanks a lot.

**Comment by pucchur** [comment]
@TangSirOnGit  open another cmd prompt, navigate to Awesome Project and type

1.react-native start 
and then type this in other cmd prompt
2. react-native run-android

**Comment by jiangqqlmj** [comment]
Now you really machine debugging, using computers to keep the same wifi network。
1.you should delete node_modules/react-deep-force-update/.babelrc 
2.if your version is v0.18.1，This path has changed。now you should delete /node_modules/react-native/node_modules/react-transform-hmr/node_modules/react-proxy/node_modules/react-deep-force-update/.babelrc 
[plesase see the details](http://www.lcode.org/react-native%E7%96%91%E9%9A%BE%E7%82%B9%E9%97%AE%E9%A2%98%E6%B7%B1%E5%9D%91%E6%9C%80%E5%BC%BA%E6%80%BB%E7%BB%93%E5%B8%96%E4%B8%8D%E6%96%AD%E6%9B%B4%E6%96%B0%E4%B8%AD/)

**Comment by TangSirOnGit** [comment]
it works for me, thanks a lot. @jiangqqlmj

I delete this file  : 
projectfolder/node_modules/react-deep-force-update/.babelrc

**Comment by ShadowZheng** [comment]
@jiangqqlmj @TangSirOnGit I delete node_modules/react-deep-force-update/.babelrc, but it still no works when I execute the command "react-native start", it throw a error as below:
```bash
c:\Users\azheng\Desktop\reactNativeApp\node_modules\babel-core\lib\transformation\file\logger.js:41
    throw new Constructor(this._buildMessage(msg));
    ^

ReferenceError: [BABEL] c:\Users\azheng\Desktop\reactNativeApp\node_modules\react-native\local-cli\bundle\bundle.js: Unknown option: base.stage
    at Logger.error (c:\Users\azheng\Desktop\reactNativeApp\node_modules\babel-core\lib\transformation\file\logger.js:41:11)
    at OptionManager.mergeOptions (c:\Users\azheng\Desktop\reactNativeApp\node_modules\babel-core\lib\transformation\file\options\option-manager.js:26
    at OptionManager.init (c:\Users\azheng\Desktop\reactNativeApp\node_modules\babel-core\lib\transformation\file\options\option-manager.js:416:10)
    at File.initOptions (c:\Users\azheng\Desktop\reactNativeApp\node_modules\babel-core\lib\transformation\file\index.js:191:75)
    at new File (c:\Users\azheng\Desktop\reactNativeApp\node_modules\babel-core\lib\transformation\file\index.js:122:22)
    at Pipeline.transform (c:\Users\azheng\Desktop\reactNativeApp\node_modules\babel-core\lib\transformation\pipeline.js:42:16)
    at Object.transformFileSync (c:\Users\azheng\Desktop\reactNativeApp\node_modules\babel-core\lib\api\node.js:116:10)
    at compile (c:\Users\azheng\Desktop\reactNativeApp\node_modules\babel-register\lib\node.js:102:20)
    at loader (c:\Users\azheng\Desktop\reactNativeApp\node_modules\babel-register\lib\node.js:130:14)
    at Object.require.extensions.(anonymous function) [as .js] (c:\Users\azheng\Desktop\reactNativeApp\node_modules\babel-register\lib\node.js:140:7)
```

Can you help me?

**Comment by PuYart** [comment]
@jiangqqlmj my version is 0.19.0 and i can't find `.babelrc` in `node_modules/react-deep-force-update`
what can i do??
