### ISSUE TITLE
I run UIExplorer this example but Crash

### ISSUE THREAD

**Issue by chenqizheng** [facebook/react-native#5718]
React Native Version is 0.1.7
I run UIExplorer this example but Crash on Moto X + 1(Android5.1),Nexus 6p(Android6.0.1)
Crash log⬇️
[react.txt](https://github.com/facebook/react-native/files/114975/react.txt)

**Comment by christopherdro** [comment]
@chenqizheng Could you try running the example from master or the latest stable release?

**Comment by chenqizheng** [comment]
@christopherdro After updating the code, APK doesn't crash on , but,when I execute “./packager/packager.sh” , error log as :

➜  react-native git:(master) ✗ ./packager/packager.sh
/Users/Chen/Study/Study/SourceCode/github/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:315
          throw new Error("Couldn't find preset " + JSON.stringify(val));
          ^

Error: Couldn't find preset "react-native"
    at OptionManager.mergePresets (/Users/Chen/Study/Study/SourceCode/github/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:315:17)
    at OptionManager.mergeOptions (/Users/Chen/Study/Study/SourceCode/github/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:12)
    at compile (/Users/Chen/Study/Study/SourceCode/github/react-native/node_modules/babel-register/lib/node.js:87:15)
    at loader (/Users/Chen/Study/Study/SourceCode/github/react-native/node_modules/babel-register/lib/node.js:128:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Chen/Study/Study/SourceCode/github/react-native/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/Users/Chen/Study/Study/SourceCode/github/react-native/local-cli/cli.js:16:14)

**Comment by Kureev** [comment]
Hi @chenqizheng,

As I see from your trace, you have
```
Error: Couldn't find preset "react-native"
```
error. To fix it, you need to install this preset as required:
```
$ npm install react-native --save-dev
```

**Comment by christopherdro** [comment]
@chenqizheng 

Double check that you ran `npm install` inside the UIExplorer demo before running the app.

Closing this for now. Feel free to re-open the issue if the problem persists. Thanks!
