### ISSUE TITLE
[Android]Release crash version 0.19.0

### ISSUE THREAD

**Issue by Richard-Cao** [facebook/react-native#5756]
Debug is right, but release crash:
```
02-04 21:46:35.058 14354-14382/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                   Process: com.reading, PID: 14354
                                                   com.facebook.react.bridge.NativeArgumentsParseException: RCTNetworking.sendRequest got 6 arguments, expected 7
                                                       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:227)
                                                       at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:158)
                                                       at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:58)
                                                       at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:431)
                                                       at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:185)
                                                       at java.lang.Thread.run(Thread.java:818)
```

**Comment by Richard-Cao** [comment]
@mkonicek

**Comment by Richard-Cao** [comment]
@janicduplessis

**Comment by Richard-Cao** [comment]
ok well down
sorry

**Comment by wvengen** [comment]
I'm seeing this as well, what did you do to workaround/fix this?

**Comment by wvengen** [comment]
Ah, found #5655 and realised that the react-native upgrade enabled running ProGuard.
Setting `def enableProguardInReleaseBuilds = false` in android/app/build.gradle worked.
