### ISSUE TITLE
Error: Command /bin/sh failed with exit code 8

### ISSUE THREAD

**Issue by erikhermans3** [facebook/react-native#5757]
React native is giving me an error, please help.
I followed the tutorial from
https://facebook.github.io/react-native/docs/getting-started.html#content

It gave me an error.

DEST=/Users/User/Library/Developer/Xcode/DerivedData/AwesomeProject-abayzwfqcshpereqmyhwxuvxnzeo/Build/Products/Debug-iphonesimulator/AwesomeProject.app
react-native bundle --entry-file index.ios.js --platform ios --dev true --bundle-output /Users/User/Library/Developer/Xcode/DerivedData/AwesomeProject-abayzwfqcshpereqmyhwxuvxnzeo/Build/Products/Debug-iphonesimulator/AwesomeProject.app/main.jsbundle --assets-dest /Users/User/Library/Developer/Xcode/DerivedData/AwesomeProject-abayzwfqcshpereqmyhwxuvxnzeo/Build/Products/Debug-iphonesimulator/AwesomeProject.app
/Users/User/Documents/Project/Test/AwesomeProject/node_modules/react-native/local-cli/cli.js:56
const setupEnvScript = /^win/.test(process.platform)
^^^^^
SyntaxError: Use of const in strict mode.
at Module._compile (module.js:439:25)
at Module._extensions..js (module.js:474:10)
at Object.require.extensions.(anonymous function) as .js
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (/Users/User/Documents/Project/Test/AwesomeProject/node_modules/react-native/cli.js:15:18)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
Command /bin/sh failed with exit code 8

My node version is 5.0.0.
I installed nvm also
nvm ls
v4.2.1
-> v5.0.0
system
default -> node (-> v5.0.0)
node -> stable (-> v5.0.0) (default)
stable -> 5.0 (-> v5.0.0) (default)
iojs -> N/A (default)

Any idea?

**Comment by christopherdro** [comment]
Duplicate #3946
