### ISSUE TITLE
Unexpected token =

### ISSUE THREAD

**Issue by pritchardjonathan** [facebook/react-native#5817]
Hi,

After removing npm packages and doing npm install I now get the exception:

```
function buildBundle(args, config, output = outputBundle) {
                                          ^
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)￿
    at Module._compile (module.js:374:25)
    at loader (/ReactApp/node_modules/react-native/node_modules/babel-core/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/ReactApp/node_modules/react-native/node_modules/babel-core/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)￿
    at require (internal/module.js:12:17)
    at Object.<anonymous> (bundle.js:11:21)
    at Module._compile (module.js:410:26)
~
Process terminated. Press <enter> to close the window
```

In the launch packager terminal.

I'm using react native v0.19.0
NodeJS version 4.2.6
npm version 2.14.12

All running on OSX. Any help would be much appreciated

**Comment by satya164** [comment]
There was an issue with babel. Try updating your node modules with `npm update`. Let's reopen if the issue persists.

**Comment by CentaurWarchief** [comment]
@satya164 This didn't solve the problem for me.

**Comment by benjreinhart** [comment]
This isn't fixed by updating node modules. Babel was updated yesterday and since react doesn't lock into any version babel is auto updated and is breaking on the new 6.5 releases.

**Comment by benjreinhart** [comment]
FYI - I changed the `babel-core` module in the react native's package.json to

```
"babel-core": "6.4",
```

Which installed `babel-core` version 6.4.5 and all is working again.

**Comment by satya164** [comment]
I thought @kittens released a hotfix to fix this.

**Comment by kittens** [comment]
@satya164 Yeah I did.
@benjreinhart See #5806.

**Comment by chinaxiaoyy** [comment]
this can help you solve it   [https://github.com/aksonov/react-native-mobx/issues/4](url)

**Comment by chinaxiaoyy** [comment]
this can help you solve it [https://github.com/aksonov/react-native-mobx/issues/4](url)
