### ISSUE TITLE
List view Crashes on Android

### ISSUE THREAD

**Issue by CreativeManix** [facebook/react-native#5875]
I am using 

https://github.com/FaridSafi/react-native-gifted-listview

Which internally uses ListView, Everything fine on IOS, but on android The app get crashed. I am facing this on Emulator (Genymotion APi level 19). 

Its a simple list without any sections, every row starts with TochableHighLight and with an image and texts.

The error is

java.lang.NullPointerException
                                                                at com.facebook.react.views.text.ReactTextView.reactTagForTouch(ReactTextView.java:42)
                                                                at com.facebook.react.uimanager.TouchTargetHelper.getTouchTargetForView(TouchTargetHelper.java:213)
                                                                at com.facebook.react.uimanager.TouchTargetHelper.findTargetTagAndCoordinatesForTouch(TouchTargetHelper.java:74)
                                                                at com.facebook.react.ReactRootView.handleTouchEvent(ReactRootView.java:147)
                                                                at com.facebook.react.ReactRootView.onInterceptTouchEvent(ReactRootView.java:268)
                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1859)
                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1917)
                                                                at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
                                                                at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
                                                                at android.app.Activity.dispatchTouchEvent(Activity.java:2458)
                                                                at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
                                                                at android.view.View.dispatchPointerEvent(View.java:7886)
                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3947)
                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3826)
                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
                                                                at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3518)
                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3419)
                                                                at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3575)
                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3419)
                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
                                                                at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5532)
                                                                at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5512)
                                                                at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5483)
                                                                at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5612)
                                                                at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                at android.os.MessageQueue.next(MessageQueue.java:138)
                                                                at android.os.Looper.loop(Looper.java:123)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by damusnet** [comment]
Hi @CreativeManix, were you able to fix this issue or to reproduce?

@facebook-github-bot label Needs more information

**Comment by CreativeManix** [comment]
It is fine on the device. Could be just on emulator...

**Comment by lacker** [comment]
I think you should file an issue on that repo, unless you can find an issue with just using a straight ListView. I'm closing this for now but feel free to reopen if you can find a problem with ListView directly.
