### ISSUE TITLE
React Packager: Error: zlib binding closed

### ISSUE THREAD

**Issue by epeli** [facebook/react-native#5876]
Sometimes I get following error from the React Packager when using Chrome Debugging with a real iOS device:

```
[2:10:19 PM] <START> request:/index.ios.map?platform=ios&dev=true
[2:10:20 PM] <END>   request:/index.ios.map?platform=ios&dev=true (335ms)
 ERROR  zlib binding closed
Error: zlib binding closed
    at DeflateRaw.Zlib._transform (zlib.js:484:15)
    at DeflateRaw.Transform._read (_stream_transform.js:166:10)
    at DeflateRaw.Transform._write (_stream_transform.js:154:12)
    at doWrite (_stream_writable.js:292:12)
    at clearBuffer (_stream_writable.js:396:7)
    at onwrite (_stream_writable.js:331:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:78:3)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:613:5)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
~
Process terminated. Press <enter> to close the window
```

or sometimes:

```
Assertion failed: ((false) == (ctx->pending_close_ && "close is pending")), function Write, file ../src/node_zlib.cc, line 124.
packager.sh: line 11: 60464 Abort trap: 6           node "$THIS_DIR/../local-cli/cli.js" start "$@
```

And all I can do is to close the terminal window and restart the app from  XCode. I have yet to figure out what exactly causes this. My guess it is something to do with the wifi connection. I using the OS X network sharing feature to create a wifi hotspot for the device.

I'm using React Native 0.19.

**Comment by itinance** [comment]
Any news on this? Having the same suddenly on an existing project

**Comment by lacker** [comment]
I think it's going to be hard to make any progress unless there is a consistent way to reproduce this. In the case of an intermittent error that can't be reproduced, either someone else shows up with a way to reproduce it, or you just use the workaround of restarting things. I'm going to close this issue for now but I encourage people to reopen new issues if there are ways to reproduce this problem.

**Comment by itinance** [comment]
FYI: while being involved in many RN-projects, i haven't seen this error for a long while.
