### ISSUE TITLE
[0.19][Android] <Picker> crashes the app

### ISSUE THREAD

**Issue by tsvetann** [facebook/react-native#5896]
Details: ReactNative 0.19
OS: Android 4.4.4

Code:
```javascript
'use strict'
import React, {
  Component,
  Picker
} from 'react-native'

export default class CPicker extends Component
{
  constructor(props) {
    super(props)
    this.state = {
      language: 'java'
    }
  }

  render() {
    return (
      <Picker
        selectedValue={this.state.language}
        onValueChange={(lang) => this.setState({language: lang})}>
        <Picker.Item label="Java" value="java" />
        <Picker.Item label="JavaScript" value="js" />
      </Picker>
    )
  }
}
```

adb logac output:

```
E/unknown:React(29461): Exception in native call from JS
E/unknown:React(29461): com.facebook.react.bridge.NoSuchKeyException: couldn't find key text in dynamic object
E/unknown:React(29461): 	at com.facebook.react.bridge.ReadableNativeMap.getString(Native Method)
E/unknown:React(29461): 	at com.facebook.react.views.picker.ReactPickerManager$ReactPickerAdapter.getView(ReactPickerManager.java:131)
E/unknown:React(29461): 	at com.facebook.react.views.picker.ReactPickerManager$ReactPickerAdapter.getView(ReactPickerManager.java:112)
E/unknown:React(29461): 	at android.widget.AbsSpinner.onMeasure(AbsSpinner.java:193)
E/unknown:React(29461): 	at android.widget.Spinner.onMeasure(Spinner.java:482)
E/unknown:React(29461): 	at android.view.View.measure(View.java:16521)
E/unknown:React(29461): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.updateLayout(NativeViewHierarchyManager.java:153)
E/unknown:React(29461): 	at com.facebook.react.uimanager.UIViewOperationQueue$UpdateLayoutOperation.execute(UIViewOperationQueue.java:122)
E/unknown:React(29461): 	at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:673)
E/unknown:React(29461): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:723)
E/unknown:React(29461): 	at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
E/unknown:React(29461): 	at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:120)
E/unknown:React(29461): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:759)
E/unknown:React(29461): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
E/unknown:React(29461): 	at android.view.Choreographer.doFrame(Choreographer.java:543)
E/unknown:React(29461): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
E/unknown:React(29461): 	at android.os.Handler.handleCallback(Handler.java:733)
E/unknown:React(29461): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/unknown:React(29461): 	at android.os.Looper.loop(Looper.java:136)
E/unknown:React(29461): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
E/unknown:React(29461): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/unknown:React(29461): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/unknown:React(29461): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/unknown:React(29461): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/unknown:React(29461): 	at dalvik.system.NativeStart.main(Native Method)
```
....

```
W/unknown:ViewManagerPropertyUpdater(29461): Could not find generated setter for class com.facebook.react.views.art.ARTRenderableViewManager
W/unknown:ViewManagerPropertyUpdater(29461): Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
W/unknown:ViewManagerPropertyUpdater(29461): Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
I/ProviderInstaller(29435): Installed default security provider GmsCore_OpenSSL
W/unknown:ViewManagerPropertyUpdater(29461): Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
W/unknown:ViewManagerPropertyUpdater(29461): Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
W/unknown:ViewManagerPropertyUpdater(29461): Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
W/unknown:ViewManagerPropertyUpdater(29461): Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
W/unknown:ViewManagerPropertyUpdater(29461): Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
W/unknown:ViewManagerPropertyUpdater(29461): Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
I/UpdateIcingCorporaServi(25517): UpdateCorporaTask done [took 119 ms] updated apps [took 119 ms]
W/unknown:ViewManagerPropertyUpdater(29461): Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
W/unknown:ViewManagerPropertyUpdater(29461): Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
I/ActivityManager(  795): Killing 29194:com.android.chrome:privileged_process1/u0a41 (adj 9): empty #17
W/cr_ChildProcessConnect(16111): onServiceDisconnected (crash or killed by oom): pid=29194
W/unknown:ViewManagerPropertyUpdater(29461): Could not find generated setter for class com.facebook.react.views.i
```

**Comment by mkonicek** [comment]
This is likely because you also need to upgrade the Android binaries dependency in your `build.gradle`. Check out that file or run `react-native upgrade`.

Let's reopen if that's not the case.

**Comment by ragnraok** [comment]
I still get the same error on version 0.21.0
