### ISSUE TITLE
[Android][0.20.0-rc] App crashed with java.lang.RuntimeException: Tried to get non-existent cookie  

### ISSUE THREAD

**Issue by terrysahaidak** [facebook/react-native#5944]
I use vysor.io to mirror my phone screen into PC. But I got into the issue. When I try to click and move mouse like swiping or something like that app crashes. It only happens when I try to do that in some RN view because in redbox or dev settings etc, also in other apps everything works fine. 

Windows 10
Rn 0.20.0-rc
Sgs4 i9500 Lollipop 5.1.1 (custom)

Logcat [here](https://gist.github.com/terrysahaidak/a67c3d5a832cb8f0379b).

As you can see when I'm clicking or scrolling by mouse wheel everything works fine, but then I try to hold and move up -- app crashed.
![crash_app_gif](https://i.imgsafe.org/a89d015.gif)

And moving scroll in redbox without a crash in the same app.
![without_crash](https://i.imgsafe.org/f329e01.gif)

**Comment by grabbou** [comment]
Having this as well in production, cc: @9mm

**Comment by mkonicek** [comment]
Can you look at Git blame and history for `TouchEventCoalescingKeyHelper` and cc the main owner of the code here?

**Comment by grabbou** [comment]
Sure, will do.

**Comment by grabbou** [comment]
Stack trace for reference:
```
Fatal Exception: java.lang.RuntimeException: Tried to get non-existent cookie
       at com.facebook.react.uimanager.events.TouchEventCoalescingKeyHelper.getCoalescingKey(TouchEventCoalescingKeyHelper.java:75)
       at com.facebook.react.uimanager.events.TouchEvent.init(TouchEvent.java:83)
       at com.facebook.react.uimanager.events.TouchEvent.obtain(TouchEvent.java:45)
       at com.facebook.react.ReactRootView.handleTouchEvent(ReactRootView.java:184)
       at com.facebook.react.ReactRootView.onInterceptTouchEvent(ReactRootView.java:267)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1989)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2135)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2135)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2458)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2135)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2449)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1774)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2809)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2410)
       at android.view.View.dispatchPointerEvent(View.java:8695)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4379)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4239)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3685)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3738)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3704)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3712)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3685)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3738)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3704)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3836)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3712)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3893)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3685)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3738)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3704)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3712)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3685)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6098)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6072)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6043)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6250)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:143)
       at android.os.Looper.loop(Looper.java:122)
       at android.app.ActivityThread.main(ActivityThread.java:5422)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
```

**Comment by grabbou** [comment]
@mkonicek unfortunately, no-one did modify that file since initial release ;/

**Comment by mkonicek** [comment]
Ah, let me check the internal Mercurial blame then :) In the first release all the files blame to me.

**Comment by andreicoman11** [comment]
@dmmiller was looking into a similar crash internally.

**Comment by tianzhijiexian** [comment]
When I touch the screen,I got:
java.lang.RuntimeException: Tried to get non-existent cookie
                                                                        at com.facebook.react.uimanager.events.TouchEventCoalescingKeyHelper.getCoalescingKey(TouchEventCoalescingKeyHelper.java:75)
                                                                        at com.facebook.react.uimanager.events.TouchEvent.init(TouchEvent.java:83)
                                                                        at com.facebook.react.uimanager.events.TouchEvent.obtain(TouchEvent.java:45)
                                                                        at com.facebook.react.ReactRootView.handleTouchEvent(ReactRootView.java:184)
                                                                        at com.facebook.react.ReactRootView.onInterceptTouchEvent(ReactRootView.java:267)
                                                                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2310)

**Comment by dmmiller** [comment]
Do you have a consistent repro that you can share?  I've got a few reports of it, but nothing is consistent that I can really investigate why we don't have the event cookie.  If you have a consistent way to get it, I would love to know.

**Comment by MarcoPolo** [comment]
Relevant issue on the vysor repo: https://github.com/koush/vysor.io/issues/79

**Comment by dmmiller** [comment]
So, I was able to repro this using vysor.  The problem is two fold.  One, vysor sometimes send MOVE events for a Touch before the DOWN event.  This means we try and send a MOVE for something that we don't even know it has been touched.  The second is that when they do correctly send DOWN then MOVE, the downTime in the MOVE event doesn't match the downTime for DOWN event.  That means we don't track that MOVE as being part of the DOWN and we can't match it up.  I'm looking to be more robust in our code when this happens and I've also posted on the vysor issue more details so that maybe vysor can fix their part of it as well.

**Comment by grabbou** [comment]
Great, fingers crossed @dmmiller ! I am getting that crash w/o using vysor, but if it's the case of events coming out of order, it might be the slow Android device user is running the app on being the case.

**Comment by dmmiller** [comment]
We are seeing issues with it at Facebook as well and presumably not all the users are using vysor either :)

I am continuing to look into why it might be occurring.

**Comment by dmmiller** [comment]
@grabbou do you regularly see it when testing your own stuff?  Or do you see reports of it?  I have yet to get an actual consistent repro for it.  I only see the crash logs and reports.

**Comment by grabbou** [comment]
I can't reproduce it unfortunately. I have a bunch of reports constantly arriving via Sentry / Crashlytics, but it's tricky to help here as I can't even figure out the reason by looking at the stack trace.

**Comment by dmmiller** [comment]
Yea, I'm trying to add some more debugging to try and figure out why it is happening as I can't find a repro yet either.

**Comment by grabbou** [comment]
New crash:
```
Tried to increment non-existent cookie
com.facebook.react.ReactRootView in onInterceptTouchEvent at line 128application

com.facebook.react.ReactRootView in dispatchJSTouchEvent at line 152application

com.facebook.react.uimanager.JSTouchDispatcher in handleTouchEvent at line 121application

com.facebook.react.uimanager.events.TouchEvent in obtain at line 45application

com.facebook.react.uimanager.events.TouchEvent in init at line 80application

com.facebook.react.uimanager.events.TouchEventCoalescingKeyHelper in incrementCoalescingKey at line 64application
```
Might be related.

**Comment by everfire130** [comment]
Having this as well in production of RN 0.24.1:

``
 java.lang.RuntimeException
Tried to get non-existent cookie
com.facebook.react.uimanager.events.TouchEventCoalescingKeyHelper.getCoalescingKey(TouchEventCoalescingKeyHelper.java:75)
com.facebook.react.uimanager.events.TouchEvent.init(TouchEvent.java:83)
com.facebook.react.uimanager.events.TouchEvent.obtain(TouchEvent.java:45)
com.facebook.react.uimanager.JSTouchDispatcher.handleTouchEvent(JSTouchDispatcher.java:111)
com.facebook.react.ReactRootView.dispatchJSTouchEvent(ReactRootView.java:152)
com.facebook.react.ReactRootView.onInterceptTouchEvent(ReactRootView.java:128)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1996)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2171)
com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2564)
com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1849)
android.app.Activity.dispatchTouchEvent(Activity.java:2826)
com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2523)
android.view.View.dispatchPointerEvent(View.java:8799)
android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4737)
android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4590)
android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4101)
android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4157)
android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4123)
android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4260)
android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4131)
android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4317)
android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4101)
android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4157)
android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4123)
android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4131)
android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4101)
android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6538)
android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6512)
android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6465)
android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6697)
android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:193)
android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:181)
android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6656)
android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6723)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
android.view.Choreographer.doCallbacks(Choreographer.java:603)
android.view.Choreographer.doFrame(Choreographer.java:570)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
android.os.Handler.handleCallback(Handler.java:815)
android.os.Handler.dispatchMessage(Handler.java:104)
android.os.Looper.loop(Looper.java:194)
android.app.ActivityThread.main(ActivityThread.java:5701)
java.lang.reflect.Method.invoke(Native Method)
java.lang.reflect.Method.invoke(Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
``

**Comment by tianzhijiexian** [comment]
+1

**Comment by foxcode7** [comment]
+1

**Comment by lixiaolihua** [comment]
+1

**Comment by jhristu** [comment]
I was also able to repro by running an 'adb shell input swipe' command, e.g.

`adb shell input swipe 360 948 30 236 89`

crashes a simple React Native app consisting of a ScrollView and some TextViews using this error:

```
07-15 14:22:53.136 23747 23747 E AndroidRuntime: java.lang.RuntimeException: Tried to get non-existent cookie
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at com.facebook.react.uimanager.events.TouchEventCoalescingKeyHelper.getCoalescingKey(TouchEventCoalescingKeyHelper.java:75)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at com.facebook.react.uimanager.events.TouchEvent.init(TouchEvent.java:83)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at com.facebook.react.uimanager.events.TouchEvent.obtain(TouchEvent.java:45)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at com.facebook.react.uimanager.JSTouchDispatcher.handleTouchEvent(JSTouchDispatcher.java:111)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at com.facebook.react.ReactRootView.dispatchJSTouchEvent(ReactRootView.java:161)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at com.facebook.react.ReactRootView.onInterceptTouchEvent(ReactRootView.java:133)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2108)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:2769)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:9517)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4242)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4108)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3654)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3707)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3673)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3799)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3681)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3856)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3654)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3707)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3673)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3681)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3654)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5969)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5908)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5869)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6072)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:183)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6043)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6095)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:600)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:746)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5443)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
07-15 14:22:53.136 23747 23747 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by dmmiller** [comment]
So the adb command you posted above shows a similar issue to vysor so something in Android is generating the bad data.  It is sending a MOVE event with a downTime value that doesn't actually correspond to a DOWN event. 

Proper event sequence from an actual touch

```
MotionEvent { action=ACTION_DOWN, id[0]=0, x[0]=295.61508, y[0]=906.29193, eventTime=38831636, downTime=38831636, deviceId=1, source=0x1002 }
MotionEvent { action=ACTION_MOVE, id[0]=0, x[0]=295.61508, y[0]=905.26697, eventTime=38831710, downTime=38831636, deviceId=1, source=0x1002 }
MotionEvent { action=ACTION_MOVE, id[0]=0, x[0]=295.61508, y[0]=896.45966, eventTime=38831726, downTime=38831636, deviceId=1, source=0x1002 }
MotionEvent { action=ACTION_UP, id[0]=0, x[0]=298.61118, y[0]=767.40045, eventTime=38831801, downTime=38831636, deviceId=1, source=0x1002 }
```
Notice how the actual downTime for the MOVE and UP match the eventTime and downTime for the DOWN event.

When I run this with the `adb shell swipe ...` command from above, notice how the first MOVE downTime matches the DOWN but the subsequent one doesn't.

```
MotionEvent { action=ACTION_DOWN, id[0]=0, x[0]=360.0, y[0]=948.0, eventTime=38845289, downTime=38845289, deviceId=0, source=0x1002 }
MotionEvent { action=ACTION_MOVE, id[0]=0, x[0]=360.0, y[0]=948.0, eventTime=38845289, downTime=38845289, deviceId=0, source=0x1002 }
MotionEvent { action=ACTION_MOVE, id[0]=0, x[0]=298.8202, y[0]=816.0, eventTime=38845305, downTime=38845300, deviceId=0, source=0x1002 }
```

We do definitely need to make it more robust to this issue.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android0200-rc-app-crashed-with-javalangruntimeexception-tried-to-get-non-existent-cookie-

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by remch1990** [comment]
What is the solution to this problem?
FATAL EXCEPTION: main
java.lang.RuntimeException: Tried to get non-existent cookie; no stack available (TouchEventCoalescingKeyHelper.java:75)

**Comment by sunkibaek** [comment]
@dmmiller Any tips for this issue? We are having many crash reports caused by this. Not sure how to go about it.

**Comment by pamler** [comment]
I have got the same problem, please help~
RN: 0.39 Android
![image](https://cloud.githubusercontent.com/assets/3872791/23329940/18f642f6-fb7e-11e6-8cd8-99f33f460753.png)

**Comment by wv1124** [comment]
In our statistics, this exception throw a lot 

RN: 0.38 Android

java.lang.RuntimeException: Tried to get non-existent cookie
	at com.facebook.react.uimanager.events.TouchEventCoalescingKeyHelper.getCoalescingKey(TouchEventCoalescingKeyHelper.java:75)
	at com.facebook.react.uimanager.events.TouchEvent.init(TouchEvent.java:90)
	at com.facebook.react.uimanager.events.TouchEvent.obtain(TouchEvent.java:45)
	at com.facebook.react.uimanager.JSTouchDispatcher.handleTouchEvent(JSTouchDispatcher.java:115)
	at com.facebook.react.ReactRootView.dispatchJSTouchEvent(ReactRootView.java:149)
	at com.facebook.react.ReactRootView.onInterceptTouchEvent(ReactRootView.java:121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1890)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2247)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2247)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2247)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1990)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2243)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1624)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2536)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2177)
	at android.view.View.dispatchPointerEvent(View.java:8020)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4489)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4368)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3924)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3974)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3943)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4050)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3951)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4107)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3924)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3974)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3943)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3951)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3924)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6107)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6071)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6042)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6187)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6160)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6206)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:548)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5054)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
	at dalvik.system.NativeStart.main(Native Method)



![image](https://cloud.githubusercontent.com/assets/2101637/24792189/8a9caade-1baf-11e7-8662-925f5d7bd593.png)

**Comment by karna41317** [comment]
How this issue is closed ?, it happens all the time, and easily reproducible bug. 

Is it fixed with latest RN

**Comment by Geor23** [comment]
+1
It happens for me on RN 0.42.3

**Comment by bartolkaruza** [comment]
+1 without vysor.io on several production apps

**Comment by henrikra** [comment]
With RN 0.44 we are NOT getting this error anymore :)

**Comment by bartolkaruza** [comment]
Missed the fix at in the release notes https://github.com/facebook/react-native/commit/d2939eafbf56f99ea4da7374b9812ae6f54c1d3d.

**Comment by ddwhan0123** [comment]
+1 RN 0.39.2

**Comment by terrysahaidak** [comment]
guys, before posting comments, try to update to RN 0.44 or above.

**Comment by ddwhan0123** [comment]
But my project on the lower version, thank you for your suggestion @terrysahaidak

**Comment by henrikra** [comment]
Why dont you update it then? 🤣

**Comment by ddwhan0123** [comment]
The company has some version control issues, I can do nothing, thank you for the help, I know the problem @henrikra

**Comment by henrikra** [comment]
Then you are out of luck :D

**Comment by cstd** [comment]
+1 when use Samsung SideSync
