### ISSUE TITLE
Documentation: Dead link yields a reference error

### ISSUE THREAD

**Issue by theseyi** [facebook/react-native#602]
Navigating to the Push Notifications page  from the Docs page yields Error:Reference Error but returns a 200 OK. The link for PushNotificationIOS 'http://facebook.github.io/react-native/docs/pushnotificationios.html#content' which is referenced from the Documentation page, returns the following error: 
```
Error: ReferenceError: notification is not defined at /Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/src/guard.js:27:12 at onOutputGenerated (/Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/src/index.js:96:9) at Object.renderReactPage.done (/Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/src/DefaultRouter.js:352:7) at renderReactPage (/Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/src/renderReactPage.js:130:17) at renderComponentPackage (/Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/src/DefaultRouter.js:338:3) at routePackageHandler (/Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/src/DefaultRouter.js:281:5) at onComputePackage (/Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/src/index.js:100:9) at /Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/src/guard.js:29:10 at onWarmed (/Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/src/Packager.js:270:9) at /Users/travis/build/facebook/react-native/website/node_modules/react-page-middleware/node_modules/async/lib/async.js:116:25
```

**Comment by vjeux** [comment]
We have a fix internally, going to be pushed soon! Thanks for the heads up

**Comment by theseyi** [comment]
Thanks., I'll close then :)
