### ISSUE TITLE
[Android]Release crash java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by shexiaoheng** [facebook/react-native#6020]
react-native version 0.20.+
```
11-23 08:24:44.223 1093-1093/? E/NBBattery: doBatteryRunnable isPluggedIn()true
11-23 08:24:48.393 692-739/? E/AndroidRuntime: FATAL EXCEPTION: Thread-15632
                                               Process: com.qianlonglaile, PID: 692
                                               java.lang.NoSuchFieldError: no field with name='mNativeContext' signature='J' in class Lcom/facebook/imagepipeline/gif/GifImage;
                                                   at java.lang.Runtime.nativeLoad(Native Method)
                                                   at java.lang.Runtime.doLoad(Runtime.java:421)
                                                   at java.lang.Runtime.load(Runtime.java:331)
                                                   at java.lang.System.load(System.java:512)
                                                   at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
                                                   at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:209)
                                                   at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:178)
                                                   at com.facebook.react.modules.fresco.FrescoModule$FrescoHandler.loadLibrary(FrescoModule.java:119)
                                                   at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
                                                   at com.facebook.imagepipeline.gif.GifImage.ensure(GifImage.java:40)
                                                   at com.facebook.imagepipeline.gif.GifImage.create(GifImage.java:62)
                                                   at com.facebook.imagepipeline.animated.factory.AnimatedImageFactory.decodeGif(AnimatedImageFactory.java:67)
                                                   at com.facebook.imagepipeline.decoder.ImageDecoder.decodeGif(ImageDecoder.java:113)
                                                   at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:88)
                                                   at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:188)
                                                   at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:96)
                                                   at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:128)
                                                   at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
                                                   at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
                                                   at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                   at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                   at java.lang.Thread.run(Thread.java:841)
11-23 08:24:49.323 32471-765/? E/ActivityThread: Failed to find provider info for setting
11-23 08:24:49.323 32471-765/? E/ActivityThread: Failed to find provider info for localmmssetting
11-23 08:24:49.333 32471-765/? E/ActivityThread: Failed to find provider info for phonesetting
```

**Comment by RomanISWG** [comment]
Same problem here with RN 0.53.0
