### ISSUE TITLE
react-native run-android  throw new TypeError('invalid data');^  TypeError: invalid data     at WriteStream.Socket.write (net.js:617:11)

### ISSUE THREAD

**Issue by ducpm0301** [facebook/react-native#6074]
I use ubuntu 14.04. I have finished install follow link : https://facebook.github.io/react-native/docs/getting-started.html. And create : react-native init AwesomeProject success but when i run command : react-native run-android, i have problem : net.js:617
    throw new TypeError('invalid data');
    ^

TypeError: invalid data
    at WriteStream.Socket.write (net.js:617:11)
    at Object.execFileSync (child_process.js:482:20)
    at Object.run (/AwesomeProject/node_modules/react-native/local-cli/cli.js:77:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:73:7)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)

My envirement : 
- uname -a
  Linux cpu-duclh 3.16.0-60-generic #80~14.04.1-Ubuntu SMP Wed Jan 20 13:37:48 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
  -nodejs -v
  v4.3.1
  npm -v
  2.14.12
  Please help me!!!

**Comment by sebluy** [comment]
This worked on my machine:
chmod +x \<project-dir\>/node_modules/react-native/local-cli/setup_env.sh

Problem seems to be at
https://github.com/facebook/react-native/blob/master/local-cli/cli.js#L77
when the cli tries to run that setup script.

**Comment by mvnnn** [comment]
i get same error

**Comment by BoluoPi** [comment]
i get same error
@mvnnn @sebluy @ducpm0301 
Would you please share your solution?

**Comment by ducpm0301** [comment]
Because some file haven't permission so it errors. I use Ubuntu with two
hard disk. I put code in mount disk with full permission(777) but also get
the errors. When i put code in home folder, it ok

**Comment by leo7r** [comment]
Same error here. Same solution of @ducpm0301. Thanks!

**Comment by rahul-kamble** [comment]
Same error here. Same solution of @ducpm0301. Thanks!

**Comment by TangHuaiZhe** [comment]
Almost Same error here.
Same solution of @sebluy. Thanks!
TypeError: Invalid data, chunk must be a string or buffer, not object
    at WriteStream.Socket.write (net.js:647:11)
    at WriteStream.stream.write (/Users/tang/Code/sdpQrcodePay/node_modules/ansi/lib/newlines.js:36:21)
    at Object.execFileSync (child_process.js:493:20)
    at Object.run (/Users/tang/Code/sdpQrcodePay/node_modules/react-native/local-cli/cliEntry.js:154:16)
    at Object.<anonymous> (/Users/tang/.nvm/versions/node/v6.2.0/lib/node_modules/react-native-cli/index.js:88:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by lacker** [comment]
It sounds like this is solved as a non-RN-bug, so I am going to close this issue. Thanks folks for chiming in with solutions!
