### ISSUE TITLE
npm(3.x) install throws Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sweetest** [facebook/react-native#6080]
I ran
```
react-native init ReactNativeSample
rm-rf node_modules/
npm install
```

and it throws this error

```
npm install
npm ERR! Darwin 15.0.0
npm ERR! argv "~/.nvm/versions/node/v5.6.0/bin/node" "~/.nvm/versions/node/v5.6.0/bin/npm" "install"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
```

I tried many different combinations of node 4, 5 along with npm 3.x

I attach below some parts of npm-debug.log

```
58984 silly build negotiator@0.5.3
58985 silly build accepts@1.2.13
58986 silly build node-fetch@1.3.3
58987 silly build node-int64@0.4.0
58988 silly build bser@1.0.2
58989 silly build fb-watchman@1.9.0
58990 silly build node-status-codes@1.0.0
58991 silly build nopt@3.0.6
58992 silly build normalize-path@2.0.1
58993 silly build nth-check@1.0.1
58994 verbose stack RangeError: Maximum call stack size exceeded
58994 verbose stack     at Tracker.completed (/Users/naver/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:87:40)
58994 verbose stack     at /Users/naver/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:27:47
58994 verbose stack     at Array.forEach (native)
58994 verbose stack     at TrackerGroup.completed (/Users/naver/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:26:19)
58994 verbose stack     at /Users/naver/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:27:47
58994 verbose stack     at Array.forEach (native)
58994 verbose stack     at TrackerGroup.completed (/Users/naver/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:26:19)
58994 verbose stack     at /Users/naver/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:27:47
58994 verbose stack     at Array.forEach (native)
58994 verbose stack     at TrackerGroup.completed (/Users/naver/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:26:19)
58995 verbose cwd /Users/naver/dev/ReactNativeSample
58996 error Darwin 15.0.0
58997 error argv "/Users/naver/.nvm/versions/node/v5.6.0/bin/node" "/Users/naver/.nvm/versions/node/v5.6.0/bin/npm" "install"
58998 error node v5.6.0
58999 error npm  v3.6.0
59000 error Maximum call stack size exceeded
59001 error If you need help, you may report this error at:
59001 error     <https://github.com/npm/npm/issues>
59002 verbose exit [ 1, true ]
```

**Comment by sweetest** [comment]
even ` npm install -g react-native` fails with node 5.6.0, npm 3.6.0

**Comment by Kureev** [comment]
Hm, I have node 5.6.0 and npm 3.6.0, but I can't reproduce this issue.
Also, I'm not sure why you need to install `react-native` globally (do you mean `react-native-cli`?).
Probably it'll help if you re-install `npm` (because `are-we-there-yet` is a dependency of the npm itself also). Try this:
```
$ npm i npm -g
$ npm i react-native-cli -g
```
I think it should solve your issue.

**Comment by sweetest** [comment]
I made a typo there I mean just `npm install react-native`.

Even I'm failing to initialize react-native project like below.

```
$ react-native init AwesomeProject

This will walk you through creating a new React Native project in /Users/sweetest/dev/AwesomeProject
Installing react-native package from npm...

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/5.7.0/bin/node" "/usr/local/bin/npm" "install" "--save" "react-native"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/naver/dev/AwesomeProject/npm-debug.log

`npm install --save react-native` failed
```

**Comment by sweetest** [comment]
`npm i npm -g` did not helped also.

**Comment by sweetest** [comment]
seems like there's an infinte loop, attached is the last part of npm-debug.log

```
59069 silly build preserve@0.2.0
59070 silly build private@0.1.6
59071 silly build process@0.5.2
59072 silly build global@4.3.0
59073 verbose stack RangeError: Maximum call stack size exceeded
59073 verbose stack     at emitOne (events.js:90:13)
59073 verbose stack     at emit (events.js:182:7)
59073 verbose stack     at null.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:9:18)
59073 verbose stack     at emitOne (events.js:90:13)
59073 verbose stack     at emit (events.js:182:7)
59073 verbose stack     at null.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:9:18)
59073 verbose stack     at emitOne (events.js:90:13)
59073 verbose stack     at emit (events.js:182:7)
59073 verbose stack     at null.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:9:18)
59073 verbose stack     at emitOne (events.js:90:13)
59073 verbose stack     at emit (events.js:182:7)
59074 verbose cwd /Users/naver/dev/AwesomeProject
59075 error Darwin 15.0.0
59076 error argv "/usr/local/Cellar/node/5.7.0/bin/node" "/usr/local/bin/npm" "install" "--save" "react-native"
59077 error node v5.7.0
59078 error npm  v3.7.3
59079 error Maximum call stack size exceeded
59080 error If you need help, you may report this error at:
59080 error     <https://github.com/npm/npm/issues>
59081 verbose exit [ 1, true ]
```

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/npm3x-install-throws-maximum-call-stack-size-exceeded

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
