### ISSUE TITLE
[ListView] Crashes if scroll down fast

### ISSUE THREAD

**Issue by kelvinaliyanto** [facebook/react-native#6265]
I am trying to render the ListView with the dataSource being retrieved from the AsyncStorage. So for some reason, if the dataSource is very long and I try to scroll down in a fast manner, it will crash the app.However, if I actually wait until it finishes rendering until the end, the app does not crash. Is there any way to prevent this from happening?

**Comment by grabbou** [comment]
Hey, could you include the stack trace from the crash? That would help a lot.

**Comment by kelvinaliyanto** [comment]
Hi, I tried to debug in chrome, but the app is crashing without giving any trace. It just force closes, "Unfortunately, app is not responding". Anyway I am compiling android version.

**Comment by kelvinaliyanto** [comment]
I just installed Fabric inside my app. When I tried to reproduce the error, it gives the following stack trace: 

Fatal Exception: java.lang.AssertionError
       at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:21)
       at com.facebook.react.uimanager.RootViewUtil.getRootView(RootViewUtil.java:29)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.measure(NativeViewHierarchyManager.java:469)
       at com.facebook.react.uimanager.UIViewOperationQueue$MeasureOperation.execute(UIViewOperationQueue.java:372)
       at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:673)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:723)
       at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
       at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:120)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:723)
       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
       at android.view.Choreographer.doFrame(Choreographer.java:524)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4745)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by brentvatne** [comment]
Hi @kelvinaliyanto -- I have yet to have this issue on any of my apps with large data sources. Please follow the issue template that you see when you create a new issue and provide the React Native version  and some sample code that allows us to reproduce this. If you can create a new issue with that information it would be much appreciated. Thanks! :) :)

**Comment by kelvinaliyanto** [comment]
Hi @brentvatne -- Sorry, I am a newbie in this github forum. Is the updated question sufficient to help? Thanks! :)
