### ISSUE TITLE
.eslintrc in repo can not work with Atom

### ISSUE THREAD

**Issue by iugo** [facebook/react-native#6335]
React Native version: 0.21.0
.eslintrc: https://github.com/facebook/react-native/blob/36f1961003a7983918f12180a4d18bb2424ee494/.eslintrc

Error info:
AssertionError: ImportDeclaration should appear when the mode is ES6 and in the module context.

Such operations can reproduce the error:
```
react-native init project
cd project/
npm i eslint babel-eslint eslint-plugin-react --save-dev
```

Atom with linter and linter-eslint packages.
When open the *.js contain `import`, editor displays the following error:

```
AssertionError: ImportDeclaration should appear when the mode is ES6 and in the module context.
    at Referencer.ImportDeclaration (/project/node_modules/escope/lib/referencer.js:591:34)
    at Referencer.Visitor.visit (/project/node_modules/esrecurse/esrecurse.js:118:34)
    at Referencer.Visitor.visitChildren (/project/node_modules/esrecurse/esrecurse.js:97:38)
    at Referencer.Program (/project/node_modules/escope/lib/referencer.js:419:18)
    at Referencer.Visitor.visit (/project/node_modules/esrecurse/esrecurse.js:118:34)
    at Object.analyze (/project/node_modules/escope/lib/index.js:153:16)
    at EventEmitter.module.exports.api.verify (/project/node_modules/eslint/lib/eslint.js:795:35)
    at processText (/project/node_modules/eslint/lib/cli-engine.js:187:27)
    at CLIEngine.executeOnText (/project/node_modules/eslint/lib/cli-engine.js:672:26)
    at Object.cli.execute (/project/node_modules/eslint/lib/cli.js:178:36)
```

**Comment by aparedes** [comment]
This is because you installed the latest eslint (2.3.0) which is not compatible with babel-eslint. 
Try installing `estlint@1.x` that worked for me.

**Comment by grabbou** [comment]
@facebook-github-bot answered
