### ISSUE TITLE
Uncaught Error: Requiring module "NativeModules" which threw an exception

### ISSUE THREAD

**Issue by nowaits** [facebook/react-native#6397]
on Mac EI Captian React Native 0.22-stable

_**

ExceptionsManager.js:76Error: Requiring unknown module "ReactPerf", stack:
Error: Requiring unknown module "ReactPerf"
at requireImpl (require.js:53)
at _require (require.js:31)
at ReactPerf (Systrace.js:35)
at Object.Systrace.setEnabled (Systrace.js:51)
at Systrace.js:203
at requireImpl (require.js:71)
at _require (require.js:31)
at MessageQueue.js:16
at requireImpl (require.js:71)
at _require (require.js:31)reactConsoleError @ ExceptionsManager.js:76
debuggerWorker.js:18 Uncaught Error: Uncaught Error: Requiring module "NativeModules" which threw an exception

**_

**Comment by solome** [comment]
on Mac EI Captian in react-native@0.22.0-rc4

```
E/ReactNativeJS: Error: Requiring unknown module "ReactPerf", stack:
                                                                       r@file://index.android.bundle:1:623
                                                                       n@file://index.android.bundle:1:413
                                                                       i@file://index.android.bundle:4:12072
                                                                       setEnabled@file://index.android.bundle:4:24301
                                                                       file://index.android.bundle:4:13453
                                                                       r@file://index.android.bundle:1:747
                                                                       n@file://index.android.bundle:1:413
                                                                       file://index.android.bundle:15:4872
                                                                       r@file://index.android.bundle:1:747
                                                                       n@file://index.android.bundle:1:413
                                                                       file://index.android.bundle:15:11998
                                                                       r@file://index.android.bundle:1:747
                                                                       n@file://index.android.bundle:1:413
                                                                       file://index.android.bundle:13:13222
                                                                       r@file://index.android.bundle:1:747
                                                                       n@file://index.android.bundle:1:413
                                                                       file://index.android.bundle:15:10346
                                                                       r@file://index.android.bundle:1:747
                                                                       n@file://index.android.bundle:1:413
                                                                       u@file://index.android.bundle:16:4177
                                                                       file://index.android.bundle:16:3958
                                                                       r@file://index.android.bundle:1:747
                                                                       r@file://index.android.bundle:1:476
                                                                       n@file://index.android.bundle:1:413
                                                                       global code@file://index.android.bundle:17:9067
```

```
PID: 26314
                                                                        java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error: Requiring module "NativeModules" which threw an exception (file://index.android.bundle:1)
                                                                            at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:171)
                                                                            at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:879)
                                                                            at com.facebook.react.ReactInstanceManagerImpl.access$700(ReactInstanceManagerImpl.java:104)
                                                                            at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:200)
                                                                            at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:183)
                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                         Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error: Requiring module "NativeModules" which threw an exception (file://index.android.bundle:1)
                                                                            at com.facebook.react.common.futures.SimpleSettableFuture.get(SimpleSettableFuture.java:68)
                                                                            at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:147)
                                                                            at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:879) 
                                                                            at com.facebook.react.ReactInstanceManagerImpl.access$700(ReactInstanceManagerImpl.java:104) 
                                                                            at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:200) 
                                                                            at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:183) 
                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:292) 
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                            at java.lang.Thread.run(Thread.java:818) 
                                                                         Caused by: java.lang.RuntimeException: Error: Requiring module "NativeModules" which threw an exception (file://index.android.bundle:1)
                                                                            at com.facebook.react.bridge.ReactBridge.loadScriptFromAssets(Native Method)
                                                                            at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:32)
                                                                            at com.facebook.react.bridge.CatalystInstanceImpl$2.call(CatalystInstanceImpl.java:157)
                                                                            at com.facebook.react.bridge.CatalystInstanceImpl$2.call(CatalystInstanceImpl.java:148)
                                                                            at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:73)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:187)
                                                                            at java.lang.Thread.run(Thread.java:818) 
```

**Comment by zsajjad** [comment]
@nowaits what was the solution?

**Comment by Mr7Cat** [comment]
the solution?

**Comment by InnerPeace080** [comment]
+1

**Comment by skeie** [comment]
I also get this error. Do anyone have a solution?

**Comment by vonovak** [comment]
I have met this error elsewhere, but this might help: if you run `npm list` you'll probably see some error about unmet dependency, solve it by `npm install`

**Comment by huyn** [comment]
as @vonovak said, run 'npm list' to check what is wrong about your dependency. but only 'npm install' may not be enough. I have met the same error, but my logs indicate 'peer dep missing: react@^0.14.5', so I add '"react":"0.14.5"' to dependencies in package.json, it worked.
