### ISSUE TITLE
[Android] Failed to initialize bridge

### ISSUE THREAD

**Issue by esauter5** [facebook/react-native#6409]
I opened the Android emulator for the first time in a couple of weeks yesterday and received this error:

![screen shot 2016-03-10 at 12 00 51 pm](https://cloud.githubusercontent.com/assets/1442232/13677438/04ea1f02-e6b8-11e5-95f5-c9129b50f2e7.png)

I've been able to reproduce on RN 0.19.0, 0.21.0, and 0.22.0rc1. This issue is not present on iOS. Using a Mac.

I am able to run my app successfully on my device. I can also create a new project and run that successfully. A peer of mine running the same project is not able to reproduce my issue.

This seems like it will be really hard to reproduce since I can't reproduce across different projects or instances of the same projects on other computers. 

If anyone has any suggestions that might help, I'd love to hear them. Otherwise, I'll close this in a week or so.

**Update**

Today I am unable to use the device as well. Same error.

**Comment by gre** [comment]
Werid. maybe worth looking at what NPM / Android SDK / Watchman different version you have with your peer.

**Comment by browniefed** [comment]
@facebook-github-bot label Android

**Comment by browniefed** [comment]
@facebook-github-bot label Android

**Comment by madwed** [comment]
Hopefully this helps.  I'm having the same problem as @esauter5. The error I get from `logcat "AndroidRuntime"` is 
```
java.lang.RuntimeException: Unable to pause activity {co.fixt/co.fixt.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.react.bridge.JavaScriptModule com.facebook.react.bridge.ReactContext.getJSModule(java.lang.Class)' on a null object reference
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3662)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3621)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3596)
        at android.app.ActivityThread.access$1100(ActivityThread.java:172)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1432)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:5835)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.react.bridge.JavaScriptModule com.facebook.react.bridge.ReactContext.getJSModule(java.lang.Class)' on a null object reference
        at co.fixt.MainActivity.onPause(MainActivity.java:92)
        at android.app.Activity.performPause(Activity.java:6373)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1308)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3648)
        ... 11 more

**Comment by madwed** [comment]
I had the same problem as @esauter5 and it turned out that one of our android modules was throwing an error when it tried to build its constants.

**Comment by esauter5** [comment]
I'll get to this in the next couple of days to determine if it's still an issue or not.

**Comment by Andruschenko** [comment]
I got the same issue. All working fine. After returning to the PC an hour later, making some changes to an Android Native Module I'm writing, I suddenly get this error..

**Comment by esauter5** [comment]
@Andruschenko I currently only have this issue on the emulator for a specific project. The project works fine on an actual Android device and I can run other projects on the emulator.

I would suggest a combination of
1. Trying it out on the device.
2. Upgrading RN version
3. Using `react-native upgrade` to update some of the android build files

I'll report back if I'm ever able to get the emulator working, but in the meantime, I'm going to close this since I can work on a device and it's not as issue with fresh projects.

**Comment by Andruschenko** [comment]
It turned out my issue is the same as @madwed . I sent a non-supported datatype as constant to JS with the getConstants() method in a native module I'm writing which caused the error. Making it a String with `String.valueof()` solved the issue for me.

Thanks for your help @esauter5 anyway!

**Comment by ckurban** [comment]
Hi All. I have a same issue on device and on emulator. 
I have RN@0.30.0 and react@15.2.0 anyone has any idea?
