### ISSUE TITLE
Fresh install of react-native results in :CFBundleIdentifier error

### ISSUE THREAD

**Issue by tonyarkles** [facebook/react-native#6492]
I'm on Mac OSX 10.11.3, Xcode 7.2.1. I just did a fresh install and followed the instructions for getting set up for iOS.

When I run "react-native run-ios" in my project, it proceeds for a while, says "*** BUILD SUCCEEDED ***", and then spits out this error:

```
Installing build/Build/Products/Debug-iphonesimulator/TestPhotoProject.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/aja042/workspace/react-native/TestPhotoProject/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/TestPhotoProject.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:469:13)
    at Object.execFileSync (child_process.js:489:13)
    at _runIOS (runIOS.js:77:34)
    at runIOS.js:24:5
    at tryCallTwo (/Users/aja042/workspace/react-native/TestPhotoProject/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/aja042/workspace/react-native/TestPhotoProject/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/aja042/workspace/react-native/TestPhotoProject/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (runIOS.js:23:10)
    at Object.run (/Users/aja042/workspace/react-native/TestPhotoProject/node_modules/react-native/local-cli/cli.js:86:13)
    at Object.<anonymous> (/Users/aja042/.nvm/versions/node/v5.8.0/lib/node_modules/react-native-cli/index.js:73:7)
```

There's a stackoverflow answer that says the solution is to run everything with "sudo", but that scares the crap out of me, especially since things like nvm are installed for my local user and not for root.

Is this something I did wrong?

**Comment by tonyarkles** [comment]
Looks like I was following directions out of a book from December 2015 that are now outdated. I opened `ios/TestPhotoProject.xcodeproj/` instead and it's working fine.

**Comment by onionhammer** [comment]
Following directions from https://facebook.github.io/react-native/docs/getting-started.html#content  and it fails with that error. (for me)

**Comment by agenthunt** [comment]
Same here. Cant seem to find a way to fix this.
