### ISSUE TITLE
Bullet Character causes app to crash

### ISSUE THREAD

**Issue by jayesbe** [facebook/react-native#6660]
Came across an interesting issue.

```
<Text numberOfLines={1} style={{textAlign: 'center'}}>•</Text>
```

the above line of code contains a utf8 bullet character • bullet (U+2022)

Which when used causes this crash
```
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                                                 Process: com.kismatmedia.karmany.dev.debug, PID: 7517
                                                                                 java.lang.StackOverflowError
                                                                                     at java.util.HashMap.get(HashMap.java:302)
                                                                                     at com.facebook.react.views.text.ReactFontManager.getTypeface(ReactFontManager.java:58)
                                                                                     at com.facebook.react.views.text.CustomStyleSpan.apply(CustomStyleSpan.java:108)
                                                                                     at com.facebook.react.views.text.CustomStyleSpan.updateMeasureState(CustomStyleSpan.java:58)
                                                                                     at android.text.MeasuredText.addStyleRun(MeasuredText.java:198)
                                                                                     at android.text.StaticLayout.generate(StaticLayout.java:281)
                                                                                     at android.text.StaticLayout.<init>(StaticLayout.java:140)
                                                                                     at android.text.StaticLayout.<init>(StaticLayout.java:90)
                                                                                     at android.text.StaticLayout.<init>(StaticLayout.java:68)
                                                                                     at android.text.StaticLayout.<init>(StaticLayout.java:48)
                                                                                     at com.facebook.react.views.text.ReactTextShadowNode$1.measure(ReactTextShadowNode.java:229)
                                                                                     at com.facebook.csslayout.CSSNode.measure(CSSNode.java:137)
                                                                                     at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:294)
                                                                                     at com.facebook.csslayout.LayoutEngine.layoutNode(LayoutEngine.java:210)
                                                                                     at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:492)
                                                                                     at com.facebook.csslayout.LayoutEngine.layoutNode(LayoutEngine.java:210)
                                                                                     at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:492)
                                                                                     at com.facebook.csslayout.LayoutEngine.layoutNode(LayoutEngine.java:210)
                                                                                     at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:492)
```

RN 0.21
Android
Using Linux (Ubuntu 14.04)

**Comment by jayesbe** [comment]
```
                <TouchableOpacity style={{width: 200}} key={key} onPress={()=>{ console.log('good') }}>
                    <View style={this.getChildrenStyle()} >
                        <Text numberOfLines={1} style={[{textAlign: 'center'}]}>{age}•</Text>
                    </View>
                </TouchableOpacity>
```

actual rendered component

**Comment by jayesbe** [comment]
Actually it looks like it was being caused by a third party component

autoresponsive-react-native 

closing this.

**Comment by artem-russkikh** [comment]
Maybe related to #5997

**Comment by jayesbe** [comment]
@artem-russkikh  Same error. Though not using autoresponsive-react-native corrects the issue.
