### ISSUE TITLE
react-native init AwesomeProject fails (throw new Constructor(this._buildMessage(msg));)

### ISSUE THREAD

**Issue by dwilt** [facebook/react-native#6675]
I just downloaded the latest react native tools, updated homebrew and am trying to create a fresh project from the [Getting Started](https://facebook.github.io/react-native/docs/getting-started.html#content) page. I ran `react-native init AwesomeProject` and got this:

```shell
dwilt:Desktop dwilt$ react-native init AwesomeProject
This will walk you through creating a new React Native project in /Users/dwilt/Desktop/AwesomeProject
Installing react-native package from npm...
/Users/dwilt/Desktop/AwesomeProject/node_modules/babel-core/lib/transformation/file/logger.js:39
    throw new Constructor(this._buildMessage(msg));
    ^

ReferenceError: [BABEL] /Users/dwilt/Desktop/AwesomeProject/node_modules/react-native/local-cli/bundle/bundle.js: Using removed Babel 5 option: base.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
    at Logger.error (/Users/dwilt/Desktop/AwesomeProject/node_modules/babel-core/lib/transformation/file/logger.js:39:11)
    at OptionManager.mergeOptions (/Users/dwilt/Desktop/AwesomeProject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:20)
    at OptionManager.init (/Users/dwilt/Desktop/AwesomeProject/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
    at File.initOptions (/Users/dwilt/Desktop/AwesomeProject/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File (/Users/dwilt/Desktop/AwesomeProject/node_modules/babel-core/lib/transformation/file/index.js:123:22)
    at Pipeline.transform (/Users/dwilt/Desktop/AwesomeProject/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
    at Object.transformFileSync (/Users/dwilt/Desktop/AwesomeProject/node_modules/babel-core/lib/api/node.js:124:10)
    at compile (/Users/dwilt/Desktop/AwesomeProject/node_modules/babel-register/lib/node.js:98:20)
    at loader (/Users/dwilt/Desktop/AwesomeProject/node_modules/babel-register/lib/node.js:126:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dwilt/Desktop/AwesomeProject/node_modules/babel-register/lib/node.js:136:7)
dwilt:Desktop dwilt$  
```
React Native version...
```shell
dwilt:AwesomeProject dwilt$ react-native --version
react-native-cli: 0.2.0
react-native: 0.22.2
dwilt:AwesomeProject dwilt$ 
```

OSX: `10.11.4`
Node: `v5.7.1`

I saw other issues that seemed similar to this:
* https://github.com/facebook/react-native/issues/4030
* https://github.com/facebook/react-native/issues/4690

but since I can't install - I can't remove a `.babelrc` file which isn't even there. Not sure what to do here.

**Comment by dwilt** [comment]
Thank you: https://github.com/facebook/react-native/issues/4030#issuecomment-156441992

Fixed, by deleting the `.babelrc` in your home directory:
`rm ~/.babelrc`

**Comment by bazzel** [comment]
I neither have a `.babelrc` nor a `.babel.json` in my home folder. After running `react-native init AwesomeProject` I get the same error and end up with a `~/.babel.json` file with an empty object in it.

```
➜  AwesomeProject react-native --version
react-native-cli: 0.2.0
react-native: 0.24.1
➜  AwesomeProject cat ~/.babel.json
{}%
```
