### ISSUE TITLE
When running app on IOS simulator I'm getting: ReferenceError: GLOBAL is not defined

### ISSUE THREAD

**Issue by jamesone** [facebook/react-native#6699]
Something is wrong here! I've tried:

- Uninstalling and reinstalling the node_modules
- Emptying the cache
- Turning computer on & off
- Creating a new react-native project & reinstalling everything from scratch.

I've looked everywhere for a fix & can't seem to find one :-1: Hopefully someone else has came across this and found a fix. I hadn't done anything on the project for around a week and when I started it up it threw all these errors (Check the stack trace below). I'm also using `npm 3.7.2`

I've got react@0.14.6 installed globally on my **_mac_** (running yosemite) & these are the packages I'm working with in the project: 

```
"dependencies": {
    "react": "^0.14.7",
    "react-native": "^0.22.2",
    "react-native-router-flux": "^2.3.1",
    "react-redux": "^4.4.0",
    "redux": "^3.3.0",
    "redux-thunk": "^1.0.3"
  },
   "devDependencies": {
    "babel-core": "^6.3.17",
    "babel-preset-react-native": "^1.4.0",
    "babel-preset-stage-0": "^6.3.13",
    "remote-redux-devtools": "^0.1.1",
    "remote-redux-devtools-on-debugger": "^0.2.4",
    "remotedev-server": "0.0.1"
  }
```

# Stack trace:

```
error-guard.js:79Error: 
 stack: ReferenceError: GLOBAL is not defined
    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true:6591:7
    at requireImpl (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:77:13)
    at requireImpl (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:45:25)
    at require (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:37:8)
    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true:67858:2
    at messageHandlers.executeApplicationScript (http://localhost:8081/debuggerWorker.js:18:5)
    at DedicatedWorkerGlobalScope.onmessage (http://localhost:8081/debuggerWorker.js:33:5)
 line: undefined
 message: GLOBAL is not defined ReferenceError: GLOBAL is not define
```

### and 

```
stack: Error: Requiring module "InitializeJavaScriptAppEngine" which threw an exception
    at requireImpl (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:63:7)
    at require (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:37:8)
    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true:6469:1
    at requireImpl (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:77:13)
    at require (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:37:8)
    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true:6328:33
    at requireImpl (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:77:13)
    at require (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:37:8)
    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true:6311:16
    at requireImpl (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:77:13)
 line: undefined
 message: Requiring module "InitializeJavaScriptAppEngine" which threw an exception Error: Requiring module "InitializeJavaScriptAppEngine" which threw an exception
```

**Comment by hojberg** [comment]
I had a similar issue with d3. I think the latest version of javascriptcore via an OSX upgrade remove the global context all together.

**Comment by janicduplessis** [comment]
Do you have a .babelrc file in your project? If so what does it looks like? It seems like the issue that happens when allowTopLevelThis is not set to true for transform-es2015-modules-commonjs.

**Comment by lacker** [comment]
Since this issue has been stale for a while and we never got to a crisp repro I'm going to close it. Feel free to reopen if you have more info.
