### ISSUE TITLE
Could not connect to development server

### ISSUE THREAD

**Issue by deveshmittal** [facebook/react-native#6729]
Not able to run the ios project on the IOS simulator.

Every time I run the project on Xcode , the following error message appears.

```
ERROR  watchman--no-pretty get-sockname returned with exit code null dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /usr/local/Cellar/watchman/4.4.0/libexec/bin/watchman
  Reason: image not found

Error: watchman--no-pretty get-sockname returned with exit code null dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /usr/local/Cellar/watchman/4.4.0/libexec/bin/watchman
  Reason: image not found

    at ChildProcess.<anonymous> (/Users/devesh/Desktop/ReactExamples/devdactic_tabs/node_modules/react-native/node_modules/sane/node_modules/fb-watchman/index.js:198:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:475:12)

```

**Comment by dsibiski** [comment]
@facebook-github-bot stack-overflow

**Comment by jolt-temporary** [comment]
Doesn't this seem like a bug though? I'm getting it too.
