### ISSUE TITLE
android NetInfo source code is updated but grade not

### ISSUE THREAD

**Issue by uyson** [facebook/react-native#6736]
android NetInfo source code is updated but grade not, 
react-native version: 0.22.2
```
com.facebook.react.bridge.NativeArgumentsParseException: NetInfo.getCurrentConnectivity got 0 arguments, expected 2
                                                                          at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:227)
                                                                          at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:158)
                                                                          at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:58)
                                                                          at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:428)
                                                                          at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
                                                                          at android.os.Handler.handleCallback(Handler.java:733)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:184)
                                                                          at java.lang.Thread.run(Thread.java:841)
``` 

relative commit: https://github.com/facebook/react-native/pull/5512/files

**Comment by satya164** [comment]
Run `react-native upgrade` in your project to update your code.

**Comment by satya164** [comment]
@facebook-github-bot answered

**Comment by rkostrab** [comment]
@uyson did you solve this issue?

**Comment by uyson** [comment]
@rkostrab  yes, thanks all

**Comment by rkostrab** [comment]
@uyson can you explain how did you overcome this bug?

**Comment by uyson** [comment]
@rkostrab  ```react-native upgrade```

**Comment by rkostrab** [comment]
@uyson I've akready tried rn upgrade but this procedure wants to rewrite my existing files do default init state - so this wipes my lib or module integrations. So which file did you let to rewrite?

**Comment by satya164** [comment]
@rkostrab You can view the diff and do the changes yourself. You need to update the `android/app/build.gradle` file.

**Comment by jayshah123** [comment]
I recently did a react-native upgrade and merged build.gradle files appropriately from 0.18 -> 0.26 still giving following error :` [TypeError: undefined is not an object (evaluating 'RCTNetInfo.getCurrentConnectivity().then')`
```
 E/unknown:React: Exception in native call from JS
 E/unknown:React: com.facebook.react.bridge.NativeArgumentsParseException: NetInfo.getCurrentConnectivity got 0 arguments, expected 2
 E/unknown:React:     at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:227)
 E/unknown:React:     at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:158)
 E/unknown:React:     at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:58)
 E/unknown:React:     at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:428)
 E/unknown:React:     at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
 E/unknown:React:     at android.os.Handler.handleCallback(Handler.java:739)
 E/unknown:React:     at android.os.Handler.dispatchMessage(Handler.java:95)
 E/unknown:React:     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
 E/unknown:React:     at android.os.Looper.loop(Looper.java:148)
 E/unknown:React:     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:184)
 E/unknown:React:     at java.lang.Thread.run(Thread.java:818)
```
