### ISSUE TITLE
react-native bundle throws SyntaxError in dev and prod mode

### ISSUE THREAD

**Issue by mihirk** [facebook/react-native#6804]
Hello,
I am using react-native to bundle an Android APK. 
I am able to run it properly in dev mode but have not been able to release a signed apk yet.
```
node version: `v5.10.0`
npm version: `3.8.3`
react-native version: `0.22.2`
```
Tried with babel-core versions
`6.5.1`
`6.4.5`
`6.7.4`

The error I am getting on running either of these commands
`react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/`

`react-native bundle --platform android --dev true --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/`

is 

```
bundle: Created ReactPackager
uncaught error Error: SyntaxError: /Users/'username'/projects/personal/openchs/openchs-client/node_modules/react-native/Libraries/react-native/react-native.js: Unexpected token (120:2)
  // Note: this must be placed last to prevent eager
  // evaluation of the getter-wrapped submodules above
  ...require('React'),
};

if (__DEV__) {
    at Parser.pp.raise (/Users/mihir/projects/personal/openchs/openchs-client/node_modules/babylon/index.js:1378:13)
    at Parser.pp.unexpected (/Users/mihir/projects/personal/openchs/openchs-client/node_modules/babylon/index.js:2817:8)
    at Parser.pp.parseIdentifier (/Users/mihir/projects/personal/openchs/openchs-client/node_modules/babylon/index.js:1227:10)
    at Parser.pp.parsePropertyName (/Users/mihir/projects/personal/openchs/openchs-client/node_modules/babylon/index.js:1070:135)
    at Parser.pp.parseObj (/Users/mihir/projects/personal/openchs/openchs-client/node_modules/babylon/index.js:986:12)
    at Parser.pp.parseExprAtom (/Users/mihir/projects/personal/openchs/openchs-client/node_modules/babylon/index.js:718:19)
    at Parser.parseExprAtom (/Users/mihir/projects/personal/openchs/openchs-client/node_modules/babylon/index.js:4305:22)
    at Parser.pp.parseExprSubscripts (/Users/mihir/projects/personal/openchs/openchs-client/node_modules/babylon/index.js:504:19)
    at Parser.pp.parseMaybeUnary (/Users/mihir/projects/personal/openchs/openchs-client/node_modules/babylon/index.js:484:19)
    at Parser.pp.parseExprOps (/Users/mihir/projects/personal/openchs/openchs-client/node_modules/babylon/index.js:415:19)
See logs /var/folders/zj/sk4075x566l8jdl1gwzjl79h0000gn/T/react-packager.log
    at SocketClient._handleMessage (SocketClient.js:144:23)
    at BunserBuf.<anonymous> (SocketClient.js:53:42)
    at emitOne (events.js:90:13)
    at BunserBuf.emit (events.js:182:7)
    at BunserBuf.process (/Users/mihir/projects/personal/openchs/openchs-client/node_modules/bser/index.js:289:10)
    at /Users/mihir/projects/personal/openchs/openchs-client/node_modules/bser/index.js:244:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

More of my code is here - https://github.com/OpenCHS/openchs-client

**Comment by mihirk** [comment]
Fixed it. Was missing babel's stage-0 preset in devDependencies.
