### ISSUE TITLE
ExtractDocs.js is refering to non-existing file ('../Libraries/Components/SliderIOS/Slider.js'). Cannot generate docs

### ISSUE THREAD

**Issue by niborb** [facebook/react-native#6836]
Seems to be introduced with commit a461d25601a3f63902a219632bdb6770993c60f0.

It's now impossible to generate the documentation:

> Connect
500 Error: ENOENT: no such file or directory, open '../Libraries/Components/SliderIOS/Slider.js'
at Error (native)
at Object.fs.openSync (fs.js:549:18)
at Object.fs.readFileSync (fs.js:397:15)
at renderComponent (/Users/robinbreuker/dev-tools/github-patch/react-native/website/server/extractDocs.js:154:8)
at Array.map (native)
at module.exports (/Users/robinbreuker/dev-tools/github-patch/react-native/website/server/extractDocs.js:301:16)
at execute (/Users/robinbreuker/dev-tools/github-patch/react-native/website/server/convert.js:137:3)
at Object.handle (/Users/robinbreuker/dev-tools/github-patch/react-native/website/server/server.js:49:7)
at next (/Users/robinbreuker/dev-tools/github-patch/react-native/website/node_modules/connect/lib/proto.js:190:15)
at Function.app.handle (/Users/robinbreuker/dev-tools/github-patch/react-native/website/node_modules/connect/lib/proto.js:198:3)

see: https://github.com/facebook/react-native/commit/a461d25601a3f63902a219632bdb6770993c60f0#diff-c9fbe764b907371487e5387d2ffa1bbfR212

**Comment by niborb** [comment]
ping @mkonicek

**Comment by brentvatne** [comment]
Looks like this is resolved:

```
  '../Libraries/Components/Slider/Slider.js',
  '../Libraries/Components/SliderIOS/SliderIOS.ios.js',
```

:)
