### ISSUE TITLE
Cannot run examples: SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by aforty** [facebook/react-native#6941]
I'm trying to run the examples project but I can't even get `npm start` to run. I've tried clearing out `nvm`, `node_modules`, reinstalling, and nothing seems to work.

What else can I try?

```
$ node --version && npm --version
v5.10.1
3.8.3
```

```
$ npm start

> react-native@1000.0.0 start /Users/aforty/Code/react-native
> /usr/bin/env bash -c './packager/packager.sh "$@" || true' --

/Users/aforty/Code/react-native/packager/react-packager/src/Server/index.js:545
      ),
      ^

SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/aforty/Code/react-native/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (buildBundle.js:14:16)
    at Module._compile (module.js:413:34)
```

**Comment by aforty** [comment]
Aaaand as soon as I post this I decide to get the latest (when I had just gotten latest yesterday) and it appears to be fixed. Again the act of asking for help solves it. :+1:
