### ISSUE TITLE
Android build with proguard throws exceptions.

### ISSUE THREAD

**Issue by WhatAKitty** [facebook/react-native#6975]
> E/AndroidRuntime: FATAL EXCEPTION: mqt_js
                                                 Process: com.gnet.gwxuetang, PID: 6397
                                                 java.lang.NoSuchMethodError: no method with name='<init>' signature='(Lcom/facebook/jni/HybridData;)V' in class Lcom/facebook/react/bridge/queue/NativeRunnable;
                                                     at com.facebook.react.bridge.ReactBridge.setGlobalVariable(Native Method)
                                                     at com.facebook.react.bridge.CatalystInstanceImpl.initializeBridge(CatalystInstanceImpl.java:127)
                                                     at com.facebook.react.bridge.CatalystInstanceImpl.access$200(CatalystInstanceImpl.java:39)
                                                     at com.facebook.react.bridge.CatalystInstanceImpl$1.call(CatalystInstanceImpl.java:96)
                                                     at com.facebook.react.bridge.CatalystInstanceImpl$1.call(CatalystInstanceImpl.java:91)
                                                     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:73)
                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:187)
                                                     at java.lang.Thread.run(Thread.java:841)
04-14 19:19:10.127 354-506/? W/ActivityManager:   Force finishing activity com.gnet.gwxuetang/.MainActivity
04-14 19:19:10.672 6397-6397/? W/unknown:React: Caught exception after cancelling react context init
                                                java.lang.RuntimeException: Failed to initialize bridge
                                                    at com.facebook.react.bridge.CatalystInstanceImpl.<init>(CatalystInstanceImpl.java:103)
                                                    at com.facebook.react.bridge.CatalystInstanceImpl.<init>(CatalystInstanceImpl.java:39)
                                                    at com.facebook.react.bridge.CatalystInstanceImpl$Builder.build(CatalystInstanceImpl.java:540)
                                                    at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:864)
                                                    at com.facebook.react.ReactInstanceManagerImpl.access$700(ReactInstanceManagerImpl.java:104)
                                                    at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:200)
                                                    at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:183)
                                                    at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                    at java.lang.Thread.run(Thread.java:841)
                                                 Caused by: java.lang.InterruptedException
                                                    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:975)
                                                    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1281)
                                                    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:202)
                                                    at com.facebook.react.common.futures.SimpleSettableFuture.get(SimpleSettableFuture.java:66)
                                                    at com.facebook.react.bridge.CatalystInstanceImpl.<init>(CatalystInstanceImpl.java:90)
                                                    at com.facebook.react.bridge.CatalystInstanceImpl.<init>(CatalystInstanceImpl.java:39) 
                                                    at com.facebook.react.bridge.CatalystInstanceImpl$Builder.build(CatalystInstanceImpl.java:540) 
                                                    at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:864) 
                                                    at com.facebook.react.ReactInstanceManagerImpl.access$700(ReactInstanceManagerImpl.java:104) 
                                                    at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:200) 
                                                    at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:183) 
                                                    at android.os.AsyncTask$2.call(AsyncTask.java:288) 
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                    at java.lang.Thread.run(Thread.java:841)

**Comment by WhatAKitty** [comment]
When I open the app after installing, it caused the above errors.

**Comment by AndrewJack** [comment]
Are you using the latest proguard config?
https://github.com/facebook/react-native/blob/master/local-cli/generator-android/templates/src/app/proguard-rules.pro

**Comment by AndrewJack** [comment]
@facebook-github-bot stack-overflow

**Comment by WhatAKitty** [comment]
I found my errors. I should set jpush proguard config in app proguard config not it owns. I'll close this issue.

**Comment by BoluoPi** [comment]
@WhatAKitty 
what have you done to solve this errors? I have just met the same error as you met before? please share your solution.

**Comment by WhatAKitty** [comment]
The error I met was caused by jpush configuration.
