### ISSUE TITLE
Include the user created source reference in traces, more helpful error messaging

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#7016]
Quite often, when you make mistakes in your code, you get these useless error messages that don't indicate the source of the problem in your code, just a reference to some internal react code. It would be extremely helpful if the trace would include a reference to your local code that is the source of the exception. 

E.g., this one occurs when you render the NavigationHeader in Navigation Experimental if you reference a variable in your code that doesn't exist.

    Argument 0 (<null>) of RCTUIManager.updateView could not be processed. Aborting method call.
    Cannot read property '_currentElement' of null
    TypeError: Cannot read property '_currentElement' of null
    at ReactCompositeComponentMixin._updateRenderedComponent (/tmp/react-native.js:16341:46)

Here is another one. It tries to give a helpful hint but doesn't indicate the location in the code where the problem occurs.

    Objects are not valid as a React child (found: object with keys {dispatchConfig, dispatchMarker, nativeEvent, type, target, currentTarget, eventPhase, bubbles, cancelable, timeStamp, defaultPrevented, isTrusted, touchHistory, isDefaultPrevented, isPropagationStopped, _dispatchListeners, _dispatchIDs}). 
    If you meant to render a collection of children, 
    use an array instead or wrap the object using createFragment(object) from the React add-ons. 
    Check the render method of `Text`.
    at invariant (/tmp/react-native.js:14101:7)
    at traverseAllChildrenImpl (/tmp/react-native.js:29065:44)
    at traverseAllChildren (/tmp/react-native.js:29093:8)
    at flattenChildren (/tmp/react-native.js:29141:1)
    at ReactMultiChild.Mixin._reconcilerUpdateChildren (/tmp/react-native.js:28499:14)
    at ReactMultiChild.Mixin._updateChildren (/tmp/react-native.js:28638:23)
    at ReactMultiChild.Mixin.updateChildren (/tmp/react-native.js:28613:6)
    at ReactNativeBaseComponent.Mixin.receiveComponent (/tmp/react-native.js:28190:6)
    at Object.ReactReconciler.receiveComponent (/tmp/react-native.js:14471:18)
    at ReactCompositeComponentMixin._updateRenderedComponent (/tmp/react-native.js:16344:17)

I would say is that the lack of proper root sourcing of errors, is my number one loss of time factor by far on RN,

**Comment by iniestano8** [comment]
totally agree
i suffered enough from this error

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/include-the-user-created-source-reference-in-traces-more-helpful-error-messaging

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
