### ISSUE TITLE
react-native init fails with Couldn't find preset "react" relative to directory

### ISSUE THREAD

**Issue by arunabha** [facebook/react-native#7032]
Running react-native init aborts with error 'Error: Couldn't find preset "react" relative to directory "/Users/agh/dev"'

The detailed error is

```bash
react-native init test
This will walk you through creating a new React Native project in /Users/agh/dev/test-react/test
Installing react-native package from npm...
/Users/agh/dev/test-react/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372
          throw new Error("Couldn't find preset " + JSON.stringify(val) + " relative to directory " + JSON.stringify(dirname));
          ^

Error: Couldn't find preset "react" relative to directory "/Users/agh/dev"
    at /Users/agh/dev/test-react/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/agh/dev/test-react/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/Users/agh/dev/test-react/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/Users/agh/dev/test-react/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at OptionManager.addConfig (/Users/agh/dev/test-react/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:207:10)
    at OptionManager.findConfigs (/Users/agh/dev/test-react/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413:16)
    at OptionManager.init (/Users/agh/dev/test-react/test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:461:12)
    at compile (/Users/agh/dev/test-react/test/node_modules/babel-register/lib/node.js:81:45)
    at loader (/Users/agh/dev/test-react/test/node_modules/babel-register/lib/node.js:126:14)
```

I have a fresh install of node (5.10.1) and npm (3.8.3) through nvm. 

I followed the suggestions listed [here](http://stackoverflow.com/questions/35787696/react-native-init-gives-error-couldnt-find-preset-es2015), however none of them helped. 

The log from react-native init is attached
[install.txt](https://github.com/facebook/react-native/files/223443/install.txt)

Any help is greatly appreciated :-)

**Comment by jhack32** [comment]
Maybe this might help? @arunabha 

http://stackoverflow.com/questions/33538403/error-couldnt-find-preset-react-when-installed-using-npm-install-global-ba

**Comment by mauricesvay** [comment]
Removing the `.babelrc` file in the folder solved the problem for me (`/Users/agh/dev` in your case).

**Comment by arunabha** [comment]
Yep, that did the trick :-)

Thanks Maurice !
