### ISSUE TITLE
[iOS] some gif are taking too much memory

### ISSUE THREAD

**Issue by seph14** [facebook/react-native#7054]
I'm not sure if this is a bug, but when adding this gif to a reading view in our app, it crashes the app.
(in simulator the memory jumps up by 500MB while the the gif is only 1.2MB)

Would this has anything to do with how react deals with gifs internally? As if using web view those gifs are just ok.

and here is the link to the gif:
https://d262ilb51hltx0.cloudfront.net/max/1600/1*95sOrFxIWbop3urblYU-5A.gif

**Comment by nikuz** [comment]
Hi, i can also stable to reproduce the crash of my app on Android, seems that the reason is the gif file. 
See the logcat trace:
```
I/ReactNativeJS( 4669): https://app-test.gloria.tv/image/smiley-nunrazz-52x30.gif
I/art     ( 4669): Background partial concurrent mark sweep GC freed 46633(2MB) AllocSpace objects, 3(466KB) LOS objects, 14% free, 23MB/27MB, paused 4.363ms total 755.059ms
E/AndroidRuntime( 4669): FATAL EXCEPTION: Thread-325
E/AndroidRuntime( 4669): Process: com.gtvapp, PID: 4669
E/AndroidRuntime( 4669): java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.gtvapp-2/lib/x86/libgifimage.so"
E/AndroidRuntime( 4669): 	at java.lang.Runtime.load(Runtime.java:331)
E/AndroidRuntime( 4669): 	at java.lang.System.load(System.java:981)
E/AndroidRuntime( 4669): 	at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
E/AndroidRuntime( 4669): 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:209)
E/AndroidRuntime( 4669): 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:178)
E/AndroidRuntime( 4669): 	at com.facebook.react.modules.fresco.FrescoModule$FrescoHandler.loadLibrary(FrescoModule.java:119)
E/AndroidRuntime( 4669): 	at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
E/AndroidRuntime( 4669): 	at com.facebook.imagepipeline.gif.GifImage.ensure(GifImage.java:40)
E/AndroidRuntime( 4669): 	at com.facebook.imagepipeline.gif.GifImage.create(GifImage.java:62)
E/AndroidRuntime( 4669): 	at com.facebook.imagepipeline.animated.factory.AnimatedImageFactory.decodeGif(AnimatedImageFactory.java:67)
E/AndroidRuntime( 4669): 	at com.facebook.imagepipeline.decoder.ImageDecoder.decodeGif(ImageDecoder.java:113)
E/AndroidRuntime( 4669): 	at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:88)
E/AndroidRuntime( 4669): 	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:188)
E/AndroidRuntime( 4669): 	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:96)
E/AndroidRuntime( 4669): 	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:128)
E/AndroidRuntime( 4669): 	at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
E/AndroidRuntime( 4669): 	at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
E/AndroidRuntime( 4669): 	at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
E/AndroidRuntime( 4669): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 4669): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 4669): 	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
E/AndroidRuntime( 4669): 	at java.lang.Thread.run(Thread.java:818)
W/ActivityManager( 1230):   Force finishing activity 1 com.gtvapp/.MainActivity
E/art     ( 4669): No implementation found for com.facebook.imagepipeline.gif.GifImage com.facebook.imagepipeline.gif.GifImage.nativeCreateFromNativeMemory(long, int) (tried Java_com_facebook_imagepipeline_gif_GifImage_nativeCreateFromNativeMemory and Java_com_facebook_imagepipeline_gif_GifImage_nativeCreateFromNativeMemory__JI)
I/Process ( 4669): Sending signal. PID: 4669 SIG: 9
E/EGL_emulation(  931): tid 931: eglCreateSyncKHR(1288): error 0x3004 (EGL_BAD_ATTRIBUTE)
W/InputDispatcher( 1230): channel '39237f8b com.gtvapp/com.gtvapp.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher( 1230): channel '39237f8b com.gtvapp/com.gtvapp.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
I/WindowState( 1230): WIN DEATH: Window{39237f8b u0 com.gtvapp/com.gtvapp.MainActivity}
W/InputDispatcher( 1230): Attempted to unregister already unregistered input channel '39237f8b com.gtvapp/com.gtvapp.MainActivity (server)'
I/ActivityManager( 1230): Process com.gtvapp (pid 4669) has died
I/OpenGLRenderer( 1230): Initialized EGL, version 1.4
W/EGL_emulation( 1403): eglSurfaceAttrib not implemented
W/OpenGLRenderer( 1403): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa5880a40, error=EGL_SUCCESS
W/EGL_emulation( 1230): eglSurfaceAttrib not implemented
W/OpenGLRenderer( 1230): Failed to set EGL_SWAP_BEHAVIOR on surface 0x9e178800, error=EGL_SUCCESS
W/InputMethodManagerService( 1230): Got RemoteException sending setActive(false) notification to pid 4669 uid 10077
```

**Comment by soliury** [comment]
Yes, before 0.10.0 this bugs is alway there, and now , when the gif is too large , such as 5M, it will take too much memory, and crash

**Comment by nihgwu** [comment]
that's a known bug for quite a long time, check the discussion here

**Comment by lacker** [comment]
I wouldn't call this a bug, because we don't plan on fixing it per se. Gifs just take up a lot of memory so if you have large gifs you should consider the workaround in the thread that nihgwu linked to.

**Comment by seph14** [comment]
FYI 

> A software bug is an error, flaw, failure or fault in a computer program or system that causes it to produce an incorrect or unexpected result, or to behave in unintended ways.
-wikipedia 

If a gif will eventually lead to crash, this definitely is a bug. 
But I understand that you won't fix it since there are more mature libs out there. 
I do think it worth at least a mention on the documentation of Image component that GIFs don't work well on iOS, so that even though you keep closing issues on gifs, new people in this community don't get confused when their app crashed by a mere GIF.

**Comment by lacker** [comment]
Improving the documentation here sounds like a good idea. Would you be interested in sending a pull request to mention this gotcha in the docs?
