### ISSUE TITLE
"Failed to dispatch window animation state change" crash occasionally on Android

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#7165]
This is tough to reproduce, I haven't noticed any patterns that lead to the crash but I see it at least once a day. @jesseruder pointed out that it might be an Android bug and not necessarily related to react-native. Similar crash report here: https://github.com/facebook/react-native/issues/6760

Has anyone seen this on FB apps? cc @mkonicek 

```
04-22 15:01:56.737  4821  4858 W WindowAnimator: Failed to dispatch window animation state change.
04-22 15:01:56.737  4821  4858 W WindowAnimator: android.os.DeadObjectException
04-22 15:01:56.737  4821  4858 W WindowAnimator:     at android.os.BinderProxy.transactNative(Native Method)
04-22 15:01:56.737  4821  4858 W WindowAnimator:     at android.os.BinderProxy.transact(Binder.java:503)
04-22 15:01:56.737  4821  4858 W WindowAnimator:     at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
04-22 15:01:56.737  4821  4858 W WindowAnimator:     at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
04-22 15:01:56.737  4821  4858 W WindowAnimator:     at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
04-22 15:01:56.737  4821  4858 W WindowAnimator:     at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
04-22 15:01:56.737  4821  4858 W WindowAnimator:     at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
04-22 15:01:56.737  4821  4858 W WindowAnimator:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
04-22 15:01:56.737  4821  4858 W WindowAnimator:     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
04-22 15:01:56.737  4821  4858 W WindowAnimator:     at android.view.Choreographer.doFrame(Choreographer.java:603)
04-22 15:01:56.737  4821  4858 W WindowAnimator:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
04-22 15:01:56.737  4821  4858 W WindowAnimator:     at android.os.Handler.handleCallback(Handler.java:739)
04-22 15:01:56.737  4821  4858 W WindowAnimator:     at android.os.Handler.dispatchMessage(Handler.java:95)
04-22 15:01:56.737  4821  4858 W WindowAnimator:     at android.os.Looper.loop(Looper.java:148)
04-22 15:01:56.737  4821  4858 W WindowAnimator:     at android.os.HandlerThread.run(HandlerThread.java:61)
04-22 15:01:56.737  4821  4858 W WindowAnimator:     at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by rturk** [comment]
What RN version you are using?
Are you also a Navigation framework? 

Why I'm asking (not sure if is related). I had a somewhat similar issue with RNRF. During app startup if try to change before the initial render is completed app will crash. Ref here
https://github.com/aksonov/react-native-router-flux/issues/472

**Comment by ide** [comment]
This is happening with a fairly recent version of RN, close to 0.24.

**Comment by xvalentino** [comment]
Anyone have an idea for a workaround? Since there seems to be some kind of memory leak, is there a way we can manually call some kind of garbage collection? I need my app to be able to run all day, while it always crashes at best about every ~12 hours.

**Comment by tomazahlin** [comment]
Any news on this? I get this crash all the time, it happens randomly while navigating in the app. It feels like it gets worse with every newer react native version, currently using 0.28. If I can provide some more info, please let me know how.

**Comment by timsuchanek** [comment]
Having the same issue!
RN `0.27.2` here

**Comment by timsuchanek** [comment]
Any updates on this? It's a serious bug which occurs a lot of times in my app.
This is the full stack:
```sh

07-19 05:56:24.567   381   765 E CameraService: disconnect: Disconnect called on already disconnected client for device 0
07-19 05:56:24.567   381   765 E CameraService: binderDied: Java client's binder died, removing it from the list of active clients
07-19 05:56:24.664  1051  1243 I OpenGLRenderer: Initialized EGL, version 1.4
07-19 05:56:24.730  1051  1243 W EGL_emulation: eglSurfaceAttrib not implemented
07-19 05:56:24.730  1051  1243 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xddd3e280, error=EGL_SUCCESS
07-19 05:56:24.990   687  1974 E Surface : getSlotFromBufferLocked: unknown buffer: 0xde383420
07-19 05:56:25.254   687   718 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
07-19 05:56:25.331   687  2280 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 2977 uid 10060
07-19 05:56:25.736   687   718 W WindowAnimator: Failed to dispatch window animation state change.
07-19 05:56:25.736   687   718 W WindowAnimator: android.os.DeadObjectException
07-19 05:56:25.736   687   718 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
07-19 05:56:25.736   687   718 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
07-19 05:56:25.736   687   718 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
07-19 05:56:25.736   687   718 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
07-19 05:56:25.736   687   718 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
07-19 05:56:25.736   687   718 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
07-19 05:56:25.736   687   718 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
07-19 05:56:25.736   687   718 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
07-19 05:56:25.736   687   718 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
07-19 05:56:25.736   687   718 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
07-19 05:56:25.736   687   718 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
07-19 05:56:25.736   687   718 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:739)
07-19 05:56:25.736   687   718 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-19 05:56:25.736   687   718 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148)
07-19 05:56:25.736   687   718 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-19 05:56:25.736   687   718 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
07-19 05:56:25.742   687   718 W WindowAnimator: Failed to dispatch window animation state change.
07-19 05:56:25.742   687   718 W WindowAnimator: android.os.DeadObjectException
07-19 05:56:25.742   687   718 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
07-19 05:56:25.742   687   718 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
07-19 05:56:25.742   687   718 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
07-19 05:56:25.742   687   718 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
07-19 05:56:25.742   687   718 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
07-19 05:56:25.742   687   718 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
07-19 05:56:25.742   687   718 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
07-19 05:56:25.742   687   718 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
07-19 05:56:25.742   687   718 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
07-19 05:56:25.742   687   718 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
07-19 05:56:25.742   687   718 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
07-19 05:56:25.742   687   718 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:739)
07-19 05:56:25.742   687   718 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-19 05:56:25.742   687   718 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148)
07-19 05:56:25.742   687   718 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-19 05:56:25.742   687   718 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by tomazahlin** [comment]
My coworker also had this problem a lot of times. He just upgraded the Android SDK and some more packages with Android SDK Manager and he told me that the crashing went away. I will now test the same and will report back with the results and exact versions of the packages.

**Comment by tomazahlin** [comment]
Looks like this is only happening when running Android app in "dev" environment, but not in "production". Is there any way to see and change some dev environment settings, so I could try to enable/disable some things to see if that could maybe help?

**Comment by dslounge** [comment]
Getting this issue too. This happens to me on Genymotion with Hot Reload enabled, after it hot reloads after changing a stateless functional component: 

```
08-30 18:46:39.794  3502  3534 V RenderScript: 0xe01be000 Launching thread(s), CPUs 4
08-30 18:46:39.966   728   759 W WindowAnimator: Failed to dispatch window animation state change.
08-30 18:46:39.966   728   759 W WindowAnimator: android.os.DeadObjectException
08-30 18:46:39.966   728   759 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
08-30 18:46:39.966   728   759 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
08-30 18:46:39.966   728   759 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
08-30 18:46:39.966   728   759 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
08-30 18:46:39.966   728   759 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
08-30 18:46:39.966   728   759 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
08-30 18:46:39.966   728   759 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
08-30 18:46:39.966   728   759 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
08-30 18:46:39.966   728   759 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
08-30 18:46:39.966   728   759 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
08-30 18:46:39.966   728   759 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
08-30 18:46:39.966   728   759 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:739)
08-30 18:46:39.966   728   759 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-30 18:46:39.966   728   759 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148)
08-30 18:46:39.966   728   759 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61)
08-30 18:46:39.966   728   759 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
08-30 18:46:40.330  3502  3534 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
08-30 18:46:40.330  3502  3534 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
08-30 18:46:40.585   728   759 W WindowAnimator: Failed to dispatch window animation state change.
08-30 18:46:40.585   728   759 W WindowAnimator: android.os.DeadObjectException
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:739)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
08-30 18:46:40.585   728   759 W WindowAnimator: Failed to dispatch window animation state change.
08-30 18:46:40.585   728   759 W WindowAnimator: android.os.DeadObjectException
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:739)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61)
08-30 18:46:40.585   728   759 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by jevakallio** [comment]
Seeing this issue a lot in conjunction with `react-native-svg` in Victory Native. 

We have a reproducible case in https://github.com/FormidableLabs/victory-uiexplorer-native - just run the app in Genymotion or Android stock emulator, navigate to `VictoryArea` chart and toggle between datasets until app crashes.

**Comment by bilelmnasser** [comment]
Hello all, any update on this issue ?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/failed-to-dispatch-window-animation-state-change-crash-occasionally-on-android

**Comment by zaguini** [comment]
Still happening...

**Comment by roberthoenig** [comment]
For me as well. Should be reopened.
