### ISSUE TITLE
version 0.24.1 run device build error

### ISSUE THREAD

**Issue by L-Jovi** [facebook/react-native#7267]
when I follow `react init awesome` and build on my device, below error appear :(  
I try to run on simulator and it works well, what happend and what should I do?

```
+ DEST=/Users/mengwenqiaoxindongcom/Library/Developer/Xcode/DerivedData/Demo-briqvyofemfxkdcgbbmztuidiirl/Build/Products/Debug-iphoneos/Demo.app
+ node /Users/mengwenqiaoxindongcom/pra/javascript/react-full_stack/react-native/0.24/Demo/node_modules/react-native/local-cli/cli.js bundle --entry-file index.ios.js --platform ios --dev true --bundle-output /Users/mengwenqiaoxindongcom/Library/Developer/Xcode/DerivedData/Demo-briqvyofemfxkdcgbbmztuidiirl/Build/Products/Debug-iphoneos/Demo.app/main.jsbundle --assets-dest /Users/mengwenqiaoxindongcom/Library/Developer/Xcode/DerivedData/Demo-briqvyofemfxkdcgbbmztuidiirl/Build/Products/Debug-iphoneos/Demo.app
/Users/mengwenqiaoxindongcom/pra/javascript/react-full_stack/react-native/0.24/Demo/node_modules/react-native/packager/react-packager/index.js:121
  return Object.keys(obj).reduce((clone, key) => {
                                            ^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Module._extensions..js (module.js:448:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mengwenqiaoxindongcom/pra/javascript/react-full_stack/react-native/0.24/Demo/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (buildBundle.js:13:23)
    at Module._compile (module.js:430:26)
Command /bin/sh failed with exit code 1
```

**Comment by bslayton** [comment]
I'm having the exact same issue. Please let me know if you figure it out. I just started playing with react native.

**Comment by bslayton** [comment]
Figured out why. I had to set NVM default @ above node version 4 since it opens a new console session.

**Comment by L-Jovi** [comment]
I'm not sure it's nvm cause this issue

```
nvm ls
->       v5.4.0
          system
node -> stable (-> v5.4.0) (default)
stable -> 5.4 (-> v5.4.0) (default)
iojs -> iojs- (-> system) (default)
```

error also exist :(

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-9** [comment]
Hey @L-Jovi and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
