### ISSUE TITLE
App crashes on Android 4.1 after upgrading to v0.24.1

### ISSUE THREAD

**Issue by zsajjad** [facebook/react-native#7277]
We were using RN 0.21 at the beginning of project and app used to work fine on API 16+ but after the recent upgrade of RN, release crashes on API 16.

**Comment by radko93** [comment]
Can you provide more details (e.g. rn stacktrace, error messages from logcat)?

**Comment by bosung90** [comment]
@zsajjad Did you run `react-native upgrade`? As radko93 said, you should give us what you get in logcat when it crashes

**Comment by zsajjad** [comment]
Yes i did run 

> react-native upgrade

. here are logs:

```
adb logcat | grep ourPackageName

I/ActivityThread(30146): Pub [ourPackageName].google_measurement_service: com.google.android.gms.measurement.AppMeasurementContentProvider
D/dalvikvm(30146): Trying to load lib /data/data/[ourPackageName]/lib/libgnustl_shared.so 0x42097da8
D/dalvikvm(30146): Added shared lib /data/data/[ourPackageName]/lib/libgnustl_shared.so 0x42097da8
D/dalvikvm(30146): No JNI_OnLoad found in /data/data/[ourPackageName]/lib/libgnustl_shared.so 0x42097da8, skipping init
D/dalvikvm(30146): Trying to load lib /data/data/[ourPackageName]/lib/libglog.so 0x42097da8
D/dalvikvm(30146): Added shared lib /data/data/[ourPackageName]/lib/libglog.so 0x42097da8
D/dalvikvm(30146): No JNI_OnLoad found in /data/data/[ourPackageName]/lib/libglog.so 0x42097da8, skipping init
D/dalvikvm(30146): Trying to load lib /data/data/[ourPackageName]/lib/libglog_init.so 0x42097da8
D/dalvikvm(30146): Added shared lib /data/data/[ourPackageName]/lib/libglog_init.so 0x42097da8
D/dalvikvm(30146): No JNI_OnLoad found in /data/data/[ourPackageName]/lib/libglog_init.so 0x42097da8, skipping init
D/dalvikvm(30146): Trying to load lib /data/data/[ourPackageName]/lib/libfb.so 0x42097da8
D/dalvikvm(30146): Added shared lib /data/data/[ourPackageName]/lib/libfb.so 0x42097da8
D/dalvikvm(30146): No JNI_OnLoad found in /data/data/[ourPackageName]/lib/libfb.so 0x42097da8, skipping init
D/dalvikvm(30146): Trying to load lib /data/data/[ourPackageName]/lib/libfbjni.so 0x42097da8
D/dalvikvm(30146): Added shared lib /data/data/[ourPackageName]/lib/libfbjni.so 0x42097da8
D/dalvikvm(30146): Trying to load lib /data/data/[ourPackageName]/lib/libfolly_json.so 0x42097da8
D/dalvikvm(30146): Added shared lib /data/data/[ourPackageName]/lib/libfolly_json.so 0x42097da8
D/dalvikvm(30146): No JNI_OnLoad found in /data/data/[ourPackageName]/lib/libfolly_json.so 0x42097da8, skipping init
D/dalvikvm(30146): Trying to load lib /data/data/[ourPackageName]/lib/libicu_common.so 0x42097da8
D/dalvikvm(30146): Added shared lib /data/data/[ourPackageName]/lib/libicu_common.so 0x42097da8
D/dalvikvm(30146): No JNI_OnLoad found in /data/data/[ourPackageName]/lib/libicu_common.so 0x42097da8, skipping init
D/dalvikvm(30146): Trying to load lib /data/data/[ourPackageName]/lib/libjsc.so 0x42097da8
D/dalvikvm(30146): Added shared lib /data/data/[ourPackageName]/lib/libjsc.so 0x42097da8
D/dalvikvm(30146): No JNI_OnLoad found in /data/data/[ourPackageName]/lib/libjsc.so 0x42097da8, skipping init
D/dalvikvm(30146): Trying to load lib /data/data/[ourPackageName]/lib/libreactnativejni.so 0x42097da8
D/dalvikvm(30146): Added shared lib /data/data/[ourPackageName]/lib/libreactnativejni.so 0x42097da8
I/ActivityManager(  329): Process [ourPackageName] (pid 30146) has died.
```

**Comment by zsajjad** [comment]
@radko93 @bosung90 any solution?

**Comment by christopherdro** [comment]
@zsajjad Can you check that you have Android NDK installed that it's path is correct?

**Comment by zsajjad** [comment]
Same apk is working very fine on 4.4+. Yes i have NDK is fine.

**Comment by zsajjad** [comment]
```
05-03 20:09:13.301 15741 15741 I dalvikvm: Could not find method android.provider.Settings.canDrawOverlays, referenced from method com.facebook.react.ReactActivity.onCreate
05-03 20:09:13.559 15741 15741 W unknown:React: Unable to dispatch keyboard events in JS as the react instance has not been attached
05-03 20:09:13.684 15741 15759 D dalvikvm: Trying to load lib /data/data/[Our Package Name]/lib/libreactnativejni.so 0x413fd490
05-03 20:09:13.684 15741 15759 D dalvikvm: Added shared lib /data/data/[Our Package Name]/lib/libreactnativejni.so 0x413fd490
05-03 20:09:13.691 15741 15759 I dalvikvm: Could not find method android.view.View.setAccessibilityLiveRegion, referenced from method com.facebook.react.uimanager.BaseViewManager.setAccessibilityLiveRegion
05-03 20:09:13.691 15741 15759 I dalvikvm: Could not find method android.view.View.setAccessibilityLiveRegion, referenced from method com.facebook.react.uimanager.BaseViewManager.setAccessibilityLiveRegion
05-03 20:09:13.691 15741 15759 I dalvikvm: Could not find method android.view.View.setAccessibilityLiveRegion, referenced from method com.facebook.react.uimanager.BaseViewManager.setAccessibilityLiveRegion
05-03 20:09:13.691 15741 15759 I dalvikvm: Could not find method android.view.View.setElevation, referenced from method com.facebook.react.uimanager.BaseViewManager.setElevation
05-03 20:09:13.707 15741 15759 I dalvikvm: Could not find method com.facebook.react.views.view.ReactViewGroup.drawableHotspotChanged, referenced from method com.facebook.react.views.view.ReactViewManager.receiveCommand
05-03 20:09:13.707 15741 15759 W dalvikvm: VFY: unable to resolve virtual method 27753: Lcom/facebook/react/views/view/ReactViewGroup;.drawableHotspotChanged (FF)V
05-03 20:09:13.715 15741 15759 I dalvikvm: Could not find method android.webkit.WebSettings.setMediaPlaybackRequiresUserGesture, referenced from method com.facebook.react.views.webview.ReactWebViewManager.setMediaPlaybackRequiresUserAction
05-03 20:09:13.731 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTRenderableViewManager
05-03 20:09:13.731 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
05-03 20:09:13.731 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
05-03 20:09:13.746 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
05-03 20:09:13.746 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
05-03 20:09:13.762 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
05-03 20:09:13.801 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
05-03 20:09:13.809 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
05-03 20:09:13.816 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
05-03 20:09:13.824 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
05-03 20:09:13.824 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
05-03 20:09:13.871 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
05-03 20:09:13.895 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
05-03 20:09:13.902 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
05-03 20:09:13.902 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
05-03 20:09:13.910 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
05-03 20:09:13.910 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
05-03 20:09:13.910 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
05-03 20:09:13.926 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
05-03 20:09:13.926 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
05-03 20:09:13.934 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
05-03 20:09:13.934 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
05-03 20:09:13.934 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
05-03 20:09:13.941 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textfrescosupport.FrescoBasedReactTextInlineImageViewManager
05-03 20:09:13.941 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textfrescosupport.FrescoBasedReactTextInlineImageShadowNode
05-03 20:09:13.941 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
05-03 20:09:13.957 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
05-03 20:09:13.957 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
05-03 20:09:13.957 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
05-03 20:09:13.965 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
05-03 20:09:13.981 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
05-03 20:09:13.988 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
05-03 20:09:13.988 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
05-03 20:09:13.988 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.recyclerview.RecyclerViewBackedScrollViewManager
05-03 20:09:14.004 15741 15759 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
05-03 20:09:14.020 15741 15759 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: com/facebook/react/uimanager/ReactProp
05-03 20:09:14.020 15741 15759 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagersPropertyCache.extractPropSettersFromViewManagerClassDefinition(ViewManagersPropertyCache.java:400)
05-03 20:09:14.020 15741 15759 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForViewManagerClass(ViewManagersPropertyCache.java:301)
05-03 20:09:14.020 15741 15759 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.<init>(ViewManagerPropertyUpdater.java:115)
05-03 20:09:14.020 15741 15759 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.<init>(ViewManagerPropertyUpdater.java:110)
05-03 20:09:14.020 15741 15759 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.findManagerSetter(ViewManagerPropertyUpdater.java:73)
05-03 20:09:14.020 15741 15759 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.getNativeProps(ViewManagerPropertyUpdater.java:60)
05-03 20:09:14.020 15741 15759 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManager.getNativeProps(ViewManager.java:199)
05-03 20:09:14.020 15741 15759 E AndroidRuntime: 	at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstants(UIManagerModuleConstantsHelper.java:62)
05-03 20:09:14.020 15741 15759 E AndroidRuntime: 	at com.facebook.react.uimanager.UIManagerModule.createConstants(UIManagerModule.java:128)
05-03 20:09:14.020 15741 15759 E AndroidRuntime: 	at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:80)
05-03 20:09:14.020 15741 15759 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage.createNativeModules(CoreModulesPackage.java:65)
05-03 20:09:14.020 15741 15759 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManagerImpl.processPackage(ReactInstanceManagerImpl.java:893)
05-03 20:09:14.020 15741 15759 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:810)
05-03 20:09:14.020 15741 15759 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManagerImpl.access$700(ReactInstanceManagerImpl.java:103)
05-03 20:09:14.020 15741 15759 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:199)
05-03 20:09:14.020 15741 15759 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:182)
05-03 20:09:14.020 15741 15759 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.react.uimanager.ReactProp" on path: /system/framework/com.google.android.maps.jar:/data/app/[Our Package Name]-2.apk

```

**Comment by zsajjad** [comment]
We were using
https://github.com/apptailor/react-native-google-signin
for google sign in, it makes its own button using native element issue was due to

`import com.facebook.react.uimanager.ReactProp;`
in https://github.com/apptailor/react-native-google-signin/blob/master/android/src/main/java/co/apptailor/googlesignin/RNGoogleSigninButtonViewManager.java at line number 7

it should be
`import com.facebook.react.uimanager.annotations.ReactProp;`

**Comment by christopherdro** [comment]
👍 Glad you figured it out!
