### ISSUE TITLE
[Android] Native crashes in com.facebook.react.views.progressbar (React 0.24)

### ISSUE THREAD

**Issue by gunters63** [facebook/react-native#7476]
We recently updated our App from React 0.23 to React 0.24

Since then native crashes started to happen which seem to originate from ProgressBarAndroid. (We track those with Fabric/Crashlytics).

They never happened with React 0.23 and our usage of ProgressBarAndroid didn't change in the new version.

Unfortunately I was not able to reproduce the crashes yet. They also seem to happen sporadically on our clients devices. The crashes happen on Android 5.x and 6.x.

There are two different stack traces, both originating from com.facebook.react.views.progressbar. The second one seems to be related to the first one.

````
Fatal Exception: java.lang.NullPointerException: Null pointer exception during instruction 'invoke-static {v5}, android.animation.AnimatorSet$Node android.animation.AnimatorSet$Node.access$200(android.animation.AnimatorSet$Node) // method@722'
       at android.animation.AnimatorSet.clone(AnimatorSet.java:707)
       at android.animation.AnimatorSet.clone(AnimatorSet.java:50)
       at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState.<init>(AnimatedVectorDrawable.java:363)
       at android.graphics.drawable.AnimatedVectorDrawable.mutate(AnimatedVectorDrawable.java:149)
       at android.content.res.Resources.loadDrawable(Resources.java:3746)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:762)
       at android.widget.ProgressBar.<init>(ProgressBar.java:355)
       at android.widget.ProgressBar.<init>(ProgressBar.java:311)
       at com.facebook.react.views.progressbar.ProgressBarShadowNode.measure(ProgressBarShadowNode.java:57)
       at com.facebook.csslayout.CSSNode.measure(CSSNode.java:137)
       at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:294)
       at com.facebook.csslayout.LayoutEngine.layoutNode(LayoutEngine.java:214)
       ... more layout engine stuff
````

and

````
Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'styleAttr' of a view managed by: AndroidProgressBar
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:88)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:123)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:42)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:213)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:829)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:797)
       at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
       at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:125)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:775)
       at android.view.Choreographer.doCallbacks(Choreographer.java:590)
       at android.view.Choreographer.doFrame(Choreographer.java:559)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6837)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:77)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:123)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:42)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:213)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:829)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:797)
       at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
       at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:125)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:775)
       at android.view.Choreographer.doCallbacks(Choreographer.java:590)
       at android.view.Choreographer.doFrame(Choreographer.java:559)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6837)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by java.lang.NullPointerException: Null pointer exception during instruction 'invoke-static {v5}, android.animation.AnimatorSet$Node android.animation.AnimatorSet$Node.access$200(android.animation.AnimatorSet$Node) // method@722'
       at android.animation.AnimatorSet.clone(AnimatorSet.java:707)
       at android.animation.AnimatorSet.clone(AnimatorSet.java:50)
       at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState.<init>(AnimatedVectorDrawable.java:363)
       at android.graphics.drawable.AnimatedVectorDrawable.mutate(AnimatedVectorDrawable.java:149)
       at android.content.res.Resources.loadDrawable(Resources.java:3746)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:762)
       at android.widget.ProgressBar.<init>(ProgressBar.java:355)
       at android.widget.ProgressBar.<init>(ProgressBar.java:311)
       at com.facebook.react.views.progressbar.ProgressBarContainerView.setStyle(ProgressBarContainerView.java:34)
       at com.facebook.react.views.progressbar.ReactProgressBarViewManager.setStyle(ReactProgressBarViewManager.java:48)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:77)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:123)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:42)
       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:213)
       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:829)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:797)
       at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
       at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:125)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:775)
       at android.view.Choreographer.doCallbacks(Choreographer.java:590)
       at android.view.Choreographer.doFrame(Choreographer.java:559)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6837)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
````

**Comment by gunters63** [comment]
There seem to be some changes in the native code of ProgressBarAndroid between React 0.23 and 0.24 (between Apr 7 and Apr 12, see https://github.com/facebook/react-native/commits/303428ea28dbde63a7a3172a76dd79e5269ac4e5/ReactAndroid/src/main/java/com/facebook/react/views/progressbar)

Probably they are related with this issue.

**Comment by damusnet** [comment]
@facebook-github-bot label Android

**Comment by Richard-Cao** [comment]
same crash +1

**Comment by Richard-Cao** [comment]
This is very important to us.
Looking forward to solve this.

**Comment by Richard-Cao** [comment]
I track those with Bugly. 
It most carsh Android 5.1.

com.facebook.react.views.progressbar.ProgressBarShadowNode.void measure(com.facebook.csslayout.CSSNode,float,float,com.facebook.csslayout.MeasureOutput)(SourceFile:57)

Null pointer exception during instruction 'invoke-static {v5}, android.animation.AnimatorSet$Node android.animation.AnimatorSet$Node.access$200(android.animation.AnimatorSet$Node) // method@96'

I think maybe crash about GC?

**Comment by Richard-Cao** [comment]
@satya164 help

**Comment by xujinyang** [comment]
We also get this crash (´Д` )

**Comment by brentvatne** [comment]
cc @astreet to hopefully ping Emil Sjolander, as this seems related to the css-layout update

**Comment by dmmiller** [comment]
Spoke with @astreet about it and we believe that there was a race issue in constructing ProgressBars on the shadow thread and the ui thread.  @astreet put in a fix (b9396cd74419dd4165fb051605076d19b1c18905) to synchronize creation.  That didn't make it in to 24 apparently, but is in 25.  Can you upgrade and try that?

**Comment by gunters63** [comment]
Thanks for the feedback,

I've just pushed a new version of our app to the play store using React 0.25.
I'll report back if the crashes still happen or not.

**Comment by Richard-Cao** [comment]
I will continue to focus on.

**Comment by Sh3rawi** [comment]
@gunters63 any news ?

**Comment by gunters63** [comment]
Most of our users have upgraded to the new version of our app now.

So far no crashes, so I can confirm >95% that the bug is fixed with React 0.25.

**Comment by ide** [comment]
@gunters63 thanks for investigating. Closing this out.

**Comment by dmmiller** [comment]
Awesome.  Glad to hear that!

**Comment by AlanFoster** [comment]
Noticed a stack trace of this in production with react-native 0.47.2 -

```
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'styleAttr' of a view managed by: AndroidProgressBar
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:95)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48)
	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:36)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:227)
	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:150)
	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:770)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:855)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$1600(UIViewOperationQueue.java:46)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:900)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:928)
	at android.view.Choreographer.doCallbacks(Choreographer.java:705)
	at android.view.Choreographer.doFrame(Choreographer.java:637)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1557)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
	... 23 more
Caused by: android.content.res.Resources$NotFoundException: Drawable android:drawable/progress_medium_material with resource ID #0x10806b0
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.content.res.StringBlock.get(int)' on a null object reference
	at android.content.res.AssetManager.getResourceValue(AssetManager.java:244)
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:198)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2977)
	at android.content.res.Resources.getAnimation(Resources.java:2014)
	at android.view.animation.AnimationUtils.loadInterpolator(AnimationUtils.java:355)
	at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:1053)
	at android.animation.AnimatorInflater.loadObjectAnimator(AnimatorInflater.java:1007)
	at android.animation.AnimatorInflater.createAnimatorFromXml(AnimatorInflater.java:663)
	at android.animation.AnimatorInflater.createAnimatorFromXml(AnimatorInflater.java:676)
	at android.animation.AnimatorInflater.createAnimatorFromXml(AnimatorInflater.java:638)
	at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:126)
	at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState$PendingAnimator.newInstance(AnimatedVectorDrawable.java:641)
	at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState.inflatePendingAnimators(AnimatedVectorDrawable.java:619)
	at android.graphics.drawable.AnimatedVectorDrawable.applyTheme(AnimatedVectorDrawable.java:451)
	at android.graphics.drawable.DrawableContainer$DrawableContainerState.applyTheme(DrawableContainer.java:953)
	at android.graphics.drawable.DrawableContainer.applyTheme(DrawableContainer.java:612)
	at com.android.internal.graphics.drawable.AnimationScaleListDrawable.applyTheme(AnimationScaleListDrawable.java:240)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:630)
	at android.content.res.Resources.loadDrawable(Resources.java:1733)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:945)
	at android.widget.ProgressBar.<init>(ProgressBar.java:371)
	at android.widget.ProgressBar.<init>(ProgressBar.java:322)
	at com.facebook.react.views.progressbar.ReactProgressBarViewManager.createProgressBar(ReactProgressBarViewManager.java:52)
	at com.facebook.react.views.progressbar.ProgressBarContainerView.setStyle(ProgressBarContainerView.java:36)
	at com.facebook.react.views.progressbar.ReactProgressBarViewManager.setStyle(ReactProgressBarViewManager.java:68)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48)
	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:36)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:227)
	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:150)
	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:770)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:855)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$1600(UIViewOperationQueue.java:46)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:900)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:928)
	at android.view.Choreographer.doCallbacks(Choreographer.java:705)
	at android.view.Choreographer.doFrame(Choreographer.java:637)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1557)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

The specs of the device were:

```
Android Build: NMF26X.N950USQU1AQH7
Manufacturer: samsung
Model: SM-N950U
OS: 7.1.1
```

I'm afraid I can't give any replication steps, as it's only happened once throughout its life in production - but just posting for visibility :+1:
