### ISSUE TITLE
ViewManager: Error while updating prop nativeActions

### ISSUE THREAD

**Issue by vermasumeet1982** [facebook/react-native#7513]
Hi When adding actions items to ToolbarAndroid, I get the following error

ViewManager: Error while updating prop nativeActions of a view Managed by ToolBarAndroid
<img width="621" alt="screen shot 2016-05-11 at 16 19 21" src="https://cloud.githubusercontent.com/assets/19309331/15186260/3a62aaca-1794-11e6-9e52-6f966fec4d41.png">

Crash log is 
05-11 11:13:47.006 7690-7690/com.deloitte.pocketsales.react E/unknown:ViewManager: Error while updating prop nativeActions
                                                                                   java.lang.reflect.InvocationTargetException
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:77)
                                                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:123)
                                                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:42)
                                                                                       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34)
                                                                                       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:213)
                                                                                       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:147)
                                                                                       at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:673)
                                                                                       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:723)
                                                                                       at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
                                                                                       at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:120)
                                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
                                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                                       at android.view.Choreographer.doFrame(Choreographer.java:549)
                                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                                    Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class android.support.v7.internal.view.menu.ActionMenuItemView
                                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                                       at android.support.v7.internal.view.menu.BaseMenuPresenter.createItemView(BaseMenuPresenter.java:161)
                                                                                       at android.support.v7.internal.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:180)
                                                                                       at android.support.v7.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:195)
                                                                                       at android.support.v7.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:483)
                                                                                       at android.support.v7.internal.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1138)
                                                                                       at android.support.v7.internal.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:91)
                                                                                       at android.support.v7.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:232)
                                                                                       at android.support.v7.internal.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:284)
                                                                                       at android.support.v7.internal.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1030)
                                                                                       at android.support.v7.internal.view.menu.MenuBuilder.onItemActionRequestChanged(MenuBuilder.java:1076)
                                                                                       at android.support.v7.internal.view.menu.MenuItemImpl.setShowAsAction(MenuItemImpl.java:603)
                                                                                       at com.facebook.react.views.toolbar.ReactToolbar.setActions(ReactToolbar.java:246)
                                                                                       at com.facebook.react.views.toolbar.ReactToolbarManager.setActions(ReactToolbarManager.java:122)
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:77) 
                                                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:123) 
                                                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:42) 
                                                                                       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34) 
                                                                                       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:213) 
                                                                                       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:147) 
                                                                                       at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:673) 
                                                                                       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:723) 
                                                                                       at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32) 
                                                                                       at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:120) 
                                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765) 
                                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:580) 
                                                                                       at android.view.Choreographer.doFrame(Choreographer.java:549) 
                                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753) 
                                                                                       at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                       at android.os.Looper.loop(Looper.java:135) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                       at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:482) 
                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                                       at android.support.v7.internal.view.menu.BaseMenuPresenter.createItemView(BaseMenuPresenter.java:161) 
                                                                                       at android.support.v7.internal.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:180) 
                                                                                       at android.support.v7.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:195) 
                                                                                       at android.support.v7.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:483) 
                                                                                       at android.support.v7.internal.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1138) 
                                                                                       at android.support.v7.internal.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:91) 
                                                                                       at android.support.v7.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:232) 
                                                                                       at android.support.v7.internal.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:284) 
                                                                                       at android.support.v7.internal.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1030) 
                                                                                       at android.support.v7.internal.view.menu.MenuBuilder.onItemActionRequestChanged(MenuBuilder.java:1076) 
                                                                                       at android.support.v7.internal.view.menu.MenuItemImpl.setShowAsAction(MenuItemImpl.java:603) 
                                                                                       at com.facebook.react.views.toolbar.ReactToolbar.setActions(ReactToolbar.java:246) 
                                                                                       at com.facebook.react.views.toolbar.ReactToolbarManager.setActions(ReactToolbarManager.java:122) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:77) 
                                                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:123) 
                                                                                       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:42) 
                                                                                       at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34) 
                                                                                       at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:213) 
                                                                                       at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:147) 
                                                                                       at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:673) 
                                                                                       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:723) 
                                                                                       at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32) 
                                                                                       at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:120) 
                                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765) 
                                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:580) 
                                                                                       at android.view.Choreographer.doFrame(Choreographer.java:549) 
                                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753) 
                                                                                       at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                       at android.os.Looper.loop(Looper.java:135) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                                    Caused by: java.lang.RuntimeException
05-11 11:13:47.007 7690-7690/com.deloitte.pocketsales.react D/AndroidRuntime: Shutting down VM
05-11 11:13:47.008 7690-7690/com.deloitte.pocketsales.react E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.deloitte.pocketsales.react, PID: 7690
                                                                              com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'nativeActions' of a view managed by: ToolbarAndroid
                                                                                  at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:88)
                                                                                  at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:123)
                                                                                  at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:42)
                                                                                  at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34)
                                                                                  at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:213)
                                                                                  at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:147)
                                                                                  at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:673)
                                                                                  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:723)
                                                                                  at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
                                                                                  at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:120)
                                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
                                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                                  at android.view.Choreographer.doFrame(Choreographer.java:549)
                                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                               Caused by: java.lang.reflect.InvocationTargetException
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:77)
                                                                                  at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:123) 
                                                                                  at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:42) 
                                                                                  at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:34) 
                                                                                  at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:213) 
                                                                                  at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:147) 
                                                                                  at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:673) 
                                                                                  at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:723) 
                                                                                  at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32) 
                                                                                  at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:120) 
                                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765) 
                                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:580) 
                                                                                  at android.view.Choreographer.doFrame(Choreographer.java:549) 
                                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753) 
                                                                                  at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                  at android.os.Looper.loop(Looper.java:135) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                               Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class android.support.v7.internal.view.menu.ActionMenuItemView
                                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                                  at android.support.v7.internal.view.menu.BaseMenuPresenter.createItemView(BaseMenuPresenter.java:161)
                                                                                  at android.support.v7.internal.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:180)
                                                                                  at android.support.v7.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:195)
                                                                                  at android.support.v7.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:483)
                                                                                  at android.support.v7.internal.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1138)
                                                                                  at android.support.v7.internal.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:91)
                                                                                  at android.support.v7.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:232)
                                                                                  at android.support.v7.internal.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:284)
                                                                                  at android.support.v7.internal.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1030)
                                                                                  at android.support.v7.internal.view.menu.MenuBuilder.onItemActionRequestChanged(MenuBuilder.java:1076)
                                                                                  at android.support.v7.internal.view.menu.MenuItemImpl.setShowAsAction(MenuItemImpl.java:603)
                                                                                  at com.facebook.react.views.toolbar.ReactToolbar.setActions(ReactToolbar.java:246)
                                                                              	at com.facebook.react.views.toolbar.ReactToolbarManager.setActions(ReactToolbarManager.java:

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-7** [comment]
Hey @vermasumeet1982 and thanks for posting this! @damusnet tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
