### ISSUE TITLE
Android 4.1 crashing with proguard enabled

### ISSUE THREAD

**Issue by yakivmospan** [facebook/react-native#7530]
Hi guys, I'm using 0.25.1 react version. And I got a crash on 4.1 device, while on 5 and above all is working ok. Here is the crash log :

```
05-12 10:36:20.244 1913-2004/{package} E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
java.lang.RuntimeException: An error occured while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:299)
    at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
    at java.util.concurrent.FutureTask.run(FutureTask.java:137)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
    at java.lang.Thread.run(Thread.java:856)
 Caused by: java.lang.ExceptionInInitializerError
    at com.facebook.react.h.a(ReactInstanceManagerImpl.java:195)
    at com.facebook.react.h.doInBackground(ReactInstanceManagerImpl.java:181)
    at android.os.AsyncTask$2.call(AsyncTask.java:287)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
    at java.util.concurrent.FutureTask.run(FutureTask.java:137) 
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
    at java.lang.Thread.run(Thread.java:856) 
 Caused by: java.lang.VerifyError: com/facebook/l/b
    at com.facebook.l.c.a(DirectorySoSource.java:50)
    at com.facebook.l.f.a(SoLoader.java:209)
    at com.facebook.l.f.a(SoLoader.java:178)
    at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:23)
    at com.facebook.react.h.a(ReactInstanceManagerImpl.java:195) 
    at com.facebook.react.h.doInBackground(ReactInstanceManagerImpl.java:181) 
    at android.os.AsyncTask$2.call(AsyncTask.java:287) 
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305) 
    at java.util.concurrent.FutureTask.run(FutureTask.java:137) 
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
    at java.lang.Thread.run(Thread.java:856) 
```

Here is the proguard rules:
```
# React Native

# Keep our interfaces so they can be used by other ProGuard rules.
# See http://sourceforge.net/p/proguard/bugs/466/
-keep,allowobfuscation @interface com.facebook.proguard.annotations.DoNotStrip
-keep,allowobfuscation @interface com.facebook.proguard.annotations.KeepGettersAndSetters

# Do not strip any method/class that is annotated with @DoNotStrip
-keep @com.facebook.proguard.annotations.DoNotStrip class *
-keepclassmembers class * {
    @com.facebook.proguard.annotations.DoNotStrip *;
}

-keepclassmembers @com.facebook.proguard.annotations.KeepGettersAndSetters class * {
  void set*(***);
  *** get*();
}

-keep class * extends com.facebook.react.bridge.JavaScriptModule { *; }
-keep class * extends com.facebook.react.bridge.NativeModule { *; }
-keepclassmembers,includedescriptorclasses class * { native <methods>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.UIProp <fields>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.annotations.ReactProp <methods>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.annotations.ReactPropGroup <methods>; }

-dontwarn com.facebook.react.**

# okhttp

-keepattributes Signature
-keepattributes *Annotation*
-keep class com.squareup.okhttp.** { *; }
-keep interface com.squareup.okhttp.** { *; }
-dontwarn com.squareup.okhttp.**

# okio

-keep class sun.misc.Unsafe { *; }
-dontwarn java.nio.file.*
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
-dontwarn okio.**
``` 

I'm not using `android upgrade`, react sources are in independent repository. But I dont think its should matter.

Does anyone had such an issue or knows how to deal with this? Thanks

**Comment by AndrewJack** [comment]
Looks like you are missing the `-dontobfuscate` option. I don't think react native supports obfuscation yet.

See https://github.com/facebook/react-native/blob/master/local-cli/generator-android/templates/src/app/proguard-rules.pro

**Comment by AndrewJack** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-1** [comment]
Closing this issue as @AndrewJack says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

**Comment by yakivmospan** [comment]
@AndrewJack thanks, but again, they don't say "Dont use -dontobfuscate" but say "It is useful when". 

># Disabling obfuscation is useful if you collect stack traces from production crashes
># (unless you are using a system that supports de-obfuscate the stack traces).
>-dontobfuscate

Also, it is not working only on 4.1. Strange not ?

**Comment by MiteshLodaya** [comment]
@yakivmospan  Did you find a solution for this? I am also facing a similar issue.

**Comment by ps-swaroop** [comment]
@yakivmospan Did you find a solution for this? I am also facing a similar issue.

**Comment by yakivmospan** [comment]
@ps-swaroop I've added `-dontobfuscate`, seems they still don;t support it.

**Comment by AndrewJack** [comment]
@yakivmospan  I've had some success by removing `-dontobfuscate` and adding the following two lines. I'll update if I find anything else.

```
-keep class com.facebook.react.cxxbridge.** { *; }
-keep class com.facebook.react.bridge.** { *; }
```

**Comment by vyky** [comment]
I have similar issue

It's a bit ashame that RN doesn't support obfuscation as android reverse engineering is real easy

**Comment by npomfret** [comment]
Was there any progress on this.  I've recently started getting SoLoader java.lang.VerifyError in 4.4 and 4.1 builds.  Its been fine until recently

**Comment by drakmail** [comment]
Have same error, proguard rules updating doesn't help
