### ISSUE TITLE
Unexpected Token ... require('React') when trying to run react-native

### ISSUE THREAD

**Issue by nealdyrkacz** [facebook/react-native#7540]
Using mac trying to get some code we have in our repo running.  Installed on Mac.

Tried removing node / npm / nvm and reinstalling everything including code from repo. Still having issues...

react-native run-ios
/node_modules/react-native/Libraries/react-native/react-native.js:121
  ...require('React'),
  ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/node_modules/react-native/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:409:22
    at Array.map (native)

**Comment by AndrewJack** [comment]
What version of React and React Native are you using?

**Comment by AndrewJack** [comment]
@facebook-github-bot label Needs more information

**Comment by nealdyrkacz** [comment]
@AndrewJack updated the above summary

React : 0.14.8
react-native-cli: 0.2.0
react-native: 0.24.0

also react-native-cli was installed globally
with npm install -g react-native-cli

**Comment by nealdyrkacz** [comment]
@Andre

**Comment by nealdyrkacz** [comment]
@AndrewJack Figured it out.... for some reason my npm was a way early veresion.... 2.4  updating it corrected everything.
