### ISSUE TITLE
Chrome debugger crashes the app on master [Android]

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#7659]
I believe it's [this](https://github.com/facebook/react-native/commit/779314a413851e7ae3d9ff483ba6421f1eb33630) commit, but need to confirm (rewinding 0.27 to pre-that).

**Update** it still breaks when reverting to 3 days old state.

Here's the stack trace:
```
E/AndroidRuntime( 1664): java.lang.NoSuchMethodError: no method with name='loadApplicationScript' signature='(Ljava/lang/String;Ljava/lang/String;)V' in interface Lcom/facebook/react/bridge/JavaJSExecutor;
E/AndroidRuntime( 1664): 	at com.facebook.react.bridge.ReactBridge.loadScriptFromFile(Native Method)
E/AndroidRuntime( 1664): 	at com.facebook.react.bridge.JSBundleLoader$3.loadScript(JSBundleLoader.java:81)
E/AndroidRuntime( 1664): 	at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:148)
E/AndroidRuntime( 1664): 	at com.facebook.react.ReactInstanceManagerImpl$4.call(ReactInstanceManagerImpl.java:851)
E/AndroidRuntime( 1664): 	at com.facebook.react.ReactInstanceManagerImpl$4.call(ReactInstanceManagerImpl.java:832)
E/AndroidRuntime( 1664): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:73)
E/AndroidRuntime( 1664): 	at android.os.Handler.handleCallback(Handler.java:730)
E/AndroidRuntime( 1664): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 1664): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
E/AndroidRuntime( 1664): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 1664): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:197)
E/AndroidRuntime( 1664): 	at java.lang.Thread.run(Thread.java:841)
```

**Comment by grabbou** [comment]
cc: @mhorowitz as you seem to be most active in the native diffs from the last week.

**Comment by mhorowitz** [comment]
I see the problem.  I'll commit a fix soon.

**Comment by grabbou** [comment]
@mhorowitz I've recompiled the project when doing 0.27 rc.1 with your diff and unfortunately, it still seems to crash with the same exception.
