### ISSUE TITLE
[0.25.1][Android][Picker][BUG] On build release

### ISSUE THREAD

**Issue by Deviloppeur** [facebook/react-native#7691]
Hi,

```
  render() {
    const {addresses, deliveryAddress} = this.props;

    const data = this._buildData();

    return addresses.size == 0 ? null : (
      <Picker
        ref={picker => this.picker = picker}
        style={{height: Dimensions.get('window').height / 3}}
        onValueChange={this._onValueChanged.bind(this)}
        selectedValue={this._buildSelectedValue()}
      >
        {data.map((datum, index) => {
          return (
            <Picker.Item key={index} label={datum.alias} value={datum.id}> </PickerItem>
          )
        })}
      </Picker>
    )
  }
```

This code will failed on trying to build release version (on Android) with gradle.

$> ./gradlew assembleRelease

```
/Users/christophe/Documents/brico/node_modules/promise/lib/done.js:10
      throw err;
      ^
TypeError: /Users/christophe/Documents/brico/src/native/carrier/AddressPicker.react.js: Property object of JSXMemberExpression expected node to be of a type ["JSXMemberExpression","JSXIdentifier"] but instead got "MemberExpression"
    at Object.validate (/Users/christophe/Documents/brico/node_modules/babel-types/lib/definitions/index.js:115:13)
    at Object.validate (/Users/christophe/Documents/brico/node_modules/babel-types/lib/index.js:552:9)
    at NodePath._replaceWith (/Users/christophe/Documents/brico/node_modules/babel-traverse/lib/path/replacement.js:214:7)
    at NodePath.replaceWith (/Users/christophe/Documents/brico/node_modules/babel-traverse/lib/path/replacement.js:192:8)
    at Object.ReferencedIdentifier (/Users/christophe/Documents/brico/node_modules/babel-plugin-transform-es2015-modules-commonjs/lib/index.js:36:14)
    at Object.newFn (/Users/christophe/Documents/brico/node_modules/babel-traverse/lib/visitors.js:343:17)
    at NodePath._call (/Users/christophe/Documents/brico/node_modules/babel-traverse/lib/path/context.js:78:18)
    at NodePath.call (/Users/christophe/Documents/brico/node_modules/babel-traverse/lib/path/context.js:49:17)
    at NodePath.visit (/Users/christophe/Documents/brico/node_modules/babel-traverse/lib/path/context.js:108:12)
TransformError: /Users/christophe/Documents/brico/src/native/carrier/AddressPicker.react.js: /Users/christophe/Documents/brico/src/native/carrier/AddressPicker.react.js: Property object of JSXMemberExpression expected node to be of a type ["JSXMemberExpression","JSXIdentifier"] but instead got "MemberExpression"
:app:bundleReleaseJsAndAssets FAILED
```

Regards,
Christophe

**Comment by Deviloppeur** [comment]
To avoid this error message :

Edit the Picker.js in react-native ({$root_dir}/node_modules/react-native/Libraries/Components/Picker.js)
```
/**
 * Individual selectable item in a Picker.
 */
Picker.Item = React.createClass({
