### ISSUE TITLE
Android Debug Caught exception after cancelling react context init

### ISSUE THREAD

**Issue by lekenny** [facebook/react-native#7715]
I'm useing Mac

E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                            Process: com.myapp, PID: 21432
                                                            java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/okhttp/ws/WebSocket$PayloadType;
                                                                at com.facebook.react.bridge.JSDebuggerWebSocketClient.sendMessage(JSDebuggerWebSocketClient.java:168)
                                                                at com.facebook.react.bridge.JSDebuggerWebSocketClient.prepareJSRuntime(JSDebuggerWebSocketClient.java:100)
                                                                at com.facebook.react.bridge.WebsocketJavaScriptExecutor$2.onSuccess(WebsocketJavaScriptExecutor.java:109)
                                                                at com.facebook.react.bridge.JSDebuggerWebSocketClient.onOpen(JSDebuggerWebSocketClient.java:238)
                                                                at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:151)
                                                                at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:40)
                                                                at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:98)
                                                                at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
                                                                at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                at java.lang.Thread.run(Thread.java:818)
                                                             Caused by: java.lang.ClassNotFoundException: Didn't find class "com.squareup.okhttp.ws.WebSocket$PayloadType" on path: DexPathList[[dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-support-annotations-23.0.1_c7d13e2abb8a4d174460e107d4623b3f17ff1c59-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-okio-1.6.0_94e1ff8ab73bdc8083f60fdd096154f52e9661ab-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-okhttp-ws-2.7.0_9d61c91c638b4fb9d3ed2e49b64e4e10200eac91-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-okhttp-2.7.0_95716192771da3e555e24f5c505377e6d514b7ef-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-library-2.4.0_967e1cae8105d681f66c0722cea5ef615784aa74-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-libammsdk_62dbdaf036611066c0c4ce730e285955249eaf1a-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-jsr305-3.0.0_3c882547cf051a4bd4428b802f45c2ee274126f4-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-jackson-core-2.2.3_59e781a6aac72fbd25d9f74c897164647a32542c-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-internal_impl-23.0.1_1e6e2423874721e7ee7298f320951489f2f84742-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-infer-annotations-1.5_d0b17da35fe0a6211e3e746e67f381b35f714ec1-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-com.facebook.react-react-native-0.24.1_a6621f9098ca180db0f9f21424438499560d22c4-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-com.facebook.fresco-imagepipeline-okhttp-0.8.1_f37def969e4cec2387c783680ee883bacd4f77e0-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-com.facebook.fresco-imagepipeline-0.8.1_eab3eff4cc17827ad9d7b0d4e312fbab0f0b082c-classes.dex", dex file "/data/data/com.rnpk16/files/instant-run/dex/slice-com.facebook.fresco-fresco-0.8.1_ff915fbce16d940169ff57265d54da8aec97c313-classes.dex", dex f

W/unknown:React: Caught exception after cancelling react context init
                                                           java.lang.RuntimeException: java.lang.InterruptedException
                                                               at com.facebook.react.devsupport.DevSupportManagerImpl$15.create(DevSupportManagerImpl.java:604)
                                                               at com.facebook.react.bridge.ProxyJavaScriptExecutor$Factory.create(ProxyJavaScriptExecutor.java:36)
                                                               at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:196)
                                                               at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:182)
                                                               at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                               at java.lang.Thread.run(Thread.java:818)
                                                            Caused by: java.lang.InterruptedException
                                                               at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1016)
                                                               at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1304)
                                                               at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:248)
                                                               at com.facebook.react.common.futures.SimpleSettableFuture.get(SimpleSettableFuture.java:84)
                                                               at com.facebook.react.devsupport.DevSupportManagerImpl$15.create(DevSupportManagerImpl.java:599)
                                                               at com.facebook.react.bridge.ProxyJavaScriptExecutor$Factory.create(ProxyJavaScriptExecutor.java:36) 
                                                               at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:196) 
                                                               at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:182) 
                                                               at android.os.AsyncTask$2.call(AsyncTask.java:292) 
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                               at java.lang.Thread.run(Thread.java:818)

**Comment by tianzhijiexian** [comment]
at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.react.devsupport.DevSupportManagerImpl" on path: DexPathList[[zip file "/data/app/com.duitang.main-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.duitang.main-2, /vendor/lib, /system/lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                     at java.lang.Class.classForName(Native Method) 
                                                     at java.lang.Class.forName(Class.java:251) 
                                                     at java.lang.Class.forName(Class.java:216) 
                                                     at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:61) 
                                                     at com.facebook.react.ReactInstanceManagerImpl.<init>(ReactInstanceManagerImpl.java:325) 
                                                     at com.facebook.react.ReactInstanceManager$Builder.build(ReactInstanceManager.java:360)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-debug-caught-exception-after-cancelling-react-context-init

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
