### ISSUE TITLE
Gradle build fail: Could not resolve com.facebook.react:react:react-native:0.26.1

### ISSUE THREAD

**Issue by talrejavishal** [facebook/react-native#7751]
## Issue with stack trace

Followed this url: https://facebook.github.io/react-native/docs/embedded-app-android.html#content
Got this runtime exception:

_05-24 15:18:51.508 14488-14577/investigation.personal.com.myawesomeapp E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                                         Process: investigation.personal.com.myawesomeapp, PID: 14488
                                                                                         java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                             at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                                             at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                                             at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                             at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                             at java.lang.Thread.run(Thread.java:818)
                                                                                          Caused by: java.lang.IllegalAccessError: Method 'void android.support.v4.net.ConnectivityManagerCompat.<init>()' is inaccessible to class 'com.facebook.react.modules.netinfo.NetInfoModule' (declaration of 'com.facebook.react.modules.netinfo.NetInfoModule' appears in /data/data/investigation.personal.com.myawesomeapp/files/instant-run/dex/slice-com.facebook.react-react-native-0.20.0_a241640f947108763e4860946579e00b709d5f95-classes.dex)
                                                                                             at com.facebook.react.modules.netinfo.NetInfoModule.<init>(NetInfoModule.java:55)
                                                                                             at com.facebook.react.shell.MainReactPackage.createNativeModules(MainReactPackage.java:67)
                                                                                             at com.facebook.react.ReactInstanceManagerImpl.processPackage(ReactInstanceManagerImpl.java:751)
                                                                                             at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:688)
                                                                                             at com.facebook.react.ReactInstanceManagerImpl.access$600(ReactInstanceManagerImpl.java:84)
                                                                                             at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:177)
                                                                                             at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:162)
                                                                                             at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                             at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                             at java.lang.Thread.run(Thread.java:818)_ 

Found a thread which talks about it: https://github.com/facebook/react-native/issues/6152
Tried to change the dependencies from     compile 'com.facebook.react:react-native:0.20.0+' to compile 'com.facebook.react:react-native:0.26.1'
After this change, the gradle build in Android Studio fails with below error:
**Could not resolve com.facebook.react:react:react-native:0.26.1**

I've uploaded the project files to the following git url:
https://github.com/talrejavishal/MyAwesomeApp.git
You could download the zip and investigate, if required.

Provide **screenshots** where appropriate
Attached screenshot: fberror.JPG
What's the **version** of React Native you're using?
0.26.1
Does this occur on iOS, Android or both?
Tried on Android only
 Are you using Mac, Linux or Windows?
Windows 64 bit

**Comment by talrejavishal** [comment]
Tried on Android only

**Comment by talrejavishal** [comment]
![fberror](https://cloud.githubusercontent.com/assets/18143856/15539195/bd5113ee-229e-11e6-9757-a3ca1f1a3510.JPG)

**Comment by charpeni** [comment]
Can you reproduce this issue with a freshly init project ?

**Comment by SudoPlz** [comment]
Same problem! I believe it might have to do with gradle not finding latest versions.

**Comment by satya164** [comment]
Did you do `npm install`?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/gradle-build-fail-could-not-resolve-comfacebookreactreactreact-native0261

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
