### ISSUE TITLE
java.lang.NullPointerException at com.facebook.react.common.network.OkHttpCallUtil.cancelTag

### ISSUE THREAD

**Issue by cancan101** [facebook/react-native#7755]
Using master of RN @ 2016-5-19. /CC @chirag04 
```
05-25 11:03:04.364 7018-7018/com.qsi E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.qsi, PID: 7018
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
    at com.facebook.react.common.network.OkHttpCallUtil.cancelTag(OkHttpCallUtil.java:30)
    at com.facebook.react.modules.network.NetworkingModule.onCatalystInstanceDestroy(NetworkingModule.java:141)
    at com.facebook.react.bridge.NativeModuleRegistry.notifyCatalystInstanceDestroy(NativeModuleRegistry.java:98)
    at com.facebook.react.bridge.CatalystInstanceImpl.destroy(CatalystInstanceImpl.java:218)
    at com.facebook.react.bridge.ReactContext.destroy(ReactContext.java:193)
    at com.facebook.react.ReactInstanceManagerImpl.tearDownReactContext(ReactInstanceManagerImpl.java:746)
    at com.facebook.react.ReactInstanceManagerImpl.access$500(ReactInstanceManagerImpl.java:98)
    at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPreExecute(ReactInstanceManagerImpl.java:182)
    at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:604)
    at android.os.AsyncTask.execute(AsyncTask.java:551)
    at com.facebook.react.ReactInstanceManagerImpl.recreateReactContextInBackground(ReactInstanceManagerImpl.java:674)
    at com.facebook.react.ReactInstanceManagerImpl.onJSBundleLoadedFromServer(ReactInstanceManagerImpl.java:657)
    at com.facebook.react.ReactInstanceManagerImpl.access$100(ReactInstanceManagerImpl.java:98)
    at com.facebook.react.ReactInstanceManagerImpl$1.onJSBundleLoadedFromServer(ReactInstanceManagerImpl.java:136)
    at com.facebook.react.devsupport.DevSupportManagerImpl$18$1.run(DevSupportManagerImpl.java:660)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by brentvatne** [comment]
I've also seen this cc @andreicoman11

**Comment by andreicoman11** [comment]
I'll take a look

**Comment by npomfret** [comment]
I just got this on RN 0.27.1:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
  at com.facebook.react.common.network.OkHttpCallUtil.cancelTag(OkHttpCallUtil.java:30)
  at com.facebook.react.modules.network.NetworkingModule.onCatalystInstanceDestroy(NetworkingModule.java:141)
  at com.facebook.react.bridge.NativeModuleRegistry.notifyCatalystInstanceDestroy(NativeModuleRegistry.java:98)
  at com.facebook.react.bridge.CatalystInstanceImpl.destroy(CatalystInstanceImpl.java:218)
  at com.facebook.react.bridge.ReactContext.destroy(ReactContext.java:193)
  at com.facebook.react.ReactInstanceManagerImpl.tearDownReactContext(ReactInstanceManagerImpl.java:746)
  at com.facebook.react.ReactInstanceManagerImpl.access$500(ReactInstanceManagerImpl.java:98)
  at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPreExecute(ReactInstanceManagerImpl.java:182)
  at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:591)
  at android.os.AsyncTask.execute(AsyncTask.java:539)
  at com.facebook.react.ReactInstanceManagerImpl.recreateReactContextInBackground(ReactInstanceManagerImpl.java:674)
  at com.facebook.react.ReactInstanceManagerImpl.onJSBundleLoadedFromServer(ReactInstanceManagerImpl.java:657)
  at com.facebook.react.ReactInstanceManagerImpl.access$100(ReactInstanceManagerImpl.java:98)
  at com.facebook.react.ReactInstanceManagerImpl$1.onJSBundleLoadedFromServer(ReactInstanceManagerImpl.java:136)
  at com.facebook.react.devsupport.DevSupportManagerImpl$18$1.run(DevSupportManagerImpl.java:660)
  at android.os.Handler.handleCallback(Handler.java:815)
  at android.os.Handler.dispatchMessage(Handler.java:104)
  at android.os.Looper.loop(Looper.java:194)
  at android.app.ActivityThread.main(ActivityThread.java:5631)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

```

**Comment by andreicoman11** [comment]
Should be fixed in https://github.com/facebook/react-native/commit/5de1151bdd48a9bc6ec6dae325c9a260121b6e04.
Feel free reopen if you get crashes after the fix.

**Comment by npomfret** [comment]
Any idea when this will be released?

**Comment by andreicoman11** [comment]
I'm not up to date with our release schedule, @bestander ?
