### ISSUE TITLE
Error running ios/android project after upgrading to RN-0.26.2

### ISSUE THREAD

**Issue by bhaskarmurthy** [facebook/react-native#7761]
I'm trying to deploy a react-native project, which worked fine in RN-0.25.

After upgrade to 0.26+, I'm seeing the following error with babel:

```
/Users/bmurthy/Development/wave/lodestar/Examples/UIExplorer/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413
          throw new Error( /*istanbul ignore next*/"Couldn't find preset " + /*istanbul ignore next*/(0, _stringify2.default)(val) + " relative to directory " + /*istanbul ignore next*/(0, _stringify2.default)(dirname));

Error: Couldn't find preset "es2016" relative to directory "/Users/bmurthy/Development/wave/lodestar"
    at /Users/bmurthy/Development/wave/lodestar/Examples/UIExplorer/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/bmurthy/Development/wave/lodestar/Examples/UIExplorer/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:405:20)
    at OptionManager.mergePresets (/Users/bmurthy/Development/wave/lodestar/Examples/UIExplorer/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:388:10)
    at OptionManager.mergeOptions (/Users/bmurthy/Development/wave/lodestar/Examples/UIExplorer/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:347:14)
    at OptionManager.addConfig (/Users/bmurthy/Development/wave/lodestar/Examples/UIExplorer/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:248:10)
    at OptionManager.findConfigs (/Users/bmurthy/Development/wave/lodestar/Examples/UIExplorer/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:454:16)
    at OptionManager.init (/Users/bmurthy/Development/wave/lodestar/Examples/UIExplorer/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:502:12)
    at compile (/Users/bmurthy/Development/wave/lodestar/Examples/UIExplorer/node_modules/react-native/node_modules/babel-register/lib/node.js:112:69)
    at loader (/Users/bmurthy/Development/wave/lodestar/Examples/UIExplorer/node_modules/react-native/node_modules/babel-register/lib/node.js:158:14)
```

I've tried clearing my `node_modules` dir, and re-installing npm dependencies, upgrading `react-native-cli`, no luck. Any help would be much appreciated, thanks.

**Comment by ms88privat** [comment]
Do you have a `babel.rc` file under `/Users/bmurthy/Development/wave/lodestar` ?
try removing it if possible.

but strange anyways.

**Comment by bhaskarmurthy** [comment]
Nope, no `.babelrc`

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow
