### ISSUE TITLE
ReferenceError testing React Native-dependent components

### ISSUE THREAD

**Issue by danybony** [facebook/react-native#7779]
I'm getting a ReferenceError when testing any class which is dependent on `react-native`, like the following example:
### Component under test
(`deep-linking-facade.js`)
```javascript
import { Linking } from 'react-native'

class DeepLinkingFacade {
  resolvePromise: any;

  listenForDeepLinking () {
    Linking.removeEventListener('url', this._handleOpenURL)
    Linking.addEventListener('url', this._handleOpenURL)
    return new Promise(function (resolve, reject) {
      this.resolvePromise = resolve
    })
  }

  _handleOpenURL (event: any) {
    this.resolvePromise(event.url)
  }
}

module.exports = DeepLinkingFacade
```

### Test
```javascript
jest.dontMock('./deep-linking-facade.js')

const DeepLinkingFacade = require('./deep-linking-facade.ios.js')

describe('Deep linking facade', () => {
  let facade

  beforeEach(() => {
    facade = new DeepLinkingFacade()
  })

  it('should start listening', () => {
    expect(facade.listenForDeepLinking()).toBeDefined();
  })
})
```

### Error
```
  - ReferenceError: _reactNative is not defined
        at DeepLinkingFacade.listenForDeepLinking (core/service/deep-linking-facade.js:7:1)
        at Object.eval (__tests__/core/service/deep-linking-facade.ios-test.js:13:15)
        at Object.<anonymous> (node_modules/jest-jasmine2/src/jasmine-pit.js:35:32)
        at jasmine2 (node_modules/jest-jasmine2/src/index.js:253:7)
        at Test.run (node_modules/jest-cli/src/Test.js:44:12)
        at handle (node_modules/worker-farm/lib/child/index.js:41:8)
        at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
        at emitTwo (events.js:106:13)
        at process.emit (events.js:191:7)
        at handleMessage (internal/child_process.js:718:10)
        at Pipe.channel.onread (internal/child_process.js:444:11)
```

I'm working on Mac OS, with the following project configuration:
```
"dependencies": {
    "react": "15.0.2",
    "react-native": "^0.26.1",
  },
  "devDependencies": {
    "babel-eslint": "^6.0.4",
    "babel-jest": "^12.1.0",
    "babel-polyfill": "^6.8.0",
    "babel-preset-react-native": "^1.7.0",
    "eslint": "^2.9.0",
    "eslint-config-standard": "^5.3.1",
    "eslint-plugin-flowtype": "^2.2.7",
    "eslint-plugin-promise": "^1.1.0",
    "eslint-plugin-react": "^5.0.1",
    "eslint-plugin-standard": "^1.3.2",
    "jest-cli": "^12.1.1",
    "rnpm-plugin-upgrade": "^0.26.0"
  },
  "jest": {
    "scriptPreprocessor": "node_modules/react-native/jestSupport/preprocessor.js",
    "setupEnvScriptFile": "react-env.js",
    "testPathIgnorePatterns": [
      "/node_modules/",
      "packager/react-packager/src/Activity/"
    ],
    "testFileExtensions": [
      "js"
    ],
    "unmockedModulePathPatterns": [
      "promise",
      "source-map"
    ]
  }
```

**Comment by bestander** [comment]
@facebook-github-bot stack-overflow

**Comment by bestander** [comment]
Have a look here: http://stackoverflow.com/questions/29730415/how-to-use-jest-with-react-native and https://github.com/facebook/jest/issues/700.
Probably could be fixed with some babel/jest configs

**Comment by facebook-github-bot-6** [comment]
Hey @danybony and thanks for posting this! @bestander tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
