### ISSUE TITLE
 Unknown plugin "transform-flow-strip-types" specified in "base" at 0, attempted to resolve relative to "/Users/zgx/Desktop/react-native/local-cli"

### ISSUE THREAD

**Issue by zgxzgxzg** [facebook/react-native#7845]
11111:react-native zgx$ npm start

> react-native@1000.0.0 start /Users/zgx/Desktop/react-native
> /usr/bin/env bash -c './packager/packager.sh "$@" || true' --

/Users/zgx/Desktop/react-native/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:204
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "transform-flow-strip-types" specified in "base" at 0, attempted to resolve relative to "/Users/zgx/Desktop/react-native/local-cli"
    at /Users/zgx/Desktop/react-native/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:204:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/zgx/Desktop/react-native/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:20)
    at OptionManager.mergeOptions (/Users/zgx/Desktop/react-native/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:300:36)
    at OptionManager.init (/Users/zgx/Desktop/react-native/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:488:10)
    at compile (/Users/zgx/Desktop/react-native/node_modules/babel-register/lib/node.js:112:69)
    at loader (/Users/zgx/Desktop/react-native/node_modules/babel-register/lib/node.js:158:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/zgx/Desktop/react-native/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

**Comment by zgxzgxzg** [comment]
help

**Comment by zgxzgxzg** [comment]
i just run npm start, but err....

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-0** [comment]
Hey @zgxzgxzg and thanks for posting this! @damusnet tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by zgxzgxzg** [comment]
OK. I SEE, thinks...
