### ISSUE TITLE
react-native init app spews a bunch of errors spawned from node-gyp

### ISSUE THREAD

**Issue by rmilesson** [facebook/react-native#8011]
I have no idea if these errors will affect me while using React Native since the initialization seems to have actually finished which is confusing after seeing all those errors.

Using:
Node v6.2.1
npm v3.9.3

Full output below.

```
Setting up new React Native app in /Users/generic-user/Development/test-app/app

> fsevents@1.0.12 install /Users/generic-user/Development/test-app/app/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn EACCES
gyp ERR! stack     at exports._errnoException (util.js:1007:11)
gyp ERR! stack     at ChildProcess.spawn (internal/child_process.js:302:11)
gyp ERR! stack     at exports.spawn (child_process.js:383:9)
gyp ERR! stack     at exports.execFile (child_process.js:139:15)
gyp ERR! stack     at checkPythonVersion (/Users/generic-user/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:371:5)
gyp ERR! stack     at /Users/generic-user/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:338:9
gyp ERR! stack     at /Users/generic-user/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/which/which.js:88:20
gyp ERR! stack     at /Users/generic-user/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /Users/generic-user/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/Users/generic-user/.nvm/versions/node/v6.2.1/bin/node" "/Users/generic-user/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/generic-user/Development/test-app/app/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/generic-user/Development/test-app/app/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64"
gyp ERR! cwd /Users/generic-user/Development/test-app/app/node_modules/fsevents
gyp ERR! node -v v6.2.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/generic-user/.nvm/versions/node/v6.2.1/bin/node /Users/generic-user/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/generic-user/Development/test-app/app/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node --module_name=fse --module_path=/Users/generic-user/Development/test-app/app/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64' (7)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/generic-user/Development/test-app/app/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Darwin 15.5.0
node-pre-gyp ERR! command "/Users/generic-user/.nvm/versions/node/v6.2.1/bin/node" "/Users/generic-user/Development/test-app/app/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/generic-user/Development/test-app/app/node_modules/fsevents
node-pre-gyp ERR! node -v v6.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.25
node-pre-gyp ERR! not ok
Failed to execute '/Users/generic-user/.nvm/versions/node/v6.2.1/bin/node /Users/generic-user/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/generic-user/Development/test-app/app/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node --module_name=fse --module_path=/Users/generic-user/Development/test-app/app/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64' (7)
npm WARN install:fsevents@1.0.12 fsevents@1.0.12 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:fsevents@1.0.12 Exit status 1

> bufferutil@1.2.1 install /Users/generic-user/Development/test-app/app/node_modules/bufferutil
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn EACCES
gyp ERR! stack     at exports._errnoException (util.js:1007:11)
gyp ERR! stack     at ChildProcess.spawn (internal/child_process.js:302:11)
gyp ERR! stack     at exports.spawn (child_process.js:383:9)
gyp ERR! stack     at exports.execFile (child_process.js:139:15)
gyp ERR! stack     at checkPythonVersion (/Users/generic-user/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:371:5)
gyp ERR! stack     at /Users/generic-user/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:338:9
gyp ERR! stack     at /Users/generic-user/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/which/which.js:88:20
gyp ERR! stack     at /Users/generic-user/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /Users/generic-user/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/Users/generic-user/.nvm/versions/node/v6.2.1/bin/node" "/Users/generic-user/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/generic-user/Development/test-app/app/node_modules/bufferutil
gyp ERR! node -v v6.2.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 7

> utf-8-validate@1.2.1 install /Users/generic-user/Development/test-app/app/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn EACCES
gyp ERR! stack     at exports._errnoException (util.js:1007:11)
gyp ERR! stack     at ChildProcess.spawn (internal/child_process.js:302:11)
gyp ERR! stack     at exports.spawn (child_process.js:383:9)
gyp ERR! stack     at exports.execFile (child_process.js:139:15)
gyp ERR! stack     at checkPythonVersion (/Users/generic-user/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:371:5)
gyp ERR! stack     at /Users/generic-user/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:338:9
gyp ERR! stack     at /Users/generic-user/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/which/which.js:88:20
gyp ERR! stack     at /Users/generic-user/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /Users/generic-user/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/Users/generic-user/.nvm/versions/node/v6.2.1/bin/node" "/Users/generic-user/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/generic-user/Development/test-app/app/node_modules/utf-8-validate
gyp ERR! node -v v6.2.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.2.1 Exit status 7
app@0.0.1 /Users/generic-user/Development/test-app/app
└── react@15.1.0

To run your app on iOS:
   cd /Users/generic-user/Development/test-app/app
   react-native run-ios
   - or -
   Open /Users/generic-user/Development/test-app/app/ios/app.xcodeproj in Xcode
   Hit the Run button
To run your app on Android:
   Have an Android emulator running (quickest way to get started), or a device connected
   cd /Users/generic-user/Development/test-app/app
   react-native run-android
generic-user@generic-users-MacBook-Pro ~/Development/test-app  $
```

**Comment by charpeni** [comment]
It seems an installation issue with node and not related to react-native itself.

I just tested it with node v6.2.1 and npm v3.9.3 and everything was fine.

Could be related ? https://facebook.github.io/react-native/docs/getting-started.html#react-native-command-line-tools

**Comment by charpeni** [comment]
@facebook-github-bot label Tooling

**Comment by rmilesson** [comment]
I've tried running the commands with `sudo`. I'm using `nvm` to manage my node installations, might that be an issue perhaps?

**Comment by rmilesson** [comment]
Also, even though all these errors pops up while running `init`, I'm still able to run the project in a simulator and do work on the project with no issues I can see.
What steps is it that's breaking? Will it cause any issues? I'd rather not continue working and then having stuff completely break down the line.
The breaking steps are not marked optional in any way so I'm guessing there's something crucial breaking, but I've no idea what.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/react-native-init-app-spews-a-bunch-of-errors-spawned-from-node-gyp

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
