### ISSUE TITLE
java.lang.AssertionErrorAssertions.java:21

### ISSUE THREAD

**Issue by jeremyeaton89** [facebook/react-native#8038]
Hello,

We recently upgraded to React Native 0.26.0 and since our production release have been seeing a large ramp up in the following crashes (This is from Bugsnag):

```
java.lang.AssertionError
        at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:21)
        at com.facebook.react.uimanager.events.EventDispatcher$DispatchEventsRunnable.run(EventDispatcher.java:305)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
        at android.os.Looper.loop(Looper.java:148)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:187)
        at java.lang.Thread.run(Thread.java:818)
```

I dove in and saw that in `EventDispatcher.java`, `mRCTEventEmitter` is `null` and there's nothing catching the exception. My urge is to check if it's null and do something like this...
```
    if (mRCTEventEmitter == null) {
      mRCTEventEmitter = mReactContext.getJSModule(RCTEventEmitter.class);
    }
```
but that can't be right - i don't know why it's null in the first place. 

We're not having these problems in iOS. 

Thanks in advanced, and i hope i've provided enough info - please ask if i haven't

**Comment by charpeni** [comment]
@facebook-github-bot label Android

**Comment by ianlin** [comment]
Had the same problem after upgraded to 0.26.2 recently.

**Comment by jeremyeaton89** [comment]
@ianlin have u done anything about this?

**Comment by BeckZero** [comment]
+1 same problem.... 

`Fatal Exception: java.lang.AssertionError
       at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:21)
       at com.facebook.react.uimanager.events.EventDispatcher$DispatchEventsRunnable.run(EventDispatcher.java:305)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:145)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:187)
       at java.lang.Thread.run(Thread.java:818)`

**Comment by ianlin** [comment]
@jeremyeaton89 sorry for not noticing this. Was using exactly the same workaround as yours on 0.26 but after upgraded to 0.28 this error did not show up.

**Comment by jetango** [comment]
Had the same problem.

java.lang.AssertionError
	at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:21)
	at com.facebook.react.uimanager.events.EventDispatcher$DispatchEventsRunnable.run(EventDispatcher.java:305)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:193)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:187)
	at java.lang.Thread.run(Thread.java:848)

**Comment by undef1ned** [comment]
Got the same issue reported to Bugsnag. Im on RN 0.26.3. Unfortunately can't update to the latest RN version because of #7995

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/javalangassertionerrorassertionsjava21

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by MicroKibaco** [comment]
i have a same problem such 

 `com.facebook.react.uimanager.events.TouchEventCoalescingKeyHelper.getCoalescingKey(TouchEventCoalescingKeyHelper.java:75)
2 com.facebook.react.uimanager.events.TouchEvent.init(TouchEvent.java:89)
3 com.facebook.react.uimanager.events.TouchEvent.obtain(TouchEvent.java:45)
4 com.facebook.react.uimanager.JSTouchDispatcher.handleTouchEvent(JSTouchDispatcher.java:114)
5 com.facebook.react.ReactRootView.dispatchJSTouchEvent(ReactRootView.java:155)
6 com.facebook.react.ReactRootView.onInterceptTouchEvent(ReactRootView.java:127)
7 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2212)
8 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
9 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
10 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
11 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
12 android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
13 android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
14 com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
15 com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
16 android.app.Activity.dispatchTouchEvent(Activity.java:3213)
17 com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
18 android.view.View.dispatchPointerEvent(View.java:10228)
19 android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4845)
20 android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4705)
21 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4238)
22 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4291)
23 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4257)
24 android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4384)
25 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4265)
26 android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4441)
27 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4238)
28 android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4291)
29 android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4257)
30 android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4265)
31 android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4238)
32 android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6665)
33 android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6639)
34 android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6600)
35 android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6792)
36 android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
37 android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
38 android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:181)
39 android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6739)
40 android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6820)
41 android.view.Choreographer$CallbackRecord.run(Choreographer.java:923)
42 android.view.Choreographer.doCallbacks(Choreographer.java:735)
43 android.view.Choreographer.doFrame(Choreographer.java:661)
44 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:909)
45 android.os.Handler.handleCallback(Handler.java:755)
46 android.os.Handler.dispatchMessage(Handler.java:95)
47 android.os.Looper.loop(Looper.java:156)
48 android.app.ActivityThread.main(ActivityThread.java:6524)
49 java.lang.reflect.Method.invoke(Native Method)
50 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
51 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)`

**Comment by wv1124** [comment]
`05-22 06:45:24.073 1747-7758/com.qianmi.adminapp E/ReactNativeJS: undefined is not an object (evaluating 'u[n]')
05-22 06:45:24.209 1747-7758/com.qianmi.adminapp E/ReactNativeJS: undefined is not an object (evaluating 'u[n]')
05-22 06:45:25.585 1747-1747/com.qianmi.adminapp D/AndroidRuntime: Shutting down VM
05-22 06:45:25.585 1747-1747/com.qianmi.adminapp W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa629a288)
05-22 06:45:25.589 1747-1747/com.qianmi.adminapp E/CustomCrashHandler: java.lang.AssertionError
                                                                           at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:21)
                                                                           at com.facebook.react.devsupport.DevSupportManagerImpl.handleReloadJS(DevSupportManagerImpl.java:647)
                                                                           at com.facebook.react.devsupport.RedBoxDialog$3.onClick(RedBoxDialog.java:283)
                                                                           at android.view.View.performClick(View.java:4084)
                                                                           at android.view.View$PerformClick.run(View.java:16966)
                                                                           at android.os.Handler.handleCallback(Handler.java:615)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                           at android.os.Looper.loop(Looper.java:137)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:511)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                       
                                                                       
                                                                       [ 05-22 06:45:25.641  1747: 7783 D/         ]
                                                                       HostConnection::get() New Host Connection established 0xb8eb12b8, tid 7783`
