### ISSUE TITLE
E/ReactNativeJNI: Got JS Exception: SyntaxError: Attempted to redefine property 'style'.

### ISSUE THREAD

**Issue by tigerohuang** [facebook/react-native#8132]
I can run in iOS,but got error in android, and I check several times for duplicate property 'style'.but can't find it.

06-15 23:47:23.160 16453-17192/com.weshop E/ReactNativeJNI: Got JS Exception: SyntaxError: Attempted to redefine property 'style'.
06-15 23:47:23.170 16453-16453/com.weshop E/unknown:React: Exception in native call from JS
                                                           java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: SyntaxError: Attempted to redefine property 'style'. (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:117084)
                                                               at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:860)
                                                               at com.facebook.react.ReactInstanceManagerImpl.access$700(ReactInstanceManagerImpl.java:98)
                                                               at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:194)
                                                               at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:177)
                                                               at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                               at java.lang.Thread.run(Thread.java:831)
                                                            Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: SyntaxError: Attempted to redefine property 'style'. (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:117084)
                                                               at com.facebook.react.common.futures.SimpleSettableFuture.get(SimpleSettableFuture.java:68)
                                                               at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:831)
                                                               at com.facebook.react.ReactInstanceManagerImpl.access$700(ReactInstanceManagerImpl.java:98) 
                                                               at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:194) 
                                                               at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:177) 
                                                               at android.os.AsyncTask$2.call(AsyncTask.java:288) 
                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                               at java.lang.Thread.run(Thread.java:831) 
                                                            Caused by: java.lang.RuntimeException: SyntaxError: Attempted to redefine property 'style'. (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:117084)
                                                               at com.facebook.react.bridge.ReactBridge.loadScriptFromFile(Native Method)
                                                               at com.facebook.react.bridge.JSBundleLoader$2.loadScript(JSBundleLoader.java:58)
                                                               at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:148)
                                                               at com.facebook.react.ReactInstanceManagerImpl$4.call(ReactInstanceManagerImpl.java:851)
                                                               at com.facebook.react.ReactInstanceManagerImpl$4.call(ReactInstanceManagerImpl.java:832)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:73)
                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                               at android.os.Looper.loop(Looper.java:135)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:197)
                                                               at java.lang.Thread.run(Thread.java:831) 
06-15 23:47:23.180 16453-16453/com.weshop W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=3 r=0x7f0d008e}
06-15 23:47:23.190 16453-16453/com.weshop W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=3 r=0x7f0d008f}

**Comment by igor-ribeiro** [comment]
Are you using ES6? If so, check if you defined 'style' as a const and then defined it again.

**Comment by pranavrajs** [comment]
@tigerohuang I had same issue due to style prop defined twice. Better way to identify the issue is using a linter. 

If you cannot identify the issue with linter , you can go to the url specified in the error, in your case it is `http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false` . You will get a JS file, See the line number `117084`. It will have some hint to the root cause.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
