### ISSUE TITLE
android.app.Application cannot be cast to com.facebook.react.ReactApplication

### ISSUE THREAD

**Issue by leeight** [facebook/react-native#8215]
After install the UIExplorer Example via `adb install /xxx/.../app-debug.apk`, but failed to lauch it.

 `adb logcat`, give me the following error logs.

```
E/AndroidRuntime(32698): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.facebook.react.uiapp/com.facebook.react.uiapp.UIExplorerActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
E/AndroidRuntime(32698): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2341)
E/AndroidRuntime(32698): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403)
E/AndroidRuntime(32698): 	at android.app.ActivityThread.access$800(ActivityThread.java:154)
E/AndroidRuntime(32698): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
E/AndroidRuntime(32698): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(32698): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(32698): 	at android.app.ActivityThread.main(ActivityThread.java:5298)
E/AndroidRuntime(32698): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32698): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(32698): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
E/AndroidRuntime(32698): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)
E/AndroidRuntime(32698): Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
E/AndroidRuntime(32698): 	at com.facebook.react.ReactActivity.getReactNativeHost(ReactActivity.java:79)
E/AndroidRuntime(32698): 	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:107)
E/AndroidRuntime(32698): 	at com.facebook.react.uiapp.UIExplorerActivity.onCreate(UIExplorerActivity.java:44)
E/AndroidRuntime(32698): 	at android.app.Activity.performCreate(Activity.java:6049)
E/AndroidRuntime(32698): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime(32698): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2294)
E/AndroidRuntime(32698): 	... 10 more
```

**Comment by pauliusuza** [comment]
Hi, I'm facing the same issue in my app after upgrading to 0.29. The code was upgraded as per migration instructions for 0.29.
 
What was your solution?

**Comment by natdm** [comment]
@greena13  Which AndroidManifest? I see a few of them? And do you mean 

```
<application
      android:name=".MainApplication">
```

?

Anywhere in the file within the <manifest></manifest> tags?

**Comment by natdm** [comment]
Ah, got it - thanks @greena13 . src/main/AndroidManifest.xml, within the actual <application> tag.

**Comment by dsimmons** [comment]
Just ran into this myself while upgrading `0.28.0` -> `0.29.2`.

Running `react-native upgrade` made all of the appropriate changes automatically ***EXCEPT*** the change mentioned above.

For posterity:

```XML
<!-- $PWD/android/app/src/main/AndroidManifest.xml -->

    <application
      android:name=".MainApplication"
```

**Comment by natdm** [comment]
Mine has that.

`<application
      android:allowBackup="true"
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">`

**Comment by sheburdos** [comment]
Had the same issue after switching 0.28.0 -> 0.31.0-rc.1.

Manual adding **_android:name=".MainApplication"_** to the AndroidManifest.xml helped

**Comment by ColCh** [comment]
Same issue, 0.28 -> 0.30

it seems that `react-native upgrade` don't updates `AndroidManifest.xml`

here is diff , 0.28 and 0.30 of AndroidManifest.xml.
(`diff 0-28.xml 0-30.xml`)

It seems that `android:name` is not only difference.
```diff
2c2,4
---
>     android:versionCode="1"
>     android:versionName="1.0">
4a7,11
>     <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
> 
>     <uses-sdk
>         android:minSdkVersion="16"
>         android:targetSdkVersion="22" />
6a14
>       android:name=".MainApplication"
9c17
<       android:icon="@drawable/ic_launcher"
---
>       android:icon="@mipmap/ic_launcher"
```

So, you need to manually update your `AndroidManifest.xml`
