### ISSUE TITLE
Packager fails on 'platform', RN 0.28.0

### ISSUE THREAD

**Issue by avishayil** [facebook/react-native#8297]
I think it's somehow related to the new ActivityIndicator. Happens on iOS simulator, haven't tested on a real device yet.
````javascript
[8:45:07 AM] <END>   find dependencies (929ms)
[8:45:07 AM] <END>   request:/index.ios.bundle?platform=ios&dev=true (1093ms)
[8:45:07 AM] <START> request:/index.ios.bundle?platform=ios&dev=true
[8:45:07 AM] <END>   request:/index.ios.bundle?platform=ios&dev=true (26ms)
[8:45:07 AM] <START> request:/index.ios.map?platform=ios&dev=true
[8:45:08 AM] <END>   request:/index.ios.map?platform=ios&dev=true (203ms)
[8:45:12 AM] <START> symbolicate
[8:45:12 AM] <START> find dependencies
Error: Error validating module options: child "platform" fails because ["platform" must be a string]
    at /Users/avishay/geektime-app/node_modules/react-native/packager/react-packager/src/lib/declareOpts.js:60:13
    at /Users/avishay/geektime-app/node_modules/react-native/packager/react-packager/src/Server/index.js:229:20
    at tryCallOne (/Users/avishay/geektime-app/node_modules/promise/lib/core.js:37:12)
    at /Users/avishay/geektime-app/node_modules/promise/lib/core.js:123:15
    at flush (/Users/avishay/geektime-app/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[8:45:12 AM] <END>   symbolicate (11ms)
transformed 843/843 (100%)
[8:45:13 AM] <END>   find dependencies (859ms)
[8:45:13 AM] <START> symbolicate
Error: Error validating module options: child "platform" fails because ["platform" must be a string]
    at /Users/avishay/geektime-app/node_modules/react-native/packager/react-packager/src/lib/declareOpts.js:60:13
    at /Users/avishay/geektime-app/node_modules/react-native/packager/react-packager/src/Server/index.js:229:20
    at tryCallOne (/Users/avishay/geektime-app/node_modules/promise/lib/core.js:37:12)
    at /Users/avishay/geektime-app/node_modules/promise/lib/core.js:123:15
    at flush (/Users/avishay/geektime-app/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[8:45:13 AM] <END>   symbolicate (2ms)
[8:45:13 AM] <START> symbolicate
Error: Error validating module options: child "platform" fails because ["platform" must be a string]
    at /Users/avishay/geektime-app/node_modules/react-native/packager/react-packager/src/lib/declareOpts.js:60:13
    at /Users/avishay/geektime-app/node_modules/react-native/packager/react-packager/src/Server/index.js:229:20
    at tryCallOne (/Users/avishay/geektime-app/node_modules/promise/lib/core.js:37:12)
    at /Users/avishay/geektime-app/node_modules/promise/lib/core.js:123:15
    at flush (/Users/avishay/geektime-app/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[8:45:13 AM] <END>   symbolicate (139ms)
[8:45:13 AM] <START> symbolicate
Error: Error validating module options: child "platform" fails because ["platform" must be a string]
    at /Users/avishay/geektime-app/node_modules/react-native/packager/react-packager/src/lib/declareOpts.js:60:13
    at /Users/avishay/geektime-app/node_modules/react-native/packager/react-packager/src/Server/index.js:229:20
    at tryCallOne (/Users/avishay/geektime-app/node_modules/promise/lib/core.js:37:12)
    at /Users/avishay/geektime-app/node_modules/promise/lib/core.js:123:15
    at flush (/Users/avishay/geektime-app/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[8:45:14 AM] <END>   symbolicate (142ms)
[8:45:14 AM] <START> symbolicate
Error: Error validating module options: child "platform" fails because ["platform" must be a string]
    at /Users/avishay/geektime-app/node_modules/react-native/packager/react-packager/src/lib/declareOpts.js:60:13
    at /Users/avishay/geektime-app/node_modules/react-native/packager/react-packager/src/Server/index.js:229:20
    at tryCallOne (/Users/avishay/geektime-app/node_modules/promise/lib/core.js:37:12)
    at /Users/avishay/geektime-app/node_modules/promise/lib/core.js:123:15
    at flush (/Users/avishay/geektime-app/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[8:45:14 AM] <END>   symbolicate (109ms)
[8:45:14 AM] <START> symbolicate
Error: Error validating module options: child "platform" fails because ["platform" must be a string]
    at /Users/avishay/geektime-app/node_modules/react-native/packager/react-packager/src/lib/declareOpts.js:60:13
    at /Users/avishay/geektime-app/node_modules/react-native/packager/react-packager/src/Server/index.js:229:20
    at tryCallOne (/Users/avishay/geektime-app/node_modules/promise/lib/core.js:37:12)
    at /Users/avishay/geektime-app/node_modules/promise/lib/core.js:123:15
    at flush (/Users/avishay/geektime-app/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[8:45:14 AM] <END>   symbolicate (104ms)
````

**Comment by avishayil** [comment]
FYI runs fine on a real device while testing.

**Comment by hadri3n** [comment]
We actually have the exact same issue running on a "real" device (iPhone 6)

**Comment by avishayil** [comment]
I discovered it's happening when you passing a null value to JSON, especially on Image component that needs to re-render according to state.
````javascript
constructor(props) {
    super(props);
    this.state = {
        imageURI: null // This is null, NOT OK
    };
}
````
and then
````javascript
<Image source={{uri: this.state.imageURI}} />
````
Will lead to the error, while putting commas over the null initial value solves it, or just put some placeholder url or resource, until it's re-rendered.
````javascript
constructor(props) {
    super(props);
    this.state = {
        imageURI: 'null' // This is a string, OK
    };
}
````

**Comment by xseignard** [comment]
Hello,
Same problem here.

Here are the options when `Joi` fails to validate:

```
{ sourceMapUrl: 'http://localhost:8081/debuggerWorker.js',
  entryFile: 'debuggerWorker.js.js',
  dev: true,
  minify: false,
  hot: false,
  runModule: true,
  inlineSourceMap: false,
  platform: null,
  entryModuleOnly: false }
```
And the error message:
```
Error: Error validating module options: child "platform" fails because ["platform" must be a string]
    at /home/bigx/repos/rnTest/node_modules/react-native/packager/react-packager/src/lib/declareOpts.js:61:13
```
And I have no idea from where it does come from, I tried to check for null values, with no luck. And from the given `opts` object it seems it's not related to my code.

Any idea?

**Comment by xseignard** [comment]
Well I did a `react-native upgrade` again, and everything is ok now.

**Comment by npomfret** [comment]
I can confirm @avishayil comment that images with a _null_ uri no longer seem to be allowed

**Comment by rokwoonkim** [comment]
+1
