### ISSUE TITLE
[Android] Crash when js parse error.

### ISSUE THREAD

**Issue by desmond1121** [facebook/react-native#8311]
After update to 0.28,  my rn app would crash in android when debug & js parse error. Crash dialog shows with red box, I have to click "Yes" and re-run my code.

There is crash log:

```
 E/ReactNativeJS: Module AppRegistry is not a registered callable module.
 E/AndroidRuntime: FATAL EXCEPTION: main Process: com.todofluxapp, PID: 6127
           java.lang.NullPointerException: Attempt to invoke interface method 'int com.facebook.react.bridge.ReadableArray.size()' on a null object reference
           at com.facebook.react.devsupport.StackTraceHelper.convertJsStackTrace(StackTraceHelper.java:95)
           at com.facebook.react.devsupport.DevSupportManagerImpl$3.run(DevSupportManagerImpl.java:228)
           at android.os.Handler.handleCallback(Handler.java:739)
           at android.os.Handler.dispatchMessage(Handler.java:95)
           at android.os.Looper.loop(Looper.java:148)
           at android.app.ActivityThread.main(ActivityThread.java:5417)
           at java.lang.reflect.Method.invoke(Native Method)
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by taypo** [comment]
Same error for me as well. Sample app from `react-native init` runs fine.

**Comment by xujinyang** [comment]
+1 this crach block all debug

**Comment by rafaelcorreiapoli** [comment]
Any updates on this? it's really annoying me =(

**Comment by fab1an** [comment]
Yes, please.

**Comment by romshiri** [comment]
Same here.

**Comment by cgrelik** [comment]
I did something hackish to bypass the issue for now:
File: ./node_modules/react-native/ReactAndroid/src/androidTest/assets/AndroidTestBundle.js
Line: 20369

```
function reportException(e,isFatal){
var parseErrorStack=require(173 /* parseErrorStack */);
var symbolicateStackTrace=require(176 /* symbolicateStackTrace */);
var RCTExceptionsManager=require(32 /* NativeModules */).ExceptionsManager;

var currentExceptionID=++exceptionID;
if(RCTExceptionsManager){
var stack=parseErrorStack(e);

// I added this here. Probably not the correct fix but it works for me.
if(!stack){
  stack = [];
}
if(isFatal){
RCTExceptionsManager.reportFatalException(e.message,stack,currentExceptionID);}else
{
RCTExceptionsManager.reportSoftException(e.message,stack,currentExceptionID);}

if(__DEV__){
symbolicateStackTrace(stack).then(
function(prettyStack){return (
RCTExceptionsManager.updateExceptionMessage(e.message,prettyStack,currentExceptionID));},
function(error){return (
console.warn('Unable to symbolicate stack trace: '+error.message));});}}}
```

**Comment by AndrewJack** [comment]
Fixed here https://github.com/facebook/react-native/commit/b5c3550857bd7360e7b5b6e227d795f859202245

It'll be in 31 unless cherry picked into an earlier release.

**Comment by ide** [comment]
Closing because this should be fixed in master ^
