### ISSUE TITLE
Animated API, slow on many transitions or operations.

### ISSUE THREAD

**Issue by nschurmann** [facebook/react-native#8320]
As far as i know from the documentation of react native, the animated API is in charge of sending to the native thread each position of the transition ocurring. So basically the Javascript thread is doing lots of operations during an animation. This of course is not effective if you need to make lots of animations.

To put in context, i'm building a clicker game, everytime you touch a button, it will display an animation of a text or number that will translate on the Y axis till reach the top of the screen, then the component will disappear. 

On one tap it takes some time to render, but after 2 or more taps it becomes unusable. Any alternative to move the operations to another thread or the animations to other thread? I'm using redux with react-native.

**Comment by nschurmann** [comment]
What i managed to discover is that `Object.assign` is a very expensive operation and can greatly reduce the fps on the javascript thread (from 58.5fps to 30fps) when cloning an object.

`Object.assign({}, state, { someAttr: 'new value' }) // this is expensive!!`
`Object.assign(state, { someAttr: 'new value' }) // this is NOT expensive`

So far I tried alternatives like `JSON.parse(JSON.stringify(state))`, and using lodash `_.assign` with no success.

**Comment by charpeni** [comment]
Are you in debug mode ?

**Comment by nschurmann** [comment]
@charpeni yes, how may i disable it for android?, i didn't found that on the documentation.

**Comment by charpeni** [comment]
Sorry I meant Debug JS mode, not the debug/release apk. http://facebook.github.io/react-native/docs/debugging.html#chrome-developer-tools

If you're in Debug JS mode, javascript will be executed in the V8 of chrome instead of JSC.

**Comment by nschurmann** [comment]
@charpeni is Debug JS remotely is not enabled.

**Comment by charpeni** [comment]
Can you show us how you handle that with Redux?

**Comment by nschurmann** [comment]
Sure!

```typescript
import {
  RECEIVE_DAMAGE,
} from '../actions/player'

export interface IPlayerState {
  maxHP: number
  currentHP: number
  dexterity: number
  strength: number
  defense: number
  level: number
}

interface IAction {
  type: string
  damage: number
}

const initialState: IPlayerState = {
  maxHP: 1000,
  currentHP: 1000,
  dexterity: 10,
  strength: 10,
  defense: 10,
  level: 1
}

// Inmutable merge
export const merge = <A, B>(x1: A, x2: B): A & B =>
  Object.assign({}, x1, x2)

export default function player(state: IPlayerState = initialState, action: IAction) {
  switch (action.type) {
    case RECEIVE_DAMAGE:
      return (state.currentHP > 0)
        ? merge(state, <IPlayerState>{currentHP: state.currentHP - action.damage})
        : state
    default:
      return state;
  }
}
```

**Comment by janicduplessis** [comment]
You can try testing with JS Dev Mode disabled to see if you still have perf issues, react does a lot of runtime checks in dev mode that are disabled in release. You can disable it in Dev Menu -> Dev Settings -> JS Dev Mode.

**Comment by nschurmann** [comment]
@janicduplessis great performance improvement!!, still needs some tweaking though, the Object.assign is still giving massive JS drop on the framerate. I think that maybe giving the animations to the main thread or expensive operations to a web worker could to the trick. But the problem is that neither workers (that you can pass objects and functions) or animations in main thread are implemented yet. Any workaround?

**Comment by janicduplessis** [comment]
There is some work to offload animations to a native thread but I haven't tried it yet and is still pretty experimental. It is android only at the moment but a PR for iOS landed recently. You can set `useNativeDriver` to true when you start an animation in the animation config. I think you also need to include [NativeAnimatedModule](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/animated/NativeAnimatedModule.java) in your native modules package as it is not included by default (http://facebook.github.io/react-native/docs/native-modules-android.html#register-the-module).

**Comment by nschurmann** [comment]
@janicduplessis thanks!, i will give it a try now.

**Comment by nschurmann** [comment]
@janicduplessis i'm a little lost here, the documentation says that `The last step within Java is to register the Module; this happens in the createNativeModules of your apps package. If a module is not registered it will not be available from JavaScript.`

And then it shows me some code, but it doesn't tells where to create that file. Is that a plain java class?, where should be typed?

**Comment by nschurmann** [comment]
Ok!, i managed to solve the issue, the documentation doesn't says it but you need to create a new java class. So the final code is this:

`NativeAnimation.java`
```java
package com.polygonsmash;

import com.facebook.react.ReactPackage;
import com.facebook.react.bridge.JavaScriptModule;
import com.facebook.react.bridge.NativeModule;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.uimanager.ViewManager;
import com.facebook.react.animated.NativeAnimatedModule;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Created by nicolas on 6/23/16.
 */
class NativeAnimation implements ReactPackage {

    @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }

    @Override
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
        return Collections.emptyList();
    }

    @Override
    public List<NativeModule> createNativeModules(
            ReactApplicationContext reactContext) {
        List<NativeModule> modules = new ArrayList<>();

        modules.add(new NativeAnimatedModule(reactContext));

        return modules;
    }
}
```

`MainActivity.java`
```java
package com.polygonsmash;

import com.facebook.react.ReactActivity;
import com.facebook.reactnative.androidsdk.FBSDKPackage;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import android.content.Intent;     // <--- import
import android.os.Bundle;

import com.facebook.CallbackManager;
import com.facebook.FacebookSdk;
import com.facebook.reactnative.androidsdk.FBSDKPackage;

import com.polygonsmash.NativeAnimation;

import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {
    CallbackManager mCallbackManager;
    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "polygonsmash";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

    /**
     * A list of packages used by the app. If the app uses additional views
     * or modules besides the default ones, add more packages here.
     */
    @Override
    protected List<ReactPackage> getPackages() {
        mCallbackManager = new CallbackManager.Factory().create();
        ReactPackage packages[] = new ReactPackage[]{
                new MainReactPackage(),
                new NativeAnimation(),
                new FBSDKPackage(mCallbackManager),
        };
        return Arrays.<ReactPackage>asList(packages);
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        mCallbackManager.onActivityResult(requestCode, resultCode, data);
    }
}
```

But still, when i'm adding this to my component:
```javascript
animate() {
    Animated.parallel([
      Animated.spring(this.bounceValue, {
        toValue: 1,
        friction: 3,
        useNativeDriver: true, // <-- doesn't affect performance
      }),
      Animated.timing(this.pan, { 
        duration: 1500,
        easing: Easing.inOut(Easing.linear),
        toValue: -200,
        useNativeDriver: true, // <-- stops the execution of everything without throwing any error
      })
      ,
      Animated.timing(this.fadeAnim, {
        duration: 1500,
        easing: Easing.inOut(Easing.linear),
        toValue: 0,
        useNativeDriver: true, // <-- stops the execution of everything without throwing any error
      })
    ]).start()
  }
```
doesn't work, and actually stops the execution of the code failing silently, any ideas? :)

**Comment by janicduplessis** [comment]
Do you still have dev mode disabled? Maybe try turning it back on to see if you can see an error. You could also look at the native logs with adb logcat see if you can find something.

**Comment by nschurmann** [comment]
@janicduplessis the only error that i get running adb logcat is this:

```
06-23 15:25:37.975  2510  2543 E Surface : getSlotFromBufferLocked: unknown buffer: 0x9f39e580
06-23 15:25:38.018  2510  2543 E Surface : getSlotFromBufferLocked: unknown buffer: 0x9a2dd4d0
06-23 15:25:38.147  1568  2201 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@b519c6c attribute=android.view.inputmethod.EditorInfo@6f0b235, token = android.os.BinderProxy@2f74286
06-23 15:25:38.154  1568  1744 W AppOps  : Finishing op nesting under-run: uid 10055 pkg com.polygonsmash code 24 time=0 duration=0 nesting=0
06-23 15:25:38.163  1568  1597 W AppOps  : Finishing op nesting under-run: uid 10055 pkg com.polygonsmash code 24 time=0 duration=0 nesting=0
06-23 15:25:38.361  2510  2543 E Surface : getSlotFromBufferLocked: unknown buffer: 0x9a2dfed0
06-23 15:25:38.368  2510  2780 I ReactNativeJS: Running application "polygonsmash" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
06-23 15:25:38.465  1568  2201 W AppOps  : Finishing op nesting under-run: uid 10055 pkg com.polygonsmash code 24 time=0 duration=0 nesting=0
06-23 15:25:38.900  2510  2725 W unknown:React: Calling JS function after bridge has been destroyed.
06-23 15:25:39.146  2510  2781 E unknown:React: Could not close WebSocket connection for id 0
06-23 15:25:39.146  2510  2781 E unknown:React: java.net.SocketException: Socket is closed
06-23 15:25:39.146  2510  2781 E unknown:React: 	at com.android.org.conscrypt.OpenSSLSocketImpl.checkOpen(OpenSSLSocketImpl.java:247)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at com.android.org.conscrypt.OpenSSLSocketImpl.-wrap0(OpenSSLSocketImpl.java)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:756)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at okio.Okio$1.write(Okio.java:80)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at okio.RealBufferedSink.emit(RealBufferedSink.java:178)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at okhttp3.internal.ws.WebSocketWriter.writeControlFrameSynchronized(WebSocketWriter.java:152)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at okhttp3.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:111)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:168)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at com.facebook.react.modules.websocket.WebSocketModule.close(WebSocketModule.java:194)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at java.lang.reflect.Method.invoke(Native Method)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:187)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:62)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:432)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at android.os.Handler.handleCallback(Handler.java:739)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at android.os.Looper.loop(Looper.java:148)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:193)
06-23 15:25:39.146  2510  2781 E unknown:React: 	at java.lang.Thread.run(Thread.java:818)
```

Also i'm running it with dev mode enabled. So far not working.

**Comment by nschurmann** [comment]
Got a new error @janicduplessis `This JS animated node type cannot be used as native animated node`.

So it seems that the configuration of the module is wrong. Any help would be appreciated it :)

**Comment by nschurmann** [comment]
@janicduplessis finally found what was going on, as this [PR says](https://github.com/facebook/react-native/pull/6466) it doesn't support transform, but opacity. So right now i'm looking for alternatives to maybe making another thread in JS available.

**Comment by Introvertuous** [comment]
Just out of curiosity, did you get anywhere with this?

**Comment by narychen** [comment]
@janicduplessis I'm just wondering why turning off ios dev won't get the performance better.
I change 
```
jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
```
to
```
jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios"];
```
I tested it on iphone 5 and it won't make the animation faster.
On android it will be better.
