### ISSUE TITLE
OkHttp Unable to extract the trust manager

### ISSUE THREAD

**Issue by ethaMont** [facebook/react-native#8322]
On Android with `react-native@0.28.0` or `react-native@0.29.0.rc.0`, I'm getting the following exception:
```
Exception in native call from JS
                                                                 java.lang.IllegalStateException: Unable to extract the trust manager on okhttp3.internal.Platform$Android@5049aa5, sslSocketFactory is class crittercism.android.q
                                                                     at okhttp3.OkHttpClient.<init>(OkHttpClient.java:187)
                                                                     at okhttp3.OkHttpClient.<init>(OkHttpClient.java:60)
                                                                     at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:718)
                                                                     at com.facebook.react.modules.network.OkHttpClientProvider.createClient(OkHttpClientProvider.java:42)
                                                                     at com.facebook.react.modules.network.OkHttpClientProvider.getOkHttpClient(OkHttpClientProvider.java:29)
                                                                     at com.facebook.react.modules.fresco.FrescoModule.getDefaultConfig(FrescoModule.java:101)
                                                                     at com.facebook.react.modules.fresco.FrescoModule.<init>(FrescoModule.java:45)
                                                                     at com.facebook.react.shell.MainReactPackage.createNativeModules(MainReactPackage.java:71)
                                                                     at com.facebook.react.ReactInstanceManagerImpl.processPackage(ReactInstanceManagerImpl.java:922)
                                                                     at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:838)
                                                                     at com.facebook.react.ReactInstanceManagerImpl.access$700(ReactInstanceManagerImpl.java:100)
                                                                     at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:197)
                                                                     at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:180)
                                                                     at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                     at java.lang.Thread.run(Thread.java:818)
```
It works fine with `react-native@0.26.3`
The application code is the exact same one than here https://facebook.github.io/react-native/docs/embedded-app-android.html

Could it be related to https://github.com/square/okhttp/issues/2323?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/okhttp-unable-to-extract-the-trust-manager

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
