### ISSUE TITLE
Packager fails on 'platform', RN 0.28.0

### ISSUE THREAD

**Issue by magrinj** [facebook/react-native#8409]
Same issue as #8297 

I try everything, clean cache, avoid `null` value for `uri` in `<Image/>` and replace it by `'null'`, and re-running the command `react-native upgrade`, but I still have the same error:

In Packager I got:

```Error: Error validating module options: child "platform" fails because ["platform" must be a string]
    at /Users/magrin_j/BeJoe/bejoe-mobile/node_modules/react-native/packager/react-packager/src/lib/declareOpts.js:60:13
    at /Users/magrin_j/BeJoe/bejoe-mobile/node_modules/react-native/packager/react-packager/src/Server/index.js:229:20
    at tryCallOne (/Users/magrin_j/BeJoe/bejoe-mobile/node_modules/promise/lib/core.js:37:12)
    at /Users/magrin_j/BeJoe/bejoe-mobile/node_modules/promise/lib/core.js:123:15
    at flush (/Users/magrin_j/BeJoe/bejoe-mobile/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)```

and in the iOS app:

<img width="374" alt="screen shot 2016-06-24 at 4 26 00 pm" src="https://cloud.githubusercontent.com/assets/3551795/16340449/83ae9444-3a28-11e6-9097-0dd3fd78724c.png">

Hope someone got the same error and find a solution.

**Comment by magrinj** [comment]
Ok I just find why, It's due to an external package using Image with an empty source.

**Comment by kfiroo** [comment]
Thanks @magrinj !
Thought I'm going crazy.. that was actually very helpful!

Maybe we can improve the error message slightly? :)

**Comment by magrinj** [comment]
Pleasure @kfiroo!

Yes, I think that's can be really helpful! 
You want to make a PR ?
