### ISSUE TITLE
error while running iOS

### ISSUE THREAD

**Issue by lironess** [facebook/react-native#8498]
I'm using React Native version 0.28 on Macbook Pro. I can run Android build without any problems, but when I'm trying to run iOS I'm getting this message:

```
➜  first-native git:(master) react-native run-ios
/Users/myuser/Workspace/first-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at process.chdir (/Users/myuser/Workspace/first-native/node_modules/graceful-fs/polyfills.js:18:9)
    at _runIOS (/Users/myuser/Workspace/first-native/node_modules/react-native/local-cli/runIOS/runIOS.js:49:11)
    at Promise (/Users/myuser/Workspace/first-native/node_modules/react-native/local-cli/runIOS/runIOS.js:24:5)
    at tryCallTwo (/Users/myuser/Workspace/first-native/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/myuser/Workspace/first-native/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/myuser/Workspace/first-native/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (/Users/myuser/Workspace/first-native/node_modules/react-native/local-cli/runIOS/runIOS.js:23:10)
    at Object.run (/Users/myuser/Workspace/first-native/node_modules/react-native/local-cli/cliEntry.js:88:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7)
```
also - I deleted previously my android/ and ios/ dirs (didn't want them to pass to GitHub), so maybe this is the problem. Also - I cannot recover them or start a new project anymore.

help ?

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-7** [comment]
Hey @lironess and thanks for posting this! @damusnet tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
