### ISSUE TITLE
Didn't find class "com.facebook.jni.NativeRunnable"

### ISSUE THREAD

**Issue by leeight** [facebook/react-native#8532]
Pull the latest master code, build UIExplorer and install to Genymotion. The UIExplorer will crash everytime.

```
07-01 20:55:26.045  1836  1836 F art     : art/runtime/runtime.cc:366] Pending exception java.lang.ClassNotFoundException: Didn't find class "com.facebook.jni.NativeRunnable" on path: DexPathList[[zip file "/data/app/com.facebook.react.uiapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.facebook.react.uiapp-1/lib/x86, /data/app/com.facebook.react.uiapp-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
07-01 20:
```

----

```
07-01 20:55:26.046  1836  1836 F art     : art/runtime/runtime.cc:366]   native: #17 pc 002c26ce  /data/dalvik-cache/x86/system@framework@boot.oat (Java_java_lang_Runtime_nativeLoad__Ljava_lang_String_2Ljava_lang_ClassLoader_2Ljava_lang_String_2+194)
07-01 20:55:26.046  1836  1836 F art     : art/runtime/runtime.cc:366]   native: #18 pc 33242453  ???
07-01 20:55:26.046  1836  1836 F art     : art/runtime/runtime.cc:366]   at java.lang.Runtime.nativeLoad(Native method)
07-01 20:55:26.046  1836  1836 F art     : art/runtime/runtime.cc:366]   at java.lang.Runtime.doLoad(Runtime.java:435)
07-01 20:55:26.046  1836  1836 F art     : art/runtime/runtime.cc:366]   - locked <0x087a8393> (a java.lang.Runtime)
07-01 20:55:26.046  1836  1836 F art     : art/runtime/runtime.cc:366]   at java.lang.Runtime.load(Runtime.java:330)
07-01 20:55:26.046  1836  1836 F art     : art/runtime/runtime.cc:366]   at java.lang.System.load(System.java:1069)
07-01 20:55:26.046  1836  1836 F art     : art/runtime/runtime.cc:366]   at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:63)
07-01 20:55:26.046  1836  1836 F art     : art/runtime/runtime.cc:366]   at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:209)
07-01 20:55:26.046  1836  1836 F art     : art/runtime/runtime.cc:366]   at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:178)
07-01 20:55:26.046  1836  1836 F art     : art/runtime/runtime.cc:366]   - locked <0x06f2ffd0> (a java.lang.Class<com.facebook.soloader.SoLoader>)
07-01 20:55:26.046  1836  1836 F art     : art/runtime/runtime.cc:366]   at com.facebook.jni.Prerequisites.ensure(Prerequisites.java:32)
07-01 20:55:26.046  1836  1836 F art     : art/runtime/runtime.cc:366]   at com.facebook.jni.HybridData.<init>(HybridData.java:32)
07-01 20:55:26.046  1836  1836 F art     : art/runtime/runtime.cc:366]   at com.facebook.react.bridge.WritableNativeMap.initHybrid(Native method)
07-01 20:55:26.046  1836  1836 F art     : art/runtime/runtime.cc:366]   at com.facebook.react.bridge.WritableNativeMap.<init>(WritableNativeMap.java:63)
07-01 20:55:26.046  1836  1836 F art     : art/runtime/runtime.cc:366]   at com.facebook.react.JSCConfig$1.getConfigMap(JSCConfig.java:14)
07-01 20:55:26.046  1836  1836 F art     : art/runtime/runtime.cc:366]   at com.facebook.react.XReactInstanceManagerImpl.onJSBundleLoadedFromServer(XReactInstanceManagerImpl.java:696)
07-01 20:55:26.046  1836  1836 F art     : art/runtime/runtime.cc:366]   at com.facebook.react.XReactInstanceManagerImpl.recreateReactContextInBackgroundInner(XReactInstanceManagerImpl.java:384)
07-01 20:55:26.046  1836  1836 F art     : art/runtime/runtime.cc:366]   at com.facebook.react.XReactInstanceManagerImpl.createReactContextInBackground(XReactInstanceManagerImpl.java:355)
```

----

```
07-01 20:55:26.156   102   102 F DEBUG   : Abort message: 'art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.ClassNotFoundException: Didn't find class "com.facebook.jni.NativeRunnable" on path: DexPathList[[zip file "/data/app/com.facebook.react.uiapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.facebook.react.uiapp-1/lib/x86, /data/app/com.facebook.react.uiapp-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]'
07-01 20:
```

**Comment by leeight** [comment]
Clean all of the `*.so` files and rebuild the UIExplorer app, i got another difference errors.

![image](https://cloud.githubusercontent.com/assets/104052/16543976/5027626e-4125-11e6-96ae-a92eb055206f.png)

**Comment by leeight** [comment]
After switch to old bridge, everything goes well.

**Comment by ide** [comment]
cc @cjhopman -- looks like some JNI files might not have been synced out.

**Comment by leeight** [comment]
Thanks @ide . Is there any documents to tell the difference between old bridge and new bridge?

**Comment by ide** [comment]
I don't think so. For the best understanding, the source code is the documentation.

**Comment by janicduplessis** [comment]
Using the new bridge by default was reverted as the gradle build files were not properly updated, lets close this for now.
