### ISSUE TITLE
RN 0.24 Occasionally unable to bundle

### ISSUE THREAD

**Issue by mrozbarry** [facebook/react-native#8664]
For context, I am part of a team developing an application that is being integrated into both an android and iOS.

When I bundle my android version, it works flawlessly.  If I attempt to bundle my iOS app afterwards, I get the following error:

```
bundle: Created ReactPackager
uncaught error Error: NotFoundError: Cannot find entry file index.ios.js in any of the roots: ["/Users/mrozbarry/work/my-app/dev-app"]
    at DependencyGraph._getAbsolutePath (/Users/mrozbarry/work/my-app/dev-app/node_modules/node-haste/lib/index.js:285:13)
    at /Users/mrozbarry/work/my-app/dev-app/node_modules/node-haste/lib/index.js:222:30
    at run (/Users/mrozbarry/work/my-app/dev-app/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /Users/mrozbarry/work/my-app/dev-app/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/Users/mrozbarry/work/my-app/dev-app/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
See logs /var/folders/7r/c8140bkn2j16xn85k7dnf53w0000gn/T/react-packager.log
    at SocketClient._handleMessage (SocketClient.js:144:23)
    at BunserBuf.<anonymous> (SocketClient.js:53:42)
    at emitOne (events.js:90:13)
    at BunserBuf.emit (events.js:182:7)
    at BunserBuf.process (/Users/mrozbarry/work/my-app/dev-app/node_modules/bser/index.js:289:10)
    at /Users/mrozbarry/work/my-app/dev-app/node_modules/bser/index.js:244:12
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
```

The only way to get it to build again is to run some sort of npm command (I typically have done `npm prune && npm install`).  I've attempted to run my bundle script in different windows to see if it was some sort of local environment that was being modified.  I've also done diffs on my node_modules directory, and nothing seems to be modified.

To build my bundles, I am doing the following commands:

```
react-native bundle \
  --entry-file=index.android.js \
  --platform=android \
  --dev=false \
  --assets-dest=../white-label/android/app/src/main/res \
  --bundle-output=../white-label/android/app/src/main/assets/android.jsbundle

react-native bundle \
  --entry-file=index.ios.js \
  --platform=ios \
  --dev=false \
  --assets-dest=../white-label/ios \
  --bundle-output=../white-label/ios/ios.jsbundle
```

It only started a week or two ago, and I haven't been able to figure out why.

**Comment by grabbou** [comment]
Hey, thanks for reporting. Are you able to check if it still happens with the latest version of React Native?

**Comment by mrozbarry** [comment]
I am done this project now, so I cannot confirm within that project if a version bump would help.  My npm fix ended up not being consistent, but doing `rm -rf $TMPDIR/react-packager-*` which did consistently fix the issue.  I'd like to say it was an issue when I was switching quickly between building an iOS and Android bundle, but sometimes it would be an issue when consistently building for one platform over the course of a day.

I can check with a more recent version later this evening and report back.

**Comment by grabbou** [comment]
@mrozbarry that would be great! I haven't ever experienced similar issue even though I was running quite a few apps simultaneously. It might be that it's been already fixed, though I'd like to confirm that first.

**Comment by mrozbarry** [comment]
@grabbou after upgrading to react-native 0.30, I still get this issue.  I have two scripts that build my android and ios bundles, so this is what it looks like:

```bash
$ ./bundleAndroid.sh && ./bundleIOS.sh                                                                                                                [2.2.2]
[5:34:21 PM] <START> Building Dependency Graph
[5:34:21 PM] <START> Crawling File System
[5:34:22 PM] <START> find dependencies
[5:34:25 PM] <END>   Crawling File System (3579ms)
[5:34:25 PM] <START> Building in-memory fs for JavaScript
[5:34:25 PM] <END>   Building in-memory fs for JavaScript (192ms)
[5:34:25 PM] <START> Building in-memory fs for Assets
[5:34:25 PM] <END>   Building in-memory fs for Assets (144ms)
[5:34:25 PM] <START> Building Haste Map
[5:34:25 PM] <START> Building (deprecated) Asset Map
[5:34:25 PM] <END>   Building (deprecated) Asset Map (87ms)
[5:34:25 PM] <END>   Building Haste Map (162ms)
[5:34:25 PM] <END>   Building Dependency Graph (4092ms)
transformed 520/520 (100%)
[5:34:26 PM] <END>   find dependencies (4063ms)
bundle: start
bundle: finish
bundle: Writing bundle output to: ./production/android/assets/android.jsbundle
bundle: Copying 16 asset files
bundle: Done writing bundle output
bundle: Done copying assets
[5:34:36 PM] <START> Building Dependency Graph
[5:34:36 PM] <START> Crawling File System
[5:34:36 PM] <START> find dependencies
[5:34:39 PM] <END>   Crawling File System (3530ms)
[5:34:39 PM] <START> Building in-memory fs for JavaScript
[5:34:40 PM] <END>   Building in-memory fs for JavaScript (229ms)
[5:34:40 PM] <START> Building in-memory fs for Assets
[5:34:40 PM] <END>   Building in-memory fs for Assets (166ms)
[5:34:40 PM] <START> Building Haste Map
[5:34:40 PM] <START> Building (deprecated) Asset Map
[5:34:40 PM] <END>   Building (deprecated) Asset Map (96ms)
[5:34:40 PM] <END>   Building Haste Map (193ms)
[5:34:40 PM] <END>   Building Dependency Graph (4132ms)
transformed 272/278 (98%)
/Users/mrozbarry/demo-app/dev-app/node_modules/promise/lib/done.js:10
      throw err;
      ^
UnableToResolveError: Unable to resolve module react/lib/ReactNative from /Users/mrozbarry/demo-app/node_modules/react-native/Libraries/react-native/react-native.js: Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/react/lib/ReactNative and its parent directories

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
    at /Users/mrozbarry/work/nbcolympics-ptcompanion-react-native/dev-app/node_modules/node-haste/lib/DependencyGraph/ResolutionRequest.js:477:17
```

Here are my dependencies for the project after upgrading:

```json
{
  "dependencies": {
    "@exponent/react-native-navigator": "^0.4.2",
    "firebase": "^2.4.2",
    "lodash": "^4.11.1",
    "moment": "^2.12.0",
    "react": "^0.14.8",
    "react-native": "^0.30.0",
    "react-native-svg": "^1.0.0-rc",
    "react-native-vector-icons": "^1.3.4"
  },
  "devDependencies": {
    "rnpm-plugin-upgrade": "^0.26.0",
    "rnpm": "^1.8.0"
  }
}
```

It's not a huge deal, doing the `rm` command I described above and recommended by the error I get does fix the problem for the next run, I just need to keep doing it each time I bundle for each platform.

**Comment by mrozbarry** [comment]
And here are my bundle scripts:

```bash
$ cat ./bundleAndroid.sh                                                                                                                              
#!/usr/bin/env sh

#rm -rf $TMPDIR/react-packager-*

react-native bundle \
  --entry-file=index.android.js \
  --platform=android \
  --dev=false \
  --assets-dest=./production/android/app/src/main/res \
  --bundle-output=./production/android/app/src/main/assets/android.jsbundle

$ cat ./bundleIOS.sh                                                                                                                                  
#!/usr/bin/env sh

#rm -rf $TMPDIR/react-packager-*

react-native bundle \
  --entry-file=index.ios.js \
  --platform=ios \
  --dev=false \
  --assets-dest=./production/ios \
  --bundle-output=./production/ios/ios.jsbundle
```

If I uncomment the `rm` lines, everything works as expected.

**Comment by lacker** [comment]
It seems like everyone is stumped and this looks like a one-off thing that is not recurring for a bunch of people, so I suggest that we give up and close this issue.
