### ISSUE TITLE
Issue running UIExplorer example

### ISSUE THREAD

**Issue by mhagmajer** [facebook/react-native#8673]
I'm getting the error below when trying to install UIExplorer example:

`./gradlew :Examples:UIExplorer:android:app:installRelease`

```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/facebook/soloader/SoSource;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
```

This happened on a fresh clone from master.

**Comment by corbt** [comment]
I'm running into this same error. @mhagmajer were you able to find a solution?

**Comment by mhagmajer** [comment]
I made a fresh clone and the problem went away.
