### ISSUE TITLE
App crashes on Android with unexpected EOF error

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#8681]
After upgrading to React Native 0.29, our Android app started crashing a lot. Here is the full stack trace,

```java
07-11 02:05:22.864 26413-26502/? E/ReactNativeJNI: Got JS Exception: SyntaxError: Unexpected EOF
07-11 02:05:22.944 26413-26502/? E/AndroidRuntime: FATAL EXCEPTION: mqt_js
   Process: chat.belong.hello, PID: 26413
   java.lang.RuntimeException: SyntaxError: Unexpected EOF (<unknown file>:1)
       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:148)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:193)
       at java.lang.Thread.run(Thread.java:818)
```

Not exactly sure what's the reason. Pretty difficult to create a reproducible example as there's no useful info in the stack trace, and same code was working in previous versions.

Any idea what might be happening? If someone could direct me towards how to pinpoint the issue, that would be great. Meanwhile I'll try to see if I can find out what's causing the issue.

**Comment by satya164** [comment]
Seems to be duplicate of https://github.com/facebook/react-native/issues/4961
