### ISSUE TITLE
Issue while using a versioning control tool

### ISSUE THREAD

**Issue by brion25** [facebook/react-native#8704]
Hi Guys, I was using git to versioning my application, but I friend just told me he was unable to make it run, he sent me this code snippet, I hope you can help us with it

```
In file included from /Users/pablo/Documents/git/Lukit%20iOS/src/lukit/node_modules/react-native/Libraries/ActionSheetIOS/RCTActionSheetManager.m:10:
/Users/pablo/Documents/git/Lukit%20iOS/src/lukit/node_modules/react-native/Libraries/ActionSheetIOS/RCTActionSheetManager.h:10:9: fatal error: 
     could not acquire lock file for module 'UIKit'
#import <UIKit/UIKit.h>
       ^
1 error generated.

** BUILD FAILED **


The following commands produced analyzer issues:
    Analyze RCTLocationObserver.m
(1 command with analyzer issues)

The following build commands failed:
    CompileC /Users/pablo/Documents/git/Lukit%20iOS/src/lukit/ios/build/Build/Intermediates/RCTWebSocket.build/Debug-iphonesimulator/RCTWebSocket.build/Objects-normal/x86_64/RCTWebSocketModule.o RCTWebSocketModule.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC /Users/pablo/Documents/git/Lukit%20iOS/src/lukit/ios/build/Build/Intermediates/RCTText.build/Debug-iphonesimulator/RCTText.build/Objects-normal/x86_64/RCTTextManager.o RCTTextManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC /Users/pablo/Documents/git/Lukit%20iOS/src/lukit/ios/build/Build/Intermediates/RCTGeolocation.build/Debug-iphonesimulator/RCTGeolocation.build/Objects-normal/x86_64/RCTLocationObserver.o RCTLocationObserver.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    CompileC /Users/pablo/Documents/git/Lukit%20iOS/src/lukit/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/Objects-normal/x86_64/RCTActionSheetManager.o RCTActionSheetManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(4 failures)
Installing build/Build/Products/Debug-iphonesimulator/lukit.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/pablo/Documents/git/Lukit%20iOS/src/lukit/node_modules/promise/lib/done.js:10
     throw err;
     ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/lukit.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

   at checkExecSyncError (child_process.js:486:13)
   at Object.execFileSync (child_process.js:506:13)
   at _runIOS (runIOS.js:91:34)
   at runIOS.js:24:5
   at tryCallTwo (/Users/pablo/Documents/git/Lukit%20iOS/src/lukit/node_modules/promise/lib/core.js:45:5)
   at doResolve (/Users/pablo/Documents/git/Lukit%20iOS/src/lukit/node_modules/promise/lib/core.js:200:13)
   at new Promise (/Users/pablo/Documents/git/Lukit%20iOS/src/lukit/node_modules/promise/lib/core.js:66:3)
   at Array.runIOS (runIOS.js:23:10)
   at Object.run (/Users/pablo/Documents/git/Lukit%20iOS/src/lukit/node_modules/react-native/local-cli/cli.js:87:13)
   at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7)
```

**Comment by ide** [comment]
Try logging out and back into your computer for the lock issue, not sure about the plist problem though. StackOverflow is a better place to get help.

@facebook-github-bot stack-overflow

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-0** [comment]
Hey @brion25 and thanks for posting this! @charpeni tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by jasmo2** [comment]
¿Have you solve this problem?
