### ISSUE TITLE
The 'Getting Started' tutorial app doesn't work for me

### ISSUE THREAD

**Issue by jeremypeters** [facebook/react-native#8837]
Just though I'd take a look at React Native, but I've failed at the first hurdle. I'm following the instructions in the getting started tutorial (https://facebook.github.io/react-native/docs/getting-started.html), and when the app launched in the simulator I get the following error:

![screen shot 2016-07-16 at 20 14 33](https://cloud.githubusercontent.com/assets/1882972/16896435/acf2b3e0-4b93-11e6-8d28-957d517cc1ca.png)

This is the contents of the launchPacker.command window:

`~/Projects/AwesomeProject/node_modules/react-native/packager ~
/Users/jezpeters/Projects/AwesomeProject/node_modules/react-native/local-cli/server/formatBanner.js:48
    chalkFunction: (fn) => fn,
                        ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jezpeters/Projects/AwesomeProject/node_modules/react-native/local-cli/server/checkNodeVersion.js:12:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
~
`

OSX 10.11.5
Xcode 7.3.1 
Node 5.2.0

Thanks.

**Comment by jeremypeters** [comment]
OK, the issue was at my end - I installed Node 6.3.0 and set NVM to use this in the terminal, but I guess the project for whatever reason was using a version I have installed that doesn't have  the ES6 support and that caused the errors. To fix it I just had to set the default version to 6.3.0.
