### ISSUE TITLE
WebSocket connection to 'ws://localhost:8081/debugger-proxy?role=debugger&name=Chrome' failed: Invalid frame header

### ISSUE THREAD

**Issue by invig** [facebook/react-native#8925]
Mac, iOS, RN 0.29.2

**Issue**

App crashes in development:  
"Runtime is not ready for debugging. Make sure Packager server is running."

- It is running. Multiple machines exhibit the same problem.

Chrome Debugger: 
"WebSocket connection to 'ws://localhost:8081/debugger-proxy?role=debugger&name=Chrome' failed: Invalid frame header"

Options enabled: 
Remote JS Debugging

Disabling remote JS debugging fixes the problem, but this is pretty inconvenient. 
Enabling Hot Reloading will cause the issue to happen quickly and always.

**May be relevant?** 
Packager:
"NotFoundError: Cannot find entry file function) (http://localhost:8081/index.ios.js in any of the roots: ["/Users/invig/Code/Kerb/Kerb"]
    at DependencyGraph._getAbsolutePath (/Users/invig/Code/Kerb/Kerb/node_modules/node-haste/lib/index.js:288:13)
    at /Users/invig/Code/Kerb/Kerb/node_modules/node-haste/lib/index.js:226:30
    at process._tickCallback (internal/process/next_tick.js:103:7)"

<img width="487" alt="screenshot 2016-07-20 22 29 59" src="https://cloud.githubusercontent.com/assets/138464/16986525/55c44626-4eca-11e6-8e4f-89fd90c32426.png">
<img width="487" alt="screenshot 2016-07-20 22 32 58" src="https://cloud.githubusercontent.com/assets/138464/16986526/55cbec78-4eca-11e6-93b4-7aeac31f5eaf.png">
<img width="948" alt="screenshot 2016-07-20 22 36 28" src="https://cloud.githubusercontent.com/assets/138464/16986544/6c23c464-4eca-11e6-946e-268c65ff9fde.png">

**Comment by invig** [comment]
0.30.0 seems like it's resolved this
