### ISSUE TITLE
Attempted to redefine property 'alignItems'

### ISSUE THREAD

**Issue by Shakarang** [facebook/react-native#8944]
Hello,

Since I updated to React native, I've got a weird issue.

react-native version : 0.30.0
Occurs on : Android (Device and simulator)

It happens only when I am NOT debugging remotely. Once I debug it with chrome everything works fine..

![Imgur](http://i.imgur.com/6a2yYsv.png)

**Comment by santong** [comment]
I have same problem in 0.29.2. I have checked the code but still error.

**Comment by yanbober** [comment]
@Shakarang  & @santong
the same problem! and the release apk start with a exception:

FATAL EXCEPTION: main
                                                   Process: com.xxxxxxx, PID: 22503
                                                   java.lang.RuntimeException: SyntaxError: Attempted to redefine property 'decelerationRate'. (index.android.bundle:452)
                                                       at com.facebook.react.cxxbridge.CatalystInstanceImpl.loadScriptFromAssets(Native Method)
                                                       at com.facebook.react.cxxbridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:37)
                                                       at com.facebook.react.cxxbridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:177)
                                                       at com.facebook.react.XReactInstanceManagerImpl$4.call(XReactInstanceManagerImpl.java:906)
                                                       at com.facebook.react.XReactInstanceManagerImpl$4.call(XReactInstanceManagerImpl.java:899)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:74)
                                                       at android.os.Handler.handleCallback(Handler.java:815)
                                                       at android.os.Handler.dispatchMessage(Handler.java:104)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                       at android.os.Looper.loop(Looper.java:207)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by yanbober** [comment]
@Shakarang & @santong 
i have the same problem, and my reason is  define tow alignItems for the same component, so  be careful!

**Comment by Shakarang** [comment]
Oh, I've totally forgotten this issue.
I've solved my error by using the same way as @yanbober.

**Comment by manjeetwadi** [comment]
@Shakarang @yanbober is there a better way to track this than looking into all files
