### ISSUE TITLE
Error when running the CLI init 

### ISSUE THREAD

**Issue by JasonArkens17** [facebook/react-native#9016]
Hey there and thank you for using React Native!

React Native, as you've probably heard, is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

Do the checklist before filing an issue:

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [ ] Have a usage question? Ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). We use StackOverflow for usage question and GitHub for bugs.
- [ ] Have an idea for a feature? Post the feature request on [Product Pains](https://productpains.com/product/react-native/). It has a voting system to surface the important issues. GitHub issues should only be used for bugs.

None of the above, create a bug report
------------------------------------------------------------------

Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ X ] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [ ] What's the **version** of React Native you're using?
react-native-cli: 1.0.0

- [ ] Does this occur on iOS, Android or both?
Both 
- [ ] Are you using Mac, Linux or Windows?
Mac

**Whenever I try running the react-native init command I get this error:**

This will walk you through creating a new React Native project in /Users/jasondavenport/hello-world-2/Test3
Installing react-native package from npm...
fs.js:603
  var r = binding.read(fd, buffer, offset, length, position);
                  ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:603:19)
    at Object.fs.readFileSync (fs.js:438:24)
    at ConfigChainBuilder.addConfig (/Users/jasondavenport/hello-world-2/Test3/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:151:32)
    at ConfigChainBuilder.findConfigs (/Users/jasondavenport/hello-world-2/Test3/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:107:30)
    at buildConfigChain (/Users/jasondavenport/hello-world-2/Test3/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:66:13)
    at OptionManager.init (/Users/jasondavenport/hello-world-2/Test3/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:346:58)
    at compile (/Users/jasondavenport/hello-world-2/Test3/node_modules/react-native/node_modules/babel-register/lib/node.js:104:45)
    at loader (/Users/jasondavenport/hello-world-2/Test3/node_modules/react-native/node_modules/babel-register/lib/node.js:151:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jasondavenport/hello-world-2/Test3/node_modules/react-native/node_modules/babel-register/lib/node.js:161:7)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/error-when-running-the-cli-init-

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
