### ISSUE TITLE
Attached DialogModule to host with pending alert but no FragmentManager (not attached to an Activity)

### ISSUE THREAD

**Issue by gmagic10** [facebook/react-native#9018]
I start my react activity. I encounter this assert fail
My React-Native version:0.28
react.js:15.2.1

What's the problem?

```
FATAL EXCEPTION: main
                                                                   Process: com.achievo.abc, PID: 4932
                                                                   java.lang.AssertionError: Attached DialogModule to host with pending alert but no FragmentManager (not attached to an Activity).
                                                                       at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:28)
                                                                       at com.facebook.react.modules.dialog.DialogModule.onHostResume(DialogModule.java:201)
                                                                       at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:161)
                                                                       at com.facebook.react.ReactInstanceManagerImpl.moveToResumedLifecycleState(ReactInstanceManagerImpl.java:574)
                                                                       at com.facebook.react.ReactInstanceManagerImpl.moveReactContextToCurrentLifecycleState(ReactInstanceManagerImpl.java:932)
                                                                       at com.facebook.react.ReactInstanceManagerImpl.setupReactContext(ReactInstanceManagerImpl.java:743)
                                                                       at com.facebook.react.ReactInstanceManagerImpl.access$800(ReactInstanceManagerImpl.java:100)
                                                                       at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPostExecute(ReactInstanceManagerImpl.java:207)
                                                                       at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.onPostExecute(ReactInstanceManagerImpl.java:180)
                                                                       at android.os.AsyncTask.finish(AsyncTask.java:632)
                                                                       at android.os.AsyncTask.access$600(AsyncTask.java:177)
                                                                       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:145)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6145)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by xujinyang** [comment]
fix here:
http://xujinyang.github.io/2016/09/13/%E8%A7%A3%E5%86%B3React-Native-Attached-DialogModule-to-host-with-pending-alert-but-no-FragmentManager/

**Comment by vnsraviteja** [comment]
@xujinyang is there a post in english

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
