### ISSUE TITLE
Multiple errors on app start after upgrading to 0.4.0

### ISSUE THREAD

**Issue by mjw56** [facebook/react-native#910]
Getting multiple errors at app start after upgrading an existing app from 0.3.11 to 0.4.0. 

Using 0.3.11 everything is fine.

First, when running cmd + R from Xcode, this error is appearing in the packager window:

```
 ERROR  Watcher took too long to load
Try running `watchman` from your terminal
https://facebook.github.io/watchman/docs/troubleshooting.html
Error: Watcher took too long to load
Try running `watchman` from your terminal
https://facebook.github.io/watchman/docs/troubleshooting.html
    at null._onTimeout (/Users/mikewilcox/code/randUM/node_modules/react-native/packager/react-packager/src/FileWatcher/index.js:74:16)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

so then followed and tried to ```npm start``` from the shell and got this:

```
Error: watch EMFILE
    at errnoException (fs.js:1030:11)
    at FSWatcher.start (fs.js:1062:11)
    at Object.fs.watch (fs.js:1087:11)
    at NodeWatcher.watchdir (/Users/mikewilcox/code/randUM/node_modules/react-native/node_modules/sane/src/node_watcher.js:144:20)
    at Walker.<anonymous> (/Users/mikewilcox/code/randUM/node_modules/react-native/node_modules/sane/src/node_watcher.js:351:12)
    at Walker2015-04-17 19:42 node[25755] (FSEvents.framework) .emit (events.js:98:17)
    at /Users/mikewilcox/code/randUM/node_modules/react-native/node_modules/sane/node_modules/walker/lib/walker.js:69:16
    at Object.oncomplete (fs.js:107:15)
FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
2015-04-17 19:42 node[25755] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
```

**Comment by mjw56** [comment]
Just to update how I solved this:

```bash
brew uninstall watchman
brew link automake
brew install --HEAD watchman
```

Cheers

**Comment by Gregoirevda** [comment]
This fixed it for me :  
rm -rf /usr/local/var/run/watchman/ && brew uninstall watchman && brew install watchman

**Comment by ngoctr** [comment]
Confirmed. Reinstall watchman fixed this issue. I got this issue when upgrading from 0.44 to 0.46.4.

**Comment by limeytrader007** [comment]
Did you salute it?

**Comment by doukasd** [comment]
I did not have `watchman` installed (new pc). So the solution for me was just:

`brew install watchman`

**Comment by cooleagle8837** [comment]
reinstalling watchman is marvelous

**Comment by preethi-pnrao** [comment]
I had installed watchman but facing issue cause it was not linked. Linking also will work. 
`brew link watchman`

**Comment by SebastienParis** [comment]
Probs to reinstalling watchman saved it for me! Thanks for helping Guys!

**Comment by IWantToLearnCoding** [comment]
Life rule - Just install watchman!!!
