### ISSUE TITLE
[android] IncompatibleClassChangeError: Couldn't find ReactProp.name crash on createContextInBackground

### ISSUE THREAD

**Issue by lelandrichardson** [facebook/react-native#9354]
We are using React Native 0.30.0 and are seeing a (relatively infrequent) hard crash when running `createReactContextInBackground()`.

This crash only happens on Android and, from what we can tell, seems to only be affecting Samsung devices.

It also only seems to be happening to devices running Android 5.0.x.

The crash appears to be reflection related. It says that `ReactProp` is missing `name`. I cannot tell which ViewManager it appears to be crashing on, but for a sanity check I have double checked all of our viewmanagers and none of them are missing a `name` prop.

Full stack trace is here:

```
java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:300)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IncompatibleClassChangeError: Couldn't find com.facebook.react.uimanager.annotations.ReactProp.name
        at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
        at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
        at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
        at java.lang.reflect.Method.getAnnotation(Method.java:301)
        at com.facebook.react.uimanager.ViewManagersPropertyCache.extractPropSettersFromViewManagerClassDefinition(ViewManagersPropertyCache.java:400)
        at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForViewManagerClass(ViewManagersPropertyCache.java:301)
        at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForViewManagerClass(ViewManagersPropertyCache.java:298)
        at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForViewManagerClass(ViewManagersPropertyCache.java:298)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.<init>(ViewManagerPropertyUpdater.java:115)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.<init>(ViewManagerPropertyUpdater.java:110)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.findManagerSetter(ViewManagerPropertyUpdater.java:73)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.getNativeProps(ViewManagerPropertyUpdater.java:60)
        at com.facebook.react.uimanager.ViewManager.getNativeProps(ViewManager.java:199)
        at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstants(UIManagerModuleConstantsHelper.java:62)
        at com.facebook.react.uimanager.UIManagerModule.createConstants(UIManagerModule.java:132)
        at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:84)
        at com.facebook.react.CoreModulesPackage.createNativeModules(CoreModulesPackage.java:66)
        at com.facebook.react.ReactInstanceManagerImpl.processPackage(ReactInstanceManagerImpl.java:923)
        at com.facebook.react.ReactInstanceManagerImpl.createReactContext(ReactInstanceManagerImpl.java:829)
        at com.facebook.react.ReactInstanceManagerImpl.access$700(ReactInstanceManagerImpl.java:99)
        at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:196)
        at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(ReactInstanceManagerImpl.java:179)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
```

Has anyone else observed this? We haven't been able to reproduce on a device ourselves.

**Comment by lelandrichardson** [comment]
cc @astreet @mkonicek

**Comment by astreet** [comment]
Seems to be hitting other frameworks with other annotations on Samsung devices :( https://github.com/google/gson/issues/726

**Comment by astreet** [comment]
Here is the Android bug tracker issue: https://code.google.com/p/android/issues/detail?id=172339

**Comment by astreet** [comment]
(it might be helpful if you cross post on that issue)

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-incompatibleclasschangeerror-couldnt-find-reactpropname-crash-on-createcontextinbackground

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (63/60 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:38536)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c670z-000jNP-HP
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 02:28:58 +0000
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c670y-00061q-W1
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 19:28:57 -0700
Date: Sun, 13 Nov 2016 18:28:48 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479090536;
	bh=AymsjhNK82fjVRzWe8zDaqb3NAdJnJOH/J2GCpnir7M=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=j1dxgepbTr1abN/aJ4gfYTZ8tgSN47YivjWvYcOcuhQZ4x1BZLgrB1H7Zjkjad65Q
	 zb7jGp+He9kifFoI+M5qHS+1bLq0D+7sdLw5+aDvvDt6QigTiD0/yQBiGiVg4liB49
	 7yWqMG+/O/zoRhY91JwFSzmLrmnCvynEKo1uNry4=

**Comment by joshyhargreaves** [comment]
Hey @lelandrichardson did you end up finding a fix to this?

We're still seeing a lot of crashes on React native 0.53 with the same Stacktrace all Samsung 5.x devices.
