### ISSUE TITLE
Android app craches on restoring Intents after upgrade to 0.30

### ISSUE THREAD

**Issue by huston007** [facebook/react-native#9370]
Hi guys! I'm trying to upgrade from 0.29, and tried both 0.30 and 0.31, but I faced this crash. 
It appears if I open browser with `Linking.openURL` and then waiting for redirecting back to with custom protocol registered in AndroidManifest by calling ` Linking.addEventListener('url', onOpenWithUrl);`

Manifest section: 

```
 <intent-filter android:label="OAuth Authorization">
            <action android:name="android.intent.action.VIEW"/>
            <category android:name="android.intent.category.DEFAULT"/>
            <category android:name="android.intent.category.BROWSABLE"/>
            <data android:scheme="foobar" android:host="landing.url"/>
        </intent-filter>
```
Also, `android:launchMode="singleTask"` is turned on for my application.

So, when I call `Linking.openURL` and then `Linking.addEventListener('url', onOpenWithUrl)`, app crashes. I got crash log from emulator:

```
08-12 11:00:04.020  2404  2404 E AndroidRuntime: FATAL EXCEPTION: main
08-12 11:00:04.020  2404  2404 E AndroidRuntime: Process: com.xxxxMyApp.app, PID: 2404
08-12 11:00:04.020  2404  2404 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "void com.facebook.react.bridge.ActivityEventListener.onNewIntent(android.content.Intent)"
08-12 11:00:04.020  2404  2404 E AndroidRuntime:        at com.facebook.react.bridge.ReactContext.onNewIntent(ReactContext.java:169)
08-12 11:00:04.020  2404  2404 E AndroidRuntime:        at com.facebook.react.XReactInstanceManagerImpl.onNewIntent(XReactInstanceManagerImpl.java:468)
08-12 11:00:04.020  2404  2404 E AndroidRuntime:        at com.facebook.react.ReactActivity.onNewIntent(ReactActivity.java:183)
08-12 11:00:04.020  2404  2404 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1212)
08-12 11:00:04.020  2404  2404 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1224)
08-12 11:00:04.020  2404  2404 E AndroidRuntime:        at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2545)
08-12 11:00:04.020  2404  2404 E AndroidRuntime:        at android.app.ActivityThread.performNewIntents(ActivityThread.java:2557)
08-12 11:00:04.020  2404  2404 E AndroidRuntime:        at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2566)
08-12 11:00:04.020  2404  2404 E AndroidRuntime:        at android.app.ActivityThread.-wrap12(ActivityThread.java)
08-12 11:00:04.020  2404  2404 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1416)
08-12 11:00:04.020  2404  2404 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
08-12 11:00:04.020  2404  2404 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
08-12 11:00:04.020  2404  2404 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
08-12 11:00:04.020  2404  2404 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-12 11:00:04.020  2404  2404 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-12 11:00:04.020  2404  2404 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

I'm using Mac OS. Surely this doesn't appears on iOS.

**Comment by huston007** [comment]
Also, there is another error either after such crash:
```
08-29 12:37:19.195  1860  1860 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.appwidget.AppWidgetHostView$ParcelableSparseArray instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/0x4. Make sure other views do not use the same id.
08-29 12:37:19.195  1860  1860 E AndroidRuntime:        at android.view.View.onRestoreInstanceState(View.java:14771)
08-29 12:37:19.195  1860  1860 E AndroidRuntime:        at android.widget.TextView.onRestoreInstanceState(TextView.java:4058)
08-29 12:37:19.195  1860  1860 E AndroidRuntime:        at android.view.View.dispatchRestoreInstanceState(View.java:14746)
08-29 12:37:19.195  1860  1860 E AndroidRuntime:        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
08-29 12:37:19.195  1860  1860 E AndroidRuntime:        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
08-29 12:37:19.195  1860  1860 E AndroidRuntime:        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
08-29 12:37:19.195  1860  1860 E AndroidRuntime:        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
08-29 12:37:19.195  1860  1860 E AndroidRuntime:        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
08-29 12:37:19.195  1860  1860 E AndroidRuntime:        at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
08-29 12:37:19.195  1860  1860 E AndroidRuntime:        at android.view.View.restoreHierarchyState(View.java:14724)
08-29 12:37:19.195  1860  1860 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2035)
08-29 12:37:19.195  1860  1860 E AndroidRuntime:        at android.app.Activity.onRestoreInstanceState(Activity.java:1004)
08-29 12:37:19.195  1860  1860 E AndroidRuntime:        at com.android.launcher3.Launcher.onRestoreInstanceState(Launcher.java:1950)
08-29 12:37:19.195  1860  1860 E AndroidRuntime:        at android.app.Activity.performRestoreInstanceState(Activity.java:959)
08-29 12:37:19.195  1860  1860 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1163)
08-29 12:37:19.195  1860  1860 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2389)
08-29 12:37:19.195  1860  1860 E AndroidRuntime:        ... 10 more
```

**Comment by huston007** [comment]
I tried to produce a example project and didn't manage to: simple project works as expected. Then I started to break my project down to simplest version and found that `"react-native-image-picker": "0.20.1"` package removing fixes the issue.

**Comment by huston007** [comment]
Seems to be react-native-image-picker issue https://github.com/marcshilling/react-native-image-picker/issues/275
