### ISSUE TITLE
SyntaxError: /Users/NCPLInc/package.json: Error while parsing JSON - Unexpected token

### ISSUE THREAD

**Issue by sairamgubba** [facebook/react-native#9425]
Rambabus-Mac-mini:beoStore 2 NCPLInc$ npm start

> eCommerce@1.0.1 start /Users/NCPLInc/Downloads/beoStore 2
> node_modules/react-native/packager/packager.sh

/Users/NCPLInc/Downloads/beoStore 2/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:159
      throw err;
      ^

SyntaxError: /Users/NCPLInc/package.json: Error while parsing JSON - Unexpected token “
    at Object.parse (native)
    at ConfigChainBuilder.addConfig (/Users/NCPLInc/Downloads/beoStore 2/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:155:65)
    at ConfigChainBuilder.findConfigs (/Users/NCPLInc/Downloads/beoStore 2/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:107:30)
    at buildConfigChain (/Users/NCPLInc/Downloads/beoStore 2/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:66:13)
    at OptionManager.init (/Users/NCPLInc/Downloads/beoStore 2/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:58)
    at compile (/Users/NCPLInc/Downloads/beoStore 2/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/NCPLInc/Downloads/beoStore 2/node_modules/babel-register/lib/node.js:148:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/NCPLInc/Downloads/beoStore 2/node_modules/babel-register/lib/node.js:158:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! eCommerce@1.0.1 start: `node_modules/react-native/packager/packager.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eCommerce@1.0.1 start script 'node_modules/react-native/packager/packager.sh'.
npm ERR! This is most likely a problem with the eCommerce package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/react-native/packager/packager.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs eCommerce
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls eCommerce
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/NCPLInc/Downloads/beoStore 2/npm-debug.log

**Comment by gmuraleekrishna** [comment]
@sairamgubba Can you try updating the npm to 3.0 or higher?

**Comment by ryankask** [comment]
It looks like you're not using a quotation mark (") but rather "left double quotation mark" and/or "right double quotation mark".

Please make sure you find and replace all `“` and `”` characters in your package.json and replace them with `"`

**Comment by ide** [comment]
@ryankask's suggestion is probably right. Try `require('/Users/NCPLInc/package.json')`. If that fails, there's a syntax error in your package.json file.
