### ISSUE TITLE
[Android] App crash on release version. RN 0.27

### ISSUE THREAD

**Issue by karkb** [facebook/react-native#9428]
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
                                                   Process: com.mypackage, PID: 23260
                                                   com.facebook.react.modules.core.JavascriptException: undefined is not an object (evaluating 'a.requestPermissions'), stack:
                                                   value@392:1766
                                                   notification@817:163
                                                   <unknown>@13:377
                                                   o@2:517
                                                   e@2:326
                                                   i@2:188
                                                   <unknown>@12:32
                                                   o@2:517
                                                   e@2:256
                                                   i@2:188
                                                   global code@819:9
                                                   
                                                       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:90)
                                                       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:78)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
                                                       at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:187)
                                                       at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:62)
                                                       at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:420)
                                                       at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:197)
                                                       at java.lang.Thread.run(Thread.java:818)

    I/WtEventController: Receive am_crash event for pid: 23260
    W/ActivityManager:   Force finishing activity com.mypackage/.MainActivity

**Comment by rmevans9** [comment]
Looks like you are making a call to requestPermissions off an object (I am guessing that has a minified name unless you named the object 'a') that is undefined. In your code find where you call requestPermissions on anything and ensure that the object actually has a value.

**Comment by rmevans9** [comment]
@facebook-github-bot android

**Comment by rmevans9** [comment]
@facebook-github-bot label android

**Comment by karkb** [comment]
I got it work. I actually forgot some coding part about PushNotificationIOS which is not a cross platform, so the response was coming undefined on android platform.
