### ISSUE TITLE
[Android] App occasionally crash on startup

### ISSUE THREAD

**Issue by naivehhr** [facebook/react-native#9483]
#### Release version of the APP is installed to the SamsungGalaxy Note II.When I repeated attempts to open APP, occasionally crash.

Thanks

---

Error Message:

```
E/AndroidRuntime(31955): FATAL EXCEPTION: main
E/AndroidRuntime(31955): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.naive.Ju244/com.naive.MainActivity}: java.lang.RuntimeException: Tried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should be protected by ReactContext#hasActiveCatalystInstance().
E/AndroidRuntime(31955):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2100)
E/AndroidRuntime(31955):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125)
E/AndroidRuntime(31955):    at android.app.ActivityThread.access$600(ActivityThread.java:140)
E/AndroidRuntime(31955):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1227)
E/AndroidRuntime(31955):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31955):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(31955):    at android.app.ActivityThread.main(ActivityThread.java:4898)
E/AndroidRuntime(31955):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(31955):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(31955):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008)
E/AndroidRuntime(31955):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)
E/AndroidRuntime(31955):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(31955): Caused by: java.lang.RuntimeException: Tried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should be protected by ReactContext#hasActiveCatalystInstance().
E/AndroidRuntime(31955):    at com.facebook.react.bridge.ReactContext.getJSModule(ReactContext.java:99)
E/AndroidRuntime(31955):    at com.jucaiapp.modules.AppStateModule.tellAppState(AppStateModule.java:72)
E/AndroidRuntime(31955):    at com.jucaiapp.modules.AppStateModule.onActivityStarted(AppStateModule.java:58)
E/AndroidRuntime(31955):    at android.app.Application.dispatchActivityStarted(Application.java:173)
E/AndroidRuntime(31955):    at android.app.Activity.onStart(Activity.java:1076)
E/AndroidRuntime(31955):    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1178)
E/AndroidRuntime(31955):    at android.app.Activity.performStart(Activity.java:5216)
E/AndroidRuntime(31955):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2073)
E/AndroidRuntime(31955):    ... 11 more
E/android.os.Debug(2276): !@Dumpstate > dumpstate -k -t -z -d -o /data/log/dumpstate_app_error
E/Launcher(2778): Error finding setting, default accessibility to not found: accessibility_enabled
E/Watchdog(2276): !@Sync 1838
E/MtpService(31941): In MTPAPP onReceive:android.intent.action.BATTERY_CHANGED
```
- "react-native": "^0.29.0"
- "android:4.1.2"

**Comment by lavystord** [comment]
Add ``android:name=".MainApplication" ``in the ``<application /> ``section of ``AndroidManifest.xml``. It should now look like,

```xml
<application
+   android:name=".MainApplication"
    android:allowBackup="true"
    android:label="@string/app_name"
    android:icon="@mipmap/ic_launcher"
    android:theme="@style/AppTheme">
```

**Comment by eladcandroid** [comment]
@lavystord Thanks! It worked. But you know why we need to set it manually?

**Comment by lavystord** [comment]
@eladcandroid  Because facebook changed the RN android application template,you can see more detail on [React Native release notes](https://github.com/facebook/react-native/releases?after=v0.29.2)

**Comment by eladcandroid** [comment]
Even I executed 'react-native upgrade'?

**Comment by lavystord** [comment]
@eladcandroid yeah,this is break change on 0.29. So when upgrade to 0.29 + from below 0.29,you need to add this to the xml file

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-app-occasionally-crash-on-startup

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
