### ISSUE TITLE
React-Native bundle --dev false

### ISSUE THREAD

**Issue by Amurmurmur** [facebook/react-native#9495]
My app crashes on boot when building with this command:
`react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle`

tho when the --dev false it boots just fine, it is a same scenario for both platforms ios/android.

For iOS I change build type to Release in the myapp scheme, and it throws the same Expected listener to be a function. exception in the log.

Tho when I build with debug it works just fine, but obvsly the shake menu and the bar at the top "Loading from" are present. 

I want to build Release builds for both platforms

Here is the stacktrace from the logcat:

> 08-20 23:03:36.626 22493-22545/com.myapp I/ReactNativeJS: Running application "myapp" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
> 08-20 23:03:36.674 22493-22545/com.myapp E/ReactNativeJS: Expected listener to be a function.
> 08-20 23:03:36.698 22493-22546/com.myapp E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
>                                                             Process: com.myapp, PID: 22493
>                                                             com.facebook.react.modules.core.JavascriptException: Expected listener to be a function., stack:
>                                                             u@429:218
>                                                             addReduxStore@463:2491
>                                                             t@449:110
>                                                             value@371:1946
>                                                             _renderValidatedComponentWithoutOwnerOrContext@135:6662
>                                                             _renderValidatedComponent@135:6790
>                                                             performInitialMount@135:2675
>                                                             mountComponent@135:1718
>                                                             mountComponent@125:213
>                                                             mountChildren@130:1180
>                                                             initializeChildren@110:448
>                                                             mountComponent@110:1486
>                                                             mountComponent@125:213
>                                                             mountChildren@130:1180
>                                                             initializeChildren@110:448
>                                                             mountComponent@110:1486
>                                                             mountComponent@125:213
>                                                             performInitialMount@135:2824
>                                                             mountComponent@135:1718
>                                                             mountComponent@125:213
>                                                             performInitialMount@135:2824
>                                                             mountComponent@135:1718
>                                                             mountComponent@125:213
>                                                             r@226:80
>                                                             perform@129:528
>                                                             a@226:261
>                                                             perform@129:528
>                                                             batchedUpdates@208:481
>                                                             a@122:346
>                                                             renderComponent@226:1019
>                                                             c@166:153
>                                                             r@325:120
>                                                             run@321:379
>                                                             runApplication@321:969
>                                                             value@34:3686
>                                                             <unknown>@34:1990
>                                                             y@34:622
>                                                             value@34:1962
>                                                             
>                                                                 at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:94)
>                                                                 at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:78)
>                                                                 at java.lang.reflect.Method.invoke(Native Method)
>                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
>                                                                 at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
>                                                                 at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:139)
>                                                                 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
>                                                                 at android.os.Handler.handleCallback(Handler.java:739)
>                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
>                                                                 at android.os.Looper.loop(Looper.java:135)
>                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
>                                                                 at java.lang.Thread.run(Thread.java:818)
> 08-20 23:03:37.234 22493-22545/com.myapp W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
> 08-20 23:03:37.235 22493-22545/com.myapp W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {170a14a1} sending message to a Handler on a dead thread
>                                                           java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {170a14a1} sending message to a Handler on a dead thread
>                                                               at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
>                                                               at android.os.Handler.enqueueMessage(Handler.java:631)
>                                                               at android.os.Handler.sendMessageAtTime(Handler.java:600)
>                                                               at android.os.Handler.sendMessageDelayed(Handler.java:570)
>                                                               at android.os.Handler.post(Handler.java:326)
>                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
>                                                               at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
>                                                               at android.os.Handler.handleCallback(Handler.java:739)
>                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                               at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
>                                                               at android.os.Looper.loop(Looper.java:135)
>                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
>                                                               at java.lang.Thread.run(Thread.java:818)

On iOS its the following:
![simulator screen shot 20 aug 2016 23 59 00](https://cloud.githubusercontent.com/assets/8608333/17834327/aa22f930-6732-11e6-90e5-36eb6d330445.png)

Could anybody give any advise?
Thanks a lot in advance!

React-native v0.31

**Comment by Amurmurmur** [comment]
Fixed the issue, reactotron just used _DEV_ var, I just completely got rid of reactotron, and it built just fine.
