### ISSUE TITLE
[iOS] RNPM/ react-native unlink : Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by mlumbroso** [facebook/react-native#9504]
Hello,

I created an issue just before RNPM was merged in react native, there is a library I can't unlink, and it prevents me from using it, since it was updated in the meanwhile. The library is https://github.com/BranchMetrics/react-native-branch-deep-linking

Other libraries I'm able to remove them.

Are there ways to manually unlink a library? What files should I modify ?

Here  is the full stack trace I see using rnpm unlink (react-native unlink is less verbose) :

```
`/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/removeFromProjectReferences.js:14
  const projectRef = firstProject.projectReferences.find(item => item.ProjectRef === file.uuid);
                                                   ^

TypeError: Cannot read property 'find' of undefined
    at removeFromProjectReferences (/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/removeFromProjectReferences.js:14:52)
    at removeProjectFromProject (/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/removeProjectFromProject.js:17:22)
    at unregisterNativeModule (/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/unregisterNativeModule.js:28:16)
    at unlinkDependencyIOS (/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/unlink.js:52:3)
    at Object.unlink [as func] (/usr/local/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/unlink.js:94:3)
    at Command.runAction (/usr/local/lib/node_modules/rnpm/bin/cli:23:15)
    at Command.listener (/usr/local/lib/node_modules/rnpm/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/rnpm/node_modules/commander/index.js:615:12)
`
```

cc @Kureev @grabbou 

Thanks 👍

**Comment by satya164** [comment]
cc @Kureev @grabbou

**Comment by grabbou** [comment]
You can follow react-native guide on unlinking, also if you could FWD me your `pbxproj` (inside `xcodeproj`) that'd be great. You can find my email listed on my profile.

**Comment by mlumbroso** [comment]
I've sent it :-) 
Btw, couldn't find the react native guide on unlinking, do you have the link?

Thanks for your help :+1:

**Comment by grabbou** [comment]
Ah, actually - my bad, there's none. All you need to do I believe is to do the linking steps in reverse order.

**Comment by haikyuu** [comment]
`react-native unlink module` works just fine 👍

**Comment by wandonye** [comment]
I got 

> Command `unlink` unrecognized

**Comment by Kureev** [comment]
It looks like a different issue, @wandonye. Could you be so kind to open a new issue describing your problem? (with RN version you're using, OS, and library name you're trying to unlink).

Subj: seems that issue is either solved or no longer actual. I'm about to close it.

**Comment by wandonye** [comment]
@Kureev I was using RN 0.29. Maybe it is not new enough to contain unlink?

**Comment by Kureev** [comment]
@wandonye I believe we added unlink at ~0.30. I think @grabbou should know (wasn't able to find it in the release notes 😞) the exact release.
