### ISSUE TITLE
React Native + DexGuard

### ISSUE THREAD

**Issue by astuetz** [facebook/react-native#9522]
We've just switched one of our projects (which includes a React Native part) from ProGuard to DexGuard and now we get the following crash on app start:

```
Caused by: java.lang.UnsatisfiedLinkError: could find DSO to load: libreactnativejni.so
            at com.facebook.soloader.SoLoader.loadLibraryBySoName(:213)
            at com.facebook.soloader.SoLoader.loadLibrary(:178)
            at com.facebook.react.bridge.NativeMap.<clinit>(:22)
            at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(:194)
            at com.facebook.react.ReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(:180)
            at android.os.AsyncTask$2.call(AsyncTask.java:295)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
            at java.lang.Thread.run(Thread.java:818)
```

Looks like DexGuard is *really* aggressive, looking into the resulting apk didn't help, it somehow obfuscated nearly everything in there.

Has anyone ever tried mixing these 2 things up or have an idea on what's going on there? Not sure if this can be fixed on the React Native side or if we should contact the DexGuard devs.
Any help would really be appreciated!

**Comment by astuetz** [comment]
Reached out to the DexGuard developers, including these rules fixed the problem for us:

```
-keepresourcefiles lib/*/libreact*.so
-keepresourcefiles lib/*/libmemchunk*.so
```
