### ISSUE TITLE
Crash in LayoutEngine.java

### ISSUE THREAD

**Issue by anuragdadheech** [facebook/react-native#9550]
Getting a crash in LayoutEngine.java, RN version: `0.30.0`
Unable to deduce the source of crash from logs.
Device: Nexus 6P, Marshmallow 6.0

```
FATAL EXCEPTION: mqt_native_modules
Process: com.myntra.android, PID: 6843
java.lang.AssertionError: availableHeight is indefinite so heightMeasureMode must be CSSMeasureMode.UNDEFINED
    at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:65)
    at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:549)
    at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:419)
    at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1015)
    at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:419)
    at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1165)
    at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:419)
    at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1165)
    at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:419)
    at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1165)
    at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:419)
    at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1165)
    at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:419)
    at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1381)
    at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:419)
    at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1165)
    at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:419)
    at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1165)
    at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:419)
    at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1165)
    at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:419)
    at com.facebook.csslayout.LayoutEngine.layoutNodeImpl(LayoutEngine.java:1165)
    at com.facebook.csslayout.LayoutEngine.layoutNodeInternal(LayoutEngine.java:419)
    at com.facebook.csslayout.LayoutEngine.layoutNode(LayoutEngine.java:251)
    at com.facebook.csslayout.CSSNode.calculateLayout(CSSNode.java:153)
    at com.facebook.react.uimanager.UIImplementation.calculateRootLayout(UIImplementation.java:732)
    at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(UIImplementation.java:506)
    at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:495)
    at com.facebook.react.uimanager.UIManagerModule.onBatchComplete(UIManagerModule.java:480)
    at com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete(NativeModuleRegistry.java:137)
    at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.onBatchComplete(CatalystInstanceImpl.java:453)
    at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:148)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/crash-in-layoutenginejava

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by SudoPlz** [comment]
I get the same issue in 0.50.0

**Comment by SudoPlz** [comment]
@anuragdadheech Did you find a solution to this?

**Comment by SudoPlz** [comment]
Ok I downgraded to RN 0.49.5 and I no longer see this.
