### ISSUE TITLE
[android][0.31.0] fetch let's encrypt ssl throw FATAL EXCEPTION: OkHttp Dispatcher

### ISSUE THREAD

**Issue by someok** [facebook/react-native#9630]
fetch('https://www.example.com/rest') will throw exception, the rest url is use let's encrypt.

the nginx config:

```
ssl_certificate /etc/letsencrypt/live/XXX/fullchain.pem;
       	ssl_certificate_key /etc/letsencrypt/live/XXX/privkey.pem;
       	ssl_trusted_certificate /etc/letsencrypt/live/XXX/chain.pem;
```

the exception:
```
08-29 12:33:50.075 5379-5508/? E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                 Process: com.xuanhuangnet.app.anytech, PID: 5379
                                                 java.lang.IllegalStateException: closed
                                                     at okio.RealBufferedSink.write(RealBufferedSink.java:39)
                                                     at okio.ForwardingSink.write(ForwardingSink.java:35)
                                                     at com.facebook.react.modules.network.ProgressRequestBody$1.write(ProgressRequestBody.java:58)
                                                     at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
                                                     at com.facebook.react.modules.network.ProgressRequestBody.writeTo(ProgressRequestBody.java:48)
                                                     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:47)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                                                     at okhttp3.RealCall.access$100(RealCall.java:33)
                                                     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
                                                     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                     at java.lang.Thread.run(Thread.java:818)

```

**Comment by MajeedThaikas** [comment]
typical exception, nothing new

**Comment by someok** [comment]
I found the reason, the okhttp has some bug with nginx http2, I remove nginx http2 config , it's ok

**Comment by armadilio3** [comment]
Please re-open this issue I still get this error on RN0.35. The server also uses lets encrypt and some requests throw the Fatal Exception. But the ngnix server we use doesn't have any http2 configuration.

**Comment by ilyago** [comment]
+1

**Comment by chetankotkar** [comment]
I am stuck with same kind of error. 
I am using 

 compile 'com.facebook.stetho:stetho:1.5.0'
    compile 'com.facebook.stetho:stetho-okhttp3:1.5.0'
    compile 'com.facebook.stetho:stetho-js-rhino:1.5.0'

fetch request will result in 
```

E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                           Process: com.elitabi, PID: 32242
                                                           java.lang.IllegalStateException: closed
                                                               at okio.RealBufferedSink.write(RealBufferedSink.java:39)
                                                               at okio.ForwardingSink.write(ForwardingSink.java:35)
                                                               at com.facebook.react.modules.network.ProgressRequestBody$1.write(ProgressRequestBody.java:58)
                                                               at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
                                                               at com.facebook.react.modules.network.ProgressRequestBody.writeTo(ProgressRequestBody.java:48)
                                                               at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:47)
                                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                               at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                               at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
                                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                               at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                               at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
                                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                               at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                               at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                                                               at okhttp3.RealCall.access$100(RealCall.java:33)
                                                               at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
                                                               at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                               at java.lang.Thread.run(Thread.java:818)
```
