### ISSUE TITLE
[android] app reloads consistently

### ISSUE THREAD

**Issue by ggordan** [facebook/react-native#9633]
Hi all, 

I am currently working on an application built for iOS and Android. The iOS version is running absolutely fine without any issues, however the android version seems to have an issue whereby it periodically reloads. This happens on a bundled version (not connected to the dev server), and the version serving js from the dev server. It's also worth noting that this happens while the application is idle (i.e. it's just sitting on my desk and I am not touching it).

Running on a device (but it also happens on an emulator)
Android version is: 4.4.2
React Native version: 0.31
Using: Mac

This is what I got from logcat whenever a reload happens:

```
08-29 11:34:34.655 15612-15612/com.ggtestapp I/SensorManager: unregisterListenerImpl++: listener = com.facebook.react.common.ShakeDetector@43ab2900
08-29 11:34:34.685 15612-24270/com.ggtestapp W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
08-29 11:34:34.685 15612-24270/com.ggtestapp W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {43b5d370} sending message to a Handler on a dead thread
                                                            java.lang.RuntimeException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {43b5d370} sending message to a Handler on a dead thread
                                                                at android.os.MessageQueue.enqueueMessage(MessageQueue.java:320)
                                                                at android.os.Handler.enqueueMessage(Handler.java:626)
                                                                at android.os.Handler.sendMessageAtTime(Handler.java:595)
                                                                at android.os.Handler.sendMessageDelayed(Handler.java:566)
                                                                at android.os.Handler.post(Handler.java:326)
                                                                at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                                                                at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                at android.os.Handler.handleCallback(Handler.java:733)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                at android.os.Looper.loop(Looper.java:157)
                                                                at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                at java.lang.Thread.run(Thread.java:864)
08-29 11:34:34.695 15612-16505/com.ggtestapp W/ContextImpl: Failed to ensure directory: /storage/ext_sd/Android/data/com.ggtestapp/cache
08-29 11:34:34.745 15612-18078/com.ggtestapp W/OkHttp: A connection to http://192.168.1.105:8081/ was leaked. Did you forget to close a response body?
08-29 11:34:34.765 15612-15612/com.ggtestapp I/SensorManager: registerListenerImpl: listener = com.facebook.react.common.ShakeDetector@430a1850, sensor = {Sensor name="Accelerometer Sensor", vendor="HTC Group Ltd.", version=1, type=1, maxRange=19.6133, resolution=0.01, power=0.17, minDelay=10000}, delay = 66667, handler = null
08-29 11:34:34.765 15612-24686/com.ggtestapp D/libc: [NET] getaddrinfo+,hn 13(0x3139322e313638),sn(),family 0,flags 4
08-29 11:34:34.765 15612-24686/com.ggtestapp D/libc: [NET] getaddrinfo-, SUCCESS
08-29 11:34:34.765 15612-24686/com.ggtestapp D/libc: [NET] getaddrinfo+,hn 13(0x3139322e313638),sn(),family 0,flags 4
08-29 11:34:34.765 15612-24686/com.ggtestapp D/libc: [NET] getaddrinfo-, SUCCESS
08-29 11:34:34.765 15612-24687/com.ggtestapp D/libc: [NET] getaddrinfo+,hn 13(0x3139322e313638),sn(),family 0,flags 4
08-29 11:34:34.765 15612-24687/com.ggtestapp D/libc: [NET] getaddrinfo-, SUCCESS
08-29 11:34:34.765 15612-24687/com.ggtestapp D/libc: [NET] getaddrinfo+,hn 13(0x3139322e313638),sn(),family 0,flags 4
08-29 11:34:34.765 15612-24687/com.ggtestapp D/libc: [NET] getaddrinfo-, SUCCESS
08-29 11:34:34.795 15612-24687/com.ggtestapp D/libc: [NET] getaddrinfo+,hn 13(0x3139322e313638),sn(),family 0,flags 4
08-29 11:34:34.795 15612-24687/com.ggtestapp D/libc: [NET] getaddrinfo-, SUCCESS
08-29 11:34:34.805 15612-15612/com.ggtestapp W/unknown:React: Unable to dispatch keyboard events in JS as the react instance has not been attached
08-29 11:34:34.825 15612-24691/com.ggtestapp D/libc: [NET] getaddrinfo+,hn 13(0x3139322e313638),sn(),family 0,flags 4
08-29 11:34:34.825 15612-24691/com.ggtestapp D/libc: [NET] getaddrinfo-, SUCCESS
08-29 11:34:34.825 15612-24691/com.ggtestapp D/libc: [NET] getaddrinfo+,hn 13(0x3139322e313638),sn(),family 0,flags 4
08-29 11:34:34.825 15612-24691/com.ggtestapp D/libc: [NET] getaddrinfo-, SUCCESS
08-29 11:34:34.875 15612-15639/com.ggtestapp W/ContextImpl: Failed to ensure directory: /storage/ext_sd/Android/data/com.ggtestapp/cache
08-29 11:34:34.935 15612-24693/com.ggtestapp W/System.err: java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10221 nor current process has android.permission.BLUETOOTH.
08-29 11:34:34.935 15612-24693/com.ggtestapp W/System.err:     at android.os.Parcel.readException(Parcel.java:1474)
08-29 11:34:34.935 15612-24693/com.ggtestapp W/System.err:     at android.os.Parcel.readException(Parcel.java:1428)
08-29 11:34:34.935 15612-24693/com.ggtestapp W/System.err:     at android.bluetooth.IBluetoothManager$Stub$Proxy.getName(IBluetoothManager.java:371)
08-29 11:34:34.935 15612-24693/com.ggtestapp W/System.err:     at android.bluetooth.BluetoothAdapter.getName(BluetoothAdapter.java:613)
08-29 11:34:34.935 15612-24693/com.ggtestapp W/System.err:     at com.learnium.RNDeviceInfo.RNDeviceModule.getConstants(RNDeviceModule.java:78)
08-29 11:34:34.935 15612-24693/com.ggtestapp W/System.err:     at com.facebook.react.cxxbridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:124)
08-29 11:34:34.935 15612-24693/com.ggtestapp W/System.err:     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
08-29 11:34:34.935 15612-24693/com.ggtestapp W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
08-29 11:34:34.935 15612-24693/com.ggtestapp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
08-29 11:34:34.935 15612-24693/com.ggtestapp W/System.err:     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
08-29 11:34:34.935 15612-24693/com.ggtestapp W/System.err:     at android.os.Looper.loop(Looper.java:157)
08-29 11:34:34.935 15612-24693/com.ggtestapp W/System.err:     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
08-29 11:34:34.935 15612-24693/com.ggtestapp W/System.err:     at java.lang.Thread.run(Thread.java:864)
08-29 11:34:34.945 15612-24693/com.ggtestapp E/ReactNativeJNI: Unable to load script from file
08-29 11:34:48.145 15612-18504/com.ggtestapp W/OkHttp: A connection to http://192.168.1.105:8081/ was leaked. Did you forget to close a response body?
```

Thanks,
Gordan

**Comment by ggordan** [comment]
Followup note here that if I add `android.permission.BLUETOOTH` the issue still occurs. And I'm not sure why the complaint for bluetooth permissions since I do not use it in my app.

**Comment by ggordan** [comment]
OK, this issue appears to be a problem with android version 4.4.2. The other android devices I have tested do not have this problem running different versions of Android (6, and 4.2.2)

**Comment by vsrinivas150283** [comment]
Closing the application from Android Emulator, version 6.0 also has this issue
 Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {8b4a5c2} sending message to a Handler on a dead thread
                                                          java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {8b4a5c2} sending message to a Handler on a dead thread
                                                              at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                              at android.os.Handler.enqueueMessage(Handler.java:631)
                                                              at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                              at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                              at android.os.Handler.post(Handler.java:326)
                                                              at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                                                              at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                              at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                              at android.os.Looper.loop(Looper.java:148)
                                                              at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                              at java.lang.Thread.run(Thread.java:818)

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-app-reloads-consistently

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by HanAsteroid** [comment]
W/OkHttp: A connection to http://localhost:8097/ was leaked. Did you forget to close a response body?
                                                         
                                                         [ 05-09 15:03:34.517  2908: 2908 E/         ]
                                                         process stopped due to unexpected signal 13
                                                         
                                                         
                                                         [ 05-09 15:03:35.128  2908: 2908 E/         ]
                                                         process stopped due to unexpected signal 13
                                                         
                                                         
                                                         [ 05-09 15:03:35.727  2908: 2908 E/         ]
                                                         process stopped due to unexpected signal 13
