### ISSUE TITLE
ViewPagerAndorid RCTEventEmitter.receiveEvent Error bug

### ISSUE THREAD

**Issue by charlesluo2014** [facebook/react-native#9750]
### Issue Description

Error calling function:ViewPagerAndorid RCTEventEmitter.receiveEvent

### Steps to Reproduce / Code Snippets
```

<View>
<ViewPagerAndorid />
</View>
```

# 

### Additional Information

* React Native version: [0.32.0]
* Platform(s) : Android
* Operating System (macOS, Linux, or Windows?):macOS

**Comment by leeight** [comment]
Where is the `ViewPagerAndorid`?

**Comment by charlesluo2014** [comment]
@leeight 
like this issue [viewpagerandroid]( http://stackoverflow.com/questions/39327429/reactnative-viewpagerandroid-rcteventemitter)

and appear in the [react-native-scrollable-tab-view](https://github.com/skv-headless/react-native-scrollable-tab-view) plugin in android platform

**Comment by leeight** [comment]
I can reproduce this issue, and get the following stack-trace 

```

09-06 14:25:13.958 9948-13095/com.facebook.react.uiapp E/unknown:React: Exception in native call
                                                                        java.lang.RuntimeException: Error calling function: RCTEventEmitter:receiveEvent
                                                                            at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                         Caused by: java.lang.RuntimeException: folly::toJson: JSON object value was a NaN or INF
                                                                            at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                            at android.os.Handler.handleCallback(Handler.java:739) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                            at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                            at android.os.Looper.loop(Looper.java:135) 
                                                                            at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                                            at java.lang.Thread.run(Thread.java:818) 
```

**Comment by charlesluo2014** [comment]
@leeyeh hi,I modify the code you are fixed in local,but it can't take effect!I test it use the  react-native-scrollable-tab-view

**Comment by leeight** [comment]
@charlesluo2014 I can't reproduce it with the following sample code on the master branch.

```jsx
<View style={{flex: 1, backgroundColor: 'white'}}>
    <ViewPagerAndroid style={{flex: 1}} initialPage={0}>
        <View style={{alignItems: 'center', padding: 20}}>
            <Text>First page</Text>
        </View>
        <View style={{alignItems: 'center', padding: 20}}>
            <Text>Second page</Text>
        </View>
    </ViewPagerAndroid>
</View>
```

**Comment by charlesluo2014** [comment]
@leeight hi，which version will the bug fixed will be merged and published？

**Comment by leeight** [comment]
I'm not sure, maybe next version `0.34.0`

**Comment by SamMatthewsIsACommonName** [comment]
I'm still seeing this issue. Is there a solution to it?

**Comment by cosmith** [comment]
I'm still seeing this but I have trouble reproducing it consistently.
