### ISSUE TITLE
 Error calling function: RCTEventEmitter:receiveEvent

### ISSUE THREAD

**Issue by charlesluo2014** [facebook/react-native#9772]
[FILL THIS OUT]

```
<View style={styles.container}>
        <ScrollableTabBar page={0}  initialPage={0} locked={true} tabStyle={styles.headerTabStyle} style={styles.headerTabbar}  tabBarTextStyle={styles.headerTextStyle} tabBarUnderlineColor="#D12A39" tabBarActiveTextColor="#D12A39">
           <View tabLabel="one" />
           <View tabLabel="two" />
           <View tabLabel="three" /> 
        </ScrollableTabBar>
      </View>
```
use the [react-native-scrollable-tab-view](https://github.com/skv-headless/react-native-scrollable-tab-view)

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

```
E/unknown:React: Exception in native call from JS
                                                 java.lang.RuntimeException: Error calling function: RCTEventEmitter:receiveEvent
                                                     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                     at android.os.Looper.loop(Looper.java:155)
                                                     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                     at java.lang.Thread.run(Thread.java:818)
                                                  Caused by: java.lang.RuntimeException: folly::toJson: JSON object value was a NaN or INF
                                                     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                     at android.os.Handler.handleCallback(Handler.java:739) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                     at android.os.Looper.loop(Looper.java:155) 
                                                     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                     at java.lang.Thread.run(Thread.java:818) 
09-06 23:21:57.809 9302-11885/? E/unknown:React: Exception in native call from JS
                                                 java.lang.RuntimeException: Error calling function: RCTEventEmitter:receiveEvent
                                                     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                     at android.os.Looper.loop(Looper.java:155)
                                                     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                     at java.lang.Thread.run(Thread.java:818)
                                                  Caused by: java.lang.RuntimeException: folly::toJson: JSON object value was a NaN or INF
                                                     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                     at android.os.Handler.handleCallback(Handler.java:739) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                     at android.os.Looper.loop(Looper.java:155) 
                                                     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) 
                                                     at java.lang.Thread.run(Thread.java:818) 
```

* React Native version: 0.32
* Platform(s) (iOS, Android, or both?): Android
* Operating System (macOS, Linux, or Windows?): macOS

**Comment by leeight** [comment]
Duplicate #9750

**Comment by yanbober** [comment]
@charlesluo2014

I have the same error as you, you have closed this issues, can you tell me how to fix it? TKS!

**Comment by NoicFank** [comment]
I got same problem, please tell how to fix it

**Comment by Liceth** [comment]
Can anyone tell me how to fix this  please! @grabbou

**Comment by TracyZhangLei** [comment]
me too

**Comment by lanjie233** [comment]
me too

**Comment by bdebout** [comment]
+1

**Comment by goibibo-tarun** [comment]
Same problem

**Comment by FMGordillo** [comment]
+1
from nowhere...

**Comment by jlsuarezs** [comment]
+1

**Comment by YuriBely** [comment]
+1
