### ISSUE TITLE
animation fails when running the same animation multiple times (useNativeDriver)

### ISSUE THREAD

**Issue by nschurmann** [facebook/react-native#9887]
I'm animating this component at the moment of creation:

``` typescript
import * as React from 'react'
import { Animated, StyleSheet, Text } from 'react-native'

interface InnerProps {
  damage: number
  pageX: number
  pageY: number
  id: any
}

interface InnerState {
  bounceValue: any
  translateValue: any
  fadeValue: any
  id: any
}

export default class Damage extends React.Component<InnerProps, InnerState> {

  constructor(props: InnerProps) {
    super(props)
    this.state = {
      bounceValue: new Animated.Value(1),
      translateValue: new Animated.Value(0),
      fadeValue: new Animated.Value(1),
      id: props.id,
    }
  }

  public componentDidMount() {
    Animated.parallel([
      Animated.timing(this.state.translateValue, {
        toValue: -200,
        duration: 1000,
        useNativeDriver: true,
      }),
      Animated.spring(this.state.bounceValue, {
        toValue: 5,
        useNativeDriver: true,
      }),
      Animated.timing(this.state.fadeValue, {
        toValue: 0,
        duration: 900,
        useNativeDriver: true,
      }),
    ]).start()
  }

  public shouldComponentUpdate(props: InnerProps, state: InnerState) {
    return props.id !== state.id
  }

  public render() {
    return <Animated.Text
      style={{
        position: 'absolute',
        top: this.props.pageY,
        left: this.props.pageX,
        color: 'yellow',
        opacity: this.state.fadeValue,
        transform: [{translateY: this.state.translateValue},
        {scale: this.state.bounceValue}],
      }}
    >
      {this.props.damage}
    </Animated.Text>
  }
}
```

The problem is that, when i'm making a lot of animation for an amount of time (let's say 10 per second for about 8 seconds) it will throw an error:
<img width="384" alt="screen shot 2016-09-13 at 12 53 40 pm" src="https://cloud.githubusercontent.com/assets/5099344/18481028/20568cf8-79b1-11e6-9619-61a79e406928.png">
 ViewManager for tag `some tag` could not be found

this happens in this file:
https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/NativeViewHierarchyManager.java

I think this is a bug, because when i remove 'useNativeDriver' this stops happening but of course the performance drops dramatically.

**Comment by janicduplessis** [comment]
Does this happens on Android only? When you say that you make a lot animations do you mean that you use multiple components like the one you linked (maybe add that code too).

**Comment by nschurmann** [comment]
This component is used to render an array of damage, let me add that section too :)
The render is very simple though

```typescript
{this.props.damageContainer.damage.map((d: any) => <Damage {...d} />)}
```

**Comment by nschurmann** [comment]
@janicduplessis i added as a workaround a setTimeout with a value of 10, with this the error is no longer happening, is ugly but useful as a workaround.

**Comment by janicduplessis** [comment]
@nschurmann Ok, looks like some race condition with views being created and starting the animation.

**Comment by K-Leon** [comment]
I just hit the same Bug in Productions - seems to happen rarely and I can't reproduce but maybe the stacktrace helps:

`Fatal Exception: com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 15808 could not be found
       at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:103)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:119)
       at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:229)
       at com.facebook.react.animated.PropsAnimatedNode.updateView(PropsAnimatedNode.java:69)
       at com.facebook.react.animated.NativeAnimatedNodesManager.runUpdates(NativeAnimatedNodesManager.java:418)
       at com.facebook.react.animated.NativeAnimatedModule$1.doFrameGuarded(NativeAnimatedModule.java:117)
       at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
       at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:771)
       at android.view.Choreographer.doCallbacks(Choreographer.java:586)
       at android.view.Choreographer.doFrame(Choreographer.java:555)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:759)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)`
